package com.astro.vajra.core.common

enum class StringKeyNakshatra(override val en: String, override val ne: String) : StringKeyInterface {

    // ============================================
    // NAKSHATRA DEITIES
    // ============================================
    DEITY_ASHWINI("Ashwini Kumaras (Divine Physicians)", "अश्विनी कुमार (दिव्य चिकित्सक)"),
    DEITY_BHARANI("Yama (God of Death)", "यम (मृत्युका देवता)"),
    DEITY_KRITTIKA("Agni (Fire God)", "अग्नि (आगोका देवता)"),
    DEITY_ROHINI("Brahma (Creator)", "ब्रह्मा (सृष्टिकर्ता)"),
    DEITY_MRIGASHIRA("Soma (Moon God)", "सोम (चन्द्र देवता)"),
    DEITY_ARDRA("Rudra (Storm God)", "रुद्र (आँधीबेहरीका देवता)"),
    DEITY_PUNARVASU("Aditi (Mother of Gods)", "अदिति (देवताहरूको माता)"),
    DEITY_PUSHYA("Brihaspati (Jupiter)", "बृहस्पति (गुरु)"),
    DEITY_ASHLESHA("Nagas (Serpent Gods)", "नाग (सर्प देवता)"),
    DEITY_MAGHA("Pitris (Ancestors)", "पितृ (पुर्खाहरू)"),
    DEITY_PURVA_PHALGUNI("Bhaga (God of Fortune)", "भग (भाग्यका देवता)"),
    DEITY_UTTARA_PHALGUNI("Aryaman (God of Contracts)", "अर्यमन (सम्झौताका देवता)"),
    DEITY_HASTA("Savitar (Sun God)", "सविता (सूर्य देवता)"),
    DEITY_CHITRA("Vishwakarma (Divine Architect)", "विश्वकर्मा (दिव्य वास्तुकार)"),
    DEITY_SWATI("Vayu (Wind God)", "वायु (हावाका देवता)"),
    DEITY_VISHAKHA("Indra-Agni", "इन्द्र-अग्नि"),
    DEITY_ANURADHA("Mitra (God of Friendship)", "मित्र (मित्रताका देवता)"),
    DEITY_JYESHTHA("Indra (King of Gods)", "इन्द्र (देवताहरूको राजा)"),
    DEITY_MULA("Nirriti (Goddess of Dissolution)", "निरृति (विनाशकी देवी)"),
    DEITY_PURVA_ASHADHA("Apas (Water Goddess)", "आप (जल देवी)"),
    DEITY_UTTARA_ASHADHA("Vishwadevas (Universal Gods)", "विश्वेदेव (ब्रह्माण्डका देवताहरू)"),
    DEITY_SHRAVANA("Vishnu (Preserver)", "विष्णु (संरक्षक)"),
    DEITY_DHANISHTHA("Vasus (Eight Elemental Gods)", "वसु (आठ तत्वका देवताहरू)"),
    DEITY_SHATABHISHA("Varuna (God of Waters)", "वरुण (जलका देवता)"),
    DEITY_PURVA_BHADRAPADA("Aja Ekapada (One-footed Goat)", "अज एकपाद (एक खुट्टे बाख्रा)"),
    DEITY_UTTARA_BHADRAPADA("Ahir Budhnya (Serpent of the Deep)", "अहिर्बुध्न्य (गहिराईको सर्प)"),
    DEITY_REVATI("Pushan (Nourisher/Protector)", "पूषा (पोषक/संरक्षक)"),

    // ============================================
    // NAKSHATRA SYMBOLS
    // ============================================
    SYMBOL_ASHWINI("Horse's Head", "घोडाको टाउको"),
    SYMBOL_BHARANI("Yoni (Female Organ)", "योनी"),
    SYMBOL_KRITTIKA("Razor/Flame", "छुरा/ज्वाला"),
    SYMBOL_ROHINI("Cart/Chariot", "गाडा/रथ"),
    SYMBOL_MRIGASHIRA("Deer's Head", "मृगको टाउको"),
    SYMBOL_ARDRA("Teardrop/Diamond", "आँसुको थोपा/हीरा"),
    SYMBOL_PUNARVASU("Bow/House", "धनुष/घर"),
    SYMBOL_PUSHYA("Cow's Udder/Flower", "गाईको थुन/फूल"),
    SYMBOL_ASHLESHA("Coiled Serpent", "कुण्डली मारेको सर्प"),
    SYMBOL_MAGHA("Royal Throne", "शाही सिंहासन"),
    SYMBOL_PURVA_PHALGUNI("Swinging Hammock", "झुल्ने खाट"),
    SYMBOL_UTTARA_PHALGUNI("Bed/Legs of Cot", "खाट/पलङको खुट्टा"),
    SYMBOL_HASTA("Hand/Palm", "हात/हत्केला"),
    SYMBOL_CHITRA("Bright Pearl/Gem", "चम्किलो मोती/रत्न"),
    SYMBOL_SWATI("Coral/Sword", "मुगा/तरवार"),
    SYMBOL_VISHAKHA("Triumphal Arch", "विजय द्वार"),
    SYMBOL_ANURADHA("Lotus", "कमल"),
    SYMBOL_JYESHTHA("Earring/Talisman", "कुण्डल/ताबीज"),
    SYMBOL_MULA("Tied Roots", "बाँधिएको जरा"),
    SYMBOL_PURVA_ASHADHA("Elephant Tusk/Fan", "हात्तीको दाह्रा/हाते पंखा"),
    SYMBOL_UTTARA_ASHADHA("Elephant Tusk/Bed", "हात्तीको दाह्रा/खाट"),
    SYMBOL_SHRAVANA("Ear/Arrow", "कान/काँड"),
    SYMBOL_DHANISHTHA("Drum/Flute", "डमरु/बाँसुरी"),
    SYMBOL_SHATABHISHA("Empty Circle", "खाली घेरा"),
    SYMBOL_PURVA_BHADRAPADA("Sword/Two Front Legs", "तरवार/अघिल्ला दुई खुट्टा"),
    SYMBOL_UTTARA_BHADRAPADA("Twin/Back Legs", "जुम्ल्याहा/पछिल्ला खुट्टा"),
    SYMBOL_REVATI("Fish/Drum", "माछा/डमरु"),

    // ============================================
    // NAKSHATRA ANIMALS
    // ============================================
    ANIMAL_HORSE("Male Horse", "भाले घोडा"),
    ANIMAL_FEMALE_HORSE("Female Horse", "पोथी घोडा"),
    ANIMAL_ELEPHANT("Male Elephant", "भाले हात्ती"),
    ANIMAL_FEMALE_ELEPHANT("Female Elephant", "पोथी हात्ती"),
    ANIMAL_SHEEP("Male Sheep", "भाले भेडा"),
    ANIMAL_FEMALE_SHEEP("Female Sheep", "पोथी भेडा"),
    ANIMAL_SERPENT("Male Serpent", "भाले सर्प"),
    ANIMAL_FEMALE_SERPENT("Female Serpent", "पोथी सर्प"),
    ANIMAL_DOG("Male Dog", "भाले कुकुर"),
    ANIMAL_FEMALE_DOG("Female Dog", "पोथी कुकुर"),
    ANIMAL_CAT("Male Cat", "भाले बिरालो"),
    ANIMAL_FEMALE_CAT("Female Cat", "पोथी बिरालो"),
    ANIMAL_RAT("Male Rat", "भाले मुसो"),
    ANIMAL_FEMALE_RAT("Female Rat", "पोथी मुसो"),
    ANIMAL_COW("Male Cow", "भाले गाई (साँढे)"),
    ANIMAL_FEMALE_COW("Female Cow", "पोथी गाई"),
    ANIMAL_BUFFALO("Male Buffalo", "भाले भैंसी (राँगो)"),
    ANIMAL_FEMALE_BUFFALO("Female Buffalo", "पोथी भैंसी"),
    ANIMAL_TIGER("Male Tiger", "भाले बाघ"),
    ANIMAL_FEMALE_TIGER("Female Tiger", "पोथी बाघ"),
    ANIMAL_DEER("Male Deer", "भाले मृग"),
    ANIMAL_FEMALE_DEER("Female Deer", "पोथी मृग"),
    ANIMAL_MONKEY("Male Monkey", "भाले बाँदर"),
    ANIMAL_FEMALE_MONKEY("Female Monkey", "पोथी बाँदर"),
    ANIMAL_MONGOOSE("Male Mongoose", "भाले न्याउरी मुसो"),
    ANIMAL_FEMALE_MONGOOSE("Female Mongoose", "पोथी न्याउरी मुसो"),
    ANIMAL_LION("Male Lion", "भाले सिंह"),
    ANIMAL_FEMALE_LION("Female Lion", "पोथी सिंह"),

    // ============================================
    // NAKSHATRA BODY PARTS
    // ============================================
    BODY_PART_HEAD("Head", "टाउको"),
    BODY_PART_FACE_EYES("Face/Eyes", "अनुहार/आँखा"),
    BODY_PART_NECK_SHOULDERS("Neck/Shoulders", "घाँटी/काँध"),
    BODY_PART_HEART_BACK("Heart/Back", "मुटु/ढाड"),
    BODY_PART_HANDS_STOMACH("Hands/Stomach", "हात/पेट"),
    BODY_PART_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
    BODY_PART_THIGHS("Thighs", "तिघ्रा"),
    BODY_PART_KNEES_LEGS("Knees/Legs", "घुँडा/खुट्टा"),
    BODY_PART_FEET_ANKLES("Feet/Ankles", "पाइताला/कुर्कुच्चा"),

    // ============================================
    // NAKSHATRA QUALITIES & TRAITS
    // ============================================
    TRAIT_QUICK_THINKING("Quick-thinking", "छिटो सोच्ने"),
    TRAIT_HEALING_ABILITIES("Healing abilities", "निको पार्ने क्षमता"),
    TRAIT_PIONEERING_SPIRIT("Pioneering spirit", "अग्रगामी भावना"),
    TRAIT_YOUTHFUL_ENERGY("Youthful energy", "युवा ऊर्जा"),
    TRAIT_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
    TRAIT_CREATIVE("Creative", "रचनात्मक"),
    TRAIT_STRONG_WILLPOWER("Strong willpower", "बलियो इच्छाशक्ति"),
    TRAIT_BEARING_RESPONSIBILITY("Bearing responsibility", "जिम्मेवारी वहन गर्ने"),
    TRAIT_FIERY_DETERMINATION("Fiery determination", "अग्नि जस्तै दृढ संकल्प"),
    TRAIT_SHARP_INTELLECT("Sharp intellect", "तीक्ष्ण बुद्धि"),
    TRAIT_PURIFYING_NATURE("Purifying nature", "शुद्धिकरण गर्ने प्रकृति"),
    TRAIT_LEADERSHIP("Leadership", "नेतृत्व"),
    TRAIT_ARTISTIC("Artistic", "कलात्मक"),
    TRAIT_MAGNETIC_PERSONALITY("Magnetic personality", "चुम्बकीय व्यक्तित्व"),
    TRAIT_MATERIAL_ABUNDANCE("Material abundance", "भौतिक प्रचुरता"),
    TRAIT_CURIOUS_MIND("Curious mind", "जिज्ञासु मन"),
    TRAIT_SEARCHING_NATURE("Searching nature", "खोजी गर्ने प्रकृति"),
    TRAIT_GENTLE_DEMEANOR("Gentle demeanor", "कोमल व्यवहार"),
    TRAIT_ADAPTABLE("Adaptable", "अनुकूलनशील"),
    TRAIT_INTENSE_EMOTIONS("Intense emotions", "तीव्र भावनाहरू"),
    TRAIT_DESTRUCTIVE_CREATIVE("Destructive-creative", "विनाशकारी-रचनात्मक"),
    TRAIT_RESEARCH_ORIENTED("Research-oriented", "अनुसन्धानमुखी"),
    TRAIT_RENEWAL("Renewal", "नवीकरण"),
    TRAIT_PROSPERITY("Prosperity", "समृद्धि"),
    TRAIT_SPIRITUAL_WISDOM("Spiritual wisdom", "आध्यात्मिक ज्ञान"),
    TRAIT_RETURN_TO_ROOTS("Return to roots", "जरामा फिर्ता"),
    TRAIT_NOURISHING("Nourishing", "पोषण गर्ने"),
    TRAIT_PROTECTIVE("Protective", "सुरक्षात्मक"),
    TRAIT_SPIRITUAL_GROWTH("Spiritual growth", "आध्यात्मिक वृद्धि"),
    TRAIT_TEACHING_ABILITY("Teaching ability", "शिक्षण क्षमता"),
    TRAIT_MYSTICAL_WISDOM("Mystical wisdom", "रहस्यमय ज्ञान"),
    TRAIT_PSYCHIC_ABILITIES("Psychic abilities", "मानसिक क्षमताहरू"),
    TRAIT_SECRETIVE_NATURE("Secretive nature", "गोप्य प्रकृति"),
    TRAIT_HYPNOTIC_CHARM("Hypnotic charm", "सम्मोहक आकर्षण"),
    TRAIT_ROYAL_BEARING("Royal bearing", "शाही व्यवहार"),
    TRAIT_ANCESTRAL_PRIDE("Ancestral pride", "पैतृक गौरव"),
    TRAIT_TRADITIONALIST("Traditionalist", "परम्परावादी"),
    TRAIT_PLEASURE_SEEKING("Pleasure-seeking", "आनन्द खोज्ने"),
    TRAIT_AFFECTIONATE("Affectionate", "मायालु"),
    TRAIT_ARTISTIC_TALENT("Artistic talent", "कलात्मक प्रतिभा"),
    TRAIT_SERVICE_ORIENTED("Service-oriented", "सेवामुखी"),
    TRAIT_HELPFUL_NATURE("Helpful nature", "सहयोगी प्रकृति"),
    TRAIT_GOOD_ORGANIZER("Good organizer", "राम्रो आयोजक"),
    TRAIT_CONTRACT_KEEPER("Contract-keeper", "सम्झौता पालन गर्ने"),
    TRAIT_SKILLED_HANDS("Skilled hands", "दक्ष हातहरू"),
    TRAIT_CLEVER("Clever", "चलाख"),
    TRAIT_RESOURCEFUL("Resourceful", "स्रोतसाधन सम्पन्न"),
    TRAIT_HEALING_TOUCH("Healing touch", "निको पार्ने स्पर्श"),
    TRAIT_BRILLIANT("Brilliant", "प्रतिभाशाली"),
    TRAIT_CREATIVE_GENIUS("Creative genius", "सिर्जनात्मक प्रतिभा"),
    TRAIT_MAGNETIC("Magnetic", "चुम्बकीय"),
    TRAIT_ARTISTIC_MASTERY("Artistic mastery", "कलात्मक निपुणता"),
    TRAIT_INDEPENDENT("Independent", "स्वतन्त्र"),
    TRAIT_BUSINESS_ACUMEN("Business acumen", "व्यापारिक सुझबुझ"),
    TRAIT_DIPLOMATIC("Diplomatic", "कूटनीतिक"),
    TRAIT_GOAL_ORIENTED("Goal-oriented", "लक्ष्यमुखी"),
    TRAIT_DETERMINED("Determined", "दृढ संकल्पित"),
    TRAIT_AMBITIOUS("Ambitious", "महत्त्वाकांक्षी"),
    TRAIT_SINGLE_MINDED_FOCUS("Single-minded focus", "एकाग्र ध्यान"),
    TRAIT_DEVOTED("Devoted", "समर्पित"),
    TRAIT_FRIENDLY("Friendly", "मिलनसार"),
    TRAIT_ORGANIZATIONAL_ABILITY("Organizational ability", "सांगठनिक क्षमता"),
    TRAIT_TRAVEL_LOVING("Travel-loving", "यात्रा प्रेमी"),
    TRAIT_ELDER_BROTHER_ENERGY("Elder brother energy", "ठूलो दाइको जस्तो ऊर्जा"),
    TRAIT_RESPONSIBILITY("Responsibility", "जिम्मेवारी"),
    TRAIT_INVESTIGATIVE("Investigative", "अनुसन्धानमुलक"),
    TRAIT_ROOT_SEEKING("Root-seeking", "जरा खोज्ने"),
    TRAIT_SPIRITUAL_DEPTH("Spiritual depth", "आध्यात्मिक गहिराई"),
    TRAIT_TRANSFORMATION("Transformation", "रूपान्तरण"),
    TRAIT_INVINCIBLE_SPIRIT("Invincible spirit", "अपराजित भावना"),
    TRAIT_PHILOSOPHICAL("Philosophical", "दार्शनिक"),
    TRAIT_OPTIMISTIC("Optimistic", "आशावादी"),
    TRAIT_PURIFYING("Purifying", "शुद्धिकरण"),
    TRAIT_FINAL_VICTORY("Final victory", "अन्तिम विजय"),
    TRAIT_INTEGRITY("Integrity", "निष्ठा"),
    TRAIT_UNIVERSAL_VALUES("Universal values", "विश्वव्यापी मूल्यहरू"),
    TRAIT_GOOD_LISTENER("Good listener", "राम्रो श्रोता"),
    TRAIT_LEARNING_ABILITY("Learning ability", "सिक्ने क्षमता"),
    TRAIT_CONNECTION_TO_TRUTH("Connection to truth", "सत्यसँगको सम्बन्ध"),
    TRAIT_PRESERVATION("Preservation", "संरक्षण"),
    TRAIT_MUSICAL_TALENT("Musical talent", "सांगीतिक प्रतिभा"),
    TRAIT_WEALTH_GIVING("Wealth-giving", "धन दिने"),
    TRAIT_MARCHING_FORWARD("Marching forward", "अगाडि बढ्ने"),
    TRAIT_GROUP_ACTIVITIES("Group activities", "सामूहिक गतिविधिहरू"),
    TRAIT_HEALING_POWERS("Healing powers", "निको पार्ने शक्ति"),
    TRAIT_SECRETIVE_WISDOM("Secretive wisdom", "गोप्य ज्ञान"),
    TRAIT_SELF_SUFFICIENT("Self-sufficient", "आत्मनिर्भर"),
    TRAIT_FIERY_PASSION("Fiery passion", "तीव्र जोश"),
    TRAIT_SPIRITUAL_WARRIOR("Spiritual warrior", "आध्यात्मिक योद्धा"),
    TRAIT_ASCETICISM("Asceticism", "तपस्या"),
    TRAIT_DEEP_MEDITATION("Deep meditation", "गहिरो ध्यान"),
    TRAIT_KUNDALINI_ENERGY("Kundalini energy", "कुण्डलिनी ऊर्जा"),
    TRAIT_WISDOM("Wisdom", "ज्ञान"),
    TRAIT_CONTROL_OVER_DESIRES("Control over desires", "इच्छाहरूमा नियन्त्रण"),
    TRAIT_PROTECTIVE_OF_OTHERS("Protective of others", "अरूको सुरक्षा गर्ने"),
    TRAIT_JOURNEY_COMPLETION("Journey completion", "यात्राको समाप्ति"),

    // ============================================
    // NAKSHATRA STRENGTHS
    // ============================================
    STRENGTH_QUICK_HEALER("Quick healer", "छिटो निको पार्ने"),
    STRENGTH_INITIATIVE("Initiative", "पहल"),
    STRENGTH_COURAGE("Courage", "साहस"),
    STRENGTH_REJUVENATION("Rejuvenation ability", "पुनरुत्थान क्षमता"),
    STRENGTH_STRONG_WILL("Strong will", "बलियो इच्छाशक्ति"),
    STRENGTH_SELF_DISCIPLINE("Self-discipline", "आत्म-अनुशासन"),
    STRENGTH_ENDURANCE("Endurance", "सहनशीलता"),
    STRENGTH_SHARP_MIND("Sharp mind", "तीक्ष्ण मन"),
    STRENGTH_PURIFYING_INFLUENCE("Purifying influence", "शुद्धिकरण प्रभाव"),
    STRENGTH_FAME_POTENTIAL("Fame potential", "प्रसिद्धिको सम्भावना"),
    STRENGTH_DETERMINATION("Determination", "दृढ संकल्प"),
    STRENGTH_INTUITION("Intuition", "अन्तर्ज्ञान"),
    STRENGTH_INNER_STRENGTH("Inner strength", "भित्री शक्ति"),

    // ============================================
    // NAKSHATRA WEAKNESSES
    // ============================================
    WEAKNESS_IMPATIENCE("Impatience", "अधैर्यता"),
    WEAKNESS_RECKLESSNESS("Recklessness", "लापरवाही"),
    WEAKNESS_OVERCONFIDENCE("Overconfidence", "अत्यधिक आत्मविश्वास"),
    WEAKNESS_RESTLESSNESS("Restlessness", "अस्थिरता"),
    WEAKNESS_STUBBORNNESS("Stubbornness", "जिद्दीपन"),
    WEAKNESS_POSSESSIVENESS("Possessiveness", "मोह"),
    WEAKNESS_JEALOUSY("Jealousy", "ईर्ष्या"),
    WEAKNESS_EXTREMISM("Extremism", "अतिवाद"),
    WEAKNESS_HARSH_SPEECH("Harsh speech", "कठोर बोली"),
    WEAKNESS_ANGER_ISSUES("Anger issues", "क्रोधका समस्याहरू"),
    WEAKNESS_CRITICAL_NATURE("Critical nature", "आलोचनात्मक प्रकृति"),
    WEAKNESS_DOMINATING("Dominating", "दबाब दिने"),
    WEAKNESS_OVERTHINKING("Overthinking", "अत्यधिक सोच"),
    WEAKNESS_ANXIETY("Anxiety", "चिन्ता"),
    WEAKNESS_SENSITIVITY("Sensitivity", "संवेदनशीलता"),
    WEAKNESS_PERFECTIONISM("Perfectionism", "पूर्णतावाद"),

    // ============================================
    // NAKSHATRA CAREER APTITUDES
    // ============================================
    CAREER_MEDICINE("Medicine", "चिकित्सा"),
    CAREER_SPORTS("Sports", "खेलकुद"),
    CAREER_EMERGENCY_SERVICES("Emergency services", "आपतकालीन सेवाहरू"),
    CAREER_TRANSPORT("Transport", "यातायात"),
    CAREER_ARTS("Arts", "कला"),
    CAREER_ENTERTAINMENT("Entertainment", "मनोरञ्जन"),
    CAREER_LEGAL_PROFESSION("Legal profession", "कानूनी पेशा"),
    CAREER_PUBLISHING("Publishing", "प्रकाशन"),
    CAREER_MILITARY("Military", "सैन्य"),
    CAREER_COOKING("Cooking", "भान्छा"),
    CAREER_ENGINEERING("Engineering", "इन्जिनियरिङ"),
    CAREER_SURGERY("Surgery", "शल्यक्रिया"),
    CAREER_AGRICULTURE("Agriculture", "कृषि"),
    CAREER_FASHION("Fashion", "फेसन"),
    CAREER_BEAUTY_INDUSTRY("Beauty industry", "सौन्दर्य उद्योग"),
    CAREER_REAL_ESTATE("Real estate", "घरजग्गा"),
    CAREER_TEACHING("Teaching", "शिक्षण"),
    CAREER_COUNSELING("Counseling", "परामर्श"),
    CAREER_CLERGY("Clergy", "धार्मिक गुरु"),
    CAREER_FOOD_INDUSTRY("Food industry", "खाद्य उद्योग"),
    CAREER_MANAGEMENT("Management", "व्यवस्थापन"),
    CAREER_CONSULTING("Consulting", "परामर्श सेवा"),
    CAREER_TECHNOLOGY("Technology", "प्रविधि"),
    CAREER_RESEARCH("Research", "अनुसन्धान"),

    // ============================================
    // NAKSHATRA MANTRAS
    // ============================================
    MANTRA_ASHWINI("ॐ अश्विनीकुमाराभ्यां नमः। Om Ashwini Kumarabhyam Namah", "ॐ अश्विनीकुमाराभ्यां नमः।"),
    MANTRA_BHARANI("ॐ यमाय नमः। Om Yamaya Namah", "ॐ यमाय नमः।"),
    MANTRA_KRITTIKA("ॐ अग्नये नमः। Om Agnaye Namah", "ॐ अग्नये नमः।"),
    MANTRA_ROHINI("ॐ ब्रह्मणे नमः। Om Brahmane Namah", "ॐ ब्रह्मणे नमः।"),
    MANTRA_MRIGASHIRA("ॐ सोमाय नमः। Om Somaya Namah", "ॐ सोमाय नमः।"),
    MANTRA_ARDRA("ॐ रुद्राय नमः। Om Rudraya Namah", "ॐ रुद्राय नमः।"),
    MANTRA_PUNARVASU("ॐ अदित्यै नमः। Om Adityai Namah", "ॐ अदित्यै नमः।"),
    MANTRA_PUSHYA("ॐ बृहस्पतये नमः। Om Brihaspataye Namah", "ॐ बृहस्पतये नमः।"),
    MANTRA_ASHLESHA("ॐ नागाय नमः। Om Nagaya Namah", "ॐ नागाय नमः।"),
    MANTRA_MAGHA("ॐ पितृभ्यो नमः। Om Pitribhyo Namah", "ॐ पितृभ्यो नमः।"),
    MANTRA_PURVA_PHALGUNI("ॐ भगाय नमः। Om Bhagaya Namah", "ॐ भगाय नमः।"),
    MANTRA_UTTARA_PHALGUNI("ॐ अर्यम्णे नमः। Om Aryamne Namah", "ॐ अर्यम्णे नमः।"),
    MANTRA_HASTA("ॐ सवित्रे नमः। Om Savitre Namah", "ॐ सवित्रे नमः।"),
    MANTRA_CHITRA("ॐ त्वष्ट्रे नमः। Om Tvashtre Namah", "ॐ त्वष्ट्रे नमः।"),
    MANTRA_SWATI("ॐ वायवे नमः। Om Vayave Namah", "ॐ वायवे नमः।"),
    MANTRA_VISHAKHA("ॐ इन्द्राग्निभ्यां नमः। Om Indragnibhyam Namah", "ॐ इन्द्राग्निभ्यां नमः।"),
    MANTRA_ANURADHA("ॐ मित्राय नमः। Om Mitraya Namah", "ॐ मित्राय नमः।"),
    MANTRA_JYESHTHA("ॐ इन्द्राय नमः। Om Indraya Namah", "ॐ इन्द्राय नमः।"),
    MANTRA_MULA("ॐ निर्ऋत्यै नमः। Om Nirrutyai Namah", "ॐ निर्ऋत्यै नमः।"),
    MANTRA_PURVA_ASHADHA("ॐ अपां नमः। Om Apam Namah", "ॐ अपां नमः।"),
    MANTRA_UTTARA_ASHADHA("ॐ विश्वेभ्यो देवेभ्यो नमः। Om Vishvebhyo Devebhyo Namah", "ॐ विश्वेभ्यो देवेभ्यो नमः।"),
    MANTRA_SHRAVANA("ॐ विष्णवे नमः। Om Vishnave Namah", "ॐ विष्णवे नमः।"),
    MANTRA_DHANISHTHA("ॐ वसुभ्यो नमः। Om Vasubhyo Namah", "ॐ वसुभ्यो नमः।"),
    MANTRA_SHATABHISHA("ॐ वरुणाय नमः। Om Varunaya Namah", "ॐ वरुणाय नमः।"),
    MANTRA_PURVA_BHADRAPADA("ॐ अजैकपदाय नमः। Om Ajaikapadaya Namah", "ॐ अजैकपदाय नमः।"),
    MANTRA_UTTARA_BHADRAPADA("ॐ अहिर्बुध्न्याय नमः। Om Ahirbudhnyaya Namah", "ॐ अहिर्बुध्न्याय नमः।"),
    MANTRA_REVATI("ॐ पूष्णे नमः। Om Pushne Namah", "ॐ पूष्णे नमः।"),
    ;
}
