package com.astro.storm.core.common
enum class StringKeyPanchanga(override val en: String, override val ne: String) : StringKeyInterface {
PANCHANGA_LIMBS_TITLE("Five Limbs of Hindu Calendar", "हिन्दु पात्रोका पाँच अंगहरू"),
    PANCHANGA_FIVE_LIMBS("Five Limbs (Pancha Anga)", "Five Limbs (Pancha Anga)"),
PANCHANGA_TIMING_AUSPICIOUSNESS("Timing & Auspiciousness", "समय र शुभता"),
PANCHANGA_SUN_MOON("Sun & Moon", "सूर्य र चन्द्रमा"),
PANCHANGA_RISE("Rise", "उदय"),
PANCHANGA_SET("Set", "अस्त"),
    PANCHANGA_LUNAR_DAY_FMT("Lunar day (%1\$2)", "Lunar day (%1\$2)"),
PANCHANGA_VARA_DESC("Weekday, ruled by specific planet", "बार, विशिष्ट ग्रहद्वारा शासित"),
    PANCHANGA_NAKSHATRA_DESC_FMT("Lunar mansion (Pada %1\$2)", "Lunar mansion (Pada %1\$2)"),
PANCHANGA_YOGA_DESC("Auspicious combination", "शुभ संयोग"),
PANCHANGA_KARANA_DESC("Half of a tithi", "तिथिको आधा भाग"),
PANCHANGA_AVOID_ACTIVITIES("Avoid important activities", "महत्त्वपूर्ण कार्यहरू नगर्नुहोस्"),
PANCHANGA_AUSPICIOUS_TIMING("Auspicious timing", "शुभ समय"),
PANCHANGA_CALCULATE_DAY("Calculate based on day", "दिनको आधारमा गणना गर्नुहोस्"),
PANCHANGA_MIDDAY_HOUR("Midday hour", "मध्यान्ह समय"),
PANCHANGA_SUN("Sun", "सूर्य"),
PANCHANGA_MOON("Moon", "चन्द्रमा"),
PANCHANGA_TITHI_LABEL("Tithi", "तिथि"),
PANCHANGA_VARA_LABEL("Vara", "वार"),
PANCHANGA_NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
PANCHANGA_YOGA_LABEL("Yoga", "योग"),
PANCHANGA_KARANA_LABEL("Karana", "करण"),
PANCHANGA_RAHU("Rahu Kaal", "राहु काल"),
PANCHANGA_YAMAGANDAM("Yamagandam", "यमगण्डम"),
PANCHANGA_GULIKA("Gulika Kaal", "गुलिक काल"),
PANCHANGA_ABHIJIT("Abhijit Muhurta", "अभिजित मुहूर्त"),
    PANCHANGA_INTRO("Panchanga comprises five essential elements (Pancha Anga)", "Panchanga comprises five essential elements (Pancha Anga)"),
    PANCHANGA_TITHI_DESC_LONG("The lunar day, calculated based on the angular distance between the Sun and Moon. Each tithi represents 12 degrees of lunar motion. There are 30 tithis in a lunar month, divided into Shukla (waxing)", "The lunar day, calculated based on the angular distance between the Sun and Moon. Each tithi represents 12 degrees of lunar motion. There are 30 tithis in a lunar month, divided into Shukla (waxing)"),
    PANCHANGA_TITHI_SIG("Determines the nature of activities suitable for the day. Some tithis like Purnima (full moon)", "Determines the nature of activities suitable for the day. Some tithis like Purnima (full moon)"),
PANCHANGA_VARA_DESC_LONG("The weekday, each ruled by a specific planet. The planetary ruler influences the nature and appropriate activities for that day.", "वार, प्रत्येक एक विशिष्ट ग्रहद्वारा शासित हुन्छ। ग्रह शासकले त्यस दिनको प्रकृति र उपयुक्त गतिविधिहरूलाई प्रभाव पार्छ।"),
PANCHANGA_VARA_SIG("Each vara has specific activities that are considered favorable. For example, Sunday is good for authority matters, Monday for emotional work.", "प्रत्येक वारमा विशिष्ट गतिविधिहरू हुन्छन् जुन अनुकूल मानिन्छन्। उदाहरणका लागि, आइतबार अधिकार मामिलाहरूको लागि राम्रो हुन्छ, सोमबार भावनात्मक कार्यको लागि।"),
PANCHANGA_NAKSHATRA_DESC_LONG("The lunar mansion where the Moon resides. There are 27 nakshatras, each spanning 13Â°20' of the zodiac. Each nakshatra has a ruling deity and planet.", "चन्द्रमा बस्ने नक्षत्र। त्यहाँ २७ नक्षत्रहरू छन्, प्रत्येकले राशिको १३°२०' ओगटेका छन्। प्रत्येक नक्षत्रको एक शासक देवता र ग्रह हुन्छ।"),
PANCHANGA_NAKSHATRA_SIG("Birth nakshatra determines personality traits and compatibility. Moon's nakshatra is crucial for muhurta selection.", "जन्म नक्षत्रले व्यक्तित्व गुणहरू र अनुकूलता निर्धारण गर्दछ। मुहूर्त चयनको लागि चन्द्रमाको नक्षत्र महत्त्वपूर्ण छ।"),
PANCHANGA_YOGA_DESC_LONG("Calculated from the combined longitudes of Sun and Moon. There are 27 yogas, each with specific qualities ranging from highly auspicious to inauspicious.", "सूर्य र चन्द्रमाको संयुक्त देशान्तरबाट गणना गरिएको। त्यहाँ २७ योगहरू छन्, प्रत्येकसँग अत्यधिक शुभ देखि अशुभ सम्मका विशिष्ट गुणहरू छन्।"),
PANCHANGA_YOGA_SIG("Yogas indicate the general nature of results from activities undertaken. Siddha, Amrita, and Shubha yogas are highly favorable.", "योगहरूले गरिएका गतिविधिहरूको परिणामको सामान्य प्रकृति संकेत गर्दछ। सिद्ध, अमृत र शुभ योगहरू अत्यधिक अनुकूल हुन्छन्।"),
PANCHANGA_KARANA_DESC_LONG("Half of a tithi, there are 11 karanas total. Seven are movable and four are fixed. Each karana has its own nature and suitable activities.", "तिथिको आधा भाग, कुल ११ करणहरू छन्। सात चर र चार स्थिर छन्। प्रत्येक करणको आफ्नै प्रकृति र उपयुक्त गतिविधिहरू छन्।"),
PANCHANGA_KARANA_SIG("Karanas fine-tune the effects of tithis. Movable karanas recur throughout the month while fixed ones appear only once.", "करणहरूले तिथिका प्रभावहरूलाई सुष्म बनाउँछन्। चर करणहरू महिनाभर दोहोरिन्छन् भने स्थिर करणहरू एक पटक मातॠर आउँछन्।"),
PANCHANGA_ABOUT_TITLE("About Panchanga", "पञ्चाङ्गको बारेमा"),
    PANCHANGA_ABOUT_DESC_1("Panchanga (Sanskrit: पञ्चाङ्ग)", "Panchanga (Sanskrit: पञ्चाङ्ग)"),
    PANCHANGA_ABOUT_DESC_2("These five elements together determine the auspiciousness of any moment and are crucial for selecting muhurtas (auspicious timings)", "These five elements together determine the auspiciousness of any moment and are crucial for selecting muhurtas (auspicious timings)"),
PANCHANGA_SIGNIFICANCE("Significance", "महत्त्व"),
PANCHANGA_AT_BIRTH("Panchanga at Birth", "जन्मको समयको पञ्चाङ्ग"),
PANCHANGA_ABOUT("About Panchanga", "पञ्चाङ्गको बारेमा"),
PANCHANGA_ABOUT_INTRO("पञ्चाङ्ग परिचय", "पञ्चाङ्ग परिचय"),
PANCHANGA_SANSKRIT("पञ्चाङ्ग", "पञ्चाङ्ग"),
PANCHANGA_LUNAR_DAY("Lunar Day", "चन्द्र दिन"),
PANCHANGA_LUNAR_DAY_SANSKRIT("तिथि", "तिथि"),
PANCHANGA_LUNAR_MANSION("Lunar Mansion", "चन्द्र नक्षत्र"),
PANCHANGA_LUNAR_MANSION_SANSKRIT("नक्षत्र", "नक्षत्र"),
PANCHANGA_LUNISOLAR("Luni-Solar Combination", "चन्द्र-सूर्य संयोजन"),
PANCHANGA_LUNISOLAR_SANSKRIT("योग", "योग"),
PANCHANGA_HALF_LUNAR_DAY("Half Lunar Day", "अर्ध चन्द्र दिन"),
PANCHANGA_HALF_LUNAR_DAY_SANSKRIT("करण", "करण"),
PANCHANGA_WEEKDAY("Weekday", "वार"),
PANCHANGA_WEEKDAY_SANSKRIT("वार", "वार"),
PANCHANGA_NUMBER("Number", "संख्या"),
PANCHANGA_NUMBER_OF("of", "मध्ये"),
PANCHANGA_DEITY("Deity", "देवता"),
PANCHANGA_LORD("Lord", "स्वामी"),
PANCHANGA_NATURE("Nature", "प्रकृति"),
PANCHANGA_PROGRESS("Progress", "प्रगति"),
PANCHANGA_SYMBOL("Symbol", "चिन्ह"),
PANCHANGA_GANA("Gana", "गण"),
PANCHANGA_GUNA("Guna", "गुण"),
PANCHANGA_ANIMAL("Animal", "पशु"),
PANCHANGA_MEANING("Meaning", "अर्थ"),
PANCHANGA_TYPE("Type", "प्रकार"),
PANCHANGA_ELEMENT("Element", "तत्व"),
PANCHANGA_DIRECTION("Direction", "दिशा"),
PANCHANGA_RULING_PLANET("Ruling Planet", "शासक ग्रह"),
PANCHANGA_CHARACTERISTICS("Characteristics", "विशेषताहरू"),
PANCHANGA_EFFECTS("Effects", "प्रभावहरू"),
PANCHANGA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
PANCHANGA_AVOID("Activities to Avoid", "टाढा रहनु पर्ने गतिविधिहरू"),
PANCHANGA_TITHI_SUBTITLE("Lunar Day • तिथि", "चन्द्र दिन • तिथि"),
PANCHANGA_NAKSHATRA_SUBTITLE("Lunar Mansion • नक्षत्र", "चन्द्र नक्षत्र • नक्षत्र"),
PANCHANGA_YOGA_SUBTITLE("Luni-Solar Combination • योग", "चन्द्र-सूर्य संयोजन • योग"),
PANCHANGA_KARANA_SUBTITLE("Half Lunar Day • करण", "अर्ध चन्द्र दिन • करण"),
PANCHANGA_VARA_SUBTITLE("Weekday • वार", "वार • वार"),
PANCHANGA_SANSKRIT_LABEL("Sanskrit", "संस्कृत"),
PANCHANGA_PADA("Pada", "पद"),
PANCHANGA_RULER("Ruler", "स्वामी"),
PANCHANGA_ABOUT_SUBTITLE("पञ्चाङ्ग परिचय", "पञ्चाङ्ग परिचय"),
    PANCHANGA_ABOUT_DESCRIPTION("Panchanga (Sanskrit: पञ्चाङ्ग)", "पञ्चाङ्ग (संस्कृत: पञ्चाङ्ग)"),
PANCHANGA_TITHI_DESC("Based on the angular distance between Sun and Moon. Each tithi spans 12° of lunar elongation. There are 30 tithis in a lunar month.", "सूर्य र चन्द्रमाबीचको कोणीय दूरीमा आधारित। प्रत्येक तिथि १२° चन्द्र विस्तार समेट्छ। एक चान्द्र महिनामा ३० तिथि हुन्छन्।"),
PANCHANGA_NAKSHATRA_DESC("The Moon's position among 27 stellar constellations, each spanning 13°20'. Determines the Moon's influence on consciousness.", "२७ नक्षत्र तारामण्डलहरू बीच चन्द्रमाको स्थिति, प्रत्येक १३°२०' समेट्छ। चेतनामा चन्द्रमाको प्रभाव निर्धारण गर्दछ।"),
PANCHANGA_BIRTH_INSIGHT("The Panchanga at birth reveals the cosmic influences active at the moment of incarnation, providing insights into one's inherent nature, tendencies, and life patterns.", "जन्मको समयको पञ्चाङ्गले अवतारको क्षणमा सक्रिय ब्रह्माण्डीय प्रभावहरू प्रकट गर्दछ, व्यक्तिको स्वभाविक प्रकृति, प्रवृत्ति र जीवन ढाँचामा अन्तर्दृष्टि प्रदान गर्दछ।"),
PANCHANGA_BIRTH_INTERP_MAIN("Born on %1\$s, under the %2\$s nakshatra during %3\$s tithi.", "%1\$sमा जन्म, %3\$s तिथिमा %2\$s नक्षत्र अन्तर्गत।"),
PANCHANGA_BIRTH_INTERP_YOGA("The %s yoga was active, indicating ", "%s योग सक्रिय थियो, जसले "),
PANCHANGA_BIRTH_INTERP_YOGA_CHALLENGE("challenges to overcome but also strength building opportunities. ", "पार गर्नुपर्ने चुनौतीहरू तर शक्ति निर्माणका अवसरहरू पनि संकेत गर्दछ।"),
PANCHANGA_BIRTH_INTERP_YOGA_AUSPICIOUS("highly auspicious conditions at birth, suggesting favorable karma. ", "जन्मको समयमा अत्यधिक शुभ परिस्थितिहरू, अनुकूल कर्मको संकेत गर्दछ।"),
PANCHANGA_BIRTH_INTERP_YOGA_MODERATE("moderate influences that support balanced development. ", "सन्तुलित विकासलाई समर्थन गर्ने मध्यम प्रभावहरू।"),
PANCHANGA_BIRTH_INTERP_KARANA("The %s karana further refines these birth energies.", "%s करणले यी जन्म ऊर्जाहरूलाई थप परिष्कृत गर्दछ।"),
    PANCHANGA_INFO_TITHI_TITLE("Tithi (तिथि)", "Tithi (तिथि)"),
    PANCHANGA_INFO_NAKSHATRA_TITLE("Nakshatra (नक्षत्र)", "Nakshatra (नक्षत्र)"),
    PANCHANGA_INFO_YOGA_TITLE("Yoga (योग)", "Yoga (योग)"),
    PANCHANGA_INFO_KARANA_TITLE("Karana (करण)", "Karana (करण)"),
    PANCHANGA_INFO_VARA_TITLE("Vara (वार)", "Vara (वार)"),
PANCHANGA_INFO_TITHI_LABEL("Lunar Day", "चन्द्र दिन"),
PANCHANGA_INFO_NAKSHATRA_LABEL("Lunar Mansion", "चन्द्र नक्षत्र"),
PANCHANGA_INFO_YOGA_LABEL("Luni-Solar Combination", "चन्द्र-सूर्य संयोजन"),
PANCHANGA_INFO_KARANA_LABEL("Half Tithi", "अर्ध तिथि"),
PANCHANGA_INFO_VARA_LABEL("Weekday", "वार"),
PANCHANGA_TITHI("Tithi", "तिथि"),
    PANCHANGA_VARA("Vara (Day)", "Vara (Day)"),
PANCHANGA_YOGA("Yoga", "योग"),
PANCHANGA_KARANA("Karana", "करण"),
PANCHANGA_SUNRISE("Sunrise", "सूर्योदय"),
PANCHANGA_SUNSET("Sunset", "सूर्यास्त"),
PANCHANGA_MOONRISE("Moonrise", "चन्द्रोदय"),
PANCHANGA_MOONSET("Moonset", "चन्द्रास्त"),
PANCHANGA_TITHI_SHUKLA("Shukla", "शुक्ल"),
PANCHANGA_TITHI_KRISHNA("Krishna", "कृष्ण"),
PANCHANGA_PAKSHA("Paksha", "पक्ष"),
PANCHANGA_MASA("Masa", "मास"),
PANCHANGA_LUNAR_PHASE("Lunar Phase", "चन्द्र कला"),
PANCHANGA_NEW_MOON("New Moon", "अमावस्या"),
PANCHANGA_FULL_MOON("Full Moon", "पूर्णिमा"),
PANCHANGA_WAXING("Waxing", "बढ्दो"),
PANCHANGA_WANING("Waning", "घट्दो"),
PANCHANGA_FAVORABLE("Favorable", "अनुकूल"),
PANCHANGA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
PANCHANGA_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू")
}
