package com.astro.storm.core.common
enum class StringKeyError(override val en: String, override val ne: String) : StringKeyInterface {
ERROR_QUERY_MIN_CHARS("Query must be at least 2 characters", "खोजी कम्तीमा २ वर्णको हुनुपर्छ"),
ERROR_CONNECTION_TIMEOUT("Connection timeout. Please check your internet.", "जडान समय समाप्त। कृपया आफ्नो इन्टरनेट जाँच गर्नुहोस्।"),
ERROR_NO_INTERNET("No internet connection.", "इन्टरनेट जडान छैन।"),
ERROR_UNKNOWN("Unknown error", "अज्ञात त्रुटि"),
ERROR_MOON_NOT_FOUND("Unable to calculate - Moon position not found", "गणना गर्न असमर्थ - चन्द्र स्थिति फेला परेन"),
ERROR_SADE_SATI_CALC("Unable to calculate Sade Sati - Moon position not available in chart.", "साढ़े साती गणना गर्न असमर्थ - कुण्डलीमा चन्द्र स्थिति उपलब्ध छैन।"),
ERROR_BAV_NOT_FOUND("Bhinnashtakavarga not found for %s", "%s को लागि भिन्नाष्टकवर्ग फेला परेन"),
ERROR_ASHTAKAVARGA_NOT_APPLICABLE("Ashtakavarga not applicable for %s", "%s को लागि अष्टकवर्ग लागू हुँदैन"),
ERROR_CALCULATION("Calculation Error", "गणना त्रुटि"),
DEBUG_UNHANDLED_EXCEPTION("Unhandled Exception", "अप्रत्याशित त्रुटि"),
DEBUG_ERROR_OCCURRED("An unexpected error occurred.", "एउटा अप्रत्याशित त्रुटि भयो।"),
DEBUG_COPY_LOG("Copy", "कपी गर्नुहोस्"),
DEBUG_RESTART_APP("Restart", "पुनः सुरु गर्नुहोस्"),
DEBUG_CRASH_LOG("Crash Log", "क्र्यास लग"),
ERROR_HOROSCOPE_UNAVAILABLE_FMT("Horoscope for {0} is currently unavailable.", "{0}को राशिफल हाल उपलब्ध छैन।"),
ERROR_GENERIC_RETRY("Please try again later.", "कृपया पछि फेरि प्रयास गर्नुहोस्।"),
ERROR_PARTIAL("Partial Data Loaded", "आंशिक डाटा लोड भयो"),
ERROR_CALCULATIONS_FAILED("{0} calculations failed", "{0} गणनाहरू असफल भए"),
ERROR_UNABLE_TO_LOAD("Unable to Load", "लोड गर्न सकिएन"),
ERROR_HOROSCOPE_UNAVAILABLE("%s's horoscope unavailable", "%s को राशिफल उपलब्ध छैन"),
ERROR_EPHEMERIS_DATA("Unable to calculate planetary positions for this period. This may be due to ephemeris data limitations.", "यस अवधिको लागि ग्रह स्थितिहरू गणना गर्न असमर्थ। यो ईफेमेरिस डाटा सीमितताको कारण हुन सक्छ।"),
ERROR_SOMETHING_WRONG("Something went wrong", "केही गलत भयो"),
ERROR_ANALYSIS_FAILED("Analysis Failed", "विश्लेषण असफल"),
ERROR_INPUT("Input Error", "इनपुट त्रुटि"),
ERROR_INVALID_COORDS("Please enter valid latitude and longitude", "कृपया मान्य अक्षांश र देशान्तर प्रविष्ट गर्नुहोस्"),
ERROR_LATITUDE_RANGE("Latitude must be between -90 and 90", "अक्षांश -९० र ९० बीचमा हुनुपर्छ"),
ERROR_LONGITUDE_RANGE("Longitude must be between -180 and 180", "देशान्तर -१८० र १८० बीचमा हुनुपर्छ"),
ERROR_CHECK_INPUT("Please check your input values", "कृपया आफ्नो इनपुट मानहरू जाँच गर्नुहोस्"),
ERROR_CALCULATION_FAILED("Calculation failed", "गणना असफल भयो"),
ERROR_RATE_LIMIT("Too many requests. Please wait.", "धेरै अनुरोधहरू। कृपया पर्खनुहोस्।"),
ERROR_SEARCH_FAILED("Search failed. Please try again.", "खोज असफल भयो। कृपया फेरि प्रयास गर्नुहोस्।"),
ERROR_RATE_LIMIT_EXCEEDED("Rate limit exceeded", "दर सीमा नाघ्यो"),
ERROR_NAME_TOO_LONG("Name must be 100 characters or less", "नाम १०० वर्ण वा कम हुनुपर्छ"),
ERROR_DATE_IN_FUTURE("Birth date cannot be in the future", "जन्म मिति भविष्यमा हुन सक्दैन"),
ERROR_DATE_TOO_OLD("Date must be after year 1800", "मिति वर्ष १८०० पछिको हुनुपर्छ"),
ERROR_LOCATION_REQUIRED("Please enter a location or coordinates", "कृपया स्थान वा निर्देशांक प्रविष्ट गर्नुहोस्"),
ERROR_TIMEZONE_INVALID("Please select a valid timezone", "कृपया मान्य समय क्षेत्र छान्नुहोस्")
}
