package com.astro.storm.core.common

enum class StringKeyDosha(override val en: String, override val ne: String) : StringKeyInterface {
    DOSHA_ABSENT("Absent", "अनुपस्थित"),
    DOSHA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    DOSHA_ANALYSIS("Dosha Analysis", "दोष विश्लेषण"),
    DOSHA_AUSPICIOUS_TIMES("Auspicious Times for Remedies", "उपायहरूको लागि शुभ समय"),
    DOSHA_BALANCE("Dosha Balance", "दोष सन्तुलन"),
    DOSHA_BHAKOOT("Bhakoot Dosha", "भकूट दोष"),
    DOSHA_CANCELLED("Cancelled", "रद्द"),
    DOSHA_CANCEL_EXPLAINED("Dosha Cancellation Factors Explained", "दोष रद्द कारकहरू व्याख्या"),
    DOSHA_INDICATORS("Indicators Found", "संकेतकहरू फेला परे"),
    DOSHA_INTERPRETATION("Interpretation", "व्याख्या"),
    DOSHA_KAPHA("Kapha Dosha", "कफ दोष"),
    DOSHA_MANGLIK("Manglik Dosha", "मांगलिक दोष"),
    DOSHA_NADI("Nadi Dosha", "नाडी दोष"),
    DOSHA_PITTA("Pitta Dosha", "पित्त दोष"),
    DOSHA_PRESENT("Present", "उपस्थित"),
    DOSHA_REMEDIES_AVAILABLE("Remedies Available", "उपायहरू उपलब्ध"),
    DOSHA_REMEDIES_SECTION("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
    DOSHA_SEVERITY_SCORE("Severity Score", "गम्भीरता अंक"),
    DOSHA_VATA("Vata Dosha", "वात दोष"),
    PITRA_AREA_CAREER("Career and public reputation", "क्यारियर र सार्वजनिक प्रतिष्ठा"),
    PITRA_AREA_CHILDREN("Children, education, and creativity", "बच्चाहरू, शिक्षा, र सृजनात्मकता"),
    PITRA_AREA_FAMILY_WEALTH("Family wealth and accumulated assets", "पारिवारिक सम्पत्ति र संचित सम्पत्ति"),
    PITRA_AREA_FATHER("Father and paternal lineage", "पिता र पैतृक वंश"),
    PITRA_AREA_FORTUNE("Fortune, higher learning, and spirituality", "भाग्य, उच्च शिक्षा, र आध्यात्मिकता"),
    PITRA_AREA_GAINS("Gains and social network", "लाभ र सामाजिक नेटवर्क"),
    PITRA_AREA_HEALTH("Health, debts, and service", "स्वास्थ्य, ऋण, र सेवा"),
    PITRA_AREA_LIBERATION("Spiritual liberation and foreign lands", "आध्यात्मिक मुक्ति र विदेश"),
    PITRA_AREA_LONGEVITY("Longevity and inherited wealth", "दीर्घायु र विरासत सम्पत्ति"),
    PITRA_AREA_MARRIAGE("Marriage and partnerships", "विवाह र साझेदारी"),
    PITRA_AREA_MOTHER("Mother, property, and domestic peace", "आमा, सम्पत्ति, र घरेलु शान्ति"),
    PITRA_AREA_SELF("Self, health, and overall life direction", "आत्म, स्वास्थ्य, र समग्र जीवन दिशा"),
    PITRA_AREA_SIBLINGS("Siblings and communication", "भाइबहिनी र संचार"),
    PITRA_AREA_SPIRITUAL("Spiritual progress and dharma", "आध्यात्मिक प्रगति र धर्म"),
    PITRA_DESC_COMBINED("Multiple factors indicate significant ancestral karma", "बहु कारकहरूले महत्त्वपूर्ण पुर्खाको कर्म संकेत गर्छन्"),
    PITRA_DESC_MALEFICS_NINTH(
        "Malefics in 9th house - Ancestral blessings blocked",
        "९औं भावमा पाप ग्रह - पैतृक आशीर्वाद अवरुद्ध"
    ),
    PITRA_DESC_NINTH_HOUSE("House of ancestors afflicted by malefics", "पुर्खाको भाव अशुभ ग्रहबाट पीडित"),
    PITRA_DESC_NINTH_LORD("Lord of father and fortune is weakened", "पिता र भाग्यको स्वामी कमजोर छ"),
    PITRA_DESC_NINTH_LORD_AFFLICTED(
        "9th lord %s is afflicted - Ancestral lineage karma",
        "९औं स्वामी %s पीडित छ - पैतृक वंश कर्म"
    ),
    PITRA_DESC_RAHU_NINTH("Strong indication of ancestral debts", "पुर्खाको ऋणको बलियो संकेत"),
    PITRA_DESC_SATURN_ASPECT(
        "Saturn aspects Sun from House %d - Delayed results due to ancestral karma",
        "शनिले भाव %d बाट सूर्यलाई हेर्छ - पैतृक कर्मले गर्दा ढिलो परिणाम"
    ),
    PITRA_DESC_SUN_KETU_HOUSE(
        "Sun conjunct Ketu in House %d - Indicates past-life ancestral karma",
        "भाव %d मा सूर्य-केतु युति - पूर्वजन्मको पैतृक कर्म संकेत"
    ),
    PITRA_DESC_SUN_RAHU_HOUSE(
        "Sun conjunct Rahu in House %d - Primary Pitra Dosha indicator",
        "भाव %d मा सूर्य-राहु युति - प्रमुख पित्र दोष संकेतक"
    ),
    PITRA_DESC_SUN_SATURN_CONJUNCT(
        "Sun conjunct Saturn in House %d - Father-related karmic issues",
        "भाव %d मा सूर्य-शनि युति - पितृ-सम्बन्धी कार्मिक मुद्दाहरू"
    ),
    PITRA_DESC_SURYA_KETU("Past-life karmic debts from paternal lineage", "पितृ वंशबाट पूर्व जन्मको कर्म ऋण"),
    PITRA_DESC_SURYA_RAHU("Primary indicator - eclipsed Sun indicates blocked ancestral blessings", "प्राथमिक संकेतक - ग्रहण लागेको सूर्यले अवरुद्ध पुर्खाको आशीर्वाद संकेत गर्छ"),
    PITRA_DESC_SURYA_SHANI("Father-related karmic lessons and delays", "पिता-सम्बन्धित कर्म पाठ र ढिलाइ"),
    PITRA_DOSHA_ABSENT_SUMMARY("No significant Pitra Dosha indicators found", "कुनै महत्त्वपूर्ण पितृ दोष संकेतकहरू फेला परेनन्"),
    PITRA_DOSHA_MINOR("Minor Pitra Dosha", "हल्का पितृ दोष"),
    PITRA_DOSHA_MODERATE("Moderate Pitra Dosha", "मध्यम पितृ दोष"),
    PITRA_DOSHA_NONE("No Pitra Dosha", "पितृ दोष छैन"),
    PITRA_DOSHA_PRESENT_SUMMARY("{level} detected in chart", "कुण्डलीमा {level} पत्ता लाग्यो"),
    PITRA_DOSHA_SEVERE("Severe Pitra Dosha", "गम्भीर पितृ दोष"),
    PITRA_DOSHA_SIGNIFICANT("Significant Pitra Dosha", "महत्त्वपूर्ण पितृ दोष"),
    PITRA_DOSHA_SUBTITLE("Ancestral Karma Assessment", "पुर्खाको कर्म मूल्यांकन"),
    PITRA_DOSHA_TITLE("Pitra Dosha Analysis", "पितृ दोष विश्लेषण"),
    PITRA_INTERP_BENEFICIAL(
        "However, performing regular ancestral offerings (Shraddha) is always beneficial for maintaining positive ancestral blessings.",
        "तथापि, सकारात्मक पैतृक आशीर्वाद कायम राख्न नियमित श्राद्ध गर्नु सधैं लाभदायक हुन्छ।"
    ),
    PITRA_INTERP_BENEFIC_INFLUENCE("Benefic Influence:", "शुभ प्रभाव:"),
    PITRA_INTERP_HEADER("PITRA DOSHA ANALYSIS", "पित्र दोष विश्लेषण"),
    PITRA_INTERP_HOUSE_AFFLICTED("9th House Afflicted:", "९औं भाव पीडित:"),
    PITRA_INTERP_LORD_AFFLICTED("9th Lord Afflicted:", "९औं स्वामी पीडित:"),
    PITRA_INTERP_NINTH_HOUSE("9TH HOUSE ANALYSIS (House of Ancestors):", "९औं भाव विश्लेषण (पूर्वजको भाव):"),
    PITRA_INTERP_NINTH_LORD("9th Lord:", "९औं स्वामी:"),
    PITRA_INTERP_NINTH_LORD_POSITION("9th Lord Position:", "९औं स्वामीको स्थिति:"),
    PITRA_INTERP_NO_DOSHA("NO SIGNIFICANT PITRA DOSHA", "कुनै महत्वपूर्ण पित्र दोष छैन"),
    PITRA_INTERP_NO_DOSHA_DESC(
        "Your chart does not show significant indicators of Pitra Dosha.",
        "तपाईंको कुण्डलीमा पित्र दोषको महत्वपूर्ण संकेतकहरू देखिँदैनन्।"
    ),
    PITRA_INTERP_SUPPORTIVE(
        "The ancestral lineage appears supportive of your life journey.",
        "पैतृक वंश तपाईंको जीवन यात्रामा सहायक देखिन्छ।"
    ),
    PITRA_INTERP_YES_MITIGATING("Yes - Mitigating", "छ - न्यूनीकरण गर्दै"),
    PITRA_LEVEL_MINOR_DESC(
        "Minor ancestral karma is indicated. This may manifest as occasional obstacles or delays that seem unexplained. Regular ancestral prayers and offerings during Pitru Paksha should be sufficient.",
        "साना पैतृक कर्म संकेत गरिएको छ। यसले अव्याख्येय देखिने कहिलेकाहीं अवरोधहरू वा ढिलाइको रूपमा प्रकट हुन सक्छ। पितृ पक्षमा नियमित पैतृक प्रार्थना र अर्पण पर्याप्त हुनुपर्छ।"
    ),
    PITRA_LEVEL_MODERATE_DESC(
        "Moderate Pitra Dosha suggests unresolved ancestral obligations. You may experience recurring challenges in life that feel karmic. Regular Tarpan and Shraddha ceremonies are recommended.",
        "मध्यम पित्र दोषले अपूर्ण पैतृक दायित्वहरू संकेत गर्दछ। तपाईंले कार्मिक जस्तो लाग्ने जीवनमा आवर्ती चुनौतीहरू अनुभव गर्न सक्नुहुन्छ। नियमित तर्पण र श्राद्ध समारोहहरू सिफारिस गरिन्छ।"
    ),
    PITRA_LEVEL_SEVERE_DESC(
        "Severe Pitra Dosha indicates deep ancestral karma that requires serious attention and remedial measures. This level of dosha often indicates: ancestors who departed with unfulfilled wishes, interrupted or improper last rites in the lineage, and significant karmic debts carried forward. Consult a qualified priest for Narayan Bali/Nagbali and Pind Daan at sacred places like Gaya.",
        "गम्भीर पित्र दोषले गहिरो पैतृक कर्म संकेत गर्दछ जसलाई गम्भीर ध्यान र उपचारात्मक उपायहरू आवश्यक छ। यस स्तरको दोषले प्रायः संकेत गर्दछ: अपूर्ण इच्छाहरूसँग गएका पूर्वजहरू, वंशमा अवरुद्ध वा अनुचित अन्तिम संस्कार, र अगाडि लगिएको महत्वपूर्ण कार्मिक ऋणहरू। गयामा नारायण बलि/नागबलि र पिण्डदान को लागि योग्य पुजारीसँग परामर्श गर्नुहोस्।"
    ),
    PITRA_LEVEL_SIGNIFICANT_DESC(
        "Significant ancestral karma is present. This may manifest as: delayed marriage or relationship issues, difficulties with children or progeny, career obstacles despite qualifications, and family disharmony. Comprehensive remedies including Narayan Bali may be beneficial.",
        "महत्वपूर्ण पैतृक कर्म उपस्थित छ। यसले विवाहमा ढिलाइ वा सम्बन्ध समस्या, सन्तान वा सन्ततिमा कठिनाइहरू, योग्यता भएता पनि क्यारियरमा अवरोधहरू, र पारिवारिक विसंगतिको रूपमा प्रकट हुन सक्छ। नारायण बलि सहित व्यापक उपायहरू लाभदायक हुन सक्छ।"
    ),
    PITRA_PERIOD_AKSHAYA("Akshaya Tritiya", "अक्षय तृतीया"),
    PITRA_PERIOD_AMAVASYA("Amavasya (New Moon days)", "औंसी (अमावस्या दिनहरू)"),
    PITRA_PERIOD_DEATH_ANNIV("Father's death anniversary", "पिताको पुण्यतिथि"),
    PITRA_PERIOD_ECLIPSE("Solar/Lunar eclipses", "सूर्य/चन्द्र ग्रहण"),
    PITRA_PERIOD_GAYA("Gaya Shraddha periods", "गया श्राद्ध अवधिहरू"),
    PITRA_PERIOD_MAHALAYA("Mahalaya Amavasya", "महालय अमावस्या"),
    PITRA_PERIOD_PITRU_PAKSHA("Pitru Paksha (15-day period in Bhadrapada month)", "पितृ पक्ष (भाद्र महिनामा १५ दिनको अवधि)"),
    PITRA_TIMING_AMAVASYA("Amavasya (New Moon) or Pitru Paksha", "औंसी वा पितृ पक्ष"),
    PITRA_TIMING_BRAHMA_MUHURTA("Daily during Brahma Muhurta", "ब्रह्म मुहूर्तमा दैनिक"),
    PITRA_TIMING_DAILY_PITRU("Daily, especially during Pitru Paksha", "दैनिक, विशेष गरी पितृ पक्षमा"),
    PITRA_TIMING_DEATH_ANNIVERSARY("Father's death anniversary or Pitru Paksha", "पिताको पुण्यतिथि वा पितृ पक्ष"),
    PITRA_TIMING_NARAYAN_BALI("Once in lifetime at Trimbakeshwar or Gaya", "जीवनकालमा एकपटक त्र्यम्बकेश्वर वा गयामा"),
    PITRA_TIMING_PIND_DAAN("Pitru Paksha at Gaya", "गयामा पितृ पक्ष"),
    PITRA_TYPE_COMBINED("Combined Affliction", "संयुक्त पीडा"),
    PITRA_TYPE_NINTH_HOUSE("9th House Affliction", "९औं भाव पीडा"),
    PITRA_TYPE_NINTH_LORD("9th Lord Affliction", "९औं भावेश पीडा"),
    PITRA_TYPE_RAHU_NINTH("Rahu in 9th House", "९औं भावमा राहु"),
    PITRA_TYPE_SURYA_KETU("Sun-Ketu Conjunction", "सूर्य-केतु युति"),
    PITRA_TYPE_SURYA_RAHU("Sun-Rahu Conjunction", "सूर्य-राहु युति"),
    PITRA_TYPE_SURYA_SHANI("Sun-Saturn Affliction", "सूर्य-शनि पीडा"),
    SADE_SATI_12TH_HOUSE("12th house", "१२औं भाव"),
    SADE_SATI_2ND_HOUSE("2nd house", "२औं भाव"),
    SADE_SATI_ACTIVE("Sade Sati Active", "साढेसाती सक्रिय"),
    SADE_SATI_ACTIVE_HEADER("SADE SATI ACTIVE - %s PHASE", "साढ़े साती सक्रिय - %s चरण"),
    SADE_SATI_ACTIVE_SUMMARY("{phase} phase active with {severity} intensity", "{phase} चरण {severity} तीव्रताका साथ सक्रिय"),
    SADE_SATI_ASHTAMA_CHALLENGING(
        "This is considered one of the most challenging Saturn transits.",
        "यो शनिको सबैभन्दा चुनौतीपूर्ण गोचर मध्ये एक मानिन्छ।"
    ),
    SADE_SATI_ASHTAMA_CHANGES("Sudden changes and transformations", "अचानक परिवर्तन र रूपान्तरणहरू"),
    SADE_SATI_ASHTAMA_HEADER("ASHTAMA SHANI - Saturn in 8th from Moon", "अष्टम शनि - चन्द्रबाट ८औं मा शनि"),
    SADE_SATI_ASHTAMA_HEALTH("Health requires vigilance", "स्वास्थ्यमा सतर्कता आवश्यक"),
    SADE_SATI_ASHTAMA_OBSTACLES("Obstacles in ventures", "उद्यमहरूमा अवरोधहरू"),
    SADE_SATI_ASHTAMA_PSYCHOLOGICAL("Deep psychological transformation", "गहिरो मनोवैज्ञानिक रूपान्तरण"),
    SADE_SATI_DAYS_REMAINING("Days Remaining", "बाँकी दिनहरू"),
    SADE_SATI_EFFECTS("Sade Sati Effects", "साढे साती प्रभावहरू"),
    SADE_SATI_FACTOR_DEBILITATED("Saturn is debilitated in transit - effects may be more challenging", "शनि गोचरमा नीच - प्रभावहरू थप चुनौतीपूर्ण हुन सक्छ"),
    SADE_SATI_FACTOR_EXALTED("Saturn is exalted in transit - effects significantly reduced", "शनि गोचरमा उच्च - प्रभावहरू उल्लेखनीय कम"),
    SADE_SATI_FACTOR_NATAL_STRONG("Natal Saturn is strong - better equipped to handle transit", "जन्म शनि बलियो - गोचर सम्हाल्न राम्रो सुसज्जित"),
    SADE_SATI_FACTOR_NATAL_WEAK("Natal Saturn is weak - transit effects may be more pronounced", "जन्म शनि कमजोर - गोचर प्रभाव थप उच्चारित हुन सक्छ"),
    SADE_SATI_FACTOR_OWN_SIGN("Saturn is in own sign - effects well-managed", "शनि स्वराशिमा - प्रभावहरू राम्रोसँग व्यवस्थित"),
    SADE_SATI_FACTOR_RETROGRADE("Natal Saturn is retrograde - internal processing of karmic lessons", "जन्म शनि वक्री - कार्मिक पाठहरूको आन्तरिक प्रशोधन"),
    SADE_SATI_FACTOR_WEAK_MOON("Natal Moon is weak - emotional resilience may be tested", "जन्म चन्द्र कमजोर - भावनात्मक लचिलोपन परीक्षण हुन सक्छ"),
    SADE_SATI_FACTOR_YOGAKARAKA("Saturn is Yogakaraka for your ascendant - may bring positive results", "शनि तपाईंको लग्नको लागि योगकारक - सकारात्मक परिणाम ल्याउन सक्छ"),
    SADE_SATI_FAVORABLE_PERIOD(
        "This is generally a favorable period regarding Saturn's influence on emotional and mental well-being.",
        "भावनात्मक र मानसिक कल्याणमा शनिको प्रभाव सम्बन्धमा यो सामान्यतया अनुकूल अवधि हो।"
    ),
    SADE_SATI_FOURTH_DOMESTIC("Domestic peace may be disturbed", "घरेलु शान्ति अशान्त हुन सक्छ"),
    SADE_SATI_FOURTH_MENTAL("Mental peace may fluctuate", "मानसिक शान्तिमा उतारचढाव"),
    SADE_SATI_FOURTH_MOTHER("Mother's health may need attention", "आमाको स्वास्थ्यमा ध्यान आवश्यक"),
    SADE_SATI_FOURTH_PROPERTY("Property matters require caution", "सम्पत्ति मामिलाहरूमा सावधानी आवश्यक"),
    SADE_SATI_FOURTH_TRANSIT("Saturn is transiting the 4th house from your Moon.", "शनि तपाईंको चन्द्रबाट ४औं भावमा गोचर गर्दैछ।"),
    SADE_SATI_MOON_SIGN("Natal Moon Sign", "जन्म चन्द्र राशि"),
    SADE_SATI_NOT_ACTIVE("Sade Sati is not currently active", "साढेसाती हाल सक्रिय छैन"),
    SADE_SATI_NOT_ACTIVE_DESC(
        "Saturn is currently transiting %s, which does not form Sade Sati or Small Panoti with your natal Moon in %s.",
        "शनि हाल %s मा गोचर गर्दैछ, जसले तपाईंको जन्म चन्द्र %s सँग साढ़े साती वा सानो पनोती बनाउँदैन।"
    ),
    SADE_SATI_NOT_ACTIVE_HEADER("SADE SATI NOT ACTIVE", "साढ़े साती सक्रिय छैन"),
    SADE_SATI_PEAK("Peak Phase", "शिखर चरण"),
    SADE_SATI_PEAK_DESC("Saturn transiting over natal Moon - Most intense phase", "शनि जन्म चन्द्रमाथि गोचर - सबैभन्दा तीव्र चरण"),
    SADE_SATI_PEAK_HEADER("PEAK PHASE CHARACTERISTICS:", "शिखर चरण विशेषताहरू:"),
    SADE_SATI_PEAK_HEALTH("Health may need attention", "स्वास्थ्यमा ध्यान आवश्यक हुन सक्छ"),
    SADE_SATI_PEAK_INTENSE("Most intense phase of Sade Sati", "साढ़े साती को सबैभन्दा तीव्र चरण"),
    SADE_SATI_PEAK_MIND("Direct impact on mind and emotions", "मन र भावनाहरूमा प्रत्यक्ष प्रभाव"),
    SADE_SATI_PEAK_RESTRUCTURE("Major life restructuring possible", "प्रमुख जीवन पुनर्संरचना सम्भव"),
    SADE_SATI_PEAK_SELF("Self-image transformation", "आत्म-छवि रूपान्तरण"),
    SADE_SATI_PHASE("Sade Sati Phase", "साढे साती चरण"),
    SADE_SATI_PHASE_PEAK("Peak Phase", "शिखर चरण"),
    SADE_SATI_PHASE_RISING("Rising Phase", "उदय चरण"),
    SADE_SATI_PHASE_SETTING("Setting Phase", "अस्त चरण"),
    SADE_SATI_PROGRESS("Progress in Phase", "चरणमा प्रगति"),
    SADE_SATI_REMEDIES("Sade Sati Remedies", "साढे साती उपचारहरू"),
    SADE_SATI_RISING("Rising Phase", "उदय चरण"),
    SADE_SATI_RISING_BEGIN("Beginning of Sade Sati period", "साढ़े साती अवधिको सुरुवात"),
    SADE_SATI_RISING_DESC("Saturn transiting 12th from Moon - Beginning of Sade Sati", "शनि चन्द्रबाट १२औं राशिमा गोचर - साढेसातीको शुरुआत"),
    SADE_SATI_RISING_ENEMIES("Hidden enemies may become active", "लुकेका शत्रुहरू सक्रिय हुन सक्छन्"),
    SADE_SATI_RISING_EXPENSES("Focus on expenses and losses (12th house)", "खर्च र हानिमा केन्द्रित (१२औं भाव)"),
    SADE_SATI_RISING_HEADER("RISING PHASE CHARACTERISTICS:", "उदय चरण विशेषताहरू:"),
    SADE_SATI_RISING_SLEEP("Sleep disturbances possible", "निद्रामा गडबडी सम्भव"),
    SADE_SATI_RISING_SPIRITUAL("Spiritual growth opportunities", "आध्यात्मिक वृद्धिका अवसरहरू"),
    SADE_SATI_SAME_SIGN("same sign", "उही राशि"),
    SADE_SATI_SATURN_SIGN("Transit Saturn Sign", "गोचर शनि राशि"),
    SADE_SATI_SETTING("Setting Phase", "अस्त चरण"),
    SADE_SATI_SETTING_DESC("Saturn transiting 2nd from Moon - Final phase of Sade Sati", "शनि चन्द्रबाट २औं राशिमा गोचर - साढेसातीको अन्तिम चरण"),
    SADE_SATI_SETTING_FINAL("Final phase of Sade Sati", "साढ़े साती को अन्तिम चरण"),
    SADE_SATI_SETTING_FINANCES("Focus on finances and family (2nd house)", "वित्त र परिवारमा केन्द्रित (२औं भाव)"),
    SADE_SATI_SETTING_HEADER("SETTING PHASE CHARACTERISTICS:", "अस्त चरण विशेषताहरू:"),
    SADE_SATI_SETTING_LESSONS("Integration of lessons learned", "सिकेका पाठहरूको एकीकरण"),
    SADE_SATI_SETTING_SPEECH("Speech and communication impacted", "वाणी र संचार प्रभावित"),
    SADE_SATI_SETTING_WEALTH("Accumulated wealth may fluctuate", "संचित सम्पत्तिमा उतारचढाव"),
    SADE_SATI_SMALL_PANOTI_HEADER("SMALL PANOTI (DHAIYA) ACTIVE", "सानो पनोती (ढैया) सक्रिय"),
    SADE_SATI_SUBTITLE("Saturn's 7.5 Year Transit", "शनिको ७.५ वर्षे गोचर"),
    SADE_SATI_TIMING_EVERY_SATURDAY("Every Saturday", "हरेक शनिबार"),
    SADE_SATI_TIMING_SATURN_HORA("Saturday during Saturn Hora", "शनि होरामा शनिबार"),
    SADE_SATI_TIMING_TUE_SAT("Tuesday and Saturday", "मंगलबार र शनिबार"),
    SADE_SATI_TITLE("Sade Sati Analysis", "साढेसाती विश्लेषण"),
    SADE_SATI_TRANSIT_DESC(
        "Saturn is currently transiting %s, which is the %s from your natal Moon in %s.",
        "शनि हाल %s मा गोचर गर्दैछ, जुन तपाईंको जन्म चन्द्र %s बाट %s हो।"
    )
}
