package com.astro.storm.core.common
enum class StringKeyDasha(override val en: String, override val ne: String) : StringKeyInterface {
SANDHI_TITLE("Dasha Sandhi Analysis", "दशा सन्धि विश्लेषण"),
SANDHI_SUBTITLE("Period Junction Analysis", "अवधि जोड विश्लेषण"),
SANDHI_CURRENT("Current Sandhi", "वर्तमान सन्धि"),
SANDHI_UPCOMING("Upcoming Sandhis", "आगामी सन्धिहरू"),
SANDHI_RECENT("Recent Sandhis", "हालैका सन्धिहरू"),
SANDHI_CALENDAR("Sandhi Calendar", "सन्धि क्यालेन्डर"),
SANDHI_VOLATILITY("Volatility Score", "अस्थिरता स्कोर"),
SANDHI_TRANSITION("Transition", "संक्रमण"),
SANDHI_FROM_PLANET("From", "बाट"),
SANDHI_TO_PLANET("To", "मा"),
SANDHI_DAYS_UNTIL("Days Until Transition", "संक्रमणसम्म दिन"),
SANDHI_PROGRESS("Sandhi Progress", "सन्धि प्रगति"),
SANDHI_KEY_DATES("Key Dates", "मुख्य मितिहरू"),
SANDHI_PREDICTIONS("Predictions", "भविष्यवाणीहरू"),
SANDHI_CAREER_EFFECTS("Career Effects", "क्यारियर प्रभावहरू"),
SANDHI_HEALTH_CONCERNS("Health Considerations", "स्वास्थ्य विचारणाहरू"),
SANDHI_RELATIONSHIP_IMPACT("Relationship Impact", "सम्बन्ध प्रभाव"),
SANDHI_FINANCIAL_TREND("Financial Trend", "आर्थिक प्रवृत्ति"),
SANDHI_SPIRITUAL("Spiritual Opportunities", "आध्यात्मिक अवसरहरू"),
SANDHI_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
SANDHI_GENERAL_GUIDANCE("General Guidance", "सामान्य मार्गदर्शन"),
SANDHI_INTENSITY_CRITICAL("Critical", "गम्भीर"),
SANDHI_INTENSITY_HIGH("High", "उच्च"),
SANDHI_INTENSITY_MODERATE("Moderate", "मध्यम"),
SANDHI_INTENSITY_MILD("Mild", "हल्का"),
SANDHI_INTENSITY_MINIMAL("Minimal", "न्यूनतम"),
SANDHI_SCREEN_TITLE("Dasha Sandhi", "दशा सन्धि"),
SANDHI_ABOUT_TITLE("About Dasha Sandhi", "दशा सन्धिको बारेमा"),
    SANDHI_ABOUT_DESC("Dasha Sandhi refers to the junction or transition point between two planetary periods (Dashas)", "Dasha Sandhi refers to the junction or transition point between two planetary periods (Dashas)"),
SANDHI_VOLATILITY_DESC("Based on current and upcoming period transitions", "वर्तमान र आगामी दशा परिवर्तनहरूमा आधारित"),
SANDHI_ACTIVE("Active", "सक्रिय"),
SANDHI_GUIDANCE("General Guidance", "सामान्य मार्गदर्शन"),
SANDHI_CURRENT_ACTIVE("Currently in Sandhi Period", "वर्तमानमा सन्धि अवधिमा"),
SANDHI_INTENSITY("Intensity:", "तीव्रता:"),
SANDHI_ENDS("Ends:", "अन्त्य:"),
SANDHI_NO_ACTIVE("No Active Sandhi", "कुनै सक्रिय सन्धि छैन"),
SANDHI_NO_ACTIVE_DESC("You are not currently in a Dasha Sandhi period. Check the Upcoming tab for future transitions.", "तपाईं हाल दशा सन्धि अवधिमा हुनुहुन्न। भविष्यका परिवर्तनहरूको लागि आगामी ट्याब जाँच गर्नुहोस्।"),
SANDHI_IMPACTS("Life Area Impacts", "जीवन क्षेत्र प्रभावहरू"),
SANDHI_REMEDIES("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
SANDHI_NO_CHART_DESC("Create or select a birth chart to analyze Dasha Sandhi periods.", "दशा सन्धि अवधिहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
SANDHI_NO_UPCOMING("No upcoming Sandhi periods in the analysis window.", "विश्लेषण अवधिमा कुनै आगामी सन्धि अवधिहरू छैनन्।"),
SANDHI_NO_CALENDAR("No calendar entries available.", "कुनै पात्रो प्रविष्टिहरू उपलब्ध छैनन्।")
}
