package com.astro.storm.core.common

/**
 * String keys for Saptamsa (D7) Progeny Analysis
 */
enum class StringKeySaptamsa(override val en: String, override val ne: String, override val hi: String) : StringKeyInterface {
    TITLE("Saptamsa (D7)", "सप्तांश (D7)", "सप्तांश (D7)"),
    SUBTITLE("Children & Progeny Analysis", "सन्तान र प्रजनन विश्लेषण", "संतान और प्रजनन विश्लेषण"),
    
    TAB_OVERVIEW("Overview", "अवलोकन", "अवलोकन"),
    TAB_CHILDREN("Children", "सन्तान", "संतान"),
    TAB_FERTILITY("Fertility", "प्रजनन क्षमता", "प्रजनन क्षमता"),
    TAB_YOGAS("Yogas", "योगहरू", "योग"),
    
    INTERPRETATION("Interpretation", "व्याख्या", "व्याख्या"),
    ESTIMATED_CHILDREN("Estimated Children", "अनुमानित सन्तान", "अनुमानित संतान"),
    CHILD("child", "सन्तान", "संतान"),
    CHILDREN("children", "सन्तानहरू", "संतानहरू"),
    RANGE("Range: %d - %d", "दायरा: %d - %d", "दायरा: %d - %d"),
    
    FIFTH_HOUSE("Fifth House", "पाँचौं भाव", "पाँचौं भाव"),
    JUPITER("Jupiter", "बृहस्पति", "बृहस्पति"),
    
    D7_LAGNA_TITLE("D7 Lagna (Saptamsa Ascendant)", "D7 लग्न (सप्तांश लग्न)", "D7 लग्न (सप्तांश लग्न)"),
    LAGNA_LORD("Lagna Lord", "लग्न स्वामी", "लग्न स्वामी"),
    LORD_POSITION("Lord Position", "स्वामीको स्थिति", "स्वामीको स्थिति"),
    
    FIFTH_HOUSE_ANALYSIS("Fifth House Analysis", "पाँचौं भाव विश्लेषण", "पाँचौं भाव विश्लेषण"),
    SIGN("Sign", "राशि", "राशि"),
    LORD("Lord", "स्वामी", "स्वामी"),
    PLANETS_IN_FIFTH("Planets in Fifth House", "पाँचौं भावमा रहेका ग्रहहरू", "पाँचौं भावमा रहेका ग्रह"),
    
    INDIVIDUAL_CHILD_INDICATIONS("Individual Child Indications", "व्यक्तिगत सन्तान संकेतहरू", "व्यक्तिगत संतान संकेतहरू"),
    CHILD_CHARACTERISTICS_DESC("Detailed analysis of each child's potential characteristics", "प्रत्येक सन्तानको सम्भावित विशेषताहरूको विस्तृत विश्लेषण", "प्रत्येक संतानको सम्भावित विशेषताहरूको विस्तृत विश्लेषण"),
    EMPTY_CHILD_INDICATIONS("No specific child indications available", "कुनै विशिष्ट सन्तान संकेतहरू उपलब्ध छैनन्", "कुनै विशिष्ट संतान संकेतहरू उपलब्ध छैनन्"),
    
    CHILD_NUMBER("Child #%d", "सन्तान #%d", "संतान #%d"),
    SIGNIFICATOR("Significator", "कारक", "कारक"),
    RELATIONSHIP("Relationship", "सम्बन्ध", "संबंध"),
    CHARACTERISTICS_LABEL("Characteristics:", "विशेषताहरू:", "विशेषताहरू:"),
    
    TIMING_INDICATORS("Timing Indicators", "समय संकेतहरू", "समय संकेतहरू"),
    TIMING_SUBTITLE("Periods related to this child's arrival", "यस सन्तानको आगमनसँग सम्बन्धित अवधिहरू", "यस संतानको आगमनसँग संबंधित अवधिहरू"),
    
    CAREER_INDICATIONS("Career Indications", "क्यारियर संकेतहरू", "क्यारियर संकेतहरू"),
    CAREER_SUBTITLE("Potential career paths or talents", "सम्भावित क्यारियर मार्ग वा प्रतिभा", "सम्भावित क्यारियर मार्ग या प्रतिभा"),
    
    HEALTH_INDICATIONS("Health Indications", "स्वास्थ्य संकेतहरू", "स्वास्थ्य संकेतहरू"),
    HEALTH_SUBTITLE("Potential health considerations", "सम्भावित स्वास्थ्य विचारहरू", "सम्भावित स्वास्थ्य विचारहरू"),
    
    FERTILITY_ANALYSIS("Fertility Analysis", "प्रजनन विश्लेषण", "प्रजनन विश्लेषण"),
    FERTILITY_SUBTITLE("Assessment of conception and childbirth prospects", "गर्भाधान र प्रसव सम्भावनाको मूल्याङ्कन", "गर्भाधान और प्रसव सम्भावनाको मूल्यांकन"),
    OVERALL_FERTILITY_SCORE("Overall Fertility Score", "समग्र प्रजनन स्कोर", "समग्र प्रजनन स्कोर"),
    FAVORABLE_PERIODS("Favorable Periods", "अनुकूल अवधिहरू", "अनुकूल अवधिहरू"),
    
    RECOMMENDATIONS("Recommendations", "सिफारिसहरू", "सिफारिसहरू"),
    
    SANTHANA_YOGAS("Santhana Yogas", "सन्तान योगहरू", "संतान योग"),
    SANTHANA_YOGAS_SUBTITLE("Positive combinations for children", "सन्तानका लागि सकारात्मक संयोजनहरू", "संतानका लिए सकारात्मक संयोजनहरू"),
    EMPTY_SANTHANA_YOGAS("No Santhana Yogas detected", "कुनै सन्तान योग फेला परेन", "कुनै संतान योग फेला परेन"),
    
    CHALLENGING_YOGAS("Challenging Yogas", "चुनौतीपूर्ण योगहरू", "चुनौतीपूर्ण योग"),
    CHALLENGING_YOGAS_SUBTITLE("Factors requiring attention", "ध्यान दिनुपर्ने कारकहरू", "ध्यान दिनुपर्ने कारकहरू"),
    
    YOGA_STRENGTH("Strength: %d%%", "बल: %d%%", "बल: %d%%"),
    YOGA_POSITIVE("Positive", "सकारात्मक", "सकारात्मक"),
    YOGA_CAUTION("Caution", "सावधानी", "सावधानी"),
    
    ANALYZING_SAPTAMSA("Analyzing Saptamsa (D7)...", "सप्तांश (D7) विश्लेषण गर्दै...", "सप्तांश (D7) विश्लेषण गर्दै..."),
    NO_CHART_AVAILABLE("No chart available", "कुनै कुण्डली उपलब्ध छैन", "कुनै कुंडली उपलब्ध छैन"),
    ERROR_ANALYZING("Error analyzing Saptamsa", "सप्तांश विश्लेषणमा त्रुटि", "सप्तांश विश्लेषणमा त्रुटि"),

    // Analyzer strings
    KARAKA_JUPITER("Putrakaraka (Primary significator of children)", "पुत्रकारक (सन्तानको मुख्य कारक)", "पुत्रकारक (संतानको मुख्य कारक)"),
    KARAKA_MOON("Nourishment and emotional connection with children", "पोषण र सन्तानसँग भावनात्मक सम्बन्ध", "पोषण और संतानसँग भावनात्मक संबंध"),
    KARAKA_VENUS("Fertility and creative expression", "प्रजनन क्षमता र रचनात्मक अभिव्यक्ति", "प्रजनन क्षमता और रचनात्मक अभिव्यक्ति"),
    KARAKA_MERCURY("Education and communication with children", "शिक्षा र सन्तानसँग सञ्चार", "शिक्षा और संतानसँग सञ्चार"),
    KARAKA_SUN("Father, authority over children", "पिता, सन्तानमाथि अधिकार", "पिता, संतानमाथि अधिकार"),
    KARAKA_MARS("Courage and protection of children", "साहस र सन्तानको सुरक्षा", "साहस और संतानको सुरक्षा"),
    KARAKA_SATURN("Discipline and karmic children", "अनुशासन र कार्मिक सन्तान", "अनुशासन और कार्मिक संतान"),
    KARAKA_RAHU("Unconventional or adopted children", "अपरम्परागत वा धर्मपुत्र/पुत्री", "अपरम्परागत या धर्मपुत्र/पुत्री"),
    KARAKA_KETU("Spiritual children, past-life connections", "आध्यात्मिक सन्तान, पूर्व-जन्म सम्बन्ध", "आध्यात्मिक संतान, पूर्व-जन्म संबंध"),

    GENDER_MALE("Male", "पुरुष", "पुरुष"),
    GENDER_FEMALE("Female", "महिला", "महिला"),
    GENDER_UNCERTAIN("Uncertain", "अनिश्चित", "अनिश्चित"),

    QUAL_EXCELLENT("Excellent", "उत्कृष्ट", "उत्कृष्ट"),
    QUAL_GOOD("Good", "राम्रो", "राम्रो"),
    QUAL_MODERATE("Moderate", "मध्यम", "मध्यम"),
    QUAL_CHALLENGING("Challenging", "चुनौतीपूर्ण", "चुनौतीपूर्ण"),
    QUAL_DIFFICULT("Difficult", "कठिन", "कठिन"),

    STATUS_HIGHLY_FAVORABLE("Highly Favorable", "अत्यन्त अनुकूल", "अत्यन्त अनुकूल"),
    STATUS_FAVORABLE("Favorable", "अनुकूल", "अनुकूल"),
    STATUS_MODERATE("Moderate", "मध्यम", "मध्यम"),
    STATUS_CHALLENGING("Challenging", "चुनौतीपूर्ण", "चुनौतीपूर्ण"),
    STATUS_NEEDS_ATTENTION("Needs Special Attention", "विशेष ध्यान आवश्यक", "विशेष ध्यान आवश्यक"),

    FACTOR_STRONG_JUPITER("Strong Jupiter increases progeny potential", "बलियो बृहस्पतिले सन्तानको सम्भावना बढाउँछ", "बलियो बृहस्पतिले संतानको सम्भावना बढाउँछ"),
    FACTOR_BENEFIC_5TH("Benefic influence on 5th house is favorable", "पाँचौं भावमा शुभ प्रभाव अनुकूल हुन्छ", "पाँचौं भावमा शुभ प्रभाव अनुकूल हुन्छ"),
    FACTOR_MALEFIC_5TH("Malefic influence may reduce or delay children", "अशुभ प्रभावले सन्तान घटाउन वा ढिलो गर्न सक्छ", "अशुभ प्रभावले संतान घटाउन या ढिलो गर्न सक्छ"),
    
    FERTILITY_JUP_STRONG("Strong Jupiter supports fertility", "बलियो बृहस्पतिले प्रजनन क्षमतालाई समर्थन गर्दछ", "बलियो बृहस्पतिले प्रजनन क्षमता को समर्थन गर्दछ"),
    FERTILITY_JUP_WEAK("Weak Jupiter may affect fertility", "कमजोर बृहस्पतिले प्रजनन क्षमतालाई असर गर्न सक्छ", "कमजोर बृहस्पतिले प्रजनन क्षमता को असर गर्न सक्छ"),
    FERTILITY_BENEFIC_5TH("Benefic planets in 5th house support conception", "पाँचौं भावमा रहेका शुभ ग्रहहरूले गर्भाधानलाई समर्थन गर्दछन्", "पाँचौं भावमा रहेका शुभ ग्रहले गर्भाधान को समर्थन गर्दछन्"),
    FERTILITY_MALEFIC_5TH("Multiple malefics in 5th may delay children", "पाँचौं भावमा धेरै अशुभ ग्रहहरूले सन्तानमा ढिलाइ गर्न सक्छन्", "पाँचौं भावमा धेरै अशुभ ग्रहले संतानमा ढिलाइ गर्न सक्छन्"),
    FERTILITY_MOON_STRONG("Strong Moon supports reproductive health", "बलियो चन्द्रमाले प्रजनन स्वास्थ्यलाई समर्थन गर्दछ", "बलियो चन्द्रमाले प्रजनन स्वास्थ्य को समर्थन गर्दछ"),
    FERTILITY_MOON_WEAK("Debilitated Moon may need attention", "नीच चन्द्रमालाई ध्यान दिनुपर्ने हुन सक्छ", "नीच चन्द्रमा को ध्यान दिनुपर्ने हुन सक्छ"),
    FERTILITY_VENUS_FAV("Venus in favorable house supports fertility", "अनुकूल भावमा रहेको शुक्रले प्रजनन क्षमतालाई समर्थन गर्दछ", "अनुकूल भावमा रहेको शुक्रले प्रजनन क्षमता को समर्थन गर्दछ"),
    FERTILITY_VENUS_RETRO("Retrograde Venus may indicate timing issues", "वक्री शुक्रले समय सम्बन्धी समस्याहरू संकेत गर्न सक्छ", "वक्री शुक्रले समय संबंधी समस्याहरू संकेत गर्न सक्छ"),

    YOGA_GURU_NAME("Guru Yoga for Progeny", "सन्तानको लागि गुरु योग", "संतानको लिए गुरु योग"),
    YOGA_GURU_SANSKRIT("Guru Santhana Yoga", "गुरु सन्तान योग", "गुरु संतान योग"),
    YOGA_GURU_EFFECT("Jupiter in Kendra/Trikona blesses with children", "केन्द्र/त्रिकोणमा रहेको बृहस्पतिले सन्तानको आशीर्वाद दिन्छ", "केन्द्र/त्रिकोणमा रहेको बृहस्पतिले संतानको आशीर्वाद दिन्छ"),
    
    YOGA_5TH_LORD_NAME("Strong Fifth Lord Yoga", "बलियो पञ्चमेश योग", "बलियो पञ्चमेश योग"),
    YOGA_5TH_LORD_SANSKRIT("Putrabhava Adhipati Yoga", "पुत्रभाव अधिपति योग", "पुत्रभाव अधिपति योग"),
    YOGA_5TH_LORD_EFFECT("Fifth lord in strength ensures progeny happiness", "बलियो पञ्चमेशले सन्तान सुख सुनिश्चित गर्दछ", "बलियो पञ्चमेशले संतान सुख सुनिश्चित गर्दछ"),
    
    YOGA_GAJA_KESARI_NAME("Gaja Kesari for Children", "सन्तानका लागि गजकेसरी", "संतानका लिए गजकेसरी"),
    YOGA_GAJA_KESARI_SANSKRIT("Putra Gaja Kesari", "पुत्र गजकेसरी", "पुत्र गजकेसरी"),
    YOGA_GAJA_KESARI_EFFECT("Jupiter-Moon relationship blesses with intelligent children", "बृहस्पति-चन्द्र सम्बन्धले बुद्धिमान सन्तानको आशीर्वाद दिन्छ", "बृहस्पति-चन्द्र संबंधले बुद्धिमान संतानको आशीर्वाद दिन्छ"),
    
    YOGA_VEN_JUP_NAME("Venus-Jupiter Santhana Yoga", "शुक्र-गुरु सन्तान योग", "शुक्र-गुरु संतान योग"),
    YOGA_VEN_JUP_SANSKRIT("Shukra-Guru Santhana Yoga", "शुक्र-गुरु सन्तान योग", "शुक्र-गुरु संतान योग"),
    YOGA_VEN_JUP_EFFECT("Artistic and prosperous children", "कलात्मक र समृद्ध सन्तान", "कलात्मक और समृद्ध संतान"),

    CHALLENGE_SATURN_5TH("Saturn in 5th without benefic aspect may delay children", "शुभ दृष्टि बिना पाँचौं भावमा रहेको शनिले सन्तानमा ढिलाइ गर्न सक्छ", "शुभ दृष्टि बिना पाँचौं भावमा रहेको शनिले संतानमा ढिलाइ गर्न सक्छ"),
    CHALLENGE_RAHU_5TH("Rahu in 5th may indicate unconventional paths to parenthood", "पाँचौं भावमा रहेको राहुले अभिभावकत्वको अपरम्परागत मार्गहरू संकेत गर्न सक्छ", "पाँचौं भावमा रहेको राहुले अभिभावकत्वको अपरम्परागत मार्गहरू संकेत गर्न सक्छ"),
    CHALLENGE_KETU_5TH("Ketu in 5th may indicate past-life karma related to children", "पाँचौं भावमा रहेको केतुले सन्तानसँग सम्बन्धित पूर्व-जन्मको कर्म संकेत गर्न सक्छ", "पाँचौं भावमा रहेको केतुले संतानसँग संबंधित पूर्व-जन्मको कर्म संकेत गर्न सक्छ"),
    CHALLENGE_JUP_COMBUST("Combust Jupiter weakens progeny significations", "अस्त बृहस्पतिले सन्तान कारकत्वलाई कमजोर बनाउँछ", "अस्त बृहस्पतिले संतान कारकत्व को कमजोर बनाउँछ"),
    CHALLENGE_5TH_LORD_DUSTHANA("Fifth lord in dusthana (6th/8th/12th) may create obstacles", "पञ्चमेश दुःस्थान (६/८/१२) मा हुनाले बाधाहरू सिर्जना गर्न सक्छ", "पञ्चमेश दुःस्थान (६/८/१२) मा हुनाले बाधाहरू सिर्जना गर्न सक्छ"),

    TRAIT_CONFIDENT("Confident and authoritative", "आत्मविश्वासी र अधिकारपूर्ण", "आत्मविश्वासी और अधिकारपूर्ण"),
    TRAIT_LEADERSHIP("Natural leadership qualities", "प्राकृतिक नेतृत्व गुणहरू", "प्राकृतिक नेतृत्व गुणहरू"),
    TRAIT_WILLPOWER("Strong willpower", "बलियो इच्छाशक्ति", "बलियो इच्छाशक्ति"),
    TRAIT_SENSITIVE("Emotionally sensitive", "भावनात्मक रूपमा संवेदनशील", "भावनात्मक रूपमा संवेदनशील"),
    TRAIT_NURTURING("Nurturing nature", "पालनपोषण गर्ने स्वभाव", "पालनपोषण गर्ने स्वभाव"),
    TRAIT_INTUITIVE("Intuitive and caring", "अन्तर्ज्ञानी र दयालु", "अन्तर्ज्ञानी और दयालु"),
    TRAIT_ENERGETIC("Energetic and active", "ऊर्जावान र सक्रिय", "ऊर्जावान और सक्रिय"),
    TRAIT_COMPETITIVE("Competitive spirit", "प्रतिस्पर्धी भावना", "प्रतिस्पर्धी भावना"),
    TRAIT_STRONG("Physically strong", "शारीरिक रूपमा बलियो", "शारीरिक रूपमा बलियो"),
    TRAIT_INTELLIGENT("Intelligent and communicative", "बुद्धिमान र मिलनसार", "बुद्धिमान और मिलनसार"),
    TRAIT_STUDIES("Good at studies", "अध्ययनमा राम्रो", "अध्ययनमा राम्रो"),
    TRAIT_LEARNER("Quick learner", "द्रुत सिक्ने", "द्रुत सिक्ने"),
    TRAIT_WISE("Wise and learned", "ज्ञानी र विद्वान", "ज्ञानी और विद्वान"),
    TRAIT_RIGHTEOUS("Righteous nature", "धर्मी स्वभाव", "धर्मी स्वभाव"),
    TRAIT_OPTIMISTIC("Optimistic outlook", "आशावादी दृष्टिकोण", "आशावादी दृष्टिकोण"),
    TRAIT_ARTISTIC("Artistic and creative", "कलात्मक र रचनात्मक", "कलात्मक और रचनात्मक"),
    TRAIT_CHARMING("Charming personality", "आकर्षक व्यक्तित्व", "आकर्षक व्यक्तित्व"),
    TRAIT_BEAUTY("Appreciation for beauty", "सौन्दर्यको कदर", "सौन्दर्यको कदर"),
    TRAIT_DISCIPLINED("Disciplined and hardworking", "अनुशासित र मेहनती", "अनुशासित और मेहनती"),
    TRAIT_MATURE("Mature for their age", "आफ्नो उमेरको लागि परिपक्व", "अपना उमेरको लिए परिपक्व"),
    TRAIT_RESPONSIBLE("Responsible nature", "जिम्मेवार स्वभाव", "जिम्मेवार स्वभाव"),
    TRAIT_UNCONVENTIONAL("Unconventional thinking", "अपरम्परागत सोच", "अपरम्परागत सोच"),
    TRAIT_AMBITIOUS("Ambitious nature", "महत्त्वाकांक्षी स्वभाव", "महत्त्वाकांक्षी स्वभाव"),
    TRAIT_INNOVATIVE("Innovative mind", "अभिनव दिमाग", "अभिनव दिमाग"),
    TRAIT_SPIRITUAL("Spiritually inclined", "आध्यात्मिक झुकाव", "आध्यात्मिक झुकाव"),
    TRAIT_DETACHED("Detached nature", "वैरागी स्वभाव", "वैरागी स्वभाव"),
    TRAIT_INTUITIVE_ABILITIES("Intuitive abilities", "अन्तर्ज्ञानी क्षमताहरू", "अन्तर्ज्ञानी क्षमताहरू"),

    HEALTH_HEART_BONE("Watch for heart and bone health", "मुटु र हड्डीको स्वास्थ्यमा ध्यान दिनुहोस्", "मुटु और हड्डीको स्वास्थ्यमा ध्यान दें"),
    HEALTH_EMOTIONAL("Emotional well-being important", "भावनात्मक कल्याण महत्त्वपूर्ण छ", "भावनात्मक कल्याण महत्त्वपूर्ण है"),
    HEALTH_INJURIES("Prone to injuries and inflammations", "चोटपटक र जलनको सम्भावना", "चोटपटक और जलनको सम्भावना"),
    HEALTH_NERVOUS("Nervous system health", "स्नायु प्रणालीको स्वास्थ्य", "स्नायु प्रणालीको स्वास्थ्य"),
    HEALTH_GENERAL("Generally good health, watch weight", "सामान्यतया राम्रो स्वास्थ्य, तौलमा ध्यान दिनुहोस्", "सामान्यतया राम्रो स्वास्थ्य, तौलमा ध्यान दें"),
    HEALTH_REPRODUCTIVE("Reproductive health, diabetes", "प्रजनन स्वास्थ्य, मधुमेह", "प्रजनन स्वास्थ्य, मधुमेह"),
    HEALTH_CHRONIC("Chronic conditions, bones", "पुरानो रोग, हड्डी", "पुरानो रोग, हड्डी"),
    HEALTH_UNUSUAL("Unusual health conditions", "असामान्य स्वास्थ्य अवस्थाहरू", "असामान्य स्वास्थ्य अवस्थाहरू"),
    HEALTH_MYSTERIOUS("Mysterious ailments", "रहस्यमय रोगहरू", "रहस्यमय रोगहरू"),

    CAREER_GOVT("Government, Medicine, Leadership", "सरकार, चिकित्सा, नेतृत्व", "सरकार, चिकित्सा, नेतृत्व"),
    CAREER_HOSPITALITY("Hospitality, Psychology, Public service", "आतिथ्य, मनोविज्ञान, सार्वजनिक सेवा", "आतिथ्य, मनोविज्ञान, सार्वजनिक सेवा"),
    CAREER_MILITARY("Military, Engineering, Sports", "सेना, इन्जिनियरिङ, खेलकुद", "सेना, इन्जिनियरिङ, खेलकुद"),
    CAREER_BUSINESS("Business, Writing, Teaching", "व्यापार, लेखन, शिक्षण", "व्यापार, लेखन, शिक्षण"),
    CAREER_EDUCATION("Education, Law, Finance", "शिक्षा, कानुन, वित्त", "शिक्षा, कानुन, वित्त"),
    CAREER_ARTS("Arts, Entertainment, Fashion", "कला, मनोरञ्जन, फेसन", "कला, मनोरञ्जन, फेसन"),
    CAREER_MINING("Engineering, Mining, Labor", "इन्जिनियरिङ, खानी, श्रम", "इन्जिनियरिङ, खानी, श्रम"),
    CAREER_TECH("Technology, Foreign, Politics", "प्रविधि, विदेशी, राजनीति", "प्रविधि, विदेशी, राजनीति"),
    CAREER_RESEARCH("Research, Spiritual, Healing", "अनुसन्धान, आध्यात्मिक, उपचार", "अनुसन्धान, आध्यात्मिक, उपचार"),

    TIMING_DASHA("Birth likely during %s Dasha or Antardasha", "जन्म सम्भवतः %s दशा वा अन्तर्दशामा", "जन्म सम्भवतः %s दशा या अन्तर्दशामा"),
    TIMING_AGE("Age %s typically favorable", "आयु %s सामान्यतया अनुकूल छ", "आयु %s सामान्यतया अनुकूल है"),
    TIMING_JUPITER_TRANSIT("Check transit of Jupiter over 5th house", "पाँचौं भावमा बृहस्पतिको गोचर जाँच गर्नुहोस्", "पाँचौं भावमा बृहस्पतिको गोचर जाँच करें"),

    APPROACH_ENTHUSIASTIC("active and independent approach to parenting.", "अभिभावकत्वमा सक्रिय र स्वतन्त्र दृष्टिकोण।", "अभिभावकत्वमा सक्रिय और स्वतन्त्र दृष्टिकोण।"),
    APPROACH_STABLE("stable and nurturing approach to children.", "सन्तानप्रति स्थिर र पोषणपूर्ण दृष्टिकोण।", "संतानप्रति स्थिर और पोषणपूर्ण दृष्टिकोण।"),
    APPROACH_COMMUNICATIVE("communicative and educationally focused parenting.", "सञ्चारात्मक र शैक्षिक रूपमा केन्द्रित अभिभावकत्व।", "सञ्चारात्मक और शैक्षिक रूपमा केन्द्रित अभिभावकत्व।"),
    APPROACH_NURTURING("deeply nurturing and protective nature.", "गहिरो पोषण गर्ने र सुरक्षात्मक स्वभाव।", "गहिरो पोषण गर्ने और सुरक्षात्मक स्वभाव।"),
    APPROACH_PROUD("proud and generous with children.", "सन्तानसँग गर्विलो र उदार।", "संतानसँग गर्विलो और उदार।"),
    APPROACH_PRACTICAL("practical and health-conscious approach.", "व्यावहारिक र स्वास्थ्य-सचेत दृष्टिकोण।", "व्यावहारिक और स्वास्थ्य-सचेत दृष्टिकोण।"),
    APPROACH_BALANCED("balanced and fair parenting style.", "सन्तुलित र निष्पक्ष अभिभावकत्व शैली।", "सन्तुलित और निष्पक्ष अभिभावकत्व शैली।"),
    APPROACH_INTENSE("intense and transformative relationships.", "तीव्र र रूपान्तरणकारी सम्बन्धहरू।", "तीव्र और रूपान्तरणकारी संबंधहरू।"),
    APPROACH_PHILOSOPHICAL("philosophical and freedom-giving nature.", "दार्शनिक र स्वतन्त्रता दिने स्वभाव।", "दार्शनिक और स्वतन्त्रता दिने स्वभाव।"),
    APPROACH_DISCIPLINED("disciplined and responsible approach.", "अनुशासित र जिम्मेवार दृष्टिकोण।", "अनुशासित और जिम्मेवार दृष्टिकोण।"),
    APPROACH_UNCONVENTIONAL("unconventional and progressive parenting.", "अपरम्परागत र प्रगतिशील अभिभावकत्व।", "अपरम्परागत और प्रगतिशील अभिभावकत्व।"),
    APPROACH_COMPASSIONATE("compassionate and spiritual connection.", "दयालु र आध्यात्मिक सम्बन्ध।", "दयालु और आध्यात्मिक संबंध।"),

    PARENT_STYLE_ENTHUSIASTIC("Enthusiastic and encouraging", "उत्साही र उत्साहजनक", "उत्साही और उत्साहजनक"),
    PARENT_STYLE_PATIENT("Patient and providing material security", "धैर्यवान र भौतिक सुरक्षा प्रदान गर्ने", "धैर्यवान और भौतिक सुरक्षा प्रदान गर्ने"),
    PARENT_STYLE_INTELLECTUAL("Intellectual and communicative", "बौद्धिक र मिलनसार", "बौद्धिक और मिलनसार"),
    PARENT_STYLE_PROTECTIVE("Emotionally nurturing and protective", "भावनात्मक रूपमा पोषण गर्ने र सुरक्षात्मक", "भावनात्मक रूपमा पोषण गर्ने और सुरक्षात्मक"),
    PARENT_STYLE_CHARISMATIC("Proud and generous with recognition", "गर्विलो र मान्यतामा उदार", "गर्विलो और मान्यतामा उदार"),
    PARENT_STYLE_HEALTH_CONSCIOUS("Practical and health-focused", "व्यावहारिक र स्वास्थ्य-केन्द्रित", "व्यावहारिक और स्वास्थ्य-केन्द्रित"),
    PARENT_STYLE_BALANCED("Balanced and aesthetically oriented", "सन्तुलित र सौन्दर्यात्मक रूपमा उन्मुख", "सन्तुलित और सौन्दर्यात्मक रूपमा उन्मुख"),
    PARENT_STYLE_BONDED("Deeply bonded and transformative", "गहिरो रूपमा बाँधिएको र रूपान्तरणकारी", "गहिरो रूपमा बाँधिएको और रूपान्तरणकारी"),
    PARENT_STYLE_FREE("Philosophical and freedom-giving", "दार्शनिक र स्वतन्त्रता दिने", "दार्शनिक और स्वतन्त्रता दिने"),
    PARENT_STYLE_RESPONSIBLE("Disciplined and responsibility-focused", "अनुशासित र जिम्मेवारी-केन्द्रित", "अनुशासित और जिम्मेवारी-केन्द्रित"),
    PARENT_STYLE_SOCIAL("Unconventional and socially conscious", "अपरम्परागत र सामाजिक रूपमा सचेत", "अपरम्परागत और सामाजिक रूपमा सचेत"),
    PARENT_STYLE_SPIRITUAL("Compassionate and spiritually nurturing", "दयालु र आध्यात्मिक रूपमा पोषण गर्ने", "दयालु और आध्यात्मिक रूपमा पोषण गर्ने"),

    INSIGHT_LAGNA("D7 Lagna in %1\$s - %2\$s", "D7 लग्न %1\$s मा - %2\$s", "D7 लग्न %1\$s मा - %2\$s"),
    INSIGHT_STRONG_JUPITER("Strong Jupiter is excellent for progeny matters", "बलियो बृहस्पति सन्तान सम्बन्धी मामिलामा उत्कृष्ट हुन्छ", "बलियो बृहस्पति संतान संबंधी मामिलामा उत्कृष्ट हुन्छ"),
    INSIGHT_CHILD_ESTIMATE("Estimated %1\$d-%2\$d children based on chart factors", "कुण्डलीका कारकहरूका आधारमा अनुमानित %1\$d-%2\$d सन्तान", "कुंडलीका कारकहरूका आधारमा अनुमानित %1\$d-%2\$d संतान"),
    INSIGHT_YOGA_PRESENT("%1\$s present - %2\$s", "%1\$s उपस्थित - %2\$s", "%1\$s उपस्थित - %2\$s"),

    REC_STRENGTHEN_JUPITER("Strengthen Jupiter through Guru mantra jaap", "गुरु मन्त्र जप मार्फत बृहस्पतिलाई बलियो बनाउनुहोस्", "गुरु मन्त्र जप मार्फत बृहस्पति को बलियो बनाएं"),
    REC_ADDRESS_CHALLENGES("Address challenges through appropriate remedies", "उपयुक्त उपायहरू मार्फत चुनौतीहरूलाई सम्बोधन गर्नुहोस्", "उपयुक्त उपाय मार्फत चुनौतियां को सम्बोधन करें"),

    ERROR_DATA_UNAVAILABLE("D7 chart data unavailable, using Rasi chart reference", "D7 कुण्डली डाटा उपलब्ध छैन, राशि कुण्डली सन्दर्भ प्रयोग गर्दै", "D7 कुंडली डाटा उपलब्ध छैन, राशि कुंडली सन्दर्भ प्रयोग गर्दै"),
    ERROR_JUPITER_UNAVAILABLE("Jupiter position unavailable", "बृहस्पतिको स्थिति उपलब्ध छैन", "बृहस्पतिको स्थिति उपलब्ध छैन"),
    ERROR_NO_SPECIFIC_DESC("No specific description", "कुनै विशिष्ट विवरण छैन", "कुनै विशिष्ट विवरण छैन"),
    
    INTERP_FIFTH_HOUSE("Fifth house in %s. ", "%s मा पाँचौं भाव। ", "%s मा पाँचौं भाव।"),
    INTERP_OCCUPIED_BY("Occupied by %s. ", "%s द्वारा ओगटिएको। ", "%s द्वारा ओगटिएको।"),
    INTERP_ASPECTED_BY("Aspected by %s. ", "%s द्वारा दृष्ट। ", "%s द्वारा दृष्ट।"),
    INTERP_LORD_PLACED("Fifth lord %1\$s placed in house %2\$d.", "पञ्चमेश %1\$s भाव %2\$d मा स्थित छ।", "पञ्चमेश %1\$s भाव %2\$d मा स्थित है।"),
    
    INTERP_JUPITER_POS("Jupiter (Putrakaraka) is in %1\$s in house %2\$d. ", "बृहस्पति (पुत्रकारक) %1\$s को %2\$d भावमा छ। ", "बृहस्पति (पुत्रकारक) %1\$s को %2\$d भावमा छ।"),
    INTERP_DIGNITY("Dignity: %s. ", "मर्यादा: %s। ", "मर्यादा: %s।"),
    INTERP_RETROGRADE("Retrograde status may indicate delayed but karmic children. ", "वक्री स्थितिले ढिलो तर कार्मिक सन्तान संकेत गर्न सक्छ। ", "वक्री स्थितिले ढिलो तर कार्मिक संतान संकेत गर्न सक्छ।"),
    INTERP_COMBUST("Combustion weakens Jupiter's significations. ", "अस्त हुनाले बृहस्पतिको कारकत्व कमजोर हुन्छ। ", "अस्त हुनाले बृहस्पतिको कारकत्व कमजोर हुन्छ।"),
    INTERP_STRENGTH("Overall strength: %s%%. ", "समग्र बल: %s%%। ", "समग्र बल: %s%%।"),
    INTERP_PROGENY_EXCELLENT("Excellent for progeny matters.", "सन्तान सम्बन्धी मामिलामा उत्कृष्ट।", "संतान संबंधी मामिलामा उत्कृष्ट।"),
    INTERP_PROGENY_MODERATE("Moderate support for children.", "सन्तानका लागि मध्यम सहयोग।", "संतानका लिए मध्यम सहयोग।"),
    INTERP_PROGENY_ATTENTION("May need attention for progeny happiness.", "सन्तान सुखका लागि ध्यान दिनुपर्ने हुन सक्छ।", "संतान सुखका लिए ध्यान दिनुपर्ने हुन सक्छ।"),
    
    SUMMARY_HEADER("SAPTAMSA (D7) - PROGENY ANALYSIS", "सप्तांश (D7) - सन्तान विश्लेषण", "सप्तांश (D7) - संतान विश्लेषण"),
    SUMMARY_LAGNA("D7 Lagna: %s", "D7 लग्न: %s", "D7 लग्न: %s"),
    SUMMARY_FIFTH_HOUSE("Fifth House: %s", "पाँचौं भाव: %s", "पाँचौं भाव: %s"),
    SUMMARY_JUPITER_STRENGTH("Jupiter Strength: %s%%", "बृहस्पति बल: %s%%", "बृहस्पति बल: %s%%"),
    SUMMARY_FERTILITY_STATUS("Fertility Status: %s", "प्रजनन स्थिति: %s", "प्रजनन स्थिति: %s"),
    SUMMARY_ESTIMATED_CHILDREN("Estimated Children: %s", "अनुमानित सन्तान: %s", "अनुमानित संतान: %s"),
    SUMMARY_OVERALL_SCORE("Overall Score: %s%%", "समग्र स्कोर: %s%%", "समग्र स्कोर: %s%%"),
    SUMMARY_FAVORABLE_YOGAS("Favorable Yogas:", "अनुकूल योगहरू:", "अनुकूल योग:"),
    SUMMARY_CHALLENGES("Challenges:", "चुनौतीहरू:", "चुनौतियां:"),
}
