package com.astro.storm.core.common
enum class StringKeyYogaExpanded(override val en: String, override val ne: String) : StringKeyInterface {
YOGA_NATURE_AUSPICIOUS("Auspicious", "शुभ"),
YOGA_NATURE_INAUSPICIOUS("Inauspicious", "अशुभ"),
YOGA_NATURE_MIXED("Mixed", "मिश्र"),
YOGA_DEEP_ANALYSIS("Deep Vedic Analysis", "गहिरो वैदिक विश्लेषण"),
YOGA_VIEW_MORE("View More", "थप हेर्नुहोस्"),
YOGA_STATUS_FMT("Status: %s", "अवस्था: %s"),
YOGA_CANCELLATION_FMT("Cancellation: %d%%", "न्यूनीकरण: %d%%"),
YOGA_STRENGTH_FMT("Strength: %d%%", "बल: %d%%"),
YOGA_STRENGTH_LEVEL_FMT("Strength: %s", "बल: %s"),
YOGA_DIGNITY_EXALTED("Exalted", "उच्च"),
YOGA_DIGNITY_OWN_SIGN("Own Sign", "स्वराशि"),
YOGA_CAT_RAJA("Raja Yoga", "राज योग"),
YOGA_CAT_RAJA_DESC("Power, authority, and leadership combinations", "शक्ति, अधिकार र नेतृत्व संयोजनहरू"),
YOGA_CAT_DHANA("Dhana Yoga", "धन योग"),
YOGA_CAT_DHANA_DESC("Wealth and prosperity combinations", "धन र समृद्धि संयोजनहरू"),
YOGA_CAT_PANCHA_MAHAPURUSHA("Pancha Mahapurusha Yoga", "पञ्च महापुरुष योग"),
YOGA_CAT_PANCHA_MAHAPURUSHA_DESC("Five great person combinations", "पाँच महान व्यक्ति संयोजनहरू"),
YOGA_CAT_NABHASA("Nabhasa Yoga", "नाभस योग"),
YOGA_CAT_NABHASA_DESC("Pattern-based planetary combinations", "ढाँचामा आधारित ग्रह संयोजनहरू"),
YOGA_CAT_CHANDRA("Chandra Yoga", "चन्द्र योग"),
YOGA_CAT_CHANDRA_DESC("Moon-based combinations", "चन्द्रमामा आधारित संयोजनहरू"),
YOGA_CAT_SOLAR("Solar Yoga", "सूर्य योग"),
YOGA_CAT_SOLAR_DESC("Sun-based combinations", "सूर्यमा आधारित संयोजनहरू"),
YOGA_CAT_NEGATIVE("Negative Yoga", "नकारात्मक योग"),
YOGA_CAT_NEGATIVE_DESC("Challenging combinations", "चुनौतीपूर्ण संयोजनहरू"),
YOGA_CAT_SPECIAL("Special Yoga", "विशेष योग"),
YOGA_CAT_SPECIAL_DESC("Other significant combinations", "अन्य महत्त्वपूर्ण संयोजनहरू"),
YOGA_STRENGTH_EXTREMELY_STRONG("Extremely Strong", "अत्यन्त बलियो"),
YOGA_STRENGTH_STRONG("Strong", "बलियो"),
YOGA_STRENGTH_MODERATE("Moderate", "मध्यम"),
YOGA_STRENGTH_WEAK("Weak", "कमजोर"),
YOGA_STRENGTH_VERY_WEAK("Very Weak", "धेरै कमजोर"),
YOGA_KENDRA_TRIKONA("Kendra-Trikona Raja Yoga", "केन्द्र-त्रिकोण राज योग"),
YOGA_PARIVARTANA("Parivartana Raja Yoga", "परिवर्तन राज योग"),
YOGA_VIPARITA("Viparita Raja Yoga", "विपरीत राज योग"),
YOGA_NEECHA_BHANGA("Neecha Bhanga Raja Yoga", "नीच भंग राज योग"),
YOGA_MAHA_RAJA("Maha Raja Yoga", "महा राज योग"),
YOGA_LAKSHMI("Lakshmi Yoga", "लक्ष्मी योग"),
YOGA_KUBERA("Kubera Yoga", "कुबेर योग"),
YOGA_CHANDRA_MANGALA("Chandra-Mangala Yoga", "चन्द्र-मंगल योग"),
YOGA_LABHA("Labha Yoga", "लाभ योग"),
YOGA_RUCHAKA("Ruchaka Yoga", "रुचक योग"),
YOGA_BHADRA("Bhadra Yoga", "भद्र योग"),
YOGA_HAMSA("Hamsa Yoga", "हंस योग"),
YOGA_MALAVYA("Malavya Yoga", "मालव्य योग"),
YOGA_SASA("Sasa Yoga", "शश योग"),
YOGA_SUNAFA("Sunafa Yoga", "सुनफा योग"),
YOGA_ANAFA("Anafa Yoga", "अनफा योग"),
YOGA_DURUDHARA("Durudhara Yoga", "दुरुधरा योग"),
YOGA_GAJA_KESARI("Gaja-Kesari Yoga", "गज-केसरी योग"),
YOGA_ADHI("Adhi Yoga", "अधि योग"),
YOGA_VESI("Vesi Yoga", "वेशी योग"),
YOGA_VOSI("Vosi Yoga", "वोशी योग"),
YOGA_UBHAYACHARI("Ubhayachari Yoga", "उभयचारी योग"),
YOGA_KEMADRUMA("Kemadruma Yoga", "केमद्रुम योग"),
YOGA_DARIDRA("Daridra Yoga", "दरिद्र योग"),
YOGA_SHAKATA("Shakata Yoga", "शकट योग"),
YOGA_GURU_CHANDAL("Guru-Chandal Yoga", "गुरु-चांडाल योग"),
YOGA_BUDHA_ADITYA("Budha-Aditya Yoga", "बुध-आदित्य योग"),
YOGA_AMALA("Amala Yoga", "अमला योग"),
YOGA_SARASWATI("Saraswati Yoga", "सरस्वती योग"),
YOGA_PARVATA("Parvata Yoga", "पर्वत योग"),
YOGA_KAHALA("Kahala Yoga", "कहल योग"),
YOGA_YAVA("Yava Yoga", "यव योग"),
YOGA_SHRINGATAKA("Shringataka Yoga", "शृंगाटक योग"),
YOGA_GADA("Gada Yoga", "गदा योग"),
YOGA_RAJJU("Rajju Yoga", "रज्जु योग"),
YOGA_MUSALA("Musala Yoga", "मुसल योग"),
YOGA_NALA("Nala Yoga", "नल योग"),
YOGA_KEDARA("Kedara Yoga", "केदार योग"),
YOGA_SHOOLA("Shoola Yoga", "शूल योग"),
YOGA_YUGA("Yuga Yoga", "युग योग"),
YOGA_GOLA("Gola Yoga", "गोल योग"),
YOGA_VEENA("Veena Yoga", "वीणा योग"),
YOGA_DASA_MULA("Dasa-Mula Yoga", "दश-मूल योग"),
YOGA_VARGOTTAMA_STRENGTH("Vargottama Strength", "वर्गोत्तम बल"),
YOGA_MAHA_BHAGYA("Maha Bhagya Yoga", "महा भाग्य योग"),
YOGA_PUSHAKALA("Pushkala Yoga", "पुष्कल योग"),
YOGA_AKHANDA_SAMRAJYA("Akhanda Samrajya Yoga", "अखण्ड साम्राज्य योग"),
YOGA_VASUMATHI("Vasumathi Yoga", "वसुमथि योग"),
YOGA_MAHALAXMI("Mahalaxmi Yoga", "महालक्ष्मी योग"),
YOGA_PARIJATA("Parijata Yoga", "पारिजात योग"),
YOGA_KUSUMA("Kusuma Yoga", "कुसुम योग"),
YOGA_INDU_LAGNA("Indu Lagna Dhana Yoga", "इन्दु लग्न धन योग"),
YOGA_SAKATA("Sakata Yoga", "शकट योग"),
YOGA_KEMADRUMA_BHANGA("Kemadruma Bhanga", "केमद्रुम भंग"),
YOGA_SANKHYA_VALLAKI("Vallaki Sankhya Yoga", "वल्लकी साङ्ख्य योग"),
YOGA_SANKHYA_DAMINI("Damini Sankhya Yoga", "दामिनी साङ्ख्य योग"),
YOGA_SANKHYA_PASA("Pasa Sankhya Yoga", "पास साङ्ख्य योग"),
YOGA_SANKHYA_KEDARA("Kedara Sankhya Yoga", "केदार साङ्ख्य योग"),
YOGA_SANKHYA_SHOOLA("Shoola Sankhya Yoga", "शूल साङ्ख्य योग"),
YOGA_SANKHYA_YUGA("Yuga Sankhya Yoga", "युग साङ्ख्य योग"),
YOGA_SANKHYA_GOLA("Gola Sankhya Yoga", "गोल साङ्ख्य योग"),
YOGA_EFFECT_MAHA_BHAGYA("Exceptional fortune, leadership, magnetic personality, success from birth", "असाधारण भाग्य, नेतृत्व, आकर्षक व्यक्तित्व, जन्मदेखि नै सफलता"),
YOGA_EFFECT_PUSHAKALA("Wealthy, honored by rulers, famous, eloquent, good conduct", "धनी, शासकहरूद्वारा सम्मानित, प्रसिद्ध, वाक्पटु, राम्रो आचरण"),
YOGA_EFFECT_AKHANDA_SAMRAJYA("Undisputed leadership, wide-ranging influence, vast wealth and authority", "अविवादित नेतृत्व, व्यापक प्रभाव, विशाल धन र अधिकार"),
YOGA_EFFECT_VASUMATHI("Continuous accumulation of wealth, prosperity increasing with age, financial independence", "धनको निरन्तर सञ्चय, उमेरसँगै बढ्दो समृद्धि, आर्थिक स्वतन्त्रता"),
YOGA_EFFECT_MAHALAXMI("Divine grace of Goddess Lakshmi, immense wealth, religious nature, respected and virtuous", "देवी लक्ष्मीको दैवी कृपा, अपार धन, धार्मिक स्वभाव, सम्मानित र सद्गुणी"),
YOGA_EFFECT_PARIJATA("Success in middle and later life, steady rise to prominence, respected authority", "मध्य र पछिल्लो जीवनमा सफलता, प्रमुखतामा स्थिर उदय, सम्मानित अधिकार"),
YOGA_EFFECT_KUSUMA("Kingly status, famous, wealthy, enjoys life's pleasures, born in a good family", "राजकीय स्थिति, प्रसिद्ध, धनी, जीवनको आनन्द लिने, राम्रो परिवारमा जन्मिएको"),
YOGA_EFFECT_INDU_LAGNA("Special financial potential revealed through lunar rays, prosperity through specific life paths", "चन्द्र किरणहरू मार्फत प्रकट भएको विशेष आर्थिक सम्भावना, विशिष्ट जीवन मार्गहरू मार्फत समृद्धि"),
YOGA_EFFECT_SAKATA("Fluctuating fortunes, periods of struggle followed by recovery, lessons in resilience", "उतारचढावपूर्ण भाग्य, संघर्षको अवधि पछि सुधार, लचिलोपनमा पाठ"),
YOGA_EFFECT_KEMADRUMA_BHANGA("Protection from loneliness and poverty, internal strength to overcome initial lack", "एक्लोपन र गरिबीबाट सुरक्षा, प्रारम्भिक अभावलाई जित्न आन्तरिक शक्ति"),
YOGA_EFFECT_SANKHYA_VALLAKI("Artistic talents, fond of music and dance, happy disposition", "कलात्मक प्रतिभा, संगीत र नृत्यको शौकीन, खुसी स्वभाव"),
YOGA_EFFECT_SANKHYA_DAMINI("Charitable, famous, helpful to others, intelligent", "दानशील, प्रसिद्ध, अरूलाई मद्दत गर्ने, बुद्धिमान"),
YOGA_EFFECT_SANKHYA_PASA("Surrounded by friends and relatives, earns through proper means", "साथीभाइ र आफन्तहरूले घेरिएको, उचित माध्यमबाट कमाउने"),
YOGA_EFFECT_SANKHYA_KEDARA("Agricultural wealth, helpful, truthful, steady progress", "कृषि धन, सहयोगी, सत्यवादी, स्थिर प्रगति"),
YOGA_EFFECT_SANKHYA_SHOOLA("Brave but potentially aggressive, success through competition", "बहादुर तर सम्भावित आक्रामक, प्रतिस्पर्धा मार्फत सफलता"),
YOGA_EFFECT_SANKHYA_YUGA("Unconventional lifestyle, may face social challenges, religious or philosophical", "अपरम्परागत जीवनशैली, सामाजिक चुनौतीहरू सामना गर्न सक्ने, धार्मिक वा दार्शनिक"),
YOGA_EFFECT_SANKHYA_GOLA("Struggles in early life, need for persistence, unconventional path", "प्रारम्भिक जीवनमा संघर्ष, दृढताको आवश्यकता, अपरम्परागत मार्ग"),
YOGA_SURYA_GRAHAN("Surya Grahan Yoga", "सूर्य ग्रहण योग"),
YOGA_SURYA_KETU_GRAHAN("Surya-Ketu Grahan Yoga", "सूर्य-केतु ग्रहण योग"),
YOGA_CHANDRA_GRAHAN("Chandra Grahan Yoga", "चन्द्र ग्रहण योग"),
YOGA_CHANDRA_KETU("Chandra-Ketu Yoga", "चन्द्र-केतु योग"),
YOGA_ANGARAK("Angarak Yoga", "अङ्गारक योग"),
YOGA_SHRAPIT("Shrapit Yoga", "शापित योग"),
YOGA_KALA_SARPA("Kala Sarpa Yoga", "कालसर्प योग"),
YOGA_PAPAKARTARI("Papakartari Yoga", "पापकर्तरी योग"),
YOGA_SHUBHAKARTARI("Shubhakartari Yoga", "शुभकर्तरी योग"),
YOGA_SANYASA("Sanyasa Yoga", "सन्यास योग"),
YOGA_CHAMARA("Chamara Yoga", "चामर योग"),
YOGA_DHARMA_KARMADHIPATI("Dharma-Karmadhipati Yoga", "धर्म-कर्माधिपति योग"),
YOGA_EFFECT_SURYA_GRAHAN("Father-related troubles, ego issues, government problems, health issues with head/eyes", "पिता सम्बन्धी समस्याहरू, अहंकार समस्याहरू, सरकारी समस्याहरू, टाउको/आँखामा स्वास्थ्य समस्याहरू"),
YOGA_EFFECT_SURYA_KETU_GRAHAN("Spiritual detachment, low self-esteem, father troubles, past-life karmic issues", "आध्यात्मिक विरक्ति, कम आत्मसम्मान, पिता समस्याहरू, पूर्वजन्म कर्म समस्याहरू"),
YOGA_EFFECT_CHANDRA_GRAHAN("Mental restlessness, mother troubles, emotional instability, obsessive tendencies", "मानसिक अशान्ति, आमा समस्याहरू, भावनात्मक अस्थिरता, जुनूनी प्रवृत्तिहरू"),
YOGA_EFFECT_CHANDRA_KETU("Detachment from emotions, past-life memories, psychic sensitivity, mother karma", "भावनाहरूबाट विरक्ति, पूर्वजन्म स्मृतिहरू, मनोवैज्ञानिक संवेदनशीलता, आमा कर्म"),
YOGA_EFFECT_ANGARAK("Accidents, surgery, aggression, sibling troubles, litigation, sudden events", "दुर्घटनाहरू, शल्यक्रिया, आक्रामकता, भाइबहिनी समस्याहरू, मुद्दा, अचानक घटनाहरू"),
YOGA_EFFECT_SHRAPIT("Past-life karma manifesting as chronic obstacles, delays, fear, ancestral issues", "पूर्वजन्म कर्म दीर्घकालीन बाधाहरू, ढिलाइ, डर, पुर्खौली समस्याहरूको रूपमा प्रकट"),
YOGA_EFFECT_KALA_SARPA("Karmic life patterns, sudden ups and downs, spiritual transformation potential", "कर्मजन्य जीवन ढाँचाहरू, अचानक उतार-चढाव, आध्यात्मिक रूपान्तरण सम्भावना"),
YOGA_EFFECT_PAPAKARTARI("Obstacles in self-expression, health challenges, restricted opportunities", "आत्म-अभिव्यक्तिमा बाधाहरू, स्वास्थ्य चुनौतीहरू, सीमित अवसरहरू"),
YOGA_EFFECT_SHUBHAKARTARI("Protected life, good health, success in endeavors, helpful people around", "सुरक्षित जीवन, राम्रो स्वास्थ्य, प्रयासहरूमा सफलता, वरपर मद्दतगर्ने मानिसहरू"),
YOGA_EFFECT_SANYASA("Renunciation tendencies, spiritual inclinations, detachment from worldly matters", "त्याग प्रवृत्तिहरू, आध्यात्मिक झुकाव, सांसारिक कुराहरूबाट विरक्ति"),
YOGA_EFFECT_CHAMARA("Royal honors, fame, eloquence, learned, respected by rulers", "राजकीय सम्मान, प्रसिद्धि, वाक्पटुता, पढेलेखेको, शासकहरूद्वारा सम्मानित"),
YOGA_EFFECT_DHARMA_KARMADHIPATI("Highly successful career, fortune through profession, fame, authority positions", "अत्यन्त सफल करियर, पेशाबाट भाग्य, प्रसिद्धि, अधिकार पदहरू"),
YOGA_EFFECT_RUCHAKA("Commander, army chief, valorous, muscular body, red complexion, successful in conflicts, skilled in warfare, leader of thieves or soldiers, wealth through martial arts or defense", "सेनापति, सेना प्रमुख, वीर, बलियो शरीर, रातो रंग, द्वन्द्वमा सफल, युद्ध कलामा दक्ष, चोर वा सैनिकहरूको नेता, युद्ध कला वा रक्षाबाट धन"),
YOGA_EFFECT_BHADRA("Intelligent, eloquent speaker, skilled in arts and sciences, long-lived, wealthy through intellect, respected in assemblies, lion-like face, broad chest", "बुद्धिमान, वाक्पटु वक्ता, कला र विज्ञानमा दक्ष, दीर्घायु, बुद्धिबाट धनी, सभामा सम्मानित, सिंह जस्तो मुख, फराकिलो छाती"),
YOGA_EFFECT_HAMSA("Righteous king, fair complexion, elevated nose, beautiful face, devoted to gods and brahmins, fond of water sports, walks like a swan, respected by rulers, spiritual inclinations", "धार्मिक राजा, गोरो रंग, उठेको नाक, सुन्दर मुख, देवता र ब्राह्मणहरूप्रति भक्त, जल क्रीडाको शौकीन, हंस जस्तो हिँड्ने, शासकहरूद्वारा सम्मानित, आध्यात्मिक झुकाव"),
YOGA_EFFECT_MALAVYA("Wealthy, enjoys all comforts, beautiful spouse, strong limbs, attractive face, blessed with vehicles and servants, learned in scriptures, lives up to 77 years", "धनी, सबै सुविधा भोग्ने, सुन्दर पति/पत्नी, बलियो अंगहरू, आकर्षक मुख, वाहन र सेवकहरूले आशीर्वादित, शास्त्रमा पढेको, ७७ वर्षसम्म बाँच्ने"),
YOGA_EFFECT_SASA("Head of village/town/city, wicked disposition but good servants, intriguing nature, knows others' weaknesses, commands over masses, wealth through iron or labor", "गाउँ/शहर/नगरको प्रमुख, दुष्ट स्वभाव तर राम्रा सेवकहरू, षड्यन्त्रकारी स्वभाव, अरूको कमजोरी जान्ने, जनतामाथि आदेश, फलाम वा श्रमबाट धन"),
YOGA_EFFECT_GAJA_KESARI("Destroyer of enemies like lion, eloquent speaker, virtuous, long-lived, famous", "सिंह जस्तो शत्रु विनाशक, वाक्पटु वक्ता, सद्गुणी, दीर्घायु, प्रसिद्ध"),
YOGA_EFFECT_SUNAFA("Self-made wealth, intelligent, good status, praised by kings", "स्व-निर्मित धन, बुद्धिमान, राम्रो स्थिति, राजाहरूद्वारा प्रशंसित"),
YOGA_EFFECT_ANAFA("Good reputation, health, happiness, self-respect", "राम्रो प्रतिष्ठा, स्वास्थ्य, खुशी, आत्म-सम्मान"),
YOGA_EFFECT_DURUDHARA("Highly fortunate, wealthy, vehicles, servants, charitable, enjoys life", "अत्यधिक भाग्यशाली, धनी, वाहनहरू, सेवकहरू, दानशील, जीवनको आनन्द लिने"),
YOGA_EFFECT_ADHI("Commander, minister, or king; polite, trustworthy, healthy, wealthy, defeats enemies", "सेनापति, मन्त्री, वा राजा; विनम्र, विश्वसनीय, स्वस्थ, धनी, शत्रुहरूलाई हराउने"),
YOGA_EFFECT_BUDHA_ADITYA("Intelligence, skilled in many arts, famous, sweet speech, scholarly", "बुद्धि, धेरै कलाहरूमा दक्ष, प्रसिद्ध, मीठो बोली, विद्वान"),
YOGA_EFFECT_SARASWATI("Highly learned, poet, prose writer, famous speaker, skilled in all arts", "अत्यधिक पढेलेखेको, कवि, गद्य लेखक, प्रसिद्ध वक्ता, सबै कलाहरूमा दक्ष"),
YOGA_EFFECT_PARVATA("King or minister, famous, generous, wealthy, charitable, mountain-like stability", "राजा वा मन्त्री, प्रसिद्ध, उदार, धनी, दानशील, पहाड जस्तो स्थिरता"),
YOGA_EFFECT_LAKSHMI("Blessed by Goddess Lakshmi, abundant wealth, luxury, beauty, artistic success", "देवी लक्ष्मीको आशीर्वाद, प्रचुर धन, विलासिता, सौन्दर्य, कलात्मक सफलता"),
YOGA_EFFECT_MAHA_RAJA("Exceptional fortune, royal status, widespread fame, great wealth and power", "असाधारण भाग्य, राजकीय स्थिति, व्यापक प्रसिद्धि, ठूलो धन र शक्ति"),
YOGA_EFFECT_KENDRA_TRIKONA("Rise to power and authority, leadership position, recognition from government", "शक्ति र अधिकारमा उदय, नेतृत्व पद, सरकारबाट मान्यता"),
YOGA_EFFECT_PARIVARTANA("Strong Raja Yoga through mutual exchange, stable rise to power, lasting authority", "आपसी आदानप्रदानबाट बलियो राज योग, शक्तिमा स्थिर उदय, दिगो अधिकार"),
YOGA_EFFECT_VIPARITA("Rise through fall of enemies, sudden fortune from unexpected sources, gains through others' losses", "शत्रुहरूको पतनबाट उदय, अप्रत्याशित स्रोतहरूबाट अचानक भाग्य, अरूको हानिबाट लाभ"),
YOGA_EFFECT_NEECHA_BHANGA("Rise from humble beginnings, success after initial struggles, respected leader", "साधारण सुरुवातबाट उदय, प्रारम्भिक संघर्षपछि सफलता, सम्मानित नेता"),
YOGA_EFFECT_KEMADRUMA("Poverty, suffering, struggles, lack of support, lonely, menial work", "गरिबी, दुख, संघर्ष, समर्थनको अभाव, एक्लो, तल्लो काम"),
YOGA_EFFECT_KEMADRUMA_CANCELLED("Kemadruma effects significantly reduced due to cancellation factors", "रद्द कारकहरूको कारण केमद्रुम प्रभाव उल्लेखनीय रूपमा कम भयो"),
YOGA_EFFECT_DARIDRA("Obstacles to gains, financial struggles, unfulfilled desires", "लाभमा बाधाहरू, आर्थिक संघर्ष, अपूर्ण इच्छाहरू"),
YOGA_EFFECT_SHAKATA("Fluctuating fortune, periods of poverty alternating with wealth", "उतार-चढाव भाग्य, गरिबीको अवधि धनसँग पालैपालो"),
YOGA_EFFECT_GURU_CHANDAL("Unorthodox beliefs, breaks from tradition, possible disgrace through teachers/religion", "अपरम्परागत विश्वासहरू, परम्परा तोड्ने, गुरु/धर्मबाट सम्भावित अपमान"),
YOGA_EFFECT_VESI("Wealth through hard work, truthful, balanced life, comfortable old age", "मेहनतबाट धन, सत्यवादी, सन्तुलित जीवन, आरामदायक बुढेसकाल"),
YOGA_EFFECT_VOSI("Famous, generous, skilled in service, gains through associations", "प्रसिद्ध, उदार, सेवामा दक्ष, संगतबाट लाभ"),
YOGA_EFFECT_UBHAYACHARI("Eloquent speaker, wealthy, influential, respected by rulers", "वाक्पटु वक्ता, धनी, प्रभावशाली, शासकहरूद्वारा सम्मानित"),
YOGA_EFFECT_LABHA("Gains from multiple sources, profitable ventures, wealth accumulation", "विभिन्न स्रोतबाट लाभ, लाभदायक उद्यमहरू, धन संचय"),
YOGA_EFFECT_KUBERA("Immense wealth like lord of wealth, treasure finder, banking success", "धनको देवता जस्तो अपार धन, खजाना फेला पार्ने, बैंकिङमा सफलता"),
YOGA_EFFECT_CHANDRA_MANGALA("Wealth through business, enterprise, real estate, aggressive financial pursuits", "व्यापारबाट धन, उद्यम, घर जग्गा, आक्रामक आर्थिक प्रयासहरू"),
YOGA_EFFECT_DASA_MULA("Obstacles in undertakings, needs remedial measures, struggle with finances", "कार्यहरूमा बाधाहरू, उपचारात्मक उपायहरू आवश्यक, आर्थिक संघर्ष"),
YOGA_EFFECT_KAHALA("Brave but stubborn, military success, leadership through conflict", "बहादुर तर हठी, सैन्य सफलता, द्वन्द्वबाट नेतृत्व"),
YOGA_DESC_KENDRA_LORD("Kendra lord", "केन्द्र अधिपति"),
YOGA_DESC_TRIKONA_LORD("Trikona lord", "त्रिकोण अधिपति"),
YOGA_DESC_IN_CONJUNCTION("in conjunction", "संयोग मा"),
YOGA_DESC_IN_ASPECT("in aspect", "दृष्टि मा"),
YOGA_DESC_OWN_SIGN("own sign", "आफ्नो राशि"),
YOGA_DESC_EXALTED("exalted sign", "उच्च राशि"),
YOGA_DESC_IN_KENDRA("in Kendra", "केन्द्रमा"),
YOGA_DESC_DUSTHANA("Dusthana", "दुस्थान"),
YOGA_DESC_DEBILITATED("debilitated", "नीच"),
YOGA_DESC_COMBUST("combust", "अस्त"),
YOGA_EFFECT_YAVA("Medium wealth initially, prosperity in middle age, decline in old age", "सुरुमा मध्यम धन, मध्य उमेरमा समृद्धि, बुढेसकालमा पतन"),
YOGA_EFFECT_SHRINGATAKA("Fond of quarrels initially, happiness in middle age, wandering in old age", "सुरुमा झगडा मनपर्ने, मध्य उमेरमा खुशी, बुढेसकालमा भौंतारिने"),
YOGA_EFFECT_GADA("Wealthy through ceremonies, always engaged in auspicious activities", "संस्कारहरूबाट धनी, सधैं शुभ कार्यहरूमा संलग्न"),
YOGA_EFFECT_SHAKATA_NABHASA("Fluctuating fortune, poverty followed by wealth in cycles", "उतार-चढाव भाग्य, गरिबीपछि धन चक्रमा"),
YOGA_EFFECT_RAJJU("Fond of travel, living in foreign lands, restless nature", "यात्राको शौकीन, विदेशी भूमिमा बस्ने, अशान्त स्वभाव"),
YOGA_EFFECT_MUSALA("Proud, wealthy, learned, famous, many children", "गर्विलो, धनी, पढेलेखेको, प्रसिद्ध, धेरै सन्तान"),
YOGA_EFFECT_NALA("Handsome, skilled in arts, wealthy through multiple sources", "सुन्दर, कलामा दक्ष, विभिन्न स्रोतबाट धनी"),
YOGA_EFFECT_KEDARA("Agricultural wealth, helpful to others, truthful", "कृषि धन, अरूलाई मद्दतगर्ने, सत्यवादी"),
YOGA_EFFECT_SHOOLA("Sharp intellect, quarrelsome, cruel, poor", "तीक्ष्ण बुद्धि, झगडालु, निर्दयी, गरिब"),
YOGA_EFFECT_YUGA("Heretic, poor, rejected by family", "विधर्मी, गरिब, परिवारद्वारा त्यागिएको"),
YOGA_EFFECT_GOLA("Poor, dirty, ignorant, idle", "गरिब, फोहोरी, अज्ञानी, अल्छी"),
YOGA_EFFECT_VEENA("Fond of music, dance, leader, wealthy, happy", "संगीत र नृत्यको शौकीन, नेता, धनी, खुशी"),
YOGA_ANALYSIS_SUMMARY("Yoga Analysis Summary", "योग विश्लेषण सारांश"),
YOGA_OVERALL_STRENGTH("Overall Yoga Strength", "समग्र योग बल"),
YOGA_TOTAL("Total Yogas", "कुल योगहरू"),
YOGA_AUSPICIOUS("Auspicious", "शुभ"),
YOGA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
YOGA_ALL("All", "सबै"),
YOGA_COUNT_DETECTED("%d yogas detected", "%d योगहरू पत्ता लागेको"),
YOGA_INFORMATION("Yoga Information", "योग जानकारी"),
YOGA_ABOUT_TITLE("About Vedic Yogas", "वैदिक योगहरूको बारेमा"),
YOGA_ABOUT_DESCRIPTION("Yogas are special planetary combinations in Vedic astrology that indicate specific life patterns, talents, and karmic influences.", "योगहरू वैदिक ज्योतिषमा विशेष ग्रह संयोजनहरू हुन् जसले विशिष्ट जीवन ढाँचा, प्रतिभा र कर्म प्रभावहरू संकेत गर्छन्।"),
YOGA_CATEGORIES_TITLE("Categories", "वर्गहरू"),
YOGA_GOT_IT("Got it", "बुझें"),
YOGA_NO_DATA("No yoga data available", "कुनै योग डाटा उपलब्ध छैन"),
YOGA_NO_CHART_MESSAGE("Select or create a birth profile to view yogas.", "योगहरू हेर्न जन्म प्रोफाइल छान्नुहोस् वा बनाउनुहोस्।"),
YOGA_CATEGORY_WEALTH("Wealth Yogas", "धन योगहरू"),
YOGA_CATEGORY_WEALTH_DESC("Combinations for prosperity", "समृद्धिका लागि संयोजनहरू"),
YOGA_CATEGORY_RAJA("Raja Yogas", "राज योगहरू"),
YOGA_CATEGORY_RAJA_DESC("Combinations for power & authority", "शक्ति र अधिकारका लागि संयोजनहरू"),
YOGA_CATEGORY_SPIRITUAL("Spiritual Yogas", "आध्यात्मिक योगहरू"),
YOGA_CATEGORY_SPIRITUAL_DESC("Combinations for spiritual growth", "आध्यात्मिक वृद्धिका लागि संयोजनहरू"),
YOGA_CATEGORY_CHALLENGING("Challenging Yogas", "चुनौतीपूर्ण योगहरू"),
YOGA_CATEGORY_CHALLENGING_DESC("Combinations indicating obstacles", "बाधाहरू संकेत गर्ने संयोजनहरू"),
YOGA_CATEGORY_OTHER("Other Yogas", "अन्य योगहरू"),
YOGA_CATEGORY_OTHER_DESC("Other planetary combinations", "अन्य ग्रह संयोजनहरू"),
YOGA_CATEGORY_DHANA("Dhana Yogas", "धन योगहरू"),
YOGA_CATEGORY_DHANA_DESC("Combinations for wealth", "धनका लागि संयोजनहरू"),
YOGA_CATEGORY_MAHAPURUSHA("Mahapurusha Yogas", "महापुरुष योगहरू"),
YOGA_CATEGORY_MAHAPURUSHA_DESC("Great personality combinations", "महान व्यक्तित्व संयोजनहरू"),
YOGA_CATEGORY_NABHASA("Nabhasa Yogas", "नाभस योगहरू"),
YOGA_CATEGORY_NABHASA_DESC("Celestial combinations", "आकाशीय संयोजनहरू"),
YOGA_CATEGORY_CHANDRA("Chandra Yogas", "चन्द्र योगहरू"),
YOGA_CATEGORY_CHANDRA_DESC("Moon-based combinations", "चन्द्रमामा आधारित संयोजनहरू"),
YOGA_CATEGORY_SOLAR("Solar Yogas", "सूर्य योगहरू"),
YOGA_CATEGORY_SOLAR_DESC("Sun-based combinations", "सूर्यमा आधारित संयोजनहरू"),
YOGA_CATEGORY_SPECIAL("Special Yogas", "विशेष योगहरू"),
YOGA_CATEGORY_SPECIAL_DESC("Rare and special combinations", "दुर्लभ र विशेष संयोजनहरू"),
YOGA_CATEGORY_NEGATIVE("Negative Yogas", "नकारात्मक योगहरू"),
YOGA_CATEGORY_NEGATIVE_DESC("Combinations indicating challenges", "चुनौतीहरू संकेत गर्ने संयोजनहरू"),
YOGA_CAT_MAHAPURUSHA("Mahapurusha Yoga", "महापुरुष योग"),
YOGA_STRENGTH_VERY_STRONG("Very Strong", "धेरै बलियो"),
YOGA_MOST_SIGNIFICANT("Most Significant Yogas", "सबैभन्दा महत्त्वपूर्ण योगहरू"),
YOGA_SANSKRIT("Sanskrit", "संस्कृत"),
YOGA_EFFECTS("Effects", "प्रभावहरू"),
YOGA_ACTIVATION("Activation", "सक्रियता"),
YOGA_CANCELLATION_FACTORS("Cancellation/Mitigation Factors", "रद्द/न्यूनीकरण कारकहरू"),
YOGA_NO_CATEGORY_FOUND("No %s found", "कुनै %s फेला परेन"),
YOGA_NONE_DETECTED("No yogas detected", "कुनै योग पत्ता लागेन"),
YOGA_HOUSE_PREFIX("H", "भाव"),
YOGA_SUBTITLE("Planetary combinations in your chart", "तपाईंको कुण्डलीमा ग्रह संयोजनहरू"),
YOGA_STRENGTH("Strength", "बल"),
YOGA_DOMINANT_CATEGORY("Dominant Category", "प्रमुख वर्ग"),
YOGA_FILTER_BY_CATEGORY("Filter by Category", "वर्गअनुसार फिल्टर गर्नुहोस्"),
YOGA_COUNT_SUFFIX("yogas", "योगहरू"),
YOGA_PLANETS_INVOLVED("Planets Involved", "संलग्न ग्रहहरू"),
YOGA_HOUSES_LABEL("Houses:", "भावहरू:"),
YOGA_STRENGTH_LABEL("Yoga Strength", "योग बल"),
YOGA_ACTIVATION_LABEL("Activation:", "सक्रियता:"),
YOGA_NO_YOGAS_FOUND("No Yogas Found", "कुनै योग फेला परेन")
}
