package com.astro.storm.core.common

enum class StringKeyDashaPart1(override val en: String, override val ne: String) : StringKeyInterface {
    ANTARDASHA_DEFAULT_INTERP(
        "Current sub-period brings mixed planetary influences requiring careful navigation.",
        "हालको उप-अवधिले मिश्रित ग्रह प्रभावहरू ल्याउँछ जसलाई सावधानीपूर्वक नेभिगेट गर्न आवश्यक छ।"
    ),
    ANTARDASHA_EFFECTS("Short-Term Effects", "छोटो-अवधि प्रभावहरू"),
    ANTARDASHA_JUPITER_INTERP(
        "Current sub-period brings wisdom, expansion, good fortune, and focus on spirituality, teachers, children, higher education, or legal matters.",
        "हालको उप-अवधिले ज्ञान, विस्तार, सौभाग्य, र आध्यात्मिकता, शिक्षकहरू, सन्तान, उच्च शिक्षा वा कानूनी मामिलाहरूमा ध्यान ल्याउँछ।"
    ),
    ANTARDASHA_KETU_INTERP(
        "Current sub-period brings spiritual insights, detachment, introspection, research, and resolution of past karmic patterns. Material concerns recede.",
        "हालको उप-अवधिले आध्यात्मिक अन्तरदृष्टि, वैराग्य, आत्म-चिन्तन, अनुसन्धान र विगतका कर्मिक ढाँचाहरूको समाधान ल्याउँछ। भौतिक चिन्ताहरू कम हुन्छन्।"
    ),
    ANTARDASHA_MARS_INTERP(
        "Current sub-period brings increased energy, drive for action, courage, and matters involving property, siblings, competition, or technical endeavors.",
        "हालको उप-अवधिले बढेको ऊर्जा, कार्यप्रतिको उत्साह, साहस, र सम्पत्ति, भाइबहिनी, प्रतिस्पर्धा वा प्राविधिक प्रयासहरू समावेश गर्ने मामिलाहरू ल्याउँछ।"
    ),
    ANTARDASHA_MERCURY_INTERP(
        "Current sub-period emphasizes communication, learning, business transactions, intellectual activities, and connections with younger people or merchants.",
        "हालको उप-अवधिले सञ्चार, सिकाइ, व्यापारिक लेनदेन, बौद्धिक गतिविधिहरू र युवा मानिसहरू वा व्यापारीहरूसँगको सम्बन्धलाई जोड दिन्छ।"
    ),
    ANTARDASHA_MOON_INTERP(
        "Current sub-period emphasizes emotional matters, mental peace, mother, public image, domestic affairs, and connection with women. Intuition heightens.",
        "हालको उप-अवधिले भावनात्मक मामिलाहरू, मानसिक शान्ति, आमा, सार्वजनिक छवि, घरायसी मामिलाहरू र महिलाहरूसँगको सम्बन्धलाई जोड दिन्छ। अन्तर्ज्ञान बढ्छ।"
    ),
    ANTARDASHA_PERIOD("Antardasha Period", "अन्तर्दशा अवधि"),
    ANTARDASHA_PLANET("Antardasha Planet", "अन्तर्दशा ग्रह"),
    ANTARDASHA_RAHU_INTERP(
        "Current sub-period emphasizes worldly ambitions, unconventional approaches, foreign matters, technology, and sudden changes or opportunities.",
        "हालको उप-अवधिले सांसारिक महत्त्वाकांक्षा, अपरम्परागत दृष्टिकोण, विदेशी मामिलाहरू, प्रविधि र अचानक परिवर्तन वा अवसरहरूलाई जोड दिन्छ।"
    ),
    ANTARDASHA_SATURN_INTERP(
        "Current sub-period brings discipline, responsibility, hard work, delays, and lessons requiring patience. Focus on service and long-term efforts.",
        "हालको उप-अवधिले अनुशासन, जिम्मेवारी, कडा परिश्रम, ढिलाइ र धैर्य चाहिने पाठहरू ल्याउँछ। सेवा र दीर्घकालीन प्रयासहरूमा ध्यान केन्द्रित गर्नुहोस्।"
    ),
    ANTARDASHA_SUN_INTERP(
        "Current sub-period (Bhukti) activates themes of authority, self-confidence, recognition, and dealings with father figures or government. Leadership opportunities may arise.",
        "हालको उप-अवधि (भुक्ति) ले अधिकार, आत्मविश्वास, मान्यता, र पिता समान व्यक्तित्व वा सरकारसँगको व्यवहारका विषयहरू सक्रिय गर्दछ। नेतृत्वका अवसरहरू आउन सक्छन्।"
    ),
    ANTARDASHA_THEME("Refined Theme", "परिष्कृत विषय"),
    ANTARDASHA_TITLE("Current Antardasha", "वर्तमान अन्तर्दशा"),
    ANTARDASHA_VENUS_INTERP(
        "Current sub-period emphasizes relationships, romance, creativity, luxury, artistic pursuits, material comforts, and partnership matters.",
        "हालको उप-अवधिले सम्बन्ध, रोमान्स, सिर्जनशीलता, विलासिता, कलात्मक कार्यहरू, भौतिक सुखसुविधाहरू र साझेदारी मामिलाहरूलाई जोड दिन्छ।"
    ),
    ASHTOTTARI_ABOUT("About Ashtottari Dasha", "अष्टोत्तरी दशाको बारेमा"),
    ASHTOTTARI_ABOUT_DESC("Ashtottari Dasha is a conditional planetary period system spanning 108 years. It uses 8 planets (excluding Ketu). The system is particularly effective for daytime births with Moon in Krishna Paksha or nighttime births with Moon in Shukla Paksha.", "अष्टोत्तरी दशा १०८ वर्षको सशर्त ग्रह अवधि प्रणाली हो। यसमा ८ ग्रह प्रयोग गरिन्छ (केतु बाहेक)। यो प्रणाली कृष्ण पक्षमा चन्द्रमासहित दिनको जन्म वा शुक्ल पक्षमा चन्द्रमासहित रातको जन्मको लागि प्रभावकारी छ।"),
    ASHTOTTARI_ABOUT_DESC_FULL("The Ashtottari Dasha system is a 108-year planetary period cycle, traditionally used for charts where the Moon is in Krishna Paksha (waning phase) between Shukla Chaturthi to Krishna Tritiya.", "अष्टोत्तरी दशा प्रणाली १०८-वर्षे ग्रह अवधि चक्र हो, जुन परम्परागत रूपमा शुक्ल चतुर्थीदेखि कृष्ण तृतीयासम्म चन्द्रमा कृष्ण पक्षमा (घट्दो चरण) हुने कुण्डलीहरूको लागि प्रयोग गरिन्छ।"),
    ASHTOTTARI_ABOUT_TITLE("About Ashtottari Dasha", "अष्टोत्तरी दशा बारे"),
    ASHTOTTARI_ANTARDASHAS_TITLE("Antardashas", "अन्तर्दशाहरू"),
    ASHTOTTARI_ANTARDASHA_LABEL("Antardasha", "अन्तर्दशा"),
    ASHTOTTARI_APPLICABILITY("Applicability Check", "लागू हुने जाँच"),
    ASHTOTTARI_APPLICABLE("Applicable", "लागू"),
    ASHTOTTARI_BALANCE("Balance at Birth", "जन्ममा शेष"),
    ASHTOTTARI_BALANCE_AT_BIRTH("Balance at Birth", "जन्ममा सन्तुलन"),
    ASHTOTTARI_BIRTH_NAKSHATRA_HEADER("BIRTH NAKSHATRA", "जन्म नक्षत्र"),
    ASHTOTTARI_COMPARISON("Vimsottari vs Ashtottari", "विंशोत्तरी बनाम अष्टोत्तरी"),
    ASHTOTTARI_CURRENT_AD("Current Antardasha", "वर्तमान अन्तर्दशा"),
    ASHTOTTARI_CURRENT_MD("Current Mahadasha", "वर्तमान महादशा"),
    ASHTOTTARI_CURRENT_PERIOD("Current Period", "वर्तमान अवधि"),
    ASHTOTTARI_CURRENT_TITLE("Current Ashtottari Period", "वर्तमान अष्टोत्तरी अवधि"),
    ASHTOTTARI_DASHA_ABOUT("About Ashtottari Dasha", "अष्टोत्तरी दशाको बारेमा"),
    ASHTOTTARI_DASHA_ABOUT_DESC("Ashtottari Dasha is a 108-year cycle using 8 planets (excluding Ketu). It is applicable when Rahu is in Kendra or Trikona from Lagna lord.", "अष्टोत्तरी दशा ८ ग्रहहरू (केतु बाहेक) प्रयोग गर्ने १०८-वर्षे चक्र हो। यो लग्नेशबाट राहु केन्द्र वा त्रिकोणमा हुँदा लागू हुन्छ।"),
    ASHTOTTARI_DASHA_SUBTITLE("108-Year Dasha Cycle", "१०८-वर्षे दशा चक्र"),
    ASHTOTTARI_DASHA_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
    ASHTOTTARI_DIFFERENT("Systems show different planets", "प्रणालीहरूले फरक ग्रह देखाउँछन्"),
    ASHTOTTARI_ENEMY("Challenging Period", "चुनौतीपूर्ण अवधि"),
    ASHTOTTARI_FRIEND("Friendly Period", "मैत्रीपूर्ण अवधि"),
    ASHTOTTARI_IDEAL_CONDITION("Ideal Condition: Day birth with Krishna Paksha Moon or Night birth with Shukla Paksha Moon", "आदर्श अवस्था: कृष्ण पक्षको चन्द्रमासहित दिनको जन्म वा शुक्ल पक्षको चन्द्रमासहित रातको जन्म"),
    ASHTOTTARI_IN_AGREEMENT("Both systems agree", "दुवै प्रणाली सहमत"),
    ASHTOTTARI_JUPITER_DURATION("Jupiter: 19 years", "बृहस्पति: १९ वर्ष"),
    ASHTOTTARI_LORD_HEADER("LORD", "स्वामी"),
    ASHTOTTARI_MAHADASHA_LABEL("Mahadasha", "महादशा"),
    ASHTOTTARI_MARS_DURATION("Mars: 8 years", "मंगल: ८ वर्ष"),
    ASHTOTTARI_MERCURY_DURATION("Mercury: 17 years", "बुध: १७ वर्ष"),
    ASHTOTTARI_MOON_DURATION("Moon: 15 years", "चन्द्र: १५ वर्ष"),
    ASHTOTTARI_NEUTRAL("Neutral Period", "तटस्थ अवधि"),
    ASHTOTTARI_NOT_APPLICABLE("Not Applicable", "लागू हुँदैन"),
    ASHTOTTARI_PERIOD_INSIGHTS("Period Insights", "अवधि अन्तर्दृष्टि"),
    ASHTOTTARI_PERIOD_LIST_HEADER("Planet Periods (108 Years Total)", "ग्रह अवधिहरू (कुल १०८ वर्ष)"),
    ASHTOTTARI_PERIOD_YEARS("Period (Years)", "अवधि (वर्ष)"),
    ASHTOTTARI_PLANETS_USED("8 Planets Used (No Sun, No Ketu)", "८ ग्रह प्रयोग (सूर्य र केतु बिना)"),
    ASHTOTTARI_RAHU_DURATION("Rahu: 12 years", "राहु: १२ वर्ष"),
    ASHTOTTARI_RAHU_FROM_LAGNA_LORD("Rahu from Lagna Lord", "लग्नेशबाट राहु"),
    ASHTOTTARI_REASON("Applicability Reason", "प्रयोज्यता कारण"),
    ASHTOTTARI_SAME("Intensified Period", "तीव्र अवधि"),
    ASHTOTTARI_SATURN_DURATION("Saturn: 10 years", "शनि: १० वर्ष"),
    ASHTOTTARI_STARTING_LORD("Starting Dasha Lord", "सुरुवात दशा स्वामी"),
    ASHTOTTARI_SUBTITLE("108-Year Conditional Dasha System", "१०८ वर्षको सशर्त दशा प्रणाली"),
    ASHTOTTARI_SUB_PERIODS_FMT("%d sub-periods", "%d उप-अवधिहरू"),
    ASHTOTTARI_SUN_DURATION("Sun: 6 years", "सूर्य: ६ वर्ष"),
    ASHTOTTARI_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
    ASHTOTTARI_TIMELINE_DESC("108-Year Planetary Cycle", "१०८-वर्षे ग्रह चक्र"),
    ASHTOTTARI_TIMELINE_TITLE("Ashtottari Timeline", "अष्टोत्तरी समयरेखा"),
    ASHTOTTARI_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
    ASHTOTTARI_TOTAL_YEARS("Total Cycle: 108 Years", "कुल चक्र: १०८ वर्ष"),
    ASHTOTTARI_UNABLE_CALC("Unable to calculate current period", "वर्तमान अवधि गणना गर्न असमर्थ"),
    ASHTOTTARI_VENUS_DURATION("Venus: 21 years", "शुक्र: २१ वर्ष"),
    CHARA_DASHA_ABOUT("About Chara Dasha", "चर दशाको बारेमा"),
    CHARA_DASHA_ABOUT_DESC("Chara Dasha is Jaimini's primary sign-based timing system. Unlike Vimsottari which uses planets, Chara Dasha uses zodiac signs as periods, providing unique insights into life events.", "चर दशा जैमिनीको प्राथमिक राशि-आधारित समय प्रणाली हो। विम्सोत्तरी जसले ग्रह प्रयोग गर्छ त्यसको विपरीत, चर दशाले अवधिको रूपमा राशिहरू प्रयोग गर्छ, जीवनका घटनाहरूमा अद्वितीय अन्तर्दृष्टि प्रदान गर्छ।"),
    CHARA_DASHA_ANTARDASHA("Current Antardasha", "वर्तमान अन्तर्दशा"),
    CHARA_DASHA_CALC_ERROR("Unknown error calculating Chara Dasha", "कारा दशा गणना गर्दा अज्ञात त्रुटि"),
    CHARA_DASHA_CURRENT("Current Sign Dasha", "वर्तमान राशि दशा"),
    CHARA_DASHA_DIRECT("Direct (Zodiacal)", "सीधो (राशिक्रम)"),
    CHARA_DASHA_DIRECTION("Dasha Direction", "दशा दिशा"),
    CHARA_DASHA_EVEN_LAGNA("Even Sign Lagna", "सम राशि लग्न"),
    CHARA_DASHA_ODD_LAGNA("Odd Sign Lagna", "विषम राशि लग्न"),
    CHARA_DASHA_REVERSE("Reverse (Anti-zodiacal)", "उल्टो (विपरीत-राशिक्रम)"),
    CHARA_DASHA_SEQUENCE("Dasha Sequence", "दशा क्रम"),
    CHARA_DASHA_SUBTITLE("Jaimini Sign-Based Dasha", "जैमिनी राशि-आधारित दशा"),
    CHARA_DASHA_TIMELINE("Chara Dasha Timeline", "चर दशा समयरेखा"),
    CHARA_DASHA_TITLE("Chara Dasha", "चर दशा"),
    CHARA_DASHA_TYPE("Type", "प्रकार"),
    CHARA_DASHA_YEARS("Years: %d", "वर्ष: %d"),
    DASHA_ABOUT_VIMSHOTTARI("About Vimshottari Dasha", "विम्शोत्तरी दशाको बारेमा"),
    DASHA_ACTIVE("Active", "सक्रिय"),
    DASHA_ACTIVE_NOW("Active Now", "अहिले सक्रिय"),
    DASHA_AFF_JUPITER("I am open to abundance and share my wisdom generously.", "म प्रचुरताको लागि खुला छु र आफ्नो ज्ञान उदारतापूर्वक साझा गर्छु।"),
    DASHA_AFF_KETU("I release what no longer serves me and embrace spiritual growth.", "म जुन कुराले अब मेरो सेवा गर्दैन त्यसलाई छाड्छु र आध्यात्मिक वृद्धिलाई अँगाल्छु।"),
    DASHA_AFF_MARS("I channel my energy constructively and act with courage.", "म आफ्नो ऊर्जा रचनात्मक रूपमा प्रयोग गर्छु र साहसका साथ काम गर्छु।"),
    DASHA_AFF_MERCURY("I communicate clearly and embrace continuous learning.", "म स्पष्ट रूपमा सञ्चार गर्छु र निरन्तर सिकाइलाई अँगाल्छु।"),
    DASHA_AFF_MOON("I trust my intuition and nurture myself with compassion.", "म आफ्नो अन्तर्ज्ञानमाथि विश्वास गर्छु र करुणाका साथ आफूलाई पोषण गर्छु।"),
    DASHA_AFF_RAHU("I embrace change and transform challenges into opportunities.", "म परिवर्तनलाई अँगाल्छु र चुनौतीहरूलाई अवसरहरूमा रूपान्तरण गर्छु।"),
    DASHA_AFF_SATURN("I embrace discipline and trust in the timing of my journey.", "म अनुशासनलाई अँगाल्छु र आफ्नो यात्राको समयमाथि विश्वास गर्छु।"),
    DASHA_AFF_SUN("I shine my light confidently and inspire those around me.", "म आत्मविश्वासका साथ आफ्नो प्रकाश फैलाउँछु र वरिपरिका मानिसहरूलाई प्रेरित गर्छु।"),
    DASHA_AFF_VENUS("I attract beauty and harmony into my life.", "म आफ्नो जीवनमा सौन्दर्य र सामञ्जस्य आकर्षित गर्छु।"),
    DASHA_ANTARDASHA("Antardasha", "अन्तर्दशा"),
    DASHA_ANTARDASHAS("Antardashas", "अन्तर्दशाहरू"),
    DASHA_ANTAR_1("• Check the relationship between Dasha and Antardasha lords", "• दशा र अन्तर्दशा स्वामीहरू बीचको सम्बन्ध जाँच गर्नुहोस्"),
    DASHA_ANTAR_2("• If they are friends - period will be favorable", "• यदि तिनीहरू मित्र हुन् भने - अवधि अनुकूल हुनेछ"),
    DASHA_ANTAR_3("• If they are enemies - increase remedies for both planets", "• यदि तिनीहरू शत्रु हुन् भने - दुवै ग्रहहरूको लागि उपायहरू बढाउनुहोस्"),
    DASHA_ANTAR_4("• Pratyantar Dasha (sub-sub period) shows fine-tuned timing", "• प्रत्यन्तर दशा (उप-उप अवधि) ले सूक्ष्म समय देखाउँछ"),
    DASHA_ANTAR_TITLE("ANTARDASHA (Sub-period) GUIDANCE:", "अन्तर्दशा (उप-अवधि) मार्गदर्शन:"),
    DASHA_ASHTOTTARI("Ashtottari", "अष्टोत्तरी"),
    DASHA_ASHTOTTARI_DESC("Traditional for night births, uses 8 planets", "रात्री जन्मको लागि परम्परागत, ८ ग्रहहरू प्रयोग गर्दछ"),
    DASHA_ASHTOTTARI_DURATION("108 years", "१०८ वर्ष"),
    DASHA_ASHTOTTARI_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
    DASHA_AWARENESS_DESC("General guidance for navigating planetary Dasha periods effectively.", "ग्रह दशा अवधिहरू प्रभावकारी रूपमा पार गर्नको लागि सामान्य मार्गदर्शन।"),
    DASHA_AWARENESS_TITLE("Dasha Period Awareness", "दशा अवधि जागरूकता"),
    DASHA_BALANCE("Dasha Balance", "दशा सन्तुलन"),
    DASHA_BENEFIT_MAX("Maximizes positive effects of favorable Dashas", "अनुकूल दशाको सकारात्मक प्रभावहरूलाई अधिकतम बनाउँछ"),
    DASHA_BENEFIT_MIN("Minimizes challenges during difficult Dashas", "कठिन दशाको समयमा चुनौतीहरू कम गर्दछ"),
    DASHA_BENEFIT_TIME("Provides timing awareness for important decisions", "महत्त्वपूर्ण निर्णयहरूको लागि समय जागरूकता प्रदान गर्दछ"),
    DASHA_BHUKTI("Bhukti", "भुक्ति"),
    DASHA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    DASHA_BODY_PERIOD_MINUTES("Body period (minutes)", "शरीर अवधि (मिनेट)"),
    DASHA_BREATH_PERIOD_HOURS("Breath period (hours)", "श्वास अवधि (घण्टा)"),
    DASHA_CALCULATING("Calculating...", "गणना गर्दै..."),
    DASHA_CALCULATING_DESC("Computing planetary periods based on\nMoon's Nakshatra position...", "चन्द्रको नक्षत्र स्थितिको आधारमा\nग्रह अवधिहरू गणना गर्दै..."),
    DASHA_CALCULATING_TIMELINE("Calculating Dasha Timeline", "दशा समयरेखा गणना गर्दै"),
    DASHA_CALCULATION_FAILED("Calculation Failed", "गणना असफल भयो"),
    DASHA_CALC_LOADING("Calculating %s Dasha timeline...", "%s दशा समयरेखा गणना गर्दै..."),
    DASHA_CAREER_FOCUS("Dasha Period Career Focus", "दशा अवधि क्यारियर फोकस"),
    DASHA_CAUTION_CONSULT("Consult a Vedic astrologer for specific Dasha analysis", "विशिष्ट दशा विश्लेषणको लागि वैदिक ज्योतिषीसँग परामर्श गर्नुहोस्"),
    DASHA_CAUTION_TRANSIT("Dasha effects are modified by transit influences", "दशा प्रभावहरू गोचर प्रभावहरूद्वारा परिमार्जित हुन्छन्"),
    DASHA_CHARA("Chara", "कारा"),
    DASHA_CHARA_DESC("Jaimini sign-based system with Karakamsha analysis", "जैमिनी राशि-आधारित प्रणाली, कारकांश विश्लेषण सहित"),
    DASHA_CHARA_DURATION("Variable", "परिवर्तनशील"),
    DASHA_CHARA_TITLE("Chara Dasha (Jaimini)", "चर दशा (जैमिनी)"),
    DASHA_COLLAPSE("Collapse", "संकुचन गर्नुहोस्"),
    DASHA_COMBINED_NAME("%s-%s", "%s-%s"),
    DASHA_COMPLETE_CYCLE("Complete 120-year Vimshottari cycle", "पूर्ण १२०-वर्षे विम्शोत्तरी चक्र"),
    DASHA_CURRENTLY_ACTIVE("Currently Active", "हाल सक्रिय"),
    DASHA_CURRENT_DASHA_PERIOD("Current Dasha Period", "हालको दशा अवधि"),
    DASHA_CURRENT_PERIOD("Current Planetary Period", "हालको ग्रह अवधि"),
    DASHA_CYCLE_DURATION("Cycle Duration: %s", "चक्र अवधि: %s"),
    DASHA_DEHA("Deha", "देह"),
    DASHA_DEHADASHA("Dehadasha", "देहदशा"),
    DASHA_DURATION("Entire Dasha duration", "पूर्ण दशा अवधि"),
    DASHA_EFFECT_TEMPLATE("Currently running %s Mahadasha with %s Antardasha. This period emphasizes %s.",
        "हाल %s महादशा %s अन्तर्दशाको साथ चलिरहेको छ। यो अवधिले %s मा जोड दिन्छ।"),
    DASHA_ERROR("Error", "त्रुटि"),
    DASHA_EXPAND("Expand", "विस्तार गर्नुहोस्"),
    DASHA_HEALTH_FOCUS("Dasha Period Health Focus", "दशा अवधि स्वास्थ्य फोकस"),
    DASHA_HIERARCHY("Dasha Hierarchy", "दशा पदानुक्रम"),
    DASHA_INTERP_ANTARDASHA_DEFAULT(
        "Current sub-period brings mixed planetary influences requiring careful navigation.",
        "हालको उप-अवधिले सावधानीपूर्वक मार्गदर्शन चाहिने मिश्रित ग्रहीय प्रभावहरू ल्याउँछ।"
    ),
    DASHA_INTERP_ANTARDASHA_JUPITER(
        "Current sub-period brings wisdom, expansion, good fortune, and focus on spirituality, teachers, children, higher education, or legal matters.",
        "हालको उप-अवधिले बुद्धि, विस्तार, सुभाग्य र आध्यात्मिकता, शिक्षकहरू, सन्तान, उच्च शिक्षा वा कानुनी मामिलाहरूमा ध्यान केन्द्रित गर्छ।"
    ),
    DASHA_INTERP_ANTARDASHA_KETU(
        "Current sub-period brings spiritual insights, detachment, introspection, research, and resolution of past karmic patterns. Material concerns recede.",
        "हालको उप-अवधिले आध्यात्मिक अन्तर्दृष्टि, वैराग्य, आत्मनिरीक्षण, अनुसन्धान र पूर्व कार्मिक ढाँचाको समाधान ल्याउँछ। भौतिक चिन्ताहरू पछाडि हट्छन्।"
    ),
    DASHA_INTERP_ANTARDASHA_MARS(
        "Current sub-period brings increased energy, drive for action, courage, and matters involving property, siblings, competition, or technical endeavors.",
        "हालको उप-अवधिले बढेको ऊर्जा, कार्यको लागि उत्प्रेरणा, साहस र सम्पत्ति, भाइबहिनी, प्रतिस्पर्धा वा प्राविधिक प्रयासका मामिलाहरू ल्याउँछ।"
    ),
    DASHA_INTERP_ANTARDASHA_MERCURY(
        "Current sub-period emphasizes communication, learning, business transactions, intellectual activities, and connections with younger people or merchants.",
        "हालको उप-अवधिले सञ्चार, सिकाइ, व्यापारिक लेनदेन, बौद्धिक गतिविधिहरू र साना मानिसहरू वा व्यापारीहरूसँगको सम्बन्धमा जोड दिन्छ।"
    ),
    DASHA_INTERP_ANTARDASHA_MOON(
        "Current sub-period emphasizes emotional matters, mental peace, mother, public image, domestic affairs, and connection with women. Intuition heightens.",
        "हालको उप-अवधिले भावनात्मक मामिला, मानसिक शान्ति, आमा, सार्वजनिक छवि, घरेलु मामिला र महिलाहरूसँगको सम्बन्धमा जोड दिन्छ। अन्तर्ज्ञान तीव्र हुन्छ।"
    ),
    DASHA_INTERP_ANTARDASHA_RAHU(
        "Current sub-period emphasizes worldly ambitions, unconventional approaches, foreign matters, technology, and sudden changes or opportunities.",
        "हालको उप-अवधिले सांसारिक महत्त्वाकांक्षा, अपरम्परागत दृष्टिकोण, विदेशी मामिला, प्रविधि र अचानक परिवर्तन वा अवसरहरूमा जोड दिन्छ।"
    ),
    DASHA_INTERP_ANTARDASHA_SATURN(
        "Current sub-period brings discipline, responsibility, hard work, delays, and lessons requiring patience. Focus on service and long-term efforts.",
        "हालको उप-अवधिले अनुशासन, जिम्मेवारी, कठिन परिश्रम, ढिलाइ र धैर्य चाहिने पाठहरू ल्याउँछ। सेवा र दीर्घकालीन प्रयासमा ध्यान केन्द्रित।"
    ),
    DASHA_INTERP_ANTARDASHA_SUN(
        "Current sub-period (Bhukti) activates themes of authority, self-confidence, recognition, and dealings with father figures or government. Leadership opportunities may arise.",
        "हालको उप-अवधि (भुक्ति) ले अधिकार, आत्मविश्वास, मान्यता र बुबाका व्यक्ति वा सरकारसँगको व्यवहारका विषयहरू सक्रिय गर्छ। नेतृत्व अवसरहरू आउन सक्छन्।"
    ),
    DASHA_INTERP_ANTARDASHA_VENUS(
        "Current sub-period emphasizes relationships, romance, creativity, luxury, artistic pursuits, material comforts, and partnership matters.",
        "हालको उप-अवधिले सम्बन्ध, रोमान्स, सिर्जनशीलता, विलासिता, कलात्मक खोज, भौतिक सुविधा र साझेदारी मामिलाहरूमा जोड दिन्छ।"
    ),
    DASHA_INTERP_MAHADASHA_DEFAULT(
        "A period of transformation and karmic unfolding according to planetary influences.",
        "ग्रहीय प्रभाव अनुसार रूपान्तरण र कार्मिक विकासको अवधि।"
    ),
    DASHA_INTERP_MAHADASHA_JUPITER(
        "A period of wisdom, expansion, prosperity, and divine grace (Guru's blessings). Focus on spirituality, higher learning, teaching, children, law, and philosophical pursuits. Fortune favors righteous endeavors. Faith and optimism increase. Excellent for marriage, progeny, and spiritual advancement.",
        "बुद्धि, विस्तार, समृद्धि र दैवी कृपाको अवधि (गुरुको आशीर्वाद)। आध्यात्मिकता, उच्च शिक्षा, शिक्षण, सन्तान, कानुन र दार्शनिक खोजमा ध्यान केन्द्रित। भाग्यले धार्मिक प्रयासहरूलाई साथ दिन्छ। विश्वास र आशावाद बढ्छ। विवाह, सन्तान र आध्यात्मिक प्रगतिको लागि उत्कृष्ट।"
    ),
    DASHA_INTERP_MAHADASHA_KETU(
        "A period of spirituality, detachment, and profound inner transformation. Focus on liberation (moksha), occult research, healing practices, and resolving past-life karma. Deep introspection yields spiritual insights. Material attachments may dissolve. Excellent for meditation, research, and spiritual practices.",
        "आध्यात्मिकता, वैराग्य र गहिरो आन्तरिक रूपान्तरणको अवधि। मुक्ति (मोक्ष), तान्त्रिक अनुसन्धान, उपचार अभ्यास र पूर्वजन्मको कर्म समाधानमा ध्यान केन्द्रित। गहिरो आत्मनिरीक्षणले आध्यात्मिक अन्तर्दृष्टि दिन्छ। भौतिक आसक्तिहरू विलीन हुन सक्छन्। ध्यान, अनुसन्धान र आध्यात्मिक अभ्यासको लागि उत्कृष्ट।"
    ),
    DASHA_INTERP_MAHADASHA_MARS(
        "A period of heightened energy, courage, initiative, and competitive drive. Focus on property matters, real estate, siblings, technical and engineering pursuits, sports, and surgery. Decisive action is favored. Physical vitality increases. Good for tackling challenges requiring strength and determination.",
        "ऊर्जा, साहस, पहल र प्रतिस्पर्धात्मक उत्प्रेरणाको उच्च अवधि। सम्पत्ति मामिला, घरजग्गा, भाइबहिनी, प्राविधिक र इन्जिनियरिङ, खेलकुद र शल्यक्रियामा ध्यान केन्द्रित। निर्णायक कार्यलाई प्राथमिकता दिइन्छ। शारीरिक जीवनशक्ति बढ्छ। बल र दृढ संकल्प चाहिने चुनौतीहरू सामना गर्न राम्रो।"
    ),
    DASHA_INTERP_MAHADASHA_MERCURY(
        "A period of enhanced learning, communication, analytical thinking, and commerce. Focus on education, writing, publishing, accounting, trade, and intellectual pursuits. Social connections expand through skillful communication. Good for developing skills, starting businesses, and mastering information.",
        "सिकाइ, सञ्चार, विश्लेषणात्मक सोच र वाणिज्यको उन्नत अवधि। शिक्षा, लेखन, प्रकाशन, लेखा, व्यापार र बौद्धिक खोजमा ध्यान केन्द्रित। दक्ष सञ्चार मार्फत सामाजिक सम्बन्ध विस्तार हुन्छ। सीप विकास, व्यवसाय सुरु गर्न र जानकारीमा दक्षता हासिल गर्न राम्रो।"
    ),
    DASHA_INTERP_MAHADASHA_MOON(
        "An emotionally rich and intuitive period emphasizing mental peace, nurturing, and receptivity. Focus on mother, home life, public image, travel across water, and emotional well-being. Creativity and imagination flourish. Memory and connection to the past strengthen. Relationships with women and the public become significant.",
        "भावनात्मक रूपले समृद्ध र अन्तर्ज्ञानात्मक अवधि जसले मानसिक शान्ति, पालनपोषण र ग्रहणशीलतामा जोड दिन्छ। आमा, घरेलु जीवन, सार्वजनिक छवि, पानी पार यात्रा र भावनात्मक कल्याणमा ध्यान केन्द्रित। सिर्जनशीलता र कल्पना फस्टाउँछ। स्मृति र भूतकालसँगको सम्बन्ध बलियो हुन्छ। महिलाहरू र जनतासँगको सम्बन्ध महत्त्वपूर्ण हुन्छ।"
    ),
    DASHA_INTERP_MAHADASHA_RAHU(
        "A period of intense worldly ambition, unconventional paths, and material desires. Focus on foreign connections, technology, innovation, and breaking traditional boundaries. Sudden opportunities and unexpected changes arise. Material gains through unusual or non-traditional means. Beware of illusions.",
        "तीव्र सांसारिक महत्त्वाकांक्षा, अपरम्परागत मार्ग र भौतिक इच्छाको अवधि। विदेशी सम्बन्ध, प्रविधि, नवीनता र परम्परागत सीमाहरू तोड्नमा ध्यान केन्द्रित। अचानक अवसरहरू र अप्रत्याशित परिवर्तनहरू आउँछन्। असामान्य वा गैर-परम्परागत माध्यमबाट भौतिक लाभ। भ्रमबाट सावधान रहनुहोस्।"
    ),
    DASHA_INTERP_MAHADASHA_SATURN(
        "A period of discipline, karmic lessons, perseverance, and structural growth. Focus on service, responsibility, hard work, long-term projects, and lessons through patience. Delays and obstacles ultimately lead to lasting success and maturity. Time to build solid foundations and pay karmic debts.",
        "अनुशासन, कार्मिक पाठ, दृढता र संरचनात्मक विकासको अवधि। सेवा, जिम्मेवारी, कठिन परिश्रम, दीर्घकालीन परियोजना र धैर्य मार्फत पाठहरूमा ध्यान केन्द्रित। ढिलाइ र बाधाहरूले अन्ततः स्थायी सफलता र परिपक्वता ल्याउँछ। ठोस आधार निर्माण गर्ने र कार्मिक ऋण चुक्ता गर्ने समय।"
    ),
    DASHA_INTERP_MAHADASHA_SUN(
        "A period of heightened self-expression, authority, and recognition. Focus turns to career advancement, leadership roles, government dealings, and matters related to father. Soul purpose becomes clearer. Health of heart and vitality gains prominence. Good for developing confidence and establishing one's identity in the world.",
        "आत्म-अभिव्यक्ति, अधिकार र मान्यताको उच्च अवधि। क्यारियर प्रगति, नेतृत्व भूमिका, सरकारी व्यवहार र बुबासँग सम्बन्धित मामिलाहरूमा ध्यान केन्द्रित हुन्छ। आत्माको उद्देश्य स्पष्ट हुन्छ। हृदय र जीवनशक्तिको स्वास्थ्यले प्रमुखता पाउँछ। आत्मविश्वास विकास गर्न र संसारमा आफ्नो पहिचान स्थापित गर्न राम्रो।"
    ),
    DASHA_INTERP_MAHADASHA_VENUS(
        "A period of luxury, beauty, relationships, artistic expression, and material comforts. Focus on marriage, partnerships, arts, music, dance, vehicles, jewelry, and sensory pleasures. Creativity and romance blossom. Refinement in all areas of life. Good for enhancing beauty, wealth, and experiencing life's pleasures.",
        "विलासिता, सौन्दर्य, सम्बन्ध, कलात्मक अभिव्यक्ति र भौतिक सुविधाहरूको अवधि। विवाह, साझेदारी, कला, सङ्गीत, नृत्य, सवारीसाधन, गहना र इन्द्रिय आनन्दमा ध्यान केन्द्रित। सिर्जनशीलता र रोमान्स फस्टाउँछ। जीवनका सबै क्षेत्रमा परिष्करण। सौन्दर्य, सम्पत्ति बढाउन र जीवनका आनन्दहरू अनुभव गर्न राम्रो।"
    ),
    DASHA_IN_DAYS("In %d days", "%d दिनमा"),
    DASHA_JUMP_TO_TODAY("Jump to current period", "हालको अवधिमा जानुहोस्"),
    DASHA_JUPITER("Jupiter Dasha Theme", "बृहस्पति दशा विषय"),
    DASHA_KALACHAKRA_DESC("Complex dasha based on Moon's Navamsha, reflecting wheel of time.", "चन्द्रमाको नवांशमा आधारित जटिल दशा, जसले समयको चक्रलाई प्रतिबिम्बित गर्दछ।"),
    DASHA_KALACHAKRA_TITLE("Kalachakra Dasha", "कालचक्र दशा"),
    DASHA_KETU("Ketu Dasha Theme", "केतु दशा विषय"),
    DASHA_KW_ACTION("Action", "कार्य"),
    DASHA_KW_AMBITION("Ambition", "महत्त्वाकांक्षा"),
    DASHA_KW_ART("Art", "कला"),
    DASHA_KW_BODY("Body", "शरीर"),
    DASHA_KW_BUSINESS("Business", "व्यापार"),
    DASHA_KW_CAREER("Career", "क्यारियर"),
    DASHA_KW_CHILDREN("Children", "सन्तान"),
    DASHA_KW_COMFORT("Comfort", "सुविधा"),
    DASHA_KW_COMMUNICATION("Communication", "सञ्चार"),
    DASHA_KW_COURAGE("Courage", "साहस"),
    DASHA_KW_DELAYS("Delays", "ढिलाइ"),
    DASHA_KW_DETACHMENT("Detachment", "वैराग्य"),
    DASHA_KW_DISCIPLINE("Discipline", "अनुशासन"),
    DASHA_KW_EMOTIONS("Emotions", "भावनाहरू"),
    DASHA_KW_ENERGY("Energy", "ऊर्जा"),
    DASHA_KW_FATHER("Father", "बुबा"),
    DASHA_KW_FOREIGN("Foreign", "विदेशी"),
    DASHA_KW_FRIENDS("Friends", "मित्रहरू"),
    DASHA_KW_GAINS("Gains", "लाभ"),
    DASHA_KW_GENERAL("General", "सामान्य"),
    DASHA_KW_GROWTH("Growth", "वृद्धि"),
    DASHA_KW_HEALTH("Health", "स्वास्थ्य"),
    DASHA_KW_HOME("Home", "घर"),
    DASHA_KW_INNOVATION("Innovation", "नवीनता"),
    DASHA_KW_KARMA("Karma", "कर्म"),
    DASHA_KW_LEADERSHIP("Leadership", "नेतृत्व"),
    DASHA_KW_LEARNING("Learning", "सिकाइ"),
    DASHA_KW_LOSSES("Losses", "हानि"),
    DASHA_KW_LOVE("Love", "प्रेम"),
    DASHA_KW_LUCK("Luck", "भाग्य"),
    DASHA_KW_MARRIAGE("Marriage", "विवाह"),
    DASHA_KW_MOTHER("Mother", "आमा"),
    DASHA_KW_PAST("Past", "भूतकाल"),
    DASHA_KW_PEACE("Peace", "शान्ति"),
    DASHA_KW_PUBLIC("Public", "सार्वजनिक"),
    DASHA_KW_RESEARCH("Research", "अनुसन्धान"),
    DASHA_KW_SELF("Self", "आत्म"),
    DASHA_KW_SERVICE("Service", "सेवा"),
    DASHA_KW_SPEECH("Speech", "वाणी"),
    DASHA_KW_STATUS("Status", "स्थिति"),
    DASHA_KW_TRANSFORMATION("Transformation", "रूपान्तरण"),
    DASHA_KW_TRAVEL("Travel", "यात्रा"),
    DASHA_KW_VITALITY("Vitality", "जीवनशक्ति"),
    DASHA_KW_WEALTH("Wealth", "धन"),
    DASHA_KW_WISDOM("Wisdom", "बुद्धि"),
    DASHA_LAST_IN_MAHADASHA("Current Antardasha is the last in this Mahadasha", "हालको अन्तर्दशा यस महादशाको अन्तिम हो"),
    DASHA_LEVEL_ANTARDASHA("Antardasha", "अन्तर्दशा"),
    DASHA_LEVEL_ANTARDASHAS("Antardashas", "अन्तर्दशाहरू"),
    DASHA_LEVEL_DEHADASHA("Dehadasha", "देहदशा"),
    DASHA_LEVEL_MAHADASHA("Mahadasha", "महादशा"),
    DASHA_LEVEL_PRANADASHA("Pranadasha", "प्राणदशा"),
    DASHA_LEVEL_PRATYANTARDASHA("Pratyantardasha", "प्रत्यन्तर्दशा"),
    DASHA_LEVEL_SOOKSHMADASHA("Sookshmadasha", "सूक्ष्मदशा"),
    DASHA_LORD("Lord", "स्वामी"),
    DASHA_MAHADASHA("Mahadasha", "महादशा"),
    DASHA_MAJOR_PERIOD_YEARS("Major period (years)", "मुख्य अवधि (वर्ष)"),
    DASHA_MARS("Mars Dasha Theme", "मंगल दशा विषय"),
    DASHA_MERCURY("Mercury Dasha Theme", "बुध दशा विषय"),
    DASHA_METHOD_1("1. Strengthen the Dasha lord through appropriate remedies", "१. उपयुक्त उपायहरू मार्फत दशा स्वामीलाई बलियो बनाउनुहोस्"),
    DASHA_METHOD_2("2. If Dasha lord is weak in your chart, increase mantra and charity", "२. यदि तपाइँको कुण्डलीमा दशा स्वामी कमजोर छ भने, मन्त्र र दान बढाउनुहोस्"),
    DASHA_METHOD_3("3. Observe the weekday of the Dasha lord with fasting or worship", "३. व्रत वा पूजाको साथ दशा स्वामीको बार मनाउनुहोस्"),
    DASHA_METHOD_4("4. Avoid major decisions during Dasha lord's retrograde", "४. दशा स्वामी वक्री भएको बेला ठूला निर्णयहरू नगर्नुहोस्"),
    DASHA_METHOD_5("5. Wear the appropriate color on the Dasha lord's day", "५. दशा स्वामीको दिन उपयुक्त रंग लगाउनुहोस्"),
    DASHA_METHOD_TITLE("DURING ANY DASHA PERIOD:", "कुनै पनि दशा अवधिमा:"),
    DASHA_MOON("Moon Dasha Theme", "चन्द्रमा दशा विषय"),
    DASHA_NOT_AVAILABLE("%s calculation not available for this chart.", "%s गणना यो कुण्डलीको लागि उपलब्ध छैन।"),
    DASHA_NO_ACTIVE_PERIOD("No active Dasha period", "कुनै सक्रिय दशा अवधि छैन"),
    DASHA_NO_CHART("No chart selected. Please select a birth chart to view dasha periods.", "कुनै कुण्डली चयन गरिएको छैन। दशा अवधिहरू हेर्न कृपया जन्म कुण्डली चयन गर्नुहोस्।"),
    DASHA_NO_CHART_MESSAGE("Please select or create a birth profile\nto view the Dasha timeline.", "दशा समयरेखा हेर्न कृपया जन्म प्रोफाइल\nछान्नुहोस् वा बनाउनुहोस्।"),
    DASHA_NO_CHART_SELECTED("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
    DASHA_NO_CURRENT_PERIOD("No current period active", "कुनै वर्तमान अवधि सक्रिय छैन"),
    DASHA_PADA("Pada", "पाद"),
    DASHA_PERCENT_COMPLETE("%s%% complete", "%s%% पूरा"),
    DASHA_PERIOD("Period", "अवधि"),
    DASHA_PERIODS_SEQUENCE("Dasha Periods (Vimshottari Sequence)", "दशा अवधिहरू (विम्शोत्तरी क्रम)"),
    DASHA_PERIOD_INSIGHTS("Period Insights", "अवधि अन्तर्दृष्टि"),
    DASHA_PERIOD_NAME("%s: %s", "%s: %s"),
    DASHA_PRANA("Prana", "प्राण"),
    DASHA_PRANADASHA("Pranadasha", "प्राणदशा"),
    DASHA_PRATYANTAR("Pratyantar", "प्रत्यन्तर"),
    DASHA_PRATYANTARDASHA("Pratyantardasha:", "प्रत्यन्तर्दशा:"),
    DASHA_PREVIEW("Dasha Preview", "दशा पूर्वावलोकन"),
    DASHA_PROGRESS("Progress", "प्रगति"),
    DASHA_RAHU("Rahu Dasha Theme", "राहु दशा विषय"),
    DASHA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    DASHA_REC_JUPITER("Expand your horizons through education, travel, or spiritual practices.", "शिक्षा, यात्रा वा आध्यात्मिक अभ्यासहरूको माध्यमबाट आफ्नो क्षितिज विस्तार गर्नुहोस्।"),
    DASHA_REC_KETU("Practice detachment and focus on spiritual development.", "वैराग्यको अभ्यास गर्नुहोस् र आध्यात्मिक विकासमा ध्यान दिनुहोस्।"),
    DASHA_REC_MARS("Channel your energy into physical activities and competitive pursuits.", "आफ्नो ऊर्जालाई शारीरिक गतिविधि र प्रतिस्पर्धात्मक प्रयासहरूमा प्रयोग गर्नुहोस्।"),
    DASHA_REC_MERCURY("Focus on learning, communication, and intellectual growth.", "सिकाइ, सञ्चार र बौद्धिक वृद्धिमा ध्यान दिनुहोस्।"),
    DASHA_REC_MOON("Prioritize emotional well-being and nurturing relationships.", "भावनात्मक कल्याण र पोषणपूर्ण सम्बन्धहरूलाई प्राथमिकता दिनुहोस्।"),
    DASHA_REC_RAHU("Explore unconventional paths while staying grounded.", "जमिनमा रहँदै अपरम्परागत मार्गहरू अन्वेषण गर्नुहोस्।"),
    DASHA_REC_SATURN("Embrace discipline, hard work, and long-term planning.", "अनुशासन, कडा परिश्रम र दीर्घकालीन योजनालाई अँगाल्नुहोस्।"),
    DASHA_REC_SUN("Engage in activities that build confidence and leadership skills.", "आत्मविश्वास र नेतृत्व कौशल विकास गर्ने गतिविधिहरूमा संलग्न हुनुहोस्।"),
    DASHA_REC_VENUS("Cultivate beauty, art, and harmonious relationships.", "सौन्दर्य, कला र सामञ्जस्यपूर्ण सम्बन्धहरू विकास गर्नुहोस्।"),
    DASHA_REL_FOCUS("Dasha Period Relationship Focus", "दशा अवधि सम्बन्ध फोकस"),
    DASHA_REMAINING("remaining", "बाँकी"),
    DASHA_SANDHI_ALERTS("Dasha Sandhi Alerts", "दशा सन्धि अलर्टहरू"),
    DASHA_SANDHI_EXPLANATION("Sandhi periods mark transitions between planetary periods. These are sensitive times requiring careful attention as the energy shifts from one planet to another.", "सन्धि अवधिहरूले ग्रह अवधिहरूबीचको सन्क्रमण चिन्ह लगाउँछन्। यी संवेदनशील समयहरू हुन् जहाँ एउटा ग्रहबाट अर्को ग्रहमा ऊर्जा परिवर्तन हुन्छ।"),
    DASHA_SANDHI_NOTE("Dasha Sandhi (junction periods) occur when transitioning between planetary periods and are considered sensitive times requiring careful attention.", "दशा सन्धि (जोड अवधिहरू) ग्रह अवधिहरूबीच सन्क्रमण हुँदा हुन्छ र यी संवेदनशील समयहरू मानिन्छन्।"),
    DASHA_SATURN("Saturn Dasha Theme", "शनि दशा विषय"),
    DASHA_SHORT_ASH("Ash", "अष्टो"),
    DASHA_SHORT_CHA("Cha", "चर"),
    DASHA_SHORT_SUD("Sud", "सुद"),
    DASHA_SHORT_VIM("Vim", "विं"),
    DASHA_SHORT_YOG("Yog", "यो"),
    DASHA_SOOKSHMA("Sookshma", "सूक्ष्म"),
    DASHA_SOOKSHMADASHA("Sookshmadasha", "सूक्ष्मदशा"),
    DASHA_SPECIFIC_BENEFIT_REDUCE("Reduces difficulties during challenging Dasha", "काठिन दशाहरूमा कठिनाइहरू कम गर्दछ"),
    DASHA_SPECIFIC_BENEFIT_TRANSFORM("Transforms karmic lessons into growth opportunities", "कार्मिक पाठहरूलाई विकासका अवसरहरूमा बदल्छ"),
    DASHA_SPECIFIC_CAUTION("Be especially careful during Sade Sati (Saturn's 7.5 year transit over Moon)", "साढे साती (शनिको साढे ७ वर्षे गोचर) को समयमा विशेष सावधान रहनुहोस्"),
    DASHA_SPECIFIC_DESC("Special remedies to perform when %s period is running.", "%s अवधि चलिरहेको बेला गर्नुपर्ने विशेष उपायहरू।"),
    DASHA_SPECIFIC_METHOD("Since %s is weak in your chart (%s), during its Dasha:\n\n1. Chant its mantra daily (108 times minimum)\n2. Perform charity on %s\n3. Wear %s's colors\n4. Fast on %s if possible\n5. Worship the ruling deity regularly", "%s तपाईंको कुण्डलीमा कमजोर (%s) भएकोले, यसको दशामा:\n\n१. यसको मन्त्र दैनिक जप गर्नुहोस् (कम्तिमा १०८ पटक)\n२. %s मा दान गर्नुहोस्\n३. %s को रंगहरू लगाउनुहोस्\n४. यदि सम्भव छ भने %s मा व्रत बस्नुहोस्\n५. नियमित रूपमा इष्ट देवताको पूजा गर्नुहोस्"),
    DASHA_SPECIFIC_TIMING("During %s Mahadasha or Antardasha", "%s महादशा वा अन्तर्दशाको समयमा"),
    DASHA_SPECIFIC_TITLE("During %s Dasha/Antardasha", "%s दशा/अन्तर्दशाको समयमा"),
    DASHA_SPIRITUAL_FOCUS("Dasha Period Spiritual Focus", "दशा अवधि आध्यात्मिक फोकस"),
    DASHA_STARTS("Starts %s", "%s मा सुरु हुन्छ"),
    DASHA_STATUS("Status", "स्थिति"),
    DASHA_SUBTLE_PERIOD_DAYS("Subtle period (days)", "सूक्ष्म अवधि (दिन)"),
    DASHA_SUB_PERIODS("%d sub-periods", "%d उप-अवधिहरू"),
    DASHA_SUB_PERIOD_MODIFIER(
        "The %s sub-period modifies these themes with its own energies.",
        "%s उप-अवधिले यी विषयहरूलाई आफ्नै ऊर्जाका साथ परिमार्जन गर्दछ।"
    ),
    DASHA_SUB_PERIOD_MONTHS("Sub-period (months)", "उप-अवधि (महिना)"),
    DASHA_SUB_SUB_PERIOD_WEEKS("Sub-sub-period (weeks)", "उप-उप-अवधि (हप्ता)"),
    DASHA_SUDARSHANA("Sudarshana", "सुदर्शन"),
    DASHA_SUDARSHANA_DESC("Chakra Dasha from Lagna, Moon, and Sun simultaneously", "लग्न, चन्द्र र सूर्यबाट एक साथ चक्र दशा"),
    DASHA_SUDARSHANA_DURATION("Triple view", "त्रिपक्षीय दृश्य"),
    DASHA_SUN("Sun Dasha Theme", "सूर्य दशा विषय"),
    DASHA_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
    DASHA_TIMING("Throughout the Dasha period", "दशा अवधि भर"),
    DASHA_TITLE_CHARA("Chara Dasha", "कारा दशा"),
    DASHA_TITLE_YOGINI("Yogini Dasha", "योगिनी दशा"),
    DASHA_TODAY("Today", "आज"),
    DASHA_TOMORROW("Tomorrow", "भोलि"),
    DASHA_TOTAL_CYCLE("Total Cycle: 120 Years", "कुल चक्र: १२० वर्ष"),
    DASHA_TRANSITION("transition", "सन्क्रमण"),
    DASHA_UNABLE_CALCULATE("Unable to calculate current dasha period", "हालको दशा अवधि गणना गर्न असक्षम"),
    DASHA_UPCOMING("Upcoming Periods", "आगामी अवधिहरू"),
    DASHA_UPCOMING_TRANSITIONS("%1\$d upcoming transition(s) within %2\$d days", "%2\$d दिनभित्र %1\$d आगामी सन्क्रमण(हरू)"),
    DASHA_VENUS("Venus Dasha Theme", "शुक्र दशा विषय"),
    DASHA_VIEW_DETAILS("View Details", "थप विवरण"),
    DASHA_VIEW_SYSTEM("View %s", "%s हेर्नुहोस्"),
    DASHA_VIMSHOTTARI("Vimshottari Dasha", "विम्शोत्तरी दशा"),
    DASHA_VIMSHOTTARI_DESC("Standard 120-year planetary cycle based on Nakshatra at moon's position.", "चन्द्रमा रहेको नक्षत्रमा आधारित मानक १२० वर्षे ग्रह चक्र।"),
    DASHA_VIMSHOTTARI_TITLE("Vimshottari Dasha", "विंशोत्तरी दशा"),
    DASHA_VIMSOTTARI("Vimsottari", "तपाईंको"),
    DASHA_VIMSOTTARI_DESC("Most widely used Nakshatra-based planetary period system", "सबैभन्दा बढी प्रयोग हुने नक्षत्र-आधारित ग्रह अवधि प्रणाली"),
    DASHA_VIMSOTTARI_DURATION("120 years", "१२० वर्ष"),
    DASHA_VIMSOTTARI_NAME("Vimsottari", "विंशोत्तरी"),
    DASHA_WEALTH_FOCUS("Dasha Period Wealth Focus", "दशा अवधि धन फोकस"),
    DASHA_YEARS_ABBR("yrs", "वर्ष"),
    DASHA_YOGINI("Yogini", "योगिनी"),
    DASHA_YOGINI_DESC("Feminine energy-based system, especially for female charts", "स्त्री ऊर्जा-आधारित प्रणाली, विशेष गरी महिला कुण्डलीको लागि"),
    DASHA_YOGINI_DURATION("36 years", "३६ वर्ष"),
    DASHA_YOGINI_TITLE("Yogini Dasha", "योगिनी दशा"),
    KALACHAKRA_APPLICABILITY("System Applicability", "प्रणाली प्रयोज्यता"),
    KALACHAKRA_APSAVYA("Apsavya (Retrograde)", "अपसव्य (उल्टो)"),
    KALACHAKRA_AREA_AGRICULTURE("Agriculture", "कृषि"),
    KALACHAKRA_AREA_ARTS("Arts", "कला"),
    KALACHAKRA_AREA_COMMUNICATION("Communication", "सञ्चार"),
    KALACHAKRA_AREA_CONSTRUCTION("Construction", "निर्माण"),
    KALACHAKRA_AREA_EDUCATION("Education", "शिक्षा"),
    KALACHAKRA_AREA_ENGINEERING("Engineering", "इन्जिनियरिङ"),
    KALACHAKRA_AREA_FINANCE("Finance", "वित्त"),
    KALACHAKRA_AREA_HEALING("Healing", "उपचार"),
    KALACHAKRA_AREA_LEADERSHIP("Leadership", "नेतृत्व"),
    KALACHAKRA_AREA_MILITARY("Military", "सैनिक"),
    KALACHAKRA_AREA_PSYCHOLOGY("Psychology", "मनोविज्ञान"),
    KALACHAKRA_AREA_REAL_ESTATE("Real estate", "घरजग्गा"),
    KALACHAKRA_AREA_SPIRITUALITY("Spirituality", "अध्यात्म"),
    KALACHAKRA_AREA_SPORTS("Sports", "खेलकुद"),
    KALACHAKRA_AREA_TECHNOLOGY("Technology", "प्रविधि"),
    KALACHAKRA_AREA_TRAVEL("Travel", "यात्रा"),
    KALACHAKRA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    KALACHAKRA_BODY("Body", "शरीर"),
    KALACHAKRA_BRIEF_AQUARIUS("Innovation, humanity, progress.", "नवप्रवर्तन, मानवता, प्रगति।"),
    KALACHAKRA_BRIEF_ARIES("Energy, initiative, new starts.", "ऊर्जा, पहल, नयाँ शुरुआत।"),
    KALACHAKRA_BRIEF_CANCER("Emotions, home, nurturing.", "भावनाहरू, घर, पालनपोषण।"),
    KALACHAKRA_BRIEF_CAPRICORN("Career, discipline, achievement.", "क्यारियर, अनुशासन, उपलब्धि।"),
    KALACHAKRA_BRIEF_GEMINI("Communication, learning, versatility.", "सञ्चार, सिकाइ, बहुमुखी प्रतिभा।"),
    KALACHAKRA_BRIEF_LEO("Recognition, creativity, authority.", "मान्यता, रचनात्मकता, अधिकार।"),
    KALACHAKRA_BRIEF_LIBRA("Balance, relationships, harmony.", "सन्तुलन, सम्बन्ध, सद्भाव।"),
    KALACHAKRA_BRIEF_PISCES("Spirituality, imagination, liberation.", "आध्यात्मिकता, कल्पना, मुक्ति।"),
    KALACHAKRA_BRIEF_SAGITTARIUS("Expansion, wisdom, fortune.", "विस्तार, ज्ञान, भाग्य।"),
    KALACHAKRA_BRIEF_SCORPIO("Transformation, depth, intensity.", "रूपान्तरण, गहिराई, तीव्रता।"),
    KALACHAKRA_BRIEF_TAURUS("Stability, wealth, comfort.", "स्थिरता, धन, आराम।"),
    KALACHAKRA_BRIEF_VIRGO("Analysis, health, service.", "विश्लेषण, स्वास्थ्य, सेवा।"),
    KALACHAKRA_CAUTION_AQUARIUS("Circulation issues, detachment, rebellion", "रक्तसञ्चार समस्या, वैराग्य, विद्रोह"),
    KALACHAKRA_CAUTION_ARIES("Head injuries, fevers, impulsive actions", "टाउकोको चोट, ज्वरो, आवेगपूर्ण कार्यहरू"),
    KALACHAKRA_CAUTION_CANCER("Emotional sensitivity, digestive issues, attachment", "भावनात्मक संवेदनशीलता, पाचन समस्या, मोह"),
    KALACHAKRA_CAUTION_CAPRICORN("Joint problems, depression, workaholism", "जोर्नीको समस्या, निराशा, कामको लत"),
    KALACHAKRA_CAUTION_GEMINI("Nervous tension, respiratory issues, inconsistency", "स्नायु तनाव, श्वासप्रश्वासको समस्या, अस्थिरता"),
    KALACHAKRA_CAUTION_HEALTH("Physical health requires attention", "शारीरिक स्वास्थ्यमा ध्यान दिनु आवश्यक छ"),
    KALACHAKRA_CAUTION_LEO("Heart issues, ego conflicts, excessive pride", "मुटुको समस्या, अहंकार विवाद, अत्यधिक गर्व"),
    KALACHAKRA_CAUTION_LIBRA("Kidney issues, indecision, relationship dependency", "मृगौलाको समस्या, अनिर्णय, सम्बन्धमा निर्भरता"),
    KALACHAKRA_CAUTION_PISCES("Foot problems, escapism, boundary issues", "खुट्टाको समस्या, पलायनवाद, सीमा समस्या"),
    KALACHAKRA_CAUTION_SAGITTARIUS("Liver issues, over-expansion, dogmatism", "कलेजोको समस्या, अत्यधिक विस्तार, कट्टरता"),
    KALACHAKRA_CAUTION_SCORPIO("Reproductive issues, intensity, control issues", "प्रजनन समस्या, तीव्रता, नियन्त्रण समस्या"),
    KALACHAKRA_CAUTION_TAURUS("Throat issues, dietary excess, stubbornness", "घाँटीको समस्या, खानपानमा अधिकता, जिद्दीपन"),
    KALACHAKRA_CAUTION_VIRGO("Digestive problems, anxiety, over-criticism", "पाचन समस्या, चिन्ता, अत्यधिक आलोचना"),
    KALACHAKRA_CURRENT("Current Period", "वर्तमान अवधि"),
    KALACHAKRA_DASHA_ABOUT("About Kalachakra Dasha", "कालचक्र दशाको बारेमा"),
    KALACHAKRA_DASHA_ABOUT_DESC("Kalachakra Dasha is a highly respected Nakshatra-based timing system from BPHS, particularly useful for health predictions and spiritual transformation. It operates on the principle that body (Deha) and soul (Jeeva) follow different but related cycles. Savya (clockwise) and Apsavya (anti-clockwise) groups determine life's flow direction.", "कालचक्र दशा BPHS बाट अत्यन्त सम्मानित नक्षत्र-आधारित समय प्रणाली हो, विशेष गरी स्वास्थ्य भविष्यवाणी र आध्यात्मिक रूपान्तरणको लागि उपयोगी। यो देह र आत्माले फरक तर सम्बन्धित चक्रहरू पछ्याउँछन् भन्ने सिद्धान्तमा काम गर्छ। सव्य (घडीको दिशामा) र अपसव्य (घडीको विपरीत दिशामा) समूहहरूले जीवनको प्रवाह दिशा निर्धारण गर्दछन्।"),
    KALACHAKRA_DASHA_SUBTITLE("Body-Soul Timing System", "देह-आत्मा समय प्रणाली"),
    KALACHAKRA_DASHA_TITLE("Kalachakra Dasha", "कालचक्र दशा"),
    KALACHAKRA_DEHA("Deha", "देह"),
    KALACHAKRA_DEHA_ANALYSIS("Deha (Body) Analysis", "देह (शरीर) विश्लेषण"),
    KALACHAKRA_DEHA_JEEVA("Deha-Jeeva", "देह-जीव"),
    KALACHAKRA_DEHA_JEEVA_SUBTITLE("Body and Soul Relationship", "शरीर र आत्माको सम्बन्ध"),
    KALACHAKRA_DEHA_JEEVA_TITLE("Deha-Jeeva Analysis", "देह-जीव विश्लेषण"),
    KALACHAKRA_DEHA_LORD("Deha Lord", "देह स्वामी"),
    KALACHAKRA_DESC_APSAVYA("Anti-clockwise progression - more karmic intensity and transformation", "राशिहरूको घडीको विपरीत दिशामा प्रगति - अधिक कार्मिक तीव्रता र परिवर्तन"),
    KALACHAKRA_DESC_SAVYA("Clockwise progression through signs - generally smoother life flow", "राशिहरूको घडीको दिशामा प्रगति - सामान्यतया सहज जीवन प्रवाह"),
    KALACHAKRA_EFFECTS("Current Effects", "वर्तमान प्रभावहरू"),
    KALACHAKRA_EFFECT_AQUARIUS("Innovation, humanitarian concerns, and group activities. Saturn/Rahu bring progressive change.", "नवप्रवर्तन, मानवीय चासो र समूह गतिविधिहरू। शनि/राहुले प्रगतिशील परिवर्तन ल्याउँछन्।"),
    KALACHAKRA_EFFECT_ARIES("Period of initiative, new beginnings, and physical vitality. Mars energy brings action and courage.", "पहल, नयाँ शुरुआत र शारीरिक जोसको अवधि। मंगलको ऊर्जाले कर्म र साहस ल्याउँछ।"),
    KALACHAKRA_EFFECT_CANCER("Emotional growth, home, and family matters take center stage. Moon brings nurturing energy.", "भावनात्मक वृद्धि, घर र पारिवारिक मामिलाहरू मुख्य हुन्छन्। चन्द्रमाले पोषण गर्ने ऊर्जा ल्याउँछ।"),
    KALACHAKRA_EFFECT_CAPRICORN("Career, discipline, and long-term achievements. Saturn brings structure and maturity.", "क्यारियर, अनुशासन र दीर्घकालीन उपलब्धिहरू। शनिले संरचना र परिपक्वता ल्याउँछ।"),
    KALACHAKRA_EFFECT_GEMINI("Communication, learning, and intellectual pursuits are highlighted. Mercury brings versatility.", "सञ्चार, सिकाइ र बौद्धिक प्रयासहरूलाई जोड दिइन्छ। बुधले बहुमुखी प्रतिभा ल्याउँछ।"),
    KALACHAKRA_EFFECT_LEO("Recognition, authority, and creative self-expression. Sun brings confidence and vitality.", "मान्यता, अधिकार र रचनात्मक आत्म-अभिव्यक्ति। सूर्यले आत्मविश्वास र जोस ल्याउँछ।"),
    KALACHAKRA_EFFECT_LIBRA("Partnerships, balance, and aesthetic pursuits. Venus brings harmony and relationships.", "साझेदारी, सन्तुलन र सौन्दर्य प्रयासहरू। शुक्रले सद्भाव र सम्बन्धहरू ल्याउँछ।"),
    KALACHAKRA_EFFECT_PISCES("Spirituality, imagination, and transcendence. Jupiter brings divine connection and liberation.", "आध्यात्मिकता, कल्पना र पारलौकिकता। बृहस्पतिले ईश्वरीय सम्बन्ध र मुक्ति ल्याउँछ।"),
    KALACHAKRA_EFFECT_SAGITTARIUS("Higher learning, philosophy, and expansion. Jupiter brings wisdom and fortune.", "उच्च सिकाइ, दर्शन र विस्तार। बृहस्पतिले ज्ञान र भाग्य ल्याउँछ।"),
    KALACHAKRA_EFFECT_SCORPIO("Deep transformation, hidden matters, and research. Mars/Ketu bring intensity and rebirth.", "गहिरो रूपान्तरण, गुप्त मामिला र अनुसन्धान। मंगल/केतुले तीव्रता र पुनर्जन्म ल्याउँछन्।"),
    KALACHAKRA_EFFECT_TAURUS("Focus on stability, wealth accumulation, and sensory pleasures. Venus brings comfort and beauty.", "स्थिरता, धन सञ्चय र इन्द्रिय सुखमा ध्यान। शुक्रले आराम र सौन्दर्य ल्याउँछ।"),
    KALACHAKRA_EFFECT_VIRGO("Analysis, health consciousness, and service. Mercury brings discrimination and healing potential.", "विश्लेषण, स्वास्थ्य चेतना र सेवा। बुधले विवेक र निको पार्ने क्षमता ल्याउँछ।"),
    KALACHAKRA_GROUP_APSAVYA("Apsavya (Retrograde)", "अपसव्य (उल्टो)"),
    KALACHAKRA_GROUP_SAVYA("Savya (Direct)", "सव्य (सीधो)"),
    KALACHAKRA_GUIDANCE("Guidance", "मार्गदर्शन"),
    KALACHAKRA_GUIDANCE_1("Monitor transits over Deha Rashi for physical health events", "शारीरिक स्वास्थ्य घटनाहरूको लागि देह राशि माथिको गोचर निगरानी गर्नुहोस्"),
    KALACHAKRA_GUIDANCE_2("Observe transits over Jeeva Rashi for spiritual opportunities", "आध्यात्मिक अवसरहरूको लागि जीव राशि माथिको गोचर अवलोकन गर्नुहोस्"),
    KALACHAKRA_GUIDANCE_3("When Deha and Jeeva sign lords are strong in transit, both health and spiritual progress are favored", "जब देह र जीव राशिका स्वामीहरू गोचरमा बलियो हुन्छन्, स्वास्थ्य र आध्यात्मिक प्रगति दुबै अनुकूल हुन्छन्")
}
