package com.astro.storm.core.common

enum class StringKeyGeneralPart6(override val en: String, override val ne: String) : StringKeyInterface {
    KEMADRUMA_ACTIVE_MODERATE("Active (Moderate)", "सक्रिय (मध्यम)"),
    KEMADRUMA_ACTIVE_SEVERE("Active (Severe)", "सक्रिय (गम्भीर)"),
    KEMADRUMA_ANXIETY("Anxiety Tendency", "चिन्ता प्रवृत्ति"),
    KEMADRUMA_CANCELLATIONS("Cancellation Factors", "रद्दीकरण कारकहरू"),
    KEMADRUMA_CONFIDENCE("Confidence Level", "आत्मविश्वास स्तर"),
    KEMADRUMA_DEPRESSION_RISK("Depression Risk", "अवसाद जोखिम"),
    KEMADRUMA_EMOTIONAL("Emotional Impact", "भावनात्मक प्रभाव"),
    KEMADRUMA_FAMILY_SUPPORT("Family Support", "पारिवारिक समर्थन"),
    KEMADRUMA_FINANCIAL("Financial Impact", "आर्थिक प्रभाव"),
    KEMADRUMA_FORMATION("Formation Details", "गठन विवरण"),
    KEMADRUMA_FRIENDSHIP("Friendship Quality", "मित्रता गुणस्तर"),
    KEMADRUMA_FULLY_CANCELLED("Fully Cancelled", "पूर्ण रूपमा रद्द"),
    KEMADRUMA_ISOLATION("Isolation Tendency", "एकान्त प्रवृत्ति"),
    KEMADRUMA_MENTAL_PEACE("Mental Peace", "मानसिक शान्ति"),
    KEMADRUMA_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
    KEMADRUMA_MOSTLY_CANCELLED("Mostly Cancelled", "प्रायः रद्द"),
    KEMADRUMA_NOT_PRESENT("Not Present", "उपस्थित छैन"),
    KEMADRUMA_PARTIALLY_CANCELLED("Partially Cancelled", "आंशिक रूपमा रद्द"),
    KEMADRUMA_SOCIAL("Social Impact", "सामाजिक प्रभाव"),
    KEMADRUMA_STABILITY("Emotional Stability", "भावनात्मक स्थिरता"),
    KEMADRUMA_SUBTITLE("Moon Support Analysis", "चन्द्र समर्थन विश्लेषण"),
    KEMADRUMA_TITLE("Kemadruma Yoga Analysis", "केमद्रुम योग विश्लेषण"),
    KEMADRUMA_WEAKLY_CANCELLED("Weakly Cancelled", "कमजोर रूपमा रद्द"),
    KEMADRUMA_WEALTH_RETENTION("Wealth Retention", "धन संरक्षण"),
    KEMA_ABOUT_DESC("Kemadruma Yoga forms when the Moon has no planets (except Sun, Rahu, Ketu) in the 2nd and 12th houses from it, and no planets are in Kendra from the Moon or Lagna.\n\nIt is considered an inauspicious yoga indicating loneliness, mental unrest, and financial instability. However, it is often cancelled (Bhanga) by the presence of planets in Kendra houses or if the Moon interacts with other planets.", "केमद्रुम योग तब बन्छ जब चन्द्रमाको दोस्रो र बाह्रौं भावमा कुनै ग्रहहरू (सूर्य, राहु, केतु बाहेक) हुँदैनन्, र चन्द्रमा वा लग्नबाट केन्द्रमा कुनै ग्रहहरू हुँदैनन्।\n\nयसलाई अशुभ योग मानिन्छ जसले एक्लोपन, मानसिक अशान्ति र आर्थिक अस्थिरतालाई संकेत गर्दछ। यद्यपि, केन्द्र भावहरूमा ग्रहहरूको उपस्थिति वा चन्द्रमाले अन्य ग्रहहरूसँग अन्तरक्रिया गरेमा यो अक्सर भंग हुन्छ।"),
    KEMA_ABOUT_TITLE("About Kemadruma Yoga", "केमद्रुम योगको बारेमा"),
    KEMA_AFTER_MOON("After Moon", "चन्द्रमा पछि"),
    KEMA_BEFORE_MOON("Before Moon", "चन्द्रमा अघि"),
    KEMA_BRIGHTNESS("Brightness", "चमक"),
    KEMA_CANCELLATIONS("Cancellations", "भंग"),
    KEMA_CANCELLATIONS_FOUND("%1\$2 Cancellation(s) Found", "%1\$2 भंग(हरू) फेला पर्यो"),
    KEMA_CONDITION_MET("No planets in houses adjacent to Moon - Kemadruma condition met", "चन्द्रमाको नजिकका भावहरूमा कुनै ग्रह छैन - केमद्रुम शर्त पूरा भयो"),
    KEMA_FORMATION_12TH_EMPTY("12th house from Moon is empty.", "चन्द्रमाबाट बाह्रौं भाव खाली छ।"),
    KEMA_FORMATION_2ND_EMPTY("2nd house from Moon is empty.", "चन्द्रमाबाट दोस्रो भाव खाली छ।"),
    KEMA_FORMATION_DETAILS("Formation Details", "योग निर्माण विवरण"),
    KEMA_FORMATION_MAIN("Moon lacks planetary support in adjacent houses.", "चन्द्रमालाई नजिकका भावहरूमा ग्रहहरूको समर्थन छैन।"),
    KEMA_FORMATION_STRENGTH("Formation strength: %1\$2%%", "योग बल: %1\$2%%"),
    KEMA_FORMATION_UNASPECTED("Moon has no planetary conjunction.", "चन्द्रमाको कुनै ग्रहसँग युति छैन।"),
    KEMA_FORMED("Kemadruma Yoga is formed in this chart", "यो कुण्डलीमा केमद्रुम योग बनेको छ"),
    KEMA_IMPACTS("Impacts", "प्रभावहरू"),
    KEMA_MOON("Moon", "चन्द्रमा"),
    KEMA_MOON_HOUSE("Moon's House", "चन्द्रमाको भाव"),
    KEMA_MOON_POSITION("Moon Position", "चन्द्रमाको स्थिति"),
    KEMA_MOON_STRENGTH("Moon Strength:", "चन्द्रमा बल:"),
    KEMA_NA("Not Applicable", "लागू हुँदैन"),
    KEMA_NAKSHATRA("Nakshatra", "नक्षत्र"),
    KEMA_NOT_FORMED("Kemadruma Yoga is not formed", "केमद्रुम योग बनेको छैन"),
    KEMA_NO_CANCELLATIONS("No Cancellations Found", "कुनै भंग फेला परेन"),
    KEMA_NO_CANCELLATIONS_DESC("No Kemadruma Bhanga (cancellation) factors were found in your chart.", "तपाईंको कुण्डलीमा कुनै केमद्रुम भंग कारकहरू फेला परेनन्।"),
    KEMA_NO_IMPACTS("No Negative Impacts", "कुनै नकारात्मक प्रभाव छैन"),
    KEMA_NO_IMPACTS_DESC("Moon is well-supported, ensuring emotional stability and mental peace.", "चन्द्रमा राम्रोसँग समर्थित छ, जसले भावनात्मक स्थिरता र मानसिक शान्ति सुनिश्चित गर्दछ।"),
    KEMA_NO_REMEDIES("No Remedies Needed", "कुनै उपाय आवश्यक छैन"),
    KEMA_NO_REMEDIES_DESC("Since Kemadruma Yoga is not formed or is fully cancelled, no remedies are required.", "केमद्रुम योग नबनेको वा पूर्ण रूपमा भंग भएकोले, कुनै उपाय आवश्यक छैन।"),
    KEMA_PAKSHA("Paksha", "पक्ष"),
    KEMA_REASON_12TH("No planets in 12th house from Moon", "चन्द्रमाबाट बाह्रौं भावमा कुनै ग्रह छैन"),
    KEMA_REASON_2ND("No planets in 2nd house from Moon", "चन्द्रमाबाट दोस्रो भावमा कुनै ग्रह छैन"),
    KEMA_REASON_CONJUNCT("Moon is not conjunct with any planet", "चन्द्रमा कुनै ग्रहसँग युतिमा छैन"),
    KEMA_SCREEN_TITLE("Kemadruma Yoga", "केमद्रुम योग"),
    KEMA_SUBTITLE("Moon Isolation Analysis", "चन्द्रमा एक्लोपन विश्लेषण"),
    KEMA_SURROUNDING_HOUSES("Surrounding Houses Analysis", "वरपरका भावहरूको विश्लेषण"),
    KETU_HOUSE("Ketu House", "केतु भाव"),
    KETU_NAKSHATRA("Ketu Nakshatra", "केतु नक्षत्र"),
    KETU_SIGN("Ketu Sign", "केतु राशि"),
    KETU_TRANSIT_HOUSE("Ketu Transit House", "केतु गोचर भाव"),
    KEYWORD_ACTION("Action", "कार्य"),
    KEYWORD_AMBITION("Ambition", "महत्त्वाकांक्षा"),
    KEYWORD_APPEARANCE("Appearance", "रूप"),
    KEYWORD_ART("Art", "कला"),
    KEYWORD_ASPIRATIONS("Aspirations", "आंकाक्षा"),
    KEYWORD_AUTHORITY("Authority", "अधिकार"),
    KEYWORD_BUSINESS("Business", "व्यापार"),
    KEYWORD_CAREER("Career", "क्यारियर"),
    KEYWORD_CHILDREN("Children", "सन्तान"),
    KEYWORD_COMFORT("Comfort", "आराम"),
    KEYWORD_COMMUNICATION("Communication", "सञ्चार"),
    KEYWORD_COMPETITION("Competition", "प्रतिस्पर्धा"),
    KEYWORD_CONTRACTS("Contracts", "सम्झौता"),
    KEYWORD_COURAGE("Courage", "साहस"),
    KEYWORD_CREATIVITY("Creativity", "सिर्जनशीलता"),
    KEYWORD_DEBTS("Debts", "ऋण"),
    KEYWORD_DELAYS("Delays", "ढिलाइ"),
    KEYWORD_DETACHMENT("Detachment", "वैराग्य"),
    KEYWORD_DISCIPLINE("Discipline", "अनुशासन"),
    KEYWORD_ELDER_SIBLINGS("Elder Siblings", "ठूला भाइबहिनी"),
    KEYWORD_EMOTIONS("Emotions", "भावना"),
    KEYWORD_ENEMIES("Enemies", "शत्रु"),
    KEYWORD_ENERGY("Energy", "ऊर्जा"),
    KEYWORD_EXPENSES("Expenses", "खर्च"),
    KEYWORD_FAME("Fame", "नाम"),
    KEYWORD_FAMILY("Family", "परिवार"),
    KEYWORD_FATHER("Father", "पिता"),
    KEYWORD_FOOD("Food", "भोजन"),
    KEYWORD_FOREIGN("Foreign", "विदेशी"),
    KEYWORD_FOREIGN_LANDS("Foreign Lands", "विदेशी भूमि"),
    KEYWORD_FORTUNE("Fortune", "भाग्य"),
    KEYWORD_FRIENDS("Friends", "मित्रहरू"),
    KEYWORD_GAINS("Gains", "लाभ"),
    KEYWORD_GENERAL("General", "सामान्य"),
    KEYWORD_GOVERNMENT("Government", "सरकार"),
    KEYWORD_GROWTH("Growth", "विकास"),
    KEYWORD_HEALTH("Health", "स्वास्थ्य"),
    KEYWORD_HEALTH_ISSUES("Health Issues", "स्वास्थ्य समस्या"),
    KEYWORD_HIDDEN_MATTERS("Hidden Matters", "लुकेका कुराहरू"),
    KEYWORD_HIGHER_EDUCATION("Higher Education", "उच्च शिक्षा"),
    KEYWORD_HOME("Home", "घर"),
    KEYWORD_INCOME("Income", "आय"),
    KEYWORD_INHERITANCE("Inheritance", "विरासत"),
    KEYWORD_INNER_PEACE("Inner Peace", "आन्तरिक शान्ति"),
    KEYWORD_INNOVATION("Innovation", "नवीनता"),
    KEYWORD_INTELLIGENCE("Intelligence", "बुद्धि"),
    KEYWORD_INVESTMENTS("Investments", "लगानी"),
    KEYWORD_KARMA("Karma", "कर्म"),
    KEYWORD_LEADERSHIP("Leadership", "नेतृत्व"),
    KEYWORD_LEARNING("Learning", "सिकाइ"),
    KEYWORD_LIBERATION("Liberation", "मुक्ति"),
    KEYWORD_LONGEVITY("Longevity", "दीर्घायु"),
    KEYWORD_LONG_TRAVEL("Long Travel", "लामो यात्रा"),
    KEYWORD_LOSSES("Losses", "हानि"),
    KEYWORD_LOVE("Love", "प्रेम"),
    KEYWORD_MARRIAGE("Marriage", "विवाह"),
    KEYWORD_MOTHER("Mother", "माता"),
    KEYWORD_NEW_BEGINNINGS("New Beginnings", "नयाँ शुरुवात"),
    KEYWORD_PARTNERSHIP("Partnership", "साझेदारी"),
    KEYWORD_PAST("Past", "अतीत"),
    KEYWORD_PERSONALITY("Personality", "व्यक्तित्व"),
    KEYWORD_PROPERTY("Property", "सम्पत्ति"),
    KEYWORD_PUBLIC("Public", "सार्वजनिक"),
    KEYWORD_PUBLIC_DEALINGS("Public Dealings", "सार्वजनिक कारोबार"),
    KEYWORD_RELIGION("Religion", "धर्म"),
    KEYWORD_RESEARCH("Research", "अनुसन्धान"),
    KEYWORD_ROMANCE("Romance", "रोमान्स"),
    KEYWORD_SELF("Self", "स्वयम्"),
    KEYWORD_SERVICE("Service", "सेवा"),
    KEYWORD_SHORT_TRAVEL("Short Travel", "छोटो यात्रा"),
    KEYWORD_SIBLINGS("Siblings", "भाइबहिनी"),
    KEYWORD_SKILLS("Skills", "सीप"),
    KEYWORD_SPEECH("Speech", "वाणी"),
    KEYWORD_SPIRITUALITY("Spirituality", "आध्यात्मिकता"),
    KEYWORD_STATUS("Status", "स्थिति"),
    KEYWORD_TRANSFORMATION("Transformation", "रूपान्तरण"),
    KEYWORD_VALUES("Values", "मूल्य मान्यता"),
    KEYWORD_VEHICLES("Vehicles", "सवारी साधन"),
    KEYWORD_VITALITY("Vitality", "प्राणशक्ति"),
    KEYWORD_WEALTH("Wealth", "धन"),
    KEYWORD_WISDOM("Wisdom", "ज्ञान"),
    KEY_DATE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KEY_DATE_DASHA_BEGINS("%s Dasha Begins", "%s दशा शुरु"),
    KEY_DATE_DASHA_DESC("Start of %s period (%d days)", "%s अवधिको शुरुवात (%d दिन)"),
    KEY_DATE_FAVORABLE("Favorable", "अनुकूल"),
    KEY_DATE_IMPORTANT("Important", "महत्त्वपूर्ण"),
    KEY_DATE_SOLAR_RETURN("Solar Return", "सौर प्रतिफल"),
    KEY_DATE_SOLAR_RETURN_DESC("Beginning of the annual horoscope year", "वार्षिक राशिफल वर्षको शुरुवात"),
    KEY_DATE_TRANSIT("Transit", "गोचर"),
    KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टि"),
    KEY_MONTHS("Key Months", "मुख्य महिनाहरू"),
    KEY_THEMES("Key Themes", "मुख्य विषयहरू"),
    KEY_TRAITS("Key Personality Traits", "मुख्य व्यक्तित्व गुणहरू"),
    KUBERA_YOGA("Kubera Yoga", "कुबेर योग"),
    LAGNA_LABEL("Lagna", "लग्न"),
    LAKSHMI_YOGA("Lakshmi Yoga", "लक्ष्मी योग"),
    LANGUAGE_ABILITY("Language Ability", "भाषा क्षमता"),
    LEADERSHIP_STYLE("Leadership Style", "नेतृत्व शैली"),
    LEADERSHIP_TENDENCY("Leadership Tendency", "नेतृत्व प्रवृत्ति"),
    LEARNING_STYLE("Learning Style", "सिक्ने शैली"),
    LEARNING_STYLE_TITLE("Learning Style Profile", "सिक्ने शैली प्रोफाइल"),
    LESSON_TO_LEARN("Lesson to Learn", "सिक्नुपर्ने पाठ"),
    LIBERATION_INDICATORS("Liberation Indicators", "मोक्ष सूचकहरू"),
    LIBERATION_PATH("Liberation Path", "मोक्ष मार्ग"),
    LIFESTYLE_BENEFIT_ALIGN("Aligns daily life with planetary energies", "ग्रहका ऊर्जाहरूसँग दैनिक जीवनलाई मिलाउँछ"),
    LIFESTYLE_BENEFIT_COST("No cost involved", "कुनै लागत लाग्दैन"),
    LIFESTYLE_BENEFIT_HOLISTIC("Holistic and sustainable improvement", "समग्र र दिगो सुधार"),
    LIFESTYLE_BENEFIT_KARMA("Creates positive karma", "सकारात्मक कर्म सिर्जना गर्दछ"),
    LIFESTYLE_DESC("Daily habits and lifestyle modifications to strengthen %s and reduce its negative effects.", "%s लाई बलियो बनाउन र यसको नकारात्मक प्रभावहरू कम गर्न दैनिक बानी र जीवनशैली परिवर्तनहरू।"),
    LIFESTYLE_DURATION("Ongoing lifestyle adoption", "निरन्तर जीवनशैली अपनाउने"),
    LIFESTYLE_JUPITER_AVOID("Avoid disrespecting teachers or elders|Avoid unethical financial dealings", "शिक्षक वा ठूलाबाडालाई अनादर नगर्नुहोस्|अनैतिक आर्थिक व्यवहारबाट बच्नुहोस्"),
    LIFESTYLE_JUPITER_PRACTICES("Study scriptures and philosophical texts|Respect teachers, elders, and Brahmins|Practice generosity and charity|Maintain ethical conduct in all dealings|Visit temples, especially on Thursdays|Apply turmeric tilak on forehead|Teach or mentor others when possible", "शास्त्र र दार्शनिक पाठहरू अध्ययन गर्नुहोस्|शिक्षक, ठूलाबाडा र ब्राह्मणहरूलाई आदर गर्नुहोस्|उदारता र दान अभ्यास गर्नुहोस्|सबै व्यवहारमा नैतिक आचरण कायम राख्नुहोस्|मन्दिर जानुहोस्, विशेष गरी बिहीबार|निधारमा बेसारको टीका लगाउनुहोस्|सम्भव भएसम्म अरूलाई सिकाउनुहोस् वा मार्गदर्शन गर्नुहोस्"),
    LIFESTYLE_KETU_AVOID("Avoid excessive attachment to outcomes|Avoid ignoring spiritual calling", "परिणामहरूप्रति अत्यधिक आसक्त नहुनुहोस्|आध्यात्मिक बोलावटलाई बेवास्ता नगर्नुहोस्"),
    LIFESTYLE_KETU_PRACTICES("Meditate daily - at least 15-30 minutes|Practice detachment from material outcomes|Pursue spiritual knowledge|Feed dogs, especially stray dogs|Visit Ganesha temples|Study ancient wisdom and occult sciences|Practice solitude and introspection", "दैनिक ध्यान गर्नुहोस् - कम्तिमा १५-३० मिनेट|भौतिक परिणामहरूबाट वैराग्य अभ्यास गर्नुहोस्|आध्यात्मिक ज्ञानको पछि लाग्नुहोस्|कुकुरहरूलाई खुवाउनुहोस्, विशेष गरी सडक कुकुरहरू|गणेश मन्दिर जानुहोस्|प्राचीन ज्ञान र गुप्त विज्ञान अध्ययन गर्नुहोस्|एकान्त र आत्मनिरीक्षण अभ्यास गर्नुहोस्"),
    LIFESTYLE_MARS_AVOID("Avoid anger and aggression|Avoid violence and conflicts|Avoid excessive spicy food", "क्रोध र आक्रामकताबाट बच्नुहोस्|हिंसा र द्वन्द्वबाट बच्नुहोस्|अत्यधिक मसालेदार खाना नखानुहोस्"),
    LIFESTYLE_MARS_PRACTICES("Exercise regularly (physical activity is essential)|Practice martial arts, yoga, or sports|Channel energy positively through constructive work|Help younger siblings and protect the weak|Donate blood if medically fit|Recite Hanuman Chalisa daily|Maintain celibacy on Tuesdays", "नियमित व्यायाम गर्नुहोस् (शारीरिक गतिविधि आवश्यक छ)|मार्शल आर्ट, योग वा खेलकुद अभ्यास गर्नुहोस्|रचनात्मक काम मार्फत ऊर्जालाई सकारात्मक रूपमा प्रयोग गर्नुहोस्|साना दाजुभाइलाई मद्दत गर्नुहोस् र कमजोरलाई रक्षा गर्नुहोस्|यदि चिकित्सकीय रूपमा योग्य हुनुहुन्छ भने रक्तदान गर्नुहोस्|दैनिक हनुमान चालिसा पाठ गर्नुहोस्|मंगलबार ब्रह्मचर्य पालन गर्नुहोस्"),
    LIFESTYLE_MERCURY_AVOID("Avoid lies and gossips|Avoid scattering energy on too many tasks", "झूट र गफबाट बच्नुहोस्|धेरै कामहरूमा ऊर्जा छर्नु हुँदैन"),
    LIFESTYLE_MERCURY_PRACTICES("Read books and acquire new knowledge daily|Practice clear and honest communication|Learn a new skill or language|Write daily - journal, notes, or creative writing|Help students and support education|Keep your living space organized|Practice numeracy - solve puzzles or calculations", "दैनिक पुस्तकहरू पढ्नुहोस् र नयाँ ज्ञान प्राप्त गर्नुहोस्|स्पष्ट र इमानदार सञ्चार अभ्यास गर्नुहोस्|नयाँ सीप वा भाषा सिक्नुहोस्|दैनिक लेख्नुहोस् - जर्नल, नोटहरू वा सिर्जनात्मक लेखन|विद्यार्थीहरूलाई मद्दत गर्नुहोस् र शिक्षालाई समर्थन गर्नुहोस्|आफ्नो बस्ने ठाउँ व्यवस्थित राख्नुहोस्|गणित अभ्यास गर्नुहोस् - पजलहरू वा हिसाब गर्नुहोस्"),
    LIFESTYLE_MOON_AVOID("Avoid suppressing emotions|Avoid staying awake late at night", "भावनाहरू दबाउनु हुँदैन|राती अबेरसम्म नबस्नुहोस्"),
    LIFESTYLE_MOON_PRACTICES("Drink plenty of water and milk|Meditate near water bodies (rivers, lakes, sea)|Respect mother and maternal figures|Practice emotional balance and mindfulness|Keep white flowers in your room|Observe Poornima (full moon) by fasting or worship|Avoid arguments, especially with mother", "प्रशस्त पानी र दूध पिउनुहोस्|जलाशय नजिक धेयान गर्नुहोस् (नदी, ताल, समुद्र)|आमा र मातृ शक्तिलाई आदर गर्नुहोस्|भावनात्मक सन्तुलन र सजगता अभ्यास गर्नुहोस्|आफ्नो कोठामा सेतो फूल राख्नुहोस्|पूर्णिमामा व्रत वा पूजा गर्नुहोस्|विवादबाट बच्नुहोस्, विशेष गरी आमासँग"),
    LIFESTYLE_RAHU_AVOID("Avoid deception and manipulation|Avoid excessive ambition|Avoid foreign travel during Rahu Dasha without proper remedies", "धोका र हेरफेरबाट बच्नुहोस्|अत्यधिक महत्त्वाकांक्षाबाट बच्नुहोस्|उचित उपाय बिना राहु दशामा विदेश यात्रा नगर्नुहोस्"),
    LIFESTYLE_RAHU_PRACTICES("Avoid shortcuts and get-rich-quick schemes|Practice honesty in all dealings|Reduce materialistic desires|Avoid intoxicants completely|Stay grounded - avoid getting carried away|Donate to outcasts and marginalized people|Keep your thoughts positive", "सर्टकट र छिटो धनी हुने योजनाहरूबाट बच्नुहोस्|सबै व्यवहारमा इमानदारी अभ्यास गर्नुहोस्|भौतिकवादी इच्छाहरू कम गर्नुहोस्|नशाबाट पूर्ण रूपमा टाढा रहनुहोस्|यथार्थमा रहनुहोस् - बहकिनु हुँदैन|बहिष्कृत र सीमान्तकृत मानिसहरूलाई दान गर्नुहोस्|आफ्नो विचार सकारात्मक राख्नुहोस्"),
    LIFESTYLE_RECS("Lifestyle Recommendations", "जीवनशैली सिफारिसहरू"),
    LIFESTYLE_REC_PRACTICES("RECOMMENDED PRACTICES:", "सिफारिस गरिएको अभ्यासहरू:"),
    LIFESTYLE_SATURN_AVOID("Avoid laziness and procrastination|Avoid disrespecting servants or workers|Avoid alcohol and intoxicants", "आलस्य र ढिलासुस्तीबाट बच्नुहोस्|सेवक वा कामदारहरूलाई अनादर नगर्नुहोस्|रक्सी र नशालु पदार्थबाट बच्नुहोस्"),
    LIFESTYLE_SATURN_PRACTICES("Practice discipline and routine strictly|Serve the elderly, poor, and disabled|Be patient - avoid shortcuts|Work hard and consistently|Help servants and laborers|Feed crows, especially on Saturdays|Visit Shani temple or recite Shani Stotram|Keep your workspace clean and organized", "अनुशासन र दिनचर्या कडा रूपमा पालना गर्नुहोस्|वृद्ध, गरिब र अपाङ्गहरूको सेवा गर्नुहोस्|धैर्यवान हुनुहोस् - सर्टकटहरू नगर्नुहोस्|कडा परिश्रम र निरन्तर काम गर्नुहोस्|सेवक र मजदुरहरूलाई मद्दत गर्नुहोस्|कागलाई खुवाउनुहोस्, विशेष गरी शनिबार|शनि मन्दिर जानुहोस् वा शनि स्तोत्र पाठ गर्नुहोस्|आफ्नो कार्यस्थल सफा र व्यवस्थित राख्नुहोस्"),
    LIFESTYLE_SUN_AVOID("Avoid disrespecting father or superiors|Avoid excessive ego or arrogance", "बुबा वा वरिष्ठहरूलाई अनादर नगर्नुहोस्|अत्यधिक अहंकार वा घमण्ड नगर्नुहोस्"),
    LIFESTYLE_SUN_PRACTICES("Wake before sunrise and perform Surya Namaskar|Offer water (Arghya) to Sun at sunrise|Spend time in natural sunlight (morning hours)|Respect father, authority figures, and government officials|Develop leadership qualities with humility|Eat meals before sunset when possible", "सूर्योदय हुनुभन्दा पहिले उठ्नुहोस् र सूर्य नमस्कार गर्नुहोस्|सूर्योदयको समयमा सूर्यलाई अर्घ्य दिनुहोस्|प्राकृतिक सूर्यको प्रकाशमा समय बिताउनुहोस् (बिहानको समय)|बुबा, अधिकारवाला व्यक्तिहरू र सरकारी अधिकारीहरूलाई आदर गर्नुहोस्|नम्रताका साथ नेतृत्व गुणहरू विकास गर्नुहोस्|सम्भव भएसम्म सूर्यास्त अघि खाना खानुहोस्"),
    LIFESTYLE_THINGS_AVOID("THINGS TO AVOID:", "बेवास्ता गर्नुपर्ने कुराहरू:"),
    LIFESTYLE_TIMING("Daily practice, especially on %s", "दैनिक अभ्यास, विशेष गरी %s मा"),
    LIFESTYLE_TITLE_SUFFIX(" Lifestyle Practices", " जीवनशैली अभ्यास"),
    LIFESTYLE_VENUS_AVOID("Avoid excessive sensual indulgence|Avoid disrespecting spouse or partner", "अत्यधिक कामुक भोगबाट बच्नुहोस्|पति/पत्नी वा साथीलाई अनादर नगर्नुहोस्"),
    LIFESTYLE_VENUS_PRACTICES("Appreciate arts, music, and beauty|Maintain harmony in relationships|Practice gratitude daily|Keep your surroundings beautiful and clean|Respect women and feminine energy|Wear clean, pleasant-smelling clothes|Use perfumes and flowers in your space", "कला, संगीत र सौन्दर्यको कदर गर्नुहोस्|सम्बन्धमा सद्भाव कायम राख्नुहोस्|दैनिक कृतज्ञता अभ्यास गर्नुहोस्|आफ्नो वरपरको वातावरण सुन्दर र सफा राख्नुहोस्|महिला र स्त्री शक्तिलाई आदर गर्नुहोस्|सफा, सुगन्धित लुगा लगाउनुहोस्|आफ्नो ठाउँमा अत्तर र फूल प्रयोग गर्नुहोस्"),
    LIFE_APPROACH_PHILOSOPHY("Life Philosophy", "जीवन दर्शन"),
    LIFE_APPROACH_STYLE("Approach Style", "दृष्टिकोण शैली"),
    LIFE_APPROACH_TITLE("Life Approach", "जीवन दृष्टिकोण"),
    LIFE_AREA_BALANCE("Life Area Balance", "जीवन क्षेत्र सन्तुलन"),
    LIFE_AREA_CAREER("Career & Authority", "करियर र अधिकार"),
    LIFE_AREA_CAREER_FULL("Career", "क्यारियर"),
    LIFE_AREA_EDUCATION("Education & Communication", "शिक्षा र सञ्चार"),
    LIFE_AREA_FAMILY("Family & Home", "परिवार र घर"),
    LIFE_AREA_FAMILY_FULL("Family & Home", "परिवार र घर"),
    LIFE_AREA_FINANCE("Finance & Wealth", "वित्त र सम्पत्ति"),
    LIFE_AREA_FINANCE_FULL("Finance & Wealth", "वित्त र सम्पत्ति"),
    LIFE_AREA_FOREIGN("Foreign & Travel", "विदेश र यात्रा"),
    LIFE_AREA_HEALTH("Health & Vitality", "स्वास्थ्य र जीवनशक्ति"),
    LIFE_AREA_HEALTH_FULL("Health & Vitality", "स्वास्थ्य र जीवनशक्ति"),
    LIFE_AREA_LOVE("Love & Relationships", "प्रेम र सम्बन्ध"),
    LIFE_AREA_LOVE_FULL("Love & Relationships", "प्रेम र सम्बन्ध"),
    LIFE_AREA_PROPERTY("Property & Fixed Assets", "सम्पत्ति र अचल सम्पत्ति"),
    LIFE_AREA_RELATIONSHIPS("Relationships & Marriage", "सम्बन्ध र विवाह"),
    LIFE_AREA_SPIRITUAL("Spiritual Growth", "आध्यात्मिक वृद्धि"),
    LIFE_AREA_SPIRITUALITY("Spiritual Growth", "आध्यात्मिक वृद्धि"),
    LIFE_AREA_SPIRITUALITY_FULL("Spiritual Growth", "आध्यात्मिक वृद्धि"),
    LIFE_AREA_TITLE("Life Area Predictions", "जीवन क्षेत्र भविष्यवाणीहरू"),
    LIFE_AREA_WEALTH("Wealth & Finance", "धन र वित्त"),
    LOADING("Consulting the shells...", "कौडीहरूसँग परामर्श गर्दै..."),
    LOADING_ANALYSIS("Analyzing patterns...", "ढाँचाहरू विश्लेषण गर्दै..."),
    LOCATION("Location", "स्थान"),
    LOCATION_CLEAR("Clear search", "खोज हटाउनुहोस्"),
    LOCATION_PLACEHOLDER("Enter city or place name", "शहर वा ठाउँको नाम प्रविष्ट गर्नुहोस्"),
    LOCATION_SEARCH("Search location", "स्थान खोज्नुहोस्"),
    LOCATION_SELECT("Select %s", "%s छान्नुहोस्"),
    LONGEVITY_CATEGORY("Longevity Category", "दीर्घायु श्रेणी"),
    LONGEVITY_INDICATOR("Marriage Longevity", "विवाह दीर्घायु"),
    LONGEVITY_LONG("Your chart indicates potential for long life with proper care and balanced lifestyle.",
        "तपाईंको कुण्डलीले उचित हेरचाह र सन्तुलित जीवनशैलीको साथ दीर्घ जीवनको सम्भावना संकेत गर्छ।"),
    LONGEVITY_MEDIUM("Your chart indicates average longevity, enhanced through healthy habits and positive thinking.",
        "तपाईंको कुण्डलीले औसत आयु संकेत गर्छ, स्वस्थ बानीहरू र सकारात्मक सोचाइबाट बढाइएको।"),
    LONGEVITY_PROSPERITY("Longevity & Prosperity", "दीर्घायु र समृद्धि"),
    LONGEVITY_REQUIRES_CARE("Your chart suggests the need for extra health consciousness and preventive measures.",
        "तपाईंको कुण्डलीले अतिरिक्त स्वास्थ्य चेतना र निवारक उपायहरूको आवश्यकता सुझाव गर्छ।"),
    LONGEVITY_SHORT("Short Lifespan Indicators", "छोटो आयु सूचकहरू"),
    LONGEVITY_TITLE("Longevity Profile", "दीर्घायु प्रोफाइल"),
    LONG_TERM("Long Term Outlook", "दीर्घ अवधि दृष्टिकोण"),
    LORD7_IN_10TH("7th Lord in 10th House", "सप्तम स्वामी दशौं भावमा"),
    LORD7_IN_11TH("7th Lord in 11th House", "सप्तम स्वामी एघारौं भावमा"),
    LORD7_IN_12TH("7th Lord in 12th House", "सप्तम स्वामी बाह्रौं भावमा"),
    LORD7_IN_1ST("7th Lord in 1st House", "सप्तम स्वामी पहिलो भावमा"),
    LORD7_IN_2ND("7th Lord in 2nd House", "सप्तम स्वामी दोस्रो भावमा"),
    LORD7_IN_3RD("7th Lord in 3rd House", "सप्तम स्वामी तेस्रो भावमा"),
    LORD7_IN_4TH("7th Lord in 4th House", "सप्तम स्वामी चौथो भावमा"),
    LORD7_IN_5TH("7th Lord in 5th House", "सप्तम स्वामी पाँचौं भावमा"),
    LORD7_IN_6TH("7th Lord in 6th House", "सप्तम स्वामी छैटौं भावमा"),
    LORD7_IN_7TH("7th Lord in 7th House", "सप्तम स्वामी सातौं भावमा"),
    LORD7_IN_8TH("7th Lord in 8th House", "सप्तम स्वामी आठौं भावमा"),
    LORD7_IN_9TH("7th Lord in 9th House", "सप्तम स्वामी नवौं भावमा"),
    LORDS("Lords", "स्वामीहरू"),
    LORD_1("Lagna Lord", "लग्नेश"),
    LORD_10("10th Lord", "दशमेश"),
    LORD_11("11th Lord", "एकादशेश"),
    LORD_12("12th Lord", "द्वादशेश"),
    LORD_2("2nd Lord", "द्वितीयेश"),
    LORD_3("3rd Lord", "तृतीयेश"),
    LORD_4("4th Lord", "चतुर्थेश"),
    LORD_5("5th Lord", "पंचमेश"),
    LORD_6("6th Lord", "षष्ठेश"),
    LORD_7("7th Lord", "सप्तमेश"),
    LORD_8("8th Lord", "अष्टमेश"),
    LORD_9("9th Lord", "नवमेश"),
    LORD_IN_10TH("10th Lord in 10th House", "दशम स्वामी दशौं भावमा"),
    LORD_IN_11TH("10th Lord in 11th House", "दशम स्वामी एघारौं भावमा"),
    LORD_IN_12TH("10th Lord in 12th House", "दशम स्वामी बाह्रौं भावमा"),
    LORD_IN_1ST("10th Lord in 1st House", "दशम स्वामी पहिलो भावमा"),
    LORD_IN_2ND("10th Lord in 2nd House", "दशम स्वामी दोस्रो भावमा"),
    LORD_IN_3RD("10th Lord in 3rd House", "दशम स्वामी तेस्रो भावमा"),
    LORD_IN_4TH("10th Lord in 4th House", "दशम स्वामी चौथो भावमा"),
    LORD_IN_5TH("10th Lord in 5th House", "दशम स्वामी पाँचौं भावमा"),
    LORD_IN_6TH("10th Lord in 6th House", "दशम स्वामी छैटौं भावमा"),
    LORD_IN_7TH("10th Lord in 7th House", "दशम स्वामी सातौं भावमा"),
    LORD_IN_8TH("10th Lord in 8th House", "दशम स्वामी आठौं भावमा"),
    LORD_IN_9TH("10th Lord in 9th House", "दशम स्वामी नवौं भावमा"),
    LORD_LABEL("Lord", "स्वामी"),
    LOVE_EXPRESSION("Love Expression", "प्रेम अभिव्यक्ति"),
    LOYALTY_PATTERN("Loyalty Pattern", "वफादारी ढाँचा"),
    LUCKY_COLOR("Color", "रंग"),
    LUCKY_DIRECTION("Direction", "दिशा"),
    LUCKY_DIRECTION_EAST("East", "पूर्व"),
    LUCKY_DIRECTION_NORTH("North", "उत्तर"),
    LUCKY_DIRECTION_NORTHEAST("North-East", "उत्तर-पूर्व"),
    LUCKY_DIRECTION_NORTHWEST("North-West", "उत्तर-पश्चिम"),
    LUCKY_DIRECTION_SOUTH("South", "दक्षिण"),
    LUCKY_DIRECTION_SOUTHEAST("South-East", "दक्षिण-पूर्व"),
    LUCKY_DIRECTION_SOUTHWEST("South-West", "दक्षिण-पश्चिम"),
    LUCKY_DIRECTION_WEST("West", "पश्चिम"),
    LUCKY_GEMSTONE("Gemstone", "रत्न"),
    LUCKY_NUMBER("Number", "अंक"),
    LUCKY_TIME_DAY("Daylight hours", "दिउँसोको समय"),
    LUCKY_TIME_EVENING("Evening hours", "साँझको समय"),
    LUCKY_TIME_MORNING("Morning hours", "बिहानी समय"),
    LUCKY_TIME_NIGHT("Night hours", "रातको समय"),
    LUNAR_ACTION("Good for taking action", "कार्य सुरु गर्न राम्रो"),
    LUNAR_COMPLETION("Emotional peak - completion energy", "भावनात्मक शिखर - पूर्णताको ऊर्जा"),
    LUNAR_FIRST_QUARTER("First Quarter Moon", "प्रथम चतुर्थांश चन्द्रमा"),
    LUNAR_FULL_MOON("Full Moon", "पूर्णिमा"),
    MAHALAXMI_YOGA("Mahalaxmi Yoga", "महालक्ष्मी योग"),
    MAJOR_TRANSITS("Major Transits", "प्रमुख गोचरहरू"),
    MALEFIC("Malefic", "पाप"),
    MANIFEST_EXCEPTIONAL("Results manifest prominently throughout life", "परिणामहरू जीवनभर प्रमुख रूपमा प्रकट हुन्छन्"),
    MANIFEST_MODERATE("Results manifest moderately with conscious effort", "सचेत प्रयासको साथ परिणामहरू मध्यम रूपमा प्रकट हुन्छन्"),
    MANIFEST_STRONG("Results manifest notably, especially during dasha periods", "परिणामहरू उल्लेखनीय रूपमा प्रकट हुन्छन्, विशेष गरी दशा अवधिमा"),
    MANIFEST_SUBTLE("Results manifest subtly, may need activation", "परिणामहरू सूक्ष्म रूपमा प्रकट हुन्छन्, सक्रियताको आवश्यकता हुन सक्छ"),
    MANTRAS("Recommended Mantras", "सिफारिस गरिएका मन्त्रहरू"),
    MARAKA_ABOUT_DESC("Maraka planets are associated with the 2nd and 7th houses, which are maraka sthanas (death-inflicting houses). The lords of these houses and planets placed in them can indicate challenging periods for health and longevity. This analysis helps identify such influences and provides remedial guidance based on classical Vedic astrology principles.", "मारक ग्रहहरू दोस्रो र सातौं भाव (मारक स्थान) सँग सम्बन्धित छन्। यी भावका स्वामी र यहाँ रहेका ग्रहहरूले स्वास्थ्य र आयुको लागि चुनौतीपूर्ण अवधि संकेत गर्न सक्छन्। यो विश्लेषणले शास्त्रीय वैदिक ज्योतिष सिद्धान्तहरूमा आधारित त्यस्ता प्रभावहरू पहिचान गर्न र उपायात्मक मार्गदर्शन प्रदान गर्न मद्दत गर्दछ।"),
    MARAKA_ABOUT_TITLE("About Maraka Analysis", "मारक विश्लेषणको बारेमा"),
    MARAKA_AFFLICTIONS("Afflictions", "पीडाहरू"),
    MARAKA_AMSAYURDAYA("Amsayurdaya", "अंशायुर्दाय"),
    MARAKA_ANALYZING("Analyzing Maraka influences...", "मारक प्रभाव विश्लेषण गर्दै..."),
    MARAKA_CRITICAL_PERIODS("Critical Dasha Periods", "महत्त्वपूर्ण दशा अवधि"),
    MARAKA_FACTORS("Longevity Factors", "आयु कारकहरू"),
    MARAKA_LONGEVITY_SCORE("Longevity Score", "आयु स्कोर"),
    MARAKA_METHODS("Longevity Assessment Methods", "आयु मूल्याङ्कन विधिहरू"),
    MARAKA_NEGATIVE("Negative Factors", "नकारात्मक कारकहरू"),
    MARAKA_NISARGAYURDAYA("Nisargayurdaya", "निसर्गायुर्दाय"),
    MARAKA_NO_CHART_DESC("Please generate a chart to view Maraka analysis.", "मारक विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
    MARAKA_NO_CRITICAL("No Critical Periods Identified", "कुनै महत्त्वपूर्ण अवधि पहिचान गरिएको छैन"),
    MARAKA_NO_REMEDIES("No specific remedies needed at this time.", "यस समयमा कुनै विशेष उपाय आवश्यक छैन।"),
    MARAKA_NO_SIGNIFICANT("No Significant Maraka Influences", "कुनै महत्त्वपूर्ण मारक प्रभाव छैन"),
    MARAKA_PERIODS("Periods", "अवधि"),
    MARAKA_PINDAYURDAYA("Pindayurdaya", "पिण्डायुर्दाय"),
    MARAKA_POSITIVE("Positive Factors", "सकारात्मक कारकहरू"),
    MARAKA_PRIMARY("Primary", "प्राथमिक"),
    MARAKA_PRIMARY_TITLE("Primary Maraka Planets", "प्राथमिक मारक ग्रहहरू"),
    MARAKA_PROTECTIVE("Protective Factors", "सुरक्षात्मक कारकहरू"),
    MARAKA_SCREEN_TITLE("Maraka Analysis", "मारक विश्लेषण"),
    MARAKA_SECONDARY("Secondary", "माध्यमिक"),
    MARAKA_SECONDARY_TITLE("Secondary Maraka Planets", "माध्यमिक मारक ग्रहहरू"),
    MARAKA_SUBTITLE("Longevity & Health Planets", "आयु र स्वास्थ्य ग्रहहरू"),
    MARAKA_TAB_LONGEVITY("Longevity", "आयु"),
    MARAKA_TAB_PLANETS("Planets", "ग्रहहरू"),
    MARRIAGE_7TH_BENEFIC("The presence of benefics in your 7th house indicates a harmonious and supportive marriage partnership.",
        "तपाईंको ७औं भावमा शुभ ग्रहहरूको उपस्थितिले सामंजस्यपूर्ण र सहयोगी विवाह साझेदारी संकेत गर्छ।"),
    MARRIAGE_7TH_MALEFIC("Malefic influences on the 7th house suggest the need for patience and understanding in relationships.",
        "७औं भावमा पापी प्रभावहरूले सम्बन्धहरूमा धैर्य र समझको आवश्यकता सुझाव गर्छ।"),
    MARRIAGE_BLESSINGS("Marriage Blessings", "विवाह आशीर्वाद"),
    MARRIAGE_JUPITER_ASPECT("Jupiter's aspect on the 7th house brings blessings, wisdom, and spiritual growth through marriage.",
        "७औं भावमा बृहस्पतिको दृष्टिले विवाह मार्फत आशीर्वाद, ज्ञान र आध्यात्मिक वृद्धि ल्याउँछ।"),
    MARRIAGE_OVERVIEW("Your marriage and relationship prospects are analyzed through the 7th house, Venus, Jupiter, and their aspects.",
        "तपाईंको विवाह र सम्बन्ध सम्भावनाहरू ७औं भाव, शुक्र, बृहस्पति, र तिनीहरूको दृष्टि मार्फत विश्लेषण गरिएको छ।"),
    MARRIAGE_QUALITY("Marriage Quality", "विवाह गुणस्तर"),
    MARRIAGE_TIMING_DELAYED("Your chart suggests delayed marriage, possibly after age 30-32, but with greater maturity.",
        "तपाईंको कुण्डलीले ढिलो विवाह सुझाव गर्छ, सम्भवतः ३०-३२ वर्षपछि, तर बढी परिपक्वताको साथ।"),
    MARRIAGE_TIMING_EARLY("Your chart indicates the possibility of early marriage, typically before age 25-27.",
        "तपाईंको कुण्डलीले प्रारम्भिक विवाहको सम्भावना संकेत गर्छ, सामान्यतया २५-२७ वर्ष अघि।"),
    MARRIAGE_TIMING_NORMAL("Your chart indicates marriage timing around the typical age of 27-32.",
        "तपाईंको कुण्डलीले सामान्य उमेर २७-३२ को आसपास विवाह समय संकेत गर्छ।"),
    MARRIAGE_VENUS_STRONG("Strong Venus blesses you with charm, romantic nature, and the ability to maintain harmonious relationships.",
        "बलियो शुक्रले तपाईंलाई आकर्षण, रोमान्टिक स्वभाव, र सामंजस्यपूर्ण सम्बन्धहरू कायम राख्ने क्षमताको आशीर्वाद दिन्छ।"),
    MARRIAGE_VENUS_WEAK("Venus affliction may cause delays or challenges in relationships, requiring conscious effort to maintain harmony.",
        "शुक्र पीडाले सम्बन्धहरूमा ढिलाइ वा चुनौतीहरू निम्त्याउन सक्छ, सामंजस्य कायम राख्न सचेत प्रयास आवश्यक पर्दछ।"),
    MARRIAGE_YOGA_TITLE("Marriage Yogas", "विवाह योगहरू"),
    MARS_HEALTH("Mars Health Influence", "मंगल स्वास्थ्य प्रभाव"),
    MATH_APTITUDE("Mathematical Aptitude", "गणितीय क्षमता"),
    MB_JUP_EFF_1("Challenges in education or spiritual growth", "शिक्षा वा आध्यात्मिक वृद्धिमा चुनौतीहरू"),
    MB_JUP_EFF_2("Issues with teachers or mentors", "शिक्षक वा गुरुहरूसँग समस्या"),
    MB_JUP_EFF_3("Financial ups and downs", "आर्थिक उतार-चढाव"),
    MB_JUP_EFF_4("Need for wisdom and philosophical grounding", "ज्ञान र दार्शनिक आधारको आवश्यकता"),
    MB_JUP_REM_1("Worship Lord Brihaspati on Thursdays", "बिहीबार भगवान बृहस्पतिको पूजा गर्नुहोस्"),
    MB_JUP_REM_2("Wear Yellow Sapphire (if suitable)", "उपयुक्त भएमा पुखराज लगाउनुहोस्"),
    MB_JUP_REM_3("Donate yellow items and turmeric", "पहेंलो वस्तु र बेसार दान गर्नुहोस्"),
    MB_JUP_REM_4("Respect teachers and elders", "शिक्षक र ठूलाबाडालाई आदर गर्नुहोस्"),
    MB_KETU_EFF_1("Spiritual crises or confusion", "आध्यात्मिक संकट वा भ्रम"),
    MB_KETU_EFF_2("Detachment-related challenges", "वैराग्य सम्बन्धी चुनौतीहरू"),
    MB_KETU_EFF_3("Past-life karma surfacing", "विगतको जीवनको कर्म बाहिर आउने"),
    MB_KETU_EFF_4("Need for spiritual practices", "आध्यात्मिक अभ्यासहरूको आवश्यकता"),
    MB_KETU_REM_1("Worship Lord Ganesha", "भगवान गणेशको पूजा गर्नुहोस्"),
    MB_KETU_REM_2("Wear Cat's Eye (if suitable)", "उपयुक्त भएमा वैदूर्य (लहसुनिया) लगाउनुहोस्"),
    MB_KETU_REM_3("Donate multi-colored blankets", "बहुरंगी कम्बल दान गर्नुहोस्"),
    MB_KETU_REM_4("Practice meditation and spiritual disciplines", "ध्यान र आध्यात्मिक अनुशासन अभ्यास गर्नुहोस्"),
    MB_MARS_EFF_1("Accident-prone tendencies during Mars periods", "मंगलको अवधिमा दुर्घटनाको जोखिम हुने प्रवृत्ति"),
    MB_MARS_EFF_2("Blood-related or surgical issues possible", "रगत सम्बन्धी वा शल्यक्रिया सम्बन्धी समस्याहरूको सम्भावना"),
    MB_MARS_EFF_3("Conflicts with siblings or competitors", "भाइबहिनी वा प्रतिस्पर्धीहरूसँग द्वन्द्व"),
    MB_MARS_EFF_4("Need to channel energy constructively", "ऊर्जालाई रचनात्मक रूपमा प्रयोग गर्नुपर्ने आवश्यकता"),
    MB_MARS_REM_1("Recite Hanuman Chalisa daily", "दैनिक हनुमान चालीसा पाठ गर्नुहोस्"),
    MB_MARS_REM_2("Wear Red Coral (if suitable)", "उपयुक्त भएमा मुगा लगाउनुहोस्"),
    MB_MARS_REM_3("Donate red lentils on Tuesdays", "मंगलबार मुसुरोको दाल दान गर्नुहोस्"),
    MB_MARS_REM_4("Practice physical exercise regularly", "नियमित रूपमा शारीरिक व्यायाम गर्नुहोस्"),
    MB_MERC_EFF_1("Communication difficulties or misunderstandings", "सञ्चारमा कठिनाइ वा गलतफहमी"),
    MB_MERC_EFF_2("Nervous system sensitivity", "स्नायु प्रणालीको संवेदनशीलता"),
    MB_MERC_EFF_3("Educational or business challenges", "शैक्षिक वा व्यापारिक चुनौतीहरू"),
    MB_MERC_EFF_4("Need for mental clarity practices", "मानसिक स्पष्टताका अभ्यासहरूको आवश्यकता"),
    MB_MERC_REM_1("Worship Lord Vishnu on Wednesdays", "बुधबार भगवान विष्णुको पूजा गर्नुहोस्"),
    MB_MERC_REM_2("Wear Emerald (if suitable)", "उपयुक्त भएमा पन्ना लगाउनुहोस्"),
    MB_MERC_REM_3("Donate green vegetables", "हरियो तरकारी दान गर्नुहोस्"),
    MB_MERC_REM_4("Chant Om Budhaya Namaha", "ॐ बुधाय नमः जप गर्नुहोस्"),
    MB_MOON_EFF_1("Emotional sensitivity and mental stress", "भावनात्मक संवेदनशीलता र मानसिक तनाव"),
    MB_MOON_EFF_2("Challenges with mother or maternal relationships", "आमा वा मातृ सम्बन्धमा चुनौतीहरू"),
    MB_MOON_EFF_3("Fluctuating public image or reputation", "सार्वजनिक छवि वा प्रतिष्ठामा उतार-चढाव"),
    MB_MOON_EFF_4("Need for emotional healing and stability", "भावनात्मक उपचार र स्थिरताको आवश्यकता"),
    MB_MOON_REM_1("Worship Divine Mother on Mondays", "सोमबार देवी भगवतीको पूजा गर्नुहोस्"),
    MB_MOON_REM_2("Wear Pearl or Moonstone (if suitable)", "उपयुक्त भएमा मोती वा चन्द्रकान्त मणि लगाउनुहोस्"),
    MB_MOON_REM_3("Offer milk to Shiva Lingam", "शिवलिङ्गमा दूध चढाउनुहोस्"),
    MB_MOON_REM_4("Practice meditation for mental peace", "मानसिक शान्तिको लागि ध्यान अभ्यास गर्नुहोस्"),
    MB_RAHU_EFF_1("Sudden unexpected events", "अचानक अप्रत्याशित घटनाहरू"),
    MB_RAHU_EFF_2("Foreign-related complications", "विदेशसँग सम्बन्धित जटिलताहरू"),
    MB_RAHU_EFF_3("Obsessive tendencies intensified", "जुनूनी प्रवृत्तिहरू तीव्र पारिएको"),
    MB_RAHU_EFF_4("Need for grounding and reality checks", "यथार्थमा रहनुपर्ने आवश्यकता"),
    MB_RAHU_REM_1("Worship Goddess Durga", "देवी दुर्गाको पूजा गर्नुहोस्"),
    MB_RAHU_REM_2("Wear Hessonite (Gomed) if suitable", "उपयुक्त भएमा गोमेद लगाउनुहोस्"),
    MB_RAHU_REM_3("Donate blue clothes and blankets", "नीलो कपडा र कम्बल दान गर्नुहोस्"),
    MB_RAHU_REM_4("Avoid intoxicants and maintain ethics", "नशालु पदार्थबाट बच्नुहोस् र नैतिकता कायम राख्नुहोस्"),
    MB_SAT_EFF_1("Career delays or professional setbacks", "करियरमा ढिलाइ वा व्यावसायिक अवरोधहरू"),
    MB_SAT_EFF_2("Joint or bone-related health issues", "जोर्नी वा हड्डीसँग सम्बन्धित स्वास्थ्य समस्याहरू"),
    MB_SAT_EFF_3("Karmic lessons intensified", "कार्मिक पाठहरू तीव्र पारिएको"),
    MB_SAT_EFF_4("Need for patience and perseverance", "धैर्य र लगनशीलताको आवश्यकता"),
    MB_SAT_REM_1("Worship Lord Shani on Saturdays", "शनिबार भगवान शनिको पूजा गर्नुहोस्"),
    MB_SAT_REM_2("Wear Blue Sapphire only after thorough analysis", "गहिरो विश्लेषण पछि मात्र नीलम लगाउनुहोस्"),
    MB_SAT_REM_3("Donate black sesame and iron items", "कालो तिल र फलामका वस्तुहरू दान गर्नुहोस्")
}
