package com.astro.storm.core.common
enum class StringKeyNakshatra(override val en: String, override val ne: String) : StringKeyInterface {
NAKSHATRA_TITLE("Nakshatra Analysis", "नक्षत्र विश्लेषण"),
NAKSHATRA_SUBTITLE("Lunar Mansion Analysis", "चन्द्र भवन विश्लेषण"),
NAKSHATRA_OVERVIEW("Overview", "अवलोकन"),
NAKSHATRA_DETAILS("Details", "विवरणहरू"),
NAKSHATRA_COMPATIBILITY("Compatibility", "अनुकूलता"),
NAKSHATRA_REMEDIES("Remedies", "उपायहरू"),
NAKSHATRA_BIRTH_STAR("Birth Nakshatra", "जन्म नक्षत्र"),
NAKSHATRA_MOON_POSITION("Moon Nakshatra", "चन्द्र नक्षत्र"),
NAKSHATRA_RULER("Ruling Planet", "स्वामी ग्रह"),
NAKSHATRA_ELEMENT("Element", "तत्व"),
NAKSHATRA_QUALITY("Quality", "गुण"),
NAKSHATRA_CASTE("Caste", "वर्ण"),
NAKSHATRA_DIRECTION("Direction", "दिशा"),
NAKSHATRA_BODY_PART("Body Part", "शरीरको अंग"),
NAKSHATRA_DOSHA("Dosha", "दोष"),
NAKSHATRA_FAVORABLE_DAYS("Favorable Days", "अनुकूल दिनहरू"),
NAKSHATRA_LUCKY_NUMBERS("Lucky Numbers", "भाग्यशाली अंकहरू"),
NAKSHATRA_LUCKY_COLORS("Lucky Colors", "भाग्यशाली रंगहरू"),
NAKSHATRA_LUCKY_STONES("Lucky Gemstones", "भाग्यशाली रत्नहरू"),
NAKSHATRA_CHARACTERISTICS("Characteristics", "विशेषताहरू"),
NAKSHATRA_STRENGTHS("Strengths", "शक्तिहरू"),
NAKSHATRA_WEAKNESSES("Weaknesses", "कमजोरीहरू"),
NAKSHATRA_CAREER("Career Aptitude", "क्यारियर योग्यता"),
NAKSHATRA_HEALTH("Health Tendencies", "स्वास्थ्य प्रवृत्तिहरू"),
NAKSHATRA_RELATIONSHIP("Relationship Style", "सम्बन्ध शैली"),
NAKSHATRA_SPIRITUAL("Spiritual Path", "आध्यात्मिक मार्ग"),
NAKSHATRA_MANTRA("Nakshatra Mantra", "नक्षत्र मन्त्र"),
NAKSHATRA_INFO_TITLE("About Nakshatras", "नक्षत्रहरूको बारेमा"),
NAKSHATRA_INFO_DESC("Nakshatras are the 27 lunar mansions in Vedic astrology, each spanning 13Â°20' of the zodiac. They reveal deeper psychological patterns and spiritual tendencies.", "नक्षत्रहरू वैदिक ज्योतिषमा २७ चन्द्र भवनहरू हुन्, प्रत्येक राशिचक्रको १३°२०' फैलिएको। तिनीहरूले गहिरो मनोवैज्ञानिक ढाँचा र आध्यात्मिक प्रवृत्तिहरू प्रकट गर्छन्।"),
NAKSHATRA_ALL_PLANETS("Planetary Nakshatras", "ग्रह नक्षत्रहरू"),
NAKSHATRA_DASHA_LORD("Dasha Lord", "दशा स्वामी"),
NAKSHATRA_SPAN("Nakshatra Span", "नक्षत्र विस्तार"),
NAKSHATRA_DEGREE_IN("Degree in Nakshatra", "नक्षत्रमा अंश"),
NAKSHATRA_TARABALA("Tarabala Analysis", "ताराबल विश्लेषण"),
NAKSHATRA_CHANDRABALA("Chandrabala", "चन्द्रबल"),
NAKSHATRA_COMPATIBLE_WITH("Compatible with", "अनुकूल"),
NAKSHATRA_INCOMPATIBLE_WITH("Incompatible with", "अनुकूल छैन"),
NAKSHATRA_VEDHA_PAIRS("Vedha Pairs", "वेध जोडीहरू"),
NAKSHATRA_RAJJU_TYPE("Rajju Type", "रज्जु प्रकार"),
    NAKSHATRA_NATURE_FIXED("Fixed (Dhruva)", "Fixed (Dhruva)"),
    NAKSHATRA_NATURE_MOVEABLE("Moveable (Chara)", "Moveable (Chara)"),
    NAKSHATRA_NATURE_SHARP("Sharp (Tikshna)", "Sharp (Tikshna)"),
    NAKSHATRA_NATURE_SOFT("Soft (Mridu)", "Soft (Mridu)"),
    NAKSHATRA_NATURE_MIXED("Mixed (Mishra)", "Mixed (Mishra)"),
    NAKSHATRA_NATURE_LIGHT("Light (Laghu)", "Light (Laghu)"),
    NAKSHATRA_NATURE_FIERCE("Fierce (Ugra)", "Fierce (Ugra)"),
    NAKSHATRA_GANA_DEVA("Deva (Divine)", "Deva (Divine)"),
    NAKSHATRA_GANA_MANUSHYA("Manushya (Human)", "Manushya (Human)"),
    NAKSHATRA_GANA_RAKSHASA("Rakshasa (Demon)", "Rakshasa (Demon)"),
    NAKSHATRA_ELEMENT_FIRE("Fire (Agni)", "Fire (Agni)"),
    NAKSHATRA_ELEMENT_EARTH("Earth (Prithvi)", "Earth (Prithvi)"),
    NAKSHATRA_ELEMENT_AIR("Air (Vayu)", "Air (Vayu)"),
    NAKSHATRA_ELEMENT_WATER("Water (Jala)", "Water (Jala)"),
    NAKSHATRA_ELEMENT_ETHER("Ether (Akasha)", "Ether (Akasha)"),
NAKSHATRA_CASTE_BRAHMIN("Brahmin", "ब्राह्मण"),
NAKSHATRA_CASTE_KSHATRIYA("Kshatriya", "क्षत्रिय"),
NAKSHATRA_CASTE_VAISHYA("Vaishya", "वैश्य"),
NAKSHATRA_CASTE_SHUDRA("Shudra", "शूद्र"),
NAKSHATRA_GENDER_MALE("Male", "पुरुष"),
NAKSHATRA_GENDER_FEMALE("Female", "स्त्री"),
NAKSHATRA_GENDER_NEUTRAL("Neutral", "नपुंसक"),
NAKSHATRA_DOSHA_VATA("Vata", "वात"),
NAKSHATRA_DOSHA_PITTA("Pitta", "पित्त"),
NAKSHATRA_DOSHA_KAPHA("Kapha", "कफ"),
NAKSHATRA_RAJJU_PAADA("Paada", "पाद"),
NAKSHATRA_RAJJU_KATI("Kati", "कटि"),
NAKSHATRA_RAJJU_NABHI("Nabhi", "नाभि"),
NAKSHATRA_RAJJU_KANTHA("Kantha", "कण्ठ"),
NAKSHATRA_RAJJU_SHIRO("Shiro", "शिरो"),
NAKSHATRA_REMEDY_TITLE("Remedies for %s", "%s का लागि उपायहरू"),
NAKSHATRA_REMEDY_DESC("Personalized remedies based on your birth nakshatra to enhance positive qualities and mitigate challenges.", "तपाइँको जन्म नक्षत्रमा आधारित व्यक्तिगत उपायहरू सकारात्मक गुणहरू बढाउन र चुनौतीहरू कम गर्न।"),
NAKSHATRA_REMEDY_TIMING("Best performed during %s hora or on %s", "%s होरा वा %s मा उत्तम"),
NAKSHATRA_BODY_PART_FEET("Feet", "पाउ"),
NAKSHATRA_BODY_PART_WAIST("Waist", "कम्मर"),
NAKSHATRA_BODY_PART_NAVEL("Navel", "नाभि"),
NAKSHATRA_BODY_PART_NECK("Neck", "घाँटी"),
NAKSHATRA_BODY_PART_HEAD("Head", "टाउको"),
NAKSHATRA_SYMBOL("Symbol", "प्रतीक"),
NAKSHATRA_DEITY("Deity", "देवता"),
NAKSHATRA_PADA("Pada", "पद"),
NAKSHATRA_GUNA("Guna", "गुण"),
NAKSHATRA_GANA("Gana", "गण"),
NAKSHATRA_YONI("Yoni", "योनि"),
NAKSHATRA_ANIMAL("Animal", "पशु"),
NAKSHATRA_BIRD("Bird", "पक्षी"),
NAKSHATRA_TREE("Tree", "वृक्ष"),
NAKSHATRA_NATURE("Nature", "प्रकृति"),
NAKSHATRA_GENDER("Gender", "लिङ्ग"),
NAKSHATRA_MALE("Male", "पुरुष"),
NAKSHATRA_FEMALE("Female", "महिला"),
NAKSHATRA_CAREERS("Careers", "क्यारियर"),
    NAKSHATRA_NATURE_SWIFT("Swift (Kshipra)", "Swift (Kshipra)"),
    NAKSHATRA_NATURE_MOVABLE("Movable (Chara)", "Movable (Chara)"),
NAKSHATRA_NATURE_DREADFUL("Dreadful", "क्रूर"),
NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
NAKSHATRA_DIFF("Nakshatra Difference", "नक्षत्र भिन्नता"),
NAKSHATRA_PADA_ACCESSIBILITY("%1\$s pada %2\$s", "%1\$s पद %2\$s"),
NAKSHATRA_ASHWINI("Ashwini", "अश्विनी"),
NAKSHATRA_BHARANI("Bharani", "भरणी"),
NAKSHATRA_KRITTIKA("Krittika", "कृत्तिका"),
NAKSHATRA_ROHINI("Rohini", "रोहिणी"),
NAKSHATRA_MRIGASHIRA("Mrigashira", "मृगशिरा"),
NAKSHATRA_ARDRA("Ardra", "आर्द्रा"),
NAKSHATRA_PUNARVASU("Punarvasu", "पुनर्वसु"),
NAKSHATRA_PUSHYA("Pushya", "पुष्य"),
NAKSHATRA_ASHLESHA("Ashlesha", "आश्लेषा"),
NAKSHATRA_MAGHA("Magha", "मघा"),
NAKSHATRA_PURVA_PHALGUNI("Purva Phalguni", "पूर्वा फाल्गुनी"),
NAKSHATRA_UTTARA_PHALGUNI("Uttara Phalguni", "उत्तरा फाल्गुनी"),
NAKSHATRA_HASTA("Hasta", "हस्त"),
NAKSHATRA_CHITRA("Chitra", "चित्रा"),
NAKSHATRA_SWATI("Swati", "स्वाति"),
NAKSHATRA_VISHAKHA("Vishakha", "विशाखा"),
NAKSHATRA_ANURADHA("Anuradha", "अनुराधा"),
NAKSHATRA_JYESHTHA("Jyeshtha", "ज्येष्ठा"),
NAKSHATRA_MULA("Mula", "मूल"),
NAKSHATRA_PURVA_ASHADHA("Purva Ashadha", "पूर्वाषाढा"),
NAKSHATRA_UTTARA_ASHADHA("Uttara Ashadha", "उत्तराषाढा"),
NAKSHATRA_SHRAVANA("Shravana", "श्रवण"),
NAKSHATRA_DHANISHTHA("Dhanishtha", "धनिष्ठा"),
NAKSHATRA_SHATABHISHA("Shatabhisha", "शतभिषा"),
NAKSHATRA_PURVA_BHADRAPADA("Purva Bhadrapada", "पूर्वभाद्रपद"),
NAKSHATRA_UTTARA_BHADRAPADA("Uttara Bhadrapada", "उत्तरभाद्रपद"),
NAKSHATRA_REVATI("Revati", "रेवती")
}
