package com.astro.storm.core.common
enum class StringKeyTransit(override val en: String, override val ne: String) : StringKeyInterface {
TRANSIT_DATA_UNAVAILABLE("Transit data not available", "गोचर डाटा उपलब्ध छैन"),
TRANSIT_TIMING("Transit Timing", "गोचर समय"),
    TRANSIT_TIMING_DESC("When slow-moving planets (Saturn, Jupiter, Rahu, Ketu)", "When slow-moving planets (Saturn, Jupiter, Rahu, Ketu)"),
TRANSIT_EXCELLENT("Excellent", "उत्कृष्ट"),
TRANSIT_GOOD("Good", "राम्रो"),
TRANSIT_MODERATE("Moderate", "मध्यम"),
TRANSIT_WEAK("Weak", "कमजोर"),
TRANSIT_NULLIFIED("Nullified by Vedha", "वेधद्वारा रद्द"),
TRANSIT_UNFAVORABLE("Unfavorable Transit", "प्रतिकूल गोचर"),
TRANSIT_OVERVIEW("Transit Overview", "गोचर सिंहावलोकन"),
TRANSIT_FAVORABLE("Favorable", "अनुकूल"),
TRANSIT_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
TRANSIT_ASPECTS("Aspects", "दृष्टिहरू"),
TRANSIT_OVERALL_SCORE("Overall Transit Score", "समग्र गोचर अंक"),
TRANSIT_CURRENT_POSITIONS("Current Planetary Positions", "हालको ग्रह स्थितिहरू"),
    TRANSIT_GOCHARA_ANALYSIS("Gochara Analysis (From Moon)", "Gochara Analysis (From Moon)"),
TRANSIT_ASPECTS_TO_NATAL("Transit Aspects to Natal", "जन्म कुण्डलीमा गोचर दृष्टि"),
TRANSIT_SIGNIFICANT_PERIODS("Significant Periods", "महत्त्वपूर्ण अवधिहरू"),
TRANSIT_APPLYING("Applying", "समीप आउँदै"),
TRANSIT_SEPARATING("Separating", "टाढा हुँदै"),
TRANSIT_ORB("Orb: %s°", "कोणान्तर: %s°"),
TRANSIT_VEDHA_FROM("Vedha from %s", "%s बाट वेध"),
TRANSIT_INTENSITY("Intensity %d/5", "तीव्रता %d/५"),
TRANSIT_HOUSE_FROM_MOON("House %d", "भाव %d"),
TRANSIT_PLANET_POSITIONS("Planet Positions", "ग्रह स्थितिहरू"),
TRANSIT_CURRENT_MOVEMENTS("Current planetary movements - %s", "वर्तमान ग्रह गतिहरू - %s"),
TRANSIT_OVERALL_ASSESSMENT("Overall Assessment", "समग्र मूल्याङ्कन"),
TRANSIT_HOUSE_LABEL("House", "भाव"),
TRANSIT_LABEL("TRANSIT", "गोचर"),
TRANSIT_NATAL_LABEL("NATAL", "जन्मकालीन"),
TRANSIT_NO_PLANETS_TRANSITING("No planets transiting", "कुनै ग्रह गोचर गर्दैन"),
TRANSIT_UPCOMING("Significant Upcoming Transits", "महत्त्वपूर्ण आगामी गोचरहरू"),
TRANSIT_NO_UPCOMING("No significant upcoming transits in the near future", "नजिकको भविष्यमा कुनै महत्त्वपूर्ण आगामी गोचर छैन"),
TRANSIT_TO_NATAL_ASPECTS("Transit to Natal Aspects", "जन्म कुण्डलीमा गोचर दृष्टि"),
TRANSIT_NO_ASPECTS("No significant transit aspects currently active", "हाल कुनै महत्त्वपूर्ण गोचर दृष्टि सक्रिय छैन"),
TRANSIT_NO_DATA("No Transit Data", "कुनै गोचर डाटा छैन"),
TRANSIT_SELECT_CHART("Please select a birth chart to view transits", "गोचर हेर्न जन्म कुण्डली छान्नुहोस्"),
TRANSIT_CURRENT_INFLUENCES("Current planetary influences", "वर्तमान ग्रह प्रभावहरू"),
TRANSIT_PLANETS_COUNT("Planets", "ग्रहहरू"),
TRANSIT_MAJOR_TRANSITS("Major Transits", "प्रमुख गोचरहरू"),
TRANSIT_QUALITY_LABEL("Quality", "गुणस्तर"),
TRANSIT_RETROGRADE_SYMBOL("R", "व"),
TRANSIT_QUALITY_EXCELLENT("Excellent", "उत्कृष्ट"),
TRANSIT_QUALITY_GOOD("Good", "राम्रो"),
TRANSIT_QUALITY_AVERAGE("Average", "औसत"),
TRANSIT_QUALITY_BELOW_AVG("Below Average", "औसतभन्दा कम"),
TRANSIT_QUALITY_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
TRANSIT_QUALITY_DIFFICULT("Difficult", "कठिन"),
TRANSIT_QUALITY_UNKNOWN("Unknown", "अज्ञात"),
TRANSIT_INTERP_EXCELLENT("Excellent - Highly favorable transit", "उत्कृष्ट - अत्यन्त अनुकूल गोचर"),
TRANSIT_INTERP_GOOD("Good - Favorable results expected", "राम्रो - अनुकूल परिणामहरू अपेक्षित"),
TRANSIT_INTERP_AVERAGE("Average - Mixed results", "औसत - मिश्रित परिणामहरू"),
TRANSIT_INTERP_BELOW_AVG("Below Average - Some challenges", "औसतभन्दा कम - केही चुनौतीहरू"),
TRANSIT_INTERP_DIFFICULT("Difficult - Careful navigation needed", "कठिन - सावधानीपूर्ण व्यवहार आवश्यक"),
TRANSIT_ANALYSIS_NOT_AVAILABLE("Transit analysis not available for this planet.", "यस ग्रहको लागि गोचर विश्लेषण उपलब्ध छैन।"),
TRANSIT_EXCELLENT_TEMPLATE("Transit through %s with %d BAV bindus and %d SAV bindus indicates excellent results. Matters related to %s will flourish. Areas of %s receive strong positive influence.", "%s मा %d BAV बिन्दु र %d SAV बिन्दुसँगको गोचरले उत्कृष्ट परिणाम देखाउँछ। %s सम्बन्धी मामिलाहरू फस्टाउनेछन्। %s को क्षेत्रमा बलियो सकारात्मक प्रभाव पर्नेछ।"),
TRANSIT_GOOD_TEMPLATE("Transit through %s brings favorable results with %d BAV and %d SAV bindus. Good progress expected in %s. %s areas are positively influenced.", "%s मा %d BAV र %d SAV बिन्दुसँगको गोचरले अनुकूल परिणामहरू ल्याउँछ। %s मा राम्रो प्रगति अपेक्षित छ। %s क्षेत्रमा सकारात्मक प्रभाव पर्नेछ।"),
    TRANSIT_AVERAGE_TEMPLATE("Transit through %s (%d BAV, %d SAV)", "Transit through %s (%d BAV, %d SAV)"),
    TRANSIT_BELOW_AVG_TEMPLATE("Transit through %s (%d BAV, %d SAV)", "Transit through %s (%d BAV, %d SAV)"),
TRANSIT_CHALLENGING_TEMPLATE("Challenging transit through %s with only %d BAV and %d SAV bindus. Difficulties possible in %s. Patience needed for %s matters.", "%s मा केवल %d BAV र %d SAV बिन्दुसँगको चुनौतीपूर्ण गोचर। %s मा कठिनाइहरू सम्भव। %s मामिलाहरूमा धैर्य आवश्यक।"),
    TRANSIT_DIFFICULT_TEMPLATE("Difficult transit period through %s (%d BAV, %d SAV)", "Difficult transit period through %s (%d BAV, %d SAV)"),
TRANSIT_EXPAND("Expand", "विस्तार"),
TRANSIT_COLLAPSE("Collapse", "संक्षिप्त"),
TRANSIT_ORB_VALUE("%d° orb", "%d° कोणान्तर"),
TRANSIT_PHRASE("%1\$s transit %2\$s natal %3\$s", "%1\$sको गोचर जन्मकालीन %3\$sमा %2\$s")
}
