package com.astro.storm.core.common
enum class StringKeyMatchmaking(override val en: String, override val ne: String) : StringKeyInterface {
VASHYA_QUADRUPED("Quadruped", "चतुष्पाद"),
VASHYA_HUMAN("Human", "मनुष्य"),
VASHYA_AQUATIC("Aquatic", "जलचर"),
VASHYA_WILD("Wild", "वन्य"),
VASHYA_INSECT("Insect", "कीट"),
COMPAT_BELOW_AVG("Below Average", "औसतभन्दा कम"),
COMPAT_BELOW_AVG_DESC("Caution advised. Several compatibility issues that need addressing through remedies and counseling.", "सावधानी सल्लाह दिइएको। उपाय र परामर्शबाट सम्बोधन गर्नुपर्ने धेरै अनुकूलता समस्याहरू।"),
MATCH_TITLE("Kundli Milan", "कुण्डली मिलान"),
MATCH_SELECT_PROFILES("Select Profiles", "प्रोफाइलहरू छान्नुहोस्"),
MATCH_PERSON_1("Person 1", "व्यक्ति १"),
MATCH_PERSON_2("Person 2", "व्यक्ति २"),
MATCH_CALCULATE("Calculate Match", "मिलान गणना गर्नुहोस्"),
MATCH_TOTAL_POINTS("Total Points", "कुल अंकहरू"),
MATCH_OUT_OF("out of", "मध्ये"),
MATCH_COMPATIBILITY("Compatibility", "अनुकूलता"),
MATCH_EXCELLENT("Excellent", "उत्कृष्ट"),
MATCH_GOOD("Good", "राम्रो"),
MATCH_AVERAGE("Average", "औसत"),
MATCH_BELOW_AVERAGE("Below Average", "औसतमुनि"),
MATCH_OVERVIEW("Overview", "अवलोकन"),
MATCH_GUNAS("Gunas", "गुणहरू"),
MATCH_DOSHAS("Doshas", "दोषहरू"),
MATCH_NAKSHATRAS("Nakshatras", "नक्षत्रहरू"),
MATCH_SELECT_BRIDE("Select Bride", "वधू छान्नुहोस्"),
MATCH_SELECT_GROOM("Select Groom", "वर छान्नुहोस्"),
MATCH_SWAP_PROFILES("Swap Profiles", "प्रोफाइलहरू स्वाप गर्नुहोस्"),
MATCH_ASHTAKOOTA("Ashtakoota Points", "अष्टकूट अंकहरू"),
MATCH_SHARE_REPORT("Share Report", "रिपोर्ट साझा गर्नुहोस्"),
MATCH_COPY_REPORT("Copy Report", "रिपोर्ट कपी गर्नुहोस्"),
MATCH_SHARE_AS_TEXT("Share as Text", "पाठको रूपमा साझा गर्नुहोस्"),
MATCH_SHARE_AS_IMAGE("Share as Image", "छविको रूपमा साझा गर्नुहोस्"),
MATCH_CALCULATING("Calculating compatibility...", "अनुकूलता गणना गर्दै..."),
MATCH_NO_PROFILES("No profiles available", "कुनै प्रोफाइल उपलब्ध छैन"),
MATCH_SELECT_BOTH("Please select both profiles", "कृपया दुवै प्रोफाइल छान्नुहोस्"),
MATCH_REMEDIES("Remedies", "उपायहरू"),
MATCH_REPORT_TITLE("Relationship Compatibility Report", "सम्बन्ध अनुकूलता रिपोर्ट"),
MATCH_CLEAR_SELECTION("Clear Selection", "छनौट हटाउनुहोस्"),
MATCH_BRIDE("Bride", "वधू"),
MATCH_GROOM("Groom", "वर"),
MATCH_CREATE_CHARTS_FIRST("Create birth charts first to use matchmaking", "मिलान प्रयोग गर्न पहिले जन्म कुण्डली बनाउनुहोस्"),
MATCH_TAP_TO_SELECT("Tap to select", "छान्न ट्याप गर्नुहोस्"),
MATCH_CONNECTED("Connected", "जोडिएको"),
MATCH_NOT_CONNECTED("Not Connected", "जोडिएको छैन"),
MATCH_ANALYZING_COMPATIBILITY("Analyzing compatibility...", "अनुकूलता विश्लेषण गर्दै..."),
MATCH_CALCULATING_DOSHAS("Calculating doshas...", "दोषहरू गणना गर्दै..."),
MATCH_CALCULATION_ERROR("Calculation Error", "गणना त्रुटि"),
MATCH_MANGLIK("Manglik", "मांगलिक"),
MATCH_NADI("Nadi", "नाडी"),
MATCH_DOSHA_PRESENT("Dosha Present", "दोष उपस्थित"),
MATCH_BHAKOOT("Bhakoot", "भकूट"),
MATCH_NEEDS_ATTENTION("Needs Attention", "ध्यान आवश्यक"),
MATCH_GUNA_DISTRIBUTION("Guna Distribution", "गुण वितरण"),
MATCH_PROFILE_COMPARISON("Profile Comparison", "प्रोफाइल तुलना"),
MATCH_AI_INSIGHT("AI Insight", "एआई अन्तर्दृष्टि"),
MATCH_AI_INSIGHT_SUBTITLE("Powered by Stormy", "Stormy द्वारा संचालित"),
MATCH_AI_INSIGHT_DESC("Get a deeper, personalized interpretation of your compatibility analysis using AI. The AI will analyze the Guna scores and Doshas to provide additional relationship guidance.", "एआई प्रयोग गरेर आफ्नो अनुकूलता विश्लेषणको गहिरो, व्यक्तिगत व्याख्या प्राप्त गर्नुहोस्। एआईले थप सम्बन्ध मार्गदर्शन प्रदान गर्न गुण स्कोर र दोषहरूको विश्लेषण गर्नेछ।"),
MATCH_GENERATE_AI_INSIGHT("Generate AI Insight", "एआई अन्तर्दृष्टि उत्पन्न गर्नुहोस्"),
MATCH_AI_ANALYZING("Analyzing compatibility...", "अनुकूलता विश्लेषण गर्दै..."),
MATCH_VS("vs", "विरुद्ध"),
MATCH_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
MATCH_NAKSHATRA("Nakshatra", "नक्षत्र"),
MATCH_PADA("Pada", "पद"),
MATCH_PADA_NUMBER("Pada %d", "पद %d"),
MATCH_KEY_CONSIDERATIONS("Key Considerations", "मुख्य विचारहरू"),
MATCH_FAVORABLE("Favorable", "अनुकूल"),
MATCH_TOTAL_SCORE("Total Score", "कुल अंक"),
MATCH_MANGLIK_DOSHA_ANALYSIS("Manglik Dosha Analysis", "मांगलिक दोष विश्लेषण"),
MATCH_MARS_PLACEMENT("Mars Placement", "मंगल स्थिति"),
MATCH_MARS_IN_HOUSE("Mars in House %d", "भाव %d मा मंगल"),
MATCH_CONTRIBUTING_FACTORS("Contributing Factors", "योगदान गर्ने कारकहरू"),
MATCH_CANCELLATION_FACTORS("Cancellation Factors", "रद्द गर्ने कारकहरू"),
MATCH_NADI_DOSHA("Nadi Dosha", "नाडी दोष"),
MATCH_HEALTH_PROGENY("Health & Progeny", "स्वास्थ्य र सन्तान"),
MATCH_PRESENT("Present", "उपस्थित"),
MATCH_ABSENT("Absent", "अनुपस्थित"),
MATCH_NADI_WARNING("Same Nadi can indicate health and progeny concerns", "एउटै नाडीले स्वास्थ्य र सन्तान सम्बन्धी चिन्ता संकेत गर्न सक्छ"),
MATCH_BHAKOOT_DOSHA("Bhakoot Dosha", "भकूट दोष"),
MATCH_FINANCIAL_HARMONY("Financial Harmony", "आर्थिक सामञ्जस्य"),
MATCH_BRIDE_RASHI("Bride Rashi", "वधू राशि"),
MATCH_GROOM_RASHI("Groom Rashi", "वर राशि"),
MATCH_NAKSHATRA_COMPATIBILITY("Nakshatra Compatibility", "नक्षत्र अनुकूलता"),
MATCH_BIRTH_STAR("Birth Star", "जन्म नक्षत्र"),
MATCH_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
MATCH_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
MATCH_GANA("Gana", "गण"),
MATCH_YONI("Yoni", "योनि"),
MATCH_RAJJU_MATCHING("Rajju Matching", "रज्जु मिलान"),
MATCH_LONGEVITY("Longevity", "दीर्घायु"),
MATCH_CONFLICT("Conflict", "द्वन्द्व"),
MATCH_COMPATIBLE("Compatible", "अनुकूल"),
MATCH_RAJJU_DESCRIPTION("Rajju indicates the body parts and their compatibility in marriage.", "रज्जुले शरीरका अंगहरू र विवाहमा तिनीहरूको अनुकूलता संकेत गर्दछ।"),
MATCH_VEDHA_ANALYSIS("Vedha Analysis", "वेध विश्लेषण"),
MATCH_OBSTRUCTION_CHECK("Obstruction Check", "बाधा जाँच"),
MATCH_NONE("None", "कुनै पनि छैन"),
MATCH_VEDHA_DESCRIPTION("Vedha indicates mutual affliction between nakshatras.", "वेधले नक्षत्रहरू बीचको पारस्परिक पीडा संकेत गर्दछ।"),
MATCH_STREE_DEERGHA("Stree Deergha", "स्त्री दीर्घ"),
MATCH_PROSPERITY_FACTORS("Prosperity Factors", "समृद्धि कारकहरू"),
MATCH_STREE_DEERGHA_LABEL("Stree Deergha", "स्त्री दीर्घ"),
MATCH_MAHENDRA("Mahendra", "महेन्द्र"),
MATCH_BENEFICIAL("Beneficial", "लाभदायक"),
MATCH_SUGGESTED_REMEDIES("Suggested Remedies", "सुझाव गरिएका उपायहरू"),
MATCH_VEDIC_RECOMMENDATIONS("Vedic Recommendations", "वैदिक सिफारिसहरू"),
MATCH_REMEDIES_DISCLAIMER("Remedies should be performed under guidance of a qualified astrologer.", "उपायहरू योग्य ज्योतिषीको मार्गदर्शनमा गर्नुपर्छ।"),
MATCH_NO_CHARTS("No Charts", "कुनै कुण्डली छैन"),
MATCH_SELECT_BRIDE_PROFILE("Select bride profile", "वधू प्रोफाइल छान्नुहोस्"),
MATCH_SELECT_GROOM_PROFILE("Select groom profile", "वर प्रोफाइल छान्नुहोस्"),
MATCH_PREPARING_ANALYSIS("Preparing analysis...", "विश्लेषण तयार गर्दै..."),
MATCH_CREATE_CHARTS("Create Charts", "कुण्डली बनाउनुहोस्"),
MATCH_SELECT_TAP_CARDS("Select by tapping cards", "कार्डहरू ट्याप गरेर छान्नुहोस्"),
MATCH_TAP_BRIDE_CARD("Tap bride card to select", "छान्न वधू कार्ड ट्याप गर्नुहोस्"),
MATCH_TAP_GROOM_CARD("Tap groom card to select", "छान्न वर कार्ड ट्याप गर्नुहोस्"),
MATCH_CHARTS_AVAILABLE("%d charts available", "%d कुण्डली उपलब्ध"),
MATCH_NO_CHARTS_AVAILABLE("No charts available", "कुनै कुण्डली उपलब्ध छैन"),
MATCH_SELECTED("Selected", "छानिएको"),
MATCH_COPY_FULL_REPORT("Copy Full Report", "पूर्ण रिपोर्ट कपी गर्नुहोस्"),
MATCH_COPY_FULL_DESC("Complete compatibility analysis", "पूर्ण अनुकूलता विश्लेषण"),
MATCH_COPY_SUMMARY("Copy Summary", "सारांश कपी गर्नुहोस्"),
MATCH_COPY_SUMMARY_DESC("Brief compatibility overview", "संक्षिप्त अनुकूलता अवलोकन"),
MATCH_COPY_SCORES("Copy Scores", "अंकहरू कपी गर्नुहोस्"),
MATCH_COPY_SCORES_DESC("Guna scores only", "गुण अंकहरू मात्र"),
VARNA_BRAHMIN("Brahmin", "ब्राह्मण"),
VARNA_KSHATRIYA("Kshatriya", "क्षत्रिय"),
VARNA_VAISHYA("Vaishya", "वैश्य"),
VARNA_SHUDRA("Shudra", "शूद्र"),
VASHYA_CHATUSHPADA("Quadruped", "चतुष्पद"),
VASHYA_MANAVA("Human", "मानव"),
VASHYA_JALACHARA("Aquatic", "जलचर"),
VASHYA_VANACHARA("Wild", "वनचर"),
VASHYA_KEETA("Insect", "कीट"),
GANA_DEVA("Deva", "देव"),
GANA_DEVA_DESC("Divine - Sattvik, gentle, spiritual", "दैवी - सात्त्विक, सौम्य, आध्यात्मिक"),
GANA_MANUSHYA("Manushya", "मनुष्य"),
GANA_MANUSHYA_DESC("Human - Rajasik, balanced, worldly", "मानव - राजसिक, सन्तुलित, सांसारिक"),
GANA_RAKSHASA("Rakshasa", "राक्षस"),
GANA_RAKSHASA_DESC("Demon - Tamasik, aggressive, dominant", "दानव - तामसिक, आक्रामक, प्रभावशाली"),
YONI_ANIMAL_HORSE("Horse", "घोडा"),
YONI_ANIMAL_ELEPHANT("Elephant", "हात्ती"),
YONI_ANIMAL_SHEEP("Sheep", "भेडा"),
YONI_ANIMAL_SERPENT("Serpent", "सर्प"),
YONI_ANIMAL_DOG("Dog", "कुकुर"),
YONI_ANIMAL_CAT("Cat", "बिरालो"),
YONI_ANIMAL_RAT("Rat", "मुसो"),
YONI_ANIMAL_COW("Cow", "गाई"),
YONI_ANIMAL_BUFFALO("Buffalo", "भैंसी"),
YONI_ANIMAL_TIGER("Tiger", "बाघ"),
YONI_ANIMAL_DEER("Deer", "मृग"),
YONI_ANIMAL_MONKEY("Monkey", "बाँदर"),
YONI_ANIMAL_MONGOOSE("Mongoose", "न्यौरी"),
YONI_ANIMAL_LION("Lion", "सिंह"),
    NADI_ADI("Adi (Vata)", "Adi (Vata)"),
NADI_ADI_DESC("Beginning - Wind element, controls movement and nervous system", "आदि - वायु तत्व, गति र स्नायु प्रणाली नियन्त्रण गर्छ"),
    NADI_MADHYA("Madhya (Pitta)", "Madhya (Pitta)"),
NADI_MADHYA_DESC("Middle - Fire element, controls digestion and metabolism", "मध्य - अग्नि तत्व, पाचन र चयापचय नियन्त्रण गर्छ"),
    NADI_ANTYA("Antya (Kapha)", "Antya (Kapha)"),
NADI_ANTYA_DESC("End - Water element, controls structure and lubrication", "अन्त्य - जल तत्व, संरचना र स्नेहन नियन्त्रण गर्छ"),
COMPAT_EXCELLENT("Excellent Match", "उत्कृष्ट मिलान"),
COMPAT_EXCELLENT_DESC("Highly recommended for marriage. Strong compatibility across all factors with harmonious planetary alignments.", "विवाहको लागि अत्यधिक सिफारिस गरिएको। सबै कारकहरूमा बलियो अनुकूलता र सामञ्जस्यपूर्ण ग्रह संरेखण।"),
COMPAT_GOOD("Good Match", "राम्रो मिलान"),
COMPAT_GOOD_DESC("Recommended. Good overall compatibility with minor differences that can be easily managed.", "सिफारिस गरिएको। सजिलैसँग व्यवस्थापन गर्न सकिने सानातिना भिन्नताहरूसहित राम्रो समग्र अनुकूलता।"),
COMPAT_AVERAGE("Average Match", "औसत मिलान"),
COMPAT_AVERAGE_DESC("Acceptable with some remedies. Moderate compatibility requiring mutual understanding and effort.", "केही उपायहरूसहित स्वीकार्य। पारस्परिक बुझाइ र प्रयास आवश्यक पर्ने मध्यम अनुकूलता।"),
COMPAT_BELOW_AVERAGE("Below Average", "औसतमुनि"),
COMPAT_BELOW_AVERAGE_DESC("Caution advised. Several compatibility issues that need addressing through remedies and counseling.", "सावधानी आवश्यक। उपाय र परामर्शद्वारा सम्बोधन गर्नुपर्ने धेरै अनुकूलता समस्याहरू।"),
COMPAT_POOR("Poor Match", "कमजोर मिलान"),
COMPAT_POOR_DESC("Not recommended. Significant compatibility challenges that may cause ongoing difficulties.", "सिफारिस गरिएको छैन। निरन्तर कठिनाइहरू ल्याउन सक्ने महत्त्वपूर्ण अनुकूलता चुनौतीहरू।"),
VARNA_DESC("Spiritual compatibility and ego harmony", "आध्यात्मिक अनुकूलता र अहंकार सामञ्जस्य"),
    VARNA_COMPATIBLE("Compatible: Groom's Varna ({groom})", "Compatible: Groom's Varna ({groom})"),
    VARNA_INCOMPATIBLE("Mismatch: Bride's Varna ({bride})", "Mismatch: Bride's Varna ({bride})"),
VASHYA_DESC("Mutual attraction and influence", "पारस्परिक आकर्षण र प्रभाव"),
VASHYA_EXCELLENT("Excellent mutual attraction and influence. Both partners can positively influence each other.", "उत्कृष्ट पारस्परिक आकर्षण र प्रभाव। दुवै साझेदारहरू एकअर्कालाई सकारात्मक रूपमा प्रभाव पार्न सक्छन्।"),
VASHYA_VERY_GOOD("Very good compatibility with balanced influence between partners.", "साझेदारहरू बीच सन्तुलित प्रभावसहित धेरै राम्रो अनुकूलता।"),
VASHYA_GOOD("Good compatibility with moderate mutual influence.", "मध्यम पारस्परिक प्रभावसहित राम्रो अनुकूलता।"),
VASHYA_PARTIAL("Partial compatibility. One partner may dominate relationship dynamics.", "आंशिक अनुकूलता। एउटा साझेदारले सम्बन्धको गतिशीलतामा प्रभुत्व जमाउन सक्छ।"),
VASHYA_INCOMPATIBLE("Incompatible Vashya types. May cause power struggles in the relationship.", "असंगत वश्य प्रकारहरू। सम्बन्धमा शक्ति संघर्ष हुन सक्छ।"),
YONI_DESC("Physical and sexual compatibility", "शारीरिक र यौन अनुकूलता"),
YONI_SAME("Same Yoni animal - perfect physical and instinctual compatibility. Strong natural attraction.", "उही योनि पशु - उत्तम शारीरिक र सहज अनुकूलता। बलियो प्राकृतिक आकर्षण।"),
YONI_FRIENDLY("Friendly Yonis - very good physical compatibility. Natural understanding.", "मित्र योनि - धेरै राम्रो शारीरिक अनुकूलता। प्राकृतिक बुझाइ।"),
YONI_NEUTRAL("Neutral Yonis - moderate physical compatibility. Requires some adjustment.", "तटस्थ योनि - मध्यम शारीरिक अनुकूलता। केही समायोजन आवश्यक।"),
YONI_UNFRIENDLY("Unfriendly Yonis - some physical and instinctual differences. Needs conscious effort.", "अमैत्रीपूर्ण योनि - केही शारीरिक र सहज भिन्नताहरू। सचेत प्रयास आवश्यक।"),
YONI_ENEMY("Enemy Yonis - significant physical incompatibility. May face intimacy challenges.", "शत्रु योनि - महत्त्वपूर्ण शारीरिक असंगतता। अन्तरंगता चुनौतीहरू सामना गर्न सक्छ।"),
GANA_DESC("Temperament and behavior compatibility", "स्वभाव र व्यवहार अनुकूलता"),
GANA_SAME("Same Gana - perfect temperamental harmony. Similar approach to life and values.", "उही गण - उत्तम स्वभावगत सामञ्जस्य। जीवन र मूल्यहरूमा समान दृष्टिकोण।"),
GANA_COMPATIBLE("Compatible Ganas - good temperamental harmony with minor differences.", "अनुकूल गण - सानातिना भिन्नताहरूसहित राम्रो स्वभावगत सामञ्जस्य।"),
GANA_PARTIAL("Partially compatible - some temperamental adjustment needed.", "आंशिक अनुकूल - केही स्वभावगत समायोजन आवश्यक।"),
GANA_DIFFERENT("Different temperaments - significant adjustment required. May cause lifestyle clashes.", "फरक स्वभाव - महत्त्वपूर्ण समायोजन आवश्यक। जीवनशैली टकराव हुन सक्छ।"),
GANA_OPPOSITE("Opposite temperaments - major incompatibility. Frequent conflicts likely.", "विपरीत स्वभाव - प्रमुख असंगतता। बारम्बार द्वन्द्व हुन सक्छ।"),
    NADI_DESC("Health and progeny compatibility (most important)", "Health and progeny compatibility (most important)"),
    NADI_DOSHA_PRESENT("NADI DOSHA PRESENT: Same Nadi ({nadi})", "NADI DOSHA PRESENT: Same Nadi ({nadi})"),
NADI_DOSHA_CANCELLED("Same Nadi but CANCELLED:", "उही नाडी तर रद्द:"),
    NADI_DIFFERENT("Different Nadis ({nadi1} & {nadi2})", "Different Nadis ({nadi1} & {nadi2})"),
    NADI_CANCEL_SAME_NAK_DIFF_RASHI("Same Nakshatra ({nakshatra})", "Same Nakshatra ({nakshatra})"),
    NADI_CANCEL_SAME_RASHI_DIFF_NAK("Same Rashi ({rashi})", "Same Rashi ({rashi})"),
    NADI_CANCEL_DIFF_PADA("Same Nakshatra and Rashi but different Padas ({pada1} vs {pada2})", "Same Nakshatra and Rashi but different Padas ({pada1} vs {pada2})"),
    NADI_CANCEL_SPECIAL_PAIR("Special Nakshatra pair ({nak1}-{nak2})", "Special Nakshatra pair ({nak1}-{nak2})"),
    NADI_CANCEL_LORDS_FRIENDS("Moon sign lords ({lord1} & {lord2})", "Moon sign lords ({lord1} & {lord2})"),
NADI_CANCEL_SAME_NAK_LORD("Both Nakshatras ruled by {lord} - Partial Cancellation", "दुवै नक्षत्र {lord} द्वारा शासित - आंशिक रद्द"),
VARNA_DETAILED_COMPATIBLE("This creates excellent spiritual harmony with natural respect flowing from bride to groom. Partners will have compatible life philosophies, values, and approaches to dharma. The groom's natural leadership in spiritual matters will be appreciated.", "यसले दुलहीबाट दुलाहातिर प्राकृतिक सम्मान प्रवाहसहित उत्कृष्ट आध्यात्मिक सामञ्जस्य सिर्जना गर्दछ। साझेदारहरूको जीवन दर्शन, मूल्यहरू र धर्मप्रति दृष्टिकोण मिल्नेछ। आध्यात्मिक विषयहरूमा दुलाहाको प्राकृतिक नेतृत्व सराहना गरिनेछ।"),
VARNA_DETAILED_INCOMPATIBLE("This may create ego conflicts and power struggles. The bride may feel she has to compromise her values or suppress her intellect. Both partners need conscious effort to respect each other's perspectives and maintain balance.", "यसले अहंकार द्वन्द्व र शक्ति संघर्ष सिर्जना गर्न सक्छ। दुलहीले आफ्ना मूल्यहरूमा सम्झौता गर्नु परोस् वा आफ्नो बुद्धि दमन गर्नुपर्ला जस्तो महसुस गर्न सक्छिन्। दुवै साझेदारहरूले एकअर्काको दृष्टिकोणलाई सम्मान गर्न र सन्तुलन कायम राख्न सचेत प्रयास चाहिन्छ।"),
VASHYA_REMEDY_LOW("Remedy: Worship Lord Shiva and Goddess Parvati together on Mondays. Practice mutual respect and avoid trying to dominate each other. Strengthen Venus through Friday fasts and donations of white items.", "उपाय: सोमबारमा भगवान शिव र देवी पार्वतीको सँगै पूजा गर्नुहोस्। पारस्परिक सम्मान अभ्यास गर्नुहोस् र एकअर्कालाई हावी गर्न नगर्नुहोस्। शुक्रबार व्रत र सेतो वस्तुहरूको दानद्वारा शुक्रलाई बलियो बनाउनुहोस्।"),
    YONI_REMEDY_LOW("Remedy: Worship Kamadeva (God of Love)", "Remedy: Worship Kamadeva (God of Love)"),
GANA_REMEDY_LOW("Remedy: Chant Ganapati Atharvasheersham daily for 41 days. Perform joint Ganesh puja every month. Practice patience, tolerance, and conscious communication to bridge temperamental differences. Couples counseling may be beneficial.", "उपाय: ४१ दिन दैनिक गणपति अथर्वशीर्षम् जाप गर्नुहोस्। प्रत्येक महिना संयुक्त गणेश पूजा गर्नुहोस्। स्वभावगत भिन्नताहरू पाट्न धैर्य, सहनशीलता र सचेत सञ्चार अभ्यास गर्नुहोस्। जोडी परामर्श लाभदायक हुन सक्छ।"),
    NADI_REMEDY_LOW("Remedy: This is critical - consult qualified astrologer immediately. Perform Maha Mrityunjaya Jaap (108 times daily for 40 days)", "Remedy: This is critical - consult qualified astrologer immediately. Perform Maha Mrityunjaya Jaap (108 times daily for 40 days)"),
VARNA_IMPORTANCE("Varna represents the spiritual evolution and work nature of the couple. It measures ego compatibility and mutual respect in the relationship.", "वर्णले जोडीको आध्यात्मिक विकास र कार्य प्रकृति प्रतिनिधित्व गर्दछ। यसले सम्बन्धमा अहंकार अनुकूलता र पारस्परिक सम्मान मापन गर्दछ।"),
    VARNA_BRAHMIN_NATURE("Brahmin (Fire signs)", "Brahmin (Fire signs)"),
    VARNA_KSHATRIYA_NATURE("Kshatriya (Earth signs)", "Kshatriya (Earth signs)"),
    VARNA_VAISHYA_NATURE("Vaishya (Air signs)", "Vaishya (Air signs)"),
    VARNA_SHUDRA_NATURE("Shudra (Water signs)", "Shudra (Water signs)"),
VASHYA_IMPORTANCE("Vashya indicates natural attraction, influence capacity, and control dynamics. It shows who holds sway in decision-making and emotional matters.", "वश्यले प्राकृतिक आकर्षण, प्रभाव क्षमता र नियन्त्रण गतिशीलता संकेत गर्दछ। यसले निर्णय लिने र भावनात्मक मामिलाहरूमा कसले प्रभाव राख्छ भनेर देखाउँछ।"),
VASHYA_POWER_BALANCE("Balanced Vashya creates equal partnership. Imbalance may lead to dominance issues but can work if both partners accept their natural roles.", "सन्तुलित वश्यले समान साझेदारी सिर्जना गर्दछ। असन्तुलनले प्रभुत्व समस्या ल्याउन सक्छ तर दुवै साझेदारहरूले आफ्नो प्राकृतिक भूमिका स्वीकार गरे काम गर्न सक्छ।"),
YONI_IMPORTANCE("Yoni represents physical, sexual, and biological compatibility. It's based on animal nature of birth nakshatras and indicates instinctual harmony.", "योनिले शारीरिक, यौन र जैविक अनुकूलता प्रतिनिधित्व गर्दछ। यो जन्म नक्षत्रको पशु प्रकृतिमा आधारित छ र सहज सामञ्जस्य संकेत गर्दछ।"),
    YONI_RELATIONSHIPS_EXPLAINED("Same yoni = Perfect (4 points)", "Same yoni = Perfect (4 points)"),
GANA_IMPORTANCE("Gana measures behavioral temperament and nature. It indicates how partners will behave in conflicts and daily life situations.", "गणले व्यवहारिक स्वभाव र प्रकृति मापन गर्दछ। यसले साझेदारहरूले द्वन्द्व र दैनिक जीवन परिस्थितिहरूमा कसरी व्यवहार गर्छन् भनेर संकेत गर्दछ।"),
    GANA_COMPATIBILITY_DETAILS("Deva-Deva = 6 points (best)", "Deva-Deva = 6 points (best)"),
    NADI_IMPORTANCE("Nadi is the MOST IMPORTANT guna (8 points)", "Nadi is the MOST IMPORTANT guna (8 points)"),
    NADI_TYPES_EXPLAINED("Adi (Vata)", "Adi (Vata)"),
NADI_ZERO_EXPLANATION("Zero points indicates Same Nadi without cancellation - this is the most serious dosha in matchmaking. Immediate astrological consultation and extensive remedies are mandatory.", "शून्य अंकले रद्द बिना उही नाडी संकेत गर्दछ - यो मिलानमा सबैभन्दा गम्भीर दोष हो। तत्काल ज्योतिषीय परामर्श र व्यापक उपायहरू अनिवार्य छन्।"),
NADI_CANCEL_EXPLANATION("Nadi Dosha can be cancelled in several specific scenarios according to classical Vedic texts. These cancellations are based on deeper astrological principles that override the superficial Nadi match.", "नाडी दोष शास्त्रीय वैदिक ग्रन्थहरू अनुसार धेरै विशिष्ट परिस्थितिहरूमा रद्द गर्न सकिन्छ। यी रद्दहरू गहन ज्योतिषीय सिद्धान्तहरूमा आधारित छन् जसले सतही नाडी मिलानलाई ओभरराइड गर्दछ।"),
COMPAT_RECOMMEND_MARRIAGE_TIMING("Recommended Marriage Timing", "सिफारिस गरिएको विवाह समय"),
COMPAT_TIMING_IMMEDIATE("Marriage can proceed without delay. Choose an auspicious muhurta during favorable planetary transits for both charts.", "विवाह ढिलाइ बिना अगाडि बढ्न सक्छ। दुवै कुण्डलीको लागि अनुकूल ग्रह गोचरको समयमा शुभ मुहूर्त छान्नुहोस्।"),
    COMPAT_TIMING_AFTER_REMEDIES("Proceed after completing essential remedies (minimum 40-90 days)", "Proceed after completing essential remedies (minimum 40-90 days)"),
COMPAT_TIMING_EXTENDED_REMEDIES("Delay marriage for 6-12 months while performing comprehensive remedies. Use this time for counseling and conscious preparation.", "व्यापक उपायहरू गर्दै ६-१२ महिना विवाहमा ढिलाइ गर्नुहोस्। परामर्श र सचेत तयारीको लागि यो समय प्रयोग गर्नुहोस्।"),
COMPAT_TIMING_RECONSIDER("Seriously reconsider this match. If proceeding, delay minimum 1 year with extensive remedies, counseling, and spiritual preparation.", "यस मिलानलाई गम्भीरतापूर्वक पुनर्विचार गर्नुहोस्। अगाडि बढ्दै हुनुहुन्छ भने, व्यापक उपाय, परामर्श र आध्यात्मिक तयारीसहित न्यूनतम १ वर्ष ढिलाइ गर्नुहोस्।"),
COMPAT_RECOMMEND_RELATIONSHIP_FOCUS("Relationship Focus Areas", "सम्बन्ध फोकस क्षेत्रहरू"),
COMPAT_FOCUS_SPIRITUAL("Spiritual Growth Together: Practice joint meditation, visit temples together, study spiritual texts, maintain shared spiritual practices.", "सँगै आध्यात्मिक विकास: संयुक्त ध्यान अभ्यास गर्नुहोस्, सँगै मन्दिरहरू भ्रमण गर्नुहोस्, आध्यात्मिक ग्रन्थहरू अध्ययन गर्नुहोस्, साझा आध्यात्मिक अभ्यासहरू कायम राख्नुहोस्।"),
COMPAT_FOCUS_COMMUNICATION("Mental & Communication: Schedule regular check-ins, practice active listening, express appreciation daily, address conflicts calmly.", "मानसिक र सञ्चार: नियमित जाँच-पडताल तालिका बनाउनुहोस्, सक्रिय सुनाइ अभ्यास गर्नुहोस्, दैनिक प्रशंसा व्यक्त गर्नुहोस्, द्वन्द्वहरूलाई शान्तपूर्वक सम्बोधन गर्नुहोस्।"),
COMPAT_FOCUS_PHYSICAL("Physical Harmony: Prioritize physical affection, maintain health together, respect boundaries, create intimate connection rituals.", "शारीरिक सामञ्जस्य: शारीरिक स्नेहलाई प्राथमिकता दिनुहोस्, सँगै स्वास्थ्य कायम राख्नुहोस्, सीमाहरूको सम्मान गर्नुहोस्, अन्तरंग सम्बन्ध अनुष्ठानहरू सिर्जना गर्नुहोस्।"),
COMPAT_FOCUS_TEMPERAMENT("Temperamental Balance: Understand personality differences, practice patience, compromise consciously, celebrate individual strengths.", "स्वभावगत सन्तुलन: व्यक्तित्व भिन्नताहरू बुझ्नुहोस्, धैर्य अभ्यास गर्नुहोस्, सचेत रूपमा सम्झौता गर्नुहोस्, व्यक्तिगत शक्तिहरू मनाउनुहोस्।"),
COMPAT_FOCUS_FINANCIAL("Financial Harmony: Create joint financial plans, discuss money values openly, set shared goals, respect spending differences.", "आर्थिक सामञ्जस्य: संयुक्त वित्तीय योजनाहरू बनाउनुहोस्, पैसा मूल्यहरू खुलेर छलफल गर्नुहोस्, साझा लक्ष्यहरू सेट गर्नुहोस्, खर्च भिन्नताहरूलाई सम्मान गर्नुहोस्।"),
COMPAT_FOCUS_HEALTH("Health & Progeny: Maintain healthy lifestyles, support each other's wellness, prepare mindfully for parenthood.", "स्वास्थ्य र सन्तान: स्वस्थ जीवनशैली कायम राख्नुहोस्, एकअर्काको कल्याणलाई समर्थन गर्नुहोस्, मातृत्व/पितृत्वको लागि सावधानीपूर्वक तयारी गर्नुहोस्।")
}
