package com.astro.storm.core.common
enum class StringKeyVarga(override val en: String, override val ne: String) : StringKeyInterface {
    VARGA_D1_TITLE("Rashi (D1)", "Rashi (D1)"),
VARGA_D1_DESC("Physical Body, General Life", "भौतिक शरीर, सामान्य जीवन"),
    VARGA_D2_TITLE("Hora (D2)", "Hora (D2)"),
VARGA_D2_DESC("Wealth, Prosperity", "धन, समृद्धि"),
    VARGA_D3_TITLE("Drekkana (D3)", "Drekkana (D3)"),
VARGA_D3_DESC("Siblings, Courage", "भाइबहिनी, साहस"),
    VARGA_D4_TITLE("Chaturthamsa (D4)", "Chaturthamsa (D4)"),
VARGA_D4_DESC("Fortune, Property", "भाग्य, सम्पत्ति"),
    VARGA_D7_TITLE("Saptamsa (D7)", "Saptamsa (D7)"),
VARGA_D7_DESC("Children, Progeny", "सन्तान"),
    VARGA_D9_TITLE("Navamsa (D9)", "Navamsa (D9)"),
VARGA_D9_DESC("Marriage, Dharma", "विवाह, धर्म"),
    VARGA_D10_TITLE("Dasamsa (D10)", "Dasamsa (D10)"),
VARGA_D10_DESC("Career, Profession", "क्यारियर, पेशा"),
    VARGA_D12_TITLE("Dwadasamsa (D12)", "Dwadasamsa (D12)"),
VARGA_D12_DESC("Parents, Ancestry", "आमाबुवा, पुर्खा"),
    VARGA_D16_TITLE("Shodasamsa (D16)", "Shodasamsa (D16)"),
VARGA_D16_DESC("Vehicles, Pleasures", "सवारी, आनन्द"),
    VARGA_D20_TITLE("Vimsamsa (D20)", "Vimsamsa (D20)"),
VARGA_D20_DESC("Spiritual Life", "आध्यात्मिक जीवन"),
    VARGA_D24_TITLE("Siddhamsa (D24)", "Siddhamsa (D24)"),
VARGA_D24_DESC("Education, Learning", "शिक्षा, सिकाइ"),
    VARGA_D27_TITLE("Bhamsa (D27)", "Bhamsa (D27)"),
VARGA_D27_DESC("Strength, Weakness", "बल, कमजोरी"),
    VARGA_D30_TITLE("Trimsamsa (D30)", "Trimsamsa (D30)"),
VARGA_D30_DESC("Evils, Misfortunes", "अशुभ, दुर्भाग्य"),
    VARGA_D40_TITLE("Khavedamsa (D40)", "Khavedamsa (D40)"),
VARGA_D40_DESC("Auspicious/Inauspicious Effects", "शुभाशुभ प्रभावहरू"),
    VARGA_D45_TITLE("Akshavedamsa (D45)", "Akshavedamsa (D45)"),
VARGA_D45_DESC("General Indications", "सामान्य सङ्केतहरू"),
    VARGA_D60_TITLE("Shashtiamsa (D60)", "Shashtiamsa (D60)"),
VARGA_D60_DESC("Past Life Karma", "पूर्वजन्मको कर्म"),
    VARGA_D5_TITLE("Panchamsa (D5)", "Panchamsa (D5)"),
VARGA_D5_DESC("Fame, Power, Authority", "ख्याति, शक्ति, अधिकार"),
    VARGA_D6_TITLE("Shasthamsa (D6)", "Shasthamsa (D6)"),
VARGA_D6_DESC("Health, Debts, Enemies", "स्वास्थ्य, ऋण, शत्रु"),
    VARGA_D8_TITLE("Ashtamsa (D8)", "Ashtamsa (D8)"),
VARGA_D8_DESC("Longevity, Transformation", "आयु, रूपान्तरण"),
    VARGA_D11_TITLE("Rudramsa (D11)", "Rudramsa (D11)"),
VARGA_D11_DESC("Victory, Defeat, Ups and Downs", "जीत, हार, उतार-चढाव"),
    VARGA_D81_TITLE("Navnavamsa (D81)", "Navnavamsa (D81)"),
VARGA_D81_DESC("Hidden Potentials, Deep Navamsa", "लुकेका सम्भावनाहरू"),
    VARGA_D108_TITLE("Ashtottarshamsa (D108)", "Ashtottarshamsa (D108)"),
VARGA_D108_DESC("Blessings, Divine Protection", "आशिर्वाद, दैवी सुरक्षा"),
    VARGA_D144_TITLE("Dwadash-Dwadashamsa (D144)", "Dwadash-Dwadashamsa (D144)"),
VARGA_D144_DESC("Minute Details, Ultimate Micro-analysis", "अति सूक्ष्म विवरण"),
VARGA_PLANETARY_POSITIONS("PLANETARY POSITIONS", "ग्रह स्थितिहरू"),
SHODASHVARGA_TITLE("Shodashvarga Strength", "षोडशवर्ग बल"),
SHODASHVARGA_SUBTITLE("16-Divisional Chart Analysis", "१६-विभाजन चार्ट विश्लेषण"),
SHODASHVARGA_ABOUT("About Shodashvarga", "षोडशवर्गको बारेमा"),
SHODASHVARGA_ABOUT_DESC("Shodashvarga Bala evaluates planetary strength across all 16 divisional charts. This comprehensive analysis reveals how effectively each planet can deliver its results.", "षोडशवर्ग बलले सबै १६ विभाजन चार्टहरूमा ग्रह बलको मूल्यांकन गर्दछ। यो व्यापक विश्लेषणले प्रत्येक ग्रहले आफ्नो परिणाम कति प्रभावकारी रूपमा प्रदान गर्न सक्छ भनेर प्रकट गर्दछ।"),
SHODASHVARGA_BALA("Shodashvarga Bala", "षोडशवर्ग बल"),
VARGA_POSITIONS("Varga Positions", "वर्ग स्थितिहरू"),
SHODASHVARGA_CALCULATION_ERROR("Failed to calculate Shodashvarga analysis", "षोडशवर्ग विश्लेषण गणना गर्न असफल"),
    SHODASHVARGA_VARGOTTAMA_COUNT_FMT("Vargottama in %d chart(s)", "Vargottama in %d chart(s)"),
SHODASHVARGA_NO_VARGOTTAMA("No Vargottama planets found", "कुनै वर्गोत्तम ग्रह फेला परेन"),
SHODASHVARGA_16_DIAGRAMS_HEADER("The 16 Divisional Charts:", "१६ षोडशवर्ग कुण्डलीहरू:"),
    HORA_ANALYSIS_TITLE("Hora (D-2)", "Hora (D-2)"),
HORA_ANALYSIS_SUBTITLE("Wealth and Financial Potential", "धन र आर्थिक सम्भावना"),
HORA_ANALYSIS_ABOUT("About Hora Chart", "होरा चार्टको बारेमा"),
HORA_ANALYSIS_ABOUT_DESC("Hora chart divides each sign into Sun and Moon halves, revealing wealth accumulation patterns and financial potential.", "होरा चार्टले प्रत्येक राशिलाई सूर्य र चन्द्र आधामा विभाजन गर्छ, धन संचय ढाँचा र आर्थिक सम्भावना प्रकट गर्दछ।"),
HORA_SUN_PLANETS("Planets in Sun Hora", "सूर्य होरामा ग्रहहरू"),
HORA_MOON_PLANETS("Planets in Moon Hora", "चन्द्र होरामा ग्रहहरू"),
HORA_DOMINANT("Dominant Hora", "प्रभावशाली होरा"),
HORA_BALANCE("Hora Balance", "होरा सन्तुलन"),
HORA_WEALTH_INDICATORS("Wealth Indicators", "धन सूचकहरू"),
HORA_INCOME_POTENTIAL("Income Potential", "आय सम्भावना"),
    DREKKANA_ANALYSIS_TITLE("Drekkana (D-3)", "Drekkana (D-3)"),
DREKKANA_ANALYSIS_SUBTITLE("Siblings and Courage", "भाइबहिनी र साहस"),
DREKKANA_ANALYSIS_ABOUT("About Drekkana Chart", "द्रेष्काण चार्टको बारेमा"),
DREKKANA_ANALYSIS_ABOUT_DESC("Drekkana chart reveals sibling relationships, courage, and personal initiative. Each sign is divided into three 10-degree portions.", "द्रेष्काण चार्टले भाइबहिनी सम्बन्ध, साहस, र व्यक्तिगत पहलकदमी प्रकट गर्दछ। प्रत्येक राशि तीन १०-अंश भागमा विभाजित छ।"),
DREKKANA_TYPE("Drekkana Type", "द्रेष्काण प्रकार"),
    DREKKANA_FIRST("First Drekkana (0-10Â°)", "First Drekkana (0-10Â°)"),
    DREKKANA_SECOND("Second Drekkana (10-20Â°)", "Second Drekkana (10-20Â°)"),
    DREKKANA_THIRD("Third Drekkana (20-30Â°)", "Third Drekkana (20-30Â°)"),
DREKKANA_SIBLING_KARMA("Sibling Karma", "भाइबहिनी कर्म"),
DREKKANA_COURAGE_LEVEL("Courage Level", "साहस स्तर"),
HORA_SELF_EARNED("Self Earned", "आर्जित"),
HORA_INHERITED("Inherited", "पैतृक"),
HORA_POTENTIAL("Wealth Potential", "धन सम्भावना"),
HORA_POTENTIAL_EXCEPTIONAL("Exceptional Wealth", "असाधारण धन"),
HORA_POTENTIAL_HIGH("High Wealth", "उच्च धन"),
HORA_POTENTIAL_MODERATE("Moderate Wealth", "मध्यम धन"),
HORA_POTENTIAL_AVERAGE("Average Wealth", "औसत धन"),
HORA_POTENTIAL_NEEDS_EFFORT("Needs Effort", "प्रयास आवश्यक"),
DREKKANA_COURAGE_TITLE("Courage Analysis", "साहस विश्लेषण"),
DREKKANA_SHORT_JOURNEYS("Short Journeys", "छोटो यात्रा"),
DREKKANA_YOUNGER("Younger Siblings", "साना भाइबहिनी"),
DREKKANA_ELDER("Elder Siblings", "ठूला भाइबहिनी"),
DREKKANA_RELATIONSHIP("Relationship", "सम्बन्ध"),
DREKKANA_COMMUNICATION_TITLE("Communication", "सञ्चार"),
DREKKANA_OVERALL("Overall", "समग्र"),
DREKKANA_WRITING("Writing", "लेखन"),
DREKKANA_SPEAKING("Speaking", "बोल्ने"),
DREKKANA_ARTISTIC_TALENTS("Artistic Talents", "कलात्मक प्रतिभा"),
HORA_SUN_TITLE("Sun Hora - Self-Earned Wealth", "सूर्य होरा - स्व-अर्जित धन"),
HORA_SUN_DESC("These planets indicate potential for wealth through your own efforts", "यी ग्रहहरूले तपाईंको आफ्नै प्रयासबाट धनको सम्भावना संकेत गर्छन्"),
HORA_MOON_TITLE("Moon Hora - Inherited/Liquid Wealth", "चन्द्र होरा - विरासत/तरल धन"),
HORA_MOON_DESC("These planets indicate potential for inherited or liquid assets", "यी ग्रहहरूले विरासत वा तरल सम्पत्तिको सम्भावना संकेत गर्छन्"),
HORA_WEALTH_SOURCES("Wealth Sources", "धनका स्रोतहरू"),
DREKKANA_PHYSICAL("Physical", "शारीरिक"),
DREKKANA_MENTAL("Mental", "मानसिक"),
DREKKANA_INITIATIVE("Initiative", "पहल"),
DREKKANA_ARTISTIC("Artistic Talents", "कलात्मक प्रतिभाहरू"),
    VARGA_D1_NAME("Lagna Chart (Rashi)", "Lagna Chart (Rashi)"),
VARGA_D2_NAME("Hora Chart", "होरा कुण्डली"),
VARGA_D3_NAME("Drekkana Chart", "द्रेक्काण कुण्डली"),
VARGA_D4_NAME("Chaturthamsa Chart", "चतुर्थांश कुण्डली"),
VARGA_D7_NAME("Saptamsa Chart", "सप्तांश कुण्डली"),
VARGA_D9_NAME("Navamsa Chart", "नवांश कुण्डली"),
VARGA_D10_NAME("Dasamsa Chart", "दशांश कुण्डली"),
VARGA_D12_NAME("Dwadasamsa Chart", "द्वादशांश कुण्डली"),
VARGA_D16_NAME("Shodasamsa Chart", "षोडशांश कुण्डली"),
VARGA_D20_NAME("Vimsamsa Chart", "विंशांश कुण्डली"),
VARGA_D24_NAME("Siddhamsa Chart", "चतुर्विंशांश कुण्डली"),
VARGA_D27_NAME("Bhamsa Chart", "सप्तविंशांश कुण्डली"),
VARGA_D30_NAME("Trimsamsa Chart", "त्रिंशांश कुण्डली"),
VARGA_D60_NAME("Shashtiamsa Chart", "षष्टिांश कुण्डली"),
VARGA_D3_DESC_FULL("Siblings, Courage, Vitality", "भाइबहिनी, साहस, जीवनशक्ति"),
VARGA_D9_DESC_FULL("Marriage, Dharma, Fortune", "विवाह, धर्म, भाग्य"),
VARGA_D10_DESC_FULL("Career, Profession", "क्यारियर, पेशा"),
VARGA_D12_DESC_FULL("Parents, Ancestry", "आमाबुबा, पुर्खा"),
VARGA_D16_DESC_FULL("Vehicles, Pleasures", "सवारी, आनन्द"),
VARGA_D20_DESC_FULL("Spiritual Life", "आध्यात्मिक जीवन"),
VARGA_D24_DESC_FULL("Education, Learning", "शिक्षा, सिकाइ"),
VARGA_D27_DESC_FULL("Strength, Weakness", "बल, कमजोरी"),
VARGA_D30_DESC_FULL("Evils, Misfortunes", "दुर्भाग्य, विपत्ति"),
VARGA_D60_DESC_FULL("Past Life Karma", "पूर्वजन्मको कर्म"),
VARGA_LAGNA("Lagna", "लग्न"),
VARGA_HORA("Hora", "होरा"),
VARGA_DREKKANA("Drekkana", "द्रेक्काण"),
VARGA_SAPTAMSA("Saptamsa", "सप्तांश"),
VARGA_NAVAMSA("Navamsa", "नवांश"),
VARGA_DASAMSA("Dasamsa", "दशांश"),
VARGA_BHAMSA("Bhamsa", "भांश"),
HORA_NATURE_BENEFIC("Benefic", "शुभ"),
HORA_NATURE_MALEFIC("Malefic", "पापी"),
HORA_NATURE_NEUTRAL("Neutral", "तटस्थ")
}
