package com.astro.storm.core.common
enum class StringKeyPrashnaPart2(override val en: String, override val ne: String) : StringKeyInterface {
PRASHNA_REC_WANING_MOON("Waning Moon suggests completion or ending phases. Good for finishing, not starting.", "कृष्ण पक्षको चन्द्रमाले समाप्ति वा अन्त्यको चरणलाई संकेत गर्दछ। सुरु गर्नका लागि होइन, समाप्त गर्नका लागि राम्रो छ।"),
PRASHNA_REC_STRENGTHEN_MOON("Strengthen Moon energies through white colors, pearl, and Monday observances.", "सेतो रंग, मोती र सोमबारको व्रत मार्फत चन्द्रमाको ऊर्जालाई बलियो बनाउनुहोस्।"),
PRASHNA_REC_AVOID_CONFRONTATION("Avoid direct confrontation. Work behind the scenes temporarily.", "प्रत्यक्ष टकरावबाट बच्नुहोस्। अस्थायी रूपमा पर्दा पछाडि काम गर्नुहोस्।"),
PRASHNA_REC_REVIEW_PAST("Review past decisions. Something may need to be reconsidered.", "विगतका निर्णयहरू समीक्षा गर्नुहोस्। केही कुरामा पुनर्विचार गर्नुपर्ने हुन सक्छ।"),
PRASHNA_REC_ACT_PROMPTLY("Act promptly while the favorable applying aspect is in effect.", "अनुकूल पक्ष प्रभावकारी हुँदा तुरुन्तै काम गर्नुहोस्।"),
PRASHNA_REC_SEEK_ASSISTANCE("Seek assistance from an intermediary or third party.", "मध्यस्थ वा तेस्रो पक्षबाट सहयोग खोज्नुहोस्।"),
PRASHNA_REC_PROPITIATE("Propitiate %1\$s to strengthen %2\$sth house matters.", "%2\$s औं भावको विषयलाई बलियो बनाउन %1\$s लाई प्रसन्न पार्नुहोस्।"),
PRASHNA_REC_REASK_NEW_SIGN("Consider re-asking when Moon enters a new sign.", "चन्द्रमा नयाँ राशिमा प्रवेश गरेपछि पुनः सोध्ने विचार गर्नुहोस्।"),
PRASHNA_SUMMARY_TITLE("Prashna Analysis Summary", "प्रश्न विश्लेषण सारांश"),
PRASHNA_SUMMARY_MATTER("Matter", "विषय"),
PRASHNA_SUMMARY_CATEGORY("Category", "श्रेणी"),
PRASHNA_SUMMARY_TIME("Time", "समय"),
PRASHNA_SUMMARY_CONFIDENCE("Confidence Score", "निश्चितता अंक"),
PRASHNA_TITHI_SHUKLA("Shukla %s", "शुक्ल %s"),
PRASHNA_TITHI_KRISHNA("Krishna %s", "कृष्ण %s"),
PRASHNA_TITHI_PRATIPADA("Pratipada", "प्रतिपदा"),
PRASHNA_TITHI_DWITIYA("Dwitiya", "द्वितीया"),
PRASHNA_TITHI_TRITIYA("Tritiya", "तृतीया"),
PRASHNA_TITHI_CHATURTHI("Chaturthi", "चतुर्थी"),
PRASHNA_TITHI_PANCHAMI("Panchami", "पञ्चमी"),
PRASHNA_TITHI_SHASHTHI("Shashthi", "षष्ठी"),
PRASHNA_TITHI_SAPTAMI("Saptami", "सप्तमी"),
PRASHNA_TITHI_ASHTAMI("Ashtami", "अष्टमी"),
PRASHNA_TITHI_NAVAMI("Navami", "नवमी"),
PRASHNA_TITHI_DASHAMI("Dashami", "दशमी"),
PRASHNA_TITHI_EKADASHI("Ekadashi", "एकादशी"),
PRASHNA_TITHI_DWADASHI("Dwadashi", "द्वादशी"),
PRASHNA_TITHI_TRAYODASHI("Trayodashi", "त्रयोदशी"),
PRASHNA_TITHI_CHATURDASHI("Chaturdashi", "चतुर्दशी"),
PRASHNA_TITHI_PURNIMA("Purnima", "पूर्णिमा"),
PRASHNA_TITHI_AMAVASYA("Amavasya", "औंसी"),
PRASHNA_YOGAS_TITLE("Special Yogas Present", "विशेष योगहरू"),
PRASHNA_HOUSE_1_NAME("Lagna/Querent", "लग्न/प्रश्नकर्ता"),
PRASHNA_HOUSE_2_NAME("Dhana", "धन"),
PRASHNA_HOUSE_3_NAME("Sahaja", "सहज"),
PRASHNA_HOUSE_4_NAME("Sukha", "सुख"),
PRASHNA_HOUSE_5_NAME("Putra", "पुत्र"),
PRASHNA_HOUSE_6_NAME("Ripu", "रिपु"),
PRASHNA_HOUSE_7_NAME("Kalatra", "कलत्र"),
PRASHNA_HOUSE_8_NAME("Ayu", "आयु"),
PRASHNA_HOUSE_9_NAME("Dharma", "धर्म"),
PRASHNA_HOUSE_10_NAME("Karma", "कर्म"),
PRASHNA_HOUSE_11_NAME("Labha", "लाभ"),
PRASHNA_HOUSE_12_NAME("Vyaya", "व्यय"),
PRASHNA_BODY_HEAD("Head", "टाउको"),
PRASHNA_BODY_FACE_MOUTH("Face/Mouth", "अनुहार/मुख"),
PRASHNA_BODY_ARMS_SHOULDERS("Arms/Shoulders", "हात/काँध"),
PRASHNA_BODY_CHEST("Chest", "छाती"),
PRASHNA_BODY_UPPER_ABDOMEN("Upper Abdomen", "माथिल्लो पेट"),
PRASHNA_BODY_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
PRASHNA_BODY_BELOW_NAVEL("Below Navel", "नाभि मुनि"),
PRASHNA_BODY_PRIVATE_PARTS("Private Parts", "गुप्ताङ्ग"),
PRASHNA_BODY_THIGHS("Thighs", "तिघ्रा"),
PRASHNA_BODY_KNEES("Knees", "घुँडा"),
PRASHNA_BODY_CALVES_ANKLES("Calves/Ankles", "पिँडुला/कुर्कुच्चा"),
PRASHNA_BODY_FEET("Feet", "गोडा"),
PRASHNA_DIR_EAST("East", "पूर्व"),
PRASHNA_DIR_SOUTH_EAST("South-East", "दक्षिण-पूर्व"),
PRASHNA_DIR_WEST("West", "पश्चिम"),
PRASHNA_DIR_NORTH("North", "उत्तर"),
PRASHNA_DIR_EAST_NORTH("North-East", "उत्तर-पूर्व"),
PRASHNA_DIR_SOUTH("South", "दक्षिण"),
PRASHNA_DIR_SOUTH_WEST("South-West", "दक्षिण-पश्चिम"),
PRASHNA_DIR_NORTH_WEST("North-West", "उत्तर-पश्चिम"),
PRASHNA_DIR_NORTH_EAST("North-East", "उत्तर-पूर्व"),
PRASHNA_CHART_LABEL("Prashna Chart", "प्रश्न कुण्डली"),
PRASHNA_QUESTION_LOCATION("Question Location", "प्रश्नस्थान"),
PRASHNA_YES("Yes", "हो"),
PRASHNA_NO("No", "होइन"),
PRASHNA_POSITIVE_FACTORS("Positive Factors", "सकारात्मक कारकहरू"),
PRASHNA_DIRECTION_SEARCH("Direction to search", "खोज्ने दिशा"),
PRASHNA_RECOVERY_LIKELIHOOD("Recovery likelihood", "प्राप्ति सम्भावना"),
PRASHNA_SAFETY_LEVEL("Safety level", "सुरक्षा स्तर"),
PRASHNA_SUCCESS_PROBABILITY("Success probability", "सफलताको सम्भावना"),
PRASHNA_TIMING_INDICATION("Timing indication", "समय संकेत"),
PRASHNA_RECOVERY_OUTLOOK("Recovery outlook", "सुधारको दृष्टिकोण"),
PRASHNA_ACTIVE("Active", "सक्रिय"),
PRASHNA_INACTIVE("Inactive", "निष्क्रिय"),
PRASHNA_STRENGTH("Strength", "बल"),
PRASHNA_CAT_GENERAL("General", "सामान्य"),
PRASHNA_CAT_CAREER("Career & Profession", "क्यारियर र पेशा"),
PRASHNA_CAT_RELATIONSHIP("Relationships", "सम्बन्धहरू"),
PRASHNA_CAT_HEALTH("Health", "स्वास्थ्य"),
PRASHNA_CAT_FINANCE("Finance", "वित्त"),
PRASHNA_CAT_TRAVEL("Travel", "यात्रा"),
PRASHNA_CAT_EDUCATION("Education", "शिक्षा"),
PRASHNA_CAT_LEGAL("Legal Matters", "कानुनी मामिलाहरू"),
PRASHNA_CAT_PROPERTY("Property", "सम्पत्ति"),
PRASHNA_CAT_LOST_ITEM("Lost Items", "हराएका वस्तुहरू")
}
