package com.astro.storm.core.common

enum class StringKeyRemedy(override val en: String, override val ne: String, override val hi: String) : StringKeyInterface {
    // Planetary Strength Labels
    STRENGTH_VERY_STRONG("Very Strong", "अति बलियो", "अति बलियह"),
    ,
    STRENGTH_STRONG("Strong", "बलियो", "बलियह"),
    ,
    STRENGTH_MODERATE("Moderate", "मध्यम", "मध्यम"),
    ,
    STRENGTH_WEAK("Weak", "कमजोर", "कमजोर"),
    ,
    STRENGTH_VERY_WEAK("Very Weak", "अति कमजोर", "अति कमजोर"),
    ,
    STRENGTH_AFFLICTED("Afflicted", "पीडित", "पीडित"),

    ,

    // Remedy Categories
    CAT_GEMSTONE("Gemstone", "रत्न", "रत्न"),
    ,
    CAT_MANTRA("Mantra", "मन्त्र", "मन्त्र"),
    ,
    CAT_YANTRA("Yantra", "यन्त्र", "यन्त्र"),
    ,
    CAT_CHARITY("Charity", "दान", "दान"),
    ,
    CAT_FASTING("Fasting", "व्रत", "व्रत"),
    ,
    CAT_COLOR("Color Therapy", "रंग चिकित्सा", "रंग चिकित्सा"),
    ,
    CAT_METAL("Metal", "धातु", "धातु"),
    ,
    CAT_RUDRAKSHA("Rudraksha", "रुद्राक्ष", "रुद्राक्ष"),
    ,
    CAT_DEITY("Deity Worship", "देवी-देवता पूजा", "देवी-देवता पूजा"),
    ,
    CAT_LIFESTYLE("Lifestyle", "जीवनशैली", "जीवनशैली"),

    ,

    // Remedy Priorities
    PRIORITY_ESSENTIAL("Essential", "अत्यावश्यक", "अत्यावश्यक"),
    ,
    PRIORITY_HIGHLY_RECOMMENDED("Highly Recommended", "अत्यधिक सिफारिस गरिएको", "अत्यधिक सिफारिस गरिए के"),
    ,
    PRIORITY_RECOMMENDED("Recommended", "सिफारिस गरिएको", "सिफारिस गरिए के"),
    ,
    PRIORITY_OPTIONAL("Optional", "वैकल्पिक", "वैकल्पिक"),

    ,

    // Gemstones
    GEM_SUN_NAME("Ruby", "माणिक", "माणिक"),
    ,
    GEM_SUN_DESC("Primary gemstone for strengthening Sun. As a functional benefic for your Lagna, this gemstone is suitable.", "सूर्यलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "सूर्य  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_SUN_METHOD("Wear 3.0-5.0 carat natural, untreated Ruby (Red) set in Gold (22K) on the Ring finger of right hand.", "दायाँ हातको अनामिका औंलामा सुन (२२ क्यारेट) मा जडान गरिएको ३.०-५.० क्यारेटको प्राकृतिक, उपचार नगरिएको माणिक (रातो) लगाउनुहोस्।", "दायाँ हात के अनामि के औंला में सुन (२२ क्यारेट) में जडान गरिए के ३.०-५.० क्यारेट के प्राकृतिक, उपचार नगरिए के माणिक (रातो) लगाउनुहोस्।"),
    ,
    GEM_SUN_TIMING("Sunday during Sunrise, during Sun Hora. Purify with raw milk and Ganga water before wearing.", "आइतबार सूर्योदयको समयमा, सूर्य होरामा। लगाउनु अघि काँचो दूध र गंगाजलले शुद्ध गर्नुहोस्।", "आइतबार सूर्यहदय के समय में, सूर्य हैरा में। लगाउनु अघि काँचो दूध और गंगाजलले शुद्ध करें।"),

    ,
    
    GEM_MOON_NAME("Natural Pearl", "मोती", "मोती"),
    ,
    GEM_MOON_DESC("Primary gemstone for strengthening Moon. As a functional benefic for your Lagna, this gemstone is suitable.", "चन्द्रलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "चन्द्र  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_MOON_METHOD("Wear 4.0-7.0 carat natural, untreated Pearl (White) set in Silver on the Little finger of right hand.", "दायाँ हातको कान्छी औंलामा चाँदीमा जडान गरिएको ४.०-७.० क्यारेटको प्राकृतिक, उपचार नगरिएको मोती (सेतो) लगाउनुहोस्।", "दायाँ हात के कान्हैी औंला में चाँदी में जडान गरिए के ४.०-७.० क्यारेट के प्राकृतिक, उपचार नगरिए के मोती (सेतो) लगाउनुहोस्।"),
    ,
    GEM_MOON_TIMING("Monday evening during Shukla Paksha, during Moon Hora.", "शुक्ल पक्षको सोमबार साँझ, चन्द्र होरामा।", "शुक्ल पक्ष के सोमबार साँझ, चन्द्र हैरा में।"),

    ,

    GEM_MARS_NAME("Red Coral", "मुगा", "मुगा"),
    ,
    GEM_MARS_DESC("Primary gemstone for strengthening Mars. As a functional benefic for your Lagna, this gemstone is suitable.", "मंगललाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "मंगल  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_MARS_METHOD("Wear 5.0-9.0 carat natural, untreated Red Coral (Red) set in Gold/Copper on the Ring finger of right hand.", "दायाँ हातको अनामिका औंलामा सुन/तामामा जडान गरिएको ५.०-९.० क्यारेटको प्राकृतिक, उपचार नगरिएको मुगा (रातो) लगाउनुहोस्।", "दायाँ हात के अनामि के औंला में सुन/तामा में जडान गरिए के ५.०-९.० क्यारेट के प्राकृतिक, उपचार नगरिए के मुगा (रातो) लगाउनुहोस्।"),
    ,
    GEM_MARS_TIMING("Tuesday morning, during Mars Hora.", "मंगलबार बिहान, मंगल होरामा।", "मंगलबार बिहान, मंगल हैरा में।"),

    ,

    GEM_MERCURY_NAME("Emerald", "पन्ना", "पन्ना"),
    ,
    GEM_MERCURY_DESC("Primary gemstone for strengthening Mercury. As a functional benefic for your Lagna, this gemstone is suitable.", "बुधलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "बुध  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_MERCURY_METHOD("Wear 3.0-6.0 carat natural, untreated Emerald (Green) set in Gold on the Little finger of right hand.", "दायाँ हातको कान्छी औंलामा सुनमा जडान गरिएको ३.०-६.० क्यारेटको प्राकृतिक, उपचार नगरिएको पन्ना (हरियो) लगाउनुहोस्।", "दायाँ हात के कान्हैी औंला में सुन में जडान गरिए के ३.०-६.० क्यारेट के प्राकृतिक, उपचार नगरिए के पन्ना (हरियह) लगाउनुहोस्।"),
    ,
    GEM_MERCURY_TIMING("Wednesday morning, during Mercury Hora.", "बुधबार बिहान, बुध होरामा।", "बुधबार बिहान, बुध हैरा में।"),

    ,

    GEM_JUPITER_NAME("Yellow Sapphire", "पुखराज", "पुखराज"),
    ,
    GEM_JUPITER_DESC("Primary gemstone for strengthening Jupiter. As a functional benefic for your Lagna, this gemstone is suitable.", "बृहस्पतिलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "बृहस्पति  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_JUPITER_METHOD("Wear 3.0-5.0 carat natural, untreated Yellow Sapphire (Yellow) set in Gold (22K) on the Index finger of right hand.", "दायाँ हातको चोर औंलामा सुन (२२ क्यारेट) मा जडान गरिएको ३.०-५.० क्यारेटको प्राकृतिक, उपचार नगरिएको पुखराज (हेलियो) लगाउनुहोस्।", "दायाँ हात के चोर औंला में सुन (२२ क्यारेट) में जडान गरिए के ३.०-५.० क्यारेट के प्राकृतिक, उपचार नगरिए के पुखराज (हेलियह) लगाउनुहोस्।"),
    ,
    GEM_JUPITER_TIMING("Thursday morning, during Jupiter Hora.", "बिहीबार बिहान, गुरु होरामा।", "बिहीबार बिहान, गुरु हैरा में।"),

    ,

    GEM_VENUS_NAME("Diamond", "हीरा", "हीरा"),
    ,
    GEM_VENUS_DESC("Primary gemstone for strengthening Venus. As a functional benefic for your Lagna, this gemstone is suitable.", "शुक्रलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "शुक्र  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_VENUS_METHOD("Wear 0.5-1.5 carat natural, untreated Diamond (White) set in Platinum/White Gold on the Middle/Little finger of right hand.", "दायाँ हातको माझी/कान्छी औंलामा प्लेटिनम/सेतो सुनमा जडान गरिएको ०.५-१.५ क्यारेटको प्राकृतिक, उपचार नगरिएको हीरा (सेतो) लगाउनुहोस्।", "दायाँ हात के माझी/कान्हैी औंला में प्लेटिनम/सेतो सुन में जडान गरिए के ०.५-१.५ क्यारेट के प्राकृतिक, उपचार नगरिए के हीरा (सेतो) लगाउनुहोस्।"),
    ,
    GEM_VENUS_TIMING("Friday morning, during Venus Hora.", "शुक्रबार बिहान, शुक्र होरामा।", "शुक्रबार बिहान, शुक्र हैरा में।"),

    ,

    GEM_SATURN_NAME("Blue Sapphire", "नीलम", "नीलम"),
    ,
    GEM_SATURN_DESC("Primary gemstone for strengthening Saturn. As a functional benefic for your Lagna, this gemstone is suitable.", "शनिलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।", "शनि  के बलियह बनाउन के लिए प्राथमिक रत्न। आप के लग्न के लिए शुभ ग्रह हुआले, यह रत्न उपयुक्त है।"),
    ,
    GEM_SATURN_METHOD("Wear 3.0-5.0 carat natural, untreated Blue Sapphire (Blue) set in Gold/Panch Dhatu on the Middle finger of right hand.", "दायाँ हातको माझी औंलामा सुन/पञ्चधातुमा जडान गरिएको ३.०-५.० क्यारेटको प्राकृतिक, उपचार नगरिएको नीलम (नीलो) लगाउनुहोस्।", "दायाँ हात के माझी औंला में सुन/पञ्चधातु में जडान गरिए के ३.०-५.० क्यारेट के प्राकृतिक, उपचार नगरिए के नीलम (नीलो) लगाउनुहोस्।"),
    ,
    GEM_SATURN_TIMING("Saturday evening, during Saturn Hora.", "शनिबार साँझ, शनि होरामा।", "शनिबार साँझ, शनि हैरा में।"),

    ,

    GEM_RAHU_NAME("Hessonite Garnet", "गोमेद", "गोमेद"),
    ,
    GEM_RAHU_DESC("Gemstone for balancing Rahu energy.", "राहु ऊर्जा सन्तुलन गर्नको लागि रत्न।", "राहु ऊर्जा सन्तुलन करने के लिए रत्न।"),
    ,
    GEM_RAHU_METHOD("Wear 5.0-8.0 carat Hessonite (Honey color) set in Silver on Middle finger.", "माझी औंलामा चाँदीमा जडान गरिएको ५.०-८.० क्यारेटको गोमेद (मह र्ग) लगाउनुहोस्।", "माझी औंला में चाँदी में जडान गरिए के ५.०-८.० क्यारेट के गोमेद (मह र्ग) लगाउनुहोस्।"),
    ,
    GEM_RAHU_TIMING("Saturday night, during Rahu Kaal.", "शनिबार राती, राहु कालमा।", "शनिबार राती, राहु काल में।"),

    ,

    GEM_KETU_NAME("Cat's Eye", "लहसुनिया", "लहसुनिया"),
    ,
    GEM_KETU_DESC("Gemstone for balancing Ketu energy.", "केतु ऊर्जा सन्तुलन गर्नको लागि रत्न।", "केतु ऊर्जा सन्तुलन करने के लिए रत्न।"),
    ,
    GEM_KETU_METHOD("Wear 3.0-5.0 carat Cat's Eye set in Silver/Gold on Middle finger.", "माझी औंलामा चाँदी/सुनमा जडान गरिएको ३.०-५.० क्यारेटको लहसुनिया लगाउनुहोस्।", "माझी औंला में चाँदी/सुन में जडान गरिए के ३.०-५.० क्यारेट के लहसुनिया लगाउनुहोस्।"),
    ,
    GEM_KETU_TIMING("Tuesday or during Ketu nakshatra.", "मंगलबार वा केतु नक्षत्रमा।", "मंगलबार या केतु नक्षत्र में।"),

    ,

    // Gemstone Utils
    GEM_CAUTION_TITLE_SUFFIX(" - Consult Before Wearing", " - लगाउनु अघि परामर्श गर्नुहोस्", "- लगाउनु अघि परामर्श करें"),
    ,
    GEM_CAUTION_DESC("%s is not a functional benefic for your Lagna. Wearing %s may increase challenges. Consider alternative remedies.", "%s तपाईंको लग्नको लागि शुभ ग्रह होइन। %s लगाउँदा चुनौतीहरू बढ्न सक्छन्। वैकल्पिक उपायहरू विचार गर्नुहोस्।", "%s आप के लग्न के लिए शुभ ग्रह हैइन। %s लगाउँदा चुनौती बढ्न सक्हैं। वैकल्पिक उपाय विचार करें।"),
    ,
    GEM_CAUTION_METHOD("CAUTION: Get expert consultation before wearing. If advised, wear %s-%s carat %s in %s on %s finger.", "सावधानी: लगाउनु अघि विशेषज्ञ परामर्श लिनुहोस्। यदि सल्लाह दिइयो भने, %s-%s क्यारेटको %s %s औंलामा %s धातुमा लगाउनुहोस्।", "सावधानी: लगाउनु अघि विशेषज्ञ परामर्श लिनुहोस्। यदि सल्लाह दिइयह भने, %s-%s क्यारेट के %s %s औंला में %s धातु में लगाउनुहोस्।"),
    ,
    GEM_CAUTION_DURATION("Trial period of 3-7 days strongly recommended", "३-७ दिनको परीक्षण अवधि कडा सिफारिस गरिन्छ", "३-७ दिन के परीक्षण अवधि कडा सिफारिस गरिन्है"),
    ,
    GEM_BENEFIT_STRENGTHEN("Strengthens %s's positive influences", "%s को सकारात्मक प्रभावहरू बलियो बनाउँछ", "%s  के सकारात्मक प्रभाव बलियह बनाउँहै"),
    ,
    GEM_BENEFIT_LIFE_AREA("Enhances %s", "%s बढाउँछ", "%s बढाउँहै"),
    ,
    GEM_BENEFIT_BALANCE("Provides continuous energy balancing", "निरन्तर ऊर्जा सन्तुलन प्रदान गर्दछ", "निरन्तर ऊर्जा सन्तुलन प्रदान करता है"),
    ,
    GEM_CAUTION_NATURAL("Ensure the gemstone is natural and untreated", "रत्न प्राकृतिक र उपचार नगरिएको सुनिश्चित गर्नुहोस्", "रत्न प्राकृतिक और उपचार नगरिए के सुनिश्चित करें"),
    ,
    GEM_CAUTION_CERT("Buy from reputable dealer with certification", "प्रमाणपत्र सहित प्रतिष्ठित व्यापारीबाट किन्नुहोस्", "प्रमाणपत्र सहित प्रतिष्ठित व्यापारीबाट किन्नुहोस्"),
    ,
    GEM_CAUTION_TRIAL("Trial period of 3-7 days recommended", "३-७ दिनको परीक्षण अवधि सिफारिस गरिन्छ", "३-७ दिन के परीक्षण अवधि सिफारिस गरिन्है"),
    ,
    GEM_CAUTION_REMOVE("Remove if experiencing adverse effects", "यदि प्रतिकूल प्रभाव अनुभव भयो भने हटाउनुहोस्", "यदि प्रतिकूल प्रभाव अनुभव भयह भने हटाएं"),
    ,
    GEM_ALT_SUB(" - More affordable substitute", " - अधिक किफायती विकल्प", "- अधिक किफायती विकल्प"),

    ,

    // Mantra
    MANTRA_TITLE_SUFFIX(" Beej Mantra", " बीज मन्त्र", "बीज मन्त्र"),
    ,
    MANTRA_DESC("Sacred sound vibration to invoke and strengthen %s. Mantras are the safest and most universally beneficial remedy.", "%s लाई आह्वान र बलियो बनाउन पवित्र ध्वनि कम्पन। मन्त्रहरू सबैभन्दा सुरक्षित र विश्वव्यापी रूपमा लाभदायक उपाय हुन्।", "%s  के आह्वान और बलियह बनाउन पवित्र ध्वनि कम्पन। मन्त्र सभीभन्दा सुरक्षित और विश्वव्यापी रूप में लाभदायक उपाय हैं।"),
    ,
    MANTRA_METHOD("Sit facing %s. Chant the beej mantra %d times:\n\n\"%s\"\n\nAlternatively, chant Gayatri Mantra of %s.", "%s दिशा फर्केर बस्नुहोस्। बीज मन्त्र %d पटक जप गर्नुहोस्:\n\n\"%s\"\n\nवैकल्पिक रूपमा, %s को गायत्री मन्त्र जप गर्नुहोस्।", "%s दिशा फर्केर बस्नुहोस्। बीज मन्त्र %d पटक जप करें:\n\n\"%s\"\n\nवैकल्पिक रूप में, %s  के गायत्री मन्त्र जप करें।"),
    ,
    MANTRA_DURATION("Complete one mala (108 times) daily for minimum 40 days. Full count of %d for maximum benefit.", "कम्तिमा ४० दिनसम्म दैनिक एक माला (१०८ पटक) पूरा गर्नुहोस्। अधिकतम लाभको लागि %d को पूर्ण संख्या।", "कम्ति में ४० दिनसम्म दैनिक एक माला (१०८ पटक) पूरा करें। अधिकतम लाभ के लिए %d  के पूर्ण संख्या।"),
    ,
    MANTRA_BENEFIT_SAFE("No side effects - safe for everyone", "कुनै साइड इफेक्ट छैन - सबैको लागि सुरक्षित", "कुनै साइड इफेक्ट हैैन - सभी के लिए सुरक्षित"),
    ,
    MANTRA_BENEFIT_INVOKE("Directly invokes %s's blessings", "प्रत्यक्ष रूपमा %s को आशीर्वाद आह्वान गर्दछ", "प्रत्यक्ष रूप में %s  के आशीर्वाद आह्वान करता है"),
    ,
    MANTRA_BENEFIT_OBSTACLES("Reduces karmic obstacles", "कार्मिक अवरोधहरू कम गर्दछ", "कार्मिक अवरोध कम करता है"),
    ,
    MANTRA_BENEFIT_VIBES("Creates positive mental vibrations", "सकारात्मक मानसिक कम्पनहरू सिर्जना गर्दछ", "सकारात्मक मानसिक कम्पन सिर्जना करता है"),
    ,
    MANTRA_CAUTION_PURITY("Maintain physical and mental purity during practice", "अभ्यासको समयमा शारीरिक र मानसिक शुद्धता कायम राख्नुहोस्", "अभ्यास के समय में शारीरिक और मानसिक शुद्धता कायम राख्नुहोस्"),
    ,
    MANTRA_CAUTION_MALA("Use Rudraksha, Tulsi, or crystal mala", "रुद्राक्ष, तुलसी, वा स्फटिक माला प्रयोग गर्नुहोस्", "रुद्राक्ष, तुलसी, या स्फटिक माला प्रयहग करें"),
    ,
    MANTRA_CAUTION_DIET("Avoid eating non-vegetarian food during the practice period", "अभ्यास अवधिमा मांसाहारी भोजन नगर्नुहोस्", "अभ्यास अवधि में मांसाहारी भोजन नकरें"),
    ,
    MANTRA_CAUTION_VOW("Complete the sankalpa (vow) once started", "एक पटक सुरु गरेपछि संकल्प पूरा गर्नुहोस्", "एक पटक सुरु गरेपहैि संकल्प पूरा करें"),

    ,

    // Charity
    CHARITY_TITLE_SUFFIX(" Daan (Charity)", " दान", "दान"),
    ,
    CHARITY_DESC("Charitable acts to reduce %s's karmic debts and negative effects.", "%s को कार्मिक ऋण र नकारात्मक प्रभावहरू कम गर्न परोपकारी कार्यहरू।", "%s  के कार्मिक ऋण और नकारात्मक प्रभाव कम करने परोपकारी कार्य।"),
    ,
    CHARITY_METHOD("Donate the following items: %s\n\nRecipients: %s\n\n%s", "निम्न वस्तुहरू दान गर्नुहोस्: %s\n\nप्राप्तकर्ताहरू: %s\n\n%s", "निम्न वस्तु दान करें: %s\n\nप्राप्तकर्ता: %s\n\n%s"),
    ,
    CHARITY_TIMING("Every %s, preferably %s", "हरेक %s, प्राथमिकता %s", "हरेक %s, प्राथमिकता %s"),
    ,
    CHARITY_DURATION("Regular practice for lasting benefits. Especially important during %s's Dasha/Antardasha.", "दीर्घकालीन लाभको लागि नियमित अभ्यास। विशेष गरी %s को दशा/अन्तर्दशामा महत्त्वपूर्ण।", "दीर्घकालीन लाभ के लिए नियमित अभ्यास। विशेष गरी %s  के दशा/अन्तर्दशा में महत्त्वपूर्ण।"),
    ,
    CHARITY_BENEFIT_KARMA("Reduces negative karma associated with %s", "%s सँग सम्बन्धित नकारात्मक कर्म कम गर्दछ", "%s सँग संबंधित नकारात्मक कर्म कम करता है"),
    ,
    CHARITY_BENEFIT_MERIT("Creates positive merit (punya)", "सकारात्मक पुण्य सिर्जना गर्दछ", "सकारात्मक पुण्य सिर्जना करता है"),
    ,
    CHARITY_BENEFIT_UNIVERSAL("No side effects - universally beneficial", "कुनै साइड इफेक्ट छैन - विश्वव्यापी रूपमा लाभदायक", "कुनै साइड इफेक्ट हैैन - विश्वव्यापी रूप में लाभदायक"),
    ,
    CHARITY_BENEFIT_BOTH("Helps both giver and receiver", "दाता र प्राप्तकर्ता दुवैलाई मद्दत गर्दछ", "दाता और प्राप्तकर्ता दुवै  के सहायता करता है"),
    ,
    CHARITY_CAUTION_INTENTION("Donate with pure intentions and humility", "शुद्ध मनसाय र नम्रताका साथ दान गर्नुहोस्", "शुद्ध मनसाय और नम्रता के साथ दान करें"),
    ,
    CHARITY_CAUTION_EXPECTATION("Give without expecting returns or recognition", "प्रतिफल वा मान्यताको अपेक्षा नगरी दिनुहोस्", "प्रतिफल या मान्यता के अपेक्षा नगरी दिनुहोस्"),
    ,
    CHARITY_CAUTION_RECIPIENT("Choose genuine recipients in need", "साँचो आवश्यकता भएका प्राप्तकर्ताहरू छान्नुहोस्", "साँचो आवश्यकता हुए प्राप्तकर्ता चुनें"),
    ,
    CHARITY_CAUTION_QUALITY("Quality matters more than quantity", "परिमाण भन्दा गुणस्तर महत्त्वपूर्ण छ", "परिमाण भन्दा गुणस्तर महत्त्वपूर्ण है"),

    ,

    // Fasting
    FASTING_TITLE_SUFFIX(" Vrat (Fast)", " व्रत", "व्रत"),
    ,
    FASTING_DESC("Fasting to appease %s and reduce its negative influences.", "%s लाई शान्त पार्न र यसको नकारात्मक प्रभावहरू कम गर्न व्रत।", "%s  के शान्त पार्न और इस के नकारात्मक प्रभाव कम करने व्रत।"),
    ,
    FASTING_METHOD("Observe fast from sunrise to sunset on %s. %s. Break fast after seeing the relevant symbol (Moon for Monday, etc.).", "%s मा सूर्योदय देखि सूर्यास्त सम्म व्रत बस्नुहोस्। %s। सम्बन्धित प्रतीक (सोमबारको लागि चन्द्रमा, आदि) देखेपछि व्रत तोड्नुहोस्।", "%s में सूर्यहदय देखि सूर्यास्त सम्म व्रत बस्नुहोस्। %s। संबंधित प्रतीक (सोमबार के लिए चन्द्र में, आदि) देखेपहैि व्रत तोड्नुहोस्।"),
    ,
    FASTING_TIMING("Every %s or for 21 continuous %ss", "हरेक %s वा २१ लगातार %s हरू", "हरेक %s या २१ लगातार %s "),
    ,
    FASTING_DURATION("Minimum 11-21 weeks, ideally 40 days continuously", "कम्तिमा ११-२१ हप्ता, आदर्श रूपमा ४० दिन लगातार", "कम्ति में ११-२१ हप्ता, आदर्श रूप में ४० दिन लगातार"),
    ,
    FASTING_BENEFIT_PURIFY("Purifies body, mind, and spirit", "शरीर, मन, र आत्मा शुद्ध गर्दछ", "शरीर, मन, और आत् में शुद्ध करता है"),
    ,
    FASTING_BENEFIT_WILL("Increases willpower and discipline", "इच्छाशक्ति र अनुशासन बढाउँछ", "इच्हैाशक्ति और अनुशासन बढाउँहै"),
    ,
    FASTING_BENEFIT_PLEASE("Pleases %s", "%s लाई खुशी पार्छ", "%s  के खुशी पार्है"),
    ,
    FASTING_CAUTION_HEALTH("Consult a doctor if you have diabetes, low BP, or other health conditions", "यदि तपाईंलाई मधुमेह, कम रक्तचाप, वा अन्य स्वास्थ्य समस्या छ भने डाक्टरसँग परामर्श गर्नुहोस्", "यदि आप  के मधुमेह, कम रक्तचाप, या अन्य स्वास्थ्य समस्या है भने डाक्टरसँग परामर्श करें"),
    ,
    FASTING_CAUTION_PREG("Pregnant women should avoid strict fasting", "गर्भवती महिलाहरूले कडा व्रत नगर्नुहोस्", "गर्भवती महिलाले कडा व्रत नकरें"),
    ,
    FASTING_CAUTION_BREAK("Break fast gently with light food", "हल्का खानाले बिस्तारै व्रत तोड्नुहोस्", "हल् के खानाले बिस्तारै व्रत तोड्नुहोस्"),
    ,
    FASTING_CAUTION_HYDRATE("Stay hydrated with water", "पानी पिएर हाइड्रेटेड रहनुहोस्", "पानी पिएर हाइड्रेटेड रहनुहोस्"),

    ,

    // Color Therapy
    COLOR_TITLE_SUFFIX(" Color Therapy", " रंग चिकित्सा", "रंग चिकित्सा"),
    ,
    COLOR_DESC("Use colors associated with %s to create favorable energy vibrations.", "अनुकूल ऊर्जा कम्पनहरू सिर्जना गर्न %s सँग सम्बन्धित रंगहरू प्रयोग गर्नुहोस्।", "अनुकूल ऊर्जा कम्पन सिर्जना करने %s सँग संबंधित रंग प्रयहग करें।"),
    ,
    COLOR_METHOD("Wear clothes of these colors: %s\n\nUse these colors in your room, workspace, and personal accessories.\n\nAvoid: %s on %s", "यी रंगका लुगाहरू लगाउनुहोस्: %s\n\nयी रंगहरू आफ्नो कोठा, कार्यस्थल र व्यक्तिगत सामानहरूमा प्रयोग गर्नुहोस्।\n\nपरिहार गर्नुहोस्: %s, %s मा", "यी रंग के लुगा लगाउनुहोस्: %s\n\nयी रंग अपना कोठा, कार्इस्थल और व्यक्तिगत सामान में प्रयहग करें।\n\nपरिहार करें: %s, %s में"),
    ,
    COLOR_TIMING("Especially on %s", "विशेष गरी %s मा", "विशेष गरी %s में"),
    ,
    COLOR_DURATION("Daily practice, particularly during %s's Dasha period", "दैनिक अभ्यास, विशेष गरी %s को दशा अवधिमा", "दैनिक अभ्यास, विशेष गरी %s  के दशा अवधि में"),
    ,
    COLOR_BENEFIT_SUBTLE("Subtle but effective energy enhancement", "सूक्ष्म तर प्रभावकारी ऊर्जा वृद्धि", "सूक्ष्म तर प्रभावकारी ऊर्जा वृद्धि"),
    ,
    COLOR_BENEFIT_EASY("Easy to implement daily", "दैनिक लागू गर्न सजिलो", "दैनिक लागू करने सजिलो"),
    ,
    COLOR_BENEFIT_COST("No cost or side effects", "कुनै लागत वा साइड इफेक्ट छैन", "कुनै लागत या साइड इफेक्ट हैैन"),
    ,
    COLOR_CAUTION_BALANCE("Balance with colors for other weak planets", "अन्य कमजोर ग्रहहरूको लागि रंगहरूसँग सन्तुलन गर्नुहोस्", "अन्य कमजोर ग्रह के लिए रंगसँग सन्तुलन करें"),

    ,

    // Lifestyle
    LIFESTYLE_TITLE_SUFFIX(" Lifestyle Practices", " जीवनशैली अभ्यास", "जीवनशैली अभ्यास"),
    ,
    LIFESTYLE_DESC("Daily habits and lifestyle modifications to strengthen %s and reduce its negative effects.", "%s लाई बलियो बनाउन र यसको नकारात्मक प्रभावहरू कम गर्न दैनिक बानी र जीवनशैली परिवर्तनहरू।", "%s  के बलियह बनाउन और इस के नकारात्मक प्रभाव कम करने दैनिक बानी और जीवनशैली परिवर्तन।"),
    ,
    LIFESTYLE_REC_PRACTICES("RECOMMENDED PRACTICES:", "सिफारिस गरिएको अभ्यासहरू:", "सिफारिस गरिए के अभ्यास:"),
    ,
    LIFESTYLE_THINGS_AVOID("THINGS TO AVOID:", "बेवास्ता गर्नुपर्ने कुराहरू:", "बेवास्ता करनेुपर्ने कुरा:"),
    ,
    LIFESTYLE_TIMING("Daily practice, especially on %s", "दैनिक अभ्यास, विशेष गरी %s मा", "दैनिक अभ्यास, विशेष गरी %s में"),
    ,
    LIFESTYLE_DURATION("Ongoing lifestyle adoption", "निरन्तर जीवनशैली अपनाउने", "निरन्तर जीवनशैली अपनाउने"),
    ,
    LIFESTYLE_BENEFIT_HOLISTIC("Holistic and sustainable improvement", "समग्र र दिगो सुधार", "समग्र और दिगो सुधार"),
    ,
    LIFESTYLE_BENEFIT_COST("No cost involved", "कुनै लागत लाग्दैन", "कुनै लागत लाग्दैन"),
    ,
    LIFESTYLE_BENEFIT_KARMA("Creates positive karma", "सकारात्मक कर्म सिर्जना गर्दछ", "सकारात्मक कर्म सिर्जना करता है"),
    ,
    LIFESTYLE_BENEFIT_ALIGN("Aligns daily life with planetary energies", "ग्रहका ऊर्जाहरूसँग दैनिक जीवनलाई मिलाउँछ", "ग्रह के ऊर्जासँग दैनिक जीवन  के मिलाउँहै"),

    ,

    // Rudraksha
    RUDRA_TITLE_SUFFIX(" Rudraksha", " रुद्राक्ष", "रुद्राक्ष"),
    ,
    RUDRA_DESC("Sacred Rudraksha bead associated with %s and blessed by %s.", "%s सँग सम्बन्धित र %s द्वारा आशीर्वाद प्राप्त पवित्र रुद्राक्ष मनका।", "%s सँग संबंधित और %s द्वारा आशीर्वाद प्राप्त पवित्र रुद्राक्ष मन के।"),
    ,
    RUDRA_METHOD_1("1. Obtain authentic %s Rudraksha from a reputable source", "१. प्रतिष्ठित स्रोतबाट प्रमाणिक %s रुद्राक्ष प्राप्त गर्नुहोस्", "१. प्रतिष्ठित स्रोतबाट प्रमाणिक %s रुद्राक्ष प्राप्त करें"),
    ,
    RUDRA_METHOD_2("2. Purify with Panchamrit (milk, curd, honey, ghee, sugar) or Gangajal", "२. पञ्चामृत (दूध, दही, मह, घिउ, चिनी) वा गंगाजलले शुद्ध गर्नुहोस्", "२. पञ्चामृत (दूध, दही, मह, घिउ, चिनी) या गंगाजलले शुद्ध करें"),
    ,
    RUDRA_METHOD_3("3. Energize by chanting: 'Om Namah Shivaya' 108 times", "३. 'ओम नमः शिवाय' १०८ पटक जप गरेर ऊर्जावान बनाउनुहोस्", "३. 'ओम नमः शिवाय' १०८ पटक जप गरेर ऊर्जावान बनाएं"),
    ,
    RUDRA_METHOD_4("4. Chant %s mantra 108 times before first wearing", "४. पहिलो पटक लगाउनु अघि %s मन्त्र १०८ पटक जप गर्नुहोस्", "४. पहिलो पटक लगाउनु अघि %s मन्त्र १०८ पटक जप करें"),
    ,
    RUDRA_METHOD_5("5. Wear on silk/wool thread or cap in silver/gold", "५. रेशम/ऊनको धागोमा वा चाँदी/सुनको टोपीमा लगाउनुहोस्", "५. रेशम/ऊन के धागो में या चाँदी/सुन के टोपी में लगाउनुहोस्"),
    ,
    RUDRA_METHOD_6("6. Wear around neck or on right wrist", "६. घाँटीमा वा दायाँ नाडीमा लगाउनुहोस्", "६. घाँटी में या दायाँ नाडी में लगाउनुहोस्"),
    ,
    RUDRA_TIMING("Wear on %s during Shukla Paksha, preferably on %s Hora", "शुक्ल पक्षको %s मा लगाउनुहोस्, प्राथमिकता %s होरामा", "शुक्ल पक्ष के %s में लगाउनुहोस्, प्राथमिकता %s हैरा में"),
    ,
    RUDRA_DURATION("Continuous wear. Remove during impure activities.", "निरन्तर लगाउनुहोस्। अशुद्ध गतिविधिहरूमा हटाउनुहोस्।", "निरन्तर लगाउनुहोस्। अशुद्ध गतिविधि में हटाएं।"),
    ,
    RUDRA_BENEFIT_NATURAL("Natural remedy with no side effects", "कुनै साइड इफेक्ट नभएको प्राकृतिक उपाय", "कुनै साइड इफेक्ट नहुआ प्राकृतिक उपाय"),
    ,
    RUDRA_BENEFIT_BALANCE("Balances %s's energy", "%s को ऊर्जा सन्तुलन गर्दछ", "%s  के ऊर्जा सन्तुलन करता है"),
    ,
    RUDRA_BENEFIT_PROTECT("Provides spiritual protection", "आध्यात्मिक सुरक्षा प्रदान गर्दछ", "आध्यात्मिक सुरक्षा प्रदान करता है"),
    ,
    RUDRA_BENEFIT_ANYONE("Can be worn by anyone regardless of Lagna", "लग्नको वास्ता नगरी जो कोहीले पनि लगाउन सक्छ", "लग्न के वास्ता नगरी जो कोहीले पनि लगाउन सक्है"),
    ,
    RUDRA_CAUTION_AUTH("Ensure authenticity - buy from certified dealers", "प्रामाणिकता सुनिश्चित गर्नुहोस् - प्रमाणित व्यापारीहरूबाट किन्नुहोस्", "प्रामाणिकता सुनिश्चित करें - प्रमाणित व्यापारीबाट किन्नुहोस्"),
    ,
    RUDRA_CAUTION_SLEEP("Remove during sleep if uncomfortable", "असहज भएमा सुत्दा हटाउनुहोस्", "असहज भए में सुत्दा हटाएं"),
    ,
    RUDRA_CAUTION_CLEAN("Clean regularly with water", "नियमित रूपमा पानीले सफा गर्नुहोस्", "नियमित रूप में पानीले सफा करें"),
    ,
    RUDRA_CAUTION_EVENTS("Avoid wearing during cremation or birth events", "दाहसंस्कार वा जन्म कार्यक्रमहरूमा नलगाउनुहोस्", "दाहसंस्कार या जन्म कार्यक्रम में नलगाउनुहोस्"),

    ,

    // Yantra
    YANTRA_INSTALL_PROC("INSTALLATION PROCEDURE:", "स्थापना प्रक्रिया:", "स्थापना प्रक्रिया:"),
    ,
    YANTRA_METHOD_1("1. Choose a %s %s from authentic source", "१. प्रामाणिक स्रोतबाट %s %s छान्नुहोस्", "१. प्रामाणिक स्रोतबाट %s %s चुनें"),
    ,
    YANTRA_METHOD_2("2. Select auspicious day: %s during %s Hora", "२. शुभ दिन छान्नुहोस्: %s, %s होरामा", "२. शुभ दिन चुनें: %s, %s हैरा में"),
    ,
    YANTRA_METHOD_3("3. Bathe the Yantra with Panchamrit and Gangajal", "३. यन्त्रलाई पञ्चामृत र गंगाजलले स्नान गराउनुहोस्", "३. यन्त्र  के पञ्चामृत और गंगाजलले स्नान गराउनुहोस्"),
    ,
    YANTRA_METHOD_4("4. Place on clean altar facing East or direction of %s", "४. पूर्व वा %s को दिशामा फर्केर सफा वेदीमा राख्नुहोस्", "४. पूर्व या %s  के दिशा में फर्केर सफा वेदी में राख्नुहोस्"),
    ,
    YANTRA_METHOD_5("5. Light incense and lamp", "५. धूप र बत्ती बाल्नुहोस्", "५. धूप और बत्ती बाल्नुहोस्"),
    ,
    YANTRA_METHOD_6("6. Chant %s mantra 108 times", "६. %s मन्त्र १०८ पटक जप गर्नुहोस्", "६. %s मन्त्र १०८ पटक जप करें"),
    ,
    YANTRA_METHOD_7("7. Offer flowers, fruits, and sandalwood", "७. फूल, फलफूल र चन्दन चढाउनुहोस्", "७. फूल, फलफूल और चन्दन चढाउनुहोस्"),
    ,
    YANTRA_METHOD_8("8. Perform daily worship with incense and lamp", "८. धूप र बत्ती बालेर दैनिक पूजा गर्नुहोस्", "८. धूप और बत्ती बालेर दैनिक पूजा करें"),
    ,
    YANTRA_TIMING("Install on %s during %s Hora in Shukla Paksha", "शुक्ल पक्षको %s मा %s होरामा स्थापना गर्नुहोस्", "शुक्ल पक्ष के %s में %s हैरा में स्थापना करें"),
    ,
    YANTRA_DURATION("Permanent installation with daily worship", "दैनिक पूजाको साथ स्थायी स्थापना", "दैनिक पूजा के साथ स्थायी स्थापना"),
    ,
    YANTRA_BENEFIT_FIELD("Creates continuous positive energy field", "निरन्तर सकारात्मक ऊर्जा क्षेत्र सिर्जना गर्दछ", "निरन्तर सकारात्मक ऊर्जा क्षेत्र सिर्जना करता है"),
    ,
    YANTRA_BENEFIT_247("Provides 24/7 remedy effect when worshipped", "पूजा गर्दा २४/७ उपाय प्रभाव प्रदान गर्दछ", "पूजा गर्दा २४/७ उपाय प्रभाव प्रदान करता है"),
    ,
    YANTRA_BENEFIT_MEDITATION("Enhances meditation and spiritual practice", "ध्यान र आध्यात्मिक अभ्यास बढाउँछ", "ध्यान और आध्यात्मिक अभ्यास बढाउँहै"),
    ,
    YANTRA_BENEFIT_PROTECT("Protects home and family from negative influences", "घर र परिवारलाई नकारात्मक प्रभावहरूबाट सुरक्षित राख्छ", "घर और परिवार  के नकारात्मक प्रभावबाट सुरक्षित राख्है"),
    ,
    YANTRA_CAUTION_WORSHIP("Requires daily worship commitment", "दैनिक पूजाको प्रतिबद्धता आवश्यक छ", "दैनिक पूजा के प्रतिबद्धता आवश्यक है"),
    ,
    YANTRA_CAUTION_RITUALS("Must be installed with proper Vedic rituals", "उचित वैदिक अनुष्ठानका साथ स्थापना गर्नुपर्छ", "उचित वैदिक अनुष्ठान के साथ स्थापना करनेुपर्है"),
    ,
    YANTRA_CAUTION_CLEAN("Keep the Yantra clean and respected", "यन्त्रलाई सफा र सम्मानित राख्नुहोस्", "यन्त्र  के सफा और सम्मानित राख्नुहोस्"),
    ,
    YANTRA_CAUTION_ALT("If unable to worship daily, consider other remedies", "यदि दैनिक पूजा गर्न असक्षम हुनुहुन्छ भने, अन्य उपायहरू विचार गर्नुहोस्", "यदि दैनिक पूजा करने असक्षम हैं भने, अन्य उपाय विचार करें"),

    ,

    // Deity
    DEITY_TITLE_SUFFIX(" Deity Worship", " देवी-देवता पूजा", "देवी-देवता पूजा"),
    ,
    DEITY_DESC("Invoke divine blessings by worshipping deities associated with %s.", "%s सँग सम्बन्धित देवी-देवताहरूको पूजा गरेर ईश्वरीय आशीर्वाद आह्वान गर्नुहोस्।", "%s सँग संबंधित देवी-देवता के पूजा गरेर ईश्वरीय आशीर्वाद आह्वान करें।"),
    ,
    DEITY_PRIMARY("PRIMARY DEITY: %s", "प्राथमिक देवता: %s", "प्राथमिक देवता: %s"),
    ,
    DEITY_SECONDARY("SECONDARY DEITIES: %s", "द्वितीयक देवताहरू: %s", "द्वितीयक देवता: %s"),
    ,
    DEITY_TEMPLES("RECOMMENDED TEMPLES: %s", "सिफारिस गरिएका मन्दिरहरू: %s", "सिफारिस गरिए के मन्दिर: %s"),
    ,
    DEITY_PROCEDURE("WORSHIP PROCEDURE:", "पूजा प्रक्रिया:", "पूजा प्रक्रिया:"),
    ,
    DEITY_METHOD_1("1. Visit temple on %s", "१. %s मा मन्दिर जानुहोस्", "१. %s में मन्दिर जानुहोस्"),
    ,
    DEITY_METHOD_2("2. Offer: %s", "२. चढाउनुहोस्: %s", "२. चढाउनुहोस्: %s"),
    ,
    DEITY_METHOD_3("3. Recite %s stotra or mantra", "३. %s स्तोत्र वा मन्त्र पाठ गर्नुहोस्", "३. %s स्तोत्र या मन्त्र पाठ करें"),
    ,
    DEITY_METHOD_4("4. Light lamp with ghee or appropriate oil", "४. घिउ वा उपयुक्त तेलले बत्ती बाल्नुहोस्", "४. घिउ या उपयुक्त तेलले बत्ती बाल्नुहोस्"),
    ,
    DEITY_METHOD_5("5. Perform pradakshina (circumambulation)", "५. परिक्रमा गर्नुहोस्", "५. परिक्र में करें"),
    ,
    DEITY_METHOD_6("6. Seek blessings with pure intention", "६. शुद्ध मनसायले आशीर्वाद माग्नुहोस्", "६. शुद्ध मनसायले आशीर्वाद माग्नुहोस्"),
    ,
    DEITY_TIMING("Every %s, especially during %s Hora", "हरेक %s, विशेष गरी %s होरामा", "हरेक %s, विशेष गरी %s हैरा में"),
    ,
    DEITY_DURATION("Regular weekly practice, more during %s Dasha", "नियमित साप्ताहिक अभ्यास, %s दशाको समयमा बढी", "नियमित साप्ताहिक अभ्यास, %s दशा के समय में बढी"),
    ,
    DEITY_BENEFIT_GRACE("Divine grace and protection", "ईश्वरीय कृपा र सुरक्षा", "ईश्वरीय कृपा और सुरक्षा"),
    ,
    DEITY_BENEFIT_RELIEF("Karmic relief and blessings", "कार्मिक राहत र आशीर्वाद", "कार्मिक राहत और आशीर्वाद"),
    ,
    DEITY_BENEFIT_GROWTH("Spiritual growth and merit", "आध्यात्मिक वृद्धि र पुण्य", "आध्यात्मिक वृद्धि और पुण्य"),
    ,
    DEITY_BENEFIT_CONNECT("Direct connection with planetary deity", "ग्रह देवतासँग प्रत्यक्ष सम्बन्ध", "ग्रह देवतासँग प्रत्यक्ष संबंध"),
    ,
    DEITY_CAUTION_DEVOTION("Worship with pure devotion and clean body/mind", "शुद्ध भक्ति र सफा शरीर/मनका साथ पूजा गर्नुहोस्", "शुद्ध भक्ति और सफा शरीर/मन के साथ पूजा करें"),
    ,
    DEITY_CAUTION_ETIQUETTE("Follow proper temple etiquette", "उचित मन्दिर शिष्टाचार पालना गर्नुहोस्", "उचित मन्दिर शिष्टाचार पालना करें"),
    ,
    DEITY_CAUTION_HOME("If unable to visit temple, perform home worship with image/idol", "यदि मन्दिर जान असक्षम हुनुहुन्छ भने, घरमै तस्बिर/मूर्ति राखेर पूजा गर्नुहोस्", "यदि मन्दिर जान असक्षम हैं भने, घरमै तस्बिर/मूर्ति राखेर पूजा करें"),

    ,

    // Nakshatra Remedy
    NAK_REMEDY_TITLE("%s Nakshatra Remedy", "%s नक्षत्र उपाय", "%s नक्षत्र उपाय"),
    ,
    NAK_REMEDY_DESC("%s is placed in %s nakshatra. This nakshatra is ruled by %s.", "%s %s नक्षत्रमा स्थित छ। यो नक्षत्रका स्वामी %s हुन्।", "%s %s नक्षत्र में स्थित है। यह नक्षत्र के स्वामी %s हैं।"),
    ,
    NAK_REMEDY_TIMING("Perform especially when Moon transits %s", "विशेष गरी चन्द्रमाले %s गोचर गर्दा गर्नुहोस्", "विशेष गरी चन्द्रमाले %s गोचर गर्दा करें"),
    ,
    NAK_REMEDY_DURATION("Regular practice, especially during relevant nakshatra days", "नियमित अभ्यास, विशेष गरी सम्बन्धित नक्षत्र दिनहरूमा", "नियमित अभ्यास, विशेष गरी संबंधित नक्षत्र दिन में"),
    ,
    NAK_BENEFIT_SPECIFIC("Addresses nakshatra-specific influences", "नक्षत्र-विशेष प्रभावहरूलाई सम्बोधन गर्दछ", "नक्षत्र-विशेष प्रभाव  के सम्बोधन करता है"),
    ,
    NAK_BENEFIT_BLESSING("Invokes blessing of nakshatra deity", "नक्षत्र देवताको आशीर्वाद आह्वान गर्दछ", "नक्षत्र देवता के आशीर्वाद आह्वान करता है"),
    ,
    NAK_BENEFIT_COMPLEMENT("Complements planetary remedies", "ग्रह उपचारहरूलाई पूरक बनाउँछ", "ग्रह उपचार  के पूरक बनाउँहै"),
    ,
    NAK_BENEFIT_FINE_TUNE("Fine-tunes remedy approach", "उपचार दृष्टिकोणलाई सुक्ष्म बनाउँछ", "उपचार दृष्टिकोण  के सुक्ष्म बनाउँहै"),
    ,
    NAK_CAUTION_COMBINE("Combine with main planetary remedies for best results", "उत्तम परिणामहरूको लागि मुख्य ग्रह उपचारहरूसँग मिलाउनुहोस्", "उत्तम परिणाम के लिए मुख्य ग्रह उपचारसँग मिलाउनुहोस्"),
    ,
    NAK_CAUTION_CHECK("Check Panchang for nakshatra transit days", "नक्षत्र गोचर दिनहरूको लागि पञ्चाङ्ग जाँच गर्नुहोस्", "नक्षत्र गोचर दिन के लिए पंचांग जाँच करें"),

    ,

    // Gandanta Remedy
    GANDANTA_TITLE("Gandanta Dosha Remedy", "गण्डान्त दोष उपाय", "गण्डान्त दोष उपाय"),
    ,
    GANDANTA_DESC("%s is in Gandanta zone (%s). This is a karmic junction requiring special attention.", "%s गण्डान्त क्षेत्र (%s) मा छ। यो विशेष ध्यान दिनुपर्ने कार्मिक संगम हो।", "%s गण्डान्त क्षेत्र (%s) में है। यह विशेष ध्यान दिनुपर्ने कार्मिक संगम है।"),
    ,
    GANDANTA_METHOD_TITLE("GANDANTA REMEDIES:", "गण्डान्त उपायहरू:", "गण्डान्त उपाय:"),
    ,
    GANDANTA_METHOD_1("1. Perform Shanti Puja for %s", "१. %s को लागि शान्ति पूजा गर्नुहोस्", "१. %s  के लिए शांति पूजा करें"),
    ,
    GANDANTA_METHOD_2("2. Chant %s mantra 11,000 times", "२. %s मन्त्र ११,००० पटक जप गर्नुहोस्", "२. %s मन्त्र ११,००० पटक जप करें"),
    ,
    GANDANTA_METHOD_3("3. Donate items related to %s", "३. %s सँग सम्बन्धित वस्तुहरू दान गर्नुहोस्", "३. %s सँग संबंधित वस्तु दान करें"),
    ,
    GANDANTA_METHOD_4("4. Perform Mrityunjaya Japa (108 times daily for 40 days)", "४. मृत्युञ्जय जप गर्नुहोस् (दैनिक १०८ पटक ४० दिनसम्म)", "४. मृत्युञ्जय जप करें (दैनिक १०८ पटक ४० दिनसम्म)"),
    ,
    GANDANTA_METHOD_5("5. Donate to orphanages or old age homes", "५. अनाथालय वा वृद्धाश्रममा दान गर्नुहोस्", "५. अनाथालय या वृद्धाश्रम में दान करें"),
    ,
    GANDANTA_METHOD_6("6. Feed Brahmins on %s", "६. %s मा ब्राह्मणहरूलाई भोजन गराउनुहोस्", "६. %s में ब्राह्मण  के भोजन गराउनुहोस्"),
    ,
    GANDANTA_METHOD_7("7. Worship Lord Ganesha to remove obstacles", "७. अवरोधहरू हटाउन भगवान गणेशको पूजा गर्नुहोस्", "७. अवरोध हटाउन भगवान गणेश के पूजा करें"),
    ,
    GANDANTA_SPECIAL("SPECIAL: Light a ghee lamp daily before the planet's deity", "विशेष: ग्रहको देवता अगाडि दैनिक घिउको बत्ती बाल्नुहोस्", "विशेष: ग्रह के देवता अगाडि दैनिक घिउ के बत्ती बाल्नुहोस्"),
    ,
    GANDANTA_TIMING("Begin on auspicious day, preferably %s", "शुभ दिनमा सुरु गर्नुहोस्, प्राथमिकता %s", "शुभ दिन में सुरु करें, प्राथमिकता %s"),
    ,
    GANDANTA_DURATION("40 days minimum, ideally during %s Dasha", "कम्तिमा ४० दिन, आदर्श रूपमा %s दशाको समयमा", "कम्ति में ४० दिन, आदर्श रूप में %s दशा के समय में"),
    ,
    GANDANTA_BENEFIT_BLOCKAGE("Removes karmic blockages from past lives", "विगतका जीवनका कार्मिक अवरोधहरू हटाउँछ", "विगत के जीवन के कार्मिक अवरोध हटाउँहै"),
    ,
    GANDANTA_BENEFIT_REDUCE("Reduces difficulties in the area ruled by %s", "%s द्वारा शासित क्षेत्रमा कठिनाइहरू कम गर्दछ", "%s द्वारा शासित क्षेत्र में कठिनाइ कम करता है"),
    ,
    GANDANTA_BENEFIT_TRANSFORM("Transforms challenging energy into spiritual growth", "चुनौतीपूर्ण ऊर्जालाई आध्यात्मिक वृद्धिमा परिवर्तन गर्दछ", "चुनौतीपूर्ण ऊर्जा  के आध्यात्मिक वृद्धि में परिवर्तन करता है"),
    ,
    GANDANTA_BENEFIT_PROTECT("Provides protection during difficult periods", "कठिन समयमा सुरक्षा प्रदान गर्दछ", "कठिन समय में सुरक्षा प्रदान करता है"),
    ,
    GANDANTA_CAUTION_CONSISTENT("Gandanta requires consistent long-term remedies", "गण्डान्तलाई निरन्तर दीर्घकालीन उपायहरू चाहिन्छ", "गण्डान्त  के निरन्तर दीर्घकालीन उपाय चाहिन्है"),
    ,
    GANDANTA_CAUTION_CONSULT("Consult a qualified astrologer for personalized guidance", "व्यक्तिगत मार्गदर्शनको लागि योग्य ज्योतिषीसँग परामर्श गर्नुहोस्", "व्यक्तिगत मार्गदर्शन के लिए यहग्य ज्यहतिषीसँग परामर्श करें"),
    ,
    GANDANTA_CAUTION_SKIP("Do not skip or abandon the remedy once started", "एक पटक सुरु गरेपछि उपाय नछोड्नुहोस्", "एक पटक सुरु गरेपहैि उपाय नहैोड्नुहोस्"),

    ,

    // General Recommendations
    GEN_REC_MULTIPLE("Multiple planets (%d) need attention. Focus on the 2-3 most afflicted planets first. Start with mantras and charity as they have no side effects.", "धेरै ग्रहहरू (%d) लाई ध्यान दिन आवश्यक छ। पहिले २-३ सबैभन्दा पीडित ग्रहहरूमा ध्यान केन्द्रित गर्नुहोस्। मन्त्र र दानबाट सुरु गर्नुहोस् किनभने यी कुनै साइड इफेक्ट छैनन्।", "धेरै ग्रह (%d)  के ध्यान दिन आवश्यक है। पहिले २-३ सभीभन्दा पीडित ग्रह में ध्यान केन्द्रित करें। मन्त्र और दानबाट सुरु करें किनभने यी कुनै साइड इफेक्ट हैैनन्।"),
    ,
    GEN_REC_LUMINARIES("Both luminaries (Sun and Moon) are weak. Prioritize: Surya Namaskar at sunrise, drink water from silver glass, and practice meditation for emotional balance.", "दुबै प्रकाशपुञ्ज (सूर्य र चन्द्रमा) कमजोर छन्। प्राथमिकता दिनुहोस्: सूर्योदयमा सूर्य नमस्कार, चाँदीको गिलासबाट पानी पिउनुहोस्, र भावनात्मक सन्तुलनको लागि ध्यान अभ्यास गर्नुहोस्।", "दुबै प्रकाशपुञ्ज (सूर्य और चन्द्रमा) कमजोर हैं। प्राथमिकता दिनुहोस्: सूर्यहदय में सूर्य नमस्कार, चाँदी के गिलासबाट पानी पिउनुहोस्, और भावनात्मक सन्तुलन के लिए ध्यान अभ्यास करें।"),
    ,
    GEN_REC_MOON("Moon remedies are essential for mental peace. Keep a bowl of water near your bed at night and offer it to plants in the morning.", "मानसिक शान्तिको लागि चन्द्रमाका उपायहरू आवश्यक छन्। राती आफ्नो ओछ्यान नजिकै पानीको कचौरा राख्नुहोस् र बिहान बोटबिरुवालाई चढाउनुहोस्।", "मानसिक शांति के लिए चन्द्र में के उपाय आवश्यक हैं। राती अपना ओहै्यान नजिकै पानी के कचौरा राख्नुहोस् और बिहान बोटबिरुवा  के चढाउनुहोस्।"),
    ,
    GEN_REC_GANDANTA("%s is in Gandanta (karmic knot). This requires dedicated long-term remedial measures including regular Mrityunjaya Japa.", "%s गण्डान्त (कार्मिक गाँठो) मा छ। यसका लागि नियमित मृत्युञ्जय जप सहित समर्पित दीर्घकालीन उपचारात्मक उपायहरू आवश्यक पर्दछ।", "%s गण्डान्त (कार्मिक गाँठो) में है। इस के लिए नियमित मृत्युञ्जय जप सहित समर्पित दीर्घकालीन उपचारात्मक उपाय आवश्यक पर्दहै।"),
    ,
    GEN_REC_NEECHA_BHANGA("%s has Neecha Bhanga Raja Yoga - initial struggles will transform into success. Stay patient and persistent.", "%s को नीच भङ्ग राजयोग छ - सुरुका संघर्षहरू सफलतामा परिणत हुनेछन्। धैर्य र निरन्तर रहनुहोस्।", "%s  के नीच भङ्ग राजयहग है - सुरु के संघर्ष सफलता में परिणत हैगान्। धैर्य और निरन्तर रहनुहोस्।"),
    ,
    GEN_REC_YOGAKARAKA("%s is your Yogakaraka planet. Strengthening it through gemstone, mantra, and lifestyle will bring significant positive results.", "%s तपाईंको योगकारक ग्रह हो। रत्न, मन्त्र र जीवनशैली मार्फत यसलाई बलियो बनाउँदा महत्त्वपूर्ण सकारात्मक परिणामहरू आउनेछन्।", "%s आप के यहगकारक ग्रह है। रत्न, मन्त्र और जीवनशैली मार्फत इस  के बलियह बनाउँदा महत्त्वपूर्ण सकारात्मक परिणाम आउनेहैं।"),
    ,
    GEN_REC_MEDITATION("Practice daily meditation for at least 15 minutes to harmonize all planetary energies.", "सबै ग्रह ऊर्जाहरूलाई सामंजस्य गर्न कम्तिमा १५ मिनेट दैनिक ध्यान अभ्यास गर्नुहोस्।", "सभी ग्रह ऊर्जा  के सामंजस्य करने कम्ति में १५ मिनेट दैनिक ध्यान अभ्यास करें।"),
    ,
    GEN_REC_CLEAN("Maintain a clean and organized living space, especially the puja area and entrance of your home.", "बस्ने ठाउँ सफा र व्यवस्थित राख्नुहोस्, विशेष गरी पूजा क्षेत्र र घरको प्रवेशद्वार।", "बस्ने ठाउँ सफा और व्यवस्थित राख्नुहोस्, विशेष गरी पूजा क्षेत्र और घर के प्रवेशद्वार।"),
    ,
    GEN_REC_ELDERS("Respect elders, teachers, and parents - this strengthens Jupiter and reduces many karmic burdens.", "बृद्धबृद्धा, गुरु र आमाबाबुलाई आदर गर्नुहोस् - यसले बृहस्पतिलाई बलियो बनाउँछ र धेरै कार्मिक भारहरू कम गर्दछ।", "बृद्धबृद्धा, गुरु और आमाबाबु  के आदर करें - यह बृहस्पति  के बलियह बनाउँहै और धेरै कार्मिक भार कम करता है।"),
    ,
    GEN_REC_CHARITY("Perform regular charity based on your means - even small acts of giving create positive karma.", "आफ्नो क्षमता अनुसार नियमित दान गर्नुहोस् - सानो दानले पनि सकारात्मक कर्म सिर्जना गर्दछ।", "अपना क्षमता अनुसार नियमित दान करें - सानो दानले पनि सकारात्मक कर्म सिर्जना करता है।"),
    ,
    GEN_REC_DIET("Avoid non-vegetarian food and alcohol on days when performing planetary remedies.", "ग्रह उपचार गर्ने दिनहरूमा मांसाहारी भोजन र मदिराबाट टाढा रहनुहोस्।", "ग्रह उपचार करनेे दिन में मांसाहारी भोजन और मदिराबाट टाढा रहनुहोस्।"),
    ,
    GEN_REC_DREAMS("Keep a dream journal - dreams often provide insights about which planets need attention.", "सपनाको जर्नल राख्नुहोस् - सपनाहरूले प्रायः कुन ग्रहहरूलाई ध्यान दिन आवश्यक छ भन्ने बारे अन्तर्दृष्टि प्रदान गर्छन्।", "सपना के जर्नल राख्नुहोस् - सपनाले प्रायः कुन ग्रह  के ध्यान दिन आवश्यक है भन्ने बारे अंतर्दृष्टि प्रदान करता हैन्।"),
    ,
    GEN_REC_SPIRITUAL("Strong spiritual potential indicated. Consider regular meditation retreats and spiritual study.", "बलियो आध्यात्मिक सम्भावना देखिन्छ। नियमित ध्यान शिविर र आध्यात्मिक अध्ययन विचार गर्नुहोस्।", "बलियह आध्यात्मिक सम्भावना देखिन्है। नियमित ध्यान शिविर और आध्यात्मिक अध्ययन विचार करें।"),

    ,

    // Dasha Remedies
    DASHA_AWARENESS_TITLE("Dasha Period Awareness", "दशा अवधि जागरूकता", "दशा अवधि जागरूकता"),
    ,
    DASHA_AWARENESS_DESC("General guidance for navigating planetary Dasha periods effectively.", "ग्रह दशा अवधिहरू प्रभावकारी रूपमा पार गर्नको लागि सामान्य मार्गदर्शन।", "ग्रह दशा अवधि प्रभावकारी रूप में पार करने के लिए सामान्य मार्गदर्शन।"),
    ,
    DASHA_METHOD_TITLE("DURING ANY DASHA PERIOD:", "कुनै पनि दशा अवधिमा:", "कुनै पनि दशा अवधिमा:"),
    ,
    DASHA_METHOD_1("1. Strengthen the Dasha lord through appropriate remedies", "१. उपयुक्त उपायहरू मार्फत दशा स्वामीलाई बलियो बनाउनुहोस्", "१. उपयुक्त उपाय मार्फत दशा स्वामी  के बलियह बनाएं"),
    ,
    DASHA_METHOD_2("2. If Dasha lord is weak in your chart, increase mantra and charity", "२. यदि तपाइँको कुण्डलीमा दशा स्वामी कमजोर छ भने, मन्त्र र दान बढाउनुहोस्", "२. यदि तपाइँ के कुंडली में दशा स्वामी कमजोर है भने, मन्त्र और दान बढाउनुहोस्"),
    ,
    DASHA_METHOD_3("3. Observe the weekday of the Dasha lord with fasting or worship", "३. व्रत वा पूजाको साथ दशा स्वामीको बार मनाउनुहोस्", "३. व्रत या पूजा के साथ दशा स्वामी के बार मनाउनुहोस्"),
    ,
    DASHA_METHOD_4("4. Avoid major decisions during Dasha lord's retrograde", "४. दशा स्वामी वक्री भएको बेला ठूला निर्णयहरू नगर्नुहोस्", "४. दशा स्वामी वक्री हुआ बेला ठूला निर्णय नकरें"),
    ,
    DASHA_METHOD_5("5. Wear the appropriate color on the Dasha lord's day", "५. दशा स्वामीको दिन उपयुक्त रंग लगाउनुहोस्", "५. दशा स्वामी के दिन उपयुक्त रंग लगाउनुहोस्"),
    ,
    DASHA_ANTAR_TITLE("ANTARDASHA (Sub-period) GUIDANCE:", "अन्तर्दशा (उप-अवधि) मार्गदर्शन:", "अन्तर्दशा (उप-अवधि) मार्गदर्शन:"),
    ,
    DASHA_ANTAR_1("• Check the relationship between Dasha and Antardasha lords", "• दशा र अन्तर्दशा स्वामीहरू बीचको सम्बन्ध जाँच गर्नुहोस्", "• दशा और अन्तर्दशा स्वामी बीच के संबंध जाँच करें"),
    ,
    DASHA_ANTAR_2("• If they are friends - period will be favorable", "• यदि तिनीहरू मित्र हुन् भने - अवधि अनुकूल हुनेछ", "• यदि तिनी मित्र हैं भने - अवधि अनुकूल हैगा"),
    ,
    DASHA_ANTAR_3("• If they are enemies - increase remedies for both planets", "• यदि तिनीहरू शत्रु हुन् भने - दुवै ग्रहहरूको लागि उपायहरू बढाउनुहोस्", "• यदि तिनी शत्रु हैं भने - दुवै ग्रह के लिए उपाय बढाउनुहोस्"),
    ,
    DASHA_ANTAR_4("• Pratyantar Dasha (sub-sub period) shows fine-tuned timing", "• प्रत्यन्तर दशा (उप-उप अवधि) ले सूक्ष्म समय देखाउँछ", "• प्रत्यन्तर दशा (उप-उप अवधि) ले सूक्ष्म समय देखाउँहै"),
    ,
    DASHA_TIMING("Throughout the Dasha period", "दशा अवधि भर", "दशा अवधि भर"),
    ,
    DASHA_DURATION("Entire Dasha duration", "पूर्ण दशा अवधि", "पूर्ण दशा अवधि"),
    ,
    DASHA_BENEFIT_MAX("Maximizes positive effects of favorable Dashas", "अनुकूल दशाको सकारात्मक प्रभावहरूलाई अधिकतम बनाउँछ", "अनुकूल दशा के सकारात्मक प्रभाव  के अधिकतम बनाउँहै"),
    ,
    DASHA_BENEFIT_MIN("Minimizes challenges during difficult Dashas", "कठिन दशाको समयमा चुनौतीहरू कम गर्दछ", "कठिन दशा के समय में चुनौती कम करता है"),
    ,
    DASHA_BENEFIT_TIME("Provides timing awareness for important decisions", "महत्त्वपूर्ण निर्णयहरूको लागि समय जागरूकता प्रदान गर्दछ", "महत्त्वपूर्ण निर्णय के लिए समय जागरूकता प्रदान करता है"),
    ,
    DASHA_CAUTION_CONSULT("Consult a Vedic astrologer for specific Dasha analysis", "विशिष्ट दशा विश्लेषणको लागि वैदिक ज्योतिषीसँग परामर्श गर्नुहोस्", "विशिष्ट दशा विश्लेषण के लिए वैदिक ज्यहतिषीसँग परामर्श करें"),
    ,
    DASHA_CAUTION_TRANSIT("Dasha effects are modified by transit influences", "दशा प्रभावहरू गोचर प्रभावहरूद्वारा परिमार्जित हुन्छन्", "दशा प्रभाव गोचर प्रभावद्वारा परिमार्जित हैता हैन्"),

    ,
    
    // Specific Dasha Mantra
    DASHA_SPECIFIC_TITLE("During %s Dasha/Antardasha", "%s दशा/अन्तर्दशाको समयमा", "%s दशा/अन्तर्दशा के समय में"),
    ,
    DASHA_SPECIFIC_DESC("Special remedies to perform when %s period is running.", "%s अवधि चलिरहेको बेला गर्नुपर्ने विशेष उपायहरू।", "%s अवधि चलिरहे के बेला करनेुपर्ने विशेष उपाय।"),
    ,
    DASHA_SPECIFIC_METHOD("Since %s is weak in your chart (%s), during its Dasha:\n\n1. Chant its mantra daily (108 times minimum)\n2. Perform charity on %s\n3. Wear %s's colors\n4. Fast on %s if possible\n5. Worship the ruling deity regularly", "%s तपाईंको कुण्डलीमा कमजोर (%s) भएकोले, यसको दशामा:\n\n१. यसको मन्त्र दैनिक जप गर्नुहोस् (कम्तिमा १०८ पटक)\n२. %s मा दान गर्नुहोस्\n३. %s को रंगहरू लगाउनुहोस्\n४. यदि सम्भव छ भने %s मा व्रत बस्नुहोस्\n५. नियमित रूपमा इष्ट देवताको पूजा गर्नुहोस्", "%s आप के कुंडली में कमजोर (%s) हुआले, इस के दशामा:\n\n१. इस के मन्त्र दैनिक जप करें (कम्ति में १०८ पटक)\n२. %s में दान करें\n३. %s  के रंग लगाउनुहोस्\n४. यदि सम्भव है भने %s में व्रत बस्नुहोस्\n५. नियमित रूप में इष्ट देवता के पूजा करें"),
    ,
    DASHA_SPECIFIC_TIMING("During %s Mahadasha or Antardasha", "%s महादशा वा अन्तर्दशाको समयमा", "%s महादशा या अन्तर्दशा के समय में"),
    ,
    DASHA_SPECIFIC_BENEFIT_REDUCE("Reduces difficulties during challenging Dasha", "काठिन दशाहरूमा कठिनाइहरू कम गर्दछ", "काठिन दशा में कठिनाइ कम करता है"),
    ,
    DASHA_SPECIFIC_BENEFIT_TRANSFORM("Transforms karmic lessons into growth opportunities", "कार्मिक पाठहरूलाई विकासका अवसरहरूमा बदल्छ", "कार्मिक पाठ  के विकास के अवसर में बदल्है"),
    ,
    DASHA_SPECIFIC_CAUTION("Be especially careful during Sade Sati (Saturn's 7.5 year transit over Moon)", "साढे साती (शनिको साढे ७ वर्षे गोचर) को समयमा विशेष सावधान रहनुहोस्", "साढे साती (शनि के साढे ७ वर्षे गोचर)  के समय में विशेष सावधान रहनुहोस्"),

    ,

    // Life Areas
    LIFE_AREA_GENERAL("General Life", "सामान्य जीवन", "सामान्य जीवन"),
    ,
    LIFE_AREA_CAREER("Career & Authority", "करियर र अधिकार", "करियर और अधिकार"),
    ,
    LIFE_AREA_RELATIONSHIPS("Relationships & Marriage", "सम्बन्ध र विवाह", "संबंध और विवाह"),
    ,
    LIFE_AREA_HEALTH("Health & Vitality", "स्वास्थ्य र जीवनशक्ति", "स्वास्थ्य और जीवनशक्ति"),
    ,
    LIFE_AREA_WEALTH("Wealth & Finance", "धन र वित्त", "धन और वित्त"),
    ,
    LIFE_AREA_EDUCATION("Education & Communication", "शिक्षा र सञ्चार", "शिक्षा और सञ्चार"),
    ,
    LIFE_AREA_SPIRITUAL("Spiritual Growth", "आध्यात्मिक वृद्धि", "आध्यात्मिक वृद्धि"),
    ,
    LIFE_AREA_FAMILY("Family & Home", "परिवार र घर", "परिवार और घर"),
    ,
    LIFE_AREA_PROPERTY("Property & Fixed Assets", "सम्पत्ति र अचल सम्पत्ति", "सम्पत्ति और अचल सम्पत्ति"),
    ,
    LIFE_AREA_FOREIGN("Foreign & Travel", "विदेश र यात्रा", "विदेश और यात्रा"),

    ,

    // Summary
    SUMMARY_TITLE("REMEDIES SUMMARY FOR %s ASCENDANT", "%s लग्नको लागि उपाय सारांश", "%s लग्न के लिए उपाय सारांश"),
    ,
    SUMMARY_FAVORABLE("Your planetary positions are generally favorable. Continue with positive practices to maintain balance.", "तपाईंको ग्रह स्थिति सामान्यतया अनुकूल छ। सन्तुलन कायम राख्न सकारात्मक अभ्यासहरू जारी राख्नुहोस्।", "आप के ग्रह स्थिति सामान्यतया अनुकूल है। सन्तुलन कायम राख्न सकारात्मक अभ्यास जारी राख्नुहोस्।"),
    ,
    SUMMARY_MAINTENANCE("RECOMMENDED MAINTENANCE PRACTICES:", "सिफारिस गरिएको मर्मत अभ्यासहरू:", "सिफारिस गरिए के मर्मत अभ्यास:"),
    ,
    SUMMARY_MAINTENANCE_1("• Daily meditation and pranayama", "• दैनिक ध्यान र प्राणायाम", "• दैनिक ध्यान और प्राणायाम"),
    ,
    SUMMARY_MAINTENANCE_2("• Weekly temple visits", "• साप्ताहिक मन्दिर दर्शन", "• साप्ताहिक मन्दिर दर्शन"),
    ,
    SUMMARY_MAINTENANCE_3("• Regular charity and service", "• नियमित दान र सेवा", "• नियमित दान और सेवा"),
    ,
    SUMMARY_MAINTENANCE_4("• Ethical living and positive thinking", "• नैतिक जीवन र सकारात्मक सोच", "• नैतिक जीवन और सकारात्मक सोच"),
    ,
    SUMMARY_FOCUS("PRIMARY FOCUS PLANETS: %s", "प्राथमिक फोकस ग्रहहरू: %s", "प्राथमिक फोकस ग्रह: %s"),
    ,
    SUMMARY_PRIORITY("REMEDY PRIORITY ORDER:", "उपाय प्राथमिकता क्रम:", "उपाय प्राथमिकता क्रम:"),
    ,
    SUMMARY_PRIORITY_1("1. MANTRAS (Start here - safest, most effective)", "१. मन्त्र (यहाँबाट सुरु गर्नुहोस् - सबैभन्दा सुरक्षित, सबैभन्दा प्रभावकारी)", "१. मन्त्र (यहाँबाट सुरु करें - सभीभन्दा सुरक्षित, सभीभन्दा प्रभावकारी)"),
    ,
    SUMMARY_PRIORITY_1_A("   • No side effects, can be done by anyone", "   • कुनै साइड इफेक्ट छैन, जो कोहीले गर्न सक्छ", "• कुनै साइड इफेक्ट हैैन, जो कोहीले करने सक्है"),
    ,
    SUMMARY_PRIORITY_1_B("   • Chant daily, preferably 108 times or more", "   • दैनिक जप गर्नुहोस्, प्राथमिकता १०८ पटक वा बढी", "• दैनिक जप करें, प्राथमिकता १०८ पटक या बढी"),
    ,
    SUMMARY_PRIORITY_1_C("   • Best performed during brahma muhurta (before sunrise)", "   • ब्रह्म मुहूर्त (सूर्योदय अघि) मा गर्नु उत्तम हुन्छ", "• ब्रह्म मुहूर्त (सूर्यहदय अघि) में करनेु उत्तम हैता है"),
    ,
    SUMMARY_PRIORITY_2("2. CHARITY (Universal benefit)", "२. दान (विश्वव्यापी लाभ)", "२. दान (विश्वव्यापी लाभ)"),
    ,
    SUMMARY_PRIORITY_2_A("   • Donate on the planet's weekday", "   • ग्रहको बारमा दान गर्नुहोस्", "• ग्रह के बार में दान करें"),
    ,
    SUMMARY_PRIORITY_2_B("   • Give with pure intention without expectation", "   • अपेक्षा बिना शुद्ध मनसायले दिनुहोस्", "• अपेक्षा बिना शुद्ध मनसायले दिनुहोस्"),
    ,
    SUMMARY_PRIORITY_3("3. FASTING (Powerful purification)", "३. व्रत (शक्तिशाली शुद्धिकरण)", "३. व्रत (शक्तिशाली शुद्धिकरण)"),
    ,
    SUMMARY_PRIORITY_3_A("   • Observe on the planet's day", "   • ग्रहको दिनमा मनाउनुहोस्", "• ग्रह के दिन में मनाउनुहोस्"),
    ,
    SUMMARY_PRIORITY_3_B("   • Even partial fasting is beneficial", "   • आंशिक व्रत पनि फाइदाजनक हुन्छ", "• आंशिक व्रत पनि फाइदाजनक हैता है"),
    ,
    SUMMARY_PRIORITY_4("4. DEITY WORSHIP (Divine connection)", "४. देवी-देवता पूजा (ईश्वरीय सम्बन्ध)", "४. देवी-देवता पूजा (ईश्वरीय संबंध)"),
    ,
    SUMMARY_PRIORITY_4_A("   • Visit relevant temples regularly", "   • सम्बन्धित मन्दिरहरूमा नियमित जानुहोस्", "• संबंधित मन्दिर में नियमित जानुहोस्"),
    ,
    SUMMARY_PRIORITY_4_B("   • Perform home worship with devotion", "   • भक्तिका साथ घरमा पूजा गर्नुहोस्", "• भक्ति के साथ घर में पूजा करें"),
    ,
    SUMMARY_PRIORITY_5("5. GEMSTONES (Use with caution)", "५. रत्न (सावधानीपूर्वक प्रयोग गर्नुहोस्)", "५. रत्न (सावधानीपूर्वक प्रयहग करें)"),
    ,
    SUMMARY_PRIORITY_5_A("   • Only for functional benefics of your Lagna", "   • मात्र तपाईंको लग्नको शुभ ग्रहहरूको लागि", "• मात्र आप के लग्न के शुभ ग्रह के लिए"),
    ,
    SUMMARY_PRIORITY_5_B("   • Consult an expert before wearing", "   • लगाउनु अघि विशेषज्ञसँग परामर्श गर्नुहोस्", "• लगाउनु अघि विशेषज्ञसँग परामर्श करें"),
    ,
    SUMMARY_PRIORITY_5_C("   • Always observe trial period first", "   • सधैं पहिले परीक्षण अवधि अवलोकन गर्नुहोस्", "• सधैं पहिले परीक्षण अवधि अवलोकन करें"),
    ,
    SUMMARY_YOGAKARAKA("IMPORTANT: %s is/are your Yogakaraka planet(s). Strengthening %s will bring maximum positive results.", "महत्त्वपूर्ण: %s तपाईंको योगकारक ग्रह(हरू) हो/हुन्। %s लाई बलियो बनाउँदा अधिकतम सकारात्मक परिणामहरू प्राप्त हुनेछन्।", "महत्त्वपूर्ण: %s आप के यहगकारक ग्रह() है/हैं। %s  के बलियह बनाउँदा अधिकतम सकारात्मक परिणाम प्राप्त हैगान्।"),
    ,
    SUMMARY_THIS_PLANET("this planet", "यो ग्रह", "यह ग्रह"),
    ,
    SUMMARY_THESE_PLANETS("these planets", "यी ग्रहहरू", "यी ग्रह"),

    ,

    SUMMARY_GUIDANCE_TITLE("GENERAL GUIDANCE:", "सामान्य मार्गदर्शन:", "सामान्य मार्गदर्शन:"),
    ,
    SUMMARY_GUIDANCE_POINT_1("• Start with one or two remedies, then gradually add more", "• एक वा दुई उपायहरूबाट सुरु गर्नुहोस्, त्यसपछि बिस्तारै थप्नुहोस्", "• एक या दुई उपायबाट सुरु करें, त्इसपहैि बिस्तारै जोड़ें"),
    ,
    SUMMARY_GUIDANCE_POINT_2("• Consistency is key - regular practice beats occasional intensity", "• निरन्तरता मुख्य कुरा हो - नियमित अभ्यासले कहिलेकाहीँको तीव्रता भन्दा राम्रो काम गर्छ", "• निरन्तरता मुख्य कुरा है - नियमित अभ्यासले कहिलेकाहीँ के तीव्रता भन्दा राम्रो काम करता है"),
    ,
    SUMMARY_GUIDANCE_POINT_3("• Remedies work best with positive attitude and good deeds", "• सकारात्मक दृष्टिकोण र राम्रो कामहरूका साथ उपायहरूले राम्रो काम गर्छन्", "• सकारात्मक दृष्टिकोण और राम्रो काम के साथ उपायले राम्रो काम करता हैन्"),
    ,
    SUMMARY_GUIDANCE_POINT_4("• Results manifest according to karmic timing", "• नतिजाहरू कार्मिक समय अनुसार प्रकट हुन्छन्", "• नतिजा कार्मिक समय अनुसार प्रकट हैता हैन्"),
    ,
    SUMMARY_GUIDANCE_POINT_5("• During difficult Dashas, increase remedy intensity", "• कठिन दशा अवधिहरूमा, उपायको तीव्रता बढाउनुहोस्", "• कठिन दशा अवधि में, उपाय के तीव्रता बढाउनुहोस्"),
    ,
    SUMMARY_GUIDANCE("GENERAL GUIDANCE:", "सामान्य मार्गदर्शन:", "सामान्य मार्गदर्शन:"),
    ,
    SUMMARY_GUIDANCE_1("• Start with one or two remedies, then gradually add more", "• एक वा दुई उपायहरूबाट सुरु गर्नुहोस्, त्यसपछि बिस्तारै थप थप्नुहोस्", "• एक या दुई उपायबाट सुरु करें, त्इसपहैि बिस्तारै थप जोड़ें"),
    ,
    SUMMARY_GUIDANCE_2("• Consistency is key - regular practice beats occasional intensity", "• निरन्तरता मुख्य हो - नियमित अभ्यासले कहिलेकाहीँको तीव्रतालाई जित्छ", "• निरन्तरता मुख्य है - नियमित अभ्यासले कहिलेकाहीँ के तीव्रता  के जित्है"),
    ,
    SUMMARY_GUIDANCE_3("• Remedies work best with positive attitude and good deeds", "• सकारात्मक दृष्टिकोण र राम्रो कामहरूसँग उपायहरूले राम्रो काम गर्छन्", "• सकारात्मक दृष्टिकोण और राम्रो कामसँग उपायले राम्रो काम करता हैन्"),
    ,
    SUMMARY_GUIDANCE_4("• Results manifest according to karmic timing", "• नतिजाहरू कार्मिक समय अनुसार प्रकट हुन्छन्", "• नतिजा कार्मिक समय अनुसार प्रकट हैता हैन्"),

    ,

    // Weekdays
    WEEKDAY_SUNDAY("Sunday", "आइतबार", "आइतबार"),
    ,
    WEEKDAY_MONDAY("Monday", "सोमबार", "सोमबार"),
    ,
    WEEKDAY_TUESDAY("Tuesday", "मंगलबार", "मंगलबार"),
    ,
    WEEKDAY_WEDNESDAY("Wednesday", "बुधबार", "बुधबार"),
    ,
    WEEKDAY_THURSDAY("Thursday", "बिहीबार", "बिहीबार"),
    ,
    WEEKDAY_FRIDAY("Friday", "शुक्रबार", "शुक्रबार"),
    ,
    WEEKDAY_SATURDAY("Saturday", "शनिबार", "शनिबार"),
    ,
    // Mantra Directions
    DIR_EAST("East", "पूर्व", "पूर्व"),
    ,
    DIR_WEST("West", "पश्चिम", "पश्चिम"),
    ,
    DIR_NORTH("North", "उत्तर", "उत्तर"),
    ,
    DIR_SOUTH("South", "दक्षिण", "दक्षिण"),
    ,
    DIR_NORTH_EAST("North-East", "उत्तर-पूर्व (ईशान)", "उत्तर-पूर्व (ईशान)"),
    ,
    DIR_NORTH_WEST("North-West", "उत्तर-पश्चिम (वायव्य)", "उत्तर-पश्चिम (वायव्य)"),
    ,
    DIR_SOUTH_EAST("South-East", "दक्षिण-पूर्व (आग्नेय)", "दक्षिण-पूर्व (आग्नेय)"),
    ,
    DIR_SOUTH_WEST("South-West", "दक्षिण-पश्चिम (नैऋत्य)", "दक्षिण-पश्चिम (नैऋत्य)"),

    ,

    // Charity Data (Sun to Ketu)
    CHARITY_SUN_ITEMS("Wheat, Jaggery (Gur), Copper vessel, Red/Orange cloth, Gold", "गहुँ, सख्खर (गुड), तामाको भाँडो, रातो/सुन्तला कपडा, सुन", "गहुँ, सख्खर (गुड), ता में के भाँडो, रातो/सुन्तला कपडा, सुन"),
    ,
    CHARITY_SUN_RECIPIENTS("Father figures, government servants, temples", "बुबा समान व्यक्तिहरू, सरकारी कर्मचारी, मन्दिरहरू", "बुबा समान व्यक्ति, सरकारी कर्मचारी, मन्दिर"),
    ,
    CHARITY_SUN_SPECIAL("Offer water to Sun at sunrise with copper vessel", "सूर्योदयमा तामाको भाँडोबाट सूर्यलाई अर्घ्य दिनुहोस्", "सूर्यहदय में ता में के भाँडोबाट सूर्य  के अर्घ्य दिनुहोस्"),

    ,
    
    CHARITY_MOON_ITEMS("Rice, White cloth, Silver, Milk, Curd, White flowers", "चामल, सेतो कपडा, चाँदी, दूध, दही, सेतो फूल", "चामल, सेतो कपडा, चाँदी, दूध, दही, सेतो फूल"),
    ,
    CHARITY_MOON_RECIPIENTS("Mother figures, elderly women, pilgrims", "आमा समान व्यक्तिहरू, वृद्ध महिलाहरू, तीर्थयात्रीहरू", "आ में समान व्यक्ति, वृद्ध महिला, तीर्थयात्री"),
    ,
    CHARITY_MOON_SPECIAL("Donate near water bodies; offer milk to Shivling", "जलाशय नजिक दान गर्नुहोस्; शिवलिङ्गमा दूध चढाउनुहोस्", "जलाशय नजिक दान करें; शिवलिङ्ग में दूध चढाउनुहोस्"),

    ,

    CHARITY_MARS_ITEMS("Red lentils (Masoor dal), Red cloth, Copper, Jaggery, Wheat bread", "रातो दाल (मसुरो), रातो कपडा, तामा, सख्खर, गहुँको रोटी", "रातो दाल (मसुरो), रातो कपडा, ता में, सख्खर, गहुँ के रोटी"),
    ,
    CHARITY_MARS_RECIPIENTS("Young men, soldiers, brothers, Hanuman temples", "युवा पुरुष, सैनिक, दाजुभाइ, हनुमान मन्दिर", "युवा पुरुष, सैनिक, दाजुभाइ, हनुमान मन्दिर"),
    ,
    CHARITY_MARS_SPECIAL("Donate at Hanuman temple; feed monkeys", "हनुमान मन्दिरमा दान गर्नुहोस्; बाँदरहरूलाई खुवाउनुहोस्", "हनुमान मन्दिर में दान करें; बाँदर  के खुवाउनुहोस्"),

    ,

    CHARITY_MERCURY_ITEMS("Green gram (Moong dal), Green cloth, Emerald green items, Books, Writing materials", "मुगको दाल, हरियो कपडा, पन्ना रङका वस्तुहरू, पुस्तकहरू, लेखन सामग्री", "मुग के दाल, हरियह कपडा, पन्ना रङ के वस्तु, पुस्तक, लेखन सामग्री"),
    ,
    CHARITY_MERCURY_RECIPIENTS("Students, scholars, young children, educational institutions", "विद्यार्थी, विद्वान, साना नानीहरू, शैक्षिक संस्थाहरू", "विद्यार्थी, विद्वान, साना नानी, शैक्षिक संस्था"),
    ,
    CHARITY_MERCURY_SPECIAL("Donate to schools; feed birds with green gram", "विद्यालयमा दान गर्नुहोस्; चराहरूलाई मुगको दाल खुवाउनुहोस्", "विद्यालय में दान करें; चरा  के मुग के दाल खुवाउनुहोस्"),

    ,

    CHARITY_JUPITER_ITEMS("Chana dal, Yellow cloth, Turmeric, Gold, Yellow flowers, Books", "चना दाल, पहेंलो कपडा, बेसार, सुन, पहेंलो फूल, पुस्तकहरू", "चना दाल, पहेंलो कपडा, बेसार, सुन, पहेंलो फूल, पुस्तक"),
    ,
    CHARITY_JUPITER_RECIPIENTS("Teachers, priests (Brahmins), temples, religious institutions", "गुरुहरू, पुजारी (ब्राह्मण), मन्दिरहरू, धार्मिक संस्थाहरू", "गुरु, पुजारी (ब्राह्मण), मन्दिर, धार्मिक संस्था"),
    ,
    CHARITY_JUPITER_SPECIAL("Donate to Vishnu/Jupiter temples; feed cows with chana dal", "विष्णु/बृहस्पति मन्दिरमा दान गर्नुहोस्; गाईलाई चना दाल खुवाउनुहोस्", "विष्णु/बृहस्पति मन्दिर में दान करें; गाई  के चना दाल खुवाउनुहोस्"),

    ,

    CHARITY_VENUS_ITEMS("Rice, White cloth, Silk, Perfumes, Sweets, Ghee", "चामल, सेतो कपडा, रेशम, अत्तर, मिठाई, घिउ", "चामल, सेतो कपडा, रेशम, अत्तर, मिठाई, घिउ"),
    ,
    CHARITY_VENUS_RECIPIENTS("Young women, artists, Lakshmi temples, cow shelters", "युवतीहरू, कलाकारहरू, लक्ष्मी मन्दिर, गाई गोठ", "युवती, कलाकार, लक्ष्मी मन्दिर, गाई गोठ"),
    ,
    CHARITY_VENUS_SPECIAL("Donate to women's welfare; offer white flowers to Lakshmi", "महिला कल्याणमा दान गर्नुहोस्; लक्ष्मीलाई सेतो फूल चढाउनुहोस्", "महिला कल्याण में दान करें; लक्ष्मी  के सेतो फूल चढाउनुहोस्"),

    ,

    CHARITY_SATURN_ITEMS("Black gram (Urad dal), Iron, Sesame oil, Blue/Black cloth, Mustard oil", "कालो मास (उरद दाल), फलाम, तिलको तेल, नीलो/कालो कपडा, तोरीको तेल", "कालो मास (उरद दाल), फलाम, तिल के तेल, नीलो/कालो कपडा, तोरी के तेल"),
    ,
    CHARITY_SATURN_RECIPIENTS("Poor and needy, servants, elderly, disabled, Shani temples", "गरिब र दुखी, सेवक, वृद्ध, अपाङ्ग, शनि मन्दिर", "गरिब और दुखी, सेवक, वृद्ध, अपाङ्ग, शनि मन्दिर"),
    ,
    CHARITY_SATURN_SPECIAL("Feed crows; offer mustard oil at Shani temple; serve the disabled", "कागलाई खुवाउनुहोस्; शनि मन्दिरमा तोरीको तेल चढाउनुहोस्; असहायको सेवा गर्नुहोस्", "काग  के खुवाउनुहोस्; शनि मन्दिर में तोरी के तेल चढाउनुहोस्; असहाय के सेवा करें"),

    ,

    CHARITY_RAHU_ITEMS("Coconut, Blue cloth, Sesame seeds, Lead, Blanket", "नरिवल, नीलो कपडा, तिल, सीसा, कम्बल", "नरिवल, नीलो कपडा, तिल, सीसा, कम्बल"),
    ,
    CHARITY_RAHU_RECIPIENTS("Outcasts, sweepers, Durga temples", "बहिष्कृत, सफाइकर्मी, दुर्गा मन्दिर", "बहिष्कृत, सफाइकर्मी, दुर्गा मन्दिर"),
    ,
    CHARITY_RAHU_SPECIAL("Donate at crossroads; offer to Durga temple", "चौबाटोमा दान गर्नुहोस्; दुर्गा मन्दिरमा चढाउनुहोस्", "चौबाटो में दान करें; दुर्गा मन्दिर में चढाउनुहोस्"),

    ,

    CHARITY_KETU_ITEMS("Mixed seven grains, Gray/Brown blanket, Sesame seeds, Dog food", "सतनजा (सात प्रकारका अन्न), खैरो कम्बल, तिल, कुकुरको खाना", "सतनजा (सात प्रकार के अन्न), खैरो कम्बल, तिल, कुकुर के खाना"),
    ,
    CHARITY_KETU_RECIPIENTS("Spiritual seekers, sadhus, dog shelters, Ganesha temples", "आध्यात्मिक साधक, साधु, कुकुर आश्रयस्थल, गणेश मन्दिर", "आध्यात्मिक साधक, साधु, कुकुर आश्रइस्थल, गणेश मन्दिर"),
    ,
    CHARITY_KETU_SPECIAL("Feed dogs; donate blankets to homeless; offer at Ganesha temple", "कुकुरलाई खुवाउनुहोस्; घरबारविहीनलाई कम्बल दान गर्नुहोस्; गणेश मन्दिरमा चढाउनुहोस्", "कुकुर  के खुवाउनुहोस्; घरबारविहीन  के कम्बल दान करें; गणेश मन्दिर में चढाउनुहोस्"),

    ,

    // Fasting Food (Sun to Ketu)
    FASTING_SUN_FOOD("Consume wheat-based items, jaggery, and avoid salt", "गहुँका परिकार, सख्खर सेवन गर्नुहोस् र नुन नखानुहोस्", "गहुँ के परिकार, सख्खर सेवन करें और नुन नखानुहोस्"),
    ,
    FASTING_MOON_FOOD("Consume rice, milk, white foods", "चामल, दूध, सेतो खाना सेवन गर्नुहोस्", "चामल, दूध, सेतो खाना सेवन करें"),
    ,
    FASTING_MARS_FOOD("Consume red lentils, avoid salt", "रातो दाल सेवन गर्नुहोस्, नुन नखानुहोस्", "रातो दाल सेवन करें, नुन नखानुहोस्"),
    ,
    FASTING_MERCURY_FOOD("Consume green gram, green vegetables", "मुगको दाल, हरियो तरकारी सेवन गर्नुहोस्", "मुग के दाल, हरियह तरकारी सेवन करें"),
    ,
    FASTING_JUPITER_FOOD("Consume chana dal, yellow foods, avoid salt", "चना दाल, पहेंलो खाना सेवन गर्नुहोस्, नुन नखानुहोस्", "चना दाल, पहेंलो खाना सेवन करें, नुन नखानुहोस्"),
    ,
    FASTING_VENUS_FOOD("Consume rice, milk, sweet foods", "चामल, दूध, गुलियो खाना सेवन गर्नुहोस्", "चामल, दूध, गुलियह खाना सेवन करें"),
    ,
    FASTING_SATURN_FOOD("Consume black gram, sesame, avoid salt", "कालो मास, तिल सेवन गर्नुहोस्, नुन नखानुहोस्", "कालो मास, तिल सेवन करें, नुन नखानुहोस्"),
    ,
    FASTING_RAHU_FOOD("Observe complete fast or consume only fruits", "पूर्ण व्रत बस्नुहोस् वा केवल फलफूल सेवन गर्नुहोस्", "पूर्ण व्रत बस्नुहोस् या केवल फलफूल सेवन करें"),
    ,
    FASTING_KETU_FOOD("Observe complete fast or consume only milk", "पूर्ण व्रत बस्नुहोस् वा केवल दूध सेवन गर्नुहोस्", "पूर्ण व्रत बस्नुहोस् या केवल दूध सेवन करें"),

    ,

    // Color Data (Colors, Avoid)
    COLOR_SUN_USE("Orange, Red, Ruby Red, Gold, Saffron", "सुन्तला, रातो, माणिक रातो, सुनौलो, केसर", "सुन्तला, रातो, माणिक रातो, सुनौलो, केसर"),
    ,
    COLOR_SUN_AVOID("Blue, Black", "नीलो, कालो", "नीलो, कालो"),
    ,
    COLOR_MOON_USE("White, Silver, Light Blue, Cream, Pearl White", "सेतो, चाँदी, हल्का नीलो, क्रिम, मोती सेतो", "सेतो, चाँदी, हल् के नीलो, क्रिम, मोती सेतो"),
    ,
    COLOR_MOON_AVOID("Red, Black", "रातो, कालो", "रातो, कालो"),
    ,
    COLOR_MARS_USE("Red, Maroon, Coral Red, Scarlet", "रातो, मेरुन, मुगा रातो, गाढा रातो", "रातो, मेरुन, मुगा रातो, गाढा रातो"),
    ,
    COLOR_MARS_AVOID("Blue, Green", "नीलो, हरियो", "नीलो, हरियह"),
    ,
    COLOR_MERCURY_USE("Green, Light Green, Emerald Green, Parrot Green", "हरियो, हल्का हरियो, पन्ना हरियो, सुगा रङ", "हरियह, हल् के हरियह, पन्ना हरियह, सुगा रङ"),
    ,
    COLOR_MERCURY_AVOID("Red", "रातो", "रातो"),
    ,
    COLOR_JUPITER_USE("Yellow, Gold, Turmeric, Saffron, Orange-Yellow", "पहेंलो, सुनौलो, बेसार रङ, केसर, सुन्तला-पहेंलो", "पहेंलो, सुनौलो, बेसार रङ, केसर, सुन्तला-पहेंलो"),
    ,
    COLOR_JUPITER_AVOID("Blue, Black", "नीलो, कालो", "नीलो, कालो"),
    ,
    COLOR_VENUS_USE("White, Pink, Light Colors, Cream, Pastel shades", "सेतो, गुलाबी, हल्का रङहरू, क्रिम, पेस्टल सेड्स", "सेतो, गुलाबी, हल् के रङ, क्रिम, पेस्टल सेड्स"),
    ,
    COLOR_VENUS_AVOID("Red, Blue", "रातो, नीलो", "रातो, नीलो"),
    ,
    COLOR_SATURN_USE("Blue, Black, Dark Blue, Navy, Violet", "नीलो, कालो, गाढा नीलो, नेभी, बैजनी", "नीलो, कालो, गाढा नीलो, नेभी, बैजनी"),
    ,
    COLOR_SATURN_AVOID("Red, Orange", "रातो, सुन्तला", "रातो, सुन्तला"),
    ,
    COLOR_RAHU_USE("Smoke Blue, Electric Blue, Multi-colored", "धुवाँ नीलो, इलेक्ट्रिक नीलो, बहुरंगी", "धुवाँ नीलो, इलेक्ट्रिक नीलो, बहुरंगी"),
    ,
    COLOR_RAHU_AVOID("Pure White", "शुद्ध सेतो", "शुद्ध सेतो"),
    ,
    COLOR_KETU_USE("Gray, Brown, Smoky, Earthy tones", "खैरो, माटो रङ, धुवाँ रङ", "खैरो, माटो रङ, धुवाँ रङ"),
    ,
    COLOR_KETU_AVOID("Bright colors", "चम्किलो रङहरू", "चम्किलो रङ"),

    ,

    // Deity Data (Primary, Secondary, Temple, Offerings)
    DEITY_SUN_TEMPLES("Surya Mandir, Konark Sun Temple, any Sun temple", "सूर्य मन्दिर, कोणार्क सूर्य मन्दिर, कुनै पनि सूर्य मन्दिर", "सूर्य मन्दिर, कोणार्क सूर्य मन्दिर, कुनै पनि सूर्य मन्दिर"),
    ,
    DEITY_SUN_OFFERINGS("Red flowers, wheat, jaggery, copper items", "रातो फूल, गहुँ, सख्खर, तामाका वस्तुहरू", "रातो फूल, गहुँ, सख्खर, ता में के वस्तु"),
    ,
    DEITY_MOON_TEMPLES("Any Shiva temple, especially Jyotirlingas", "कुनै पनि शिव मन्दिर, विशेष गरी ज्योतिर्लिङ्ग", "कुनै पनि शिव मन्दिर, विशेष गरी ज्यहतिर्लिङ्ग"),
    ,
    DEITY_MOON_OFFERINGS("White flowers, milk, water, rice, silver items", "सेतो फूल, दूध, जल, चामल, चाँदीका वस्तुहरू", "सेतो फूल, दूध, जल, चामल, चाँदी के वस्तु"),
    ,
    DEITY_MARS_TEMPLES("Hanuman temple, Mangalnath Mandir Ujjain", "हनुमान मन्दिर, मंगलनाथ मन्दिर उज्जैन", "हनुमान मन्दिर, मंगलनाथ मन्दिर उज्जैन"),
    ,
    DEITY_MARS_OFFERINGS("Red flowers, red sindoor, jaggery, coconut", "रातो फूल, रातो सिन्दूर, सख्खर, नरिवल", "रातो फूल, रातो सिन्दूर, सख्खर, नरिवल"),
    ,
    DEITY_MERCURY_TEMPLES("Vishnu temple, any Krishna temple", "विष्णु मन्दिर, कुनै पनि कृष्ण मन्दिर", "विष्णु मन्दिर, कुनै पनि कृष्ण मन्दिर"),
    ,
    DEITY_MERCURY_OFFERINGS("Green items, green gram, tulsi, flowers", "हरियो वस्तुहरू, मुगको दाल, तुलसी, फूलहरू", "हरियह वस्तु, मुग के दाल, तुलसी, फूल"),
    ,
    DEITY_JUPITER_TEMPLES("Guru temple, Vishnu temple", "गुरु मन्दिर, विष्णु मन्दिर", "गुरु मन्दिर, विष्णु मन्दिर"),
    ,
    DEITY_JUPITER_OFFERINGS("Yellow flowers, turmeric, chana dal, bananas", "पहेंलो फूल, बेसार, चना दाल, केरा", "पहेंलो फूल, बेसार, चना दाल, केरा"),
    ,
    DEITY_VENUS_TEMPLES("Lakshmi temple, any Devi temple", "लक्ष्मी मन्दिर, कुनै पनि देवी मन्दिर", "लक्ष्मी मन्दिर, कुनै पनि देवी मन्दिर"),
    ,
    DEITY_VENUS_OFFERINGS("White flowers, rice, sweets, silk, perfumes", "सेतो फूल, चामल, मिठाई, रेशम, अत्तर", "सेतो फूल, चामल, मिठाई, रेशम, अत्तर"),
    ,
    DEITY_SATURN_TEMPLES("Shani temple, Shani Shingnapur, any Shani shrine", "शनि मन्दिर, शनि शिंगणापुर, कुनै पनि शनि पीठ", "शनि मन्दिर, शनि शिंगणापुर, कुनै पनि शनि पीठ"),
    ,
    DEITY_SATURN_OFFERINGS("Black sesame, mustard oil, iron items, blue flowers", "कालो तिल, तोरीको तेल, फलामका वस्तुहरू, नीलो फूल", "कालो तिल, तोरी के तेल, फलाम के वस्तु, नीलो फूल"),
    ,
    DEITY_RAHU_TEMPLES("Durga temple, Naga temples, Rahu shrine", "दुर्गा मन्दिर, नाग मन्दिर, राहु पीठ", "दुर्गा मन्दिर, नाग मन्दिर, राहु पीठ"),
    ,
    DEITY_RAHU_OFFERINGS("Coconut, blue flowers, hessonite, sandalwood", "नरिवल, नीलो फूल, गोमेद, चन्दन", "नरिवल, नीलो फूल, गोमेद, चन्दन"),
    ,
    DEITY_KETU_TEMPLES("Ganesha temple, any Ketu shrine", "गणेश मन्दिर, कुनै पनि केतु पीठ", "गणेश मन्दिर, कुनै पनि केतु पीठ"),
    ,
    DEITY_KETU_OFFERINGS("Mixed grains, brown/gray items, dog food for charity", "मिश्रित अन्न, खैरो वस्तुहरू, कुकुरको खाना", "मिश्रित अन्न, खैरो वस्तु, कुकुर के खाना"),
    ,
    // Note: Primary/Secondary deity names are generally names, can use existing strings or add if needed.
    // I'll add them to be safe and thorough.
    DEITY_SUN_PRIM("Lord Surya Narayan", "भगवान सूर्य नारायण", "भगवान सूर्य नारायण"),
    ,
    DEITY_SUN_SEC("Lord Vishnu, Lord Ram, Lord Shiva (as Mrityunjaya)", "भगवान विष्णु, भगवान राम, भगवान शिव", "भगवान विष्णु, भगवान राम, भगवान शिव"),
    ,
    DEITY_MOON_PRIM("Lord Shiva", "भगवान शिव", "भगवान शिव"),
    ,
    DEITY_MOON_SEC("Goddess Parvati, Goddess Ganga, Lord Chandra", "देवी पार्वती, देवी गंगा, भगवान चन्द्र", "देवी पार्वती, देवी गंगा, भगवान चन्द्र"),
    ,
    DEITY_MARS_PRIM("Lord Hanuman", "भगवान हनुमान", "भगवान हनुमान"),
    ,
    DEITY_MARS_SEC("Lord Kartikeya (Murugan), Goddess Durga, Lord Bhairav", "भगवान कार्तिकेय, देवी दुर्गा, भगवान भैरव", "भगवान कार्तिकेय, देवी दुर्गा, भगवान भैरव"),
    ,
    DEITY_MERCURY_PRIM("Lord Vishnu", "भगवान विष्णु", "भगवान विष्णु"),
    ,
    DEITY_MERCURY_SEC("Lord Krishna, Lord Buddha, Goddess Saraswati", "भगवान कृष्ण, भगवान बुद्ध, देवी सरस्वती", "भगवान कृष्ण, भगवान बुद्ध, देवी सरस्वती"),
    ,
    DEITY_JUPITER_PRIM("Lord Brihaspati / Dakshinamurthy", "भगवान बृहस्पति / दक्षिणामूर्ति", "भगवान बृहस्पति / दक्षिणामूर्ति"),
    ,
    DEITY_JUPITER_SEC("Lord Vishnu, Lord Shiva (as Guru), Lord Dattatreya", "भगवान विष्णु, भगवान शिव (गुरु रूपमा), भगवान दत्तात्रेय", "भगवान विष्णु, भगवान शिव (गुरु रूपमा), भगवान दत्तात्रेय"),
    ,
    DEITY_VENUS_PRIM("Goddess Lakshmi", "देवी लक्ष्मी", "देवी लक्ष्मी"),
    ,
    DEITY_VENUS_SEC("Goddess Saraswati, Lord Krishna, Goddess Annapurna", "देवी सरस्वती, भगवान कृष्ण, देवी अन्नपूर्णा", "देवी सरस्वती, भगवान कृष्ण, देवी अन्नपूर्णा"),
    ,
    DEITY_SATURN_PRIM("Lord Shani Dev", "भगवान शनि देव", "भगवान शनि देव"),
    ,
    DEITY_SATURN_SEC("Lord Hanuman, Lord Bhairav, Goddess Kali", "भगवान हनुमान, भगवान भैरव, देवी काली", "भगवान हनुमान, भगवान भैरव, देवी काली"),
    ,
    DEITY_RAHU_PRIM("Goddess Durga", "देवी दुर्गा", "देवी दुर्गा"),
    ,
    DEITY_RAHU_SEC("Lord Bhairav, Goddess Kali, Naga Devatas", "भगवान भैरव, देवी काली, नाग देवताहरू", "भगवान भैरव, देवी काली, नाग देवता"),
    ,
    DEITY_KETU_PRIM("Lord Ganesha", "भगवान गणेश", "भगवान गणेश"),
    ,
    DEITY_KETU_SEC("Chitragupta, Lord Kartikeya, Goddess Kali", "चित्रगुप्त, भगवान कार्तिकेय, देवी काली", "चित्रगुप्त, भगवान कार्तिकेय, देवी काली"),

    ,

    SUMMARY_GUIDANCE_5("• During difficult Dashas, increase remedy intensity", "• कठिन दशाको समयमा, उपायको तीव्रता बढाउनुहोस्", "• कठिन दशा के समय में, उपाय के तीव्रता बढाउनुहोस्"),

    ,

    // Yantra Descriptions
    YANTRA_SUN_DESC("Geometric representation of Sun's energy, brings fame, authority, and government favor", "सूर्यको ऊर्जाको ज्यामितीय प्रतिनिधित्व, ख्याति, अधिकार र सरकारी लाभ ल्याउँछ", "सूर्य के ऊर्जा के ज्यामितीय प्रतिनिधित्व, ख्याति, अधिकार और सरकारी लाभ लाता है"),
    ,
    YANTRA_MOON_DESC("Represents lunar energy, brings mental peace, emotional stability, and public favor", "चन्द्रमाको ऊर्जा प्रतिनिधित्व गर्दछ, मानसिक शान्ति, भावनात्मक स्थिरता र सार्वजनिक समर्थन ल्याउँछ", "चन्द्र में के ऊर्जा प्रतिनिधित्व करता है, मानसिक शांति, भावनात्मक स्थिरता और सार्वजनिक समर्थन लाता है"),
    ,
    YANTRA_MARS_DESC("Represents Mars energy, brings courage, property success, and victory over enemies", "मंगल ऊर्जा प्रतिनिधित्व गर्दछ, साहस, सम्पत्ति सफलता र शत्रुहरूमाथि विजय ल्याउँछ", "मंगल ऊर्जा प्रतिनिधित्व करता है, साहस, सम्पत्ति सफलता और शत्रुमाथि विजय लाता है"),
    ,
    YANTRA_MERCURY_DESC("Represents Mercury's energy, brings intelligence, business success, and communication skills", "बुधको ऊर्जा प्रतिनिधित्व गर्दछ, बुद्धि, व्यावसायिक सफलता र सञ्चार कौशल ल्याउँछ", "बुध के ऊर्जा प्रतिनिधित्व करता है, बुद्धि, व्यावसायिक सफलता और सञ्चार कौशल लाता है"),
    ,
    YANTRA_JUPITER_DESC("Represents Jupiter's energy, brings wisdom, wealth, children, and spiritual growth", "बृहस्पतिको ऊर्जा प्रतिनिधित्व गर्दछ, ज्ञान, धन, सन्तान र आध्यात्मिक वृद्धि ल्याउँछ", "बृहस्पति के ऊर्जा प्रतिनिधित्व करता है, ज्ञान, धन, संतान और आध्यात्मिक वृद्धि लाता है"),
    ,
    YANTRA_VENUS_DESC("Represents Venus energy, brings love, beauty, luxury, and artistic success", "शुक्र ऊर्जा प्रतिनिधित्व गर्दछ, प्रेम, सौन्दर्य, विलासिता र कलात्मक सफलता ल्याउँछ", "शुक्र ऊर्जा प्रतिनिधित्व करता है, प्रेम, सौन्दर्य, विलासिता और कलात्मक सफलता लाता है"),
    ,
    YANTRA_SATURN_DESC("Represents Saturn's energy, removes obstacles, brings discipline and success through persistence", "शनिको ऊर्जा प्रतिनिधित्व गर्दछ, अवरोधहरू हटाउँछ, अनुशासन र लगनशीलता मार्फत सफलता ल्याउँछ", "शनि के ऊर्जा प्रतिनिधित्व करता है, अवरोध हटाउँहै, अनुशासन और लगनशीलता मार्फत सफलता लाता है"),
    ,
    YANTRA_RAHU_DESC("Represents Rahu's energy, brings worldly success, removes fear, and protects from black magic", "राहुको ऊर्जा प्रतिनिधित्व गर्दछ, सांसारिक सफलता ल्याउँछ, डर हटाउँछ र कालो जादुबाट बचाउँछ", "राहु के ऊर्जा प्रतिनिधित्व करता है, सांसारिक सफलता लाता है, डर हटाउँहै और कालो जादुबाट बचाउँहै"),
    ,
    YANTRA_KETU_DESC("Represents Ketu's energy, brings spiritual liberation, removes past karma, and enhances intuition", "केतुको ऊर्जा प्रतिनिधित्व गर्दछ, आध्यात्मिक मुक्ति ल्याउँछ, विगतको कर्म हटाउँछ र अन्तर्ज्ञान बढाउँछ", "केतु के ऊर्जा प्रतिनिधित्व करता है, आध्यात्मिक मुक्ति लाता है, विगत के कर्म हटाउँहै और अन्तर्ज्ञान बढाउँहै"),

    ,

    // Rudraksha Benefits (Delimited by |)
    RUDRA_SUN_BENEFITS("Enhances leadership|Boosts confidence|Improves health|Success in government matters", "नेतृत्व क्षमता बढाउँछ|आत्मविश्वास बढाउँछ|स्वास्थ्य सुधार गर्छ|सरकारी मामिलामा सफलता", "नेतृत्व क्षमता बढाउँहै|आत्मविश्वास बढाउँहै|स्वास्थ्य सुधार करता है|सरकारी मामिला में सफलता"),
    ,
    RUDRA_MOON_BENEFITS("Emotional balance|Mental peace|Harmonious relationships|Cures mood disorders", "भावनात्मक सन्तुलन|मानसिक शान्ति|सुमधुर सम्बन्ध|मनोदशा विकारहरू निको पार्छ", "भावनात्मक सन्तुलन|मानसिक शांति|सुमधुर संबंध|मनोदशा विकार नि के पार्है"),
    ,
    RUDRA_MARS_BENEFITS("Removes lethargy|Increases energy|Boosts courage|Overcomes fear and guilt", "आलस्य हटाउँछ|ऊर्जा बढाउँछ|साहस बढाउँछ|डर र अपराधबोध जित्छ", "आलस्य हटाउँहै|ऊर्जा बढाउँहै|साहस बढाउँहै|डर और अपराधबोध जित्है"),
    ,
    RUDRA_MERCURY_BENEFITS("Enhances intelligence|Improves communication|Academic success|Creative abilities", "बौद्धिकता बढाउँछ|सञ्चार सुधार गर्छ|शैक्षिक सफलता|सिर्जनात्मक क्षमताहरू", "बौद्धिकता बढाउँहै|सञ्चार सुधार करता है|शैक्षिक सफलता|सिर्जनात्मक क्षमता"),
    ,
    RUDRA_JUPITER_BENEFITS("Spiritual growth|Wisdom enhancement|Good fortune|Removes sins", "आध्यात्मिक वृद्धि|ज्ञान वृद्धि|भाग्य|पाप हटाउँछ", "आध्यात्मिक वृद्धि|ज्ञान वृद्धि|भाग्य|पाप हटाउँहै"),
    ,
    RUDRA_VENUS_BENEFITS("Love and relationships|Artistic abilities|Material comforts|Removes obstacles in marriage", "प्रेम र सम्बन्ध|कलात्मक क्षमताहरू|भौतिक सुख-सुविधा|विवाहमा अवरोधहरू हटाउँछ", "प्रेम और संबंध|कलात्मक क्षमता|भौतिक सुख-सुविधा|विवाह में अवरोध हटाउँहै"),
    ,
    RUDRA_SATURN_BENEFITS("Wealth and prosperity|Removes poverty|Good fortune|Success after struggle", "धन र समृद्धि|गरिबी हटाउँछ|भाग्य|संघर्ष पछि सफलता", "धन और समृद्धि|गरिबी हटाउँहै|भाग्य|संघर्ष पहैि सफलता"),
    ,
    RUDRA_RAHU_BENEFITS("Removes obstacles|Protection from enemies|Success in endeavors|Removes Rahu dosha", "अवरोधहरू हटाउँछ|शत्रुहरूबाट सुरक्षा|प्रयासहरूमा सफलता|राहु दोष हटाउँछ", "अवरोध हटाउँहै|शत्रुबाट सुरक्षा|प्रयास में सफलता|राहु दोष हटाउँहै"),
    ,
    RUDRA_KETU_BENEFITS("Spiritual liberation|Removes fear|Protection from negativity|Removes Ketu dosha", "आध्यात्मिक मुक्ति|डर हटाउँछ|नकारात्मकताबाट सुरक्षा|केतु दोष हटाउँछ", "आध्यात्मिक मुक्ति|डर हटाउँहै|नकारात्मकताबाट सुरक्षा|केतु दोष हटाउँहै"),

    ,

    // Lifestyle Practices (Delimited by |)
    LIFESTYLE_SUN_PRACTICES("Wake before sunrise and perform Surya Namaskar|Offer water (Arghya) to Sun at sunrise|Spend time in natural sunlight (morning hours)|Respect father, authority figures, and government officials|Develop leadership qualities with humility|Eat meals before sunset when possible", "सूर्योदय हुनुभन्दा पहिले उठ्नुहोस् र सूर्य नमस्कार गर्नुहोस्|सूर्योदयको समयमा सूर्यलाई अर्घ्य दिनुहोस्|प्राकृतिक सूर्यको प्रकाशमा समय बिताउनुहोस् (बिहानको समय)|बुबा, अधिकारवाला व्यक्तिहरू र सरकारी अधिकारीहरूलाई आदर गर्नुहोस्|नम्रताका साथ नेतृत्व गुणहरू विकास गर्नुहोस्|सम्भव भएसम्म सूर्यास्त अघि खाना खानुहोस्", "सूर्यहदय हुनुभन्दा पहिले उठ्नुहोस् और सूर्य नमस्कार करें|सूर्यहदय के समय में सूर्य  के अर्घ्य दिनुहोस्|प्राकृतिक सूर्य के प्रकाश में समय बिताउनुहोस् (बिहान के समय)|बुबा, अधिकारवाला व्यक्ति और सरकारी अधिकारी  के आदर करें|नम्रता के साथ नेतृत्व गुण विकास करें|सम्भव भएसम्म सूर्यास्त अघि खाना खानुहोस्"),
    ,
    LIFESTYLE_MOON_PRACTICES("Drink plenty of water and milk|Meditate near water bodies (rivers, lakes, sea)|Respect mother and maternal figures|Practice emotional balance and mindfulness|Keep white flowers in your room|Observe Poornima (full moon) by fasting or worship|Avoid arguments, especially with mother", "प्रशस्त पानी र दूध पिउनुहोस्|जलाशय नजिक धेयान गर्नुहोस् (नदी, ताल, समुद्र)|आमा र मातृ शक्तिलाई आदर गर्नुहोस्|भावनात्मक सन्तुलन र सजगता अभ्यास गर्नुहोस्|आफ्नो कोठामा सेतो फूल राख्नुहोस्|पूर्णिमामा व्रत वा पूजा गर्नुहोस्|विवादबाट बच्नुहोस्, विशेष गरी आमासँग", "प्रशस्त पानी और दूध पिउनुहोस्|जलाशय नजिक धेयान करें (नदी, ताल, समुद्र)|आ में और मातृ शक्ति  के आदर करें|भावनात्मक सन्तुलन और सजगता अभ्यास करें|अपना कोठा में सेतो फूल राख्नुहोस्|पूर्णिमा में व्रत या पूजा करें|विवादबाट बच्नुहोस्, विशेष गरी आमासँग"),
    ,
    LIFESTYLE_MARS_PRACTICES("Exercise regularly (physical activity is essential)|Practice martial arts, yoga, or sports|Channel energy positively through constructive work|Help younger siblings and protect the weak|Donate blood if medically fit|Recite Hanuman Chalisa daily|Maintain celibacy on Tuesdays", "नियमित व्यायाम गर्नुहोस् (शारीरिक गतिविधि आवश्यक छ)|मार्शल आर्ट, योग वा खेलकुद अभ्यास गर्नुहोस्|रचनात्मक काम मार्फत ऊर्जालाई सकारात्मक रूपमा प्रयोग गर्नुहोस्|साना दाजुभाइलाई मद्दत गर्नुहोस् र कमजोरलाई रक्षा गर्नुहोस्|यदि चिकित्सकीय रूपमा योग्य हुनुहुन्छ भने रक्तदान गर्नुहोस्|दैनिक हनुमान चालिसा पाठ गर्नुहोस्|मंगलबार ब्रह्मचर्य पालन गर्नुहोस्", "नियमित व्यायाम करें (शारीरिक गतिविधि आवश्यक है)|मार्शल आर्ट, यहग या खेलकुद अभ्यास करें|रचनात्मक काम मार्फत ऊर्जा  के सकारात्मक रूप में प्रयहग करें|साना दाजुभाइ  के सहायता करें और कमजोर  के रक्षा करें|यदि चिकित्सकीय रूप में यहग्य हैं भने रक्तदान करें|दैनिक हनुमान चालिसा पाठ करें|मंगलबार ब्रह्मचर्य पालन करें"),
    ,
    LIFESTYLE_MERCURY_PRACTICES("Read books and acquire new knowledge daily|Practice clear and honest communication|Learn a new skill or language|Write daily - journal, notes, or creative writing|Help students and support education|Keep your living space organized|Practice numeracy - solve puzzles or calculations", "दैनिक पुस्तकहरू पढ्नुहोस् र नयाँ ज्ञान प्राप्त गर्नुहोस्|स्पष्ट र इमानदार सञ्चार अभ्यास गर्नुहोस्|नयाँ सीप वा भाषा सिक्नुहोस्|दैनिक लेख्नुहोस् - जर्नल, नोटहरू वा सिर्जनात्मक लेखन|विद्यार्थीहरूलाई मद्दत गर्नुहोस् र शिक्षालाई समर्थन गर्नुहोस्|आफ्नो बस्ने ठाउँ व्यवस्थित राख्नुहोस्|गणित अभ्यास गर्नुहोस् - पजलहरू वा हिसाब गर्नुहोस्", "दैनिक पुस्तक पढ्नुहोस् और नयाँ ज्ञान प्राप्त करें|स्पष्ट और इमानदार सञ्चार अभ्यास करें|नयाँ सीप या भाषा सिक्नुहोस्|दैनिक लेख्नुहोस् - जर्नल, नोट या सिर्जनात्मक लेखन|विद्यार्थी  के सहायता करें और शिक्षा  के समर्थन करें|अपना बस्ने ठाउँ व्यवस्थित राख्नुहोस्|गणित अभ्यास करें - पजल या हिसाब करें"),
    ,
    LIFESTYLE_JUPITER_PRACTICES("Study scriptures and philosophical texts|Respect teachers, elders, and Brahmins|Practice generosity and charity|Maintain ethical conduct in all dealings|Visit temples, especially on Thursdays|Apply turmeric tilak on forehead|Teach or mentor others when possible", "शास्त्र र दार्शनिक पाठहरू अध्ययन गर्नुहोस्|शिक्षक, ठूलाबाडा र ब्राह्मणहरूलाई आदर गर्नुहोस्|उदारता र दान अभ्यास गर्नुहोस्|सबै व्यवहारमा नैतिक आचरण कायम राख्नुहोस्|मन्दिर जानुहोस्, विशेष गरी बिहीबार|निधारमा बेसारको टीका लगाउनुहोस्|सम्भव भएसम्म अरूलाई सिकाउनुहोस् वा मार्गदर्शन गर्नुहोस्", "शास्त्र और दार्शनिक पाठ अध्ययन करें|शिक्षक, ठूलाबाडा और ब्राह्मण  के आदर करें|उदारता और दान अभ्यास करें|सभी व्यवहार में नैतिक आचरण कायम राख्नुहोस्|मन्दिर जानुहोस्, विशेष गरी बिहीबार|निधार में बेसार के टी के लगाउनुहोस्|सम्भव भएसम्म अरू  के सिकाउनुहोस् या मार्गदर्शन करें"),
    ,
    LIFESTYLE_VENUS_PRACTICES("Appreciate arts, music, and beauty|Maintain harmony in relationships|Practice gratitude daily|Keep your surroundings beautiful and clean|Respect women and feminine energy|Wear clean, pleasant-smelling clothes|Use perfumes and flowers in your space", "कला, संगीत र सौन्दर्यको कदर गर्नुहोस्|सम्बन्धमा सद्भाव कायम राख्नुहोस्|दैनिक कृतज्ञता अभ्यास गर्नुहोस्|आफ्नो वरपरको वातावरण सुन्दर र सफा राख्नुहोस्|महिला र स्त्री शक्तिलाई आदर गर्नुहोस्|सफा, सुगन्धित लुगा लगाउनुहोस्|आफ्नो ठाउँमा अत्तर र फूल प्रयोग गर्नुहोस्", "कला, संगीत और सौन्दर्य के कदर करें|संबंध में सद्भाव कायम राख्नुहोस्|दैनिक कृतज्ञता अभ्यास करें|अपना वरपर के वातावरण सुन्दर और सफा राख्नुहोस्|महिला और स्त्री शक्ति  के आदर करें|सफा, सुगन्धित लुगा लगाउनुहोस्|अपना ठाउँ में अत्तर और फूल प्रयहग करें"),
    ,
    LIFESTYLE_SATURN_PRACTICES("Practice discipline and routine strictly|Serve the elderly, poor, and disabled|Be patient - avoid shortcuts|Work hard and consistently|Help servants and laborers|Feed crows, especially on Saturdays|Visit Shani temple or recite Shani Stotram|Keep your workspace clean and organized", "अनुशासन र दिनचर्या कडा रूपमा पालना गर्नुहोस्|वृद्ध, गरिब र अपाङ्गहरूको सेवा गर्नुहोस्|धैर्यवान हुनुहोस् - सर्टकटहरू नगर्नुहोस्|कडा परिश्रम र निरन्तर काम गर्नुहोस्|सेवक र मजदुरहरूलाई मद्दत गर्नुहोस्|कागलाई खुवाउनुहोस्, विशेष गरी शनिबार|शनि मन्दिर जानुहोस् वा शनि स्तोत्र पाठ गर्नुहोस्|आफ्नो कार्यस्थल सफा र व्यवस्थित राख्नुहोस्", "अनुशासन और दिनचर्या कडा रूप में पालना करें|वृद्ध, गरिब और अपाङ्ग के सेवा करें|धैर्यवान हुनुहोस् - सर्टकट नकरें|कडा परिश्रम और निरन्तर काम करें|सेवक और मजदुर  के सहायता करें|काग  के खुवाउनुहोस्, विशेष गरी शनिबार|शनि मन्दिर जानुहोस् या शनि स्तोत्र पाठ करें|अपना कार्इस्थल सफा और व्यवस्थित राख्नुहोस्"),
    ,
    LIFESTYLE_RAHU_PRACTICES("Avoid shortcuts and get-rich-quick schemes|Practice honesty in all dealings|Reduce materialistic desires|Avoid intoxicants completely|Stay grounded - avoid getting carried away|Donate to outcasts and marginalized people|Keep your thoughts positive", "सर्टकट र छिटो धनी हुने योजनाहरूबाट बच्नुहोस्|सबै व्यवहारमा इमानदारी अभ्यास गर्नुहोस्|भौतिकवादी इच्छाहरू कम गर्नुहोस्|नशाबाट पूर्ण रूपमा टाढा रहनुहोस्|यथार्थमा रहनुहोस् - बहकिनु हुँदैन|बहिष्कृत र सीमान्तकृत मानिसहरूलाई दान गर्नुहोस्|आफ्नो विचार सकारात्मक राख्नुहोस्", "सर्टकट और हैिटो धनी हुने यहजनाबाट बच्नुहोस्|सभी व्यवहार में इमानदारी अभ्यास करें|भौतिकवादी इच्हैा कम करें|नशाबाट पूर्ण रूप में टाढा रहनुहोस्|यथार्थ में रहनुहोस् - बहकिनु हुँदैन|बहिष्कृत और सीमान्तकृत मानिस  के दान करें|अपना विचार सकारात्मक राख्नुहोस्"),
    ,
    LIFESTYLE_KETU_PRACTICES("Meditate daily - at least 15-30 minutes|Practice detachment from material outcomes|Pursue spiritual knowledge|Feed dogs, especially stray dogs|Visit Ganesha temples|Study ancient wisdom and occult sciences|Practice solitude and introspection", "दैनिक ध्यान गर्नुहोस् - कम्तिमा १५-३० मिनेट|भौतिक परिणामहरूबाट वैराग्य अभ्यास गर्नुहोस्|आध्यात्मिक ज्ञानको पछि लाग्नुहोस्|कुकुरहरूलाई खुवाउनुहोस्, विशेष गरी सडक कुकुरहरू|गणेश मन्दिर जानुहोस्|प्राचीन ज्ञान र गुप्त विज्ञान अध्ययन गर्नुहोस्|एकान्त र आत्मनिरीक्षण अभ्यास गर्नुहोस्", "दैनिक ध्यान करें - कम्ति में १५-३० मिनेट|भौतिक परिणामबाट वैराग्य अभ्यास करें|आध्यात्मिक ज्ञान के पहैि लाग्नुहोस्|कुकुर  के खुवाउनुहोस्, विशेष गरी सडक कुकुर|गणेश मन्दिर जानुहोस्|प्राचीन ज्ञान और गुप्त विज्ञान अध्ययन करें|एकान्त और आत्मनिरीक्षण अभ्यास करें"),

    ,

    // Lifestyle Avoid (Delimited by |)
    LIFESTYLE_SUN_AVOID("Avoid disrespecting father or superiors|Avoid excessive ego or arrogance", "बुबा वा वरिष्ठहरूलाई अनादर नगर्नुहोस्|अत्यधिक अहंकार वा घमण्ड नगर्नुहोस्", "बुबा या वरिष्ठ  के अनादर नकरें|अत्यधिक अहंकार या घमण्ड नकरें"),
    ,
    LIFESTYLE_MOON_AVOID("Avoid suppressing emotions|Avoid staying awake late at night", "भावनाहरू दबाउनु हुँदैन|राती अबेरसम्म नबस्नुहोस्", "भावना दबाउनु हुँदैन|राती अबेरसम्म नबस्नुहोस्"),
    ,
    LIFESTYLE_MARS_AVOID("Avoid anger and aggression|Avoid violence and conflicts|Avoid excessive spicy food", "क्रोध र आक्रामकताबाट बच्नुहोस्|हिंसा र द्वन्द्वबाट बच्नुहोस्|अत्यधिक मसालेदार खाना नखानुहोस्", "क्रोध और आक्रामकताबाट बच्नुहोस्|हिंसा और द्वन्द्वबाट बच्नुहोस्|अत्यधिक मसालेदार खाना नखानुहोस्"),
    ,
    LIFESTYLE_MERCURY_AVOID("Avoid lies and gossips|Avoid scattering energy on too many tasks", "झूट र गफबाट बच्नुहोस्|धेरै कामहरूमा ऊर्जा छर्नु हुँदैन", "झूट और गफबाट बच्नुहोस्|धेरै काम में ऊर्जा हैर्नु हुँदैन"),
    ,
    LIFESTYLE_JUPITER_AVOID("Avoid disrespecting teachers or elders|Avoid unethical financial dealings", "शिक्षक वा ठूलाबाडालाई अनादर नगर्नुहोस्|अनैतिक आर्थिक व्यवहारबाट बच्नुहोस्", "शिक्षक या ठूलाबाडा  के अनादर नकरें|अनैतिक आर्थिक व्यवहारबाट बच्नुहोस्"),
    ,
    LIFESTYLE_VENUS_AVOID("Avoid excessive sensual indulgence|Avoid disrespecting spouse or partner", "अत्यधिक कामुक भोगबाट बच्नुहोस्|पति/पत्नी वा साथीलाई अनादर नगर्नुहोस्", "अत्यधिक कामुक भोगबाट बच्नुहोस्|पति/पत्नी या मित्र  के अनादर नकरें"),
    ,
    LIFESTYLE_SATURN_AVOID("Avoid laziness and procrastination|Avoid disrespecting servants or workers|Avoid alcohol and intoxicants", "आलस्य र ढिलासुस्तीबाट बच्नुहोस्|सेवक वा कामदारहरूलाई अनादर नगर्नुहोस्|रक्सी र नशालु पदार्थबाट बच्नुहोस्", "आलस्य और ढिलासुस्तीबाट बच्नुहोस्|सेवक या कामदार  के अनादर नकरें|रक्सी और नशालु पदार्थबाट बच्नुहोस्"),
    ,
    LIFESTYLE_RAHU_AVOID("Avoid deception and manipulation|Avoid excessive ambition|Avoid foreign travel during Rahu Dasha without proper remedies", "धोका र हेरफेरबाट बच्नुहोस्|अत्यधिक महत्त्वाकांक्षाबाट बच्नुहोस्|उचित उपाय बिना राहु दशामा विदेश यात्रा नगर्नुहोस्", "धो के और हेरफेरबाट बच्नुहोस्|अत्यधिक महत्त्वाकांक्षाबाट बच्नुहोस्|उचित उपाय बिना राहु दशा में विदेश यात्रा नकरें"),
    ,
    LIFESTYLE_KETU_AVOID("Avoid excessive attachment to outcomes|Avoid ignoring spiritual calling", "परिणामहरूप्रति अत्यधिक आसक्त नहुनुहोस्|आध्यात्मिक बोलावटलाई बेवास्ता नगर्नुहोस्", "परिणामप्रति अत्यधिक आसक्त नहुनुहोस्|आध्यात्मिक बोलावट  के बेवास्ता नकरें"),

    ,

    // Nakshatra Remedy Methods
    NAK_REMEDY_METHOD_ASHWINI("Worship Ashwini Kumaras, offer white items, avoid surgery on this nakshatra days", "अश्विनी कुमारहरूको पूजा गर्नुहोस्, सेतो वस्तुहरू चढाउनुहोस्, यस नक्षत्रको दिनमा शल्यक्रिया नगर्नुहोस्", "अश्विनी कुमार के पूजा करें, सेतो वस्तु चढाउनुहोस्, इस नक्षत्र के दिन में शल्यक्रिया नकरें"),
    ,
    NAK_REMEDY_METHOD_BHARANI("Worship Yama, practice dharma, donate to funeral services", "यमको पूजा गर्नुहोस्, धर्म अभ्यास गर्नुहोस्, अन्त्येष्टि सेवाहरूमा दान गर्नुहोस्", "यम के पूजा करें, धर्म अभ्यास करें, अन्त्येष्टि सेवा में दान करें"),
    ,
    NAK_REMEDY_METHOD_KRITTIKA("Worship Agni, perform homa/fire rituals, offer ghee", "अग्नीको पूजा गर्नुहोस्, होम/अग्नि अनुष्ठान गर्नुहोस्, घिउ चढाउनुहोस्", "अग्नी के पूजा करें, हैम/अग्नि अनुष्ठान करें, घिउ चढाउनुहोस्"),
    ,
    NAK_REMEDY_METHOD_ROHINI("Worship Brahma, offer white flowers and milk, practice creativity", "ब्रह्माजीको पूजा गर्नुहोस्, सेतो फूल र दूध चढाउनुहोस्, रचनात्मकता अभ्यास गर्नुहोस्", "ब्रह्माजी के पूजा करें, सेतो फूल और दूध चढाउनुहोस्, रचनात्मकता अभ्यास करें"),
    ,
    NAK_REMEDY_METHOD_MRIGASHIRA("Worship Soma/Chandra, offer white items, stay near water", "सोम/चन्द्रको पूजा गर्नुहोस्, सेतो वस्तुहरू चढाउनुहोस्, पानीको नजिक बस्नुहोस्", "सोम/चन्द्र के पूजा करें, सेतो वस्तु चढाउनुहोस्, पानी के नजिक बस्नुहोस्"),
    ,
    NAK_REMEDY_METHOD_ARDRA("Worship Lord Rudra, perform Rudra Abhisheka, offer blue flowers", "भगवान रुद्रको पूजा गर्नुहोस्, रुद्र अभिषेक गर्नुहोस्, नीलो फूल चढाउनुहोस्", "भगवान रुद्र के पूजा करें, रुद्र अभिषेक करें, नीलो फूल चढाउनुहोस्"),
    ,
    NAK_REMEDY_METHOD_PUNARVASU("Worship Goddess Aditi, practice hospitality, help the needy", "देवी अदितिको पूजा गर्नुहोस्, आतिथ्य अभ्यास गर्नुहोस्, खाँचोमा परेकाहरूलाई मद्दत गर्नुहोस्", "देवी अदिति के पूजा करें, आतिथ्य अभ्यास करें, खाँचो में परेका  के सहायता करें"),
    ,
    NAK_REMEDY_METHOD_PUSHYA("Worship Brihaspati, donate to teachers, study scriptures", "बृहस्पतिको पूजा गर्नुहोस्, शिक्षकहरूलाई दान गर्नुहोस्, शास्त्र अध्ययन गर्नुहोस्", "बृहस्पति के पूजा करें, शिक्षक  के दान करें, शास्त्र अध्ययन करें"),
    ,
    NAK_REMEDY_METHOD_ASHLESHA("Worship Naga deities, offer milk to snake idols, avoid harming snakes", "नाग देवताहरूको पूजा गर्नुहोस्, सर्पको मूर्तिमा दूध चढाउनुहोस्, सर्पलाई हानि नगर्नुहोस्", "नाग देवता के पूजा करें, सर्प के मूर्ति में दूध चढाउनुहोस्, सर्प  के हानि नकरें"),
    ,
    NAK_REMEDY_METHOD_MAGHA("Worship ancestors (Pitris), perform Shraddha rituals, respect elders", "पितृहरूको पूजा गर्नुहोस्, श्राद्ध कर्म गर्नुहोस्, ठूलाबाडालाई आदर गर्नुहोस्", "पितृ के पूजा करें, श्राद्ध कर्म करें, ठूलाबाडा  के आदर करें"),
    ,
    NAK_REMEDY_METHOD_PURVA_PHALGUNI("Worship Bhaga, practice generosity, enjoy arts and creativity", "भगको पूजा गर्नुहोस्, उदारता अभ्यास गर्नुहोस्, कला र रचनात्मकताको आनन्द लिनुहोस्", "भग के पूजा करें, उदारता अभ्यास करें, कला और रचनात्मकता के आनन्द लिनुहोस्"),
    ,
    NAK_REMEDY_METHOD_UTTARA_PHALGUNI("Worship Aryaman, honor contracts and promises, practice charity", "अर्यमाको पूजा गर्नुहोस्, सम्झौता र वाचाहरूको सम्मान गर्नुहोस्, दान अभ्यास गर्नुहोस्", "अर्य में के पूजा करें, सम्झौता और वाचा के सम्मान करें, दान अभ्यास करें"),
    ,
    NAK_REMEDY_METHOD_HASTA("Worship Savitar (Sun), practice healing arts, offer sunflowers", "सविता (सूर्य) को पूजा गर्नुहोस्, निको पार्ने कला अभ्यास गर्नुहोस्, सूर्यमुखी फूल चढाउनुहोस्", "सविता (सूर्य)  के पूजा करें, नि के पार्ने कला अभ्यास करें, सूर्यमुखी फूल चढाउनुहोस्"),
    ,
    NAK_REMEDY_METHOD_CHITRA("Worship Vishwakarma, practice craftsmanship, donate tools", "विश्वकर्माको पूजा गर्नुहोस्, शिल्प कौशल अभ्यास गर्नुहोस्, औजारहरू दान गर्नुहोस्", "विश्वकर् में के पूजा करें, शिल्प कौशल अभ्यास करें, औजार दान करें"),
    ,
    NAK_REMEDY_METHOD_SWATI("Worship Vayu, practice pranayama, offer incense", "वायुको पूजा गर्नुहोस्, प्राणायाम अभ्यास गर्नुहोस्, धूप चढाउनुहोस्", "वायु के पूजा करें, प्राणायाम अभ्यास करें, धूप चढाउनुहोस्"),
    ,
    NAK_REMEDY_METHOD_VISHAKHA("Worship Indra-Agni, practice determination, perform fire rituals", "इन्द्र-अग्नीको पूजा गर्नुहोस्, दृढ संकल्प अभ्यास गर्नुहोस्, अग्नि अनुष्ठान गर्नुहोस्", "इन्द्र-अग्नी के पूजा करें, दृढ संकल्प अभ्यास करें, अग्नि अनुष्ठान करें"),
    ,
    NAK_REMEDY_METHOD_ANURADHA("Worship Mitra, cultivate friendships, practice devotion", "मित्रको पूजा गर्नुहोस्, मित्रता बढाउनुहोस्, भक्ति अभ्यास गर्नुहोस्", "मित्र के पूजा करें, मित्रता बढाउनुहोस्, भक्ति अभ्यास करें"),
    ,
    NAK_REMEDY_METHOD_JYESHTHA("Worship Indra, develop leadership, protect the weak", "इन्द्रको पूजा गर्नुहोस्, नेतृत्व विकास गर्नुहोस्, कमजोरलाई रक्षा गर्नुहोस्", "इन्द्र के पूजा करें, नेतृत्व विकास करें, कमजोर  के रक्षा करें"),
    ,
    NAK_REMEDY_METHOD_MULA("Worship Goddess Nirriti/Kali, practice detachment, donate roots/herbs", "देवी निर्ऋति/कालीको पूजा गर्नुहोस्, वैराग्य अभ्यास गर्नुहोस्, जरा/जडीबुटी दान गर्नुहोस्", "देवी निर्ऋति/काली के पूजा करें, वैराग्य अभ्यास करें, जरा/जडीबुटी दान करें"),
    ,
    NAK_REMEDY_METHOD_PURVA_ASHADHA("Worship Apas (water deities), stay near water, practice purification", "आप (जल देवता) को पूजा गर्नुहोस्, पानीको नजिक बस्नुहोस्, शुद्धीकरण अभ्यास गर्नुहोस्", "आप (जल देवता)  के पूजा करें, पानी के नजिक बस्नुहोस्, शुद्धीकरण अभ्यास करें"),
    ,
    NAK_REMEDY_METHOD_UTTARA_ASHADHA("Worship Vishvadevas, practice universal service, be helpful to all", "विश्वदेवहरूको पूजा गर्नुहोस्, विश्वव्यापी सेवा अभ्यास गर्नुहोस्, सबैलाई सहयोगी हुनुहोस्", "विश्वदेव के पूजा करें, विश्वव्यापी सेवा अभ्यास करें, सभी  के सहयहगी हुनुहोस्"),
    ,
    NAK_REMEDY_METHOD_SHRAVANA("Worship Lord Vishnu, practice listening and learning, chant Vishnu mantras", "भगवान विष्णुको पूजा गर्नुहोस्, सुन्ने र सिक्ने अभ्यास गर्नुहोस्, विष्णु मन्त्र जप गर्नुहोस्", "भगवान विष्णु के पूजा करें, सुन्ने और सिक्ने अभ्यास करें, विष्णु मन्त्र जप करें"),
    ,
    NAK_REMEDY_METHOD_DHANISHTHA("Worship Vasus, practice music, donate musical instruments", "वसुहरूको पूजा गर्नुहोस्, संगीत अभ्यास गर्नुहोस्, वाद्ययन्त्र दान गर्नुहोस्", "वसु के पूजा करें, संगीत अभ्यास करें, वाद्ययन्त्र दान करें"),
    ,
    NAK_REMEDY_METHOD_SHATABHISHA("Worship Varuna, practice healing, work with herbs and medicines", "वरुणको पूजा गर्नुहोस्, निको पार्ने अभ्यास गर्नुहोस्, जडीबुटी र औषधिहरूसँग काम गर्नुहोस्", "वरुण के पूजा करें, नि के पार्ने अभ्यास करें, जडीबुटी और औषधिसँग काम करें"),
    ,
    NAK_REMEDY_METHOD_PURVA_BHADRAPADA("Worship Aja Ekapad, practice yoga and meditation, seek spiritual liberation", "अज एकपादको पूजा गर्नुहोस्, योग र ध्यान अभ्यास गर्नुहोस्, आध्यात्मिक मुक्ति खोज्नुहोस्", "अज एकपाद के पूजा करें, यहग और ध्यान अभ्यास करें, आध्यात्मिक मुक्ति खोज्नुहोस्"),
    ,
    NAK_REMEDY_METHOD_UTTARA_BHADRAPADA("Worship Ahir Budhnya, practice deep meditation, seek wisdom", "अहिर्बुध्न्यको पूजा गर्नुहोस्, गहिरो ध्यान अभ्यास गर्नुहोस्, ज्ञान खोज्नुहोस्", "अहिर्बुध्न्य के पूजा करें, गहिरो ध्यान अभ्यास करें, ज्ञान खोज्नुहोस्"),
    ,
    NAK_REMEDY_METHOD_REVATI("Worship Pushan, practice guidance and protection, help travelers", "पुषनको पूजा गर्नुहोस्, मार्गदर्शन र सुरक्षा अभ्यास गर्नुहोस्, यात्रीहरूलाई मद्दत गर्नुहोस्", "पुषन के पूजा करें, मार्गदर्शन और सुरक्षा अभ्यास करें, यात्री  के सहायता करें"),

    ,

    // Analysis
    DIGNITY_IN_SIGN("%s in %s", "%s %s मा", "%s %s में"),
    ,
    DIGNITY_EXALTED("(Exalted)", "(उच्च)", "(उच्च)"),
    ,
    DIGNITY_DEBILITATED("(Debilitated)", "(नीच)", "(नीच)"),
    ,
    DIGNITY_MOOLTRIKONA("(Mooltrikona)", "(मूलत्रिकोण)", "(मूलत्रिकोण)"),
    ,
    DIGNITY_OWN("(Own Sign)", "(स्वराशि)", "(स्वराशि)"),
    ,
    DIGNITY_FRIEND("(Friendly)", "(मित्र)", "(मित्र)"),
    ,
    DIGNITY_ENEMY("(Enemy)", "(शत्रु)", "(शत्रु)"),
    ,
    DIGNITY_NEUTRAL("(Neutral)", "(सम)", "(सम)"),
    ,
    DIGNITY_RETRO("Retrograde", "वक्री", "वक्री"),
    ,
    DIGNITY_COMBUST("Combust", "अस्त", "अस्त"),


    ,


    ANALYSIS_DEBILITATED_DEEP("Deeply debilitated at %.1f° %s", "%.1f° %s मा गहिरो नीच", "%.1f° %s में गहिरो नीच"),
    ,
    ANALYSIS_DEBILITATED("Debilitated in %s", "%s मा नीच", "%s में नीच"),
    ,
    ANALYSIS_EXALTED_DEEP("Deeply exalted at %.1f° %s", "%.1f° %s मा गहिरो उच्च", "%.1f° %s में गहिरो उच्च"),
    ,
    ANALYSIS_EXALTED("Exalted in %s", "%s मा उच्च", "%s में उच्च"),
    ,
    ANALYSIS_NEECHA_BHANGA("Neecha Bhanga Raja Yoga - Debilitation cancelled", "नीच भङ्ग राजयोग - नीचता रद्द", "नीच भङ्ग राजयहग - नीचता रद्द"),
    ,
    ANALYSIS_OWN_SIGN("In own sign %s", "स्वराशि %s मा", "स्वराशि %s में"),
    ,
    ANALYSIS_MOOLTRIKONA("In Mooltrikona", "मूलत्रिकोणमा", "मूलत्रिकोण में"),
    ,
    ANALYSIS_FRIEND_SIGN("In friend's sign (%s)", "मित्र राशि (%s) मा", "मित्र राशि (%s) में"),
    ,
    ANALYSIS_ENEMY_SIGN("In enemy sign (%s)", "शत्रु राशि (%s) मा", "शत्रु राशि (%s) में"),
    ,
    ANALYSIS_KENDRA("Placed in Kendra (angle) house %d", "केन्द्र भाव %d मा स्थित", "केन्द्र भाव %d में स्थित"),
    ,
    ANALYSIS_TRIKONA("Placed in Trikona (trine) house %d", "त्रिकोण भाव %d मा स्थित", "त्रिकोण भाव %d में स्थित"),
    ,
    ANALYSIS_DUSTHANA("Placed in Dusthana house %d", "दुस्थान भाव %d मा स्थित", "दुस्थान भाव %d में स्थित"),
    ,
    ANALYSIS_WEALTH("Placed in wealth house %d", "धन भाव %d मा स्थित", "धन भाव %d में स्थित"),
    ,
    ANALYSIS_RETRO_STRONG("Retrograde (strengthened)", "वक्री (बलियो)", "वक्री (बलियह)"),
    ,
    ANALYSIS_RETRO_REVIEW("Retrograde (review communication matters)", "वक्री (सञ्चार विषयमा समीक्षा गर्नुहोस्)", "वक्री (सञ्चार विषय में समीक्षा करें)"),
    ,
    ANALYSIS_RETRO_INTERNAL("Retrograde (internalized energy)", "वक्री (आन्तरिक ऊर्जा)", "वक्री (आन्तरिक ऊर्जा)"),
    ,
    ANALYSIS_COMBUST("Combust by Sun (%s weakened)", "सूर्यद्वारा अस्त (%s कमजोर)", "सूर्यद्वारा अस्त (%s कमजोर)"),
    ,
    ANALYSIS_CONJUNCT_MALEFICS("Conjunct malefics: %s", "पाप ग्रह युति: %s", "पाप ग्रह युति: %s"),
    ,
    ANALYSIS_CONJUNCT_BENEFICS("Conjunct benefics: %s", "शुभ ग्रह युति: %s", "शुभ ग्रह युति: %s"),
    ,
    ANALYSIS_ASPECT_JUPITER("Aspected by Jupiter (protected)", "बृहस्पतिद्वारा दृष्ट (सुरक्षित)", "बृहस्पतिद्वारा दृष्ट (सुरक्षित)"),
    ,
    ANALYSIS_ASPECT_SATURN("Aspected by Saturn", "शनिद्वारा दृष्ट", "शनिद्वारा दृष्ट"),
    ,
    ANALYSIS_GANDANTA("In Gandanta (karmic knot at water-fire sign junction)", "गण्डान्तमा (जल-अग्नि राशि सन्धिमा कार्मिक गाँठो)", "गण्डान्त में (जल-अग्नि राशि सन्धि में कार्मिक गाँठो)"),
    ,
    ANALYSIS_MRITYU_BHAGA("In Mrityu Bhaga (critical degree)", "मृत्यु भागमा (महत्त्वपूर्ण डिग्री)", "मृत्यु भाग में (महत्त्वपूर्ण डिग्री)"),
    ,
    ANALYSIS_PUSHKARA("In Pushkara Navamsha (auspicious degree)", "पुष्कर नवरांशमा (शुभ डिग्री)", "पुष्कर नवरांश में (शुभ डिग्री)"),
    ,
    ANALYSIS_YOGAKARAKA("Yogakaraka planet for %s Lagna", "%s लग्नको लागि योगकारक ग्रह", "%s लग्न के लिए यहगकारक ग्रह"),
    ,
    ANALYSIS_MOON_DARK("Dark Moon (Krishna Paksha) - emotionally challenged", "कृष्ण पक्षको चन्द्रमा - भावनात्मक चुनौती", "कृष्ण पक्ष के चन्द्र में - भावनात्मक चुनौती"),
    ,
    ANALYSIS_MOON_BRIGHT("Bright Moon (Shukla Paksha)", "शुक्ल पक्षको चन्द्रमा", "शुक्ल पक्ष के चन्द्र में"),

    ,
    
    // New keys for improved localization
    GEM_DURATION_CONTINUOUS("Continuous wear recommended", "निरन्तर लगाउन सिफारिस गरिएको", "निरन्तर लगाउन सिफारिस गरिए के"),
    ,
    MANTRA_TIMING_WAXING("during Shukla Paksha", "शुक्ल पक्षमा", "शुक्ल पक्ष में"),
    ,
    CHARITY_TIMING_MORNING("Morning", "बिहान", "बिहान"),
    ,
    CHARITY_TIMING_EVENING("Evening", "साँझ", "साँझ"),
    ,
    CHARITY_TIMING_NIGHT("Night", "राती", "राती"),
    ,
    CHARITY_TIMING_BEFORE_SUNSET("Before sunset", "सूर्यास्त अघि", "सूर्यास्त अघि"),
    ,
    CHARITY_TIMING_BEFORE_SUNRISE_AFTER_SUNSET("Before sunrise or after sunset", "सूर्योदय अघि वा सूर्यास्त पछि", "सूर्यहदय अघि या सूर्यास्त पहैि"),
    ,
    FASTING_TIMING_SUNRISE_SUNSET("Sunrise to Sunset", "सूर्योदयदेखि सूर्यास्तसम्म", "सूर्यहदयदेखि सूर्यास्तसम्म"),
    ,
    RUDRAKSHA_DESC("Wear %d mukhi Rudraksha to balance %s energy. Deity: %s.", "%s ऊर्जा सन्तुलन गर्न %d मुखी रुद्राक्ष लगाउनुहोस्। देवता: %s।", "%s ऊर्जा सन्तुलन करने %d मुखी रुद्राक्ष लगाउनुहोस्। देवता: %s।"),

    ,

    // Deities for Rudraksha/Nakshatra
    DEITY_ASHWINI_KUMARAS("Ashwini Kumaras", "अश्विनी कुमार", "अश्विनी कुमार"),
    ,
    DEITY_YAMA("Yama", "यम", "यम"),
    ,
    DEITY_AGNI("Agni", "अग्नि", "अग्नि"),
    ,
    DEITY_BRAHMA("Brahma", "ब्रह्मा", "ब्रह् में"),
    ,
    DEITY_SOMA("Soma/Chandra", "सोम/चन्द्र", "सोम/चन्द्र"),
    ,
    DEITY_RUDRA("Rudra", "रुद्र", "रुद्र"),
    ,
    DEITY_ADITI("Aditi", "अदिति", "अदिति"),
    ,
    DEITY_BRIHASPATI("Brihaspati", "बृहस्पति", "बृहस्पति"),
    ,
    DEITY_NAGAS("Nagas", "नाग", "नाग"),
    ,
    DEITY_PITRIS("Pitris", "पितृ", "पितृ"),
    ,
    DEITY_BHAGA("Bhaga", "भग", "भग"),
    ,
    DEITY_ARYAMAN("Aryaman", "अर्यमा", "अर्य में"),
    ,
    DEITY_SAVITAR("Savitar", "सविता", "सविता"),
    ,
    DEITY_VISHWAKARMA("Vishwakarma", "विश्वकर्मा", "विश्वकर् में"),
    ,
    DEITY_VAYU("Vayu", "वायु", "वायु"),
    ,
    DEITY_INDRA_AGNI("Indra-Agni", "इन्द्राग्नी", "इन्द्राग्नी"),
    ,
    DEITY_MITRA("Mitra", "मित्र", "मित्र"),
    ,
    DEITY_INDRA("Indra", "इन्द्र", "इन्द्र"),
    ,
    DEITY_KALI("Kali", "काली", "काली"),
    ,
    DEITY_APAS("Apas", "आप", "आप"),
    ,
    DEITY_VISHVADEVAS("Vishvadevas", "विश्वेदेव", "विश्वेदेव"),
    ,
    DEITY_VISHNU("Vishnu", "विष्णु", "विष्णु"),
    ,
    DEITY_VASUS("Vasus", "वसु", "वसु"),
    ,
    DEITY_VARUNA("Varuna", "वरुण", "वरुण"),
    ,
    DEITY_AJA_EKAPAD("Aja Ekapad", "अज एकपाद", "अज एकपाद"),
    ,
    DEITY_AHIR_BUDHNYA("Ahir Budhnya", "अहिर्बुध्न्य", "अहिर्बुध्न्य"),
    ,
    DEITY_PUSHAN("Pushan", "पूषा", "पूषा"),

    ,

    // Default Labels if null
    LABEL_UNKNOWN("Unknown", "अज्ञात", "अज्ञात");
    
    fun getKey(): String = name
}
