package com.astro.storm.core.common

enum class StringKeyPrashnaPart2(override val en: String, override val ne: String) : StringKeyInterface {
    PRASHNA_TOPIC_FEET("Feet", "गोडा"),
    PRASHNA_TOPIC_FOOD("Food", "भोजन"),
    PRASHNA_TOPIC_FOREIGN_LANDS("Foreign lands", "विदेशी भूमि"),
    PRASHNA_TOPIC_FOREIGN_TRAVEL("Foreign travel", "विदेश यात्रा"),
    PRASHNA_TOPIC_FORTUNE("Fortune", "सुभाग्य"),
    PRASHNA_TOPIC_FRIENDS("Friends", "साथीहरू"),
    PRASHNA_TOPIC_FULFILLMENT("Fulfillment", "पूर्णता"),
    PRASHNA_TOPIC_GAINS("Gains", "लाभ"),
    PRASHNA_TOPIC_GOVERNMENT("Government", "सरकार"),
    PRASHNA_TOPIC_GURU("Guru", "गुरु"),
    PRASHNA_TOPIC_HAPPINESS("Happiness", "सुख"),
    PRASHNA_TOPIC_HEALTH("Health", "स्वास्थ्य"),
    PRASHNA_TOPIC_HIDDEN("Hidden things", "लुकेका कुरा"),
    PRASHNA_TOPIC_HIGHER_LEARNING("Higher learning", "उच्च शिक्षा"),
    PRASHNA_TOPIC_HOME("Home", "घर"),
    PRASHNA_TOPIC_HOSPITAL("Hospital", "अस्पताल"),
    PRASHNA_TOPIC_INCOME("Income", "आय"),
    PRASHNA_TOPIC_INHERITANCE("Inheritance", "विरासत"),
    PRASHNA_TOPIC_INTELLIGENCE("Intelligence", "बुद्धि"),
    PRASHNA_TOPIC_INTESTINES("Intestines", "आन्द्रा"),
    PRASHNA_TOPIC_KIDNEYS("Kidneys", "मृगौला"),
    PRASHNA_TOPIC_KNEES("Knees", "घुँडा"),
    PRASHNA_TOPIC_LIBERATION("Liberation", "मुक्ति"),
    PRASHNA_TOPIC_LIFE_FORCE("Life force", "जीवन शक्ति"),
    PRASHNA_TOPIC_LONG_TRAVEL("Long journeys", "लामो यात्रा"),
    PRASHNA_TOPIC_LOSSES("Losses", "हानि"),
    PRASHNA_TOPIC_LUCK("Luck", "भाग्य"),
    PRASHNA_TOPIC_MANTRAS("Mantras", "मन्त्र"),
    PRASHNA_TOPIC_MARRIAGE("Marriage", "विवाह"),
    PRASHNA_TOPIC_MOTHER("Mother", "आमा"),
    PRASHNA_TOPIC_MYSTERY("Mystery", "रहस्य"),
    PRASHNA_TOPIC_NEIGHBORS("Neighbors", "छिमेकी"),
    PRASHNA_TOPIC_OBSTACLES("Obstacles", "बाधा"),
    PRASHNA_TOPIC_OCCULT("Occult", "तन्त्र-मन्त्र"),
    PRASHNA_TOPIC_OPPONENT("Opponent", "विपक्षी"),
    PRASHNA_TOPIC_PARTNERSHIP("Partnership", "साझेदारी"),
    PRASHNA_TOPIC_PAST_MERIT("Past merit", "पूर्व पुण्य"),
    PRASHNA_TOPIC_PHYSICAL("Physical appearance", "शारीरिक बनावट"),
    PRASHNA_TOPIC_POSSESSIONS("Possessions", "सम्पत्ति"),
    PRASHNA_TOPIC_PROPERTY("Property", "सम्पत्ति"),
    PRASHNA_TOPIC_PUBLIC_LIFE("Public life", "सार्वजनिक जीवन"),
    PRASHNA_TOPIC_QUERENT("The querent", "प्रश्नकर्ता"),
    PRASHNA_TOPIC_RECOVERY("Recovery from illness", "बिरामीबाट सुधार"),
    PRASHNA_TOPIC_RELIGION("Religion", "धर्म"),
    PRASHNA_TOPIC_REPRODUCTIVE("Reproductive organs", "प्रजनन अंग"),
    PRASHNA_TOPIC_RESOURCES("Resources", "स्रोत"),
    PRASHNA_TOPIC_RIGHT_EAR("Right ear", "दायाँ कान"),
    PRASHNA_TOPIC_RIGHT_EYE("Right eye", "दायाँ आँखा"),
    PRASHNA_TOPIC_ROMANCE("Romance", "रोमान्स"),
    PRASHNA_TOPIC_SELF("Self", "स्वयम्"),
    PRASHNA_TOPIC_SERVICE("Service", "सेवा"),
    PRASHNA_TOPIC_SEXUAL("Sexual matters", "यौन मामिला"),
    PRASHNA_TOPIC_SHORT_TRAVEL("Short journeys", "छोटो यात्रा"),
    PRASHNA_TOPIC_SIBLINGS("Siblings", "भाइबहिनी"),
    PRASHNA_TOPIC_SKILLS("Skills", "सीप"),
    PRASHNA_TOPIC_SLEEP("Sleep", "निद्रा"),
    PRASHNA_TOPIC_SPECULATION("Speculation", "सट्टा"),
    PRASHNA_TOPIC_SPEECH("Speech", "वाणी"),
    PRASHNA_TOPIC_STATUS("Status", "स्थिति"),
    PRASHNA_TOPIC_STOMACH("Stomach", "पेट"),
    PRASHNA_TOPIC_SUCCESS("General success", "सामान्य सफलता"),
    PRASHNA_TOPIC_THIGHS("Thighs", "तिघ्रा"),
    PRASHNA_TOPIC_TRANSFORMATION("Transformation", "रूपान्तरण"),
    PRASHNA_TOPIC_TREASURE("Buried treasure", "गाडिएको धन"),
    PRASHNA_TOPIC_UNCLE("Maternal uncle", "मामा"),
    PRASHNA_TOPIC_VEHICLES("Vehicles", "सवारी साधन"),
    PRASHNA_TOPIC_WEALTH("Wealth", "धन"),
    PRASHNA_TOPIC_WISHES("Wishes", "इच्छाहरू"),
    PRASHNA_UNCERTAIN("Uncertain", "अनिश्चित"),
    PRASHNA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    PRASHNA_VEDIC_REF("Vedic Reference: Prashna Marga, Tajika Neelakanthi", "वैदिक सन्दर्भ: प्रश्न मार्ग, ताजिक नीलकण्ठी"),
    PRASHNA_VERDICT_LIKELY_NO("Likely No - Difficulties Indicated", "सम्भवतः होइन - कठिनाइहरू संकेत"),
    PRASHNA_VERDICT_LIKELY_YES("Likely Yes - Conditions Apply", "सम्भवतः हो - सर्तहरू लागू"),
    PRASHNA_VERDICT_NO("No - Unfavorable Outcome", "होइन - प्रतिकूल परिणाम"),
    PRASHNA_VERDICT_STRONGLY_NO("Strongly No - Failure Indicated", "निश्चित होइन - असफलताको संकेत"),
    PRASHNA_VERDICT_STRONGLY_YES("Strongly Yes - Success Indicated", "निश्चित हो - सफलताको संकेत"),
    PRASHNA_VERDICT_TIMING_DEPENDENT("Timing Dependent - Wait Indicated", "समय निर्भर - प्रतीक्षा गर्नुहोस्"),
    PRASHNA_VERDICT_UNCERTAIN("Uncertain - Mixed Indications", "अनिश्चित - मिश्रित संकेत"),
    PRASHNA_VERDICT_YES("Yes - Favorable Outcome", "हो - अनुकूल परिणाम"),
    PRASHNA_VERY_FAR("Very Far", "धेरै टाढा"),
    PRASHNA_WEEKS("Weeks", "हप्ताहरू"),
    PRASHNA_WHEN("When Will It Happen", "कहिले हुनेछ"),
    PRASHNA_WILL_COMPLETE("Will Complete", "पूरा हुनेछ"),
    PRASHNA_WILL_NOT_COMPLETE("Will Not Complete", "पूरा हुनेछैन"),
    PRASHNA_WILL_RETURN("Will Return", "फर्कनेछ"),
    PRASHNA_YAMAYA("Yamaya (Prohibition)", "यमया (निषेध)"),
    PRASHNA_YAMAYA_DESC("Another planet blocks the application", "अर्को ग्रहले आवेदन रोक्छ"),
    PRASHNA_YEARS("Years", "वर्षहरू"),
    PRASHNA_YES("Yes", "हो"),
    PRASHNA_YES_NO("Yes/No Probability", "हो/होइन सम्भावना"),
    PRASHNA_YES_PROBABILITY("Yes Probability", "हो सम्भावना"),
    PRASHNA_YOGAS_TITLE("Special Yogas Present", "विशेष योगहरू"),
    PRASHNA_YOGA_DHURUFA_DESC("Moon in cadent house without strength", "चन्द्रमा बल बिना आपोक्लिम भावमा"),
    PRASHNA_YOGA_DHURUFA_INTERP("Failure is indicated. Best to abandon the matter.", "असफलताको संकेत छ। विषय छोड्नु नै राम्रो हुनेछ।"),
    PRASHNA_YOGA_DHURUFA_NAME("Dhurufa Yoga", "धुरुफ योग"),
    PRASHNA_YOGA_GAIRI_KAMBOOLA_DESC("Moon weak though in angular house", "चन्द्रमा केन्द्र भावमा भए पनि कमजोर छ"),
    PRASHNA_YOGA_GAIRI_KAMBOOLA_INTERP("Initial hopes but eventual disappointment. Success after delays.", "सुरुमा आशा तर अन्तमा निराशा। ढिलाइ पछि सफलता।"),
    PRASHNA_YOGA_GAIRI_KAMBOOLA_NAME("Gairi Kamboola", "गैर कम्बूल"),
    PRASHNA_YOGA_GANDANTA_DESC("Moon at junction point between water and fire signs", "चन्द्रमा जल र अग्नि राशि बीचको सन्धि बिन्दुमा"),
    PRASHNA_YOGA_GANDANTA_INTERP("Danger, crisis, or difficult transformation indicated.", "खतरा, संकट वा कठिन रूपान्तरणको संकेत।"),
    PRASHNA_YOGA_GANDANTA_NAME("Gandanta Position", "गण्डान्त स्थिति"),
    PRASHNA_YOGA_ITHASALA_DESC("Moon is applying to aspect with relevant significator", "चन्द्रमा सम्बन्धित भावेशसँग दृष्टिको लागि अघि बढ्दैछ"),
    PRASHNA_YOGA_ITHASALA_INTERP("Success in the matter is indicated. The event will come to fruition.", "विषयमा सफलताको संकेत छ। घटना सफल हुनेछ।"),
    PRASHNA_YOGA_ITHASALA_NAME("Ithasala Yoga", "इत्थशाल योग"),
    PRASHNA_YOGA_KAMBOOLA_DESC("Moon in angular house with lord", "चन्द्रमा भावेशसँग केन्द्र भावमा"),
    PRASHNA_YOGA_KAMBOOLA_INTERP("Very favorable for success. Quick positive results expected.", "सफलताको लागि धेरै अनुकूल। छिटो सकारात्मक नतिजाको अपेक्षा।"),
    PRASHNA_YOGA_KAMBOOLA_NAME("Kamboola Yoga", "कम्बूल योग"),
    PRASHNA_YOGA_MANAOU_DESC("Third planet prohibits completion", "तेस्रो ग्रहले पूर्णतामा अवरोध गर्दछ"),
    PRASHNA_YOGA_MANAOU_INTERP("Third party or external factor will prevent success.", "तेस्रो पक्ष वा बाह्य कारकले सफलतामा अवरोध गर्नेछ।"),
    PRASHNA_YOGA_MANAOU_NAME("Manaou Yoga", "मनाऊ योग"),
    PRASHNA_YOGA_MUSARIPHA_DESC("Moon is separating from significant aspect", "चन्द्रमा महत्त्वपूर्ण दृष्टिबाट टाढा हुँदैछ"),
    PRASHNA_YOGA_MUSARIPHA_INTERP("The matter has already passed or opportunity was missed.", "विषय पहिले नै बितिसकेको छ वा अवसर गुमेको छ।"),
    PRASHNA_YOGA_MUSARIPHA_NAME("Musaripha Yoga", "मुसरिफ योग"),
    PRASHNA_YOGA_NAKTA_DESC("Transfer of light between planets", "ग्रहहरू बीच प्रकाशको हस्तान्तरण"),
    PRASHNA_YOGA_NAKTA_INTERP("Success through an intermediary or third party assistance.", "मध्यस्थ वा तेस्रो पक्षको सहयोग मार्फत सफलता।"),
    PRASHNA_YOGA_NAKTA_NAME("Nakta Yoga", "नक्त योग"),
    PRASHNA_YOGA_PUSHKARA_DESC("Moon in auspicious navamsha division", "चन्द्रमा शुभ नवांश विभाजनमा"),
    PRASHNA_YOGA_PUSHKARA_INTERP("Excellent omen. The matter will have nourishing, supportive outcomes.", "उत्कृष्ट शकुन। विषयमा पोषक, सहयोगी नतिजाहरू प्राप्त हुनेछन्।"),
    PRASHNA_YOGA_PUSHKARA_NAME("Pushkara Navamsha", "पुष्कर नवांश"),
    PRASHNA_YOGA_SYMBOL_NEGATIVE("- %s: %s", "- %s: %s"),
    PRASHNA_YOGA_SYMBOL_POSITIVE("+ %s: %s", "+ %s: %s"),
    PRASHNA_YOGA_UNION_DESC("Moon with Lagna Lord", "चन्द्रमा लग्न स्वामीसँग"),
    PRASHNA_YOGA_UNION_INTERP("Strong personal involvement and favorable outcome.", "बलियो व्यक्तिगत संलग्नता र अनुकूल परिणाम।"),
    PRASHNA_YOGA_UNION_NAME("Lagna-Moon Union", "लग्न-चन्द्र युति"),
    PRASHNA_YOUR_QUESTION("Your Question", "तपाईंको प्रश्न")
}
