package com.astro.storm.core.common
enum class StringKeyPrashnaPart1(override val en: String, override val ne: String) : StringKeyInterface {
PRASHNA_HOUSE_1_NAME("Lagna/Querent", "लग्न/प्रश्नकर्ता"),
PRASHNA_HOUSE_2_NAME("Dhana", "धन"),
PRASHNA_HOUSE_3_NAME("Sahaja", "सहज"),
PRASHNA_HOUSE_4_NAME("Sukha", "सुख"),
PRASHNA_HOUSE_5_NAME("Putra", "पुत्र"),
PRASHNA_HOUSE_6_NAME("Ripu", "रिपु"),
PRASHNA_HOUSE_7_NAME("Kalatra", "कलत्र"),
PRASHNA_HOUSE_8_NAME("Ayu", "आयु"),
PRASHNA_HOUSE_9_NAME("Dharma", "धर्म"),
PRASHNA_HOUSE_10_NAME("Karma", "कर्म"),
PRASHNA_HOUSE_11_NAME("Labha", "लाभ"),
PRASHNA_HOUSE_12_NAME("Vyaya", "व्यय"),
    PRASHNA_MOOK("Mook (Dumb)", "Mook (Dumb)"),
PRASHNA_ARUDHA("Arudha Lagna", "आरूढ लग्न"),
PRASHNA_CAT_YES_NO("Yes/No", "हो/होइन"),
PRASHNA_CAT_YES_NO_DESC("Simple yes or no questions", "साधारण हो वा होइन प्रश्नहरू"),
PRASHNA_CAT_CAREER("Career", "क्यारियर"),
PRASHNA_CAT_CAREER_DESC("Job, profession, and career-related questions", "जागिर, पेशा र क्यारियर सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_MARRIAGE("Marriage", "विवाह"),
PRASHNA_CAT_MARRIAGE_DESC("Marriage and spouse-related questions", "विवाह र जीवनसाथी सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_CHILDREN("Children", "सन्तान"),
PRASHNA_CAT_CHILDREN_DESC("Questions about children and progeny", "सन्तान र सन्ततिका बारेमा प्रश्नहरू"),
PRASHNA_CAT_HEALTH("Health", "स्वास्थ्य"),
PRASHNA_CAT_HEALTH_DESC("Health and illness-related questions", "स्वास्थ्य र रोग सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_WEALTH("Wealth", "धन-सम्पत्ति"),
PRASHNA_CAT_WEALTH_DESC("Financial and wealth-related questions", "आर्थिक र धन-सम्पत्ति सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_PROPERTY("Property", "सम्पत्ति"),
PRASHNA_CAT_PROPERTY_DESC("Real estate and property questions", "जग्गा-जमिन र सम्पत्ति सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_TRAVEL("Travel", "यात्रा"),
PRASHNA_CAT_TRAVEL_DESC("Journey and travel-related questions", "यात्रा सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_EDUCATION("Education", "शिक्षा"),
PRASHNA_CAT_EDUCATION_DESC("Studies and educational questions", "अध्ययन र शैक्षिक प्रश्नहरू"),
PRASHNA_CAT_LEGAL("Legal", "कानुनी"),
PRASHNA_CAT_LEGAL_DESC("Court cases and legal matters", "मुद्दा-मामिला र कानुनी विषयहरू"),
PRASHNA_CAT_LOST_OBJECT("Lost Object", "हराएको वस्तु"),
PRASHNA_CAT_LOST_OBJECT_DESC("Finding lost or stolen items", "हराएको वा चोरी भएको वस्तु खोज्ने"),
PRASHNA_CAT_RELATIONSHIP("Relationship", "सम्बन्ध"),
PRASHNA_CAT_RELATIONSHIP_DESC("Love and relationship questions", "प्रेम र सम्बन्ध सम्बन्धी प्रश्नहरू"),
PRASHNA_CAT_BUSINESS("Business", "व्यापार"),
PRASHNA_CAT_BUSINESS_DESC("Business partnership and deals", "व्यापार साझेदारी र सौदाहरू"),
PRASHNA_CAT_SPIRITUAL("Spiritual", "आध्यात्मिक"),
PRASHNA_CAT_SPIRITUAL_DESC("Spiritual and religious questions", "आध्यात्मिक र धार्मिक प्रश्नहरू"),
PRASHNA_CAT_GENERAL("General", "सामान्य"),
PRASHNA_CAT_GENERAL_DESC("General questions and queries", "सामान्य प्रश्नहरू"),
PRASHNA_TATTVA_FIRE("Agni/Fire", "अग्नि"),
PRASHNA_TATTVA_FIRE_SIGNS("Aries, Leo, Sagittarius", "मेष, सिंह, धनु"),
PRASHNA_TATTVA_EARTH("Prithvi/Earth", "पृथ्वी"),
PRASHNA_TATTVA_EARTH_SIGNS("Taurus, Virgo, Capricorn", "वृष, कन्या, मकर"),
PRASHNA_TATTVA_AIR("Vayu/Air", "वायु"),
PRASHNA_TATTVA_AIR_SIGNS("Gemini, Libra, Aquarius", "मिथुन, तुला, कुम्भ"),
PRASHNA_TATTVA_WATER("Jala/Water", "जल"),
PRASHNA_TATTVA_WATER_SIGNS("Cancer, Scorpio, Pisces", "कर्कट, वृश्चिक, मीन"),
PRASHNA_TATTVA_ETHER("Akasha/Ether", "आकाश"),
PRASHNA_TATTVA_ETHER_SIGNS("None - represents void/space", "कुनै पनि होइन - शून्य/अन्तरिक्ष"),
PRASHNA_TIMING_HOURS("Hours", "घण्टा"),
PRASHNA_TIMING_DAYS("Days", "दिन"),
PRASHNA_TIMING_WEEKS("Weeks", "हप्ता"),
PRASHNA_TIMING_MONTHS("Months", "महिना"),
PRASHNA_TIMING_YEARS("Years", "वर्ष"),
PRASHNA_VERDICT_STRONGLY_YES("Strongly Yes - Success Indicated", "निश्चित हो - सफलताको संकेत"),
PRASHNA_VERDICT_YES("Yes - Favorable Outcome", "हो - अनुकूल परिणाम"),
PRASHNA_VERDICT_LIKELY_YES("Likely Yes - Conditions Apply", "सम्भवतः हो - सर्तहरू लागू"),
PRASHNA_VERDICT_UNCERTAIN("Uncertain - Mixed Indications", "अनिश्चित - मिश्रित संकेत"),
PRASHNA_VERDICT_LIKELY_NO("Likely No - Difficulties Indicated", "सम्भवतः होइन - कठिनाइहरू संकेत"),
PRASHNA_VERDICT_NO("No - Unfavorable Outcome", "होइन - प्रतिकूल परिणाम"),
PRASHNA_VERDICT_STRONGLY_NO("Strongly No - Failure Indicated", "निश्चित होइन - असफलताको संकेत"),
PRASHNA_VERDICT_TIMING_DEPENDENT("Timing Dependent - Wait Indicated", "समय निर्भर - प्रतीक्षा गर्नुहोस्"),
PRASHNA_CERTAINTY_VERY_HIGH("Very High Certainty", "अत्यधिक निश्चितता"),
PRASHNA_CERTAINTY_HIGH("High Certainty", "उच्च निश्चितता"),
PRASHNA_CERTAINTY_MODERATE("Moderate Certainty", "मध्यम निश्चितता"),
PRASHNA_CERTAINTY_LOW("Low Certainty", "न्यून निश्चितता"),
PRASHNA_CERTAINTY_VERY_LOW("Very Low Certainty", "अति न्यून निश्चितता"),
PRASHNA_MOON_EXCELLENT("Excellent", "उत्कृष्ट"),
PRASHNA_MOON_GOOD("Good", "राम्रो"),
PRASHNA_MOON_AVERAGE("Average", "औसत"),
PRASHNA_MOON_WEAK("Weak", "कमजोर"),
PRASHNA_MOON_VERY_WEAK("Very Weak", "अत्यन्त कमजोर"),
PRASHNA_MOON_AFFLICTED("Afflicted", "पीडित"),
PRASHNA_LAGNA_STRONG("Strong - Well placed lord", "बलियो - राम्रोसँग स्थापित स्वामी"),
PRASHNA_LAGNA_MODERATE("Moderate - Mixed influences", "मध्यम - मिश्रित प्रभावहरू"),
PRASHNA_LAGNA_WEAK("Weak - Afflicted or poorly placed", "कमजोर - पीडित वा खराब स्थापित"),
PRASHNA_LAGNA_COMBUST("Combust - Lord too close to Sun", "अस्त - स्वामी सूर्यको अत्यधिक नजिक"),
PRASHNA_LAGNA_RETROGRADE_LORD("Lord is Retrograde", "स्वामी वक्री छ"),
PRASHNA_STRENGTH_VERY_STRONG("Very Strong", "अत्यन्त बलियो"),
PRASHNA_STRENGTH_STRONG("Strong", "बलियो"),
PRASHNA_STRENGTH_MODERATE("Moderate", "मध्यम"),
PRASHNA_STRENGTH_WEAK("Weak", "कमजोर"),
PRASHNA_STRENGTH_VERY_WEAK("Very Weak", "अत्यन्त कमजोर"),
PRASHNA_STRENGTH_DEBILITATED("Debilitated", "नीच"),
PRASHNA_ASPECT_CONJUNCTION("Conjunction", "युति"),
PRASHNA_ASPECT_SEXTILE("Sextile", "षष्ठ"),
PRASHNA_ASPECT_SQUARE("Square", "चतुर्थ"),
PRASHNA_ASPECT_TRINE("Trine", "त्रिकोण"),
PRASHNA_ASPECT_OPPOSITION("Opposition", "सप्तम"),
PRASHNA_ASPECT_MARS_4TH("Mars 4th Aspect", "मंगल ४ औं दृष्टि"),
PRASHNA_ASPECT_MARS_8TH("Mars 8th Aspect", "मंगल ८ औं दृष्टि"),
PRASHNA_ASPECT_JUPITER_5TH("Jupiter 5th Aspect", "गुरु ५ औं दृष्टि"),
PRASHNA_ASPECT_JUPITER_9TH("Jupiter 9th Aspect", "गुरु ९ औं दृष्टि"),
PRASHNA_ASPECT_SATURN_3RD("Saturn 3rd Aspect", "शनि ३ रो दृष्टि"),
PRASHNA_ASPECT_SATURN_10TH("Saturn 10th Aspect", "शनि १० औं दृष्टि"),
PRASHNA_HOUSE_EXCELLENT("Excellent", "उत्कृष्ट"),
PRASHNA_HOUSE_GOOD("Good", "राम्रो"),
PRASHNA_HOUSE_MODERATE("Moderate", "मध्यम"),
PRASHNA_HOUSE_POOR("Poor", "कमजोर"),
PRASHNA_HOUSE_AFFLICTED("Afflicted", "पीडित"),
PRASHNA_METHOD_MOON_TRANSIT("Moon Transit Method", "चन्द्र गोचर विधि"),
PRASHNA_METHOD_MOON_NAKSHATRA("Moon Nakshatra Method", "चन्द्र नक्षत्र विधि"),
PRASHNA_METHOD_HOUSE_LORD_DEGREES("House Lord Degrees", "भावेश अंश विधि"),
PRASHNA_METHOD_LAGNA_DEGREES("Lagna Degrees Method", "लग्न अंश विधि"),
PRASHNA_METHOD_PLANETARY_CONJUNCTION("Planetary Conjunction", "ग्रह युति विधि"),
PRASHNA_METHOD_DASHA_BASED("Dasha-based Timing", "दशा आधारित समय"),
PRASHNA_METHOD_MIXED("Combined Methods", "संयुक्त विधिहरू"),
PRASHNA_OMEN_LAGNA("Prashna Lagna Sign", "प्रश्न लग्न राशि"),
PRASHNA_OMEN_MOON_PLACEMENT("Moon Placement", "चन्द्र स्थिति"),
PRASHNA_OMEN_HORA_LORD("Hora Lord", "होरा स्वामी"),
PRASHNA_OMEN_DAY_LORD("Day Lord", "दिन स्वामी"),
PRASHNA_OMEN_NAKSHATRA("Question Nakshatra", "प्रश्न नक्षत्र"),
PRASHNA_OMEN_PLANETARY_WAR("Planetary War", "ग्रह युद्ध"),
PRASHNA_OMEN_COMBUSTION("Combustion", "अस्त"),
PRASHNA_OMEN_RETROGRADE("Retrograde Planet", "वक्री ग्रह"),
PRASHNA_OMEN_GANDANTA("Gandanta Position", "गण्डान्त स्थिति"),
PRASHNA_PUSHKARA("Pushkara Navamsha", "पुष्कर नवांश"),
PRASHNA_COLOR_RED("Red", "रातो"),
PRASHNA_COLOR_ORANGE("Orange", "सुन्तला"),
PRASHNA_COLOR_GREEN("Green", "हरियो"),
PRASHNA_COLOR_WHITE("White", "सेतो"),
PRASHNA_COLOR_YELLOW("Yellow", "पहेंलो"),
PRASHNA_COLOR_GREY_BLUE("Grey-Blue", "खरानी-नीलो"),
PRASHNA_COLOR_MULTI("Multi-colored", "बहुरंगी"),
PRASHNA_COLOR_BLACK("Black", "कालो"),
PRASHNA_COLOR_GOLDEN("Golden", "सुनौलो"),
PRASHNA_COLOR_GOLDEN_YELLOW("Golden-Yellow", "सुनौलो-पहेंलो"),
PRASHNA_COLOR_BROWN("Brown", "खैरो"),
PRASHNA_TOPIC_QUERENT("The querent", "प्रश्नकर्ता"),
PRASHNA_TOPIC_HEALTH("Health", "स्वास्थ्य"),
PRASHNA_TOPIC_SELF("Self", "स्वयम्"),
PRASHNA_TOPIC_BEGINNING("Beginning of matter", "विषयको शुरुवात"),
PRASHNA_TOPIC_PHYSICAL("Physical appearance", "शारीरिक बनावट"),
PRASHNA_TOPIC_SUCCESS("General success", "सामान्य सफलता"),
PRASHNA_TOPIC_LIFE_FORCE("Life force", "जीवन शक्ति"),
PRASHNA_TOPIC_WEALTH("Wealth", "धन"),
PRASHNA_TOPIC_FAMILY("Family", "परिवार"),
PRASHNA_TOPIC_SPEECH("Speech", "वाणी"),
PRASHNA_TOPIC_RESOURCES("Resources", "स्रोत"),
PRASHNA_TOPIC_FOOD("Food", "भोजन"),
PRASHNA_TOPIC_RIGHT_EYE("Right eye", "दायाँ आँखा"),
PRASHNA_TOPIC_FACE("Face", "अनुहार"),
PRASHNA_TOPIC_POSSESSIONS("Possessions", "सम्पत्ति"),
PRASHNA_TOPIC_COURAGE("Courage", "साहस"),
PRASHNA_TOPIC_SIBLINGS("Siblings", "भाइबहिनी"),
PRASHNA_TOPIC_SHORT_TRAVEL("Short journeys", "छोटो यात्रा"),
PRASHNA_TOPIC_COMMUNICATION("Communication", "सञ्चार"),
PRASHNA_TOPIC_NEIGHBORS("Neighbors", "छिमेकी"),
PRASHNA_TOPIC_SKILLS("Skills", "सीप"),
PRASHNA_TOPIC_EFFORTS("Efforts", "प्रयास"),
PRASHNA_TOPIC_RIGHT_EAR("Right ear", "दायाँ कान"),
PRASHNA_TOPIC_HOME("Home", "घर"),
PRASHNA_TOPIC_MOTHER("Mother", "आमा"),
PRASHNA_TOPIC_PROPERTY("Property", "सम्पत्ति"),
PRASHNA_TOPIC_VEHICLES("Vehicles", "सवारी साधन"),
PRASHNA_TOPIC_EDUCATION("Education", "शिक्षा"),
PRASHNA_TOPIC_HAPPINESS("Happiness", "सुख"),
PRASHNA_TOPIC_TREASURE("Buried treasure", "गाडिएको धन"),
PRASHNA_TOPIC_STOMACH("Stomach", "पेट"),
PRASHNA_TOPIC_CHILDREN("Children", "सन्तान"),
PRASHNA_TOPIC_INTELLIGENCE("Intelligence", "बुद्धि"),
PRASHNA_TOPIC_ROMANCE("Romance", "रोमान्स"),
PRASHNA_TOPIC_SPECULATION("Speculation", "सट्टा"),
PRASHNA_TOPIC_MANTRAS("Mantras", "मन्त्र"),
PRASHNA_TOPIC_PAST_MERIT("Past merit", "पूर्व पुण्य"),
PRASHNA_TOPIC_ENEMIES("Enemies", "शत्रु"),
PRASHNA_TOPIC_DISEASE("Disease", "रोग"),
PRASHNA_TOPIC_OBSTACLES("Obstacles", "बाधा"),
PRASHNA_TOPIC_SERVICE("Service", "सेवा"),
PRASHNA_TOPIC_DEBTS("Debts", "ऋण"),
PRASHNA_TOPIC_COMPETITORS("Competitors", "प्रतिस्पर्धी"),
PRASHNA_TOPIC_UNCLE("Maternal uncle", "मामा"),
PRASHNA_TOPIC_INTESTINES("Intestines", "आन्द्रा"),
PRASHNA_TOPIC_MARRIAGE("Marriage", "विवाह"),
PRASHNA_TOPIC_PARTNERSHIP("Partnership", "साझेदारी"),
PRASHNA_TOPIC_DEALS("Business deals", "व्यापार सम्झौता"),
PRASHNA_TOPIC_OPPONENT("Opponent", "विपक्षी"),
PRASHNA_TOPIC_FOREIGN_TRAVEL("Foreign travel", "विदेश यात्रा"),
PRASHNA_TOPIC_DEATH("Death", "मृत्यु"),
PRASHNA_TOPIC_SEXUAL("Sexual matters", "यौन मामिला"),
PRASHNA_TOPIC_KIDNEYS("Kidneys", "मृगौला"),
PRASHNA_TOPIC_HIDDEN("Hidden things", "लुकेका कुरा"),
PRASHNA_TOPIC_INHERITANCE("Inheritance", "विरासत"),
PRASHNA_TOPIC_TRANSFORMATION("Transformation", "रूपान्तरण"),
PRASHNA_TOPIC_CHRONIC("Chronic illness", "दीर्घकालीन रोग"),
PRASHNA_TOPIC_OCCULT("Occult", "तन्त्र-मन्त्र"),
PRASHNA_TOPIC_MYSTERY("Mystery", "रहस्य"),
PRASHNA_TOPIC_REPRODUCTIVE("Reproductive organs", "प्रजनन अंग"),
PRASHNA_TOPIC_LUCK("Luck", "भाग्य"),
PRASHNA_TOPIC_FATHER("Father", "पिता"),
PRASHNA_TOPIC_LONG_TRAVEL("Long journeys", "लामो यात्रा"),
PRASHNA_TOPIC_HIGHER_LEARNING("Higher learning", "उच्च शिक्षा"),
PRASHNA_TOPIC_RELIGION("Religion", "धर्म"),
PRASHNA_TOPIC_GURU("Guru", "गुरु"),
PRASHNA_TOPIC_FORTUNE("Fortune", "सुभाग्य"),
PRASHNA_TOPIC_THIGHS("Thighs", "तिघ्रा"),
PRASHNA_TOPIC_CAREER("Career", "क्यारियर"),
PRASHNA_TOPIC_STATUS("Status", "स्थिति"),
PRASHNA_TOPIC_AUTHORITY("Authority", "अधिकार"),
PRASHNA_TOPIC_GOVERNMENT("Government", "सरकार"),
PRASHNA_TOPIC_PUBLIC_LIFE("Public life", "सार्वजनिक जीवन"),
PRASHNA_TOPIC_ACHIEVEMENT("Achievement", "उपलब्धि"),
PRASHNA_TOPIC_KNEES("Knees", "घुँडा"),
PRASHNA_TOPIC_GAINS("Gains", "लाभ"),
PRASHNA_TOPIC_FULFILLMENT("Fulfillment", "पूर्णता"),
PRASHNA_TOPIC_ELDER_SIBLINGS("Elder siblings", "ठूला भाइबहिनी"),
PRASHNA_TOPIC_FRIENDS("Friends", "साथीहरू"),
PRASHNA_TOPIC_INCOME("Income", "आय"),
PRASHNA_TOPIC_WISHES("Wishes", "इच्छाहरू"),
PRASHNA_TOPIC_RECOVERY("Recovery from illness", "बिरामीबाट सुधार"),
PRASHNA_TOPIC_ANKLES("Ankles", "कुर्कुच्चा"),
PRASHNA_TOPIC_LOSSES("Losses", "हानि"),
PRASHNA_TOPIC_EXPENSES("Expenses", "खर्च"),
PRASHNA_TOPIC_LIBERATION("Liberation", "मुक्ति"),
PRASHNA_TOPIC_FOREIGN_LANDS("Foreign lands", "विदेशी भूमि"),
PRASHNA_TOPIC_BED_PLEASURES("Bed pleasures", "शय्या सुख"),
PRASHNA_TOPIC_SLEEP("Sleep", "निद्रा"),
PRASHNA_TOPIC_HOSPITAL("Hospital", "अस्पताल"),
PRASHNA_TOPIC_FEET("Feet", "गोडा"),
PRASHNA_NEW_QUESTION("New question", "नयाँ प्रश्न"),
PRASHNA_KUNDALI("Prashna Kundali", "प्रश्न कुण्डली"),
PRASHNA_HORARY("Horary Astrology", "प्रश्न ज्योतिष"),
PRASHNA_INTRO("Ask your question and receive guidance based on the planetary positions at this very moment.", "आफ्नो प्रश्न सोध्नुहोस् र यस क्षणको ग्रह स्थितिको आधारमा मार्गदर्शन प्राप्त गर्नुहोस्।"),
PRASHNA_YOUR_QUESTION("Your Question", "तपाईंको प्रश्न"),
PRASHNA_QUESTION_HINT("Enter your question here...", "यहाँ आफ्नो प्रश्न प्रविष्ट गर्नुहोस्..."),
PRASHNA_QUESTION_HELP("Be specific and clear. Frame your question with a sincere intent.", "स्पष्ट र विशिष्ट हुनुहोस्। ईमानदार इरादाले आफ्नो प्रश्न बनाउनुहोस्।"),
PRASHNA_CATEGORY("Question Category", "प्रश्न वर्ग"),
PRASHNA_LOCATION("Question Location", "प्रश्न स्थान"),
PRASHNA_TIME_NOW("Now", "अहिले"),
PRASHNA_ANALYZE("Analyze Question", "प्रश्न विश्लेषण गर्नुहोस्"),
PRASHNA_ABOUT("About Prashna", "प्रश्न बारेमा"),
PRASHNA_ANALYZING("Analyzing your question...", "तपाईंको प्रश्न विश्लेषण गर्दै..."),
PRASHNA_CALCULATING("Calculating planetary positions and yogas", "ग्रह स्थिति र योगहरू गणना गर्दै"),
PRASHNA_ANALYSIS_FAILED("Analysis Failed", "विश्लेषण असफल"),
PRASHNA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
PRASHNA_FAVORABLE("Favorable", "अनुकूल"),
PRASHNA_SCORE("Score: %s", "अंक: %s"),
PRASHNA_QUESTION_DETAILS("Question Details", "प्रश्न विवरण"),
PRASHNA_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
PRASHNA_LAGNA_ANALYSIS("Lagna Analysis", "लग्न विश्लेषण"),
PRASHNA_RISING_SIGN("Rising Sign", "उदय राशि"),
PRASHNA_LAGNA_LORD("Lagna Lord", "लग्नेश"),
PRASHNA_LORD_POSITION("Lord Position", "स्वामी स्थिति"),
PRASHNA_CONDITION("Condition", "अवस्था"),
PRASHNA_PLANETS_IN_LAGNA("Planets in Lagna", "लग्नमा ग्रहहरू"),
PRASHNA_MOON_VOID("Moon is Void of Course - delays or changes likely", "चन्द्र शून्य गतिमा छ - ढिलाइ वा परिवर्तन सम्भावित"),
PRASHNA_TIMING("Timing Prediction", "समय भविष्यवाणी"),
PRASHNA_ESTIMATED_TIMEFRAME("Estimated Timeframe", "अनुमानित समयावधि"),
PRASHNA_SPECIAL_YOGAS("Special Prashna Yogas", "विशेष प्रश्न योगहरू"),
PRASHNA_SUPPORTING_FACTORS("Supporting Factors", "समर्थक कारकहरू"),
PRASHNA_CHALLENGES("Challenges", "चुनौतीहरू"),
PRASHNA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
PRASHNA_MOON_PHASE_WAXING("Waxing", "शुक्ल पक्ष"),
PRASHNA_MOON_PHASE_WANING("Waning", "कृष्ण पक्ष"),
PRASHNA_SIGN("Sign", "राशि"),
PRASHNA_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
PRASHNA_TITHI("Tithi", "तिथि"),
PRASHNA_PHASE("Phase", "पक्ष"),
PRASHNA_INST_1("Prashna Kundali is cast for the moment the question arises in your mind or when you ask it.", "प्रश्न कुण्डली तपाईंको मनमा प्रश्न उठेको क्षणमा वा तपाईंले सोधेको बेला बनाइन्छ।"),
PRASHNA_INST_2("The Moon is the primary significator representing your mind and the matter at hand.", "चन्द्रमा प्राथमिक कारक हो जसले तपाईंको मन र हातमा रहेको विषयलाई प्रतिनिधित्व गर्दछ।"),
PRASHNA_INST_3("Frame your question with sincerity and focused intent for accurate guidance.", "सटीक मार्गदर्शनको लागि आफ्नो प्रश्न ईमानदारिता र केन्द्रित उद्देश्यसहित बनाउनुहोस्।"),
PRASHNA_INST_4("The analysis considers Lagna, Moon, relevant houses, and special Prashna yogas.", "विश्लेषणले लग्न, चन्द्रमा, सम्बन्धित भावहरू, र विशेष प्रश्न योगहरूलाई विचार गर्छ।"),
PRASHNA_INST_5("Timing predictions are based on planetary movements and house lord positions.", "समय भविष्यवाणीहरू ग्रह गतिविधि र भाव स्वामी स्थितिमा आधारित छन्।"),
PRASHNA_ANALYZE_ERROR("Failed to analyze question", "प्रश्न विश्लेषण गर्न असफल"),
PRASHNA_AI_INSIGHT("AI Insight", "एआई अन्तर्दृष्टि"),
PRASHNA_AI_INSIGHT_SUBTITLE("Powered by Stormy", "Stormy द्वारा संचालित"),
PRASHNA_AI_INSIGHT_DESC("Get a deeper, personalized interpretation of your Prashna chart using AI. The AI will analyze the planetary positions and yogas to provide additional guidance.", "एआई प्रयोग गरेर आफ्नो प्रश्न चार्टको गहिरो, व्यक्तिगत व्याख्या प्राप्त गर्नुहोस्। एआईले थप मार्गदर्शन प्रदान गर्न ग्रह स्थिति र योगहरूको विश्लेषण गर्नेछ।"),
PRASHNA_GENERATE_AI_INSIGHT("Generate AI Insight", "एआई अन्तर्दृष्टि उत्पन्न गर्नुहोस्"),
PRASHNA_AI_ANALYZING("Consulting the stars...", "ताराहरूसँग परामर्श गर्दै..."),
PRASHNA_CONFIDENCE("%s%% confidence", "%s%% विश्वास"),
PRASHNA_REPORT_TITLE("PRASHNA ANALYSIS REPORT", "प्रश्न विश्लेषण रिपोर्ट"),
PRASHNA_REPORT_QUESTION("Question", "प्रश्न"),
PRASHNA_REPORT_CATEGORY("Category", "वर्ग"),
PRASHNA_REPORT_VERDICT("Verdict", "निर्णय"),
PRASHNA_REPORT_CERTAINTY("Certainty", "निश्चितता"),
PRASHNA_REPORT_PRIMARY_INDICATION("Primary Indication", "प्राथमिक संकेत"),
PRASHNA_REPORT_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
PRASHNA_REPORT_POSITION("Position", "स्थिति"),
PRASHNA_REPORT_HOUSE("House", "भाव"),
PRASHNA_REPORT_NAKSHATRA("Nakshatra", "नक्षत्र"),
PRASHNA_REPORT_PADA("Pada", "पद"),
PRASHNA_REPORT_PHASE("Phase", "पक्ष"),
PRASHNA_REPORT_WAXING("Waxing", "शुक्ल"),
PRASHNA_REPORT_WANING("Waning", "कृष्ण"),
PRASHNA_REPORT_STRENGTH("Strength", "बल"),
PRASHNA_REPORT_WARNING_VOID("WARNING: Moon is Void of Course - outcome may be nullified or delayed.", "चेतावनी: चन्द्रमा शून्य छ - परिणाम शून्य वा ढिलाइ हुन सक्छ।"),
PRASHNA_REPORT_LAGNA_ANALYSIS("Lagna Analysis", "लग्न विश्लेषण"),
PRASHNA_REPORT_RISING_SIGN("Rising Sign", "उदय राशि"),
PRASHNA_REPORT_LAGNA_LORD("Lagna Lord", "लग्नेश"),
PRASHNA_REPORT_CONDITION("Condition", "अवस्था"),
PRASHNA_REPORT_RELEVANT_HOUSES("Relevant Houses", "सम्बन्धित भावहरू"),
PRASHNA_REPORT_TIMING("Timing Prediction", "समय भविष्यवाणी"),
PRASHNA_REPORT_ESTIMATED("Estimated Time", "अनुमानित समय"),
PRASHNA_REPORT_METHOD("Method", "विधि"),
PRASHNA_REPORT_CONFIDENCE("Confidence", "विश्वास"),
PRASHNA_OMEN_LAGNA_DESC("Rising sign is %s", "उदय राशि %s हो"),
    PRASHNA_OMEN_MOON_PLACEMENT_DESC("Moon in %s house (%s)", "Moon in %s house (%s)"),
PRASHNA_OMEN_HORA_LORD_DESC("Question in %s Hora", "प्रश्न %s को होरामा"),
PRASHNA_OMEN_DAY_LORD_DESC("Question on %s's day", "प्रश्न %s को बारमा"),
PRASHNA_OMEN_NAKSHATRA_DESC("Moon in %s Nakshatra", "चन्द्रमा %s नक्षत्रमा"),
PRASHNA_OMEN_PLANETARY_WAR_DESC("%s in war with %s", "%s र %s बीच ग्रह युद्ध"),
PRASHNA_OMEN_COMBUSTION_DESC("%s is combust", "%s अस्त छ"),
PRASHNA_OMEN_RETROGRADE_DESC("%s is retrograde", "%s वक्री छ"),
PRASHNA_OMEN_GANDANTA_DESC("%s is in Gandanta", "%s गण्डान्तमा छ"),
PRASHNA_OMEN_PUSHKARA_DESC("%s is in Pushkara Navamsha", "%s पुष्कर नवांशमा छ"),
PRASHNA_OMEN_WAR_IND("Planetary War", "ग्रहयुद्ध"),
PRASHNA_OMEN_COMBUST_IND("%s is Combust", "%s अस्त छ"),
PRASHNA_OMEN_RETRO_IND("%s is Retrograde", "%s वक्री छ"),
PRASHNA_REPORT_HOUSE_INDICATOR("House %s: %s", "भाव %s: %s"),
PRASHNA_REPORT_HOUSE_LORD_INDICATOR("Lord in House %s", "भावेश भाव %s मा"),
PRASHNA_REPORT_TATTVA_INDICATOR("Element: %s", "तत्व: %s"),
    PRASHNA_REPORT_TIMING_TEMPLATE("%1\$s: %2\$s (%3\$s°/day)", "%1\$s: %2\$s (%3\$s°/day)"),
PRASHNA_REPORT_FACTORS_POSITIVE("+ %s", "+ %s"),
PRASHNA_REPORT_FACTORS_NEGATIVE("- %s", "- %s"),
PRASHNA_YOGA_SYMBOL_POSITIVE("+ %s: %s", "+ %s: %s"),
PRASHNA_YOGA_SYMBOL_NEGATIVE("- %s: %s", "- %s: %s"),
    PRASHNA_NAKSHATRA_IND_TEMPLATE("%1\$s (Lord: %2\$s)", "%1\$s (Lord: %2\$s)"),
PRASHNA_MOON_HOUSE_IND_TEMPLATE("House %s", "भाव %s"),
PRASHNA_MOON_INTERP_TEMPLATE("Moon Analysis: %1\$s Position %2\$s House %3\$s. Phase %4\$s, %5\$s. Strength: %6\$s.%7\$s", "चन्द्र विश्लेषण: %1\$s स्थिति %2\$s भाव %3\$s। पक्ष %4\$s, %5\$s। बल: %6\$s।%7\$s"),
PRASHNA_LAGNA_INTERP_TEMPLATE("Rising Sign: %1\$s. Lagna Lord %2\$s House %3\$s. Condition: %4\$s.%5\$s", "उदय राशि: %1\$s। लग्नेश %2\$s भाव %3\$s। अवस्था: %4\$s।%5\$s"),
    PRASHNA_HOUSE_INTERP_TEMPLATE("Relevant Houses (%1\$s)", "Relevant Houses (%1\$s)"),
PRASHNA_HOUSE_ITEM_TEMPLATE("House %1\$s: %2\$s", "भाव %1\$s: %2\$s"),
PRASHNA_PLANETS_IN_LAGNA_TEMPLATE("Planets in Lagna: %s", "लग्नमा ग्रहहरू: %s"),
PRASHNA_FACTOR_MOON_EXCELLENT("Moon is exceptionally strong", "चन्द्रमा अत्यन्त बलियो छ"),
PRASHNA_FACTOR_MOON_GOOD("Moon is well-placed and strong", "चन्द्रमा राम्रो अवस्थामा र बलियो छ"),
PRASHNA_FACTOR_MOON_AVERAGE("Moon has moderate strength", "चन्द्रमाको बल औसत छ"),
PRASHNA_FACTOR_MOON_WEAK("Moon is weak", "चन्द्रमा कमजोर छ"),
PRASHNA_FACTOR_MOON_VERY_WEAK("Moon is very weak or afflicted", "चन्द्रमा धेरै कमजोर वा पीडित छ"),
PRASHNA_FACTOR_MOON_AFFLICTED("Moon is severely afflicted", "चन्द्रमा गम्भीर रूपमा पीडित छ"),
    PRASHNA_FACTOR_MOON_WAXING("Moon is waxing (increasing strength)", "Moon is waxing (increasing strength)"),
    PRASHNA_FACTOR_MOON_WANING("Moon is waning (decreasing strength)", "Moon is waning (decreasing strength)"),
PRASHNA_FACTOR_MOON_VOID("Moon is Void of Course", "चन्द्रमा शून्य अवस्थामा छ"),
PRASHNA_FACTOR_LAGNA_STRONG("Lagna and its lord are strong", "लग्न र लग्नेश बलियो छ"),
PRASHNA_FACTOR_LAGNA_MODERATE("Lagna has moderate strength", "लग्नको बल औसत छ"),
PRASHNA_FACTOR_LAGNA_WEAK("Lagna is weak", "लग्न कमजोर छ"),
PRASHNA_FACTOR_LAGNA_COMBUST("Lagna lord is combust", "लग्नेश अस्त छ"),
PRASHNA_FACTOR_LAGNA_RETRO("Lagna lord is retrograde", "लग्नेश वक्री छ"),
PRASHNA_FACTOR_HOUSES_FAVORABLE("Relevant houses are well-disposed", "सम्बन्धित भावहरू अनुकूल छन्"),
PRASHNA_FACTOR_HOUSES_AFFLICTED("Relevant houses are afflicted", "सम्बन्धित भावहरू पीडित छन्"),
PRASHNA_REASON_STRONGLY_YES("Multiple highly favorable factors indicate success", "धेरै अनुकूल कारकहरूले सफलता संकेत गर्छन्"),
PRASHNA_REASON_YES("Favorable planetary positions support the matter", "अनुकूल ग्रह स्थितिले विषयलाई समर्थन गर्छ"),
PRASHNA_REASON_UNCERTAIN("Mixed influences make the outcome uncertain", "मिश्रित प्रभावले परिणाम अनिश्चित बनाउँछ"),
PRASHNA_REASON_CHALLENGES("Several challenging factors may hinder progress", "धेरै चुनौतीपूर्ण कारकहरूले प्रगतिमा बाधा पुर्याउन सक्छन्"),
PRASHNA_REASON_STRONGLY_NO("Serious afflictions suggest unfavorable outcome", "गम्भीर पीडाहरूले प्रतिकूल परिणाम सुझाव दिन्छ"),
PRASHNA_TIMING_WITHIN("Within %s", "%s भित्र"),
PRASHNA_TIMING_ABOUT("About %s", "लगभग %s"),
PRASHNA_YOGA_ITHASALA_NAME("Ithasala Yoga", "इत्थशाल योग"),
PRASHNA_YOGA_ITHASALA_DESC("Moon is applying to aspect with relevant significator", "चन्द्रमा सम्बन्धित भावेशसँग दृष्टिको लागि अघि बढ्दैछ"),
PRASHNA_YOGA_ITHASALA_INTERP("Success in the matter is indicated. The event will come to fruition.", "विषयमा सफलताको संकेत छ। घटना सफल हुनेछ।"),
PRASHNA_YOGA_MUSARIPHA_NAME("Musaripha Yoga", "मुसरिफ योग"),
PRASHNA_YOGA_MUSARIPHA_DESC("Moon is separating from significant aspect", "चन्द्रमा महत्त्वपूर्ण दृष्टिबाट टाढा हुँदैछ"),
PRASHNA_YOGA_MUSARIPHA_INTERP("The matter has already passed or opportunity was missed.", "विषय पहिले नै बितिसकेको छ वा अवसर गुमेको छ।"),
PRASHNA_YOGA_NAKTA_NAME("Nakta Yoga", "नक्त योग"),
PRASHNA_YOGA_NAKTA_DESC("Transfer of light between planets", "ग्रहहरू बीच प्रकाशको हस्तान्तरण"),
PRASHNA_YOGA_NAKTA_INTERP("Success through an intermediary or third party assistance.", "मध्यस्थ वा तेस्रो पक्षको सहयोग मार्फत सफलता।"),
PRASHNA_YOGA_MANAOU_NAME("Manaou Yoga", "मनाऊ योग"),
PRASHNA_YOGA_MANAOU_DESC("Third planet prohibits completion", "तेस्रो ग्रहले पूर्णतामा अवरोध गर्दछ"),
PRASHNA_YOGA_MANAOU_INTERP("Third party or external factor will prevent success.", "तेस्रो पक्ष वा बाह्य कारकले सफलतामा अवरोध गर्नेछ।"),
PRASHNA_YOGA_KAMBOOLA_NAME("Kamboola Yoga", "कम्बूल योग"),
PRASHNA_YOGA_KAMBOOLA_DESC("Moon in angular house with lord", "चन्द्रमा भावेशसँग केन्द्र भावमा"),
PRASHNA_YOGA_KAMBOOLA_INTERP("Very favorable for success. Quick positive results expected.", "सफलताको लागि धेरै अनुकूल। छिटो सकारात्मक नतिजाको अपेक्षा।"),
PRASHNA_YOGA_GAIRI_KAMBOOLA_NAME("Gairi Kamboola", "गैर कम्बूल"),
PRASHNA_YOGA_GAIRI_KAMBOOLA_DESC("Moon weak though in angular house", "चन्द्रमा केन्द्र भावमा भए पनि कमजोर छ"),
PRASHNA_YOGA_GAIRI_KAMBOOLA_INTERP("Initial hopes but eventual disappointment. Success after delays.", "सुरुमा आशा तर अन्तमा निराशा। ढिलाइ पछि सफलता।"),
PRASHNA_YOGA_DHURUFA_NAME("Dhurufa Yoga", "धुरुफ योग"),
PRASHNA_YOGA_DHURUFA_DESC("Moon in cadent house without strength", "चन्द्रमा बल बिना आपोक्लिम भावमा"),
PRASHNA_YOGA_DHURUFA_INTERP("Failure is indicated. Best to abandon the matter.", "असफलताको संकेत छ। विषय छोड्नु नै राम्रो हुनेछ।"),
PRASHNA_YOGA_PUSHKARA_NAME("Pushkara Navamsha", "पुष्कर नवांश"),
PRASHNA_YOGA_PUSHKARA_DESC("Moon in auspicious navamsha division", "चन्द्रमा शुभ नवांश विभाजनमा"),
PRASHNA_YOGA_PUSHKARA_INTERP("Excellent omen. The matter will have nourishing, supportive outcomes.", "उत्कृष्ट शकुन। विषयमा पोषक, सहयोगी नतिजाहरू प्राप्त हुनेछन्।"),
PRASHNA_YOGA_GANDANTA_NAME("Gandanta Position", "गण्डान्त स्थिति"),
PRASHNA_YOGA_GANDANTA_DESC("Moon at junction point between water and fire signs", "चन्द्रमा जल र अग्नि राशि बीचको सन्धि बिन्दुमा"),
PRASHNA_YOGA_GANDANTA_INTERP("Danger, crisis, or difficult transformation indicated.", "खतरा, संकट वा कठिन रूपान्तरणको संकेत।"),
PRASHNA_YOGA_UNION_NAME("Lagna-Moon Union", "लग्न-चन्द्र युति"),
PRASHNA_YOGA_UNION_DESC("Moon with Lagna Lord", "चन्द्रमा लग्न स्वामीसँग"),
PRASHNA_YOGA_UNION_INTERP("Strong personal involvement and favorable outcome.", "बलियो व्यक्तिगत संलग्नता र अनुकूल परिणाम।"),
    PRASHNA_TIMING_EXPLANATION("Based on %1\$s, the estimated timing is approximately %2\$s. Moon's current position and speed (%3\$s°/day)", "Based on %1\$s, the estimated timing is approximately %2\$s. Moon's current position and speed (%3\$s°/day)"),
PRASHNA_REC_PROCEED("Proceed with confidence. The cosmic conditions are supportive.", "आत्मविश्वासका साथ अगाडि बढ्नुहोस्। ब्रह्माण्डीय परिस्थितिहरू सहयोगी छन्।"),
PRASHNA_REC_CAUTION("Proceed with caution. Carefully monitor developments.", "सावधानीका साथ अगाडि बढ्नुहोस्। विकासक्रमहरूलाई ध्यानपूर्वक निगरानी गर्नुहोस्।"),
PRASHNA_REC_DELAY("Expect delays. Patience and persistence will be required.", "ढिलाइको अपेक्षा गर्नुहोस्। धैर्य र दृढता आवश्यक हुनेछ।"),
PRASHNA_REC_WAIT("Wait for a better time. Current conditions are not conducive to success.", "राम्रो समयको लागि प्रतीक्षा गर्नुहोस्। वर्तमान परिस्थितिहरू सफलताको लागि अनुकूल छैनन्।"),
PRASHNA_REC_RETHINK("Rethink the approach. Significant obstacles or hidden factors detected.", "दृष्टिकोण पुनर्विचार गर्नुहोस्। महत्त्वपूर्ण बाधाहरू वा लुकेका कारकहरू पत्ता लागेका छन्।"),
PRASHNA_REC_STRONGLY_SUPPORT("Proceed with confidence. The chart strongly supports your endeavor.", "आत्मविश्वासका साथ अगाडि बढ्नुहोस्। कुण्डलीले तपाईंको प्रयासलाई दृढतापूर्वक समर्थन गर्दछ।"),
PRASHNA_REC_AWARENESS("Proceed with awareness. Minor adjustments may improve outcomes.", "सचेतताका साथ अगाडि बढ्नुहोस्। साना समायोजनहरूले नतिजाहरू सुधार्न सक्छन्।"),
PRASHNA_REC_PATIENCE("Exercise patience. Wait for clearer signs before major action.", "धैर्य धारण गर्नुहोस्। ठूलो कदम चाल्नु अघि स्पष्ट संकेतहरूको प्रतीक्षा गर्नुहोस्।"),
PRASHNA_REC_GUIDANCE("Seek additional guidance or information before proceeding.", "अगाडि बढ्नु अघि थप मार्गदर्शन वा जानकारी खोज्नुहोस्।"),
    PRASHNA_REC_VOID_MOON("The matter requires better timing. Moon is void of course.", "The matter requires better timing. Moon is void of course."),
PRASHNA_REC_OBSTACLES("Expect obstacles. Success through struggle is possible but not guaranteed.", "बाधाहरूको अपेक्षा गर्नुहोस्। संघर्ष मार्फत सफलता सम्भव छ तर ग्यारेन्टी छैन।"),
PRASHNA_REC_UNFAVORABLE("Unfavorable conditions. Reconsider your objectives or approach.", "अतुलनीय परिस्थितिहरू। आफ्ना उद्देश्यहरू वा दृष्टिकोण पुनर्विचार गर्नुहोस्।"),
    PRASHNA_REC_MUSARIPHA("The matter is already decided or opportunity has passed (Musaripha)", "The matter is already decided or opportunity has passed (Musaripha)"),
PRASHNA_REC_VOID_MOON_REASK("Consider re-asking when Moon enters a new sign.", "चन्द्रमा नयाँ राशिमा प्रवेश गरेपछि फेरि सोध्ने विचार गर्नुहोस्।"),
PRASHNA_REC_RECONSIDER("Reconsider your approach. Current conditions are not supportive.", "आफ्नो दृष्टिकोण पुनर्विचार गर्नुहोस्। वर्तमान परिस्थितिहरू सहयोगी छैनन्।"),
PRASHNA_REC_EXPLORE("Explore alternative options or modify your plans.", "वैकल्पिक विकल्पहरू अन्वेषण गर्नुहोस् वा आफ्ना योजनाहरू परिमार्जन गर्नुहोस्।"),
PRASHNA_REC_ABANDON("It is advisable to abandon or significantly modify this pursuit.", "यस प्रयासलाई छोड्नु वा महत्त्वपूर्ण रूपमा परिमार्जन गर्नु उचित हुन्छ।"),
PRASHNA_REC_FOCUS_FAVORABLE("Focus energy on matters with more favorable indications.", "थप अनुकूल संकेत भएका विषयहरूमा ऊर्जा केन्द्रित गर्नुहोस्।")
}
