package com.astro.storm.core.common

enum class StringKeyGeneralPart7(override val en: String, override val ne: String) : StringKeyInterface {
    MB_SAT_REM_4("Serve the elderly and underprivileged", "वृद्ध र असहायहरूको सेवा गर्नुहोस्"),
    MB_SEV_APPROACHING("Approaching", "आउँदै गरेको"),
    MB_SEV_EXACT("Exact", "पूर्ण"),
    MB_SEV_SAFE("Safe", "सुरक्षित"),
    MB_SEV_VERY_CLOSE("Very Close", "धेरै नजिक"),
    MB_SEV_WITHIN_ORB("Within Orb", "प्रभाव क्षेत्र भित्र"),
    MB_SUN_EFF_1("Challenges with authority figures or father", "अधिकारवाला व्यक्ति वा बुबासँग चुनौतीहरू"),
    MB_SUN_EFF_2("Potential health issues related to heart or vitality", "मुटु वा जीवनशक्तिसँग सम्बन्धित सम्भावित स्वास्थ्य समस्याहरू"),
    MB_SUN_EFF_3("Career obstacles during certain periods", "निश्चित अवधिमा करियरमा अवरोधहरू"),
    MB_SUN_EFF_4("Need for ego transformation", "अहंकार रूपान्तरणको आवश्यकता"),
    MB_SUN_REM_1("Offer water to Sun at sunrise", "सूर्योदयमा सूर्यलाई जल अर्पण गर्नुहोस्"),
    MB_SUN_REM_2("Recite Aditya Hridayam regularly", "नियमित रूपमा आदित्य हृदयम् पाठ गर्नुहोस्"),
    MB_SUN_REM_3("Wear Ruby with proper muhurta (if suitable)", "उपयुक्त भएमा शुभ मुहूर्तमा माणिक लगाउनुहोस्"),
    MB_SUN_REM_4("Donate wheat and jaggery on Sundays", "आइतबार गहुँ र सख्खर दान गर्नुहोस्"),
    MB_VENUS_EFF_1("Relationship challenges or disappointments", "सम्बन्धमा चुनौती वा निराशा"),
    MB_VENUS_EFF_2("Reproductive health considerations", "प्रजनन स्वास्थ्य सम्बन्धी विचारणीय कुराहरू"),
    MB_VENUS_EFF_3("Artistic blocks or creative challenges", "कलात्मक अवरोध वा सिर्जनात्मक चुनौतीहरू"),
    MB_VENUS_EFF_4("Need for self-love and relationship healing", "आत्म-प्रेम र सम्बन्ध उपचारको आवश्यकता"),
    MB_VENUS_REM_1("Worship Goddess Lakshmi on Fridays", "शुक्रबार देवी लक्ष्मीको पूजा गर्नुहोस्"),
    MB_VENUS_REM_2("Wear Diamond or White Sapphire (if suitable)", "उपयुक्त भएमा हीरा वा सेतो पुखराज लगाउनुहोस्"),
    MB_VENUS_REM_3("Donate white items and rice", "सेतो वस्तु र चामल दान गर्नुहोस्"),
    MB_VENUS_REM_4("Practice self-care and appreciation", "आत्म-हेरचाह र प्रशंसा अभ्यास गर्नुहोस्"),
    MEDITATION_INCLINATION("Meditation Inclination", "ध्यान झुकाव"),
    MEDITATION_TITLE("Meditation Recommendations", "ध्यान सिफारिसहरू"),
    MEDIUM_TERM("Medium Term Outlook", "मध्यम अवधि दृष्टिकोण"),
    MEETING_CIRCUMSTANCES("Meeting Circumstances", "भेट परिस्थितिहरू"),
    MEETING_DIRECTION("Direction of Meeting", "भेटको दिशा"),
    MEMORY_AND_GRASP("Memory & Grasp", "स्मरणशक्ति र ग्रहणशक्ति"),
    MERCURY_HEALTH("Mercury Health Influence", "बुध स्वास्थ्य प्रभाव"),
    MERCURY_HOUSE("Mercury House", "बुध भाव"),
    MERCURY_SIGN("Mercury Sign", "बुध राशि"),
    METABOLIC_TYPE("Metabolic Type", "चयापचय प्रकार"),
    METHOD_CHARITY("Charity/Donation", "दान/दक्षिणा"),
    METHOD_EARTH("Earth ritual", "भूमि विधि"),
    METHOD_FEEDING("Feeding ritual", "भोजन गराउने विधि"),
    METHOD_GENERAL("General remedy", "सामान्य उपाय"),
    METHOD_MANTRA("Mantra/Prayer", "मन्त्र/प्रार्थना"),
    METHOD_OFFERING("Offering ritual", "अर्पण विधि"),
    METHOD_PROTECTIVE("Protective item", "रक्षात्मक वस्तु"),
    METHOD_WATER("Water ritual", "जल विधि"),
    MINDSET_ANALYTICAL("Analytical Mindset", "विश्लेषणात्मक मानसिकता"),
    MINDSET_CREATIVE("Creative Mindset", "रचनात्मक मानसिकता"),
    MINDSET_INTUITIVE("Intuitive Mindset", "अन्तर्ज्ञानी मानसिकता"),
    MINDSET_PRACTICAL("Practical Mindset", "व्यावहारिक मानसिकता"),
    MINDSET_TITLE("Mindset", "मानसिकता"),
    MINUTES_SHORT("m", "मि"),
    MISC_COLLAPSE("Collapse", "संकुचन"),
    MISC_CURRENT("Current", "वर्तमान"),
    MISC_DAYS_LEFT("days left", "दिन बाँकी"),
    MISC_EXPAND("Expand", "विस्तार"),
    MISC_INFO("Information", "जानकारी"),
    MISC_LESS("Less", "कम"),
    MISC_LOADING("Loading...", "लोड हुँदैछ..."),
    MISC_MONTHS("months", "महिना"),
    MISC_MORE("More", "थप"),
    MISC_NO_DATA("No data available", "डाटा उपलब्ध छैन"),
    MISC_UNAVAILABLE("Unavailable", "उपलब्ध छैन"),
    MISC_UNKNOWN("Unknown", "अज्ञात"),
    MISC_YEARS("years", "वर्ष"),
    MODEL_AI_LABEL("AI Model", "एआई मोडेल"),
    MODEL_CONFIGURE("Configure Models", "मोडेलहरू कन्फिगर गर्नुहोस्"),
    MODEL_DONE("Done", "सम्पन्न"),
    MODEL_MANAGE("Manage AI Models", "एआई मोडेलहरू व्यवस्थापन गर्नुहोस्"),
    MODEL_NONE_AVAILABLE("No models available", "कुनै मोडेल उपलब्ध छैन"),
    MODEL_OPTIONS_TITLE("Model Options", "मोडेल विकल्पहरू"),
    MODEL_SELECT_PROMPT("Select a model", "मोडेल छान्नुहोस्"),
    MODEL_SELECT_TITLE("Select AI Model", "एआई मोडेल छान्नुहोस्"),
    MODEL_THINKING_DESC("Extended reasoning before answering", "जवाफ दिनु अघि विस्तारित तर्क"),
    MODEL_THINKING_MODE("Thinking Mode", "सोच्ने मोड"),
    MODEL_WEB_SEARCH("Web Search", "वेब खोज"),
    MODEL_WEB_SEARCH_DESC("Search the web for current information", "वर्तमान जानकारीको लागि वेब खोज्नुहोस्"),
    MOKSHA_YOGA("Moksha Yoga", "मोक्ष योग"),
    MONTHLY_RATING("Monthly Rating", "मासिक मूल्याङ्कन"),
    MONTHLY_THEME("Monthly Theme", "मासिक विषय"),
    MONTHS_SHORT("m", "म"),
    MONTH_APR("Apr", "अप्रिल"),
    MONTH_AUG("Aug", "अगस्ट"),
    MONTH_DEC("Dec", "डिसेम्बर"),
    MONTH_FEB("Feb", "फेब्रुअरी"),
    MONTH_JAN("Jan", "जनवरी"),
    MONTH_JUL("Jul", "जुलाई"),
    MONTH_JUN("Jun", "जुन"),
    MONTH_MAR("Mar", "मार्च"),
    MONTH_MAY("May", "मे"),
    MONTH_NOV("Nov", "नोभेम्बर"),
    MONTH_OCT("Oct", "अक्टोबर"),
    MONTH_SEP("Sep", "सेप्टेम्बर"),
    MOON_AQUARIUS("Your emotional nature is detached and humanitarian. You process feelings intellectually and value emotional freedom.",
        "तपाईंको भावनात्मक स्वभाव अलग र मानवतावादी छ। तपाईं भावनाहरूलाई बौद्धिक रूपमा प्रशोधन गर्नुहुन्छ र भावनात्मक स्वतन्त्रतालाई मूल्य दिनुहुन्छ।"),
    MOON_ARIES("Your emotional nature is fiery and spontaneous. You react quickly to situations and need independence in emotional expression.",
        "तपाईंको भावनात्मक स्वभाव अग्निमय र स्वत:स्फूर्त छ। तपाईं परिस्थितिहरूमा छिटो प्रतिक्रिया दिनुहुन्छ र भावनात्मक अभिव्यक्तिमा स्वतन्त्रता चाहिन्छ।"),
    MOON_BRIGHTNESS_AVERAGE("Average Moon", "औसत चन्द्र"),
    MOON_BRIGHTNESS_BRIGHT("Bright Moon", "उज्यालो चन्द्र"),
    MOON_BRIGHTNESS_DIM("Dim Moon", "धमिलो चन्द्र"),
    MOON_BRIGHTNESS_FULL("Full Moon", "पूर्णिमा"),
    MOON_BRIGHTNESS_NEW("New Moon", "अमावस्या"),
    MOON_CANCER("Your emotional nature is deeply sensitive and nurturing. You have strong intuition and need emotional security above all.",
        "तपाईंको भावनात्मक स्वभाव गहिरो संवेदनशील र पालनपोषण गर्ने छ। तपाईंसँग बलियो अन्तर्ज्ञान छ र सबैभन्दा माथि भावनात्मक सुरक्षा चाहिन्छ।"),
    MOON_CAPRICORN("Your emotional nature is controlled and responsible. You may suppress feelings for duty but are deeply loyal.",
        "तपाईंको भावनात्मक स्वभाव नियन्त्रित र जिम्मेवार छ। तपाईंले कर्तव्यको लागि भावनाहरू दबाउन सक्नुहुन्छ तर गहिरो वफादार हुनुहुन्छ।"),
    MOON_FIRST_QUARTER("First Quarter Moon", "पहिलो चौथाई चन्द्रमा"),
    MOON_FIRST_QUARTER_DESC("Good for taking action", "कार्य गर्नको लागि राम्रो"),
    MOON_FULL("Full Moon", "पूर्णिमा"),
    MOON_FULL_DESC("Emotional peak - completion energy", "भावनात्मक शिखर - पूर्णता ऊर्जा"),
    MOON_GEMINI("Your emotional nature is curious and changeable. You process feelings intellectually and need mental stimulation.",
        "तपाईंको भावनात्मक स्वभाव जिज्ञासु र परिवर्तनशील छ। तपाईं भावनाहरूलाई बौद्धिक रूपमा प्रशोधन गर्नुहुन्छ र मानसिक उत्तेजना चाहिन्छ।"),
    MOON_HEALTH("Moon Health Influence", "चन्द्रमा स्वास्थ्य प्रभाव"),
    MOON_LABEL("Moon", "चन्द्र"),
    MOON_LEO("Your emotional nature is warm, generous, and dramatic. You need recognition and express feelings openly and passionately.",
        "तपाईंको भावनात्मक स्वभाव न्यानो, उदार र नाटकीय छ। तपाईंलाई मान्यता चाहिन्छ र भावनाहरू खुलेर र जोशपूर्ण रूपमा व्यक्त गर्नुहुन्छ।"),
    MOON_LIBRA("Your emotional nature seeks harmony and partnership. You need balanced relationships and avoid emotional extremes.",
        "तपाईंको भावनात्मक स्वभावले सामंजस्य र साझेदारी खोज्छ। तपाईंलाई सन्तुलित सम्बन्धहरू चाहिन्छ र भावनात्मक चरमहरूबाट बच्नुहुन्छ।"),
    MOON_LONGITUDE("Moon Longitude", "चन्द्र देशान्तर"),
    MOON_PISCES("Your emotional nature is deeply empathetic and intuitive. You absorb others' feelings and need spiritual outlets.",
        "तपाईंको भावनात्मक स्वभाव गहिरो सहानुभूतिपूर्ण र अन्तर्ज्ञानी छ। तपाईं अरूको भावनाहरू सोस्नुहुन्छ र आध्यात्मिक आउटलेटहरू चाहिन्छ।"),
    MOON_SAGITTARIUS("Your emotional nature is optimistic and freedom-loving. You need space to explore and grow emotionally.",
        "तपाईंको भावनात्मक स्वभाव आशावादी र स्वतन्त्रता-प्रेमी छ। तपाईंलाई भावनात्मक रूपमा अन्वेषण र बढ्न ठाउँ चाहिन्छ।"),
    MOON_SCORPIO("Your emotional nature is intense and transformative. You feel deeply and may hide vulnerabilities behind a strong exterior.",
        "तपाईंको भावनात्मक स्वभाव तीव्र र परिवर्तनकारी छ। तपाईं गहिरो रूपमा महसुस गर्नुहुन्छ र बलियो बाहिरी आवरण पछाडि कमजोरीहरू लुकाउन सक्नुहुन्छ।"),
    MOON_SIGN("Moon Sign", "चन्द्र राशि"),
    MOON_TAURUS("Your emotional nature is stable and sensual. You seek comfort and security, and are deeply loyal in relationships.",
        "तपाईंको भावनात्मक स्वभाव स्थिर र संवेदनशील छ। तपाईं आराम र सुरक्षा खोज्नुहुन्छ, र सम्बन्धहरूमा गहिरो वफादार हुनुहुन्छ।"),
    MOON_VIRGO("Your emotional nature is practical and analytical. You express care through service and may overthink feelings.",
        "तपाईंको भावनात्मक स्वभाव व्यावहारिक र विश्लेषणात्मक छ। तपाईं सेवा मार्फत हेरचाह व्यक्त गर्नुहुन्छ र भावनाहरूको बारेमा बढी सोच्न सक्नुहुन्छ।"),
    MOTHER_INFLUENCE_EDU("Mother's Influence on Education", "शिक्षामा आमाको प्रभाव"),
    MOTHER_RELATIONSHIP("Relationship with Mother", "आमासँगको सम्बन्ध"),
    MSG_MAY_TAKE_MOMENT("This may take a moment", "यसमा केही समय लाग्न सक्छ"),
    MUHURTA_ABHIJIT("Abhijit Muhurta", "अभिजित मुहूर्त"),
    MUHURTA_ACTIVE("ACTIVE", "सक्रिय"),
    MUHURTA_AUSPICIOUS_TIME("Auspicious Time", "शुभ समय"),
    MUHURTA_AVERAGE_TIME("Average Time", "सामान्य समय"),
    MUHURTA_AVOID_ACTIVITIES("Activities to Avoid", "बच्नुपर्ने गतिविधिहरू"),
    MUHURTA_BRAHMA("Brahma Muhurta", "ब्रह्म मुहूर्त"),
    MUHURTA_CALCULATING("Calculating muhurta...", "मुहूर्त गणना गर्दै..."),
    MUHURTA_CHOGHADIYA("Choghadiya", "चौघडिया"),
    MUHURTA_CHOGHADIYA_SUFFIX("Choghadiya: %s", "चौघडिया: %s"),
    MUHURTA_DATE_RANGE("Date Range", "मिति दायरा"),
    MUHURTA_DATE_RANGE_LABEL("Date Range", "मिति दायरा"),
    MUHURTA_DAY_CHOGHADIYA("Day Choghadiya", "दिनको चोघड़िया"),
    MUHURTA_DETAIL_CHOGHADIYA("Choghadiya", "चोघड़िया"),
    MUHURTA_DETAIL_DAY("Day", "दिन"),
    MUHURTA_ERROR("Something went wrong", "केही गलत भयो"),
    MUHURTA_EVENT_BUSINESS_START("Business Start", "व्यापार शुरुआत"),
    MUHURTA_EVENT_CONSTRUCTION("Construction", "निर्माण"),
    MUHURTA_EVENT_EDUCATION_START("Education Start", "शिक्षा शुरुआत"),
    MUHURTA_EVENT_ENGAGEMENT("Engagement", "सगाई"),
    MUHURTA_EVENT_GRIHA_PRAVESH("Griha Pravesh", "गृह प्रवेश"),
    MUHURTA_EVENT_INVESTMENT("Investment", "लगानी"),
    MUHURTA_EVENT_MARRIAGE("Marriage", "विवाह"),
    MUHURTA_EVENT_MEDICAL_TREATMENT("Medical Treatment", "चिकित्सा उपचार"),
    MUHURTA_EVENT_MUNDAN("Mundan", "चौलकर्म"),
    MUHURTA_EVENT_NAME_CEREMONY("Name Ceremony", "नामकरण"),
    MUHURTA_EVENT_TRAVEL("Travel", "यात्रा"),
    MUHURTA_EVENT_UPANAYANA("Upanayana", "ब्रतबन्ध"),
    MUHURTA_EVENT_VEHICLE_PURCHASE("Vehicle Purchase", "सवारी खरिद"),
    MUHURTA_FIND("Find Auspicious Times", "शुभ समय खोज्नुहोस्"),
    MUHURTA_FINDING("Finding auspicious times...", "शुभ समय खोज्दै..."),
    MUHURTA_FIND_AUSPICIOUS("Find Auspicious Dates", "शुभ मितिहरू खोज्नुहोस्"),
    MUHURTA_FIND_DATES("Find Auspicious Dates", "शुभ मिति खोज्नुहोस्"),
    MUHURTA_FROM("From", "बाट"),
    MUHURTA_GULIKA_KAAL("Gulika Kaal", "गुलिका काल"),
    MUHURTA_GULIKA_KALA("Gulika Kala", "गुलिक काल"),
    MUHURTA_GULIKA_KALA_DESC("Avoid new beginnings", "नयाँ शुरुआत बच्नुहोस्"),
    MUHURTA_HORA_SUFFIX("Hora: %s", "होरा: %s"),
    MUHURTA_INAUSPICIOUS_PERIODS("Inauspicious Periods", "अशुभ अवधिहरू"),
    MUHURTA_KARANA("Karana", "करण"),
    MUHURTA_NEXT_DAY("Next day", "अर्को दिन"),
    MUHURTA_NEXT_DAY_A11Y("Next day", "अर्को दिन"),
    MUHURTA_NOW("NOW", "अहिले"),
    MUHURTA_NO_RESULTS("No Auspicious Times Found", "कुनै शुभ समय फेला परेन"),
    MUHURTA_NO_RESULTS_HELP("Try expanding your date range", "मिति दायरा विस्तार गर्ने प्रयास गर्नुहोस्"),
    MUHURTA_PANCHANGA("Panchanga", "पञ्चाङ्ग"),
    MUHURTA_PERIODS("%d periods", "%d अवधिहरू"),
    MUHURTA_PREV_DAY("Previous day", "अघिल्लो दिन"),
    MUHURTA_PREV_DAY_A11Y("Previous day", "अघिल्लो दिन"),
    MUHURTA_RAHUKALA("Rahukala", "राहुकाल"),
    MUHURTA_RAHUKALA_DESC("Avoid important work", "महत्त्वपूर्ण कार्य बच्नुहोस्"),
    MUHURTA_RAHU_KAAL("Rahu Kaal", "राहुकाल"),
    MUHURTA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    MUHURTA_RESULTS("Auspicious Muhurtas", "शुभ मुहूर्तहरू"),
    MUHURTA_RESULTS_COUNT("%d found", "%d फेला परेको"),
    MUHURTA_RESULTS_TITLE("Auspicious Times", "शुभ समयहरू"),
    MUHURTA_SCORE("Score", "अंक"),
    MUHURTA_SEARCHING("Searching...", "खोज्दै..."),
    MUHURTA_SEARCH_EMPTY("Search for Auspicious Times", "शुभ समय खोज्नुहोस्"),
    MUHURTA_SEARCH_ERROR("Search Failed", "खोज असफल"),
    MUHURTA_SEARCH_HELP("Select an activity and date range to find the most favorable muhurtas", "सबैभन्दा अनुकूल मुहूर्तहरू खोज्न गतिविधि र मिति दायरा छान्नुहोस्"),
    MUHURTA_SEARCH_RESULTS("Search Results", "खोज परिणामहरू"),
    MUHURTA_SELECT_ACTIVITY("Select Activity", "गतिविधि चयन गर्नुहोस्"),
    MUHURTA_SELECT_DATE("Select Date", "मिति चयन गर्नुहोस्"),
    MUHURTA_SELECT_EVENT("Select Event Type", "घटना प्रकार छान्नुहोस्"),
    MUHURTA_SUITABLE_ACTIVITIES("Suitable Activities", "उपयुक्त गतिविधिहरू"),
    MUHURTA_SUNRISE_SUNSET("Sunrise / Sunset", "सूर्योदय / सूर्यास्त"),
    MUHURTA_TITHI("Tithi", "तिथि"),
    MUHURTA_TITLE("Muhurta Finder", "मुहूर्त खोजकर्ता"),
    MUHURTA_TO("To", "सम्म"),
    MUHURTA_TODAY("Today", "आज"),
    MUHURTA_VARA("Vara", "वार"),
    MUHURTA_YAMAGHANTA("Yamaghanta", "यमघन्ता"),
    MUHURTA_YAMAGHANTA_DESC("Avoid travel", "यात्रा बच्नुहोस्"),
    MUHURTA_YAMA_GHANTAKA("Yama Ghantaka", "यम घण्टक"),
    MUHURTA_YOGA("Yoga", "योग"),
    NAK_ASHWINI_CAREERS("Medical field, Emergency services, Sports, Transportation, Veterinary science", "चिकित्सा क्षेत्र, आपतकालीन सेवा, खेलकुद, यातायात, पशु चिकित्सा विज्ञान"),
    NAK_ASHWINI_CHARS("Ashwini natives are quick, energetic, and pioneering. They have natural healing abilities and are often the first to try new things. Speed and initiative are their hallmarks.", "अश्विनी जातकहरू छिटो, ऊर्जावान र अग्रगामी हुन्छन्। तिनीहरूसँग प्राकृतिक उपचार क्षमताहरू हुन्छन् र प्रायः नयाँ कुराहरू प्रयास गर्ने पहिलो हुन्छन्। गति र पहल तिनीहरूको चिनारी हो।"),
    NAK_ASHWINI_SYMBOL("Horse's Head", "घोडाको टाउको"),
    NAK_BENEFIT_BLESSING("Invokes blessing of nakshatra deity", "नक्षत्र देवताको आशीर्वाद आह्वान गर्दछ"),
    NAK_BENEFIT_COMPLEMENT("Complements planetary remedies", "ग्रह उपचारहरूलाई पूरक बनाउँछ"),
    NAK_BENEFIT_FINE_TUNE("Fine-tunes remedy approach", "उपचार दृष्टिकोणलाई सुक्ष्म बनाउँछ"),
    NAK_BENEFIT_SPECIFIC("Addresses nakshatra-specific influences", "नक्षत्र-विशेष प्रभावहरूलाई सम्बोधन गर्दछ"),
    NAK_BHARANI_CAREERS("Midwifery, Funeral services, Entertainment, Creative arts, Psychology", "प्रसूति सेवा, अन्त्येष्टि सेवा, मनोरञ्जन, सिर्जनात्मक कला, मनोविज्ञान"),
    NAK_BHARANI_CHARS("Bharani natives are creative, responsible, and can bear heavy burdens. They understand life's transformative nature and often work with matters of birth, death, and transformation.", "भरणी जातकहरू सिर्जनशील, जिम्मेवार हुन्छन् र ठूलो बोझ उठाउन सक्छन्। तिनीहरू जीवनको परिवर्तनकारी प्रकृति बुझ्छन् र प्रायः जन्म, मृत्यु, र रूपान्तरणका विषयहरूसँग काम गर्छन्।"),
    NAK_BHARANI_SYMBOL("Yoni (Female reproductive organ)", "योनि (स्त्री प्रजनन अंग)"),
    NAK_CAUTION_CHECK("Check Panchang for nakshatra transit days", "नक्षत्र गोचर दिनहरूको लागि पञ्चाङ्ग जाँच गर्नुहोस्"),
    NAK_CAUTION_COMBINE("Combine with main planetary remedies for best results", "उत्तम परिणामहरूको लागि मुख्य ग्रह उपचारहरूसँग मिलाउनुहोस्"),
    NAK_DEFAULT_CAREERS("Various fields depending on overall chart analysis", "समग्र कुण्डली विश्लेषणमा निर्भर गर्दै विभिन्न क्षेत्रहरू"),
    NAK_DEFAULT_CHARS("%s is ruled by %s. Natives are influenced by the deity %s.", "%s %s द्वारा शासित छ। जातकहरू देवता %s द्वारा प्रभावित हुन्छन्।"),
    NAK_DESC_ANURADHA("Anuradha is ruled by Saturn and represents devotion and friendship. Those born here are loyal, cooperative, and succeed in foreign lands. They possess the ability to create harmony and meaningful connections.", "अनुराधा शनिद्वारा शासित छ र भक्ति तथा मित्रताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू वफादार, सहयोगी हुन्छन् र विदेशी भूमिमा सफल हुन्छन्। तिनीहरूसँग सद्भाव र अर्थपूर्ण सम्बन्धहरू सिर्जना गर्ने क्षमता हुन्छ।"),
    NAK_DESC_ARDRA("Ardra is ruled by Rahu and represents transformation through storms. Those born here experience intense emotions and transformative life events. They possess sharp intellect and the ability to destroy old patterns for renewal.", "आर्द्रा राहुद्वारा शासित छ र आँधीबेहरी मार्फत रूपान्तरणको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूले तीव्र भावनाहरू र परिवर्तनकारी जीवन घटनाहरू अनुभव गर्छन्। तिनीहरूसँग तीक्ष्ण बुद्धि र नवीकरणका लागि पुराना ढाँचाहरू नष्ट गर्ने क्षमता हुन्छ।"),
    NAK_DESC_ASHLESHA("Ashlesha is ruled by Mercury and represents serpentine wisdom. Those born here possess deep intuition, hypnotic abilities, and kundalini energy. They can be secretive and possess transformative mystical powers.", "आश्लेषा बुधद्वारा शासित छ र सर्प ज्ञानको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग गहिरो अन्तर्ज्ञान, सम्मोहक क्षमता र कुण्डलिनी ऊर्जा हुन्छ। तिनीहरू गोप्य हुन सक्छन् र परिवर्तनकारी रहस्यमय शक्तिहरू हुन्छन्।"),
    NAK_DESC_ASHWINI("Ashwini is the first nakshatra, ruled by Ketu. Those born under this star possess quick healing abilities, spontaneity, and pioneering spirit. They are energetic, courageous, and drawn to helping others. Associated with speed, initiative, and new beginnings.", "अश्विनी पहिलो नक्षत्र हो, केतुद्वारा शासित। यस नक्षत्रमा जन्मेकाहरूसँग छिटो निको पार्ने क्षमता, स्वाभाविकता र अग्रगामी भावना हुन्छ। तिनीहरू ऊर्जावान, साहसी र अरूलाई मद्दत गर्न आकर्षित हुन्छन्। गति, पहल र नयाँ सुरुवातसँग सम्बन्धित।"),
    NAK_DESC_BHARANI("Bharani is ruled by Venus and represents the power of transformation. Those born here possess strong will, creativity, and the ability to bear great responsibilities. Associated with birth, death, and transformation cycles.", "भरणी शुक्रद्वारा शासित छ र रूपान्तरणको शक्ति प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग बलियो इच्छाशक्ति, सिर्जनशीलता र ठूलो जिम्मेवारी वहन गर्ने क्षमता हुन्छ। जन्म, मृत्यु र रूपान्तरण चक्रहरूसँग सम्बन्धित।"),
    NAK_DESC_CHITRA("Chitra is ruled by Mars and represents brilliant creativity. Those born here possess artistic talent, attention to detail, and the ability to create beautiful things. Associated with architecture, design, and craftsmanship.", "चित्रा मंगलद्वारा शासित छ र उत्कृष्ट सिर्जनशीलताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग कलात्मक प्रतिभा, विवरणमा ध्यान र सुन्दर चीजहरू सिर्जना गर्ने क्षमता हुन्छ। वास्तुकला, डिजाइन र शिल्पकलासँग सम्बन्धित।"),
    NAK_DESC_DHANISHTHA("Dhanishtha is ruled by Mars and represents wealth and musical talent. Those born here possess rhythm, prosperity consciousness, and adaptability. Associated with fame, wealth, and artistic expression.", "धनिष्ठा मंगलद्वारा शासित छ र धन तथा सांगीतिक प्रतिभाको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग लय, समृद्धि चेतना र अनुकूलनशीलता हुन्छ। प्रसिद्धि, धन र कलात्मक अभिव्यक्तिसँग सम्बन्धित।"),
    NAK_DESC_HASTA("Hasta is ruled by the Moon and represents skill and dexterity. Those born here are clever, resourceful, and possess healing hands. They excel in crafts, arts, and activities requiring manual dexterity.", "हस्त चन्द्रमाद्वारा शासित छ र सीप तथा निपुणताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू चलाख, स्रोतसाधन सम्पन्न हुन्छन् र निको पार्ने हातहरू हुन्छन्। तिनीहरू हस्तकला, कला र म्यानुअल निपुणता चाहिने गतिविधिहरूमा उत्कृष्ट हुन्छन्।"),
    NAK_DESC_JYESHTHA("Jyeshtha is ruled by Mercury and represents seniority and protection. Those born here possess leadership qualities, protective nature, and may face karmic challenges. They often rise to positions of authority and responsibility.", "ज्येष्ठा बुधद्वारा शासित छ र वरिष्ठता तथा सुरक्षाको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग नेतृत्व गुणहरू, सुरक्षात्मक स्वभाव हुन्छ र कर्मिक चुनौतीहरूको सामना गर्न सक्छन्। तिनीहरू प्रायः अधिकार र जिम्मेवारीको पदमा पुग्छन्।"),
    NAK_DESC_KRITTIKA("Krittika is ruled by the Sun and represents purifying fire. Those born here possess sharp intellect, determination, and the ability to cut through illusions. They are often leaders with strong principles and purifying influence.", "कृत्तिका सूर्यद्वारा शासित छ र शुद्धिकरण गर्ने आगोको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग तीक्ष्ण बुद्धि, दृढ संकल्प र भ्रमहरू चिर्ने क्षमता हुन्छ। तिनीहरू प्रायः बलियो सिद्धान्त र शुद्धिकरण प्रभाव भएका नेताहरू हुन्।"),
    NAK_DESC_MAGHA("Magha is ruled by Ketu and represents ancestral power and royal heritage. Those born here possess natural authority, connection to lineage, and leadership qualities. They honor traditions and carry ancestral blessings.", "मघा केतुद्वारा शासित छ र पैतृक शक्ति तथा शाही सम्पदाको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग प्राकृतिक अधिकार, वंशसँगको सम्बन्ध र नेतृत्व गुणहरू हुन्छन्। तिनीहरू परम्पराहरूको सम्मान गर्छन् र पैतृक आशीर्वाद बोक्छन्।"),
    NAK_DESC_MRIGASHIRA("Mrigashira is ruled by Mars and represents the searching nature. Those born here are curious, gentle, and always seeking. They possess artistic sensibilities and are drawn to exploration and research.", "मृगशिरा मंगलद्वारा शासित छ र खोजी गर्ने प्रकृतिको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू जिज्ञासु, कोमल र सधैं खोजी गरिरहने हुन्छन्। तिनीहरूसँग कलात्मक संवेदनशीलता हुन्छ र अन्वेषण तथा अनुसन्धानप्रति आकर्षित हुन्छन्।"),
    NAK_DESC_MULA("Mula is ruled by Ketu and represents getting to the root of things. Those born here experience transformative life events that lead to spiritual awakening. Associated with investigation, research, and uprooting the old.", "मूल केतुद्वारा शासित छ र कुराको जडसम्म पुग्ने प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूले परिवर्तनकारी जीवन घटनाहरू अनुभव गर्छन् जसले आध्यात्मिक जागरणतिर लैजान्छ। अनुसन्धान, खोज र पुरानो उखेल्नेसँग सम्बन्धित।"),
    NAK_DESC_PUNARVASU("Punarvasu is ruled by Jupiter and represents renewal and return to light. Those born here possess optimism, philosophical nature, and the ability to bounce back from difficulties. Associated with safety, home, and nurturing.", "पुनर्वसु बृहस्पतिद्वारा शासित छ र नवीकरण तथा प्रकाशमा फिर्तीको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग आशावाद, दार्शनिक स्वभाव र कठिनाइहरूबाट उम्किने क्षमता हुन्छ। सुरक्षा, घर र पोषणसँग सम्बन्धित।"),
    NAK_DESC_PURVA_ASHADHA("Purva Ashadha is ruled by Venus and represents invincible victory. Those born here possess charisma, philosophical nature, and the ability to influence others. They are optimistic and believe in ultimate success.", "पूर्वाषाढा शुक्रद्वारा शासित छ र अजय विजयको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग क्यािज्मा, दार्शनिक स्वभाव र अरूलाई प्रभाव पार्ने क्षमता हुन्छ। तिनीहरू आशावादी हुन्छन् र अन्तिम सफलतामा विश्वास गर्छन्।"),
    NAK_DESC_PURVA_BHADRAPADA("Purva Bhadrapada is ruled by Jupiter and represents spiritual fire. Those born here possess intensity, occult interests, and transformative abilities. Associated with purification through spiritual heat and sacrifice.", "पूर्वा भाद्रपद बृहस्पतिद्वारा शासित छ र आध्यात्मिक अग्निको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग तीव्रता, तान्त्रिक रुचि र परिवर्तनकारी क्षमताहरू हुन्छन्। आध्यात्मिक ताप र त्याग मार्फत शुद्धिकरणसँग सम्बन्धित।"),
    NAK_DESC_PURVA_PHALGUNI("Purva Phalguni is ruled by Venus and represents creative pleasure and luxury. Those born here enjoy life's pleasures, are artistic, and possess natural charm. Associated with love, creativity, and enjoyment.", "पूर्वा फाल्गुनी शुक्रद्वारा शासित छ र रचनात्मक आनन्द तथा विलासिताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू जीवनका सुखहरूको आनन्द लिन्छन्, कलात्मक हुन्छन् र प्राकृतिक आकर्षण हुन्छन्। प्रेम, सिर्जनशीलता र रमाइलोसँग सम्बन्धित।"),
    NAK_DESC_PUSHYA("Pushya is considered the most auspicious nakshatra for most activities, ruled by Saturn. Those born here are nurturing, wise, and spiritually inclined. They possess the ability to nourish and support others' growth.", "पुष्यलाई अधिकांश गतिविधिहरूको लागि सबैभन्दा शुभ नक्षत्र मानिन्छ, शनिद्वारा शासित। यहाँ जन्मेकाहरू पोषण गर्ने, बुद्धिमान र आध्यात्मिक झुकाव भएका हुन्छन्। तिनीहरूसँग अरूको वृद्धिलाई पोषण र समर्थन गर्ने क्षमता हुन्छ।"),
    NAK_DESC_REVATI("Revati is the final nakshatra, ruled by Mercury. Those born here are nurturing, wealthy, and possess safe travel. Associated with protection, guidance, and completion of cycles. Represents the journey's end and new beginnings.", "रेवती अन्तिम नक्षत्र हो, बुधद्वारा शासित। यहाँ जन्मेकाहरू पोषण गर्ने, धनी हुन्छन् र सुरक्षित यात्रा गर्छन्। सुरक्षा, मार्गदर्शन र चक्रहरूको पूर्णतासँग सम्बन्धित। यात्राको अन्त्य र नयाँ सुरुवातको प्रतिनिधित्व गर्छ।"),
    NAK_DESC_ROHINI("Rohini is the most fertile nakshatra, ruled by the Moon. Those born here possess beauty, creativity, and material abundance. They are charming, artistic, and have strong desires. The Moon is exalted in this nakshatra.", "रोहिणी सबैभन्दा उर्वर नक्षत्र हो, चन्द्रमाद्वारा शासित। यहाँ जन्मेकाहरूसँग सौन्दर्य, सिर्जनशीलता र भौतिक प्रचुरता हुन्छ। तिनीहरू आकर्षक, कलात्मक र बलियो इच्छाहरू भएका हुन्छन्। चन्द्रमा यस नक्षत्रमा उच्च हुन्छ।"),
    NAK_DESC_SHATABHISHA("Shatabhisha is ruled by Rahu and represents healing and veiling. Those born here possess healing abilities, secretive nature, and interest in mysteries. Associated with alternative healing and unconventional approaches.", "शतभिषा राहुद्वारा शासित छ र निको पार्ने तथा लुकाउने प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग निको पार्ने क्षमता, गोप्य स्वभाव र रहस्यहरूमा रुचि हुन्छ। वैकल्पिक उपचार र अपरम्परागत दृष्टिकोणहरूसँग सम्बन्धित।"),
    NAK_DESC_SHRAVANA("Shravana is ruled by the Moon and represents learning through listening. Those born here are wise, knowledgeable, and possess excellent communication skills. Associated with preservation of knowledge and teaching.", "श्रवण चन्द्रमाद्वारा शासित छ र सुनेर सिक्ने प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू बुद्धिमान, ज्ञानी हुन्छन् र उत्कृष्ट सञ्चार सीपहरू हुन्छन्। ज्ञानको संरक्षण र शिक्षणसँग सम्बन्धित।"),
    NAK_DESC_SWATI("Swati is ruled by Rahu and represents independence and flexibility. Those born here are adaptable, diplomatic, and value freedom. Like the wind, they can navigate various situations with grace.", "स्वाति राहुद्वारा शासित छ र स्वतन्त्रता तथा लचिलोपनको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू अनुकूलनशील, कूटनीतिक हुन्छन् र स्वतन्त्रताको कदर गर्छन्। हावा जस्तै, तिनीहरू विभिन्न परिस्थितिहरूमा ग्रेसका साथ नेभिगेट गर्न सक्छन्।"),
    NAK_DESC_UTTARA_ASHADHA("Uttara Ashadha is ruled by the Sun and represents final victory. Those born here achieve lasting success through righteousness and perseverance. They are principled, responsible, and earn respect through merit.", "उत्तराषाढा सूर्यद्वारा शासित छ र अन्तिम विजयको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूले धार्मिकता र लगनशीलता मार्फत स्थायी सफलता प्राप्त गर्छन्। तिनीहरू सिद्धान्तवादी, जिम्मेवार हुन्छन् र योग्यता मार्फत सम्मान कमाउँछन्।"),
    NAK_DESC_UTTARA_BHADRAPADA("Uttara Bhadrapada is ruled by Saturn and represents spiritual depth. Those born here possess wisdom, self-control, and compassionate nature. Associated with enlightenment, renunciation, and spiritual attainment.", "उत्तरा भाद्रपद शनिद्वारा शासित छ र आध्यात्मिक गहिराइको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग ज्ञान, आत्म-नियन्त्रण र दयालु स्वभाव हुन्छ। ज्ञानोदय, वैराग्य र आध्यात्मिक प्राप्तिसँग सम्बन्धित।"),
    NAK_DESC_UTTARA_PHALGUNI("Uttara Phalguni is ruled by the Sun and represents lasting prosperity. Those born here are generous, friendly, and establish lasting partnerships. They excel in leadership and creating stable foundations.", "उत्तरा फाल्गुनी सूर्यद्वारा शासित छ र स्थायी समृद्धिको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू उदार, मिलनसार हुन्छन् र स्थायी साझेदारीहरू स्थापना गर्छन्। तिनीहरू नेतृत्व र स्थिर जग निर्माणमा उत्कृष्ट हुन्छन्।"),
    NAK_DESC_VISHAKHA("Vishakha is ruled by Jupiter and represents determined pursuit of goals. Those born here possess single-pointed focus, ambition, and the ability to achieve their objectives. Associated with transformation and success.", "विशाखा बृहस्पतिद्वारा शासित छ र लक्ष्यहरूको दृढ खोजको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग एकाग्र ध्यान, महत्त्वाकांक्षा र आफ्ना उद्देश्यहरू प्राप्त गर्ने क्षमता हुन्छ। रूपान्तरण र सफलतासँग सम्बन्धित।"),
    NAK_ROHINI_CAREERS("Fashion, Beauty industry, Agriculture, Music, Hospitality", "फेसन, सौन्दर्य उद्योग, कृषि, संगीत, आतिथ्य"),
    NAK_ROHINI_CHARS("Rohini natives are attractive, artistic, and materialistic in a positive way. They appreciate beauty and luxury. Strong creative and productive abilities.", "रोहिणी जातकहरू आकर्षक, कलात्मक र सकारात्मक रूपमा भौतिकवादी हुन्छन्। तिनीहरू सौन्दर्य र विलासिताको कदर गर्छन्। बलियो सिर्जनात्मक र उत्पादक क्षमताहरू।"),
    NAK_ROHINI_SYMBOL("Ox Cart / Chariot", "गोरु गाडा / रथ"),
    NATIVE_ANALYSIS_SUBTITLE("Comprehensive Life Profile", "व्यापक जीवन प्रोफाइल"),
    NATIVE_ANALYSIS_TITLE("Native Analysis", "जातक विश्लेषण"),
    NATURE_BENEFIC("Benefic", "शुभ"),
    NATURE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    NATURE_KARMIC("Karmic", "कार्मिक"),
    NATURE_MALEFIC("Malefic", "अशुभ"),
    NATURE_MIXED("Mixed", "मिश्रित"),
    NATURE_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
    NAV_BACK("Back", "पछाडि"),
    NAV_CHAT("Chat", "कुराकानी"),
    NAV_HOME("Home", "गृह"),
    NAV_INSIGHTS("Insights", "अन्तर्दृष्टि"),
    NAV_NAVIGATE_BACK("Navigate back", "पछाडि जानुहोस्"),
    NAV_NEXT("Next", "अर्को"),
    NAV_NEXT_DAY("Next day", "अर्को दिन"),
    NAV_NEXT_YEAR("Next year", "अर्को वर्ष"),
    NAV_PREVIOUS("Previous", "अघिल्लो"),
    NAV_PREVIOUS_DAY("Previous day", "अघिल्लो दिन"),
    NAV_PREVIOUS_YEAR("Previous year", "अघिल्लो वर्ष"),
    NAV_SETTINGS("Settings", "सेटिङहरू"),
    NEEDS_ATTENTION("Needs Attention", "ध्यान आवश्यक"),
    NEEDS_FOCUS("Needs Focus", "ध्यान दिनुपर्ने"),
    NEED_CONNECTION("Need for Connection", "सम्बन्धको आवश्यकता"),
    NEED_FREEDOM("Need for Freedom", "स्वतन्त्रताको आवश्यकता"),
    NEED_RECOGNITION("Need for Recognition", "मान्यताको आवश्यकता"),
    NEED_SECURITY("Need for Security", "सुरक्षाको आवश्यकता"),
    NETWORK_WEALTH("Wealth Through Networks", "नेटवर्कहरू मार्फत धन"),
    NEUTRAL("Neutral", "तटस्थ"),
    NEUTRAL_INFLUENCES("Neutral influences", "तटस्थ प्रभावहरू"),
    NEXT_LABEL("Next", "अर्को"),
    NIGHT_BIRTH("Night Birth", "रात्रि जन्म"),
    NIGHT_BIRTH_CHART("Night Birth Chart", "रात्रि जन्म कुण्डली"),
    NINTH_DHARMA_LORD("9th House Lord", "नवम भाव स्वामी"),
    NINTH_DHARMA_SIGN("9th House Sign", "नवम भाव राशि"),
    NINTH_HOUSE_LORD("9th House Lord", "नवम भाव स्वामी"),
    NINTH_HOUSE_SIGN("9th House Sign", "नवम भाव राशि"),
    NITYA_ABOUT_DESC("Nitya Yoga (Daily Yoga) is one of the five elements of the Panchanga (Hindu almanac).\n\nThere are 27 Nitya Yogas, each spanning 13Â°20' of the combined longitude of Sun and Moon.\n\nCalculation:\nNitya Yoga = (Sun longitude + Moon longitude) Ã· 13Â°20'\n\nThese yogas indicate the general auspiciousness of a moment and are used in Muhurta (electional astrology) to select favorable times for important activities.\n\nEach yoga is ruled by a planet and has specific characteristics affecting health, wealth, relationships, and spiritual matters.", "नित्य योग पञ्चाङ्गका पाँच अंगहरू मध्ये एक हो।\n\nत्यहाँ २७ नित्य योगहरू छन्, प्रत्येकले सूर्य र चन्द्रमाको संयुक्त देशान्तरको १३°२०' समेट्छ।\n\nगणना:\nनित्य योग = (सूर्य स्पष्ट + चन्द्र स्पष्ट) ÷ १३°२०'\n\nयी योगहरूले समयको सामान्य शुभतालाई संकेत गर्दछ र महत्त्वपूर्ण गतिविधिहरूको लागि शुभ समय छनौट गर्न मुहूर्तमा प्रयोग गरिन्छ।\n\nप्रत्येक योग एक ग्रहद्वारा शासित हुन्छ र यसले स्वास्थ्य, धन, सम्बन्ध र आध्यात्मिक मामिलाहरूलाई असर गर्ने विशिष्ट विशेषताहरू राख्छ।"),
    NITYA_ABOUT_TITLE("About Nitya Yoga", "नित्य योगको बारेमा"),
    NITYA_AVOID("Activities to Avoid", "बच्नुपर्ने गतिविधिहरू"),
    NITYA_CURRENT_PROGRESS("Progress in Current Yoga", "वर्तमान योगमा प्रगति"),
    NITYA_NATURE("Nature", "प्रकृति"),
    NITYA_NEXT("Next:", "अर्को:"),
    NITYA_NO_DATA_DESC("Create or select a birth chart to view Nitya Yoga analysis.", "नित्य योग विश्लेषण हेर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    NITYA_POSITION("Position", "स्थिति"),
    NITYA_PROGRESS("Progress", "प्रगति"),
    NITYA_REMAINING("remaining", "बाँकी"),
    NITYA_SCREEN_TITLE("Nitya Yoga", "नित्य योग"),
    NITYA_STRENGTH_MODERATE("Moderate", "मध्यम"),
    NITYA_STRENGTH_STRONG("Strong", "बलियो"),
    NITYA_STRENGTH_VERY_STRONG("Very Strong", "अत्यन्त बलियो"),
    NITYA_STRENGTH_VERY_WEAK("Very Weak", "अत्यन्त कमजोर"),
    NITYA_STRENGTH_WEAK("Weak", "कमजोर"),
    NITYA_SUBTITLE("27 Daily Yogas", "२७ दैनिक योगहरू"),
    NITYA_SUITABLE("Suitable Activities", "उपयुक्त गतिविधिहरू"),
    NO("No", "छैन"),
    NODAL_AXIS_EFFECTS("Nodal Axis Effects", "नोडल अक्ष प्रभावहरू"),
    NOT_APPLICABLE("Not Applicable", "लागू हुँदैन"),
    NOT_PRESENT("Not Present", "उपस्थित छैन"),
    NOT_SATISFIED("Not Satisfied", "सन्तुष्ट छैन"),
    NO_CHART_SELECTED("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
    NO_PROFILE_MESSAGE("Select or create a profile to view your personalized astrological insights.", "आफ्नो व्यक्तिगत ज्योतिष अन्तर्दृष्टि हेर्न प्रोफाइल छान्नुहोस् वा बनाउनुहोस्।"),
    NO_PROFILE_MESSAGE_LONG("Select or create a profile to view your personalized astrological insights and predictions", "आफ्नो व्यक्तिगत ज्योतिष अन्तर्दृष्टि र भविष्यवाणी हेर्न प्रोफाइल छान्नुहोस् वा बनाउनुहोस्"),
    NO_PROFILE_SELECTED("No Profile Selected", "कुनै प्रोफाइल छानिएको छैन"),
    NO_SAHAMS_FOUND("No Sahams found matching criteria", "मापदण्ड अनुरूप कुनै सहम फेला परेन"),
    NUM_0("0 Open - Total denial, delay, not now", "० खुला - पूर्ण अस्वीकार, ढिलाइ, अहिले होइन"),
    NUM_1("1 Open - Weak affirmation, much effort needed", "१ खुला - कमजोर पुष्टि, धेरै प्रयास चाहिन्छ"),
    NUM_2("2 Open - Partial success, obstacles remain", "२ खुला - आंशिक सफलता, बाधाहरू बाँकी"),
    NUM_3("3 Open - Favorable with conditions", "३ खुला - शर्तहरूसँग अनुकूल"),
    NUM_4("4 Open - Balanced outcome, transformation", "४ खुला - सन्तुलित परिणाम, रूपान्तरण"),
    NUM_5("5 Open - Good success likely", "५ खुला - राम्रो सफलता सम्भव"),
    NUM_6("6 Open - Strong positive indication", "६ खुला - बलियो सकारात्मक संकेत"),
    NUM_7("7 Open - Very favorable outcome", "७ खुला - अत्यन्त अनुकूल परिणाम"),
    NUM_8("8 Open - Complete success, divine blessing", "८ खुला - पूर्ण सफलता, दैवी आशीर्वाद"),
    NUM_INTERPRETATION("Shell Interpretation", "कौडी व्याख्या"),
    NUM_OPEN_SHELLS("Open Shells", "खुला कौडीहरू"),
    NUM_TITLE("Numerical Analysis", "संख्यात्मक विश्लेषण"),
    OBSTRUCTION("Obstruction", "बाधा"),
    OFFICE_DYNAMICS("Office Dynamics", "कार्यालय गतिशीलता"),
    OPPORTUNITY_ADVICE("How to Maximize", "अधिकतम कसरी गर्ने"),
    OPPORTUNITY_DURATION("Duration", "अवधि"),
    OPPORTUNITY_NAME("Window Name", "सञ्झ्याल नाम"),
    OPPORTUNITY_TITLE("Opportunity Windows", "अवसर सञ्झ्यालहरू"),
    OPPORTUNITY_TYPE("Opportunity Type", "अवसर प्रकार"),
    ORDINAL_ND("nd", "औं"),
    ORDINAL_RD("rd", "औं"),
    ORDINAL_ST("st", "औं"),
    ORDINAL_TH("th", "औं"),
    OVERALL_ADVICE("Overall Remedial Advice", "समग्र उपचारात्मक सल्लाह"),
    OWN_SIGN(" Strong in own sign.", " आफ्नो राशिमा बलियो।"),
    PADA_DESC_TEMPLATE("Pada %d falls in %s Navamsa, ruled by %s. This pada emphasizes the %s element qualities combined with the main nakshatra characteristics.", "पद %d %s नवांशमा पर्छ, जुन %s द्वारा शासित छ। यो पदले मुख्य नक्षत्र विशेषताहरूसँग संयुक्त %s तत्व गुणहरूलाई जोड दिन्छ।"),
    PADA_LABEL("Pada", "पाद"),
    PANCHA_ABOUT_DESC("Panch Mahapurusha Yoga (Five Great Person Yogas) are special planetary combinations that indicate exceptional qualities and achievements.\n\nThe five yogas are:\n• Ruchaka (Mars) - Courage, leadership, military prowess\n• Bhadra (Mercury) - Intelligence, communication, commerce\n• Hamsa (Jupiter) - Wisdom, spirituality, fortune\n• Malavya (Venus) - Beauty, luxury, artistic talents\n• Sasha (Saturn) - Discipline, authority, longevity\n\nFormation requirements:\nThe planet must be in a Kendra house (1st, 4th, 7th, or 10th) AND in its own sign or exaltation sign.\n\nHaving one or more of these yogas in a chart indicates the native will possess the exceptional qualities of that planet and achieve success in related areas.", "पञ्च महापुरुष योगहरू विशेष ग्रह संयोजनहरू हुन् जसले असाधारण गुणहरू र उपलब्धिहरूलाई संकेत गर्दछ।\n\nपाँच योगहरू हुन्:\n• रुचक (मंगल) - साहस, नेतृत्व, सैन्य कौशल\n• भद्र (बुध) - बुद्धि, सञ्चार, वाणिज्य\n• हंस (बृहस्पति) - ज्ञान, आध्यात्मिकता, भाग्य\n• मालव्य (शुक्र) - सौन्दर्य, विलासिता, कलात्मक प्रतिभा\n• शश (शनि) - अनुशासन, अधिकार, दीर्घायु\n\nबन्ने शर्तहरू:\nग्रह केन्द्र भाव (१, ४, ७, वा १०) मा हुनुपर्छ र आफ्नै राशि वा उच्च राशिमा हुनुपर्छ।\n\nकुण्डलीमा यी मध्ये एक वा बढी योगहरू हुनुले जातकमा त्यस ग्रहका असाधारण गुणहरू हुनेछन् र सम्बन्धित क्षेत्रमा सफलता प्राप्त गर्नेछन् भन्ने संकेत गर्दछ।"),
    PANCHA_ABOUT_TITLE("About Panch Mahapurusha Yoga", "पञ्च महापुरुष योगको बारेमा"),
    PANCHA_ACTIVATION_PERIODS("Activation Periods", "सक्रियता अवधिहरू"),
    PANCHA_ANALYZING("Analyzing Panch Mahapurusha Yogas...", "पञ्च महापुरुष योगहरू विश्लेषण गर्दै..."),
    PANCHA_AVERAGE("Average (3)", "औसत (३)"),
    PANCHA_BELOW_AVERAGE("Below Average (2)", "औसत भन्दा कम (२)"),
    PANCHA_CAREER("Career", "करियर"),
    PANCHA_COMBINED("Combined Effects", "संयुक्त प्रभावहरू"),
    PANCHA_DETAILS_EMPTY_DESC("This section will show details when Mahapurusha Yogas are present in the chart.", "यस खण्डले कुण्डलीमा महापुरुष योगहरू उपस्थित हुँदा विवरणहरू देखाउनेछ।"),
    PANCHA_EFFECTS_TITLE("%s Effects", "%s प्रभावहरू"),
    PANCHA_EXCELLENT("Excellent (5+)", "उत्कृष्ट (५+)"),
    PANCHA_GOOD("Good (4)", "राम्रो (४)"),
    PANCHA_MENTAL("Mental", "मानसिक"),
    PANCHA_NO_CHART_DESC("Create or select a birth chart to analyze Panch Mahapurusha Yogas.", "पञ्च महापुरुष योगहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    PANCHA_NO_YOGAS("No Yogas", "कुनै योग छैन"),
    PANCHA_NO_YOGAS_DESC("For a Mahapurusha Yoga to form, Mars, Mercury, Jupiter, Venus, or Saturn must be in Kendra (1,4,7,10) in its own or exaltation sign.", "महापुरुष योग बन्नको लागि, मंगल, बुध, बृहस्पति, शुक्र वा शनि केन्द्र (१, ४, ७, १०) मा आफ्नै वा उच्च राशिमा हुनुपर्छ।"),
    PANCHA_NO_YOGAS_DISPLAY("No Yogas to Display", "देखाउनको लागि कुनै योगहरू छैनन्"),
    PANCHA_PERIODS("Periods", "अवधिहरू"),
    PANCHA_PHYSICAL("Physical", "शारीरिक"),
    PANCHA_RECOMMENDATIONS_TITLE("%s Recommendations", "%s सिफारिसहरू"),
    PANCHA_RELATIONSHIPS("Relationships", "सम्बन्ध"),
    PANCHA_SCREEN_TITLE("Panch Mahapurusha Yoga", "पञ्च महापुरुष योग"),
    PANCHA_SPIRITUAL("Spiritual", "आध्यात्मिक"),
    PANCHA_STATUS_FOUND("Yoga(s) Found!", "योग(हरू) फेला पर्यो!"),
    PANCHA_STATUS_FOUND_DESC("You have %1\$d Panch Mahapurusha Yoga(s) in your chart", "तपाईंको कुण्डलीमा %1\$d पञ्च महापुरुष योग(हरू) छन्"),
    PANCHA_STATUS_NONE_DESC("None of the five Mahapurusha Yogas are formed", "पाँच महापुरुष योगहरू मध्ये कुनै पनि बनेको छैन"),
    PANCHA_STRENGTH("Strength", "बल"),
    PANCHA_SUBTITLE("Five Great Person Yogas", "पाँच महापुरुष योगहरू"),
    PANCHA_SYNERGIES("Synergies:", "समन्वयहरू:"),
    PANCHA_TIMING_LABEL("Timing: %s", "समय: %s"),
    PANCHA_WEAK("Weak (0-1)", "कमजोर (०-१)"),
    PARTNERSHIP_ENVIRONMENT("Partnership Environment", "साझेदारी वातावरण"),
    PARTNERSHIP_POTENTIAL("Partnership Potential", "साझेदारी क्षमता"),
    PARTNER_BACKGROUND("Partner Background", "साथी पृष्ठभूमि"),
    PARTNER_PERSONALITY("Partner Personality Traits", "साथी व्यक्तित्व गुणहरू"),
    PARTNER_PHYSICAL("Partner Physical Description", "साथी शारीरिक विवरण"),
    PARTNER_PROFESSION("Partner Profession Indicators", "साथी पेशा सूचकहरू"),
    PASSIVE_INCOME("Passive Income Indicators", "निष्क्रिय आय सूचकहरू"),
    PAST_LIFE_KARMA("Past Life Karma", "पूर्व जीवन कर्म"),
    PERIOD_ASHTAMA_SHANI("Ashtama Shani (Saturn in 8th from Moon)", "अष्टम शनि (चन्द्रमाबाट आठौंमा शनि)"),
    PERIOD_GENERIC("%1\$s transit in %2\$dth from Moon", "चन्द्रमाबाट %2\$dऔंमा %1\$s गोचर"),
    PERIOD_JUPITER_1("Jupiter over natal Moon - expansion and growth", "जन्म चन्द्रमामाथि बृहस्पति - विस्तार र वृद्धि"),
    PERIOD_JUPITER_5("Jupiter in 5th from Moon - creativity and children", "चन्द्रमाबाट पाँचौंमा बृहस्पति - सिर्जनशीलता र सन्तान"),
    PERIOD_JUPITER_9("Jupiter in 9th from Moon - fortune and dharma", "चन्द्रमाबाट नवौंमा बृहस्पति - भाग्य र धर्म"),
    PERIOD_JUPITER_GENERIC("Jupiter transit in %dth from Moon", "चन्द्रमाबाट %dऔंमा बृहस्पति गोचर"),
    PERIOD_KANTAK_SHANI("Kantak Shani (Saturn in 4th from Moon)", "कन्टक शनि (चन्द्रमाबाट चौथोमा शनि)"),
    PERIOD_KETU_GENERIC("Ketu transit in %dth from Moon - spiritual detachment", "चन्द्रमाबाट %dऔंमा केतु गोचर - आध्यात्मिक वैराग्य"),
    PERIOD_RAHU_GENERIC("Rahu transit in %dth from Moon - worldly desires amplified", "चन्द्रमाबाट %dऔंमा राहु गोचर - सांसारिक इच्छाहरू बढ्छ"),
    PERIOD_SADE_SATI_BEGIN("Sade Sati beginning phase (Saturn in 12th from Moon)", "साढे साती सुरु हुने चरण (चन्द्रमाबाट १२औंमा शनि)"),
    PERIOD_SADE_SATI_END("Sade Sati ending phase (Saturn in 2nd from Moon)", "साढे साती अन्त्य हुने चरण (चन्द्रमाबाट दोस्रोमा शनि)"),
    PERIOD_SADE_SATI_PEAK("Sade Sati peak phase (Saturn over natal Moon)", "साढे साती शिखर चरण (जन्म चन्द्रमामाथि शनि)"),
    PERIOD_SATURN_10("Saturn in 10th from Moon - career challenges and growth", "चन्द्रमाबाट दशौंमा शनि - करियर चुनौतीहरू र वृद्धि"),
    PERIOD_SATURN_7("Saturn in 7th from Moon - relationship focus", "चन्द्रमाबाट सातौंमा शनि - सम्बन्धमा ध्यान"),
    PERIOD_SATURN_GENERIC("Saturn transit in %dth from Moon", "चन्द्रमाबाट %dऔंमा शनि गोचर"),
    PERIOD_TODAY("Today", "आज"),
    PERIOD_TOMORROW("Tomorrow", "भोलि"),
    PERIOD_WEEKLY("Weekly", "साप्ताहिक"),
    PERSONALITY_SCORE("Personality Strength Score", "व्यक्तित्व शक्ति स्कोर"),
    PERSONALITY_SUMMARY("Personality Summary", "व्यक्तित्व सारांश"),
    PHILOSOPHICAL_LEARNING("Philosophical Learning", "दार्शनिक सिक्ने"),
    PHYSICAL_CONSTITUTION("Physical Constitution", "शारीरिक संविधान"),
    PLACEHOLDER_TYPE_RESPONSE("Type your response...", "तपाईंको प्रतिक्रिया टाइप गर्नुहोस्..."),
    PLACEMENT_INTERP_DEFAULT("The %s in the %dth house influences the areas of %s. Results depend on the sign placement, aspects, and overall chart strength.", "%dऔं भावमा रहेको %s ले %s का क्षेत्रहरूलाई प्रभाव पार्छ। परिणामहरू राशि स्थिति, दृष्टि, र समग्र कुण्डलीको बलमा निर्भर हुन्छन्।"),
    PLACEMENT_INTERP_JUPITER_1("Wise and optimistic personality. Natural teacher or advisor. Good fortune and ethical nature. Respected by others.", "बुद्धिमान र आशावादी व्यक्तित्व। प्राकृतिक शिक्षक वा सल्लाहकार। राम्रो भाग्य र नैतिक स्वभाव। अरूद्वारा सम्मानित।"),
    PLACEMENT_INTERP_JUPITER_9("Excellent position for spiritual growth and higher learning. Good fortune with father and long journeys. Success in teaching or law.", "आध्यात्मिक वृद्धि र उच्च शिक्षाको लागि उत्कृष्ट स्थिति। बुबा र लामो यात्रासँग राम्रो भाग्य। शिक्षण वा कानूनमा सफलता।"),
    PLACEMENT_INTERP_KETU_12("Strong spiritual inclinations. Interest in meditation and liberation. May spend time in foreign lands or ashrams.", "बलियो आध्यात्मिक झुकाव। ध्यान र मुक्तिमा रुचि। विदेशी भूमि वा आश्रमहरूमा समय बिताउन सक्छ।"),
    PLACEMENT_INTERP_MARS_1("Energetic and courageous personality. Athletic abilities. Can be aggressive or impulsive. Strong drive for success.", "ऊर्जावान र साहसी व्यक्तित्व। एथलेटिक क्षमताहरू। आक्रामक वा आवेगपूर्ण हुन सक्छ। सफलताको लागि बलियो प्रेरणा।"),
    PLACEMENT_INTERP_MARS_10("Dynamic career with technical or engineering success. Leadership in competitive fields. Achievement through bold actions.", "प्राविधिक वा इन्जिनियरिङ सफलताको साथ गतिशील करियर। प्रतिस्पर्धी क्षेत्रहरूमा नेतृत्व। साहसी कार्यहरू मार्फत उपलब्धि।"),
    PLACEMENT_INTERP_MERCURY_1("Intelligent and communicative personality. Good business sense. Quick thinking and versatile nature.", "बुद्धिमान र मिलनसार व्यक्तित्व। राम्रो व्यापारिक ज्ञान। छिटो सोच्ने र बहुमुखी स्वभाव।"),
    PLACEMENT_INTERP_MERCURY_5("Creative intelligence and good with children. Success in speculation and education. Artistic communication skills.", "सिर्जनात्मक बुद्धि र बालबालिकाहरूसँग राम्रो। अनुमान र शिक्षामा सफलता। कलात्मक सञ्चार सीपहरू।"),
    PLACEMENT_INTERP_MOON_1("Emotional and intuitive personality. Strong connection to feelings. Popular with the public and adaptable nature.", "भावनात्मक र अन्तर्ज्ञानी व्यक्तित्व। भावनाहरूसँग बलियो सम्बन्ध। जनतामा लोकप्रिय र अनुकूलनशील स्वभाव।"),
    PLACEMENT_INTERP_MOON_4("Strong emotional foundation and attachment to home. Good relationship with mother. Domestic happiness and property gains likely.", "बलियो भावनात्मक आधार र घरप्रतिको लगाव। आमासँग राम्रो सम्बन्ध। पारिवारिक खुसी र सम्पत्ति लाभको सम्भावना छ।"),
    PLACEMENT_INTERP_RAHU_10("Unconventional career path. Success in foreign lands or technology. Ambitious and worldly.", "अपरम्परागत करियर मार्ग। विदेशी भूमि वा प्रविधिमा सफलता। महत्त्वाकांक्षी र सांसारिक।"),
    PLACEMENT_INTERP_SATURN_10("Slow but steady rise in career. Success through hard work and persistence. Authority gained through discipline.", "करियरमा ढिलो तर स्थिर वृद्धि। कडा परिश्रम र दृढता मार्फत सफलता। अनुशासन मार्फत प्राप्त अधिकार।"),
    PLACEMENT_INTERP_SATURN_7("Delayed marriage but stable. Serious approach to partnerships. May marry someone older or more mature.", "विवाहमा ढिलाइ तर स्थिर। साझेदारीप्रति गम्भीर दृष्टिकोण। आफूभन्दा जेठो वा बढी परिपक्व व्यक्तिसँग विवाह गर्न सक्छ।")
}
