package com.astro.storm.core.common

enum class StringKeyPanchanga(override val en: String, override val ne: String) : StringKeyInterface {
    KARANA_BALAVA("Balava", "बालव"),
    KARANA_BAVA("Bava", "बव"),
    KARANA_CHATUSHPADA("Chatushpada", "चतुष्पद"),
    KARANA_DESC_BALAVA("Balava karana brings youthful energy and is good for learning, education, and activities involving young people. Favorable for new learning experiences.", "बालव करणले युवा ऊर्जा ल्याउँछ र सिकाइ, शिक्षा, र युवा मानिसहरू संलग्न गतिविधिहरूको लागि राम्रो छ। नयाँ सिकाइ अनुभवहरूको लागि अनुकूल।"),
    KARANA_DESC_BAVA("Bava karana is favorable for travel, beginning new ventures, and activities requiring movement. It supports progress and forward motion in all endeavors.", "बव करण यात्रा, नयाँ उद्यम सुरु गर्न, र चाल चाहिने गतिविधिहरूको लागि अनुकूल छ। यसले सबै प्रयासहरूमा प्रगति र अगाडि बढ्ने गतिलाई समर्थन गर्छ।"),
    KARANA_DESC_CHATUSHPADA("Chatushpada is a fixed karana favorable for activities involving four-legged animals and agriculture. Good for animal husbandry and farming.", "चतुष्पद एक स्थिर करण हो जुन चार खुट्टे जनावरहरू र कृषिसँग सम्बन्धित गतिविधिहरूको लागि अनुकूल छ। पशुपालन र खेतीको लागि राम्रो।"),
    KARANA_DESC_GARA("Gara karana is good for agriculture, construction, and activities involving the earth. Favorable for property matters and physical labor.", "गर करण कृषि, निर्माण, र पृथ्वीसँग सम्बन्धित गतिविधिहरूको लागि राम्रो छ। सम्पत्ति मामिलाहरू र शारीरिक श्रमको लागि अनुकूल।"),
    KARANA_DESC_KAULAVA("Kaulava karana is excellent for family matters, social gatherings, and community activities. It supports harmony in relationships and group endeavors.", "कौलव करण पारिवारिक मामिलाहरू, सामाजिक जमघटहरू, र सामुदायिक गतिविधिहरूको लागि उत्कृष्ट छ। यसले सम्बन्ध र सामूहिक प्रयासहरूमा सद्भावलाई समर्थन गर्छ।"),
    KARANA_DESC_KIMSTUGHNA("Kimstughna is a fixed karana that destroys negativity. Favorable for removing obstacles, protection rituals, and overcoming enemies.", "किंस्तुघ्न एक स्थिर करण हो जसले नकारात्मकता नष्ट गर्छ। बाधाहरू हटाउन, सुरक्षा अनुष्ठानहरू, र शत्रुहरूमाथि विजय प्राप्त गर्न अनुकूल।"),
    KARANA_DESC_NAGA("Naga is a fixed karana associated with serpent energies. Favorable for activities involving hidden matters, underground work, and protective rituals.", "नाग सर्प ऊर्जाहरूसँग सम्बन्धित एक स्थिर करण हो। लुकेका कुरा, भूमिगत काम, र सुरक्षात्मक अनुष्ठानहरूसँग सम्बन्धित गतिविधिहरूको लागि अनुकूल।"),
    KARANA_DESC_SHAKUNI("Shakuni is a fixed karana appearing only once per lunar month. It supports activities requiring cleverness and strategy but can bring mixed results.", "शकुनि एक स्थिर करण हो जुन चन्द्र महिनामा एक पटक मात्र आउँछ। यसले चलाखी र रणनीति चाहिने गतिविधिहरूलाई समर्थन गर्छ तर मिश्रित परिणामहरू ल्याउन सक्छ।"),
    KARANA_DESC_TAITILA("Taitila karana is highly favorable for business, commerce, and material gain. Excellent for financial transactions and wealth-building activities.", "तैतिल करण व्यापार, वाणिज्य, र भौतिक लाभको लागि धेरै अनुकूल छ। वित्तीय कारोबार र धन-निर्माण गतिविधिहरूको लागि उत्कृष्ट।"),
    KARANA_DESC_VANIJA("Vanija karana is excellent for trade, business deals, and commercial success. Highly favorable for merchants and those in business.", "वणिज करण व्यापार, व्यापारिक सम्झौताहरू, र व्यावसायिक सफलताको लागि उत्कृष्ट छ। व्यापारीहरू र व्यवसायमा भएकाहरूका लागि धेरै अनुकूल।"),
    KARANA_DESC_VISHTI("Vishti (Bhadra) karana is inauspicious and should be avoided for important activities. Only suitable for fierce activities or confronting enemies.", "विष्टि (भद्रा) करण अशुभ छ र महत्त्वपूर्ण गतिविधिहरूको लागि बच्नुपर्छ। उग्र गतिविधिहरू वा शत्रुहरूको सामना गर्न मात्र उपयुक्त।"),
    KARANA_FIXED("Fixed", "स्थिर"),
    KARANA_GARA("Gara", "गर"),
    KARANA_KAULAVA("Kaulava", "कौलव"),
    KARANA_KIMSTUGHNA("Kimstughna", "किंस्तुघ्न"),
    KARANA_MOVABLE("Movable", "चर"),
    KARANA_NAGA("Naga", "नाग"),
    KARANA_SHAKUNI("Shakuni", "शकुनि"),
    KARANA_TAITILA("Taitila", "तैतिल"),
    KARANA_TYPE_FIXED("Sthira (Fixed)", "स्थिर"),
    KARANA_TYPE_MOVABLE("Chara (Movable)", "चर (चलायमान)"),
    KARANA_VANIJA("Vanija", "वणिज"),
    KARANA_VISHTI("Vishti (Bhadra)", "विष्टि (भद्रा)"),
    NAKSHATRA_ALL_PLANETS("Planetary Nakshatras", "ग्रह नक्षत्रहरू"),
    NAKSHATRA_ANIMAL("Animal", "पशु"),
    NAKSHATRA_ANURADHA("Anuradha", "अनुराधा"),
    NAKSHATRA_ARDRA("Ardra", "आर्द्रा"),
    NAKSHATRA_ASHLESHA("Ashlesha", "आश्लेषा"),
    NAKSHATRA_ASHWINI("Ashwini", "अश्विनी"),
    NAKSHATRA_BHARANI("Bharani", "भरणी"),
    NAKSHATRA_BIRD("Bird", "पक्षी"),
    NAKSHATRA_BIRTH_STAR("Birth Nakshatra", "जन्म नक्षत्र"),
    NAKSHATRA_BODY_PART("Body Part", "शरीरको अंग"),
    NAKSHATRA_BODY_PART_FEET("Feet", "पाउ"),
    NAKSHATRA_BODY_PART_HEAD("Head", "टाउको"),
    NAKSHATRA_BODY_PART_NAVEL("Navel", "नाभि"),
    NAKSHATRA_BODY_PART_NECK("Neck", "घाँटी"),
    NAKSHATRA_BODY_PART_WAIST("Waist", "कम्मर"),
    NAKSHATRA_CAREER("Career Aptitude", "क्यारियर योग्यता"),
    NAKSHATRA_CAREERS("Careers", "क्यारियर"),
    NAKSHATRA_CASTE("Caste", "वर्ण"),
    NAKSHATRA_CASTE_BRAHMIN("Brahmin", "ब्राह्मण"),
    NAKSHATRA_CASTE_KSHATRIYA("Kshatriya", "क्षत्रिय"),
    NAKSHATRA_CASTE_SHUDRA("Shudra", "शूद्र"),
    NAKSHATRA_CASTE_VAISHYA("Vaishya", "वैश्य"),
    NAKSHATRA_CHANDRABALA("Chandrabala", "चन्द्रबल"),
    NAKSHATRA_CHARACTERISTICS("Characteristics", "विशेषताहरू"),
    NAKSHATRA_CHITRA("Chitra", "चित्रा"),
    NAKSHATRA_COMPATIBILITY("Compatibility", "अनुकूलता"),
    NAKSHATRA_COMPATIBLE_WITH("Compatible with", "अनुकूल"),
    NAKSHATRA_DASHA_LORD("Dasha Lord", "दशा स्वामी"),
    NAKSHATRA_DEGREE_IN("Degree in Nakshatra", "नक्षत्रमा अंश"),
    NAKSHATRA_DEITY("Deity", "देवता"),
    NAKSHATRA_DETAILS("Details", "विवरणहरू"),
    NAKSHATRA_DHANISHTHA("Dhanishtha", "धनिष्ठा"),
    NAKSHATRA_DIFF("Nakshatra Difference", "नक्षत्र भिन्नता"),
    NAKSHATRA_DIRECTION("Direction", "दिशा"),
    NAKSHATRA_DOSHA("Dosha", "दोष"),
    NAKSHATRA_DOSHA_KAPHA("Kapha", "कफ"),
    NAKSHATRA_DOSHA_PITTA("Pitta", "पित्त"),
    NAKSHATRA_DOSHA_VATA("Vata", "वात"),
    NAKSHATRA_ELEMENT("Element", "तत्व"),
    NAKSHATRA_ELEMENT_AIR("Air (Vayu)", "वायु"),
    NAKSHATRA_ELEMENT_EARTH("Earth (Prithvi)", "पृथ्वी"),
    NAKSHATRA_ELEMENT_ETHER("Ether (Akasha)", "आकाश"),
    NAKSHATRA_ELEMENT_FIRE("Fire (Agni)", "अग्नि"),
    NAKSHATRA_ELEMENT_WATER("Water (Jala)", "जल"),
    NAKSHATRA_FAVORABLE_DAYS("Favorable Days", "अनुकूल दिनहरू"),
    NAKSHATRA_FEMALE("Female", "महिला"),
    NAKSHATRA_GANA("Gana", "गण"),
    NAKSHATRA_GANA_DEVA("Deva (Divine)", "देव"),
    NAKSHATRA_GANA_MANUSHYA("Manushya (Human)", "मनुष्य"),
    NAKSHATRA_GANA_RAKSHASA("Rakshasa (Demon)", "राक्षस"),
    NAKSHATRA_GENDER("Gender", "लिङ्ग"),
    NAKSHATRA_GENDER_FEMALE("Female", "स्त्री"),
    NAKSHATRA_GENDER_MALE("Male", "पुरुष"),
    NAKSHATRA_GENDER_NEUTRAL("Neutral", "नपुंसक"),
    NAKSHATRA_GUNA("Guna", "गुण"),
    NAKSHATRA_HASTA("Hasta", "हस्त"),
    NAKSHATRA_HEALTH("Health Tendencies", "स्वास्थ्य प्रवृत्तिहरू"),
    NAKSHATRA_INCOMPATIBLE_WITH("Incompatible with", "अनुकूल छैन"),
    NAKSHATRA_INFLUENCE_STRONG("The nakshatra placement strongly influences your personality, adding unique characteristics to your basic nature.",
        "नक्षत्र स्थितिले तपाईंको व्यक्तित्वलाई बलियो रूपमा प्रभाव पार्छ, तपाईंको आधारभूत स्वभावमा अद्वितीय विशेषताहरू थप्दै।"),
    NAKSHATRA_INFO_DESC("Nakshatras are the 27 lunar mansions in Vedic astrology, each spanning 13Â°20' of the zodiac. They reveal deeper psychological patterns and spiritual tendencies.", "नक्षत्रहरू वैदिक ज्योतिषमा २७ चन्द्र भवनहरू हुन्, प्रत्येक राशिचक्रको १३°२०' फैलिएको। तिनीहरूले गहिरो मनोवैज्ञानिक ढाँचा र आध्यात्मिक प्रवृत्तिहरू प्रकट गर्छन्।"),
    NAKSHATRA_INFO_TITLE("About Nakshatras", "नक्षत्रहरूको बारेमा"),
    NAKSHATRA_JYESHTHA("Jyeshtha", "ज्येष्ठा"),
    NAKSHATRA_KRITTIKA("Krittika", "कृत्तिका"),
    NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
    NAKSHATRA_LUCKY_COLORS("Lucky Colors", "भाग्यशाली रंगहरू"),
    NAKSHATRA_LUCKY_NUMBERS("Lucky Numbers", "भाग्यशाली अंकहरू"),
    NAKSHATRA_LUCKY_STONES("Lucky Gemstones", "भाग्यशाली रत्नहरू"),
    NAKSHATRA_MAGHA("Magha", "मघा"),
    NAKSHATRA_MALE("Male", "पुरुष"),
    NAKSHATRA_MANTRA("Nakshatra Mantra", "नक्षत्र मन्त्र"),
    NAKSHATRA_MOON_POSITION("Moon Nakshatra", "चन्द्र नक्षत्र"),
    NAKSHATRA_MRIGASHIRA("Mrigashira", "मृगशिरा"),
    NAKSHATRA_MULA("Mula", "मूल"),
    NAKSHATRA_NATURE("Nature", "प्रकृति"),
    NAKSHATRA_NATURE_DREADFUL("Dreadful", "क्रूर"),
    NAKSHATRA_NATURE_FIERCE("Fierce (Ugra)", "उग्र"),
    NAKSHATRA_NATURE_FIXED("Fixed (Dhruva)", "स्थिर (ध्रुव)"),
    NAKSHATRA_NATURE_LIGHT("Light (Laghu)", "लघु"),
    NAKSHATRA_NATURE_MIXED("Mixed (Mishra)", "मिश्र"),
    NAKSHATRA_NATURE_MOVABLE("Movable (Chara)", "चर"),
    NAKSHATRA_NATURE_MOVEABLE("Moveable (Chara)", "चर"),
    NAKSHATRA_NATURE_SHARP("Sharp (Tikshna)", "तीक्ष्ण"),
    NAKSHATRA_NATURE_SOFT("Soft (Mridu)", "मृदु"),
    NAKSHATRA_NATURE_SWIFT("Swift (Kshipra)", "क्षिप्र (छिटो)"),
    NAKSHATRA_OVERVIEW("Overview", "अवलोकन"),
    NAKSHATRA_PADA("Pada", "पद"),
    NAKSHATRA_PADA_ACCESSIBILITY("%1\$s pada %2\$s", "%1\$s पद %2\$s"),
    NAKSHATRA_PUNARVASU("Punarvasu", "पुनर्वसु"),
    NAKSHATRA_PURVA_ASHADHA("Purva Ashadha", "पूर्वाषाढा"),
    NAKSHATRA_PURVA_BHADRAPADA("Purva Bhadrapada", "पूर्वभाद्रपद"),
    NAKSHATRA_PURVA_PHALGUNI("Purva Phalguni", "पूर्वा फाल्गुनी"),
    NAKSHATRA_PUSHYA("Pushya", "पुष्य"),
    NAKSHATRA_QUALITY("Quality", "गुण"),
    NAKSHATRA_RAJJU_KANTHA("Kantha", "कण्ठ"),
    NAKSHATRA_RAJJU_KATI("Kati", "कटि"),
    NAKSHATRA_RAJJU_NABHI("Nabhi", "नाभि"),
    NAKSHATRA_RAJJU_PAADA("Paada", "पाद"),
    NAKSHATRA_RAJJU_SHIRO("Shiro", "शिरो"),
    NAKSHATRA_RAJJU_TYPE("Rajju Type", "रज्जु प्रकार"),
    NAKSHATRA_RELATIONSHIP("Relationship Style", "सम्बन्ध शैली"),
    NAKSHATRA_REMEDIES("Remedies", "उपायहरू"),
    NAKSHATRA_REMEDY_DESC("Personalized remedies based on your birth nakshatra to enhance positive qualities and mitigate challenges.", "तपाइँको जन्म नक्षत्रमा आधारित व्यक्तिगत उपायहरू सकारात्मक गुणहरू बढाउन र चुनौतीहरू कम गर्न।"),
    NAKSHATRA_REMEDY_TIMING("Best performed during %s hora or on %s", "%s होरा वा %s मा उत्तम"),
    NAKSHATRA_REMEDY_TITLE("Remedies for %s", "%s का लागि उपायहरू"),
    NAKSHATRA_REVATI("Revati", "रेवती"),
    NAKSHATRA_ROHINI("Rohini", "रोहिणी"),
    NAKSHATRA_RULER("Ruling Planet", "स्वामी ग्रह"),
    NAKSHATRA_SHAKTI("Shakti (Power)", "शक्ति"),
    NAKSHATRA_SHATABHISHA("Shatabhisha", "शतभिषा"),
    NAKSHATRA_SHRAVANA("Shravana", "श्रवण"),
    NAKSHATRA_SPAN("Nakshatra Span", "नक्षत्र विस्तार"),
    NAKSHATRA_SPIRITUAL("Spiritual Path", "आध्यात्मिक मार्ग"),
    NAKSHATRA_STRENGTHS("Strengths", "शक्तिहरू"),
    NAKSHATRA_SUBTITLE("Lunar Mansion Analysis", "चन्द्र भवन विश्लेषण"),
    NAKSHATRA_SWATI("Swati", "स्वाति"),
    NAKSHATRA_SYMBOL("Symbol", "प्रतीक"),
    NAKSHATRA_TARABALA("Tarabala Analysis", "ताराबल विश्लेषण"),
    NAKSHATRA_TITLE("Nakshatra Analysis", "नक्षत्र विश्लेषण"),
    NAKSHATRA_TREE("Tree", "वृक्ष"),
    NAKSHATRA_UTTARA_ASHADHA("Uttara Ashadha", "उत्तराषाढा"),
    NAKSHATRA_UTTARA_BHADRAPADA("Uttara Bhadrapada", "उत्तरभाद्रपद"),
    NAKSHATRA_UTTARA_PHALGUNI("Uttara Phalguni", "उत्तरा फाल्गुनी"),
    NAKSHATRA_VEDHA_PAIRS("Vedha Pairs", "वेध जोडीहरू"),
    NAKSHATRA_VISHAKHA("Vishakha", "विशाखा"),
    NAKSHATRA_WEAKNESSES("Weaknesses", "कमजोरीहरू"),
    NAKSHATRA_YONI("Yoni", "योनि"),
    PAKSHA_KRISHNA("Krishna Paksha", "कृष्ण पक्ष"),
    PAKSHA_SHUKLA("Shukla Paksha", "शुक्ल पक्ष"),
    PANCHANGA_ABHIJIT("Abhijit Muhurta", "अभिजित मुहूर्त"),
    PANCHANGA_ABOUT("About Panchanga", "पञ्चाङ्गको बारेमा"),
    PANCHANGA_ABOUT_DESCRIPTION("Panchanga (Sanskrit: पञ्चाङ्ग, \"five limbs\") is the traditional Hindu calendar and almanac. It tracks five fundamental elements of Vedic time-keeping, essential for determining auspicious moments (muhurta) for important activities.", "पञ्चाङ्ग (संस्कृत: पञ्चाङ्ग, \"पाँच अंग\") परम्परागत हिन्दू पात्रो र पंचांग हो। यसले वैदिक समय-गणनाको पाँच मौलिक तत्वहरूको ट्र्याक गर्दछ, जुन महत्त्वपूर्ण कार्यहरूको लागि शुभ क्षण (मुहूर्त) निर्धारण गर्न आवश्यक छ।"),
    PANCHANGA_ABOUT_DESC_1("Panchanga (Sanskrit: पञ्चाङ्ग) means 'five limbs' and refers to the traditional Hindu almanac that tracks five elements of time: Tithi, Vara, Nakshatra, Yoga, and Karana.", "पञ्चाङ्ग (संस्कृत: पञ्चाङ्ग) को अर्थ 'पाँच अंग' हो र यसले समयका पाँच तत्वहरू: तिथि, वार, नक्षत्र, योग र करण ट्र्याक गर्ने परम्परागत हिन्दु पात्रोलाई जनाउँछ।"),
    PANCHANGA_ABOUT_DESC_2("These five elements together determine the auspiciousness of any moment and are crucial for selecting muhurtas (auspicious timings) for important activities.", "यी पाँच तत्वहरूले मिलेर कुनै पनि क्षणको शुभता निर्धारण गर्दछ र महत्त्वपूर्ण गतिविधिहरूको लागि मुहूर्त (शुभ समय) चयन गर्न महत्त्वपूर्ण छन्।"),
    PANCHANGA_ABOUT_INTRO("पञ्चाङ्ग परिचय", "पञ्चाङ्ग परिचय"),
    PANCHANGA_ABOUT_SUBTITLE("पञ्चाङ्ग परिचय", "पञ्चाङ्ग परिचय"),
    PANCHANGA_ABOUT_TITLE("About Panchanga", "पञ्चाङ्गको बारेमा"),
    PANCHANGA_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
    PANCHANGA_ANIMAL("Animal", "पशु"),
    PANCHANGA_AT_BIRTH("Panchanga at Birth", "जन्मको समयको पञ्चाङ्ग"),
    PANCHANGA_AUSPICIOUS_TIMING("Auspicious timing", "शुभ समय"),
    PANCHANGA_AVOID("Activities to Avoid", "टाढा रहनु पर्ने गतिविधिहरू"),
    PANCHANGA_AVOID_ACTIVITIES("Avoid important activities", "महत्त्वपूर्ण कार्यहरू नगर्नुहोस्"),
    PANCHANGA_BIRTH_INSIGHT("The Panchanga at birth reveals the cosmic influences active at the moment of incarnation, providing insights into one's inherent nature, tendencies, and life patterns.", "जन्मको समयको पञ्चाङ्गले अवतारको क्षणमा सक्रिय ब्रह्माण्डीय प्रभावहरू प्रकट गर्दछ, व्यक्तिको स्वभाविक प्रकृति, प्रवृत्ति र जीवन ढाँचामा अन्तर्दृष्टि प्रदान गर्दछ।"),
    PANCHANGA_BIRTH_INTERP_KARANA("The %s karana further refines these birth energies.", "%s करणले यी जन्म ऊर्जाहरूलाई थप परिष्कृत गर्दछ।"),
    PANCHANGA_BIRTH_INTERP_MAIN("Born on %1\$s, under the %2\$s nakshatra during %3\$s tithi.", "%1\$sमा जन्म, %3\$s तिथिमा %2\$s नक्षत्र अन्तर्गत।"),
    PANCHANGA_BIRTH_INTERP_YOGA("The %s yoga was active, indicating ", "%s योग सक्रिय थियो, जसले "),
    PANCHANGA_BIRTH_INTERP_YOGA_AUSPICIOUS("highly auspicious conditions at birth, suggesting favorable karma. ", "जन्मको समयमा अत्यधिक शुभ परिस्थितिहरू, अनुकूल कर्मको संकेत गर्दछ।"),
    PANCHANGA_BIRTH_INTERP_YOGA_CHALLENGE("challenges to overcome but also strength building opportunities. ", "पार गर्नुपर्ने चुनौतीहरू तर शक्ति निर्माणका अवसरहरू पनि संकेत गर्दछ।"),
    PANCHANGA_BIRTH_INTERP_YOGA_MODERATE("moderate influences that support balanced development. ", "सन्तुलित विकासलाई समर्थन गर्ने मध्यम प्रभावहरू।"),
    PANCHANGA_CALCULATE_DAY("Calculate based on day", "दिनको आधारमा गणना गर्नुहोस्"),
    PANCHANGA_CHARACTERISTICS("Characteristics", "विशेषताहरू"),
    PANCHANGA_DEITY("Deity", "देवता"),
    PANCHANGA_DIRECTION("Direction", "दिशा"),
    PANCHANGA_EFFECTS("Effects", "प्रभावहरू"),
    PANCHANGA_ELEMENT("Element", "तत्व"),
    PANCHANGA_FAVORABLE("Favorable", "अनुकूल"),
    PANCHANGA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
    PANCHANGA_FIVE_LIMBS("Five Limbs (Pancha Anga)", "पाँच अंगहरू (पञ्चाङ्ग)"),
    PANCHANGA_FULL_MOON("Full Moon", "पूर्णिमा"),
    PANCHANGA_GANA("Gana", "गण"),
    PANCHANGA_GULIKA("Gulika Kaal", "गुलिक काल"),
    PANCHANGA_GUNA("Guna", "गुण"),
    PANCHANGA_HALF_LUNAR_DAY("Half Lunar Day", "अर्ध चन्द्र दिन"),
    PANCHANGA_HALF_LUNAR_DAY_SANSKRIT("करण", "करण"),
    PANCHANGA_INFO_KARANA_LABEL("Half Tithi", "अर्ध तिथि"),
    PANCHANGA_INFO_KARANA_TITLE("Karana (करण)", "करण (करण)"),
    PANCHANGA_INFO_NAKSHATRA_LABEL("Lunar Mansion", "चन्द्र नक्षत्र"),
    PANCHANGA_INFO_NAKSHATRA_TITLE("Nakshatra (नक्षत्र)", "नक्षत्र (नक्षत्र)"),
    PANCHANGA_INFO_TITHI_LABEL("Lunar Day", "चन्द्र दिन"),
    PANCHANGA_INFO_TITHI_TITLE("Tithi (तिथि)", "तिथि (तिथि)"),
    PANCHANGA_INFO_VARA_LABEL("Weekday", "वार"),
    PANCHANGA_INFO_VARA_TITLE("Vara (वार)", "वार (वार)"),
    PANCHANGA_INFO_YOGA_LABEL("Luni-Solar Combination", "चन्द्र-सूर्य संयोजन"),
    PANCHANGA_INFO_YOGA_TITLE("Yoga (योग)", "योग (योग)"),
    PANCHANGA_INTRO("Panchanga comprises five essential elements (Pancha Anga) that determine the quality and auspiciousness of any moment in the Hindu calendar system.", "पञ्चाङ्गमा पाँच आवश्यक तत्वहरू (पञ्च अंग) हुन्छन् जसले हिन्दु पात्रो प्रणालीमा कुनै पनि क्षणको गुणस्तर र शुभता निर्धारण गर्दछ।"),
    PANCHANGA_KARANA("Karana", "करण"),
    PANCHANGA_KARANA_DESC("Half of a tithi", "तिथिको आधा भाग"),
    PANCHANGA_KARANA_DESC_LONG("Half of a tithi, there are 11 karanas total. Seven are movable and four are fixed. Each karana has its own nature and suitable activities.", "तिथिको आधा भाग, कुल ११ करणहरू छन्। सात चर र चार स्थिर छन्। प्रत्येक करणको आफ्नै प्रकृति र उपयुक्त गतिविधिहरू छन्।"),
    PANCHANGA_KARANA_LABEL("Karana", "करण"),
    PANCHANGA_KARANA_SIG("Karanas fine-tune the effects of tithis. Movable karanas recur throughout the month while fixed ones appear only once.", "करणहरूले तिथिका प्रभावहरूलाई सुष्म बनाउँछन्। चर करणहरू महिनाभर दोहोरिन्छन् भने स्थिर करणहरू एक पटक मातॠर आउँछन्।"),
    PANCHANGA_KARANA_SUBTITLE("Half Lunar Day • करण", "अर्ध चन्द्र दिन • करण"),
    PANCHANGA_LIMBS_TITLE("Five Limbs of Hindu Calendar", "हिन्दु पात्रोका पाँच अंगहरू"),
    PANCHANGA_LORD("Lord", "स्वामी"),
    PANCHANGA_LUNAR_DAY("Lunar Day", "चन्द्र दिन"),
    PANCHANGA_LUNAR_DAY_FMT("Lunar day (%1\$2)", "चन्द्र दिन (%1\$2)"),
    PANCHANGA_LUNAR_DAY_SANSKRIT("तिथि", "तिथि"),
    PANCHANGA_LUNAR_MANSION("Lunar Mansion", "चन्द्र नक्षत्र"),
    PANCHANGA_LUNAR_MANSION_SANSKRIT("नक्षत्र", "नक्षत्र"),
    PANCHANGA_LUNAR_PHASE("Lunar Phase", "चन्द्र कला"),
    PANCHANGA_LUNISOLAR("Luni-Solar Combination", "चन्द्र-सूर्य संयोजन"),
    PANCHANGA_LUNISOLAR_SANSKRIT("योग", "योग"),
    PANCHANGA_MASA("Masa", "मास"),
    PANCHANGA_MEANING("Meaning", "अर्थ"),
    PANCHANGA_MIDDAY_HOUR("Midday hour", "मध्यान्ह समय"),
    PANCHANGA_MOON("Moon", "चन्द्रमा"),
    PANCHANGA_MOONRISE("Moonrise", "चन्द्रोदय"),
    PANCHANGA_MOONSET("Moonset", "चन्द्रास्त"),
    PANCHANGA_NAKSHATRA_DESC("The Moon's position among 27 stellar constellations, each spanning 13°20'. Determines the Moon's influence on consciousness.", "२७ नक्षत्र तारामण्डलहरू बीच चन्द्रमाको स्थिति, प्रत्येक १३°२०' समेट्छ। चेतनामा चन्द्रमाको प्रभाव निर्धारण गर्दछ।"),
    PANCHANGA_NAKSHATRA_DESC_FMT("Lunar mansion (Pada %1\$2)", "नक्षत्र (पद %1\$2)"),
    PANCHANGA_NAKSHATRA_DESC_LONG("The lunar mansion where the Moon resides. There are 27 nakshatras, each spanning 13Â°20' of the zodiac. Each nakshatra has a ruling deity and planet.", "चन्द्रमा बस्ने नक्षत्र। त्यहाँ २७ नक्षत्रहरू छन्, प्रत्येकले राशिको १३°२०' ओगटेका छन्। प्रत्येक नक्षत्रको एक शासक देवता र ग्रह हुन्छ।"),
    PANCHANGA_NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
    PANCHANGA_NAKSHATRA_SIG("Birth nakshatra determines personality traits and compatibility. Moon's nakshatra is crucial for muhurta selection.", "जन्म नक्षत्रले व्यक्तित्व गुणहरू र अनुकूलता निर्धारण गर्दछ। मुहूर्त चयनको लागि चन्द्रमाको नक्षत्र महत्त्वपूर्ण छ।"),
    PANCHANGA_NAKSHATRA_SUBTITLE("Lunar Mansion • नक्षत्र", "चन्द्र नक्षत्र • नक्षत्र"),
    PANCHANGA_NATURE("Nature", "प्रकृति"),
    PANCHANGA_NEW_MOON("New Moon", "अमावस्या"),
    PANCHANGA_NUMBER("Number", "संख्या"),
    PANCHANGA_NUMBER_OF("of", "मध्ये"),
    PANCHANGA_PADA("Pada", "पद"),
    PANCHANGA_PAKSHA("Paksha", "पक्ष"),
    PANCHANGA_PROGRESS("Progress", "प्रगति"),
    PANCHANGA_RAHU("Rahu Kaal", "राहु काल"),
    PANCHANGA_RISE("Rise", "उदय"),
    PANCHANGA_RULER("Ruler", "स्वामी"),
    PANCHANGA_RULING_PLANET("Ruling Planet", "शासक ग्रह"),
    PANCHANGA_SANSKRIT("पञ्चाङ्ग", "पञ्चाङ्ग"),
    PANCHANGA_SANSKRIT_LABEL("Sanskrit", "संस्कृत"),
    PANCHANGA_SET("Set", "अस्त"),
    PANCHANGA_SIGNIFICANCE("Significance", "महत्त्व"),
    PANCHANGA_SUN("Sun", "सूर्य"),
    PANCHANGA_SUNRISE("Sunrise", "सूर्योदय"),
    PANCHANGA_SUNSET("Sunset", "सूर्यास्त"),
    PANCHANGA_SUN_MOON("Sun & Moon", "सूर्य र चन्द्रमा"),
    PANCHANGA_SYMBOL("Symbol", "चिन्ह"),
    PANCHANGA_TIMING_AUSPICIOUSNESS("Timing & Auspiciousness", "समय र शुभता"),
    PANCHANGA_TITHI("Tithi", "तिथि"),
    PANCHANGA_TITHI_DESC("Based on the angular distance between Sun and Moon. Each tithi spans 12° of lunar elongation. There are 30 tithis in a lunar month.", "सूर्य र चन्द्रमाबीचको कोणीय दूरीमा आधारित। प्रत्येक तिथि १२° चन्द्र विस्तार समेट्छ। एक चान्द्र महिनामा ३० तिथि हुन्छन्।"),
    PANCHANGA_TITHI_DESC_LONG("The lunar day, calculated based on the angular distance between the Sun and Moon. Each tithi represents 12 degrees of lunar motion. There are 30 tithis in a lunar month, divided into Shukla (waxing) and Krishna (waning) Paksha.", "चन्द्र दिन, जुन सूर्य र चन्द्रमा बीचको कोणीय दूरीको आधारमा गणना गरिन्छ। प्रत्येक तिथिले १२ डिग्रीको चन्द्र गति प्रतिनिधित्व गर्दछ। एक चन्द्र मासमा ३० तिथिहरू हुन्छन्, जुन शुक्ल (बढ्दो) र कृष्ण (घट्दो) पक्षमा विभाजित हुन्छन्।"),
    PANCHANGA_TITHI_KRISHNA("Krishna", "कृष्ण"),
    PANCHANGA_TITHI_LABEL("Tithi", "तिथि"),
    PANCHANGA_TITHI_SHUKLA("Shukla", "शुक्ल"),
    PANCHANGA_TITHI_SIG("Determines the nature of activities suitable for the day. Some tithis like Purnima (full moon) and Amavasya (new moon) have special significance.", "दिनको लागि उपयुक्त गतिविधिहरूको प्रकृति निर्धारण गर्दछ। पूर्णिमा र औंशी जस्ता केही तिथिहरूको विशेष महत्त्व हुन्छ।"),
    PANCHANGA_TITHI_SUBTITLE("Lunar Day • तिथि", "चन्द्र दिन • तिथि"),
    PANCHANGA_TYPE("Type", "प्रकार"),
    PANCHANGA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    PANCHANGA_VARA("Vara (Day)", "वार"),
    PANCHANGA_VARA_DESC("Weekday, ruled by specific planet", "बार, विशिष्ट ग्रहद्वारा शासित"),
    PANCHANGA_VARA_DESC_LONG("The weekday, each ruled by a specific planet. The planetary ruler influences the nature and appropriate activities for that day.", "वार, प्रत्येक एक विशिष्ट ग्रहद्वारा शासित हुन्छ। ग्रह शासकले त्यस दिनको प्रकृति र उपयुक्त गतिविधिहरूलाई प्रभाव पार्छ।"),
    PANCHANGA_VARA_LABEL("Vara", "वार"),
    PANCHANGA_VARA_SIG("Each vara has specific activities that are considered favorable. For example, Sunday is good for authority matters, Monday for emotional work.", "प्रत्येक वारमा विशिष्ट गतिविधिहरू हुन्छन् जुन अनुकूल मानिन्छन्। उदाहरणका लागि, आइतबार अधिकार मामिलाहरूको लागि राम्रो हुन्छ, सोमबार भावनात्मक कार्यको लागि।"),
    PANCHANGA_VARA_SUBTITLE("Weekday • वार", "वार • वार"),
    PANCHANGA_WANING("Waning", "घट्दो"),
    PANCHANGA_WAXING("Waxing", "बढ्दो"),
    PANCHANGA_WEEKDAY("Weekday", "वार"),
    PANCHANGA_WEEKDAY_SANSKRIT("वार", "वार"),
    PANCHANGA_YAMAGANDAM("Yamagandam", "यमगण्डम"),
    PANCHANGA_YOGA("Yoga", "योग"),
    PANCHANGA_YOGA_DESC("Auspicious combination", "शुभ संयोग"),
    PANCHANGA_YOGA_DESC_LONG("Calculated from the combined longitudes of Sun and Moon. There are 27 yogas, each with specific qualities ranging from highly auspicious to inauspicious.", "सूर्य र चन्द्रमाको संयुक्त देशान्तरबाट गणना गरिएको। त्यहाँ २७ योगहरू छन्, प्रत्येकसँग अत्यधिक शुभ देखि अशुभ सम्मका विशिष्ट गुणहरू छन्।"),
    PANCHANGA_YOGA_LABEL("Yoga", "योग"),
    PANCHANGA_YOGA_SIG("Yogas indicate the general nature of results from activities undertaken. Siddha, Amrita, and Shubha yogas are highly favorable.", "योगहरूले गरिएका गतिविधिहरूको परिणामको सामान्य प्रकृति संकेत गर्दछ। सिद्ध, अमृत र शुभ योगहरू अत्यधिक अनुकूल हुन्छन्।"),
    PANCHANGA_YOGA_SUBTITLE("Luni-Solar Combination • योग", "चन्द्र-सूर्य संयोजन • योग"),
    RAHU_KETU_AXIS("Rahu-Ketu Axis", "राहु-केतु अक्ष"),
    RAHU_KETU_TRANSIT("Rahu-Ketu Transit", "राहु-केतु गोचर"),
    RAHU_TRANSIT_HOUSE("Rahu Transit House", "राहु गोचर भाव"),
    TITHI_AMAVASYA("Amavasya", "अमावस्या"),
    TITHI_ASHTAMI("Ashtami", "अष्टमी"),
    TITHI_CHATURDASHI("Chaturdashi", "चतुर्दशी"),
    TITHI_CHATURTHI("Chaturthi", "चतुर्थी"),
    TITHI_DASHAMI("Dashami", "दशमी"),
    TITHI_DEITY_AGNI("Agni (Fire God)", "अग्नि (आगोका देवता)"),
    TITHI_DEITY_BRAHMA("Brahma (Creator)", "ब्रह्मा (सृष्टिकर्ता)"),
    TITHI_DEITY_CHANDRA("Chandra (Moon God)", "चन्द्र (चन्द्र देवता)"),
    TITHI_DEITY_DURGA("Durga (Mother Goddess)", "दुर्गा (भवानी)"),
    TITHI_DEITY_GANESHA_YAMA("Ganesha/Yama", "गणेश/यम"),
    TITHI_DEITY_GAURI("Gauri (Parvati)", "गौरी (पार्वती)"),
    TITHI_DEITY_KAMADEVA("Kamadeva (God of Love)", "कामदेव (प्रेमका देवता)"),
    TITHI_DEITY_KARTIKEYA("Kartikeya (Skanda)", "कार्तिकेय (स्कन्द)"),
    TITHI_DEITY_NAGAS("Nagas (Serpent deities)", "नाग (सर्प देवता)"),
    TITHI_DEITY_PITRIS("Pitris (Ancestors)", "पितृ (पुर्खाहरू)"),
    TITHI_DEITY_SHIVA_KALI("Shiva/Kali", "शिव/काली"),
    TITHI_DEITY_SHIVA_RUDRA("Shiva/Rudra", "शिव/रुद्र"),
    TITHI_DEITY_SURYA("Surya (Sun God)", "सूर्य (सूर्य देवता)"),
    TITHI_DEITY_VISHNU("Vishnu (Preserver)", "विष्णु (संरक्षक)"),
    TITHI_DEITY_YAMA("Yama (God of Death)", "यम (मृत्युका देवता)"),
    TITHI_DESC_1("Pratipada marks new beginnings. The first tithi after New Moon or Full Moon carries the energy of initiation and fresh starts. It is auspicious for beginning new ventures, laying foundations, and starting journeys.", "प्रतिपदाले नयाँ सुरुवातको संकेत गर्छ। औँसी वा पूर्णिमा पछिको पहिलो तिथिले प्रारम्भ र ताजा सुरुवातको ऊर्जा बोक्छ। यो नयाँ उद्यम सुरु गर्न, जग बसाल्न र यात्रा सुरु गर्न शुभ छ।"),
    TITHI_DESC_10("Dashami represents victory and completion. Ruled by Yama, it is excellent for completing tasks, achieving goals, and celebrating success. Highly auspicious for important undertakings.", "दशमी विजय र पूर्णताको प्रतिनिधित्व गर्छ। यमद्वारा शासित, यो कार्यहरू पूरा गर्न, लक्ष्यहरू प्राप्त गर्न र सफलता मनाउन उत्कृष्ट छ। महत्त्वपूर्ण कार्यहरूको लागि धेरै शुभ।"),
    TITHI_DESC_11("Ekadashi is the most spiritually significant tithi, sacred to Lord Vishnu. Fasting on this day is considered highly meritorious. Excellent for spiritual practices, but material activities should be minimized.", "एकादशी सबैभन्दा आध्यात्मिक रूपमा महत्त्वपूर्ण तिथि हो, भगवान विष्णुका लागि पवित्र। यस दिन व्रत बस्नु धेरै पुण्यदायी मानिन्छ। आध्यात्मिक अभ्यासहरूको लागि उत्कृष्ट, तर भौतिक गतिविधिहरू कम गर्नुपर्छ।"),
    TITHI_DESC_12("Dwadashi follows Ekadashi and is auspicious for breaking the fast and religious ceremonies. Good for charitable activities, feeding Brahmins, and continuing spiritual practices.", "द्वादशी एकादशी पछि आउँछ र व्रत तोड्न तथा धार्मिक समारोहहरूको लागि शुभ छ। परोपकारी गतिविधिहरू, ब्राह्मणहरूलाई भोजन गराउन र आध्यात्मिक अभ्यासहरू जारी राख्न राम्रो।"),
    TITHI_DESC_13("Trayodashi is favorable for Shiva worship, especially on Maha Shivaratri. Good for love-related matters, arts, and activities bringing joy. The 13th tithi is associated with auspiciousness.", "त्रयोदशी शिव पूजाको लागि अनुकूल छ, विशेष गरी महाशिवरात्रिमा। प्रेम-सम्बन्धित मामिलाहरू, कला र आनन्द ल्याउने गतिविधिहरूको लागि राम्रो। १३औं तिथि शुभतासँग सम्बन्धित छ।"),
    TITHI_DESC_14("Chaturdashi is ruled by Shiva and Kali. While powerful for tantric practices and worship, it is considered challenging for worldly activities. Excellent for spiritual disciplines and removing negative energies.", "चतुर्दशी शिव र कालीद्वारा शासित छ। तान्त्रिक अभ्यास र पूजाको लागि शक्तिशाली भए पनि, यसलाई सांसारिक गतिविधिहरूको लागि चुनौतीपूर्ण मानिन्छ। आध्यात्मिक अनुशासन र नकारात्मक ऊर्जाहरू हटाउन उत्कृष्ट।"),
    TITHI_DESC_15("Purnima (Full Moon) is the most auspicious tithi, representing completion and fullness. The Moon is at peak strength, making it excellent for all auspicious activities, spiritual practices, and celebrations.", "पूर्णिमा सबैभन्दा शुभ तिथि हो, जसले पूर्णता र पूर्णताको प्रतिनिधित्व गर्छ। चन्द्रमा चरम शक्तिमा हुन्छ, जसले यसलाई सबै शुभ गतिविधिहरू, आध्यात्मिक अभ्यासहरू र उत्सवहरूको लागि उत्कृष्ट बनाउँछ।"),
    TITHI_DESC_2("Dwitiya is ruled by Brahma, the creator. This tithi is excellent for creative endeavors, naming ceremonies, and constructive activities. It supports growth and expansion of new initiatives.", "द्वितीया ब्रह्मा, सृष्टिकर्ताद्वारा शासित छ। यो तिथि सिर्जनात्मक कार्य, नामकरण समारोह र रचनात्मक गतिविधिहरूको लागि उत्कृष्ट छ। यसले नयाँ पहलहरूको वृद्धि र विस्तारलाई समर्थन गर्छ।"),
    TITHI_DESC_3("Tritiya is associated with victory and success. Ruled by Gauri, it is highly auspicious for celebrations, religious ceremonies, and activities requiring divine grace and feminine energy.", "तृतीया विजय र सफलतासँग सम्बन्धित छ। गौरीद्वारा शासित, यो उत्सव, धार्मिक समारोह र दैवीय कृपा तथा नारी ऊर्जा चाहिने गतिविधिहरूको लागि धेरै शुभ छ।"),
    TITHI_DESC_30("Amavasya (New Moon) is sacred to the ancestors. While considered inauspicious for new beginnings, it is excellent for ancestral rites (Shraddha), Kali worship, and tantric practices. A time for introspection.", "औँसी (नयाँ चन्द्र) पुर्खाहरूका लागि पवित्र छ। नयाँ सुरुवातको लागि अशुभ मानिए पनि, यो पैतृक संस्कार (श्राद्ध), काली पूजा र तान्त्रिक अभ्यासहरूको लागि उत्कृष्ट छ। आत्म-चिन्तनको समय।"),
    TITHI_DESC_4("Chaturthi is ruled by Ganesha (4th) and Yama (19th). While the 4th is for Ganesha worship, these tithis are generally considered inauspicious for beginning new work due to their 'empty' nature.", "चतुर्थी गणेश (चौथो) र यम (१९औं) द्वारा शासित छ। चौथो गणेश पूजाको लागि भए पनि, यी तिथिहरूलाई सामान्यतया तिनीहरूको 'रिक्त' प्रकृतिको कारण नयाँ काम सुरु गर्न अशुभ मानिन्छ।"),
    TITHI_DESC_5("Panchami is excellent for education, learning, and wisdom pursuits. Ruled by the Nagas, it supports activities requiring knowledge, skill development, and intellectual growth.", "पञ्चमी शिक्षा, सिकाइ र ज्ञानका लागि उत्कृष्ट छ। नागहरूद्वारा शासित, यसले ज्ञान, सीप विकास र बौद्धिक वृद्धि चाहिने गतिविधिहरूलाई समर्थन गर्छ।"),
    TITHI_DESC_6("Shashthi is dedicated to Kartikeya (Skanda), the god of war and victory. It is favorable for activities requiring courage, medical treatments, and overcoming enemies or diseases.", "षष्ठी कार्तिकेय (स्कन्द), युद्ध र विजयका देवतालाई समर्पित छ। यो साहस, चिकित्सा उपचार, र शत्रु वा रोगहरूमाथि विजय प्राप्त गर्न चाहिने गतिविधिहरूको लागि अनुकूल छ।"),
    TITHI_DESC_7("Saptami is ruled by the Sun and brings victory and success. Excellent for travel, especially pilgrimages, vehicle purchases, and activities requiring solar energy and vitality.", "सप्तमी सूर्यद्वारा शासित छ र विजय तथा सफलता ल्याउँछ। यात्रा, विशेष गरी तीर्थयात्रा, सवारी साधन खरिद, र सौर्य ऊर्जा तथा जीवनशक्ति चाहिने गतिविधिहरूको लागि उत्कृष्ट।"),
    TITHI_DESC_8("Ashtami is sacred to Lord Shiva and considered powerful for spiritual practices. While classified as Rikta, it is excellent for worship, fasting, and tantric practices. Mixed for worldly activities.", "अष्टमी भगवान शिवका लागि पवित्र छ र आध्यात्मिक अभ्यासहरूको लागि शक्तिशाली मानिन्छ। रिक्ताको रूपमा वर्गीकृत भए पनि, यो पूजा, व्रत र तान्त्रिक अभ्यासहरूको लागि उत्कृष्ट छ। सांसारिक गतिविधिहरूको लागि मिश्रित।"),
    TITHI_DESC_9("Navami is sacred to Durga and other fierce forms of the Divine Mother. Excellent for worship of the goddess, overcoming enemies, and activities requiring aggressive energy and protection.", "नवमी दुर्गा र दिव्य माताका अन्य उग्र रूपहरूका लागि पवित्र छ। देवीको पूजा, शत्रुहरूमाथि विजय प्राप्त गर्न, र आक्रामक ऊर्जा तथा सुरक्षा चाहिने गतिविधिहरूको लागि उत्कृष्ट।"),
    TITHI_DESC_MIXED("This tithi carries mixed influences based on various planetary factors at the time.", "यो तिथिले समयका विभिन्न ग्रह कारकहरूको आधारमा मिश्रित प्रभावहरू बोक्छ।"),
    TITHI_DWADASHI("Dwadashi", "द्वादशी"),
    TITHI_DWITIYA("Dwitiya", "द्वितीया"),
    TITHI_EKADASHI("Ekadashi", "एकादशी"),
    TITHI_GROUP_BHADRA("Bhadra", "भद्रा"),
    TITHI_GROUP_BHADRA_NATURE("Auspicious", "शुभ"),
    TITHI_GROUP_JAYA("Jaya", "जया"),
    TITHI_GROUP_JAYA_NATURE("Victorious", "विजयी"),
    TITHI_GROUP_NANDA("Nanda", "नन्दा"),
    TITHI_GROUP_NANDA_NATURE("Joyful", "आनन्दमय"),
    TITHI_GROUP_PURNA("Purna", "पूर्णा"),
    TITHI_GROUP_PURNA_NATURE("Complete", "पूर्ण"),
    TITHI_GROUP_RIKTA("Rikta", "रिक्ता"),
    TITHI_GROUP_RIKTA_NATURE("Empty", "रित्त"),
    TITHI_NATURE_BHADRA("Bhadra", "भद्रा"),
    TITHI_NATURE_JAYA("Jaya", "जया"),
    TITHI_NATURE_NANDA("Nanda", "नन्दा"),
    TITHI_NATURE_PURNA("Purna", "पूर्णा"),
    TITHI_NATURE_RIKTA("Rikta", "रिक्ता"),
    TITHI_NAVAMI("Navami", "नवमी"),
    TITHI_PANCHAMI("Panchami", "पञ्चमी"),
    TITHI_PRATIPADA("Pratipada", "प्रतिपदा"),
    TITHI_PURNIMA("Purnima", "पूर्णिमा"),
    TITHI_SAPTAMI("Saptami", "सप्तमी"),
    TITHI_SHASHTHI("Shashthi", "षष्ठी"),
    TITHI_SUGGESTION("Tithi Suggestion", "तिथि सुझाव"),
    TITHI_TRAYODASHI("Trayodashi", "त्रयोदशी"),
    TITHI_TRITIYA("Tritiya", "तृतीया"),
    VARA_DESC_FRIDAY("Friday is ruled by Venus (Shukra), representing love, beauty, and pleasure. Venus brings artistic sensibility, romance, and material enjoyment. This day is sacred to Goddess Lakshmi and Santoshi Ma.", "शुक्रबार शुक्र (शुक्र) द्वारा शासित छ, जसले प्रेम, सौन्दर्य र आनन्दको प्रतिनिधित्व गर्छ। शुक्रले कलात्मक संवेदनशीलता, रोमान्स र भौतिक आनन्द ल्याउँछ। यो दिन देवी लक्ष्मी र सन्तोषी आमाका लागि पवित्र छ।"),
    VARA_DESC_MONDAY("Monday is ruled by the Moon (Chandra), representing the mind, emotions, and nurturing. The Moon's energy brings sensitivity, intuition, and public connection. This day is sacred to Lord Shiva.", "सोमबार चन्द्रमा (चन्द्र) द्वारा शासित छ, जसले मन, भावना र पोषणको प्रतिनिधित्व गर्छ। चन्द्रमाको ऊर्जाले संवेदनशीलता, अन्तर्ज्ञान र सार्वजनिक सम्बन्ध ल्याउँछ। यो दिन भगवान शिवका लागि पवित्र छ।"),
    VARA_DESC_SATURDAY("Saturday is ruled by Saturn (Shani), representing discipline, karma, and endurance. Saturn brings lessons, structure, and spiritual growth through challenges. This day is sacred to Lord Shani and Hanuman.", "शनिबार शनि (शनि) द्वारा शासित छ, जसले अनुशासन, कर्म र सहनशीलताको प्रतिनिधित्व गर्छ। शनिले पाठ, संरचना र चुनौतीहरू मार्फत आध्यात्मिक वृद्धि ल्याउँछ। यो दिन भगवान शनि र हनुमानका लागि पवित्र छ।"),
    VARA_DESC_SUNDAY("Sunday is ruled by the Sun (Surya), representing the soul, authority, and vitality. The Sun's energy brings power, leadership, and illumination. This day is sacred to Lord Vishnu and Surya Deva.", "आइतबार सूर्य (सूर्य) द्वारा शासित छ, जसले आत्मा, अधिकार र जीवनशक्तिको प्रतिनिधित्व गर्छ। सूर्यको ऊर्जाले शक्ति, नेतृत्व र प्रकाश ल्याउँछ। यो दिन भगवान विष्णु र सूर्य देवका लागि पवित्र छ।"),
    VARA_DESC_THURSDAY("Thursday is ruled by Jupiter (Guru), representing wisdom, expansion, and divine grace. Jupiter brings blessings, prosperity, and spiritual growth. This day is sacred to Lord Brihaspati and Vishnu.", "बिहीबार बृहस्पति (गुरु) द्वारा शासित छ, जसले ज्ञान, विस्तार र दैवीय कृपाको प्रतिनिधित्व गर्छ। बृहस्पतिले आशीर्वाद, समृद्धि र आध्यात्मिक वृद्धि ल्याउँछ। यो दिन भगवान बृहस्पति र विष्णुका लागि पवित्र छ।"),
    VARA_DESC_TUESDAY("Tuesday is ruled by Mars (Mangal), representing courage, energy, and action. Mars brings warrior energy, determination, and physical strength. This day is sacred to Lord Hanuman and Kartikeya.", "मंगलबार मंगल (मंगल) द्वारा शासित छ, जसले साहस, ऊर्जा र कार्यको प्रतिनिधित्व गर्छ। मंगलले योद्धा ऊर्जा, दृढता र शारीरिक शक्ति ल्याउँछ। यो दिन भगवान हनुमान र कार्तिकेयका लागि पवित्र छ।"),
    VARA_DESC_WEDNESDAY("Wednesday is ruled by Mercury (Budha), representing intellect, communication, and commerce. Mercury brings mental agility, business acumen, and learning ability. This day is sacred to Lord Vishnu.", "बुधबार बुध (बुध) द्वारा शासित छ, जसले बुद्धि, सञ्चार र वाणिज्यको प्रतिनिधित्व गर्छ। बुधले मानसिक चुस्ती, व्यापारिक कौशल र सिक्ने क्षमता ल्याउँछ। यो दिन भगवान विष्णुका लागि पवित्र छ।"),
    VARA_FAV_FRIDAY("Romance, Marriage, Arts, Music, Luxury purchases, Beauty treatments, Entertainment, Lakshmi worship", "रोमान्स, विवाह, कला, संगीत, विलासी खरिदहरू, सौन्दर्य उपचार, मनोरञ्जन, लक्ष्मी पूजा"),
    VARA_FAV_MONDAY("Travel, Public dealings, Emotional matters, Starting ventures, Agriculture, Dealing with women, Shiva worship", "यात्रा, सार्वजनिक व्यवहार, भावनात्मक मामिलाहरू, उद्यम सुरु गर्न, कृषि, महिलाहरूसँगको व्यवहार, शिव पूजा"),
    VARA_FAV_SATURDAY("Property matters, Agriculture, Labor work, Iron/oil business, Spiritual discipline, Shani worship, Hanuman worship", "सम्पत्ति मामिलाहरू, कृषि, श्रम कार्य, फलाम/तेल व्यापार, आध्यात्मिक अनुशासन, शनि पूजा, हनुमान पूजा"),
    VARA_FAV_SUNDAY("Government work, Authority matters, Health initiatives, Father-related activities, Leadership, Spiritual practices, Worship of Surya", "सरकारी काम, अधिकार मामिलाहरू, स्वास्थ्य पहलहरू, पितासँग सम्बन्धित गतिविधिहरू, नेतृत्व, आध्यात्मिक अभ्यासहरू, सूर्य पूजा"),
    VARA_FAV_THURSDAY("Religious ceremonies, Marriage, Education, Financial matters, Legal matters, Guru worship, Charity, Beginning important ventures", "धार्मिक समारोहहरू, विवाह, शिक्षा, वित्तीय मामिलाहरू, कानूनी मामिलाहरू, गुरु पूजा, दान, महत्त्वपूर्ण उद्यमहरू सुरु गर्न"),
    VARA_FAV_TUESDAY("Property matters, Surgery, Competitive activities, Physical training, Dealing with enemies, Hanuman worship, Military activities", "सम्पत्ति मामिलाहरू, शल्यक्रिया, प्रतिस्पर्धात्मक गतिविधिहरू, शारीरिक प्रशिक्षण, शत्रुहरूसँगको व्यवहार, हनुमान पूजा, सैन्य गतिविधिहरू"),
    VARA_FAV_WEDNESDAY("Education, Communication, Business, Writing, Trade, Intellectual pursuits, Travel, Vishnu worship", "शिक्षा, सञ्चार, व्यापार, लेखन, व्यापार, बौद्धिक कार्यहरू, यात्रा, विष्णु पूजा"),
    VARA_FRIDAY("Friday", "शुक्रबार"),
    VARA_FRIDAY_DESC("Ruled by Venus - Good for romance, marriage, arts, luxury", "शुक्र द्वारा शासित - प्रेम, विवाह, कला, विलासिताको लागि राम्रो"),
    VARA_MONDAY("Monday", "सोमबार"),
    VARA_MONDAY_DESC("Ruled by Moon - Good for travel, public dealings, emotional matters", "चन्द्रमा द्वारा शासित - यात्रा, सार्वजनिक व्यवहार, भावनात्मक मामिलाहरूको लागि राम्रो"),
    VARA_SATURDAY("Saturday", "शनिबार"),
    VARA_SATURDAY_DESC("Ruled by Saturn - Good for property, agriculture, spiritual discipline", "शनि द्वारा शासित - सम्पत्ति, कृषि, आध्यात्मिक अनुशासनको लागि राम्रो"),
    VARA_SUNDAY("Sunday", "आइतबार"),
    VARA_SUNDAY_DESC("Ruled by Sun - Good for government work, authority, spiritual practices", "सूर्य द्वारा शासित - सरकारी काम, अधिकार, आध्यात्मिक अभ्यासको लागि राम्रो"),
    VARA_THURSDAY("Thursday", "बिहीबार"),
    VARA_THURSDAY_DESC("Ruled by Jupiter - Good for religious ceremonies, marriage, education", "बृहस्पति द्वारा शासित - धार्मिक समारोह, विवाह, शिक्षाको लागि राम्रो"),
    VARA_TUESDAY("Tuesday", "मंगलबार"),
    VARA_TUESDAY_DESC("Ruled by Mars - Good for property, surgery, competitive activities", "मंगल द्वारा शासित - सम्पत्ति, शल्यक्रिया, प्रतिस्पर्धात्मक गतिविधिहरूको लागि राम्रो"),
    VARA_UNFAV_FRIDAY("Surgery, Aggressive activities, Conflicts", "शल्यक्रिया, आक्रामक गतिविधिहरू, द्वन्द्वहरू"),
    VARA_UNFAV_MONDAY("Surgery, Cutting activities", "शल्यक्रिया, काट्ने गतिविधिहरू"),
    VARA_UNFAV_SATURDAY("New beginnings, Travel, Auspicious ceremonies, Hair cutting", "नयाँ सुरुवात, यात्रा, शुभ समारोहहरू, कपाल काट्न"),
    VARA_UNFAV_SUNDAY("Beginning journeys to the East, Starting new businesses (according to some traditions)", "पूर्वतिरको यात्रा सुरु गर्न, नयाँ व्यवसाय सुरु गर्न (केही परम्परा अनुसार)"),
    VARA_UNFAV_THURSDAY("Hair cutting (for some traditions), Lending money", "कपाल काट्न (केही परम्परा अनुसार), पैसा ऋण दिन"),
    VARA_UNFAV_TUESDAY("Marriage, Peaceful negotiations, Beginning gentle activities", "विवाह, शान्तिपूर्ण वार्ता, कोमल गतिविधिहरू सुरु गर्न"),
    VARA_UNFAV_WEDNESDAY("Agriculture, Building construction (according to some traditions)", "कृषि, भवन निर्माण (केही परम्परा अनुसार)"),
    VARA_WEDNESDAY("Wednesday", "बुधबार"),
    VARA_WEDNESDAY_DESC("Ruled by Mercury - Good for education, communication, business", "बुध द्वारा शासित - शिक्षा, सञ्चार, व्यापारको लागि राम्रो"),
    WEEKDAY_FR("Fr", "शु"),
    WEEKDAY_FRIDAY("Friday", "शुक्रबार"),
    WEEKDAY_MO("Mo", "सो"),
    WEEKDAY_MONDAY("Monday", "सोमबार"),
    WEEKDAY_SA("Sa", "श"),
    WEEKDAY_SATURDAY("Saturday", "शनिबार"),
    WEEKDAY_SU("Su", "आ"),
    WEEKDAY_SUNDAY("Sunday", "आइतबार"),
    WEEKDAY_TH("Th", "बि"),
    WEEKDAY_THURSDAY("Thursday", "बिहीबार"),
    WEEKDAY_TU("Tu", "मं"),
    WEEKDAY_TUESDAY("Tuesday", "मंगलबार"),
    WEEKDAY_WE("We", "बु"),
    WEEKDAY_WEDNESDAY("Wednesday", "बुधबार"),
    YOGAS_COUNT_DETECTED("%1\$d yogas detected in %2\$s", "%2\$s मा %1\$d योगहरू पत्ता लागेको"),
    YOGA_ABOUT_DESCRIPTION("Yogas are special planetary combinations in Vedic astrology that indicate specific life patterns, talents, and karmic influences.", "योगहरू वैदिक ज्योतिषमा विशेष ग्रह संयोजनहरू हुन् जसले विशिष्ट जीवन ढाँचा, प्रतिभा र कर्म प्रभावहरू संकेत गर्छन्।"),
    YOGA_ABOUT_TITLE("About Vedic Yogas", "वैदिक योगहरूको बारेमा"),
    YOGA_ACTIVATION("Activation", "सक्रियता"),
    YOGA_ACTIVATION_LABEL("Activation:", "सक्रियता:"),
    YOGA_ACTIVATION_TITLE("Yoga Activation Events", "योग सक्रियता घटनाहरू"),
    YOGA_ADHI("Adhi Yoga", "अधि योग"),
    YOGA_AKHANDA_SAMRAJYA("Akhanda Samrajya Yoga", "अखण्ड साम्राज्य योग"),
    YOGA_AKHANDA_SAMRAJYA_EXP("Akhanda Samrajya Yoga", "अखण्ड साम्राज्य योग"),
    YOGA_ALL("All", "सबै"),
    YOGA_AMALA("Amala Yoga", "अमला योग"),
    YOGA_AMAVASYA("Amavasya Yoga", "अमावस्या योग"),
    YOGA_ANAFA("Anafa Yoga", "अनफा योग"),
    YOGA_ANALYSIS_SUMMARY("Yoga Analysis Summary", "योग विश्लेषण सारांश"),
    YOGA_ANGARAK("Angarak Yoga", "अङ्गारक योग"),
    YOGA_AUSPICIOUS("Auspicious", "शुभ"),
    YOGA_AYUSH("Ayush Yoga", "आयुष योग"),
    YOGA_BALARISHTA("Balarishta Yoga", "बालारिष्ट योग"),
    YOGA_BANDHANA("Bandhana Yoga", "बन्धन योग"),
    YOGA_BHADRA("Bhadra Yoga", "भद्र योग"),
    YOGA_BHARATHI("Bharathi Yoga", "भारती योग"),
    YOGA_BHARATHI_EXP("Bharathi Yoga", "भारती योग"),
    YOGA_BHAVA_LORD_PLACEMENT("{0} in {1}", "{1}मा {0}"),
    YOGA_BHAVA_TITLE("Bhava Yoga", "भाव योग"),
    YOGA_BHERI("Bheri Yoga", "भेरी योग"),
    YOGA_BHRATRI_KARAKA("Bhratri Karaka Yoga", "भ्रातृ कारक योग"),
    YOGA_BRAHMA("Brahma Yoga", "ब्रह्म योग"),
    YOGA_BUDHA_ADITYA("Budha-Aditya Yoga", "बुध-आदित्य योग"),
    YOGA_BUDHA_DIGNITY("Budha Dignity Yoga", "बुध गरिमा योग"),
    YOGA_BUSINESS("Business Yoga", "व्यापार योग"),
    YOGA_CANCELLATION_FACTORS("Cancellation/Mitigation Factors", "रद्द/न्यूनीकरण कारकहरू"),
    YOGA_CANCELLATION_FMT("Cancellation: %d%%", "न्यूनीकरण: %d%%"),
    YOGA_CAREER_EFFECT("Yoga Effect on Career", "क्यारियरमा योग प्रभाव"),
    YOGA_CATEGORIES_TITLE("Categories", "वर्गहरू"),
    YOGA_CATEGORY_CHALLENGING("Challenging Yogas", "चुनौतीपूर्ण योगहरू"),
    YOGA_CATEGORY_CHALLENGING_DESC("Combinations indicating obstacles", "बाधाहरू संकेत गर्ने संयोजनहरू"),
    YOGA_CATEGORY_CHANDRA("Chandra Yogas", "चन्द्र योगहरू"),
    YOGA_CATEGORY_CHANDRA_DESC("Moon-based combinations", "चन्द्रमामा आधारित संयोजनहरू"),
    YOGA_CATEGORY_DHANA("Dhana Yogas", "धन योगहरू"),
    YOGA_CATEGORY_DHANA_DESC("Combinations for wealth", "धनका लागि संयोजनहरू"),
    YOGA_CATEGORY_MAHAPURUSHA("Mahapurusha Yogas", "महापुरुष योगहरू"),
    YOGA_CATEGORY_MAHAPURUSHA_DESC("Great personality combinations", "महान व्यक्तित्व संयोजनहरू"),
    YOGA_CATEGORY_NABHASA("Nabhasa Yogas", "नाभस योगहरू"),
    YOGA_CATEGORY_NABHASA_DESC("Celestial combinations", "आकाशीय संयोजनहरू"),
    YOGA_CATEGORY_NEGATIVE("Negative Yogas", "नकारात्मक योगहरू"),
    YOGA_CATEGORY_NEGATIVE_DESC("Combinations indicating challenges", "चुनौतीहरू संकेत गर्ने संयोजनहरू"),
    YOGA_CATEGORY_OTHER("Other Yogas", "अन्य योगहरू"),
    YOGA_CATEGORY_OTHER_DESC("Other planetary combinations", "अन्य ग्रह संयोजनहरू"),
    YOGA_CATEGORY_RAJA("Raja Yogas", "राज योगहरू"),
    YOGA_CATEGORY_RAJA_DESC("Combinations for power & authority", "शक्ति र अधिकारका लागि संयोजनहरू"),
    YOGA_CATEGORY_SOLAR("Solar Yogas", "सूर्य योगहरू"),
    YOGA_CATEGORY_SOLAR_DESC("Sun-based combinations", "सूर्यमा आधारित संयोजनहरू"),
    YOGA_CATEGORY_SPECIAL("Special Yogas", "विशेष योगहरू"),
    YOGA_CATEGORY_SPECIAL_DESC("Rare and special combinations", "दुर्लभ र विशेष संयोजनहरू"),
    YOGA_CATEGORY_SPIRITUAL("Spiritual Yogas", "आध्यात्मिक योगहरू"),
    YOGA_CATEGORY_SPIRITUAL_DESC("Combinations for spiritual growth", "आध्यात्मिक वृद्धिका लागि संयोजनहरू"),
    YOGA_CATEGORY_WEALTH("Wealth Yogas", "धन योगहरू"),
    YOGA_CATEGORY_WEALTH_DESC("Combinations for prosperity", "समृद्धिका लागि संयोजनहरू"),
    YOGA_CAT_BHAVA("Bhava Yoga", "भाव योग"),
    YOGA_CAT_BHAVA_DESC("House Lord Placements", "भाव अधिपति स्थितिहरू"),
    YOGA_CAT_CHANDRA("Chandra Yoga", "चन्द्र योग"),
    YOGA_CAT_CHANDRA_DESC("Moon-based combinations", "चन्द्रमामा आधारित संयोजनहरू"),
    YOGA_CAT_CONJUNCTION("Conjunction Yoga", "युति योग"),
    YOGA_CAT_CONJUNCTION_DESC("Planetary Conjunctions", "ग्रह युतिहरू"),
    YOGA_CAT_DHANA("Dhana Yoga", "धन योग"),
    YOGA_CAT_DHANA_DESC("Wealth and prosperity combinations", "धन र समृद्धि संयोजनहरू"),
    YOGA_CAT_MAHAPURUSHA("Mahapurusha Yoga", "महापुरुष योग"),
    YOGA_CAT_NABHASA("Nabhasa Yoga", "नाभस योग"),
    YOGA_CAT_NABHASA_DESC("Planetary Patterns", "ग्रह आकृतिहरू"),
    YOGA_CAT_NEGATIVE("Negative Yoga", "नकारात्मक योग"),
    YOGA_CAT_NEGATIVE_DESC("Challenging combinations", "चुनौतीपूर्ण संयोजनहरू"),
    YOGA_CAT_PANCHA_MAHAPURUSHA("Pancha Mahapurusha Yoga", "पञ्च महापुरुष योग"),
    YOGA_CAT_PANCHA_MAHAPURUSHA_DESC("Five great person combinations", "पाँच महान व्यक्ति संयोजनहरू"),
    YOGA_CAT_RAJA("Raja Yoga", "राज योग"),
    YOGA_CAT_RAJA_DESC("Power, authority, and leadership combinations", "शक्ति, अधिकार र नेतृत्व संयोजनहरू"),
    YOGA_CAT_SOLAR("Solar Yoga", "सूर्य योग"),
    YOGA_CAT_SOLAR_DESC("Sun-based combinations", "सूर्यमा आधारित संयोजनहरू"),
    YOGA_CAT_SPECIAL("Special Yoga", "विशेष योग"),
    YOGA_CAT_SPECIAL_DESC("Other significant combinations", "अन्य महत्त्वपूर्ण संयोजनहरू"),
    YOGA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    YOGA_CHAMARA("Chamara Yoga", "चामर योग"),
    YOGA_CHANDRADHI("Chandradhi Yoga", "चंद्राधि योग"),
    YOGA_CHANDRA_DIGNITY("Chandra Dignity Yoga", "चन्द्र गरिमा योग"),
    YOGA_CHANDRA_GRAHAN("Chandra Grahan Yoga", "चन्द्र ग्रहण योग"),
    YOGA_CHANDRA_KETU("Chandra-Ketu Yoga", "चन्द्र-केतु योग"),
    YOGA_CHANDRA_LAKSHMI("Chandra Lakshmi Yoga", "चंद्र लक्ष्मी योग"),
    YOGA_CHANDRA_MANGALA("Chandra-Mangala Yoga", "चन्द्र-मंगल योग"),
    YOGA_CHATUSSAGARA("Chatussagara Yoga", "चतुःसागर योग"),
    YOGA_COMBUSTION("Combustion Yoga", "अस्त योग"),
    YOGA_CONJUNCTION_2_PLANETS("Conjunction of {0} and {1}", "{0} र {1} को युति"),
    YOGA_CONJUNCTION_3_PLANETS("Conjunction of {0}, {1} and {2}", "{0}, {1} र {2} को युति"),
    YOGA_CONJUNCTION_4_PLANETS("Conjunction of {0}, {1}, {2} and {3}", "{0}, {1}, {2} र {3} को युति"),
    YOGA_CONJUNCTION_TITLE("Conjunction Yoga", "युति योग"),
    YOGA_COUNT_DETECTED("%d yogas detected", "%d योगहरू पत्ता लागेको"),
    YOGA_COUNT_SUFFIX("yogas", "योगहरू"),
    YOGA_DAINYA_PARIVARTTANA("Dainya Parivarttana Yoga", "दैन्य परिवर्तन योग"),
    YOGA_DANDA("Danda Yoga", "दण्ड योग"),
    YOGA_DARIDRA("Daridra Yoga", "दरिद्र योग"),
    YOGA_DARIDRA_EXP("Daridra Yoga", "दरिद्र योग"),
    YOGA_DASA_MULA("Dasa-Mula Yoga", "दश-मूल योग"),
    YOGA_DEEP_ANALYSIS("Deep Vedic Analysis", "गहिरो वैदिक विश्लेषण"),
    YOGA_DESC_ATIGANDA("Atiganda yoga indicates significant obstacles and dangers. Those born under this yoga face karmic challenges. Avoid important activities during this period.", "अतिगण्ड योगले महत्त्वपूर्ण बाधाहरू र खतराहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले कर्मिक चुनौतीहरूको सामना गर्छन्। यस अवधिमा महत्त्वपूर्ण गतिविधिहरूबाट बच्नुहोस्।"),
    YOGA_DESC_AYUSHMAN("Ayushman yoga bestows longevity and good health. Those born under this yoga enjoy vitality and well-being. Auspicious for health-related matters and new beginnings.", "आयुष्मान योगले दीर्घायु र राम्रो स्वास्थ्य प्रदान गर्छ। यस योगमा जन्मेकाहरूले जीवनशक्ति र कल्याणको आनन्द लिन्छन्। स्वास्थ्य-सम्बन्धित मामिलाहरू र नयाँ सुरुवातको लागि शुभ।"),
    YOGA_DESC_BRAHMA("Brahma yoga bestows creative powers and wisdom. Those born under this yoga are natural creators. Excellent for beginning creative projects.", "ब्रह्म योगले सिर्जनात्मक शक्ति र ज्ञान प्रदान गर्छ। यस योगमा जन्मेकाहरू प्राकृतिक सिर्जनाकर्ता हुन्। सिर्जनात्मक परियोजनाहरू सुरु गर्न उत्कृष्ट।"),
    YOGA_DESC_COMBUST("combust", "अस्त"),
    YOGA_DESC_DEBILITATED("debilitated", "नीच"),
    YOGA_DESC_DHRITI("Dhriti yoga bestows determination and stability. Those born under this yoga possess mental strength and perseverance. Good for activities requiring patience and commitment.", "धृति योगले दृढ संकल्प र स्थिरता प्रदान गर्छ। यस योगमा जन्मेकाहरूसँग मानसिक शक्ति र लगनशीलता हुन्छ। धैर्य र प्रतिबद्धता चाहिने गतिविधिहरूको लागि राम्रो।"),
    YOGA_DESC_DHRUVA("Dhruva yoga provides stability and permanence. Those born under this yoga create lasting foundations. Good for activities meant to endure, like property purchases.", "ध्रुव योगले स्थिरता र स्थायित्व प्रदान गर्छ। यस योगमा जन्मेकाहरूले स्थायी जग निर्माण गर्छन्। सम्पत्ति खरिद जस्ता टिक्नका लागि गरिने गतिविधिहरूको लागि राम्रो।"),
    YOGA_DESC_DUSTHANA("Dusthana", "दुस्थान"),
    YOGA_DESC_EXALTED("exalted sign", "उच्च राशि"),
    YOGA_DESC_GANDA("Ganda yoga brings obstacles and difficulties. Those born under this yoga develop problem-solving abilities through challenges. Not ideal for new beginnings.", "गण्ड योगले बाधाहरू र कठिनाइहरू ल्याउँछ। यस योगमा जन्मेकाहरूले चुनौतीहरू मार्फत समस्या समाधान गर्ने क्षमता विकास गर्छन्। नयाँ सुरुवातको लागि आदर्श होइन।"),
    YOGA_DESC_HARSHANA("Harshana yoga brings joy and happiness. Those born under this yoga spread positivity and attract good fortune. Excellent for celebrations and social activities.", "हर्षण योगले आनन्द र खुसी ल्याउँछ। यस योगमा जन्मेकाहरूले सकारात्मकता फैलाउँछन् र सौभाग्य आकर्षित गर्छन्। उत्सवहरू र सामाजिक गतिविधिहरूको लागि उत्कृष्ट।"),
    YOGA_DESC_INDRA("Indra yoga bestows power, authority, and success. Those born under this yoga are natural leaders. Favorable for leadership and governmental matters.", "इन्द्र योगले शक्ति, अधिकार र सफलता प्रदान गर्छ। यस योगमा जन्मेकाहरू प्राकृतिक नेता हुन्। नेतृत्व र सरकारी मामिलाहरूको लागि अनुकूल।"),
    YOGA_DESC_IN_ASPECT("in aspect", "दृष्टि मा"),
    YOGA_DESC_IN_CONJUNCTION("in conjunction", "संयोग मा"),
    YOGA_DESC_IN_KENDRA("in Kendra", "केन्द्रमा"),
    YOGA_DESC_KENDRA_LORD("Kendra lord", "केन्द्र अधिपति"),
    YOGA_DESC_OWN_SIGN("own sign", "आफ्नो राशि"),
    YOGA_DESC_PARIGHA("Parigha yoga indicates barriers and restrictions. Those born under this yoga develop strength through overcoming obstacles. Caution in new ventures.", "परिघ योगले अवरोधहरू र प्रतिबन्धहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले बाधाहरू पार गरेर शक्ति विकास गर्छन्। नयाँ उद्यमहरूमा सावधानी।"),
    YOGA_DESC_PRITI("Priti yoga brings love, affection, and pleasant relationships. Those born under this yoga are charming and attract positive connections. Excellent for romance and partnerships.", "प्रीति योगले प्रेम, स्नेह र रमाइलो सम्बन्धहरू ल्याउँछ। यस योगमा जन्मेकाहरू आकर्षक हुन्छन् र सकारात्मक सम्बन्धहरू आकर्षित गर्छन्। रोमान्स र साझेदारीको लागि उत्कृष्ट।"),
    YOGA_DESC_SADHYA("Sadhya yoga makes goals achievable with effort. Those born under this yoga succeed through determination. Good for pursuing challenging objectives.", "साध्य योगले प्रयासद्वारा लक्ष्यहरू प्राप्त गर्न योग्य बनाउँछ। यस योगमा जन्मेकाहरूले दृढता मार्फत सफलता प्राप्त गर्छन्। चुनौतीपूर्ण उद्देश्यहरू पछ्याउन राम्रो।"),
    YOGA_DESC_SAUBHAGYA("Saubhagya yoga brings luck and prosperity. Those born under this yoga are fortunate in material matters. Highly auspicious for wealth-related activities.", "सौभाग्य योगले भाग्य र समृद्धि ल्याउँछ। यस योगमा जन्मेकाहरू भौतिक मामिलामा भाग्यमानी हुन्छन्। धन-सम्बन्धित गतिविधिहरूको लागि धेरै शुभ।"),
    YOGA_DESC_SHIVA("Shiva yoga is highly auspicious and brings divine blessings. Those born under this yoga possess spiritual inclinations. Excellent for all auspicious activities.", "शिव योग धेरै शुभ छ र दैवीय आशीर्वाद ल्याउँछ। यस योगमा जन्मेकाहरूसँग आध्यात्मिक झुकाव हुन्छ। सबै शुभ गतिविधिहरूको लागि उत्कृष्ट।"),
    YOGA_DESC_SHOBHANA("Shobhana yoga bestows beauty, grace, and splendor. Those born under this yoga possess attractive qualities. Favorable for arts, aesthetics, and public appearances.", "शोभन योगले सौन्दर्य, ग्रेस र भव्यता प्रदान गर्छ। यस योगमा जन्मेकाहरूसँग आकर्षक गुणहरू हुन्छन्। कला, सौन्दर्यशास्त्र र सार्वजनिक उपस्थितिहरूको लागि अनुकूल।"),
    YOGA_DESC_SHUBHA("Shubha yoga is highly auspicious for all activities. Those born under this yoga attract good fortune. Excellent for ceremonies and celebrations.", "शुभ योग सबै गतिविधिहरूको लागि धेरै शुभ छ। यस योगमा जन्मेकाहरूले सौभाग्य आकर्षित गर्छन्। समारोहहरू र उत्सवहरूको लागि उत्कृष्ट।"),
    YOGA_DESC_SHUKLA("Shukla yoga brings brightness and clarity. Those born under this yoga have clear minds and pure intentions. Favorable for education and spiritual practices.", "शुक्ल योगले उज्यालो र स्पष्टता ल्याउँछ। यस योगमा जन्मेकाहरूसँग स्पष्ट मन र शुद्ध मनसाय हुन्छ। शिक्षा र आध्यात्मिक अभ्यासहरूको लागि अनुकूल।"),
    YOGA_DESC_SHULA("Shula yoga indicates sharp experiences and potential conflicts. Those born under this yoga may face sudden challenges. Caution advised in risky activities.", "शूल योगले तीक्ष्ण अनुभवहरू र सम्भावित द्वन्द्वहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले अचानक चुनौतीहरूको सामना गर्न सक्छन्। जोखिमपूर्ण गतिविधिहरूमा सावधानी अपनाउन सल्लाह दिइन्छ।"),
    YOGA_DESC_SIDDHA("Siddha yoga bestows accomplishment and success. Those born under this yoga are naturally talented. Very favorable for achieving goals.", "सिद्ध योगले उपलब्धि र सफलता प्रदान गर्छ। यस योगमा जन्मेकाहरू स्वाभाविक रूपमा प्रतिभाशाली हुन्छन्। लक्ष्यहरू प्राप्त गर्न धेरै अनुकूल।"),
    YOGA_DESC_SIDDHI("Siddhi yoga bestows success and accomplishment. Those born under this yoga achieve their goals. Highly auspicious for completing important tasks.", "सिद्धि योगले सफलता र उपलब्धि प्रदान गर्छ। यस योगमा जन्मेकाहरूले आफ्ना लक्ष्यहरू प्राप्त गर्छन्। महत्त्वपूर्ण कार्यहरू पूरा गर्न धेरै शुभ।"),
    YOGA_DESC_SUKARMA("Sukarma yoga favors righteous actions and good deeds. Those born under this yoga are inclined toward virtuous acts. Excellent for charitable activities and spiritual practices.", "सुकर्म योगले धार्मिक कार्यहरू र राम्रा कामहरूलाई पक्ष दिन्छ। यस योगमा जन्मेकाहरू सद्गुणी कार्यहरूप्रति झुकाव राख्छन्। परोपकारी गतिविधिहरू र आध्यात्मिक अभ्यासहरूको लागि उत्कृष्ट।"),
    YOGA_DESC_TRIKONA_LORD("Trikona lord", "त्रिकोण अधिपति"),
    YOGA_DESC_VAIDHRITI("Vaidhriti yoga is the final yoga and indicates discord. Those born under this yoga face endings and transitions. Avoid important beginnings; good for conclusions.", "वैधृति योग अन्तिम योग हो र कलह संकेत गर्छ। यस योगमा जन्मेकाहरूले अन्त्य र संक्रमणहरूको सामना गर्छन्। महत्त्वपूर्ण सुरुवातहरूबाट बच्नुहोस्; निष्कर्षका लागि राम्रो।"),
    YOGA_DESC_VAJRA("Vajra yoga provides strength like a thunderbolt but can be harsh. Those born under this yoga are powerful and determined. Mixed results for activities.", "वज्र योगले बज्र जस्तै शक्ति प्रदान गर्छ तर कठोर हुन सक्छ। यस योगमा जन्मेकाहरू शक्तिशाली र दृढ हुन्छन्। गतिविधिहरूको लागि मिश्रित परिणामहरू।"),
    YOGA_DESC_VARIYAN("Variyan yoga is one of the most auspicious yogas. Those born under this yoga enjoy success and recognition. Favorable for all important undertakings.", "वरीयान योग सबैभन्दा शुभ योगहरू मध्ये एक हो। यस योगमा जन्मेकाहरूले सफलता र मान्यताको आनन्द लिन्छन्। सबै महत्त्वपूर्ण कार्यहरूको लागि अनुकूल।"),
    YOGA_DESC_VISHKUMBHA("Vishkumbha yoga indicates obstacles and difficulties. Those born under this yoga may face initial struggles but develop resilience. Not favorable for beginning new ventures.", "विष्कुम्भ योगले बाधाहरू र कठिनाइहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले प्रारम्भिक संघर्षको सामना गर्न सक्छन् तर लचिलोपन विकास गर्छन्। नयाँ उद्यम सुरु गर्न अनुकूल छैन।"),
    YOGA_DESC_VRIDDHI("Vriddhi yoga promotes growth and expansion in all areas. Those born under this yoga experience progressive development. Excellent for investments and long-term projects.", "वृद्धि योगले सबै क्षेत्रहरूमा वृद्धि र विस्तारलाई बढावा दिन्छ। यस योगमा जन्मेकाहरूले प्रगतिशील विकास अनुभव गर्छन्। लगानी र दीर्घकालीन परियोजनाहरूको लागि उत्कृष्ट।"),
    YOGA_DESC_VYAGHATA("Vyaghata yoga indicates destruction and loss. Those born under this yoga may experience significant transformations. Avoid major decisions and beginnings.", "व्याघात योगले विनाश र हानि संकेत गर्छ। यस योगमा जन्मेकाहरूले महत्त्वपूर्ण रूपान्तरणहरू अनुभव गर्न सक्छन्। ठूला निर्णयहरू र सुरुवातहरूबाट बच्नुहोस्।"),
    YOGA_DESC_VYATIPATA("Vyatipata yoga is considered highly inauspicious. Those born under this yoga face significant karmic challenges. Avoid all important activities.", "व्यतीपात योगलाई धेरै अशुभ मानिन्छ। यस योगमा जन्मेकाहरूले महत्त्वपूर्ण कर्मिक चुनौतीहरूको सामना गर्छन्। सबै महत्त्वपूर्ण गतिविधिहरूबाट बच्नुहोस्।"),
    YOGA_DHANA_KARAKA("Dhana Karaka Yoga", "धन कारक योग"),
    YOGA_DHANA_PAPA_KARTARI("Dhana Papa Kartari", "धन पाप कर्तरी"),
    YOGA_DHARMA("Dharma Yoga", "धर्म योग"),
    YOGA_DHARMA_KARMADHIPATI("Dharma-Karmadhipati Yoga", "धर्म-कर्माधिपति योग"),
    YOGA_DIGBALA_RAJA("Digbala Raja Yoga", "दिक्बल राज योग"),
    YOGA_DIGNITY_EXALTED("Exalted", "उच्च"),
    YOGA_DIGNITY_OWN_SIGN("Own Sign", "स्वराशि"),
    YOGA_DOMINANT_CATEGORY("Dominant Category", "प्रमुख वर्ग"),
    YOGA_DUR("Dur Yoga", "दुर् योग"),
    YOGA_DURUDHARA("Durudhara Yoga", "दुरुधरा योग"),
    YOGA_DURYOGA("Duryoga", "दुर्योग"),
    YOGA_EFFECT("Yoga Effect", "योग प्रभाव"),
    YOGA_EFFECTS("Effects", "प्रभावहरू"),
    YOGA_EFFECT_ADHI("Commander, minister, or king; polite, trustworthy, healthy, wealthy, defeats enemies", "सेनापति, मन्त्री, वा राजा; विनम्र, विश्वसनीय, स्वस्थ, धनी, शत्रुहरूलाई हराउने"),
    YOGA_EFFECT_AKHANDA_SAMRAJYA("Undisputed leadership, wide-ranging influence, vast wealth and authority", "अविवादित नेतृत्व, व्यापक प्रभाव, विशाल धन र अधिकार"),
    YOGA_EFFECT_ANAFA("Good reputation, health, happiness, self-respect", "राम्रो प्रतिष्ठा, स्वास्थ्य, खुशी, आत्म-सम्मान"),
    YOGA_EFFECT_ANGARAK("Accidents, surgery, aggression, sibling troubles, litigation, sudden events", "दुर्घटनाहरू, शल्यक्रिया, आक्रामकता, भाइबहिनी समस्याहरू, मुद्दा, अचानक घटनाहरू"),
    YOGA_EFFECT_BHADRA("Intelligent, eloquent speaker, skilled in arts and sciences, long-lived, wealthy through intellect, respected in assemblies, lion-like face, broad chest", "बुद्धिमान, वाक्पटु वक्ता, कला र विज्ञानमा दक्ष, दीर्घायु, बुद्धिबाट धनी, सभामा सम्मानित, सिंह जस्तो मुख, फराकिलो छाती"),
    YOGA_EFFECT_BUDHA_ADITYA("Intelligence, skilled in many arts, famous, sweet speech, scholarly", "बुद्धि, धेरै कलाहरूमा दक्ष, प्रसिद्ध, मीठो बोली, विद्वान"),
    YOGA_EFFECT_CHAMARA("Royal honors, fame, eloquence, learned, respected by rulers", "राजकीय सम्मान, प्रसिद्धि, वाक्पटुता, पढेलेखेको, शासकहरूद्वारा सम्मानित"),
    YOGA_EFFECT_CHANDRA_GRAHAN("Mental restlessness, mother troubles, emotional instability, obsessive tendencies", "मानसिक अशान्ति, आमा समस्याहरू, भावनात्मक अस्थिरता, जुनूनी प्रवृत्तिहरू"),
    YOGA_EFFECT_CHANDRA_KETU("Detachment from emotions, past-life memories, psychic sensitivity, mother karma", "भावनाहरूबाट विरक्ति, पूर्वजन्म स्मृतिहरू, मनोवैज्ञानिक संवेदनशीलता, आमा कर्म"),
    YOGA_EFFECT_CHANDRA_MANGALA("Wealth through business, enterprise, real estate, aggressive financial pursuits", "व्यापारबाट धन, उद्यम, घर जग्गा, आक्रामक आर्थिक प्रयासहरू"),
    YOGA_EFFECT_DARIDRA("Obstacles to gains, financial struggles, unfulfilled desires", "लाभमा बाधाहरू, आर्थिक संघर्ष, अपूर्ण इच्छाहरू"),
    YOGA_EFFECT_DASA_MULA("Obstacles in undertakings, needs remedial measures, struggle with finances", "कार्यहरूमा बाधाहरू, उपचारात्मक उपायहरू आवश्यक, आर्थिक संघर्ष"),
    YOGA_EFFECT_DHARMA_KARMADHIPATI("Highly successful career, fortune through profession, fame, authority positions", "अत्यन्त सफल करियर, पेशाबाट भाग्य, प्रसिद्धि, अधिकार पदहरू"),
    YOGA_EFFECT_DURUDHARA("Highly fortunate, wealthy, vehicles, servants, charitable, enjoys life", "अत्यधिक भाग्यशाली, धनी, वाहनहरू, सेवकहरू, दानशील, जीवनको आनन्द लिने"),
    YOGA_EFFECT_GADA("Wealthy through ceremonies, always engaged in auspicious activities", "संस्कारहरूबाट धनी, सधैं शुभ कार्यहरूमा संलग्न"),
    YOGA_EFFECT_GAJA_KESARI("Destroyer of enemies like lion, eloquent speaker, virtuous, long-lived, famous", "सिंह जस्तो शत्रु विनाशक, वाक्पटु वक्ता, सद्गुणी, दीर्घायु, प्रसिद्ध"),
    YOGA_EFFECT_GOLA("Poor, dirty, ignorant, idle", "गरिब, फोहोरी, अज्ञानी, अल्छी"),
    YOGA_EFFECT_GURU_CHANDAL("Unorthodox beliefs, breaks from tradition, possible disgrace through teachers/religion", "अपरम्परागत विश्वासहरू, परम्परा तोड्ने, गुरु/धर्मबाट सम्भावित अपमान"),
    YOGA_EFFECT_HAMSA("Righteous king, fair complexion, elevated nose, beautiful face, devoted to gods and brahmins, fond of water sports, walks like a swan, respected by rulers, spiritual inclinations", "धार्मिक राजा, गोरो रंग, उठेको नाक, सुन्दर मुख, देवता र ब्राह्मणहरूप्रति भक्त, जल क्रीडाको शौकीन, हंस जस्तो हिँड्ने, शासकहरूद्वारा सम्मानित, आध्यात्मिक झुकाव"),
    YOGA_EFFECT_INDU_LAGNA("Special financial potential revealed through lunar rays, prosperity through specific life paths", "चन्द्र किरणहरू मार्फत प्रकट भएको विशेष आर्थिक सम्भावना, विशिष्ट जीवन मार्गहरू मार्फत समृद्धि"),
    YOGA_EFFECT_KAHALA("Brave but stubborn, military success, leadership through conflict", "बहादुर तर हठी, सैन्य सफलता, द्वन्द्वबाट नेतृत्व"),
    YOGA_EFFECT_KALA_SARPA("Karmic life patterns, sudden ups and downs, spiritual transformation potential", "कर्मजन्य जीवन ढाँचाहरू, अचानक उतार-चढाव, आध्यात्मिक रूपान्तरण सम्भावना"),
    YOGA_EFFECT_KEDARA("Agricultural wealth, helpful to others, truthful", "कृषि धन, अरूलाई मद्दतगर्ने, सत्यवादी"),
    YOGA_EFFECT_KEMADRUMA("Poverty, suffering, struggles, lack of support, lonely, menial work", "गरिबी, दुख, संघर्ष, समर्थनको अभाव, एक्लो, तल्लो काम"),
    YOGA_EFFECT_KEMADRUMA_BHANGA("Protection from loneliness and poverty, internal strength to overcome initial lack", "एक्लोपन र गरिबीबाट सुरक्षा, प्रारम्भिक अभावलाई जित्न आन्तरिक शक्ति"),
    YOGA_EFFECT_KEMADRUMA_CANCELLED("Kemadruma effects significantly reduced due to cancellation factors", "रद्द कारकहरूको कारण केमद्रुम प्रभाव उल्लेखनीय रूपमा कम भयो"),
    YOGA_EFFECT_KENDRA_TRIKONA("Rise to power and authority, leadership position, recognition from government", "शक्ति र अधिकारमा उदय, नेतृत्व पद, सरकारबाट मान्यता"),
    YOGA_EFFECT_KUBERA("Immense wealth like lord of wealth, treasure finder, banking success", "धनको देवता जस्तो अपार धन, खजाना फेला पार्ने, बैंकिङमा सफलता"),
    YOGA_EFFECT_KUSUMA("Kingly status, famous, wealthy, enjoys life's pleasures, born in a good family", "राजकीय स्थिति, प्रसिद्ध, धनी, जीवनको आनन्द लिने, राम्रो परिवारमा जन्मिएको"),
    YOGA_EFFECT_LABHA("Gains from multiple sources, profitable ventures, wealth accumulation", "विभिन्न स्रोतबाट लाभ, लाभदायक उद्यमहरू, धन संचय"),
    YOGA_EFFECT_LAKSHMI("Blessed by Goddess Lakshmi, abundant wealth, luxury, beauty, artistic success", "देवी लक्ष्मीको आशीर्वाद, प्रचुर धन, विलासिता, सौन्दर्य, कलात्मक सफलता"),
    YOGA_EFFECT_MAHALAXMI("Divine grace of Goddess Lakshmi, immense wealth, religious nature, respected and virtuous", "देवी लक्ष्मीको दैवी कृपा, अपार धन, धार्मिक स्वभाव, सम्मानित र सद्गुणी"),
    YOGA_EFFECT_MAHA_BHAGYA("Exceptional fortune, leadership, magnetic personality, success from birth", "असाधारण भाग्य, नेतृत्व, आकर्षक व्यक्तित्व, जन्मदेखि नै सफलता"),
    YOGA_EFFECT_MAHA_RAJA("Exceptional fortune, royal status, widespread fame, great wealth and power", "असाधारण भाग्य, राजकीय स्थिति, व्यापक प्रसिद्धि, ठूलो धन र शक्ति"),
    YOGA_EFFECT_MALAVYA("Wealthy, enjoys all comforts, beautiful spouse, strong limbs, attractive face, blessed with vehicles and servants, learned in scriptures, lives up to 77 years", "धनी, सबै सुविधा भोग्ने, सुन्दर पति/पत्नी, बलियो अंगहरू, आकर्षक मुख, वाहन र सेवकहरूले आशीर्वादित, शास्त्रमा पढेको, ७७ वर्षसम्म बाँच्ने"),
    YOGA_EFFECT_MUSALA("Proud, wealthy, learned, famous, many children", "गर्विलो, धनी, पढेलेखेको, प्रसिद्ध, धेरै सन्तान"),
    YOGA_EFFECT_NALA("Handsome, skilled in arts, wealthy through multiple sources", "सुन्दर, कलामा दक्ष, विभिन्न स्रोतबाट धनी"),
    YOGA_EFFECT_NEECHA_BHANGA("Rise from humble beginnings, success after initial struggles, respected leader", "साधारण सुरुवातबाट उदय, प्रारम्भिक संघर्षपछि सफलता, सम्मानित नेता"),
    YOGA_EFFECT_PAPAKARTARI("Obstacles in self-expression, health challenges, restricted opportunities", "आत्म-अभिव्यक्तिमा बाधाहरू, स्वास्थ्य चुनौतीहरू, सीमित अवसरहरू"),
    YOGA_EFFECT_PARIJATA("Success in middle and later life, steady rise to prominence, respected authority", "मध्य र पछिल्लो जीवनमा सफलता, प्रमुखतामा स्थिर उदय, सम्मानित अधिकार"),
    YOGA_EFFECT_PARIVARTANA("Strong Raja Yoga through mutual exchange, stable rise to power, lasting authority", "आपसी आदानप्रदानबाट बलियो राज योग, शक्तिमा स्थिर उदय, दिगो अधिकार"),
    YOGA_EFFECT_PARVATA("King or minister, famous, generous, wealthy, charitable, mountain-like stability", "राजा वा मन्त्री, प्रसिद्ध, उदार, धनी, दानशील, पहाड जस्तो स्थिरता"),
    YOGA_EFFECT_PUSHAKALA("Wealthy, honored by rulers, famous, eloquent, good conduct", "धनी, शासकहरूद्वारा सम्मानित, प्रसिद्ध, वाक्पटु, राम्रो आचरण"),
    YOGA_EFFECT_RAJJU("Fond of travel, living in foreign lands, restless nature", "यात्राको शौकीन, विदेशी भूमिमा बस्ने, अशान्त स्वभाव"),
    YOGA_EFFECT_RUCHAKA("Commander, army chief, valorous, muscular body, red complexion, successful in conflicts, skilled in warfare, leader of thieves or soldiers, wealth through martial arts or defense", "सेनापति, सेना प्रमुख, वीर, बलियो शरीर, रातो रंग, द्वन्द्वमा सफल, युद्ध कलामा दक्ष, चोर वा सैनिकहरूको नेता, युद्ध कला वा रक्षाबाट धन"),
    YOGA_EFFECT_SAKATA("Fluctuating fortunes, periods of struggle followed by recovery, lessons in resilience", "उतारचढावपूर्ण भाग्य, संघर्षको अवधि पछि सुधार, लचिलोपनमा पाठ"),
    YOGA_EFFECT_SANKHYA_DAMINI("Charitable, famous, helpful to others, intelligent", "दानशील, प्रसिद्ध, अरूलाई मद्दत गर्ने, बुद्धिमान"),
    YOGA_EFFECT_SANKHYA_GOLA("Struggles in early life, need for persistence, unconventional path", "प्रारम्भिक जीवनमा संघर्ष, दृढताको आवश्यकता, अपरम्परागत मार्ग"),
    YOGA_EFFECT_SANKHYA_KEDARA("Agricultural wealth, helpful, truthful, steady progress", "कृषि धन, सहयोगी, सत्यवादी, स्थिर प्रगति"),
    YOGA_EFFECT_SANKHYA_PASA("Surrounded by friends and relatives, earns through proper means", "साथीभाइ र आफन्तहरूले घेरिएको, उचित माध्यमबाट कमाउने"),
    YOGA_EFFECT_SANKHYA_SHOOLA("Brave but potentially aggressive, success through competition", "बहादुर तर सम्भावित आक्रामक, प्रतिस्पर्धा मार्फत सफलता"),
    YOGA_EFFECT_SANKHYA_VALLAKI("Artistic talents, fond of music and dance, happy disposition", "कलात्मक प्रतिभा, संगीत र नृत्यको शौकीन, खुसी स्वभाव"),
    YOGA_EFFECT_SANKHYA_YUGA("Unconventional lifestyle, may face social challenges, religious or philosophical", "अपरम्परागत जीवनशैली, सामाजिक चुनौतीहरू सामना गर्न सक्ने, धार्मिक वा दार्शनिक"),
    YOGA_EFFECT_SANYASA("Renunciation tendencies, spiritual inclinations, detachment from worldly matters", "त्याग प्रवृत्तिहरू, आध्यात्मिक झुकाव, सांसारिक कुराहरूबाट विरक्ति"),
    YOGA_EFFECT_SARASWATI("Highly learned, poet, prose writer, famous speaker, skilled in all arts", "अत्यधिक पढेलेखेको, कवि, गद्य लेखक, प्रसिद्ध वक्ता, सबै कलाहरूमा दक्ष"),
    YOGA_EFFECT_SASA("Head of village/town/city, wicked disposition but good servants, intriguing nature, knows others' weaknesses, commands over masses, wealth through iron or labor", "गाउँ/शहर/नगरको प्रमुख, दुष्ट स्वभाव तर राम्रा सेवकहरू, षड्यन्त्रकारी स्वभाव, अरूको कमजोरी जान्ने, जनतामाथि आदेश, फलाम वा श्रमबाट धन"),
    YOGA_EFFECT_SHAKATA("Fluctuating fortune, periods of poverty alternating with wealth", "उतार-चढाव भाग्य, गरिबीको अवधि धनसँग पालैपालो"),
    YOGA_EFFECT_SHAKATA_NABHASA("Fluctuating fortune, poverty followed by wealth in cycles", "उतार-चढाव भाग्य, गरिबीपछि धन चक्रमा"),
    YOGA_EFFECT_SHOOLA("Sharp intellect, quarrelsome, cruel, poor", "तीक्ष्ण बुद्धि, झगडालु, निर्दयी, गरिब"),
    YOGA_EFFECT_SHRAPIT("Past-life karma manifesting as chronic obstacles, delays, fear, ancestral issues", "पूर्वजन्म कर्म दीर्घकालीन बाधाहरू, ढिलाइ, डर, पुर्खौली समस्याहरूको रूपमा प्रकट"),
    YOGA_EFFECT_SHRINGATAKA("Fond of quarrels initially, happiness in middle age, wandering in old age", "सुरुमा झगडा मनपर्ने, मध्य उमेरमा खुशी, बुढेसकालमा भौंतारिने"),
    YOGA_EFFECT_SHUBHAKARTARI("Protected life, good health, success in endeavors, helpful people around", "सुरक्षित जीवन, राम्रो स्वास्थ्य, प्रयासहरूमा सफलता, वरपर मद्दतगर्ने मानिसहरू"),
    YOGA_EFFECT_SUNAFA("Self-made wealth, intelligent, good status, praised by kings", "स्व-निर्मित धन, बुद्धिमान, राम्रो स्थिति, राजाहरूद्वारा प्रशंसित"),
    YOGA_EFFECT_SURYA_GRAHAN("Father-related troubles, ego issues, government problems, health issues with head/eyes", "पिता सम्बन्धी समस्याहरू, अहंकार समस्याहरू, सरकारी समस्याहरू, टाउको/आँखामा स्वास्थ्य समस्याहरू"),
    YOGA_EFFECT_SURYA_KETU_GRAHAN("Spiritual detachment, low self-esteem, father troubles, past-life karmic issues", "आध्यात्मिक विरक्ति, कम आत्मसम्मान, पिता समस्याहरू, पूर्वजन्म कर्म समस्याहरू"),
    YOGA_EFFECT_UBHAYACHARI("Eloquent speaker, wealthy, influential, respected by rulers", "वाक्पटु वक्ता, धनी, प्रभावशाली, शासकहरूद्वारा सम्मानित"),
    YOGA_EFFECT_VASUMATHI("Continuous accumulation of wealth, prosperity increasing with age, financial independence", "धनको निरन्तर सञ्चय, उमेरसँगै बढ्दो समृद्धि, आर्थिक स्वतन्त्रता"),
    YOGA_EFFECT_VEENA("Fond of music, dance, leader, wealthy, happy", "संगीत र नृत्यको शौकीन, नेता, धनी, खुशी"),
    YOGA_EFFECT_VESI("Wealth through hard work, truthful, balanced life, comfortable old age", "मेहनतबाट धन, सत्यवादी, सन्तुलित जीवन, आरामदायक बुढेसकाल"),
    YOGA_EFFECT_VIPARITA("Rise through fall of enemies, sudden fortune from unexpected sources, gains through others' losses", "शत्रुहरूको पतनबाट उदय, अप्रत्याशित स्रोतहरूबाट अचानक भाग्य, अरूको हानिबाट लाभ"),
    YOGA_EFFECT_VOSI("Famous, generous, skilled in service, gains through associations", "प्रसिद्ध, उदार, सेवामा दक्ष, संगतबाट लाभ"),
    YOGA_EFFECT_YAVA("Medium wealth initially, prosperity in middle age, decline in old age", "सुरुमा मध्यम धन, मध्य उमेरमा समृद्धि, बुढेसकालमा पतन"),
    YOGA_EFFECT_YUGA("Heretic, poor, rejected by family", "विधर्मी, गरिब, परिवारद्वारा त्यागिएको"),
    YOGA_FILTER_BY_CATEGORY("Filter by Category", "वर्गअनुसार फिल्टर गर्नुहोस्"),
    YOGA_GADA("Gada Yoga", "गदा योग"),
    YOGA_GAJA_KESARI("Gaja-Kesari Yoga", "गज-केसरी योग"),
    YOGA_GANAPATI("Ganapati Yoga", "गणपति योग"),
    YOGA_GANDANTA("Gandanta Yoga", "गण्डान्त योग"),
    YOGA_GOLA("Gola Yoga", "गोल योग"),
    YOGA_GOT_IT("Got it", "बुझें"),
    YOGA_GOURI("Gouri Yoga", "गौरी योग"),
    YOGA_GRAHAYUDDHA("Grahayuddha", "ग्रहयुद्ध"),
    YOGA_GURU_CHANDAL("Guru-Chandal Yoga", "गुरु-चांडाल योग"),
    YOGA_GURU_DIGNITY("Guru Dignity Yoga", "गुरु गरिमा योग"),
    YOGA_GURU_MANGALA("Guru Mangala Yoga", "गुरु मंगल योग"),
    YOGA_HAMSA("Hamsa Yoga", "हंस योग"),
    YOGA_HARIHARA_BRAHMA("Harihara Brahma Yoga", "हरिहर ब्रह्म योग"),
    YOGA_HOUSES_LABEL("Houses:", "भावहरू:"),
    YOGA_HOUSE_PREFIX("H", "भाव"),
    YOGA_INDU_LAGNA("Indu Lagna Dhana Yoga", "इन्दु लग्न धन योग"),
    YOGA_INDU_LAGNA_EXP("Indu Lagna Dhana Yoga", "इन्दु लग्न धन योग"),
    YOGA_INFORMATION("Yoga Information", "योग जानकारी"),
    YOGA_INHERITANCE("Inheritance Yoga", "उत्तराधिकार योग"),
    YOGA_KAHALA("Kahala Yoga", "कहल योग"),
    YOGA_KALANIDHI("Kalanidhi Yoga", "कलानिधि योग"),
    YOGA_KALATRA("Kalatra Yoga", "कलत्र योग"),
    YOGA_KALA_SARPA("Kala Sarpa Yoga", "कालसर्प योग"),
    YOGA_KAMALA("Kamala Yoga", "कमल योग"),
    YOGA_KAMINI("Kamini Yoga", "कामिनी योग"),
    YOGA_KEDARA("Kedara Yoga", "केदार योग"),
    YOGA_KEMADRUMA("Kemadruma Yoga", "केमद्रुम योग"),
    YOGA_KEMADRUMA_BHANGA("Kemadruma Bhanga", "केमद्रुम भंग"),
    YOGA_KENDRA_TRIKONA("Kendra-Trikona Raja Yoga", "केन्द्र-त्रिकोण राज योग"),
    YOGA_KETU_MOKSHA("Ketu Moksha Yoga", "केतु मोक्ष योग"),
    YOGA_KHADGA("Khadga Yoga", "खड्ग योग"),
    YOGA_KHALA_PARIVARTTANA("Khala Parivarttana Yoga", "खल परिवर्तन योग"),
    YOGA_KUBERA("Kubera Yoga", "कुबेर योग"),
    YOGA_KUBERA_EXP("Kubera Yoga", "कुबेर योग"),
    YOGA_KURMA("Kurma Yoga", "कूर्म योग"),
    YOGA_KUSUMA("Kusuma Yoga", "कुसुम योग"),
    YOGA_KUSUMA_EXP("Kusuma Yoga", "कुसुम योग"),
    YOGA_KUTA("Kuta Yoga", "कूट योग"),
    YOGA_LABHA("Labha Yoga", "लाभ योग"),
    YOGA_LAGNA_ADHI("Lagna Adhi Yoga", "लग्न अधि योग"),
    YOGA_LAGNESH_STRENGTH("Lagnesh Strength Yoga", "लग्नेश बल योग"),
    YOGA_LAKSHMI("Lakshmi Yoga", "लक्ष्मी योग"),
    YOGA_MAHALAKSHMI("Mahalakshmi Yoga", "महालक्ष्मी योग"),
    YOGA_MAHALAXMI("Mahalaxmi Yoga", "महालक्ष्मी योग"),
    YOGA_MAHA_BHAGYA("Maha Bhagya Yoga", "महा भाग्य योग"),
    YOGA_MAHA_PARIVARTTANA("Maha Parivarttana Yoga", "महा परिवर्तन योग"),
    YOGA_MAHA_RAJA("Maha Raja Yoga", "महा राज योग"),
    YOGA_MALAVYA("Malavya Yoga", "मालव्य योग"),
    YOGA_MANGAL_DIGNITY("Mangala Dignity Yoga", "मंगल गरिमा योग"),
    YOGA_MANIFESTATION("Manifestation Style", "अभिव्यक्ति शैली"),
    YOGA_MARRIAGE_EFFECT("Yoga Effect on Marriage", "विवाहमा योग प्रभाव"),
    YOGA_MATIMANTA("Matimanta Yoga", "मतिमंत योग"),
    YOGA_MATSYA("Matsya Yoga", "मत्स्य योग"),
    YOGA_MEANING_ACCOMPLISHED("Accomplished", "सिद्ध"),
    YOGA_MEANING_ACCOMPLISHMENT("Accomplishment", "सिद्धि"),
    YOGA_MEANING_ACHIEVABLE("Achievable", "साध्य"),
    YOGA_MEANING_AUSPICIOUS("Auspicious", "शुभ"),
    YOGA_MEANING_BRIGHT("Bright", "शुक्ल"),
    YOGA_MEANING_CALAMITY("Calamity", "व्यतीपात"),
    YOGA_MEANING_CREATOR("Creator", "ब्रह्मा"),
    YOGA_MEANING_DESTRUCTION("Destruction", "व्याघात"),
    YOGA_MEANING_DISCORD("Discord", "वैधृति"),
    YOGA_MEANING_EXCELLENT("Excellent", "वरीयान"),
    YOGA_MEANING_FIXED("Fixed", "ध्रुव"),
    YOGA_MEANING_GOOD_DEEDS("Good Deeds", "सुकर्म"),
    YOGA_MEANING_GOOD_FORTUNE("Good Fortune", "सौभाग्य"),
    YOGA_MEANING_GREAT_OBSTACLE("Great Obstacle", "अतिगण्ड"),
    YOGA_MEANING_GROWTH("Growth", "वृद्धि"),
    YOGA_MEANING_JOY("Joy", "हर्षण"),
    YOGA_MEANING_KING_OF_GODS("King of Gods", "इन्द्र"),
    YOGA_MEANING_LONG_LIVED("Long-lived", "दीर्घायु"),
    YOGA_MEANING_LOVE("Love", "प्रेम"),
    YOGA_MEANING_OBSTACLE("Obstacle", "गण्ड"),
    YOGA_MEANING_OBSTRUCTION("Obstruction", "परिघ"),
    YOGA_MEANING_SPEAR("Spear", "शूल"),
    YOGA_MEANING_SPLENDOR("Splendor", "वैभव"),
    YOGA_MEANING_STEADINESS("Steadiness", "धृति"),
    YOGA_MEANING_SUPPORTING("Supporting", "सहयोगी"),
    YOGA_MEANING_THUNDERBOLT("Thunderbolt", "वज्र"),
    YOGA_MOKSHA("Moksha Yoga", "मोक्ष योग"),
    YOGA_MOKSHA_TRIKONA("Moksha Trikona Yoga", "मोक्ष त्रिकोण योग"),
    YOGA_MOST_SIGNIFICANT("Most Significant Yogas", "सबैभन्दा महत्त्वपूर्ण योगहरू"),
    YOGA_MRIDANGA("Mridanga Yoga", "मृदंग योग"),
    YOGA_MUSALA("Musala Yoga", "मुसल योग"),
    YOGA_MUSALA_EXP("Musala Yoga", "मुसल योग"),
    YOGA_NAKSHATRA_DEVA("Deva Nakshatra Yoga", "देव नक्षत्र योग"),
    YOGA_NAKSHATRA_MANUSHYA("Manushya Nakshatra Yoga", "मनुष्य नक्षत्र योग"),
    YOGA_NAKSHATRA_RAKSHASA("Rakshasa Nakshatra Yoga", "राक्षस नक्षत्र योग"),
    YOGA_NALA("Nala Yoga", "नल योग"),
    YOGA_NALA_EXP("Nala Yoga", "नल योग"),
    YOGA_NATURE_AUSPICIOUS("Auspicious", "शुभ"),
    YOGA_NATURE_INAUSPICIOUS("Inauspicious", "अशुभ"),
    YOGA_NATURE_MIXED("Mixed", "मिश्र"),
    YOGA_NAUKA("Nauka Yoga", "नौका योग"),
    YOGA_NEECHABHILASHI("Neechabhilashi Yoga", "नीचाभिलाषी योग"),
    YOGA_NEECHA_BHANGA("Neecha Bhanga Raja Yoga", "नीच भंग राज योग"),
    YOGA_NEECHA_GRAHAS("Neecha Grahas Yoga", "नीच ग्रह योग"),
    YOGA_NIPUNA("Nipuna Yoga", "निपुण योग"),
    YOGA_NONE_DETECTED("No yogas detected", "कुनै योग पत्ता लागेन"),
    YOGA_NO_CATEGORY_FOUND("No %s found", "कुनै %s फेला परेन"),
    YOGA_NO_CHART_MESSAGE("Select or create a birth profile to view yogas.", "योगहरू हेर्न जन्म प्रोफाइल छान्नुहोस् वा बनाउनुहोस्।"),
    YOGA_NO_DATA("No yoga data available", "कुनै योग डाटा उपलब्ध छैन"),
    YOGA_NO_YOGAS_FOUND("No Yogas Found", "कुनै योग फेला परेन"),
    YOGA_OVERALL_STRENGTH("Overall Yoga Strength", "समग्र योग बल"),
    YOGA_PAPAKARTARI("Papakartari Yoga", "पापकर्तरी योग"),
    YOGA_PAPAKARTARI_LAGNA("Papakartari Lagna Yoga", "पापकर्तरी लग्न योग"),
    YOGA_PARAKRAMA("Parakrama Yoga", "पराक्रम योग"),
    YOGA_PARIJATA("Parijata Yoga", "पारिजात योग"),
    YOGA_PARIVARTANA("Parivartana Raja Yoga", "परिवर्तन राज योग"),
    YOGA_PARVATA("Parvata Yoga", "पर्वत योग"),
    YOGA_PERSONALITY_TITLE("Personality Yogas", "व्यक्तित्व योगहरू"),
    YOGA_PLANETS_INVOLVED("Planets Involved", "संलग्न ग्रहहरू"),
    YOGA_PRABHAKAR("Prabhakar Yoga", "प्रभाकर योग"),
    YOGA_PRACTICES("Yoga Practices", "योग अभ्यासहरू"),
    YOGA_PRAVRAJYA("Pravrajya Yoga", "प्रव्रज्या योग"),
    YOGA_PROPERTY("Property Yoga", "सम्पत्ति योग"),
    YOGA_PURNIMA("Purnima Yoga", "पूर्णिमा योग"),
    YOGA_PUSHAKALA("Pushkala Yoga", "पुष्कल योग"),
    YOGA_PUSHKARA_NAVAMSA("Pushkara Navamsha Yoga", "पुष्कर नवांश योग"),
    YOGA_PUSHYA_NAKSHATRA("Pushya Nakshatra Yoga", "पुष्य नक्षत्र योग"),
    YOGA_RAHU_UPACHAYA("Rahu Upachaya Yoga", "राहु उपचय योग"),
    YOGA_RAJJU("Rajju Yoga", "रज्जु योग"),
    YOGA_RAJJU_EXP("Rajju Yoga", "रज्जु योग"),
    YOGA_ROGAISHTA("Rogaishta Yoga", "रोगेष्ट योग"),
    YOGA_RUCHAKA("Ruchaka Yoga", "रुचक योग"),
    YOGA_SAKATA("Sakata Yoga", "शकट योग"),
    YOGA_SANKHYA_DAMINI("Damini Sankhya Yoga", "दामिनी साङ्ख्य योग"),
    YOGA_SANKHYA_GOLA("Gola Sankhya Yoga", "गोल साङ्ख्य योग"),
    YOGA_SANKHYA_KEDARA("Kedara Sankhya Yoga", "केदार साङ्ख्य योग"),
    YOGA_SANKHYA_PASA("Pasa Sankhya Yoga", "पास साङ्ख्य योग"),
    YOGA_SANKHYA_SHOOLA("Shoola Sankhya Yoga", "शूल साङ्ख्य योग"),
    YOGA_SANKHYA_VALLAKI("Vallaki Sankhya Yoga", "वल्लकी साङ्ख्य योग"),
    YOGA_SANKHYA_YUGA("Yuga Sankhya Yoga", "युग साङ्ख्य योग"),
    YOGA_SANNYASA("Sannyasa Yoga", "सन्यास योग"),
    YOGA_SANSKRIT("Sanskrit", "संस्कृत"),
    YOGA_SANYASA("Sanyasa Yoga", "सन्यास योग"),
    YOGA_SARASWATI("Saraswati Yoga", "सरस्वती योग"),
    YOGA_SASA("Sasa Yoga", "शश योग"),
    YOGA_SHAKATA("Shakata Yoga", "शकट योग"),
    YOGA_SHAKTI("Shakti Yoga", "शक्ति योग"),
    YOGA_SHANI("Shani Yoga", "शनि योग"),
    YOGA_SHANI_DIGNITY("Shani Dignity Yoga", "शनि गरिमा योग"),
    YOGA_SHARA("Shara Yoga", "शर योग"),
    YOGA_SHARADA("Sharada Yoga", "शारदा योग"),
    YOGA_SHOOLA("Shoola Yoga", "शूल योग"),
    YOGA_SHRAPIT("Shrapit Yoga", "शापित योग"),
    YOGA_SHRINGATAKA("Shringataka Yoga", "शृंगाटक योग"),
    YOGA_SHUBHAKARTARI("Shubhakartari Yoga", "शुभकर्तरी योग"),
    YOGA_SHUKRA_DIGNITY("Shukra Dignity Yoga", "शुक्र गरिमा योग"),
    YOGA_SIMHASANA("Simhasana Yoga", "सिंहासन योग"),
    YOGA_SPIRITUAL_EFFECT("Spiritual Yoga Effect", "आध्यात्मिक योग प्रभाव"),
    YOGA_SREENATHA("Sreenatha Yoga", "श्रीनाथ योग"),
    YOGA_STATUS_FMT("Status: %s", "अवस्था: %s"),
    YOGA_STRENGTH("Strength", "बल"),
    YOGA_STRENGTH_EXTREMELY_STRONG("Extremely Strong", "अत्यन्त बलियो"),
    YOGA_STRENGTH_FMT("Strength: %d%%", "बल: %d%%"),
    YOGA_STRENGTH_LABEL("Yoga Strength", "योग बल"),
    YOGA_STRENGTH_LEVEL_FMT("Strength: %s", "बल: %s"),
    YOGA_STRENGTH_MODERATE("Moderate", "मध्यम"),
    YOGA_STRENGTH_STRONG("Strong", "बलियो"),
    YOGA_STRENGTH_VERY_STRONG("Very Strong", "धेरै बलियो"),
    YOGA_STRENGTH_VERY_WEAK("Very Weak", "धेरै कमजोर"),
    YOGA_STRENGTH_WEAK("Weak", "कमजोर"),
    YOGA_SUBHAKARTARI_LAGNA("Subhakartari Lagna Yoga", "शुभकर्तरी लग्न योग"),
    YOGA_SUBHAPATI("Subhapati Yoga", "शुभपति योग"),
    YOGA_SUBTITLE("Planetary combinations in your chart", "तपाईंको कुण्डलीमा ग्रह संयोजनहरू"),
    YOGA_SUNAFA("Sunafa Yoga", "सुनफा योग"),
    YOGA_SURYA("Surya Yoga", "सूर्य योग"),
    YOGA_SURYA_DIGNITY("Surya Dignity Yoga", "सूर्य गरिमा योग"),
    YOGA_SURYA_GRAHAN("Surya Grahan Yoga", "सूर्य ग्रहण योग"),
    YOGA_SURYA_KETU_GRAHAN("Surya-Ketu Grahan Yoga", "सूर्य-केतु ग्रहण योग"),
    YOGA_SWAGRAHA("Swagraha Yoga", "स्वग्रह योग"),
    YOGA_TAPASVI("Tapasvi Yoga", "तपस्वी योग"),
    YOGA_TOTAL("Total Yogas", "कुल योगहरू"),
    YOGA_TRIGRAHA("Trigraha Yoga", "त्रिग्रह योग"),
    YOGA_TRIMURTI("Trimurti Yoga", "त्रिमूर्ति योग"),
    YOGA_UBHAYACHARI("Ubhayachari Yoga", "उभयचारी योग"),
    YOGA_UTTAMADI("Uttamadi Yoga", "उत्तमादि योग"),
    YOGA_UTTAMA_GRAHAS("Uttama Grahas Yoga", "उत्तम ग्रह योग"),
    YOGA_VAJRA("Vajra Yoga", "वज्र योग"),
    YOGA_VANIJYA("Vanijya Yoga", "वणिज्य योग"),
    YOGA_VAPI("Vapi Yoga", "वापी योग"),
    YOGA_VARGOTTAMA_LAGNA("Vargottama Lagna Yoga", "वर्गोत्तम लग्न योग"),
    YOGA_VARGOTTAMA_SPEC("Vargottama {0}", "वर्गोत्तम {0}"),
    YOGA_VARGOTTAMA_STRENGTH("Vargottama Strength", "वर्गोत्तम बल"),
    YOGA_VASUMATHI("Vasumathi Yoga", "वसुमथि योग"),
    YOGA_VEENA("Veena Yoga", "वीणा योग"),
    YOGA_VESI("Vesi Yoga", "वेशी योग"),
    YOGA_VIDYA("Vidya Yoga", "विद्या योग"),
    YOGA_VIEW_MORE("View More", "थप हेर्नुहोस्"),
    YOGA_VIJAYA("Vijaya Yoga", "विजय योग"),
    YOGA_VIJNAANA("Vijnaana Yoga", "विज्ञान योग"),
    YOGA_VIPARITA("Viparita Raja Yoga", "विपरीत राज योग"),
    YOGA_VOSI("Vosi Yoga", "वोशी योग"),
    YOGA_YAVA("Yava Yoga", "यव योग"),
    YOGA_YUGA("Yuga Yoga", "युग योग"),
    YOGA_YUPA("Yupa Yoga", "यूप योग")
}
