package com.astro.storm.core.common

enum class StringKeyUIPart1(override val en: String, override val ne: String) : StringKeyInterface {
    A11Y_COLLAPSE("Collapse", "संक्षिप्त गर्नुहोस्"),
    A11Y_EXPAND("Expand", "विस्तार गर्नुहोस्"),
    A11Y_NAVIGATE_BACK("Navigate back", "पछाडि जानुहोस्"),
    A11Y_SHOW_INFO("Show information", "जानकारी देखाउनुहोस्"),
    ACC_CHART_ANALYSIS("Chart analysis", "कुण्डली विश्लेषण"),
    ACC_COLLAPSE("Collapse section", "खण्ड संक्षिप्त गर्नुहोस्"),
    ACC_COMING_SOON("Coming soon", "चाँडै आउँदैछ"),
    ACC_EXPAND("Expand section", "खण्ड विस्तार गर्नुहोस्"),
    ACC_FULLSCREEN("Fullscreen", "पूर्णस्क्रीन"),
    ACC_PROFILE_AVATAR("Profile avatar", "प्रोफाइल अवतार"),
    ACC_VIEW_DETAILS("View details", "विवरण हेर्नुहोस्"),
    BTN_BACK("Back", "पछाडि"),
    BTN_CANCEL("Cancel", "रद्द गर्नुहोस्"),
    BTN_CLOSE("Close", "बन्द गर्नुहोस्"),
    BTN_CREATE_CHART("Create Chart", "कुण्डली बनाउनुहोस्"),
    BTN_DELETE("Delete", "मेट्नुहोस्"),
    BTN_DETAILS("Details", "विवरण"),
    BTN_EDIT("Edit", "सम्पादन गर्नुहोस्"),
    BTN_GENERATE("Generate", "उत्पन्न गर्नुहोस्"),
    BTN_GENERATE_SAVE("Generate & Save", "उत्पन्न गर्नुहोस् र सेभ गर्नुहोस्"),
    BTN_GOT_IT("Got it", "बुझें"),
    BTN_GO_BACK("Go back", "पछाडि जानुहोस्"),
    BTN_INTERPRET("Get Interpretation", "व्याख्या प्राप्त गर्नुहोस्"),
    BTN_JUMP_TODAY("Jump to today", "आजमा जानुहोस्"),
    BTN_NEW_QUERY("New Query", "नयाँ प्रश्न"),
    BTN_OK("OK", "ठीक छ"),
    BTN_PREVIEW("Preview", "पूर्वावलोकन"),
    BTN_REFRESH("Refresh", "रिफ्रेस"),
    BTN_REGENERATE("Regenerate", "पुन: उत्पन्न"),
    BTN_RETRY("Retry", "पुनः प्रयास"),
    BTN_SAVE("Save", "सेभ गर्नुहोस्"),
    BTN_SAVE_READING("Save Reading", "पठन सुरक्षित गर्नुहोस्"),
    BTN_TRY_AGAIN("Try Again", "फेरि प्रयास गर्नुहोस्"),
    BTN_UPDATE_SAVE("Update & Save", "अपडेट गर्नुहोस् र सेभ गर्नुहोस्"),
    BTN_VIEW_DETAILS("View Details", "विवरण हेर्नुहोस्"),
    COLOR_APP_JUP("Apply saffron tilak, wear yellow on Thursdays", "केशरी तिलक लगाउनुहोस्, बिहीबार पहेंलो लगाउनुहोस्"),
    COLOR_APP_KETU("Two-toned clothes work well, avoid bright single colors", "दुई रंगका लुगाहरू राम्रो हुन्छन्, चम्किलो एकनाश रंगबाट बच्नुहोस्"),
    COLOR_APP_MARS("Wear red on Tuesdays, keep red items in south direction", "मंगलबार रातो लगाउनुहोस्, दक्षिण दिशामा राता वस्तुहरू राख्नुहोस्"),
    COLOR_APP_MERC("Wear green on Wednesdays, keep green plants at home", "बुधबार हरियो लगाउनुहोस्, घरमा हरियो बोटबिरुवा राख्नुहोस्"),
    COLOR_APP_MOON("Prefer white clothes on Mondays, keep white items at home", "सोमबार सेतो कपडा लगाउनुहोस्, घरमा सेता वस्तुहरू राख्नुहोस्"),
    COLOR_APP_RAHU("Prefer subdued colors, avoid flashy dressing", "हल्का रंगहरू रोज्नुहोस्, चम्किलो लुगाबाट बच्नुहोस्"),
    COLOR_APP_SAT("Wear blue/black on Saturdays, donate black items", "शनिबार नीलो/कालो लगाउनुहोस्, कालो वस्तुहरू दान गर्नुहोस्"),
    COLOR_APP_SUN("Wear these colors on Sundays, especially in upper garments", "आइतबार यी रंगहरू लगाउनुहोस्, विशेष गरी माथिल्लो शरीरमा"),
    COLOR_APP_VENUS("Wear white or pink on Fridays, keep white items in bedroom", "शुक्रबार सेतो वा गुलाबी लगाउनुहोस्, सुत्ने कोठामा सेता वस्तुहरू राख्नुहोस्"),
    COLOR_BENEFIT_COST("No cost or side effects", "कुनै लागत वा साइड इफेक्ट छैन"),
    COLOR_BENEFIT_EASY("Easy to implement daily", "दैनिक लागू गर्न सजिलो"),
    COLOR_BENEFIT_SUBTLE("Subtle but effective energy enhancement", "सूक्ष्म तर प्रभावकारी ऊर्जा वृद्धि"),
    COLOR_BLACK("Black", "कालो"),
    COLOR_BLUE("Blue", "नीलो"),
    COLOR_BLUE_LIGHT_SILVER("Blue, Light Blue, or Silver", "निलो, हल्का निलो, वा चाँदी"),
    COLOR_BROWN("Brown", "खैरो"),
    COLOR_CAUTION_BALANCE("Balance with colors for other weak planets", "अन्य कमजोर ग्रहहरूको लागि रंगहरूसँग सन्तुलन गर्नुहोस्"),
    COLOR_CORAL("Coral", "मुगा रंग"),
    COLOR_CREAM("Cream", "क्रीम"),
    COLOR_DARK("Dark colors", "गाढा रंगहरू"),
    COLOR_DESC("Use colors associated with %s to create favorable energy vibrations.", "अनुकूल ऊर्जा कम्पनहरू सिर्जना गर्न %s सँग सम्बन्धित रंगहरू प्रयोग गर्नुहोस्।"),
    COLOR_DURATION("Daily practice, particularly during %s's Dasha period", "दैनिक अभ्यास, विशेष गरी %s को दशा अवधिमा"),
    COLOR_EMERALD("Emerald", "पन्ना"),
    COLOR_GOLD("Gold", "सुनौलो"),
    COLOR_GREEN("Green", "हरियो"),
    COLOR_GREEN_BROWN_WHITE("Green, Brown, or White", "हरियो, खैरो, वा सेतो"),
    COLOR_GREY("Grey", "खरानी"),
    COLOR_INDIGO("Indigo", "इन्डिगो"),
    COLOR_JUPITER_AVOID("Blue, Black", "नीलो, कालो"),
    COLOR_JUPITER_USE("Yellow, Gold, Turmeric, Saffron, Orange-Yellow", "पहेंलो, सुनौलो, बेसार रङ, केसर, सुन्तला-पहेंलो"),
    COLOR_KETU_AVOID("Bright colors", "चम्किलो रङहरू"),
    COLOR_KETU_USE("Gray, Brown, Smoky, Earthy tones", "खैरो, माटो रङ, धुवाँ रङ"),
    COLOR_LIGHT_BLUE("Light Blue", "हल्का नीलो"),
    COLOR_MAROON("Maroon", "मरुन"),
    COLOR_MARS_AVOID("Blue, Green", "नीलो, हरियो"),
    COLOR_MARS_USE("Red, Maroon, Coral Red, Scarlet", "रातो, मेरुन, मुगा रातो, गाढा रातो"),
    COLOR_MERCURY_AVOID("Red", "रातो"),
    COLOR_MERCURY_USE("Green, Light Green, Emerald Green, Parrot Green", "हरियो, हल्का हरियो, पन्ना हरियो, सुगा रङ"),
    COLOR_METHOD("Wear clothes of these colors: %s\n\nUse these colors in your room, workspace, and personal accessories.\n\nAvoid: %s on %s", "यी रंगका लुगाहरू लगाउनुहोस्: %s\n\nयी रंगहरू आफ्नो कोठा, कार्यस्थल र व्यक्तिगत सामानहरूमा प्रयोग गर्नुहोस्।\n\nपरिहार गर्नुहोस्: %s, %s मा"),
    COLOR_MIXED("Mixed colors", "मिश्रित रंगहरू"),
    COLOR_MOON_AVOID("Red, Black", "रातो, कालो"),
    COLOR_MOON_USE("White, Silver, Light Blue, Cream, Pearl White", "सेतो, चाँदी, हल्का नीलो, क्रिम, मोती सेतो"),
    COLOR_MULTI("Multi-colored", "बहुरंगी"),
    COLOR_ORANGE("Orange", "सुन्तला"),
    COLOR_PASTEL("Pastel", "पास्टेल"),
    COLOR_PEARL("Pearl White", "मोती"),
    COLOR_PINK("Pink", "गुलाबी"),
    COLOR_PURPLE("Purple", "बैजनी"),
    COLOR_RAHU_AVOID("Pure White", "शुद्ध सेतो"),
    COLOR_RAHU_USE("Smoke Blue, Electric Blue, Multi-colored", "धुवाँ नीलो, इलेक्ट्रिक नीलो, बहुरंगी"),
    COLOR_RED("Red", "रातो"),
    COLOR_RED_ORANGE_GOLD("Red, Orange, or Gold", "रातो, सुन्तला, वा सुनौलो"),
    COLOR_SATURN_AVOID("Red, Orange", "रातो, सुन्तला"),
    COLOR_SATURN_USE("Blue, Black, Dark Blue, Navy, Violet", "नीलो, कालो, गाढा नीलो, नेभी, बैजनी"),
    COLOR_SCARLET("Scarlet", "सिन्दूरे"),
    COLOR_SEA_GREEN("Sea Green", "समुद्री हरियो"),
    COLOR_SILVER("Silver", "चाँदी"),
    COLOR_SMOKY("Smoky", "धुवाँ"),
    COLOR_SUN_AVOID("Blue, Black", "नीलो, कालो"),
    COLOR_SUN_USE("Orange, Red, Ruby Red, Gold, Saffron", "सुन्तला, रातो, माणिक रातो, सुनौलो, केसर"),
    COLOR_TIMING("Especially on %s", "विशेष गरी %s मा"),
    COLOR_TITLE_SUFFIX(" Color Therapy", " रंग चिकित्सा"),
    COLOR_TURQUOISE("Turquoise", "फिरोजा"),
    COLOR_VENUS_AVOID("Red, Blue", "रातो, नीलो"),
    COLOR_VENUS_USE("White, Pink, Light Colors, Cream, Pastel shades", "सेतो, गुलाबी, हल्का रङहरू, क्रिम, पेस्टल सेड्स"),
    COLOR_WHITE("White", "सेतो"),
    COLOR_WHITE_CREAM_SEA("White, Cream, or Sea Green", "सेतो, क्रिम, वा समुद्री हरियो"),
    COLOR_YELLOW("Yellow", "हेलों"),
    DIALOG_AT_WAR_WITH("At war with %s", "%s सँग युद्धमा"),
    DIALOG_BASIC_INFO("Basic Information", "आधारभूत जानकारी"),
    DIALOG_BENEFIC("Benefic", "शुभ"),
    DIALOG_BODY_PARTS("Body Parts:", "शरीर अंग:"),
    DIALOG_CAREER_INDICATIONS("Career Indications", "क्यारियर संकेतहरू"),
    DIALOG_CHART_SAVED("Chart saved to gallery!", "चार्ट ग्यालेरीमा सेभ भयो!"),
    DIALOG_CHART_STRENGTH("Chart Strength", "कुण्डली बल"),
    DIALOG_CHESTA_BALA("Chesta Bala (Motional)", "चेष्टा बल"),
    DIALOG_CLOSE("Close", "बन्द गर्नुहोस्"),
    DIALOG_COMBUSTION("Combustion", "अस्त"),
    DIALOG_CUSP_DEGREE("Cusp Degree", "सन्धि अंश"),
    DIALOG_DEGREE("Degree", "अंश"),
    DIALOG_DEGREE_RANGE("Degree Range", "अंश दायरा"),
    DIALOG_DELETE_CONFIRM("Are you sure you want to delete %s? This action cannot be undone.", "के तपाईं %s मेट्न चाहनुहुन्छ? यो कार्य पूर्ववत गर्न सकिँदैन।"),
    DIALOG_DELETE_PROFILE("Delete Profile", "प्रोफाइल मेट्नुहोस्"),
    DIALOG_DETAILED_INTERPRETATION("Detailed Interpretation", "विस्तृत व्याख्या"),
    DIALOG_DIGNITY("Dignity", "मर्यादा"),
    DIALOG_DIG_BALA("Dig Bala (Directional)", "दिग्बल"),
    DIALOG_DOWNLOAD("Download", "डाउनलोड"),
    DIALOG_DRIK_BALA("Drik Bala (Aspectual)", "दृग्बल"),
    DIALOG_ELEMENT("Element", "तत्व"),
    DIALOG_EXPORT_CHART("Export Chart", "कुण्डली निर्यात गर्नुहोस्"),
    DIALOG_GENDER("Gender", "लिङ्ग"),
    DIALOG_GENERAL_CHARACTERISTICS("General Characteristics", "सामान्य विशेषताहरू"),
    DIALOG_HOUSE("House", "भाव"),
    DIALOG_HOUSE_INFO("House Information", "भाव जानकारी"),
    DIALOG_HOUSE_PLACEMENT("House %d Placement", "भाव %d स्थिति"),
    DIALOG_HOUSE_TYPE("House Type", "भाव प्रकार"),
    DIALOG_INSIGHTS_PREDICTIONS("Insights & Predictions", "अन्तर्दृष्टि र भविष्यवाणी"),
    DIALOG_KALA_BALA("Kala Bala (Temporal)", "काल बल"),
    DIALOG_MALEFIC("Malefic", "पापी"),
    DIALOG_MOTION("Motion", "गति"),
    DIALOG_NAISARGIKA_BALA("Naisargika Bala (Natural)", "नैसर्गिक बल"),
    DIALOG_NAKSHATRA("Nakshatra", "नक्षत्र"),
    DIALOG_NAKSHATRA_DEITY("Nakshatra Deity", "नक्षत्र देवता"),
    DIALOG_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
    DIALOG_NAKSHATRA_NATURE("Nakshatra Nature", "नक्षत्र प्रकृति"),
    DIALOG_NATURE("Nature", "प्रकृति"),
    DIALOG_NAVAMSA_SIGN("Navamsa Sign", "नवांश राशि"),
    DIALOG_NUMBER("Number", "क्रमांक"),
    DIALOG_OVERALL("Overall: %s / %s Rupas", "समग्र: %s / %s रुपा"),
    DIALOG_OVERALL_SUMMARY("Overall Summary", "समग्र सारांश"),
    DIALOG_PADA_CHARACTERISTICS("Pada %d Characteristics", "पाद %d विशेषताहरू"),
    DIALOG_PERCENT_OF_REQUIRED("%s%% of required strength", "आवश्यक बलको %s%%"),
    DIALOG_PLANETARY_WAR("Planetary War", "ग्रहयुद्ध"),
    DIALOG_PLANETS_IN_HOUSE("Planets in House", "भावमा ग्रहहरू"),
    DIALOG_POSITION_DETAILS("Position Details", "स्थिति विवरण"),
    DIALOG_PROFESSIONS("Professions:", "पेशाहरू:"),
    DIALOG_REPRESENTS("Represents:", "प्रतिनिधित्व:"),
    DIALOG_REQUIRED_STRENGTH("Required", "आवश्यक"),
    DIALOG_RESET("Reset", "रिसेट"),
    DIALOG_RETROGRADE("Retrograde", "वक्री"),
    DIALOG_SAVE_FAILED("Failed to save chart", "चार्ट सेभ गर्न असफल"),
    DIALOG_SAVING("Saving...", "सेभ गर्दै..."),
    DIALOG_SHADBALA_ANALYSIS("Shadbala Analysis", "षड्बल विश्लेषण"),
    DIALOG_SIGNIFICATIONS("Significations & Nature", "करकत्व र प्रकृति"),
    DIALOG_SIGN_LORD("Sign Lord", "राशि स्वामी"),
    DIALOG_SIXFOLD_STRENGTH("Six-fold Planetary Strength", "छवटा ग्रह बल"),
    DIALOG_STATUS_CONDITIONS("Status & Conditions", "स्थिति र अवस्था"),
    DIALOG_STHANA_BALA("Sthana Bala (Positional)", "स्थान बल"),
    DIALOG_STRENGTH_ANALYSIS("Strength Analysis (Shadbala)", "बल विश्लेषण (षड्बल)"),
    DIALOG_STRENGTH_BREAKDOWN("Strength Breakdown (Virupas)", "बल विभाजन (विरुपा)"),
    DIALOG_STRONGEST("Strongest", "सबैभन्दा बलियो"),
    DIALOG_TOTAL_VIRUPAS("Total Virupas", "कुल विरुपा"),
    DIALOG_WEAKEST("Weakest", "सबैभन्दा कमजोर"),
    DIALOG_ZODIAC_SIGN("Zodiac Sign", "राशि"),
    DIALOG_ZOOM_IN("Zoom In", "ठूलो पार्नुहोस्"),
    DIALOG_ZOOM_OUT("Zoom Out", "सानो पार्नुहोस्"),
    DIGNITY_COMBUST("Combust", "अस्त"),
    DIGNITY_DEBILITATED("Debilitated", "नीच"),
    DIGNITY_DEBILITATED_STATUS("Debilitated", "नीच"),
    DIGNITY_DUSTHANA("in a challenging house (Dusthana)", "दुःस्थान भावमा"),
    DIGNITY_ENEMY("Enemy", "शत्रु"),
    DIGNITY_EXALTED("Exalted", "उच्च"),
    DIGNITY_EXALTED_STATUS("Exalted", "उच्च"),
    DIGNITY_FRIEND("Friend", "मित्र"),
    DIGNITY_FRIENDLY("in the friendly sign of %s", "%s मित्र राशिमा"),
    DIGNITY_GAINS("in a house of gains", "लाभ भावमा"),
    DIGNITY_GREAT_ENEMY("Great Enemy", "अधिशत्रु"),
    DIGNITY_GREAT_FRIEND("Great Friend", "अधिमित्र"),
    DIGNITY_IN_SIGN("%s in %s", "%s %s मा"),
    DIGNITY_KENDRA("in an angular house (Kendra)", "केन्द्र भावमा"),
    DIGNITY_MOOLATRIKONA("Moolatrikona", "मूलत्रिकोण"),
    DIGNITY_MOOLTRIKONA("(Mooltrikona)", "(मूलत्रिकोण)"),
    DIGNITY_NEUTRAL("Neutral", "सम"),
    DIGNITY_NEUTRAL_STATUS("Neutral", "तटस्थ"),
    DIGNITY_OWN("(Own Sign)", "(स्वराशि)"),
    DIGNITY_OWN_SIGN("Own Sign", "स्वराशि"),
    DIGNITY_OWN_SIGN_STATUS("Own Sign", "स्वगृह"),
    DIGNITY_RETRO("Retrograde", "वक्री"),
    DIGNITY_RETROGRADE("and is retrograde", "र वक्री छ"),
    DIGNITY_TRIKONA("in a trine house (Trikona)", "त्रिकोण भावमा"),
    DIGNITY_UPACHAYA("in an upachaya house", "उपचय भावमा"),
    DIGNITY_YEARLORD_DESC("The Year Lord %s is %s. This suggests its influence will be potent and its results will manifest clearly throughout the year.", "वर्ष स्वामी %s %s छ। यसले संकेत गर्छ कि यसको प्रभाव शक्तिशाली हुनेछ र यसको परिणामहरू वर्षभर स्पष्ट रूपमा प्रकट हुनेछन्।"),
    GEMSTONE_BHADRA("Emerald (Panna)", "पन्ना"),
    GEMSTONE_BLUE_SAPPHIRE("Blue Sapphire", "नीलम"),
    GEMSTONE_CATS_EYE("Cat's Eye", "लहसुनिया"),
    GEMSTONE_CAUTIONS("Cautions", "सावधानीहरू"),
    GEMSTONE_DIAMOND("Diamond/White Sapphire", "हीरा/सेतो नीलम"),
    GEMSTONE_EMERALD("Emerald", "पन्ना"),
    GEMSTONE_HAMSA("Yellow Sapphire (Pukhraj)", "पुष्पराज"),
    GEMSTONE_HESSONITE("Hessonite", "गोमेद"),
    GEMSTONE_MALAVYA("Diamond (Heera) or White Sapphire", "हीरा वा सेतो नीलम"),
    GEMSTONE_PEARL("Pearl", "मोती"),
    GEMSTONE_RED_CORAL("Red Coral", "मूंगा"),
    GEMSTONE_REMEDIES("Gemstone Remedies", "रत्न उपचारहरू"),
    GEMSTONE_RUBY("Ruby", "माणिक"),
    GEMSTONE_RUCHAKA("Red Coral (Moonga)", "मुगा"),
    GEMSTONE_SASHA("Blue Sapphire (Neelam) - only after careful consultation", "नीलम - सावधानीपूर्वक परामर्श पछि मात्र"),
    GEMSTONE_YELLOW_SAPPHIRE("Yellow Sapphire", "पुखराज"),
    GENDER_FEMALE("Female", "महिला"),
    GENDER_MALE("Male", "पुरुष"),
    GENDER_OTHER("Other", "अन्य"),
    LABEL_ACTUAL_DEGREE("Actual: %s°", "वास्तविक: %s°"),
    LABEL_AD("AD", "ई.सं."),
    LABEL_ANALYSIS_ERROR("Analysis Error", "विश्लेषण त्रुटि"),
    LABEL_ANALYZING_CHART("Analyzing chart...", "कुण्डली विश्लेषण गर्दै..."),
    LABEL_BS("BS", "बि.सं."),
    LABEL_CAREER_INDICATORS("Career Indicators", "क्यारियरका सूचकहरू"),
    LABEL_CHALLENGES("Challenges", "चुनौतीहरू"),
    LABEL_COMPREHENSIVE_DESC("This comprehensive analysis examines your birth chart to provide insights into various life areas including personality, career, relationships, health, wealth, education, and spiritual path.", "यो व्यापक विश्लेषणले व्यक्तित्व, क्यारियर, सम्बन्ध, स्वास्थ्य, धन, शिक्षा, र आध्यात्मिक मार्ग सहित विभिन्न जीवन क्षेत्रहरूमा अन्तर्दृष्टि प्रदान गर्न तपाईंको जन्म कुण्डलीको परीक्षण गर्दछ।"),
    LABEL_DASH("-", "-"),
    LABEL_DHANA_YOGA_PRESENT("Dhana Yoga Present", "धन योग उपस्थित"),
    LABEL_FAVORABLE_CAREER_FIELDS("Favorable Career Fields", "अनुकूल क्यारियर क्षेत्रहरू"),
    LABEL_FAVORABLE_PERIODS("Favorable Periods", "अनुकूल समय"),
    LABEL_FAVORABLE_SUBJECTS("Favorable Subjects", "अनुकूल विषयहरू"),
    LABEL_GANDANTA("Gandanta", "गण्डान्त"),
    LABEL_GAND_IN("in Gandanta", "गण्डान्तमा"),
    LABEL_GAND_REM("Gandanta Remedies", "गण्डान्त उपायहरू"),
    LABEL_HEALTH_CONCERNS("Health Concerns", "स्वास्थ्य चिन्ताहरू"),
    LABEL_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
    LABEL_IN_HOUSE("In House", "भावमा"),
    LABEL_JUPITER_BLESSING("Jupiter's Blessing", "बृहस्पतिको आशीर्वाद"),
    LABEL_LONGEVITY_INDICATOR("Longevity Indicator", "दीर्घायु सूचक"),
    LABEL_MARRIAGE_TIMING("Marriage Timing", "विवाहको समय"),
    LABEL_MB("Mrityu Bhaga", "मृत्यु भाग"),
    LABEL_MB_DEGREE("MB: %s°", "मृ.भा.: %s°"),
    LABEL_MB_IN("in Mrityu Bhaga", "मृत्यु भागमा"),
    LABEL_MERCURY_STRENGTH("Mercury Strength", "बुधको बल"),
    LABEL_NA("N/A", "-"),
    LABEL_NEXT_MONTH("Next month", "अर्को महिना"),
    LABEL_NOURISHING_DEGREE("Nourishing degree: %1\$s° (Orb: %2\$s°)", "पोषक डिग्री: %1\$s° (अर्ब: %2\$s°)"),
    LABEL_NO_CHART_SELECTED("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
    LABEL_OVERVIEW("Overview", "सारांश"),
    LABEL_PERCENT_REQUIRED("% of required", "आवश्यकको %"),
    LABEL_PERCENT_REQUIRED_VALUE("%s%% of required", "आवश्यकको %s%%"),
    LABEL_PERSONALITY_FOUNDATION("Personality Foundation", "व्यक्तित्वको आधार"),
    LABEL_PLANETARY_INFLUENCE("Planetary Influence", "ग्रह प्रभाव"),
    LABEL_PLANETS_IN_HOUSE("Planets in %dth House", "%dऔं भावमा ग्रहहरू"),
    LABEL_PLANET_REM("%s Remedies", "%s उपायहरू"),
    LABEL_PLANET_SPEC_REM("Planet-Specific Remedies", "ग्रह-विशिष्ट उपायहरू"),
    LABEL_PREDICTIONS("Predictions", "भविष्यवाणी"),
    LABEL_PREVIOUS_MONTH("Previous month", "अघिल्लो महिना"),
    LABEL_PRIMARY_WEALTH_SOURCES("Primary Wealth Sources", "मुख्य धन स्रोतहरू"),
    LABEL_PUSH_BHAGA("Pushkara Bhaga", "पुष्कर भाग"),
    LABEL_PUSH_BHAGA_IN("in Pushkara Bhaga", "पुष्कर भागमा"),
    LABEL_PUSH_NAV("Pushkara Navamsa", "पुष्कर नवरांश"),
    LABEL_PUSH_NAV_IN("in Pushkara Navamsa", "पुष्कर नवरांशमा"),
    LABEL_RECOMMENDED_PRACTICES("Recommended Practices", "सिफारिस गरिएका अभ्यासहरू"),
    LABEL_REMEDIES("Remedial Measures", "उपाय"),
    LABEL_REQUIRED("Required:", "आवश्यक:"),
    LABEL_REQUIRED_VALUE("Required: %s", "आवश्यक: %s"),
    LABEL_RUPAS("Rupas", "रूपा"),
    LABEL_SELECT_CHART_DESC("Please select a birth chart to view native analysis", "जातक विश्लेषण हेर्न कृपया जन्म कुण्डली छान्नुहोस्"),
    LABEL_SPIRITUAL_INDICATORS("Spiritual Indicators", "आध्यात्मिक सूचकहरू"),
    LABEL_SPOUSE_NATURE("Spouse Nature", "जीवनसाथीको स्वभाव"),
    LABEL_STRENGTHS("Key Strengths", "मुख्य शक्तिहरू"),
    LABEL_TODAY("Today", "आज"),
    LABEL_UNKNOWN("Unknown", "अज्ञात"),
    LABEL_VENUS_STRENGTH("Venus Strength", "शुक्रको बल"),
    LABEL_VULNERABLE_AREAS("Vulnerable Areas", "कमजोर क्षेत्रहरू"),
    LABEL_WEALTH_LORDS("Wealth Lords", "धनका स्वामीहरू"),
    SCREEN_CALCULATING("Calculating analysis...", "विश्लेषण गणना गर्दै..."),
    SCREEN_DESC("Kerala tradition cowrie shell divination integrated with chart analysis", "कुण्डली विश्लेषणसँग एकीकृत केरल परम्परा कौडी भविष्यवाणी"),
    SCREEN_DETAILS("Details", "विवरणहरू"),
    SCREEN_ERROR_CALCULATION("Error calculating results", "परिणाम गणनामा त्रुटि"),
    SCREEN_INTERPRETATION("Interpretation", "व्याख्या"),
    SCREEN_NO_DATA("No data available", "कुनै डाटा उपलब्ध छैन"),
    SCREEN_OVERVIEW("Overview", "सिंहावलोकन"),
    SCREEN_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    SCREEN_SUBTITLE("Eight-fold Horary Divination", "आठ-गुना प्रश्न विज्ञान"),
    SCREEN_TIMELINE("Timeline", "समयरेखा"),
    SCREEN_TITLE("Ashtamangala Prashna", "अष्टमंगल प्रश्न"),
    STRENGTH_ABOVE_AVERAGE("Above Average", "औसतभन्दा माथि"),
    STRENGTH_AFFLICTED("Afflicted", "पीडित"),
    STRENGTH_ASCENDANT("Ascendant", "लग्न"),
    STRENGTH_AVERAGE("Average", "औसत"),
    STRENGTH_AVERAGE_KEMA("Average", "औसत"),
    STRENGTH_BELOW_AVERAGE("Below Average", "औसतमुनि"),
    STRENGTH_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    STRENGTH_COURAGE("Courage", "साहस"),
    STRENGTH_DEBILITATED_KEMA("Weak (Debilitated)", "कमजोर (नीच)"),
    STRENGTH_DETERMINATION("Determination", "दृढ संकल्प"),
    STRENGTH_DIFFICULT("Difficult", "कठिन"),
    STRENGTH_ENDURANCE("Endurance", "सहनशीलता"),
    STRENGTH_ERROR("Error", "त्रुटि"),
    STRENGTH_EXALTED_KEMA("Strong (Exalted)", "बलियो (उच्च)"),
    STRENGTH_EXCELLENT("Excellent", "उत्कृष्ट"),
    STRENGTH_EXCEPTIONAL("Exceptional", "असाधारण"),
    STRENGTH_EXTREMELY_STRONG("Extremely Strong", "अति शक्तिशाली"),
    STRENGTH_EXTREMELY_WEAK("Extremely Weak", "अत्यन्त कमजोर"),
    STRENGTH_FACTORS("Strength Factors", "बल कारकहरू"),
    STRENGTH_FAME_POTENTIAL("Fame potential", "प्रसिद्धिको सम्भावना"),
    STRENGTH_GOOD("Good", "राम्रो"),
    STRENGTH_INITIATIVE("Initiative", "पहल"),
    STRENGTH_INNER_STRENGTH("Inner strength", "भित्री शक्ति"),
    STRENGTH_INTUITION("Intuition", "अन्तर्ज्ञान"),
    STRENGTH_LABEL("Strength", "बल"),
    STRENGTH_LEVEL_EXCEPTIONAL("Exceptional (80-100%)", "असाधारण (८०-१००%)"),
    STRENGTH_LEVEL_MODERATE("Moderate (40-59%)", "मध्यम (४०-५९%)"),
    STRENGTH_LEVEL_STRONG("Strong (60-79%)", "बलियो (६०-७९%)"),
    STRENGTH_LEVEL_VERY_WEAK("Very Weak (0-19%)", "धेरै कमजोर (०-१९%)"),
    STRENGTH_LEVEL_WEAK("Weak (20-39%)", "कमजोर (२०-३९%)"),
    STRENGTH_MILD("Mild", "हल्का"),
    STRENGTH_MODERATE("Moderate", "मध्यम"),
    STRENGTH_MODERATE_VIP("Moderate", "मध्यम"),
    STRENGTH_MOOLATRIKONA_KEMA("Strong (Moolatrikona)", "बलियो (मूलत्रिकोण)"),
    STRENGTH_NOT_FORMED("Not Formed", "बनेको छैन"),
    STRENGTH_OWN_SIGN_KEMA("Strong (Own Sign)", "बलियो (स्वराशि)"),
    STRENGTH_PURIFYING_INFLUENCE("Purifying influence", "शुद्धिकरण प्रभाव"),
    STRENGTH_QUICK_HEALER("Quick healer", "छिटो निको पार्ने"),
    STRENGTH_REJUVENATION("Rejuvenation ability", "पुनरुत्थान क्षमता"),
    STRENGTH_SELF_DISCIPLINE("Self-discipline", "आत्म-अनुशासन"),
    STRENGTH_SHARP_MIND("Sharp mind", "तीक्ष्ण मन"),
    STRENGTH_STRONG("Strong", "बलियो"),
    STRENGTH_STRONG_VIP("Strong", "बलियो"),
    STRENGTH_STRONG_WILL("Strong will", "बलियो इच्छाशक्ति"),
    STRENGTH_VERY_STRONG("Very Strong", "अति बलियो"),
    STRENGTH_VERY_WEAK("Very Weak", "अति कमजोर"),
    STRENGTH_WEAK("Weak", "कमजोर"),
    STRENGTH_WEAK_VIP("Weak", "कमजोर"),
    TAB_ALL_SAHAMS("All Sahams", "सबै सहमहरू"),
    TAB_ANALYSIS("Analysis", "विश्लेषण"),
    TAB_ASPECTS("Aspects", "दृष्टिहरू"),
    TAB_BIRTH_DAY("Birth Day", "जन्म दिन"),
    TAB_BY_CATEGORY("By Category", "वर्गानुसार"),
    TAB_BY_HOUSE("By House", "भावानुसार"),
    TAB_BY_PLANET("By Planet", "ग्रहानुसार"),
    TAB_CHAT("Chat", "च्याट"),
    TAB_CURRENT_POSITIONS("Current Positions", "हालको स्थिति"),
    TAB_DASHA("Dasha", "दशा"),
    TAB_DETAILS("Details", "विवरणहरू"),
    TAB_DIGNITIES("Dignities", "मर्यादाहरू"),
    TAB_ELEMENTS("Elements", "तत्वहरू"),
    TAB_FIND_MUHURTA("Find Muhurta", "मुहूर्त खोज्नुहोस्"),
    TAB_HOME("Home", "गृह"),
    TAB_HOUSES("Houses", "भावहरू"),
    TAB_INSIGHTS("Insights", "अन्तर्दृष्टि"),
    TAB_OVERVIEW("Overview", "अवलोकन"),
    TAB_PLANETS("Planets", "ग्रहहरू"),
    TAB_POSITIONS("Positions", "स्थितिहरू"),
    TAB_QUERY("Query", "प्रश्न"),
    TAB_REMEDIES("Remedies", "उपायहरू"),
    TAB_SAHAMS("Sahams", "सहमहरू"),
    TAB_SARVASHTAKAVARGA("Sarvashtakavarga", "सर्वाष्टकवर्ग"),
    TAB_SETTINGS("Settings", "सेटिङ्स"),
    TAB_STRENGTH("Strength", "बल"),
    TAB_TAJIKA("Tajika", "ताजिक"),
    TAB_TIMING("Timing", "समय"),
    TAB_TODAY("Today", "आज"),
    TAB_TRANSITS("Transits", "गोचर"),
    TAB_UPCOMING("Upcoming", "आगामी"),
    UI_AFFECTED_AREAS("Affected Areas", "प्रभावित क्षेत्रहरू"),
    UI_ALL_COUNT_FMT("All (%d)", "सबै (%d)"),
    UI_ANALYSIS_ERROR("Analysis Error", "विश्लेषण त्रुटि"),
    UI_ARGALA_INFLUENCES("Argala Influences", "अर्गला प्रभावहरू"),
    UI_ASCENDING("Ascending", "आरोही"),
    UI_ASPECT("aspect", "दृष्टि"),
    UI_AUSPICIOUS_TIMING("Auspicious timing", "शुभ समय"),
    UI_AVOID_ACTIVITIES("Avoid important activities", "महत्त्वपूर्ण गतिविधिहरूबाट बच्नुहोस्"),
    UI_BENEFIC_STRENGTH("Benefic Strength", "शुभ बल"),
    UI_BEST_HOURS("Best Hours", "उत्तम समय"),
    UI_BIRTH_DAY_SIGNIFICANCE("Birth Day Significance", "जन्म दिनको महत्त्व"),
    UI_BIRTH_PANCHANGA("Birth Panchanga", "जन्म पञ्चाङ्ग"),
    UI_CALENDAR("Calendar", "पात्रो"),
    UI_CAUTION_PERIOD("Caution Period", "सावधानी अवधि"),
    UI_CONJUNCTION("conjunction", "युति"),
    UI_CURRENT("Current", "वर्तमान"),
    UI_DESCENDING("Descending", "अवरोही"),
    UI_DETAILS("Details", "विवरण"),
    UI_EFFECTS("Effects", "प्रभावहरू"),
    UI_END("End:", "अन्त्य:"),
    UI_ERROR_LOADING("Error loading chart", "कुन्डली लोड गर्दा त्रुटि"),
    UI_EXCHANGE("exchange", "परिवर्तन"),
    UI_EXIT_DATE("Exit Date", "निस्कने मिति"),
    UI_FAILED_GENERATE_INSIGHT("Failed to generate insight", "अन्तर्दृष्टि उत्पन्न गर्न असफल"),
    UI_FAVORABLE_PERIOD("Favorable Period", "अनुकूल अवधि"),
    UI_FAVORABLE_SIGNS("Favorable Signs", "अनुकूल राशिहरू"),
    UI_FINANCIAL_INDICATIONS("Financial Indications", "आर्थिक संकेतहरू"),
    UI_FROM_LAGNA("From Lagna", "लग्नबाट"),
    UI_FROM_MOON("From Moon", "चन्द्रबाट"),
    UI_GENERAL_NATURE("General Nature", "सामान्य प्रकृति"),
    UI_HEALTH_INDICATIONS("Health Indications", "स्वास्थ्य संकेतहरू"),
    UI_HIGH("High", "उच्च"),
    UI_HOURS_TO_AVOID("Hours to Avoid", "बच्नुपर्ने समय"),
    UI_INTERPRETATION("Interpretation", "व्याख्या"),
    UI_IN_DAYS_FMT("In %d days", "%d दिनमा")
}
