package com.astro.storm.core.common
enum class StringKeyRemedy(override val en: String, override val ne: String) : StringKeyInterface {
REMEDY_SHANI_MANTRA_TITLE("Shani Mantra", "शनि मन्त्र"),
REMEDY_SHANI_MANTRA_DESC("Recite 'Om Sham Shanaishcharaya Namah' 108 times daily", "'ॐ शं शनैश्चराय नमः' दैनिक १०८ पटक जप गर्नुहोस्"),
REMEDY_SATURDAY_CHARITY_TITLE("Saturday Charity", "शनिबार दान"),
REMEDY_SATURDAY_CHARITY_DESC("Donate black sesame, mustard oil, or iron items to the needy", "कालो तिल, सर्स्यूको तेल, वा फलामका सामानहरू गरिबलाई दान गर्नुहोस्"),
REMEDY_SATURDAY_FAST_TITLE("Saturday Fasting", "शनिबार व्रत"),
REMEDY_SATURDAY_FAST_DESC("Observe fast on Saturdays and eat only after sunset", "शनिबार व्रत राख्नुहोस् र सूर्यास्त पछि मात्र खानुहोस्"),
REMEDY_HANUMAN_WORSHIP_TITLE("Hanuman Worship", "हनुमान पूजा"),
REMEDY_HANUMAN_WORSHIP_DESC("Recite Hanuman Chalisa daily, especially on Tuesdays and Saturdays", "हनुमान चालीसा दैनिक पाठ गर्नुहोस्, विशेष गरी मंगलबार र शनिबार"),
    REMEDY_BLUE_SAPPHIRE_TITLE("Blue Sapphire (Neelam)", "Blue Sapphire (Neelam)"),
REMEDY_BLUE_SAPPHIRE_DESC("Wear after proper testing and astrologer consultation", "उचित परीक्षण र ज्योतिषी परामर्श पछि लगाउनुहोस्"),
REMEDY_KUMBH_VIVAH_TITLE("Kumbh Vivah", "कुम्भ विवाह"),
REMEDY_KUMBH_VIVAH_DESC("Ceremonial marriage to a clay pot or Peepal tree before actual marriage", "वास्तविक विवाह अघि माटोको घडा वा पीपलको रूखसँग विवाह समारोह"),
REMEDY_MANGAL_SHANTI_TITLE("Mangal Shanti Puja", "मंगल शान्ति पूजा"),
REMEDY_MANGAL_SHANTI_DESC("Perform Mars pacification ritual at a temple or home", "मन्दिर वा घरमा मंगल शान्ति विधि गर्नुहोस्"),
REMEDY_MARS_MANTRA_TITLE("Mars Mantra", "मंगल मन्त्र"),
REMEDY_MARS_MANTRA_DESC("Recite 'Om Kram Kreem Kroum Sah Bhaumaya Namah' 108 times on Tuesdays", "मंगलबार 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः' १०८ पटक जप गर्नुहोस्"),
    REMEDY_CORAL_TITLE("Red Coral (Moonga)", "Red Coral (Moonga)"),
REMEDY_CORAL_DESC("Wear red coral in gold or copper on right hand ring finger", "दाहिने हातको अनामिकामा सुन वा तामामा मूंगा लगाउनुहोस्"),
REMEDY_TUESDAY_CHARITY_TITLE("Tuesday Charity", "मंगलबार दान"),
REMEDY_TUESDAY_CHARITY_DESC("Donate red lentils, red cloth, or copper items on Tuesdays", "मंगलबार रातो दाल, रातो कपडा, वा तामाका सामान दान गर्नुहोस्"),
REMEDY_PITRA_TARPAN_TITLE("Pitra Tarpan", "पितृ तर्पण"),
REMEDY_PITRA_TARPAN_DESC("Offer water with sesame seeds to ancestors during Amavasya", "अमावस्यामा पुर्खालाई तिल पानी अर्पण गर्नुहोस्"),
REMEDY_SHRADDHA_TITLE("Shraddha Ceremony", "श्राद्ध विधि"),
REMEDY_SHRADDHA_DESC("Perform annual death anniversary rituals for departed ancestors", "दिवंगत पुर्खाको वार्षिक मृत्यु वर्षगाँठ विधि गर्नुहोस्"),
REMEDY_CROW_FEEDING_TITLE("Crow Feeding", "काग भोजन"),
REMEDY_CROW_FEEDING_DESC("Feed crows daily as they are considered messengers of ancestors", "कागलाई दैनिक खुवाउनुहोस् किनभने तिनीहरूलाई पुर्खाको दूत मानिन्छ"),
REMEDY_NARAYAN_BALI_TITLE("Narayan Bali", "नारायण बलि"),
REMEDY_NARAYAN_BALI_DESC("Special ritual for departed souls performed at Trimbakeshwar", "त्र्यम्बकेश्वरमा दिवंगत आत्माको लागि विशेष विधि"),
REMEDY_PIND_DAAN_TITLE("Pind Daan", "पिण्ड दान"),
REMEDY_PIND_DAAN_DESC("Offer rice balls to ancestors at Gaya or other sacred places", "गया वा अन्य पवित्र स्थानमा पुर्खालाई भातको पिण्ड अर्पण गर्नुहोस्"),
REMEDY_PITRA_GAYATRI_TITLE("Pitra Gayatri Mantra", "पितृ गायत्री मन्त्र"),
REMEDY_PITRA_GAYATRI_DESC("Recite Pitra Gayatri daily during Brahma Muhurta for ancestral peace", "पुर्खाको शान्तिको लागि ब्रह्म मुहूर्तमा पितृ गायत्री दैनिक जप गर्नुहोस्"),
REMEDY_EFFECTIVENESS_TRADITIONAL("Traditional remedy - highly effective", "परम्परागत उपाय - अत्यधिक प्रभावकारी"),
REMEDY_EFFECTIVENESS_ALL_LEVELS("Recommended for all Manglik levels", "सबै मांगलिक स्तरहरूको लागि सिफारिस"),
REMEDY_EFFECTIVENESS_TUESDAY("Daily recitation on Tuesdays", "मंगलबार दैनिक पाठ"),
REMEDY_EFFECTIVENESS_CONSULT("Consult astrologer before wearing", "लगाउनु अघि ज्योतिषीसँग परामर्श गर्नुहोस्"),
REMEDY_EFFECTIVENESS_EVERY_TUESDAY("Every Tuesday", "हरेक मंगलबार"),
REMEDIES_TITLE("Vedic Remedies", "वैदिक उपायहरू"),
REMEDIES_GEMSTONES("Gemstones", "रत्नहरू"),
REMEDIES_MANTRAS("Mantras", "मन्त्रहरू"),
REMEDIES_YANTRAS("Yantras", "यन्त्रहरू"),
REMEDIES_RITUALS("Rituals", "पूजा विधिहरू"),
REMEDIES_CHARITY("Charity", "दान"),
REMEDIES_OVERVIEW("Overview", "अवलोकन"),
REMEDIES_PLANETS("Planets", "ग्रहहरू"),
REMEDIES_ANALYSIS("Remedies Analysis", "उपाय विश्लेषण"),
REMEDIES_CHART_STRENGTH("Chart Strength", "कुण्डली बल"),
REMEDIES_PLANETS_WELL_PLACED("%d of %d planets well-placed", "%d मध्ये %d ग्रह राम्ररी स्थित"),
REMEDIES_PLANETS_ATTENTION("Planets Requiring Attention", "ध्यान आवश्यक ग्रहहरू"),
REMEDIES_ESSENTIAL("Essential Remedies", "आवश्यक उपायहरू"),
REMEDIES_WEEKLY_SCHEDULE("Weekly Remedy Schedule", "साप्ताहिक उपाय तालिका"),
REMEDIES_WEEKLY_SCHEDULE_DESC("Perform planet-specific remedies on their designated days for maximum effect", "अधिकतम प्रभावको लागि तिनीहरूको तोकिएको दिनमा ग्रह-विशेष उपायहरू गर्नुहोस्"),
REMEDIES_LIFE_AREA_FOCUS("Life Area Focus", "जीवन क्षेत्र फोकस"),
REMEDIES_GENERAL_RECOMMENDATIONS("General Recommendations", "सामान्य सिफारिसहरू"),
REMEDIES_METHOD("Method", "विधि"),
REMEDIES_TIMING("Timing", "समय"),
REMEDIES_DURATION("Duration", "अवधि"),
REMEDIES_MANTRA_SECTION("Mantra", "मन्त्र"),
REMEDIES_BENEFITS("Benefits", "लाभहरू"),
REMEDIES_CAUTIONS("Cautions", "सावधानीहरू"),
REMEDIES_SEARCH("Search remedies...", "उपायहरू खोज्नुहोस्..."),
REMEDIES_FILTER_ALL("All", "सबै"),
REMEDIES_NO_RESULTS("No remedies found", "कुनै उपाय फेला परेन"),
REMEDIES_NO_RESULTS_SEARCH("No remedies found for \"%s\"", "\"%s\" को लागि कुनै उपाय फेला परेन"),
REMEDIES_NO_CATEGORY("No remedies in this category", "यस वर्गमा कुनै उपाय छैन"),
REMEDIES_NO_CHART("No chart selected", "कुनै कुण्डली छानिएको छैन"),
REMEDIES_SELECT_CHART("Select a chart to view remedies", "उपायहरू हेर्न कुण्डली छान्नुहोस्"),
REMEDIES_ANALYZING("Analyzing your chart...", "तपाईंको कुण्डली विश्लेषण गर्दै..."),
REMEDIES_PREPARING("Preparing personalized remedies", "व्यक्तिगत उपायहरू तयार गर्दै"),
REMEDIES_COPY_MANTRA("Copy mantra", "मन्त्र कपी गर्नुहोस्"),
REMEDIES_RECOMMENDED("%d remedies recommended", "%d उपायहरू सिफारिस गरिएको"),
REMEDIES_BEST_DAY("Best performed on %s", "%s मा गर्नु उत्तम"),
REMEDIES_TOTAL("Total", "कुल"),
REMEDIES_ESSENTIAL_COUNT("Essential", "आवश्यक"),
REMEDY_NADI_1("Nadi Dosha: Donate grains, gold, or cow on an auspicious day after consulting a priest", "नाडी दोष: पुजारीसँग परामर्श पछि शुभ दिनमा अन्न, सुन, वा गाई दान गर्नुहोस्"),
    REMEDY_NADI_2("Nadi Dosha: Perform Maha Mrityunjaya Jaap (108 times daily for 40 days)", "Nadi Dosha: Perform Maha Mrityunjaya Jaap (108 times daily for 40 days)"),
REMEDY_NADI_3("Nadi Dosha: Worship Lord Shiva and Goddess Parvati together on Mondays", "नाडी दोष: सोमबारमा भगवान शिव र देवी पार्वतीको सँगै पूजा गर्नुहोस्"),
REMEDY_BHAKOOT_1("Bhakoot Dosha: Perform Graha Shanti puja for Moon sign lords of both partners", "भकुट दोष: दुवै साझेदारको चन्द्र राशि स्वामीको ग्रह शान्ति पूजा गर्नुहोस्"),
REMEDY_BHAKOOT_2("Bhakoot Dosha: Chant Vishnu Sahasranama on Thursdays for 21 weeks", "भकुट दोष: २१ हप्ता बिहीबारमा विष्णु सहस्रनाम जाप गर्नुहोस्"),
    REMEDY_SHADASHTAK("Shadashtak (6-8)", "Shadashtak (6-8)"),
    REMEDY_MANGLIK_1("Manglik Dosha: Perform Kumbh Vivah (symbolic marriage to a pot or banana tree)", "Manglik Dosha: Perform Kumbh Vivah (symbolic marriage to a pot or banana tree)"),
REMEDY_MANGLIK_2("Manglik Dosha: Chant Mangal Mantra 'Om Kraam Kreem Kraum Sah Bhaumaya Namah' 108 times on Tuesdays", "मांगलिक दोष: मंगलबारमा मंगल मन्त्र 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः' १०८ पटक जाप गर्नुहोस्"),
    REMEDY_MANGLIK_3("Manglik Dosha: Wear a Red Coral (Moonga)", "Manglik Dosha: Wear a Red Coral (Moonga)"),
REMEDY_MANGLIK_BRIDE("For Bride's Manglik: Visit Hanuman temple on Tuesdays and offer vermilion and jasmine oil", "दुलहीको मांगलिकको लागि: मंगलबारमा हनुमान मन्दिरमा जानुहोस् र सिन्दूर र चमेलीको तेल चढाउनुहोस्"),
    REMEDY_MANGLIK_GROOM("For Groom's Manglik: Perform Mars-related charity on Tuesdays (donate red lentils, jaggery, copper)", "For Groom's Manglik: Perform Mars-related charity on Tuesdays (donate red lentils, jaggery, copper)"),
REMEDY_DOUBLE_MANGLIK("Double Manglik: Requires extended Kumbh Vivah ritual and 11 Rudrabhisheks over 11 consecutive Mondays", "दोहोरो मांगलिक: विस्तारित कुम्भ विवाह विधि र लगातार ११ सोमबारमा ११ रुद्राभिषेक आवश्यक"),
REMEDY_GANA_1("Gana Incompatibility: Chant Ganapati Atharvasheersham daily for 41 days", "गण असंगतता: ४१ दिन दैनिक गणपति अथर्वशीर्षम् जाप गर्नुहोस्"),
REMEDY_GANA_2("Gana Incompatibility: Perform Navgraha Shanti puja together before marriage", "गण असंगतता: विवाह अघि सँगै नवग्रह शान्ति पूजा गर्नुहोस्"),
REMEDY_GANA_3("Gana Incompatibility: Practice mutual respect and conscious communication daily", "गण असंगतता: दैनिक पारस्परिक सम्मान र सचेत सञ्चार अभ्यास गर्नुहोस्"),
REMEDY_GRAHA_MAITRI_1("Graha Maitri: Strengthen Mercury through green charity and Budh mantra chanting on Wednesdays", "ग्रह मैत्री: बुधबारमा हरियो दान र बुध मन्त्र जापद्वारा बुध बलियो बनाउनुहोस्"),
REMEDY_GRAHA_MAITRI_2("Graha Maitri: Both partners should meditate together daily to improve mental harmony", "ग्रह मैत्री: मानसिक सामञ्जस्य सुधार गर्न दुवै साझेदारले दैनिक सँगै ध्यान गर्नुपर्छ"),
    REMEDY_YONI_1("Yoni Incompatibility: Worship Kamadeva (God of Love)", "Yoni Incompatibility: Worship Kamadeva (God of Love)"),
REMEDY_YONI_2("Yoni Incompatibility: Perform Ashwamedha or Gajamedha symbolic puja to neutralize animal enmity", "योनि असंगतता: पशु वैमनस्य निष्क्रिय गर्न अश्वमेध वा गजमेध प्रतीकात्मक पूजा गर्नुहोस्"),
REMEDY_VEDHA_1("Vedha Dosha: Perform Nakshatra Shanti puja for both birth stars", "वेध दोष: दुवै जन्म नक्षत्रको लागि नक्षत्र शान्ति पूजा गर्नुहोस्"),
REMEDY_VEDHA_2("Vedha Dosha: Donate black sesame and urad dal on Saturdays", "वेध दोष: शनिबारमा कालो तिल र उडदको दाल दान गर्नुहोस्"),
    REMEDY_RAJJU_SIRO("Siro Rajju Dosha (Head)", "Siro Rajju Dosha (Head)"),
    REMEDY_RAJJU_KANTHA("Kantha Rajju Dosha (Neck)", "Kantha Rajju Dosha (Neck)"),
    REMEDY_RAJJU_NABHI("Nabhi Rajju Dosha (Navel)", "Nabhi Rajju Dosha (Navel)"),
    REMEDY_RAJJU_KATI("Kati Rajju Dosha (Waist)", "Kati Rajju Dosha (Waist)"),
    REMEDY_RAJJU_PADA("Pada Rajju Dosha (Feet)", "Pada Rajju Dosha (Feet)"),
    REMEDY_GENERAL_1("General: Perform Satyanarayan Puja together on Purnima (full moon)", "General: Perform Satyanarayan Puja together on Purnima (full moon)"),
REMEDY_GENERAL_2("General: Chant Swayamvara Parvati Mantra for marital harmony", "सामान्य: वैवाहिक सामञ्जस्यको लागि स्वयंवर पार्वती मन्त्र जाप गर्नुहोस्"),
REMEDY_GENERAL_3("General: Donate to couples in need or contribute to marriage funds for the poor", "सामान्य: जरुरतमन्द जोडीहरूलाई दान गर्नुहोस् वा गरिबको विवाह कोषमा योगदान गर्नुहोस्"),
REMEDY_GENERAL_4("General: Both partners should observe Monday fasts for Lord Shiva", "सामान्य: दुवै साझेदारले भगवान शिवको लागि सोमबार व्रत गर्नुपर्छ"),
REMEDY_SERIOUS_1("Serious Concerns: Consult a qualified Vedic astrologer for personalized guidance", "गम्भीर चिन्ताहरू: व्यक्तिगत मार्गदर्शनको लागि योग्य वैदिक ज्योतिषीसँग परामर्श गर्नुहोस्"),
REMEDY_SERIOUS_2("Serious Concerns: Consider Maha Mrityunjaya Homa for overall protection", "गम्भीर चिन्ताहरू: समग्र सुरक्षाको लागि महा मृत्युञ्जय होम विचार गर्नुहोस्"),
REMEDY_NONE_NEEDED("Excellent compatibility - no specific remedies required.", "उत्कृष्ट अनुकूलता - कुनै विशेष उपाय आवश्यक छैन।"),
REMEDY_SATYANARAYAN("For auspiciousness: Perform Satyanarayan Katha together on the first Purnima after marriage", "शुभताको लागि: विवाह पछिको पहिलो पूर्णिमामा सँगै सत्यनारायण कथा गर्नुहोस्"),
REMEDY_CAT_GEMSTONE("Gemstone", "रत्न"),
REMEDY_CAT_MANTRA("Mantra", "मन्त्र"),
REMEDY_CAT_YANTRA("Yantra", "यन्त्र"),
REMEDY_CAT_CHARITY("Charity", "दान"),
REMEDY_CAT_FASTING("Fasting", "उपवास"),
REMEDY_CAT_COLOR("Color Therapy", "रंग चिकित्सा"),
REMEDY_CAT_METAL("Metal", "धातु"),
REMEDY_CAT_RUDRAKSHA("Rudraksha", "रुद्राक्ष"),
REMEDY_CAT_DEITY("Deity Worship", "देवता पूजा"),
REMEDY_CAT_LIFESTYLE("Lifestyle", "जीवनशैली"),
REMEDY_PRIORITY_ESSENTIAL("Essential", "आवश्यक"),
REMEDY_PRIORITY_HIGHLY_RECOMMENDED("Highly Recommended", "अत्यधिक सिफारिस"),
REMEDY_PRIORITY_RECOMMENDED("Recommended", "सिफारिस गरिएको"),
REMEDY_PRIORITY_OPTIONAL("Optional", "वैकल्पिक"),
REMEDY_TITLE("Remedies", "उपायहरू"),
REMEDY_SEARCH("Search remedies", "उपायहरू खोज्नुहोस्"),
REMEDY_CALCULATION_FAILED("Failed to calculate remedies: %s", "उपायहरू गणना गर्न असफल: %s"),
REMEDY_COPY("Copy", "कपी गर्नुहोस्"),
REMEDY_SHARE("Share", "साझा गर्नुहोस्"),
REMEDY_PLANETARY_ANALYSIS("Planetary Analysis", "ग्रह विश्लेषण"),
REMEDY_ESSENTIAL_COUNT("%d Essential Remedies", "%d आवश्यक उपायहरू"),
REMEDY_ALL_STRONG("All planets are in good condition", "सबै ग्रह राम्रो अवस्थामा छन्")
}
