package com.astro.storm.core.common

enum class StringKeyAnalysis(override val en: String, override val ne: String) : StringKeyInterface {
    ANALYSIS_ASPECT_JUPITER("Aspected by Jupiter (protected)", "बृहस्पतिद्वारा दृष्ट (सुरक्षित)"),
    ANALYSIS_ASPECT_SATURN("Aspected by Saturn", "शनिद्वारा दृष्ट"),
    ANALYSIS_CHART_ANALYSIS("Chart Analysis", "कुण्डली विश्लेषण"),
    ANALYSIS_COMBUST("Combust by Sun (%s weakened)", "सूर्यद्वारा अस्त (%s कमजोर)"),
    ANALYSIS_CONJUNCT_BENEFICS("Conjunct benefics: %s", "शुभ ग्रह युति: %s"),
    ANALYSIS_CONJUNCT_MALEFICS("Conjunct malefics: %s", "पाप ग्रह युति: %s"),
    ANALYSIS_DEBILITATED("Debilitated in %s", "%s मा नीच"),
    ANALYSIS_DEBILITATED_DEEP("Deeply debilitated at %.1f° %s", "%.1f° %s मा गहिरो नीच"),
    ANALYSIS_DUSTHANA("Placed in Dusthana house %d", "दुस्थान भाव %d मा स्थित"),
    ANALYSIS_ENEMY_SIGN("In enemy sign (%s)", "शत्रु राशि (%s) मा"),
    ANALYSIS_EXALTED("Exalted in %s", "%s मा उच्च"),
    ANALYSIS_EXALTED_DEEP("Deeply exalted at %.1f° %s", "%.1f° %s मा गहिरो उच्च"),
    ANALYSIS_FRIEND_SIGN("In friend's sign (%s)", "मित्र राशि (%s) मा"),
    ANALYSIS_GANDANTA("In Gandanta (karmic knot at water-fire sign junction)", "गण्डान्तमा (जल-अग्नि राशि सन्धिमा कार्मिक गाँठो)"),
    ANALYSIS_KENDRA("Placed in Kendra (angle) house %d", "केन्द्र भाव %d मा स्थित"),
    ANALYSIS_LABEL("Analysis", "विश्लेषण"),
    ANALYSIS_MOOLTRIKONA("In Mooltrikona", "मूलत्रिकोणमा"),
    ANALYSIS_MOON_BRIGHT("Bright Moon (Shukla Paksha)", "शुक्ल पक्षको चन्द्रमा"),
    ANALYSIS_MOON_DARK("Dark Moon (Krishna Paksha) - emotionally challenged", "कृष्ण पक्षको चन्द्रमा - भावनात्मक चुनौती"),
    ANALYSIS_MRITYU_BHAGA("In Mrityu Bhaga (critical degree)", "मृत्यु भागमा (महत्त्वपूर्ण डिग्री)"),
    ANALYSIS_NEECHA_BHANGA("Neecha Bhanga Raja Yoga - Debilitation cancelled", "नीच भङ्ग राजयोग - नीचता रद्द"),
    ANALYSIS_OWN_SIGN("In own sign %s", "स्वराशि %s मा"),
    ANALYSIS_PUSHKARA("In Pushkara Navamsha (auspicious degree)", "पुष्कर नवरांशमा (शुभ डिग्री)"),
    ANALYSIS_RETRO_INTERNAL("Retrograde (internalized energy)", "वक्री (आन्तरिक ऊर्जा)"),
    ANALYSIS_RETRO_REVIEW("Retrograde (review communication matters)", "वक्री (सञ्चार विषयमा समीक्षा गर्नुहोस्)"),
    ANALYSIS_RETRO_STRONG("Retrograde (strengthened)", "वक्री (बलियो)"),
    ANALYSIS_TAB_ASHTAKAVARGA("Ashtakavarga", "अष्टकवर्ग"),
    ANALYSIS_TAB_CHART("Chart", "कुण्डली"),
    ANALYSIS_TAB_DASHAS("Dashas", "दशाहरू"),
    ANALYSIS_TAB_PANCHANGA("Panchanga", "पञ्चाङ्ग"),
    ANALYSIS_TAB_PLANETS("Planets", "ग्रहहरू"),
    ANALYSIS_TAB_TRANSITS("Transits", "गोचरहरू"),
    ANALYSIS_TAB_YOGAS("Yogas", "योगहरू"),
    ANALYSIS_TRIKONA("Placed in Trikona (trine) house %d", "त्रिकोण भाव %d मा स्थित"),
    ANALYSIS_WEALTH("Placed in wealth house %d", "धन भाव %d मा स्थित"),
    ANALYSIS_YOGAKARAKA("Yogakaraka planet for %s Lagna", "%s लग्नको लागि योगकारक ग्रह"),
    AREA_REC_CAREER("Capitalize on favorable career energy today.", "आज अनुकूल क्यारियर ऊर्जाको फाइदा उठाउनुहोस्।"),
    AREA_REC_FAMILY("Spend quality time with family members.", "परिवारका सदस्यहरूसँग गुणस्तरीय समय बिताउनुहोस्।"),
    AREA_REC_FINANCE("Take advantage of positive financial influences.", "सकारात्मक वित्तीय प्रभावहरूको फाइदा उठाउनुहोस्।"),
    AREA_REC_HEALTH("Make the most of your vibrant health energy.", "आफ्नो जीवन्त स्वास्थ्य ऊर्जाको अधिकतम फाइदा लिनुहोस्।"),
    AREA_REC_LOVE("Nurture your relationships with extra attention.", "थप ध्यानका साथ आफ्ना सम्बन्धहरूलाई पोषण गर्नुहोस्।"),
    AREA_REC_SPIRITUALITY("Deepen your spiritual practices.", "आफ्नो आध्यात्मिक अभ्यासहरूलाई गहिरो बनाउनुहोस्।"),
    ASHTAKAVARGA_ABOUT_DESC("Ashtakavarga is a unique Vedic system that calculates the strength of each house by analyzing beneficial points (bindus) contributed by seven planets.", "अष्टकवर्ग एक अद्वितीय वैदिक प्रणाली हो जसले सात ग्रहहरूद्वारा प्रदान गरिएको शुभ बिन्दुहरूको विश्लेषण गरेर प्रत्येक भावको शक्ति गणना गर्दछ।"),
    ASHTAKAVARGA_ABOUT_TITLE("About Ashtakavarga", "अष्टकवर्गको बारेमा"),
    ASHTAKAVARGA_AVG_PER_HOUSE("Avg/House", "औसत/भाव"),
    ASHTAKAVARGA_BAV_DESC("Individual planet strength in each sign (0-8 bindus). Use this to predict transit effects.", "प्रत्येक राशिमा व्यक्तिगत ग्रहको शक्ति (०-८ बिन्दु)। गोचर प्रभाव पूर्वानुमान गर्न यो प्रयोग गर्नुहोस्।"),
    ASHTAKAVARGA_BAV_TITLE("Bhinnashtakavarga (BAV)", "भिन्नाष्टकवर्ग (BAV)"),
    ASHTAKAVARGA_BINDUS_SUFFIX("bindus", "बिन्दुहरू"),
    ASHTAKAVARGA_CHART_STRENGTH("Overall Chart Strength", "समग्र कुण्डली बल"),
    ASHTAKAVARGA_DESC_FMT("Bindu strength analysis - %s", "विन्दु बल विश्लेषण - %s"),
    ASHTAKAVARGA_DISTRIBUTION_DESC("Bindu distribution analysis", "विन्दु वितरण विश्लेषण"),
    ASHTAKAVARGA_DISTRIBUTION_TITLE("House Strength Distribution", "भाव बल विभाजन"),
    ASHTAKAVARGA_GUIDE_TEXT("• 30+ bindus: Very strong, excellent results\n• 25-30 bindus: Good strength, favorable\n• 20-25 bindus: Average, mixed results\n• Below 20: Weak, challenges expected", "• ३०+ बिन्दु: धेरै बलियो, उत्कृष्ट परिणाम\n• २५-३० बिन्दु: राम्रो शक्ति, अनुकूल\n• २०-२५ बिन्दु: औसत, मिश्रित परिणाम\n• २० भन्दा कम: कमजोर, चुनौतीहरू अपेक्षित"),
    ASHTAKAVARGA_INFO_A11Y("Ashtakavarga info", "अष्टकवर्ग जानकारी"),
    ASHTAKAVARGA_INTERPRETATION("Interpretation Guide:", "व्याख्या मार्गदर्शन:"),
    ASHTAKAVARGA_KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टि"),
    ASHTAKAVARGA_LEGEND_GOOD("25-30 Good", "२५-३० राम्रो"),
    ASHTAKAVARGA_LEGEND_STRONG(">30 Strong", ">३० बलियो"),
    ASHTAKAVARGA_LEGEND_WEAK("<25 Weak", "<२५ कमजोर"),
    ASHTAKAVARGA_MODERATE(" Ashtakavarga (%d/8) moderates results.", " अष्टकवर्ग (%d/8) ले परिणाम मध्यम बनाउँछ।"),
    ASHTAKAVARGA_PLANET_TOTALS("Planet Bindu Totals", "ग्रह बिन्दु योग"),
    ASHTAKAVARGA_SARVA_DESC("Sarvashtakavarga is the combined bindu strength from all seven planets for each house/sign.", "सर्वाष्टकवर्ग प्रत्येक भाव/राशिको लागि सातै ग्रहहरूको संयुक्त बिन्दु शक्ति हो।"),
    ASHTAKAVARGA_SAV_DESC("Combined strength points from all planets in each zodiac sign. Higher values (28+) indicate favorable areas.", "सबै ग्रहबाट प्रत्येक राशिमा संयोजित शक्ति बिन्दु। उच्च मान (२८+) अनुकूल क्षेत्रहरू संकेत गर्छ।"),
    ASHTAKAVARGA_SAV_TITLE("Sarvashtakavarga (SAV)", "सर्वाष्टकवर्ग (SAV)"),
    ASHTAKAVARGA_STRENGTH("Strength", "बल"),
    ASHTAKAVARGA_STRONG(" Ashtakavarga (%d/8) strengthens results.", " अष्टकवर्ग (%d/8) ले परिणाम बलियो बनाउँछ।"),
    ASHTAKAVARGA_STRONGEST("STRONGEST HOUSES", "सबैभन्दा बलियो भावहरू"),
    ASHTAKAVARGA_SUMMARY_TITLE("Ashtakavarga Summary", "अष्टकवर्ग सारांश"),
    ASHTAKAVARGA_TOTAL_BINDUS("Total Bindus", "कुल विन्दुहरू"),
    ASHTAKAVARGA_WEAK(" Low Ashtakavarga (%d/8) weakens results.", " कम अष्टकवर्ग (%d/8) ले परिणाम कमजोर बनाउँछ।"),
    ASHTAKAVARGA_WEAKEST("WEAKEST HOUSES", "सबैभन्दा कमजोर भावहरू"),
    AVASTHA_ABOUT_DESC("Avasthas are planetary states that indicate how effectively a planet can deliver its results.\n\nFour Types of Avasthas:\n\n1. Baladi (Age-based):\nBala (Infant), Kumara (Youth), Yuva (Adult), Vriddha (Old), Mrita (Dead)\n\n2. Jagradadi (Alertness):\nJagrat (Awake), Swapna (Dreaming), Sushupti (Deep Sleep)\n\n3. Deeptadi (Dignity):\nDeepta, Swastha, Mudita, Shanta, Dina, Vikala, Khala, Kopa, Bhita\n\n4. Lajjitadi (Emotional):\nLajjita, Garvita, Kshudita, Trushita, Mudita, Kshobhita\n\nA planet in good avasthas gives its full results, while one in poor avasthas struggles to manifest its significations.", "अवस्थाहरू ग्रहका स्थितिहरू हुन् जसले ग्रहले आफ्ना नतिजाहरू कत्तिको प्रभावकारी रूपमा दिन सक्छ भनेर संकेत गर्दछ।\n\nचार प्रकारका अवस्थाहरू:\n\n१. बालादि (उमेरमा आधारित):\nबाल, कुमार, युवा, वृद्ध, मृत\n\n२. जाग्रदादि (जागरूकता):\nजाग्रत, स्वप्न, सुषुप्ति\n\n३. दीप्तादि (मर्यादा):\nदीप्त, स्वस्थ, मुदित, शान्त, दीन, विकल, खल, कोप, भीत\n\n४. लज्जितादि (भावनात्मक):\nलज्जित, गर्वित, क्षुधित, तृषित, मुदित, क्षोभित\n\nराम्रो अवस्थामा रहेको ग्रहले पूर्ण फल दिन्छ, जबकि कमजोर अवस्थामा रहेको ग्रहले आफ्ना कारकहरू व्यक्त गर्न संघर्ष गर्दछ।"),
    AVASTHA_ABOUT_TITLE("About Planetary Avasthas", "ग्रह अवस्थाहरूको बारेमा"),
    AVASTHA_AGE_STATE("Age State (Baladi)", "वय अवस्था (बालादि)"),
    AVASTHA_ALERTNESS("Alertness (Jagradadi)", "सचेतता (जाग्रदादि)"),
    AVASTHA_ANALYZING("Analyzing Planetary States...", "ग्रहको अवस्थाहरू विश्लेषण गर्दै..."),
    AVASTHA_BALADI_DESC_INFO("Based on the planet's degree within a sign. Determines the maturity and capability of the planet to deliver results.", "राशिको डिग्रीमा आधारित। यसले ग्रहको नतिजा दिने परिपक्वता र क्षमता निर्धारण गर्दछ।"),
    AVASTHA_BALA_DESC("Planet is in infant state - like a child, it gives results slowly and with help from others. Results manifest in the later part of life.", "ग्रह शिशु अवस्थामा छ - बच्चा जस्तै, यसले बिस्तारै र अरूको सहयोगमा नतिजा दिन्छ। नतिजाहरू जीवनको पछिल्लो भागमा प्रकट हुन्छन्।"),
    AVASTHA_BALA_NAME("Bala (Infant)", "बाल (शिशु)"),
    AVASTHA_BHITA_DESC("Planet in great enemy's sign - very uncomfortable, gives minimal or adverse results.", "ग्रह अति शत्रुको राशिमा छ - धेरै असहज, न्यूनतम वा प्रतिकूल नतिजा दिन्छ।"),
    AVASTHA_BHITA_NAME("Bhita (Frightened)", "भीत (डराएको)"),
    AVASTHA_DEEPTADI_DESC_INFO("Nine states based on exaltation, own sign, friends/enemies, and combustion. Determines overall dignity.", "उच्च, स्वराशि, मित्र/शत्रु र अस्तमा आधारित नौ अवस्थाहरू। यसले समग्र मर्यादा निर्धारण गर्दछ।"),
    AVASTHA_DEEPTA_DESC("Exalted planet - shines brilliantly and gives exceptional results in all areas it signifies.", "उच्चको ग्रह - उज्यालो भएर चम्कन्छ र यसले संकेत गर्ने सबै क्षेत्रहरूमा असाधारण नतिजा दिन्छ।"),
    AVASTHA_DEEPTA_NAME("Deepta (Blazing)", "दीप्त (प्रज्वलित)"),
    AVASTHA_DIGNITY("Dignity (Deeptadi)", "मर्यादा (दीप्तादि)"),
    AVASTHA_DINA_DESC("Planet in neutral sign - gives average results, neither specially good nor bad.", "ग्रह सम राशिमा छ - औसत नतिजा दिन्छ, न विशेष राम्रो न नराम्रो।"),
    AVASTHA_DINA_NAME("Dina (Ordinary)", "दीन (सामान्य)"),
    AVASTHA_EMOTIONAL("Emotional (Lajjitadi)", "भावनात्मक (लज्जितादि)"),
    AVASTHA_GARVITA_DESC("Planet in exaltation or moolatrikona - proud and confident, gives excellent results with dignity.", "ग्रह उच्च वा मूलत्रिकोणमा छ - गौरवान्वित र आत्मविश्वासी, मर्यादाका साथ उत्कृष्ट नतिजा दिन्छ।"),
    AVASTHA_GARVITA_NAME("Garvita (Proud)", "गर्वित (गर्वित)"),
    AVASTHA_JAGRADADI_DESC_INFO("Based on planet's relationship with sign lord. Determines how alert and active the planet is.", "राशि स्वामीसँगको सम्बन्धमा आधारित। यसले ग्रह कति सतर्क र सक्रिय छ भन्ने निर्धारण गर्दछ।"),
    AVASTHA_JAGRAT_DESC("Planet is fully awake and alert - gives complete and timely results. Functions at full capacity.", "ग्रह पूर्ण रूपमा जागृत र सचेत छ - पूर्ण र समयमै नतिजा दिन्छ। पूर्ण क्षमतामा काम गर्दछ।"),
    AVASTHA_JAGRAT_NAME("Jagrat (Awake)", "जाग्रत (जागृत)"),
    AVASTHA_KHALA_DESC("Planet in debilitation - significantly weakened, gives poor or opposite results.", "ग्रह नीच राशिमा छ - महत्त्वपूर्ण रूपमा कमजोर भएको, खराब वा विपरित नतिजा दिन्छ।"),
    AVASTHA_KHALA_NAME("Khala (Debilitated)", "खल (नीच)"),
    AVASTHA_KOPA_DESC("Planet in enemy sign - frustrated and obstructed, gives results with difficulty.", "ग्रह शत्रु राशिमा छ - निराश र अवरुद्ध, कठिनाइको साथ नतिजा दिन्छ।"),
    AVASTHA_KOPA_NAME("KOPA (Angry)", "कोप (क्रोधित)"),
    AVASTHA_KSHOBHITA_DESC("Planet conjunct Sun and aspected by malefic - disturbed and unsettled, gives erratic results.", "सूर्यसँग युति र पाप ग्रहद्वारा दृष्ट ग्रह - विचलित र अस्थिर, अनिश्चित नतिजा दिन्छ।"),
    AVASTHA_KSHOBHITA_NAME("Kshobhita (Agitated)", "क्षोभित (क्षुब्ध)"),
    AVASTHA_KSHUDITA_DESC("Planet in enemy sign with enemy aspect - constantly craving, never satisfied. Results feel incomplete.", "शत्रु राशिमा शत्रुको दृष्टि भएको ग्रह - निरन्तर चाहना राख्ने, कहिल्यै सन्तुष्ट नहुने। नतिजाहरू अपूर्ण महसुस हुन्छन्।"),
    AVASTHA_KSHUDITA_NAME("Kshudita (Hungry)", "क्षुधित (भोको)"),
    AVASTHA_KUMARA_DESC("Planet is in adolescent state - eager and active but not fully mature. Results come with some effort and learning.", "ग्रह किशोरावस्थामा छ - उत्सुक र सक्रिय तर पूर्ण रूपमा परिपक्व छैन। नतिजाहरू केही प्रयास र सिकाइसँगै आउँछन्।"),
    AVASTHA_KUMARA_NAME("Kumara (Adolescent)", "कुमार (किशोर)"),
    AVASTHA_LAJJITADI_DESC_INFO("Based on conjunctions and aspects. Determines the emotional state and how the planet feels in its position.", "युति र दृष्टिमा आधारित। यसले भावनात्मक अवस्था र ग्रह आफ्नो स्थितिमा कस्तो महसुस गर्छ भन्ने निर्धारण गर्दछ।"),
    AVASTHA_LAJJITA_DESC("Planet feels ashamed due to conjunction with Sun/Saturn in 5th house. Children and creativity matters may suffer.", "५औं भावमा सूर्य/शनिसँग युति भएका कारण ग्रहले लज्जित महसुस गर्छ। सन्तान र सिर्जनशीलताका मामिलाहरू प्रभावित हुन सक्छन्।"),
    AVASTHA_LAJJITA_NAME("Lajjita (Ashamed)", "लज्जित (लज्जित)"),
    AVASTHA_MODERATE_PLANETS_NOTE("Most planets are in moderate states, giving mixed results based on their periods.", "धेरै जसो ग्रहहरू मध्यम अवस्थामा छन्, जसले आफ्नो अवधि अनुसार मिश्रित नतिजा दिन्छन्।"),
    AVASTHA_MODERATE_RESULTS("This planet has moderate strength with mixed results.", "यो ग्रहको मध्यम बल छ र मिश्रित नतिजा दिनेछ।"),
    AVASTHA_MODERATE_STRENGTH("Moderate overall planetary strength", "मध्यम समग्र ग्रह बल"),
    AVASTHA_MRITA_DESC("Planet is in dead state - minimal ability to give results. May need strong remedial measures.", "ग्रह मृत अवस्थामा छ - नतिजा दिने न्यूनतम क्षमता। बलियो उपचारात्मक उपायहरू आवश्यक हुन सक्छ।"),
    AVASTHA_MRITA_NAME("Mrita (Dead)", "मृत (मृत)"),
    AVASTHA_MUDITA_DESC("Planet in great friend's sign - happy and supported, gives good results with cooperation.", "ग्रह अति मित्रको राशिमा छ - खुसी र समर्थित, सहयोगको साथ राम्रो नतिजा दिन्छ।"),
    AVASTHA_MUDITA_LAJ_DESC("Planet with friendly influences - joyful and supported, gives pleasant and fulfilling results.", "मित्रवत प्रभाव भएको ग्रह - हर्षित र समर्थित, सुखद र सन्तोषजनक नतिजा दिन्छ।"),
    AVASTHA_MUDITA_LAJ_NAME("Mudita (Delighted)", "मुदित (हर्षित)"),
    AVASTHA_MUDITA_NAME("Mudita (Delighted)", "मुदित (हर्षित)"),
    AVASTHA_NEEDS_ATTENTION("Needs Attention", "ध्यान दिनुपर्ने"),
    AVASTHA_NEEDS_MEASURES("Planets need strengthening measures", "ग्रहहरूलाई सवलीकरण उपायहरू आवश्यक छ"),
    AVASTHA_NODE_POS("Node position in %s. %s", "%sमा नोडको स्थिति। %s"),
    AVASTHA_NO_CHART_DESC("Create or select a birth chart to analyze planetary Avasthas.", "ग्रह अवस्थाहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    AVASTHA_OVERALL_STRENGTH("Overall Planetary Strength", "समग्र ग्रह बल"),
    AVASTHA_OVERALL_STRENGTH_LABEL("Overall Strength: %d%%", "समग्र बल: %d%%"),
    AVASTHA_PLANET_ANALYSIS("%s Analysis", "%s विश्लेषण"),
    AVASTHA_REC_LOW_STRENGTH("Low strength (%d%%)", "न्यून बल (%d%%)"),
    AVASTHA_REC_STRENGTHEN("Strengthen %s through gemstones, mantras, or charitable acts", "रत्न, मन्त्र वा परोपकारी कार्यहरू मार्फत %s लाई बलियो बनाउनुहोस्"),
    AVASTHA_RESULT_CAPACITY("%d%% result capacity", "%d%% नतिजा क्षमता"),
    AVASTHA_SCREEN_TITLE("Planetary Avasthas", "ग्रह अवस्थाहरू"),
    AVASTHA_SHANTA_DESC("Planet in friendly sign - calm and stable, gives consistent positive results.", "ग्रह मित्रको राशिमा छ - शान्त र स्थिर, निरन्तर सकारात्मक नतिजा दिन्छ।"),
    AVASTHA_SHANTA_NAME("Shanta (Peaceful)", "शान्त (शान्त)"),
    AVASTHA_STRONGEST("Strongest", "सबैभन्दा बलियो"),
    AVASTHA_STRONG_CONFIG("Strong overall planetary configuration", "बलियो समग्र ग्रह विन्यास"),
    AVASTHA_STRONG_PLANETS("Strong Planets: %s", "बलिया ग्रहहरू: %s"),
    AVASTHA_STRONG_PLANETS_NOTE("These planets are well-placed and will give favorable results.", "यी ग्रहहरू राम्रो स्थितिमा छन् र अनुकूल नतिजा दिनेछन्।"),
    AVASTHA_STRONG_RESULTS("This planet is strong and will give good results.", "यो ग्रह बलियो छ र राम्रो नतिजा दिनेछ।"),
    AVASTHA_SUBTITLE("Planetary States & Conditions", "ग्रह स्थिति र अवस्थाहरू"),
    AVASTHA_SUSHUPTI_DESC("Planet is in deep sleep - struggles to manifest results. May give minimal or no results without remedies.", "ग्रह गहिरो निद्रामा छ - नतिजा प्रकट गर्न संघर्ष गर्दछ। उपाय बिना न्यूनतम वा कुनै नतिजा नदिन सक्छ।"),
    AVASTHA_SUSHUPTI_NAME("Sushupti (Deep Sleep)", "सुषुप्ति (गहिरो निद्रा)"),
    AVASTHA_SWAPNA_DESC("Planet is in dreaming state - gives partial results, often delayed or through indirect means.", "ग्रह सपनाको अवस्थामा छ - आंशिक नतिजा दिन्छ, प्रायः ढिलो वा अप्रत्यक्ष माध्यमबाट।"),
    AVASTHA_SWAPNA_NAME("Swapna (Dreaming)", "स्वप्न (सपना)"),
    AVASTHA_SWASTHA_DESC("Planet in own sign - comfortable and gives strong, natural results with ease.", "ग्रह आफ्नै राशिमा छ - सहज र सजिलै संग बलियो, प्राकृतिक नतिजा दिन्छ।"),
    AVASTHA_SWASTHA_NAME("Swastha (Healthy)", "स्वस्थ (स्वस्थ)"),
    AVASTHA_TAB_BALADI("Baladi", "बालादि"),
    AVASTHA_TAB_DEEPTADI("Deeptadi", "दीप्तादि"),
    AVASTHA_TAB_JAGRADADI("Jagradadi", "जाग्रदादि"),
    AVASTHA_TAB_LAJJITADI("Lajjitadi", "लज्जितादि"),
    AVASTHA_TAB_OVERVIEW("Overview", "अवलोकन"),
    AVASTHA_TAB_PLANETS("Planets", "ग्रहहरू"),
    AVASTHA_TRUSHITA_DESC("Planet in watery sign with enemy aspect - emotionally parched, seeking fulfillment. Emotional needs unmet.", "जल राशिमा शत्रुको दृष्टि भएको ग्रह - भावनात्मक रूपमा प्यासी, तृप्ति खोजिरहेको। भावनात्मक आवश्यकताहरू पूरा नभएका।"),
    AVASTHA_TRUSHITA_NAME("Trushita (Thirsty)", "तृषित (तिर्खाएको)"),
    AVASTHA_VERY_POWERFUL("This planet is very powerful and will deliver excellent results.", "यो ग्रह धेरै शक्तिशाली छ र उत्कृष्ट नतिजा दिनेछ।"),
    AVASTHA_VERY_WEAK_RESULTS("This planet is very weak and needs remedial measures.", "यो ग्रह धेरै कमजोर छ र उपचारात्मक उपायहरू आवश्यक छ।"),
    AVASTHA_VIKALA_DESC("Combust planet - weakened by Sun's rays, struggles to give full results. Hidden or overshadowed.", "अस्त भएको ग्रह - सूर्यको किरणले कमजोर भएको, पूर्ण नतिजा दिन संघर्ष गर्छ। लुकेको वा छायामा परेको।"),
    AVASTHA_VIKALA_NAME("Vikala (Afflicted)", "विकाल (पीडित)"),
    AVASTHA_VRIDDHA_DESC("Planet is in aged state - wisdom but declining vitality. Results come through experience and patience.", "ग्रह वृद्ध अवस्थामा छ - ज्ञान तर घट्दो जीवनशक्ति। नतिजाहरू अनुभव र धैर्य मार्फत आउँछन्।"),
    AVASTHA_VRIDDHA_NAME("Vriddha (Old)", "वृद्ध (वृद्ध)"),
    AVASTHA_WEAK_PLANETS("Weak Planets: %s", "कमजोर ग्रहहरू: %s"),
    AVASTHA_WEAK_PLANETS_NOTE("These planets may need remedial measures to strengthen their significations.", "यी ग्रहहरूको कारकत्व बलियो बनाउन उपचारात्मक उपायहरू आवश्यक हुन सक्छ।"),
    AVASTHA_WEAK_RESULTS("This planet is weak and may struggle to give full results.", "यो ग्रह कमजोर छ र पूर्ण नतिजा दिन संघर्ष गर्न सक्छ।"),
    AVASTHA_YUVA_DESC("Planet is in prime youthful state - most powerful and capable of giving full results. Best time for manifestation.", "ग्रह युवा अवस्थामा छ - सबैभन्दा शक्तिशाली र पूर्ण नतिजा दिन सक्षम। प्रकटीकरणको लागि उत्तम समय।"),
    AVASTHA_YUVA_NAME("Yuva (Young Adult)", "युवा (युवा)"),
    BHRIGU_BINDU_ABOUT("About Bhrigu Bindu", "भृगु बिन्दुको बारेमा"),
    BHRIGU_BINDU_ABOUT_DESC("Bhrigu Bindu is a sensitive point calculated from the midpoint of Rahu and Moon. It indicates where significant karmic events manifest in life and is used for precise event timing.", "भृगु बिन्दु राहु र चन्द्रको मध्यबिन्दुबाट गणना गरिएको संवेदनशील बिन्दु हो। यसले जीवनमा महत्त्वपूर्ण कार्मिक घटनाहरू कहाँ प्रकट हुन्छन् भनेर संकेत गर्छ र सटीक घटना समयको लागि प्रयोग गरिन्छ।"),
    BHRIGU_BINDU_ASPECTS("Aspecting Planets", "दृष्टि गर्ने ग्रहहरू"),
    BHRIGU_BINDU_AUSPICIOUS_DAYS("Auspicious Days", "शुभ दिनहरू"),
    BHRIGU_BINDU_CALCULATION("Calculation: (Rahu + Moon) / 2", "गणना: (राहु + चन्द्र) / २"),
    BHRIGU_BINDU_CALC_ERROR("Unable to calculate Bhrigu Bindu. Please check chart data.", "भृगु बिन्दु गणना गर्न असमर्थ। कृपया कुण्डली डाटा जाँच गर्नुहोस्।"),
    BHRIGU_BINDU_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    BHRIGU_BINDU_CONJUNCTIONS("Conjunct Planets", "युति ग्रहहरू"),
    BHRIGU_BINDU_DIFFICULT("Difficult", "कठिन"),
    BHRIGU_BINDU_EXCELLENT("Excellent", "उत्कृष्ट"),
    BHRIGU_BINDU_GOOD("Good", "राम्रो"),
    BHRIGU_BINDU_HOUSE("House", "भाव"),
    BHRIGU_BINDU_KARMIC_SIGNIFICANCE("Karmic Significance", "कार्मिक महत्त्व"),
    BHRIGU_BINDU_LIFE_AREAS("Life Area Influences", "जीवन क्षेत्र प्रभावहरू"),
    BHRIGU_BINDU_LONGITUDE("Bhrigu Bindu Longitude", "भृगु बिन्दु देशान्तर"),
    BHRIGU_BINDU_LORD("Sign Lord", "राशि स्वामी"),
    BHRIGU_BINDU_MODERATE("Moderate", "मध्यम"),
    BHRIGU_BINDU_MOON_POSITION("Moon Position", "चन्द्र स्थिति"),
    BHRIGU_BINDU_NAKSHATRA("Nakshatra", "नक्षत्र"),
    BHRIGU_BINDU_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
    BHRIGU_BINDU_PADA("Pada", "पद"),
    BHRIGU_BINDU_RAHU_POSITION("Rahu Position", "राहु स्थिति"),
    BHRIGU_BINDU_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    BHRIGU_BINDU_REMEDIES("Remedial Measures", "उपचारात्मक उपायहरू"),
    BHRIGU_BINDU_SIGN("Sign", "राशि"),
    BHRIGU_BINDU_STRENGTH("Strength Assessment", "शक्ति मूल्यांकन"),
    BHRIGU_BINDU_SUBTITLE("Karmic Destiny Point", "कार्मिक भाग्य बिन्दु"),
    BHRIGU_BINDU_TITLE("Bhrigu Bindu Analysis", "भृगु बिन्दु विश्लेषण"),
    BHRIGU_BINDU_TRANSITS("Transit Analysis", "गोचर विश्लेषण"),
    ISHTA_KASHTA_ABOUT_DESC("Ishta Kashta Phala is derived from Shadbala calculations per BPHS. Ishta Phala (benefic result) is calculated as √(Uccha Bala × Chesta Bala), while Kashta Phala (malefic result) is √((60-Uccha Bala) × (60-Chesta Bala)). A planet with high Ishta and low Kashta delivers excellent results, while the opposite indicates challenges. Net Phala (Ishta minus Kashta) reveals a planet's overall tendency to produce favorable or unfavorable outcomes.", "इष्ट कष्ट फल BPHS अनुसार षडबल गणनाबाट निकालिन्छ। इष्ट फल (शुभ फल) = √(उच्च बल × चेष्टा बल), कष्ट फल (अशुभ फल) = √((60-उच्च बल) × (60-चेष्टा बल))। उच्च इष्ट र कम कष्ट भएको ग्रहले उत्कृष्ट फल दिन्छ, जबकि उल्टोले चुनौतीहरू संकेत गर्दछ। नेट फल (इष्ट माइनस कष्ट) ले ग्रहको अनुकूल वा प्रतिकूल परिणामहरू उत्पादन गर्ने समग्र प्रवृत्ति देखाउँछ।"),
    ISHTA_KASHTA_ABOUT_TITLE("About Ishta Kashta Phala", "इष्ट कष्ट फलको बारेमा"),
    ISHTA_KASHTA_AFFECTS("Affects", "प्रभाव"),
    ISHTA_KASHTA_ANALYZING("Analyzing Ishta Kashta Phala...", "इष्ट कष्ट फल विश्लेषण गर्दै..."),
    ISHTA_KASHTA_BENEFIC("Benefic", "शुभ"),
    ISHTA_KASHTA_BENEFITS("Expected Benefits", "अपेक्षित लाभहरू"),
    ISHTA_KASHTA_CHALLENGES("Potential Challenges", "सम्भावित चुनौतीहरू"),
    ISHTA_KASHTA_CHESTA_BALA("Chesta Bala", "चेष्टा बल"),
    ISHTA_KASHTA_INFLUENCED_BY("Influenced by:", "प्रभावित:"),
    ISHTA_KASHTA_ISHTA("Ishta (Benefic)", "इष्ट (शुभ)"),
    ISHTA_KASHTA_KASHTA("Kashta (Malefic)", "कष्ट (अशुभ)"),
    ISHTA_KASHTA_LIFE_AREAS("Life Area Impact Analysis", "जीवन क्षेत्र प्रभाव विश्लेषण"),
    ISHTA_KASHTA_MALEFIC("Malefic", "अशुभ"),
    ISHTA_KASHTA_MOST_BENEFIC("Most Benefic", "सबैभन्दा शुभ"),
    ISHTA_KASHTA_MOST_MALEFIC("Most Malefic", "सबैभन्दा अशुभ"),
    ISHTA_KASHTA_NEUTRAL("Neutral", "तटस्थ"),
    ISHTA_KASHTA_NO_CHART_DESC("Please generate a chart to view Ishta Kashta Phala analysis.", "इष्ट कष्ट फल विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
    ISHTA_KASHTA_PERIOD_PREDICTIONS("Dasha Period Predictions", "दशा अवधि भविष्यवाणी"),
    ISHTA_KASHTA_SCREEN_TITLE("Ishta Kashta Phala", "इष्ट कष्ट फल"),
    ISHTA_KASHTA_SUBTITLE("Benefic & Malefic Results", "शुभ र अशुभ फलहरू"),
    ISHTA_KASHTA_TAB_LIFE_AREAS("Life Areas", "जीवन क्षेत्रहरू"),
    ISHTA_KASHTA_TAB_PLANETS("Planets", "ग्रहहरू"),
    ISHTA_KASHTA_UCCHA_BALA("Uccha Bala", "उच्च बल"),
    MRITYU_BHAGA_ABOUT("About Mrityu Bhaga", "मृत्यु भागको बारेमा"),
    MRITYU_BHAGA_ABOUT_DESC("Mrityu Bhaga indicates critical degrees where planets become vulnerable. Analysis includes Gandanta junctions and auspicious Pushkara placements.", "मृत्यु भागले ग्रहहरू कमजोर हुने महत्त्वपूर्ण अंशहरू देखाउँछ। विश्लेषणमा गण्डान्त सन्धिहरू र शुभ पुष्कर स्थितिहरू समावेश छन्।"),
    MRITYU_BHAGA_ALL_SIGNS("All Signs Reference", "सबै राशि सन्दर्भ"),
    MRITYU_BHAGA_APPROACHING("Approaching", "नजिक आउँदै"),
    MRITYU_BHAGA_AUSPICIOUS_COUNT("Auspicious", "शुभ"),
    MRITYU_BHAGA_AUSPICIOUS_PLACEMENTS("Auspicious Placements", "शुभ स्थितिहरू"),
    MRITYU_BHAGA_BENEFITS("Benefits", "लाभहरू"),
    MRITYU_BHAGA_CRITICAL_COUNT("Critical", "गम्भीर"),
    MRITYU_BHAGA_DEGREE("Mrityu Bhaga Degree", "मृत्यु भाग अंश"),
    MRITYU_BHAGA_DISTANCE("Distance from Critical Degree", "महत्त्वपूर्ण अंशबाट दूरी"),
    MRITYU_BHAGA_DISTANCE_JUNCTION("Distance from Junction: %1\$2", "सन्धिबाट दूरी: %1\$2"),
    MRITYU_BHAGA_EFFECTS("Effects", "प्रभावहरू"),
    MRITYU_BHAGA_EXACT("Exact", "यथार्थ"),
    MRITYU_BHAGA_GANDANTA_BRAHMA("Brahma Gandanta", "ब्रह्म गण्डान्त"),
    MRITYU_BHAGA_GANDANTA_PLACEMENTS("Gandanta Placements", "गण्डान्त स्थितिहरू"),
    MRITYU_BHAGA_GANDANTA_SHIVA("Shiva Gandanta", "शिव गण्डान्त"),
    MRITYU_BHAGA_GANDANTA_VISHNU("Vishnu Gandanta", "विष्णु गण्डान्त"),
    MRITYU_BHAGA_JUNCTION_DESC("Junction between %1\$2 and %2\$2", "%1\$2 र %2\$2 बीचको सन्धि"),
    MRITYU_BHAGA_LEVEL_BALANCED("Balanced", "सन्तुलित"),
    MRITYU_BHAGA_LEVEL_GENERALLY_POSITIVE("Generally Positive", "सामान्यतया सकारात्मक"),
    MRITYU_BHAGA_LEVEL_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यधिक शुभ"),
    MRITYU_BHAGA_LEVEL_MODERATE_CONCERN("Moderate Concern", "मध्यम चिन्ता"),
    MRITYU_BHAGA_LEVEL_NEEDS_ATTENTION("Needs Attention", "ध्यान दिन आवश्यक"),
    MRITYU_BHAGA_LIFE_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    MRITYU_BHAGA_NO_CRITICAL("Your chart is free from critical Mrityu Bhaga placements.", "तपाईंको कुण्डली गम्भीर मृत्यु भाग स्थितिहरूबाट मुक्त छ।"),
    MRITYU_BHAGA_NO_PLANETS("No planets in Mrityu Bhaga", "मृत्यु भागमा कुनै ग्रह छैन"),
    MRITYU_BHAGA_ORB("Orb", "कोणान्तर"),
    MRITYU_BHAGA_OVERALL_ASSESSMENT("Overall Assessment", "समग्र मूल्यांकन"),
    MRITYU_BHAGA_PLANETS_AFFECTED("Planets in Mrityu Bhaga", "मृत्यु भागमा ग्रहहरू"),
    MRITYU_BHAGA_PRECAUTIONS("Precautionary Measures", "सावधानीका उपायहरू"),
    MRITYU_BHAGA_PUSHKARA_BHAGA_TITLE("Pushkara Bhaga", "पुष्कर भाग"),
    MRITYU_BHAGA_PUSHKARA_NAVAMSA_TITLE("Pushkara Navamsa", "पुष्कर नवमांश"),
    MRITYU_BHAGA_REMEDIES_SECTION("Suggested Remedies", "सुझाव गरिएका उपायहरू"),
    MRITYU_BHAGA_SAFE("Safe", "सुरक्षित"),
    MRITYU_BHAGA_SCREEN_ABOUT("About Mrityu Bhaga", "मृत्यु भागको बारेमा"),
    MRITYU_BHAGA_SCREEN_ABOUT_DESC("Mrityu Bhaga refers to specific sensitive degrees in each zodiac sign. When planets occupy these degrees, they indicate areas of life requiring extra attention. These are sensitive points that may indicate health vulnerabilities or significant life challenges.", "मृत्यु भागले प्रत्येक राशिमा विशेष संवेदनशील अंशहरूलाई जनाउँछ। जब ग्रहहरू यी अंशहरूमा हुन्छन्, तिनीहरूले थप ध्यान चाहिने जीवनका क्षेत्रहरू संकेत गर्दछन्।"),
    MRITYU_BHAGA_SCREEN_SUBTITLE("Sensitive Degrees in Chart", "कुण्डलीमा संवेदनशील अंशहरू"),
    MRITYU_BHAGA_SCREEN_TITLE("Mrityu Bhaga Analysis", "मृत्यु भाग विश्लेषण"),
    MRITYU_BHAGA_SENSITIVE_DEGREE("Sensitive Degree", "संवेदनशील अंश"),
    MRITYU_BHAGA_SEVERITY("Severity Level", "गम्भीरता स्तर"),
    MRITYU_BHAGA_SIGN_DEGREES("Mrityu Bhaga Degrees by Sign", "राशि अनुसार मृत्यु भाग अंशहरू"),
    MRITYU_BHAGA_SUBTITLE("Sensitive Degrees Analysis", "संवेदनशील अंश विश्लेषण"),
    MRITYU_BHAGA_TITLE("Mrityu Bhaga Analysis", "मृत्यु भाग विश्लेषण"),
    MRITYU_BHAGA_TRANSIT_WARNING("Transit Alerts", "गोचर चेतावनीहरू"),
    MRITYU_BHAGA_VERY_CLOSE("Very Close", "अति नजिक"),
    MRITYU_BHAGA_VULNERABILITIES("Vulnerability Areas", "कमजोर क्षेत्रहरू"),
    MRITYU_BHAGA_WITHIN_ORB("Within Orb", "परिधि भित्र"),
    SHADBALA_ABOVE_AVERAGE("Above Average", "औसतभन्दा माथि"),
    SHADBALA_AVERAGE("Average", "औसत"),
    SHADBALA_AYANA_BALA("Ayana Bala", "अयन बल"),
    SHADBALA_BELOW_AVERAGE("Below Average", "औसतभन्दा तल"),
    SHADBALA_BELOW_REQUIREMENT("Below required strength", "आवश्यक शक्तिभन्दा तल"),
    SHADBALA_BREAKDOWN("Strength Breakdown", "शक्ति विवरण"),
    SHADBALA_CALCULATING("Calculating Shadbala...", "षड्बल गणना गर्दै..."),
    SHADBALA_CALCULATION_ERROR("Failed to calculate Shadbala", "षडबल गणना गर्न असफल भयो"),
    SHADBALA_CHART_ANALYSIS("Chart Strength Analysis", "कुण्डली शक्ति विश्लेषण"),
    SHADBALA_CHESTA("Chesta", "चेष्टा"),
    SHADBALA_CHESTA_BALA("Chesta Bala", "चेष्टा बल"),
    SHADBALA_CHESTA_BALA_DESC("Motional Strength", "गतिशील शक्ति"),
    SHADBALA_COMPARISON("Comparison", "तुलना"),
    SHADBALA_DETAILS("Detailed Analysis", "विस्तृत विश्लेषण"),
    SHADBALA_DIG("Dig", "दिक्"),
    SHADBALA_DIG_BALA("Dig Bala", "दिग् बल"),
    SHADBALA_DIG_BALA_DESC("Directional Strength", "दिशागत शक्ति"),
    SHADBALA_DREKKANA_BALA("Drekkana Bala", "द्रेक्काण बल"),
    SHADBALA_DRIK_BALA("Drik Bala", "दृक् बल"),
    SHADBALA_DRIK_BALA_DESC("Aspectual Strength", "दृष्टिगत शक्ति"),
    SHADBALA_EXTREMELY_STRONG("Extremely Strong", "अत्यन्त बलियो"),
    SHADBALA_EXTREMELY_WEAK("Extremely Weak", "अत्यन्त कमजोर"),
    SHADBALA_HORA_BALA("Hora/Dina/Masa/Varsha", "होरा/दिन/मास/वर्ष"),
    SHADBALA_INFO_DESC("Shadbala is the six-fold strength calculation system in Vedic astrology that determines a planet's capacity to deliver its significations. Each planet needs to meet a minimum threshold to be considered functionally strong.", "षड्बल वैदिक ज्योतिषमा छवटा शक्ति गणना प्रणाली हो जसले ग्रहको आफ्नो संकेतहरू प्रदान गर्ने क्षमता निर्धारण गर्दछ। प्रत्येक ग्रहलाई कार्यात्मक रूपमा बलियो मानिनको लागि न्यूनतम सीमा पूरा गर्नुपर्छ।"),
    SHADBALA_INFO_INTRO("The six sources of strength:", "शक्तिका छवटा स्रोतहरू:"),
    SHADBALA_INFO_ITEM_1("1. Sthana Bala - Positional strength based on exaltation, own sign, etc.", "१. स्थान बल - उच्चता, स्वराशि, आदिमा आधारित स्थितिगत शक्ति।"),
    SHADBALA_INFO_ITEM_2("2. Dig Bala - Directional strength based on house placement", "२. दिग् बल - भाव स्थितिमा आधारित दिशागत शक्ति"),
    SHADBALA_INFO_ITEM_3("3. Kala Bala - Temporal strength from time of birth", "३. काल बल - जन्म समयबाट समयगत शक्ति"),
    SHADBALA_INFO_ITEM_4("4. Chesta Bala - Motional strength from planetary motion", "४. चेष्टा बल - ग्रह गतिबाट गतिशील शक्ति"),
    SHADBALA_INFO_ITEM_5("5. Naisargika Bala - Natural inherent strength", "५. नैसर्गिक बल - प्राकृतिक अन्तर्निहित शक्ति"),
    SHADBALA_INFO_ITEM_6("6. Drik Bala - Strength from aspects received", "६. दृक् बल - प्राप्त दृष्टिहरूबाट शक्ति"),
    SHADBALA_INFO_TITLE("About Shadbala", "षड्बलको बारेमा"),
    SHADBALA_INTERPRETATION("Interpretation", "व्याख्या"),
    SHADBALA_KALA("Kala", "काल"),
    SHADBALA_KALA_BALA("Kala Bala", "काल बल"),
    SHADBALA_KALA_BALA_DESC("Temporal Strength", "समयगत शक्ति"),
    SHADBALA_KENDRADI_BALA("Kendradi Bala", "केन्द्रादि बल"),
    SHADBALA_MEETS_REQUIREMENT("Meets required strength", "आवश्यक शक्ति पूरा गर्दछ"),
    SHADBALA_NAISARGIKA_BALA("Naisargika Bala", "नैसर्गिक बल"),
    SHADBALA_NAISARGIKA_BALA_DESC("Natural Strength", "प्राकृतिक शक्ति"),
    SHADBALA_NATHONNATHA_BALA("Nathonnatha Bala", "नथोन्नथ बल"),
    SHADBALA_OJHAYUGMA_BALA("Ojhayugma Bala", "ओझायुग्म बल"),
    SHADBALA_OVERALL_STRENGTH("Overall Chart Strength", "समग्र कुण्डली शक्ति"),
    SHADBALA_OVERVIEW("Overview", "अवलोकन"),
    SHADBALA_PAKSHA_BALA("Paksha Bala", "पक्ष बल"),
    SHADBALA_PERCENTAGE("Percentage", "प्रतिशत"),
    SHADBALA_PLANET_ANALYSIS("%s Analysis", "%s विश्लेषण"),
    SHADBALA_RATING("Rating", "मूल्यांकन"),
    SHADBALA_REQUIRED("Required", "आवश्यक"),
    SHADBALA_RUPAS("Rupas", "रूपा"),
    SHADBALA_RUPAS_VALUE("%s Rupas", "%s रूपा"),
    SHADBALA_SAPTAVARGAJA_BALA("Saptavargaja Bala", "सप्तवर्गज बल"),
    SHADBALA_STHANA("Sthana", "स्थान"),
    SHADBALA_STHANA_BALA("Sthana Bala", "स्थान बल"),
    SHADBALA_STHANA_BALA_DESC("Positional Strength", "स्थितिगत शक्ति"),
    SHADBALA_STRONG("Strong", "बलियो"),
    SHADBALA_STRONGEST_PLANET("Strongest Planet", "सबैभन्दा बलियो ग्रह"),
    SHADBALA_STRONG_COUNT("%d planets above required", "%d ग्रह आवश्यकताभन्दा माथि"),
    SHADBALA_SUBTITLE("Six-fold Planetary Strength", "छवटा ग्रह शक्ति"),
    SHADBALA_TITLE("Shadbala", "षड्बल"),
    SHADBALA_TOTAL("Total", "कुल"),
    SHADBALA_TOTAL_STRENGTH("Total Strength", "कुल शक्ति"),
    SHADBALA_TRIBHAGA_BALA("Tribhaga Bala", "त्रिभाग बल"),
    SHADBALA_UCCHA_BALA("Uccha Bala", "उच्च बल"),
    SHADBALA_VERY_STRONG("Very Strong", "धेरै बलियो"),
    SHADBALA_VIRUPAS("Virupas", "विरूपा"),
    SHADBALA_WEAK("Weak", "कमजोर"),
    SHADBALA_WEAKEST_PLANET("Weakest Planet", "सबैभन्दा कमजोर ग्रह"),
    SHADBALA_WEAK_COUNT("%d planets below required", "%d ग्रह आवश्यकताभन्दा तल"),
    SHADBALA_YUDDHA_BALA("Yuddha Bala", "युद्ध बल")
}
