package com.astro.storm.core.common
enum class StringKeyAnalysisPart3(override val en: String, override val ne: String) : StringKeyInterface {
KEYWORD_ENERGY("Energy", "ऊर्जा"),
KEYWORD_COURAGE("Courage", "साहस"),
KEYWORD_COMMUNICATION("Communication", "सञ्चार"),
KEYWORD_LEARNING("Learning", "सिकाइ"),
KEYWORD_BUSINESS("Business", "व्यापार"),
KEYWORD_WISDOM("Wisdom", "ज्ञान"),
KEYWORD_GROWTH("Growth", "विकास"),
KEYWORD_FORTUNE("Fortune", "भाग्य"),
KEYWORD_LOVE("Love", "प्रेम"),
KEYWORD_ART("Art", "कला"),
KEYWORD_COMFORT("Comfort", "आराम"),
KEYWORD_DISCIPLINE("Discipline", "अनुशासन"),
KEYWORD_KARMA("Karma", "कर्म"),
KEYWORD_DELAYS("Delays", "ढिलाइ"),
KEYWORD_AMBITION("Ambition", "महत्त्वाकांक्षा"),
KEYWORD_INNOVATION("Innovation", "नवीनता"),
KEYWORD_FOREIGN("Foreign", "विदेशी"),
KEYWORD_SPIRITUALITY("Spirituality", "आध्यात्मिकता"),
KEYWORD_DETACHMENT("Detachment", "वैराग्य"),
KEYWORD_PAST("Past", "अतीत"),
KEYWORD_GENERAL("General", "सामान्य"),
KEYWORD_SELF("Self", "स्वयम्"),
KEYWORD_PERSONALITY("Personality", "व्यक्तित्व"),
KEYWORD_HEALTH("Health", "स्वास्थ्य"),
KEYWORD_APPEARANCE("Appearance", "रूप"),
KEYWORD_NEW_BEGINNINGS("New Beginnings", "नयाँ शुरुवात"),
KEYWORD_WEALTH("Wealth", "धन"),
KEYWORD_FAMILY("Family", "परिवार"),
KEYWORD_SPEECH("Speech", "वाणी"),
KEYWORD_VALUES("Values", "मूल्य मान्यता"),
KEYWORD_FOOD("Food", "भोजन"),
KEYWORD_SIBLINGS("Siblings", "भाइबहिनी"),
KEYWORD_SHORT_TRAVEL("Short Travel", "छोटो यात्रा"),
KEYWORD_SKILLS("Skills", "सीप"),
KEYWORD_HOME("Home", "घर"),
KEYWORD_PROPERTY("Property", "सम्पत्ति"),
KEYWORD_VEHICLES("Vehicles", "सवारी साधन"),
KEYWORD_INNER_PEACE("Inner Peace", "आन्तरिक शान्ति"),
KEYWORD_CHILDREN("Children", "सन्तान"),
KEYWORD_INTELLIGENCE("Intelligence", "बुद्धि"),
KEYWORD_ROMANCE("Romance", "रोमान्स"),
KEYWORD_CREATIVITY("Creativity", "सिर्जनशीलता"),
KEYWORD_INVESTMENTS("Investments", "लगानी"),
KEYWORD_ENEMIES("Enemies", "शत्रु"),
KEYWORD_HEALTH_ISSUES("Health Issues", "स्वास्थ्य समस्या"),
KEYWORD_SERVICE("Service", "सेवा"),
KEYWORD_DEBTS("Debts", "ऋण"),
KEYWORD_COMPETITION("Competition", "प्रतिस्पर्धा"),
KEYWORD_MARRIAGE("Marriage", "विवाह"),
KEYWORD_PARTNERSHIP("Partnership", "साझेदारी"),
KEYWORD_PUBLIC_DEALINGS("Public Dealings", "सार्वजनिक कारोबार"),
KEYWORD_CONTRACTS("Contracts", "सम्झौता"),
KEYWORD_LONGEVITY("Longevity", "दीर्घायु"),
KEYWORD_TRANSFORMATION("Transformation", "रूपान्तरण"),
KEYWORD_RESEARCH("Research", "अनुसन्धान"),
KEYWORD_INHERITANCE("Inheritance", "विरासत"),
KEYWORD_HIDDEN_MATTERS("Hidden Matters", "लुकेका कुराहरू"),
KEYWORD_RELIGION("Religion", "धर्म"),
KEYWORD_HIGHER_EDUCATION("Higher Education", "उच्च शिक्षा"),
KEYWORD_LONG_TRAVEL("Long Travel", "लामो यात्रा"),
KEYWORD_CAREER("Career", "क्यारियर"),
KEYWORD_STATUS("Status", "स्थिति"),
KEYWORD_AUTHORITY("Authority", "अधिकार"),
KEYWORD_GOVERNMENT("Government", "सरकार"),
KEYWORD_FAME("Fame", "नाम"),
KEYWORD_GAINS("Gains", "लाभ"),
KEYWORD_INCOME("Income", "आय"),
KEYWORD_FRIENDS("Friends", "मित्रहरू"),
KEYWORD_ELDER_SIBLINGS("Elder Siblings", "ठूला भाइबहिनी"),
KEYWORD_ASPIRATIONS("Aspirations", "आंकाक्षा"),
KEYWORD_LOSSES("Losses", "हानि"),
KEYWORD_EXPENSES("Expenses", "खर्च"),
KEYWORD_FOREIGN_LANDS("Foreign Lands", "विदेशी भूमि"),
KEYWORD_LIBERATION("Liberation", "मुक्ति"),
HOUSE_1_SIGNIFICANCE("Self, Appearance, Health", "स्वयं, स्वरूप, स्वास्थ्य"),
HOUSE_2_SIGNIFICANCE("Wealth, Family, Speech", "धन, परिवार, वाणी"),
HOUSE_3_SIGNIFICANCE("Siblings, Courage, Communication", "भाइबहिनी, साहस, सञ्चार"),
HOUSE_4_SIGNIFICANCE("Mother, Happiness, Property", "आमा, सुख, सम्पत्ति"),
HOUSE_5_SIGNIFICANCE("Children, Intelligence, Creativity", "सन्तान, बुद्धि, सिर्जनात्मकता"),
HOUSE_6_SIGNIFICANCE("Health, Debts, Enemies", "स्वास्थ्य, ऋण, शत्रु"),
HOUSE_7_SIGNIFICANCE("Marriage, Partnership, Public", "विवाह, साझेदारी, सार्वजनिक"),
HOUSE_8_SIGNIFICANCE("Longevity, Transformation, Hidden", "दीर्घायु, रूपान्तरण, लुकेका कुराहरू"),
HOUSE_9_SIGNIFICANCE("Fortune, Religion, Father", "भाग्य, धर्म, पिता"),
HOUSE_10_SIGNIFICANCE("Career, Status, Authority", "क्यारियर, स्थिति, अधिकार"),
HOUSE_11_SIGNIFICANCE("Gains, Income, Friends", "लाभ, आय, मित्रहरू"),
HOUSE_12_SIGNIFICANCE("Losses, Expenses, Foreign", "हानि, खर्च, विदेश"),
DASHA_VIMSHOTTARI_TITLE("Vimshottari Dasha", "विंशोत्तरी दशा"),
DASHA_VIMSHOTTARI_DESC("Standard 120-year planetary cycle based on Nakshatra at moon's position.", "चन्द्रमा रहेको नक्षत्रमा आधारित मानक १२० वर्षे ग्रह चक्र।"),
    DASHA_CHARA_TITLE("Chara Dasha (Jaimini)", "Chara Dasha (Jaimini)"),
DASHA_CHARA_DESC("Sign-based dasha system where signs act as periods.", "राशिमा आधारित दशा प्रणाली जहाँ राशिहरूले अवधिको रूपमा काम गर्छन्।"),
DASHA_YOGINI_TITLE("Yogini Dasha", "योगिनी दशा"),
DASHA_YOGINI_DESC("An 8-year recurring cycle of 8 Yoginis, popular in Northern India.", "८ योगिनीहरूको ८ वर्षे आवर्ती चक्र, जुन उत्तर भारतमा लोकप्रिय छ।"),
DASHA_KALACHAKRA_TITLE("Kalachakra Dasha", "कालचक्र दशा"),
DASHA_KALACHAKRA_DESC("Complex dasha based on Moon's Navamsha, reflecting wheel of time.", "चन्द्रमाको नवांशमा आधारित जटिल दशा, जसले समयको चक्रलाई प्रतिबिम्बित गर्दछ।"),
DASHA_ASHTOTTARI_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
DASHA_ASHTOTTARI_DESC("A 108-year dasha system used when Rahu is in a quadrant from Lagna Lord.", "१०८ वर्षे दशा प्रणाली, राहु लग्नको स्वामीबाट केन्द्रमा हुँदा प्रयोग गरिन्छ।"),
DASHA_VIEW_DETAILS("View Details", "थप विवरण"),
    AVASTHA_BALA_NAME("Bala (Infant)", "Bala (Infant)"),
AVASTHA_BALA_DESC("Planet is in infant state - like a child, it gives results slowly and with help from others. Results manifest in the later part of life.", "ग्रह शिशु अवस्थामा छ - बच्चा जस्तै, यसले बिस्तारै र अरूको सहयोगमा नतिजा दिन्छ। नतिजाहरू जीवनको पछिल्लो भागमा प्रकट हुन्छन्।"),
    AVASTHA_KUMARA_NAME("Kumara (Adolescent)", "Kumara (Adolescent)"),
AVASTHA_KUMARA_DESC("Planet is in adolescent state - eager and active but not fully mature. Results come with some effort and learning.", "ग्रह किशोरावस्थामा छ - उत्सुक र सक्रिय तर पूर्ण रूपमा परिपक्व छैन। नतिजाहरू केही प्रयास र सिकाइसँगै आउँछन्।"),
    AVASTHA_YUVA_NAME("Yuva (Young Adult)", "Yuva (Young Adult)"),
AVASTHA_YUVA_DESC("Planet is in prime youthful state - most powerful and capable of giving full results. Best time for manifestation.", "ग्रह युवा अवस्थामा छ - सबैभन्दा शक्तिशाली र पूर्ण नतिजा दिन सक्षम। प्रकटीकरणको लागि उत्तम समय।"),
    AVASTHA_VRIDDHA_NAME("Vriddha (Old)", "Vriddha (Old)"),
AVASTHA_VRIDDHA_DESC("Planet is in aged state - wisdom but declining vitality. Results come through experience and patience.", "ग्रह वृद्ध अवस्थामा छ - ज्ञान तर घट्दो जीवनशक्ति। नतिजाहरू अनुभव र धैर्य मार्फत आउँछन्।"),
    AVASTHA_MRITA_NAME("Mrita (Dead)", "Mrita (Dead)"),
AVASTHA_MRITA_DESC("Planet is in dead state - minimal ability to give results. May need strong remedial measures.", "ग्रह मृत अवस्थामा छ - नतिजा दिने न्यूनतम क्षमता। बलियो उपचारात्मक उपायहरू आवश्यक हुन सक्छ।"),
    AVASTHA_JAGRAT_NAME("Jagrat (Awake)", "Jagrat (Awake)"),
AVASTHA_JAGRAT_DESC("Planet is fully awake and alert - gives complete and timely results. Functions at full capacity.", "ग्रह पूर्ण रूपमा जागृत र सचेत छ - पूर्ण र समयमै नतिजा दिन्छ। पूर्ण क्षमतामा काम गर्दछ।"),
    AVASTHA_SWAPNA_NAME("Swapna (Dreaming)", "Swapna (Dreaming)"),
AVASTHA_SWAPNA_DESC("Planet is in dreaming state - gives partial results, often delayed or through indirect means.", "ग्रह सपनाको अवस्थामा छ - आंशिक नतिजा दिन्छ, प्रायः ढिलो वा अप्रत्यक्ष माध्यमबाट।"),
    AVASTHA_SUSHUPTI_NAME("Sushupti (Deep Sleep)", "Sushupti (Deep Sleep)"),
AVASTHA_SUSHUPTI_DESC("Planet is in deep sleep - struggles to manifest results. May give minimal or no results without remedies.", "ग्रह गहिरो निद्रामा छ - नतिजा प्रकट गर्न संघर्ष गर्दछ। उपाय बिना न्यूनतम वा कुनै नतिजा नदिन सक्छ।"),
    AVASTHA_DEEPTA_NAME("Deepta (Blazing)", "Deepta (Blazing)"),
AVASTHA_DEEPTA_DESC("Exalted planet - shines brilliantly and gives exceptional results in all areas it signifies.", "उच्चको ग्रह - उज्यालो भएर चम्कन्छ र यसले संकेत गर्ने सबै क्षेत्रहरूमा असाधारण नतिजा दिन्छ।"),
    AVASTHA_SWASTHA_NAME("Swastha (Healthy)", "Swastha (Healthy)"),
AVASTHA_SWASTHA_DESC("Planet in own sign - comfortable and gives strong, natural results with ease.", "ग्रह आफ्नै राशिमा छ - सहज र सजिलै संग बलियो, प्राकृतिक नतिजा दिन्छ।"),
    AVASTHA_MUDITA_NAME("Mudita (Delighted)", "Mudita (Delighted)"),
AVASTHA_MUDITA_DESC("Planet in great friend's sign - happy and supported, gives good results with cooperation.", "ग्रह अति मित्रको राशिमा छ - खुसी र समर्थित, सहयोगको साथ राम्रो नतिजा दिन्छ।"),
    AVASTHA_SHANTA_NAME("Shanta (Peaceful)", "Shanta (Peaceful)"),
AVASTHA_SHANTA_DESC("Planet in friendly sign - calm and stable, gives consistent positive results.", "ग्रह मित्रको राशिमा छ - शान्त र स्थिर, निरन्तर सकारात्मक नतिजा दिन्छ।"),
    AVASTHA_DINA_NAME("Dina (Ordinary)", "Dina (Ordinary)"),
AVASTHA_DINA_DESC("Planet in neutral sign - gives average results, neither specially good nor bad.", "ग्रह सम राशिमा छ - औसत नतिजा दिन्छ, न विशेष राम्रो न नराम्रो।"),
    AVASTHA_VIKALA_NAME("Vikala (Afflicted)", "Vikala (Afflicted)"),
AVASTHA_VIKALA_DESC("Combust planet - weakened by Sun's rays, struggles to give full results. Hidden or overshadowed.", "अस्त भएको ग्रह - सूर्यको किरणले कमजोर भएको, पूर्ण नतिजा दिन संघर्ष गर्छ। लुकेको वा छायामा परेको।"),
    AVASTHA_KHALA_NAME("Khala (Debilitated)", "Khala (Debilitated)"),
AVASTHA_KHALA_DESC("Planet in debilitation - significantly weakened, gives poor or opposite results.", "ग्रह नीच राशिमा छ - महत्त्वपूर्ण रूपमा कमजोर भएको, खराब वा विपरित नतिजा दिन्छ।"),
    AVASTHA_KOPA_NAME("KOPA (Angry)", "KOPA (Angry)"),
AVASTHA_KOPA_DESC("Planet in enemy sign - frustrated and obstructed, gives results with difficulty.", "ग्रह शत्रु राशिमा छ - निराश र अवरुद्ध, कठिनाइको साथ नतिजा दिन्छ।"),
    AVASTHA_BHITA_NAME("Bhita (Frightened)", "Bhita (Frightened)"),
AVASTHA_BHITA_DESC("Planet in great enemy's sign - very uncomfortable, gives minimal or adverse results.", "ग्रह अति शत्रुको राशिमा छ - धेरै असहज, न्यूनतम वा प्रतिकूल नतिजा दिन्छ।"),
    AVASTHA_LAJJITA_NAME("Lajjita (Ashamed)", "Lajjita (Ashamed)"),
AVASTHA_LAJJITA_DESC("Planet feels ashamed due to conjunction with Sun/Saturn in 5th house. Children and creativity matters may suffer.", "५औं भावमा सूर्य/शनिसँग युति भएका कारण ग्रहले लज्जित महसुस गर्छ। सन्तान र सिर्जनशीलताका मामिलाहरू प्रभावित हुन सक्छन्।"),
    AVASTHA_GARVITA_NAME("Garvita (Proud)", "Garvita (Proud)"),
AVASTHA_GARVITA_DESC("Planet in exaltation or moolatrikona - proud and confident, gives excellent results with dignity.", "ग्रह उच्च वा मूलत्रिकोणमा छ - गौरवान्वित र आत्मविश्वासी, मर्यादाका साथ उत्कृष्ट नतिजा दिन्छ।"),
    AVASTHA_KSHUDITA_NAME("Kshudita (Hungry)", "Kshudita (Hungry)"),
AVASTHA_KSHUDITA_DESC("Planet in enemy sign with enemy aspect - constantly craving, never satisfied. Results feel incomplete.", "शत्रु राशिमा शत्रुको दृष्टि भएको ग्रह - निरन्तर चाहना राख्ने, कहिल्यै सन्तुष्ट नहुने। नतिजाहरू अपूर्ण महसुस हुन्छन्।"),
    AVASTHA_TRUSHITA_NAME("Trushita (Thirsty)", "Trushita (Thirsty)"),
AVASTHA_TRUSHITA_DESC("Planet in watery sign with enemy aspect - emotionally parched, seeking fulfillment. Emotional needs unmet.", "जल राशिमा शत्रुको दृष्टि भएको ग्रह - भावनात्मक रूपमा प्यासी, तृप्ति खोजिरहेको। भावनात्मक आवश्यकताहरू पूरा नभएका।"),
    AVASTHA_MUDITA_LAJ_NAME("Mudita (Delighted)", "Mudita (Delighted)"),
AVASTHA_MUDITA_LAJ_DESC("Planet with friendly influences - joyful and supported, gives pleasant and fulfilling results.", "मित्रवत प्रभाव भएको ग्रह - हर्षित र समर्थित, सुखद र सन्तोषजनक नतिजा दिन्छ।"),
    AVASTHA_KSHOBHITA_NAME("Kshobhita (Agitated)", "Kshobhita (Agitated)"),
AVASTHA_KSHOBHITA_DESC("Planet conjunct Sun and aspected by malefic - disturbed and unsettled, gives erratic results.", "सूर्यसँग युति र पाप ग्रहद्वारा दृष्ट ग्रह - विचलित र अस्थिर, अनिश्चित नतिजा दिन्छ।"),
AVASTHA_PLANET_ANALYSIS("%s Analysis", "%s विश्लेषण"),
    AVASTHA_AGE_STATE("Age State (Baladi)", "Age State (Baladi)"),
    AVASTHA_ALERTNESS("Alertness (Jagradadi)", "Alertness (Jagradadi)"),
    AVASTHA_DIGNITY("Dignity (Deeptadi)", "Dignity (Deeptadi)"),
    AVASTHA_EMOTIONAL("Emotional (Lajjitadi)", "Emotional (Lajjitadi)"),
AVASTHA_OVERALL_STRENGTH_LABEL("Overall Strength: %d%%", "समग्र बल: %d%%"),
AVASTHA_VERY_POWERFUL("This planet is very powerful and will deliver excellent results.", "यो ग्रह धेरै शक्तिशाली छ र उत्कृष्ट नतिजा दिनेछ।"),
AVASTHA_STRONG_RESULTS("This planet is strong and will give good results.", "यो ग्रह बलियो छ र राम्रो नतिजा दिनेछ।"),
AVASTHA_MODERATE_RESULTS("This planet has moderate strength with mixed results.", "यो ग्रहको मध्यम बल छ र मिश्रित नतिजा दिनेछ।"),
AVASTHA_WEAK_RESULTS("This planet is weak and may struggle to give full results.", "यो ग्रह कमजोर छ र पूर्ण नतिजा दिन संघर्ष गर्न सक्छ।"),
AVASTHA_VERY_WEAK_RESULTS("This planet is very weak and needs remedial measures.", "यो ग्रह धेरै कमजोर छ र उपचारात्मक उपायहरू आवश्यक छ।"),
AVASTHA_STRONG_PLANETS("Strong Planets: %s", "बलिया ग्रहहरू: %s"),
AVASTHA_STRONG_PLANETS_NOTE("These planets are well-placed and will give favorable results.", "यी ग्रहहरू राम्रो स्थितिमा छन् र अनुकूल नतिजा दिनेछन्।"),
AVASTHA_WEAK_PLANETS("Weak Planets: %s", "कमजोर ग्रहहरू: %s"),
AVASTHA_WEAK_PLANETS_NOTE("These planets may need remedial measures to strengthen their significations.", "यी ग्रहहरूको कारकत्व बलियो बनाउन उपचारात्मक उपायहरू आवश्यक हुन सक्छ।"),
AVASTHA_MODERATE_PLANETS_NOTE("Most planets are in moderate states, giving mixed results based on their periods.", "धेरै जसो ग्रहहरू मध्यम अवस्थामा छन्, जसले आफ्नो अवधि अनुसार मिश्रित नतिजा दिन्छन्।"),
    AVASTHA_REC_LOW_STRENGTH("Low strength (%d%%)", "Low strength (%d%%)"),
AVASTHA_REC_STRENGTHEN("Strengthen %s through gemstones, mantras, or charitable acts", "रत्न, मन्त्र वा परोपकारी कार्यहरू मार्फत %s लाई बलियो बनाउनुहोस्"),
AVASTHA_BALADI_DESC_INFO("Based on the planet's degree within a sign. Determines the maturity and capability of the planet to deliver results.", "राशिको डिग्रीमा आधारित। यसले ग्रहको नतिजा दिने परिपक्वता र क्षमता निर्धारण गर्दछ।"),
AVASTHA_JAGRADADI_DESC_INFO("Based on planet's relationship with sign lord. Determines how alert and active the planet is.", "राशि स्वामीसँगको सम्बन्धमा आधारित। यसले ग्रह कति सतर्क र सक्रिय छ भन्ने निर्धारण गर्दछ।"),
AVASTHA_DEEPTADI_DESC_INFO("Nine states based on exaltation, own sign, friends/enemies, and combustion. Determines overall dignity.", "उच्च, स्वराशि, मित्र/शत्रु र अस्तमा आधारित नौ अवस्थाहरू। यसले समग्र मर्यादा निर्धारण गर्दछ।"),
AVASTHA_LAJJITADI_DESC_INFO("Based on conjunctions and aspects. Determines the emotional state and how the planet feels in its position.", "युति र दृष्टिमा आधारित। यसले भावनात्मक अवस्था र ग्रह आफ्नो स्थितिमा कस्तो महसुस गर्छ भन्ने निर्धारण गर्दछ।"),
AVASTHA_RESULT_CAPACITY("%d%% result capacity", "%d%% नतिजा क्षमता"),
AVASTHA_NODE_POS("Node position in %s. %s", "%sमा नोडको स्थिति। %s"),
AVASTHA_ANALYZING("Analyzing Planetary States...", "ग्रहको अवस्थाहरू विश्लेषण गर्दै..."),
PRIORITY_HIGH("High Priority", "उच्च प्राथमिकता"),
PRIORITY_MEDIUM("Medium Priority", "मध्यम प्राथमिकता"),
PRIORITY_LOW("Low Priority", "न्यून प्राथमिकता"),
DIVISIONAL_OVERALL_STRENGTH("Overall Strength", "समग्र बल"),
DIVISIONAL_DOMINANT_PLANET("Dominant Planet", "प्रमुख ग्रह"),
DIVISIONAL_VARGOTTAMA_PLANETS("Vargottama Planets", "वर्गोत्तम ग्रहहरू"),
    DIVISIONAL_PLANETS_SAME_SIGN_DESC("Planets in same sign as Rashi (D1)", "Planets in same sign as Rashi (D1)"),
DIVISIONAL_HOUSE_PLACEMENTS("House Placements", "भाव स्थितिहरू"),
DIVISIONAL_HOUSE_EMPTY("Empty", "खाली"),
DIVISIONAL_HOUSE_OCCUPIED("Occupied", "भरिएको"),
DIVISIONAL_REMEDIES_DESC("Consider remedies for %s to improve its results.", "%s को नतिजा सुधार गर्न उपायहरू विचार गर्नुहोस्।"),
DIVISIONAL_STRENGTH_DESC("Utilize the strength of %s in this varga.", "यस वर्गमा %s को शक्ति सदुपयोग गर्नुहोस्।"),
HOUSE_LORD_1("1st Lord", "लग्नेश"),
HOUSE_LORD_2("2nd Lord", "द्वितीयेश"),
HOUSE_LORD_3("3rd Lord", "तृतीयेश"),
HOUSE_LORD_4("4th Lord", "चतुर्थेश"),
HOUSE_LORD_5("5th Lord", "पञ्चमेश"),
HOUSE_LORD_6("6th Lord", "षष्ठेश"),
HOUSE_LORD_7("7th Lord", "सप्तमेश"),
HOUSE_LORD_8("8th Lord", "अष्टमेश"),
HOUSE_LORD_9("9th Lord", "नवमेश"),
HOUSE_LORD_10("10th Lord", "दशमेश"),
HOUSE_LORD_11("11th Lord", "एकादशेश"),
HOUSE_LORD_12("12th Lord", "द्वादशेश"),
CAUTIONS("Cautions", "सावधानी")
}
