package com.astro.storm.core.common
enum class StringKeyFeature(override val en: String, override val ne: String) : StringKeyInterface {
FEATURE_BIRTH_CHART("Birth Chart", "जन्म कुण्डली"),
FEATURE_BIRTH_CHART_DESC("View your complete Vedic birth chart", "आफ्नो पूर्ण वैदिक जन्म कुण्डली हेर्नुहोस्"),
FEATURE_PLANETS("Planets", "ग्रहहरू"),
FEATURE_PLANETS_DESC("Detailed planetary positions", "विस्तृत ग्रह स्थिति"),
FEATURE_YOGAS("Yogas", "योगहरू"),
FEATURE_YOGAS_DESC("Planetary combinations & effects", "ग्रह संयोजन र प्रभावहरू"),
FEATURE_DASHAS("Dashas", "दशाहरू"),
FEATURE_DASHAS_DESC("Planetary period timeline", "ग्रह अवधि समयरेखा"),
FEATURE_TRANSITS("Transits", "गोचरहरू"),
FEATURE_TRANSITS_DESC("Current planetary movements", "हालको ग्रह गतिविधिहरू"),
FEATURE_ASHTAKAVARGA("Ashtakavarga", "अष्टकवर्ग"),
FEATURE_ASHTAKAVARGA_DESC("Strength analysis by house", "भावानुसार बल विश्लेषण"),
FEATURE_PANCHANGA("Panchanga", "पञ्चाङ्ग"),
FEATURE_PANCHANGA_DESC("Vedic calendar elements", "वैदिक पात्रो तत्वहरू"),
FEATURE_MATCHMAKING("Matchmaking", "कुण्डली मिलान"),
FEATURE_MATCHMAKING_DESC("Kundli Milan compatibility", "विवाह मेलापक गुण मिलान"),
FEATURE_MUHURTA("Muhurta", "मुहूर्त"),
FEATURE_MUHURTA_DESC("Auspicious timing finder", "शुभ समय खोजकर्ता"),
FEATURE_REMEDIES("Remedies", "उपायहरू"),
FEATURE_REMEDIES_DESC("Personalized remedies", "व्यक्तिगत उपायहरू"),
FEATURE_VARSHAPHALA("Varshaphala", "वर्षफल"),
FEATURE_VARSHAPHALA_DESC("Solar return horoscope", "वार्षिक राशिफल"),
FEATURE_PRASHNA("Prashna", "प्रश्न"),
FEATURE_PRASHNA_DESC("Horary astrology", "प्रश्न ज्योतिष"),
FEATURE_SYNASTRY("Synastry", "सिनास्ट्री"),
FEATURE_SYNASTRY_DESC("Chart comparison", "कुण्डली तुलना"),
FEATURE_NAKSHATRAS("Nakshatras", "नक्षत्रहरू"),
FEATURE_NAKSHATRAS_DESC("Deep nakshatra analysis", "गहन नक्षत्र विश्लेषण"),
FEATURE_SHADBALA("Shadbala", "षड्बल"),
FEATURE_SHADBALA_DESC("Six-fold strength", "छवटा बलहरू"),
FEATURE_SHODASHVARGA("Shodashvarga", "षोडशवर्ग"),
FEATURE_SHODASHVARGA_DESC("16-divisional chart strength", "१६-विभाजन कुण्डली बल"),
FEATURE_YOGINI_DASHA("Yogini Dasha", "योगिनी दशा"),
FEATURE_YOGINI_DASHA_DESC("36-year nakshatra dasha", "३६-वर्षे नक्षत्र दशा"),
FEATURE_ARGALA("Argala", "अर्गला"),
FEATURE_ARGALA_DESC("Jaimini intervention analysis", "जैमिनी हस्तक्षेप विश्लेषण"),
FEATURE_CHARA_DASHA("Chara Dasha", "चर दशा"),
FEATURE_CHARA_DASHA_DESC("Jaimini sign-based dasha", "जैमिनी राशि-आधारित दशा"),
FEATURE_BHRIGU_BINDU("Bhrigu Bindu", "भृगु बिन्दु"),
FEATURE_BHRIGU_BINDU_DESC("Karmic destiny point", "कार्मिक भाग्य बिन्दु"),
FEATURE_PREDICTIONS("Predictions", "भविष्यवाणी"),
FEATURE_PREDICTIONS_DESC("Comprehensive life analysis", "व्यापक जीवन विश्लेषण"),
FEATURE_ASHTOTTARI_DASHA("Ashtottari Dasha", "अष्टोत्तरी दशा"),
FEATURE_ASHTOTTARI_DASHA_DESC("108-year Nakshatra-based timing", "१०८ वर्षे नक्षत्र-आधारित समय"),
FEATURE_SUDARSHANA_CHAKRA("Sudarshana Chakra", "सुदर्शन चक्र"),
FEATURE_SUDARSHANA_CHAKRA_DESC("Triple-reference annual prediction", "त्रि-संदर्भ वार्षिक भविष्यवाणी"),
FEATURE_MRITYU_BHAGA("Mrityu Bhaga", "मृत्यु भाग"),
FEATURE_MRITYU_BHAGA_DESC("Sensitive degrees analysis", "संवेदनशील अंश विश्लेषण"),
FEATURE_LAL_KITAB("Lal Kitab Remedies", "लाल किताब उपाय"),
FEATURE_LAL_KITAB_DESC("Practical everyday remedies", "व्यावहारिक दैनिक उपाय"),
FEATURE_DIVISIONAL_CHARTS("Divisional Charts", "विभागीय कुण्डली"),
FEATURE_DIVISIONAL_CHARTS_DESC("D-2, D-3, D-9, D-10, D-12 analysis", "होरा, द्रेक्काण, नवांश, दशमांश, द्वादशांश"),
FEATURE_UPACHAYA_TRANSIT("Upachaya Transits", "उपचय गोचर"),
FEATURE_UPACHAYA_TRANSIT_DESC("Growth house transit tracking", "उपचय भाव गोचर विश्लेषण"),
FEATURE_KALACHAKRA_DASHA("Kalachakra Dasha", "कालचक्र दशा"),
FEATURE_KALACHAKRA_DASHA_DESC("Body-soul timing system for health and spiritual predictions", "स्वास्थ्य र आध्यात्मिक भविष्यवाणीको लागि देह-आत्मा समय प्रणाली"),
FEATURE_TARABALA("Tarabala", "ताराबल"),
FEATURE_TARABALA_DESC("Daily Moon strength & Nakshatra timing", "दैनिक चन्द्र बल र नक्षत्र समय"),
FEATURE_ARUDHA_PADA("Arudha Pada", "आरूढ पद"),
FEATURE_ARUDHA_PADA_DESC("Jaimini Arudha analysis for manifestation", "जैमिनी आरूढ विश्लेषण"),
FEATURE_GRAHA_YUDDHA("Graha Yuddha", "ग्रह युद्ध"),
FEATURE_GRAHA_YUDDHA_DESC("Planetary war analysis & remedies", "ग्रह युद्ध विश्लेषण र उपाय"),
FEATURE_DASHA_SANDHI("Dasha Sandhi", "दशा सन्धि"),
FEATURE_DASHA_SANDHI_DESC("Period transition analysis", "अवधि संक्रमण विश्लेषण"),
FEATURE_GOCHARA_VEDHA("Gochara Vedha", "गोचर वेध"),
FEATURE_GOCHARA_VEDHA_DESC("Transit obstruction effects", "गोचर अवरोध प्रभाव"),
FEATURE_KEMADRUMA_YOGA("Kemadruma Yoga", "केमद्रुम योग"),
FEATURE_KEMADRUMA_YOGA_DESC("Moon isolation analysis", "चन्द्र एकान्त विश्लेषण"),
FEATURE_PANCH_MAHAPURUSHA("Panch Mahapurusha", "पञ्च महापुरुष"),
FEATURE_PANCH_MAHAPURUSHA_DESC("Five great person yogas", "पाँच महान् व्यक्ति योग"),
FEATURE_NITYA_YOGA("Nitya Yoga", "नित्य योग"),
FEATURE_NITYA_YOGA_DESC("27 daily yogas", "२७ दैनिक योगहरू"),
FEATURE_AVASTHA("Avastha", "अवस्था"),
FEATURE_AVASTHA_DESC("Planetary states analysis", "ग्रह अवस्था विश्लेषण"),
FEATURE_MARAKA("Maraka", "मारक"),
FEATURE_MARAKA_DESC("Death-inflicting planets", "मृत्यु कारक ग्रहहरू"),
FEATURE_BADHAKA("Badhaka", "बाधक"),
FEATURE_BADHAKA_DESC("Obstructing planets", "बाधा कारक ग्रहहरू"),
FEATURE_VIPAREETA_RAJA_YOGA("Vipareeta Raja Yoga", "विपरीत राजयोग"),
FEATURE_VIPAREETA_RAJA_YOGA_DESC("Reverse raja yogas", "विपरीत राजयोग विश्लेषण"),
FEATURE_ISHTA_KASHTA_PHALA("Ishta Kashta Phala", "इष्ट कष्ट फल"),
FEATURE_ISHTA_KASHTA_PHALA_DESC("Benefic/malefic results", "शुभ/अशुभ फल विश्लेषण"),
FEATURE_SHOOLA_DASHA("Shoola Dasha", "शूल दशा"),
FEATURE_SHOOLA_DASHA_DESC("Health & critical timing", "स्वास्थ्य र गम्भीर समय"),
FEATURE_ASHTAVARGA_TRANSIT("Ashtavarga Transit", "अष्टकवर्ग गोचर"),
FEATURE_ASHTAVARGA_TRANSIT_DESC("Transit predictions by bindu", "बिन्दुद्वारा गोचर भविष्यवाणी"),
FEATURE_KAKSHYA_TRANSIT("Kakshya Transit", "कक्ष्या गोचर"),
FEATURE_KAKSHYA_TRANSIT_DESC("Advanced 8-fold micro-transit analysis", "८-गुणा सूक्ष्म गोचर विश्लेषण"),
FEATURE_NATIVE_ANALYSIS("Native Analysis", "जातक विश्लेषण"),
FEATURE_NATIVE_ANALYSIS_DESC("Complete life profile & personality", "सम्पूर्ण जीवन प्रोफाइल र व्यक्तित्व"),
ONBOARDING_WELCOME_TITLE("Welcome to AstroStorm", "AstroStorm मा स्वागत छ"),
ONBOARDING_WELCOME_SUBTITLE("Your personal Vedic astrology companion", "तपाईंको व्यक्तिगत वैदिक ज्योतिष साथी"),
ONBOARDING_WELCOME_DESC("Discover the ancient wisdom of Vedic astrology with precision calculations and personalized insights.", "सटीक गणना र व्यक्तिगत अन्तर्दृष्टिका साथ वैदिक ज्योतिषको प्राचीन ज्ञान पत्ता लगाउनुहोस्।"),
ONBOARDING_TAGLINE("Precision Vedic Astrology", "सटीक वैदिक ज्योतिष"),
ONBOARDING_FEATURES_OVERVIEW_TITLE("What AstroStorm Offers", "AstroStorm ले के प्रदान गर्दछ"),
ONBOARDING_FEATURE_CAT_CHART("Complete Chart Analysis", "पूर्ण कुण्डली विश्लेषण"),
ONBOARDING_FEATURE_CAT_CHART_ITEMS("Rashi & Divisional Charts • Shadbala & Ashtakavarga • All 16 Vargas", "राशि र विभागीय कुण्डलीहरू • षड्बल र अष्टकवर्ग • सबै १६ वर्गहरू"),
ONBOARDING_FEATURE_CAT_DASHA("Dasha Systems", "दशा प्रणालीहरू"),
ONBOARDING_FEATURE_CAT_DASHA_ITEMS("Vimshottari & Yogini • Ashtottari & Chara • Kalachakra Dasha", "विम्शोत्तरी र योगिनी • अष्टोत्तरी र चर • कालचक्र दशा"),
ONBOARDING_FEATURE_CAT_PREDICTION("Predictions & Yogas", "भविष्यवाणी र योगहरू"),
    ONBOARDING_FEATURE_CAT_PREDICTION_ITEMS("200+ Yoga Calculations • Transit Analysis • Matchmaking (Kundali Milan)", "200+ Yoga Calculations • Transit Analysis • Matchmaking (Kundali Milan)"),
ONBOARDING_FEATURE_CAT_REMEDY("Remedies & Muhurta", "उपाय र मुहूर्त"),
ONBOARDING_FEATURE_CAT_REMEDY_ITEMS("Vedic & Lal Kitab Remedies • Auspicious Timing • Panchanga", "वैदिक र लाल किताब उपायहरू • शुभ समय • पञ्चाङ्ग"),
ONBOARDING_QUICK_START_TITLE("You'll need:", "तपाईंलाई आवश्यक पर्नेछ:"),
ONBOARDING_QUICK_START_1("Birth date & time", "जन्म मिति र समय"),
    ONBOARDING_QUICK_START_2("Birth location (city)", "Birth location (city)"),
ONBOARDING_QUICK_START_3("That's all!", "त्यति मात्र हो!"),
ONBOARDING_LANGUAGE_TITLE("Choose Your Language", "आफ्नो भाषा छान्नुहोस्"),
ONBOARDING_LANGUAGE_SUBTITLE("Select your preferred language", "आफ्नो मनपर्ने भाषा छान्नुहोस्"),
ONBOARDING_LANGUAGE_DESC("You can change this later in settings.", "तपाईं यसलाई पछि सेटिङ्समा परिवर्तन गर्न सक्नुहुन्छ।"),
ONBOARDING_THEME_TITLE("Choose Your Theme", "आफ्नो थिम छान्नुहोस्"),
ONBOARDING_THEME_SUBTITLE("Select your preferred appearance", "आफ्नो मनपर्ने रूप छान्नुहोस्"),
ONBOARDING_THEME_DESC("You can change this later in settings.", "तपाईं यसलाई पछि सेटिङ्समा परिवर्तन गर्न सक्नुहुन्छ।"),
ONBOARDING_THEME_LIGHT("Light", "उज्यालो"),
ONBOARDING_THEME_DARK("Dark", "अँध्यारो"),
ONBOARDING_THEME_SYSTEM("System", "प्रणाली"),
ONBOARDING_FEATURES_TITLE("Powerful Features", "शक्तिशाली सुविधाहरू"),
ONBOARDING_FEATURES_SUBTITLE("Everything you need for Vedic astrology", "वैदिक ज्योतिषको लागि तपाईंलाई चाहिने सबै"),
ONBOARDING_FEATURE_CHARTS("Birth Charts", "जन्म कुण्डली"),
ONBOARDING_FEATURE_CHARTS_DESC("Accurate Vedic birth chart calculations", "सटीक वैदिक जन्म कुण्डली गणना"),
ONBOARDING_FEATURE_DASHAS("Dashas", "दशाहरू"),
ONBOARDING_FEATURE_DASHAS_DESC("Complete planetary period analysis", "पूर्ण ग्रह अवधि विश्लेषण"),
ONBOARDING_FEATURE_TRANSITS("Transits", "गोचरहरू"),
ONBOARDING_FEATURE_TRANSITS_DESC("Real-time planetary movements", "वास्तविक-समय ग्रह गतिविधि"),
ONBOARDING_FEATURE_MATCHMAKING("Matchmaking", "कुण्डली मिलान"),
ONBOARDING_FEATURE_MATCHMAKING_DESC("Kundli Milan compatibility", "कुण्डली मिलान अनुकूलता"),
ONBOARDING_READY_TITLE("You're All Set!", "तपाईं तयार हुनुहुन्छ!"),
ONBOARDING_READY_SUBTITLE("Start exploring your cosmic journey", "आफ्नो ब्रह्माण्डीय यात्रा अन्वेषण गर्न सुरु गर्नुहोस्"),
ONBOARDING_READY_DESC("Create your first birth chart and discover personalized astrological insights.", "आफ्नो पहिलो जन्म कुण्डली बनाउनुहोस् र व्यक्तिगत ज्योतिषीय अन्तर्दृष्टिहरू पत्ता लगाउनुहोस्।"),
ONBOARDING_CREATE_FIRST_CHART("Create Your First Chart", "तपाईंको पहिलो कुण्डली बनाउनुहोस्"),
ONBOARDING_BTN_NEXT("Next", "अर्को"),
ONBOARDING_BTN_BACK("Back", "पछाडि"),
ONBOARDING_BTN_GET_STARTED("Get Started", "सुरु गर्नुहोस्"),
ONBOARDING_BTN_SKIP("Skip", "छोड्नुहोस्")
}
