package com.astro.storm.core.common

enum class StringKeyGeneralPart9(override val en: String, override val ne: String) : StringKeyInterface {
    PRED_SPIRIT_KEY_2("Self-reflection", "आत्म-चिन्तन"),
    PRED_SPIRIT_KEY_3("Service to others", "अरूको सेवा"),
    PRED_SPIRIT_LEO("heart-centered consciousness", "हृदय-केन्द्रित चेतना"),
    PRED_SPIRIT_LIBRA("balance and unity consciousness", "सन्तुलन र एकता चेतना"),
    PRED_SPIRIT_LONG("Significant spiritual evolution. Inner peace and wisdom established.", "महत्त्वपूर्ण आध्यात्मिक विकास। आन्तरिक शान्ति र ज्ञान स्थापित।"),
    PRED_SPIRIT_MED("Deepening spiritual understanding. Connection with teachers or spiritual communities.", "आध्यात्मिक समझ गहिरो हुँदै। शिक्षक वा आध्यात्मिक समुदायहरूसँग सम्बन्ध।"),
    PRED_SPIRIT_PISCES("dissolution into divine consciousness", "दिव्य चेतनामि विलय"),
    PRED_SPIRIT_SAGITTARIUS("truth-seeking and higher knowledge", "सत्यको खोज र उच्च ज्ञान"),
    PRED_SPIRIT_SCORPIO("death and rebirth cycles", "मृत्यु र पुनर्जन्म चक्र"),
    PRED_SPIRIT_SHORT("Daily practices bring mental peace. Insights come through meditation.", "दैनिक अभ्यासले मानसिक शान्ति ल्याउँछ। ध्यान मार्फत अन्तरदृष्टि आउँछ।"),
    PRED_SPIRIT_TAURUS("grounding and material transcendence", "आधार र भौतिक उत्कृष्टता"),
    PRED_SPIRIT_TEMPLATE("Your spiritual journey emphasizes %s through %s influences.", "तपाईंको आध्यात्मिक यात्राले %s प्रभावहरू मार्फत %s मा जोड दिन्छ।"),
    PRED_SPIRIT_VIRGO("perfection through service", "सेवा मार्फत पूर्णता"),
    PRED_STRENGTH_DETERMINATION("Strong determination and resilience in your character", "तपाईंको चरित्रमा बलियो दृढ संकल्प र लचिलोपन"),
    PRED_STRENGTH_EMOTIONAL("Capacity for deep emotional understanding", "गहिरो भावनात्मक समझको क्षमता"),
    PRED_STRENGTH_PRACTICAL("Practical approach to life's challenges", "जीवनका चुनौतीहरूप्रति व्यावहारिक दृष्टिकोण"),
    PRED_STRENGTH_SPIRITUAL("Natural ability to connect with spiritual wisdom", "आध्यात्मिक ज्ञानसँग जोडिने प्राकृतिक क्षमता"),
    PRED_THEME_AQUARIUS("Innovator & Humanitarian", "नवप्रवर्तक र मानवतावादी"),
    PRED_THEME_ARIES("Pioneer & Warrior", "अग्रगामी र योद्धा"),
    PRED_THEME_CANCER("Nurturer & Protector", "पालनकर्ता र संरक्षक"),
    PRED_THEME_CAPRICORN("Achiever & Master", "सफल र निपुण"),
    PRED_THEME_GEMINI("Communicator & Learner", "सञ्चारकर्मी र शिक्षार्थी"),
    PRED_THEME_LEO("Leader & Creator", "नेता र सिर्जनाकर्ता"),
    PRED_THEME_LIBRA("Diplomat & Artist", "कुटनीतिज्ञ र कलाकार"),
    PRED_THEME_PISCES("Mystic & Compassionate Soul", "रहस्यवादी र दयालु आत्मा"),
    PRED_THEME_SAGITTARIUS("Philosopher & Explorer", "दार्शनिक र अन्वेषक"),
    PRED_THEME_SCORPIO("Transformer & Investigator", "रूपान्तरक र अन्वेषक"),
    PRED_THEME_TAURUS("Builder & Preserver", "निर्माता र रक्षक"),
    PRED_THEME_VIRGO("Server & Healer", "सेवक र उपचारक"),
    PRED_TIMING_JUPITER_ASPECT_EVENT("Favorable Jupiter Aspect", "शुभ बृहस्पति दृष्टि"),
    PRED_TIMING_JUPITER_ASPECT_SIG("Excellent for new beginnings", "नयाँ सुरुवातका लागि उत्कृष्ट"),
    PRED_TIMING_JUPITER_BEST_1("New ventures", "नयाँ उद्यमहरू"),
    PRED_TIMING_JUPITER_BEST_2("Important decisions", "महत्त्वपूर्ण निर्णयहरू"),
    PRED_TIMING_JUPITER_BEST_3("Relationships", "सम्बन्धहरू"),
    PRED_TIMING_JUPITER_REASON("Jupiter transit supports growth", "बृहस्पति गोचरले वृद्धिलाई सहयोग गर्छ"),
    PRED_TIMING_SATURN_AVOID_1("Major investments", "ठूला लगानीहरू"),
    PRED_TIMING_SATURN_AVOID_2("Hasty decisions", "हतारका निर्णयहरू"),
    PRED_TIMING_SATURN_AVOID_3("Conflicts", "द्वन्द्वहरू"),
    PRED_TIMING_SATURN_REASON("Saturn transit requires caution", "शनि गोचरले सावधानीको माग गर्छ"),
    PRED_TRANSIT_DEFAULT("Planetary influence active", "ग्रह प्रभाव सक्रिय"),
    PRED_TRANSIT_JUPITER("Growth and opportunities", "वृद्धि र अवसरहरू"),
    PRED_TRANSIT_KETU("Spiritual awakening", "आध्यात्मिक जागरण"),
    PRED_TRANSIT_MARS("Increased energy and drive", "बढेको ऊर्जा र उत्साह"),
    PRED_TRANSIT_MERCURY("Mental activity and communication", "मानसिक गतिविधि र सञ्चार"),
    PRED_TRANSIT_MOON("Emotional fluctuations", "भावनात्मक उतार-चढाव"),
    PRED_TRANSIT_RAHU("Unexpected developments", "अप्रत्याशित घटनाक्रम"),
    PRED_TRANSIT_SATURN("Discipline and restrictions", "अनुशासन र प्रतिबन्धहरू"),
    PRED_TRANSIT_SUN("Illuminating life purpose", "जीवन उद्देश्य प्रष्ट पार्दै"),
    PRED_TRANSIT_VENUS("Harmony and relationships", "सद्भाव र सम्बन्धहरू"),
    PRED_YEARS_REMAINING("%.1f years remaining", "%.1f वर्ष बाँकी"),
    PRED_YOGA_DHANA_DESC("Wealth-creating planetary combination", "धन-सिर्जना गर्ने ग्रह संयोजन"),
    PRED_YOGA_DHANA_EFFECT("Favorable for financial growth and material prosperity", "आर्थिक वृद्धि र भौतिक समृद्धिको लागि अनुकूल"),
    PRED_YOGA_DHANA_NAME("Dhana Yoga", "धन योग"),
    PRED_YOGA_RAJA_DESC("Royal combination indicating success", "सफलता संकेत गर्ने शाही संयोजन"),
    PRED_YOGA_RAJA_EFFECT("Support for leadership and achievement", "नेतृत्व र उपलब्धिका लागि सहयोग"),
    PRED_YOGA_RAJA_NAME("Raja Yoga", "राज योग"),
    PRESENT("Present", "उपस्थित"),
    PREVENTIVE_MEASURES("Preventive Measures", "रोकथाम उपायहरू"),
    PREVIOUS_LABEL("Previous", "अघिल्लो"),
    PRIMARY_DOSHA("Primary Dosha", "प्राथमिक दोष"),
    PRIMARY_EDUCATION("Primary Education Pattern", "प्राथमिक शिक्षा ढाँचा"),
    PRIMARY_GEMSTONE("Primary Gemstone", "प्राथमिक रत्न"),
    PRIMARY_INDICATORS("Primary Career Indicators", "प्राथमिक क्यारियर सूचकहरू"),
    PRIMARY_LABEL("Primary", "प्राथमिक"),
    PRIMARY_SOURCES("Primary Wealth Sources", "प्राथमिक धन स्रोतहरू"),
    PRIORITY_AREAS("Priority Focus Areas", "प्राथमिकता फोकस क्षेत्रहरू"),
    PRIORITY_ESSENTIAL("Essential", "अत्यावश्यक"),
    PRIORITY_HIGH("High Priority", "उच्च प्राथमिकता"),
    PRIORITY_HIGHLY_RECOMMENDED("Highly Recommended", "अत्यधिक सिफारिस गरिएको"),
    PRIORITY_LOW("Low Priority", "न्यून प्राथमिकता"),
    PRIORITY_MEDIUM("Medium Priority", "मध्यम प्राथमिकता"),
    PRIORITY_OPTIONAL("Optional", "वैकल्पिक"),
    PRIORITY_RECOMMENDED("Recommended", "सिफारिस गरिएको"),
    PROBLEM_SOLVING("Problem Solving Style", "समस्या समाधान शैली"),
    PROFESSIONAL_CERTS("Professional Certifications", "व्यावसायिक प्रमाणपत्रहरू"),
    PROFESSIONAL_REPUTATION("Professional Reputation", "व्यावसायिक प्रतिष्ठा"),
    PROFESSION_ARTS("Arts & Entertainment", "कला र मनोरञ्जन"),
    PROFESSION_BUSINESS("Business & Commerce", "व्यापार र वाणिज्य"),
    PROFESSION_EDUCATION("Education & Teaching", "शिक्षा र शिक्षण"),
    PROFESSION_ENGINEERING("Engineering & Technical", "इन्जिनियरिङ र प्राविधिक"),
    PROFESSION_FINANCE("Finance & Banking", "वित्त र बैंकिङ"),
    PROFESSION_GOVERNMENT("Government & Administration", "सरकार र प्रशासन"),
    PROFESSION_HEALTHCARE("Healthcare & Medicine", "स्वास्थ्य सेवा र चिकित्सा"),
    PROFESSION_LAW("Law & Legal", "कानुन र कानूनी"),
    PROFESSION_MEDIA("Media & Communications", "मिडिया र सञ्चार"),
    PROFESSION_MILITARY("Military & Defense", "सैनिक र रक्षा"),
    PROFESSION_RESEARCH("Research & Academia", "अनुसन्धान र शिक्षाविद्"),
    PROFESSION_SPIRITUAL("Spiritual & Religious", "आध्यात्मिक र धार्मिक"),
    PROFESSION_TECHNOLOGY("Technology & IT", "प्रविधि र आईटी"),
    PROFILE_ADD_FIRST_CHART("Add your first chart to get started", "सुरु गर्न आफ्नो पहिलो कुण्डली थप्नुहोस्"),
    PROFILE_ADD_NEW("Add New Profile", "नयाँ प्रोफाइल थप्नुहोस्"),
    PROFILE_ADD_NEW_CHART("Add new chart", "नयाँ कुण्डली थप्नुहोस्"),
    PROFILE_BIRTH_CHART("Birth chart", "जन्म कुण्डली"),
    PROFILE_CURRENT("Current", "हालको"),
    PROFILE_CURRENT_A11Y("Current profile: %s. Tap to switch profiles", "हालको प्रोफाइल: %s। प्रोफाइलहरू बदल्न ट्याप गर्नुहोस्"),
    PROFILE_DELETE_MESSAGE("Are you sure you want to delete \"{name}\"? This action cannot be undone and all associated data will be permanently removed.", "के तपाईं \"{name}\" मेट्न निश्चित हुनुहुन्छ? यो कार्य पूर्ववत गर्न सकिँदैन र सबै सम्बन्धित डाटा स्थायी रूपमा हटाइनेछ।"),
    PROFILE_DELETE_TITLE("Delete Birth Chart", "जन्म कुण्डली मेट्नुहोस्"),
    PROFILE_EDIT_CHART("Edit Chart", "कुण्डली सम्पादन गर्नुहोस्"),
    PROFILE_ID_LABEL("ID: %s", "आईडी: %s"),
    PROFILE_NO_SAVED_CHARTS("No saved charts", "कुनै सुरक्षित कुण्डली छैन"),
    PROFILE_NO_SELECTED_A11Y("No profile selected. Tap to select a profile", "कुनै प्रोफाइल छानिएको छैन। प्रोफाइल छान्न ट्याप गर्नुहोस्"),
    PROFILE_OP_CREATING("Creating Profile", "प्रोफाइल बनाउँदै"),
    PROFILE_OP_DELETING("Deleting Profile", "प्रोफाइल हटाउँदै"),
    PROFILE_OP_UPDATING("Updating Profile", "प्रोफाइल अपडेट गर्दै"),
    PROFILE_OP_VIEWING("Viewing Profile", "प्रोफाइल हेर्दै"),
    PROFILE_SELECT("Select Profile", "प्रोफाइल छान्नुहोस्"),
    PROFILE_SELECTED("selected", "छानिएको"),
    PROFILE_STATUS_FAILED("Failed", "असफल"),
    PROFILE_STATUS_IN_PROGRESS("In Progress", "प्रगतिमा"),
    PROFILE_STATUS_PENDING("Pending", "पर्खिएको"),
    PROFILE_STATUS_SUCCESS("Success", "सफल"),
    PROFILE_SWITCH("Switch Profile", "प्रोफाइल बदल्नुहोस्"),
    PUBLIC_DEALINGS("Public Dealings", "सार्वजनिक व्यवहार"),
    PUBLIC_IMAGE_TITLE("Public Image", "सार्वजनिक छवि"),
    PUBLIC_PERCEPTION("How Others Perceive You", "अरूले तपाईंलाई कसरी बुझ्छन्"),
    PURPOSE("Purpose", "उद्देश्य"),
    PUSHKARA_BHAGA_DESC("Single auspicious degrees providing nourishment", "पोषण प्रदान गर्ने एकल शुभ अंशहरू"),
    PUSHKARA_BHAGA_TITLE("Pushkara Bhaga", "पुष्कर भाग"),
    PUSHKARA_NAVAMSA_DESC("Highly auspicious navamsa placements providing protection", "सुरक्षा प्रदान गर्ने अत्यधिक शुभ नवांश स्थितिहरू"),
    PUSHKARA_NAVAMSA_TITLE("Pushkara Navamsa", "पुष्कर नवांश"),
    PUSH_BASE_1("Highly auspicious placement bringing good fortune", "उच्च शुभ स्थिति जसले राम्रो भाग्य ल्याउँछ"),
    PUSH_BASE_2("Planet's significations strengthened", "ग्रहको कारकत्व बलियो पारिएको"),
    PUSH_BASE_3("Protection during difficult periods", "कठिन अवधिमा सुरक्षा"),
    PUSH_BHAGA_ACT("Auspicious for %s-related activities", "%s सँग सम्बन्धित गतिविधिहरूको लागि शुभ"),
    PUSH_BHAGA_NOURISH("Planet at its most nourishing degree", "ग्रह आफ्नो सबैभन्दा पोषक डिग्रीमा"),
    PUSH_BHAGA_PROT("Natural protection during %s periods", "%s को अवधिमा प्राकृतिक सुरक्षा"),
    PUSH_BHAGA_SUPPORT("Significations of %s receive special support", "%s को कारकत्वहरूले विशेष समर्थन प्राप्त गर्दछ"),
    PUSH_GEN_PROT("General protection and auspiciousness", "सामान्य सुरक्षा र शुभता"),
    PUSH_JUP_1("Wisdom and spiritual growth enhanced", "ज्ञान र आध्यात्मिक वृद्धि बढाइएको"),
    PUSH_JUP_2("Educational success", "शैक्षिक सफलता"),
    PUSH_MERC_1("Intellectual brilliance", "बौद्धिक प्रखरता"),
    PUSH_MERC_2("Communication excellence", "उत्कृष्ट सञ्चार"),
    PUSH_MOON_1("Emotional stability and contentment", "भावनात्मक स्थिरता र सन्तुष्टि"),
    PUSH_MOON_2("Good mental health", "राम्रो मानसिक स्वास्थ्य"),
    PUSH_VENUS_1("Relationship harmony", "सम्बन्धमा सद्भाव"),
    PUSH_VENUS_2("Artistic success and beauty", "कलात्मक सफलता र सौन्दर्य"),
    QUALITY_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    QUALITY_DIFFICULT("Difficult Period", "कठिन अवधि"),
    QUALITY_EXCELLENT("Excellent", "उत्कृष्ट"),
    QUALITY_GOOD("Good", "राम्रो"),
    QUALITY_INAUSPICIOUS("Inauspicious", "अशुभ"),
    QUALITY_LABEL("Quality", "गुणस्तर"),
    QUALITY_MIXED("Mixed Period", "मिश्रित अवधि"),
    QUALITY_NEUTRAL("Neutral", "तटस्थ"),
    QUICK_ACTIONS("Quick Actions", "द्रुत कार्यहरू"),
    RAJA_YOGA_CAREER("Raja Yoga Career Effect", "राज योग क्यारियर प्रभाव"),
    RARITY_2("Uncommon - Two Mahapurusha Yogas", "असामान्य - दुई महापुरुष योग"),
    RARITY_3("Rare - Three Mahapurusha Yogas", "दुर्लभ - तीन महापुरुष योग"),
    RARITY_4("Very Rare - Four Mahapurusha Yogas", "धेरै दुर्लभ - चार महापुरुष योग"),
    RARITY_5("Extremely Rare - All Five Mahapurusha Yogas", "अत्यन्तै दुर्लभ - सबै पाँच महापुरुष योग"),
    REASON_ACCIDENTS_LIKELY("Accidents/problems likely", "दुर्घटना/समस्याको सम्भावना"),
    REASON_AUSPICIOUS_UNIONS("Auspicious for unions", "मिलनका लागि शुभ"),
    REASON_COMM_ENHANCED("Communication enhanced", "सञ्चार बढाइएको छ"),
    REASON_CONTINUE_WORK("Continue existing work", "अवस्थित काम जारी राख्नुहोस्"),
    REASON_DAY_INAUSPICIOUS("Day is inauspicious", "दिन अशुभ छ"),
    REASON_DELAYS_POSSIBLE("Delays possible", "ढिलाइ हुन सक्छ"),
    REASON_DELAYS_PROBLEMS("Delays and problems possible", "ढिलाइ र समस्याहरू सम्भव छ"),
    REASON_FACE_DESTRUCTION("Will face destruction", "विनाशको सामना गर्नेछ"),
    REASON_GENERALLY_SUPPORTIVE("Generally supportive", "सामान्यतया समर्थनात्मक"),
    REASON_HEALTH_SUPPORTED("Health matters supported", "स्वास्थ्य मामिलाहरू समर्थित"),
    REASON_INNER_WORK_BENEFICIAL("Inner work beneficial", "आन्तरिक कार्य लाभदायक"),
    REASON_JOURNEYS_SUCCESS("Journeys will be successful", "यात्राहरू सफल हुनेछन्"),
    REASON_JUDGMENT_CLOUDED("Judgment may be clouded", "निर्णय धमिलो हुन सक्छ"),
    REASON_MIXED_RESULTS("Mixed results likely", "मिश्रित परिणामको सम्भावना"),
    REASON_NORMAL_PRODUCTIVITY("Normal productivity expected", "सामान्य उत्पादकता अपेक्षित छ"),
    REASON_NOT_BENEFICIAL("Will not be beneficial", "लाभदायक हुने छैन"),
    REASON_NOT_BEST_SPECULATION("Not the best time for speculation", "सट्टेबाजीको लागि उत्तम समय होइन"),
    REASON_OBSTACLES_LIKELY("Obstacles likely", "बाधाहरूको सम्भावना"),
    REASON_PRODUCTIVITY_ENHANCED("Productivity enhanced", "उत्पादकता बढाइएको छ"),
    REASON_REDUCES_NEG_KARMA("Reduces negative karma", "नकारात्मक कर्म कम गर्दछ"),
    REASON_REJUVENATION_FAVORED("Rejuvenation favored", "पुनरुत्थानका लागि अनुकूल"),
    REASON_RELATIONSHIPS_FAVORED("Relationships favored", "सम्बन्धहरूको लागि अनुकूल"),
    REASON_SAFE_JOURNEYS("Safe for journeys", "यात्राको लागि सुरक्षित"),
    REASON_SPIRITUAL_PROT_NEEDED("Spiritual protection needed", "आध्यात्मिक सुरक्षा आवश्यक छ"),
    REASON_TARA_CHANDRA_SUPPORT("Both Tara and Chandra support new beginnings", "तारा र चन्द्र दुवैले नयाँ सुरुवातलाई समर्थन गर्दछ"),
    REASON_UNLESS_EMERGENCY("Unless emergency", "संकट बाहेक"),
    REASON_UNLESS_LIFE_THREATENING("Unless life-threatening emergency", "जीवन-जोखिम संकट बाहेक"),
    REASON_WAIT_BETTER_TIMING("Wait for better timing", "राम्रो समयको लागि पर्खनुहोस्"),
    REASON_WEALTH_FAVORED("Wealth matters favored", "धनको मामिलामा अनुकूल"),
    RECOMMEND_ACTIVITY("Activity Guidance", "गतिविधि मार्गदर्शन"),
    RECOMMEND_GENERAL("General Guidance", "सामान्य मार्गदर्शन"),
    RECOMMEND_MANTRA("Mantra Recitation", "मन्त्र जप"),
    RECOMMEND_SPIRITUAL("Spiritual Practice", "आध्यात्मिक अभ्यास"),
    RECOMMEND_TIMING("Timing Advice", "समय सल्लाह"),
    RECOVERY_LIKELIHOOD("Recovery likelihood", "प्राप्ति सम्भावना"),
    RECOVERY_OUTLOOK("Recovery outlook", "सुधारको दृष्टिकोण"),
    REC_ACTIVATE_YOGA("Activate {0} through {1} worship", "{1} पूजाको माध्यमबाट {0} सक्रिय गर्नुहोस्"),
    REC_AREA_CAREER("Capitalize on favorable career energy today.", "आज अनुकूल करियर ऊर्जाको फाइदा उठाउनुहोस्।"),
    REC_AREA_FAMILY("Spend quality time with family members.", "परिवारका सदस्यहरूसँग गुणस्तरीय समय बिताउनुहोस्।"),
    REC_AREA_FINANCE("Take advantage of positive financial influences.", "सकारात्मक वित्तीय प्रभावहरूको फाइदा उठाउनुहोस्।"),
    REC_AREA_HEALTH("Make the most of your vibrant health energy.", "आफ्नो जीवन्त स्वास्थ्य ऊर्जाको अधिकतम सदुपयोग गर्नुहोस्।"),
    REC_AREA_LOVE("Nurture your relationships with extra attention.", "आफ्नो सम्बन्धलाई अतिरिक्त ध्यान दिएर पोषण गर्नुहोस्।"),
    REC_AREA_SPIRITUALITY("Deepen your spiritual practices.", "आफ्नो आध्यात्मिक अभ्यासहरूलाई गहिरो बनाउनुहोस्।"),
    REC_AVOID_ISOLATION("Avoid isolation - maintain social connections", "एक्लोपनबाट बच्नुहोस् - सामाजिक सम्बन्धहरू कायम राख्नुहोस्"),
    REC_AVOID_LOANS("Avoid loans and debts during Moon periods", "चन्द्रमाको अवधिमा ऋण र उधारोबाट बच्नुहोस्"),
    REC_AVOID_SPECULATION("Avoid speculative investments", "सट्टा लगानीबाट बच्नुहोस्"),
    REC_BEST_CAREER("Best career alignment: {0}", "उत्तम करियर संरेखण: {0}"),
    REC_COMMUNITY_SERVICE("Join community or spiritual groups. Service to others reduces isolation effects", "सामुदायिक वा आध्यात्मिक समूहहरूमा सामेल हुनुहोस्। अरूको सेवाले एक्लोपनको प्रभावलाई कम गर्छ"),
    REC_CONT_WORSHIP("Continue regular worship and ethical living", "नियमित पूजा र नैतिक जीवन जारी राख्नुहोस्"),
    REC_ELEMENT_AIR("Engage in social activities and intellectual pursuits.", "सामाजिक गतिविधि र बौद्धिक कार्यहरूमा संलग्न हुनुहोस्।"),
    REC_ELEMENT_EARTH("Focus on practical matters and material progress.", "व्यावहारिक मामिला र भौतिक प्रगतिमा ध्यान दिनुहोस्।"),
    REC_ELEMENT_FIRE("Take bold action and express yourself confidently.", "साहसी कदम चाल्नुहोस् र आत्मविश्वासका साथ आफूलाई व्यक्त गर्नुहोस्।"),
    REC_ELEMENT_WATER("Trust your intuition and honor your emotions.", "आफ्नो अन्तर्ज्ञानमा विश्वास गर्नुहोस् र आफ्ना भावनाहरूको सम्मान गर्नुहोस्।"),
    REC_EMERGENCY_SAVINGS("Build emergency savings for unexpected expenses", "अप्रत्यक्षित खर्चका लागि आपतकालीन बचत बनाउनुहोस्"),
    REC_EMOTIONAL_SUPPORT("Seek emotional support networks", "भावनात्मक समर्थन नेटवर्कहरू खोज्नुहोस्"),
    REC_EXPLORE_OTHER_YOGAS("Explore other yogas present in your horoscope", "आफ्नो जन्मकुण्डलीमा रहेका अन्य योगहरू अन्वेषण गर्नुहोस्"),
    REC_FINANCIAL_PLAN("Consider financial planning consultation", "वित्तीय योजना परामर्श विचार गर्नुहोस्"),
    REC_GAND_KNOTS("Gandanta placements indicate karmic knots requiring spiritual work", "गण्डान्त स्थितिहरूले आध्यात्मिक कार्य आवश्यक पर्ने कार्मिक गाँठोहरू संकेत गर्दछ"),
    REC_GAND_MOON_ATTN("Moon in Gandanta requires special attention - Gandanta Shanti recommended", "गण्डान्तमा रहेको चन्द्रमालाई विशेष ध्यान चाहिन्छ - गण्डान्त शान्ति सिफारिस गरिएको"),
    REC_GAND_MOON_GROUND("Practice meditation and emotional grounding regularly", "नियमित रूपमा ध्यान र भावनात्मक स्थिरताको अभ्यास गर्नुहोस्"),
    REC_JUPITER("Expand your horizons through education, travel, or spiritual practices.", "शिक्षा, यात्रा वा आध्यात्मिक अभ्यासहरूको माध्यमबाट आफ्नो क्षितिज विस्तार गर्नुहोस्।"),
    REC_KETU("Practice detachment and focus on spiritual development.", "वैराग्यको अभ्यास गर्नुहोस् र आध्यात्मिक विकासमा ध्यान दिनुहोस्।"),
    REC_MAINTAIN_FAMILY("Actively maintain family relationships", "सक्रिय रूपमा पारिवारिक सम्बन्धहरू कायम राख्नुहोस्"),
    REC_MARS("Channel your energy into physical activities and competitive pursuits.", "आफ्नो ऊर्जालाई शारीरिक गतिविधि र प्रतिस्पर्धात्मक प्रयासहरूमा प्रयोग गर्नुहोस्।"),
    REC_MB_CAREFUL("Be especially careful during Dasha/Antardasha of affected planets", "प्रभावित ग्रहहरूको दशा/अन्तर्दशामा विशेष सावधान रहनुहोस्"),
    REC_MB_SPECIFIC("Perform specific planetary remedies for planets in exact Mrityu Bhaga", "सही मृत्यु भागमा रहेका ग्रहहरूको लागि विशिष्ट ग्रह उपचार गर्नुहोस्"),
    REC_MEDITATION_MIND("Meditation and mindfulness practices highly recommended", "ध्यान र माइन्डफुलनेस अभ्यासहरू अत्यधिक सिफारिस गरिन्छ"),
    REC_MERCURY("Focus on learning, communication, and intellectual growth.", "सिकाइ, सञ्चार र बौद्धिक वृद्धिमा ध्यान दिनुहोस्।"),
    REC_MOON("Prioritize emotional well-being and nurturing relationships.", "भावनात्मक कल्याण र पोषणपूर्ण सम्बन्धहरूलाई प्राथमिकता दिनुहोस्।"),
    REC_MOON_DEBILITATED("Moon debilitated - strengthen through charity and worship", "चन्द्रमा कमजोर छ - दान र पूजा मार्फत बलियो बनाउनुहोस्"),
    REC_MOON_WORSHIP("Regular Moon worship is essential for emotional balance", "भावनात्मक सन्तुलनको लागि नियमित चन्द्र पूजा आवश्यक छ"),
    REC_NEW_MOON_CARE("Be extra careful during New Moon periods", "औंसीको समयमा अतिरिक्त सावधानी अपनाउनुहोस्"),
    REC_NO_CRITICAL("No critical sensitive degree placements - general spiritual practices sufficient", "कुनै गम्भीर संवेदनशील डिग्री स्थिति छैन - सामान्य आध्यात्मिक अभ्यासहरू पर्याप्त छन्"),
    REC_NURTURE_RELATIONS("Prioritize relationship nurturing during Moon periods", "चन्द्रमाको अवधिमा सम्बन्ध सुधारलाई प्राथमिकता दिनुहोस्"),
    REC_PLANETARY_REMEDIES("Planetary remedies can enhance positive influences", "ग्रह सम्बन्धी उपायहरूले सकारात्मक प्रभावहरूलाई बढाउन सक्छन्"),
    REC_RAHU("Explore unconventional paths while staying grounded.", "जमिनमा रहँदै अपरम्परागत मार्गहरू अन्वेषण गर्नुहोस्।"),
    REC_SATURN("Embrace discipline, hard work, and long-term planning.", "अनुशासन, कडा परिश्रम र दीर्घकालीन योजनालाई अँगाल्नुहोस्।"),
    REC_SHUKLA_PAKSHA("Shukla Paksha (waxing Moon) is better for important activities", "महत्त्वपूर्ण कार्यका लागि शुक्ल पक्ष (बढ्दो चन्द्रमा) उत्तम हुन्छ"),
    REC_STABLE_INCOME("Seek stable income sources", "स्थिर आय स्रोतहरू खोज्नुहोस्"),
    REC_STRENGTHEN_BENEFICS("Focus on strengthening the natural benefics in your chart", "आफ्नो कुण्डलीमा प्राकृतिक शुभ ग्रहहरूलाई बलियो बनाउनमा ध्यान दिनुहोस्"),
    REC_SUN("Engage in activities that build confidence and leadership skills.", "आत्मविश्वास र नेतृत्व कौशल विकास गर्ने गतिविधिहरूमा संलग्न हुनुहोस्।"),
    REC_VENUS("Cultivate beauty, art, and harmonious relationships.", "सौन्दर्य, कला र सामञ्जस्यपूर्ण सम्बन्धहरू विकास गर्नुहोस्।"),
    REGENERATIVE_CAPACITY("Regenerative Capacity", "पुनर्जनन क्षमता"),
    RELATIONSHIP_APPROACH("Relationship Approach", "सम्बन्ध दृष्टिकोण"),
    RELATIONSHIP_ENEMY("Inimical", "शत्रुतापूर्ण"),
    RELATIONSHIP_FRIEND("Friendly", "मैत्रीपूर्ण"),
    RELATIONSHIP_NEUTRAL("Neutral", "तटस्थ"),
    RELATIONSHIP_OUTLOOK("Relationship Outlook", "सम्बन्ध दृष्टिकोण"),
    RELATIONSHIP_SAME("Intensified", "तीव्र"),
    RELATIONSHIP_STYLE("Relationship Style", "सम्बन्ध शैली"),
    RELATION_ENEMY("Enemy", "शत्रु"),
    RELATION_FRIEND("Friend", "मित्र"),
    RELATION_MUTUAL_ENEMIES("Mutual Enemies", "पारस्परिक शत्रु"),
    RELATION_MUTUAL_FRIENDS("Mutual Friends", "पारस्परिक मित्र"),
    RELATION_NEUTRAL("Neutral", "तटस्थ"),
    RELATION_ONE_FRIENDLY("One Friendly", "एक मैत्रीपूर्ण"),
    RELATION_ONE_INIMICAL("One Inimical", "एक शत्रुतापूर्ण"),
    RELIGIOUS_INCLINATION("Religious Inclination", "धार्मिक झुकाव"),
    REL_ADVICE("Relationship Advice", "सम्बन्ध सल्लाह"),
    REL_CHALLENGES_TITLE("Relationship Challenges", "सम्बन्ध चुनौतीहरू"),
    REL_QUAL_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    REL_QUAL_DIFFICULT("Difficult", "कठिन"),
    REL_QUAL_EXCELLENT("Excellent", "उत्कृष्ट"),
    REL_QUAL_GOOD("Good", "राम्रो"),
    REL_QUAL_NEUTRAL("Neutral", "तटस्थ"),
    REL_SCORE("Relationship Strength Score", "सम्बन्ध शक्ति स्कोर"),
    REL_SUMMARY("Relationship Summary", "सम्बन्ध सारांश"),
    REL_TIMELINE_TITLE("Relationship Timeline", "सम्बन्ध समयरेखा"),
    REMAINING_PERIOD_MONTHS("%s months remaining", "%s महिना बाँकी"),
    REMAINING_PERIOD_YEARS("%s years, %s months remaining", "%s वर्ष, %s महिना बाँकी"),
    REM_CHANDRA_SHANTI("Perform Chandra Shanti puja or Kemadruma Nivarana puja", "चन्द्र शान्ति पूजा वा केमद्रुम निवारण पूजा गर्नुहोस्"),
    REM_CHANDRA_YANTRA("Worship Chandra Yantra daily with sandalwood paste and white flowers", "चन्दन र सेतो फूलका साथ दैनिक चन्द्र यन्त्रको पूजा गर्नुहोस्"),
    REM_DONATE_WHITE("Donate white items (rice, milk, white cloth) on Mondays", "सोमबार सेतो वस्तुहरू (चामल, दूध, सेतो कपडा) दान गर्नुहोस्"),
    REM_DURATION_43("Continue for at least 43 days", "कम्तिमा ४३ दिनसम्म जारी राख्नुहोस्"),
    REM_DURATION_LONG("Long-term practice recommended", "दीर्घकालीन अभ्यास सिफारिस गरिएको"),
    REM_EFF_HIGH("High impact remedy", "उच्च प्रभाव पार्ने उपाय"),
    REM_EFF_MOD("Moderate impact remedy", "मध्यम प्रभाव पार्ने उपाय"),
    REM_EFF_ROOT("Addresses root karmic cause", "मूल कार्मिक कारणलाई सम्बोधन गर्दछ"),
    REM_FAST_MONDAY("Observe Monday fasts consuming only milk and white foods", "सोमबार केवल दूध र सेतो खाना खाएर व्रत बस्नुहोस्"),
    REM_FREQ_WEEKLY("Weekly or as specified", "साप्ताहिक वा तोकिए अनुसार"),
    REM_HOUSE_CHARITY("Perform charity for %s house remedy", "%s भावको उपायका लागि दान गर्नुहोस्"),
    REM_HOUSE_PEACE("Avoid conflicts and maintain peace", "द्वन्द्वबाट बच्नुहोस् र शान्ति कायम राख्नुहोस्"),
    REM_JUP_BRAHMIN("Feed Brahmins and seek their blessings", "ब्राह्मणहरूलाई भोजन गराउनुहोस् र आशीर्वाद लिनुहोस्"),
    REM_JUP_DONATE("Donate yellow items on Thursdays", "बिहीबार पहेंला वस्तुहरू दान गर्नुहोस्"),
    REM_JUP_PEEPAL("Offer water at Peepal tree roots", "पीपलको फेदमा जल चढाउनुहोस्"),
    REM_JUP_TILAK("Apply saffron tilak on forehead", "निधारमा केशरी तिलक लगाउनुहोस्"),
    REM_KETU_CLOTHES("Wear two-toned (black and white) clothes", "दुई रङका (कालो र सेतो) लुगा लगाउनुहोस्"),
    REM_KETU_DOGS("Keep a dog as pet or feed stray dogs", "कुकुर पाल्नुहोस् वा सडकका कुकुरहरूलाई खुवाउनुहोस्"),
    REM_KETU_DONATE("Donate blanket to poor on Tuesdays", "मंगलबार गरिबलाई कम्बल दान गर्नुहोस्"),
    REM_KETU_SESAME("Offer sesame seeds at temple", "मन्दिरमा तिल चढाउनुहोस्"),
    REM_MANTRA_SOM("Chant ''Om Som Somaya Namah'' or ''Om Chandraya Namah'' 108 times daily", "दैनिक १०८ पटक ''ॐ सों सोमाय नमः'' वा ''ॐ चन्द्राय नमः'' जप गर्नुहोस्"),
    REM_MARS_DEER("Keep deer skin at home", "घरमा मृगको छाला राख्नुहोस्"),
    REM_MARS_DONATE("Donate red items on Tuesdays", "मंगलबार राता वस्तुहरू दान गर्नुहोस्"),
    REM_MARS_FEED("Feed jaggery/wheat to monkeys on Tuesdays", "मंगलबार बाँदरहरूलाई सख्खर/गहुँ खुवाउनुहोस्"),
    REM_MARS_HANUMAN("Recite Hanuman Chalisa daily", "दैनिक हनुमान चालीसा पाठ गर्नुहोस्"),
    REM_MEDITATION("Practice meditation and pranayama for mental peace", "मानसिक शान्तिको लागि ध्यान र प्राणायाम अभ्यास गर्नुहोस्"),
    REM_MERC_BURY("Bury green bottle with honey in deserted place", "निर्जन ठाउँमा महसहितको हरियो बोतल गाड्नुहोस्"),
    REM_MERC_DONATE("Donate green vegetables on Wednesdays", "बुधबार हरिया तरकारीहरू दान गर्नुहोस्"),
    REM_MERC_FEED("Feed green grass to cows", "गाईलाई हरियो घाँस खुवाउनुहोस्"),
    REM_MERC_PARROT("Keep a parrot or help parrots", "सुगा पाल्नुहोस् वा सुगाहरूलाई मद्दत गर्नुहोस्"),
    REM_MOON_GLASS("Keep drinking water in silver glass", "चाँदीको गिलासमा खानेपानी राख्नुहोस्"),
    REM_MOON_MOTHER("Serve your mother and elderly women", "आफ्नो आमा र वृद्ध महिलाहरूको सेवा गर्नुहोस्"),
    REM_MOON_SHIVA("Offer milk to Shiva Lingam on Mondays", "सोमबार शिवलिङ्गमा दूध चढाउनुहोस्"),
    REM_MOON_SILVER("Keep silver items and wear pearl", "चाँदीका वस्तुहरू राख्नुहोस् र मोती लगाउनुहोस्"),
    REM_MOON_WORSHIP("Continue regular Moon worship on Mondays for emotional wellbeing", "भावनात्मक कल्याणको लागि सोमबार नियमित चन्द्र पूजा जारी राख्नुहोस्"),
    REM_MOTHER_RELATION("Maintain good relationship with mother, serve elderly women, avoid isolation", "आमासँग राम्रो सम्बन्ध राख्नुहोस्, वृद्ध महिलाहरूको सेवा गर्नुहोस्, एक्लोपनबाट बच्नुहोस्"),
    REM_RAHU_BARLEY("Keep barley under your pillow and feed fish with it next morning", "सिरानीमुनि जौ राख्नुहोस् र अर्को बिहान माछालाई खुवाउनुहोस्"),
    REM_RAHU_COCONUT("Float coconut in running water", "बगिरहेको पानीमा नरिवल बगाउनुहोस्"),
    REM_RAHU_DOGS("Feed dogs regularly", "कुकुरहरूलाई नियमित खुवाउनुहोस्"),
    REM_RAHU_DONATE("Donate radish and blue/black items", "मुला र नीलो/कालो वस्तुहरू दान गर्नुहोस्"),
    REM_SAT_DONATE("Donate black items on Saturdays", "शनिबार काला वस्तुहरू दान गर्नुहोस्"),
    REM_SAT_FEED("Feed crows with sweet bread", "कागलाई गुलियो रोटी खुवाउनुहोस्"),
    REM_SAT_OIL("Offer mustard oil to Shani idol", "शनिदेवलाई तोरीको तेल चढाउनुहोस्"),
    REM_SAT_SERVE("Serve elderly and disabled persons", "वृद्ध र अपाङ्गहरूको सेवा गर्नुहोस्"),
    REM_SUN_FEED("Feed wheat and jaggery to cows on Sundays", "आइतबार गाईलाई गहुँ र सख्खर खुवाउनुहोस्"),
    REM_SUN_RUBY("Wear Ruby ring on ring finger (if suitable)", "उपयुक्त भएमा अनामिकामा माणिकको औंठी लगाउनुहोस्"),
    REM_SUN_SILVER("Keep a solid silver square piece", "चाँदीको ठोस वर्गाकार टुक्रा राख्नुहोस्"),
    REM_SUN_WATER("Offer water to Sun at sunrise with copper vessel", "सूर्योदयमा तामाको भाँडोबाट सूर्यलाई जल अर्पण गर्नुहोस्"),
    REM_VENUS_DONATE("Donate white items on Fridays", "शुक्रबार सेता वस्तुहरू दान गर्नुहोस्"),
    REM_VENUS_FEED("Feed white cows with wheat and sugar", "सेता गाईलाई गहुँ र चिनी खुवाउनुहोस्"),
    REM_VENUS_SILVER("Keep silver in your pocket", "आफ्नो खल्तीमा चाँदी राख्नुहोस्"),
    REM_VENUS_WOMEN("Respect and help women", "महिलाहरूको सम्मान र मद्दत गर्नुहोस्"),
    REM_WEAR_PEARL("Wear natural Pearl (Moti) in silver on Monday after proper energization", "उचित ऊर्जा प्रदान गरेपछि सोमबार चाँदीमा प्राकृतिक मोती धारण गर्नुहोस्"),
    RESEARCH_ABILITY("Research Ability", "अनुसन्धान क्षमता"),
    RESPONSE_SUBMITTED("Response submitted", "प्रतिक्रिया पेश गरियो"),
    RESULT_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    RESULT_FAVORABLE("Favorable", "अनुकूल"),
    RESULT_MIXED("Mixed", "मिश्रित"),
    RESULT_NEUTRAL("Neutral", "तटस्थ"),
    RESULT_PRIMARY("Primary Indication", "प्राथमिक संकेत"),
    RESULT_SECONDARY("Secondary Influences", "द्वितीयक प्रभावहरू"),
    RESULT_STRENGTH("Indication Strength", "संकेत बल"),
    RESULT_TITLE("Ashtamangala Reading", "अष्टमंगल पठन"),
    RESULT_VERY_CHALLENGING("Very Challenging", "अत्यन्त चुनौतीपूर्ण"),
    RESULT_VERY_FAVORABLE("Very Favorable", "अत्यन्त अनुकूल"),
    RETROGRADE_APPROACH("Unusual Approach", "असामान्य दृष्टिकोण"),
    RETROGRADE_DELAY(" %s's retrograde motion delays manifestation.", " %s को वक्री गतिले नतिजा ढिलो गराउँछ।"),
    RETROGRADE_INTERNAL("Internal Processing", "आन्तरिक प्रशोधन"),
    RETROGRADE_PAST_LIFE("Past Life Karma", "पूर्व जीवन कर्म"),
    RETROGRADE_RELIEF(" %s's retrograde provides some relief from challenges.", " %s को वक्रीले चुनौतीहरूबाट केही राहत दिन्छ।"),
    RETROGRADE_TITLE("Retrograde Planet Effects", "वक्री ग्रह प्रभावहरू"),
    RETRO_ALWAYS_RETROGRADE("Perpetual Retrograde", "सदा वक्री"),
    RETRO_DIRECT("Direct", "मार्गी"),
    RETRO_RETROGRADE("Retrograde", "वक्री"),
    RETRO_STATIONARY_DIRECT("Stationary Direct", "स्थिर मार्गी"),
    RETRO_STATIONARY_RETRO("Stationary Retrograde", "स्थिर वक्री"),
    RISK_TOLERANCE("Risk Tolerance", "जोखिम सहनशीलता"),
    ROBUST_AREAS("Robust Health Areas", "बलियो स्वास्थ्य क्षेत्रहरू"),
    ROMANTIC_NATURE("Romantic Nature", "रोमान्टिक स्वभाव"),
    RUDRAKSHA_DESC("Wear %d mukhi Rudraksha to balance %s energy. Deity: %s.", "%s ऊर्जा सन्तुलन गर्न %d मुखी रुद्राक्ष लगाउनुहोस्। देवता: %s।"),
    RUDRA_BENEFIT_ANYONE("Can be worn by anyone regardless of Lagna", "लग्नको वास्ता नगरी जो कोहीले पनि लगाउन सक्छ"),
    RUDRA_BENEFIT_BALANCE("Balances %s's energy", "%s को ऊर्जा सन्तुलन गर्दछ"),
    RUDRA_BENEFIT_NATURAL("Natural remedy with no side effects", "कुनै साइड इफेक्ट नभएको प्राकृतिक उपाय"),
    RUDRA_BENEFIT_PROTECT("Provides spiritual protection", "आध्यात्मिक सुरक्षा प्रदान गर्दछ"),
    RUDRA_CAUTION_AUTH("Ensure authenticity - buy from certified dealers", "प्रामाणिकता सुनिश्चित गर्नुहोस् - प्रमाणित व्यापारीहरूबाट किन्नुहोस्"),
    RUDRA_CAUTION_CLEAN("Clean regularly with water", "नियमित रूपमा पानीले सफा गर्नुहोस्"),
    RUDRA_CAUTION_EVENTS("Avoid wearing during cremation or birth events", "दाहसंस्कार वा जन्म कार्यक्रमहरूमा नलगाउनुहोस्"),
    RUDRA_CAUTION_SLEEP("Remove during sleep if uncomfortable", "असहज भएमा सुत्दा हटाउनुहोस्"),
    RUDRA_DESC("Sacred Rudraksha bead associated with %s and blessed by %s.", "%s सँग सम्बन्धित र %s द्वारा आशीर्वाद प्राप्त पवित्र रुद्राक्ष मनका।"),
    RUDRA_DURATION("Continuous wear. Remove during impure activities.", "निरन्तर लगाउनुहोस्। अशुद्ध गतिविधिहरूमा हटाउनुहोस्।"),
    RUDRA_JUPITER_BENEFITS("Spiritual growth|Wisdom enhancement|Good fortune|Removes sins", "आध्यात्मिक वृद्धि|ज्ञान वृद्धि|भाग्य|पाप हटाउँछ"),
    RUDRA_KETU_BENEFITS("Spiritual liberation|Removes fear|Protection from negativity|Removes Ketu dosha", "आध्यात्मिक मुक्ति|डर हटाउँछ|नकारात्मकताबाट सुरक्षा|केतु दोष हटाउँछ"),
    RUDRA_MARS_BENEFITS("Removes lethargy|Increases energy|Boosts courage|Overcomes fear and guilt", "आलस्य हटाउँछ|ऊर्जा बढाउँछ|साहस बढाउँछ|डर र अपराधबोध जित्छ"),
    RUDRA_MERCURY_BENEFITS("Enhances intelligence|Improves communication|Academic success|Creative abilities", "बौद्धिकता बढाउँछ|सञ्चार सुधार गर्छ|शैक्षिक सफलता|सिर्जनात्मक क्षमताहरू"),
    RUDRA_METHOD_1("1. Obtain authentic %s Rudraksha from a reputable source", "१. प्रतिष्ठित स्रोतबाट प्रमाणिक %s रुद्राक्ष प्राप्त गर्नुहोस्"),
    RUDRA_METHOD_2("2. Purify with Panchamrit (milk, curd, honey, ghee, sugar) or Gangajal", "२. पञ्चामृत (दूध, दही, मह, घिउ, चिनी) वा गंगाजलले शुद्ध गर्नुहोस्"),
    RUDRA_METHOD_3("3. Energize by chanting: 'Om Namah Shivaya' 108 times", "३. 'ओम नमः शिवाय' १०८ पटक जप गरेर ऊर्जावान बनाउनुहोस्"),
    RUDRA_METHOD_4("4. Chant %s mantra 108 times before first wearing", "४. पहिलो पटक लगाउनु अघि %s मन्त्र १०८ पटक जप गर्नुहोस्"),
    RUDRA_METHOD_5("5. Wear on silk/wool thread or cap in silver/gold", "५. रेशम/ऊनको धागोमा वा चाँदी/सुनको टोपीमा लगाउनुहोस्"),
    RUDRA_METHOD_6("6. Wear around neck or on right wrist", "६. घाँटीमा वा दायाँ नाडीमा लगाउनुहोस्"),
    RUDRA_MOON_BENEFITS("Emotional balance|Mental peace|Harmonious relationships|Cures mood disorders", "भावनात्मक सन्तुलन|मानसिक शान्ति|सुमधुर सम्बन्ध|मनोदशा विकारहरू निको पार्छ"),
    RUDRA_RAHU_BENEFITS("Removes obstacles|Protection from enemies|Success in endeavors|Removes Rahu dosha", "अवरोधहरू हटाउँछ|शत्रुहरूबाट सुरक्षा|प्रयासहरूमा सफलता|राहु दोष हटाउँछ"),
    RUDRA_SATURN_BENEFITS("Wealth and prosperity|Removes poverty|Good fortune|Success after struggle", "धन र समृद्धि|गरिबी हटाउँछ|भाग्य|संघर्ष पछि सफलता"),
    RUDRA_SUN_BENEFITS("Enhances leadership|Boosts confidence|Improves health|Success in government matters", "नेतृत्व क्षमता बढाउँछ|आत्मविश्वास बढाउँछ|स्वास्थ्य सुधार गर्छ|सरकारी मामिलामा सफलता"),
    RUDRA_TIMING("Wear on %s during Shukla Paksha, preferably on %s Hora", "शुक्ल पक्षको %s मा लगाउनुहोस्, प्राथमिकता %s होरामा"),
    RUDRA_TITLE_SUFFIX(" Rudraksha", " रुद्राक्ष"),
    RUDRA_VENUS_BENEFITS("Love and relationships|Artistic abilities|Material comforts|Removes obstacles in marriage", "प्रेम र सम्बन्ध|कलात्मक क्षमताहरू|भौतिक सुख-सुविधा|विवाहमा अवरोधहरू हटाउँछ"),
    SAFETY_LEVEL("Safety level", "सुरक्षा स्तर"),
    SAME_RAJJU("Same Rajju", "उही रज्जु"),
    SANDHI_ABOUT_DESC("Dasha Sandhi refers to the junction or transition point between two planetary periods (Dashas) in Vedic astrology.\n\nThese transition periods are considered sensitive times when:\n• The energy shifts from one planetary influence to another\n• Both planets' effects may be felt simultaneously\n• Major life changes often occur\n• Careful planning is advised\n\nThe intensity of a Sandhi depends on:\n• The nature of the transitioning planets\n• Their relationship in your chart\n• Current transits and aspects\n\nUnderstanding your Sandhi periods helps you prepare for and navigate these significant life transitions.", "दशा सन्धि भन्नाले वैदिक ज्योतिषमा दुई ग्रह दशा (समय अवधि) बीचको मिलन वा संक्रमण बिन्दुलाई जनाउँछ।\n\nयी संक्रमण अवधिहरूलाई संवेदनशील समय मानिन्छ जब:\n• ऊर्जा एक ग्रहको प्रभावबाट अर्कोमा सर्छ\n• दुबै ग्रहका प्रभावहरू एक साथ महसुस हुन सक्छ\n• अक्सर ठूला जीवन परिवर्तनहरू हुन्छन्\n• सावधानीपूर्वक योजना बनाउन सल्लाह दिइन्छ\n\nसन्धिको तीव्रता यसमा निर्भर गर्दछ:\n• संक्रमण भइरहेका ग्रहहरूको प्रकृति\n• तपाईंको कुण्डलीमा तिनीहरूको सम्बन्ध\n• वर्तमान गोचर र दृष्टिहरू\n\nतपाईंको सन्धि अवधिहरू बुझ्नाले तपाईंलाई यी महत्त्वपूर्ण जीवन संक्रमणहरूको तयारी गर्न र नेभिगेट गर्न मद्दत गर्छ।"),
    SANDHI_ABOUT_TITLE("About Dasha Sandhi", "दशा सन्धिको बारेमा"),
    SANDHI_ACTIVE("Active", "सक्रिय"),
    SANDHI_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    SANDHI_CALENDAR("Sandhi Calendar", "सन्धि क्यालेन्डर"),
    SANDHI_CAREER_EFFECTS("Career Effects", "क्यारियर प्रभावहरू"),
    SANDHI_CURRENT("Current Sandhi", "वर्तमान सन्धि"),
    SANDHI_CURRENT_ACTIVE("Currently in Sandhi Period", "वर्तमानमा सन्धि अवधिमा"),
    SANDHI_DAYS_UNTIL("Days Until Transition", "संक्रमणसम्म दिन"),
    SANDHI_ENDS("Ends:", "अन्त्य:"),
    SANDHI_FINANCIAL_TREND("Financial Trend", "आर्थिक प्रवृत्ति"),
    SANDHI_FROM_PLANET("From", "बाट"),
    SANDHI_GENERAL_GUIDANCE("General Guidance", "सामान्य मार्गदर्शन"),
    SANDHI_GUIDANCE("General Guidance", "सामान्य मार्गदर्शन"),
    SANDHI_HEALTH_CONCERNS("Health Considerations", "स्वास्थ्य विचारणाहरू"),
    SANDHI_IMPACTS("Life Area Impacts", "जीवन क्षेत्र प्रभावहरू"),
    SANDHI_INTENSITY("Intensity:", "तीव्रता:"),
    SANDHI_INTENSITY_CRITICAL("Critical", "गम्भीर"),
    SANDHI_INTENSITY_HIGH("High", "उच्च"),
    SANDHI_INTENSITY_MILD("Mild", "हल्का"),
    SANDHI_INTENSITY_MINIMAL("Minimal", "न्यूनतम"),
    SANDHI_INTENSITY_MODERATE("Moderate", "मध्यम"),
    SANDHI_KEY_DATES("Key Dates", "मुख्य मितिहरू"),
    SANDHI_NO_ACTIVE("No Active Sandhi", "कुनै सक्रिय सन्धि छैन"),
    SANDHI_NO_ACTIVE_DESC("You are not currently in a Dasha Sandhi period. Check the Upcoming tab for future transitions.", "तपाईं हाल दशा सन्धि अवधिमा हुनुहुन्न। भविष्यका परिवर्तनहरूको लागि आगामी ट्याब जाँच गर्नुहोस्।"),
    SANDHI_NO_CALENDAR("No calendar entries available.", "कुनै पात्रो प्रविष्टिहरू उपलब्ध छैनन्।"),
    SANDHI_NO_CHART_DESC("Create or select a birth chart to analyze Dasha Sandhi periods.", "दशा सन्धि अवधिहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    SANDHI_NO_UPCOMING("No upcoming Sandhi periods in the analysis window.", "विश्लेषण अवधिमा कुनै आगामी सन्धि अवधिहरू छैनन्।"),
    SANDHI_PREDICTIONS("Predictions", "भविष्यवाणीहरू"),
    SANDHI_PROGRESS("Sandhi Progress", "सन्धि प्रगति"),
    SANDHI_RECENT("Recent Sandhis", "हालैका सन्धिहरू")
}
