package com.astro.storm.core.common

enum class StringKeyPanchanga(override val en: String, override val ne: String, override val hi: String) : StringKeyInterface {

    // ============================================
    // TITHI DESCRIPTIONS
    // ============================================
    TITHI_DESC_1("Pratipada marks new beginnings. The first tithi after New Moon or Full Moon carries the energy of initiation and fresh starts. It is auspicious for beginning new ventures, laying foundations, and starting journeys.", "प्रतिपदाले नयाँ सुरुवातको संकेत गर्छ। औँसी वा पूर्णिमा पछिको पहिलो तिथिले प्रारम्भ र ताजा सुरुवातको ऊर्जा बोक्छ। यो नयाँ उद्यम सुरु गर्न, जग बसाल्न र यात्रा सुरु गर्न शुभ छ।", "प्रतिपदाले नयाँ सुरुवात के संकेत करता है। औँसी या पूर्णि में पहैि के पहिलो तिथिले प्रारम्भ और ताजा सुरुवात के ऊर्जा बोक्है। यह नयाँ उद्यम सुरु करने, जग बसाल्न और यात्रा सुरु करने शुभ है।"),
    ,
    TITHI_DESC_2("Dwitiya is ruled by Brahma, the creator. This tithi is excellent for creative endeavors, naming ceremonies, and constructive activities. It supports growth and expansion of new initiatives.", "द्वितीया ब्रह्मा, सृष्टिकर्ताद्वारा शासित छ। यो तिथि सिर्जनात्मक कार्य, नामकरण समारोह र रचनात्मक गतिविधिहरूको लागि उत्कृष्ट छ। यसले नयाँ पहलहरूको वृद्धि र विस्तारलाई समर्थन गर्छ।", "द्वितीया ब्रह् में, सृष्टिकर्ताद्वारा शासित है। यह तिथि सिर्जनात्मक कार्य, नामकरण समारोह और रचनात्मक गतिविधि के लिए उत्कृष्ट है। यह नयाँ पहल के वृद्धि और विस्तार  के समर्थन करता है।"),
    ,
    TITHI_DESC_3("Tritiya is associated with victory and success. Ruled by Gauri, it is highly auspicious for celebrations, religious ceremonies, and activities requiring divine grace and feminine energy.", "तृतीया विजय र सफलतासँग सम्बन्धित छ। गौरीद्वारा शासित, यो उत्सव, धार्मिक समारोह र दैवीय कृपा तथा नारी ऊर्जा चाहिने गतिविधिहरूको लागि धेरै शुभ छ।", "तृतीया विजय और सफलतासँग संबंधित है। गौरीद्वारा शासित, यह उत्सव, धार्मिक समारोह और दैवीय कृपा तथा नारी ऊर्जा चाहिने गतिविधि के लिए धेरै शुभ है।"),
    ,
    TITHI_DESC_4("Chaturthi is ruled by Ganesha (4th) and Yama (19th). While the 4th is for Ganesha worship, these tithis are generally considered inauspicious for beginning new work due to their 'empty' nature.", "चतुर्थी गणेश (चौथो) र यम (१९औं) द्वारा शासित छ। चौथो गणेश पूजाको लागि भए पनि, यी तिथिहरूलाई सामान्यतया तिनीहरूको 'रिक्त' प्रकृतिको कारण नयाँ काम सुरु गर्न अशुभ मानिन्छ।", "चतुर्थी गणेश (चौथो) और यम (१९औं) द्वारा शासित है। चौथो गणेश पूजा के लिए भए पनि, यी तिथि  के सामान्यतया तिनी के 'रिक्त' प्रकृति के कारण नयाँ काम सुरु करने अशुभ मानिन्है।"),
    ,
    TITHI_DESC_5("Panchami is excellent for education, learning, and wisdom pursuits. Ruled by the Nagas, it supports activities requiring knowledge, skill development, and intellectual growth.", "पञ्चमी शिक्षा, सिकाइ र ज्ञानका लागि उत्कृष्ट छ। नागहरूद्वारा शासित, यसले ज्ञान, सीप विकास र बौद्धिक वृद्धि चाहिने गतिविधिहरूलाई समर्थन गर्छ।", "पञ्चमी शिक्षा, सिकाइ और ज्ञान के लिए उत्कृष्ट है। नागद्वारा शासित, यह ज्ञान, सीप विकास और बौद्धिक वृद्धि चाहिने गतिविधि  के समर्थन करता है।"),
    ,
    TITHI_DESC_6("Shashthi is dedicated to Kartikeya (Skanda), the god of war and victory. It is favorable for activities requiring courage, medical treatments, and overcoming enemies or diseases.", "षष्ठी कार्तिकेय (स्कन्द), युद्ध र विजयका देवतालाई समर्पित छ। यो साहस, चिकित्सा उपचार, र शत्रु वा रोगहरूमाथि विजय प्राप्त गर्न चाहिने गतिविधिहरूको लागि अनुकूल छ।", "षष्ठी कार्तिकेय (स्कन्द), युद्ध और विजय के देवता  के समर्पित है। यह साहस, चिकित्सा उपचार, और शत्रु या रोगमाथि विजय प्राप्त करने चाहिने गतिविधि के लिए अनुकूल है।"),
    ,
    TITHI_DESC_7("Saptami is ruled by the Sun and brings victory and success. Excellent for travel, especially pilgrimages, vehicle purchases, and activities requiring solar energy and vitality.", "सप्तमी सूर्यद्वारा शासित छ र विजय तथा सफलता ल्याउँछ। यात्रा, विशेष गरी तीर्थयात्रा, सवारी साधन खरिद, र सौर्य ऊर्जा तथा जीवनशक्ति चाहिने गतिविधिहरूको लागि उत्कृष्ट।", "सप्तमी सूर्यद्वारा शासित है और विजय तथा सफलता लाता है। यात्रा, विशेष गरी तीर्थयात्रा, सवारी साधन खरिद, और सौर्य ऊर्जा तथा जीवनशक्ति चाहिने गतिविधि के लिए उत्कृष्ट।"),
    ,
    TITHI_DESC_8("Ashtami is sacred to Lord Shiva and considered powerful for spiritual practices. While classified as Rikta, it is excellent for worship, fasting, and tantric practices. Mixed for worldly activities.", "अष्टमी भगवान शिवका लागि पवित्र छ र आध्यात्मिक अभ्यासहरूको लागि शक्तिशाली मानिन्छ। रिक्ताको रूपमा वर्गीकृत भए पनि, यो पूजा, व्रत र तान्त्रिक अभ्यासहरूको लागि उत्कृष्ट छ। सांसारिक गतिविधिहरूको लागि मिश्रित।", "अष्टमी भगवान शिव के लिए पवित्र है और आध्यात्मिक अभ्यास के लिए शक्तिशाली मानिन्है। रिक्ता के रूप में वर्गीकृत भए पनि, यह पूजा, व्रत और तान्त्रिक अभ्यास के लिए उत्कृष्ट है। सांसारिक गतिविधि के लिए मिश्रित।"),
    ,
    TITHI_DESC_9("Navami is sacred to Durga and other fierce forms of the Divine Mother. Excellent for worship of the goddess, overcoming enemies, and activities requiring aggressive energy and protection.", "नवमी दुर्गा र दिव्य माताका अन्य उग्र रूपहरूका लागि पवित्र छ। देवीको पूजा, शत्रुहरूमाथि विजय प्राप्त गर्न, र आक्रामक ऊर्जा तथा सुरक्षा चाहिने गतिविधिहरूको लागि उत्कृष्ट।", "नवमी दुर्गा और दिव्य माता के अन्य उग्र रूप के लिए पवित्र है। देवी के पूजा, शत्रुमाथि विजय प्राप्त करने, और आक्रामक ऊर्जा तथा सुरक्षा चाहिने गतिविधि के लिए उत्कृष्ट।"),
    ,
    TITHI_DESC_10("Dashami represents victory and completion. Ruled by Yama, it is excellent for completing tasks, achieving goals, and celebrating success. Highly auspicious for important undertakings.", "दशमी विजय र पूर्णताको प्रतिनिधित्व गर्छ। यमद्वारा शासित, यो कार्यहरू पूरा गर्न, लक्ष्यहरू प्राप्त गर्न र सफलता मनाउन उत्कृष्ट छ। महत्त्वपूर्ण कार्यहरूको लागि धेरै शुभ।", "दशमी विजय और पूर्णता के प्रतिनिधित्व करता है। यमद्वारा शासित, यह कार्य पूरा करने, लक्ष्य प्राप्त करने और सफलता मनाउन उत्कृष्ट है। महत्त्वपूर्ण कार्य के लिए धेरै शुभ।"),
    ,
    TITHI_DESC_11("Ekadashi is the most spiritually significant tithi, sacred to Lord Vishnu. Fasting on this day is considered highly meritorious. Excellent for spiritual practices, but material activities should be minimized.", "एकादशी सबैभन्दा आध्यात्मिक रूपमा महत्त्वपूर्ण तिथि हो, भगवान विष्णुका लागि पवित्र। यस दिन व्रत बस्नु धेरै पुण्यदायी मानिन्छ। आध्यात्मिक अभ्यासहरूको लागि उत्कृष्ट, तर भौतिक गतिविधिहरू कम गर्नुपर्छ।", "एकादशी सभीभन्दा आध्यात्मिक रूप में महत्त्वपूर्ण तिथि है, भगवान विष्णु के लिए पवित्र। इस दिन व्रत बस्नु धेरै पुण्यदायी मानिन्है। आध्यात्मिक अभ्यास के लिए उत्कृष्ट, तर भौतिक गतिविधि कम करनेुपर्है।"),
    ,
    TITHI_DESC_12("Dwadashi follows Ekadashi and is auspicious for breaking the fast and religious ceremonies. Good for charitable activities, feeding Brahmins, and continuing spiritual practices.", "द्वादशी एकादशी पछि आउँछ र व्रत तोड्न तथा धार्मिक समारोहहरूको लागि शुभ छ। परोपकारी गतिविधिहरू, ब्राह्मणहरूलाई भोजन गराउन र आध्यात्मिक अभ्यासहरू जारी राख्न राम्रो।", "द्वादशी एकादशी पहैि आउँहै और व्रत तोड्न तथा धार्मिक समारोह के लिए शुभ है। परोपकारी गतिविधि, ब्राह्मण  के भोजन गराउन और आध्यात्मिक अभ्यास जारी राख्न राम्रो।"),
    ,
    TITHI_DESC_13("Trayodashi is favorable for Shiva worship, especially on Maha Shivaratri. Good for love-related matters, arts, and activities bringing joy. The 13th tithi is associated with auspiciousness.", "त्रयोदशी शिव पूजाको लागि अनुकूल छ, विशेष गरी महाशिवरात्रिमा। प्रेम-सम्बन्धित मामिलाहरू, कला र आनन्द ल्याउने गतिविधिहरूको लागि राम्रो। १३औं तिथि शुभतासँग सम्बन्धित छ।", "त्रयहदशी शिव पूजा के लिए अनुकूल है, विशेष गरी महाशिवरात्रि में। प्रेम-संबंधित मामिला, कला और आनन्द ल्याउने गतिविधि के लिए राम्रो। १३औं तिथि शुभतासँग संबंधित है।"),
    ,
    TITHI_DESC_14("Chaturdashi is ruled by Shiva and Kali. While powerful for tantric practices and worship, it is considered challenging for worldly activities. Excellent for spiritual disciplines and removing negative energies.", "चतुर्दशी शिव र कालीद्वारा शासित छ। तान्त्रिक अभ्यास र पूजाको लागि शक्तिशाली भए पनि, यसलाई सांसारिक गतिविधिहरूको लागि चुनौतीपूर्ण मानिन्छ। आध्यात्मिक अनुशासन र नकारात्मक ऊर्जाहरू हटाउन उत्कृष्ट।", "चतुर्दशी शिव और कालीद्वारा शासित है। तान्त्रिक अभ्यास और पूजा के लिए शक्तिशाली भए पनि, इस  के सांसारिक गतिविधि के लिए चुनौतीपूर्ण मानिन्है। आध्यात्मिक अनुशासन और नकारात्मक ऊर्जा हटाउन उत्कृष्ट।"),
    ,
    TITHI_DESC_15("Purnima (Full Moon) is the most auspicious tithi, representing completion and fullness. The Moon is at peak strength, making it excellent for all auspicious activities, spiritual practices, and celebrations.", "पूर्णिमा सबैभन्दा शुभ तिथि हो, जसले पूर्णता र पूर्णताको प्रतिनिधित्व गर्छ। चन्द्रमा चरम शक्तिमा हुन्छ, जसले यसलाई सबै शुभ गतिविधिहरू, आध्यात्मिक अभ्यासहरू र उत्सवहरूको लागि उत्कृष्ट बनाउँछ।", "पूर्णि में सभीभन्दा शुभ तिथि है, जसले पूर्णता और पूर्णता के प्रतिनिधित्व करता है। चन्द्र में चरम शक्ति में हैता है, जसले इस  के सभी शुभ गतिविधि, आध्यात्मिक अभ्यास और उत्सव के लिए उत्कृष्ट बनाउँहै।"),
    ,
    TITHI_DESC_30("Amavasya (New Moon) is sacred to the ancestors. While considered inauspicious for new beginnings, it is excellent for ancestral rites (Shraddha), Kali worship, and tantric practices. A time for introspection.", "औँसी (नयाँ चन्द्र) पुर्खाहरूका लागि पवित्र छ। नयाँ सुरुवातको लागि अशुभ मानिए पनि, यो पैतृक संस्कार (श्राद्ध), काली पूजा र तान्त्रिक अभ्यासहरूको लागि उत्कृष्ट छ। आत्म-चिन्तनको समय।", "औँसी (नयाँ चन्द्र) पुर्खा के लिए पवित्र है। नयाँ सुरुवात के लिए अशुभ मानिए पनि, यह पैतृक संस्कार (श्राद्ध), काली पूजा और तान्त्रिक अभ्यास के लिए उत्कृष्ट है। आत्म-चिन्तन के समय।"),
    ,
    TITHI_DESC_MIXED("This tithi carries mixed influences based on various planetary factors at the time.", "यो तिथिले समयका विभिन्न ग्रह कारकहरूको आधारमा मिश्रित प्रभावहरू बोक्छ।", "यह तिथिले समय के विभिन्न ग्रह कारक के आधार में मिश्रित प्रभाव बोक्है।"),

    ,

    // ============================================
    // NAKSHATRA DESCRIPTIONS
    // ============================================
    NAK_DESC_ASHWINI("Ashwini is the first nakshatra, ruled by Ketu. Those born under this star possess quick healing abilities, spontaneity, and pioneering spirit. They are energetic, courageous, and drawn to helping others. Associated with speed, initiative, and new beginnings.", "अश्विनी पहिलो नक्षत्र हो, केतुद्वारा शासित। यस नक्षत्रमा जन्मेकाहरूसँग छिटो निको पार्ने क्षमता, स्वाभाविकता र अग्रगामी भावना हुन्छ। तिनीहरू ऊर्जावान, साहसी र अरूलाई मद्दत गर्न आकर्षित हुन्छन्। गति, पहल र नयाँ सुरुवातसँग सम्बन्धित।", "अश्विनी पहिलो नक्षत्र है, केतुद्वारा शासित। इस नक्षत्र में जन्मेकासँग हैिटो नि के पार्ने क्षमता, स्वाभाविकता और अग्रगामी भावना हैता है। तिनी ऊर्जावान, साहसी और अरू  के सहायता करने आकर्षित हैता हैन्। गति, पहल और नयाँ सुरुवातसँग संबंधित।"),
    ,
    NAK_DESC_BHARANI("Bharani is ruled by Venus and represents the power of transformation. Those born here possess strong will, creativity, and the ability to bear great responsibilities. Associated with birth, death, and transformation cycles.", "भरणी शुक्रद्वारा शासित छ र रूपान्तरणको शक्ति प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग बलियो इच्छाशक्ति, सिर्जनशीलता र ठूलो जिम्मेवारी वहन गर्ने क्षमता हुन्छ। जन्म, मृत्यु र रूपान्तरण चक्रहरूसँग सम्बन्धित।", "भरणी शुक्रद्वारा शासित है और रूपान्तरण के शक्ति प्रतिनिधित्व करता है। यहाँ जन्मेकासँग बलियह इच्हैाशक्ति, सिर्जनशीलता और ठूलो जिम्मेवारी वहन करनेे क्षमता हैता है। जन्म, मृत्यु और रूपान्तरण चक्रसँग संबंधित।"),
    ,
    NAK_DESC_KRITTIKA("Krittika is ruled by the Sun and represents purifying fire. Those born here possess sharp intellect, determination, and the ability to cut through illusions. They are often leaders with strong principles and purifying influence.", "कृत्तिका सूर्यद्वारा शासित छ र शुद्धिकरण गर्ने आगोको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग तीक्ष्ण बुद्धि, दृढ संकल्प र भ्रमहरू चिर्ने क्षमता हुन्छ। तिनीहरू प्रायः बलियो सिद्धान्त र शुद्धिकरण प्रभाव भएका नेताहरू हुन्।", "कृत्ति के सूर्यद्वारा शासित है और शुद्धिकरण करनेे आगो के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग तीक्ष्ण बुद्धि, दृढ संकल्प और भ्रम चिर्ने क्षमता हैता है। तिनी प्रायः बलियह सिद्धान्त और शुद्धिकरण प्रभाव हुए नेता हैं।"),
    ,
    NAK_DESC_ROHINI("Rohini is the most fertile nakshatra, ruled by the Moon. Those born here possess beauty, creativity, and material abundance. They are charming, artistic, and have strong desires. The Moon is exalted in this nakshatra.", "रोहिणी सबैभन्दा उर्वर नक्षत्र हो, चन्द्रमाद्वारा शासित। यहाँ जन्मेकाहरूसँग सौन्दर्य, सिर्जनशीलता र भौतिक प्रचुरता हुन्छ। तिनीहरू आकर्षक, कलात्मक र बलियो इच्छाहरू भएका हुन्छन्। चन्द्रमा यस नक्षत्रमा उच्च हुन्छ।", "रोहिणी सभीभन्दा उर्वर नक्षत्र है, चन्द्रमाद्वारा शासित। यहाँ जन्मेकासँग सौन्दर्य, सिर्जनशीलता और भौतिक प्रचुरता हैता है। तिनी आकर्षक, कलात्मक और बलियह इच्हैा हुए हैता हैन्। चन्द्र में इस नक्षत्र में उच्च हैता है।"),
    ,
    NAK_DESC_MRIGASHIRA("Mrigashira is ruled by Mars and represents the searching nature. Those born here are curious, gentle, and always seeking. They possess artistic sensibilities and are drawn to exploration and research.", "मृगशिरा मंगलद्वारा शासित छ र खोजी गर्ने प्रकृतिको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू जिज्ञासु, कोमल र सधैं खोजी गरिरहने हुन्छन्। तिनीहरूसँग कलात्मक संवेदनशीलता हुन्छ र अन्वेषण तथा अनुसन्धानप्रति आकर्षित हुन्छन्।", "मृगशिरा मंगलद्वारा शासित है और खोजी करनेे प्रकृति के प्रतिनिधित्व करता है। यहाँ जन्मेका जिज्ञासु, कोमल और सधैं खोजी गरिरहने हैता हैन्। तिनीसँग कलात्मक संवेदनशीलता हैता है और अन्वेषण तथा अनुसन्धानप्रति आकर्षित हैता हैन्।"),
    ,
    NAK_DESC_ARDRA("Ardra is ruled by Rahu and represents transformation through storms. Those born here experience intense emotions and transformative life events. They possess sharp intellect and the ability to destroy old patterns for renewal.", "आर्द्रा राहुद्वारा शासित छ र आँधीबेहरी मार्फत रूपान्तरणको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूले तीव्र भावनाहरू र परिवर्तनकारी जीवन घटनाहरू अनुभव गर्छन्। तिनीहरूसँग तीक्ष्ण बुद्धि र नवीकरणका लागि पुराना ढाँचाहरू नष्ट गर्ने क्षमता हुन्छ।", "आर्द्रा राहुद्वारा शासित है और आँधीबेहरी मार्फत रूपान्तरण के प्रतिनिधित्व करता है। यहाँ जन्मेकाले तीव्र भावना और परिवर्तनकारी जीवन घटना अनुभव करता हैन्। तिनीसँग तीक्ष्ण बुद्धि और नवीकरण के लिए पुराना ढाँचा नष्ट करनेे क्षमता हैता है।"),
    ,
    NAK_DESC_PUNARVASU("Punarvasu is ruled by Jupiter and represents renewal and return to light. Those born here possess optimism, philosophical nature, and the ability to bounce back from difficulties. Associated with safety, home, and nurturing.", "पुनर्वसु बृहस्पतिद्वारा शासित छ र नवीकरण तथा प्रकाशमा फिर्तीको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग आशावाद, दार्शनिक स्वभाव र कठिनाइहरूबाट उम्किने क्षमता हुन्छ। सुरक्षा, घर र पोषणसँग सम्बन्धित।", "पुनर्वसु बृहस्पतिद्वारा शासित है और नवीकरण तथा प्रकाश में फिर्ती के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग आशावाद, दार्शनिक स्वभाव और कठिनाइबाट उम्किने क्षमता हैता है। सुरक्षा, घर और पोषणसँग संबंधित।"),
    ,
    NAK_DESC_PUSHYA("Pushya is considered the most auspicious nakshatra for most activities, ruled by Saturn. Those born here are nurturing, wise, and spiritually inclined. They possess the ability to nourish and support others' growth.", "पुष्यलाई अधिकांश गतिविधिहरूको लागि सबैभन्दा शुभ नक्षत्र मानिन्छ, शनिद्वारा शासित। यहाँ जन्मेकाहरू पोषण गर्ने, बुद्धिमान र आध्यात्मिक झुकाव भएका हुन्छन्। तिनीहरूसँग अरूको वृद्धिलाई पोषण र समर्थन गर्ने क्षमता हुन्छ।", "पुष्य  के अधिकांश गतिविधि के लिए सभीभन्दा शुभ नक्षत्र मानिन्है, शनिद्वारा शासित। यहाँ जन्मेका पोषण करनेे, बुद्धिमान और आध्यात्मिक झुकाव हुए हैता हैन्। तिनीसँग अरू के वृद्धि  के पोषण और समर्थन करनेे क्षमता हैता है।"),
    ,
    NAK_DESC_ASHLESHA("Ashlesha is ruled by Mercury and represents serpentine wisdom. Those born here possess deep intuition, hypnotic abilities, and kundalini energy. They can be secretive and possess transformative mystical powers.", "आश्लेषा बुधद्वारा शासित छ र सर्प ज्ञानको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग गहिरो अन्तर्ज्ञान, सम्मोहक क्षमता र कुण्डलिनी ऊर्जा हुन्छ। तिनीहरू गोप्य हुन सक्छन् र परिवर्तनकारी रहस्यमय शक्तिहरू हुन्छन्।", "आश्लेषा बुधद्वारा शासित है और सर्प ज्ञान के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग गहिरो अन्तर्ज्ञान, सम्मोहक क्षमता और कुण्डलिनी ऊर्जा हैता है। तिनी गोप्य हुन सक्हैं और परिवर्तनकारी रहस्यमय शक्ति हैता हैन्।"),
    ,
    NAK_DESC_MAGHA("Magha is ruled by Ketu and represents ancestral power and royal heritage. Those born here possess natural authority, connection to lineage, and leadership qualities. They honor traditions and carry ancestral blessings.", "मघा केतुद्वारा शासित छ र पैतृक शक्ति तथा शाही सम्पदाको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग प्राकृतिक अधिकार, वंशसँगको सम्बन्ध र नेतृत्व गुणहरू हुन्छन्। तिनीहरू परम्पराहरूको सम्मान गर्छन् र पैतृक आशीर्वाद बोक्छन्।", "मघा केतुद्वारा शासित है और पैतृक शक्ति तथा शाही सम्पदा के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग प्राकृतिक अधिकार, वंशसँग के संबंध और नेतृत्व गुण हैता हैन्। तिनी परम्परा के सम्मान करता हैन् और पैतृक आशीर्वाद बोक्हैं।"),
    ,
    NAK_DESC_PURVA_PHALGUNI("Purva Phalguni is ruled by Venus and represents creative pleasure and luxury. Those born here enjoy life's pleasures, are artistic, and possess natural charm. Associated with love, creativity, and enjoyment.", "पूर्वा फाल्गुनी शुक्रद्वारा शासित छ र रचनात्मक आनन्द तथा विलासिताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू जीवनका सुखहरूको आनन्द लिन्छन्, कलात्मक हुन्छन् र प्राकृतिक आकर्षण हुन्छन्। प्रेम, सिर्जनशीलता र रमाइलोसँग सम्बन्धित।", "पूर्वा फाल्गुनी शुक्रद्वारा शासित है और रचनात्मक आनन्द तथा विलासिता के प्रतिनिधित्व करता है। यहाँ जन्मेका जीवन के सुख के आनन्द लिन्हैं, कलात्मक हैता हैन् और प्राकृतिक आकर्षण हैता हैन्। प्रेम, सिर्जनशीलता और रमाइलोसँग संबंधित।"),
    ,
    NAK_DESC_UTTARA_PHALGUNI("Uttara Phalguni is ruled by the Sun and represents lasting prosperity. Those born here are generous, friendly, and establish lasting partnerships. They excel in leadership and creating stable foundations.", "उत्तरा फाल्गुनी सूर्यद्वारा शासित छ र स्थायी समृद्धिको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू उदार, मिलनसार हुन्छन् र स्थायी साझेदारीहरू स्थापना गर्छन्। तिनीहरू नेतृत्व र स्थिर जग निर्माणमा उत्कृष्ट हुन्छन्।", "उत्तरा फाल्गुनी सूर्यद्वारा शासित है और स्थायी समृद्धि के प्रतिनिधित्व करता है। यहाँ जन्मेका उदार, मिलनसार हैता हैन् और स्थायी साझेदारी स्थापना करता हैन्। तिनी नेतृत्व और स्थिर जग निर्माण में उत्कृष्ट हैता हैन्।"),
    ,
    NAK_DESC_HASTA("Hasta is ruled by the Moon and represents skill and dexterity. Those born here are clever, resourceful, and possess healing hands. They excel in crafts, arts, and activities requiring manual dexterity.", "हस्त चन्द्रमाद्वारा शासित छ र सीप तथा निपुणताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू चलाख, स्रोतसाधन सम्पन्न हुन्छन् र निको पार्ने हातहरू हुन्छन्। तिनीहरू हस्तकला, कला र म्यानुअल निपुणता चाहिने गतिविधिहरूमा उत्कृष्ट हुन्छन्।", "हस्त चन्द्रमाद्वारा शासित है और सीप तथा निपुणता के प्रतिनिधित्व करता है। यहाँ जन्मेका चलाख, स्रोतसाधन सम्पन्न हैता हैन् और नि के पार्ने हात हैता हैन्। तिनी हस्तकला, कला और म्यानुअल निपुणता चाहिने गतिविधि में उत्कृष्ट हैता हैन्।"),
    ,
    NAK_DESC_CHITRA("Chitra is ruled by Mars and represents brilliant creativity. Those born here possess artistic talent, attention to detail, and the ability to create beautiful things. Associated with architecture, design, and craftsmanship.", "चित्रा मंगलद्वारा शासित छ र उत्कृष्ट सिर्जनशीलताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग कलात्मक प्रतिभा, विवरणमा ध्यान र सुन्दर चीजहरू सिर्जना गर्ने क्षमता हुन्छ। वास्तुकला, डिजाइन र शिल्पकलासँग सम्बन्धित।", "चित्रा मंगलद्वारा शासित है और उत्कृष्ट सिर्जनशीलता के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग कलात्मक प्रतिभा, विवरण में ध्यान और सुन्दर चीज सिर्जना करनेे क्षमता हैता है। वास्तुकला, डिजाइन और शिल्पकलासँग संबंधित।"),
    ,
    NAK_DESC_SWATI("Swati is ruled by Rahu and represents independence and flexibility. Those born here are adaptable, diplomatic, and value freedom. Like the wind, they can navigate various situations with grace.", "स्वाति राहुद्वारा शासित छ र स्वतन्त्रता तथा लचिलोपनको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू अनुकूलनशील, कूटनीतिक हुन्छन् र स्वतन्त्रताको कदर गर्छन्। हावा जस्तै, तिनीहरू विभिन्न परिस्थितिहरूमा ग्रेसका साथ नेभिगेट गर्न सक्छन्।", "स्वाति राहुद्वारा शासित है और स्वतन्त्रता तथा लचिलोपन के प्रतिनिधित्व करता है। यहाँ जन्मेका अनुकूलनशील, कूटनीतिक हैता हैन् और स्वतन्त्रता के कदर करता हैन्। हावा जस्तै, तिनी विभिन्न परिस्थिति में ग्रेस के साथ नेभिगेट करने सक्हैं।"),
    ,
    NAK_DESC_VISHAKHA("Vishakha is ruled by Jupiter and represents determined pursuit of goals. Those born here possess single-pointed focus, ambition, and the ability to achieve their objectives. Associated with transformation and success.", "विशाखा बृहस्पतिद्वारा शासित छ र लक्ष्यहरूको दृढ खोजको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग एकाग्र ध्यान, महत्त्वाकांक्षा र आफ्ना उद्देश्यहरू प्राप्त गर्ने क्षमता हुन्छ। रूपान्तरण र सफलतासँग सम्बन्धित।", "विशाखा बृहस्पतिद्वारा शासित है और लक्ष्य के दृढ खोज के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग एकाग्र ध्यान, महत्त्वाकांक्षा और आफ्ना उद्देश्य प्राप्त करनेे क्षमता हैता है। रूपान्तरण और सफलतासँग संबंधित।"),
    ,
    NAK_DESC_ANURADHA("Anuradha is ruled by Saturn and represents devotion and friendship. Those born here are loyal, cooperative, and succeed in foreign lands. They possess the ability to create harmony and meaningful connections.", "अनुराधा शनिद्वारा शासित छ र भक्ति तथा मित्रताको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू वफादार, सहयोगी हुन्छन् र विदेशी भूमिमा सफल हुन्छन्। तिनीहरूसँग सद्भाव र अर्थपूर्ण सम्बन्धहरू सिर्जना गर्ने क्षमता हुन्छ।", "अनुराधा शनिद्वारा शासित है और भक्ति तथा मित्रता के प्रतिनिधित्व करता है। यहाँ जन्मेका वफादार, सहयहगी हैता हैन् और विदेशी भूमि में सफल हैता हैन्। तिनीसँग सद्भाव और अर्थपूर्ण संबंध सिर्जना करनेे क्षमता हैता है।"),
    ,
    NAK_DESC_JYESHTHA("Jyeshtha is ruled by Mercury and represents seniority and protection. Those born here possess leadership qualities, protective nature, and may face karmic challenges. They often rise to positions of authority and responsibility.", "ज्येष्ठा बुधद्वारा शासित छ र वरिष्ठता तथा सुरक्षाको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग नेतृत्व गुणहरू, सुरक्षात्मक स्वभाव हुन्छ र कर्मिक चुनौतीहरूको सामना गर्न सक्छन्। तिनीहरू प्रायः अधिकार र जिम्मेवारीको पदमा पुग्छन्।", "ज्येष्ठा बुधद्वारा शासित है और वरिष्ठता तथा सुरक्षा के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग नेतृत्व गुण, सुरक्षात्मक स्वभाव हैता है और कर्मिक चुनौती के सामना करने सक्हैं। तिनी प्रायः अधिकार और जिम्मेवारी के पद में पुग्हैं।"),
    ,
    NAK_DESC_MULA("Mula is ruled by Ketu and represents getting to the root of things. Those born here experience transformative life events that lead to spiritual awakening. Associated with investigation, research, and uprooting the old.", "मूल केतुद्वारा शासित छ र कुराको जडसम्म पुग्ने प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूले परिवर्तनकारी जीवन घटनाहरू अनुभव गर्छन् जसले आध्यात्मिक जागरणतिर लैजान्छ। अनुसन्धान, खोज र पुरानो उखेल्नेसँग सम्बन्धित।", "मूल केतुद्वारा शासित है और कुरा के जडसम्म पुग्ने प्रतिनिधित्व करता है। यहाँ जन्मेकाले परिवर्तनकारी जीवन घटना अनुभव करता हैन् जसले आध्यात्मिक जागरणतिर लैजान्है। अनुसन्धान, खोज और पुरानो उखेल्नेसँग संबंधित।"),
    ,
    NAK_DESC_PURVA_ASHADHA("Purva Ashadha is ruled by Venus and represents invincible victory. Those born here possess charisma, philosophical nature, and the ability to influence others. They are optimistic and believe in ultimate success.", "पूर्वाषाढा शुक्रद्वारा शासित छ र अजय विजयको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग क्यािज्मा, दार्शनिक स्वभाव र अरूलाई प्रभाव पार्ने क्षमता हुन्छ। तिनीहरू आशावादी हुन्छन् र अन्तिम सफलतामा विश्वास गर्छन्।", "पूर्वाषाढा शुक्रद्वारा शासित है और अजय विजय के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग क्यािज् में, दार्शनिक स्वभाव और अरू  के प्रभाव पार्ने क्षमता हैता है। तिनी आशावादी हैता हैन् और अन्तिम सफलता में विश्वास करता हैन्।"),
    ,
    NAK_DESC_UTTARA_ASHADHA("Uttara Ashadha is ruled by the Sun and represents final victory. Those born here achieve lasting success through righteousness and perseverance. They are principled, responsible, and earn respect through merit.", "उत्तराषाढा सूर्यद्वारा शासित छ र अन्तिम विजयको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूले धार्मिकता र लगनशीलता मार्फत स्थायी सफलता प्राप्त गर्छन्। तिनीहरू सिद्धान्तवादी, जिम्मेवार हुन्छन् र योग्यता मार्फत सम्मान कमाउँछन्।", "उत्तराषाढा सूर्यद्वारा शासित है और अन्तिम विजय के प्रतिनिधित्व करता है। यहाँ जन्मेकाले धार्मिकता और लगनशीलता मार्फत स्थायी सफलता प्राप्त करता हैन्। तिनी सिद्धान्तवादी, जिम्मेवार हैता हैन् और यहग्यता मार्फत सम्मान कमाउँहैं।"),
    ,
    NAK_DESC_SHRAVANA("Shravana is ruled by the Moon and represents learning through listening. Those born here are wise, knowledgeable, and possess excellent communication skills. Associated with preservation of knowledge and teaching.", "श्रवण चन्द्रमाद्वारा शासित छ र सुनेर सिक्ने प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरू बुद्धिमान, ज्ञानी हुन्छन् र उत्कृष्ट सञ्चार सीपहरू हुन्छन्। ज्ञानको संरक्षण र शिक्षणसँग सम्बन्धित।", "श्रवण चन्द्रमाद्वारा शासित है और सुनेर सिक्ने प्रतिनिधित्व करता है। यहाँ जन्मेका बुद्धिमान, ज्ञानी हैता हैन् और उत्कृष्ट सञ्चार सीप हैता हैन्। ज्ञान के संरक्षण और शिक्षणसँग संबंधित।"),
    ,
    NAK_DESC_DHANISHTHA("Dhanishtha is ruled by Mars and represents wealth and musical talent. Those born here possess rhythm, prosperity consciousness, and adaptability. Associated with fame, wealth, and artistic expression.", "धनिष्ठा मंगलद्वारा शासित छ र धन तथा सांगीतिक प्रतिभाको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग लय, समृद्धि चेतना र अनुकूलनशीलता हुन्छ। प्रसिद्धि, धन र कलात्मक अभिव्यक्तिसँग सम्बन्धित।", "धनिष्ठा मंगलद्वारा शासित है और धन तथा सांगीतिक प्रतिभा के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग लय, समृद्धि चेतना और अनुकूलनशीलता हैता है। प्रसिद्धि, धन और कलात्मक अभिव्यक्तिसँग संबंधित।"),
    ,
    NAK_DESC_SHATABHISHA("Shatabhisha is ruled by Rahu and represents healing and veiling. Those born here possess healing abilities, secretive nature, and interest in mysteries. Associated with alternative healing and unconventional approaches.", "शतभिषा राहुद्वारा शासित छ र निको पार्ने तथा लुकाउने प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग निको पार्ने क्षमता, गोप्य स्वभाव र रहस्यहरूमा रुचि हुन्छ। वैकल्पिक उपचार र अपरम्परागत दृष्टिकोणहरूसँग सम्बन्धित।", "शतभिषा राहुद्वारा शासित है और नि के पार्ने तथा लुकाउने प्रतिनिधित्व करता है। यहाँ जन्मेकासँग नि के पार्ने क्षमता, गोप्य स्वभाव और रहस्य में रुचि हैता है। वैकल्पिक उपचार और अपरम्परागत दृष्टिकोणसँग संबंधित।"),
    ,
    NAK_DESC_PURVA_BHADRAPADA("Purva Bhadrapada is ruled by Jupiter and represents spiritual fire. Those born here possess intensity, occult interests, and transformative abilities. Associated with purification through spiritual heat and sacrifice.", "पूर्वा भाद्रपद बृहस्पतिद्वारा शासित छ र आध्यात्मिक अग्निको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग तीव्रता, तान्त्रिक रुचि र परिवर्तनकारी क्षमताहरू हुन्छन्। आध्यात्मिक ताप र त्याग मार्फत शुद्धिकरणसँग सम्बन्धित।", "पूर्वा भाद्रपद बृहस्पतिद्वारा शासित है और आध्यात्मिक अग्नि के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग तीव्रता, तान्त्रिक रुचि और परिवर्तनकारी क्षमता हैता हैन्। आध्यात्मिक ताप और त्याग मार्फत शुद्धिकरणसँग संबंधित।"),
    ,
    NAK_DESC_UTTARA_BHADRAPADA("Uttara Bhadrapada is ruled by Saturn and represents spiritual depth. Those born here possess wisdom, self-control, and compassionate nature. Associated with enlightenment, renunciation, and spiritual attainment.", "उत्तरा भाद्रपद शनिद्वारा शासित छ र आध्यात्मिक गहिराइको प्रतिनिधित्व गर्छ। यहाँ जन्मेकाहरूसँग ज्ञान, आत्म-नियन्त्रण र दयालु स्वभाव हुन्छ। ज्ञानोदय, वैराग्य र आध्यात्मिक प्राप्तिसँग सम्बन्धित।", "उत्तरा भाद्रपद शनिद्वारा शासित है और आध्यात्मिक गहिराइ के प्रतिनिधित्व करता है। यहाँ जन्मेकासँग ज्ञान, आत्म-नियन्त्रण और दयालु स्वभाव हैता है। ज्ञानोदय, वैराग्य और आध्यात्मिक प्राप्तिसँग संबंधित।"),
    ,
    NAK_DESC_REVATI("Revati is the final nakshatra, ruled by Mercury. Those born here are nurturing, wealthy, and possess safe travel. Associated with protection, guidance, and completion of cycles. Represents the journey's end and new beginnings.", "रेवती अन्तिम नक्षत्र हो, बुधद्वारा शासित। यहाँ जन्मेकाहरू पोषण गर्ने, धनी हुन्छन् र सुरक्षित यात्रा गर्छन्। सुरक्षा, मार्गदर्शन र चक्रहरूको पूर्णतासँग सम्बन्धित। यात्राको अन्त्य र नयाँ सुरुवातको प्रतिनिधित्व गर्छ।", "रेवती अन्तिम नक्षत्र है, बुधद्वारा शासित। यहाँ जन्मेका पोषण करनेे, धनी हैता हैन् और सुरक्षित यात्रा करता हैन्। सुरक्षा, मार्गदर्शन और चक्र के पूर्णतासँग संबंधित। यात्रा के अन्त्य और नयाँ सुरुवात के प्रतिनिधित्व करता है।"),

    ,

    // ============================================
    // YOGA DESCRIPTIONS
    // ============================================
    YOGA_DESC_VISHKUMBHA("Vishkumbha yoga indicates obstacles and difficulties. Those born under this yoga may face initial struggles but develop resilience. Not favorable for beginning new ventures.", "विष्कुम्भ योगले बाधाहरू र कठिनाइहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले प्रारम्भिक संघर्षको सामना गर्न सक्छन् तर लचिलोपन विकास गर्छन्। नयाँ उद्यम सुरु गर्न अनुकूल छैन।", "विष्कुम्भ यहगले बाधा और कठिनाइ संकेत करता है। इस यहग में जन्मेकाले प्रारम्भिक संघर्ष के सामना करने सक्हैं तर लचिलोपन विकास करता हैन्। नयाँ उद्यम सुरु करने अनुकूल हैैन।"),
    ,
    YOGA_DESC_PRITI("Priti yoga brings love, affection, and pleasant relationships. Those born under this yoga are charming and attract positive connections. Excellent for romance and partnerships.", "प्रीति योगले प्रेम, स्नेह र रमाइलो सम्बन्धहरू ल्याउँछ। यस योगमा जन्मेकाहरू आकर्षक हुन्छन् र सकारात्मक सम्बन्धहरू आकर्षित गर्छन्। रोमान्स र साझेदारीको लागि उत्कृष्ट।", "प्रीति यहगले प्रेम, स्नेह और रमाइलो संबंध लाता है। इस यहग में जन्मेका आकर्षक हैता हैन् और सकारात्मक संबंध आकर्षित करता हैन्। रोमान्स और साझेदारी के लिए उत्कृष्ट।"),
    ,
    YOGA_DESC_AYUSHMAN("Ayushman yoga bestows longevity and good health. Those born under this yoga enjoy vitality and well-being. Auspicious for health-related matters and new beginnings.", "आयुष्मान योगले दीर्घायु र राम्रो स्वास्थ्य प्रदान गर्छ। यस योगमा जन्मेकाहरूले जीवनशक्ति र कल्याणको आनन्द लिन्छन्। स्वास्थ्य-सम्बन्धित मामिलाहरू र नयाँ सुरुवातको लागि शुभ।", "आयुष्मान यहगले दीर्घायु और राम्रो स्वास्थ्य प्रदान करता है। इस यहग में जन्मेकाले जीवनशक्ति और कल्याण के आनन्द लिन्हैं। स्वास्थ्य-संबंधित मामिला और नयाँ सुरुवात के लिए शुभ।"),
    ,
    YOGA_DESC_SAUBHAGYA("Saubhagya yoga brings luck and prosperity. Those born under this yoga are fortunate in material matters. Highly auspicious for wealth-related activities.", "सौभाग्य योगले भाग्य र समृद्धि ल्याउँछ। यस योगमा जन्मेकाहरू भौतिक मामिलामा भाग्यमानी हुन्छन्। धन-सम्बन्धित गतिविधिहरूको लागि धेरै शुभ।", "सौभाग्य यहगले भाग्य और समृद्धि लाता है। इस यहग में जन्मेका भौतिक मामिला में भाग्यमानी हैता हैन्। धन-संबंधित गतिविधि के लिए धेरै शुभ।"),
    ,
    YOGA_DESC_SHOBHANA("Shobhana yoga bestows beauty, grace, and splendor. Those born under this yoga possess attractive qualities. Favorable for arts, aesthetics, and public appearances.", "शोभन योगले सौन्दर्य, ग्रेस र भव्यता प्रदान गर्छ। यस योगमा जन्मेकाहरूसँग आकर्षक गुणहरू हुन्छन्। कला, सौन्दर्यशास्त्र र सार्वजनिक उपस्थितिहरूको लागि अनुकूल।", "शोभन यहगले सौन्दर्य, ग्रेस और भव्यता प्रदान करता है। इस यहग में जन्मेकासँग आकर्षक गुण हैता हैन्। कला, सौन्दर्यशास्त्र और सार्वजनिक उपस्थिति के लिए अनुकूल।"),
    ,
    YOGA_DESC_ATIGANDA("Atiganda yoga indicates significant obstacles and dangers. Those born under this yoga face karmic challenges. Avoid important activities during this period.", "अतिगण्ड योगले महत्त्वपूर्ण बाधाहरू र खतराहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले कर्मिक चुनौतीहरूको सामना गर्छन्। यस अवधिमा महत्त्वपूर्ण गतिविधिहरूबाट बच्नुहोस्।", "अतिगण्ड यहगले महत्त्वपूर्ण बाधा और खतरा संकेत करता है। इस यहग में जन्मेकाले कर्मिक चुनौती के सामना करता हैन्। इस अवधि में महत्त्वपूर्ण गतिविधिबाट बच्नुहोस्।"),
    ,
    YOGA_DESC_SUKARMA("Sukarma yoga favors righteous actions and good deeds. Those born under this yoga are inclined toward virtuous acts. Excellent for charitable activities and spiritual practices.", "सुकर्म योगले धार्मिक कार्यहरू र राम्रा कामहरूलाई पक्ष दिन्छ। यस योगमा जन्मेकाहरू सद्गुणी कार्यहरूप्रति झुकाव राख्छन्। परोपकारी गतिविधिहरू र आध्यात्मिक अभ्यासहरूको लागि उत्कृष्ट।", "सुकर्म यहगले धार्मिक कार्य और राम्रा काम  के पक्ष देता है। इस यहग में जन्मेका सद्गुणी कार्यप्रति झुकाव राख्हैं। परोपकारी गतिविधि और आध्यात्मिक अभ्यास के लिए उत्कृष्ट।"),
    ,
    YOGA_DESC_DHRITI("Dhriti yoga bestows determination and stability. Those born under this yoga possess mental strength and perseverance. Good for activities requiring patience and commitment.", "धृति योगले दृढ संकल्प र स्थिरता प्रदान गर्छ। यस योगमा जन्मेकाहरूसँग मानसिक शक्ति र लगनशीलता हुन्छ। धैर्य र प्रतिबद्धता चाहिने गतिविधिहरूको लागि राम्रो।", "धृति यहगले दृढ संकल्प और स्थिरता प्रदान करता है। इस यहग में जन्मेकासँग मानसिक शक्ति और लगनशीलता हैता है। धैर्य और प्रतिबद्धता चाहिने गतिविधि के लिए राम्रो।"),
    ,
    YOGA_DESC_SHULA("Shula yoga indicates sharp experiences and potential conflicts. Those born under this yoga may face sudden challenges. Caution advised in risky activities.", "शूल योगले तीक्ष्ण अनुभवहरू र सम्भावित द्वन्द्वहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले अचानक चुनौतीहरूको सामना गर्न सक्छन्। जोखिमपूर्ण गतिविधिहरूमा सावधानी अपनाउन सल्लाह दिइन्छ।", "शूल यहगले तीक्ष्ण अनुभव और सम्भावित द्वन्द्व संकेत करता है। इस यहग में जन्मेकाले अचानक चुनौती के सामना करने सक्हैं। जोखिमपूर्ण गतिविधि में सावधानी अपनाउन सल्लाह दिइन्है।"),
    ,
    YOGA_DESC_GANDA("Ganda yoga brings obstacles and difficulties. Those born under this yoga develop problem-solving abilities through challenges. Not ideal for new beginnings.", "गण्ड योगले बाधाहरू र कठिनाइहरू ल्याउँछ। यस योगमा जन्मेकाहरूले चुनौतीहरू मार्फत समस्या समाधान गर्ने क्षमता विकास गर्छन्। नयाँ सुरुवातको लागि आदर्श होइन।", "गण्ड यहगले बाधा और कठिनाइ लाता है। इस यहग में जन्मेकाले चुनौती मार्फत समस्या समाधान करनेे क्षमता विकास करता हैन्। नयाँ सुरुवात के लिए आदर्श हैइन।"),
    ,
    YOGA_DESC_VRIDDHI("Vriddhi yoga promotes growth and expansion in all areas. Those born under this yoga experience progressive development. Excellent for investments and long-term projects.", "वृद्धि योगले सबै क्षेत्रहरूमा वृद्धि र विस्तारलाई बढावा दिन्छ। यस योगमा जन्मेकाहरूले प्रगतिशील विकास अनुभव गर्छन्। लगानी र दीर्घकालीन परियोजनाहरूको लागि उत्कृष्ट।", "वृद्धि यहगले सभी क्षेत्र में वृद्धि और विस्तार  के बढावा देता है। इस यहग में जन्मेकाले प्रगतिशील विकास अनुभव करता हैन्। लगानी और दीर्घकालीन परियहजना के लिए उत्कृष्ट।"),
    ,
    YOGA_DESC_DHRUVA("Dhruva yoga provides stability and permanence. Those born under this yoga create lasting foundations. Good for activities meant to endure, like property purchases.", "ध्रुव योगले स्थिरता र स्थायित्व प्रदान गर्छ। यस योगमा जन्मेकाहरूले स्थायी जग निर्माण गर्छन्। सम्पत्ति खरिद जस्ता टिक्नका लागि गरिने गतिविधिहरूको लागि राम्रो।", "ध्रुव यहगले स्थिरता और स्थायित्व प्रदान करता है। इस यहग में जन्मेकाले स्थायी जग निर्माण करता हैन्। सम्पत्ति खरिद जस्ता टिक्न के लिए गरिने गतिविधि के लिए राम्रो।"),
    ,
    YOGA_DESC_VYAGHATA("Vyaghata yoga indicates destruction and loss. Those born under this yoga may experience significant transformations. Avoid major decisions and beginnings.", "व्याघात योगले विनाश र हानि संकेत गर्छ। यस योगमा जन्मेकाहरूले महत्त्वपूर्ण रूपान्तरणहरू अनुभव गर्न सक्छन्। ठूला निर्णयहरू र सुरुवातहरूबाट बच्नुहोस्।", "व्याघात यहगले विनाश और हानि संकेत करता है। इस यहग में जन्मेकाले महत्त्वपूर्ण रूपान्तरण अनुभव करने सक्हैं। ठूला निर्णय और सुरुवातबाट बच्नुहोस्।"),
    ,
    YOGA_DESC_HARSHANA("Harshana yoga brings joy and happiness. Those born under this yoga spread positivity and attract good fortune. Excellent for celebrations and social activities.", "हर्षण योगले आनन्द र खुसी ल्याउँछ। यस योगमा जन्मेकाहरूले सकारात्मकता फैलाउँछन् र सौभाग्य आकर्षित गर्छन्। उत्सवहरू र सामाजिक गतिविधिहरूको लागि उत्कृष्ट।", "हर्षण यहगले आनन्द और खुसी लाता है। इस यहग में जन्मेकाले सकारात्मकता फैलाउँहैं और सौभाग्य आकर्षित करता हैन्। उत्सव और सामाजिक गतिविधि के लिए उत्कृष्ट।"),
    ,
    YOGA_DESC_VAJRA("Vajra yoga provides strength like a thunderbolt but can be harsh. Those born under this yoga are powerful and determined. Mixed results for activities.", "वज्र योगले बज्र जस्तै शक्ति प्रदान गर्छ तर कठोर हुन सक्छ। यस योगमा जन्मेकाहरू शक्तिशाली र दृढ हुन्छन्। गतिविधिहरूको लागि मिश्रित परिणामहरू।", "वज्र यहगले बज्र जस्तै शक्ति प्रदान करता है तर कठोर हुन सक्है। इस यहग में जन्मेका शक्तिशाली और दृढ हैता हैन्। गतिविधि के लिए मिश्रित परिणाम।"),
    ,
    YOGA_DESC_SIDDHI("Siddhi yoga bestows success and accomplishment. Those born under this yoga achieve their goals. Highly auspicious for completing important tasks.", "सिद्धि योगले सफलता र उपलब्धि प्रदान गर्छ। यस योगमा जन्मेकाहरूले आफ्ना लक्ष्यहरू प्राप्त गर्छन्। महत्त्वपूर्ण कार्यहरू पूरा गर्न धेरै शुभ।", "सिद्धि यहगले सफलता और उपलब्धि प्रदान करता है। इस यहग में जन्मेकाले आफ्ना लक्ष्य प्राप्त करता हैन्। महत्त्वपूर्ण कार्य पूरा करने धेरै शुभ।"),
    ,
    YOGA_DESC_VYATIPATA("Vyatipata yoga is considered highly inauspicious. Those born under this yoga face significant karmic challenges. Avoid all important activities.", "व्यतीपात योगलाई धेरै अशुभ मानिन्छ। यस योगमा जन्मेकाहरूले महत्त्वपूर्ण कर्मिक चुनौतीहरूको सामना गर्छन्। सबै महत्त्वपूर्ण गतिविधिहरूबाट बच्नुहोस्।", "व्यतीपात यहग  के धेरै अशुभ मानिन्है। इस यहग में जन्मेकाले महत्त्वपूर्ण कर्मिक चुनौती के सामना करता हैन्। सभी महत्त्वपूर्ण गतिविधिबाट बच्नुहोस्।"),
    ,
    YOGA_DESC_VARIYAN("Variyan yoga is one of the most auspicious yogas. Those born under this yoga enjoy success and recognition. Favorable for all important undertakings.", "वरीयान योग सबैभन्दा शुभ योगहरू मध्ये एक हो। यस योगमा जन्मेकाहरूले सफलता र मान्यताको आनन्द लिन्छन्। सबै महत्त्वपूर्ण कार्यहरूको लागि अनुकूल।", "वरीयान यहग सभीभन्दा शुभ यहग मध्ये एक है। इस यहग में जन्मेकाले सफलता और मान्यता के आनन्द लिन्हैं। सभी महत्त्वपूर्ण कार्य के लिए अनुकूल।"),
    ,
    YOGA_DESC_PARIGHA("Parigha yoga indicates barriers and restrictions. Those born under this yoga develop strength through overcoming obstacles. Caution in new ventures.", "परिघ योगले अवरोधहरू र प्रतिबन्धहरू संकेत गर्छ। यस योगमा जन्मेकाहरूले बाधाहरू पार गरेर शक्ति विकास गर्छन्। नयाँ उद्यमहरूमा सावधानी।", "परिघ यहगले अवरोध और प्रतिबन्ध संकेत करता है। इस यहग में जन्मेकाले बाधा पार गरेर शक्ति विकास करता हैन्। नयाँ उद्यम में सावधानी।"),
    ,
    YOGA_DESC_SHIVA("Shiva yoga is highly auspicious and brings divine blessings. Those born under this yoga possess spiritual inclinations. Excellent for all auspicious activities.", "शिव योग धेरै शुभ छ र दैवीय आशीर्वाद ल्याउँछ। यस योगमा जन्मेकाहरूसँग आध्यात्मिक झुकाव हुन्छ। सबै शुभ गतिविधिहरूको लागि उत्कृष्ट।", "शिव यहग धेरै शुभ है और दैवीय आशीर्वाद लाता है। इस यहग में जन्मेकासँग आध्यात्मिक झुकाव हैता है। सभी शुभ गतिविधि के लिए उत्कृष्ट।"),
    ,
    YOGA_DESC_SIDDHA("Siddha yoga bestows accomplishment and success. Those born under this yoga are naturally talented. Very favorable for achieving goals.", "सिद्ध योगले उपलब्धि र सफलता प्रदान गर्छ। यस योगमा जन्मेकाहरू स्वाभाविक रूपमा प्रतिभाशाली हुन्छन्। लक्ष्यहरू प्राप्त गर्न धेरै अनुकूल।", "सिद्ध यहगले उपलब्धि और सफलता प्रदान करता है। इस यहग में जन्मेका स्वाभाविक रूप में प्रतिभाशाली हैता हैन्। लक्ष्य प्राप्त करने धेरै अनुकूल।"),
    ,
    YOGA_DESC_SADHYA("Sadhya yoga makes goals achievable with effort. Those born under this yoga succeed through determination. Good for pursuing challenging objectives.", "साध्य योगले प्रयासद्वारा लक्ष्यहरू प्राप्त गर्न योग्य बनाउँछ। यस योगमा जन्मेकाहरूले दृढता मार्फत सफलता प्राप्त गर्छन्। चुनौतीपूर्ण उद्देश्यहरू पछ्याउन राम्रो।", "साध्य यहगले प्रयासद्वारा लक्ष्य प्राप्त करने यहग्य बनाउँहै। इस यहग में जन्मेकाले दृढता मार्फत सफलता प्राप्त करता हैन्। चुनौतीपूर्ण उद्देश्य पहै्याउन राम्रो।"),
    ,
    YOGA_DESC_SHUBHA("Shubha yoga is highly auspicious for all activities. Those born under this yoga attract good fortune. Excellent for ceremonies and celebrations.", "शुभ योग सबै गतिविधिहरूको लागि धेरै शुभ छ। यस योगमा जन्मेकाहरूले सौभाग्य आकर्षित गर्छन्। समारोहहरू र उत्सवहरूको लागि उत्कृष्ट।", "शुभ यहग सभी गतिविधि के लिए धेरै शुभ है। इस यहग में जन्मेकाले सौभाग्य आकर्षित करता हैन्। समारोह और उत्सव के लिए उत्कृष्ट।"),
    ,
    YOGA_DESC_SHUKLA("Shukla yoga brings brightness and clarity. Those born under this yoga have clear minds and pure intentions. Favorable for education and spiritual practices.", "शुक्ल योगले उज्यालो र स्पष्टता ल्याउँछ। यस योगमा जन्मेकाहरूसँग स्पष्ट मन र शुद्ध मनसाय हुन्छ। शिक्षा र आध्यात्मिक अभ्यासहरूको लागि अनुकूल।", "शुक्ल यहगले उज्यालो और स्पष्टता लाता है। इस यहग में जन्मेकासँग स्पष्ट मन और शुद्ध मनसाय हैता है। शिक्षा और आध्यात्मिक अभ्यास के लिए अनुकूल।"),
    ,
    YOGA_DESC_BRAHMA("Brahma yoga bestows creative powers and wisdom. Those born under this yoga are natural creators. Excellent for beginning creative projects.", "ब्रह्म योगले सिर्जनात्मक शक्ति र ज्ञान प्रदान गर्छ। यस योगमा जन्मेकाहरू प्राकृतिक सिर्जनाकर्ता हुन्। सिर्जनात्मक परियोजनाहरू सुरु गर्न उत्कृष्ट।", "ब्रह्म यहगले सिर्जनात्मक शक्ति और ज्ञान प्रदान करता है। इस यहग में जन्मेका प्राकृतिक सिर्जनाकर्ता हैं। सिर्जनात्मक परियहजना सुरु करने उत्कृष्ट।"),
    ,
    YOGA_DESC_INDRA("Indra yoga bestows power, authority, and success. Those born under this yoga are natural leaders. Favorable for leadership and governmental matters.", "इन्द्र योगले शक्ति, अधिकार र सफलता प्रदान गर्छ। यस योगमा जन्मेकाहरू प्राकृतिक नेता हुन्। नेतृत्व र सरकारी मामिलाहरूको लागि अनुकूल।", "इन्द्र यहगले शक्ति, अधिकार और सफलता प्रदान करता है। इस यहग में जन्मेका प्राकृतिक नेता हैं। नेतृत्व और सरकारी मामिला के लिए अनुकूल।"),
    ,
    YOGA_DESC_VAIDHRITI("Vaidhriti yoga is the final yoga and indicates discord. Those born under this yoga face endings and transitions. Avoid important beginnings; good for conclusions.", "वैधृति योग अन्तिम योग हो र कलह संकेत गर्छ। यस योगमा जन्मेकाहरूले अन्त्य र संक्रमणहरूको सामना गर्छन्। महत्त्वपूर्ण सुरुवातहरूबाट बच्नुहोस्; निष्कर्षका लागि राम्रो।", "वैधृति यहग अन्तिम यहग है और कलह संकेत करता है। इस यहग में जन्मेकाले अन्त्य और संक्रमण के सामना करता हैन्। महत्त्वपूर्ण सुरुवातबाट बच्नुहोस्; निष्कर्ष के लिए राम्रो।"),

    ,

    // ============================================
    // KARANA DESCRIPTIONS
    // ============================================
    KARANA_DESC_BAVA("Bava karana is favorable for travel, beginning new ventures, and activities requiring movement. It supports progress and forward motion in all endeavors.", "बव करण यात्रा, नयाँ उद्यम सुरु गर्न, र चाल चाहिने गतिविधिहरूको लागि अनुकूल छ। यसले सबै प्रयासहरूमा प्रगति र अगाडि बढ्ने गतिलाई समर्थन गर्छ।", "बव करण यात्रा, नयाँ उद्यम सुरु करने, और चाल चाहिने गतिविधि के लिए अनुकूल है। यह सभी प्रयास में प्रगति और अगाडि बढ्ने गति  के समर्थन करता है।"),
    ,
    KARANA_DESC_BALAVA("Balava karana brings youthful energy and is good for learning, education, and activities involving young people. Favorable for new learning experiences.", "बालव करणले युवा ऊर्जा ल्याउँछ र सिकाइ, शिक्षा, र युवा मानिसहरू संलग्न गतिविधिहरूको लागि राम्रो छ। नयाँ सिकाइ अनुभवहरूको लागि अनुकूल।", "बालव करणले युवा ऊर्जा लाता है और सिकाइ, शिक्षा, और युवा मानिस संलग्न गतिविधि के लिए राम्रो है। नयाँ सिकाइ अनुभव के लिए अनुकूल।"),
    ,
    KARANA_DESC_KAULAVA("Kaulava karana is excellent for family matters, social gatherings, and community activities. It supports harmony in relationships and group endeavors.", "कौलव करण पारिवारिक मामिलाहरू, सामाजिक जमघटहरू, र सामुदायिक गतिविधिहरूको लागि उत्कृष्ट छ। यसले सम्बन्ध र सामूहिक प्रयासहरूमा सद्भावलाई समर्थन गर्छ।", "कौलव करण पारिवारिक मामिला, सामाजिक जमघट, और सामुदायिक गतिविधि के लिए उत्कृष्ट है। यह संबंध और सामूहिक प्रयास में सद्भाव  के समर्थन करता है।"),
    ,
    KARANA_DESC_TAITILA("Taitila karana is highly favorable for business, commerce, and material gain. Excellent for financial transactions and wealth-building activities.", "तैतिल करण व्यापार, वाणिज्य, र भौतिक लाभको लागि धेरै अनुकूल छ। वित्तीय कारोबार र धन-निर्माण गतिविधिहरूको लागि उत्कृष्ट।", "तैतिल करण व्यापार, वाणिज्य, और भौतिक लाभ के लिए धेरै अनुकूल है। वित्तीय कारोबार और धन-निर्माण गतिविधि के लिए उत्कृष्ट।"),
    ,
    KARANA_DESC_GARA("Gara karana is good for agriculture, construction, and activities involving the earth. Favorable for property matters and physical labor.", "गर करण कृषि, निर्माण, र पृथ्वीसँग सम्बन्धित गतिविधिहरूको लागि राम्रो छ। सम्पत्ति मामिलाहरू र शारीरिक श्रमको लागि अनुकूल।", "गर करण कृषि, निर्माण, और पृथ्वीसँग संबंधित गतिविधि के लिए राम्रो है। सम्पत्ति मामिला और शारीरिक श्रम के लिए अनुकूल।"),
    ,
    KARANA_DESC_VANIJA("Vanija karana is excellent for trade, business deals, and commercial success. Highly favorable for merchants and those in business.", "वणिज करण व्यापार, व्यापारिक सम्झौताहरू, र व्यावसायिक सफलताको लागि उत्कृष्ट छ। व्यापारीहरू र व्यवसायमा भएकाहरूका लागि धेरै अनुकूल।", "वणिज करण व्यापार, व्यापारिक सम्झौता, और व्यावसायिक सफलता के लिए उत्कृष्ट है। व्यापारी और व्यवसाय में हुए के लिए धेरै अनुकूल।"),
    ,
    KARANA_DESC_VISHTI("Vishti (Bhadra) karana is inauspicious and should be avoided for important activities. Only suitable for fierce activities or confronting enemies.", "विष्टि (भद्रा) करण अशुभ छ र महत्त्वपूर्ण गतिविधिहरूको लागि बच्नुपर्छ। उग्र गतिविधिहरू वा शत्रुहरूको सामना गर्न मात्र उपयुक्त।", "विष्टि (भद्रा) करण अशुभ है और महत्त्वपूर्ण गतिविधि के लिए बच्नुपर्है। उग्र गतिविधि या शत्रु के सामना करने मात्र उपयुक्त।"),
    ,
    KARANA_DESC_SHAKUNI("Shakuni is a fixed karana appearing only once per lunar month. It supports activities requiring cleverness and strategy but can bring mixed results.", "शकुनि एक स्थिर करण हो जुन चन्द्र महिनामा एक पटक मात्र आउँछ। यसले चलाखी र रणनीति चाहिने गतिविधिहरूलाई समर्थन गर्छ तर मिश्रित परिणामहरू ल्याउन सक्छ।", "शकुनि एक स्थिर करण है जो चन्द्र महिना में एक पटक मात्र आउँहै। यह चलाखी और रणनीति चाहिने गतिविधि  के समर्थन करता है तर मिश्रित परिणाम ल्याउन सक्है।"),
    ,
    KARANA_DESC_CHATUSHPADA("Chatushpada is a fixed karana favorable for activities involving four-legged animals and agriculture. Good for animal husbandry and farming.", "चतुष्पद एक स्थिर करण हो जुन चार खुट्टे जनावरहरू र कृषिसँग सम्बन्धित गतिविधिहरूको लागि अनुकूल छ। पशुपालन र खेतीको लागि राम्रो।", "चतुष्पद एक स्थिर करण है जो चार खुट्टे जनावर और कृषिसँग संबंधित गतिविधि के लिए अनुकूल है। पशुपालन और खेती के लिए राम्रो।"),
    ,
    KARANA_DESC_NAGA("Naga is a fixed karana associated with serpent energies. Favorable for activities involving hidden matters, underground work, and protective rituals.", "नाग सर्प ऊर्जाहरूसँग सम्बन्धित एक स्थिर करण हो। लुकेका कुरा, भूमिगत काम, र सुरक्षात्मक अनुष्ठानहरूसँग सम्बन्धित गतिविधिहरूको लागि अनुकूल।", "नाग सर्प ऊर्जासँग संबंधित एक स्थिर करण है। लुके के कुरा, भूमिगत काम, और सुरक्षात्मक अनुष्ठानसँग संबंधित गतिविधि के लिए अनुकूल।"),
    ,
    KARANA_DESC_KIMSTUGHNA("Kimstughna is a fixed karana that destroys negativity. Favorable for removing obstacles, protection rituals, and overcoming enemies.", "किंस्तुघ्न एक स्थिर करण हो जसले नकारात्मकता नष्ट गर्छ। बाधाहरू हटाउन, सुरक्षा अनुष्ठानहरू, र शत्रुहरूमाथि विजय प्राप्त गर्न अनुकूल।", "किंस्तुघ्न एक स्थिर करण है जसले नकारात्मकता नष्ट करता है। बाधा हटाउन, सुरक्षा अनुष्ठान, और शत्रुमाथि विजय प्राप्त करने अनुकूल।"),

    ,

    // ============================================
    // VARA DESCRIPTIONS & LISTS
    // ============================================
    VARA_DESC_SUNDAY("Sunday is ruled by the Sun (Surya), representing the soul, authority, and vitality. The Sun's energy brings power, leadership, and illumination. This day is sacred to Lord Vishnu and Surya Deva.", "आइतबार सूर्य (सूर्य) द्वारा शासित छ, जसले आत्मा, अधिकार र जीवनशक्तिको प्रतिनिधित्व गर्छ। सूर्यको ऊर्जाले शक्ति, नेतृत्व र प्रकाश ल्याउँछ। यो दिन भगवान विष्णु र सूर्य देवका लागि पवित्र छ।", "आइतबार सूर्य (सूर्य) द्वारा शासित है, जसले आत् में, अधिकार और जीवनशक्ति के प्रतिनिधित्व करता है। सूर्य के ऊर्जाले शक्ति, नेतृत्व और प्रकाश लाता है। यह दिन भगवान विष्णु और सूर्य देव के लिए पवित्र है।"),
    ,
    VARA_DESC_MONDAY("Monday is ruled by the Moon (Chandra), representing the mind, emotions, and nurturing. The Moon's energy brings sensitivity, intuition, and public connection. This day is sacred to Lord Shiva.", "सोमबार चन्द्रमा (चन्द्र) द्वारा शासित छ, जसले मन, भावना र पोषणको प्रतिनिधित्व गर्छ। चन्द्रमाको ऊर्जाले संवेदनशीलता, अन्तर्ज्ञान र सार्वजनिक सम्बन्ध ल्याउँछ। यो दिन भगवान शिवका लागि पवित्र छ।", "सोमबार चन्द्र में (चन्द्र) द्वारा शासित है, जसले मन, भावना और पोषण के प्रतिनिधित्व करता है। चन्द्र में के ऊर्जाले संवेदनशीलता, अन्तर्ज्ञान और सार्वजनिक संबंध लाता है। यह दिन भगवान शिव के लिए पवित्र है।"),
    ,
    VARA_DESC_TUESDAY("Tuesday is ruled by Mars (Mangal), representing courage, energy, and action. Mars brings warrior energy, determination, and physical strength. This day is sacred to Lord Hanuman and Kartikeya.", "मंगलबार मंगल (मंगल) द्वारा शासित छ, जसले साहस, ऊर्जा र कार्यको प्रतिनिधित्व गर्छ। मंगलले योद्धा ऊर्जा, दृढता र शारीरिक शक्ति ल्याउँछ। यो दिन भगवान हनुमान र कार्तिकेयका लागि पवित्र छ।", "मंगलबार मंगल (मंगल) द्वारा शासित है, जसले साहस, ऊर्जा और कार्य के प्रतिनिधित्व करता है। मंगलले यहद्धा ऊर्जा, दृढता और शारीरिक शक्ति लाता है। यह दिन भगवान हनुमान और कार्तिकेय के लिए पवित्र है।"),
    ,
    VARA_DESC_WEDNESDAY("Wednesday is ruled by Mercury (Budha), representing intellect, communication, and commerce. Mercury brings mental agility, business acumen, and learning ability. This day is sacred to Lord Vishnu.", "बुधबार बुध (बुध) द्वारा शासित छ, जसले बुद्धि, सञ्चार र वाणिज्यको प्रतिनिधित्व गर्छ। बुधले मानसिक चुस्ती, व्यापारिक कौशल र सिक्ने क्षमता ल्याउँछ। यो दिन भगवान विष्णुका लागि पवित्र छ।", "बुधबार बुध (बुध) द्वारा शासित है, जसले बुद्धि, सञ्चार और वाणिज्य के प्रतिनिधित्व करता है। बुधले मानसिक चुस्ती, व्यापारिक कौशल और सिक्ने क्षमता लाता है। यह दिन भगवान विष्णु के लिए पवित्र है।"),
    ,
    VARA_DESC_THURSDAY("Thursday is ruled by Jupiter (Guru), representing wisdom, expansion, and divine grace. Jupiter brings blessings, prosperity, and spiritual growth. This day is sacred to Lord Brihaspati and Vishnu.", "बिहीबार बृहस्पति (गुरु) द्वारा शासित छ, जसले ज्ञान, विस्तार र दैवीय कृपाको प्रतिनिधित्व गर्छ। बृहस्पतिले आशीर्वाद, समृद्धि र आध्यात्मिक वृद्धि ल्याउँछ। यो दिन भगवान बृहस्पति र विष्णुका लागि पवित्र छ।", "बिहीबार बृहस्पति (गुरु) द्वारा शासित है, जसले ज्ञान, विस्तार और दैवीय कृपा के प्रतिनिधित्व करता है। बृहस्पतिले आशीर्वाद, समृद्धि और आध्यात्मिक वृद्धि लाता है। यह दिन भगवान बृहस्पति और विष्णु के लिए पवित्र है।"),
    ,
    VARA_DESC_FRIDAY("Friday is ruled by Venus (Shukra), representing love, beauty, and pleasure. Venus brings artistic sensibility, romance, and material enjoyment. This day is sacred to Goddess Lakshmi and Santoshi Ma.", "शुक्रबार शुक्र (शुक्र) द्वारा शासित छ, जसले प्रेम, सौन्दर्य र आनन्दको प्रतिनिधित्व गर्छ। शुक्रले कलात्मक संवेदनशीलता, रोमान्स र भौतिक आनन्द ल्याउँछ। यो दिन देवी लक्ष्मी र सन्तोषी आमाका लागि पवित्र छ।", "शुक्रबार शुक्र (शुक्र) द्वारा शासित है, जसले प्रेम, सौन्दर्य और आनन्द के प्रतिनिधित्व करता है। शुक्रले कलात्मक संवेदनशीलता, रोमान्स और भौतिक आनन्द लाता है। यह दिन देवी लक्ष्मी और सन्तोषी आ में के लिए पवित्र है।"),
    ,
    VARA_DESC_SATURDAY("Saturday is ruled by Saturn (Shani), representing discipline, karma, and endurance. Saturn brings lessons, structure, and spiritual growth through challenges. This day is sacred to Lord Shani and Hanuman.", "शनिबार शनि (शनि) द्वारा शासित छ, जसले अनुशासन, कर्म र सहनशीलताको प्रतिनिधित्व गर्छ। शनिले पाठ, संरचना र चुनौतीहरू मार्फत आध्यात्मिक वृद्धि ल्याउँछ। यो दिन भगवान शनि र हनुमानका लागि पवित्र छ।", "शनिबार शनि (शनि) द्वारा शासित है, जसले अनुशासन, कर्म और सहनशीलता के प्रतिनिधित्व करता है। शनिले पाठ, संरचना और चुनौती मार्फत आध्यात्मिक वृद्धि लाता है। यह दिन भगवान शनि और हनुमान के लिए पवित्र है।"),

    ,

    // Favorable Activities
    VARA_FAV_SUNDAY("Government work, Authority matters, Health initiatives, Father-related activities, Leadership, Spiritual practices, Worship of Surya", "सरकारी काम, अधिकार मामिलाहरू, स्वास्थ्य पहलहरू, पितासँग सम्बन्धित गतिविधिहरू, नेतृत्व, आध्यात्मिक अभ्यासहरू, सूर्य पूजा", "सरकारी काम, अधिकार मामिला, स्वास्थ्य पहल, पितासँग संबंधित गतिविधि, नेतृत्व, आध्यात्मिक अभ्यास, सूर्य पूजा"),
    ,
    VARA_FAV_MONDAY("Travel, Public dealings, Emotional matters, Starting ventures, Agriculture, Dealing with women, Shiva worship", "यात्रा, सार्वजनिक व्यवहार, भावनात्मक मामिलाहरू, उद्यम सुरु गर्न, कृषि, महिलाहरूसँगको व्यवहार, शिव पूजा", "यात्रा, सार्वजनिक व्यवहार, भावनात्मक मामिला, उद्यम सुरु करने, कृषि, महिलासँग के व्यवहार, शिव पूजा"),
    ,
    VARA_FAV_TUESDAY("Property matters, Surgery, Competitive activities, Physical training, Dealing with enemies, Hanuman worship, Military activities", "सम्पत्ति मामिलाहरू, शल्यक्रिया, प्रतिस्पर्धात्मक गतिविधिहरू, शारीरिक प्रशिक्षण, शत्रुहरूसँगको व्यवहार, हनुमान पूजा, सैन्य गतिविधिहरू", "सम्पत्ति मामिला, शल्यक्रिया, प्रतिस्पर्धात्मक गतिविधि, शारीरिक प्रशिक्षण, शत्रुसँग के व्यवहार, हनुमान पूजा, सैन्य गतिविधि"),
    ,
    VARA_FAV_WEDNESDAY("Education, Communication, Business, Writing, Trade, Intellectual pursuits, Travel, Vishnu worship", "शिक्षा, सञ्चार, व्यापार, लेखन, व्यापार, बौद्धिक कार्यहरू, यात्रा, विष्णु पूजा", "शिक्षा, सञ्चार, व्यापार, लेखन, व्यापार, बौद्धिक कार्य, यात्रा, विष्णु पूजा"),
    ,
    VARA_FAV_THURSDAY("Religious ceremonies, Marriage, Education, Financial matters, Legal matters, Guru worship, Charity, Beginning important ventures", "धार्मिक समारोहहरू, विवाह, शिक्षा, वित्तीय मामिलाहरू, कानूनी मामिलाहरू, गुरु पूजा, दान, महत्त्वपूर्ण उद्यमहरू सुरु गर्न", "धार्मिक समारोह, विवाह, शिक्षा, वित्तीय मामिला, कानूनी मामिला, गुरु पूजा, दान, महत्त्वपूर्ण उद्यम सुरु करने"),
    ,
    VARA_FAV_FRIDAY("Romance, Marriage, Arts, Music, Luxury purchases, Beauty treatments, Entertainment, Lakshmi worship", "रोमान्स, विवाह, कला, संगीत, विलासी खरिदहरू, सौन्दर्य उपचार, मनोरञ्जन, लक्ष्मी पूजा", "रोमान्स, विवाह, कला, संगीत, विलासी खरिद, सौन्दर्य उपचार, मनोरञ्जन, लक्ष्मी पूजा"),
    ,
    VARA_FAV_SATURDAY("Property matters, Agriculture, Labor work, Iron/oil business, Spiritual discipline, Shani worship, Hanuman worship", "सम्पत्ति मामिलाहरू, कृषि, श्रम कार्य, फलाम/तेल व्यापार, आध्यात्मिक अनुशासन, शनि पूजा, हनुमान पूजा", "सम्पत्ति मामिला, कृषि, श्रम कार्य, फलाम/तेल व्यापार, आध्यात्मिक अनुशासन, शनि पूजा, हनुमान पूजा"),

    ,

    // Unfavorable Activities
    VARA_UNFAV_SUNDAY("Beginning journeys to the East, Starting new businesses (according to some traditions)", "पूर्वतिरको यात्रा सुरु गर्न, नयाँ व्यवसाय सुरु गर्न (केही परम्परा अनुसार)", "पूर्वतिर के यात्रा सुरु करने, नयाँ व्यवसाय सुरु करने (केही परम्परा अनुसार)"),
    ,
    VARA_UNFAV_MONDAY("Surgery, Cutting activities", "शल्यक्रिया, काट्ने गतिविधिहरू", "शल्यक्रिया, काट्ने गतिविधि"),
    ,
    VARA_UNFAV_TUESDAY("Marriage, Peaceful negotiations, Beginning gentle activities", "विवाह, शान्तिपूर्ण वार्ता, कोमल गतिविधिहरू सुरु गर्न", "विवाह, शांतिपूर्ण वार्ता, कोमल गतिविधि सुरु करने"),
    ,
    VARA_UNFAV_WEDNESDAY("Agriculture, Building construction (according to some traditions)", "कृषि, भवन निर्माण (केही परम्परा अनुसार)", "कृषि, भवन निर्माण (केही परम्परा अनुसार)"),
    ,
    VARA_UNFAV_THURSDAY("Hair cutting (for some traditions), Lending money", "कपाल काट्न (केही परम्परा अनुसार), पैसा ऋण दिन", "कपाल काट्न (केही परम्परा अनुसार), पैसा ऋण दिन"),
    ,
    VARA_UNFAV_FRIDAY("Surgery, Aggressive activities, Conflicts", "शल्यक्रिया, आक्रामक गतिविधिहरू, द्वन्द्वहरू", "शल्यक्रिया, आक्रामक गतिविधि, द्वन्द्व"),
    ,
    VARA_UNFAV_SATURDAY("New beginnings, Travel, Auspicious ceremonies, Hair cutting", "नयाँ सुरुवात, यात्रा, शुभ समारोहहरू, कपाल काट्न", "नयाँ सुरुवात, यात्रा, शुभ समारोह, कपाल काट्न"),

    ,

    // ============================================
    // TITHI DETAILS
    // ============================================
    TITHI_DEITY_AGNI("Agni (Fire God)", "अग्नि (आगोका देवता)", "अग्नि (आगो के देवता)"),
    ,
    TITHI_DEITY_BRAHMA("Brahma (Creator)", "ब्रह्मा (सृष्टिकर्ता)", "ब्रह् में (सृष्टिकर्ता)"),
    ,
    TITHI_DEITY_GAURI("Gauri (Parvati)", "गौरी (पार्वती)", "गौरी (पार्वती)"),
    ,
    TITHI_DEITY_GANESHA_YAMA("Ganesha/Yama", "गणेश/यम", "गणेश/यम"),
    ,
    TITHI_DEITY_NAGAS("Nagas (Serpent deities)", "नाग (सर्प देवता)", "नाग (सर्प देवता)"),
    ,
    TITHI_DEITY_KARTIKEYA("Kartikeya (Skanda)", "कार्तिकेय (स्कन्द)", "कार्तिकेय (स्कन्द)"),
    ,
    TITHI_DEITY_SURYA("Surya (Sun God)", "सूर्य (सूर्य देवता)", "सूर्य (सूर्य देवता)"),
    ,
    TITHI_DEITY_SHIVA_RUDRA("Shiva/Rudra", "शिव/रुद्र", "शिव/रुद्र"),
    ,
    TITHI_DEITY_DURGA("Durga (Mother Goddess)", "दुर्गा (भवानी)", "दुर्गा (भवानी)"),
    ,
    TITHI_DEITY_YAMA("Yama (God of Death)", "यम (मृत्युका देवता)", "यम (मृत्यु के देवता)"),
    ,
    TITHI_DEITY_VISHNU("Vishnu (Preserver)", "विष्णु (संरक्षक)", "विष्णु (संरक्षक)"),
    ,
    TITHI_DEITY_KAMADEVA("Kamadeva (God of Love)", "कामदेव (प्रेमका देवता)", "कामदेव (प्रेम के देवता)"),
    ,
    TITHI_DEITY_SHIVA_KALI("Shiva/Kali", "शिव/काली", "शिव/काली"),
    ,
    TITHI_DEITY_CHANDRA("Chandra (Moon God)", "चन्द्र (चन्द्र देवता)", "चन्द्र (चन्द्र देवता)"),
    ,
    TITHI_DEITY_PITRIS("Pitris (Ancestors)", "पितृ (पुर्खाहरू)", "पितृ (पुर्खा)"),

    ,

    TITHI_NATURE_NANDA("Nanda (Joyful)", "नन्दा (आनन्ददायी)", "नन्दा (आनन्ददायी)"),
    ,
    TITHI_NATURE_BHADRA("Bhadra (Auspicious)", "भद्रा (शुभ)", "भद्रा (शुभ)"),
    ,
    TITHI_NATURE_JAYA("Jaya (Victory)", "जया (विजयी)", "जया (विजयी)"),
    ,
    TITHI_NATURE_RIKTA("Rikta (Empty)", "रिक्ता (खाली)", "रिक्ता (खाली)"),
    ,
    TITHI_NATURE_PURNA("Purna (Complete)", "पूर्णा (पूर्ण)", "पूर्णा (पूर्ण)"),

    ,

    // ============================================
    // YOGA MEANINGS
    // ============================================
    YOGA_MEANING_SUPPORTING("Supporting", "सहयोगी", "सहयहगी"),
    ,
    YOGA_MEANING_LOVE("Love", "प्रेम", "प्रेम"),
    ,
    YOGA_MEANING_LONG_LIVED("Long-lived", "दीर्घायु", "दीर्घायु"),
    ,
    YOGA_MEANING_GOOD_FORTUNE("Good Fortune", "सौभाग्य", "सौभाग्य"),
    ,
    YOGA_MEANING_SPLENDOR("Splendor", "वैभव", "वैभव"),
    ,
    YOGA_MEANING_GREAT_OBSTACLE("Great Obstacle", "अतिगण्ड", "अतिगण्ड"),
    ,
    YOGA_MEANING_GOOD_DEEDS("Good Deeds", "सुकर्म", "सुकर्म"),
    ,
    YOGA_MEANING_STEADINESS("Steadiness", "धृति", "धृति"),
    ,
    YOGA_MEANING_SPEAR("Spear", "शूल", "शूल"),
    ,
    YOGA_MEANING_OBSTACLE("Obstacle", "गण्ड", "गण्ड"),
    ,
    YOGA_MEANING_GROWTH("Growth", "वृद्धि", "वृद्धि"),
    ,
    YOGA_MEANING_FIXED("Fixed", "ध्रुव", "ध्रुव"),
    ,
    YOGA_MEANING_DESTRUCTION("Destruction", "व्याघात", "व्याघात"),
    ,
    YOGA_MEANING_JOY("Joy", "हर्षण", "हर्षण"),
    ,
    YOGA_MEANING_THUNDERBOLT("Thunderbolt", "वज्र", "वज्र"),
    ,
    YOGA_MEANING_ACCOMPLISHMENT("Accomplishment", "सिद्धि", "सिद्धि"),
    ,
    YOGA_MEANING_CALAMITY("Calamity", "व्यतीपात", "व्यतीपात"),
    ,
    YOGA_MEANING_EXCELLENT("Excellent", "वरीयान", "वरीयान"),
    ,
    YOGA_MEANING_OBSTRUCTION("Obstruction", "परिघ", "परिघ"),
    ,
    YOGA_MEANING_AUSPICIOUS("Auspicious", "शुभ", "शुभ"),
    ,
    YOGA_MEANING_ACCOMPLISHED("Accomplished", "सिद्ध", "सिद्ध"),
    ,
    YOGA_MEANING_ACHIEVABLE("Achievable", "साध्य", "साध्य"),
    ,
    YOGA_MEANING_BRIGHT("Bright", "शुक्ल", "शुक्ल"),
    ,
    YOGA_MEANING_CREATOR("Creator", "ब्रह्मा", "ब्रह् में"),
    ,
    YOGA_MEANING_KING_OF_GODS("King of Gods", "इन्द्र", "इन्द्र"),
    ,
    YOGA_MEANING_DISCORD("Discord", "वैधृति", "वैधृति"),

    ,

    // ============================================
    // KARANA TYPES
    // ============================================
    KARANA_TYPE_MOVABLE("Chara (Movable)", "चर (चलायमान)", "चर (चलायमान)"),
    ,
    KARANA_TYPE_FIXED("Sthira (Fixed)", "स्थिर", "स्थिर"),
,
;
}
