package com.astro.storm.core.common

enum class StringKeyRemedy(override val en: String, override val ne: String) : StringKeyInterface {
    CHARITY_BENEFIT_BOTH("Helps both giver and receiver", "दाता र प्राप्तकर्ता दुवैलाई मद्दत गर्दछ"),
    CHARITY_BENEFIT_KARMA("Reduces negative karma associated with %s", "%s सँग सम्बन्धित नकारात्मक कर्म कम गर्दछ"),
    CHARITY_BENEFIT_MERIT("Creates positive merit (punya)", "सकारात्मक पुण्य सिर्जना गर्दछ"),
    CHARITY_BENEFIT_UNIVERSAL("No side effects - universally beneficial", "कुनै साइड इफेक्ट छैन - विश्वव्यापी रूपमा लाभदायक"),
    CHARITY_BHADRA("green moong dal, green cloth, books to students", "हरियो मुगीको दाल, हरियो कपडा, विद्यार्थीहरूलाई पुस्तक"),
    CHARITY_CAUTION_EXPECTATION("Give without expecting returns or recognition", "प्रतिफल वा मान्यताको अपेक्षा नगरी दिनुहोस्"),
    CHARITY_CAUTION_INTENTION("Donate with pure intentions and humility", "शुद्ध मनसाय र नम्रताका साथ दान गर्नुहोस्"),
    CHARITY_CAUTION_QUALITY("Quality matters more than quantity", "परिमाण भन्दा गुणस्तर महत्त्वपूर्ण छ"),
    CHARITY_CAUTION_RECIPIENT("Choose genuine recipients in need", "साँचो आवश्यकता भएका प्राप्तकर्ताहरू छान्नुहोस्"),
    CHARITY_DESC("Charitable acts to reduce %s's karmic debts and negative effects.", "%s को कार्मिक ऋण र नकारात्मक प्रभावहरू कम गर्न परोपकारी कार्यहरू।"),
    CHARITY_DURATION("Regular practice for lasting benefits. Especially important during %s's Dasha/Antardasha.", "दीर्घकालीन लाभको लागि नियमित अभ्यास। विशेष गरी %s को दशा/अन्तर्दशामा महत्त्वपूर्ण।"),
    CHARITY_HAMSA("turmeric, yellow cloth, ghee, gold to Brahmins", "बेसार, पहेँलो कपडा, घ्यू, ब्राह्मणहरूलाई सुन"),
    CHARITY_JUPITER_ITEMS("Chana dal, Yellow cloth, Turmeric, Gold, Yellow flowers, Books", "चना दाल, पहेंलो कपडा, बेसार, सुन, पहेंलो फूल, पुस्तकहरू"),
    CHARITY_JUPITER_RECIPIENTS("Teachers, priests (Brahmins), temples, religious institutions", "गुरुहरू, पुजारी (ब्राह्मण), मन्दिरहरू, धार्मिक संस्थाहरू"),
    CHARITY_JUPITER_SPECIAL("Donate to Vishnu/Jupiter temples; feed cows with chana dal", "विष्णु/बृहस्पति मन्दिरमा दान गर्नुहोस्; गाईलाई चना दाल खुवाउनुहोस्"),
    CHARITY_KETU_ITEMS("Mixed seven grains, Gray/Brown blanket, Sesame seeds, Dog food", "सतनजा (सात प्रकारका अन्न), खैरो कम्बल, तिल, कुकुरको खाना"),
    CHARITY_KETU_RECIPIENTS("Spiritual seekers, sadhus, dog shelters, Ganesha temples", "आध्यात्मिक साधक, साधु, कुकुर आश्रयस्थल, गणेश मन्दिर"),
    CHARITY_KETU_SPECIAL("Feed dogs; donate blankets to homeless; offer at Ganesha temple", "कुकुरलाई खुवाउनुहोस्; घरबारविहीनलाई कम्बल दान गर्नुहोस्; गणेश मन्दिरमा चढाउनुहोस्"),
    CHARITY_MALAVYA("white rice, white cloth, sugar, silver items to women", "सेतो चामल, सेतो कपडा, चिनी, महिलाहरूलाई चाँदीका सामान"),
    CHARITY_MARS_ITEMS("Red lentils (Masoor dal), Red cloth, Copper, Jaggery, Wheat bread", "रातो दाल (मसुरो), रातो कपडा, तामा, सख्खर, गहुँको रोटी"),
    CHARITY_MARS_RECIPIENTS("Young men, soldiers, brothers, Hanuman temples", "युवा पुरुष, सैनिक, दाजुभाइ, हनुमान मन्दिर"),
    CHARITY_MARS_SPECIAL("Donate at Hanuman temple; feed monkeys", "हनुमान मन्दिरमा दान गर्नुहोस्; बाँदरहरूलाई खुवाउनुहोस्"),
    CHARITY_MERCURY_ITEMS("Green gram (Moong dal), Green cloth, Emerald green items, Books, Writing materials", "मुगको दाल, हरियो कपडा, पन्ना रङका वस्तुहरू, पुस्तकहरू, लेखन सामग्री"),
    CHARITY_MERCURY_RECIPIENTS("Students, scholars, young children, educational institutions", "विद्यार्थी, विद्वान, साना नानीहरू, शैक्षिक संस्थाहरू"),
    CHARITY_MERCURY_SPECIAL("Donate to schools; feed birds with green gram", "विद्यालयमा दान गर्नुहोस्; चराहरूलाई मुगको दाल खुवाउनुहोस्"),
    CHARITY_METHOD("Donate the following items: %s\n\nRecipients: %s\n\n%s", "निम्न वस्तुहरू दान गर्नुहोस्: %s\n\nप्राप्तकर्ताहरू: %s\n\n%s"),
    CHARITY_MOON_ITEMS("Rice, White cloth, Silver, Milk, Curd, White flowers", "चामल, सेतो कपडा, चाँदी, दूध, दही, सेतो फूल"),
    CHARITY_MOON_RECIPIENTS("Mother figures, elderly women, pilgrims", "आमा समान व्यक्तिहरू, वृद्ध महिलाहरू, तीर्थयात्रीहरू"),
    CHARITY_MOON_SPECIAL("Donate near water bodies; offer milk to Shivling", "जलाशय नजिक दान गर्नुहोस्; शिवलिङ्गमा दूध चढाउनुहोस्"),
    CHARITY_RAHU_ITEMS("Coconut, Blue cloth, Sesame seeds, Lead, Blanket", "नरिवल, नीलो कपडा, तिल, सीसा, कम्बल"),
    CHARITY_RAHU_RECIPIENTS("Outcasts, sweepers, Durga temples", "बहिष्कृत, सफाइकर्मी, दुर्गा मन्दिर"),
    CHARITY_RAHU_SPECIAL("Donate at crossroads; offer to Durga temple", "चौबाटोमा दान गर्नुहोस्; दुर्गा मन्दिरमा चढाउनुहोस्"),
    CHARITY_RUCHAKA("red lentils, red cloth, jaggery to the needy", "रातो दाल, रातो कपडा, गरिबलाई सख्खर"),
    CHARITY_SASHA("black sesame, black cloth, iron items, oil to the poor", "कालो तिल, कालो कपडा, फलामका सामान, गरिबलाई तेल"),
    CHARITY_SATURN_ITEMS("Black gram (Urad dal), Iron, Sesame oil, Blue/Black cloth, Mustard oil", "कालो मास (उरद दाल), फलाम, तिलको तेल, नीलो/कालो कपडा, तोरीको तेल"),
    CHARITY_SATURN_RECIPIENTS("Poor and needy, servants, elderly, disabled, Shani temples", "गरिब र दुखी, सेवक, वृद्ध, अपाङ्ग, शनि मन्दिर"),
    CHARITY_SATURN_SPECIAL("Feed crows; offer mustard oil at Shani temple; serve the disabled", "कागलाई खुवाउनुहोस्; शनि मन्दिरमा तोरीको तेल चढाउनुहोस्; असहायको सेवा गर्नुहोस्"),
    CHARITY_SUN_ITEMS("Wheat, Jaggery (Gur), Copper vessel, Red/Orange cloth, Gold", "गहुँ, सख्खर (गुड), तामाको भाँडो, रातो/सुन्तला कपडा, सुन"),
    CHARITY_SUN_RECIPIENTS("Father figures, government servants, temples", "बुबा समान व्यक्तिहरू, सरकारी कर्मचारी, मन्दिरहरू"),
    CHARITY_SUN_SPECIAL("Offer water to Sun at sunrise with copper vessel", "सूर्योदयमा तामाको भाँडोबाट सूर्यलाई अर्घ्य दिनुहोस्"),
    CHARITY_TIMING("Every %s, preferably %s", "हरेक %s, प्राथमिकता %s"),
    CHARITY_TIMING_BEFORE_SUNRISE_AFTER_SUNSET("Before sunrise or after sunset", "सूर्योदय अघि वा सूर्यास्त पछि"),
    CHARITY_TIMING_BEFORE_SUNSET("Before sunset", "सूर्यास्त अघि"),
    CHARITY_TIMING_EVENING("Evening", "साँझ"),
    CHARITY_TIMING_MORNING("Morning", "बिहान"),
    CHARITY_TIMING_NIGHT("Night", "राती"),
    CHARITY_TITLE_SUFFIX(" Daan (Charity)", " दान"),
    CHARITY_VENUS_ITEMS("Rice, White cloth, Silk, Perfumes, Sweets, Ghee", "चामल, सेतो कपडा, रेशम, अत्तर, मिठाई, घिउ"),
    CHARITY_VENUS_RECIPIENTS("Young women, artists, Lakshmi temples, cow shelters", "युवतीहरू, कलाकारहरू, लक्ष्मी मन्दिर, गाई गोठ"),
    CHARITY_VENUS_SPECIAL("Donate to women's welfare; offer white flowers to Lakshmi", "महिला कल्याणमा दान गर्नुहोस्; लक्ष्मीलाई सेतो फूल चढाउनुहोस्"),
    DEITY_ADITI("Aditi", "अदिति"),
    DEITY_AGNI("Agni", "अग्नि"),
    DEITY_AHIR_BUDHNYA("Ahir Budhnya", "अहिर्बुध्न्य"),
    DEITY_AJA_EKAPAD("Aja Ekapad", "अज एकपाद"),
    DEITY_ANURADHA("Mitra (God of Friendship)", "मित्र (मित्रताका देवता)"),
    DEITY_APAS("Apas", "आप"),
    DEITY_ARDRA("Rudra (Storm God)", "रुद्र (आँधीबेहरीका देवता)"),
    DEITY_ARYAMAN("Aryaman", "अर्यमा"),
    DEITY_ASHLESHA("Nagas (Serpent Gods)", "नाग (सर्प देवता)"),
    DEITY_ASHWINI("Ashwini Kumaras (Divine Physicians)", "अश्विनी कुमार (दिव्य चिकित्सक)"),
    DEITY_ASHWINI_KUMARAS("Ashwini Kumaras", "अश्विनी कुमार"),
    DEITY_BENEFIT_CONNECT("Direct connection with planetary deity", "ग्रह देवतासँग प्रत्यक्ष सम्बन्ध"),
    DEITY_BENEFIT_GRACE("Divine grace and protection", "ईश्वरीय कृपा र सुरक्षा"),
    DEITY_BENEFIT_GROWTH("Spiritual growth and merit", "आध्यात्मिक वृद्धि र पुण्य"),
    DEITY_BENEFIT_RELIEF("Karmic relief and blessings", "कार्मिक राहत र आशीर्वाद"),
    DEITY_BHADRA("Lord Vishnu or Lord Ganesha", "भगवान विष्णु वा भगवान गणेश"),
    DEITY_BHAGA("Bhaga", "भग"),
    DEITY_BHARANI("Yama (God of Death)", "यम (मृत्युका देवता)"),
    DEITY_BRAHMA("Brahma", "ब्रह्मा"),
    DEITY_BRIHASPATI("Brihaspati", "बृहस्पति"),
    DEITY_CAUTION_DEVOTION("Worship with pure devotion and clean body/mind", "शुद्ध भक्ति र सफा शरीर/मनका साथ पूजा गर्नुहोस्"),
    DEITY_CAUTION_ETIQUETTE("Follow proper temple etiquette", "उचित मन्दिर शिष्टाचार पालना गर्नुहोस्"),
    DEITY_CAUTION_HOME("If unable to visit temple, perform home worship with image/idol", "यदि मन्दिर जान असक्षम हुनुहुन्छ भने, घरमै तस्बिर/मूर्ति राखेर पूजा गर्नुहोस्"),
    DEITY_CHITRA("Vishwakarma (Divine Architect)", "विश्वकर्मा (दिव्य वास्तुकार)"),
    DEITY_DESC("Invoke divine blessings by worshipping deities associated with %s.", "%s सँग सम्बन्धित देवी-देवताहरूको पूजा गरेर ईश्वरीय आशीर्वाद आह्वान गर्नुहोस्।"),
    DEITY_DHANISHTHA("Vasus (Eight Elemental Gods)", "वसु (आठ तत्वका देवताहरू)"),
    DEITY_DURATION("Regular weekly practice, more during %s Dasha", "नियमित साप्ताहिक अभ्यास, %s दशाको समयमा बढी"),
    DEITY_HAMSA("Lord Brihaspati or Lord Shiva", "भगवान वृहस्पति वा भगवान शिव"),
    DEITY_HASTA("Savitar (Sun God)", "सविता (सूर्य देवता)"),
    DEITY_INDRA("Indra", "इन्द्र"),
    DEITY_INDRA_AGNI("Indra-Agni", "इन्द्राग्नी"),
    DEITY_JUPITER_OFFERINGS("Yellow flowers, turmeric, chana dal, bananas", "पहेंलो फूल, बेसार, चना दाल, केरा"),
    DEITY_JUPITER_PRIM("Lord Brihaspati / Dakshinamurthy", "भगवान बृहस्पति / दक्षिणामूर्ति"),
    DEITY_JUPITER_SEC("Lord Vishnu, Lord Shiva (as Guru), Lord Dattatreya", "भगवान विष्णु, भगवान शिव (गुरु रूपमा), भगवान दत्तात्रेय"),
    DEITY_JUPITER_TEMPLES("Guru temple, Vishnu temple", "गुरु मन्दिर, विष्णु मन्दिर"),
    DEITY_JYESHTHA("Indra (King of Gods)", "इन्द्र (देवताहरूको राजा)"),
    DEITY_KALI("Kali", "काली"),
    DEITY_KETU_OFFERINGS("Mixed grains, brown/gray items, dog food for charity", "मिश्रित अन्न, खैरो वस्तुहरू, कुकुरको खाना"),
    DEITY_KETU_PRIM("Lord Ganesha", "भगवान गणेश"),
    DEITY_KETU_SEC("Chitragupta, Lord Kartikeya, Goddess Kali", "चित्रगुप्त, भगवान कार्तिकेय, देवी काली"),
    DEITY_KETU_TEMPLES("Ganesha temple, any Ketu shrine", "गणेश मन्दिर, कुनै पनि केतु पीठ"),
    DEITY_KRITTIKA("Agni (Fire God)", "अग्नि (आगोका देवता)"),
    DEITY_MAGHA("Pitris (Ancestors)", "पितृ (पुर्खाहरू)"),
    DEITY_MALAVYA("Goddess Lakshmi or Goddess Saraswati", "देवी लक्ष्मी वा देवी सरस्वती"),
    DEITY_MARS_OFFERINGS("Red flowers, red sindoor, jaggery, coconut", "रातो फूल, रातो सिन्दूर, सख्खर, नरिवल"),
    DEITY_MARS_PRIM("Lord Hanuman", "भगवान हनुमान"),
    DEITY_MARS_SEC("Lord Kartikeya (Murugan), Goddess Durga, Lord Bhairav", "भगवान कार्तिकेय, देवी दुर्गा, भगवान भैरव"),
    DEITY_MARS_TEMPLES("Hanuman temple, Mangalnath Mandir Ujjain", "हनुमान मन्दिर, मंगलनाथ मन्दिर उज्जैन"),
    DEITY_MERCURY_OFFERINGS("Green items, green gram, tulsi, flowers", "हरियो वस्तुहरू, मुगको दाल, तुलसी, फूलहरू"),
    DEITY_MERCURY_PRIM("Lord Vishnu", "भगवान विष्णु"),
    DEITY_MERCURY_SEC("Lord Krishna, Lord Buddha, Goddess Saraswati", "भगवान कृष्ण, भगवान बुद्ध, देवी सरस्वती"),
    DEITY_MERCURY_TEMPLES("Vishnu temple, any Krishna temple", "विष्णु मन्दिर, कुनै पनि कृष्ण मन्दिर"),
    DEITY_METHOD_1("1. Visit temple on %s", "१. %s मा मन्दिर जानुहोस्"),
    DEITY_METHOD_2("2. Offer: %s", "२. चढाउनुहोस्: %s"),
    DEITY_METHOD_3("3. Recite %s stotra or mantra", "३. %s स्तोत्र वा मन्त्र पाठ गर्नुहोस्"),
    DEITY_METHOD_4("4. Light lamp with ghee or appropriate oil", "४. घिउ वा उपयुक्त तेलले बत्ती बाल्नुहोस्"),
    DEITY_METHOD_5("5. Perform pradakshina (circumambulation)", "५. परिक्रमा गर्नुहोस्"),
    DEITY_METHOD_6("6. Seek blessings with pure intention", "६. शुद्ध मनसायले आशीर्वाद माग्नुहोस्"),
    DEITY_MITRA("Mitra", "मित्र"),
    DEITY_MOON_OFFERINGS("White flowers, milk, water, rice, silver items", "सेतो फूल, दूध, जल, चामल, चाँदीका वस्तुहरू"),
    DEITY_MOON_PRIM("Lord Shiva", "भगवान शिव"),
    DEITY_MOON_SEC("Goddess Parvati, Goddess Ganga, Lord Chandra", "देवी पार्वती, देवी गंगा, भगवान चन्द्र"),
    DEITY_MOON_TEMPLES("Any Shiva temple, especially Jyotirlingas", "कुनै पनि शिव मन्दिर, विशेष गरी ज्योतिर्लिङ्ग"),
    DEITY_MRIGASHIRA("Soma (Moon God)", "सोम (चन्द्र देवता)"),
    DEITY_MULA("Nirriti (Goddess of Dissolution)", "निरृति (विनाशकी देवी)"),
    DEITY_NAGAS("Nagas", "नाग"),
    DEITY_PITRIS("Pitris", "पितृ"),
    DEITY_PRIMARY("PRIMARY DEITY: %s", "प्राथमिक देवता: %s"),
    DEITY_PROCEDURE("WORSHIP PROCEDURE:", "पूजा प्रक्रिया:"),
    DEITY_PUNARVASU("Aditi (Mother of Gods)", "अदिति (देवताहरूको माता)"),
    DEITY_PURVA_ASHADHA("Apas (Water Goddess)", "आप (जल देवी)"),
    DEITY_PURVA_BHADRAPADA("Aja Ekapada (One-footed Goat)", "अज एकपाद (एक खुट्टे बाख्रा)"),
    DEITY_PURVA_PHALGUNI("Bhaga (God of Fortune)", "भग (भाग्यका देवता)"),
    DEITY_PUSHAN("Pushan", "पूषा"),
    DEITY_PUSHYA("Brihaspati (Jupiter)", "बृहस्पति (गुरु)"),
    DEITY_RAHU_OFFERINGS("Coconut, blue flowers, hessonite, sandalwood", "नरिवल, नीलो फूल, गोमेद, चन्दन"),
    DEITY_RAHU_PRIM("Goddess Durga", "देवी दुर्गा"),
    DEITY_RAHU_SEC("Lord Bhairav, Goddess Kali, Naga Devatas", "भगवान भैरव, देवी काली, नाग देवताहरू"),
    DEITY_RAHU_TEMPLES("Durga temple, Naga temples, Rahu shrine", "दुर्गा मन्दिर, नाग मन्दिर, राहु पीठ"),
    DEITY_REVATI("Pushan (Nourisher/Protector)", "पूषा (पोषक/संरक्षक)"),
    DEITY_ROHINI("Brahma (Creator)", "ब्रह्मा (सृष्टिकर्ता)"),
    DEITY_RUCHAKA("Lord Hanuman or Lord Kartikeya", "भगवान हनुमान वा भगवान कार्तिकेय"),
    DEITY_RUDRA("Rudra", "रुद्र"),
    DEITY_SASHA("Lord Shani or Lord Hanuman", "भगवान शनि वा भगवान हनुमान"),
    DEITY_SATURN_OFFERINGS("Black sesame, mustard oil, iron items, blue flowers", "कालो तिल, तोरीको तेल, फलामका वस्तुहरू, नीलो फूल"),
    DEITY_SATURN_PRIM("Lord Shani Dev", "भगवान शनि देव"),
    DEITY_SATURN_SEC("Lord Hanuman, Lord Bhairav, Goddess Kali", "भगवान हनुमान, भगवान भैरव, देवी काली"),
    DEITY_SATURN_TEMPLES("Shani temple, Shani Shingnapur, any Shani shrine", "शनि मन्दिर, शनि शिंगणापुर, कुनै पनि शनि पीठ"),
    DEITY_SAVITAR("Savitar", "सविता"),
    DEITY_SECONDARY("SECONDARY DEITIES: %s", "द्वितीयक देवताहरू: %s"),
    DEITY_SHATABHISHA("Varuna (God of Waters)", "वरुण (जलका देवता)"),
    DEITY_SHRAVANA("Vishnu (Preserver)", "विष्णु (संरक्षक)"),
    DEITY_SOMA("Soma/Chandra", "सोम/चन्द्र"),
    DEITY_SUN_OFFERINGS("Red flowers, wheat, jaggery, copper items", "रातो फूल, गहुँ, सख्खर, तामाका वस्तुहरू"),
    DEITY_SUN_PRIM("Lord Surya Narayan", "भगवान सूर्य नारायण"),
    DEITY_SUN_SEC("Lord Vishnu, Lord Ram, Lord Shiva (as Mrityunjaya)", "भगवान विष्णु, भगवान राम, भगवान शिव"),
    DEITY_SUN_TEMPLES("Surya Mandir, Konark Sun Temple, any Sun temple", "सूर्य मन्दिर, कोणार्क सूर्य मन्दिर, कुनै पनि सूर्य मन्दिर"),
    DEITY_SWATI("Vayu (Wind God)", "वायु (हावाका देवता)"),
    DEITY_TEMPLES("RECOMMENDED TEMPLES: %s", "सिफारिस गरिएका मन्दिरहरू: %s"),
    DEITY_TIMING("Every %s, especially during %s Hora", "हरेक %s, विशेष गरी %s होरामा"),
    DEITY_TITLE_SUFFIX(" Deity Worship", " देवी-देवता पूजा"),
    DEITY_UTTARA_ASHADHA("Vishwadevas (Universal Gods)", "विश्वेदेव (ब्रह्माण्डका देवताहरू)"),
    DEITY_UTTARA_BHADRAPADA("Ahir Budhnya (Serpent of the Deep)", "अहिर्बुध्न्य (गहिराईको सर्प)"),
    DEITY_UTTARA_PHALGUNI("Aryaman (God of Contracts)", "अर्यमन (सम्झौताका देवता)"),
    DEITY_VARUNA("Varuna", "वरुण"),
    DEITY_VASUS("Vasus", "वसु"),
    DEITY_VAYU("Vayu", "वायु"),
    DEITY_VENUS_OFFERINGS("White flowers, rice, sweets, silk, perfumes", "सेतो फूल, चामल, मिठाई, रेशम, अत्तर"),
    DEITY_VENUS_PRIM("Goddess Lakshmi", "देवी लक्ष्मी"),
    DEITY_VENUS_SEC("Goddess Saraswati, Lord Krishna, Goddess Annapurna", "देवी सरस्वती, भगवान कृष्ण, देवी अन्नपूर्णा"),
    DEITY_VENUS_TEMPLES("Lakshmi temple, any Devi temple", "लक्ष्मी मन्दिर, कुनै पनि देवी मन्दिर"),
    DEITY_VISHAKHA("Indra-Agni", "इन्द्र-अग्नि"),
    DEITY_VISHNU("Vishnu", "विष्णु"),
    DEITY_VISHVADEVAS("Vishvadevas", "विश्वेदेव"),
    DEITY_VISHWAKARMA("Vishwakarma", "विश्वकर्मा"),
    DEITY_YAMA("Yama", "यम"),
    FASTING_BENEFIT_PLEASE("Pleases %s", "%s लाई खुशी पार्छ"),
    FASTING_BENEFIT_PURIFY("Purifies body, mind, and spirit", "शरीर, मन, र आत्मा शुद्ध गर्दछ"),
    FASTING_BENEFIT_WILL("Increases willpower and discipline", "इच्छाशक्ति र अनुशासन बढाउँछ"),
    FASTING_CAUTION_BREAK("Break fast gently with light food", "हल्का खानाले बिस्तारै व्रत तोड्नुहोस्"),
    FASTING_CAUTION_HEALTH("Consult a doctor if you have diabetes, low BP, or other health conditions", "यदि तपाईंलाई मधुमेह, कम रक्तचाप, वा अन्य स्वास्थ्य समस्या छ भने डाक्टरसँग परामर्श गर्नुहोस्"),
    FASTING_CAUTION_HYDRATE("Stay hydrated with water", "पानी पिएर हाइड्रेटेड रहनुहोस्"),
    FASTING_CAUTION_PREG("Pregnant women should avoid strict fasting", "गर्भवती महिलाहरूले कडा व्रत नगर्नुहोस्"),
    FASTING_DAY("Fasting Day", "उपवास दिन"),
    FASTING_DESC("Fasting to appease %s and reduce its negative influences.", "%s लाई शान्त पार्न र यसको नकारात्मक प्रभावहरू कम गर्न व्रत।"),
    FASTING_DURATION("Minimum 11-21 weeks, ideally 40 days continuously", "कम्तिमा ११-२१ हप्ता, आदर्श रूपमा ४० दिन लगातार"),
    FASTING_GUIDELINES("Fasting Guidelines", "उपवास दिशानिर्देशहरू"),
    FASTING_JUPITER_FOOD("Consume chana dal, yellow foods, avoid salt", "चना दाल, पहेंलो खाना सेवन गर्नुहोस्, नुन नखानुहोस्"),
    FASTING_KETU_FOOD("Observe complete fast or consume only milk", "पूर्ण व्रत बस्नुहोस् वा केवल दूध सेवन गर्नुहोस्"),
    FASTING_MARS_FOOD("Consume red lentils, avoid salt", "रातो दाल सेवन गर्नुहोस्, नुन नखानुहोस्"),
    FASTING_MERCURY_FOOD("Consume green gram, green vegetables", "मुगको दाल, हरियो तरकारी सेवन गर्नुहोस्"),
    FASTING_METHOD("Observe fast from sunrise to sunset on %s. %s. Break fast after seeing the relevant symbol (Moon for Monday, etc.).", "%s मा सूर्योदय देखि सूर्यास्त सम्म व्रत बस्नुहोस्। %s। सम्बन्धित प्रतीक (सोमबारको लागि चन्द्रमा, आदि) देखेपछि व्रत तोड्नुहोस्।"),
    FASTING_MOON_FOOD("Consume rice, milk, white foods", "चामल, दूध, सेतो खाना सेवन गर्नुहोस्"),
    FASTING_RAHU_FOOD("Observe complete fast or consume only fruits", "पूर्ण व्रत बस्नुहोस् वा केवल फलफूल सेवन गर्नुहोस्"),
    FASTING_REMEDIES("Fasting Remedies", "उपवास उपचारहरू"),
    FASTING_SATURN_FOOD("Consume black gram, sesame, avoid salt", "कालो मास, तिल सेवन गर्नुहोस्, नुन नखानुहोस्"),
    FASTING_SUN_FOOD("Consume wheat-based items, jaggery, and avoid salt", "गहुँका परिकार, सख्खर सेवन गर्नुहोस् र नुन नखानुहोस्"),
    FASTING_TIMING("Every %s or for 21 continuous %ss", "हरेक %s वा २१ लगातार %s हरू"),
    FASTING_TIMING_SUNRISE_SUNSET("Sunrise to Sunset", "सूर्योदयदेखि सूर्यास्तसम्म"),
    FASTING_TITLE_SUFFIX(" Vrat (Fast)", " व्रत"),
    FASTING_TYPE("Fasting Type", "उपवास प्रकार"),
    FASTING_VENUS_FOOD("Consume rice, milk, sweet foods", "चामल, दूध, गुलियो खाना सेवन गर्नुहोस्"),
    GEM_ALT_SUB(" - More affordable substitute", " - अधिक किफायती विकल्प"),
    GEM_BENEFIT_BALANCE("Provides continuous energy balancing", "निरन्तर ऊर्जा सन्तुलन प्रदान गर्दछ"),
    GEM_BENEFIT_LIFE_AREA("Enhances %s", "%s बढाउँछ"),
    GEM_BENEFIT_STRENGTHEN("Strengthens %s's positive influences", "%s को सकारात्मक प्रभावहरू बलियो बनाउँछ"),
    GEM_BLUE_SAPPHIRE("Blue Sapphire", "नीलम"),
    GEM_CATS_EYE("Cat's Eye", "लहसुनिया"),
    GEM_CAUTION_CERT("Buy from reputable dealer with certification", "प्रमाणपत्र सहित प्रतिष्ठित व्यापारीबाट किन्नुहोस्"),
    GEM_CAUTION_DESC("%s is not a functional benefic for your Lagna. Wearing %s may increase challenges. Consider alternative remedies.", "%s तपाईंको लग्नको लागि शुभ ग्रह होइन। %s लगाउँदा चुनौतीहरू बढ्न सक्छन्। वैकल्पिक उपायहरू विचार गर्नुहोस्।"),
    GEM_CAUTION_DURATION("Trial period of 3-7 days strongly recommended", "३-७ दिनको परीक्षण अवधि कडा सिफारिस गरिन्छ"),
    GEM_CAUTION_METHOD("CAUTION: Get expert consultation before wearing. If advised, wear %s-%s carat %s in %s on %s finger.", "सावधानी: लगाउनु अघि विशेषज्ञ परामर्श लिनुहोस्। यदि सल्लाह दिइयो भने, %s-%s क्यारेटको %s %s औंलामा %s धातुमा लगाउनुहोस्।"),
    GEM_CAUTION_NATURAL("Ensure the gemstone is natural and untreated", "रत्न प्राकृतिक र उपचार नगरिएको सुनिश्चित गर्नुहोस्"),
    GEM_CAUTION_REMOVE("Remove if experiencing adverse effects", "यदि प्रतिकूल प्रभाव अनुभव भयो भने हटाउनुहोस्"),
    GEM_CAUTION_TITLE_SUFFIX(" - Consult Before Wearing", " - लगाउनु अघि परामर्श गर्नुहोस्"),
    GEM_CAUTION_TRIAL("Trial period of 3-7 days recommended", "३-७ दिनको परीक्षण अवधि सिफारिस गरिन्छ"),
    GEM_DIAMOND("Diamond", "हीरा"),
    GEM_DURATION_CONTINUOUS("Continuous wear recommended", "निरन्तर लगाउन सिफारिस गरिएको"),
    GEM_EMERALD("Emerald", "पन्ना"),
    GEM_HESSONITE("Hessonite", "गोमेद"),
    GEM_JUPITER_DESC("Primary gemstone for strengthening Jupiter. As a functional benefic for your Lagna, this gemstone is suitable.", "बृहस्पतिलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_JUPITER_METHOD("Wear 3.0-5.0 carat natural, untreated Yellow Sapphire (Yellow) set in Gold (22K) on the Index finger of right hand.", "दायाँ हातको चोर औंलामा सुन (२२ क्यारेट) मा जडान गरिएको ३.०-५.० क्यारेटको प्राकृतिक, उपचार नगरिएको पुखराज (हेलियो) लगाउनुहोस्।"),
    GEM_JUPITER_NAME("Yellow Sapphire", "पुखराज"),
    GEM_JUPITER_TIMING("Thursday morning, during Jupiter Hora.", "बिहीबार बिहान, गुरु होरामा।"),
    GEM_KETU_DESC("Gemstone for balancing Ketu energy.", "केतु ऊर्जा सन्तुलन गर्नको लागि रत्न।"),
    GEM_KETU_METHOD("Wear 3.0-5.0 carat Cat's Eye set in Silver/Gold on Middle finger.", "माझी औंलामा चाँदी/सुनमा जडान गरिएको ३.०-५.० क्यारेटको लहसुनिया लगाउनुहोस्।"),
    GEM_KETU_NAME("Cat's Eye", "लहसुनिया"),
    GEM_KETU_TIMING("Tuesday or during Ketu nakshatra.", "मंगलबार वा केतु नक्षत्रमा।"),
    GEM_MARS_DESC("Primary gemstone for strengthening Mars. As a functional benefic for your Lagna, this gemstone is suitable.", "मंगललाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_MARS_METHOD("Wear 5.0-9.0 carat natural, untreated Red Coral (Red) set in Gold/Copper on the Ring finger of right hand.", "दायाँ हातको अनामिका औंलामा सुन/तामामा जडान गरिएको ५.०-९.० क्यारेटको प्राकृतिक, उपचार नगरिएको मुगा (रातो) लगाउनुहोस्।"),
    GEM_MARS_NAME("Red Coral", "मुगा"),
    GEM_MARS_TIMING("Tuesday morning, during Mars Hora.", "मंगलबार बिहान, मंगल होरामा।"),
    GEM_MERCURY_DESC("Primary gemstone for strengthening Mercury. As a functional benefic for your Lagna, this gemstone is suitable.", "बुधलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_MERCURY_METHOD("Wear 3.0-6.0 carat natural, untreated Emerald (Green) set in Gold on the Little finger of right hand.", "दायाँ हातको कान्छी औंलामा सुनमा जडान गरिएको ३.०-६.० क्यारेटको प्राकृतिक, उपचार नगरिएको पन्ना (हरियो) लगाउनुहोस्।"),
    GEM_MERCURY_NAME("Emerald", "पन्ना"),
    GEM_MERCURY_TIMING("Wednesday morning, during Mercury Hora.", "बुधबार बिहान, बुध होरामा।"),
    GEM_MOON_DESC("Primary gemstone for strengthening Moon. As a functional benefic for your Lagna, this gemstone is suitable.", "चन्द्रलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_MOON_METHOD("Wear 4.0-7.0 carat natural, untreated Pearl (White) set in Silver on the Little finger of right hand.", "दायाँ हातको कान्छी औंलामा चाँदीमा जडान गरिएको ४.०-७.० क्यारेटको प्राकृतिक, उपचार नगरिएको मोती (सेतो) लगाउनुहोस्।"),
    GEM_MOON_NAME("Natural Pearl", "मोती"),
    GEM_MOON_TIMING("Monday evening during Shukla Paksha, during Moon Hora.", "शुक्ल पक्षको सोमबार साँझ, चन्द्र होरामा।"),
    GEM_PEARL("Pearl", "मोती"),
    GEM_RAHU_DESC("Gemstone for balancing Rahu energy.", "राहु ऊर्जा सन्तुलन गर्नको लागि रत्न।"),
    GEM_RAHU_METHOD("Wear 5.0-8.0 carat Hessonite (Honey color) set in Silver on Middle finger.", "माझी औंलामा चाँदीमा जडान गरिएको ५.०-८.० क्यारेटको गोमेद (मह र्ग) लगाउनुहोस्।"),
    GEM_RAHU_NAME("Hessonite Garnet", "गोमेद"),
    GEM_RAHU_TIMING("Saturday night, during Rahu Kaal.", "शनिबार राती, राहु कालमा।"),
    GEM_RED_CORAL("Red Coral", "मुगा"),
    GEM_RUBY("Ruby", "माणिक"),
    GEM_SATURN_DESC("Primary gemstone for strengthening Saturn. As a functional benefic for your Lagna, this gemstone is suitable.", "शनिलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_SATURN_METHOD("Wear 3.0-5.0 carat natural, untreated Blue Sapphire (Blue) set in Gold/Panch Dhatu on the Middle finger of right hand.", "दायाँ हातको माझी औंलामा सुन/पञ्चधातुमा जडान गरिएको ३.०-५.० क्यारेटको प्राकृतिक, उपचार नगरिएको नीलम (नीलो) लगाउनुहोस्।"),
    GEM_SATURN_NAME("Blue Sapphire", "नीलम"),
    GEM_SATURN_TIMING("Saturday evening, during Saturn Hora.", "शनिबार साँझ, शनि होरामा।"),
    GEM_SUN_DESC("Primary gemstone for strengthening Sun. As a functional benefic for your Lagna, this gemstone is suitable.", "सूर्यलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_SUN_METHOD("Wear 3.0-5.0 carat natural, untreated Ruby (Red) set in Gold (22K) on the Ring finger of right hand.", "दायाँ हातको अनामिका औंलामा सुन (२२ क्यारेट) मा जडान गरिएको ३.०-५.० क्यारेटको प्राकृतिक, उपचार नगरिएको माणिक (रातो) लगाउनुहोस्।"),
    GEM_SUN_NAME("Ruby", "माणिक"),
    GEM_SUN_TIMING("Sunday during Sunrise, during Sun Hora. Purify with raw milk and Ganga water before wearing.", "आइतबार सूर्योदयको समयमा, सूर्य होरामा। लगाउनु अघि काँचो दूध र गंगाजलले शुद्ध गर्नुहोस्।"),
    GEM_VENUS_DESC("Primary gemstone for strengthening Venus. As a functional benefic for your Lagna, this gemstone is suitable.", "शुक्रलाई बलियो बनाउनको लागि प्राथमिक रत्न। तपाईंको लग्नको लागि शुभ ग्रह भएकोले, यो रत्न उपयुक्त छ।"),
    GEM_VENUS_METHOD("Wear 0.5-1.5 carat natural, untreated Diamond (White) set in Platinum/White Gold on the Middle/Little finger of right hand.", "दायाँ हातको माझी/कान्छी औंलामा प्लेटिनम/सेतो सुनमा जडान गरिएको ०.५-१.५ क्यारेटको प्राकृतिक, उपचार नगरिएको हीरा (सेतो) लगाउनुहोस्।"),
    GEM_VENUS_NAME("Diamond", "हीरा"),
    GEM_VENUS_TIMING("Friday morning, during Venus Hora.", "शुक्रबार बिहान, शुक्र होरामा।"),
    GEM_YELLOW_SAPPHIRE("Yellow Sapphire", "पुष्पराज"),
    LAL_KITAB_ABOUT("About Lal Kitab", "लाल किताबको बारेमा"),
    LAL_KITAB_ABOUT_DESC("Lal Kitab is a distinct astrological system with practical, cost-effective remedies. It differs from classical Vedic astrology in house analysis and remedy approach.", "लाल किताब व्यावहारिक, लागत-प्रभावी उपचारहरू भएको एक विशिष्ट ज्योतिष प्रणाली हो। यो भाव विश्लेषण र उपचार दृष्टिकोणमा शास्त्रीय वैदिक ज्योतिषभन्दा फरक छ।"),
    LAL_KITAB_AFFLICTION_GENERAL("General Affliction", "सामान्य पीडा"),
    LAL_KITAB_AFFLICTION_GRAHAN("Grahan Dosha", "ग्रहण दोष"),
    LAL_KITAB_AFFLICTION_KANYA("Kanya Rin (Debt of Young Women)", "कन्या ऋण"),
    LAL_KITAB_AFFLICTION_SEVERITY("Severity", "गम्भीरता"),
    LAL_KITAB_AFFLICTION_SHANI("Shani Affliction", "शनि पीडा"),
    LAL_KITAB_AFFLICTION_TYPE("Affliction Type", "पीडा प्रकार"),
    LAL_KITAB_ANNUAL_CALENDAR("Weekly Remedy Calendar", "साप्ताहिक उपाय पात्रो"),
    LAL_KITAB_AVOID("Avoid", "त्याग गर्नुहोस्"),
    LAL_KITAB_AVOID_COLORS("Colors to Avoid", "परिहार गर्ने रंगहरू"),
    LAL_KITAB_AVOID_DIRECTION("Direction to Avoid", "परिहार गर्ने दिशा"),
    LAL_KITAB_CATEGORY_GENERAL("General Remedy", "सामान्य उपाय"),
    LAL_KITAB_CATEGORY_HOUSE("House-based Remedy", "भाव-आधारित उपाय"),
    LAL_KITAB_CATEGORY_KARMIC("Karmic Debt Remedy", "कार्मिक ऋण उपाय"),
    LAL_KITAB_CATEGORY_PLANETARY("Planetary Remedy", "ग्रह उपाय"),
    LAL_KITAB_COLOR_APPLICATION("Application", "प्रयोग"),
    LAL_KITAB_COLOR_REMEDIES("Color Remedies", "रंग उपायहरू"),
    LAL_KITAB_COLOR_THERAPY("Color Therapy", "रंग चिकित्सा"),
    LAL_KITAB_DAILY_REMEDIES("Daily Remedies", "दैनिक उपायहरू"),
    LAL_KITAB_DAILY_REMEDIES_DESC("Daily remedies for each planetary day as per Lal Kitab tradition", "लाल किताब परम्परा अनुसार प्रत्येक ग्रह बारका दैनिक उपायहरू"),
    LAL_KITAB_DEBT_EFFECTS("Effects", "प्रभावहरू"),
    LAL_KITAB_DEBT_INDICATORS("Indicators", "सूचकहरू"),
    LAL_KITAB_DEBT_KANYA("Girl Child Debt", "कन्या ऋण"),
    LAL_KITAB_DEBT_MATRU("Matru Rin (Maternal)", "मातृ ऋण (मातृपक्ष)"),
    LAL_KITAB_DEBT_PITRU("Pitru Rin (Ancestral)", "पितृ ऋण (पूर्वज)"),
    LAL_KITAB_DEBT_SELF("Swayam Rin (Self)", "स्वयं ऋण (स्वयं)"),
    LAL_KITAB_DEBT_STRI("Stri Rin (Feminine)", "स्त्री ऋण (स्त्री)"),
    LAL_KITAB_DEBT_TYPE("Debt Type", "ऋण प्रकार"),
    LAL_KITAB_DESC_MATRU("Debt towards mother and maternal lineage", "आमा र मातृपक्षप्रति ऋण"),
    LAL_KITAB_DESC_PITRU("Debt towards father and ancestors", "पिता र पूर्वजहरूप्रति ऋण"),
    LAL_KITAB_DESC_SELF("Debt towards self and karma", "स्वयं र कर्मप्रति ऋण"),
    LAL_KITAB_DESC_STRI("Debt towards wife/women", "पत्नी/स्त्रीहरूप्रति ऋण"),
    LAL_KITAB_DIRECTION_APPLICATION("Direction Application", "दिशा प्रयोग"),
    LAL_KITAB_DIRECTION_GUIDANCE("Direction Guidance", "दिशा मार्गदर्शन"),
    LAL_KITAB_DIRECTION_REMEDIES("Direction Remedies", "दिशा उपायहरू"),
    LAL_KITAB_EFFECTIVENESS_HIGH("Highly Effective", "अत्यधिक प्रभावकारी"),
    LAL_KITAB_EFFECTIVENESS_MEDIUM("Moderately Effective", "मध्यम प्रभावकारी"),
    LAL_KITAB_FAVORABLE("Favorable", "अनुकूल"),
    LAL_KITAB_FAVORABLE_COLORS("Favorable Colors", "शुभ रंगहरू"),
    LAL_KITAB_FAVORABLE_DIRECTION("Favorable Direction", "शुभ दिशा"),
    LAL_KITAB_FRIDAY("Friday - Venus", "शुक्रबार - शुक्र"),
    LAL_KITAB_GENERAL_PRINCIPLES("General Principles of Lal Kitab", "लाल किताबका सामान्य सिद्धान्तहरू"),
    LAL_KITAB_GENERAL_RECOMMENDATIONS("General Recommendations", "सामान्य सिफारिसहरू"),
    LAL_KITAB_GRAHAN_DOSH("Grahan Dosh", "ग्रहण दोष"),
    LAL_KITAB_HOUSE_AFFLICTED("Afflicted", "पीडित"),
    LAL_KITAB_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
    LAL_KITAB_HOUSE_BENEFIC("Benefic Influence", "शुभ प्रभाव"),
    LAL_KITAB_HOUSE_EMPTY("Empty", "खाली"),
    LAL_KITAB_HOUSE_OCCUPIED("Occupied", "भरिएको"),
    LAL_KITAB_HOUSE_REMEDIES("House-Based Remedies", "भाव-आधारित उपायहरू"),
    LAL_KITAB_HOUSE_STATUS("House Status", "भाव स्थिति"),
    LAL_KITAB_INDICATORS("Indicators", "संकेतहरू"),
    LAL_KITAB_ITEM_BASED("Item-Based Remedies", "वस्तु-आधारित उपायहरू"),
    LAL_KITAB_KANYA_RIN("Kanya Rin", "कन्या ऋण"),
    LAL_KITAB_KARMIC_DEBTS("Karmic Debts (Rin)", "कार्मिक ऋण"),
    LAL_KITAB_MATRU_RIN("Matru Rin", "मातृ ऋण"),
    LAL_KITAB_MONDAY("Monday - Moon", "सोमबार - चन्द्र"),
    LAL_KITAB_NOTE_DISTINCT("Lal Kitab remedies are unique and different from traditional Vedic remedies.", "लाल किताब उपायहरू अद्वितीय छन् र परम्परागत वैदिक उपायहरूभन्दा फरक छन्।"),
    LAL_KITAB_PITRU_DOSH("Pitru Dosh", "पितृ दोष"),
    LAL_KITAB_PLANETARY_AFFLICTIONS("Planetary Afflictions", "ग्रह पीडाहरू"),
    LAL_KITAB_RECOMMENDED_REMEDIES("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
    LAL_KITAB_REMEDIES("Remedies", "उपायहरू"),
    LAL_KITAB_REMEDIES_LABEL("Remedies", "उपायहरू"),
    LAL_KITAB_REMEDY_ACTION("Action Required", "आवश्यक कार्य"),
    LAL_KITAB_REMEDY_CATEGORY("Remedy Category", "उपाय श्रेणी"),
    LAL_KITAB_REMEDY_DURATION("Duration", "अवधि"),
    LAL_KITAB_REMEDY_EFFECTIVENESS("Effectiveness", "प्रभावकारिता"),
    LAL_KITAB_REMEDY_FREQUENCY("Frequency", "आवृत्ति"),
    LAL_KITAB_REMEDY_ITEM("Remedy Item", "उपाय वस्तु"),
    LAL_KITAB_REMEDY_METHOD("Method", "विधि"),
    LAL_KITAB_REMEDY_TIMING("Best Timing", "उत्तम समय"),
    LAL_KITAB_RIN_DESC("Karmic debts indicate areas where remedial measures are needed to balance past karma.", "कर्म ऋणहरूले विगतको कर्म सन्तुलन गर्न उपायहरू आवश्यक पर्ने क्षेत्रहरू संकेत गर्दछ।"),
    LAL_KITAB_RIN_NONE_DESC("Your chart does not indicate major karmic debts requiring immediate remedies.", "तपाईंको कुण्डलीले तत्काल उपाय आवश्यक पर्ने प्रमुख कर्म ऋणहरू संकेत गर्दैन।"),
    LAL_KITAB_RIN_NONE_TITLE("No Significant Karmic Debts", "कुनै महत्त्वपूर्ण कर्म ऋण छैन"),
    LAL_KITAB_RIN_TITLE("Karmic Debts (Rin)", "कर्म ऋणहरू"),
    LAL_KITAB_SATURDAY("Saturday - Saturn", "शनिबार - शनि"),
    LAL_KITAB_SCREEN_ABOUT("About Lal Kitab", "लाल किताबको बारेमा"),
    LAL_KITAB_SCREEN_ABOUT_DESC("Lal Kitab offers simple, practical remedies using everyday items like turmeric, milk, honey, and specific actions. These remedies work on karmic debts and planetary afflictions without expensive rituals.", "लाल किताबले बेसार, दूध, मह जस्ता दैनिक वस्तुहरू प्रयोग गरी सरल, व्यावहारिक उपायहरू प्रदान गर्दछ। यी उपायहरूले महँगो विधि बिना कार्मिक ऋण र ग्रह पीडामा काम गर्दछन्।"),
    LAL_KITAB_SCREEN_KARMIC_DEBTS("Karmic Debts (Rin)", "कार्मिक ऋणहरू"),
    LAL_KITAB_SCREEN_PLANETARY_AFFLICTIONS("Planetary Afflictions", "ग्रह पीडाहरू"),
    LAL_KITAB_SCREEN_SUBTITLE("Practical Karmic Remedies", "व्यावहारिक कार्मिक उपायहरू"),
    LAL_KITAB_SCREEN_TITLE("Lal Kitab Remedies", "लाल किताब उपायहरू"),
    LAL_KITAB_SECTION_REMEDIES("Remedies", "उपायहरू"),
    LAL_KITAB_SEVERITY_MILD("Mild", "हल्का"),
    LAL_KITAB_SEVERITY_MINIMAL("Minimal", "न्यूनतम"),
    LAL_KITAB_SEVERITY_MODERATE("Moderate", "मध्यम"),
    LAL_KITAB_SEVERITY_SEVERE("Severe", "गम्भीर"),
    LAL_KITAB_SHANI_PEEDA("Shani Peeda", "शनि पीडा"),
    LAL_KITAB_STRI_RIN("Stri Rin", "स्त्री ऋण"),
    LAL_KITAB_SUBTITLE("Traditional Remedial System", "परम्परागत उपचार प्रणाली"),
    LAL_KITAB_SUNDAY("Sunday - Sun", "आइतबार - सूर्य"),
    LAL_KITAB_SYSTEM_NOTE("System Note", "प्रणाली नोट"),
    LAL_KITAB_THURSDAY("Thursday - Jupiter", "बिहीबार - बृहस्पति"),
    LAL_KITAB_TITLE("Lal Kitab Analysis", "लाल किताब विश्लेषण"),
    LAL_KITAB_TUESDAY("Tuesday - Mars", "मंगलबार - मंगल"),
    LAL_KITAB_TYPES_TITLE("Types of Karmic Debts", "कार्मिक ऋणका प्रकारहरू"),
    LAL_KITAB_WEDNESDAY("Wednesday - Mercury", "बुधबार - बुध"),
    LAL_KITAB_WEEKLY_SCHEDULE("Weekly Remedy Schedule", "साप्ताहिक उपाय तालिका"),
    MANTRA_ANURADHA("ॐ मित्राय नमः। Om Mitraya Namah", "ॐ मित्राय नमः।"),
    MANTRA_ARDRA("ॐ रुद्राय नमः। Om Rudraya Namah", "ॐ रुद्राय नमः।"),
    MANTRA_ASHLESHA("ॐ नागाय नमः। Om Nagaya Namah", "ॐ नागाय नमः।"),
    MANTRA_ASHWINI("ॐ अश्विनीकुमाराभ्यां नमः। Om Ashwini Kumarabhyam Namah", "ॐ अश्विनीकुमाराभ्यां नमः।"),
    MANTRA_BENEFIT_INVOKE("Directly invokes %s's blessings", "प्रत्यक्ष रूपमा %s को आशीर्वाद आह्वान गर्दछ"),
    MANTRA_BENEFIT_OBSTACLES("Reduces karmic obstacles", "कार्मिक अवरोधहरू कम गर्दछ"),
    MANTRA_BENEFIT_SAFE("No side effects - safe for everyone", "कुनै साइड इफेक्ट छैन - सबैको लागि सुरक्षित"),
    MANTRA_BENEFIT_VIBES("Creates positive mental vibrations", "सकारात्मक मानसिक कम्पनहरू सिर्जना गर्दछ"),
    MANTRA_BHADRA("Om Braam Breem Braum Sah Budhaya Namah", "ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः"),
    MANTRA_BHARANI("ॐ यमाय नमः। Om Yamaya Namah", "ॐ यमाय नमः।"),
    MANTRA_CAUTION_DIET("Avoid eating non-vegetarian food during the practice period", "अभ्यास अवधिमा मांसाहारी भोजन नगर्नुहोस्"),
    MANTRA_CAUTION_MALA("Use Rudraksha, Tulsi, or crystal mala", "रुद्राक्ष, तुलसी, वा स्फटिक माला प्रयोग गर्नुहोस्"),
    MANTRA_CAUTION_PURITY("Maintain physical and mental purity during practice", "अभ्यासको समयमा शारीरिक र मानसिक शुद्धता कायम राख्नुहोस्"),
    MANTRA_CAUTION_VOW("Complete the sankalpa (vow) once started", "एक पटक सुरु गरेपछि संकल्प पूरा गर्नुहोस्"),
    MANTRA_CHITRA("ॐ त्वष्ट्रे नमः। Om Tvashtre Namah", "ॐ त्वष्ट्रे नमः।"),
    MANTRA_DESC("Sacred sound vibration to invoke and strengthen %s. Mantras are the safest and most universally beneficial remedy.", "%s लाई आह्वान र बलियो बनाउन पवित्र ध्वनि कम्पन। मन्त्रहरू सबैभन्दा सुरक्षित र विश्वव्यापी रूपमा लाभदायक उपाय हुन्।"),
    MANTRA_DHANISHTHA("ॐ वसुभ्यो नमः। Om Vasubhyo Namah", "ॐ वसुभ्यो नमः।"),
    MANTRA_DURATION("Complete one mala (108 times) daily for minimum 40 days. Full count of %d for maximum benefit.", "कम्तिमा ४० दिनसम्म दैनिक एक माला (१०८ पटक) पूरा गर्नुहोस्। अधिकतम लाभको लागि %d को पूर्ण संख्या।"),
    MANTRA_HAMSA("Om Graam Greem Graum Sah Gurave Namah", "ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः"),
    MANTRA_HASTA("ॐ सवित्रे नमः। Om Savitre Namah", "ॐ सवित्रे नमः।"),
    MANTRA_JYESHTHA("ॐ इन्द्राय नमः। Om Indraya Namah", "ॐ इन्द्राय नमः।"),
    MANTRA_KRITTIKA("ॐ अग्नये नमः। Om Agnaye Namah", "ॐ अग्नये नमः।"),
    MANTRA_MAGHA("ॐ पितृभ्यो नमः। Om Pitribhyo Namah", "ॐ पितृभ्यो नमः।"),
    MANTRA_MALAVYA("Om Draam Dreem Draum Sah Shukraya Namah", "ॐ द्रां द्रीं द्रौं सः शुक्राय नमः"),
    MANTRA_METHOD("Sit facing %s. Chant the beej mantra %d times:\n\n\"%s\"\n\nAlternatively, chant Gayatri Mantra of %s.", "%s दिशा फर्केर बस्नुहोस्। बीज मन्त्र %d पटक जप गर्नुहोस्:\n\n\"%s\"\n\nवैकल्पिक रूपमा, %s को गायत्री मन्त्र जप गर्नुहोस्।"),
    MANTRA_MRIGASHIRA("ॐ सोमाय नमः। Om Somaya Namah", "ॐ सोमाय नमः।"),
    MANTRA_MULA("ॐ निर्ऋत्यै नमः। Om Nirrutyai Namah", "ॐ निर्ऋत्यै नमः।"),
    MANTRA_PUNARVASU("ॐ अदित्यै नमः। Om Adityai Namah", "ॐ अदित्यै नमः।"),
    MANTRA_PURVA_ASHADHA("ॐ अपां नमः। Om Apam Namah", "ॐ अपां नमः।"),
    MANTRA_PURVA_BHADRAPADA("ॐ अजैकपदाय नमः। Om Ajaikapadaya Namah", "ॐ अजैकपदाय नमः।"),
    MANTRA_PURVA_PHALGUNI("ॐ भगाय नमः। Om Bhagaya Namah", "ॐ भगाय नमः।"),
    MANTRA_PUSHYA("ॐ बृहस्पतये नमः। Om Brihaspataye Namah", "ॐ बृहस्पतये नमः।"),
    MANTRA_REMEDIES("Mantra Remedies", "मन्त्र उपचारहरू"),
    MANTRA_REVATI("ॐ पूष्णे नमः। Om Pushne Namah", "ॐ पूष्णे नमः।"),
    MANTRA_ROHINI("ॐ ब्रह्मणे नमः। Om Brahmane Namah", "ॐ ब्रह्मणे नमः।"),
    MANTRA_RUCHAKA("Om Kraam Kreem Kraum Sah Bhaumaya Namah", "ॐ क्रां क्रीं क्रौं सः भौमाय नमः"),
    MANTRA_SASHA("Om Praam Preem Praum Sah Shanaischaraya Namah", "ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः"),
    MANTRA_SHATABHISHA("ॐ वरुणाय नमः। Om Varunaya Namah", "ॐ वरुणाय नमः।"),
    MANTRA_SHRAVANA("ॐ विष्णवे नमः। Om Vishnave Namah", "ॐ विष्णवे नमः।"),
    MANTRA_SWATI("ॐ वायवे नमः। Om Vayave Namah", "ॐ वायवे नमः।"),
    MANTRA_TIMING_WAXING("during Shukla Paksha", "शुक्ल पक्षमा"),
    MANTRA_TITLE_SUFFIX(" Beej Mantra", " बीज मन्त्र"),
    MANTRA_UTTARA_ASHADHA("ॐ विश्वेभ्यो देवेभ्यो नमः। Om Vishvebhyo Devebhyo Namah", "ॐ विश्वेभ्यो देवेभ्यो नमः।"),
    MANTRA_UTTARA_BHADRAPADA("ॐ अहिर्बुध्न्याय नमः। Om Ahirbudhnyaya Namah", "ॐ अहिर्बुध्न्याय नमः।"),
    MANTRA_UTTARA_PHALGUNI("ॐ अर्यम्णे नमः। Om Aryamne Namah", "ॐ अर्यम्णे नमः।"),
    MANTRA_VISHAKHA("ॐ इन्द्राग्निभ्यां नमः। Om Indragnibhyam Namah", "ॐ इन्द्राग्निभ्यां नमः।"),
    NAK_REMEDY_DESC("%s is placed in %s nakshatra. This nakshatra is ruled by %s.", "%s %s नक्षत्रमा स्थित छ। यो नक्षत्रका स्वामी %s हुन्।"),
    NAK_REMEDY_DURATION("Regular practice, especially during relevant nakshatra days", "नियमित अभ्यास, विशेष गरी सम्बन्धित नक्षत्र दिनहरूमा"),
    NAK_REMEDY_METHOD_ANURADHA("Worship Mitra, cultivate friendships, practice devotion", "मित्रको पूजा गर्नुहोस्, मित्रता बढाउनुहोस्, भक्ति अभ्यास गर्नुहोस्"),
    NAK_REMEDY_METHOD_ARDRA("Worship Lord Rudra, perform Rudra Abhisheka, offer blue flowers", "भगवान रुद्रको पूजा गर्नुहोस्, रुद्र अभिषेक गर्नुहोस्, नीलो फूल चढाउनुहोस्"),
    NAK_REMEDY_METHOD_ASHLESHA("Worship Naga deities, offer milk to snake idols, avoid harming snakes", "नाग देवताहरूको पूजा गर्नुहोस्, सर्पको मूर्तिमा दूध चढाउनुहोस्, सर्पलाई हानि नगर्नुहोस्"),
    NAK_REMEDY_METHOD_ASHWINI("Worship Ashwini Kumaras, offer white items, avoid surgery on this nakshatra days", "अश्विनी कुमारहरूको पूजा गर्नुहोस्, सेतो वस्तुहरू चढाउनुहोस्, यस नक्षत्रको दिनमा शल्यक्रिया नगर्नुहोस्"),
    NAK_REMEDY_METHOD_BHARANI("Worship Yama, practice dharma, donate to funeral services", "यमको पूजा गर्नुहोस्, धर्म अभ्यास गर्नुहोस्, अन्त्येष्टि सेवाहरूमा दान गर्नुहोस्"),
    NAK_REMEDY_METHOD_CHITRA("Worship Vishwakarma, practice craftsmanship, donate tools", "विश्वकर्माको पूजा गर्नुहोस्, शिल्प कौशल अभ्यास गर्नुहोस्, औजारहरू दान गर्नुहोस्"),
    NAK_REMEDY_METHOD_DHANISHTHA("Worship Vasus, practice music, donate musical instruments", "वसुहरूको पूजा गर्नुहोस्, संगीत अभ्यास गर्नुहोस्, वाद्ययन्त्र दान गर्नुहोस्"),
    NAK_REMEDY_METHOD_HASTA("Worship Savitar (Sun), practice healing arts, offer sunflowers", "सविता (सूर्य) को पूजा गर्नुहोस्, निको पार्ने कला अभ्यास गर्नुहोस्, सूर्यमुखी फूल चढाउनुहोस्"),
    NAK_REMEDY_METHOD_JYESHTHA("Worship Indra, develop leadership, protect the weak", "इन्द्रको पूजा गर्नुहोस्, नेतृत्व विकास गर्नुहोस्, कमजोरलाई रक्षा गर्नुहोस्"),
    NAK_REMEDY_METHOD_KRITTIKA("Worship Agni, perform homa/fire rituals, offer ghee", "अग्नीको पूजा गर्नुहोस्, होम/अग्नि अनुष्ठान गर्नुहोस्, घिउ चढाउनुहोस्"),
    NAK_REMEDY_METHOD_MAGHA("Worship ancestors (Pitris), perform Shraddha rituals, respect elders", "पितृहरूको पूजा गर्नुहोस्, श्राद्ध कर्म गर्नुहोस्, ठूलाबाडालाई आदर गर्नुहोस्"),
    NAK_REMEDY_METHOD_MRIGASHIRA("Worship Soma/Chandra, offer white items, stay near water", "सोम/चन्द्रको पूजा गर्नुहोस्, सेतो वस्तुहरू चढाउनुहोस्, पानीको नजिक बस्नुहोस्"),
    NAK_REMEDY_METHOD_MULA("Worship Goddess Nirriti/Kali, practice detachment, donate roots/herbs", "देवी निर्ऋति/कालीको पूजा गर्नुहोस्, वैराग्य अभ्यास गर्नुहोस्, जरा/जडीबुटी दान गर्नुहोस्"),
    NAK_REMEDY_METHOD_PUNARVASU("Worship Goddess Aditi, practice hospitality, help the needy", "देवी अदितिको पूजा गर्नुहोस्, आतिथ्य अभ्यास गर्नुहोस्, खाँचोमा परेकाहरूलाई मद्दत गर्नुहोस्"),
    NAK_REMEDY_METHOD_PURVA_ASHADHA("Worship Apas (water deities), stay near water, practice purification", "आप (जल देवता) को पूजा गर्नुहोस्, पानीको नजिक बस्नुहोस्, शुद्धीकरण अभ्यास गर्नुहोस्"),
    NAK_REMEDY_METHOD_PURVA_BHADRAPADA("Worship Aja Ekapad, practice yoga and meditation, seek spiritual liberation", "अज एकपादको पूजा गर्नुहोस्, योग र ध्यान अभ्यास गर्नुहोस्, आध्यात्मिक मुक्ति खोज्नुहोस्"),
    NAK_REMEDY_METHOD_PURVA_PHALGUNI("Worship Bhaga, practice generosity, enjoy arts and creativity", "भगको पूजा गर्नुहोस्, उदारता अभ्यास गर्नुहोस्, कला र रचनात्मकताको आनन्द लिनुहोस्"),
    NAK_REMEDY_METHOD_PUSHYA("Worship Brihaspati, donate to teachers, study scriptures", "बृहस्पतिको पूजा गर्नुहोस्, शिक्षकहरूलाई दान गर्नुहोस्, शास्त्र अध्ययन गर्नुहोस्"),
    NAK_REMEDY_METHOD_REVATI("Worship Pushan, practice guidance and protection, help travelers", "पुषनको पूजा गर्नुहोस्, मार्गदर्शन र सुरक्षा अभ्यास गर्नुहोस्, यात्रीहरूलाई मद्दत गर्नुहोस्"),
    NAK_REMEDY_METHOD_ROHINI("Worship Brahma, offer white flowers and milk, practice creativity", "ब्रह्माजीको पूजा गर्नुहोस्, सेतो फूल र दूध चढाउनुहोस्, रचनात्मकता अभ्यास गर्नुहोस्"),
    NAK_REMEDY_METHOD_SHATABHISHA("Worship Varuna, practice healing, work with herbs and medicines", "वरुणको पूजा गर्नुहोस्, निको पार्ने अभ्यास गर्नुहोस्, जडीबुटी र औषधिहरूसँग काम गर्नुहोस्"),
    NAK_REMEDY_METHOD_SHRAVANA("Worship Lord Vishnu, practice listening and learning, chant Vishnu mantras", "भगवान विष्णुको पूजा गर्नुहोस्, सुन्ने र सिक्ने अभ्यास गर्नुहोस्, विष्णु मन्त्र जप गर्नुहोस्"),
    NAK_REMEDY_METHOD_SWATI("Worship Vayu, practice pranayama, offer incense", "वायुको पूजा गर्नुहोस्, प्राणायाम अभ्यास गर्नुहोस्, धूप चढाउनुहोस्"),
    NAK_REMEDY_METHOD_UTTARA_ASHADHA("Worship Vishvadevas, practice universal service, be helpful to all", "विश्वदेवहरूको पूजा गर्नुहोस्, विश्वव्यापी सेवा अभ्यास गर्नुहोस्, सबैलाई सहयोगी हुनुहोस्"),
    NAK_REMEDY_METHOD_UTTARA_BHADRAPADA("Worship Ahir Budhnya, practice deep meditation, seek wisdom", "अहिर्बुध्न्यको पूजा गर्नुहोस्, गहिरो ध्यान अभ्यास गर्नुहोस्, ज्ञान खोज्नुहोस्"),
    NAK_REMEDY_METHOD_UTTARA_PHALGUNI("Worship Aryaman, honor contracts and promises, practice charity", "अर्यमाको पूजा गर्नुहोस्, सम्झौता र वाचाहरूको सम्मान गर्नुहोस्, दान अभ्यास गर्नुहोस्"),
    NAK_REMEDY_METHOD_VISHAKHA("Worship Indra-Agni, practice determination, perform fire rituals", "इन्द्र-अग्नीको पूजा गर्नुहोस्, दृढ संकल्प अभ्यास गर्नुहोस्, अग्नि अनुष्ठान गर्नुहोस्"),
    NAK_REMEDY_TIMING("Perform especially when Moon transits %s", "विशेष गरी चन्द्रमाले %s गोचर गर्दा गर्नुहोस्"),
    NAK_REMEDY_TITLE("%s Nakshatra Remedy", "%s नक्षत्र उपाय"),
    REMEDIES_ANALYSIS("Remedies Analysis", "उपाय विश्लेषण"),
    REMEDIES_ANALYZING("Analyzing your chart...", "तपाईंको कुण्डली विश्लेषण गर्दै..."),
    REMEDIES_BENEFITS("Benefits", "लाभहरू"),
    REMEDIES_BEST_DAY("Best performed on %s", "%s मा गर्नु उत्तम"),
    REMEDIES_CAUTIONS("Cautions", "सावधानीहरू"),
    REMEDIES_CHARITY("Charity", "दान"),
    REMEDIES_CHART_STRENGTH("Chart Strength", "कुण्डली बल"),
    REMEDIES_COPY_MANTRA("Copy mantra", "मन्त्र कपी गर्नुहोस्"),
    REMEDIES_DURATION("Duration", "अवधि"),
    REMEDIES_ESSENTIAL("Essential Remedies", "आवश्यक उपायहरू"),
    REMEDIES_ESSENTIAL_COUNT("Essential", "आवश्यक"),
    REMEDIES_FILTER_ALL("All", "सबै"),
    REMEDIES_GEMSTONES("Gemstones", "रत्नहरू"),
    REMEDIES_GENERAL_RECOMMENDATIONS("General Recommendations", "सामान्य सिफारिसहरू"),
    REMEDIES_LIFE_AREA_FOCUS("Life Area Focus", "जीवन क्षेत्र फोकस"),
    REMEDIES_MANTRAS("Mantras", "मन्त्रहरू"),
    REMEDIES_MANTRA_SECTION("Mantra", "मन्त्र"),
    REMEDIES_METHOD("Method", "विधि"),
    REMEDIES_NO_CATEGORY("No remedies in this category", "यस वर्गमा कुनै उपाय छैन"),
    REMEDIES_NO_CHART("No chart selected", "कुनै कुण्डली छानिएको छैन"),
    REMEDIES_NO_RESULTS("No remedies found", "कुनै उपाय फेला परेन"),
    REMEDIES_NO_RESULTS_SEARCH("No remedies found for \"%s\"", "\"%s\" को लागि कुनै उपाय फेला परेन"),
    REMEDIES_OVERVIEW("Overview", "अवलोकन"),
    REMEDIES_PLANETS("Planets", "ग्रहहरू"),
    REMEDIES_PLANETS_ATTENTION("Planets Requiring Attention", "ध्यान आवश्यक ग्रहहरू"),
    REMEDIES_PLANETS_WELL_PLACED("%d of %d planets well-placed", "%d मध्ये %d ग्रह राम्ररी स्थित"),
    REMEDIES_PREPARING("Preparing personalized remedies", "व्यक्तिगत उपायहरू तयार गर्दै"),
    REMEDIES_RECOMMENDED("%d remedies recommended", "%d उपायहरू सिफारिस गरिएको"),
    REMEDIES_RITUALS("Rituals", "पूजा विधिहरू"),
    REMEDIES_SEARCH("Search remedies...", "उपायहरू खोज्नुहोस्..."),
    REMEDIES_SELECT_CHART("Select a chart to view remedies", "उपायहरू हेर्न कुण्डली छान्नुहोस्"),
    REMEDIES_TIMING("Timing", "समय"),
    REMEDIES_TITLE("Remedial Measures", "उपचारात्मक उपायहरू"),
    REMEDIES_TOTAL("Total", "कुल"),
    REMEDIES_WEEKLY_SCHEDULE("Weekly Remedy Schedule", "साप्ताहिक उपाय तालिका"),
    REMEDIES_WEEKLY_SCHEDULE_DESC("Perform planet-specific remedies on their designated days for maximum effect", "अधिकतम प्रभावको लागि तिनीहरूको तोकिएको दिनमा ग्रह-विशेष उपायहरू गर्नुहोस्"),
    REMEDIES_YANTRAS("Yantras", "यन्त्रहरू"),
    REMEDY_ACTION("Suggested Action", "सुझाव गरिएको कार्य"),
    REMEDY_ACTION_CAREER("Pursue careers in {0}", "{0} मा करियर बनाउनुहोस्"),
    REMEDY_ACTION_CHARITY("Donate {0} on {1}", "{1} मा {0} दान गर्नुहोस्"),
    REMEDY_ACTION_GEMSTONE("Consider wearing {0} after proper consultation", "उचित परामर्श पछि {0} लगाउने विचार गर्नुहोस्"),
    REMEDY_ACTION_MANTRA("Recite {0} 108 times", "{0} १०८ पटक जप गर्नुहोस्"),
    REMEDY_ACTION_WORSHIP("Worship {0} on {1}''s day ({2})", "{1} को दिन ({2}) मा {0} को पूजा गर्नुहोस्"),
    REMEDY_ALL_STRONG("All planets are in good condition", "सबै ग्रह राम्रो अवस्थामा छन्"),
    REMEDY_BENEFIT_ACTIVATE("Activates and strengthens the yoga''s positive effects", "योगको सकारात्मक प्रभावहरूलाई सक्रिय र बलियो बनाउँछ"),
    REMEDY_BENEFIT_AMPLIFY("Amplifies {0}''s positive significations", "{0} को सकारात्मक विशेषताहरूलाई बढावा दिन्छ"),
    REMEDY_BENEFIT_CAREER("Maximum success in areas aligned with the yoga", "योगसँग मिल्दाजुल्दा क्षेत्रहरूमा अधिकतम सफलता"),
    REMEDY_BENEFIT_INVOKE("Invokes {0}''s blessings for yoga activation", "योग सक्रियताका लागि {0} को आशीर्वाद प्राप्त हुन्छ"),
    REMEDY_BENEFIT_KARMA("Creates good karma and removes obstacles", "राम्रो कर्म सिर्जना गर्दछ र बाधाहरू हटाउँछ"),
    REMEDY_BHAKOOT_1("Bhakoot Dosha: Perform Graha Shanti puja for Moon sign lords of both partners", "भकुट दोष: दुवै साझेदारको चन्द्र राशि स्वामीको ग्रह शान्ति पूजा गर्नुहोस्"),
    REMEDY_BHAKOOT_2("Bhakoot Dosha: Chant Vishnu Sahasranama on Thursdays for 21 weeks", "भकुट दोष: २१ हप्ता बिहीबारमा विष्णु सहस्रनाम जाप गर्नुहोस्"),
    REMEDY_BLUE_SAPPHIRE_DESC("Wear after proper testing and astrologer consultation", "उचित परीक्षण र ज्योतिषी परामर्श पछि लगाउनुहोस्"),
    REMEDY_BLUE_SAPPHIRE_TITLE("Blue Sapphire (Neelam)", "नीलम रत्न"),
    REMEDY_CALCULATION_FAILED("Failed to calculate remedies: %s", "उपायहरू गणना गर्न असफल: %s"),
    REMEDY_CAT_CHARITY("Charity", "दान"),
    REMEDY_CAT_COLOR("Color Therapy", "रंग चिकित्सा"),
    REMEDY_CAT_DEITY("Deity Worship", "देवता पूजा"),
    REMEDY_CAT_FASTING("Fasting", "उपवास"),
    REMEDY_CAT_GEMSTONE("Gemstone", "रत्न"),
    REMEDY_CAT_LIFESTYLE("Lifestyle", "जीवनशैली"),
    REMEDY_CAT_MANTRA("Mantra", "मन्त्र"),
    REMEDY_CAT_METAL("Metal", "धातु"),
    REMEDY_CAT_RUDRAKSHA("Rudraksha", "रुद्राक्ष"),
    REMEDY_CAT_YANTRA("Yantra", "यन्त्र"),
    REMEDY_CHARITY_TEMPLATE("Donating %s on %s can help mitigate challenging planetary influences.",
        "%s मा %s दान गर्दा चुनौतीपूर्ण ग्रह प्रभावहरू कम गर्न मद्दत गर्न सक्छ।"),
    REMEDY_COLOR("Favorable Color", "अनुकूल रंग"),
    REMEDY_COPY("Copy", "कपी गर्नुहोस्"),
    REMEDY_CORAL_DESC("Wear red coral in gold or copper on right hand ring finger", "दाहिने हातको अनामिकामा सुन वा तामामा मूंगा लगाउनुहोस्"),
    REMEDY_CORAL_TITLE("Red Coral (Moonga)", "मूंगा रत्न"),
    REMEDY_CROW_FEEDING_DESC("Feed crows daily as they are considered messengers of ancestors", "कागलाई दैनिक खुवाउनुहोस् किनभने तिनीहरूलाई पुर्खाको दूत मानिन्छ"),
    REMEDY_CROW_FEEDING_TITLE("Crow Feeding", "काग भोजन"),
    REMEDY_DAY("Best Weekday", "उत्तम वार"),
    REMEDY_DEITY_WORSHIP("Deity Worship", "देवता पूजा"),
    REMEDY_DIRECTION("Auspicious Direction", "शुभ दिशा"),
    REMEDY_DONATION("Recommended Donation", "सिफारिस गरिएको दान"),
    REMEDY_DOUBLE_MANGLIK("Double Manglik: Requires extended Kumbh Vivah ritual and 11 Rudrabhisheks over 11 consecutive Mondays", "दोहोरो मांगलिक: विस्तारित कुम्भ विवाह विधि र लगातार ११ सोमबारमा ११ रुद्राभिषेक आवश्यक"),
    REMEDY_EFFECTIVENESS_ALL_LEVELS(
        "Recommended for all Manglik levels",
        "सबै मांगलिक स्तरहरूको लागि सिफारिस"
    ),
    REMEDY_EFFECTIVENESS_CONSULT(
        "Consult astrologer before wearing",
        "लगाउनु अघि ज्योतिषीसँग परामर्श गर्नुहोस्"
    ),
    REMEDY_EFFECTIVENESS_EVERY_TUESDAY(
        "Every Tuesday",
        "हरेक मंगलबार"
    ),
    REMEDY_EFFECTIVENESS_TRADITIONAL(
        "Traditional remedy - highly effective",
        "परम्परागत उपाय - अत्यधिक प्रभावकारी"
    ),
    REMEDY_EFFECTIVENESS_TUESDAY(
        "Daily recitation on Tuesdays",
        "मंगलबार दैनिक पाठ"
    ),
    REMEDY_ESSENTIAL_COUNT("%d Essential Remedies", "%d आवश्यक उपायहरू"),
    REMEDY_FASTING_TEMPLATE("Fasting on %s can strengthen beneficial planetary energies.",
        "%s मा उपवास गर्दा लाभदायक ग्रह ऊर्जाहरू बलियो बनाउन सक्छ।"),
    REMEDY_GANA_1("Gana Incompatibility: Chant Ganapati Atharvasheersham daily for 41 days", "गण असंगतता: ४१ दिन दैनिक गणपति अथर्वशीर्षम् जाप गर्नुहोस्"),
    REMEDY_GANA_2("Gana Incompatibility: Perform Navgraha Shanti puja together before marriage", "गण असंगतता: विवाह अघि सँगै नवग्रह शान्ति पूजा गर्नुहोस्"),
    REMEDY_GANA_3("Gana Incompatibility: Practice mutual respect and conscious communication daily", "गण असंगतता: दैनिक पारस्परिक सम्मान र सचेत सञ्चार अभ्यास गर्नुहोस्"),
    REMEDY_GEMSTONE_TEMPLATE("Wearing %s gemstone can strengthen %s and bring positive results.",
        "%s रत्न लगाउँदा %s लाई बलियो बनाउन र सकारात्मक परिणामहरू ल्याउन सक्छ।"),
    REMEDY_GENERAL_1("General: Perform Satyanarayan Puja together on Purnima (full moon)", "सामान्य: पूर्णिमामा सँगै सत्यनारायण पूजा गर्नुहोस्"),
    REMEDY_GENERAL_2("General: Chant Swayamvara Parvati Mantra for marital harmony", "सामान्य: वैवाहिक सामञ्जस्यको लागि स्वयंवर पार्वती मन्त्र जाप गर्नुहोस्"),
    REMEDY_GENERAL_3("General: Donate to couples in need or contribute to marriage funds for the poor", "सामान्य: जरुरतमन्द जोडीहरूलाई दान गर्नुहोस् वा गरिबको विवाह कोषमा योगदान गर्नुहोस्"),
    REMEDY_GENERAL_4("General: Both partners should observe Monday fasts for Lord Shiva", "सामान्य: दुवै साझेदारले भगवान शिवको लागि सोमबार व्रत गर्नुपर्छ"),
    REMEDY_GRAHA_MAITRI_1("Graha Maitri: Strengthen Mercury through green charity and Budh mantra chanting on Wednesdays", "ग्रह मैत्री: बुधबारमा हरियो दान र बुध मन्त्र जापद्वारा बुध बलियो बनाउनुहोस्"),
    REMEDY_GRAHA_MAITRI_2("Graha Maitri: Both partners should meditate together daily to improve mental harmony", "ग्रह मैत्री: मानसिक सामञ्जस्य सुधार गर्न दुवै साझेदारले दैनिक सँगै ध्यान गर्नुपर्छ"),
    REMEDY_HANUMAN_WORSHIP_DESC("Recite Hanuman Chalisa daily, especially on Tuesdays and Saturdays", "हनुमान चालीसा दैनिक पाठ गर्नुहोस्, विशेष गरी मंगलबार र शनिबार"),
    REMEDY_HANUMAN_WORSHIP_TITLE("Hanuman Worship", "हनुमान पूजा"),
    REMEDY_KUMBH_VIVAH_DESC("Ceremonial marriage to a clay pot or Peepal tree before actual marriage", "वास्तविक विवाह अघि माटोको घडा वा पीपलको रूखसँग विवाह समारोह"),
    REMEDY_KUMBH_VIVAH_TITLE("Kumbh Vivah", "कुम्भ विवाह"),
    REMEDY_MANGAL_SHANTI_DESC("Perform Mars pacification ritual at a temple or home", "मन्दिर वा घरमा मंगल शान्ति विधि गर्नुहोस्"),
    REMEDY_MANGAL_SHANTI_TITLE("Mangal Shanti Puja", "मंगल शान्ति पूजा"),
    REMEDY_MANGLIK_1("Manglik Dosha: Perform Kumbh Vivah (symbolic marriage to a pot or banana tree) before actual marriage", "मांगलिक दोष: वास्तविक विवाह अघि कुम्भ विवाह (घैंटो वा केराको बोटसँग प्रतीकात्मक विवाह) गर्नुहोस्"),
    REMEDY_MANGLIK_2("Manglik Dosha: Chant Mangal Mantra 'Om Kraam Kreem Kraum Sah Bhaumaya Namah' 108 times on Tuesdays", "मांगलिक दोष: मंगलबारमा मंगल मन्त्र 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः' १०८ पटक जाप गर्नुहोस्"),
    REMEDY_MANGLIK_3("Manglik Dosha: Wear a Red Coral (Moonga) after proper energization and astrological consultation", "मांगलिक दोष: उचित ऊर्जावान र ज्योतिषीय परामर्श पछि मुंगा (प्रवाल) धारण गर्नुहोस्"),
    REMEDY_MANGLIK_BRIDE("For Bride's Manglik: Visit Hanuman temple on Tuesdays and offer vermilion and jasmine oil", "दुलहीको मांगलिकको लागि: मंगलबारमा हनुमान मन्दिरमा जानुहोस् र सिन्दूर र चमेलीको तेल चढाउनुहोस्"),
    REMEDY_MANGLIK_GROOM("For Groom's Manglik: Perform Mars-related charity on Tuesdays (donate red lentils, jaggery, copper)", "दुलाहाको मांगलिकको लागि: मंगलबारमा मंगल-सम्बन्धित दान गर्नुहोस् (रातो दाल, गुड, तामा दान गर्नुहोस्)"),
    REMEDY_MANTRA("Recommended Mantra", "सिफारिस गरिएको मन्त्र"),
    REMEDY_MANTRA_TEMPLATE("Chanting %s mantra regularly can appease %s and bring blessings.",
        "%s मन्त्र नियमित जप गर्दा %s लाई शान्त पार्न र आशीर्वाद ल्याउन सक्छ।"),
    REMEDY_MARS_MANTRA_DESC("Recite 'Om Kram Kreem Kroum Sah Bhaumaya Namah' 108 times on Tuesdays", "मंगलबार 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः' १०८ पटक जप गर्नुहोस्"),
    REMEDY_MARS_MANTRA_TITLE("Mars Mantra", "मंगल मन्त्र"),
    REMEDY_NADI_1("Nadi Dosha: Donate grains, gold, or cow on an auspicious day after consulting a priest", "नाडी दोष: पुजारीसँग परामर्श पछि शुभ दिनमा अन्न, सुन, वा गाई दान गर्नुहोस्"),
    REMEDY_NADI_2("Nadi Dosha: Perform Maha Mrityunjaya Jaap (108 times daily for 40 days)", "नाडी दोष: महा मृत्युञ्जय जाप गर्नुहोस् (४० दिन दैनिक १०८ पटक)"),
    REMEDY_NADI_3("Nadi Dosha: Worship Lord Shiva and Goddess Parvati together on Mondays", "नाडी दोष: सोमबारमा भगवान शिव र देवी पार्वतीको सँगै पूजा गर्नुहोस्"),
    REMEDY_NARAYAN_BALI_DESC("Special ritual for departed souls performed at Trimbakeshwar", "त्र्यम्बकेश्वरमा दिवंगत आत्माको लागि विशेष विधि"),
    REMEDY_NARAYAN_BALI_TITLE("Narayan Bali", "नारायण बलि"),
    REMEDY_NONE_NEEDED("Excellent compatibility - no specific remedies required.", "उत्कृष्ट अनुकूलता - कुनै विशेष उपाय आवश्यक छैन।"),
    REMEDY_PIND_DAAN_DESC("Offer rice balls to ancestors at Gaya or other sacred places", "गया वा अन्य पवित्र स्थानमा पुर्खालाई भातको पिण्ड अर्पण गर्नुहोस्"),
    REMEDY_PIND_DAAN_TITLE("Pind Daan", "पिण्ड दान"),
    REMEDY_PITRA_GAYATRI_DESC("Recite Pitra Gayatri daily during Brahma Muhurta for ancestral peace", "पुर्खाको शान्तिको लागि ब्रह्म मुहूर्तमा पितृ गायत्री दैनिक जप गर्नुहोस्"),
    REMEDY_PITRA_GAYATRI_TITLE("Pitra Gayatri Mantra", "पितृ गायत्री मन्त्र"),
    REMEDY_PITRA_TARPAN_DESC("Offer water with sesame seeds to ancestors during Amavasya", "अमावस्यामा पुर्खालाई तिल पानी अर्पण गर्नुहोस्"),
    REMEDY_PITRA_TARPAN_TITLE("Pitra Tarpan", "पितृ तर्पण"),
    REMEDY_PLANETARY_ANALYSIS("Planetary Analysis", "ग्रह विश्लेषण"),
    REMEDY_PRIORITY_ESSENTIAL("Essential", "आवश्यक"),
    REMEDY_PRIORITY_HIGHLY_RECOMMENDED("Highly Recommended", "अत्यधिक सिफारिस"),
    REMEDY_PRIORITY_OPTIONAL("Optional", "वैकल्पिक"),
    REMEDY_PRIORITY_RECOMMENDED("Recommended", "सिफारिस गरिएको"),
    REMEDY_RAJJU_KANTHA("Kantha Rajju Dosha (Neck): Wear Rudraksha mala and chant Vishnu mantras", "कण्ठ रज्जु दोष (घाँटी): रुद्राक्ष माला लगाउनुहोस् र विष्णु मन्त्र जाप गर्नुहोस्"),
    REMEDY_RAJJU_KATI("Kati Rajju Dosha (Waist): Perform Lakshmi puja and donate to poverty relief", "कटि रज्जु दोष (कम्मर): लक्ष्मी पूजा गर्नुहोस् र गरिबी उन्मूलनमा दान गर्नुहोस्"),
    REMEDY_RAJJU_NABHI("Nabhi Rajju Dosha (Navel): Perform Santan Gopal puja and donate to orphanages", "नाभि रज्जु दोष (नाभि): सन्तान गोपाल पूजा गर्नुहोस् र अनाथाश्रममा दान गर्नुहोस्"),
    REMEDY_RAJJU_PADA("Pada Rajju Dosha (Feet): Worship at a pilgrimage site together before marriage", "पाद रज्जु दोष (पाउ): विवाह अघि सँगै तीर्थस्थलमा पूजा गर्नुहोस्"),
    REMEDY_RAJJU_SIRO("Siro Rajju Dosha (Head): Perform Ayushya Homa and worship Lord Mrityunjaya Shiva", "शिरो रज्जु दोष (शिर): आयुष्य होम गर्नुहोस् र भगवान मृत्युञ्जय शिवको पूजा गर्नुहोस्"),
    REMEDY_SATURDAY_CHARITY_DESC("Donate black sesame, mustard oil, or iron items to the needy", "कालो तिल, सर्स्यूको तेल, वा फलामका सामानहरू गरिबलाई दान गर्नुहोस्"),
    REMEDY_SATURDAY_CHARITY_TITLE("Saturday Charity", "शनिबार दान"),
    REMEDY_SATURDAY_FAST_DESC("Observe fast on Saturdays and eat only after sunset", "शनिबार व्रत राख्नुहोस् र सूर्यास्त पछि मात्र खानुहोस्"),
    REMEDY_SATURDAY_FAST_TITLE("Saturday Fasting", "शनिबार व्रत"),
    REMEDY_SATYANARAYAN("For auspiciousness: Perform Satyanarayan Katha together on the first Purnima after marriage", "शुभताको लागि: विवाह पछिको पहिलो पूर्णिमामा सँगै सत्यनारायण कथा गर्नुहोस्"),
    REMEDY_SEARCH("Search remedies", "उपायहरू खोज्नुहोस्"),
    REMEDY_SERIOUS_1("Serious Concerns: Consult a qualified Vedic astrologer for personalized guidance", "गम्भीर चिन्ताहरू: व्यक्तिगत मार्गदर्शनको लागि योग्य वैदिक ज्योतिषीसँग परामर्श गर्नुहोस्"),
    REMEDY_SERIOUS_2("Serious Concerns: Consider Maha Mrityunjaya Homa for overall protection", "गम्भीर चिन्ताहरू: समग्र सुरक्षाको लागि महा मृत्युञ्जय होम विचार गर्नुहोस्"),
    REMEDY_SHADASHTAK("Shadashtak (6-8) Dosha: Perform Rudrabhishek and donate medicines to the needy", "षडाष्टक (६-८) दोष: रुद्राभिषेक गर्नुहोस् र जरुरतमन्दलाई औषधि दान गर्नुहोस्"),
    REMEDY_SHANI_MANTRA_DESC("Recite 'Om Sham Shanaishcharaya Namah' 108 times daily", "'ॐ शं शनैश्चराय नमः' दैनिक १०८ पटक जप गर्नुहोस्"),
    REMEDY_SHANI_MANTRA_TITLE("Shani Mantra", "शनि मन्त्र"),
    REMEDY_SHARE("Share", "साझा गर्नुहोस्"),
    REMEDY_SHRADDHA_DESC("Perform annual death anniversary rituals for departed ancestors", "दिवंगत पुर्खाको वार्षिक मृत्यु वर्षगाँठ विधि गर्नुहोस्"),
    REMEDY_SHRADDHA_TITLE("Shraddha Ceremony", "श्राद्ध विधि"),
    REMEDY_TIMING_DASHA("During {0}''s dasha/antardasha periods", "{0} को दशा/अन्तर्दशा अवधिमा"),
    REMEDY_TIMING_HORA("Daily during {0}''s hora", "दैनिक {0} को होरामा"),
    REMEDY_TIMING_MORNING("{0} mornings", "{0} बिहान"),
    REMEDY_TIMING_MUHURTA("During auspicious muhurta on {0}", "{0} मा शुभ मुहूर्तको समयमा"),
    REMEDY_TIMING_REGULAR("{0}s regularly", "नियमित {0} मा"),
    REMEDY_TITLE("Recommendations", "सिफारिसहरू"),
    REMEDY_TUESDAY_CHARITY_DESC("Donate red lentils, red cloth, or copper items on Tuesdays", "मंगलबार रातो दाल, रातो कपडा, वा तामाका सामान दान गर्नुहोस्"),
    REMEDY_TUESDAY_CHARITY_TITLE("Tuesday Charity", "मंगलबार दान"),
    REMEDY_VEDHA_1("Vedha Dosha: Perform Nakshatra Shanti puja for both birth stars", "वेध दोष: दुवै जन्म नक्षत्रको लागि नक्षत्र शान्ति पूजा गर्नुहोस्"),
    REMEDY_VEDHA_2("Vedha Dosha: Donate black sesame and urad dal on Saturdays", "वेध दोष: शनिबारमा कालो तिल र उडदको दाल दान गर्नुहोस्"),
    REMEDY_WORSHIP_TEMPLATE("Worshipping %s deity can bring blessings for %s.",
        "%s देवताको पूजा गर्दा %s को लागि आशीर्वाद ल्याउन सक्छ।"),
    REMEDY_YONI_1("Yoni Incompatibility: Worship Kamadeva (God of Love) and offer flowers on Fridays", "योनि असंगतता: शुक्रबारमा कामदेव (प्रेमको देवता) पूजा गर्नुहोस् र फूल चढाउनुहोस्"),
    REMEDY_YONI_2("Yoni Incompatibility: Perform Ashwamedha or Gajamedha symbolic puja to neutralize animal enmity", "योनि असंगतता: पशु वैमनस्य निष्क्रिय गर्न अश्वमेध वा गजमेध प्रतीकात्मक पूजा गर्नुहोस्")
}
