package com.astro.storm.core.common

enum class StringKeyGeneralPart1(override val en: String, override val ne: String) : StringKeyInterface {
    ACADEMIC_CHALLENGES("Academic Challenges", "शैक्षिक चुनौतीहरू"),
    ACADEMIC_STRENGTHS("Academic Strengths", "शैक्षिक शक्तिहरू"),
    ACCUMULATION_PATTERN("Wealth Accumulation Pattern", "धन संचय ढाँचा"),
    ACTION_BUSINESS("Business", "व्यापार"),
    ACTION_CHARITY("Charity", "दान"),
    ACTION_CLEAR("Clear", "खाली गर्नुहोस्"),
    ACTION_CLEAR_SEARCH("Clear search", "खोज खाली गर्नुहोस्"),
    ACTION_COPY("Copy", "कपी गर्नुहोस्"),
    ACTION_COPY_MANTRA("Copy mantra", "मन्त्र कपी गर्नुहोस्"),
    ACTION_CREATIVE_WORK("Creative work", "सिर्जनात्मक काम"),
    ACTION_EDUCATION("Education", "शिक्षा"),
    ACTION_EXPORT("Export", "निर्यात गर्नुहोस्"),
    ACTION_FASTING("Fasting", "उपवास"),
    ACTION_FINANCIAL_MATTERS("Financial matters", "वित्तीय मामिलाहरू"),
    ACTION_GOVERNMENT_WORK("Government work", "सरकारी काम"),
    ACTION_LEGAL_MATTERS("Legal matters", "कानुनी मामिलाहरू"),
    ACTION_MARRIAGE("Marriage", "विवाह"),
    ACTION_MEDITATION("Meditation", "ध्यान"),
    ACTION_NEW_BEGINNINGS("New beginnings", "नयाँ सुरुवातहरू"),
    ACTION_NEW_QUESTION("New question", "नयाँ प्रश्न"),
    ACTION_PROPERTY_MATTERS("Property matters", "सम्पत्ति मामिलाहरू"),
    ACTION_SEARCH("Search", "खोज्नुहोस्"),
    ACTION_SPIRITUAL_PRACTICES("Spiritual practices", "आध्यात्मिक अभ्यास"),
    ACTION_STARTING_VENTURES("Starting ventures", "उद्यमहरू सुरु गर्दै"),
    ACTION_SURGERY("Surgery", "शल्यक्रिया"),
    ACTION_TRAVEL("Travel", "यात्रा"),
    ACTION_VIEW_DETAILS("View details", "विवरणहरू हेर्नुहोस्"),
    ACTION_VIEW_FULLSCREEN("View fullscreen", "पूर्ण स्क्रिनमा हेर्नुहोस्"),
    ACTION_WORSHIP("Worship", "पूजा"),
    ACTIVATED("Activated", "सक्रिय"),
    ACTIVATED_YOGAS("Activated Yogas", "सक्रिय योगहरू"),
    ACTIVATION_JUPITER("When Jupiter transits over or aspects natal {0}", "जब बृहस्पति जन्म {0} माथि गोचर गर्दछ वा दृष्टि दिन्छ"),
    ACTIVATION_PERIOD("Activation Period", "सक्रियता अवधि"),
    ACTIVATION_PRIMARY("{0} Mahadasha - Primary yoga activation period", "{0} महादशा - प्राथमिक योग सक्रियता अवधि"),
    ACTIVATION_SECONDARY("{0} Antardasha - Secondary activation in any major period", "{0} अन्तर्दशा - कुनै पनि मुख्य अवधिमा माध्यमिक सक्रियता"),
    ACTIVATION_STRENGTH("Activation Strength", "सक्रियता शक्ति"),
    ACTIVATION_TRANSIT("When {0} transits its natal position or exaltation sign", "जब {0} आफ्नो जन्म स्थिति वा उच्च राशिमा गोचर गर्दछ"),
    ACTIVE("Active", "सक्रिय"),
    ACTIVE_BADGE("ACTIVE", "सक्रिय"),
    ACTIVE_SAHAMS_TODAY("Active Sahams today", "आज सक्रिय सहमहरू"),
    ACTIVITY_BUSINESS_ACT("Business activities", "व्यापारिक गतिविधिहरू"),
    ACTIVITY_BUSINESS_DESC("Opening shop, new ventures", "पसल खोल्ने, नयाँ उद्यमहरू"),
    ACTIVITY_BUSINESS_NAME("Business", "व्यापार"),
    ACTIVITY_CHARITY("Charity", "दान"),
    ACTIVITY_CONTRACTS_AGREEMENTS("Contracts and agreements", "सम्झौता र सम्झौताहरू"),
    ACTIVITY_EDUCATION_DESC("Admissions, starting studies", "भर्ना, अध्ययन सुरु"),
    ACTIVITY_EDUCATION_NAME("Education", "शिक्षा"),
    ACTIVITY_FINANCIAL_INVEST("Financial investments", "वित्तीय लगानी"),
    ACTIVITY_GENERAL_DESC("General auspicious activities", "सामान्य शुभ गतिविधिहरू"),
    ACTIVITY_GENERAL_NAME("General", "सामान्य"),
    ACTIVITY_GRIHA_PRAVESHA_DESC("House warming", "गृह प्रवेश"),
    ACTIVITY_GRIHA_PRAVESHA_NAME("Griha Pravesha", "गृह प्रवेश"),
    ACTIVITY_HIGH_RISK_INVEST("High-risk investments", "उच्च जोखिमको लगानी"),
    ACTIVITY_IMPORTANT_DECISIONS("Important decisions", "महत्त्वपूर्ण निर्णयहरू"),
    ACTIVITY_IMPORTANT_MEETINGS("Important meetings", "महत्त्वपूर्ण बैठकहरू"),
    ACTIVITY_IMPORTANT_NEGOTIATIONS("Important negotiations", "महत्त्वपूर्ण वार्ता"),
    ACTIVITY_MAJOR_ACT("All major activities", "सबै प्रमुख गतिविधिहरू"),
    ACTIVITY_MAJOR_PURCHASES("Major purchases", "ठूला खरिदहरू"),
    ACTIVITY_MARRIAGE("Marriage ceremonies", "विवाह समारोह"),
    ACTIVITY_MARRIAGE_DESC("Wedding ceremonies, engagement", "विवाह समारोह, इन्गेज्मेन्ट"),
    ACTIVITY_MARRIAGE_NAME("Marriage", "विवाह"),
    ACTIVITY_MEDICAL_DESC("Surgery, treatment start", "शल्यक्रिया, उपचार सुरु"),
    ACTIVITY_MEDICAL_NAME("Medical", "चिकित्सा"),
    ACTIVITY_MEDICAL_PROCEDURES("Medical procedures", "चिकित्सा प्रक्रियाहरू"),
    ACTIVITY_MEDICAL_TREATMENT("Medical treatments", "चिकित्सा उपचार"),
    ACTIVITY_NAMING_DESC("Naming ceremony", "नामकरण समारोह"),
    ACTIVITY_NAMING_NAME("Naming", "न्वारन"),
    ACTIVITY_NEW_BEGINNINGS("New beginnings", "नयाँ सुरुवात"),
    ACTIVITY_NEW_VENTURES("New ventures", "नयाँ उद्यमहरू"),
    ACTIVITY_ONGOING_PROJECTS("Ongoing projects", "चलिरहेका परियोजनाहरू"),
    ACTIVITY_PRAYER_MEDITATION("Prayers and meditation", "प्रार्थना र ध्यान"),
    ACTIVITY_PROPERTY_DESC("Buying/selling land, house", "जग्गा, घर खरीद/बिक्री"),
    ACTIVITY_PROPERTY_NAME("Property", "सम्पत्ति"),
    ACTIVITY_REST_RECOVERY("Rest and recovery", "आराम र स्वास्थ्य लाभ"),
    ACTIVITY_ROUTINE_ACT("Routine activities", "नियमित गतिविधिहरू"),
    ACTIVITY_ROUTINE_WORK("Routine work", "नियमित काम"),
    ACTIVITY_SHORT_TRAVEL("Short travels", "छोटो यात्राहरू"),
    ACTIVITY_SOCIAL_EVENTS("Social events", "सामाजिक कार्यक्रमहरू"),
    ACTIVITY_SPIRITUAL_DESC("Initiation, ceremonies", "दीक्षा, समारोहहरू"),
    ACTIVITY_SPIRITUAL_NAME("Spiritual", "आध्यात्मिक"),
    ACTIVITY_SPIRITUAL_PRACTICES("Spiritual practices", "आध्यात्मिक अभ्यासहरू"),
    ACTIVITY_START_BUSINESS("Starting new business", "नयाँ व्यवसाय सुरु गर्दै"),
    ACTIVITY_SURGERIES("Surgeries", "शल्यक्रियाहरू"),
    ACTIVITY_TRAVEL("Travel", "यात्रा"),
    ACTIVITY_TRAVEL_DESC("Long journeys, business trips", "लामो यात्रा, व्यापारिक यात्रा"),
    ACTIVITY_TRAVEL_NAME("Travel", "यात्रा"),
    ACTIVITY_VEHICLE_DESC("Buying new vehicle", "नयाँ सवारी साधन खरीद"),
    ACTIVITY_VEHICLE_NAME("Vehicle", "सवारी साधन"),
    ACT_DISPOSITOR_MOON("As Moon''s dispositor, activates Moon-related yogas", "चन्द्रमाको मालिकको रूपमा, चन्द्रमा सम्बन्धी योगहरू सक्रिय गर्दछ"),
    ACT_MOON_FORMING("Moon is the yoga-forming planet", "चन्द्रमा योग बनाउने ग्रह हो"),
    ACT_RAHU_ANXIETY("Rahu amplifies mental anxieties", "राहुले मानसिक चिन्ता बढाउँछ"),
    ACT_SATURN_ISOLATION("Saturn increases feelings of separation", "शनिले अलगावको भावना बढाउँछ"),
    ADDITIONAL_FACTORS_TITLE("Additional Compatibility Factors", "अतिरिक्त अनुकूलता कारकहरू"),
    ADVICE_AIR_ELEMENT("Engage in social activities and intellectual pursuits.", "सामाजिक क्रियाकलापहरू र बौद्धिक खोजमा संलग्न हुनुहोस्।"),
    ADVICE_CHALLENGING("Today presents challenges with %s Tara and Moon in %dth house. Exercise caution in all matters. Postpone important decisions if possible. Focus on spiritual practices and inner strength.", "आज %s तारा र %dऔं भावमा चन्द्रमा भएकाले चुनौतीहरू छन्। सबै कुरामा सावधानी अपनाउनुहोस्। सम्भव भएमा महत्त्वपूर्ण निर्णयहरू स्थगित गर्नुहोस्। आध्यात्मिक अभ्यास र आन्तरिक शक्तिमा ध्यान दिनुहोस्।"),
    ADVICE_EARTH_ELEMENT("Focus on practical matters and material progress.", "व्यावहारिक मामिलाहरू र भौतिक प्रगतिमा ध्यान दिनुहोस्।"),
    ADVICE_FAVORABLE("Today offers good support from the cosmic energies. Tarabala is %s and Moon's position in the %dth house provides %s results. Proceed with confidence in normal activities.", "आज ब्रह्माण्डीय ऊर्जाहरूबाट राम्रो सहयोग मिल्नेछ। तारबल %s छ र चन्द्रमाको %dऔं भावमा स्थितिको कारण %s परिणाम मिल्नेछ। सामान्य गतिविधिहरू आत्मविश्वासका साथ अगाडि बढाउनुहोस्।"),
    ADVICE_FIRE_ELEMENT("Take bold action and express yourself confidently.", "साहसिक कदम चाल्नुहोस् र आत्मविश्वासका साथ आफूलाई अभिव्यक्त गर्नुहोस्।"),
    ADVICE_GENERAL("maintain balance and trust in divine timing.", "सन्तुलन कायम राख्नुहोस् र ईश्वरीय समयमा विश्वास गर्नुहोस्।"),
    ADVICE_HIGHLY_AUSPICIOUS("Today is highly auspicious with both Tarabala (%s) and Chandrabala supporting your activities. This is an excellent day for important decisions, new beginnings, and significant undertakings. Make the most of this favorable alignment.", "आज तारबल (%s) र चन्द्रबल दुवैले तपाईका गतिविधिहरूलाई समर्थन गर्ने भएकाले धेरै शुभ छ। महत्त्वपूर्ण निर्णयहरू, नयाँ सुरुवात र ठूला कार्यहरूका लागि यो उत्कृष्ट दिन हो। यस अनुकूल समयको अधिकतम सदुपयोग गर्नुहोस्।"),
    ADVICE_JUPITER("embrace opportunities for learning and expansion. Your wisdom and optimism attract positive outcomes.", "सिकाई र विस्तारका अवसरहरूलाई अँगाल्नुहोस्। तपाईंको ज्ञान र आशावादले सकारात्मक परिणामहरू आकर्षित गर्दछ।"),
    ADVICE_KETU("focus on spiritual growth and letting go. Detachment brings peace.", "आध्यात्मिक वृद्धि र त्यागमा ध्यान दिनुहोस्। वैराग्यले शान्ति ल्याउँछ।"),
    ADVICE_MARS("channel your energy into productive activities. Exercise and competition are favored.", "आफ्नो ऊर्जालाई उत्पादक गतिविधिहरूमा लगाउनुहोस्। व्यायाम र प्रतिस्पर्धालाई प्राथमिकता दिइन्छ।"),
    ADVICE_MERCURY("prioritize communication, learning, and intellectual activities. Your mind is sharp.", "सञ्चार, सिकाई, र बौद्धिक गतिविधिहरूलाई प्राथमिकता दिनुहोस्। तपाईंको दिमाग तेज छ।"),
    ADVICE_MIXED("Mixed influences today require balanced approach. While %s Tara brings %s, Chandrabala shows %s strength. Focus on routine matters and avoid extremes.", "आजको मिश्रित प्रभावले सन्तुलित दृष्टिकोणको आवश्यकता देखाउँछ। %s ताराले %s ल्याउँदा, चन्द्रबलले %s बल देखाउँछ। नियमित मामिलामा ध्यान दिनुहोस् र चरम सीमाबाट बच्नुहोस्।"),
    ADVICE_MOON("honor your emotions and intuition. Nurturing activities bring fulfillment.", "आफ्ना भावना र अन्तर्ज्ञानको सम्मान गर्नुहोस्। पोषण गर्ने गतिविधिहरूले सन्तुष्टि ल्याउँछ।"),
    ADVICE_RAHU("embrace transformation while staying grounded. Unconventional approaches may succeed.", "आधारभूत मूल्यहरूमा रहँदै परिवर्तनलाई अँगाल्नुहोस्। अपरम्परागत दृष्टिकोणहरू सफल हुन सक्छन्।"),
    ADVICE_SATURN("embrace discipline and patience. Hard work now builds lasting foundations for the future.", "अनुशासन र धैर्यलाई अँगाल्नुहोस्। अहिलेको कडा परिश्रमले भविष्यको लागि स्थायी आधार निर्माण गर्दछ।"),
    ADVICE_SUN("let your light shine. Leadership roles and self-expression bring recognition.", "आफ्नो चमक फैलिन दिनुहोस्। नेतृत्वदायी भूमिका र आत्म-अभिव्यक्तिले पहिचान दिलाउँछ।"),
    ADVICE_UNFAVORABLE("Caution advised today. The %s Tara combined with Moon's position creates unfavorable conditions. This is not suitable for any important activity. Focus on prayers, charity, and rest. Wait for better cosmic alignment before proceeding with significant matters.", "आज सावधानी अपनाउन सल्लाह दिइन्छ। %s तारा र चन्द्रमाको स्थितिले प्रतिकूल परिस्थिति सिर्जना गर्दछ। यो कुनै पनि महत्त्वपूर्ण गतिविधिको लागि उपयुक्त छैन। प्रार्थना, दान र आराममा ध्यान दिनुहोस्। महत्त्वपूर्ण कार्यहरू अघि बढाउनु अघि राम्रो समयको पर्खाइ गर्नुहोस्।"),
    ADVICE_VENUS("focus on cultivating beauty, harmony, and meaningful relationships. Artistic pursuits are favored.", "सौन्दर्य, सामञ्जस्य, र अर्थपूर्ण सम्बन्धहरू विकास गर्नमा ध्यान दिनुहोस्। कलात्मक कार्यहरूलाई प्राथमिकता दिइन्छ।"),
    ADVICE_WATER_ELEMENT("Trust your intuition and honor your emotions.", "आफ्नो अन्तर्ज्ञानमा विश्वास गर्नुहोस् र भावनाहरूलाई सम्मान गर्नुहोस्।"),
    ADVICE_WEEKLY_TEMPLATE("This week shows an average strength score of %d%%. %d out of 7 days are favorable for important activities. Best day is %s with %d%% strength. Avoid major decisions on %s (%d%% strength). Plan your important activities accordingly.", "यो हप्ताको औसत शक्ति स्कोर %d%% छ। ७ मध्ये %d दिन महत्त्वपूर्ण गतिविधिहरूका लागि अनुकूल छन्। सबैभन्दा राम्रो दिन %s हो जसमा %d%% शक्ति छ। %s (%d%% शक्ति) मा प्रमुख निर्णयहरू लिनबाट बच्नुहोस्। आफ्ना महत्त्वपूर्ण गतिविधिहरू तदनुसार योजना बनाउनुहोस्।"),
    AFFECTED_AREAS("Affected Areas", "प्रभावित क्षेत्रहरू"),
    AFFL_GRAHAN("Eclipse-like effect on planet's significations", "ग्रहको कारकत्वमा ग्रहण जस्तो प्रभाव"),
    AFFL_GRAHAN_HIDDEN("Hidden matters surfacing", "लुकेका कुराहरू बाहिर आउने"),
    AFFL_GRAHAN_SUDDEN("Sudden obstacles and confusions", "अचानक अवरोध र भ्रम"),
    AFFL_KANYA("Debt towards unmarried girls/daughters", "अविवाहित केटी/छोरीहरूप्रतिको ऋण"),
    AFFL_KANYA_CHILD("Female child related matters", "छोरी सम्बन्धी मामिलाहरू"),
    AFFL_KANYA_EDU("Education disruptions", "शिक्षामा अवरोध"),
    AFFL_MATRU("Debt towards mother figure", "माता समान व्यक्तिप्रतिको ऋण"),
    AFFL_MATRU_PEACE("Mental peace disturbances", "मानसिक शान्तिमा अवरोध"),
    AFFL_MATRU_PROP("Property and comfort matters affected", "सम्पत्ति र सुख-सुविधाका मामिलाहरू प्रभावित"),
    AFFL_PITRU("Ancestral karma affecting current life", "वर्तमान जीवनलाई प्रभावित गर्ने पुर्ख्यौली कर्म"),
    AFFL_PITRU_HEALTH("Health issues related to father's lineage", "पिताको वंशसँग सम्बन्धित स्वास्थ्य समस्या"),
    AFFL_PITRU_PROGENY("Obstacles in progeny matters", "सन्तान सम्बन्धी मामिलामा अवरोध"),
    AFFL_SHANI("Saturn's restrictive influence", "शनिको प्रतिबन्धात्मक प्रभाव"),
    AFFL_SHANI_DELAY("Delays and obstacles", "ढिलाइ र अवरोधहरू"),
    AFFL_SHANI_INTENSE("Karmic lessons intensified", "कार्मिक पाठहरू तीव्र पारिएको"),
    AFFL_STRI("Debt towards women/wife", "महिला/पत्नीप्रतिको ऋण"),
    AFFL_STRI_FIN("Financial fluctuations", "आर्थिक उतार-चढाव"),
    AFFL_STRI_MARR("Marriage and relationship challenges", "विवाह र सम्बन्धमा चुनौतीहरू"),
    AFF_DEFAULT("I am aligned with cosmic energies and flow with life's rhythm.", "म ब्रह्माण्डीय ऊर्जाहरूसँग संरेखित छु र जीवनको लयसँगै बग्छु।"),
    AFF_JUPITER("I am open to abundance and share my wisdom generously.", "म प्रचुरताको लागि खुला छु र आफ्नो ज्ञान उदारतापूर्वक साझा गर्छु।"),
    AFF_KETU("I release what no longer serves me and embrace spiritual growth.", "म जुन कुराले अब मेरो सेवा गर्दैन त्यसलाई छाड्छु र आध्यात्मिक वृद्धिलाई अँगाल्छु।"),
    AFF_MARS("I channel my energy constructively and act with courage.", "म आफ्नो ऊर्जा रचनात्मक रूपमा प्रयोग गर्छु र साहसका साथ काम गर्छु।"),
    AFF_MERCURY("I communicate clearly and embrace continuous learning.", "म स्पष्ट रूपमा सञ्चार गर्छु र निरन्तर सिकाइलाई अँगाल्छु।"),
    AFF_MOON("I trust my intuition and nurture myself with compassion.", "म आफ्नो अन्तर्ज्ञानमाथि विश्वास गर्छु र करुणाका साथ आफूलाई पोषण गर्छु।"),
    AFF_RAHU("I embrace change and transform challenges into opportunities.", "म परिवर्तनलाई अँगाल्छु र चुनौतीहरूलाई अवसरहरूमा रूपान्तरण गर्छु।"),
    AFF_SATURN("I embrace discipline and trust in the timing of my journey.", "म अनुशासनलाई अँगाल्छु र आफ्नो यात्राको समयमाथि विश्वास गर्छु।"),
    AFF_SUN("I shine my light confidently and inspire those around me.", "म आत्मविश्वासका साथ आफ्नो प्रकाश फैलाउँछु र वरिपरिका मानिसहरूलाई प्रेरित गर्छु।"),
    AFF_VENUS("I attract beauty and harmony into my life.", "म आफ्नो जीवनमा सौन्दर्य र सामञ्जस्य आकर्षित गर्छु।"),
    AGE_RELATION("Partner Age Relation", "साथी उमेर सम्बन्ध"),
    AI_ANALYZING_QUESTION("Analyzing your question...", "तपाईंको प्रश्न विश्लेषण गर्दै..."),
    AI_GENERATING("Generating...", "उत्पन्न गर्दैछ..."),
    AI_MODELS_BACK("Back", "पछाडि"),
    AI_MODELS_CANCEL("Cancel", "रद्द गर्नुहोस्"),
    AI_MODELS_DEFAULT("Default Model", "पूर्वनिर्धारित मोडेल"),
    AI_MODELS_DISABLE_ALL("Disable All", "सबै असक्षम गर्नुहोस्"),
    AI_MODELS_ENABLED_COUNT("%d models enabled", "%d मोडेलहरू सक्षम"),
    AI_MODELS_ENABLE_ALL("Enable All", "सबै सक्षम गर्नुहोस्"),
    AI_MODELS_FREE_DESC("These models are provided by free API providers and don't require any API keys. Model availability may vary.", "यी मोडेलहरू निःशुल्क API प्रदायकहरूबाट प्रदान गरिएका हुन् र कुनै API कुञ्जी आवश्यक पर्दैन। मोडेल उपलब्धता फरक हुन सक्छ।"),
    AI_MODELS_FREE_TITLE("Free AI Models", "निःशुल्क AI मोडेलहरू"),
    AI_MODELS_MODELS_ENABLED("%d/%d models enabled", "%d/%d मोडेलहरू सक्षम"),
    AI_MODELS_NONE("No Models Available", "कुनै मोडेल उपलब्ध छैन"),
    AI_MODELS_NONE_DESC("Unable to fetch AI models. Check your internet connection and try again.", "AI मोडेलहरू प्राप्त गर्न असमर्थ। आफ्नो इन्टरनेट जडान जाँच गर्नुहोस् र पुन: प्रयास गर्नुहोस्।"),
    AI_MODELS_NOT_SET("Not set", "सेट गरिएको छैन"),
    AI_MODELS_REASONING("Reasoning", "तर्क"),
    AI_MODELS_REFRESH("Refresh models", "मोडेलहरू रिफ्रेस गर्नुहोस्"),
    AI_MODELS_RETRY("Retry", "पुन: प्रयास गर्नुहोस्"),
    AI_MODELS_SELECT_DEFAULT("Select Default Model", "पूर्वनिर्धारित मोडेल छान्नुहोस्"),
    AI_MODELS_TITLE("AI Models", "AI मोडेलहरू"),
    AI_MODELS_TOOLS("Tools", "उपकरणहरू"),
    AI_MODELS_VISION("Vision", "दृष्टि"),
    AI_PROVIDER_BLACKBOX("Blackbox AI", "ब्ल्याकबक्स AI"),
    AI_PROVIDER_DDG("DuckDuckGo AI", "डकडकगो AI"),
    AI_PROVIDER_DEEPINFRA("DeepInfra", "डीपइन्फ्रा"),
    AI_PROVIDER_QWEN("Qwen", "क्वेन"),
    ALTERNATIVE_GEMSTONE("Alternative Gemstone", "वैकल्पिक रत्न"),
    ANALYTICAL_ABILITY("Analytical Ability", "विश्लेषणात्मक क्षमता"),
    ANIMAL_BUFFALO("Male Buffalo", "भाले भैंसी (राँगो)"),
    ANIMAL_CAT("Male Cat", "भाले बिरालो"),
    ANIMAL_COW("Male Cow", "भाले गाई (साँढे)"),
    ANIMAL_DEER("Male Deer", "भाले मृग"),
    ANIMAL_DOG("Male Dog", "भाले कुकुर"),
    ANIMAL_ELEPHANT("Male Elephant", "भाले हात्ती"),
    ANIMAL_FEMALE_BUFFALO("Female Buffalo", "पोथी भैंसी"),
    ANIMAL_FEMALE_CAT("Female Cat", "पोथी बिरालो"),
    ANIMAL_FEMALE_COW("Female Cow", "पोथी गाई"),
    ANIMAL_FEMALE_DEER("Female Deer", "पोथी मृग"),
    ANIMAL_FEMALE_DOG("Female Dog", "पोथी कुकुर"),
    ANIMAL_FEMALE_ELEPHANT("Female Elephant", "पोथी हात्ती"),
    ANIMAL_FEMALE_HORSE("Female Horse", "पोथी घोडा"),
    ANIMAL_FEMALE_LION("Female Lion", "पोथी सिंह"),
    ANIMAL_FEMALE_MONGOOSE("Female Mongoose", "पोथी न्याउरी मुसो"),
    ANIMAL_FEMALE_MONKEY("Female Monkey", "पोथी बाँदर"),
    ANIMAL_FEMALE_RAT("Female Rat", "पोथी मुसो"),
    ANIMAL_FEMALE_SERPENT("Female Serpent", "पोथी सर्प"),
    ANIMAL_FEMALE_SHEEP("Female Sheep", "पोथी भेडा"),
    ANIMAL_FEMALE_TIGER("Female Tiger", "पोथी बाघ"),
    ANIMAL_HORSE("Male Horse", "भाले घोडा"),
    ANIMAL_LION("Male Lion", "भाले सिंह"),
    ANIMAL_MONGOOSE("Male Mongoose", "भाले न्याउरी मुसो"),
    ANIMAL_MONKEY("Male Monkey", "भाले बाँदर"),
    ANIMAL_RAT("Male Rat", "भाले मुसो"),
    ANIMAL_SERPENT("Male Serpent", "भाले सर्प"),
    ANIMAL_SHEEP("Male Sheep", "भाले भेडा"),
    ANIMAL_TIGER("Male Tiger", "भाले बाघ"),
    APPEARANCE_BODY_TYPE("Body Type", "शरीर प्रकार"),
    APPEARANCE_COMPLEXION("Complexion", "रंग"),
    APPEARANCE_FACE("Facial Features", "अनुहार विशेषताहरू"),
    APPEARANCE_OVERALL("Overall Appearance", "समग्र रूप"),
    APPEARANCE_TITLE("Physical Appearance", "शारीरिक रूप"),
    APPLYING("Applying", "लागू हुँदै"),
    AREA_ACCIDENTS("Accidents", "दुर्घटना"),
    AREA_BLOOD("Blood", "रगत"),
    AREA_BONES("Bones", "हड्डी"),
    AREA_BREASTS("Breasts", "स्तन"),
    AREA_BURNS("Burns", "पोलेको"),
    AREA_CAREER("Career", "करियर"),
    AREA_CHRONIC("Chronic Conditions", "पुरानो रोग"),
    AREA_EARS("Ears", "कान"),
    AREA_EDUCATION("Education", "शिक्षा"),
    AREA_EMOTIONS("Emotions", "भावना"),
    AREA_EYES("Eyes", "आँखा"),
    AREA_FACE("Face", "अनुहार"),
    AREA_FAMILY("Family", "परिवार"),
    AREA_FAT("Fat Tissues", "बोसो तन्तु"),
    AREA_FLUIDS("Fluids", "तरल पदार्थ"),
    AREA_FOREIGN_CONNECTIONS("Foreign Connections", "विदेशी सम्बन्ध"),
    AREA_GENERAL("General Life", "सामान्य जीवन"),
    AREA_HEAD("Head", "टाउको"),
    AREA_HEALTH("Health", "स्वास्थ्य"),
    AREA_HEART("Heart", "मुटु"),
    AREA_INFECTIONS("Infections", "संक्रमण"),
    AREA_JOINTS("Joints", "जोर्नी"),
    AREA_KIDNEYS("Kidneys", "मृगौला"),
    AREA_LIVER("Liver", "कलेजो"),
    AREA_LUNGS("Lungs", "फोक्सो"),
    AREA_MIND("Mind", "मन"),
    AREA_MUSCLES("Muscles", "मांसपेशी"),
    AREA_NERVOUS("Nervous System", "स्नायु प्रणाली"),
    AREA_POISONS("Poisons", "विष"),
    AREA_RELATIONSHIP("Relationships", "सम्बन्धहरू"),
    AREA_RELATIONSHIPS("Relationships", "सम्बन्ध"),
    AREA_REPRO("Reproductive System", "प्रजनन प्रणाली"),
    AREA_SKIN("Skin", "छाला"),
    AREA_SPEECH("Speech", "वाणी"),
    AREA_SPINE("Spine", "मेरुदण्ड"),
    AREA_SPIRITUAL("Spirituality", "आध्यात्मिकता"),
    AREA_SPIRITUALITY("Spirituality", "आध्यात्मिकता"),
    AREA_SPIRIT_CRISIS("Spiritual Crises", "आध्यात्मिक संकट"),
    AREA_STOMACH("Stomach", "पेट"),
    AREA_TEETH("Teeth", "दाँत"),
    AREA_THIGHS("Thighs", "तिघ्रा"),
    AREA_THROAT("Throat", "घाँटी"),
    AREA_UNKNOWN_DIS("Unknown Diseases", "अज्ञात रोग"),
    AREA_VITALITY("Vitality", "जीवनशक्ति"),
    AREA_WEALTH("Wealth", "धन"),
    AREA_WOUNDS("Wounds", "चोट"),
    ARGALA_ABOUT("About Argala", "अर्गलाको बारेमा"),
    ARGALA_ABOUT_DESC("Argala is a Jaimini system showing how planets in certain houses create interventions (Argala) that influence the results of other houses. Understanding Argala helps predict how life events unfold.", "अर्गला एक जैमिनी प्रणाली हो जसले निश्चित भावहरूमा ग्रहहरूले कसरी हस्तक्षेप (अर्गला) सिर्जना गर्छन् जसले अन्य भावहरूको परिणामलाई प्रभावित गर्छ भनेर देखाउँछ। अर्गला बुझ्दा जीवनका घटनाहरू कसरी प्रकट हुन्छन् भनेर भविष्यवाणी गर्न मद्दत गर्छ।"),
    ARGALA_ASHUBHA("Ashubha Argala (Malefic)", "अशुभ अर्गला (हानिकारक)"),
    ARGALA_CALCULATING("Calculating Argala...", "अर्गला गणना गर्दै..."),
    ARGALA_CHART_WIDE_PATTERNS("Chart-Wide Argala Patterns", "कुण्डली-व्यापी अर्गाला ढाँचाहरू"),
    ARGALA_ELEVENTH_HOUSE("11th House Argala", "एकादश भाव अर्गला"),
    ARGALA_FAILED("Failed to calculate Argala", "अर्गला गणना गर्न असफल"),
    ARGALA_FIFTH_HOUSE("5th House Argala", "पञ्चम भाव अर्गला"),
    ARGALA_FIFTH_HOUSE_DESC("5th house creates special interventions", "पाँचौं भावले विशेष हस्तक्षेप सिर्जना गर्दछ"),
    ARGALA_FOURTH_HOUSE("4th House Argala", "चतुर्थ भाव अर्गला"),
    ARGALA_FROM_HOUSE("From House %d", "भाव %d बाट"),
    ARGALA_GREATEST_CHALLENGE("Greatest Challenge", "सबैभन्दा ठूलो चुनौती"),
    ARGALA_HOUSE_SELECTOR_LABEL("Select House to Analyze", "विश्लेषण गर्न भाव चयन गर्नुहोस्"),
    ARGALA_HOUSE_STRENGTH("House Argala Strength", "भाव अर्गला बल"),
    ARGALA_KARMA_ARTHA("Artha Argala", "अर्थ अर्गला"),
    ARGALA_KARMA_DHARMA("Dharma Argala", "धर्म अर्गला"),
    ARGALA_KARMA_KAMA("Kama Argala", "काम अर्गला"),
    ARGALA_KARMA_MOKSHA("Moksha Argala", "मोक्ष अर्गला"),
    ARGALA_KARMA_PATTERNS("Karma Patterns", "कर्म ढाँचाहरू"),
    ARGALA_LEAST_OBSTRUCTED("Least Obstructed", "कम से कम बाधित"),
    ARGALA_MIXED("Mixed", "मिश्रित"),
    ARGALA_MOST_OBSTRUCTED("Most Obstructed", "सबैभन्दा बाधित"),
    ARGALA_NEGATIVE("Negative", "नकारात्मक"),
    ARGALA_NET_EFFECT("Net Effect", "शुद्ध प्रभाव"),
    ARGALA_OBSTRUCTED("Obstructed Argala", "बाधित अर्गला"),
    ARGALA_PLANET_CAUSES("Planet Argala Effects", "ग्रह अर्गला प्रभाव"),
    ARGALA_POSITIVE("Positive", "सकारात्मक"),
    ARGALA_PRIMARY("Primary Argala", "प्राथमिक अर्गला"),
    ARGALA_PRIMARY_DESC("4th & 11th houses create primary interventions", "चौथो र एघारौं भावले प्राथमिक हस्तक्षेप सिर्जना गर्दछ"),
    ARGALA_SECONDARY("Secondary Argala", "माध्यमिक अर्गला"),
    ARGALA_SECONDARY_DESC("2nd house creates secondary interventions", "दोस्रो भावले माध्यमिक हस्तक्षेप सिर्जना गर्दछ"),
    ARGALA_SECOND_HOUSE("2nd House Argala", "द्वितीय भाव अर्गला"),
    ARGALA_SELECT_HOUSE("Select House to Analyze", "विश्लेषण गर्न भाव चयन गर्नुहोस्"),
    ARGALA_SHUBHA("Shubha Argala (Benefic)", "शुभ अर्गला (लाभकारी)"),
    ARGALA_SIGNIFICANT_ARGALAS("Significant Argalas", "महत्वपूर्ण अर्गालाहरू"),
    ARGALA_STRENGTH_MODERATE("Moderate", "मध्यम"),
    ARGALA_STRENGTH_OBSTRUCTED("Obstructed", "बाधित"),
    ARGALA_STRENGTH_STRONG("Strong", "बलियो"),
    ARGALA_STRENGTH_VERY_STRONG("Very Strong", "धेरै बलियो"),
    ARGALA_STRENGTH_WEAK("Weak", "कमजोर"),
    ARGALA_STRONGEST_SUPPORT("Strongest Support", "सबैभन्दा बलियो समर्थन"),
    ARGALA_SUBTITLE("Jaimini Intervention System", "जैमिनी हस्तक्षेप प्रणाली"),
    ARGALA_TITLE("Argala Analysis", "अर्गला विश्लेषण"),
    ARGALA_TO_HOUSE("To House %d", "भाव %d मा"),
    ARGALA_TYPES_TITLE("Argala Types", "अर्गलाका प्रकारहरू"),
    ARGALA_UNOBSTRUCTED("Unobstructed Argala", "अबाधित अर्गला"),
    ARGALA_VIRODHA("Virodha Argala (Obstruction)", "विरोध अर्गला (बाधा)"),
    ARGALA_VIRODHA_DESC("12th, 10th, 3rd, 9th houses obstruct Argala", "१२औं, १०औं, ३औं, र ९औं भावले अर्गालालाई बाधा पुर्‍याउँछ"),
    ARUDHA_ABOUT_BTN("About Arudha Pada", "आरुढ पदको बारेमा"),
    ARUDHA_ANALYSIS_TITLE("Arudha Pada Analysis", "आरुढ पद विश्लेषण"),
    ARUDHA_CALCULATING("Calculating Arudha Padas...", "आरुढ पद गणना गर्दै..."),
    ARUDHA_CAREER("Career", "क्यारियर"),
    ARUDHA_GAINS("Gains", "लाभ"),
    ARUDHA_KEY_POSITIONS("Key Arudha Positions", "मुख्य आरुढ स्थितिहरू"),
    ARUDHA_KEY_THEMES("Key Themes", "मुख्य विषयवस्तुहरू"),
    ARUDHA_MANIFESTATION("Manifestation Strength", "प्रकटीकरण शक्ति"),
    ARUDHA_PUBLIC_IMAGE("Public Image", "सार्वजनिक छवि"),
    ARUDHA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    ARUDHA_RELATIONSHIPS("Relationships", "सम्बन्धहरू"),
    ARUDHA_SCREEN_TITLE("Arudha Pada", "आरुढ पद"),
    ARUDHA_YOGAS_TITLE("Arudha Yogas", "आरुढ योगहरू"),
    ASCENDANT("Ascendant", "लग्न"),
    ASCENDANT_HEALTH("Ascendant Health Profile", "लग्न स्वास्थ्य प्रोफाइल"),
    ASCETIC_TENDENCIES("Ascetic Tendencies", "त्याग प्रवृत्तिहरू"),
    ASC_AQUARIUS_DESC("Innovative, humanitarian, independent personality", "नवीन, मानवतावादी, स्वतन्त्र व्यक्तित्व"),
    ASC_AQUARIUS_TITLE("Aquarius Rising", "कुम्भ लग्न"),
    ASC_ARIES_DESC("Bold, pioneering, action-oriented personality", "साहसी, अग्रगामी, कार्य-उन्मुख व्यक्तित्व"),
    ASC_ARIES_TITLE("Aries Rising", "मेष लग्न"),
    ASC_CANCER_DESC("Nurturing, emotional, family-oriented personality", "पालनपोषण गर्ने, भावनात्मक, परिवार-उन्मुख व्यक्तित्व"),
    ASC_CANCER_TITLE("Cancer Rising", "कर्कट लग्न"),
    ASC_CAPRICORN_DESC("Ambitious, disciplined, achievement-oriented personality", "महत्वाकांक्षी, अनुशासित, उपलब्धि-उन्मुख व्यक्तित्व"),
    ASC_CAPRICORN_TITLE("Capricorn Rising", "मकर लग्न"),
    ASC_GEMINI_DESC("Curious, communicative, mentally agile personality", "जिज्ञासु, सञ्चारी, मानसिक रूपमा चुस्त व्यक्तित्व"),
    ASC_GEMINI_TITLE("Gemini Rising", "मिथुन लग्न"),
    ASC_LEO_DESC("Confident, creative, natural leader personality", "आत्मविश्वासी, रचनात्मक, प्राकृतिक नेता व्यक्तित्व"),
    ASC_LEO_TITLE("Leo Rising", "सिंह लग्न"),
    ASC_LIBRA_DESC("Diplomatic, harmonious, relationship-focused personality", "कूटनीतिक, सामंजस्यपूर्ण, सम्बन्ध-केन्द्रित व्यक्तित्व"),
    ASC_LIBRA_TITLE("Libra Rising", "तुला लग्न"),
    ASC_PISCES_DESC("Intuitive, compassionate, spiritually inclined personality", "अन्तर्ज्ञानी, दयालु, आध्यात्मिक रूपमा झुकाव भएको व्यक्तित्व"),
    ASC_PISCES_TITLE("Pisces Rising", "मीन लग्न"),
    ASC_SAGITTARIUS_DESC("Adventurous, philosophical, freedom-loving personality", "साहसिक, दार्शनिक, स्वतन्त्रता-प्रेमी व्यक्तित्व"),
    ASC_SAGITTARIUS_TITLE("Sagittarius Rising", "धनु लग्न"),
    ASC_SCORPIO_DESC("Intense, transformative, deeply perceptive personality", "तीव्र, परिवर्तनकारी, गहिरो बोधगम्य व्यक्तित्व"),
    ASC_SCORPIO_TITLE("Scorpio Rising", "वृश्चिक लग्न"),
    ASC_TAURUS_DESC("Steady, sensual, materially focused personality", "स्थिर, संवेदी, भौतिक रूपमा केन्द्रित व्यक्तित्व"),
    ASC_TAURUS_TITLE("Taurus Rising", "वृष लग्न"),
    ASC_VIRGO_DESC("Analytical, service-oriented, detail-focused personality", "विश्लेषणात्मक, सेवा-उन्मुख, विस्तार-केन्द्रित व्यक्तित्व"),
    ASC_VIRGO_TITLE("Virgo Rising", "कन्या लग्न"),
    ASHTAK_ANALYSIS_HEADER("ASHTAKAVARGA ANALYSIS", "अष्टकवर्ग विश्लेषण"),
    ASHTAK_AVG_PER_SIGN("Average per Sign:", "प्रति राशि औसत:"),
    ASHTAK_BAV_AVERAGE("3 (Average)", "३ (औसत)"),
    ASHTAK_BAV_GOOD("4 (Good)", "४ (राम्रो)"),
    ASHTAK_BAV_HEADER("BHINNASHTAKAVARGA (Individual Planet Strengths)", "भिन्नाष्टकवर्ग (व्यक्तिगत ग्रह बल)"),
    ASHTAK_BAV_INDIVIDUAL_DESC("Individual planet strength in each sign (0-8 bindus)", "प्रत्येक राशिमा व्यक्तिगत ग्रहको बल (०-८ बिन्दु)"),
    ASHTAK_BAV_STRONG("5+ (Strong)", "५+ (बलियो)"),
    ASHTAK_BAV_TITLE("Bhinnashtakavarga (BAV)", "भिन्नाष्टकवर्ग (BAV)"),
    ASHTAK_BAV_WEAK("0-2 (Weak)", "०-२ (कमजोर)"),
    ASHTAK_CHALLENGING_SIGNS("Challenging Signs (<25):", "चुनौतीपूर्ण राशिहरू (<२५):"),
    ASHTAK_FAVORABLE_SIGNS("Favorable Signs (28+):", "अनुकूल राशिहरू (२८+):"),
    ASHTAK_GENERAL_EFFECTS("general matters", "सामान्य मामिलाहरू"),
    ASHTAK_GUIDE_BAV_02("0-2 bindus: Difficult transit period", "०-२ बिन्दु: कठिन गोचर अवधि"),
    ASHTAK_GUIDE_BAV_3("3 bindus: Average, neutral results", "३ बिन्दु: औसत, तटस्थ परिणामहरू"),
    ASHTAK_GUIDE_BAV_4("4 bindus: Good results from transit", "४ बिन्दु: गोचरबाट राम्रो परिणाम"),
    ASHTAK_GUIDE_BAV_5("5+ bindus: Planet transit highly beneficial", "५+ बिन्दु: ग्रह गोचर अत्यधिक लाभदायक"),
    ASHTAK_GUIDE_BAV_TITLE("Bhinnashtakavarga (BAV)", "भिन्नाष्टकवर्ग (BAV)"),
    ASHTAK_GUIDE_SAV_25("25-27 bindus: Average - mixed results expected", "२५-२७ बिन्दु: औसत - मिश्रित परिणामहरू अपेक्षित"),
    ASHTAK_GUIDE_SAV_28("28-29 bindus: Good for transits - favorable outcomes", "२८-२९ बिन्दु: गोचरको लागि राम्रो - अनुकूल परिणामहरू"),
    ASHTAK_GUIDE_SAV_30("30+ bindus: Excellent for transits - major positive events", "३०+ बिन्दु: गोचरको लागि उत्कृष्ट - प्रमुख सकारात्मक घटनाहरू"),
    ASHTAK_GUIDE_SAV_BELOW("Below 25: Challenging - caution during transits", "२५ भन्दा कम: चुनौतीपूर्ण - गोचरमा सावधानी"),
    ASHTAK_GUIDE_SAV_TITLE("Sarvashtakavarga (SAV)", "सर्वाष्टकवर्ग (SAV)"),
    ASHTAK_GUIDE_TITLE("Interpretation Guide", "व्याख्या गाइड"),
    ASHTAK_GUIDE_TRANSIT_1("Check SAV of the sign a planet transits", "ग्रहले गोचर गर्ने राशिको SAV जाँच गर्नुहोस्"),
    ASHTAK_GUIDE_TRANSIT_2("Check BAV score of that planet in transited sign", "गोचर गरिएको राशिमा त्यो ग्रहको BAV स्कोर जाँच गर्नुहोस्"),
    ASHTAK_GUIDE_TRANSIT_3("High combined scores = favorable transit", "उच्च संयुक्त स्कोर = अनुकूल गोचर"),
    ASHTAK_GUIDE_TRANSIT_4("Use for timing important decisions", "महत्त्वपूर्ण निर्णयहरूको समयको लागि प्रयोग गर्नुहोस्"),
    ASHTAK_GUIDE_TRANSIT_TITLE("Transit Application", "गोचर अनुप्रयोग"),
    ASHTAK_HOUSE_10_MATTERS("career, status, authority", "क्यारियर, हैसियत, अधिकार"),
    ASHTAK_HOUSE_11_MATTERS("gains, friends, aspirations", "लाभ, साथीहरू, आकांक्षाहरू"),
    ASHTAK_HOUSE_12_MATTERS("losses, spirituality, foreign", "हानि, आध्यात्मिकता, विदेश"),
    ASHTAK_HOUSE_1_MATTERS("self, personality, health", "आफू, व्यक्तित्व, स्वास्थ्य"),
    ASHTAK_HOUSE_2_MATTERS("wealth, family, speech", "धन, परिवार, वाणी"),
    ASHTAK_HOUSE_3_MATTERS("courage, siblings, communication", "साहस, भाइबहिनी, सञ्चार"),
    ASHTAK_HOUSE_4_MATTERS("home, mother, comfort", "घर, आमा, आराम"),
    ASHTAK_HOUSE_5_MATTERS("children, intelligence, romance", "सन्तान, बुद्धि, प्रेम"),
    ASHTAK_HOUSE_6_MATTERS("enemies, health issues, service", "शत्रु, स्वास्थ्य समस्या, सेवा"),
    ASHTAK_HOUSE_7_MATTERS("partnership, marriage, business", "साझेदारी, विवाह, व्यापार"),
    ASHTAK_HOUSE_8_MATTERS("transformation, inheritance, occult", "रूपान्तरण, सम्पत्ति, गुप्त विद्या"),
    ASHTAK_HOUSE_9_MATTERS("luck, father, higher learning", "भाग्य, पिता, उच्च शिक्षा"),
    ASHTAK_JUPITER_EFFECTS("wisdom, children, fortune, spirituality", "ज्ञान, सन्तान, भाग्य, आध्यात्मिकता"),
    ASHTAK_MARS_EFFECTS("energy, siblings, property, courage", "ऊर्जा, भाइबहिनी, सम्पत्ति, साहस"),
    ASHTAK_MERCURY_EFFECTS("communication, intellect, business, education", "सञ्चार, बुद्धि, व्यापार, शिक्षा"),
    ASHTAK_MOON_EFFECTS("mind, emotions, mother, public image", "मन, भावना, आमा, सार्वजनिक छवि"),
    ASHTAK_NOT_APPLICABLE("Ashtakavarga not applicable for %s", "%s को लागि अष्टकवर्ग लागू हुँदैन"),
    ASHTAK_QUICK_ANALYSIS("Quick Analysis", "द्रुत विश्लेषण"),
    ASHTAK_SATURN_EFFECTS("career, longevity, discipline, challenges", "क्यारियर, दीर्घायु, अनुशासन, चुनौतीहरू"),
    ASHTAK_SAV_AVERAGE("25-27 (Average)", "२५-२७ (औसत)"),
    ASHTAK_SAV_COMBINED_DESC("Combined strength of all planets in each sign", "प्रत्येक राशिमा सबै ग्रहहरूको संयुक्त बल"),
    ASHTAK_SAV_EXCELLENT("30+ (Excellent)", "३०+ (उत्कृष्ट)"),
    ASHTAK_SAV_GOOD("28-29 (Good)", "२८-२९ (राम्रो)"),
    ASHTAK_SAV_HEADER("SARVASHTAKAVARGA (Combined Strength)", "सर्वाष्टकवर्ग (संयुक्त बल)"),
    ASHTAK_SAV_TITLE("Sarvashtakavarga (SAV)", "सर्वाष्टकवर्ग (SAV)"),
    ASHTAK_SAV_WEAK("<25 (Weak)", "<२५ (कमजोर)"),
    ASHTAK_SIGNS_COUNT("%d signs", "%d राशिहरू"),
    ASHTAK_STRONGEST("Strongest", "सबैभन्दा बलियो"),
    ASHTAK_SUMMARY("Ashtakavarga Summary", "अष्टकवर्ग सारांश"),
    ASHTAK_SUN_EFFECTS("authority, father, health, government, career", "अधिकार, पिता, स्वास्थ्य, सरकार, क्यारियर"),
    ASHTAK_TOTAL("Total", "कुल"),
    ASHTAK_TOTAL_SAV("Total SAV", "कुल SAV"),
    ASHTAK_TOTAL_SAV_BINDUS("Total SAV Bindus:", "कुल SAV बिन्दुहरू:"),
    ASHTAK_VENUS_EFFECTS("relationships, luxury, arts, vehicles", "सम्बन्ध, विलासिता, कला, सवारी")
}
