package com.astro.storm.core.common

enum class StringKeyPrashnaPart1(override val en: String, override val ne: String) : StringKeyInterface {
    PRASHNA_ABOUT("About Prashna", "प्रश्न बारेमा"),
    PRASHNA_ACTIVE("Active", "सक्रिय"),
    PRASHNA_AI_ANALYZING("Consulting the stars...", "ताराहरूसँग परामर्श गर्दै..."),
    PRASHNA_AI_INSIGHT("AI Insight", "एआई अन्तर्दृष्टि"),
    PRASHNA_AI_INSIGHT_DESC("Get a deeper, personalized interpretation of your Prashna chart using AI. The AI will analyze the planetary positions and yogas to provide additional guidance.", "एआई प्रयोग गरेर आफ्नो प्रश्न चार्टको गहिरो, व्यक्तिगत व्याख्या प्राप्त गर्नुहोस्। एआईले थप मार्गदर्शन प्रदान गर्न ग्रह स्थिति र योगहरूको विश्लेषण गर्नेछ।"),
    PRASHNA_AI_INSIGHT_SUBTITLE("Powered by Stormy", "Stormy द्वारा संचालित"),
    PRASHNA_ANALYSIS_FAILED("Analysis Failed", "विश्लेषण असफल"),
    PRASHNA_ANALYZE("Analyze Question", "प्रश्न विश्लेषण गर्नुहोस्"),
    PRASHNA_ANALYZE_ERROR("Failed to analyze question", "प्रश्न विश्लेषण गर्न असफल"),
    PRASHNA_ANALYZING("Analyzing your question...", "तपाईंको प्रश्न विश्लेषण गर्दै..."),
    PRASHNA_ARUDHA("Arudha Lagna", "आरूढ लग्न"),
    PRASHNA_ARUDHA_CALCULATION("Arudha Calculation", "आरूढ गणना"),
    PRASHNA_ARUDHA_DESC("Manifestation point for the question", "प्रश्नको प्रकटीकरण बिन्दु"),
    PRASHNA_ARUDHA_LAGNA("Prashna Arudha Lagna", "प्रश्न आरूढ लग्न"),
    PRASHNA_ASPECT_CONJUNCTION("Conjunction", "युति"),
    PRASHNA_ASPECT_FORMING("Aspect Forming", "पक्ष गठन हुँदैछ"),
    PRASHNA_ASPECT_JUPITER_5TH("Jupiter 5th Aspect", "गुरु ५ औं दृष्टि"),
    PRASHNA_ASPECT_JUPITER_9TH("Jupiter 9th Aspect", "गुरु ९ औं दृष्टि"),
    PRASHNA_ASPECT_MARS_4TH("Mars 4th Aspect", "मंगल ४ औं दृष्टि"),
    PRASHNA_ASPECT_MARS_8TH("Mars 8th Aspect", "मंगल ८ औं दृष्टि"),
    PRASHNA_ASPECT_OPPOSITION("Opposition", "सप्तम"),
    PRASHNA_ASPECT_SATURN_10TH("Saturn 10th Aspect", "शनि १० औं दृष्टि"),
    PRASHNA_ASPECT_SATURN_3RD("Saturn 3rd Aspect", "शनि ३ रो दृष्टि"),
    PRASHNA_ASPECT_SEPARATING("Aspect Separating", "पक्ष विघटन हुँदैछ"),
    PRASHNA_ASPECT_SEXTILE("Sextile", "षष्ठ"),
    PRASHNA_ASPECT_SQUARE("Square", "चतुर्थ"),
    PRASHNA_ASPECT_TRINE("Trine", "त्रिकोण"),
    PRASHNA_BODY_ARMS_SHOULDERS("Arms/Shoulders", "हात/काँध"),
    PRASHNA_BODY_BELOW_NAVEL("Below Navel", "नाभि मुनि"),
    PRASHNA_BODY_CALVES_ANKLES("Calves/Ankles", "पिँडुला/कुर्कुच्चा"),
    PRASHNA_BODY_CHEST("Chest", "छाती"),
    PRASHNA_BODY_FACE_MOUTH("Face/Mouth", "अनुहार/मुख"),
    PRASHNA_BODY_FEET("Feet", "गोडा"),
    PRASHNA_BODY_HEAD("Head", "टाउको"),
    PRASHNA_BODY_KNEES("Knees", "घुँडा"),
    PRASHNA_BODY_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
    PRASHNA_BODY_PRIVATE_PARTS("Private Parts", "गुप्ताङ्ग"),
    PRASHNA_BODY_THIGHS("Thighs", "तिघ्रा"),
    PRASHNA_BODY_UPPER_ABDOMEN("Upper Abdomen", "माथिल्लो पेट"),
    PRASHNA_CALCULATING("Calculating planetary positions and yogas", "ग्रह स्थिति र योगहरू गणना गर्दै"),
    PRASHNA_CATEGORY("Question Category", "प्रश्न वर्ग"),
    PRASHNA_CAT_BUSINESS("Business", "व्यापार"),
    PRASHNA_CAT_BUSINESS_DESC("Business partnership and deals", "व्यापार साझेदारी र सौदाहरू"),
    PRASHNA_CAT_CAREER("Career", "क्यारियर"),
    PRASHNA_CAT_CAREER_DESC("Job, profession, and career-related questions", "जागिर, पेशा र क्यारियर सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_CHILDREN("Children", "सन्तान"),
    PRASHNA_CAT_CHILDREN_DESC("Questions about children and progeny", "सन्तान र सन्ततिका बारेमा प्रश्नहरू"),
    PRASHNA_CAT_EDUCATION("Education", "शिक्षा"),
    PRASHNA_CAT_EDUCATION_DESC("Studies and educational questions", "अध्ययन र शैक्षिक प्रश्नहरू"),
    PRASHNA_CAT_FINANCE("Finance", "वित्त"),
    PRASHNA_CAT_GENERAL("General", "सामान्य"),
    PRASHNA_CAT_GENERAL_DESC("General questions and queries", "सामान्य प्रश्नहरू"),
    PRASHNA_CAT_HEALTH("Health", "स्वास्थ्य"),
    PRASHNA_CAT_HEALTH_DESC("Health and illness-related questions", "स्वास्थ्य र रोग सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_LEGAL("Legal", "कानुनी"),
    PRASHNA_CAT_LEGAL_DESC("Court cases and legal matters", "मुद्दा-मामिला र कानुनी विषयहरू"),
    PRASHNA_CAT_LOST("Lost Object Questions", "हराएको वस्तु प्रश्नहरू"),
    PRASHNA_CAT_LOST_ITEM("Lost Items", "हराएका वस्तुहरू"),
    PRASHNA_CAT_LOST_OBJECT("Lost Object", "हराएको वस्तु"),
    PRASHNA_CAT_LOST_OBJECT_DESC("Finding lost or stolen items", "हराएको वा चोरी भएको वस्तु खोज्ने"),
    PRASHNA_CAT_MARRIAGE("Marriage", "विवाह"),
    PRASHNA_CAT_MARRIAGE_DESC("Marriage and spouse-related questions", "विवाह र जीवनसाथी सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_MISSING("Missing Person Questions", "हराएको व्यक्ति प्रश्नहरू"),
    PRASHNA_CAT_PROGENY("Progeny Questions", "सन्तान प्रश्नहरू"),
    PRASHNA_CAT_PROPERTY("Property", "सम्पत्ति"),
    PRASHNA_CAT_PROPERTY_DESC("Real estate and property questions", "जग्गा-जमिन र सम्पत्ति सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_RELATIONSHIP("Relationship", "सम्बन्ध"),
    PRASHNA_CAT_RELATIONSHIP_DESC("Love and relationship questions", "प्रेम र सम्बन्ध सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_SPIRITUAL("Spiritual", "आध्यात्मिक"),
    PRASHNA_CAT_SPIRITUAL_DESC("Spiritual and religious questions", "आध्यात्मिक र धार्मिक प्रश्नहरू"),
    PRASHNA_CAT_TRAVEL("Travel", "यात्रा"),
    PRASHNA_CAT_TRAVEL_DESC("Journey and travel-related questions", "यात्रा सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_WEALTH("Wealth", "धन-सम्पत्ति"),
    PRASHNA_CAT_WEALTH_DESC("Financial and wealth-related questions", "आर्थिक र धन-सम्पत्ति सम्बन्धी प्रश्नहरू"),
    PRASHNA_CAT_YES_NO("Yes/No", "हो/होइन"),
    PRASHNA_CAT_YES_NO_DESC("Simple yes or no questions", "साधारण हो वा होइन प्रश्नहरू"),
    PRASHNA_CERTAINTY_HIGH("High Certainty", "उच्च निश्चितता"),
    PRASHNA_CERTAINTY_LOW("Low Certainty", "न्यून निश्चितता"),
    PRASHNA_CERTAINTY_MODERATE("Moderate Certainty", "मध्यम निश्चितता"),
    PRASHNA_CERTAINTY_VERY_HIGH("Very High Certainty", "अत्यधिक निश्चितता"),
    PRASHNA_CERTAINTY_VERY_LOW("Very Low Certainty", "अति न्यून निश्चितता"),
    PRASHNA_CHALLENGES("Challenges", "चुनौतीहरू"),
    PRASHNA_CHART_LABEL("Prashna Chart", "प्रश्न कुण्डली"),
    PRASHNA_COLOR_BLACK("Black", "कालो"),
    PRASHNA_COLOR_BROWN("Brown", "खैरो"),
    PRASHNA_COLOR_GOLDEN("Golden", "सुनौलो"),
    PRASHNA_COLOR_GOLDEN_YELLOW("Golden-Yellow", "सुनौलो-पहेंलो"),
    PRASHNA_COLOR_GREEN("Green", "हरियो"),
    PRASHNA_COLOR_GREY_BLUE("Grey-Blue", "खरानी-नीलो"),
    PRASHNA_COLOR_MULTI("Multi-colored", "बहुरंगी"),
    PRASHNA_COLOR_ORANGE("Orange", "सुन्तला"),
    PRASHNA_COLOR_RED("Red", "रातो"),
    PRASHNA_COLOR_WHITE("White", "सेतो"),
    PRASHNA_COLOR_YELLOW("Yellow", "पहेंलो"),
    PRASHNA_COMPLETION("Matter Completion", "विषय पूर्णता"),
    PRASHNA_COMPLETION_INDICATORS("Completion Indicators", "पूर्णता संकेतकहरू"),
    PRASHNA_CONDITION("Condition", "अवस्था"),
    PRASHNA_CONFIDENCE("%s%% confidence", "%s%% विश्वास"),
    PRASHNA_D10_CAREER("D-10 for Career Questions", "क्यारियर प्रश्नको लागि D-10"),
    PRASHNA_D4_PROPERTY("D-4 for Property Questions", "सम्पत्ति प्रश्नको लागि D-4"),
    PRASHNA_D7_PROGENY("D-7 for Progeny Questions", "सन्तान प्रश्नको लागि D-7"),
    PRASHNA_D9_MARRIAGE("D-9 for Marriage Questions", "विवाह प्रश्नको लागि D-9"),
    PRASHNA_DAYS("Days", "दिनहरू"),
    PRASHNA_DELAYED("Delayed/Obstructed", "ढिलो/अवरुद्ध"),
    PRASHNA_DIRECTION("Direction", "दिशा"),
    PRASHNA_DIRECTION_SEARCH("Direction to search", "खोज्ने दिशा"),
    PRASHNA_DIR_EAST("East", "पूर्व"),
    PRASHNA_DIR_EAST_NORTH("North-East", "उत्तर-पूर्व"),
    PRASHNA_DIR_NORTH("North", "उत्तर"),
    PRASHNA_DIR_NORTH_EAST("North-East", "उत्तर-पूर्व"),
    PRASHNA_DIR_NORTH_WEST("North-West", "उत्तर-पश्चिम"),
    PRASHNA_DIR_SOUTH("South", "दक्षिण"),
    PRASHNA_DIR_SOUTH_EAST("South-East", "दक्षिण-पूर्व"),
    PRASHNA_DIR_SOUTH_WEST("South-West", "दक्षिण-पश्चिम"),
    PRASHNA_DIR_WEST("West", "पश्चिम"),
    PRASHNA_DISTANCE("Distance", "दूरी"),
    PRASHNA_ENHANCED_DESC("Complete Prashna analysis with Arudha, divisional charts, Itthasala aspects, and specialized predictions", "आरूढ, विभागीय चार्टहरू, इत्थशाला पक्षहरू, र विशेष भविष्यवाणीहरू सहित पूर्ण प्रश्न विश्लेषण"),
    PRASHNA_ENHANCED_SUBTITLE("Advanced Horary Techniques", "उन्नत होरारी प्रविधिहरू"),
    PRASHNA_ENHANCED_TITLE("Enhanced Prashna", "उन्नत प्रश्न"),
    PRASHNA_ESTIMATED_TIMEFRAME("Estimated Timeframe", "अनुमानित समयावधि"),
    PRASHNA_FACTOR_HOUSES_AFFLICTED("Relevant houses are afflicted", "सम्बन्धित भावहरू पीडित छन्"),
    PRASHNA_FACTOR_HOUSES_FAVORABLE("Relevant houses are well-disposed", "सम्बन्धित भावहरू अनुकूल छन्"),
    PRASHNA_FACTOR_LAGNA_COMBUST("Lagna lord is combust", "लग्नेश अस्त छ"),
    PRASHNA_FACTOR_LAGNA_MODERATE("Lagna has moderate strength", "लग्नको बल औसत छ"),
    PRASHNA_FACTOR_LAGNA_RETRO("Lagna lord is retrograde", "लग्नेश वक्री छ"),
    PRASHNA_FACTOR_LAGNA_STRONG("Lagna and its lord are strong", "लग्न र लग्नेश बलियो छ"),
    PRASHNA_FACTOR_LAGNA_WEAK("Lagna is weak", "लग्न कमजोर छ"),
    PRASHNA_FACTOR_MOON_AFFLICTED("Moon is severely afflicted", "चन्द्रमा गम्भीर रूपमा पीडित छ"),
    PRASHNA_FACTOR_MOON_AVERAGE("Moon has moderate strength", "चन्द्रमाको बल औसत छ"),
    PRASHNA_FACTOR_MOON_EXCELLENT("Moon is exceptionally strong", "चन्द्रमा अत्यन्त बलियो छ"),
    PRASHNA_FACTOR_MOON_GOOD("Moon is well-placed and strong", "चन्द्रमा राम्रो अवस्थामा र बलियो छ"),
    PRASHNA_FACTOR_MOON_VERY_WEAK("Moon is very weak or afflicted", "चन्द्रमा धेरै कमजोर वा पीडित छ"),
    PRASHNA_FACTOR_MOON_VOID("Moon is Void of Course", "चन्द्रमा शून्य अवस्थामा छ"),
    PRASHNA_FACTOR_MOON_WANING("Moon is waning (decreasing strength)", "चन्द्रमा कृष्ण पक्षमा छ (बल घट्दै)"),
    PRASHNA_FACTOR_MOON_WAXING("Moon is waxing (increasing strength)", "चन्द्रमा शुक्ल पक्षमा छ (बल बढ्दै)"),
    PRASHNA_FACTOR_MOON_WEAK("Moon is weak", "चन्द्रमा कमजोर छ"),
    PRASHNA_FAR("Far", "टाढा"),
    PRASHNA_FAVORABLE("Favorable", "अनुकूल"),
    PRASHNA_FRUSTRATION_INDICATORS("Frustration Indicators", "निराशा संकेतकहरू"),
    PRASHNA_GENERATE_AI_INSIGHT("Generate AI Insight", "एआई अन्तर्दृष्टि उत्पन्न गर्नुहोस्"),
    PRASHNA_HORARY("Horary Astrology", "प्रश्न ज्योतिष"),
    PRASHNA_HOUSE_10_NAME("Karma", "कर्म"),
    PRASHNA_HOUSE_11_NAME("Labha", "लाभ"),
    PRASHNA_HOUSE_12_NAME("Vyaya", "व्यय"),
    PRASHNA_HOUSE_1_NAME("Lagna/Querent", "लग्न/प्रश्नकर्ता"),
    PRASHNA_HOUSE_2_NAME("Dhana", "धन"),
    PRASHNA_HOUSE_3_NAME("Sahaja", "सहज"),
    PRASHNA_HOUSE_4_NAME("Sukha", "सुख"),
    PRASHNA_HOUSE_5_NAME("Putra", "पुत्र"),
    PRASHNA_HOUSE_6_NAME("Ripu", "रिपु"),
    PRASHNA_HOUSE_7_NAME("Kalatra", "कलत्र"),
    PRASHNA_HOUSE_8_NAME("Ayu", "आयु"),
    PRASHNA_HOUSE_9_NAME("Dharma", "धर्म"),
    PRASHNA_HOUSE_AFFLICTED("Afflicted", "पीडित"),
    PRASHNA_HOUSE_EXCELLENT("Excellent", "उत्कृष्ट"),
    PRASHNA_HOUSE_GOOD("Good", "राम्रो"),
    PRASHNA_HOUSE_INTERP_TEMPLATE("Relevant Houses (%1\$s): %2\$s", "सम्बन्धित भावहरू (%1\$s): %2\$s"),
    PRASHNA_HOUSE_ITEM_TEMPLATE("House %1\$s: %2\$s", "भाव %1\$s: %2\$s"),
    PRASHNA_HOUSE_MODERATE("Moderate", "मध्यम"),
    PRASHNA_HOUSE_POOR("Poor", "कमजोर"),
    PRASHNA_INACTIVE("Inactive", "निष्क्रिय"),
    PRASHNA_INFO_DESC("Enhanced Prashna (Horary) analysis includes advanced techniques from Prashna Marga and Tajika traditions. Itthasala aspects show application/separation timing, while specialized analyses help with lost objects and missing persons.", "उन्नत प्रश्न (होरारी) विश्लेषणमा प्रश्न मार्ग र ताजिक परम्पराहरूबाट उन्नत प्रविधिहरू समावेश छन्। इत्थशाला पक्षहरूले आवेदन/अलगाव समय देखाउँछन्, जबकि विशेष विश्लेषणहरूले हराएको वस्तुहरू र हराएको व्यक्तिहरूमा मद्दत गर्छन्।"),
    PRASHNA_INFO_TITLE("About Enhanced Prashna", "उन्नत प्रश्नको बारेमा"),
    PRASHNA_INST_1("Prashna Kundali is cast for the moment the question arises in your mind or when you ask it.", "प्रश्न कुण्डली तपाईंको मनमा प्रश्न उठेको क्षणमा वा तपाईंले सोधेको बेला बनाइन्छ।"),
    PRASHNA_INST_2("The Moon is the primary significator representing your mind and the matter at hand.", "चन्द्रमा प्राथमिक कारक हो जसले तपाईंको मन र हातमा रहेको विषयलाई प्रतिनिधित्व गर्दछ।"),
    PRASHNA_INST_3("Frame your question with sincerity and focused intent for accurate guidance.", "सटीक मार्गदर्शनको लागि आफ्नो प्रश्न ईमानदारिता र केन्द्रित उद्देश्यसहित बनाउनुहोस्।"),
    PRASHNA_INST_4("The analysis considers Lagna, Moon, relevant houses, and special Prashna yogas.", "विश्लेषणले लग्न, चन्द्रमा, सम्बन्धित भावहरू, र विशेष प्रश्न योगहरूलाई विचार गर्छ।"),
    PRASHNA_INST_5("Timing predictions are based on planetary movements and house lord positions.", "समय भविष्यवाणीहरू ग्रह गतिविधि र भाव स्वामी स्थितिमा आधारित छन्।"),
    PRASHNA_INTRO("Ask your question and receive guidance based on the planetary positions at this very moment.", "आफ्नो प्रश्न सोध्नुहोस् र यस क्षणको ग्रह स्थितिको आधारमा मार्गदर्शन प्राप्त गर्नुहोस्।"),
    PRASHNA_ISARAFA("Isarafa (Separation)", "ईसराफ (अलगाव)"),
    PRASHNA_ISARAFA_DESC("Moon separating from planets - past influence", "चन्द्रमा ग्रहहरूबाट अलग हुँदै - बितेको प्रभाव"),
    PRASHNA_IS_ALIVE("Is Alive", "जीवित छ"),
    PRASHNA_ITTHASALA("Itthasala (Application)", "इत्थशाला"),
    PRASHNA_ITTHASALA_DESC("Moon applying to other planets - key for timing", "चन्द्रमा अन्य ग्रहहरूमा आवेदन - समयको लागि महत्त्वपूर्ण"),
    PRASHNA_KUNDALI("Prashna Kundali", "प्रश्न कुण्डली"),
    PRASHNA_LAGNA_ANALYSIS("Lagna Analysis", "लग्न विश्लेषण"),
    PRASHNA_LAGNA_COMBUST("Combust - Lord too close to Sun", "अस्त - स्वामी सूर्यको अत्यधिक नजिक"),
    PRASHNA_LAGNA_INTERP_TEMPLATE("Rising Sign: %1\$s. Lagna Lord %2\$s House %3\$s. Condition: %4\$s.%5\$s", "उदय राशि: %1\$s। लग्नेश %2\$s भाव %3\$s। अवस्था: %4\$s।%5\$s"),
    PRASHNA_LAGNA_LORD("Lagna Lord", "लग्नेश"),
    PRASHNA_LAGNA_MODERATE("Moderate - Mixed influences", "मध्यम - मिश्रित प्रभावहरू"),
    PRASHNA_LAGNA_RETROGRADE_LORD("Lord is Retrograde", "स्वामी वक्री छ"),
    PRASHNA_LAGNA_STRONG("Strong - Well placed lord", "बलियो - राम्रोसँग स्थापित स्वामी"),
    PRASHNA_LAGNA_WEAK("Weak - Afflicted or poorly placed", "कमजोर - पीडित वा खराब स्थापित"),
    PRASHNA_LOCATION("Question Location", "प्रश्न स्थान"),
    PRASHNA_LOCATION_TYPE("Location Type", "स्थान प्रकार"),
    PRASHNA_LORD_POSITION("Lord Position", "स्वामी स्थिति"),
    PRASHNA_LOST_OBJECT("Lost Object Analysis", "हराएको वस्तु विश्लेषण"),
    PRASHNA_METHOD_DASHA_BASED("Dasha-based Timing", "दशा आधारित समय"),
    PRASHNA_METHOD_HOUSE_LORD_DEGREES("House Lord Degrees", "भावेश अंश विधि"),
    PRASHNA_METHOD_LAGNA_DEGREES("Lagna Degrees Method", "लग्न अंश विधि"),
    PRASHNA_METHOD_MIXED("Combined Methods", "संयुक्त विधिहरू"),
    PRASHNA_METHOD_MOON_NAKSHATRA("Moon Nakshatra Method", "चन्द्र नक्षत्र विधि"),
    PRASHNA_METHOD_MOON_TRANSIT("Moon Transit Method", "चन्द्र गोचर विधि"),
    PRASHNA_METHOD_PLANETARY_CONJUNCTION("Planetary Conjunction", "ग्रह युति विधि"),
    PRASHNA_MISSING_PERSON("Missing Person Analysis", "हराएको व्यक्ति विश्लेषण"),
    PRASHNA_MONTHS("Months", "महिनाहरू"),
    PRASHNA_MOOK("Mook (Dumb) Prashna", "मूक प्रश्न"),
    PRASHNA_MOON_AFFLICTED("Afflicted", "पीडित"),
    PRASHNA_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
    PRASHNA_MOON_AVERAGE("Average", "औसत"),
    PRASHNA_MOON_EXCELLENT("Excellent", "उत्कृष्ट"),
    PRASHNA_MOON_GOOD("Good", "राम्रो"),
    PRASHNA_MOON_HOUSE_IND_TEMPLATE("House %s", "भाव %s"),
    PRASHNA_MOON_INTERP_TEMPLATE("Moon Analysis: %1\$s Position %2\$s House %3\$s. Phase %4\$s, %5\$s. Strength: %6\$s.%7\$s", "चन्द्र विश्लेषण: %1\$s स्थिति %2\$s भाव %3\$s। पक्ष %4\$s, %5\$s। बल: %6\$s।%7\$s"),
    PRASHNA_MOON_PHASE_WANING("Waning", "कृष्ण पक्ष"),
    PRASHNA_MOON_PHASE_WAXING("Waxing", "शुक्ल पक्ष"),
    PRASHNA_MOON_VERY_WEAK("Very Weak", "अत्यन्त कमजोर"),
    PRASHNA_MOON_VOID("Moon is Void of Course - delays or changes likely", "चन्द्र शून्य गतिमा छ - ढिलाइ वा परिवर्तन सम्भावित"),
    PRASHNA_MOON_WEAK("Weak", "कमजोर"),
    PRASHNA_NAKSHATRA_IND_TEMPLATE("%1\$s (Lord: %2\$s)", "%1\$s (स्वामी: %2\$s)"),
    PRASHNA_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
    PRASHNA_NAKTA("Nakta (Translation)", "नक्त (अनुवाद)"),
    PRASHNA_NAKTA_DESC("Light transferred through intermediary planet", "मध्यस्थ ग्रहमार्फत प्रकाश स्थानान्तरण"),
    PRASHNA_NEAR("Near", "नजिक"),
    PRASHNA_NEW_QUESTION("New question", "नयाँ प्रश्न"),
    PRASHNA_NO("No", "होइन"),
    PRASHNA_NO_PROBABILITY("No Probability", "होइन सम्भावना"),
    PRASHNA_OMEN_COMBUSTION("Combustion", "अस्त"),
    PRASHNA_OMEN_COMBUSTION_DESC("%s is combust", "%s अस्त छ"),
    PRASHNA_OMEN_COMBUST_IND("%s is Combust", "%s अस्त छ"),
    PRASHNA_OMEN_DAY_LORD("Day Lord", "दिन स्वामी"),
    PRASHNA_OMEN_DAY_LORD_DESC("Question on %s's day", "प्रश्न %s को बारमा"),
    PRASHNA_OMEN_GANDANTA("Gandanta Position", "गण्डान्त स्थिति"),
    PRASHNA_OMEN_GANDANTA_DESC("%s is in Gandanta", "%s गण्डान्तमा छ"),
    PRASHNA_OMEN_HORA_LORD("Hora Lord", "होरा स्वामी"),
    PRASHNA_OMEN_HORA_LORD_DESC("Question in %s Hora", "प्रश्न %s को होरामा"),
    PRASHNA_OMEN_LAGNA("Prashna Lagna Sign", "प्रश्न लग्न राशि"),
    PRASHNA_OMEN_LAGNA_DESC("Rising sign is %s", "उदय राशि %s हो"),
    PRASHNA_OMEN_MOON_PLACEMENT("Moon Placement", "चन्द्र स्थिति"),
    PRASHNA_OMEN_MOON_PLACEMENT_DESC("Moon in %s house (%s)", "चन्द्रमा %s भाव (%s) मा"),
    PRASHNA_OMEN_NAKSHATRA("Question Nakshatra", "प्रश्न नक्षत्र"),
    PRASHNA_OMEN_NAKSHATRA_DESC("Moon in %s Nakshatra", "चन्द्रमा %s नक्षत्रमा"),
    PRASHNA_OMEN_PLANETARY_WAR("Planetary War", "ग्रह युद्ध"),
    PRASHNA_OMEN_PLANETARY_WAR_DESC("%s in war with %s", "%s र %s बीच ग्रह युद्ध"),
    PRASHNA_OMEN_PUSHKARA_DESC("%s is in Pushkara Navamsha", "%s पुष्कर नवांशमा छ"),
    PRASHNA_OMEN_RETROGRADE("Retrograde Planet", "वक्री ग्रह"),
    PRASHNA_OMEN_RETROGRADE_DESC("%s is retrograde", "%s वक्री छ"),
    PRASHNA_OMEN_RETRO_IND("%s is Retrograde", "%s वक्री छ"),
    PRASHNA_OMEN_WAR_IND("Planetary War", "ग्रहयुद्ध"),
    PRASHNA_PHASE("Phase", "पक्ष"),
    PRASHNA_PLANETS_IN_LAGNA("Planets in Lagna", "लग्नमा ग्रहहरू"),
    PRASHNA_PLANETS_IN_LAGNA_TEMPLATE("Planets in Lagna: %s", "लग्नमा ग्रहहरू: %s"),
    PRASHNA_POSITIVE_FACTORS("Positive Factors", "सकारात्मक कारकहरू"),
    PRASHNA_PUSHKARA("Pushkara Navamsha", "पुष्कर नवांश"),
    PRASHNA_QUESTION_DETAILS("Question Details", "प्रश्न विवरण"),
    PRASHNA_QUESTION_HELP("Be specific and clear. Frame your question with a sincere intent.", "स्पष्ट र विशिष्ट हुनुहोस्। ईमानदार इरादाले आफ्नो प्रश्न बनाउनुहोस्।"),
    PRASHNA_QUESTION_HINT("Enter your question here...", "यहाँ आफ्नो प्रश्न प्रविष्ट गर्नुहोस्..."),
    PRASHNA_QUESTION_LOCATION("Question Location", "प्रश्नस्थान"),
    PRASHNA_REASON_CHALLENGES("Several challenging factors may hinder progress", "धेरै चुनौतीपूर्ण कारकहरूले प्रगतिमा बाधा पुर्याउन सक्छन्"),
    PRASHNA_REASON_STRONGLY_NO("Serious afflictions suggest unfavorable outcome", "गम्भीर पीडाहरूले प्रतिकूल परिणाम सुझाव दिन्छ"),
    PRASHNA_REASON_STRONGLY_YES("Multiple highly favorable factors indicate success", "धेरै अनुकूल कारकहरूले सफलता संकेत गर्छन्"),
    PRASHNA_REASON_UNCERTAIN("Mixed influences make the outcome uncertain", "मिश्रित प्रभावले परिणाम अनिश्चित बनाउँछ"),
    PRASHNA_REASON_YES("Favorable planetary positions support the matter", "अनुकूल ग्रह स्थितिले विषयलाई समर्थन गर्छ"),
    PRASHNA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    PRASHNA_RECOVERY_CHANCE("Recovery Chance", "प्राप्ति सम्भावना"),
    PRASHNA_RECOVERY_LIKELIHOOD("Recovery likelihood", "प्राप्ति सम्भावना"),
    PRASHNA_RECOVERY_OUTLOOK("Recovery outlook", "सुधारको दृष्टिकोण"),
    PRASHNA_REC_ABANDON("It is advisable to abandon or significantly modify this pursuit.", "यस प्रयासलाई छोड्नु वा महत्त्वपूर्ण रूपमा परिमार्जन गर्नु उचित हुन्छ।"),
    PRASHNA_REC_ACT_PROMPTLY("Act promptly while the favorable applying aspect is in effect.", "अनुकूल पक्ष प्रभावकारी हुँदा तुरुन्तै काम गर्नुहोस्।"),
    PRASHNA_REC_AVOID_CONFRONTATION("Avoid direct confrontation. Work behind the scenes temporarily.", "प्रत्यक्ष टकरावबाट बच्नुहोस्। अस्थायी रूपमा पर्दा पछाडि काम गर्नुहोस्।"),
    PRASHNA_REC_AWARENESS("Proceed with awareness. Minor adjustments may improve outcomes.", "सचेतताका साथ अगाडि बढ्नुहोस्। साना समायोजनहरूले नतिजाहरू सुधार्न सक्छन्।"),
    PRASHNA_REC_CAUTION("Proceed with caution. Carefully monitor developments.", "सावधानीका साथ अगाडि बढ्नुहोस्। विकासक्रमहरूलाई ध्यानपूर्वक निगरानी गर्नुहोस्।"),
    PRASHNA_REC_DELAY("Expect delays. Patience and persistence will be required.", "ढिलाइको अपेक्षा गर्नुहोस्। धैर्य र दृढता आवश्यक हुनेछ।"),
    PRASHNA_REC_EXPLORE("Explore alternative options or modify your plans.", "वैकल्पिक विकल्पहरू अन्वेषण गर्नुहोस् वा आफ्ना योजनाहरू परिमार्जन गर्नुहोस्।"),
    PRASHNA_REC_FOCUS_FAVORABLE("Focus energy on matters with more favorable indications.", "थप अनुकूल संकेत भएका विषयहरूमा ऊर्जा केन्द्रित गर्नुहोस्।"),
    PRASHNA_REC_GUIDANCE("Seek additional guidance or information before proceeding.", "अगाडि बढ्नु अघि थप मार्गदर्शन वा जानकारी खोज्नुहोस्।"),
    PRASHNA_REC_MUSARIPHA("The matter is already decided or opportunity has passed (Musaripha).", "विषय पहिले नै तय भइसकेको छ वा अवसर गुमेको छ (मुसरिफ)।"),
    PRASHNA_REC_OBSTACLES("Expect obstacles. Success through struggle is possible but not guaranteed.", "बाधाहरूको अपेक्षा गर्नुहोस्। संघर्ष मार्फत सफलता सम्भव छ तर ग्यारेन्टी छैन।"),
    PRASHNA_REC_PATIENCE("Exercise patience. Wait for clearer signs before major action.", "धैर्य धारण गर्नुहोस्। ठूलो कदम चाल्नु अघि स्पष्ट संकेतहरूको प्रतीक्षा गर्नुहोस्।"),
    PRASHNA_REC_PROCEED("Proceed with confidence. The cosmic conditions are supportive.", "आत्मविश्वासका साथ अगाडि बढ्नुहोस्। ब्रह्माण्डीय परिस्थितिहरू सहयोगी छन्।"),
    PRASHNA_REC_PROPITIATE("Propitiate %1\$s to strengthen %2\$sth house matters.", "%2\$s औं भावको विषयलाई बलियो बनाउन %1\$s लाई प्रसन्न पार्नुहोस्।"),
    PRASHNA_REC_REASK_NEW_SIGN("Consider re-asking when Moon enters a new sign.", "चन्द्रमा नयाँ राशिमा प्रवेश गरेपछि पुनः सोध्ने विचार गर्नुहोस्।"),
    PRASHNA_REC_RECONSIDER("Reconsider your approach. Current conditions are not supportive.", "आफ्नो दृष्टिकोण पुनर्विचार गर्नुहोस्। वर्तमान परिस्थितिहरू सहयोगी छैनन्।"),
    PRASHNA_REC_RETHINK("Rethink the approach. Significant obstacles or hidden factors detected.", "दृष्टिकोण पुनर्विचार गर्नुहोस्। महत्त्वपूर्ण बाधाहरू वा लुकेका कारकहरू पत्ता लागेका छन्।"),
    PRASHNA_REC_REVIEW_PAST("Review past decisions. Something may need to be reconsidered.", "विगतका निर्णयहरू समीक्षा गर्नुहोस्। केही कुरामा पुनर्विचार गर्नुपर्ने हुन सक्छ।"),
    PRASHNA_REC_SEEK_ASSISTANCE("Seek assistance from an intermediary or third party.", "मध्यस्थ वा तेस्रो पक्षबाट सहयोग खोज्नुहोस्।"),
    PRASHNA_REC_STRENGTHEN_MOON("Strengthen Moon energies through white colors, pearl, and Monday observances.", "सेतो रंग, मोती र सोमबारको व्रत मार्फत चन्द्रमाको ऊर्जालाई बलियो बनाउनुहोस्।"),
    PRASHNA_REC_STRONGLY_SUPPORT("Proceed with confidence. The chart strongly supports your endeavor.", "आत्मविश्वासका साथ अगाडि बढ्नुहोस्। कुण्डलीले तपाईंको प्रयासलाई दृढतापूर्वक समर्थन गर्दछ।"),
    PRASHNA_REC_UNFAVORABLE("Unfavorable conditions. Reconsider your objectives or approach.", "अतुलनीय परिस्थितिहरू। आफ्ना उद्देश्यहरू वा दृष्टिकोण पुनर्विचार गर्नुहोस्।"),
    PRASHNA_REC_VOID_MOON("The matter requires better timing. Moon is void of course.", "विषयको लागि राम्रो समय चाहिन्छ। चन्द्रमा शून्य (Void) छ।"),
    PRASHNA_REC_VOID_MOON_REASK("Consider re-asking when Moon enters a new sign.", "चन्द्रमा नयाँ राशिमा प्रवेश गरेपछि फेरि सोध्ने विचार गर्नुहोस्।"),
    PRASHNA_REC_WAIT("Wait for a better time. Current conditions are not conducive to success.", "राम्रो समयको लागि प्रतीक्षा गर्नुहोस्। वर्तमान परिस्थितिहरू सफलताको लागि अनुकूल छैनन्।"),
    PRASHNA_REC_WANING_MOON("Waning Moon suggests completion or ending phases. Good for finishing, not starting.", "कृष्ण पक्षको चन्द्रमाले समाप्ति वा अन्त्यको चरणलाई संकेत गर्दछ। सुरु गर्नका लागि होइन, समाप्त गर्नका लागि राम्रो छ।"),
    PRASHNA_REPORT_CATEGORY("Category", "वर्ग"),
    PRASHNA_REPORT_CERTAINTY("Certainty", "निश्चितता"),
    PRASHNA_REPORT_CONDITION("Condition", "अवस्था"),
    PRASHNA_REPORT_CONFIDENCE("Confidence", "विश्वास"),
    PRASHNA_REPORT_ESTIMATED("Estimated Time", "अनुमानित समय"),
    PRASHNA_REPORT_FACTORS_NEGATIVE("- %s", "- %s"),
    PRASHNA_REPORT_FACTORS_POSITIVE("+ %s", "+ %s"),
    PRASHNA_REPORT_HOUSE("House", "भाव"),
    PRASHNA_REPORT_HOUSE_INDICATOR("House %s: %s", "भाव %s: %s"),
    PRASHNA_REPORT_HOUSE_LORD_INDICATOR("Lord in House %s", "भावेश भाव %s मा"),
    PRASHNA_REPORT_LAGNA_ANALYSIS("Lagna Analysis", "लग्न विश्लेषण"),
    PRASHNA_REPORT_LAGNA_LORD("Lagna Lord", "लग्नेश"),
    PRASHNA_REPORT_METHOD("Method", "विधि"),
    PRASHNA_REPORT_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
    PRASHNA_REPORT_NAKSHATRA("Nakshatra", "नक्षत्र"),
    PRASHNA_REPORT_PADA("Pada", "पद"),
    PRASHNA_REPORT_PHASE("Phase", "पक्ष"),
    PRASHNA_REPORT_POSITION("Position", "स्थिति"),
    PRASHNA_REPORT_PRIMARY_INDICATION("Primary Indication", "प्राथमिक संकेत"),
    PRASHNA_REPORT_QUESTION("Question", "प्रश्न"),
    PRASHNA_REPORT_RELEVANT_HOUSES("Relevant Houses", "सम्बन्धित भावहरू"),
    PRASHNA_REPORT_RISING_SIGN("Rising Sign", "उदय राशि"),
    PRASHNA_REPORT_STRENGTH("Strength", "बल"),
    PRASHNA_REPORT_TATTVA_INDICATOR("Element: %s", "तत्व: %s"),
    PRASHNA_REPORT_TIMING("Timing Prediction", "समय भविष्यवाणी"),
    PRASHNA_REPORT_TIMING_TEMPLATE("%1\$s: %2\$s (%3\$s°/day)", "%1\$s: %2\$s (%3\$s°/दिन)"),
    PRASHNA_REPORT_TITLE("PRASHNA ANALYSIS REPORT", "प्रश्न विश्लेषण रिपोर्ट"),
    PRASHNA_REPORT_VERDICT("Verdict", "निर्णय"),
    PRASHNA_REPORT_WANING("Waning", "कृष्ण"),
    PRASHNA_REPORT_WARNING_VOID("WARNING: Moon is Void of Course - outcome may be nullified or delayed.", "चेतावनी: चन्द्रमा शून्य छ - परिणाम शून्य वा ढिलाइ हुन सक्छ।"),
    PRASHNA_REPORT_WAXING("Waxing", "शुक्ल"),
    PRASHNA_RISING_SIGN("Rising Sign", "उदय राशि"),
    PRASHNA_SAFETY_LEVEL("Safety level", "सुरक्षा स्तर"),
    PRASHNA_SCORE("Score: %s", "अंक: %s"),
    PRASHNA_SIGN("Sign", "राशि"),
    PRASHNA_SPECIAL_YOGAS("Special Prashna Yogas", "विशेष प्रश्न योगहरू"),
    PRASHNA_STRENGTH("Strength", "बल"),
    PRASHNA_STRENGTH_DEBILITATED("Debilitated", "नीच"),
    PRASHNA_STRENGTH_MODERATE("Moderate", "मध्यम"),
    PRASHNA_STRENGTH_STRONG("Strong", "बलियो"),
    PRASHNA_STRENGTH_VERY_STRONG("Very Strong", "अत्यन्त बलियो"),
    PRASHNA_STRENGTH_VERY_WEAK("Very Weak", "अत्यन्त कमजोर"),
    PRASHNA_STRENGTH_WEAK("Weak", "कमजोर"),
    PRASHNA_SUCCESS_PROBABILITY("Success probability", "सफलताको सम्भावना"),
    PRASHNA_SUMMARY_CATEGORY("Category", "श्रेणी"),
    PRASHNA_SUMMARY_CONFIDENCE("Confidence Score", "निश्चितता अंक"),
    PRASHNA_SUMMARY_MATTER("Matter", "विषय"),
    PRASHNA_SUMMARY_TIME("Time", "समय"),
    PRASHNA_SUMMARY_TITLE("Prashna Analysis Summary", "प्रश्न विश्लेषण सारांश"),
    PRASHNA_SUPPORTING_FACTORS("Supporting Factors", "समर्थक कारकहरू"),
    PRASHNA_TAB_ARUDHA("Arudha", "आरूढ"),
    PRASHNA_TAB_ASPECTS("Aspects", "पक्षहरू"),
    PRASHNA_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    PRASHNA_TAB_SPECIAL("Special", "विशेष"),
    PRASHNA_TATTVA_AIR("Vayu/Air", "वायु"),
    PRASHNA_TATTVA_AIR_SIGNS("Gemini, Libra, Aquarius", "मिथुन, तुला, कुम्भ"),
    PRASHNA_TATTVA_EARTH("Prithvi/Earth", "पृथ्वी"),
    PRASHNA_TATTVA_EARTH_SIGNS("Taurus, Virgo, Capricorn", "वृष, कन्या, मकर"),
    PRASHNA_TATTVA_ETHER("Akasha/Ether", "आकाश"),
    PRASHNA_TATTVA_ETHER_SIGNS("None - represents void/space", "कुनै पनि होइन - शून्य/अन्तरिक्ष"),
    PRASHNA_TATTVA_FIRE("Agni/Fire", "अग्नि"),
    PRASHNA_TATTVA_FIRE_SIGNS("Aries, Leo, Sagittarius", "मेष, सिंह, धनु"),
    PRASHNA_TATTVA_WATER("Jala/Water", "जल"),
    PRASHNA_TATTVA_WATER_SIGNS("Cancer, Scorpio, Pisces", "कर्कट, वृश्चिक, मीन"),
    PRASHNA_TIME_NOW("Now", "अहिले"),
    PRASHNA_TIMING("Timing Prediction", "समय भविष्यवाणी"),
    PRASHNA_TIMING_ABOUT("About %s", "लगभग %s"),
    PRASHNA_TIMING_DAYS("Days", "दिन"),
    PRASHNA_TIMING_EXPLANATION("Based on %1\$s, the estimated timing is approximately %2\$s. Moon's current position and speed (%3\$s°/day) were primary factors in this calculation.", "%1\$s को आधारमा, अनुमानित समय लगभग %2\$s हो। चन्द्रमाको वर्तमान स्थिति र गति (%3\$s°/दिन) यस गणनामा प्राथमिक कारकहरू थिए।"),
    PRASHNA_TIMING_HOURS("Hours", "घण्टा"),
    PRASHNA_TIMING_INDICATION("Timing indication", "समय संकेत"),
    PRASHNA_TIMING_MONTHS("Months", "महिना"),
    PRASHNA_TIMING_WEEKS("Weeks", "हप्ता"),
    PRASHNA_TIMING_WITHIN("Within %s", "%s भित्र"),
    PRASHNA_TIMING_YEARS("Years", "वर्ष"),
    PRASHNA_TITHI("Tithi", "तिथि"),
    PRASHNA_TITHI_AMAVASYA("Amavasya", "औंसी"),
    PRASHNA_TITHI_ASHTAMI("Ashtami", "अष्टमी"),
    PRASHNA_TITHI_CHATURDASHI("Chaturdashi", "चतुर्दशी"),
    PRASHNA_TITHI_CHATURTHI("Chaturthi", "चतुर्थी"),
    PRASHNA_TITHI_DASHAMI("Dashami", "दशमी"),
    PRASHNA_TITHI_DWADASHI("Dwadashi", "द्वादशी"),
    PRASHNA_TITHI_DWITIYA("Dwitiya", "द्वितीया"),
    PRASHNA_TITHI_EKADASHI("Ekadashi", "एकादशी"),
    PRASHNA_TITHI_KRISHNA("Krishna %s", "कृष्ण %s"),
    PRASHNA_TITHI_NAVAMI("Navami", "नवमी"),
    PRASHNA_TITHI_PANCHAMI("Panchami", "पञ्चमी"),
    PRASHNA_TITHI_PRATIPADA("Pratipada", "प्रतिपदा"),
    PRASHNA_TITHI_PURNIMA("Purnima", "पूर्णिमा"),
    PRASHNA_TITHI_SAPTAMI("Saptami", "सप्तमी"),
    PRASHNA_TITHI_SHASHTHI("Shashthi", "षष्ठी"),
    PRASHNA_TITHI_SHUKLA("Shukla %s", "शुक्ल %s"),
    PRASHNA_TITHI_TRAYODASHI("Trayodashi", "त्रयोदशी"),
    PRASHNA_TITHI_TRITIYA("Tritiya", "तृतीया"),
    PRASHNA_TOPIC_ACHIEVEMENT("Achievement", "उपलब्धि"),
    PRASHNA_TOPIC_ANKLES("Ankles", "कुर्कुच्चा"),
    PRASHNA_TOPIC_AUTHORITY("Authority", "अधिकार"),
    PRASHNA_TOPIC_BED_PLEASURES("Bed pleasures", "शय्या सुख"),
    PRASHNA_TOPIC_BEGINNING("Beginning of matter", "विषयको शुरुवात"),
    PRASHNA_TOPIC_CAREER("Career", "क्यारियर"),
    PRASHNA_TOPIC_CHILDREN("Children", "सन्तान"),
    PRASHNA_TOPIC_CHRONIC("Chronic illness", "दीर्घकालीन रोग"),
    PRASHNA_TOPIC_COMMUNICATION("Communication", "सञ्चार"),
    PRASHNA_TOPIC_COMPETITORS("Competitors", "प्रतिस्पर्धी"),
    PRASHNA_TOPIC_COURAGE("Courage", "साहस"),
    PRASHNA_TOPIC_DEALS("Business deals", "व्यापार सम्झौता"),
    PRASHNA_TOPIC_DEATH("Death", "मृत्यु"),
    PRASHNA_TOPIC_DEBTS("Debts", "ऋण"),
    PRASHNA_TOPIC_DISEASE("Disease", "रोग"),
    PRASHNA_TOPIC_EDUCATION("Education", "शिक्षा"),
    PRASHNA_TOPIC_EFFORTS("Efforts", "प्रयास"),
    PRASHNA_TOPIC_ELDER_SIBLINGS("Elder siblings", "ठूला भाइबहिनी"),
    PRASHNA_TOPIC_ENEMIES("Enemies", "शत्रु"),
    PRASHNA_TOPIC_EXPENSES("Expenses", "खर्च"),
    PRASHNA_TOPIC_FACE("Face", "अनुहार"),
    PRASHNA_TOPIC_FAMILY("Family", "परिवार"),
    PRASHNA_TOPIC_FATHER("Father", "पिता")
}
