package com.astro.storm.core.common

enum class StringKeyVargaPart1(override val en: String, override val ne: String) : StringKeyInterface {
    DASHAMSA_10TH_LORD("10th Lord in D-10", "D-10 मा १०औं स्वामी"),
    DASHAMSA_BIZ_APTITUDE("Strong aptitude for business/entrepreneurship", "व्यापार/उद्यमशीलताको लागि बलियो योग्यता"),
    DASHAMSA_BOTH_APTITUDE("Can excel in both business and service", "व्यापार र सेवा दुवैमा फस्टाउन सक्छ"),
    DASHAMSA_BUSINESS("Business Aptitude", "व्यापार योग्यता"),
    DASHAMSA_BUSINESS_VS_SERVICE("Business vs Service", "व्यापार बनाम सेवा"),
    DASHAMSA_CAREER_ABOUT("About Dashamsa Chart", "दशांश चार्टको बारेमा"),
    DASHAMSA_CAREER_ABOUT_DESC("Dashamsa reveals career potential, professional achievements, and worldly status through 10th harmonic analysis.", "दशांशले १०औं हार्मोनिक विश्लेषण मार्फत करियर सम्भावना, व्यावसायिक उपलब्धि, र सांसारिक स्थिति प्रकट गर्दछ।"),
    DASHAMSA_CAREER_HOUSES("Career Houses Analysis", "करियर भाव विश्लेषण"),
    DASHAMSA_CAREER_SUBTITLE("Professional Life and Status", "व्यावसायिक जीवन र स्थिति"),
    DASHAMSA_CAREER_TITLE("Dashamsa (D-10) Career Analysis", "दशांश (D-10) करियर विश्लेषण"),
    DASHAMSA_FACTOR_EXALTED_SUN("Exalted Sun", "उच्चको सूर्य"),
    DASHAMSA_FACTOR_SUN_10("Sun in 10th house of D10", "D10 को १०औं भावमा सूर्य"),
    DASHAMSA_GOVT_HIGH("High", "उच्च"),
    DASHAMSA_GOVT_LOW("Low", "न्यून"),
    DASHAMSA_GOVT_MODERATE("Moderate", "मध्यम"),
    DASHAMSA_GOVT_SERVICE_TITLE("Government Service", "सरकारी सेवा"),
    DASHAMSA_GOVT_VERY_HIGH("Very High", "अत्यन्त उच्च"),
    DASHAMSA_LAGNA_LORD("D-10 Lagna Lord", "D-10 लग्न स्वामी"),
    DASHAMSA_MERC_VERSATILE("Strong Mercury suggests versatility in career", "बलियो बुधले करियरमा बहुमुखी प्रतिभा सुझाव दिन्छ"),
    DASHAMSA_MULTIPLE_10TH("Multiple planets in 10th house indicate potential for multiple careers", "१०औं भावमा धेरै ग्रहहरूले बहु करियरको सम्भावना संकेत गर्दछ"),
    DASHAMSA_PEAK_10TH_LORD("10th lord Dasha - Primary career growth period", "१०औं स्वामीको दशा - प्राथमिक करियर विकास अवधि"),
    DASHAMSA_PEAK_10TH_SIG("Major career advancements and recognition", "प्रमुख करियर प्रगति र मान्यता"),
    DASHAMSA_PEAK_PLANET_FMT("%1\$s Dasha/Antardasha", "%1\$s दशा/अन्तर्दशा"),
    DASHAMSA_PEAK_PLANET_SIG("Career opportunities in %1\$s", "%1\$s मा करियरको अवसर"),
    DASHAMSA_POTENTIAL("Potential", "सम्भावना"),
    DASHAMSA_PROFESSIONAL_STRENGTHS("Professional Strengths", "व्यावसायिक शक्तिहरू"),
    DASHAMSA_PROFESSION_TYPE("Profession Indicators", "पेशा सूचकहरू"),
    DASHAMSA_RAHU_UNCONVENTIONAL("Rahu indicates unconventional career path or career changes", "राहुले अपरम्परागत करियर मार्ग वा करियर परिवर्तन संकेत गर्दछ"),
    DASHAMSA_RECOMMENDED_AREAS("Recommended Areas", "सिफारिस गरिएका क्षेत्रहरू"),
    DASHAMSA_REC_PERIOD_FAVORS("%1\$s period favors: %2\$s", "%1\$s को अवधि अनुकूल छ: %2\$s"),
    DASHAMSA_REC_PRIMARY_FOCUS("Primary career focus: %1\$s", "प्राथमिक करियर फोकस: %1\$s"),
    DASHAMSA_REC_TOP_INDUSTRIES("Top industries: %1\$s", "प्रमुख उद्योगहरू: %1\$s"),
    DASHAMSA_SERVICE("Service Aptitude", "सेवा योग्यता"),
    DASHAMSA_SERVICE_APTITUDE("Better suited for service/employment", "सेवा/जागिरको लागि बढी उपयुक्त"),
    DASHAMSA_STATUS_POTENTIAL("Status Potential", "स्थिति सम्भावना"),
    DASHAMSA_STRENGTH_COMM("Communication and analytical skills", "सञ्चार र विश्लेषणात्मक सीप"),
    DASHAMSA_STRENGTH_CREATIVITY("Creativity and relationship skills", "सिर्जनशीलता र सम्बन्ध सीप"),
    DASHAMSA_STRENGTH_DRIVE("Drive and competitive spirit", "जोस र प्रतिस्पर्धी भावना"),
    DASHAMSA_STRENGTH_EXCEPTIONAL("Exceptional abilities in chosen field", "रोजिएको क्षेत्रमा असाधारण क्षमता"),
    DASHAMSA_STRENGTH_IDENTITY("Strong professional identity and presence", "बलियो व्यावसायिक पहिचान र उपस्थिति"),
    DASHAMSA_STRENGTH_LEADERSHIP("Leadership and authority", "नेतृत्व र अधिकार"),
    DASHAMSA_STRENGTH_PERSISTENCE("Persistence and organizational ability", "दृढता र संगठनात्मक क्षमता"),
    DASHAMSA_STRENGTH_PUBLIC("Public appeal and emotional intelligence", "जनताको आकर्षण र भावनात्मक बुद्धि"),
    DASHAMSA_STRENGTH_WISDOM("Wisdom and advisory capabilities", "ज्ञान र सल्लाहकार क्षमता"),
    DASHAMSA_SUIT_ADMIN("Leadership positions, authority roles", "नेतृत्व पदहरू, अधिकार भूमिकाहरू"),
    DASHAMSA_SUIT_ADVISORY("Positions requiring wisdom and guidance", "ज्ञान र मार्गदर्शन चाहिने पदहरू"),
    DASHAMSA_SUIT_COMM("Intellectual and analytical roles", "बौद्धिक र विश्लेषणात्मक भूमिकाहरू"),
    DASHAMSA_SUIT_CREATIVE("Aesthetic and pleasure-related industries", "सौन्दर्य र आनन्द सम्बन्धित उद्योगहरू"),
    DASHAMSA_SUIT_LABOR("Careers requiring persistence and hard work", "दृढता र कडा परिश्रम चाहिने करियरहरू"),
    DASHAMSA_SUIT_PUBLIC("People-facing roles, caring professions", "जनतासँग जोडिने भूमिकाहरू, हेरचाह गर्ने पेशाहरू"),
    DASHAMSA_SUIT_SPIRITUAL("Fields requiring deep investigation", "गहन अनुसन्धान चाहिने क्षेत्रहरू"),
    DASHAMSA_SUIT_TECH("Action-oriented careers requiring courage", "साहस चाहिने कार्य-उन्मुख करियरहरू"),
    DASHAMSA_SUIT_UNCONVENTIONAL("Innovative and cutting-edge fields", "अभिनव र अत्याधुनिक क्षेत्रहरू"),
    DASHAMSA_SUIT_VARIOUS("Various career possibilities", "विभिन्न करियर सम्भावनाहरू"),
    DASHAMSA_TYPE_ADMIN("Administrative/Government", "प्रशासनिक/सरकारी"),
    DASHAMSA_TYPE_ADVISORY("Advisory/Educational", "सल्लाहकार/शैक्षिक"),
    DASHAMSA_TYPE_COMM("Communication/Business", "सञ्चार/व्यापार"),
    DASHAMSA_TYPE_CREATIVE("Creative/Luxury", "सिर्जनात्मक/विलासी"),
    DASHAMSA_TYPE_GENERAL("General", "सामान्य"),
    DASHAMSA_TYPE_LABOR("Labor/Resource", "श्रम/स्रोत"),
    DASHAMSA_TYPE_PUBLIC("Public Service/Nurturing", "सार्वजनिक सेवा/हेरचाह"),
    DASHAMSA_TYPE_SPIRITUAL("Spiritual/Research", "आध्यात्मिक/अनुसन्धान"),
    DASHAMSA_TYPE_TECH("Technical/Competitive", "प्राविधिक/प्रतिस्पर्धात्मक"),
    DASHAMSA_TYPE_UNCONVENTIONAL("Unconventional/Foreign", "अपरम्परागत/विदेशी"),
    DREKKANA_ANALYSIS_ABOUT("About Drekkana Chart", "द्रेष्काण चार्टको बारेमा"),
    DREKKANA_ANALYSIS_ABOUT_DESC("Drekkana chart reveals sibling relationships, courage, and personal initiative. Each sign is divided into three 10-degree portions.", "द्रेष्काण चार्टले भाइबहिनी सम्बन्ध, साहस, र व्यक्तिगत पहलकदमी प्रकट गर्दछ। प्रत्येक राशि तीन १०-अंश भागमा विभाजित छ।"),
    DREKKANA_ANALYSIS_SUBTITLE("Siblings and Courage", "भाइबहिनी र साहस"),
    DREKKANA_ANALYSIS_TITLE("Drekkana (D-3) Analysis", "द्रेष्काण (D-3) विश्लेषण"),
    DREKKANA_ARTISTIC("Artistic Talents", "कलात्मक प्रतिभाहरू"),
    DREKKANA_ARTISTIC_TALENTS("Artistic Talents", "कलात्मक प्रतिभा"),
    DREKKANA_ART_MUSIC("Music and rhythm", "संगीत र लय"),
    DREKKANA_ART_VISUAL("Visual arts and aesthetics", "दृश्य कला र सौन्दर्य शास्त्र"),
    DREKKANA_COMMUNICATION_TITLE("Communication", "सञ्चार"),
    DREKKANA_COMM_AVERAGE("Average", "औसत"),
    DREKKANA_COMM_EXCEPTIONAL("Exceptional", "असाधारण"),
    DREKKANA_COMM_GOOD("Good", "राम्रो"),
    DREKKANA_COMM_VERY_GOOD("Very Good", "धेरै राम्रो"),
    DREKKANA_COURAGE_LEVEL("Courage Level", "साहस स्तर"),
    DREKKANA_COURAGE_TITLE("Courage Analysis", "साहस विश्लेषण"),
    DREKKANA_ELDER("Elder Siblings", "ठूला भाइबहिनी"),
    DREKKANA_FIRST("First Drekkana (0-10Â°)", "पहिलो द्रेष्काण (०-१०°)"),
    DREKKANA_INITIATIVE("Initiative", "पहल"),
    DREKKANA_INITIATIVE_MODERATE("Moderate initiative - benefits from preparation and planning", "मध्यम पहल - तयारी र योजनाबाट फाइदा हुन्छ"),
    DREKKANA_INITIATIVE_STRONG("Strong initiative ability - natural leader and pioneer", "बलियो पहल क्षमता - प्राकृतिक नेता र अग्रगामी"),
    DREKKANA_JOURNEY_BUSINESS("Travel for communication or business purposes", "सञ्चार वा व्यापारिक उद्देश्यका लागि यात्रा"),
    DREKKANA_JOURNEY_FREQUENT("Frequent short travels likely", "बारम्बार छोटो यात्राहरूको सम्भावना"),
    DREKKANA_JOURNEY_UNUSUAL("Unusual or sudden short journeys", "असामान्य वा अचानक छोटो यात्राहरू"),
    DREKKANA_MENTAL("Mental", "मानसिक"),
    DREKKANA_MENTAL_EXPERIENCE("Mental courage develops through life experiences", "जीवनका अनुभवहरू मार्फत मानसिक साहस विकसित हुन्छ"),
    DREKKANA_MENTAL_INTELLECTUAL("Sharp intellectual courage and quick decision-making", "तीक्ष्ण बौद्धिक साहस र छिटो निर्णय लिने क्षमता"),
    DREKKANA_MENTAL_STABLE("Stable mental fortitude", "स्थिर मानसिक दृढता"),
    DREKKANA_MENTAL_WISDOM("Exceptional wisdom-backed mental courage", "बुद्धिमा आधारित असाधारण मानसिक साहस"),
    DREKKANA_OVERALL("Overall", "समग्र"),
    DREKKANA_PHYSICAL("Physical", "शारीरिक"),
    DREKKANA_PHYSICAL_ADEQUATE("Adequate physical courage for normal situations", "सामान्य परिस्थितिहरूको लागि पर्याप्त शारीरिक साहस"),
    DREKKANA_PHYSICAL_DEPENDS("Physical courage depends on other factors", "शारीरिक साहस अन्य कारकहरूमा निर्भर गर्दछ"),
    DREKKANA_PHYSICAL_DEVELOPMENT("Physical courage may need development", "शारीरिक साहसको विकास आवश्यक हुन सक्छ"),
    DREKKANA_PHYSICAL_EXCEPTIONAL("Exceptional physical courage and athletic ability", "असाधारण शारीरिक साहस र एथलेटिक क्षमता"),
    DREKKANA_PHYSICAL_STRONG("Strong physical constitution and bravery", "बलियो शारीरिक बनावट र वीरता"),
    DREKKANA_REC_BALANCE_CAUTION("Maintain balance between caution and boldness", "सावधानी र साहस बीच सन्तुलन कायम राख्नुहोस्"),
    DREKKANA_REC_CHANNEL_COURAGE("Channel courage into leadership and pioneering ventures", "साहसलाई नेतृत्व र अग्रगामी कार्यहरूमा लगाउनुहोस्"),
    DREKKANA_REC_COUNSELING("Consider family counseling if needed", "आवश्यक भएमा पारिवारिक परामर्श विचार गर्नुहोस्"),
    DREKKANA_REC_HANUMAN("Worship Lord Hanuman for courage", "साहसको लागि भगवान हनुमानको पूजा गर्नुहोस्"),
    DREKKANA_REC_MARS_ACTIVITIES("Practice Mars-strengthening activities like sports or martial arts", "खेलकुद वा मार्सल आर्ट जस्ता मंगल-बलियो बनाउने गतिविधिहरू अभ्यास गर्नुहोस्"),
    DREKKANA_REC_SIBLING_PATIENCE("Practice patience and understanding with siblings", "भाइबहिनीसँग धैर्य र समझदारी अभ्यास गर्नुहोस्"),
    DREKKANA_RELATIONSHIP("Relationship", "सम्बन्ध"),
    DREKKANA_SECOND("Second Drekkana (10-20Â°)", "दोस्रो द्रेष्काण (१०-२०°)"),
    DREKKANA_SHORT_JOURNEYS("Short Journeys", "छोटो यात्रा"),
    DREKKANA_SIBLING_JUPITER("Jupiter's blessing on younger siblings - prosperity for them", "साना भाइबहिनीमा बृहस्पतिको आशीर्वाद - उनीहरूको लागि समृद्धि"),
    DREKKANA_SIBLING_KARMA("Sibling Karma", "भाइबहिनी कर्म"),
    DREKKANA_SIBLING_MARS("Mars shows courageous and competitive siblings", "मंगलले साहसी र प्रतिस्पर्धी भाइबहिनी देखाउँछ"),
    DREKKANA_SIBLING_SATURN("Saturn indicates hard-working siblings with delayed success", "शनिले कडा परिश्रम गर्ने भाइबहिनी संकेत गर्दछ जसको सफलतामा ढिलाइ हुन्छ"),
    DREKKANA_SPEAKING("Speaking", "बोल्ने"),
    DREKKANA_SPEAKING_AUTHORITATIVE("Authoritative and commanding speech", "अधिकारपूर्ण र प्रभावशाली बोली"),
    DREKKANA_SPEAKING_ELOQUENT("Eloquent speaker with wisdom", "ज्ञान सहितको वाक्पटु वक्ता"),
    DREKKANA_SPEAKING_NORMAL("Normal speaking abilities", "सामान्य बोल्ने क्षमता"),
    DREKKANA_SPEAKING_QUICK("Quick and articulate speech", "छिटो र स्पष्ट बोली"),
    DREKKANA_THIRD("Third Drekkana (20-30Â°)", "तेस्रो द्रेष्काण (२०-३०°)"),
    DREKKANA_TYPE("Drekkana Type", "द्रेष्काण प्रकार"),
    DREKKANA_WRITING("Writing", "लेखन"),
    DREKKANA_WRITING_AVERAGE("Average writing ability", "औसत लेखन क्षमता"),
    DREKKANA_WRITING_DEPTH("Strong writing ability with wisdom and depth", "ज्ञान र गहिराई सहित बलियो लेखन क्षमता"),
    DREKKANA_WRITING_EXCEPTIONAL("Exceptional writing talent - potential author or journalist", "असाधारण लेखन प्रतिभा - सम्भावित लेखक वा पत्रकार"),
    DREKKANA_WRITING_GOOD("Good written communication skills", "राम्रो लिखित सञ्चार सीप"),
    DREKKANA_YOUNGER("Younger Siblings", "साना भाइबहिनी"),
    DWADASAMSA_ABOUT("About Dwadasamsa Chart", "द्वादशांश चार्टको बारेमा"),
    DWADASAMSA_ABOUT_DESC("Dwadasamsa reveals parental relationships, ancestral inheritance, and genetic predispositions through 12th harmonic analysis.", "द्वादशांशले १२औं हार्मोनिक विश्लेषण मार्फत अभिभावक सम्बन्ध, पैतृक विरासत, र आनुवंशिक प्रवृत्तिहरू प्रकट गर्दछ।"),
    DWADASAMSA_ANCESTRAL_KARMA("Ancestral Karma", "पैतृक कर्म"),
    DWADASAMSA_ANCESTRAL_PROPERTY("Ancestral Property", "पैतृक सम्पत्ति"),
    DWADASAMSA_CHARACTERISTICS("Characteristics", "विशेषताहरू"),
    DWADASAMSA_CONCERN_FATHER("Father: Regular health checkups advised", "पिता: नियमित स्वास्थ्य जाँचको सल्लाह"),
    DWADASAMSA_CONCERN_MOTHER("Mother: Emotional wellbeing attention", "माता: भावनात्मक कल्याणमा ध्यान"),
    DWADASAMSA_FAM_DEPENDS("Family lineage characteristics depend on other factors", "पारिवारिक वंशका विशेषताहरू अन्य कारकहरूमा निर्भर गर्दछ"),
    DWADASAMSA_FAM_DHARMA("Family known for dharma or profession", "धर्म वा पेशाको लागि परिचित परिवार"),
    DWADASAMSA_FAM_NOBLE("Noble or respected family lineage", "कुलीन वा सम्मानित पारिवारिक वंश"),
    DWADASAMSA_FAM_SUCCESS("Family with creative or financial success", "सिर्जनात्मक वा आर्थिक सफलता भएको परिवार"),
    DWADASAMSA_FATHER("Father", "बुबा"),
    DWADASAMSA_FATHER_ANALYSIS("Father Analysis", "बुबा विश्लेषण"),
    DWADASAMSA_FATHER_CHAR_AMBITIOUS("Career-focused, ambitious, prominent position", "करियर-केन्द्रित, महत्त्वाकांक्षी, प्रतिष्ठित पद"),
    DWADASAMSA_FATHER_CHAR_AUTHORITATIVE("Authoritative, successful, government/administrative role", "अधिकारपूर्ण, सफल, सरकारी/प्रशासनिक भूमिका"),
    DWADASAMSA_FATHER_CHAR_RELIGIOUS("Religious, wise, generous", "धार्मिक, ज्ञानी, उदार"),
    DWADASAMSA_FATHER_CHAR_VARIES("Characteristics vary based on overall chart", "समग्र कुण्डलीको आधारमा विशेषताहरू फरक हुन सक्छन्"),
    DWADASAMSA_FATHER_WELLBEING_GOOD("Good health and prosperity indicated", "राम्रो स्वास्थ्य र समृद्धिको संकेत"),
    DWADASAMSA_HEALTH_CONCERNS("Health Concerns", "स्वास्थ्य चिन्ताहरू"),
    DWADASAMSA_HOUSE_LORD("House Lord", "भाव स्वामी"),
    DWADASAMSA_INHERITANCE("Inheritance Potential", "विरासत सम्भावना"),
    DWADASAMSA_INHERITANCE_TITLE("Inheritance Analysis", "विरासत विश्लेषण"),
    DWADASAMSA_INH_GOOD("Good inheritance potential", "राम्रो पैतृक सम्पत्ति सम्भावना"),
    DWADASAMSA_INH_LIMITED("Limited inheritance indicated", "सीमित पैतृक सम्पत्तिको संकेत"),
    DWADASAMSA_INH_MODERATE("Moderate inheritance", "मध्यम पैतृक सम्पत्ति"),
    DWADASAMSA_INH_TIMING("During Dasha of benefic planets in 2nd, 4th, or 8th house of D-12", "D-12 को २औं, ४औं वा ८औं भावमा रहेका शुभ ग्रहहरूको दशाको समयमा"),
    DWADASAMSA_LONGEVITY_TITLE("Parental Longevity", "अभिभावक दीर्घायु"),
    DWADASAMSA_LONG_ATTENTION("Health attention needed", "स्वास्थ्यमा ध्यान आवश्यक"),
    DWADASAMSA_LONG_INDICATED("Long life indicated", "लामो आयुको संकेत"),
    DWADASAMSA_LONG_MODERATE("Moderate longevity", "मध्यम आयु"),
    DWADASAMSA_MOON_POSITION("Moon in D-12 (Mother)", "D-12 मा चन्द्र (आमा)"),
    DWADASAMSA_MOTHER("Mother", "आमा"),
    DWADASAMSA_MOTHER_ANALYSIS("Mother Analysis", "आमा विश्लेषण"),
    DWADASAMSA_MOTHER_CHAR_ARTISTIC("Artistic, beautiful, comfort-loving", "कलात्मक, सुन्दर, आराम-प्रेमी"),
    DWADASAMSA_MOTHER_CHAR_HOME("Home-oriented, caring, family-focused", "घर-उन्मुख, दयालु, परिवार-केन्द्रित"),
    DWADASAMSA_MOTHER_CHAR_NURTURING("Nurturing, emotionally supportive, prosperous", "हेरचाह गर्ने, भावनात्मक रूपमा सहयोगी, समृद्ध"),
    DWADASAMSA_MOTHER_CHAR_VARIES("Characteristics vary based on overall chart", "समग्र कुण्डलीको आधारमा विशेषताहरू फरक हुन सक्छन्"),
    DWADASAMSA_MOTHER_WELLBEING_GOOD("Good health and emotional wellbeing indicated", "राम्रो स्वास्थ्य र भावनात्मक कल्याणको संकेत"),
    DWADASAMSA_POTENTIAL("Potential", "सम्भावना"),
    DWADASAMSA_PROP_LAND("Land or real estate from ancestors", "पुर्खाहरूबाट प्राप्त जमिन वा घरजग्गा"),
    DWADASAMSA_PROP_OLD("Old ancestral property indicated", "पुरानो पुर्ख्यौली सम्पत्तिको संकेत"),
    DWADASAMSA_PROP_RELIGIOUS("Religious or educational property", "धार्मिक वा शैक्षिक सम्पत्ति"),
    DWADASAMSA_REC_FATHER_RESPECT("Respect and serve father figures", "पिता समान व्यक्तित्वहरूको सम्मान र सेवा गर्नुहोस्"),
    DWADASAMSA_REC_FATHER_SUN("Offer water to Sun on Sundays for father's wellbeing", "पिताको कल्याणको लागि आइतबार सूर्यलाई जल अर्पण गर्नुहोस्"),
    DWADASAMSA_REC_MOTHER_CHARITY("Offer milk/white items in charity", "दूध/सेतो वस्तुहरू दान गर्नुहोस्"),
    DWADASAMSA_REC_MOTHER_MOON("Worship Moon on Mondays for mother's health", "माताको स्वास्थ्यको लागि सोमबार चन्द्रमाको पूजा गर्नुहोस्"),
    DWADASAMSA_REC_PITRU_TARPAN("Perform Pitru Tarpan during Pitru Paksha for ancestral blessings", "पुर्खाहरूको आशीर्वादको लागि पितृ पक्षमा पितृ तर्पण गर्नुहोस्"),
    DWADASAMSA_RELATIONSHIP("Relationship", "सम्बन्ध"),
    DWADASAMSA_REL_CHALLENGES("Some challenges in relationship", "सम्बन्धमा केही चुनौतीहरू"),
    DWADASAMSA_REL_DEPENDS("Relationship quality depends on other factors", "सम्बन्धको गुणस्तर अन्य कारकहरूमा निर्भर गर्दछ"),
    DWADASAMSA_REL_HARMONIOUS("Harmonious, beneficial relationship", "सामञ्जस्यपूर्ण, लाभदायक सम्बन्ध"),
    DWADASAMSA_REL_MODERATE("Moderate relationship quality", "मध्यम सम्बन्ध गुणस्तर"),
    DWADASAMSA_REL_STRONG("Strong, supportive relationship", "बलियो, सहयोगी सम्बन्ध"),
    DWADASAMSA_SIGNIFICATOR("Significator", "कारक"),
    DWADASAMSA_SOURCES("Sources", "स्रोतहरू"),
    DWADASAMSA_SOURCE_PROPERTY("Property/Land", "सम्पत्ति/जमिन"),
    DWADASAMSA_SOURCE_UNEXPECTED("Unexpected gains", "अप्रत्याशित लाभ"),
    DWADASAMSA_SOURCE_WEALTH("Family wealth", "पारिवारिक धन"),
    DWADASAMSA_SUBTITLE("Parents and Ancestral Karma", "अभिभावक र पूर्वज कर्म"),
    DWADASAMSA_SUN_POSITION("Sun in D-12 (Father)", "D-12 मा सूर्य (बुबा)"),
    DWADASAMSA_TIMING("Timing", "समय"),
    DWADASAMSA_TITLE("Dwadasamsa (D-12) Analysis", "द्वादशांश (D-12) विश्लेषण"),
    HORA_ANALYSIS_ABOUT("About Hora Chart", "होरा चार्टको बारेमा"),
    HORA_ANALYSIS_ABOUT_DESC("Hora chart divides each sign into Sun and Moon halves, revealing wealth accumulation patterns and financial potential.", "होरा चार्टले प्रत्येक राशिलाई सूर्य र चन्द्र आधामा विभाजन गर्छ, धन संचय ढाँचा र आर्थिक सम्भावना प्रकट गर्दछ।"),
    HORA_ANALYSIS_SUBTITLE("Wealth and Financial Potential", "धन र आर्थिक सम्भावना"),
    HORA_ANALYSIS_TITLE("Hora (D-2) Analysis", "होरा (D-2) विश्लेषण"),
    HORA_BALANCE("Hora Balance", "होरा सन्तुलन"),
    HORA_DOMINANT("Dominant Hora", "प्रभावशाली होरा"),
    HORA_INCOME_POTENTIAL("Income Potential", "आय सम्भावना"),
    HORA_INHERITED("Inherited", "पैतृक"),
    HORA_JUPITER("10:00 AM - 11:00 AM (Jupiter Hora)", "बिहान १०:०० - ११:०० (बृहस्पति होरा)"),
    HORA_MARS("8:00 AM - 9:00 AM (Mars Hora)", "बिहान ८:०० - ९:०० (मंगल होरा)"),
    HORA_MERCURY("9:00 AM - 10:00 AM (Mercury Hora)", "बिहान ९:०० - १०:०० (बुध होरा)"),
    HORA_MOON("7:00 AM - 8:00 AM (Moon Hora)", "बिहान ७:०० - ८:०० (चन्द्र होरा)"),
    HORA_MOON_DESC("These planets indicate potential for inherited or liquid assets", "यी ग्रहहरूले विरासत वा तरल सम्पत्तिको सम्भावना संकेत गर्छन्"),
    HORA_MOON_PLANETS("Planets in Moon Hora", "चन्द्र होरामा ग्रहहरू"),
    HORA_MOON_SOURCE_ANCESTRAL_TRADE("Ancestral trade", "पुर्खौली व्यापार"),
    HORA_MOON_SOURCE_DELAYED("Delayed inheritance", "ढिलो गरी प्राप्त पैतृक सम्पत्ति"),
    HORA_MOON_SOURCE_EDUCATIONAL("Educational trusts", "शैक्षिक गुठी"),
    HORA_MOON_SOURCE_FAMILY_BIZ("Family business", "पारिवारिक व्यवसाय"),
    HORA_MOON_SOURCE_FAMILY_LAND("Land from family", "परिवारबाट प्राप्त जमिन"),
    HORA_MOON_SOURCE_GOVT_BENEFITS("Government benefits", "सरकारी सुविधा"),
    HORA_MOON_SOURCE_INHERITANCE("Inheritance", "पैतृक सम्पत्ति"),
    HORA_MOON_SOURCE_INTELLECTUAL("Intellectual property", "बौद्धिक सम्पत्ति"),
    HORA_MOON_SOURCE_MILITARY_PENSION("Military pension", "सैनिक पेन्सन"),
    HORA_MOON_SOURCE_MOTHER("Mother's side", "माताको पक्ष"),
    HORA_MOON_SOURCE_OLD_WEALTH("Old wealth", "पुरानो सम्पत्ति"),
    HORA_MOON_SOURCE_PEARLS("Pearls", "मोती"),
    HORA_MOON_SOURCE_ROYAL("Royal grants", "राजकीय अनुदान"),
    HORA_MOON_SOURCE_SILVER("Silver", "चाँदी"),
    HORA_MOON_SOURCE_SPOUSE("Spouse's wealth", "जीवनसाथीको धन"),
    HORA_MOON_TITLE("Moon Hora - Inherited/Liquid Wealth", "चन्द्र होरा - विरासत/तरल धन"),
    HORA_NATURE_BENEFIC("Benefic", "शुभ"),
    HORA_NATURE_MALEFIC("Malefic", "पापी"),
    HORA_NATURE_NEUTRAL("Neutral", "तटस्थ"),
    HORA_POTENTIAL("Wealth Potential", "धन सम्भावना"),
    HORA_POTENTIAL_AVERAGE("Average Wealth", "औसत धन"),
    HORA_POTENTIAL_CHALLENGES("Some challenges indicated - remedies beneficial", "केही चुनौतीहरूको संकेत - उपायहरू लाभदायक"),
    HORA_POTENTIAL_EXCEPTIONAL("Exceptional Wealth", "असाधारण धन"),
    HORA_POTENTIAL_HIGH("High Wealth", "उच्च धन"),
    HORA_POTENTIAL_MODERATE("Moderate Wealth", "मध्यम धन"),
    HORA_POTENTIAL_NEEDS_EFFORT("Needs Effort", "प्रयास आवश्यक"),
    HORA_REC_AVOID_SPECULATION("Avoid speculation; focus on steady income sources", "सट्टा/जुवाबाट बच्नुहोस्; स्थिर आय स्रोतहरूमा ध्यान दिनुहोस्"),
    HORA_REC_CAPITALIZE_STRENGTH("Capitalize on %1\$s's strength in %2\$s", "%2\$s मा %1\$s को शक्तिको सदुपयोग गर्नुहोस्"),
    HORA_REC_CONSISTENT_EFFORT("Consistent effort in indicated areas will yield gradual wealth", "संकेत गरिएका क्षेत्रमा निरन्तर प्रयासले क्रमिक धन दिनेछ"),
    HORA_REC_FOCUS_SOURCES("Focus on indicated wealth sources for maximum prosperity", "अधिकतम समृद्धिको लागि संकेत गरिएका धन स्रोतहरूमा ध्यान दिनुहोस्"),
    HORA_REC_INVEST_FAVORABLE("Invest during favorable Dasha periods of strong Hora planets", "बलियो होरा ग्रहहरूको अनुकूल दशा अवधिमा लगानी गर्नुहोस्"),
    HORA_REC_STRENGTHEN_JUP_VEN("Strengthen Jupiter and Venus through gemstones or mantras", "बृहस्पति र शुक्रलाई रत्न वा मन्त्र मार्फत बलियो बनाउनुहोस्"),
    HORA_REC_STRENGTHEN_WEAK("Strengthen weak planets through appropriate remedies", "उपयुक्त उपायहरू मार्फत कमजोर ग्रहहरूलाई बलियो बनाउनुहोस्"),
    HORA_REC_WORSHIP_LAKSHMI("Worship Goddess Lakshmi for wealth blessings", "धनको आशीर्वादको लागि देवी लक्ष्मीको पूजा गर्नुहोस्"),
    HORA_SATURN("5:00 PM - 6:00 PM (Saturn Hora)", "बेलुका ५:०० - ६:०० (शनि होरा)"),
    HORA_SELF_EARNED("Self Earned", "आर्जित"),
    HORA_SUN("6:00 AM - 7:00 AM (Sun Hora)", "बिहान ६:०० - ७:०० (सूर्य होरा)"),
    HORA_SUN_DESC("These planets indicate potential for wealth through your own efforts", "यी ग्रहहरूले तपाईंको आफ्नै प्रयासबाट धनको सम्भावना संकेत गर्छन्"),
    HORA_SUN_PLANETS("Planets in Sun Hora", "सूर्य होरामा ग्रहहरू"),
    HORA_SUN_SOURCE_ARTS("Arts", "कला"),
    HORA_SUN_SOURCE_AUTHORITY("Authority roles", "अधिकार भूमिकाहरू"),
    HORA_SUN_SOURCE_BANKING("Banking", "बैंकिङ"),
    HORA_SUN_SOURCE_BEAUTY("Beauty industry", "सौन्दर्य उद्योग"),
    HORA_SUN_SOURCE_BUSINESS("Business", "व्यापार"),
    HORA_SUN_SOURCE_COMMUNICATION("Communication", "सञ्चार"),
    HORA_SUN_SOURCE_CONSULTANCY("Consultancy", "परामर्श"),
    HORA_SUN_SOURCE_DAIRY("Dairy", "दुग्धजन्य"),
    HORA_SUN_SOURCE_DETACHMENT("Detachment-based gains", "विरक्तिमा आधारित लाभ"),
    HORA_SUN_SOURCE_ENGINEERING("Engineering", "इन्जिनियरिङ"),
    HORA_SUN_SOURCE_ENTERTAINMENT("Entertainment", "मनोरञ्जन"),
    HORA_SUN_SOURCE_FATHER("Father's legacy", "पिताको विरासत"),
    HORA_SUN_SOURCE_FOREIGN("Foreign sources", "विदेशी स्रोतहरू"),
    HORA_SUN_SOURCE_GOLD("Gold investments", "सुन लगानी"),
    HORA_SUN_SOURCE_GOVT("Government positions", "सरकारी पदहरू"),
    HORA_SUN_SOURCE_HOSPITALITY("Hospitality", "आतिथ्य"),
    HORA_SUN_SOURCE_LABOR("Labor management", "श्रम व्यवस्थापन"),
    HORA_SUN_SOURCE_LAND("Land", "जमिन"),
    HORA_SUN_SOURCE_LIQUIDS("Liquids", "तरल पदार्थ"),
    HORA_SUN_SOURCE_LUXURY("Luxury goods", "विलासी वस्तुहरू"),
    HORA_SUN_SOURCE_MILITARY("Military/Police", "सेना/प्रहरी"),
    HORA_SUN_SOURCE_MINING("Mining", "खनन"),
    HORA_SUN_SOURCE_OCCULT("Occult", "तन्त्रमन्त्र"),
    HORA_SUN_SOURCE_OIL("Oil/Petroleum", "तेल/पेट्रोलियम"),
    HORA_SUN_SOURCE_PUBLIC("Public dealings", "सार्वजनिक व्यवहार"),
    HORA_SUN_SOURCE_REAL_ESTATE("Real estate", "घरजग्गा"),
    HORA_SUN_SOURCE_RELIGIOUS("Religious institutions", "धार्मिक संस्थाहरू"),
    HORA_SUN_SOURCE_RESEARCH("Research", "अनुसन्धान"),
    HORA_SUN_SOURCE_SPECULATION("Speculation", "अनुमान/सट्टा"),
    HORA_SUN_SOURCE_SPIRITUAL("Spiritual pursuits", "आध्यात्मिक कार्य"),
    HORA_SUN_SOURCE_SPORTS("Sports", "खेलकुद"),
    HORA_SUN_SOURCE_TEACHING("Teaching", "शिक्षण"),
    HORA_SUN_SOURCE_TECHNOLOGY("Technology", "प्रविधि"),
    HORA_SUN_SOURCE_TRADE("Trade", "व्यापार"),
    HORA_SUN_SOURCE_UNCONVENTIONAL("Unconventional means", "अपरम्परागत माध्यम"),
    HORA_SUN_TITLE("Sun Hora - Self-Earned Wealth", "सूर्य होरा - स्व-अर्जित धन"),
    HORA_VENUS("11:00 AM - 12:00 PM (Venus Hora)", "बिहान ११:०० - १२:०० (शुक्र होरा)"),
    HORA_WEALTH_INDICATORS("Wealth Indicators", "धन सूचकहरू"),
    HORA_WEALTH_SOURCES("Wealth Sources", "धनका स्रोतहरू"),
    NAVAMSA_7TH_LORD("7th Lord in Navamsa", "नवांशमा ७म स्वामी"),
    NAVAMSA_7TH_LORD_LABEL("7th Lord", "७म स्वामी"),
    NAVAMSA_APPEAR_JUPITER("Well-proportioned, dignified appearance", "मिलेको शरीर, मर्यादित रूप"),
    NAVAMSA_APPEAR_MARS("Athletic build, sharp features, reddish complexion", "एथलेटिक शरीर, तीक्ष्ण अनुहार, रातो वर्ण"),
    NAVAMSA_APPEAR_MERCURY("Youthful appearance, quick movements", "युवा जस्तो रूप, फुर्तिलो चाल"),
    NAVAMSA_APPEAR_MOON("Fair complexion, round face, attractive", "गोरो वर्ण, गोलो अनुहार, आकर्षक"),
    NAVAMSA_APPEAR_SATURN("Tall, thin build, mature appearance", "अग्लो, पातलो शरीर, परिपक्व रूप"),
    NAVAMSA_APPEAR_SUN("Medium height, well-built, commanding presence", "मध्यम उचाई, बलियो शरीर, प्रभावशाली उपस्थिति"),
    NAVAMSA_APPEAR_VARIES("Appearance varies", "रूप परिवर्तनशील हुन सक्छ"),
    NAVAMSA_APPEAR_VENUS("Very attractive, charming, pleasant features", "अत्यन्त आकर्षक, मोहक, रमाइलो अनुहार"),
    NAVAMSA_AREAS_ATTENTION("Areas for Attention", "ध्यान दिनुपर्ने क्षेत्रहरू"),
    NAVAMSA_DARAKARAKA("Darakaraka", "दाराकारक"),
    NAVAMSA_DIRECTION("Direction", "दिशा"),
    NAVAMSA_DIR_EAST("East direction", "पूर्व दिशा"),
    NAVAMSA_DIR_NORTH("North direction", "उत्तर दिशा"),
    NAVAMSA_DIR_SOUTH("South direction", "दक्षिण दिशा"),
    NAVAMSA_DIR_UNKNOWN("Direction not clearly indicated", "दिशा स्पष्ट रूपमा संकेत गरिएको छैन"),
    NAVAMSA_DIR_WEST("West direction", "पश्चिम दिशा"),
    NAVAMSA_FAMILY_BACKGROUND("Family Background", "पारिवारिक पृष्ठभूमि"),
    NAVAMSA_FAM_JUPITER("Respectable, possibly from educated or religious family", "प्रतिष्ठित, सम्भवतः शिक्षित वा धार्मिक परिवार"),
    NAVAMSA_FAM_MOON("Family-oriented, possibly business background", "पारिवारिक झुकाव भएको, सम्भवतः व्यापारिक पृष्ठभूमि"),
    NAVAMSA_FAM_SATURN("Hardworking family, possibly modest beginnings", "मेहनती परिवार, सम्भवतः साधारण सुरुवात"),
    NAVAMSA_FAM_SUN("Family with government or administrative background", "सरकारी वा प्रशासनिक पृष्ठभूमि भएको परिवार"),
    NAVAMSA_FAM_VARIES("Family background varies", "पारिवारिक पृष्ठभूमि फरक हुन सक्छ"),
    NAVAMSA_FAM_VENUS("Cultured family with appreciation for arts", "कलाको कदर गर्ने संस्कारी परिवार"),
    NAVAMSA_FAVORABLE_DASHA("Favorable Dasha", "शुभ दशा"),
    NAVAMSA_JUPITER("Jupiter", "बृहस्पति"),
    NAVAMSA_KEY_PLANETS_TITLE("Key Planets", "मुख्य ग्रहहरू"),
    NAVAMSA_MARRIAGE_ABOUT("About Navamsa for Marriage", "विवाहको लागि नवांशको बारेमा"),
    NAVAMSA_MARRIAGE_ABOUT_DESC("Navamsa is the most important divisional chart for marriage timing, spouse characteristics, and relationship quality.", "नवांश विवाह समय, जीवनसाथी विशेषताहरू, र सम्बन्ध गुणस्तरको लागि सबैभन्दा महत्त्वपूर्ण विभाजन चार्ट हो।"),
    NAVAMSA_MARRIAGE_SUBTITLE("D-9 Partnership Timing", "D-9 साझेदारी समय"),
    NAVAMSA_MARRIAGE_TIMING("Marriage Timing", "विवाह समय"),
    NAVAMSA_MARRIAGE_TITLE("Navamsa Marriage Analysis", "नवांश विवाह विश्लेषण"),
    NAVAMSA_MITIGATE_NONE("No strong multiple marriage indicators", "बहु विवाहको कुनै बलियो संकेत छैन"),
    NAVAMSA_MUHURTA_JUPITER("Best muhurta when Jupiter transits %1\$s or its trikona", "जब बृहस्पति %1\$s वा यसको त्रिकोणमा गोचर गर्छ, त्यो उत्तम मुहूर्त हो"),
    NAVAMSA_NATURE("General Nature", "सामान्य प्रकृति"),
    NAVAMSA_NATURE_JUPITER("Wise, religious, generous, optimistic", "ज्ञानी, धार्मिक, उदार, आशावादी"),
    NAVAMSA_NATURE_KETU("Spiritual, detached, intuitive, mysterious", "आध्यात्मिक, विरक्त, अन्तर्ज्ञानी, रहस्यमय"),
    NAVAMSA_NATURE_MARS("Energetic, assertive, passionate, athletic", "ऊर्जावान, दृढ, जोसिलो, एथलेटिक"),
    NAVAMSA_NATURE_MERCURY("Intelligent, communicative, youthful, adaptable", "बुद्धिमान, मिलनसार, युवावस्थाको, अनुकूलनशील"),
    NAVAMSA_NATURE_MIXED("Mixed qualities", "मिश्रित गुणहरू"),
    NAVAMSA_NATURE_MOON("Emotional, nurturing, sensitive, caring", "भावनात्मक, पालनपोषण गर्ने, संवेदनशील, दयालु"),
    NAVAMSA_NATURE_RAHU("Unconventional, foreign influence, ambitious", "अपरम्परागत, विदेशी प्रभाव, महत्त्वाकांक्षी"),
    NAVAMSA_NATURE_SATURN("Serious, hardworking, mature, responsible", "गम्भीर, मेहनती, परिपक्व, जिम्मेवार"),
    NAVAMSA_NATURE_SUN("Dignified, authoritative, proud, loyal", "मर्यादित, अधिकारपूर्ण, गर्विलो, वफादार"),
    NAVAMSA_NATURE_VENUS("Beautiful, artistic, romantic, pleasure-loving", "सुन्दर, कलात्मक, रोमान्टिक, विलासी"),
    NAVAMSA_PHYSICAL_TRAITS("Physical Traits", "शारीरिक लक्षण"),
    NAVAMSA_PROBABLE_PROFESSIONS("Probable Professions", "सम्भावित पेशाहरू"),
    NAVAMSA_PROF_ADMIN("Administration", "प्रशासन"),
    NAVAMSA_PROF_AGRICULTURE("Agriculture", "कृषि"),
    NAVAMSA_PROF_ARTS("Arts", "कला"),
    NAVAMSA_PROF_BUSINESS("Business", "व्यापार"),
    NAVAMSA_PROF_CONSTRUCTION("Construction", "निर्माण"),
    NAVAMSA_PROF_ENGINEERING("Engineering", "इन्जिनियरिङ"),
    NAVAMSA_PROF_ENTERTAINMENT("Entertainment", "मनोरञ्जन"),
    NAVAMSA_PROF_FASHION("Fashion", "फेसन"),
    NAVAMSA_PROF_FIELDS("Various fields", "विभिन्न क्षेत्रहरू"),
    NAVAMSA_PROF_FINANCE("Finance", "वित्त"),
    NAVAMSA_PROF_GOVT("Government", "सरकारी"),
    NAVAMSA_PROF_HEALTHCARE("Healthcare", "स्वास्थ्य सेवा"),
    NAVAMSA_PROF_HOSPITALITY("Hospitality", "आतिथ्य"),
    NAVAMSA_PROF_LABOR("Labor", "श्रम"),
    NAVAMSA_PROF_LAW("Law", "कानुन"),
    NAVAMSA_PROF_MEDICINE("Medicine", "चिकित्सा"),
    NAVAMSA_PROF_MILITARY("Military", "सेना"),
    NAVAMSA_PROF_PR("Public relations", "जनसम्पर्क"),
    NAVAMSA_PROF_SPORTS("Sports", "खेलकुद"),
    NAVAMSA_PROF_TEACHING("Teaching", "शिक्षण"),
    NAVAMSA_PROF_TECH("Technology", "प्रविधि"),
    NAVAMSA_PROF_VARIOUS("Various professions possible", "विभिन्न पेशाहरू सम्भव"),
    NAVAMSA_PROF_WRITING("Writing", "लेखन"),
    NAVAMSA_PROTECTIVE_FACTORS("Protective Factors", "रक्षात्मक कारकहरू"),
    NAVAMSA_REC_TIMING("Best marriage timing: During %1\$s Dasha/Antardasha", "उत्तम विवाह समय: %1\$s दशा/अन्तर्दशाको समयमा"),
    NAVAMSA_REC_VENUS_STRONG("Venus is strong - romantic approach to marriage is favorable", "शुक्र बलियो छ - विवाहप्रति रोमान्टिक दृष्टिकोण अनुकूल छ"),
    NAVAMSA_REC_VENUS_WEAK("Strengthen Venus through white colors, Fridays worship, and diamond/white sapphire", "सेतो रंग, शुक्रबारको पूजा, र हीरा/सेतो नीलम मार्फत शुक्रलाई बलियो बनाउनुहोस्"),
    NAVAMSA_RELATIONSHIP_QUALITY("Relationship Quality", "सम्बन्ध गुणस्तर"),
    NAVAMSA_RELATIONSHIP_STABILITY("Relationship Stability", "सम्बन्ध स्थिरता"),
    NAVAMSA_RISK_7TH_LORD_DUSTHANA("7th lord in dusthana", "७औं स्वामी दुःस्थानमा"),
    NAVAMSA_RISK_MULTIPLE_PLANETS("Multiple planets in 7th house", "७औं भावमा धेरै ग्रहहरू"),
    NAVAMSA_RISK_RETRO_VENUS("Retrograde Venus", "वक्री शुक्र"),
    NAVAMSA_SPOUSE_INDICATORS("Spouse Indicators", "जीवनसाथी सूचकहरू"),
    NAVAMSA_SPOUSE_TITLE("Spouse Characteristics", "जीवनसाथी विशेषताहरू"),
    NAVAMSA_TIMING_TITLE("Marriage Timing", "विवाह समय"),
    NAVAMSA_TRANSIT_JUPITER("Jupiter transit over 7th house from Moon or Navamsa Lagna", "चन्द्रमा वा नवांश लग्नबाट ७औं भावमा बृहस्पतिको गोचर"),
    NAVAMSA_UPAPADA("Upapada Lagna", "उपपद लग्न"),
    NAVAMSA_VENUS("Venus", "शुक्र"),
    NAVAMSA_VENUS_POSITION("Venus in Navamsa", "नवांशमा शुक्र"),
    SHODASHVARGA_16_DIAGRAMS_HEADER("The 16 Divisional Charts:", "१६ षोडशवर्ग कुण्डलीहरू:"),
    SHODASHVARGA_ABOUT("About Shodashvarga", "षोडशवर्गको बारेमा"),
    SHODASHVARGA_ABOUT_DESC("Shodashvarga Bala evaluates planetary strength across all 16 divisional charts. This comprehensive analysis reveals how effectively each planet can deliver its results.", "षोडशवर्ग बलले सबै १६ विभाजन चार्टहरूमा ग्रह बलको मूल्यांकन गर्दछ। यो व्यापक विश्लेषणले प्रत्येक ग्रहले आफ्नो परिणाम कति प्रभावकारी रूपमा प्रदान गर्न सक्छ भनेर प्रकट गर्दछ।"),
    SHODASHVARGA_BALA("Shodashvarga Bala", "षोडशवर्ग बल"),
    SHODASHVARGA_CALCULATION_ERROR("Failed to calculate Shodashvarga analysis", "षोडशवर्ग विश्लेषण गणना गर्न असफल"),
    SHODASHVARGA_NO_VARGOTTAMA("No Vargottama planets found", "कुनै वर्गोत्तम ग्रह फेला परेन"),
    SHODASHVARGA_SUBTITLE("16-Divisional Chart Analysis", "१६-विभाजन चार्ट विश्लेषण"),
    SHODASHVARGA_TITLE("Shodashvarga Strength", "षोडशवर्ग बल"),
    SHODASHVARGA_VARGOTTAMA_COUNT_FMT("Vargottama in %d chart(s)", "वर्गोत्तम %d कुण्डलीमा"),
    VARGA_BHAMSA("Bhamsa", "भांश"),
    VARGA_D108_DESC("Blessings, Divine Protection", "आशिर्वाद, दैवी सुरक्षा"),
    VARGA_D108_TITLE("Ashtottarshamsa (D108)", "अष्टोत्तरशांश (D108)"),
    VARGA_D10_DESC("Career, Profession", "क्यारियर, पेशा"),
    VARGA_D10_DESC_FULL("Career, Profession", "क्यारियर, पेशा"),
    VARGA_D10_NAME("Dasamsa Chart", "दशांश कुण्डली"),
    VARGA_D10_TITLE("Dasamsa (D10)", "दशमांश (D10)"),
    VARGA_D11_DESC("Victory, Defeat, Ups and Downs", "जीत, हार, उतार-चढाव"),
    VARGA_D11_TITLE("Rudramsa (D11)", "रुद्रांश (D11)"),
    VARGA_D12_DESC("Parents, Ancestry", "आमाबुवा, पुर्खा"),
    VARGA_D12_DESC_FULL("Parents, Ancestry", "आमाबुबा, पुर्खा"),
    VARGA_D12_NAME("Dwadasamsa Chart", "द्वादशांश कुण्डली"),
    VARGA_D12_TITLE("Dwadasamsa (D12)", "द्वादशांश (D12)"),
    VARGA_D144_DESC("Minute Details, Ultimate Micro-analysis", "अति सूक्ष्म विवरण"),
    VARGA_D144_TITLE("Dwadash-Dwadashamsa (D144)", "द्वादश-द्वादशांश (D144)"),
    VARGA_D16_DESC("Vehicles, Pleasures", "सवारी, आनन्द"),
    VARGA_D16_DESC_FULL("Vehicles, Pleasures", "सवारी, आनन्द"),
    VARGA_D16_NAME("Shodasamsa Chart", "षोडशांश कुण्डली"),
    VARGA_D16_TITLE("Shodasamsa (D16)", "षोडशांश (D16)"),
    VARGA_D1_DESC("Physical Body, General Life", "भौतिक शरीर, सामान्य जीवन"),
    VARGA_D1_NAME("Lagna Chart (Rashi)", "लग्न कुण्डली (राशि)"),
    VARGA_D1_TITLE("Rashi (D1)", "राशि (D1)"),
    VARGA_D20_DESC("Spiritual Life", "आध्यात्मिक जीवन"),
    VARGA_D20_DESC_FULL("Spiritual Life", "आध्यात्मिक जीवन"),
    VARGA_D20_NAME("Vimsamsa Chart", "विंशांश कुण्डली")
}
