package com.astro.storm.core.common

enum class StringKeyGeneralPart12(override val en: String, override val ne: String) : StringKeyInterface {
    TRI_PATAKI_ARTHA_AREA("financial or material growth", "आर्थिक वा भौतिक विकास"),
    TRI_PATAKI_ARTHA_DESC("Focus on material success, career, and stability.", "भौतिक सफलता, क्यारियर र स्थिरतामा ध्यान।"),
    TRI_PATAKI_BALANCED("Balanced Influence", "सन्तुलित प्रभाव"),
    TRI_PATAKI_BALANCED_DESC("Energy is evenly distributed across life areas.", "जीवनका क्षेत्रहरूमा ऊर्जा समान रूपमा वितरित छ।"),
    TRI_PATAKI_CHALLENGING("Challenging Activation", "चुनौतीपूर्ण सक्रियता"),
    TRI_PATAKI_DHARMA("Dharma Sector", "धर्म क्षेत्र"),
    TRI_PATAKI_DHARMA_AREA("spiritual or professional duties", "आध्यात्मिक वा व्यावसायिक कर्तव्यहरू"),
    TRI_PATAKI_DHARMA_DESC("Focus on purpose, spirituality, and duties.", "उद्देश्य, आध्यात्मिकता र कर्तव्यहरूमा ध्यान।"),
    TRI_PATAKI_EMPHASIS("Strong emphasis on %s.", "%s मा कडा जोड।"),
    TRI_PATAKI_FAVORABLE("Favorable Activation", "अनुकूल सक्रियता"),
    TRI_PATAKI_KAMA("Kama Sector", "काम क्षेत्र"),
    TRI_PATAKI_KAMA_AREA("desires and social connections", "इच्छाहरू र सामाजिक सम्बन्धहरू"),
    TRI_PATAKI_KAMA_DESC("Focus on desires, relationships, and social life.", "इच्छाहरू, सम्बन्धहरू र सामाजिक जीवनमा ध्यान।"),
    TRI_PATAKI_QUIET("Quiet Period", "शान्त अवधि"),
    TRI_PATAKI_VARIABLE("Variable Energy", "परिवर्तनशील ऊर्जा"),
    TWELFTH_LORD("12th House Lord", "द्वादश भाव स्वामी"),
    TWELFTH_SIGN("12th House Sign", "द्वादश भाव राशि"),
    UNIT_DAYS("days", "दिन"),
    UNIT_MONTHS("months", "महिना"),
    UNIT_RUPAS("rupas", "रुपास"),
    UNIT_YEARS("years", "वर्ष"),
    UPCOMING_DASHAS("Upcoming Dasha Periods", "आगामी दशा अवधिहरू"),
    UPCOMING_TRANSITS("Upcoming Significant Transits", "आगामी महत्त्वपूर्ण गोचरहरू"),
    VARGOTTAMA_DASHAMSA("Dashamsa Vargottama", "दशांश वर्गोत्तम"),
    VARGOTTAMA_DESC("Planet in same sign in D1 and divisional chart", "D1 र विभाजन चार्टमा समान राशिमा ग्रह"),
    VARGOTTAMA_NAVAMSA("Navamsa Vargottama", "नवांश वर्गोत्तम"),
    VARGOTTAMA_TITLE("Vargottama Planets", "वर्गोत्तम ग्रहहरू"),
    VARIOUS_ACTIVITIES("various activities", "विभिन्न गतिविधिहरू"),
    VARSHA_ASPECT_SUMMARY("Planetary aspects highlight %s. ", "ग्रहका दृष्टिहरूले %s लाई उजागर गर्दछ।"),
    VARSHA_BENEFICS_ENHANCE(" %s enhance positive outcomes.", " %s ले सकारात्मक परिणामहरू बढाउँछ।"),
    VARSHA_COORD_FORMAT("%.1f°", "%.1f°"),
    VARSHA_DASHA_CHALLENGING("A challenging phase for %s requiring extra effort and caution.", "अतिरिक्त प्रयास र सावधानी आवश्यक पर्ने %s को लागि एक चुनौतीपूर्ण चरण।"),
    VARSHA_DASHA_EXCEPTIONAL("An exceptional period for %s, bringing significant rewards.", "%s को लागि एक असाधारण अवधि, महत्त्वपूर्ण पुरस्कार ल्याउँदै।"),
    VARSHA_DASHA_MIXED("A mixed period for %s with both opportunities and minor hurdles.", "अवसर र साना बाधाहरू दुवै भएको %s को लागि एक मिश्रित अवधि।"),
    VARSHA_DASHA_PERIOD_FORMAT("%1\$s - %2\$s Period", "%1\$s - %2\$s अवधि"),
    VARSHA_DASHA_PREDICTION_FORMAT("%s focuses on %s. %s", "%s ले %s मा ध्यान केन्द्रित गर्दछ। %s"),
    VARSHA_DASHA_SUPPORTED("A well-supported time for %s and positive developments.", "%s र सकारात्मक विकासका लागि राम्रो समर्थन भएको समय।"),
    VARSHA_DEPENDS_LORD(" Results depend primarily on the lord's position.", " परिणामहरू मुख्यतया स्वामीको स्थितिमा निर्भर छन्।"),
    VARSHA_DURING_PERIOD("During this %s period, focus shifts to %s, particularly affecting %s. %s.", "यो %s अवधिमा, %s मा फोकस सर्छ, विशेष गरी %s लाई असर गर्दछ। %s।"),
    VARSHA_EVENT_ACADEMIC("Academic success or childbirth possible", "शैक्षिक सफलता वा सन्तान जन्म सम्भव"),
    VARSHA_EVENT_ACADEMIC_SUCCESS("Academic success or new learning opportunities", "शैक्षिक सफलता वा नयाँ सिकाइका अवसरहरू"),
    VARSHA_EVENT_ACCIDENTS("Increased energy - watch for accidents", "बढेको ऊर्जा - दुर्घटनाबाट सावधान"),
    VARSHA_EVENT_AUTHORITY_RECOGNITION("Gain of authority, fame, or social status", "अधिकार, नाम वा सामाजिक स्थितिको प्राप्ति"),
    VARSHA_EVENT_CAREER_ADVANCE("Career advancement or promotion", "क्यारियर प्रगति वा पदोन्नति"),
    VARSHA_EVENT_CAREER_ADVANCEMENT("Advancement in career or professional recognition", "क्यारियरमा प्रगति वा व्यावसायिक मान्यता"),
    VARSHA_EVENT_CHILDREN_MATTERS("Favorable for children's matters", "सन्तान सम्बन्धी मामिलाहरूको लागि अनुकूल"),
    VARSHA_EVENT_CREATIVE("Creative success and recognition", "सिर्जनात्मक सफलता र मान्यता"),
    VARSHA_EVENT_CREATIVE_SUCCESS("Success in creative pursuits and self-expression", "सिर्जनात्मक प्रयास र आत्म-अभिव्यक्तिमा सफलता"),
    VARSHA_EVENT_DASHA_BEGINS("%s Dasha Begins", "%s दशा सुरु हुन्छ"),
    VARSHA_EVENT_DASHA_BEGINS_DESC("A minor period of %s influence starts today.", "%s प्रभावको एक सानो अवधि आजदेखि सुरु हुन्छ।"),
    VARSHA_EVENT_DESIRES("Fulfillment of desires and wishes", "इच्छाहरू र कामनाहरूको पूर्ति"),
    VARSHA_EVENT_DESIRE_FULFILLMENT("Fulfillment of long-held desires and ambitions", "लामो समयदेखिका इच्छाहरू र महत्त्वाकांक्षाहरूको पूर्ति"),
    VARSHA_EVENT_FAMILY("Improvement in family relationships", "पारिवारिक सम्बन्धमा सुधार"),
    VARSHA_EVENT_FAMILY_RELATIONS("Strengthening of family bonds and values", "पारिवारिक सम्बन्ध र मूल्य मान्यताको सुदृढीकरण"),
    VARSHA_EVENT_FINANCIAL("Financial gains and wealth accumulation", "आर्थिक लाभ र धन संचय"),
    VARSHA_EVENT_FINANCIAL_GAINS("Significant financial gains or new income sources", "महत्त्वपूर्ण आर्थिक लाभ वा नयाँ आय स्रोत"),
    VARSHA_EVENT_GOVERNMENT_FAVOR("Favor from government or influential figures", "सरकार वा प्रभावशाली व्यक्तिहरूबाट सहयोग"),
    VARSHA_EVENT_GOVT_FAVOR("Government favor or leadership role", "सरकारी कृपा वा नेतृत्व भूमिका"),
    VARSHA_EVENT_INCREASED_ENERGY("Increased energy and dynamic activity", "बढेको ऊर्जा र गतिशील गतिविधि"),
    VARSHA_EVENT_LUXURY("Acquisition of luxury items", "विलासी वस्तुहरूको प्राप्ति"),
    VARSHA_EVENT_LUXURY_ACQUISITION("Acquisition of luxury items or increased comforts", "लक्जरी वस्तुहरूको प्राप्ति वा बढेको सुखसुविधा"),
    VARSHA_EVENT_MARRIAGE_BUSINESS("Favorable for marriage or business", "विवाह वा व्यापारको लागि अनुकूल"),
    VARSHA_EVENT_MARRIAGE_FAVORABLE("Favorable conditions for marriage or long-term commitments", "विवाह वा दीर्घकालीन प्रतिबद्धताको लागि अनुकूल परिस्थिति"),
    VARSHA_EVENT_MULTIPLE_GAINS("Gains from multiple sources", "विभिन्न स्रोतहरूबाट लाभ"),
    VARSHA_EVENT_NEW_VENTURES("Favorable for starting new ventures", "नयाँ उद्यमहरू सुरु गर्न अनुकूल"),
    VARSHA_EVENT_PARTNERSHIPS("Strengthening of partnerships", "साझेदारीहरूको सुदृढीकरण"),
    VARSHA_EVENT_PARTNERSHIP_STRENGTH("Strengthening of business or personal partnerships", "व्यापार वा व्यक्तिगत साझेदारीको सुदृढीकरण"),
    VARSHA_EVENT_RECOGNITION("Recognition from authorities", "अधिकारीहरूबाट मान्यता"),
    VARSHA_EVENT_ROMANTIC("Romantic happiness", "रोमान्टिक खुशी"),
    VARSHA_EVENT_ROMANTIC_FULFILL("Romantic fulfillment", "रोमान्टिक पूर्णता"),
    VARSHA_EVENT_ROMANTIC_FULFILLMENT("Emotional fulfillment through significant others", "महत्त्वपूर्ण व्यक्तिहरू मार्फत भावनात्मक सन्तुष्टि"),
    VARSHA_EVENT_ROMANTIC_HAPPINESS("Happiness in romantic relationships or with children", "रोमान्टिक सम्बन्ध वा सन्तानसँगको खुशी"),
    VARSHA_EVENT_SOLAR_RETURN("Solar Return Activation", "सौर्य फिर्ती सक्रियता"),
    VARSHA_EVENT_SOLAR_RETURN_DESC("The precise moment the Sun returns to your birth position.", "सूर्य तपाईंको जन्म स्थितिमा फर्कने सटीक क्षण।"),
    VARSHA_EVENT_SPIRITUAL("Spiritual growth and wisdom", "आध्यात्मिक वृद्धि र बुद्धि"),
    VARSHA_EVENT_SPIRITUAL_GROWTH("Spiritual growth and self-discovery", "आध्यात्मिक विकास र आत्म-खोज"),
    VARSHA_EVENT_VITALITY("Increased vitality and personal confidence", "बढेको जीवनशक्ति र व्यक्तिगत आत्मविश्वास"),
    VARSHA_FORMAT_DATE_FULL("EEEE, MMMM d, yyyy", "EEEE, MMMM d, yyyy"),
    VARSHA_FORMAT_DATE_SHORT("MMM d", "MMM d"),
    VARSHA_FORMAT_TIME_FULL("h:mm:ss a", "h:mm:ss a"),
    VARSHA_GENERAL_NATURE("general influences", "सामान्य प्रभावहरू"),
    VARSHA_HOUSE_10_SIG("career and status", "क्यारियर र स्थिति"),
    VARSHA_HOUSE_11_SIG("gains and friendships", "लाभ र मित्रता"),
    VARSHA_HOUSE_12_SIG("spirituality and foreign matters", "आध्यात्मिकता र विदेशी मामिलाहरू"),
    VARSHA_HOUSE_1_SIG("personal development and health", "व्यक्तिगत विकास र स्वास्थ्य"),
    VARSHA_HOUSE_2_SIG("finances and family", "वित्त र परिवार"),
    VARSHA_HOUSE_3_SIG("communication and siblings", "सञ्चार र भाइबहिनी"),
    VARSHA_HOUSE_4_SIG("home and property", "घर र सम्पत्ति"),
    VARSHA_HOUSE_5_SIG("creativity and children", "सिर्जनशीलता र सन्तान"),
    VARSHA_HOUSE_6_SIG("health and service", "स्वास्थ्य र सेवा"),
    VARSHA_HOUSE_7_SIG("partnerships and marriage", "साझेदारी र विवाह"),
    VARSHA_HOUSE_8_SIG("transformation and inheritance", "रूपान्तरण र विरासत"),
    VARSHA_HOUSE_9_SIG("fortune and higher learning", "भाग्य र उच्च शिक्षा"),
    VARSHA_HOUSE_BENEFICS_ENHANCE("Presence of benefic planets enhances the themes of %s.", "शुभ ग्रहहरूको उपस्थितिले %s का विषयहरूलाई सुधार्छ।"),
    VARSHA_HOUSE_GENERAL_SIG("general life matters", "सामान्य जीवनका मामिलाहरू"),
    VARSHA_HOUSE_GOVERNS("House %d in %s governs %s.", "भाव %d %s मा %s शासन गर्दछ।"),
    VARSHA_HOUSE_LORD_CHALLENGED("The lord faces challenges here, requiring caution and extra effort regarding %s.", "स्वामीले यहाँ चुनौतीहरूको सामना गर्नु पर्छ, जसले %s को सम्बन्धमा सावधानी र अतिरिक्त प्रयासको आवश्यकता देखाउँछ।"),
    VARSHA_HOUSE_LORD_DEPENDENT("Success in %s depends heavily on other planetary configurations.", "%s मा सफलता धेरै हदसम्म अन्य ग्रह विन्यासमा निर्भर गर्दछ।"),
    VARSHA_HOUSE_LORD_EXCELLENT("This position is exceptionally strong, promising major success in %s.", "यो स्थिति असाधारण रूपमा बलियो छ, जसले %s मा ठूलो सफलताको वाचा गर्दछ।"),
    VARSHA_HOUSE_LORD_MODERATE("The lord's position is moderate, indicating balanced results for %s.", "स्वामीको स्थिति मध्यम छ, जसले %s को लागि सन्तुलित नतिजाहरू संकेत गर्दछ।"),
    VARSHA_HOUSE_LORD_POSITION("The house lord %s is positioned in H%d.", "भाव स्वामी %s भाव%d मा स्थित छ।"),
    VARSHA_HOUSE_LORD_STRONG("The lord is well-placed, supporting steady growth and positive results in %s.", "स्वामी राम्रो स्थानमा छ, जसले %s मा स्थिर विकास र सकारात्मक नतिजाहरूलाई समर्थन गर्दछ।"),
    VARSHA_HOUSE_LORD_VARIABLE("Current placement indicates variable or inconsistent results for %s.", "वर्तमान स्थितिले %s को लागि परिवर्तनशील वा अस्थिर नतिजाहरू संकेत गर्दछ।"),
    VARSHA_HOUSE_MALEFICS_CHALLENGE("Presence of malefic planets may challenge the stability of %s.", "पाप ग्रहहरूको उपस्थितिले %s को स्थिरतालाई चुनौती दिन सक्छ।"),
    VARSHA_HOUSE_MIXED_INF("Mixed planetary influences suggest a period of ups and downs for %s.", "मिश्रित ग्रह प्रभावले %s को लागि उतारचढावको अवधि संकेत गर्दछ।"),
    VARSHA_HOUSE_MUNTHA_EMPHASIS("Muntha's presence here significantly increases the priority of %s this year.", "यहाँ मुन्थको उपस्थितिले यस वर्ष %s को प्राथमिकतालाई महत्त्वपूर्ण रूपमा बढाउँछ।"),
    VARSHA_HOUSE_PREDICTION_FORMAT("House %1\$d (%2\$s) Overview: %3\$s. %4\$s %5\$s %6\$s", "भाव %1\$d (%2\$s) अवलोकन: %3\$s। %4\$s %5\$s %6\$s"),
    VARSHA_HOUSE_VARIOUS("various life areas", "विभिन्न जीवन क्षेत्रहरू"),
    VARSHA_HOUSE_YEARLORD_RULE("Year Lord's rule over this house elevates the importance of %s matters.", "यस भावमा वर्ष स्वामीको शासनले %s मामिलाहरूको महत्त्व बढाउँछ।"),
    VARSHA_JUPITER_NATURE("wisdom, expansion, and good fortune", "बुद्धि, विस्तार र सुभाग्य"),
    VARSHA_KETU_NATURE("spirituality, detachment, and past karma", "आध्यात्मिकता, वैराग्य र पूर्व कर्म"),
    VARSHA_LORD_CHALLENGES("faces challenges requiring attention.", "ध्यान चाहिने चुनौतीहरूको सामना गर्दछ।"),
    VARSHA_LORD_EXCELLENT("is excellently placed for positive outcomes.", "सकारात्मक परिणामहरूको लागि उत्कृष्ट रूपमा स्थित छ।"),
    VARSHA_LORD_IN_HOUSE("The lord %s in house %d ", "स्वामी %s भाव %d मा "),
    VARSHA_LORD_MODERATE_SUPPORT("provides moderate support.", "मध्यम समर्थन प्रदान गर्दछ।"),
    VARSHA_LORD_VARIABLE("influences results variably.", "परिणामहरूलाई परिवर्तनशील रूपमा प्रभाव पार्छ।"),
    VARSHA_LORD_WELL_POSITIONED("is well-positioned for success.", "सफलताको लागि राम्ररी स्थित छ।"),
    VARSHA_MALEFICS_CHALLENGE(" %s may bring challenges.", " %s ले चुनौतीहरू ल्याउन सक्छ।"),
    VARSHA_MARS_NATURE("energy, initiative, and competitive drive", "ऊर्जा, पहल र प्रतिस्पर्धात्मक उत्प्रेरणा"),
    VARSHA_MERCURY_NATURE("communication, learning, and business", "सञ्चार, सिकाइ र व्यापार"),
    VARSHA_MIXED_PLANETS(" Mixed influences from %s.", " %s बाट मिश्रित प्रभावहरू।"),
    VARSHA_MOON_NATURE("emotions, nurturing, and public connections", "भावनाहरू, पालनपोषण र सार्वजनिक सम्बन्धहरू"),
    VARSHA_MUNTHA_DIRECTS("Muntha in House %d (%s) directs attention to %s.", "भाव %d (%s) मा मुन्थले %s मा ध्यान केन्द्रित गर्दछ।"),
    VARSHA_MUNTHA_EMPHASIS(" Muntha emphasizes these matters this year.", " मुन्थले यस वर्ष यी मामिलाहरूमा जोड दिन्छ।"),
    VARSHA_MUNTHA_INFLUENCE("Muntha in %s suggests emphasis on %s. ", "%s मा मुन्थले %s मा जोड दिने संकेत गर्दछ।"),
    VARSHA_MUNTHA_POS_FORMAT("House %1\$d • %2\$.1f°", "भाव %1\$d • %2\$.1f°"),
    VARSHA_OVERALL_TEMPLATE("This Varshaphala year presents an overall %s outlook. %s %s The Tajika aspects show %d favorable and %d challenging configurations. By understanding these influences, the year's potential can be maximized.", "यो वर्षफल वर्षले समग्र %s दृष्टिकोण प्रस्तुत गर्दछ। %s %s ताजिक पक्षहरूले %d अनुकूल र %d चुनौतीपूर्ण विन्यासहरू देखाउँछन्। यी प्रभावहरूलाई बुझेर, वर्षको सम्भावनालाई अधिकतम बनाउन सकिन्छ।"),
    VARSHA_OVERALL_TONE("Overall, the year appears to be %s. ", "समग्रमा, वर्ष %s देखिन्छ।"),
    VARSHA_PERIOD_EXCEPTIONAL("This period promises exceptional results", "यो अवधिले असाधारण परिणामहरूको वाचा गर्छ"),
    VARSHA_PERIOD_EXTRA_EFFORT("This period requires extra effort and patience", "यो अवधिमा थप प्रयास र धैर्य चाहिन्छ"),
    VARSHA_PERIOD_MIXED("This period brings mixed but manageable influences", "यो अवधिले मिश्रित तर व्यवस्थापनयोग्य प्रभावहरू ल्याउँछ"),
    VARSHA_PERIOD_WELL_SUPPORTED("This period is well-supported for success", "यो अवधि सफलताको लागि राम्ररी समर्थित छ"),
    VARSHA_POTENTIAL_MAXIMIZED("Success can be maximized by focusing on %s.", "%s मा ध्यान केन्द्रित गरेर सफलतालाई अधिकतम बनाउन सकिन्छ।"),
    VARSHA_RAHU_NATURE("ambition, innovation, and unconventional paths", "महत्त्वाकांक्षा, नवीनता र अपरम्परागत मार्गहरू"),
    VARSHA_REPORT_CHALLENGING_MONTHS("CHALLENGING MONTHS: %s", "चुनौतीपूर्ण महिनाहरू: %s"),
    VARSHA_REPORT_CURRENT_MARKER(" [CURRENT]", " [वर्तमान]"),
    VARSHA_REPORT_DASHA_LINE("%s: %s to %s (%d days)%s", "%s: %s देखि %s (%d दिन)%s"),
    VARSHA_REPORT_FAVORABLE_MONTHS("FAVORABLE MONTHS: %s", "अनुकूल महिनाहरू: %s"),
    VARSHA_REPORT_FOOTER("Generated by AstroStorm - Ultra-Precision Vedic Astrology", "AstroStorm द्वारा उत्पन्न - अति-सटीक वैदिक ज्योतिष"),
    VARSHA_REPORT_MUNTHA_HOUSE("Muntha House: %d", "मुन्थ भाव: %d"),
    VARSHA_REPORT_MUNTHA_LORD("Muntha Lord: %s in House %d", "मुन्थ स्वामी: %s भाव %d मा"),
    VARSHA_REPORT_MUNTHA_POSITION("Muntha Position: %s° %s", "मुन्थ स्थिति: %s° %s"),
    VARSHA_REPORT_NAME("Name: %s", "नाम: %s"),
    VARSHA_REPORT_POSITION("Position: House %d", "स्थिति: भाव %d"),
    VARSHA_REPORT_SECTION_MUDDA("MUDDA DASHA PERIODS", "मुद्द दशा अवधिहरू"),
    VARSHA_REPORT_SECTION_MUNTHA("MUNTHA", "मुन्थ"),
    VARSHA_REPORT_SECTION_PREDICTION("OVERALL PREDICTION", "समग्र भविष्यवाणी"),
    VARSHA_REPORT_SECTION_THEMES("MAJOR THEMES", "मुख्य विषयहरू"),
    VARSHA_REPORT_SECTION_YEARLORD("YEAR LORD", "वर्ष स्वामी"),
    VARSHA_REPORT_SOLAR_RETURN("Solar Return: %s", "सौर प्रतिफल: %s"),
    VARSHA_REPORT_TITLE("VARSHAPHALA (ANNUAL HOROSCOPE) REPORT", "वर्षफल (वार्षिक राशिफल) रिपोर्ट"),
    VARSHA_REPORT_YEAR("Year: %d (Age: %d)", "वर्ष: %d (उमेर: %d)"),
    VARSHA_REPORT_YEARLORD_LINE("Year Lord: %s (%s)", "वर्ष स्वामी: %s (%s)"),
    VARSHA_REPORT_YEAR_RATING("Year Rating: %s/5.0", "वर्ष मूल्याङ्कन: %s/५.०"),
    VARSHA_RESET_YEAR("Reset to Current Year", "हालको वर्षमा रिसेट गर्नुहोस्"),
    VARSHA_SAHAM_LORD_SUPPORT("The lord %s provides %s support.", "स्वामी %s ले %s समर्थन प्रदान गर्दछ।"),
    VARSHA_SAHAM_RELATES("relates to %s", "%s सँग सम्बन्धित छ"),
    VARSHA_SATURN_NATURE("discipline, responsibility, and long-term goals", "अनुशासन, जिम्मेवारी र दीर्घकालीन लक्ष्यहरू"),
    VARSHA_SIGN_DEGREE_FORMAT("%1\$s %2\$.1f°", "%1\$s %2\$.1f°"),
    VARSHA_STRENGTH_ANGULAR("Angular", "केन्द्रीय"),
    VARSHA_STRENGTH_CHALLENGED("Challenged", "चुनौतीपूर्ण"),
    VARSHA_STRENGTH_DEBILITATED("Debilitated", "नीच"),
    VARSHA_STRENGTH_EXALTED("Exalted", "उच्च"),
    VARSHA_STRENGTH_EXCELLENT("Excellent", "उत्कृष्ट"),
    VARSHA_STRENGTH_MODERATE("Moderate", "मध्यम"),
    VARSHA_STRENGTH_RETROGRADE("Retrograde", "वक्री"),
    VARSHA_STRENGTH_STRONG("Strong", "बलियो"),
    VARSHA_STRENGTH_UNKNOWN("Unknown", "अज्ञात"),
    VARSHA_STRENGTH_WEAK("Weak", "कमजोर"),
    VARSHA_SUN_NATURE("vitality, authority, and self-expression", "जीवनशक्ति, अधिकार र आत्म-अभिव्यक्ति"),
    VARSHA_THEME_FAVORABLE("Favorable year for overall progress", "समग्र प्रगतिको लागि अनुकूल वर्ष"),
    VARSHA_THEME_MUNTHA("Muntha Focus: House %1\$d - %2\$s", "मुन्थ फोकस: भाव %1\$d - %2\$s"),
    VARSHA_THEME_TAJIKA("Tajika Aspect Influence: %1\$s (%2\$d/%3\$d)", "ताजिक दृष्टि प्रभाव: %1\$s (%2\$d/%3\$d)"),
    VARSHA_THEME_TRIPATAKI("Tri-Pataki Activation in %s", "%s मा त्रिपताकी सक्रियता"),
    VARSHA_THEME_YEARLORD("Year Lord (%s Influence)", "वर्ष स्वामी (%s प्रभाव)"),
    VARSHA_TONE_BALANCED("balanced", "सन्तुलित"),
    VARSHA_TONE_CHALLENGING("challenging but growth-oriented", "चुनौतीपूर्ण तर विकासोन्मुख"),
    VARSHA_TONE_CHALLENGING_GROWTH("challenging but growth-oriented", "चुनौतीपूर्ण तर विकास उन्मुख"),
    VARSHA_TONE_EXCELLENT("excellent", "उत्कृष्ट"),
    VARSHA_TONE_FAVORABLE("favorable", "अनुकूल"),
    VARSHA_TONE_POSITIVE("positive", "सकारात्मक"),
    VARSHA_TONE_SUPPORTIVE("supportive", "सहयोगी"),
    VARSHA_VENUS_NATURE("relationships, creativity, and pleasures", "सम्बन्धहरू, सिर्जनशीलता र आनन्द"),
    VARSHA_YEARLORD_DIGNITY_FORMAT("%1\$s is in %2\$s (House %3\$d)", "%1\$s भाव %3\$d मा %2\$s राशिमा छ"),
    VARSHA_YEARLORD_GENERAL("The year is ruled by %s, bringing %s focus. ", "यो वर्ष %s द्वारा शासित छ, जसले %s ध्यान ल्याउँछ।"),
    VARSHA_YEARLORD_GENERIC("The Year Lord influences various aspects with balanced energy.", "वर्ष स्वामीले सन्तुलित ऊर्जासहित विभिन्न पक्षहरूलाई प्रभाव पार्छ।"),
    VARSHA_YEARLORD_JUPITER("Year Lord Jupiter bestows wisdom, expansion, and good fortune.", "वर्ष स्वामी बृहस्पतिले बुद्धि, विस्तार र सुभाग्य प्रदान गर्छ।"),
    VARSHA_YEARLORD_MARS("Year Lord Mars energizes initiatives and competitive endeavors.", "वर्ष स्वामी मंगलले पहलहरू र प्रतिस्पर्धात्मक प्रयासहरूलाई ऊर्जित गर्छ।"),
    VARSHA_YEARLORD_MERCURY("Year Lord Mercury enhances communication and business activities.", "वर्ष स्वामी बुधले सञ्चार र व्यापारिक गतिविधिहरू बढाउँछ।"),
    VARSHA_YEARLORD_MOON("Year Lord Moon emphasizes emotional wellbeing and public connections.", "वर्ष स्वामी चन्द्रमाले भावनात्मक कल्याण र सार्वजनिक सम्बन्धहरूमा जोड दिन्छ।"),
    VARSHA_YEARLORD_RULES(" Year Lord rules this house - significant developments expected.", " वर्ष स्वामीले यो भाव शासन गर्छ - महत्त्वपूर्ण विकासहरू अपेक्षित।"),
    VARSHA_YEARLORD_SATURN("Year Lord Saturn teaches discipline and responsibility.", "वर्ष स्वामी शनिले अनुशासन र जिम्मेवारी सिकाउँछ।"),
    VARSHA_YEARLORD_SUN("Year Lord Sun brings focus on leadership, authority, and self-expression.", "वर्ष स्वामी सूर्यले नेतृत्व, अधिकार र आत्म-अभिव्यक्तिमा फोकस ल्याउँछ।"),
    VARSHA_YEARLORD_VENUS("Year Lord Venus brings harmony to relationships and creativity.", "वर्ष स्वामी शुक्रले सम्बन्धहरू र सिर्जनशीलतामा सामञ्जस्य ल्याउँछ।"),
    VASUMATHI_YOGA("Vasumathi Yoga", "वसुमती योग"),
    VEDHA_ACTIVE("Active Vedhas", "सक्रिय वेधहरू"),
    VEDHA_COMPLETE("Complete Obstruction", "पूर्ण अवरोध"),
    VEDHA_FAVORABLE_COUNT("Favorable Transits", "अनुकूल गोचरहरू"),
    VEDHA_KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टिहरू"),
    VEDHA_LOST_BENEFITS("Lost Benefits", "गुमाएको फाइदाहरू"),
    VEDHA_MODERATE("Moderate Obstruction", "मध्यम अवरोध"),
    VEDHA_NONE("No Obstruction", "कुनै अवरोध छैन"),
    VEDHA_NOT_PRESENT("No Vedha between the nakshatras - favorable", "नक्षत्रहरू बीच वेध छैन - अनुकूल"),
    VEDHA_OBSTRUCTED_BY("Obstructed by", "द्वारा अवरुद्ध"),
    VEDHA_OBSTRUCTED_COUNT("Obstructed Transits", "अवरुद्ध गोचरहरू"),
    VEDHA_OBSTRUCTION(" However, %s creates Vedha obstruction, reducing benefits.", " तर, %s ले वेध अवरोध सिर्जना गर्छ, जसले लाभ कम गर्छ।"),
    VEDHA_OVERALL_SCORE("Overall Transit Score", "समग्र गोचर स्कोर"),
    VEDHA_OVERVIEW("Transit Overview", "गोचर सिंहावलोकन"),
    VEDHA_PARTIAL("Partial Obstruction", "आंशिक अवरोध"),
    VEDHA_PLANET_TRANSITS("Planetary Transits", "ग्रह गोचरहरू"),
    VEDHA_PRESENT("Vedha (obstruction) present between {nak1} and {nak2} - may cause obstacles", "वेध (बाधा) {nak1} र {nak2} बीच उपस्थित - अवरोधहरू हुन सक्छ"),
    VEDHA_STRONG("Strong Obstruction", "बलियो अवरोध"),
    VEDHA_SUBTITLE("Transit Obstruction Analysis", "गोचर अवरोध विश्लेषण"),
    VEDHA_TITLE("Gochara Vedha Analysis", "गोचर वेध विश्लेषण"),
    VENUS_DIGNITY("Venus Dignity", "शुक्र गौरव"),
    VENUS_HEALTH("Venus Health Influence", "शुक्र स्वास्थ्य प्रभाव"),
    VENUS_HOUSE("Venus House", "शुक्र भाव"),
    VENUS_NAKSHATRA("Venus Nakshatra", "शुक्र नक्षत्र"),
    VENUS_SIGN("Venus Sign", "शुक्र राशि"),
    VERY_FAVORABLE("Very Favorable", "धेरै अनुकूल"),
    VIEW_CURRENT_TRANSITS("View current planetary positions", "हालको ग्रह स्थितिहरू हेर्नुहोस्"),
    VIMSOPAKA_BALA("Vimsopaka Bala", "विम्शोपक बल"),
    VIMSOPAKA_MADHYA("Madhya Scheme", "मध्य योजना"),
    VIMSOPAKA_PARA("Para Scheme", "पर योजना"),
    VIMSOPAKA_POORVA("Poorva Scheme", "पूर्व योजना"),
    VIPAREETA_ABOUT_DESC("Vipareeta Raja Yogas are formed when lords of dusthana houses (6th, 8th, 12th) are placed in other dusthana houses. The three yogas are: Harsha (6th lord in 6/8/12), Sarala (8th lord in 6/8/12), and Vimala (12th lord in 6/8/12). These yogas operate on the principle that 'negative times negative equals positive', transforming adversity into success and gains from unexpected sources.", "विपरीत राजयोग दुस्थान भावका स्वामी (६, ८, १२) अन्य दुस्थान भावमा रहेमा बन्दछन्। तीन योगहरू: हर्ष (६औंको स्वामी ६/८/१२मा), सरल (८औंको स्वामी ६/८/१२मा), र विमल (१२औंको स्वामी ६/८/१२मा)। यी योगहरू 'नकारात्मक गुणा नकारात्मक बराबर सकारात्मक' सिद्धान्तमा काम गर्दछन्, प्रतिकूलतालाई सफलतामा र अप्रत्याशित स्रोतबाट लाभमा रूपान्तरण गर्दछन्।"),
    VIPAREETA_ABOUT_TITLE("About Vipareeta Raja Yoga", "विपरीत राजयोगको बारेमा"),
    VIPAREETA_ACTIVATIONS("Activations", "सक्रियताहरू"),
    VIPAREETA_ACTIVATION_PERIODS("Activation Periods", "सक्रियता अवधि"),
    VIPAREETA_ALL_YOGAS("All Three Vipareeta Raja Yogas!", "तीनवटै विपरीत राजयोग!"),
    VIPAREETA_ANALYZING("Analyzing Vipareeta Raja Yogas...", "विपरीत राजयोग विश्लेषण गर्दै..."),
    VIPAREETA_BENEFITS("Benefits", "लाभहरू"),
    VIPAREETA_CANCELLATION("Cancellation Factors", "रद्द कारकहरू"),
    VIPAREETA_ENHANCEMENT("Enhancement Factors", "वृद्धि कारकहरू"),
    VIPAREETA_EXCHANGES("Exchanges", "परिवर्तनहरू"),
    VIPAREETA_EXCHANGES_TITLE("Dusthana Parivartana (Exchanges)", "दुस्थान परिवर्तन"),
    VIPAREETA_NO_BENEFITS("No specific benefits identified without active yogas.", "सक्रिय योग बिना कुनै विशेष लाभ पहिचान गरिएको छैन।"),
    VIPAREETA_NO_CHART_DESC("Please generate a chart to view Vipareeta Raja Yoga analysis.", "विपरीत राजयोग विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
    VIPAREETA_NO_FACTORS("No significant enhancement or cancellation factors.", "कुनै महत्त्वपूर्ण वृद्धि वा रद्द कारकहरू छैनन्।"),
    VIPAREETA_NO_TIMING("No activation periods without active yogas.", "सक्रिय योग बिना कुनै सक्रियता अवधि छैन।"),
    VIPAREETA_NO_YOGAS("No Vipareeta Raja Yogas", "कुनै विपरीत राजयोग छैन"),
    VIPAREETA_ONE_YOGA("One Vipareeta Raja Yoga", "एक विपरीत राजयोग"),
    VIPAREETA_PRIMARY_BENEFITS("Primary Benefits", "प्राथमिक लाभहरू"),
    VIPAREETA_SCREEN_TITLE("Vipareeta Raja Yoga", "विपरीत राजयोग"),
    VIPAREETA_STRENGTH("Overall Strength", "समग्र शक्ति"),
    VIPAREETA_SUBTITLE("Reverse Fortune Yogas", "उल्टो भाग्य योगहरू"),
    VIPAREETA_TAB_BENEFITS("Benefits", "लाभहरू"),
    VIPAREETA_TAB_FACTORS("Factors", "कारकहरू"),
    VIPAREETA_TWO_YOGAS("Two Vipareeta Raja Yogas", "दुई विपरीत राजयोग"),
    VIPAREETA_YOGAS_FORMED("Yogas Formed", "बनेका योगहरू"),
    VIP_DESC_HARSHA("6th lord in dusthana - Victory over enemies, good health, happiness from overcoming obstacles", "६औं भावको स्वामी दुस्थानमा - शत्रुमाथि विजय, राम्रो स्वास्थ्य, बाधाहरू पार गरेर सुख"),
    VIP_DESC_SARALA("8th lord in dusthana - Fearlessness, longevity, gains through inheritance, occult knowledge", "८औं भावको स्वामी दुस्थानमा - निडरता, दीर्घायु, उत्तराधिकारबाट लाभ, गुप्त ज्ञान"),
    VIP_DESC_VIMALA("12th lord in dusthana - Reduced losses, spiritual advancement, liberation, fame after death", "१२औं भावको स्वामी दुस्थानमा - घाटामा कमी, आध्यात्मिक उन्नति, मुक्ति, मृत्युपछि प्रसिद्धि"),
    VULNERABILITIES_TITLE("Health Vulnerabilities", "स्वास्थ्य कमजोरीहरू"),
    VULNERABILITY_AREA("Vulnerable Area", "कमजोर क्षेत्र"),
    VULNERABILITY_SEVERITY("Severity Level", "गम्भीरता स्तर"),
    WARNING_LABEL("Warning", "चेतावनी"),
    WAR_BRIGHTNESS("Greater Brightness", "अधिक चमक"),
    WAR_COMBINED("Both Factors", "दुवै कारक"),
    WAR_INDETERMINATE("Evenly Matched", "बराबर"),
    WAR_NORTHERN_LAT("Northern Latitude", "उत्तरी अक्षांश"),
    WEAKEST_PLANET("Weakest Planet", "दुर्बल ग्रह"),
    WEAKNESS_AFFLICTED_MALEFIC("Afflicted by malefic conjunction", "पाप ग्रहको युतिबाट पीडित"),
    WEAKNESS_ANGER_ISSUES("Anger issues", "क्रोधका समस्याहरू"),
    WEAKNESS_ANXIETY("Anxiety", "चिन्ता"),
    WEAKNESS_COMBUST("Combust position reduces yoga strength", "अस्त स्थितिले योगको बल घटाउँछ"),
    WEAKNESS_CRITICAL_NATURE("Critical nature", "आलोचनात्मक प्रकृति"),
    WEAKNESS_DEBILITATED("Debilitated dusthana lord - weakened results", "नीच दुस्थान स्वामी - कमजोर परिणाम"),
    WEAKNESS_DOMINATING("Dominating", "दबाब दिने"),
    WEAKNESS_EXTREMISM("Extremism", "अतिवाद"),
    WEAKNESS_HARSH_SPEECH("Harsh speech", "कठोर बोली"),
    WEAKNESS_IMPATIENCE("Impatience", "अधैर्यता"),
    WEAKNESS_JEALOUSY("Jealousy", "ईर्ष्या"),
    WEAKNESS_OVERCONFIDENCE("Overconfidence", "अत्यधिक आत्मविश्वास"),
    WEAKNESS_OVERTHINKING("Overthinking", "अत्यधिक सोच"),
    WEAKNESS_PERFECTIONISM("Perfectionism", "पूर्णतावाद"),
    WEAKNESS_POSSESSIVENESS("Possessiveness", "मोह"),
    WEAKNESS_RECKLESSNESS("Recklessness", "लापरवाही"),
    WEAKNESS_RESTLESSNESS("Restlessness", "अस्थिरता"),
    WEAKNESS_SENSITIVITY("Sensitivity", "संवेदनशीलता"),
    WEAKNESS_STUBBORNNESS("Stubbornness", "जिद्दीपन"),
    WEAK_PLANET_CHALLENGE("Weak Planet Challenge", "कमजोर ग्रह चुनौती"),
    WEALTH_11TH_LORD_STRONG("Your 11th house lord is favorable, indicating gains through various sources and fulfillment of desires.",
        "तपाईंको ११औं भावको स्वामी अनुकूल छ, विभिन्न स्रोतहरूबाट लाभ र इच्छाहरूको पूर्ति संकेत गर्दै।"),
    WEALTH_2ND_LORD_STRONG("Your 2nd house lord is well-placed, indicating steady income and good savings potential.",
        "तपाईंको २औं भावको स्वामी राम्रोसँग राखिएको छ, स्थिर आय र राम्रो बचत क्षमता संकेत गर्दै।"),
    WEALTH_ADVICE("Wealth Advice", "धन सल्लाह"),
    WEALTH_CAUTIONS("Wealth Cautions", "धन सावधानीहरू"),
    WEALTH_CAUTION_RAHU("Rahu's influence suggests caution with speculative investments and get-rich-quick schemes.",
        "राहुको प्रभावले सट्टेबाजी लगानी र छिटो धनी बन्ने योजनाहरूमा सावधानी सुझाव गर्छ।"),
    WEALTH_CAUTION_SATURN("Saturn's influence indicates wealth through steady effort rather than quick gains.",
        "शनिको प्रभावले छिटो लाभभन्दा स्थिर प्रयास मार्फत धन संकेत गर्छ।"),
    WEALTH_DHANA_YOGA("Dhana Yogas in your chart indicate wealth accumulation potential. Financial success through proper effort is indicated.",
        "तपाईंको कुण्डलीमा धन योगहरूले धन संचय क्षमता संकेत गर्दछ। उचित प्रयासबाट आर्थिक सफलता संकेत गरिएको छ।"),
    WEALTH_FROM_INDU("Wealth Capacity from Indu Lagna", "इन्दु लग्नबाट धन क्षमता"),
    WEALTH_JUPITER_STRONG("Strong Jupiter blesses you with wisdom in financial matters and opportunities for wealth growth.",
        "बलियो बृहस्पतिले तपाईंलाई वित्तीय मामिलाहरूमा ज्ञान र धन वृद्धिको लागि अवसरहरूको आशीर्वाद दिन्छ।"),
    WEALTH_OPPORTUNITIES("Wealth Opportunities", "धन अवसरहरू"),
    WEALTH_OUTLOOK("Wealth Outlook", "धन दृष्टिकोण"),
    WEALTH_OVERVIEW("Financial prospects are analyzed through the 2nd house (savings), 11th house (gains), and their lords' positions.",
        "वित्तीय सम्भावनाहरू २औं भाव (बचत), ११औं भाव (लाभ), र तिनीहरूका स्वामीहरूको स्थिति मार्फत विश्लेषण गरिएको छ।"),
    WEALTH_SCORE("Wealth Potential Score", "धन क्षमता स्कोर"),
    WEALTH_SOURCES_TITLE("Wealth Sources Analysis", "धन स्रोतहरू विश्लेषण"),
    WEALTH_SOURCE_TEMPLATE("Primary wealth sources indicated: %s. Secondary sources: %s.",
        "संकेतित प्राथमिक धन स्रोतहरू: %s। माध्यमिक स्रोतहरू: %s।"),
    WEALTH_SUMMARY("Wealth Summary", "धन सारांश"),
    WEALTH_TIMELINE("Wealth Timeline", "धन समयरेखा"),
    WEARING_GUIDELINES("Wearing Guidelines", "लगाउने दिशानिर्देशहरू"),
    WEEKLY_ADVICE_DATE(" Mark %s for important initiatives.", " महत्त्वपूर्ण पहलहरूको लागि %s मार्क गर्नुहोस्।"),
    WEEKLY_ADVICE_JUPITER("embrace opportunities for learning and expansion. Your wisdom and optimism attract positive outcomes.", "सिकाइ र विस्तारका अवसरहरूलाई अँगाल्नुहोस्। तपाईंको ज्ञान र आशावादले सकारात्मक परिणामहरू आकर्षित गर्दछ।"),
    WEEKLY_ADVICE_KETU("focus on spiritual growth and letting go. Detachment brings peace.", "आध्यात्मिक वृद्धि र त्यागमा ध्यान दिनुहोस्। वैराग्यले शान्ति ल्याउँछ।"),
    WEEKLY_ADVICE_MARS("channel your energy into productive activities. Exercise and competition are favored.", "आफ्नो ऊर्जालाई उत्पादक गतिविधिहरूमा लगाउनुहोस्। व्यायाम र प्रतिस्पर्धा अनुकूल छन्।"),
    WEEKLY_ADVICE_MERCURY("prioritize communication, learning, and intellectual activities. Your mind is sharp.", "सञ्चार, सिकाइ र बौद्धिक गतिविधिहरूलाई प्राथमिकता दिनुहोस्। तपाईंको दिमाग तीक्ष्ण छ।"),
    WEEKLY_ADVICE_MOON("honor your emotions and intuition. Nurturing activities bring fulfillment.", "आफ्नो भावना र अन्तर्ज्ञानको सम्मान गर्नुहोस्। पोषण गर्ने गतिविधिहरूले सन्तुष्टि ल्याउँछन्।"),
    WEEKLY_ADVICE_PREFIX("During this %s period, ", "%s अवधिको समयमा, "),
    WEEKLY_ADVICE_RAHU("embrace transformation while staying grounded. Unconventional approaches may succeed.", "जमिनमा रहँदै रूपान्तरणलाई अँगाल्नुहोस्। अपरम्परागत दृष्टिकोणहरू सफल हुन सक्छन्।"),
    WEEKLY_ADVICE_SATURN("embrace discipline and patience. Hard work now builds lasting foundations for the future.", "अनुशासन र धैर्यतालाई अँगाल्नुहोस्। अहिलेको कडा परिश्रमले भविष्यका लागि स्थायी आधार निर्माण गर्दछ।"),
    WEEKLY_ADVICE_SUN("let your light shine. Leadership roles and self-expression bring recognition.", "आफ्नो चमक फैलाउनुहोस्। नेतृत्व भूमिका र आत्म-अभिव्यक्तिले पहिचान ल्याउँछ।"),
    WEEKLY_ADVICE_VENUS("focus on cultivating beauty, harmony, and meaningful relationships. Artistic pursuits are favored.", "सौन्दर्य, सद्भाव र अर्थपूर्ण सम्बन्धहरू विकास गर्नमा ध्यान दिनुहोस्। कलात्मक कार्यहरू अनुकूल छन्।"),
    WEEKLY_CAREER_CHALLENGING("Career matters may require extra effort this week. Stay patient and avoid major changes.", "यस हप्ता करियरका मामिलाहरूमा अतिरिक्त प्रयास आवश्यक हुन सक्छ। धैर्यवान रहनुहोस् र ठूला परिवर्तनहरूबाट बच्नुहोस्।"),
    WEEKLY_CAREER_EXCELLENT("An exceptional week for career advancement. Your %s period supports professional recognition. Key meetings and projects will progress smoothly.", "करियर उन्नतिका लागि एक असाधारण हप्ता। तपाईंको %s अवधिले व्यावसायिक मान्यतालाई समर्थन गर्दछ। मुख्य बैठकहरू र परियोजनाहरू सुचारु रूपमा अगाडि बढ्नेछन्।"),
    WEEKLY_CAREER_STEADY("Steady professional progress this week. Focus on completing pending tasks and building relationships with colleagues.", "यस हप्ता स्थिर व्यावसायिक प्रगति। बाँकी रहेका कार्यहरू पूरा गर्न र सहकर्मीहरूसँग सम्बन्ध निर्माणमा ध्यान दिनुहोस्।"),
    WEEKLY_FAMILY_CHALLENGING("Family dynamics may be challenging this week. Choose understanding over confrontation.", "यस हप्ता पारिवारिक गतिशीलता चुनौतीपूर्ण हुन सक्छ। टकराव भन्दा समझदारी रोज्नुहोस्।"),
    WEEKLY_FAMILY_EXCELLENT("Harmonious family week ahead. Celebrations, gatherings, and quality time strengthen bonds. Support flows both ways.", "सामञ्जस्यपूर्ण पारिवारिक हप्ता। उत्सव, जमघट र गुणस्तरीय समयले बन्धनलाई बलियो बनाउँछ। दुवै तर्फबाट सहयोग मिल्नेछ।"),
    WEEKLY_FAMILY_STEADY("Good week for family matters. Focus on communication and shared activities.", "पारिवारिक मामिलाका लागि राम्रो हप्ता। सञ्चार र साझा गतिविधिहरूमा ध्यान दिनुहोस्।"),
    WEEKLY_FINANCE_CHALLENGING("Financial caution advised this week. Avoid impulsive spending and postpone major investments.", "यस हप्ता वित्तीय सावधानीको सल्लाह दिइन्छ। आवेगपूर्ण खर्चबाट बच्नुहोस् र ठूला लगानीहरू स्थगित गर्नुहोस्।"),
    WEEKLY_FINANCE_EXCELLENT("Prosperous week for finances. Opportunities for gains through investments or new income sources. Review financial plans.", "आर्थिक रूपमा समृद्ध हप्ता। लगानी वा नयाँ आय स्रोतहरू मार्फत लाभको अवसरहरू। वित्तीय योजनाहरूको समीक्षा गर्नुहोस्।"),
    WEEKLY_FINANCE_STEADY("Stable financial week. Good for routine money management and planned purchases.", "स्थिर वित्तीय हप्ता। नियमित पैसा व्यवस्थापन र योजनाबद्ध खरिदका लागि राम्रो।"),
    WEEKLY_HEALTH_CHALLENGING("Health vigilance needed this week. Prioritize rest, nutrition, and stress management.", "यस हप्ता स्वास्थ्य सचेतना आवश्यक छ। आराम, पोषण र तनाव व्यवस्थापनलाई प्राथमिकता दिनुहोस्।"),
    WEEKLY_HEALTH_EXCELLENT("Excellent vitality this week! Great time to start new fitness routines or health practices. Energy levels are high.", "यस हप्ता उत्कृष्ट जीवनशक्ति! नयाँ फिटनेस दिनचर्या वा स्वास्थ्य अभ्यासहरू सुरु गर्नको लागि उत्कृष्ट समय। ऊर्जा स्तर उच्च छ।"),
    WEEKLY_HEALTH_STEADY("Stable health week. Maintain your regular wellness routines and stay consistent with rest.", "स्थिर स्वास्थ्यको हप्ता। आफ्नो नियमित स्वास्थ्य दिनचर्या कायम राख्नुहोस् र आराममा निरन्तरता दिनुहोस्।"),
    WEEKLY_LOVE_CHALLENGING("Relationships need nurturing this week. Practice patience and understanding with your partner.", "यस हप्ता सम्बन्धहरूलाई पोषण आवश्यक छ। आफ्नो पार्टनरसँग धैर्यता र समझदारीको अभ्यास गर्नुहोस्।"),
    WEEKLY_LOVE_EXCELLENT("Romantic energy flows abundantly this week. Single or committed, relationships deepen. Express your feelings openly.", "यस हप्ता रोमान्टिक ऊर्जा प्रचुर मात्रामा प्रवाहित हुन्छ। अविवाहित होस् वा प्रतिबद्ध सम्बन्धमा, सम्बन्धहरू गहिरो हुनेछन्। आफ्ना भावनाहरू खुलेर व्यक्त गर्नुहोस्।"),
    WEEKLY_LOVE_STEADY("Balanced relationship energy. Good for maintaining harmony and working through minor issues together.", "सन्तुलित सम्बन्ध ऊर्जा। सद्भाव कायम राख्न र सानातिना समस्याहरू मिलेर समाधान गर्न राम्रो।"),
    WEEKLY_OVERVIEW_CAUTION("%s may require extra patience and care. ", "%s मा थप धैर्य र सावधानी आवश्यक हुन सक्छ। "),
    WEEKLY_OVERVIEW_CHALLENGING("challenges that, when navigated wisely, lead to growth. ", "चुनौतीहरू जसलाई बुद्धिमानीपूर्वक सामना गर्दा वृद्धि हुन्छ। "),
    WEEKLY_OVERVIEW_EXCELLENT("excellent opportunities for growth and success. ", "वृद्धि र सफलताको लागि उत्कृष्ट अवसरहरू। "),
    WEEKLY_OVERVIEW_FAVORABLE("%s appears most favorable for important activities. ", "%s महत्त्वपूर्ण गतिविधिहरूको लागि सबैभन्दा अनुकूल देखिन्छ। "),
    WEEKLY_OVERVIEW_FOOTER("Trust in your cosmic guidance and make the most of each day's unique energy.", "आफ्नो ब्रह्माण्डीय मार्गदर्शनमा विश्वास गर्नुहोस् र प्रत्येक दिनको अद्वितीय ऊर्जाको सदुपयोग गर्नुहोस्।"),
    WEEKLY_OVERVIEW_HIGH("excellent opportunities for growth and success. ", "वृद्धि र सफलताका लागि उत्कृष्ट अवसरहरू ल्याउँछ। "),
    WEEKLY_OVERVIEW_LOW("challenges that, when navigated wisely, lead to growth. ", "चुनौतीहरू ल्याउँछ जसले, बुद्धिमानीपूर्वक सामना गर्दा वृद्धितर्फ लैजान्छ। "),
    WEEKLY_OVERVIEW_MED("steady progress and balanced energy. ", "स्थिर प्रगति र सन्तुलित ऊर्जा ल्याउँछ। "),
    WEEKLY_OVERVIEW_PREFIX("This week under your %s Mahadasha brings ", "तपाईंको %s महादशा अन्तर्गत यो हप्ताले "),
    WEEKLY_OVERVIEW_STEADY("steady progress and balanced energy. ", "स्थिर प्रगति र सन्तुलित ऊर्जा। "),
    WEEKLY_OVERVIEW_SUFFIX("Trust in your cosmic guidance and make the most of each day's unique energy.", "आफ्नो ब्रह्माण्डीय मार्गदर्शनमा विश्वास गर्नुहोस् र प्रत्येक दिनको अद्वितीय ऊर्जाको अधिकतम सदुपयोग गर्नुहोस्।"),
    WEEKLY_SPIRITUALITY_CHALLENGING("Spiritual connection may feel elusive. Simple practices and patience will help restore balance.", "आध्यात्मिक सम्बन्ध टाढा महसुस हुन सक्छ। सरल अभ्यास र धैर्यताले सन्तुलन पुनर्स्थापित गर्न मद्दत गर्नेछ।"),
    WEEKLY_SPIRITUALITY_EXCELLENT("Profound spiritual week. Meditation, reflection, and inner guidance are heightened. Seek meaningful experiences.", "गहिरो आध्यात्मिक हप्ता। ध्यान, चिन्तन र आन्तरिक मार्गदर्शन बढेको छ। अर्थपूर्ण अनुभवहरू खोज्नुहोस्।"),
    WEEKLY_SPIRITUALITY_STEADY("Steady spiritual energy. Maintain your practices and stay connected to your inner self.", "स्थिर आध्यात्मिक ऊर्जा। आफ्नो अभ्यासहरू कायम राख्नुहोस् र आफ्नो आन्तरिक स्वयंसँग जोडिनुहोस्।"),
    WEEKLY_THEME_NAVIGATION("Mindful Navigation", "सावधानीपूर्वक यात्रा"),
    WEEKLY_THEME_OPPORTUNITY("Week of Opportunities", "अवसरहरूको हप्ता"),
    WEEKLY_THEME_PROGRESS("Steady Progress", "स्थिर प्रगति"),
    WEEKS_SHORT("w", "ह"),
    WEEK_MINDFUL_NAVIGATION("Mindful Navigation", "सचेत नेभिगेसन"),
    WEEK_OPPORTUNITIES("Week of Opportunities", "अवसरहरूको हप्ता"),
    WEEK_STEADY_PROGRESS("Steady Progress", "स्थिर प्रगति"),
    WIFE_PROSPERITY("Wife's Prosperity", "पत्नीको समृद्धि"),
    WISDOM_DEVELOPMENT("Wisdom Development", "ज्ञान विकास"),
    WISDOM_PATH("Wisdom Development", "ज्ञान विकास"),
    WORK_ATMOSPHERE("Work Atmosphere", "कार्य वातावरण"),
    WORK_STYLE_TITLE("Work Style", "कार्य शैली"),
    YANTRA_BENEFIT_247("Provides 24/7 remedy effect when worshipped", "पूजा गर्दा २४/७ उपाय प्रभाव प्रदान गर्दछ"),
    YANTRA_BENEFIT_FIELD("Creates continuous positive energy field", "निरन्तर सकारात्मक ऊर्जा क्षेत्र सिर्जना गर्दछ"),
    YANTRA_BENEFIT_MEDITATION("Enhances meditation and spiritual practice", "ध्यान र आध्यात्मिक अभ्यास बढाउँछ"),
    YANTRA_BENEFIT_PROTECT("Protects home and family from negative influences", "घर र परिवारलाई नकारात्मक प्रभावहरूबाट सुरक्षित राख्छ"),
    YANTRA_CAUTION_ALT("If unable to worship daily, consider other remedies", "यदि दैनिक पूजा गर्न असक्षम हुनुहुन्छ भने, अन्य उपायहरू विचार गर्नुहोस्"),
    YANTRA_CAUTION_CLEAN("Keep the Yantra clean and respected", "यन्त्रलाई सफा र सम्मानित राख्नुहोस्"),
    YANTRA_CAUTION_RITUALS("Must be installed with proper Vedic rituals", "उचित वैदिक अनुष्ठानका साथ स्थापना गर्नुपर्छ"),
    YANTRA_CAUTION_WORSHIP("Requires daily worship commitment", "दैनिक पूजाको प्रतिबद्धता आवश्यक छ"),
    YANTRA_DURATION("Permanent installation with daily worship", "दैनिक पूजाको साथ स्थायी स्थापना"),
    YANTRA_INSTALL_PROC("INSTALLATION PROCEDURE:", "स्थापना प्रक्रिया:"),
    YANTRA_JUPITER_DESC("Represents Jupiter's energy, brings wisdom, wealth, children, and spiritual growth", "बृहस्पतिको ऊर्जा प्रतिनिधित्व गर्दछ, ज्ञान, धन, सन्तान र आध्यात्मिक वृद्धि ल्याउँछ"),
    YANTRA_KETU_DESC("Represents Ketu's energy, brings spiritual liberation, removes past karma, and enhances intuition", "केतुको ऊर्जा प्रतिनिधित्व गर्दछ, आध्यात्मिक मुक्ति ल्याउँछ, विगतको कर्म हटाउँछ र अन्तर्ज्ञान बढाउँछ"),
    YANTRA_MARS_DESC("Represents Mars energy, brings courage, property success, and victory over enemies", "मंगल ऊर्जा प्रतिनिधित्व गर्दछ, साहस, सम्पत्ति सफलता र शत्रुहरूमाथि विजय ल्याउँछ"),
    YANTRA_MERCURY_DESC("Represents Mercury's energy, brings intelligence, business success, and communication skills", "बुधको ऊर्जा प्रतिनिधित्व गर्दछ, बुद्धि, व्यावसायिक सफलता र सञ्चार कौशल ल्याउँछ"),
    YANTRA_METHOD_1("1. Choose a %s %s from authentic source", "१. प्रामाणिक स्रोतबाट %s %s छान्नुहोस्"),
    YANTRA_METHOD_2("2. Select auspicious day: %s during %s Hora", "२. शुभ दिन छान्नुहोस्: %s, %s होरामा"),
    YANTRA_METHOD_3("3. Bathe the Yantra with Panchamrit and Gangajal", "३. यन्त्रलाई पञ्चामृत र गंगाजलले स्नान गराउनुहोस्"),
    YANTRA_METHOD_4("4. Place on clean altar facing East or direction of %s", "४. पूर्व वा %s को दिशामा फर्केर सफा वेदीमा राख्नुहोस्"),
    YANTRA_METHOD_5("5. Light incense and lamp", "५. धूप र बत्ती बाल्नुहोस्"),
    YANTRA_METHOD_6("6. Chant %s mantra 108 times", "६. %s मन्त्र १०८ पटक जप गर्नुहोस्"),
    YANTRA_METHOD_7("7. Offer flowers, fruits, and sandalwood", "७. फूल, फलफूल र चन्दन चढाउनुहोस्"),
    YANTRA_METHOD_8("8. Perform daily worship with incense and lamp", "८. धूप र बत्ती बालेर दैनिक पूजा गर्नुहोस्"),
    YANTRA_MOON_DESC("Represents lunar energy, brings mental peace, emotional stability, and public favor", "चन्द्रमाको ऊर्जा प्रतिनिधित्व गर्दछ, मानसिक शान्ति, भावनात्मक स्थिरता र सार्वजनिक समर्थन ल्याउँछ"),
    YANTRA_RAHU_DESC("Represents Rahu's energy, brings worldly success, removes fear, and protects from black magic", "राहुको ऊर्जा प्रतिनिधित्व गर्दछ, सांसारिक सफलता ल्याउँछ, डर हटाउँछ र कालो जादुबाट बचाउँछ"),
    YANTRA_SATURN_DESC("Represents Saturn's energy, removes obstacles, brings discipline and success through persistence", "शनिको ऊर्जा प्रतिनिधित्व गर्दछ, अवरोधहरू हटाउँछ, अनुशासन र लगनशीलता मार्फत सफलता ल्याउँछ"),
    YANTRA_SUN_DESC("Geometric representation of Sun's energy, brings fame, authority, and government favor", "सूर्यको ऊर्जाको ज्यामितीय प्रतिनिधित्व, ख्याति, अधिकार र सरकारी लाभ ल्याउँछ"),
    YANTRA_TIMING("Install on %s during %s Hora in Shukla Paksha", "शुक्ल पक्षको %s मा %s होरामा स्थापना गर्नुहोस्"),
    YANTRA_VENUS_DESC("Represents Venus energy, brings love, beauty, luxury, and artistic success", "शुक्र ऊर्जा प्रतिनिधित्व गर्दछ, प्रेम, सौन्दर्य, विलासिता र कलात्मक सफलता ल्याउँछ"),
    YEARLY_ADVICE("Yearly Advice", "वार्षिक सल्लाह"),
    YEARLY_RATING("Overall Year Rating", "समग्र वर्ष मूल्याङ्कन"),
    YEARLY_THEME("Yearly Theme", "वार्षिक विषय"),
    YEARS("years", "वर्ष"),
    YEARS_SHORT("y", "व"),
    YES("Yes", "छ"),
    YESNO_CONFIDENCE("Confidence Level", "विश्वास स्तर"),
    YESNO_HIGH("High Confidence", "उच्च विश्वास"),
    YESNO_LOW("Low Confidence", "न्यून विश्वास"),
    YESNO_MEDIUM("Medium Confidence", "मध्यम विश्वास"),
    YESNO_NO("No", "होइन"),
    YESNO_PROBABILITY("Probability", "सम्भावना"),
    YESNO_TITLE("Yes/No Probability", "हो/होइन सम्भावना"),
    YESNO_YES("Yes", "हो"),
    YOGIC_REMEDIES("Yogic Remedies", "योगिक उपचारहरू")
}
