package com.astro.storm.core.common

/**
 * String keys for Dasha Systems
 * Includes: Ashtottari, Sudarshana, Kalachakra, Chara, Yogini, and common Dasha keys
 */
enum class StringKeyDoshaDasha(
    override val en: String,
    override val ne: String,
) : StringKeyInterface {

    // ============================================
    // DASHA SYSTEMS - COMMON
    // ============================================
    DASHA_VIMSOTTARI_NAME("Vimsottari", "विंशोत्तरी"),
    DASHA_VIMSOTTARI_DESC("Most widely used Nakshatra-based planetary period system", "सबैभन्दा बढी प्रयोग हुने नक्षत्र-आधारित ग्रह अवधि प्रणाली"),
    DASHA_VIMSOTTARI_DURATION("120 years", "१२० वर्ष"),
    DASHA_YOGINI("Yogini", "योगिनी"),
    DASHA_YOGINI_DESC("Feminine energy-based system, especially for female charts", "स्त्री ऊर्जा-आधारित प्रणाली, विशेष गरी महिला कुण्डलीको लागि"),
    DASHA_YOGINI_DURATION("36 years", "३६ वर्ष"),
    DASHA_ASHTOTTARI("Ashtottari", "अष्टोत्तरी"),
    DASHA_ASHTOTTARI_DESC("Traditional for night births, uses 8 planets", "रात्री जन्मको लागि परम्परागत, ८ ग्रहहरू प्रयोग गर्दछ"),
    DASHA_ASHTOTTARI_DURATION("108 years", "१०८ वर्ष"),
    DASHA_SUDARSHANA("Sudarshana", "सुदर्शन"),
    DASHA_SUDARSHANA_DESC("Chakra Dasha from Lagna, Moon, and Sun simultaneously", "लग्न, चन्द्र र सूर्यबाट एक साथ चक्र दशा"),
    DASHA_SUDARSHANA_DURATION("Triple view", "त्रिपक्षीय दृश्य"),
    DASHA_CHARA("Chara", "कारा"),
    DASHA_CHARA_DESC("Jaimini sign-based system with Karakamsha analysis", "जैमिनी राशि-आधारित प्रणाली, कारकांश विश्लेषण सहित"),
    DASHA_CHARA_DURATION("Variable", "परिवर्तनशील"),
    DASHA_TITLE_YOGINI("Yogini Dasha", "योगिनी दशा"),
    DASHA_TITLE_CHARA("Chara Dasha", "कारा दशा"),
    DASHA_VIEW_SYSTEM("View %s", "%s हेर्नुहोस्"),
    DASHA_CYCLE_DURATION("Cycle Duration: %s", "चक्र अवधि: %s"),
    DASHA_CALC_LOADING("Calculating %s Dasha timeline...", "%s दशा समयरेखा गणना गर्दै..."),
    DASHA_NO_CHART("No chart selected. Please select a birth chart to view dasha periods.", "कुनै कुण्डली चयन गरिएको छैन। दशा अवधिहरू हेर्न कृपया जन्म कुण्डली चयन गर्नुहोस्।"),
    DASHA_NOT_AVAILABLE("%s calculation not available for this chart.", "%s गणना यो कुण्डलीको लागि उपलब्ध छैन।"),
    DASHA_SHORT_VIM("Vim", "विं"),
    DASHA_SHORT_YOG("Yog", "यो"),
    DASHA_SHORT_ASH("Ash", "अष्टो"),
    DASHA_SHORT_SUD("Sud", "सुद"),
    DASHA_SHORT_CHA("Cha", "चर"),

    // ============================================
    // ASHTOTTARI DASHA
    // ============================================
    ASHTOTTARI_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
    ASHTOTTARI_BALANCE("Balance at Birth", "जन्ममा शेष"),
    ASHTOTTARI_SUBTITLE("108-Year Conditional Dasha System", "१०८ वर्षको सशर्त दशा प्रणाली"),
    ASHTOTTARI_ABOUT("About Ashtottari Dasha", "अष्टोत्तरी दशाको बारेमा"),
    ASHTOTTARI_ABOUT_DESC("Ashtottari Dasha is a conditional planetary period system spanning 108 years. It uses 8 planets (excluding Ketu). The system is particularly effective for daytime births with Moon in Krishna Paksha or nighttime births with Moon in Shukla Paksha.", "अष्टोत्तरी दशा १०८ वर्षको सशर्त ग्रह अवधि प्रणाली हो। यसमा ८ ग्रह प्रयोग गरिन्छ (केतु बाहेक)। यो प्रणाली कृष्ण पक्षमा चन्द्रमासहित दिनको जन्म वा शुक्ल पक्षमा चन्द्रमासहित रातको जन्मको लागि प्रभावकारी छ।"),
    ASHTOTTARI_APPLICABILITY("Applicability Check", "लागू हुने जाँच"),
    ASHTOTTARI_IDEAL_CONDITION("Ideal Condition: Day birth with Krishna Paksha Moon or Night birth with Shukla Paksha Moon", "आदर्श अवस्था: कृष्ण पक्षको चन्द्रमासहित दिनको जन्म वा शुक्ल पक्षको चन्द्रमासहित रातको जन्म"),
    ASHTOTTARI_TOTAL_YEARS("Total Cycle: 108 Years", "कुल चक्र: १०८ वर्ष"),
    ASHTOTTARI_PLANETS_USED("8 Planets Used (No Sun, No Ketu)", "८ ग्रह प्रयोग (सूर्य र केतु बिना)"),
    ASHTOTTARI_CURRENT_PERIOD("Current Period", "वर्तमान अवधि"),
    ASHTOTTARI_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
    ASHTOTTARI_SUN_DURATION("Sun: 6 years", "सूर्य: ६ वर्ष"),
    ASHTOTTARI_MOON_DURATION("Moon: 15 years", "चन्द्र: १५ वर्ष"),
    ASHTOTTARI_MARS_DURATION("Mars: 8 years", "मंगल: ८ वर्ष"),
    ASHTOTTARI_MERCURY_DURATION("Mercury: 17 years", "बुध: १७ वर्ष"),
    ASHTOTTARI_SATURN_DURATION("Saturn: 10 years", "शनि: १० वर्ष"),
    ASHTOTTARI_JUPITER_DURATION("Jupiter: 19 years", "बृहस्पति: १९ वर्ष"),
    ASHTOTTARI_RAHU_DURATION("Rahu: 12 years", "राहु: १२ वर्ष"),
    ASHTOTTARI_VENUS_DURATION("Venus: 21 years", "शुक्र: २१ वर्ष"),
    ASHTOTTARI_CURRENT_TITLE("Current Ashtottari Period", "वर्तमान अष्टोत्तरी अवधि"),
    ASHTOTTARI_BIRTH_NAKSHATRA_HEADER("BIRTH NAKSHATRA", "जन्म नक्षत्र"),
    ASHTOTTARI_LORD_HEADER("LORD", "स्वामी"),
    ASHTOTTARI_MAHADASHA_LABEL("Mahadasha", "महादशा"),
    ASHTOTTARI_ANTARDASHA_LABEL("Antardasha", "अन्तर्दशा"),
    ASHTOTTARI_PERIOD_INSIGHTS("Period Insights", "अवधि अन्तर्दृष्टि"),
    ASHTOTTARI_ABOUT_TITLE("About Ashtottari Dasha", "अष्टोत्तरी दशा बारे"),
    ASHTOTTARI_ABOUT_DESC_FULL("The Ashtottari Dasha system is a 108-year planetary period cycle, traditionally used for charts where the Moon is in Krishna Paksha (waning phase) between Shukla Chaturthi to Krishna Tritiya.", "अष्टोत्तरी दशा प्रणाली १०८-वर्षे ग्रह अवधि चक्र हो, जुन परम्परागत रूपमा शुक्ल चतुर्थीदेखि कृष्ण तृतीयासम्म चन्द्रमा कृष्ण पक्षमा (घट्दो चरण) हुने कुण्डलीहरूको लागि प्रयोग गरिन्छ।"),
    ASHTOTTARI_PERIOD_LIST_HEADER("Planet Periods (108 Years Total)", "ग्रह अवधिहरू (कुल १०८ वर्ष)"),
    ASHTOTTARI_TIMELINE_TITLE("Ashtottari Timeline", "अष्टोत्तरी समयरेखा"),
    ASHTOTTARI_TIMELINE_DESC("108-Year Planetary Cycle", "१०८-वर्षे ग्रह चक्र"),
    ASHTOTTARI_ANTARDASHAS_TITLE("Antardashas", "अन्तर्दशाहरू"),
    ASHTOTTARI_SUB_PERIODS_FMT("%d sub-periods", "%d उप-अवधिहरू"),
    ASHTOTTARI_UNABLE_CALC("Unable to calculate current period", "वर्तमान अवधि गणना गर्न असमर्थ"),

    // Chara Dasha
    CHARA_DASHA_TYPE("Type", "प्रकार"),

    // ============================================
    // SUDARSHANA CHAKRA DASHA
    // ============================================
    SUDARSHANA_TITLE("Sudarshana Chakra Dasha", "सुदर्शन चक्र दशा"),
    SUDARSHANA_SUBTITLE("Triple-Reference Timing System", "त्रि-सन्दर्भ समय प्रणाली"),
    SUDARSHANA_ABOUT("About Sudarshana Chakra", "सुदर्शन चक्रको बारेमा"),
    SUDARSHANA_ABOUT_TITLE("About Sudarshana Chakra", "सुदर्शन चक्र दशा बारे"),
    SUDARSHANA_ABOUT_DESC("Sudarshana Chakra Dasha simultaneously considers the Lagna, Chandra, and Surya charts. Each year progresses through signs from these three reference points, giving a holistic view of life events.", "सुदर्शन चक्र दशाले लग्न, चन्द्र र सूर्य कुण्डली एकैसाथ विचार गर्दछ। प्रत्येक वर्ष यी तीन सन्दर्भ बिन्दुहरूबाट राशिहरू मार्फत अगाडि बढ्छ।"),
    SUDARSHANA_LAGNA_CHAKRA("Lagna Chakra", "लग्न चक्र"),
    SUDARSHANA_CHANDRA_CHAKRA("Chandra Chakra", "चन्द्र चक्र"),
    SUDARSHANA_SURYA_CHAKRA("Surya Chakra", "सूर्य चक्र"),
    SUDARSHANA_AGE("Age", "उमेर"),
    SUDARSHANA_COMBINED_ANALYSIS("Combined Period Analysis", "संयुक्त अवधि विश्लेषण"),
    SUDARSHANA_CONVERGENCE("Convergence Analysis", "अभिसरण विश्लेषण"),
    SUDARSHANA_TRIPLE_VIEW("Triple View", "त्रिगुण दृश्य"),
    SUDARSHANA_YEAR_ANALYSIS("Year Analysis", "वार्षिक विश्लेषण"),
    SUDARSHANA_LAGNA_INFLUENCE("Lagna Influence", "लग्न प्रभाव"),
    SUDARSHANA_CHANDRA_INFLUENCE("Chandra Influence", "चन्द्र प्रभाव"),
    SUDARSHANA_SURYA_INFLUENCE("Surya Influence", "सूर्य प्रभाव"),
    SUDARSHANA_CURRENT_SIGNS("Current Signs", "वर्तमान राशिहरू"),
    SUDARSHANA_HOUSE_SIGNIFICATIONS("House Significations", "भाव अर्थहरू"),
    SUDARSHANA_PLANETS_IN_SIGN("Planets in Sign", "राशिमा ग्रहहरू"),
    SUDARSHANA_ASPECTS_RECEIVED("Aspects Received", "प्राप्त दृष्टिहरू"),
    SUDARSHANA_STRONG_CONVERGENCE("Strong Convergence", "बलियो अभिसरण"),
    SUDARSHANA_WEAK_CONVERGENCE("Weak Convergence", "कमजोर अभिसरण"),
    SUDARSHANA_YEAR_HEADER("Sudarshana Chakra - %d", "सुदर्शन चक्र - %d"),
    SUDARSHANA_TRIPLE_DESC("Triple-Reference Annual Analysis", "त्रि-सन्दर्भ वार्षिक विश्लेषण"),
    SUDARSHANA_YEAR_STRENGTH("OVERALL YEAR STRENGTH", "समग्र वर्ष बल"),
    SUDARSHANA_YEAR_THEMES("Year Themes", "वर्षका विषयहरू"),
    SUDARSHANA_BIRTH_REF_TITLE("Birth Reference Points", "जन्म सन्दर्भ बिन्दुहरू"),
    SUDARSHANA_BIRTH_REF_DESC("Starting positions for chakra progression", "चक्र प्रगतिका लागि सुरुवाती स्थिति"),
    SUDARSHANA_PERSPECTIVES_TITLE("Three Perspectives", "तीन दृष्टिकोण"),
    SUDARSHANA_LAGNA_CHAKRA_DESC("Physical body, appearance, overall life direction", "भौतिक शरीर, रूप, समग्र जीवन दिशा"),
    SUDARSHANA_MOON_CHAKRA_DESC("Mind, emotions, mother, public image", "मन, भावना, आमा, सार्वजनिक छवि"),
    SUDARSHANA_SUN_CHAKRA_DESC("Soul, authority, father, career recognition", "आत्मा, अधिकार, बुबा, करियर मान्यता"),
    SUDARSHANA_COMBINED_NOTE("The combined analysis of all three chakras gives the most accurate prediction of annual themes and events.", "सबै तीन चक्रहरूको संयुक्त विश्लेषणले वार्षिक विषय र घटनाहरूको सबैभन्दा सटीक भविष्यवाणी दिन्छ।"),
    SUDARSHANA_YEARS_COUNT_FMT("%d years", "%d वर्ष"),
    SUDARSHANA_AGE_FMT("Age %d", "उमेर %d"),
    SUDARSHANA_UNABLE_CALC("Current year analysis not available", "वर्तमान वर्षको विश्लेषण उपलब्ध छैन"),

    // Sudarshana House Descriptions
    SUDARSHANA_HOUSE_1_DESC("Year of self-focus, health matters, and personal initiatives", "आत्म-केन्द्रित, स्वास्थ्य मामिला, र व्यक्तिगत पहलहरूको वर्ष"),
    SUDARSHANA_HOUSE_2_DESC("Year of financial matters, family affairs, and resource building", "आर्थिक मामिला, पारिवारिक मामिला, र स्रोत निर्माणको वर्ष"),
    SUDARSHANA_HOUSE_3_DESC("Year of courage, communication, and sibling matters", "साहस, संचार, र भाईबहिनी मामिलाहरूको वर्ष"),
    SUDARSHANA_HOUSE_4_DESC("Year of home, mother, property, and emotional well-being", "घर, आमा, सम्पत्ति, र भावनात्मक कल्याणको वर्ष"),
    SUDARSHANA_HOUSE_5_DESC("Year of children, romance, creativity, and spiritual practices", "सन्तान, रोमान्स, रचनात्मकता, र आध्यात्मिक अभ्यासहरूको वर्ष"),
    SUDARSHANA_HOUSE_6_DESC("Year of health focus, overcoming obstacles, and service", "स्वास्थ्यमा ध्यान, बाधाहरू पार गर्ने, र सेवाको वर्ष"),
    SUDARSHANA_HOUSE_7_DESC("Year of relationships, partnerships, and public dealings", "सम्बन्ध, साझेदारी, र सार्वजनिक व्यवहारहरूको वर्ष"),
    SUDARSHANA_HOUSE_8_DESC("Year of transformation, research, and handling sudden events", "रूपान्तरण, अनुसन्धान, र अचानक घटनाहरू संहाल्ने वर्ष"),
    SUDARSHANA_HOUSE_9_DESC("Year of fortune, spiritual growth, and father-related matters", "भाग्य, आध्यात्मिक वृद्धि, र पितासम्बन्धी मामिलाहरूको वर्ष"),
    SUDARSHANA_HOUSE_10_DESC("Year of career growth, recognition, and professional achievements", "करियर वृद्धि, मान्यता, र व्यावसायिक उपलब्धिहरूको वर्ष"),
    SUDARSHANA_HOUSE_11_DESC("Year of gains, fulfillment of desires, and social expansion", "लाभ, इच्छाहरूको पूर्ति, र सामाजिक विस्तारको वर्ष"),
    SUDARSHANA_HOUSE_12_DESC("Year of spiritual growth, foreign connections, and completion of cycles", "आध्यात्मिक वृद्धि, विदेशी सम्बन्ध, र चक्रहरूको समापनको वर्ष"),

    // Sudarshana Effects and Assessments
    SUDARSHANA_EFFECT_ACTIVATED("%s activated - %s element emphasized", "%s सक्रिय - %s तत्वलाई जोड"),
    SUDARSHANA_EFFECT_MOVABLE("Movable sign - new initiatives and changes favored", "चर राशि - नयाँ पहल र परिवर्तनहरू अनुकूल"),
    SUDARSHANA_EFFECT_FIXED("Fixed sign - stability and consolidation emphasized", "स्थिर राशि - स्थिरता र समेकनलाई जोड"),
    SUDARSHANA_EFFECT_DUAL("Dual sign - adaptability and flexibility needed", "द्विस्वभाव राशि - अनुकूलनशीलता र लचिलोपन आवश्यक"),
    SUDARSHANA_EFFECT_LORD_POS("Lord %s in %d from active sign", "स्वामी %s सक्रिय राशिबाट %d मा"),
    SUDARSHANA_EFFECT_EXALTED("Sign lord is exalted - strong positive results", "राशि स्वामी उच्च - बलियो सकारात्मक परिणाम"),
    SUDARSHANA_EFFECT_DEBILITATED("Sign lord is debilitated - extra efforts needed", "राशि स्वामी नीच - अतिरिक्त प्रयास आवश्यक"),
    SUDARSHANA_EFFECT_NORMAL("Sign lord is in normal dignity", "राशि स्वामी सामान्य अवस्थामा"),
    SUDARSHANA_INFLUENCE_PRESENT("%s present - direct influence on year's themes", "%s उपस्थित - वर्षका विषयहरूमा प्रत्यक्ष प्रभाव"),
    SUDARSHANA_INFLUENCE_ASPECT("%s aspects from %s", "%s ले %s बाट दृष्टि दिन्छ"),
    SUDARSHANA_FACTOR_DIGNITY("Sign lord %s dignity: %s", "राशि स्वामी %s अवस्था: %s"),
    SUDARSHANA_FACTOR_PLANETS("%d planets in active sign", "%d ग्रहहरू सक्रिय राशिमा"),
    SUDARSHANA_FACTOR_ASPECTS("%d planets aspecting", "%d ग्रहहरूको दृष्टि"),
    SUDARSHANA_ASSESSMENT_HIGHLY_FAVORABLE("Highly favorable year with aligned energies from all three references", "तीनै सन्दर्भहरूबाट समान ऊर्जासहित अत्यन्त अनुकूल वर्ष"),
    SUDARSHANA_ASSESSMENT_POSITIVE("Generally positive year with good support from chart references", "कुण्डली सन्दर्भहरूबाट राम्रो समर्थनसहित सामान्यतया सकारात्मक वर्ष"),
    SUDARSHANA_ASSESSMENT_MIXED("Mixed year requiring balanced approach to different life areas", "विभिन्न जीवन क्षेत्रहरूमा सन्तुलित दृष्टिकोण आवश्यक पर्ने मिश्रित वर्ष"),
    SUDARSHANA_ASSESSMENT_CHALLENGING("Challenging year requiring extra effort and remedial measures", "अतिरिक्त प्रयास र उपचारात्मक उपायहरू आवश्यक पर्ने चुनौतीपूर्ण वर्ष"),

    // Sudarshana Recommendations
    SUDARSHANA_REC_FAVORABLE("Favorable year - take initiative in %s", "अनुकूल वर्ष - %s मा पहल गर्नुहोस्"),
    SUDARSHANA_REC_EXPAND("Expand activities related to %s", "%s सम्बन्धी गतिविधिहरू विस्तार गर्नुहोस्"),
    SUDARSHANA_REC_BALANCED("Balanced approach needed - focus on %s", "सन्तुलित दृष्टिकोण आवश्यक - %s मा ध्यान दिनुहोस्"),
    SUDARSHANA_REC_PATIENCE("Be patient with %s", "%s सँग धैर्य राख्नुहोस्"),
    SUDARSHANA_REC_CHALLENGING("Challenging year - strengthen remedies for weak areas", "चुनौतीपूर्ण वर्ष - कमजोर क्षेत्रहरूको लागि उपायहरू बलियो बनाउनुहोस्"),
    SUDARSHANA_REC_SPIRITUAL("Focus on spiritual practices and patience", "आध्यात्मिक अभ्यास र धैर्यमा ध्यान दिनुहोस्"),
    SUDARSHANA_REC_REVIEW("Review all three references monthly for detailed guidance", "विस्तृत मार्गदर्शनको लागि मासिक रूपमा तीनै सन्दर्भहरू समीक्षा गर्नुहोस्"),

    // Sudarshana Themes
    SUDARSHANA_THEME_MULTIPLE("Multiple references point to %s house themes", "धेरै सन्दर्भहरूले %s भाव विषयहरूलाई औंल्याउँछन्"),
    SUDARSHANA_THEME_ACTIVATED("%s activated from multiple references", "%s धेरै सन्दर्भहरूबाट सक्रिय"),
    SUDARSHANA_THEME_VARIATION("Significant variation in strength across references - uneven year expected", "सन्दर्भहरूमा शक्तिको महत्त्वपूर्ण भिन्नता - असमान वर्षको अपेक्षा"),
    SUDARSHANA_FOCUS_GENERAL("General matters", "सामान्य मामिलाहरू"),
    SUDARSHANA_FOCUS_FROM("%s from %s reference", "%s सन्दर्भबाट %s"),
    SUDARSHANA_CONTRIB_LAGNA("Physical matters, personality, and health - %s", "भौतिक मामिला, व्यक्तित्व, र स्वास्थ्य - %s"),
    SUDARSHANA_CONTRIB_CHANDRA("Mind, emotions, and public life - %s", "मन, भावना, र सार्वजनिक जीवन - %s"),
    SUDARSHANA_CONTRIB_SURYA("Soul, authority, and career - %s", "आत्मा, अधिकार, र करियर - %s"),
    SUDARSHANA_YEAR_SUMMARY("Age %d: %s house activated - %s", "उमेर %d: %s भाव सक्रिय - %s"),
    SUDARSHANA_TREND_FAVORABLE("Favorable period in annual cycle", "वार्षिक चक्रमा अनुकूल अवधि"),
    SUDARSHANA_TREND_CHALLENGING("Challenging period requiring extra attention", "अतिरिक्त ध्यान आवश्यक पर्ने चुनौतीपूर्ण अवधि"),
    SUDARSHANA_TREND_NEUTRAL("Neutral period with mixed opportunities", "मिश्रित अवसरहरूसहित तटस्थ अवधि"),
    SUDARSHANA_DIG_EXALTED("Exalted", "उच्च"),
    SUDARSHANA_DIG_OWN("Own Sign", "स्वराशि"),
    SUDARSHANA_DIG_DEBILITATED("Debilitated", "नीच"),
    SUDARSHANA_DIG_NORMAL("Normal", "सामान्य"),

    // Sudarshana House Themes (Top 2 for each house)
    SUDARSHANA_THEME_H1_1("Self", "स्वयं"),
    SUDARSHANA_THEME_H1_2("Body", "शरीर"),
    SUDARSHANA_THEME_H2_1("Wealth", "धन"),
    SUDARSHANA_THEME_H2_2("Family", "परिवार"),
    SUDARSHANA_THEME_H3_1("Siblings", "भाईबहिनी"),
    SUDARSHANA_THEME_H3_2("Courage", "साहस"),
    SUDARSHANA_THEME_H4_1("Mother", "आमा"),
    SUDARSHANA_THEME_H4_2("Home", "घर"),
    SUDARSHANA_THEME_H5_1("Children", "सन्तान"),
    SUDARSHANA_THEME_H5_2("Romance", "प्रेम"),
    SUDARSHANA_THEME_H6_1("Health", "स्वास्थ्य"),
    SUDARSHANA_THEME_H6_2("Enemies", "शत्रु"),
    SUDARSHANA_THEME_H7_1("Marriage", "विवाह"),
    SUDARSHANA_THEME_H7_2("Partnership", "साझेदारी"),
    SUDARSHANA_THEME_H8_1("Transformation", "रूपान्तरण"),
    SUDARSHANA_THEME_H8_2("Longevity", "आयु"),
    SUDARSHANA_THEME_H9_1("Fortune", "भाग्य"),
    SUDARSHANA_THEME_H9_2("Father", "पिता"),
    SUDARSHANA_THEME_H10_1("Career", "करियर"),
    SUDARSHANA_THEME_H10_2("Status", "प्रतिष्ठा"),
    SUDARSHANA_THEME_H11_1("Gains", "लाभ"),
    SUDARSHANA_THEME_H11_2("Income", "आम्दानी"),
    SUDARSHANA_THEME_H12_1("Losses", "हानि"),
    SUDARSHANA_THEME_H12_2("Expenses", "खर्च"),

    // ============================================
    // KALACHAKRA DASHA SYSTEM
    // ============================================
    KALACHAKRA_DASHA_TITLE("Kalachakra Dasha", "कालचक्र दशा"),
    KALACHAKRA_DASHA_SUBTITLE("Body-Soul Timing System", "देह-आत्मा समय प्रणाली"),
    KALACHAKRA_DASHA_ABOUT("About Kalachakra Dasha", "कालचक्र दशाको बारेमा"),
    KALACHAKRA_DASHA_ABOUT_DESC("Kalachakra Dasha is a highly respected Nakshatra-based timing system from BPHS, particularly useful for health predictions and spiritual transformation. It operates on the principle that body (Deha) and soul (Jeeva) follow different but related cycles. Savya (clockwise) and Apsavya (anti-clockwise) groups determine life's flow direction.", "कालचक्र दशा BPHS बाट अत्यन्त सम्मानित नक्षत्र-आधारित समय प्रणाली हो, विशेष गरी स्वास्थ्य भविष्यवाणी र आध्यात्मिक रूपान्तरणको लागि उपयोगी। यो देह र आत्माले फरक तर सम्बन्धित चक्रहरू पछ्याउँछन् भन्ने सिद्धान्तमा काम गर्छ। सव्य (घडीको दिशामा) र अपसव्य (घडीको विपरीत दिशामा) समूहहरूले जीवनको प्रवाह दिशा निर्धारण गर्दछन्।"),
    KALACHAKRA_CURRENT("Current Period", "वर्तमान अवधि"),
    KALACHAKRA_TIMELINE("Timeline", "समयरेखा"),
    KALACHAKRA_DEHA_JEEVA("Deha-Jeeva", "देह-जीव"),
    KALACHAKRA_DEHA_JEEVA_TITLE("Deha-Jeeva Analysis", "देह-जीव विश्लेषण"),
    KALACHAKRA_DEHA_JEEVA_SUBTITLE("Body and Soul Relationship", "शरीर र आत्माको सम्बन्ध"),
    KALACHAKRA_DEHA("Deha", "देह"),
    KALACHAKRA_JEEVA("Jeeva", "जीव"),
    KALACHAKRA_BODY("Body", "शरीर"),
    KALACHAKRA_SOUL("Soul", "आत्मा"),
    KALACHAKRA_EFFECTS("Current Effects", "वर्तमान प्रभावहरू"),
    KALACHAKRA_NAKSHATRA_GROUP("Nakshatra Group", "नक्षत्र समूह"),
    KALACHAKRA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    KALACHAKRA_PADA("Pada", "पाद"),
    KALACHAKRA_APPLICABILITY("System Applicability", "प्रणाली प्रयोज्यता"),
    KALACHAKRA_HEALTH_INDICATOR("Health Outlook", "स्वास्थ्य दृष्टिकोण"),
    KALACHAKRA_PARAMA_AYUSH("Parama Ayush Sign - Special longevity indicator", "परम आयुष राशि - विशेष दीर्घायु सूचक"),
    KALACHAKRA_INTERPRETATION("Interpretation & Guidance", "व्याख्या र मार्गदर्शन"),
    KALACHAKRA_GUIDANCE("Guidance", "मार्गदर्शन"),
    KALACHAKRA_DEHA_ANALYSIS("Deha (Body) Analysis", "देह (शरीर) विश्लेषण"),
    KALACHAKRA_JEEVA_ANALYSIS("Jeeva (Soul) Analysis", "जीव (आत्मा) विश्लेषण"),
    KALACHAKRA_DEHA_LORD("Deha Lord", "देह स्वामी"),
    KALACHAKRA_JEEVA_LORD("Jeeva Lord", "जीव स्वामी"),
    KALACHAKRA_STRENGTH("Strength", "बल"),
    KALACHAKRA_RELATIONSHIP("Deha-Jeeva Relationship", "देह-जीव सम्बन्ध"),
    KALACHAKRA_SAVYA("Savya (Direct)", "सव्य (सीधो)"),
    KALACHAKRA_APSAVYA("Apsavya (Retrograde)", "अपसव्य (उल्टो)"),
    KALACHAKRA_RELATIONSHIP_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
    KALACHAKRA_RELATIONSHIP_SUPPORTIVE("Supportive", "सहयोगी"),
    KALACHAKRA_RELATIONSHIP_NEUTRAL("Neutral", "तटस्थ"),
    KALACHAKRA_RELATIONSHIP_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KALACHAKRA_RELATIONSHIP_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),

    // Kalachakra Groups
    KALACHAKRA_GROUP_SAVYA("Savya (Direct)", "सव्य (सीधो)"),
    KALACHAKRA_GROUP_APSAVYA("Apsavya (Retrograde)", "अपसव्य (उल्टो)"),
    KALACHAKRA_DESC_SAVYA("Clockwise progression through signs - generally smoother life flow", "राशिहरूको घडीको दिशामा प्रगति - सामान्यतया सहज जीवन प्रवाह"),
    KALACHAKRA_DESC_APSAVYA("Anti-clockwise progression - more karmic intensity and transformation", "राशिहरूको घडीको विपरीत दिशामा प्रगति - अधिक कार्मिक तीव्रता र परिवर्तन"),

    // Kalachakra Health
    KALACHAKRA_HEALTH_EXCELLENT("Excellent", "उत्कृष्ट"),
    KALACHAKRA_HEALTH_GOOD("Good", "राम्रो"),
    KALACHAKRA_HEALTH_MODERATE("Moderate", "मध्यम"),
    KALACHAKRA_HEALTH_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KALACHAKRA_HEALTH_CRITICAL("Critical", "गम्भीर"),
    KALACHAKRA_HEALTH_DESC_EXCELLENT("Very favorable for health and vitality", "स्वास्थ्य र जोसका लागि धेरै अनुकूल"),
    KALACHAKRA_HEALTH_DESC_GOOD("Generally supportive of health", "सामान्यतया स्वास्थ्यको लागि सहयोगी"),
    KALACHAKRA_HEALTH_DESC_MODERATE("Mixed health indications", "मिश्रित स्वास्थ्य संकेतहरू"),
    KALACHAKRA_HEALTH_DESC_CHALLENGING("Need to take care of health", "स्वास्थ्यको ख्याल राख्नु आवश्यक"),
    KALACHAKRA_HEALTH_DESC_CRITICAL("Extra caution needed - follow remedies", "अतिरिक्त सावधानी आवश्यक - उपायहरू अपनाउनुहोस्"),

    // Kalachakra Relationships
    KALACHAKRA_REL_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
    KALACHAKRA_REL_SUPPORTIVE("Supportive", "सहयोगी"),
    KALACHAKRA_REL_NEUTRAL("Neutral", "तटस्थ"),
    KALACHAKRA_REL_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KALACHAKRA_REL_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
    KALACHAKRA_REL_DESC_HARMONIOUS("Body and soul are aligned - good health and spiritual progress", "शरिर र आत्मा एकरुप छन् - राम्रो स्वास्थ्य र आध्यात्मिक प्रगति"),
    KALACHAKRA_REL_DESC_SUPPORTIVE("Jeeva supports Deha - spiritual practices benefit health", "जीवले देहलाई सहयोग गर्छ - आध्यात्मिक अभ्यासले स्वास्थ्यलाई फाइदा पुर्‍याउँछ"),
    KALACHAKRA_REL_DESC_NEUTRAL("Independent functioning of body and spirit", "शरिर र आत्माको स्वतन्त्र कार्य"),
    KALACHAKRA_REL_DESC_CHALLENGING("Some friction between material and spiritual needs", "भौतिक र आध्यात्मिक आवश्यकताहरू बीच केही घर्षण"),
    KALACHAKRA_REL_DESC_TRANSFORMATIVE("Deep karmic work needed to align body and soul", "शरिर र आत्मा मिलाउन गहिरो कार्मिक कार्य आवश्यक"),

    // Kalachakra Overview and Guidance
    KALACHAKRA_OVERVIEW_TEXT("Kalachakra Dasha is a sophisticated timing system particularly useful for health predictions and spiritual transformation timing. It operates on the principle that body (Deha) and soul (Jeeva) follow different but related cycles.", "कालचक्र दशा स्वास्थ्य भविष्यवाणी र आध्यात्मिक रूपान्तरण समयको लागि विशेष गरी उपयोगी एक परिष्कृत समय प्रणाली हो। यो शरीर (देह) र आत्मा (जीव) ले फरक तर सम्बन्धित चक्रहरू पछ्याउँछन् भन्ने सिद्धान्तमा काम गर्दछ।"),
    KALACHAKRA_GUIDANCE_1("Monitor transits over Deha Rashi for physical health events", "शारीरिक स्वास्थ्य घटनाहरूको लागि देह राशि माथिको गोचर निगरानी गर्नुहोस्"),
    KALACHAKRA_GUIDANCE_2("Observe transits over Jeeva Rashi for spiritual opportunities", "आध्यात्मिक अवसरहरूको लागि जीव राशि माथिको गोचर अवलोकन गर्नुहोस्"),
    KALACHAKRA_GUIDANCE_3("When Deha and Jeeva sign lords are strong in transit, both health and spiritual progress are favored", "जब देह र जीव राशिका स्वामीहरू गोचरमा बलियो हुन्छन्, स्वास्थ्य र आध्यात्मिक प्रगति दुबै अनुकूल हुन्छन्"),
    KALACHAKRA_GUIDANCE_4("Use Kalachakra Dasha alongside Vimsottari for comprehensive analysis", "विस्तृत विश्लेषणको लागि विंशोत्तरी सँगै कालचक्र दशा प्रयोग गर्नुहोस्"),
    KALACHAKRA_GUIDANCE_5("Pay special attention when malefics transit your Deha Rashi", "जब पापी ग्रहहरूले तपाईंको देह राशिमा गोचर गर्छन् विशेष ध्यान दिनुहोस्"),

    // Kalachakra Sign Effects
    KALACHAKRA_EFFECT_ARIES("Period of initiative, new beginnings, and physical vitality. Mars energy brings action and courage.", "पहल, नयाँ शुरुआत र शारीरिक जोसको अवधि। मंगलको ऊर्जाले कर्म र साहस ल्याउँछ।"),
    KALACHAKRA_EFFECT_TAURUS("Focus on stability, wealth accumulation, and sensory pleasures. Venus brings comfort and beauty.", "स्थिरता, धन सञ्चय र इन्द्रिय सुखमा ध्यान। शुक्रले आराम र सौन्दर्य ल्याउँछ।"),
    KALACHAKRA_EFFECT_GEMINI("Communication, learning, and intellectual pursuits are highlighted. Mercury brings versatility.", "सञ्चार, सिकाइ र बौद्धिक प्रयासहरूलाई जोड दिइन्छ। बुधले बहुमुखी प्रतिभा ल्याउँछ।"),
    KALACHAKRA_EFFECT_CANCER("Emotional growth, home, and family matters take center stage. Moon brings nurturing energy.", "भावनात्मक वृद्धि, घर र पारिवारिक मामिलाहरू मुख्य हुन्छन्। चन्द्रमाले पोषण गर्ने ऊर्जा ल्याउँछ।"),
    KALACHAKRA_EFFECT_LEO("Recognition, authority, and creative self-expression. Sun brings confidence and vitality.", "मान्यता, अधिकार र रचनात्मक आत्म-अभिव्यक्ति। सूर्यले आत्मविश्वास र जोस ल्याउँछ।"),
    KALACHAKRA_EFFECT_VIRGO("Analysis, health consciousness, and service. Mercury brings discrimination and healing potential.", "विश्लेषण, स्वास्थ्य चेतना र सेवा। बुधले विवेक र निको पार्ने क्षमता ल्याउँछ।"),
    KALACHAKRA_EFFECT_LIBRA("Partnerships, balance, and aesthetic pursuits. Venus brings harmony and relationships.", "साझेदारी, सन्तुलन र सौन्दर्य प्रयासहरू। शुक्रले सद्भाव र सम्बन्धहरू ल्याउँछ।"),
    KALACHAKRA_EFFECT_SCORPIO("Deep transformation, hidden matters, and research. Mars/Ketu bring intensity and rebirth.", "गहिरो रूपान्तरण, गुप्त मामिला र अनुसन्धान। मंगल/केतुले तीव्रता र पुनर्जन्म ल्याउँछन्।"),
    KALACHAKRA_EFFECT_SAGITTARIUS("Higher learning, philosophy, and expansion. Jupiter brings wisdom and fortune.", "उच्च सिकाइ, दर्शन र विस्तार। बृहस्पतिले ज्ञान र भाग्य ल्याउँछ।"),
    KALACHAKRA_EFFECT_CAPRICORN("Career, discipline, and long-term achievements. Saturn brings structure and maturity.", "क्यारियर, अनुशासन र दीर्घकालीन उपलब्धिहरू। शनिले संरचना र परिपक्वता ल्याउँछ।"),
    KALACHAKRA_EFFECT_AQUARIUS("Innovation, humanitarian concerns, and group activities. Saturn/Rahu bring progressive change.", "नवप्रवर्तन, मानवीय चासो र समूह गतिविधिहरू। शनि/राहुले प्रगतिशील परिवर्तन ल्याउँछन्।"),
    KALACHAKRA_EFFECT_PISCES("Spirituality, imagination, and transcendence. Jupiter brings divine connection and liberation.", "आध्यात्मिकता, कल्पना र पारलौकिकता। बृहस्पतिले ईश्वरीय सम्बन्ध र मुक्ति ल्याउँछ।"),

    // Kalachakra Brief Effects
    KALACHAKRA_BRIEF_ARIES("Energy, initiative, new starts.", "ऊर्जा, पहल, नयाँ शुरुआत।"),
    KALACHAKRA_BRIEF_TAURUS("Stability, wealth, comfort.", "स्थिरता, धन, आराम।"),
    KALACHAKRA_BRIEF_GEMINI("Communication, learning, versatility.", "सञ्चार, सिकाइ, बहुमुखी प्रतिभा।"),
    KALACHAKRA_BRIEF_CANCER("Emotions, home, nurturing.", "भावनाहरू, घर, पालनपोषण।"),
    KALACHAKRA_BRIEF_LEO("Recognition, creativity, authority.", "मान्यता, रचनात्मकता, अधिकार।"),
    KALACHAKRA_BRIEF_VIRGO("Analysis, health, service.", "विश्लेषण, स्वास्थ्य, सेवा।"),
    KALACHAKRA_BRIEF_LIBRA("Balance, relationships, harmony.", "सन्तुलन, सम्बन्ध, सद्भाव।"),
    KALACHAKRA_BRIEF_SCORPIO("Transformation, depth, intensity.", "रूपान्तरण, गहिराई, तीव्रता।"),
    KALACHAKRA_BRIEF_SAGITTARIUS("Expansion, wisdom, fortune.", "विस्तार, ज्ञान, भाग्य।"),
    KALACHAKRA_BRIEF_CAPRICORN("Career, discipline, achievement.", "क्यारियर, अनुशासन, उपलब्धि।"),
    KALACHAKRA_BRIEF_AQUARIUS("Innovation, humanity, progress.", "नवप्रवर्तन, मानवता, प्रगति।"),
    KALACHAKRA_BRIEF_PISCES("Spirituality, imagination, liberation.", "आध्यात्मिकता, कल्पना, मुक्ति।"),

    // Kalachakra Spiritual Effects
    KALACHAKRA_SPIR_FIRE("Spiritual growth through action and courage. Karma yoga is favored.", "कर्म र साहस मार्फत आध्यात्मिक वृद्धि। कर्म योग अनुकूल छ।"),
    KALACHAKRA_SPIR_EARTH("Spiritual grounding through service. Seva is emphasized.", "सेवा मार्फत आध्यात्मिक स्थिरता। सेवामा जोड दिइन्छ।"),
    KALACHAKRA_SPIR_AIR("Spiritual development through knowledge. Jnana yoga is favored.", "ज्ञान मार्फत आध्यात्मिक विकास। ज्ञान योग अनुकूल छ।"),
    KALACHAKRA_SPIR_WATER("Spiritual awakening through devotion. Bhakti yoga is emphasized.", "भक्ति मार्फत आध्यात्मिक जागरण। भक्ति योगमा जोड दिइन्छ।"),
    KALACHAKRA_SPIR_GEN("Balanced spiritual development.", "सन्तुलित आध्यात्मिक विकास।"),

    // Kalachakra Detailed Spiritual Effects
    KALACHAKRA_SPIRITUAL_FIRE("Spiritual growth through action, courage, and self-assertion. Karma yoga is favored.", "कार्य, साहस र आत्म-दावी मार्फत आध्यात्मिक वृद्धि। कर्म योग अनुकूल छ।"),
    KALACHAKRA_SPIRITUAL_EARTH("Spiritual grounding through practical service and material detachment. Seva is emphasized.", "व्यावहारिक सेवा र भौतिक अनासक्ति मार्फत आध्यात्मिक स्थिरता। सेवामा जोड दिइन्छ।"),
    KALACHAKRA_SPIRITUAL_AIR("Spiritual development through knowledge, study, and intellectual understanding. Jnana yoga is favored.", "ज्ञान, अध्ययन र बौद्धिक समझ मार्फत आध्यात्मिक विकास। ज्ञान योग अनुकूल छ।"),
    KALACHAKRA_SPIRITUAL_WATER("Spiritual awakening through devotion, intuition, and emotional surrender. Bhakti yoga is emphasized.", "भक्ति, अन्तर्ज्ञान र भावनात्मक समर्पण मार्फत आध्यात्मिक जागरण। भक्ति योगमा जोड दिइन्छ।"),
    KALACHAKRA_SPIRITUAL_GENERAL("Balanced spiritual development across all paths.", "सबै मार्गहरूमा सन्तुलित आध्यात्मिक विकास।"),

    // Kalachakra Material Effects
    KALACHAKRA_MAT_H1("focus on self and physical initiatives.", "स्वयं र शारीरिक पहलमा ध्यान।"),
    KALACHAKRA_MAT_H2("focus on wealth and resources.", "धन र स्रोतहरूमा ध्यान।"),
    KALACHAKRA_MAT_H3("focus on courage and communication.", "साहस र संचारमा ध्यान।"),
    KALACHAKRA_MAT_H4("focus on property and home.", "सम्पत्ति र घरमा ध्यान।"),
    KALACHAKRA_MAT_H5("focus on creativity and children.", "रचनात्मकता र सन्तानमा ध्यान।"),
    KALACHAKRA_MAT_H6("focus on service and health.", "सेवा र स्वास्थ्यमा ध्यान।"),
    KALACHAKRA_MAT_H7("focus on partnerships and marriage.", "साझेदारी र विवाहमा ध्यान।"),
    KALACHAKRA_MAT_H8("focus on transformation and research.", "रूपान्तरण र अनुसन्धानमा ध्यान।"),
    KALACHAKRA_MAT_H9("focus on fortune and higher learning.", "भाग्य र उच्च शिक्षामा ध्यान।"),
    KALACHAKRA_MAT_H10("focus on career and status.", "करियर र प्रतिष्ठामा ध्यान।"),
    KALACHAKRA_MAT_H11("focus on gains and networking.", "लाभ र नेटवर्किङमा ध्यान।"),
    KALACHAKRA_MAT_H12("focus on spirituality and foreign matters.", "आध्यात्मिकता र वैदेशिक मामिलामा ध्यान।"),
    KALACHAKRA_MATERIAL_SIGN_FOCUS("Material focus on %s matters.", "%s मामिलाहरूमा भौतिक ध्यान।"),
    KALACHAKRA_MATERIAL_LORD_POS("Sign lord %s in House %d indicates ", "राशि स्वामी %s भाव %d मा हुनुले "),
    KALACHAKRA_MATERIAL_H1("self-focused material gains.", "आत्म-केन्द्रित भौतिक लाभ।"),
    KALACHAKRA_MATERIAL_H2("wealth and resource accumulation.", "धन र स्रोत संकलन।"),
    KALACHAKRA_MATERIAL_H3("gains through courage and communication.", "साहस र संचार मार्फत लाभ।"),
    KALACHAKRA_MATERIAL_H4("property and domestic comfort.", "सम्पत्ति र पारिवारिक सुख।"),
    KALACHAKRA_MATERIAL_H5("creative and speculative gains.", "रचनात्मक र सट्टा लाभ।"),
    KALACHAKRA_MATERIAL_H6("gains through service and overcoming obstacles.", "सेवा र अवरोधहरू पार गरेर लाभ।"),
    KALACHAKRA_MATERIAL_H7("partnership-related material matters.", "साझेदारी सम्बन्धित भौतिक मामिलाहरू।"),
    KALACHAKRA_MATERIAL_H8("transformation of resources, inheritance.", "स्रोतहरूको रूपान्तरण, पैतृक सम्पत्ति।"),
    KALACHAKRA_MATERIAL_H9("fortune through dharma and higher pursuits.", "धर्म र उच्च खोज मार्फत भाग्य।"),
    KALACHAKRA_MATERIAL_H10("career advancement and public recognition.", "करियर उन्नति र सार्वजनिक पहिचान।"),
    KALACHAKRA_MATERIAL_H11("fulfillment of desires and network gains.", "इच्छा पूर्ति र नेटवर्क लाभ।"),
    KALACHAKRA_MATERIAL_H12("spiritual investments and foreign connections.", "आध्यात्मिक लगानी र विदेशी सम्बन्ध।"),
    KALACHAKRA_MATERIAL_GENERAL_PROGRESS("general material progression.", "सामान्य भौतिक प्रगति।"),

    // Kalachakra Caution Areas
    KALACHAKRA_CAUTION_HEALTH("Physical health requires attention", "शारीरिक स्वास्थ्यमा ध्यान दिनु आवश्यक छ"),
    KALACHAKRA_CAUTION_ARIES("Head injuries, fevers, impulsive actions", "टाउकोको चोट, ज्वरो, आवेगपूर्ण कार्यहरू"),
    KALACHAKRA_CAUTION_TAURUS("Throat issues, dietary excess, stubbornness", "घाँटीको समस्या, खानपानमा अधिकता, जिद्दीपन"),
    KALACHAKRA_CAUTION_GEMINI("Nervous tension, respiratory issues, inconsistency", "स्नायु तनाव, श्वासप्रश्वासको समस्या, अस्थिरता"),
    KALACHAKRA_CAUTION_CANCER("Emotional sensitivity, digestive issues, attachment", "भावनात्मक संवेदनशीलता, पाचन समस्या, मोह"),
    KALACHAKRA_CAUTION_LEO("Heart issues, ego conflicts, excessive pride", "मुटुको समस्या, अहंकार विवाद, अत्यधिक गर्व"),
    KALACHAKRA_CAUTION_VIRGO("Digestive problems, anxiety, over-criticism", "पाचन समस्या, चिन्ता, अत्यधिक आलोचना"),
    KALACHAKRA_CAUTION_LIBRA("Kidney issues, indecision, relationship dependency", "मृगौलाको समस्या, अनिर्णय, सम्बन्धमा निर्भरता"),
    KALACHAKRA_CAUTION_SCORPIO("Reproductive issues, intensity, control issues", "प्रजनन समस्या, तीव्रता, नियन्त्रण समस्या"),
    KALACHAKRA_CAUTION_SAGITTARIUS("Liver issues, over-expansion, dogmatism", "कलेजोको समस्या, अत्यधिक विस्तार, कट्टरता"),
    KALACHAKRA_CAUTION_CAPRICORN("Joint problems, depression, workaholism", "जोर्नीको समस्या, निराशा, कामको लत"),
    KALACHAKRA_CAUTION_AQUARIUS("Circulation issues, detachment, rebellion", "रक्तसञ्चार समस्या, वैराग्य, विद्रोह"),
    KALACHAKRA_CAUTION_PISCES("Foot problems, escapism, boundary issues", "खुट्टाको समस्या, पलायनवाद, सीमा समस्या"),

    // Kalachakra Remedies
    KALACHAKRA_REMEDY_MANTRA("Chant %s mantra for strengthening this period", "यो अवधिलाई बलियो बनाउन %s मन्त्र जप गर्नुहोस्"),
    KALACHAKRA_REMEDY_FIRE("Perform Agni-related rituals (Homa, lighting lamp)", "अग्नि सम्बन्धित विधि (होम, दीप बाल्ने) गर्नुहोस्"),
    KALACHAKRA_REMEDY_EARTH("Service to earth (gardening, feeding, grounding practices)", "पृथ्वीको सेवा (बगैंचा, खुवाउने, ग्राउन्डिङ अभ्यास) गर्नुहोस्"),
    KALACHAKRA_REMEDY_AIR("Pranayama and breath-related practices", "प्राणायाम र श्वास सम्बन्धी अभ्यासहरू"),
    KALACHAKRA_REMEDY_WATER("Water offerings, visiting sacred water bodies", "जल अर्पण, पवित्र जलाशयको भ्रमण"),
    KALACHAKRA_REMEDY_DEITY("Honor the sign deity through appropriate worship", "उपयुक्त पूजा मार्फत राशि देवताको सम्मान गर्नुहोस्"),

    // Kalachakra Predictions
    KALACHAKRA_PRED_INTRO_DEHA("Based on Deha lord's %1\$2 status and %2\$2 Deha-Jeeva relationship: ", "देह स्वामीको %1\$2 अवस्था र %2\$2 देह-जीव सम्बन्धको आधारमा: "),
    KALACHAKRA_PRED_INTRO_JEEVA("Jeeva lord's %1\$2 condition indicates ", "जीव स्वामीको %1\$2 अवस्थाले संकेत गर्दछ "),
    KALACHAKRA_HEALTH_PRED_HARMONIOUS("Physical health is well-supported by spiritual practices. Body responds well to holistic healing.", "शारीरिक स्वास्थ्यलाई आध्यात्मिक अभ्यासहरूले राम्रो समर्थन गर्दछ। शरीरले समग्र उपचारलाई राम्रो प्रतिक्रिया दिन्छ।"),
    KALACHAKRA_HEALTH_PRED_SUPPORTIVE("Good baseline health with spiritual practices enhancing physical wellbeing.", "राम्रो आधारभूत स्वास्थ्यको साथ आध्यात्मिक अभ्यासहरूले शारीरिक कल्याण बढाउँछ।"),
    KALACHAKRA_HEALTH_PRED_NEUTRAL("Health matters follow their natural course. Maintain regular routines.", "स्वास्थ्य मामिलाहरूले आफ्नो प्राकृतिक मार्ग पछ्याउँछन्। नियमित दिनचर्या कायम राख्नुहोस्।"),
    KALACHAKRA_HEALTH_PRED_CHALLENGING("May experience tension between physical demands and spiritual aspirations. Balance is key.", "शारीरिक माग र आध्यात्मिक आकांक्षाहरू बीच तनाव अनुभव हुन सक्छ। सन्तुलन कुञ्जी हो।"),
    KALACHAKRA_HEALTH_PRED_TRANSFORMATIVE("Health challenges may serve as catalysts for spiritual growth. Deep healing possible.", "स्वास्थ्य चुनौतीहरूले आध्यात्मिक वृद्धिको लागि उत्प्रेरकको रूपमा काम गर्न सक्छन्। गहिरो उपचार सम्भव छ।"),
    KALACHAKRA_SPIRITUAL_PRED_HARMONIOUS("natural spiritual progress. Meditation and dharmic practices flow easily.", "प्राकृतिक आध्यात्मिक प्रगति। ध्यान र धार्मिक अभ्यासहरू सजिलै प्रवाहित हुन्छन्।"),
    KALACHAKRA_SPIRITUAL_PRED_SUPPORTIVE("spiritual growth through practical application of wisdom.", "ज्ञानको व्यावहारिक प्रयोग मार्फत आध्यात्मिक वृद्धि।"),
    KALACHAKRA_SPIRITUAL_PRED_NEUTRAL("steady spiritual development through consistent practice.", "निरन्तर अभ्यास मार्फत स्थिर आध्यात्मिक विकास।"),
    KALACHAKRA_SPIRITUAL_PRED_CHALLENGING("spiritual growth through overcoming material attachments.", "भौतिक आसक्तिहरू जितेर आध्यात्मिक वृद्धि।"),
    KALACHAKRA_SPIRITUAL_PRED_TRANSFORMATIVE("profound spiritual transformation through life's challenges.", "जीवनका चुनौतीहरू मार्फत गहिरो आध्यात्मिक रूपान्तरण।"),

    // Kalachakra Recommendations
    KALACHAKRA_REC_DEHA_LORD("Strengthen Deha lord (%1\$2) through appropriate mantras and gemstones", "उपयुक्त मन्त्र र रत्नहरू मार्फत देह स्वामी (%1\$2) लाई बलियो बनाउनुहोस्"),
    KALACHAKRA_REC_JEEVA_LORD("Honor Jeeva lord (%1\$2) through spiritual practices", "आध्यात्मिक अभ्यासहरू मार्फत जीव स्वामी (%1\$2) लाई सम्मान गर्नुहोस्"),
    KALACHAKRA_REC_HARMONIOUS_1("Continue current spiritual and health practices - they are aligned", "वर्तमान आध्यात्मिक र स्वास्थ्य अभ्यासहरू जारी राख्नुहोस् - तिनीहरू पङ्क्तिबद्ध छन्"),
    KALACHAKRA_REC_HARMONIOUS_2("Use this favorable period for deepening meditation", "यो अनुकूल अवधिलाई ध्यान गहिरो बनाउन प्रयोग गर्नुहोस्"),
    KALACHAKRA_REC_SUPPORTIVE_1("Integrate physical yoga with spiritual practices", "शारीरिक योगलाई आध्यात्मिक अभ्यासहरूसँग एकीकृत गर्नुहोस्"),
    KALACHAKRA_REC_SUPPORTIVE_2("Serve others as part of spiritual path", "आध्यात्मिक मार्गको भागको रूपमा अरूको सेवा गर्नुहोस्"),
    KALACHAKRA_REC_NEUTRAL_1("Establish regular routines for both physical and spiritual health", "शारीरिक र आध्यात्मिक स्वास्थ्य दुवैको लागि नियमित दिनचर्या स्थापना गर्नुहोस्"),
    KALACHAKRA_REC_NEUTRAL_2("Create balance between material and spiritual pursuits", "भौतिक र आध्यात्मिक प्रयासहरू बीच सन्तुलन सिर्जना गर्नुहोस्"),
    KALACHAKRA_REC_CHALLENGING_1("Practice patience and acceptance with physical limitations", "शारीरिक सीमाहरूसँग धैर्य र स्वीकृति अभ्यास गर्नुहोस्"),
    KALACHAKRA_REC_CHALLENGING_2("Transform challenges into spiritual growth opportunities", "चुनौतीहरूलाई आध्यात्मिक वृद्धिको अवसरमा रूपान्तरण गर्नुहोस्"),
    KALACHAKRA_REC_TRANSFORMATIVE_1("Embrace transformation as part of soul's journey", "रूपान्तरणलाई आत्माको यात्राको भागको रूपमा अँगाल्नुहोस्"),
    KALACHAKRA_REC_TRANSFORMATIVE_2("Seek guidance from spiritual teachers during difficult periods", "कठिन समयमा आध्यात्मिक गुरुहरूबाट मार्गदर्शन लिनुहोस्"),

    // Kalachakra Interpretation
    KALACHAKRA_INTERP_GROUP_ANALYSIS("Your Moon falls in %s group. %s This influences the direction and nature of your life's unfoldment.", "तपाईंको चन्द्रमा %s समूहमा पर्दछ। %s यसले तपाईंको जीवनको विकासको दिशा र प्रकृतिलाई प्रभाव पार्छ।"),
    KALACHAKRA_INTERP_DEHA_JEEVA_SUMMARY("Deha (Body) Rashi: %s, Jeeva (Soul) Rashi: %s. Relationship: %s", "देह (शरीर) राशि: %s, जीव (आत्मा) राशि: %s। सम्बन्ध: %s"),
    KALACHAKRA_INTERP_CURRENT_PHASE("Currently in %s Mahadasha (%d years). Health outlook: %s. %s", "हाल %s महादशामा (%d वर्ष)। स्वास्थ्य दृष्टिकोण: %s। %s"),
    KALACHAKRA_INTERP_NO_CURRENT("Current Mahadasha extends beyond calculated range.", "वर्तमान महादशा गणना गरिएको दायरा भन्दा बाहिर छ।"),
    KALACHAKRA_INTERP_HEALTH_SPIRITUAL("Health & Spiritual Outlook", "स्वास्थ्य र आध्यात्मिक दृष्टिकोण"),
    KALACHAKRA_INTERP_MATERIAL_GUIDANCE("Material & General Guidance", "भौतिक र सामान्य मार्गदर्शन"),
    KALACHAKRA_INTERP_CLOSING("Use this period to align with your %s-ruled energies for maximum growth.", "अधिकतम वृद्धिको लागि तपाईंको %s-शासित ऊर्जाहरूसँग पङ्क्तिबद्ध हुन यो अवधि प्रयोग गर्नुहोस्"),

    // Kalachakra Favorable Areas
    KALACHAKRA_AREA_LEADERSHIP("Leadership", "नेतृत्व"),
    KALACHAKRA_AREA_SPORTS("Sports", "खेलकुद"),
    KALACHAKRA_AREA_ENGINEERING("Engineering", "इन्जिनियरिङ"),
    KALACHAKRA_AREA_MILITARY("Military", "सैनिक"),
    KALACHAKRA_AREA_FINANCE("Finance", "वित्त"),
    KALACHAKRA_AREA_REAL_ESTATE("Real estate", "घरजग्गा"),
    KALACHAKRA_AREA_AGRICULTURE("Agriculture", "कृषि"),
    KALACHAKRA_AREA_CONSTRUCTION("Construction", "निर्माण"),
    KALACHAKRA_AREA_COMMUNICATION("Communication", "सञ्चार"),
    KALACHAKRA_AREA_EDUCATION("Education", "शिक्षा"),
    KALACHAKRA_AREA_TRAVEL("Travel", "यात्रा"),
    KALACHAKRA_AREA_TECHNOLOGY("Technology", "प्रविधि"),
    KALACHAKRA_AREA_HEALING("Healing", "उपचार"),
    KALACHAKRA_AREA_ARTS("Arts", "कला"),
    KALACHAKRA_AREA_PSYCHOLOGY("Psychology", "मनोविज्ञान"),
    KALACHAKRA_AREA_SPIRITUALITY("Spirituality", "अध्यात्म"),

    // ============================================
    // YOGINI DASHA ERRORS
    // ============================================
    YOGINI_ERROR_MOON("Unable to determine Moon's Nakshatra position. Please verify birth data.", "चन्द्रमाको नक्षत्र स्थिति निर्धारण गर्न असमर्थ। कृपया जन्म डाटा प्रमाणित गर्नुहोस्।"),
    YOGINI_ERROR_BIRTH("Invalid birth data provided. Please check date, time, and location.", "अमान्य जन्म डाटा प्रदान गरियो। कृपया मिति, समय र स्थान जाँच गर्नुहोस्।"),
    YOGINI_ERROR_NAKSHATRA("Unable to calculate Yogini Dasha. Nakshatra calculation error.", "योगिनी दशा गणना गर्न असमर्थ। नक्षत्र गणना त्रुटि।"),
    YOGINI_ERROR_GENERIC("Failed to calculate Yogini Dasha. Please try again.", "योगिनी दशा गणना गर्न असफल। कृपया फेरि प्रयास गर्नुहोस्।"),
    YOGINI_SEQUENCE("Yogini Sequence", "योगिनी क्रम"),

    // Planet Strength
    PLANET_STRENGTH_EXALTED("Exalted - Very Strong", "उच्च - धेरै बलियो"),
    PLANET_STRENGTH_OWN_SIGN("Own Sign - Strong", "स्वराशि - बलियो"),
    PLANET_STRENGTH_DEBILITATED("Debilitated - Weak", "नीच - कमजोर"),
    PLANET_STRENGTH_RETROGRADE("Retrograde - Introspective", "बक्री - आत्मनिरीक्षक"),
    PLANET_STRENGTH_MODERATE("Moderate", "मध्यम"),
    PLANET_STRENGTH_UNKNOWN("Unknown", "अज्ञात"),
;
}
