package com.astro.storm.core.common

/**
 * String keys for Screen-specific UI elements
 * Includes: Lal Kitab, Mrityu Bhaga, Upachaya Transit, Arudha Pada, Ashtakavarga, Panchanga,
 * Avastha, Nitya Yoga, Nakshatra, Shadbala, Bhrigu Bindu, and Common UI elements
 */
enum class StringKeyDoshaScreen(
    override val en: String,
    override val ne: String,
) : StringKeyInterface {

    // ============================================
    // LAL KITAB REMEDIES
    // ============================================
    LAL_KITAB_TITLE("Lal Kitab Analysis", "लाल किताब विश्लेषण"),
    LAL_KITAB_SUBTITLE("Traditional Remedial System", "परम्परागत उपचार प्रणाली"),
    LAL_KITAB_ABOUT("About Lal Kitab", "लाल किताबको बारेमा"),
    LAL_KITAB_ABOUT_DESC("Lal Kitab is a distinct astrological system with practical, cost-effective remedies. It differs from classical Vedic astrology in house analysis and remedy approach.", "लाल किताब व्यावहारिक, लागत-प्रभावी उपचारहरू भएको एक विशिष्ट ज्योतिष प्रणाली हो। यो भाव विश्लेषण र उपचार दृष्टिकोणमा शास्त्रीय वैदिक ज्योतिषभन्दा फरक छ।"),
    LAL_KITAB_SYSTEM_NOTE("System Note", "प्रणाली नोट"),
    LAL_KITAB_PLANETARY_AFFLICTIONS("Planetary Afflictions", "ग्रह पीडाहरू"),
    LAL_KITAB_KARMIC_DEBTS("Karmic Debts (Rin)", "कार्मिक ऋण"),
    LAL_KITAB_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
    LAL_KITAB_REMEDIES("Remedies", "उपायहरू"),
    LAL_KITAB_COLOR_REMEDIES("Color Remedies", "रंग उपायहरू"),
    LAL_KITAB_DIRECTION_REMEDIES("Direction Remedies", "दिशा उपायहरू"),
    LAL_KITAB_ANNUAL_CALENDAR("Weekly Remedy Calendar", "साप्ताहिक उपाय पात्रो"),
    LAL_KITAB_GENERAL_RECOMMENDATIONS("General Recommendations", "सामान्य सिफारिसहरू"),
    LAL_KITAB_AFFLICTION_TYPE("Affliction Type", "पीडा प्रकार"),
    LAL_KITAB_AFFLICTION_SEVERITY("Severity", "गम्भीरता"),
    LAL_KITAB_PITRU_DOSH("Pitru Dosh", "पितृ दोष"),
    LAL_KITAB_MATRU_RIN("Matru Rin", "मातृ ऋण"),
    LAL_KITAB_STRI_RIN("Stri Rin", "स्त्री ऋण"),
    LAL_KITAB_KANYA_RIN("Kanya Rin", "कन्या ऋण"),
    LAL_KITAB_GRAHAN_DOSH("Grahan Dosh", "ग्रहण दोष"),
    LAL_KITAB_SHANI_PEEDA("Shani Peeda", "शनि पीडा"),
    LAL_KITAB_SEVERITY_MINIMAL("Minimal", "न्यूनतम"),
    LAL_KITAB_SEVERITY_MILD("Mild", "हल्का"),
    LAL_KITAB_SEVERITY_MODERATE("Moderate", "मध्यम"),
    LAL_KITAB_SEVERITY_SEVERE("Severe", "गम्भीर"),
    LAL_KITAB_DEBT_TYPE("Debt Type", "ऋण प्रकार"),
    LAL_KITAB_DEBT_INDICATORS("Indicators", "सूचकहरू"),
    LAL_KITAB_DEBT_EFFECTS("Effects", "प्रभावहरू"),
    LAL_KITAB_HOUSE_STATUS("House Status", "भाव स्थिति"),
    LAL_KITAB_HOUSE_EMPTY("Empty", "खाली"),
    LAL_KITAB_HOUSE_OCCUPIED("Occupied", "भरिएको"),
    LAL_KITAB_HOUSE_BENEFIC("Benefic Influence", "शुभ प्रभाव"),
    LAL_KITAB_HOUSE_AFFLICTED("Afflicted", "पीडित"),
    LAL_KITAB_REMEDY_CATEGORY("Remedy Category", "उपाय श्रेणी"),
    LAL_KITAB_CATEGORY_PLANETARY("Planetary Remedy", "ग्रह उपाय"),
    LAL_KITAB_CATEGORY_KARMIC("Karmic Debt Remedy", "कार्मिक ऋण उपाय"),
    LAL_KITAB_CATEGORY_HOUSE("House-based Remedy", "भाव-आधारित उपाय"),
    LAL_KITAB_CATEGORY_GENERAL("General Remedy", "सामान्य उपाय"),
    LAL_KITAB_REMEDY_METHOD("Method", "विधि"),
    LAL_KITAB_REMEDY_FREQUENCY("Frequency", "आवृत्ति"),
    LAL_KITAB_REMEDY_DURATION("Duration", "अवधि"),
    LAL_KITAB_REMEDY_EFFECTIVENESS("Effectiveness", "प्रभावकारिता"),
    LAL_KITAB_FAVORABLE_COLORS("Favorable Colors", "शुभ रंगहरू"),
    LAL_KITAB_AVOID_COLORS("Colors to Avoid", "परिहार गर्ने रंगहरू"),
    LAL_KITAB_COLOR_APPLICATION("Application", "प्रयोग"),
    LAL_KITAB_FAVORABLE_DIRECTION("Favorable Direction", "शुभ दिशा"),
    LAL_KITAB_AVOID_DIRECTION("Direction to Avoid", "परिहार गर्ने दिशा"),
    LAL_KITAB_DIRECTION_APPLICATION("Direction Application", "दिशा प्रयोग"),
    LAL_KITAB_SUNDAY("Sunday - Sun", "आइतबार - सूर्य"),
    LAL_KITAB_MONDAY("Monday - Moon", "सोमबार - चन्द्र"),
    LAL_KITAB_TUESDAY("Tuesday - Mars", "मंगलबार - मंगल"),
    LAL_KITAB_WEDNESDAY("Wednesday - Mercury", "बुधबार - बुध"),
    LAL_KITAB_THURSDAY("Thursday - Jupiter", "बिहीबार - बृहस्पति"),
    LAL_KITAB_FRIDAY("Friday - Venus", "शुक्रबार - शुक्र"),
    LAL_KITAB_SATURDAY("Saturday - Saturn", "शनिबार - शनि"),
    LAL_KITAB_SCREEN_TITLE("Lal Kitab Remedies", "लाल किताब उपायहरू"),
    LAL_KITAB_INDICATORS("Indicators", "संकेतहरू"),
    LAL_KITAB_REMEDIES_LABEL("Remedies", "उपायहरू"),
    LAL_KITAB_TYPES_TITLE("Types of Karmic Debts", "कार्मिक ऋणका प्रकारहरू"),
    LAL_KITAB_DESC_PITRU("Debt towards father and ancestors", "पिता र पूर्वजहरूप्रति ऋण"),
    LAL_KITAB_DESC_MATRU("Debt towards mother and maternal lineage", "आमा र मातृपक्षप्रति ऋण"),
    LAL_KITAB_DESC_STRI("Debt towards wife/women", "पत्नी/स्त्रीहरूप्रति ऋण"),
    LAL_KITAB_DESC_SELF("Debt towards self and karma", "स्वयं र कर्मप्रति ऋण"),
    LAL_KITAB_DAILY_REMEDIES_DESC("Daily remedies for each planetary day as per Lal Kitab tradition", "लाल किताब परम्परा अनुसार प्रत्येक ग्रह बारका दैनिक उपायहरू"),
    LAL_KITAB_FAVORABLE("Favorable", "अनुकूल"),
    LAL_KITAB_AVOID("Avoid", "त्याग गर्नुहोस्"),
    LAL_KITAB_DEBT_KANYA("Girl Child Debt", "कन्या ऋण"),
    LAL_KITAB_SCREEN_SUBTITLE("Practical Karmic Remedies", "व्यावहारिक कार्मिक उपायहरू"),
    LAL_KITAB_SCREEN_ABOUT("About Lal Kitab", "लाल किताबको बारेमा"),
    LAL_KITAB_SCREEN_ABOUT_DESC("Lal Kitab offers simple, practical remedies using everyday items like turmeric, milk, honey, and specific actions. These remedies work on karmic debts and planetary afflictions without expensive rituals.", "लाल किताबले बेसार, दूध, मह जस्ता दैनिक वस्तुहरू प्रयोग गरी सरल, व्यावहारिक उपायहरू प्रदान गर्दछ। यी उपायहरूले महँगो विधि बिना कार्मिक ऋण र ग्रह पीडामा काम गर्दछन्।"),
    LAL_KITAB_SCREEN_KARMIC_DEBTS("Karmic Debts (Rin)", "कार्मिक ऋणहरू"),
    LAL_KITAB_SCREEN_PLANETARY_AFFLICTIONS("Planetary Afflictions", "ग्रह पीडाहरू"),
    LAL_KITAB_HOUSE_REMEDIES("House-Based Remedies", "भाव-आधारित उपायहरू"),
    LAL_KITAB_DAILY_REMEDIES("Daily Remedies", "दैनिक उपायहरू"),
    LAL_KITAB_ITEM_BASED("Item-Based Remedies", "वस्तु-आधारित उपायहरू"),
    LAL_KITAB_COLOR_THERAPY("Color Therapy", "रंग चिकित्सा"),
    LAL_KITAB_DIRECTION_GUIDANCE("Direction Guidance", "दिशा मार्गदर्शन"),
    LAL_KITAB_WEEKLY_SCHEDULE("Weekly Remedy Schedule", "साप्ताहिक उपाय तालिका"),
    LAL_KITAB_REMEDY_ITEM("Remedy Item", "उपाय वस्तु"),
    LAL_KITAB_REMEDY_ACTION("Action Required", "आवश्यक कार्य"),
    LAL_KITAB_REMEDY_TIMING("Best Timing", "उत्तम समय"),
    LAL_KITAB_EFFECTIVENESS_HIGH("Highly Effective", "अत्यधिक प्रभावकारी"),
    LAL_KITAB_EFFECTIVENESS_MEDIUM("Moderately Effective", "मध्यम प्रभावकारी"),
    LAL_KITAB_DEBT_PITRU("Pitru Rin (Ancestral)", "पितृ ऋण (पूर्वज)"),
    LAL_KITAB_DEBT_MATRU("Matru Rin (Maternal)", "मातृ ऋण (मातृपक्ष)"),
    LAL_KITAB_DEBT_STRI("Stri Rin (Feminine)", "स्त्री ऋण (स्त्री)"),
    LAL_KITAB_DEBT_SELF("Swayam Rin (Self)", "स्वयं ऋण (स्वयं)"),
    LAL_KITAB_NOTE_DISTINCT("Lal Kitab remedies are unique and different from traditional Vedic remedies.", "लाल किताब उपायहरू अद्वितीय छन् र परम्परागत वैदिक उपायहरूभन्दा फरक छन्।"),
    LAL_KITAB_RECOMMENDED_REMEDIES("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
    LAL_KITAB_AFFLICTION_KANYA("Kanya Rin (Debt of Young Women)", "कन्या ऋण"),
    LAL_KITAB_AFFLICTION_GRAHAN("Grahan Dosha", "ग्रहण दोष"),
    LAL_KITAB_AFFLICTION_SHANI("Shani Affliction", "शनि पीडा"),
    LAL_KITAB_AFFLICTION_GENERAL("General Affliction", "सामान्य पीडा"),
    LAL_KITAB_SECTION_REMEDIES("Remedies", "उपायहरू"),
    LAL_KITAB_GENERAL_PRINCIPLES("General Principles of Lal Kitab", "लाल किताबका सामान्य सिद्धान्तहरू"),
    LAL_KITAB_RIN_TITLE("Karmic Debts (Rin)", "कर्म ऋणहरू"),
    LAL_KITAB_RIN_DESC("Karmic debts indicate areas where remedial measures are needed to balance past karma.", "कर्म ऋणहरूले विगतको कर्म सन्तुलन गर्न उपायहरू आवश्यक पर्ने क्षेत्रहरू संकेत गर्दछ।"),
    LAL_KITAB_RIN_NONE_TITLE("No Significant Karmic Debts", "कुनै महत्त्वपूर्ण कर्म ऋण छैन"),
    LAL_KITAB_RIN_NONE_DESC("Your chart does not indicate major karmic debts requiring immediate remedies.", "तपाईंको कुण्डलीले तत्काल उपाय आवश्यक पर्ने प्रमुख कर्म ऋणहरू संकेत गर्दैन।"),

    // ============================================
    // MRITYU BHAGA
    // ============================================
    MRITYU_BHAGA_SCREEN_TITLE("Mrityu Bhaga Analysis", "मृत्यु भाग विश्लेषण"),
    MRITYU_BHAGA_SCREEN_SUBTITLE("Sensitive Degrees in Chart", "कुण्डलीमा संवेदनशील अंशहरू"),
    MRITYU_BHAGA_SCREEN_ABOUT("About Mrityu Bhaga", "मृत्यु भागको बारेमा"),
    MRITYU_BHAGA_SCREEN_ABOUT_DESC("Mrityu Bhaga refers to specific sensitive degrees in each zodiac sign. When planets occupy these degrees, they indicate areas of life requiring extra attention. These are sensitive points that may indicate health vulnerabilities or significant life challenges.", "मृत्यु भागले प्रत्येक राशिमा विशेष संवेदनशील अंशहरूलाई जनाउँछ। जब ग्रहहरू यी अंशहरूमा हुन्छन्, तिनीहरूले थप ध्यान चाहिने जीवनका क्षेत्रहरू संकेत गर्दछन्।"),
    MRITYU_BHAGA_PLANETS_AFFECTED("Planets in Mrityu Bhaga", "मृत्यु भागमा ग्रहहरू"),
    MRITYU_BHAGA_NO_PLANETS("No planets in Mrityu Bhaga", "मृत्यु भागमा कुनै ग्रह छैन"),
    MRITYU_BHAGA_SENSITIVE_DEGREE("Sensitive Degree", "संवेदनशील अंश"),
    MRITYU_BHAGA_ORB("Orb", "कोणान्तर"),
    MRITYU_BHAGA_SEVERITY("Severity Level", "गम्भीरता स्तर"),
    MRITYU_BHAGA_LIFE_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    MRITYU_BHAGA_REMEDIES_SECTION("Suggested Remedies", "सुझाव गरिएका उपायहरू"),
    MRITYU_BHAGA_TRANSIT_WARNING("Transit Alerts", "गोचर चेतावनीहरू"),
    MRITYU_BHAGA_SIGN_DEGREES("Mrityu Bhaga Degrees by Sign", "राशि अनुसार मृत्यु भाग अंशहरू"),
    MRITYU_BHAGA_ALL_SIGNS("All Signs Reference", "सबै राशि सन्दर्भ"),
    MRITYU_BHAGA_PRECAUTIONS("Precautionary Measures", "सावधानीका उपायहरू"),
    MRITYU_BHAGA_GANDANTA_PLACEMENTS("Gandanta Placements", "गण्डान्त स्थितिहरू"),
    MRITYU_BHAGA_AUSPICIOUS_PLACEMENTS("Auspicious Placements", "शुभ स्थितिहरू"),
    MRITYU_BHAGA_NO_CRITICAL("Your chart is free from critical Mrityu Bhaga placements.", "तपाईंको कुण्डली गम्भीर मृत्यु भाग स्थितिहरूबाट मुक्त छ।"),
    MRITYU_BHAGA_LEVEL_NEEDS_ATTENTION("Needs Attention", "ध्यान दिन आवश्यक"),
    MRITYU_BHAGA_LEVEL_MODERATE_CONCERN("Moderate Concern", "मध्यम चिन्ता"),
    MRITYU_BHAGA_LEVEL_BALANCED("Balanced", "सन्तुलित"),
    MRITYU_BHAGA_LEVEL_GENERALLY_POSITIVE("Generally Positive", "सामान्यतया सकारात्मक"),
    MRITYU_BHAGA_LEVEL_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यधिक शुभ"),
    MRITYU_BHAGA_CRITICAL_COUNT("Critical", "गम्भीर"),
    MRITYU_BHAGA_AUSPICIOUS_COUNT("Auspicious", "शुभ"),
    MRITYU_BHAGA_GANDANTA_BRAHMA("Brahma Gandanta", "ब्रह्म गण्डान्त"),
    MRITYU_BHAGA_GANDANTA_VISHNU("Vishnu Gandanta", "विष्णु गण्डान्त"),
    MRITYU_BHAGA_GANDANTA_SHIVA("Shiva Gandanta", "शिव गण्डान्त"),
    MRITYU_BHAGA_JUNCTION_DESC("Junction between %1\$2 and %2\$2", "%1\$2 र %2\$2 बीचको सन्धि"),
    MRITYU_BHAGA_DISTANCE_JUNCTION("Distance from Junction: %1\$2", "सन्धिबाट दूरी: %1\$2"),
    MRITYU_BHAGA_PUSHKARA_NAVAMSA_TITLE("Pushkara Navamsa", "पुष्कर नवमांश"),
    MRITYU_BHAGA_PUSHKARA_BHAGA_TITLE("Pushkara Bhaga", "पुष्कर भाग"),
    MRITYU_BHAGA_BENEFITS("Benefits", "लाभहरू"),
    MRITYU_BHAGA_OVERALL_ASSESSMENT("Overall Assessment", "समग्र मूल्यांकन"),
    MB_SEV_EXACT("Exact", "पूर्ण"),
    MB_SEV_VERY_CLOSE("Very Close", "धेरै नजिक"),
    MB_SEV_WITHIN_ORB("Within Orb", "प्रभाव क्षेत्र भित्र"),
    MB_SEV_APPROACHING("Approaching", "आउँदै गरेको"),
    MB_SEV_SAFE("Safe", "सुरक्षित"),
    GANDANTA_SEV_EXACT("Exact Junction", "पूर्ण सन्धि"),
    GANDANTA_SEV_CRITICAL("Critical", "गम्भीर"),
    GANDANTA_SEV_SEVERE("Severe", "कडा"),
    GANDANTA_SEV_MODERATE("Moderate", "मध्यम"),
    GANDANTA_SEV_MILD("Mild", "हल्का"),

    // ============================================
    // UPACHAYA TRANSIT SCREEN
    // ============================================
    UPACHAYA_SCREEN_TITLE("Upachaya Transits", "उपचय गोचर"),
    UPACHAYA_SCREEN_SUBTITLE("Growth House Transit Tracker", "वृद्धि भाव गोचर ट्र्याकर"),
    UPACHAYA_SCREEN_ABOUT("About Upachaya Houses", "उपचय भावहरूको बारेमा"),
    UPACHAYA_SCREEN_ABOUT_DESC("Upachaya houses (3, 6, 10, 11) are growth houses where malefic planets give good results over time. Natural malefics improve with age in these houses.", "उपचय भावहरू (३, ६, १०, ११) वृद्धि भावहरू हुन् जहाँ पापग्रहले समयसँगै राम्रो परिणाम दिन्छन्।"),
    UPACHAYA_HOUSES("Upachaya Houses (3, 6, 10, 11)", "उपचय भावहरू (३, ६, १०, ११)"),
    UPACHAYA_SCREEN_FROM_MOON("Transit from Moon Sign", "चन्द्र राशिबाट गोचर"),
    UPACHAYA_CURRENT_TRANSITS("Current Beneficial Transits", "वर्तमान लाभदायक गोचर"),
    UPACHAYA_SCREEN_UPCOMING("Upcoming Favorable Periods", "आगामी अनुकूल अवधिहरू"),
    UPACHAYA_SATURN_TRANSIT("Saturn in Upachaya", "उपचयमा शनि"),
    UPACHAYA_MARS_TRANSIT("Mars in Upachaya", "उपचयमा मंगल"),
    UPACHAYA_RAHU_TRANSIT("Rahu in Upachaya", "उपचयमा राहु"),
    UPACHAYA_JUPITER_TRANSIT("Jupiter in Upachaya", "उपचयमा बृहस्पति"),
    UPACHAYA_SCREEN_HOUSE_3("3rd House - Courage, Siblings, Communication", "तेस्रो भाव - साहस, भाइबहिनी, सञ्चार"),
    UPACHAYA_SCREEN_HOUSE_6("6th House - Enemies, Service, Health", "छैटौं भाव - शत्रु, सेवा, स्वास्थ्य"),
    UPACHAYA_SCREEN_HOUSE_10("10th House - Career, Status, Authority", "दसौं भाव - क्यारियर, स्थिति, अधिकार"),
    UPACHAYA_SCREEN_HOUSE_11("11th House - Gains, Desires, Friends", "एघारौं भाव - लाभ, इच्छा, मित्र"),
    UPACHAYA_GROWTH_INDICATOR("Growth Indicator", "वृद्धि सूचक"),
    UPACHAYA_ACTIVE_NOW("Active Now", "अहिले सक्रिय"),
    UPACHAYA_COMING_SOON("Coming Soon", "छिट्टै आउँदैछ"),
    UPACHAYA_SCREEN_DURATION("Transit Duration", "गोचर अवधि"),
    UPACHAYA_SCREEN_EFFECTS("Expected Effects", "अपेक्षित प्रभावहरू"),
    UPACHAYA_IMPROVEMENT_AREAS("Areas of Improvement", "सुधारका क्षेत्रहरू"),
    UPACHAYA_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
    UPACHAYA_TRANSIT_DETAILS("Transit Details", "गोचर विवरण"),
    UPACHAYA_UPCOMING_TRANSITS("Upcoming Transits", "आगामी गोचरहरू"),
    UPACHAYA_ACTIVE_ALERTS("Active Alerts", "सक्रिय सूचनाहरू"),
    UPACHAYA_SIGNIFICANT_TRANSITS("Significant Transits", "महत्त्वपूर्ण गोचरहरू"),
    UPACHAYA_TRANSIT_ASSESSMENT("Transit Assessment", "गोचर मूल्याङ्कन"),
    UPACHAYA_REFERENCE_POINTS("Reference Points", "सन्दर्भ बिन्दुहरू"),
    UPACHAYA_ABOUT("About Upachaya", "उपचयको बारेमा"),
    UPACHAYA_SATURN_PROGRESS("Saturn strengthens discipline in %s", "शनिले %s मा अनुशासन बलियो बनाउँछ"),
    UPACHAYA_MARS_PROGRESS("Mars energizes action in %s", "मंगलले %s मा कार्यलाई ऊर्जित गर्छ"),
    UPACHAYA_JUPITER_PROGRESS("Jupiter expands opportunities in %s", "बृहस्पतिले %s मा अवसरहरू विस्तार गर्छ"),
    UPACHAYA_ASSESS_NO_ACTIVE("No significant Upachaya transits currently active", "हाल कुनै महत्त्वपूर्ण उपचय गोचर सक्रिय छैन"),
    UPACHAYA_ASSESS_WAIT("Wait for slow planets to enter Upachaya houses", "ढिलो हिड्ने ग्रहहरू उपचय भावहरूमा प्रवेश गर्ने प्रतीक्षा गर्नुहोस्"),
    UPACHAYA_ASSESS_EXCEPTIONAL("Exceptional period! Multiple powerful transits favor growth in career, gains, and overcoming obstacles", "असाधारण अवधि! बहु शक्तिशाली गोचरहरूले क्यारियर, लाभ र बाधाहरू पार गर्न मद्दत गर्छन्"),
    UPACHAYA_ASSESS_HIGH("Favorable period with strong Upachaya transits supporting professional and material growth", "व्यावसायिक र भौतिक वृद्धिलाई समर्थन गर्ने बलियो उपचय गोचरसहितको अनुकूल अवधि"),
    UPACHAYA_ASSESS_MODERATE("Moderate Upachaya support - steady progress possible with focused effort", "मध्यम उपचय समर्थन - केन्द्रित प्रयासको साथ स्थिर प्रगति सम्भव छ"),
    UPACHAYA_ASSESS_LOW("Limited Upachaya activation - focus on preparation for upcoming favorable transits", "सीमित उपचय सक्रियता - आगामी अनुकूल गोचरहरूको तयारीमा ध्यान दिनुहोस्"),
    UPACHAYA_ASSESS_KEY_TRANSIT("%s in %s house is the key transit", "%s भावमा %s मुख्य गोचर हो"),
    UPACHAYA_ASSESS_DAILY_ACTION("Focus on daily actions to maximize current transits", "वर्तमान गोचरहरूलाई अधिकतम बनाउन दैनिक कार्यहरूमा ध्यान दिनुहोस्"),
    UPACHAYA_REC_BOLD_INITIATIVE("Take bold initiatives - courage is supported now", "साहसी पहलहरू गर्नुहोस् - साहस अहिले समर्थित छ"),
    UPACHAYA_REC_HEALTH_CONFLICTS("Address health and resolve conflicts - victory over obstacles favored", "स्वास्थ्य र विवाद समाधानमा ध्यान दिनुहोस् - बाधाहरूमाथि विजय अनुकूल छ"),
    UPACHAYA_REC_CAREER_FOCUS("Focus on career advancement - professional recognition possible", "क्यारियर प्रगतिमा ध्यान दिनुहोस् - व्यावसायिक मान्यता सम्भव छ"),
    UPACHAYA_REC_FINANCIAL_GOALS("Pursue financial goals - gains and fulfillment of desires supported", "आर्थिक लक्ष्यहरू पछ्याउनुहोस् - लाभ र इच्छाहरूको पूर्ति समर्थित छ"),
    UPACHAYA_REC_SLOW_PLANET("Major slow-planet transit active - commit to long-term goals", "प्रमुख ढिलो ग्रह गोचर सक्रिय छ - दीर्घकालीन लक्ष्यहरूमा प्रतिबद्ध रहनुहोस्"),
    UPACHAYA_REC_PREPARE_UPCOMING("Prepare for upcoming Upachaya transits by organizing current affairs", "वर्तमान मामिलाहरू व्यवस्थित गरेर आगामी उपचय गोचरहरूको लागि तयारी गर्नुहोस्"),
    UPACHAYA_ALERT_EXCELLENT("%s in %s house - Excellent opportunity period!", "%s भावमा %s - उत्कृष्ट अवसर अवधि!"),
    UPACHAYA_ALERT_SATURN_10("Saturn transiting 10th house - Major career period! Work hard for lasting results", "शनिको १०औं भावमा गोचर - प्रमुख क्यारियर अवधि! स्थायी परिणामका लागि कडा परिश्रम गर्नुहोस्"),
    UPACHAYA_ALERT_JUPITER_11("Jupiter transiting 11th house - Excellent for gains and fulfillment of desires!", "बृहस्पतिको ११औं भावमा गोचर - लाभ र इच्छाहरूको पूर्तिका लागि उत्कृष्ट!"),
    UPACHAYA_UPCOMING_SIGNIFICANCE("When %s enters %s - %s activated", "जब %s ले %s मा प्रवेश गर्छ - %s सक्रिय हुन्छ"),
    UPACHAYA_UPCOMING_REC("Prepare for %s related activities", "%s सम्बन्धित गतिविधिहरूको तयारी गर्नुहोस्"),
    UPACHAYA_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
    UPACHAYA_LAGNA("Lagna", "लग्न"),
    UPACHAYA_ACTIVE("Active", "सक्रिय"),
    QUALITY_LABEL("Quality", "गुणस्तर"),
    FROM_LABEL("from", "बाट"),
    PLANETS_TITLE("Transiting Planets", "गोचर ग्रहहरू"),
    UPACHAYA_TRANSITS_LABEL("Transits", "गोचरहरू"),

    // ============================================
    // ARUDHA PADA SCREEN
    // ============================================
    ARUDHA_SCREEN_TITLE("Arudha Pada", "आरुढ पद"),
    ARUDHA_ANALYSIS_TITLE("Arudha Pada Analysis", "आरुढ पद विश्लेषण"),
    ARUDHA_KEY_POSITIONS("Key Arudha Positions", "मुख्य आरुढ स्थितिहरू"),
    ARUDHA_MANIFESTATION("Manifestation Strength", "प्रकटीकरण शक्ति"),
    ARUDHA_PUBLIC_IMAGE("Public Image", "सार्वजनिक छवि"),
    ARUDHA_CAREER("Career", "क्यारियर"),
    ARUDHA_GAINS("Gains", "लाभ"),
    ARUDHA_RELATIONSHIPS("Relationships", "सम्बन्धहरू"),
    ARUDHA_KEY_THEMES("Key Themes", "मुख्य विषयवस्तुहरू"),
    ARUDHA_YOGAS_TITLE("Arudha Yogas", "आरुढ योगहरू"),
    ARUDHA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    ARUDHA_CALCULATING("Calculating Arudha Padas...", "आरुढ पद गणना गर्दै..."),
    ARUDHA_ABOUT_BTN("About Arudha Pada", "आरुढ पदको बारेमा"),

    // ============================================
    // ASHTAKAVARGA SCREEN
    // ============================================
    ASHTAKAVARGA_SUMMARY_TITLE("Ashtakavarga Summary", "अष्टकवर्ग सारांश"),
    ASHTAKAVARGA_DISTRIBUTION_TITLE("House Strength Distribution", "भाव बल विभाजन"),
    ASHTAKAVARGA_TOTAL_BINDUS("Total Bindus", "कुल विन्दुहरू"),
    ASHTAKAVARGA_AVG_PER_HOUSE("Avg/House", "औसत/भाव"),
    ASHTAKAVARGA_STRENGTH("Strength", "बल"),
    ASHTAKAVARGA_CHART_STRENGTH("Overall Chart Strength", "समग्र कुण्डली बल"),
    ASHTAKAVARGA_LEGEND_STRONG(">30 Strong", ">३० बलियो"),
    ASHTAKAVARGA_LEGEND_GOOD("25-30 Good", "२५-३० राम्रो"),
    ASHTAKAVARGA_LEGEND_WEAK("<25 Weak", "<२५ कमजोर"),
    ASHTAKAVARGA_KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टि"),
    ASHTAKAVARGA_DESC_FMT("Bindu strength analysis - %s", "विन्दु बल विश्लेषण - %s"),
    ASHTAKAVARGA_DISTRIBUTION_DESC("Bindu distribution analysis", "विन्दु वितरण विश्लेषण"),
    ASHTAKAVARGA_INFO_A11Y("Ashtakavarga info", "अष्टकवर्ग जानकारी"),
    ASHTAKAVARGA_STRONGEST("STRONGEST HOUSES", "सबैभन्दा बलियो भावहरू"),
    ASHTAKAVARGA_WEAKEST("WEAKEST HOUSES", "सबैभन्दा कमजोर भावहरू"),
    ASHTAKAVARGA_PLANET_TOTALS("Planet Bindu Totals", "ग्रह बिन्दु योग"),
    ASHTAKAVARGA_SARVA_DESC("Sarvashtakavarga is the combined bindu strength from all seven planets for each house/sign.", "सर्वाष्टकवर्ग प्रत्येक भाव/राशिको लागि सातै ग्रहहरूको संयुक्त बिन्दु शक्ति हो।"),
    ASHTAKAVARGA_ABOUT_TITLE("About Ashtakavarga", "अष्टकवर्गको बारेमा"),
    ASHTAKAVARGA_ABOUT_DESC("Ashtakavarga is a unique Vedic system that calculates the strength of each house by analyzing beneficial points (bindus) contributed by seven planets.", "अष्टकवर्ग एक अद्वितीय वैदिक प्रणाली हो जसले सात ग्रहहरूद्वारा प्रदान गरिएको शुभ बिन्दुहरूको विश्लेषण गरेर प्रत्येक भावको शक्ति गणना गर्दछ।"),
    ASHTAKAVARGA_INTERPRETATION("Interpretation Guide:", "व्याख्या मार्गदर्शन:"),
    ASHTAKAVARGA_GUIDE_TEXT("• 30+ bindus: Very strong, excellent results\n• 25-30 bindus: Good strength, favorable\n• 20-25 bindus: Average, mixed results\n• Below 20: Weak, challenges expected", "• ३०+ बिन्दु: धेरै बलियो, उत्कृष्ट परिणाम\n• २५-३० बिन्दु: राम्रो शक्ति, अनुकूल\n• २०-२५ बिन्दु: औसत, मिश्रित परिणाम\n• २० भन्दा कम: कमजोर, चुनौतीहरू अपेक्षित"),
    ASHTAKAVARGA_BINDUS_SUFFIX("bindus", "बिन्दुहरू"),

    // House Significations (Short)
    HOUSE_SIG_1("Self, Body, Personality", "स्वयं, शरीर, व्यक्तित्व"),
    HOUSE_SIG_2("Wealth, Speech, Family", "धन, वाणी, परिवार"),
    HOUSE_SIG_3("Siblings, Courage", "दाजुभाइ, साहस"),
    HOUSE_SIG_4("Home, Mother, Property", "घर, आमा, सम्पत्ति"),
    HOUSE_SIG_5("Children, Education", "सन्तान, शिक्षा"),
    HOUSE_SIG_6("Health, Enemies", "स्वास्थ्य, शत्रु"),
    HOUSE_SIG_7("Marriage, Partnership", "विवाह, साझेदारी"),
    HOUSE_SIG_8("Transformation", "रूपान्तरण"),
    HOUSE_SIG_9("Fortune, Father", "भाग्य, पिता"),
    HOUSE_SIG_10("Career, Fame", "क्यारियर, प्रसिद्धि"),
    HOUSE_SIG_11("Gains, Wishes", "लाभ, इच्छा"),
    HOUSE_SIG_12("Losses, Liberation", "हानी, मोक्ष"),

    // ============================================
    // AVASTHA SCREEN
    // ============================================
    AVASTHA_SCREEN_TITLE("Planetary Avasthas", "ग्रह अवस्थाहरू"),
    AVASTHA_SUBTITLE("Planetary States & Conditions", "ग्रह स्थिति र अवस्थाहरू"),
    AVASTHA_NO_CHART_DESC("Create or select a birth chart to analyze planetary Avasthas.", "ग्रह अवस्थाहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    AVASTHA_ABOUT_TITLE("About Planetary Avasthas", "ग्रह अवस्थाहरूको बारेमा"),
    AVASTHA_ABOUT_DESC("Avasthas are planetary states that indicate how effectively a planet can deliver its results.\n\nFour Types of Avasthas:\n\n1. Baladi (Age-based):\nBala (Infant), Kumara (Youth), Yuva (Adult), Vriddha (Old), Mrita (Dead)\n\n2. Jagradadi (Alertness):\nJagrat (Awake), Swapna (Dreaming), Sushupti (Deep Sleep)\n\n3. Deeptadi (Dignity):\nDeepta, Swastha, Mudita, Shanta, Dina, Vikala, Khala, Kopa, Bhita\n\n4. Lajjitadi (Emotional):\nLajjita, Garvita, Kshudita, Trushita, Mudita, Kshobhita\n\nA planet in good avasthas gives its full results, while one in poor avasthas struggles to manifest its significations.", "अवस्थाहरू ग्रहका स्थितिहरू हुन् जसले ग्रहले आफ्ना नतिजाहरू कत्तिको प्रभावकारी रूपमा दिन सक्छ भनेर संकेत गर्दछ।\n\nचार प्रकारका अवस्थाहरू:\n\n१. बालादि (उमेरमा आधारित):\nबाल, कुमार, युवा, वृद्ध, मृत\n\n२. जाग्रदादि (जागरूकता):\nजाग्रत, स्वप्न, सुषुप्ति\n\n३. दीप्तादि (मर्यादा):\nदीप्त, स्वस्थ, मुदित, शान्त, दीन, विकल, खल, कोप, भीत\n\n४. लज्जितादि (भावनात्मक):\nलज्जित, गर्वित, क्षुधित, तृषित, मुदित, क्षोभित\n\nराम्रो अवस्थामा रहेको ग्रहले पूर्ण फल दिन्छ, जबकि कमजोर अवस्थामा रहेको ग्रहले आफ्ना कारकहरू व्यक्त गर्न संघर्ष गर्दछ।"),
    AVASTHA_OVERALL_STRENGTH("Overall Planetary Strength", "समग्र ग्रह बल"),
    AVASTHA_STRONGEST("Strongest", "सबैभन्दा बलियो"),
    AVASTHA_NEEDS_ATTENTION("Needs Attention", "ध्यान दिनुपर्ने"),

    // ============================================
    // NITYA YOGA SCREEN
    // ============================================
    NITYA_SCREEN_TITLE("Nitya Yoga", "नित्य योग"),
    NITYA_SUBTITLE("27 Daily Yogas", "२७ दैनिक योगहरू"),
    NITYA_NO_DATA_DESC("Create or select a birth chart to view Nitya Yoga analysis.", "नित्य योग विश्लेषण हेर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    NITYA_ABOUT_TITLE("About Nitya Yoga", "नित्य योगको बारेमा"),
    NITYA_ABOUT_DESC("Nitya Yoga (Daily Yoga) is one of the five elements of the Panchanga (Hindu almanac).\n\nThere are 27 Nitya Yogas, each spanning 13°20' of the combined longitude of Sun and Moon.\n\nCalculation:\nNitya Yoga = (Sun longitude + Moon longitude) ÷ 13°20'\n\nThese yogas indicate the general auspiciousness of a moment and are used in Muhurta (electional astrology) to select favorable times for important activities.\n\nEach yoga is ruled by a planet and has specific characteristics affecting health, wealth, relationships, and spiritual matters.", "नित्य योग पञ्चाङ्गका पाँच अंगहरू मध्ये एक हो।\n\nत्यहाँ २७ नित्य योगहरू छन्, प्रत्येकले सूर्य र चन्द्रमाको संयुक्त देशान्तरको १३°२०' समेट्छ।\n\nगणना:\nनित्य योग = (सूर्य स्पष्ट + चन्द्र स्पष्ट) ÷ १३°२०'\n\nयी योगहरूले समयको सामान्य शुभतालाई संकेत गर्दछ र महत्त्वपूर्ण गतिविधिहरूको लागि शुभ समय छनौट गर्न मुहूर्तमा प्रयोग गरिन्छ।\n\nप्रत्येक योग एक ग्रहद्वारा शासित हुन्छ र यसले स्वास्थ्य, धन, सम्बन्ध र आध्यात्मिक मामिलाहरूलाई असर गर्ने विशिष्ट विशेषताहरू राख्छ।"),
    NITYA_PROGRESS("Progress", "प्रगति"),
    NITYA_POSITION("Position", "स्थिति"),
    NITYA_NATURE("Nature", "प्रकृति"),
    NITYA_CURRENT_PROGRESS("Progress in Current Yoga", "वर्तमान योगमा प्रगति"),
    NITYA_SUITABLE("Suitable Activities", "उपयुक्त गतिविधिहरू"),
    NITYA_AVOID("Activities to Avoid", "बच्नुपर्ने गतिविधिहरू"),
    NITYA_NEXT("Next:", "अर्को:"),
    NITYA_REMAINING("remaining", "बाँकी"),

    // ============================================
    // NAKSHATRA SCREEN
    // ============================================
    NAKSHATRA_NATURE_FIXED("Fixed (Dhruva)", "स्थिर (ध्रुव)"),
    NAKSHATRA_NATURE_MOVEABLE("Moveable (Chara)", "चर"),
    NAKSHATRA_NATURE_SHARP("Sharp (Tikshna)", "तीक्ष्ण"),
    NAKSHATRA_NATURE_SOFT("Soft (Mridu)", "मृदु"),
    NAKSHATRA_NATURE_MIXED("Mixed (Mishra)", "मिश्र"),
    NAKSHATRA_NATURE_LIGHT("Light (Laghu)", "लघु"),
    NAKSHATRA_NATURE_FIERCE("Fierce (Ugra)", "उग्र"),
    NAKSHATRA_GANA_DEVA("Deva (Divine)", "देव"),
    NAKSHATRA_GANA_MANUSHYA("Manushya (Human)", "मनुष्य"),
    NAKSHATRA_GANA_RAKSHASA("Rakshasa (Demon)", "राक्षस"),
    NAKSHATRA_ELEMENT_FIRE("Fire (Agni)", "अग्नि"),
    NAKSHATRA_ELEMENT_EARTH("Earth (Prithvi)", "पृथ्वी"),
    NAKSHATRA_ELEMENT_AIR("Air (Vayu)", "वायु"),
    NAKSHATRA_ELEMENT_WATER("Water (Jala)", "जल"),
    NAKSHATRA_ELEMENT_ETHER("Ether (Akasha)", "आकाश"),
    NAKSHATRA_CASTE_BRAHMIN("Brahmin", "ब्राह्मण"),
    NAKSHATRA_CASTE_KSHATRIYA("Kshatriya", "क्षत्रिय"),
    NAKSHATRA_CASTE_VAISHYA("Vaishya", "वैश्य"),
    NAKSHATRA_CASTE_SHUDRA("Shudra", "शूद्र"),
    NAKSHATRA_GENDER_MALE("Male", "पुरुष"),
    NAKSHATRA_GENDER_FEMALE("Female", "स्त्री"),
    NAKSHATRA_GENDER_NEUTRAL("Neutral", "नपुंसक"),
    NAKSHATRA_DOSHA_VATA("Vata", "वात"),
    NAKSHATRA_DOSHA_PITTA("Pitta", "पित्त"),
    NAKSHATRA_DOSHA_KAPHA("Kapha", "कफ"),
    NAKSHATRA_RAJJU_PAADA("Paada", "पाद"),
    NAKSHATRA_RAJJU_KATI("Kati", "कटि"),
    NAKSHATRA_RAJJU_NABHI("Nabhi", "नाभि"),
    NAKSHATRA_RAJJU_KANTHA("Kantha", "कण्ठ"),
    NAKSHATRA_RAJJU_SHIRO("Shiro", "शिरो"),
    NAKSHATRA_REMEDY_TITLE("Remedies for %s", "%s का लागि उपायहरू"),
    NAKSHATRA_REMEDY_DESC("Personalized remedies based on your birth nakshatra to enhance positive qualities and mitigate challenges.", "तपाइँको जन्म नक्षत्रमा आधारित व्यक्तिगत उपायहरू सकारात्मक गुणहरू बढाउन र चुनौतीहरू कम गर्न।"),
    NAKSHATRA_REMEDY_TIMING("Best performed during %s hora or on %s", "%s होरा वा %s मा उत्तम"),
    NAKSHATRA_BODY_PART_FEET("Feet", "पाउ"),
    NAKSHATRA_BODY_PART_WAIST("Waist", "कम्मर"),
    NAKSHATRA_BODY_PART_NAVEL("Navel", "नाभि"),
    NAKSHATRA_BODY_PART_NECK("Neck", "घाँटी"),
    NAKSHATRA_BODY_PART_HEAD("Head", "टाउको"),

    // Gemstones
    GEM_RUBY("Ruby", "माणिक"),
    GEM_PEARL("Pearl", "मोती"),
    GEM_RED_CORAL("Red Coral", "मुगा"),
    GEM_EMERALD("Emerald", "पन्ना"),
    GEM_YELLOW_SAPPHIRE("Yellow Sapphire", "पुष्पराज"),
    GEM_DIAMOND("Diamond", "हीरा"),
    GEM_BLUE_SAPPHIRE("Blue Sapphire", "नीलम"),
    GEM_HESSONITE("Hessonite", "गोमेद"),
    GEM_CATS_EYE("Cat's Eye", "लहसुनिया"),

    // Colors
    COLOR_ORANGE("Orange", "सुन्तला"),
    COLOR_GOLD("Gold", "सुनौलो"),
    COLOR_RED("Red", "रातो"),
    COLOR_WHITE("White", "सेतो"),
    COLOR_SILVER("Silver", "चाँदी"),
    COLOR_PEARL("Pearl White", "मोती"),
    COLOR_CORAL("Coral", "मुगा रंग"),
    COLOR_SCARLET("Scarlet", "सिन्दूरे"),
    COLOR_GREEN("Green", "हरियो"),
    COLOR_EMERALD("Emerald", "पन्ना"),
    COLOR_TURQUOISE("Turquoise", "फिरोजा"),
    COLOR_YELLOW("Yellow", "हेलों"),
    COLOR_PINK("Pink", "गुलाबी"),
    COLOR_PASTEL("Pastel", "पास्टेल"),
    COLOR_BLUE("Blue", "नीलो"),
    COLOR_BLACK("Black", "कालो"),
    COLOR_DARK("Dark colors", "गाढा रंगहरू"),
    COLOR_SMOKY("Smoky", "धुवाँ"),
    COLOR_GREY("Grey", "खरानी"),
    COLOR_MIXED("Mixed colors", "मिश्रित रंगहरू"),
    COLOR_BROWN("Brown", "खैरो"),
    COLOR_MULTI("Multi-colored", "बहुरंगी"),

    // Days
    DAY_SUNDAY("Sunday", "आइतबार"),
    DAY_MONDAY("Monday", "सोमबार"),
    DAY_TUESDAY("Tuesday", "मङ्गलबार"),
    DAY_WEDNESDAY("Wednesday", "बुधबार"),
    DAY_THURSDAY("Thursday", "बिहीबार"),
    DAY_FRIDAY("Friday", "शुक्रबार"),
    DAY_SATURDAY("Saturday", "शनिबार"),
    DAY_ANY("Any day", "कुनै पनि दिन"),

    // ============================================
    // SHADBALA SCREEN
    // ============================================
    SHADBALA_STHANA("Sthana", "स्थान"),
    SHADBALA_DIG("Dig", "दिक्"),
    SHADBALA_KALA("Kala", "काल"),
    SHADBALA_CHESTA("Chesta", "चेष्टा"),
    SHADBALA_TOTAL("Total", "कुल"),
    REPORT_PLANET("Planet Report", "ग्रह रिपोर्ट"),

    // ============================================
    // PANCHANGA
    // ============================================
    PANCHANGA_LIMBS_TITLE("Five Limbs of Hindu Calendar", "हिन्दु पात्रोका पाँच अंगहरू"),
    PANCHANGA_FIVE_LIMBS("Five Limbs (Pancha Anga)", "पाँच अंगहरू (पञ्चाङ्ग)"),
    PANCHANGA_TIMING_AUSPICIOUSNESS("Timing & Auspiciousness", "समय र शुभता"),
    PANCHANGA_SUN_MOON("Sun & Moon", "सूर्य र चन्द्रमा"),
    PANCHANGA_RISE("Rise", "उदय"),
    PANCHANGA_SET("Set", "अस्त"),
    PANCHANGA_LUNAR_DAY_FMT("Lunar day (%1\$2)", "चन्द्र दिन (%1\$2)"),
    PANCHANGA_VARA_DESC("Weekday, ruled by specific planet", "बार, विशिष्ट ग्रहद्वारा शासित"),
    PANCHANGA_NAKSHATRA_DESC_FMT("Lunar mansion (Pada %1\$2)", "नक्षत्र (पद %1\$2)"),
    PANCHANGA_YOGA_DESC("Auspicious combination", "शुभ संयोग"),
    PANCHANGA_KARANA_DESC("Half of a tithi", "तिथिको आधा भाग"),
    PANCHANGA_AVOID_ACTIVITIES("Avoid important activities", "महत्त्वपूर्ण कार्यहरू नगर्नुहोस्"),
    PANCHANGA_AUSPICIOUS_TIMING("Auspicious timing", "शुभ समय"),
    PANCHANGA_CALCULATE_DAY("Calculate based on day", "दिनको आधारमा गणना गर्नुहोस्"),
    PANCHANGA_MIDDAY_HOUR("Midday hour", "मध्यान्ह समय"),
    PANCHANGA_SUN("Sun", "सूर्य"),
    PANCHANGA_MOON("Moon", "चन्द्रमा"),
    PANCHANGA_TITHI_LABEL("Tithi", "तिथि"),
    PANCHANGA_VARA_LABEL("Vara", "वार"),
    PANCHANGA_NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
    PANCHANGA_YOGA_LABEL("Yoga", "योग"),
    PANCHANGA_KARANA_LABEL("Karana", "करण"),
    PANCHANGA_RAHU("Rahu Kaal", "राहु काल"),
    PANCHANGA_YAMAGANDAM("Yamagandam", "यमगण्डम"),
    PANCHANGA_GULIKA("Gulika Kaal", "गुलिक काल"),
    PANCHANGA_ABHIJIT("Abhijit Muhurta", "अभिजित मुहूर्त"),
    PANCHANGA_INTRO("Panchanga comprises five essential elements (Pancha Anga) that determine the quality and auspiciousness of any moment in the Hindu calendar system.", "पञ्चाङ्गमा पाँच आवश्यक तत्वहरू (पञ्च अंग) हुन्छन् जसले हिन्दु पात्रो प्रणालीमा कुनै पनि क्षणको गुणस्तर र शुभता निर्धारण गर्दछ।"),
    PANCHANGA_TITHI_DESC_LONG("The lunar day, calculated based on the angular distance between the Sun and Moon. Each tithi represents 12 degrees of lunar motion. There are 30 tithis in a lunar month, divided into Shukla (waxing) and Krishna (waning) Paksha.", "चन्द्र दिन, जुन सूर्य र चन्द्रमा बीचको कोणीय दूरीको आधारमा गणना गरिन्छ। प्रत्येक तिथिले १२ डिग्रीको चन्द्र गति प्रतिनिधित्व गर्दछ। एक चन्द्र मासमा ३० तिथिहरू हुन्छन्, जुन शुक्ल (बढ्दो) र कृष्ण (घट्दो) पक्षमा विभाजित हुन्छन्।"),
    PANCHANGA_TITHI_SIG("Determines the nature of activities suitable for the day. Some tithis like Purnima (full moon) and Amavasya (new moon) have special significance.", "दिनको लागि उपयुक्त गतिविधिहरूको प्रकृति निर्धारण गर्दछ। पूर्णिमा र औंशी जस्ता केही तिथिहरूको विशेष महत्त्व हुन्छ।"),
    PANCHANGA_VARA_DESC_LONG("The weekday, each ruled by a specific planet. The planetary ruler influences the nature and appropriate activities for that day.", "वार, प्रत्येक एक विशिष्ट ग्रहद्वारा शासित हुन्छ। ग्रह शासकले त्यस दिनको प्रकृति र उपयुक्त गतिविधिहरूलाई प्रभाव पार्छ।"),
    PANCHANGA_VARA_SIG("Each vara has specific activities that are considered favorable. For example, Sunday is good for authority matters, Monday for emotional work.", "प्रत्येक वारमा विशिष्ट गतिविधिहरू हुन्छन् जुन अनुकूल मानिन्छन्। उदाहरणका लागि, आइतबार अधिकार मामिलाहरूको लागि राम्रो हुन्छ, सोमबार भावनात्मक कार्यको लागि।"),
    PANCHANGA_NAKSHATRA_DESC_LONG("The lunar mansion where the Moon resides. There are 27 nakshatras, each spanning 13°20' of the zodiac. Each nakshatra has a ruling deity and planet.", "चन्द्रमा बस्ने नक्षत्र। त्यहाँ २७ नक्षत्रहरू छन्, प्रत्येकले राशिको १३°२०' ओगटेका छन्। प्रत्येक नक्षत्रको एक शासक देवता र ग्रह हुन्छ।"),
    PANCHANGA_NAKSHATRA_SIG("Birth nakshatra determines personality traits and compatibility. Moon's nakshatra is crucial for muhurta selection.", "जन्म नक्षत्रले व्यक्तित्व गुणहरू र अनुकूलता निर्धारण गर्दछ। मुहूर्त चयनको लागि चन्द्रमाको नक्षत्र महत्त्वपूर्ण छ।"),
    PANCHANGA_YOGA_DESC_LONG("Calculated from the combined longitudes of Sun and Moon. There are 27 yogas, each with specific qualities ranging from highly auspicious to inauspicious.", "सूर्य र चन्द्रमाको संयुक्त देशान्तरबाट गणना गरिएको। त्यहाँ २७ योगहरू छन्, प्रत्येकसँग अत्यधिक शुभ देखि अशुभ सम्मका विशिष्ट गुणहरू छन्।"),
    PANCHANGA_YOGA_SIG("Yogas indicate the general nature of results from activities undertaken. Siddha, Amrita, and Shubha yogas are highly favorable.", "योगहरूले गरिएका गतिविधिहरूको परिणामको सामान्य प्रकृति संकेत गर्दछ। सिद्ध, अमृत र शुभ योगहरू अत्यधिक अनुकूल हुन्छन्।"),
    PANCHANGA_KARANA_DESC_LONG("Half of a tithi, there are 11 karanas total. Seven are movable and four are fixed. Each karana has its own nature and suitable activities.", "तिथिको आधा भाग, कुल ११ करणहरू छन्। सात चर र चार स्थिर छन्। प्रत्येक करणको आफ्नै प्रकृति र उपयुक्त गतिविधिहरू छन्।"),
    PANCHANGA_KARANA_SIG("Karanas fine-tune the effects of tithis. Movable karanas recur throughout the month while fixed ones appear only once.", "करणहरूले तिथिका प्रभावहरूलाई सुष्म बनाउँछन्। चर करणहरू महिनाभर दोहोरिन्छन् भने स्थिर करणहरू एक पटक मात्र आउँछन्।"),
    PANCHANGA_ABOUT_TITLE("About Panchanga", "पञ्चाङ्गको बारेमा"),
    PANCHANGA_ABOUT_DESC_1("Panchanga (Sanskrit: पञ्चाङ्ग) means 'five limbs' and refers to the traditional Hindu almanac that tracks five elements of time: Tithi, Vara, Nakshatra, Yoga, and Karana.", "पञ्चाङ्ग (संस्कृत: पञ्चाङ्ग) को अर्थ 'पाँच अंग' हो र यसले समयका पाँच तत्वहरू: तिथि, वार, नक्षत्र, योग र करण ट्र्याक गर्ने परम्परागत हिन्दु पात्रोलाई जनाउँछ।"),
    PANCHANGA_ABOUT_DESC_2("These five elements together determine the auspiciousness of any moment and are crucial for selecting muhurtas (auspicious timings) for important activities.", "यी पाँच तत्वहरूले मिलेर कुनै पनि क्षणको शुभता निर्धारण गर्दछ र महत्त्वपूर्ण गतिविधिहरूको लागि मुहूर्त (शुभ समय) चयन गर्न महत्त्वपूर्ण छन्।"),
    PANCHANGA_SIGNIFICANCE("Significance", "महत्त्व"),

    // ============================================
    // BHRIGU BINDU
    // ============================================
    BHRIGU_BINDU_CALC_ERROR("Unable to calculate Bhrigu Bindu. Please check chart data.", "भृगु बिन्दु गणना गर्न असमर्थ। कृपया कुण्डली डाटा जाँच गर्नुहोस्।"),
    POSITION_INTERPRETATION("Position Interpretation", "स्थिति व्याख्या"),
    STRENGTH_FACTORS("Strength Factors", "बल कारकहरू"),
    TRANSIT_DATA_UNAVAILABLE("Transit data not available", "गोचर डाटा उपलब्ध छैन"),
    CURRENT_PLANETARY_POSITIONS("Current Planetary Positions", "वर्तमान ग्रह स्थितिहरू"),
    UPCOMING_TRANSITS("Upcoming Significant Transits", "आगामी महत्त्वपूर्ण गोचरहरू"),
    TRANSIT_TIMING("Transit Timing", "गोचर समय"),
    TRANSIT_TIMING_DESC("When slow-moving planets (Saturn, Jupiter, Rahu, Ketu) transit over your Bhrigu Bindu, significant karmic events tend to manifest.", "जब ढिलो हिड्ने ग्रहहरू (शनि, बृहस्पति, राहु, केतु) तपाइँको भृगु बिन्दु माथि गोचर गर्छन्, महत्त्वपूर्ण कार्मिक घटनाहरू प्रकट हुन्छन्।"),
    CONJUNCT("Conjunct", "युति"),
    APPLYING("Applying", "लागू हुँदै"),

    // ============================================
    // COMMON UI STRINGS
    // ============================================
    KEY_THEMES("Key Themes", "मुख्य विषयहरू"),
    EFFECTS_LABEL("Effects", "प्रभावहरू"),
    CURRENT_LABEL("Current", "वर्तमान"),
    PREVIOUS_LABEL("Previous", "अघिल्लो"),
    NEXT_LABEL("Next", "अर्को"),
    PRIMARY_LABEL("Primary", "प्राथमिक"),
    SECONDARY_LABEL("Secondary", "माध्यमिक"),
    LAGNA_LABEL("Lagna", "लग्न"),
    MOON_LABEL("Moon", "चन्द्र"),
    SUN_LABEL("Sun", "सूर्य"),
    SIGN_LABEL("Sign", "राशि"),
    HOUSE_LABEL("House", "भाव"),
    STRENGTH_LABEL("Strength", "बल"),
    RELATIONSHIP_FRIEND("Friendly", "मैत्रीपूर्ण"),
    RELATIONSHIP_ENEMY("Inimical", "शत्रुतापूर्ण"),
    RELATIONSHIP_NEUTRAL("Neutral", "तटस्थ"),
    RELATIONSHIP_SAME("Intensified", "तीव्र"),
    BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    BALANCE_LABEL("Balance at Birth", "जन्ममा सन्तुलन"),

    // ============================================
    // COMMON SCREEN STRINGS
    // ============================================
    SCREEN_CALCULATING("Calculating analysis...", "विश्लेषण गणना गर्दै..."),
    SCREEN_NO_DATA("No data available", "कुनै डाटा उपलब्ध छैन"),
    SCREEN_ERROR_CALCULATION("Error calculating results", "परिणाम गणनामा त्रुटि"),
    SCREEN_OVERVIEW("Overview", "सिंहावलोकन"),
    SCREEN_DETAILS("Details", "विवरणहरू"),
    SCREEN_TIMELINE("Timeline", "समयरेखा"),
    SCREEN_INTERPRETATION("Interpretation", "व्याख्या"),
    SCREEN_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    ERROR_CALCULATION("Calculation Error", "गणना त्रुटि"),

    // ============================================
    // UI SCREENS & EMPTY STATES
    // ============================================
    UI_NO_CHART_DATA("No Chart Data", "कुन्डली डाटा उपलब्ध छैन"),
    UI_NO_BIRTH_CHART("No Birth Chart", "कुनै जन्म कुन्डली छैन"),
    UI_SELECT_CHART("Please select a birth chart", "कृपया जन्म कुन्डली चयन गर्नुहोस्"),
    UI_ERROR_LOADING("Error loading chart", "कुन्डली लोड गर्दा त्रुटि"),
    UI_NO_ASHTAKAVARGA_DATA("No Ashtakavarga Data", "अष्टकवर्ग डाटा छैन"),
    UI_NO_ARUDHA_YOGAS("No significant Arudha Yogas found", "कुनै महत्त्वपूर्ण आरुढ योग फेला परेन"),
    UI_NO_ACTIVE_SANDHI("No Active Sandhi", "कुनै सक्रिय सन्धि छैन"),
    UI_NO_UPCOMING_SANDHI("No upcoming Sandhi periods in the analysis window.", "विश्लेषण अवधिमा कुनै आगामी सन्धि अवधि छैन।"),
    UI_NO_CALENDAR_ENTRIES("No calendar entries available.", "कुनै क्यालेन्डर प्रविष्टिहरू उपलब्ध छैनन्।"),
    UI_NO_ACTIVE_VEDHAS("No Active Vedhas", "कुनै सक्रिय वेध छैन"),
    UI_NO_PLANET_WARS("No Active Planetary Wars", "कुनै सक्रिय ग्रह युद्ध छैन"),
    UI_NO_WAR_DASHA("No War-Related Dasha Effects", "कुनै युद्ध-सम्बन्धित दशा प्रभावहरू छैन"),
    UI_NO_WAR_REMEDIES("No Specific Remedies Needed", "कुनै विशिष्ट उपाय आवश्यक छैन"),
    UI_NO_ACTIVE_WAR_REMEDIES("No active wars to remediate", "उपचार गर्न कुनै सक्रिय युद्ध छैन"),
    UI_KEMADRUMA_CONDITION_MET("No planets in houses adjacent to Moon - Kemadruma condition met", "चन्द्रमाको छेउका भावहरूमा कुनै ग्रह छैन - केमद्रुम अवस्था पूरा भयो"),
    UI_NO_REMEDIES_NEEDED("No Remedies Needed", "कुनै उपाय आवश्यक छैन"),
    UI_NO_YOGAS_FORMED("No Yogas Formed", "कुनै योग बनेको छैन"),
    UI_NO_YOGAS_DISPLAY("No Yogas to Display", "देखाउनको लागि कुनै योग छैन"),
    UI_INTERPRETATION("Interpretation", "व्याख्या"),
    UI_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    UI_OVERVIEW("Overview", "अवलोकन"),
    UI_YOGAS("Yogas", "योगहरू"),
    UI_EFFECTS("Effects", "प्रभावहरू"),
    UI_TIMING("Timing", "समय"),
    UI_REMEDIES("Remedies", "उपायहरू"),
    UI_TRANSITS("Transits", "गोचरहरू"),
    UI_CURRENT("Current", "वर्तमान"),
    UI_UPCOMING("Upcoming", "आगामी"),
    UI_CALENDAR("Calendar", "पात्रो"),
    UI_KEY_INSIGHTS("Key Insights", "मुख्य अन्तरदृष्टिहरू"),
    UI_START("Start:", "सुरु:"),
    UI_END("End:", "अन्त्य:"),
    BTN_GOT_IT("Got it", "बुझें"),
;
}
