package com.astro.storm.core.common

enum class StringKeyTransitPart1(override val en: String, override val ne: String) : StringKeyInterface {
    GOCHARA_ABOUT_DESC("Gochara refers to planetary transits, while Vedha means \"obstruction\" in Sanskrit.\n\nWhen a planet transits through a favorable house from your natal Moon, its positive effects can be blocked (Vedha) by another planet positioned in specific houses.\n\nKey concepts:\n• Each house has specific Vedha points\n• Benefic transits can be nullified by malefic planets\n• The severity of Vedha varies based on planetary combinations\n• Understanding Vedha helps predict when good transits may not deliver expected results\n\nThis analysis helps you identify periods when planetary energies are blocked and plan accordingly.", "गोचर भन्नाले ग्रहहरूको वर्तमान चाललाई जनाउँछ, जबकि वेधको अर्थ संस्कृतमा \"अवरोध\" हो।\n\nजब कुनै ग्रह तपाईंको जन्म चन्द्रमाबाट शुभ भावमा गोचर गर्छ, यसको सकारात्मक प्रभावहरू विशिष्ट भावहरूमा रहेका अन्य ग्रहहरूद्वारा अवरोधित (वेध) हुन सक्छन्।\n\nमुख्य अवधारणाहरू:\n• प्रत्येक भावका विशिष्ट वेध बिन्दुहरू हुन्छन्\n• शुभ गोचरहरू पाप ग्रहहरूद्वारा निष्फल हुन सक्छन्\n• वेधको गम्भीरता ग्रह संयोजनहरूमा आधारित हुन्छ\n• वेध बुझ्नाले राम्रो गोचरले कहिले अपेक्षित नतिजा नदिन सक्छ भनी अनुमान गर्न मद्दत गर्छ\n\nयो विश्लेषणले तपाईंलाई ग्रह उर्जाहरू कहिले अवरोधित हुन्छन् भनी पहिचान गर्न र सोही अनुसार योजना बनाउन मद्दत गर्छ।"),
    GOCHARA_ABOUT_TITLE("About Gochara Vedha", "गोचर वेधको बारेमा"),
    GOCHARA_ACTIVE_VEDHAS("Active Vedhas", "सक्रिय वेध"),
    GOCHARA_CURRENT_TRANSITS("Current Planetary Transits", "वर्तमान ग्रह गोचरहरू"),
    GOCHARA_EFFECT_CHALLENGING("%1\$s transit in %2\$dth house may challenge %3\$s.%4\$s", "%2\$dऔं भावमा %1\$s गोचरले %3\$s लाई चुनौती दिन सक्छ।%4\$s"),
    GOCHARA_EFFECT_DIFFICULT("%1\$s transit in %2\$dth house requires caution in %3\$s.%4\$s", "%2\$dऔं भावमा %1\$s गोचरले %3\$s मा सावधानी आवश्यक छ।%4\$s"),
    GOCHARA_EFFECT_EXCELLENT("%1\$s transit in %2\$dth house brings excellent results for %3\$s.%4\$s", "%2\$dऔं भावमा %1\$s गोचरले %3\$s को लागि उत्कृष्ट परिणाम ल्याउँछ।%4\$s"),
    GOCHARA_EFFECT_GOOD("%1\$s transit in %2\$dth house supports %3\$s.%4\$s", "%2\$dऔं भावमा %1\$s गोचरले %3\$s लाई सहयोग गर्छ।%4\$s"),
    GOCHARA_EFFECT_NEUTRAL("%1\$s transit in %2\$dth house has neutral effects on %3\$s.%4\$s", "%2\$dऔं भावमा %1\$s गोचरले %3\$s मा तटस्थ प्रभाव पार्छ।%4\$s"),
    GOCHARA_FAVORABLE("Favorable", "शुभ"),
    GOCHARA_FORECAST("Forecast", "पूर्वानुमान"),
    GOCHARA_FROM("From:", "बाट:"),
    GOCHARA_JUPITER_1("Weight gain. Overconfidence. Health issues.", "तौल बढ्ने। अत्यधिक आत्मविश्वास। स्वास्थ्य समस्या।"),
    GOCHARA_JUPITER_10("Professional setbacks. Reputation challenges.", "व्यावसायिक अवरोध। प्रतिष्ठामा चुनौती।"),
    GOCHARA_JUPITER_11("Major gains. Fulfillment of desires. Eldest sibling's success.", "प्रमुख लाभ। इच्छाहरूको पूर्ति। जेठो भाइबहिनीको सफलता।"),
    GOCHARA_JUPITER_12("Expenses. Foreign troubles. Spiritual doubts.", "खर्च। विदेशी समस्या। आध्यात्मिक शङ्का।"),
    GOCHARA_JUPITER_2("Wealth increases. Family harmony. Sweet speech. Good food.", "धन बढ्छ। पारिवारिक सद्भाव। मधुर वाणी। राम्रो भोजन।"),
    GOCHARA_JUPITER_3("Reduced courage. Sibling issues.", "साहस घट्ने। भाइबहिनीका समस्या।"),
    GOCHARA_JUPITER_4("Domestic expansion issues. Property disputes.", "घरेलु विस्तारमा समस्या। सम्पत्ति विवाद।"),
    GOCHARA_JUPITER_5("Intelligence flourishes. Good for children. Romance. Creativity.", "बुद्धि फस्टाउँछ। सन्तानका लागि राम्रो। रोमान्स। सिर्जनशीलता।"),
    GOCHARA_JUPITER_6("Debts may increase. Enemy problems.", "ऋण बढ्न सक्छ। शत्रुको समस्या।"),
    GOCHARA_JUPITER_7("Partnership success. Marriage prospects. Business partnerships.", "साझेदारीमा सफलता। विवाहको सम्भावना। व्यापारिक साझेदारी।"),
    GOCHARA_JUPITER_8("Unexpected expenses. Health vulnerabilities.", "अप्रत्याशित खर्च। स्वास्थ्य कमजोरी।"),
    GOCHARA_JUPITER_9("Spiritual growth. Luck and fortune. Father's blessings. Pilgrimage.", "आध्यात्मिक वृद्धि। भाग्य र किस्मत। पिताको आशीर्वाद। तीर्थयात्रा।"),
    GOCHARA_KETU_1("Health vulnerabilities. Lack of direction.", "स्वास्थ्य कमजोरी। दिशाहीनता।"),
    GOCHARA_KETU_10("Career confusion. Direction loss.", "करियरमा भ्रम। लक्ष्य हराउनु।"),
    GOCHARA_KETU_11("Gains through spiritual pursuits. Liberation from desires.", "आध्यात्मिक खोजीबाट लाभ। इच्छाहरूबाट मुक्ति।"),
    GOCHARA_KETU_12("Expenses. Spiritual confusion. Isolation.", "खर्च। आध्यात्मिक भ्रम। एक्लोपन।"),
    GOCHARA_KETU_2("Financial losses. Family separation.", "वित्तीय घाटा। परिवारबाट अलगाव।"),
    GOCHARA_KETU_3("Spiritual courage. Success in research.", "आध्यात्मिक साहस। अनुसन्धानमा सफलता।"),
    GOCHARA_KETU_4("Domestic detachment. Property losses.", "घरेलु विरक्ति। सम्पत्ति घाटा।"),
    GOCHARA_KETU_5("Children's issues. Poor decisions.", "सन्तानका समस्या। गलत निर्णय।"),
    GOCHARA_KETU_6("Healing abilities increase. Victory through spiritual means.", "उपचार क्षमता बढ्छ। आध्यात्मिक माध्यमबाट विजय।"),
    GOCHARA_KETU_7("Relationship detachment. Partnership dissolution.", "सम्बन्धमा विरक्ति। साझेदारी विच्छेद।"),
    GOCHARA_KETU_8("Sudden health issues. Accidents. Hidden problems.", "अचानक स्वास्थ्य समस्या। दुर्घटना। लुकेका समस्या।"),
    GOCHARA_KETU_9("Spiritual insights. Pilgrimage. Blessings from teachers.", "आध्यात्मिक अन्तर्दृष्टि। तीर्थयात्रा। गुरुहरूबाट आशीर्वाद।"),
    GOCHARA_MARS_1("Impulsive actions. Accidents. Health issues. Anger.", "आवेगपूर्ण कार्यहरू। दुर्घटना। स्वास्थ्य समस्या। क्रोध।"),
    GOCHARA_MARS_10("Professional conflicts. Authority issues.", "व्यावसायिक द्वन्द्व। अधिकारका समस्याहरू।"),
    GOCHARA_MARS_11("Financial gains through effort. Achievement of goals. Success in ventures.", "प्रयासबाट वित्तीय लाभ। लक्ष्य प्राप्ति। उद्यमहरूमा सफलता।"),
    GOCHARA_MARS_12("Hidden enemies. Expenses. Hospitalization risk.", "लुकेका शत्रुहरू। खर्च। अस्पताल भर्ना हुने जोखिम।"),
    GOCHARA_MARS_2("Financial losses through haste. Family arguments.", "हतारका कारण वित्तीय घाटा। पारिवारिक बहस।"),
    GOCHARA_MARS_3("Courage and determination. Victory in competitions. Energy for initiatives.", "साहस र दृढ संकल्प। प्रतियोगिताहरूमा विजय। पहलका लागि ऊर्जा।"),
    GOCHARA_MARS_4("Domestic conflicts. Property disputes. Mother's health.", "घरेलु द्वन्द्व। सम्पत्ति विवाद। आमाको स्वास्थ्य।"),
    GOCHARA_MARS_5("Children's issues. Poor decisions. Speculation loss.", "सन्तानका समस्याहरू। गलत निर्णय। सट्टाबाजीमा घाटा।"),
    GOCHARA_MARS_6("Defeat of enemies. Success through effort. Good for legal matters.", "शत्रुहरूको पराजय। प्रयासबाट सफलता। कानूनी मामिलाका लागि राम्रो।"),
    GOCHARA_MARS_7("Relationship conflicts. Partnership disputes.", "सम्बन्धमा द्वन्द्व। साझेदारीमा विवाद।"),
    GOCHARA_MARS_8("Accidents. Surgeries. Hidden enemies active.", "दुर्घटना। शल्यक्रिया। लुकेका शत्रुहरू सक्रिय।"),
    GOCHARA_MARS_9("Conflicts with teachers. Father's health.", "गुरुहरूसँग द्वन्द्व। पिताको स्वास्थ्य।"),
    GOCHARA_MATTERS_1("self, health, personality", "स्वयं, स्वास्थ्य, व्यक्तित्व"),
    GOCHARA_MATTERS_10("career, status, government", "करियर, प्रतिष्ठा, सरकार"),
    GOCHARA_MATTERS_11("gains, friends, elder siblings", "लाभ, साथीहरू, ठूला भाइबहिनी"),
    GOCHARA_MATTERS_12("expenses, spirituality, foreign", "खर्च, आध्यात्मिकता, विदेश"),
    GOCHARA_MATTERS_2("wealth, family, speech", "धन, परिवार, वाणी"),
    GOCHARA_MATTERS_3("courage, siblings, short journeys", "साहस, भाइबहिनी, छोटो यात्रा"),
    GOCHARA_MATTERS_4("home, mother, mental peace", "घर, आमा, मानसिक शान्ति"),
    GOCHARA_MATTERS_5("children, creativity, romance", "सन्तान, सिर्जनशीलता, रोमान्स"),
    GOCHARA_MATTERS_6("enemies, health issues, debts", "शत्रु, स्वास्थ्य समस्या, ऋण"),
    GOCHARA_MATTERS_7("marriage, partnerships, business", "विवाह, साझेदारी, व्यापार"),
    GOCHARA_MATTERS_8("obstacles, longevity, occult", "बाधाहरू, दीर्घायु, तन्त्रमन्त्र"),
    GOCHARA_MATTERS_9("fortune, father, religion", "भाग्य, पिता, धर्म"),
    GOCHARA_MATTERS_GENERAL("general matters", "सामान्य मामिलाहरू"),
    GOCHARA_MERCURY_1("Nervous tension. Skin issues. Restless mind.", "स्नायु तनाव। छालाको समस्या। अशान्त मन।"),
    GOCHARA_MERCURY_10("Professional success. Recognition for intelligence. Business growth.", "व्यावसायिक सफलता। बुद्धिका लागि मान्यता। व्यापार वृद्धि।"),
    GOCHARA_MERCURY_11("Financial gains through communication. Network expansion.", "सञ्चारबाट वित्तीय लाभ। नेटवर्क विस्तार।"),
    GOCHARA_MERCURY_12("Mental anxieties. Hidden worries. Poor sleep.", "मानसिक चिन्ता। लुकेका पीरहरू। कम निद्रा।"),
    GOCHARA_MERCURY_2("Gains through speech and intellect. Family harmony. Financial gains.", "वाणी र बुद्धिबाट लाभ। पारिवारिक सद्भाव। वित्तीय लाभ।"),
    GOCHARA_MERCURY_3("Communication problems. Sibling issues. Short trips troubled.", "सञ्चार समस्या। भाइबहिनीका समस्या। छोटो यात्राहरूमा समस्या।"),
    GOCHARA_MERCURY_4("Domestic happiness. Property matters favorable. Mental peace.", "घरेलु खुसी। सम्पत्ति मामिलाहरू अनुकूल। मानसिक शान्ति।"),
    GOCHARA_MERCURY_5("Poor decisions. Learning difficulties.", "गलत निर्णय। सिकाइमा कठिनाइ।"),
    GOCHARA_MERCURY_6("Victory over competitors. Success in studies. Sharp intellect.", "प्रतिस्पर्धीहरूमाथि विजय। अध्ययनमा सफलता। तीक्ष्ण बुद्धि।"),
    GOCHARA_MERCURY_7("Partnership misunderstandings. Contract issues.", "साझेदारीमा गलतफहमी। सम्झौता समस्याहरू।"),
    GOCHARA_MERCURY_8("Gains through research. Understanding occult matters.", "अनुसन्धानबाट लाभ। तन्त्रमन्त्रका कुराहरू बुझ्ने।"),
    GOCHARA_MERCURY_9("Educational obstacles. Communication with father strained.", "शैक्षिक अवरोध। पितासँगको सञ्चारमा तनाव।"),
    GOCHARA_MOON_1("Mental peace and satisfaction. Good health and comforts.", "मानसिक शान्ति र सन्तुष्टि। राम्रो स्वास्थ्य र सुविधाहरू।"),
    GOCHARA_MOON_10("Success in profession. Recognition from superiors.", "पेशामा सफलता। उच्च अधिकारीहरूबाट मान्यता।"),
    GOCHARA_MOON_11("Financial gains. Fulfillment of desires. Social success.", "वित्तीय लाभ। इच्छाहरूको पूर्ति। सामाजिक सफलता।"),
    GOCHARA_MOON_12("Sleep issues. Expenses. Emotional withdrawal.", "निद्राको समस्या। खर्च। भावनात्मक विरक्ति।"),
    GOCHARA_MOON_2("Financial fluctuations. Emotional eating issues.", "वित्तीय उतार-चढाव। भावनात्मक खानपानको समस्या।"),
    GOCHARA_MOON_3("Courage increases. Success in short journeys. Good relations with siblings.", "साहस बढ्छ। छोटो यात्रामा सफलता। भाइबहिनीसँग राम्रो सम्बन्ध।"),
    GOCHARA_MOON_4("Mental restlessness. Domestic worries.", "मानसिक अशान्ति। घरेलु चिन्ताहरू।"),
    GOCHARA_MOON_5("Emotional challenges with children. Poor speculation.", "सन्तानसँग भावनात्मक चुनौतीहरू। गलत सट्टाबाजी।"),
    GOCHARA_MOON_6("Victory over enemies. Relief from debts and diseases.", "शत्रुमाथि विजय। ऋण र रोगबाट राहत।"),
    GOCHARA_MOON_7("Pleasure through spouse. Partnership gains. Social happiness.", "जीवनसाथीबाट सुख। साझेदारीमा लाभ। सामाजिक खुसी।"),
    GOCHARA_MOON_8("Emotional turmoil. Hidden anxieties. Health vulnerabilities.", "भावनात्मक हलचल। लुकेका चिन्ताहरू। स्वास्थ्य कमजोरी।"),
    GOCHARA_MOON_9("Spiritual doubts. Emotional distance from teachers.", "आध्यात्मिक शङ्काहरू। गुरुहरूबाट भावनात्मक दूरी।"),
    GOCHARA_MOON_SIGN("Natal Moon Sign", "जन्म राशी"),
    GOCHARA_NATURALLY_FAVORABLE("Naturally Favorable", "स्वाभाविक रूपमा शुभ"),
    GOCHARA_NATURALLY_UNFAVORABLE("Naturally Unfavorable", "स्वाभाविक रूपमा अशुभ"),
    GOCHARA_NO_CHART_DESC("Create or select a birth chart to analyze Gochara Vedha effects.", "गोचर वेध प्रभावहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    GOCHARA_OBSTRUCTED("Obstructed", "अवरोधित"),
    GOCHARA_RAHU_1("Confusion. Wrong decisions. Health anxieties.", "भ्रम। गलत निर्णय। स्वास्थ्य चिन्ता।"),
    GOCHARA_RAHU_10("Sudden rise in career. Foreign opportunities.", "करियरमा अचानक उदय। विदेशी अवसरहरू।"),
    GOCHARA_RAHU_11("Unexpected gains. Fulfillment of unusual desires.", "अप्रत्याशित लाभ। असामान्य इच्छाहरूको पूर्ति।"),
    GOCHARA_RAHU_12("Hidden enemies. Expenses. Foreign troubles.", "लुकेका शत्रुहरू। खर्च। विदेशी समस्या।"),
    GOCHARA_RAHU_2("Financial deception. Family disharmony.", "वित्तीय छलकपट। पारिवारिक मनमुटाव।"),
    GOCHARA_RAHU_3("Courage for unconventional paths. Success through innovation.", "अपरम्परागत मार्गका लागि साहस। नवप्रवर्तन मार्फत सफलता।"),
    GOCHARA_RAHU_4("Mental confusion. Domestic issues.", "मानसिक भ्रम। घरेलु समस्या।"),
    GOCHARA_RAHU_5("Children's concerns. Poor speculation.", "सन्तानको चिन्ता। गलत सट्टाबाजी।"),
    GOCHARA_RAHU_6("Victory over hidden enemies. Overcoming obstacles.", "लुकेका शत्रुहरूमाथि विजय। बाधाहरू पार गर्ने।"),
    GOCHARA_RAHU_7("Relationship deceptions. Partnership frauds.", "सम्बन्धमा छलकपट। साझेदारीमा धोखाधडी।"),
    GOCHARA_RAHU_8("Sudden problems. Hidden enemies. Health scares.", "अचानक समस्याहरू। लुकेका शत्रुहरू। स्वास्थ्य डर।"),
    GOCHARA_RAHU_9("Spiritual confusion. Issues with teachers.", "आध्यात्मिक भ्रम। गुरुहरूसँगको समस्या।"),
    GOCHARA_SATURN_1("Health issues. Depression. Physical weakness.", "स्वास्थ्य समस्या। डिप्रेसन। शारीरिक कमजोरी।"),
    GOCHARA_SATURN_10("Career setbacks. Authority conflicts. Reputation damage.", "करियरमा अवरोध। अधिकारसँग द्वन्द्व। प्रतिष्ठामा क्षति।"),
    GOCHARA_SATURN_11("Long-term gains materialize. Slow but steady prosperity.", "दीर्घकालीन लाभहरू प्राप्त हुन्छन्। ढिलो तर स्थिर समृद्धि।"),
    GOCHARA_SATURN_12("Isolation. Expenses. Sleep issues. Foreign troubles.", "एक्लोपन। खर्च। निद्राको समस्या। विदेशी समस्या।"),
    GOCHARA_SATURN_2("Financial constraints. Family separation. Speech issues.", "वित्तीय अवरोध। परिवारबाट अलगाव। वाणीमा समस्या।"),
    GOCHARA_SATURN_3("Perseverance pays off. Courage through discipline. Victory through patience.", "दृढताले फल दिन्छ। अनुशासन मार्फत साहस। धैर्य मार्फत विजय।"),
    GOCHARA_SATURN_4("Domestic stress. Mother's health. Property issues.", "घरेलु तनाव। आमाको स्वास्थ्य। सम्पत्ति समस्या।"),
    GOCHARA_SATURN_5("Children's problems. Poor decisions. Mental worry.", "सन्तानका समस्या। गलत निर्णय। मानसिक चिन्ता।"),
    GOCHARA_SATURN_6("Victory over enemies through persistence. Health through discipline.", "दृढता मार्फत शत्रुहरूमाथि विजय। अनुशासन मार्फत स्वास्थ्य।"),
    GOCHARA_SATURN_7("Relationship strain. Partnership challenges. Delays in marriage.", "सम्बन्धमा तनाव। साझेदारीमा चुनौती। विवाहमा ढिलाइ।"),
    GOCHARA_SATURN_8("Chronic health issues. Hidden problems. Accidents.", "दीर्घकालीन स्वास्थ्य समस्या। लुकेका समस्या। दुर्घटना।"),
    GOCHARA_SATURN_9("Father's troubles. Spiritual obstacles. Bad luck phase.", "पिताका समस्याहरू। आध्यात्मिक अवरोध। दुर्भाग्यपूर्ण चरण।"),
    GOCHARA_SCORE("Overall Transit Score", "समग्र गोचर अङ्क"),
    GOCHARA_SCREEN_TITLE("Gochara Vedha", "गोचर वेध"),
    GOCHARA_SEVERITY("Severity:", "गम्भीरता:"),
    GOCHARA_SUBTITLE("Transit Obstructions", "गोचर अवरोधहरू"),
    GOCHARA_SUN_1("Health issues. Ego challenges. Conflicts with authority.", "स्वास्थ्य समस्याहरू। अहंकारका चुनौतीहरू। अधिकारसँग द्वन्द्व।"),
    GOCHARA_SUN_10("Professional success and recognition. Authority increases.", "व्यावसायिक सफलता र मान्यता। अधिकार बढ्छ।"),
    GOCHARA_SUN_11("Gains of wealth. Fulfillment of desires. Success in endeavors.", "धन लाभ। इच्छाहरूको पूर्ति। प्रयासहरूमा सफलता।"),
    GOCHARA_SUN_12("Expenses increase. Sleep disturbances. Hidden losses.", "खर्च बढ्छ। निद्रामा गडबडी। लुकेका घाटा।"),
    GOCHARA_SUN_2("Financial difficulties. Family disputes. Speech issues.", "वित्तीय कठिनाइहरू। पारिवारिक विवाद। वाणीमा समस्या।"),
    GOCHARA_SUN_3("Courage and valor increase. Victory over rivals.", "साहस र पराक्रम बढ्छ। प्रतिद्वन्द्वीहरूमाथि विजय।"),
    GOCHARA_SUN_4("Domestic unrest. Mental worry. Vehicle problems.", "घरेलु अशान्ति। मानसिक चिन्ता। सवारी साधनमा समस्या।"),
    GOCHARA_SUN_5("Obstacles to children. Poor decisions. Speculation loss.", "सन्तानमा अवरोध। गलत निर्णयहरू। सट्टाबाजीमा घाटा।"),
    GOCHARA_SUN_6("Destruction of enemies. Health improves. Debts decrease.", "शत्रुहरूको विनाश। स्वास्थ्यमा सुधार। ऋण घट्छ।"),
    GOCHARA_SUN_7("Relationship strain. Partnership challenges.", "सम्बन्धमा तनाव। साझेदारीमा चुनौतीहरू।"),
    GOCHARA_SUN_8("Health concerns. Unexpected problems. Hidden enemies.", "स्वास्थ्य चिन्ताहरू। अप्रत्याशित समस्याहरू। लुकेका शत्रुहरू।"),
    GOCHARA_SUN_9("Obstacles in luck. Difficulties with father/teacher.", "भाग्यमा बाधा। पिता/गुरुसँग कठिनाइहरू।"),
    GOCHARA_TRANSITS_TRACKED("Transits Tracked", "ट्र्याक गरिएका गोचरहरू"),
    GOCHARA_TRANSIT_EFFECTS("Transit Effects", "गोचर प्रभावहरू"),
    GOCHARA_VEDHAS("Vedhas", "वेधहरू"),
    GOCHARA_VEDHA_LABEL("VEDHA", "वेध"),
    GOCHARA_VEDHA_NOTE(" Effects may be diminished due to Vedha.", " वेधको कारण प्रभावहरू कम हुन सक्छ।"),
    GOCHARA_VEDHA_OBSTRUCTION("Vedha Obstruction", "वेध अवरोध"),
    GOCHARA_VENUS_1("Personal charm increases. Attraction and luxury. Good health.", "व्यक्तिगत आकर्षण बढ्छ। आकर्षण र विलासिता। राम्रो स्वास्थ्य।"),
    GOCHARA_VENUS_11("Major gains through arts/finance. Social success.", "कला/वित्तबाट प्रमुख लाभ। सामाजिक सफलता।"),
    GOCHARA_VENUS_12("Pleasures of bed. Foreign connections favorable.", "शय्या सुख। विदेशी सम्बन्धहरू अनुकूल।"),
    GOCHARA_VENUS_2("Wealth and family happiness. Good food and comforts.", "धन र पारिवारिक खुसी। राम्रो भोजन र सुविधाहरू।"),
    GOCHARA_VENUS_3("Artistic talents shine. Harmonious relations with siblings.", "कलात्मक प्रतिभा चम्किन्छ। भाइबहिनीसँग सामञ्जस्यपूर्ण सम्बन्ध।"),
    GOCHARA_VENUS_4("Domestic bliss. Vehicle and property gains. Mother's blessings.", "घरेलु आनन्द। सवारी साधन र सम्पत्ति लाभ। आमाको आशीर्वाद।"),
    GOCHARA_VENUS_5("Romance and creativity. Pleasure through children. Entertainment.", "रोमान्स र सिर्जनशीलता। सन्तानबाट सुख। मनोरञ्जन।"),
    GOCHARA_VENUS_8("Unexpected gains. Inheritance matters favorable.", "अप्रत्याशित लाभ। पैतृक सम्पत्ति मामिलाहरू अनुकूल।"),
    GOCHARA_VENUS_9("Fortune through relationships. Spiritual partnerships.", "सम्बन्धबाट भाग्य। आध्यात्मिक साझेदारी।"),
    KAKSHYA_BINDU_STATUS("Bindu Status", "बिन्दु स्थिति"),
    KAKSHYA_CRITICAL_TRANSITS("Critical Kakshya Transits", "गम्भीर कक्ष्या गोचरहरू"),
    KAKSHYA_CURRENT_POSITION("Current Kakshya Position", "वर्तमान कक्ष्या स्थिति"),
    KAKSHYA_DEGREE_RANGE("Degree Range", "डिग्री दायरा"),
    KAKSHYA_DESC("Precise micro-transit timing using 8 divisions per sign (3°45' each)", "प्रत्येक राशिमा ८ विभाजन (३°४५' प्रत्येक) प्रयोग गरी सूक्ष्म गोचर समय"),
    KAKSHYA_DURATION("Duration", "अवधि"),
    KAKSHYA_ENTRY_TIME("Entry Time", "प्रवेश समय"),
    KAKSHYA_EXCELLENT("Excellent", "उत्कृष्ट"),
    KAKSHYA_EXIT_TIME("Exit Time", "निकास समय"),
    KAKSHYA_FAVORABLE_PERIODS("Favorable Kakshya Periods", "अनुकूल कक्ष्या अवधिहरू"),
    KAKSHYA_GOOD("Good", "राम्रो"),
    KAKSHYA_HAS_BINDU("Has Bindu ✓", "बिन्दु छ ✓"),
    KAKSHYA_INFO_DESC("Kakshya divides each sign into 8 parts of 3°45' each, ruled by Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon, and Lagna. Combined with Ashtakavarga, it provides precise timing for transit effects.", "कक्ष्याले प्रत्येक राशिलाई ३°४५' को ८ भागमा विभाजन गर्छ, जुन शनि, गुरु, मंगल, सूर्य, शुक्र, बुध, चन्द्र, र लग्नले शासन गर्छन्। अष्टकवर्गसँग मिलाएर, यसले गोचर प्रभावको सटीक समय प्रदान गर्छ।"),
    KAKSHYA_INFO_TITLE("About Kakshya System", "कक्ष्या प्रणालीको बारेमा"),
    KAKSHYA_LORD("Kakshya Lord", "कक्ष्या स्वामी"),
    KAKSHYA_LORD_JUPITER("Jupiter Kakshya", "गुरु कक्ष्या"),
    KAKSHYA_LORD_LAGNA("Lagna Kakshya", "लग्न कक्ष्या"),
    KAKSHYA_LORD_MARS("Mars Kakshya", "मंगल कक्ष्या"),
    KAKSHYA_LORD_MERCURY("Mercury Kakshya", "बुध कक्ष्या"),
    KAKSHYA_LORD_MOON("Moon Kakshya", "चन्द्र कक्ष्या"),
    KAKSHYA_LORD_SATURN("Saturn Kakshya", "शनि कक्ष्या"),
    KAKSHYA_LORD_SUN("Sun Kakshya", "सूर्य कक्ष्या"),
    KAKSHYA_LORD_VENUS("Venus Kakshya", "शुक्र कक्ष्या"),
    KAKSHYA_MODERATE("Moderate", "मध्यम"),
    KAKSHYA_NEXT("Next Kakshya", "अर्को कक्ष्या"),
    KAKSHYA_NEXT_CHANGE("Next Kakshya Change", "अर्को कक्ष्या परिवर्तन"),
    KAKSHYA_NO_BINDU("No Bindu ✗", "बिन्दु छैन ✗"),
    KAKSHYA_NO_CHANGES("No upcoming changes in next 7 days", "आगामी ७ दिनमा कुनै परिवर्तन छैन"),
    KAKSHYA_NO_FAVORABLE("No favorable micro-transits found for the next 30 days", "अर्को ३० दिनको लागि कुनै अनुकूल सूक्ष्म-गोचर भेटिएन"),
    KAKSHYA_OVERALL_QUALITY("Overall Quality", "समग्र गुणस्तर"),
    KAKSHYA_PLANET_POSITIONS("Planet Positions", "ग्रहहरूको स्थिति"),
    KAKSHYA_POOR("Poor", "कमजोर"),
    KAKSHYA_QUALITY_EXCELLENT("Excellent", "अत्युत्तम"),
    KAKSHYA_QUALITY_GOOD("Good", "राम्रो"),
    KAKSHYA_QUALITY_MODERATE("Moderate", "मध्यम"),
    KAKSHYA_QUALITY_POOR("Poor", "कमजोर"),
    KAKSHYA_RULER("Kakshya Ruler", "कक्ष्या स्वामी"),
    KAKSHYA_SELECT_PLANET("Select a planet to see details", "विवरण हेर्न ग्रह छान्नुहोस्"),
    KAKSHYA_SIGN("Sign", "राशि"),
    KAKSHYA_SUBTITLE("High-precision micro-transit timing", "उच्च-सटीक सूक्ष्म-गोचर समय"),
    KAKSHYA_TAB_CURRENT("Current", "वर्तमान"),
    KAKSHYA_TAB_FAVORABLE("Favorable", "अनुकूल"),
    KAKSHYA_TAB_PLANETS("Planets", "ग्रहहरू"),
    KAKSHYA_TAB_TIMELINE("Timeline", "समयरेखा"),
    KAKSHYA_TITLE("Kakshya Transit", "कक्ष्या गोचर"),
    KAKSHYA_TRANSIT_QUALITY("Transit Quality", "गोचर गुणस्तर"),
    KAKSHYA_UNABLE_CALCULATE("Unable to calculate Kakshya transits", "कक्ष्या गोचर गणना गर्न सकिएन"),
    KAKSHYA_UPCOMING_CHANGES("Next Kakshya Changes", "आगामी कक्ष्या परिवर्तनहरू"),
    KAKSHYA_UPCOMING_FAVORABLE("Upcoming Favorable Periods", "आगामी अनुकूल अवधिहरू"),
    KAKSHYA_VEDIC_REF("Vedic Reference: BPHS Ashtakavarga chapters, Jataka Parijata", "वैदिक सन्दर्भ: बृहत् पाराशर होरा शास्त्र अष्टकवर्ग अध्यायहरू, जातक पारिजात"),
    TRANSITION_ENEMY_ENEMY("Enemy to Enemy", "शत्रुबाट शत्रुमा"),
    TRANSITION_ENEMY_FRIEND("Enemy to Friend", "शत्रुबाट मित्रमा"),
    TRANSITION_ENEMY_NEUTRAL("Enemy to Neutral", "शत्रुबाट तटस्थमा"),
    TRANSITION_FRIEND_ENEMY("Friend to Enemy", "मित्रबाट शत्रुमा"),
    TRANSITION_FRIEND_FRIEND("Friend to Friend", "मित्रबाट मित्रमा"),
    TRANSITION_FRIEND_NEUTRAL("Friend to Neutral", "मित्रबाट तटस्थमा"),
    TRANSITION_NEUTRAL_ENEMY("Neutral to Enemy", "तटस्थबाट शत्रुमा"),
    TRANSITION_NEUTRAL_FRIEND("Neutral to Friend", "तटस्थबाट मित्रमा"),
    TRANSITION_NEUTRAL_NEUTRAL("Neutral to Neutral", "तटस्थबाट तटस्थमा"),
    TRANSITS_CURRENT("Current Transits", "हालका गोचरहरू"),
    TRANSITS_MOON_IN("Moon in %s", "चन्द्रमा %s मा"),
    TRANSIT_ANALYSIS_NOT_AVAILABLE("Transit analysis not available for this planet.", "यस ग्रहको लागि गोचर विश्लेषण उपलब्ध छैन।"),
    TRANSIT_APPLYING("Applying", "समीप आउँदै"),
    TRANSIT_ASPECTS("Aspects", "दृष्टिहरू"),
    TRANSIT_ASPECTS_TO_NATAL("Transit Aspects to Natal", "जन्म कुण्डलीमा गोचर दृष्टि"),
    TRANSIT_AVERAGE_TEMPLATE("Transit through %s (%d BAV, %d SAV) brings mixed results. Some progress in %s with occasional challenges. Balance needed in %s.", "%s मा (%d BAV, %d SAV) गोचरले मिश्रित परिणामहरू ल्याउँछ। %s मा केही प्रगति तर कहिलेकाहीँ चुनौतीहरू। %s मा सन्तुलन आवश्यक।"),
    TRANSIT_AWARENESS("Maintain awareness but avoid excessive worry", "सजग रहनुहोस् तर धेरै चिन्ता नगर्नुहोस्"),
    TRANSIT_BELOW_AVG_TEMPLATE("Transit through %s (%d BAV, %d SAV) suggests caution needed. %s matters may face delays. Extra effort required in %s areas.", "%s मा (%d BAV, %d SAV) गोचरले सावधानी आवश्यक देखाउँछ। %s मामिलाहरूमा ढिलाइ हुन सक्छ। %s क्षेत्रमा थप प्रयास आवश्यक।"),
    TRANSIT_CAUTION("Be extra cautious during this transit period", "यस गोचर अवधिमा विशेष सावधान रहनुहोस्"),
    TRANSIT_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    TRANSIT_CHALLENGING_TEMPLATE("Challenging transit through %s with only %d BAV and %d SAV bindus. Difficulties possible in %s. Patience needed for %s matters.", "%s मा केवल %d BAV र %d SAV बिन्दुसँगको चुनौतीपूर्ण गोचर। %s मा कठिनाइहरू सम्भव। %s मामिलाहरूमा धैर्य आवश्यक।"),
    TRANSIT_COLLAPSE("Collapse", "संक्षिप्त"),
    TRANSIT_CURRENT_INFLUENCES("Current influences on your chart", "तपाईंको कुण्डलीमा हालको प्रभावहरू"),
    TRANSIT_CURRENT_MOVEMENTS("Current movements in %s", "%s मा हालको गति"),
    TRANSIT_CURRENT_POSITIONS("Current Planetary Positions", "हालको ग्रह स्थितिहरू"),
    TRANSIT_DATA_UNAVAILABLE("Transit data not available", "गोचर डाटा उपलब्ध छैन"),
    TRANSIT_DIFFICULT_TEMPLATE("Difficult transit period through %s (%d BAV, %d SAV). Significant challenges in %s areas. Careful handling of %s required.", "%s मा (%d BAV, %d SAV) कठिन गोचर अवधि। %s क्षेत्रमा महत्त्वपूर्ण चुनौतीहरू। %s को सावधानीपूर्वक व्यवस्थापन आवश्यक।"),
    TRANSIT_DURATION("Transit Duration", "गोचर अवधि"),
    TRANSIT_EFFECT("Transit Effect", "गोचर प्रभाव"),
    TRANSIT_EFFECT_TEMPLATE("%s is transiting your %s house, influencing %s matters.",
        "%s तपाईंको %s भावमा गोचर गर्दैछ, %s मामिलाहरूलाई प्रभावित गर्दै।"),
    TRANSIT_EXCELLENT("Excellent", "उत्कृष्ट"),
    TRANSIT_EXCELLENT_TEMPLATE("Transit through %s with %d BAV bindus and %d SAV bindus indicates excellent results. Matters related to %s will flourish. Areas of %s receive strong positive influence.", "%s मा %d BAV बिन्दु र %d SAV बिन्दुसँगको गोचरले उत्कृष्ट परिणाम देखाउँछ। %s सम्बन्धी मामिलाहरू फस्टाउनेछन्। %s को क्षेत्रमा बलियो सकारात्मक प्रभाव पर्नेछ।"),
    TRANSIT_EXPAND("Expand", "विस्तार"),
    TRANSIT_FAVORABLE("Favorable", "अनुकूल"),
    TRANSIT_GOCHARA_ANALYSIS("Gochara Analysis (From Moon)", "गोचर विश्लेषण (चन्द्रबाट)"),
    TRANSIT_GOOD("Good", "राम्रो"),
    TRANSIT_GOOD_TEMPLATE("Transit through %s brings favorable results with %d BAV and %d SAV bindus. Good progress expected in %s. %s areas are positively influenced.", "%s मा %d BAV र %d SAV बिन्दुसँगको गोचरले अनुकूल परिणामहरू ल्याउँछ। %s मा राम्रो प्रगति अपेक्षित छ। %s क्षेत्रमा सकारात्मक प्रभाव पर्नेछ।"),
    TRANSIT_HOUSE_FROM_MOON("House %d", "भाव %d"),
    TRANSIT_HOUSE_LABEL("House", "भाव"),
    TRANSIT_INTENSE_REM("Practice %s's remedies more intensely", "%s को उपायहरू थप तीव्रताका साथ गर्नुहोस्"),
    TRANSIT_INTENSITY("Intensity %d/5", "तीव्रता %d/५"),
    TRANSIT_INTERP_AVERAGE("Average - Mixed results", "औसत - मिश्रित परिणामहरू"),
    TRANSIT_INTERP_BELOW_AVG("Below Average - Some challenges", "औसतभन्दा कम - केही चुनौतीहरू"),
    TRANSIT_INTERP_DIFFICULT("Difficult - Careful navigation needed", "कठिन - सावधानीपूर्ण व्यवहार आवश्यक"),
    TRANSIT_INTERP_EXCELLENT("Excellent - Highly favorable transit", "उत्कृष्ट - अत्यन्त अनुकूल गोचर"),
    TRANSIT_INTERP_GOOD("Good - Favorable results expected", "राम्रो - अनुकूल परिणामहरू अपेक्षित"),
    TRANSIT_LABEL("Transit", "गोचर"),
    TRANSIT_MAJOR_DEC("Avoid major decisions related to %s's significations", "%s को कारकत्वसँग सम्बन्धित ठूला निर्णयहरू नगर्नुहोस्"),
    TRANSIT_MAJOR_TRANSITS("Major Transits", "मुख्य गोचरहरू"),
    TRANSIT_MODERATE("Moderate", "मध्यम"),
    TRANSIT_NATAL_LABEL("Natal", "जन्म"),
    TRANSIT_NO_ASPECTS("No transit aspects at this time", "यस समयमा कुनै गोचर पहलुहरू छैनन्"),
    TRANSIT_NO_DATA("No Transit Data", "कुनै गोचर डाटा छैन"),
    TRANSIT_NO_PLANETS_TRANSITING("No planets in this house", "यस भावमा कोनै ग्रह छैन"),
    TRANSIT_NO_UPCOMING("No upcoming significant transits", "कुनै आगामी महत्त्वपूर्ण गोचरहरू छैनन्"),
    TRANSIT_NULLIFIED("Nullified by Vedha", "वेधद्वारा रद्द"),
    TRANSIT_ORB("Orb: %s°", "कोणान्तर: %s°"),
    TRANSIT_ORB_VALUE("%d° orb", "%d° कोणान्तर"),
    TRANSIT_OVERALL_ASSESSMENT("Overall Assessment", "समग्र मूल्यांकन"),
    TRANSIT_OVERALL_SCORE("Overall Transit Score", "समग्र गोचर अंक"),
    TRANSIT_OVERVIEW("Transit Overview", "गोचर अवलोकन"),
    TRANSIT_PHRASE("%1\$s transit %2\$s natal %3\$s", "%1\$sको गोचर जन्मकालीन %3\$sमा %2\$s"),
    TRANSIT_PLANETS_COUNT("Planets Transiting", "गोचरमा ग्रहहरू"),
    TRANSIT_PLANET_POSITIONS("Current Positions", "हालको स्थितिहरू"),
    TRANSIT_QUALITY_AVERAGE("Average", "औसत"),
    TRANSIT_QUALITY_BELOW_AVG("Below Average", "औसतभन्दा कम"),
    TRANSIT_QUALITY_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    TRANSIT_QUALITY_DIFFICULT("Difficult", "कठिन"),
    TRANSIT_QUALITY_EXCELLENT("Excellent", "उत्कृष्ट"),
    TRANSIT_QUALITY_GOOD("Good", "राम्रो"),
    TRANSIT_QUALITY_LABEL("Quality Score", "गुणस्तर स्कोर"),
    TRANSIT_QUALITY_UNKNOWN("Unknown", "अज्ञात"),
    TRANSIT_RETROGRADE_SYMBOL("Rx", "Rx"),
    TRANSIT_SELECT_CHART("Select a chart to view transits", "गोचरहरू हेर्न कुण्डली छान्नुहोस्"),
    TRANSIT_SEPARATING("Separating", "टाढा हुँदै"),
    TRANSIT_SIGNIFICANT_PERIODS("Significant Periods", "महत्त्वपूर्ण अवधिहरू"),
    TRANSIT_TIMING("Transit Timing", "गोचर समय"),
    TRANSIT_TIMING_DESC("When slow-moving planets (Saturn, Jupiter, Rahu, Ketu) transit over your Bhrigu Bindu, significant karmic events tend to manifest.", "जब ढिलो हिड्ने ग्रहहरू (शनि, बृहस्पति, राहु, केतु) तपाइँको भृगु बिन्दु माथि गोचर गर्छन्, महत्त्वपूर्ण कार्मिक घटनाहरू प्रकट हुन्छन्।"),
    TRANSIT_TO_NATAL_ASPECTS("Transit to Natal Aspects", "गोचर-जन्म पहलुहरू"),
    TRANSIT_UNFAVORABLE("Unfavorable Transit", "प्रतिकूल गोचर"),
    TRANSIT_UPCOMING("Upcoming Transits", "आगामी गोचरहरू"),
    TRANSIT_VEDHA_FROM("Vedha from %s", "%s बाट वेध"),
    TRANSIT_WEAK("Weak", "कमजोर"),
    UPACHAYA_ABOUT("About Upachaya", "उपचयको बारेमा"),
    UPACHAYA_ACTIVE("Active", "सक्रिय"),
    UPACHAYA_ACTIVE_ALERTS("Active Alerts", "सक्रिय सूचनाहरू"),
    UPACHAYA_ACTIVE_NOW("Active Now", "अहिले सक्रिय"),
    UPACHAYA_ACTIVE_TRANSITS("Active Upachaya Transits", "सक्रिय उपचय गोचरहरू"),
    UPACHAYA_ALERTS("Transit Alerts", "गोचर सचेतनाहरू"),
    UPACHAYA_ALERT_EXCELLENT("%s in %s house - Excellent opportunity period!", "%s भावमा %s - उत्कृष्ट अवसर अवधि!"),
    UPACHAYA_ALERT_FORTUNE("Fortune", "भाग्य"),
    UPACHAYA_ALERT_JUPITER_11("Jupiter transiting 11th house - Excellent for gains and fulfillment of desires!", "बृहस्पतिको ११औं भावमा गोचर - लाभ र इच्छाहरूको पूर्तिका लागि उत्कृष्ट!"),
    UPACHAYA_ALERT_MAJOR_TRANSIT("Major Transit", "प्रमुख गोचर"),
    UPACHAYA_ALERT_OPPORTUNITY("Opportunity", "अवसर"),
    UPACHAYA_ALERT_SATURN_10("Saturn transiting 10th house - Major career period! Work hard for lasting results", "शनिको १०औं भावमा गोचर - प्रमुख क्यारियर अवधि! स्थायी परिणामका लागि कडा परिश्रम गर्नुहोस्"),
    UPACHAYA_ASSESSMENT("Overall Assessment", "समग्र मूल्यांकन"),
    UPACHAYA_ASSESS_DAILY_ACTION("Focus on daily actions to maximize current transits", "वर्तमान गोचरहरूलाई अधिकतम बनाउन दैनिक कार्यहरूमा ध्यान दिनुहोस्"),
    UPACHAYA_ASSESS_EXCEPTIONAL("Exceptional period! Multiple powerful transits favor growth in career, gains, and overcoming obstacles", "असाधारण अवधि! बहु शक्तिशाली गोचरहरूले क्यारियर, लाभ र बाधाहरू पार गर्न मद्दत गर्छन्"),
    UPACHAYA_ASSESS_HIGH("Favorable period with strong Upachaya transits supporting professional and material growth", "व्यावसायिक र भौतिक वृद्धिलाई समर्थन गर्ने बलियो उपचय गोचरसहितको अनुकूल अवधि"),
    UPACHAYA_ASSESS_KEY_TRANSIT("%s in %s house is the key transit", "%s भावमा %s मुख्य गोचर हो"),
    UPACHAYA_ASSESS_LOW("Limited Upachaya activation - focus on preparation for upcoming favorable transits", "सीमित उपचय सक्रियता - आगामी अनुकूल गोचरहरूको तयारीमा ध्यान दिनुहोस्"),
    UPACHAYA_ASSESS_MODERATE("Moderate Upachaya support - steady progress possible with focused effort", "मध्यम उपचय समर्थन - केन्द्रित प्रयासको साथ स्थिर प्रगति सम्भव छ"),
    UPACHAYA_ASSESS_NO_ACTIVE("No significant Upachaya transits currently active", "हाल कुनै महत्त्वपूर्ण उपचय गोचर सक्रिय छैन"),
    UPACHAYA_ASSESS_WAIT("Wait for slow planets to enter Upachaya houses", "ढिलो हिड्ने ग्रहहरू उपचय भावहरूमा प्रवेश गर्ने प्रतीक्षा गर्नुहोस्"),
    UPACHAYA_COMING_SOON("Coming Soon", "छिट्टै आउँदैछ"),
    UPACHAYA_CURRENT_TRANSITS("Current Beneficial Transits", "वर्तमान लाभदायक गोचर"),
    UPACHAYA_DURATION("Duration", "अवधि"),
    UPACHAYA_DURATION_JUPITER("~1 year per sign", "नजिकै १ वर्ष प्रति राशि"),
    UPACHAYA_DURATION_MARS("~6-8 weeks per sign", "नजिकै ६-८ हप्ता प्रति राशि"),
    UPACHAYA_DURATION_MERCURY("~3-4 weeks per sign", "नजिकै ३-४ हप्ता प्रति राशि"),
    UPACHAYA_DURATION_MOON("~2.5 days per sign", "नजिकै २.५ दिन प्रति राशि"),
    UPACHAYA_DURATION_RAHU("~1.5 years per sign", "नजिकै १.५ वर्ष प्रति राशि"),
    UPACHAYA_DURATION_SATURN("~2.5 years per sign", "नजिकै २.५ वर्ष प्रति राशि"),
    UPACHAYA_DURATION_SUN("~1 month per sign", "नजिकै १ महिना प्रति राशि"),
    UPACHAYA_DURATION_VENUS("~3-4 weeks per sign", "नजिकै ३-४ हप्ता प्रति राशि"),
    UPACHAYA_EFFECT_CAREER_ADVANCE("Career advancement opportunities", "क्यारियर प्रगतिका अवसरहरू"),
    UPACHAYA_EFFECT_COURAGE("Courage and initiative enhanced", "साहस र पहल वृद्धि"),
    UPACHAYA_EFFECT_DEBTS("Debt resolution possibilities", "ऋण समाधानको सम्भावना"),
    UPACHAYA_EFFECT_DESIRES("Desires and aspirations fulfilled", "इच्छा र आकांक्षाहरू पूरा"),
    UPACHAYA_EFFECT_ELDER_SIBLINGS("Elder siblings related benefits", "ठूला भाइबहिनीबाट लाभ"),
    UPACHAYA_EFFECT_ENEMIES("Victory over enemies and competitors", "शत्रु र प्रतिस्पर्धीहरूमाथि विजय"),
    UPACHAYA_EFFECT_FRIENDSHIP("Friendships and social network expansion", "मित्रता र सामाजिक सञ्जाल विस्तार"),
    UPACHAYA_EFFECT_GAINS("Gains and income increase likely", "लाभ र आयमा वृद्धिको सम्भावना"),
    UPACHAYA_EFFECT_GOVT_FAVORED("Government-related matters favored", "सरकारी सम्बन्धित मामिलाहरू अनुकूल"),
    UPACHAYA_EFFECT_HEALTH_IMPROVE("Health improvements through discipline", "अनुशासन मार्फत स्वास्थ्यमा सुधार"),
    UPACHAYA_EFFECT_PROFESSIONAL("Professional recognition possible", "व्यावसायिक मान्यता सम्भव"),
    UPACHAYA_EFFECT_SERVICE("Service opportunities arise", "सेवाका अवसरहरू प्राप्त"),
    UPACHAYA_EFFECT_SIBLINGS("Sibling relationships in focus", "भाइबहिनीको सम्बन्धमा ध्यान"),
    UPACHAYA_EFFECT_SKILLS("Skills and hobbies development", "सीप र शौकको विकास"),
    UPACHAYA_EFFECT_STATUS("Authority and status improvements", "अधिकार र स्थितिमा सुधार"),
    UPACHAYA_EFFECT_TRAVELS("Short travels and communications favored", "छोटो यात्रा र सञ्चार अनुकूल"),
    UPACHAYA_FROM_LAGNA("From Lagna", "लग्नबाट"),
    UPACHAYA_FROM_MOON("From Moon", "चन्द्रबाट"),
    UPACHAYA_GROWTH_INDICATOR("Growth Indicator", "वृद्धि सूचक"),
    UPACHAYA_HOUSES("Upachaya Houses (3, 6, 10, 11)", "उपचय भावहरू (३, ६, १०, ११)"),
    UPACHAYA_HOUSE_10("10th House (Career)", "१० भाव (करियर)"),
    UPACHAYA_HOUSE_11("11th House (Gains)", "११ भाव (लाभ)"),
    UPACHAYA_HOUSE_3("3rd House (Courage)", "३ भाव (साहस)"),
    UPACHAYA_HOUSE_6("6th House (Enemies)", "६ भाव (शत्रु)"),
    UPACHAYA_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
    UPACHAYA_HOUSE_INACTIVE("Inactive", "निष्क्रिय"),
    UPACHAYA_HOUSE_MILD("Mild", "हल्का"),
    UPACHAYA_HOUSE_MODERATE("Moderate", "मध्यम"),
    UPACHAYA_HOUSE_NO_TRANSIT("No active Upachaya transits in %s house", "%s भावमा कुनै सक्रिय उपचय गोचर छैन"),
    UPACHAYA_HOUSE_PLANETS_COUNT("%d planet(s) transiting %s house", "%s भावमा %d ग्रह(हरू) गोचर गर्दै"),
    UPACHAYA_HOUSE_STRONG("Strong", "बलियो"),
    UPACHAYA_HOUSE_VERY_STRONG("Very Strong", "अति बलियो"),
    UPACHAYA_HOUSE_WISE("House-wise Analysis", "भाव-अनुसार विश्लेषण"),
    UPACHAYA_IMPROVEMENT_AREAS("Areas of Improvement", "सुधारका क्षेत्रहरू"),
    UPACHAYA_JUPITER_PROGRESS("Jupiter expands opportunities in %s", "बृहस्पतिले %s मा अवसरहरू विस्तार गर्छ"),
    UPACHAYA_JUPITER_TRANSIT("Jupiter in Upachaya", "उपचयमा बृहस्पति"),
    UPACHAYA_LAGNA("Lagna", "लग्न"),
    UPACHAYA_LEVEL_EXCEPTIONAL("Exceptional Period", "असाधारण अवधि"),
    UPACHAYA_LEVEL_HIGH("High Activity", "उच्च सक्रियता"),
    UPACHAYA_LEVEL_LOW("Low Activity", "कम सक्रियता"),
    UPACHAYA_LEVEL_MODERATE("Moderate Activity", "मध्यम सक्रियता"),
    UPACHAYA_MARS_PROGRESS("Mars energizes action in %s", "मंगलले %s मा कार्यलाई ऊर्जित गर्छ"),
    UPACHAYA_MARS_TRANSIT("Mars in Upachaya", "उपचयमा मंगल"),
    UPACHAYA_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
    UPACHAYA_MOST_SIGNIFICANT("Most Significant Transits", "सबैभन्दा महत्त्वपूर्ण गोचरहरू"),
    UPACHAYA_PLANET_GENERIC("%s influences %s house themes", "%s ले %s भावको विषयवस्तुहरूलाई प्रभाव पार्छ"),
    UPACHAYA_PLANET_JUPITER_1("Wisdom and expansion in %s matters", "%s मामिलाहरूमा ज्ञान र विस्तार"),
    UPACHAYA_PLANET_JUPITER_2("Teachers and guides appear", "शिक्षक र मार्गदर्शकहरू देखा पर्छन्"),
    UPACHAYA_PLANET_JUPITER_3("Fortune through righteous action", "धार्मिक कार्य मार्फत भाग्य"),
    UPACHAYA_PLANET_KETU_1("Spiritual insights through practical matters", "व्यावहारिक मामिलाहरू मार्फत आध्यात्मिक अन्तर्दृष्टि"),
    UPACHAYA_PLANET_KETU_2("Detachment brings clarity", "वैराग्यले स्पष्टता ल्याउँछ"),
    UPACHAYA_PLANET_KETU_3("Past karma resolution", "विगतको कर्म समाधान"),
    UPACHAYA_PLANET_MARS_1("Energy and drive for action", "कार्यका लागि ऊर्जा र प्रेरणा"),
    UPACHAYA_PLANET_MARS_2("Competitive success possible", "प्रतिस्पर्धात्मक सफलता सम्भव"),
    UPACHAYA_PLANET_MARS_3("Physical activities favored", "शारीरिक गतिविधिहरू अनुकूल"),
    UPACHAYA_PLANET_RAHU_1("Unconventional opportunities arise", "अपरम्परागत अवसरहरू प्राप्त"),
    UPACHAYA_PLANET_RAHU_2("Foreign connections beneficial", "विदेशी सम्बन्धहरू लाभदायक"),
    UPACHAYA_PLANET_RAHU_3("Technology and innovation favored", "प्रविधि र नवीनता अनुकूल"),
    UPACHAYA_PLANET_SATURN_1("Slow but lasting results through discipline", "अनुशासन मार्फत ढिलो तर स्थायी परिणाम"),
    UPACHAYA_PLANET_SATURN_2("Karmic rewards for past efforts", "विगतका प्रयासहरूका लागि कार्मिक पुरस्कार"),
    UPACHAYA_PLANET_SATURN_3("Structure and organization bring success", "संरचना र संगठनले सफलता ल्याउँछ"),
    UPACHAYA_PLANET_SUN_1("Authority and confidence boosted", "अधिकार र आत्मविश्वास वृद्धि"),
    UPACHAYA_PLANET_SUN_2("Government favor possible", "सरकारी कृपा सम्भव"),
    UPACHAYA_PLANET_SUN_3("Leadership opportunities", "नेतृत्वका अवसरहरू"),
    UPACHAYA_QUALITY_EXCELLENT("Excellent", "उत्कृष्ट"),
    UPACHAYA_QUALITY_FAVORABLE("Favorable", "अनुकूल"),
    UPACHAYA_QUALITY_GOOD("Good", "राम्रो"),
    UPACHAYA_QUALITY_NEUTRAL("Neutral", "तटस्थ"),
    UPACHAYA_RAHU_TRANSIT("Rahu in Upachaya", "उपचयमा राहु"),
    UPACHAYA_REC_BOLD_INITIATIVE("Take bold initiatives - courage is supported now", "साहसी पहलहरू गर्नुहोस् - साहस अहिले समर्थित छ"),
    UPACHAYA_REC_CAREER_FOCUS("Focus on career advancement - professional recognition possible", "क्यारियर प्रगतिमा ध्यान दिनुहोस् - व्यावसायिक मान्यता सम्भव छ"),
    UPACHAYA_REC_FINANCIAL_GOALS("Pursue financial goals - gains and fulfillment of desires supported", "आर्थिक लक्ष्यहरू पछ्याउनुहोस् - लाभ र इच्छाहरूको पूर्ति समर्थित छ"),
    UPACHAYA_REC_HEALTH_CONFLICTS("Address health and resolve conflicts - victory over obstacles favored", "स्वास्थ्य र विवाद समाधानमा ध्यान दिनुहोस् - बाधाहरूमाथि विजय अनुकूल छ"),
    UPACHAYA_REC_HOUSE_10_1("Focus on career goals", "क्यारियर लक्ष्यहरूमा ध्यान दिनुहोस्"),
    UPACHAYA_REC_HOUSE_10_2("Seek recognition for your work", "आफ्नो कामका लागि मान्यता खोज्नुहोस्"),
    UPACHAYA_REC_HOUSE_10_3("Take on leadership responsibilities", "नेतृत्वको जिम्मेवारी लिनुहोस्"),
    UPACHAYA_REC_HOUSE_11_1("Network and expand connections", "नेटवर्क र सम्बन्धहरू विस्तार गर्नुहोस्"),
    UPACHAYA_REC_HOUSE_11_2("Pursue financial opportunities", "आर्थिक अवसरहरू पछ्याउनुहोस्"),
    UPACHAYA_REC_HOUSE_11_3("Support friends and community", "साथीहरू र समुदायलाई समर्थन गर्नुहोस्"),
    UPACHAYA_REC_HOUSE_3_1("Take initiative on pending matters", "बाँकी मामिलाहरूमा पहल गर्नुहोस्"),
    UPACHAYA_REC_HOUSE_3_2("Communicate your ideas boldly", "आफ्ना विचारहरू साहसका साथ व्यक्त गर्नुहोस्"),
    UPACHAYA_REC_HOUSE_3_3("Learn a new skill or hobby", "नयाँ सीप वा शौक सिक्नुहोस्"),
    UPACHAYA_REC_HOUSE_6_1("Address health matters proactively", "स्वास्थ्य मामिलाहरूमा सक्रिय रूपमा ध्यान दिनुहोस्"),
    UPACHAYA_REC_HOUSE_6_2("Resolve conflicts decisively", "विवादहरू निर्णायक रूपठप्पा समाधान गर्नुहोस्"),
    UPACHAYA_REC_HOUSE_6_3("Organize daily routines", "दैनिक दिनचर्या व्यवस्थित गर्नुहोस्"),
    UPACHAYA_REC_JUPITER_1("Expand through wisdom", "ज्ञान मार्फत विस्तार गर्नुहोस्"),
    UPACHAYA_REC_JUPITER_2("Share knowledge generously", "उदारतापूर्वक ज्ञान साझा गर्नुहोस्"),
    UPACHAYA_REC_JUPITER_3("Maintain ethical standards", "नैतिक मापदण्डहरू कायम राख्नुहोस्"),
    UPACHAYA_REC_MARS_1("Channel energy constructively", "ऊर्जालाई रचनात्मक रूपमा प्रयोग गर्नुहोस्"),
    UPACHAYA_REC_MARS_2("Avoid impulsive actions", "आवेगी कार्यहरूबाट बच्नुहोस्")
}
