package com.astro.storm.core.common
enum class StringKeyDashaInterpretationsPart1(override val en: String, override val ne: String) : StringKeyInterface {
    YOGINI_CHANDRA("Chandra (Moon)", "Chandra (Moon)"),
    YOGINI_SURYA("Surya (Sun)", "Surya (Sun)"),
    YOGINI_GURU("Guru (Jupiter)", "Guru (Jupiter)"),
    YOGINI_MANGAL("Mangal (Mars)", "Mangal (Mars)"),
    YOGINI_BUDHA("Budha (Mercury)", "Budha (Mercury)"),
    YOGINI_SHANI("Shani (Saturn)", "Shani (Saturn)"),
    YOGINI_SHUKRA("Shukra (Venus)", "Shukra (Venus)"),
YOGINI_RAHU("Rahu", "राहु"),
YOGINI_DASHA_TITLE("Yogini Dasha", "योगिनी दशा"),
YOGINI_DASHA_SUBTITLE("36-Year Cycle Dasha System", "३६-वर्षे चक्र दशा प्रणाली"),
YOGINI_DASHA_ABOUT("About Yogini Dasha", "योगिनी दशाको बारेमा"),
YOGINI_DASHA_ABOUT_DESC("Yogini Dasha is a nakshatra-based timing system with a 36-year cycle. It is particularly effective for female horoscopes and relationship timing.", "योगिनी दशा ३६-वर्षे चक्रको साथ नक्षत्रमा आधारित समय प्रणाली हो। यो महिला कुण्डली र सम्बन्ध समयको लागि विशेष प्रभावकारी छ।"),
YOGINI_DASHA_CURRENT("Current Yogini", "वर्तमान योगिनी"),
YOGINI_DASHA_ANTARDASHA("Current Antardasha", "वर्तमान अन्तर्दशा"),
YOGINI_DASHA_BALANCE("Balance at Birth", "जन्ममा सन्तुलन"),
YOGINI_DASHA_SEQUENCE("Yogini Sequence", "योगिनी क्रम"),
YOGINI_DASHA_APPLICABILITY("Applicability", "प्रयोज्यता"),
YOGINI_DASHA_RECOMMENDED("Recommended for this chart", "यो कुण्डलीको लागि सिफारिस"),
YOGINI_DASHA_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
YOGINI_MANGALA("Mangala", "मंगला"),
YOGINI_MANGALA_DESC("Auspicious beginnings, prosperity, and happiness. Moon's nurturing energy.", "शुभ शुरुआत, समृद्धि, र खुशी। चन्द्रको पोषणकारी ऊर्जा।"),
YOGINI_PINGALA("Pingala", "पिंगला"),
YOGINI_PINGALA_DESC("Authority, father-related matters, recognition. Sun's illuminating energy.", "अधिकार, पिता-सम्बन्धित मामिलाहरू, मान्यता। सूर्यको प्रकाशित ऊर्जा।"),
YOGINI_DHANYA("Dhanya", "धान्या"),
YOGINI_DHANYA_DESC("Wealth, wisdom, children, spiritual growth. Jupiter's expansive grace.", "धन, ज्ञान, सन्तान, आध्यात्मिक वृद्धि। गुरुको विस्तारित कृपा।"),
YOGINI_BHRAMARI("Bhramari", "भ्रामरी"),
YOGINI_BHRAMARI_DESC("Energy, conflicts, property matters. Mars brings action and courage.", "ऊर्जा, द्वन्द्व, सम्पत्ति मामिलाहरू। मंगलले कार्य र साहस ल्याउँछ।"),
YOGINI_BHADRIKA("Bhadrika", "भद्रिका"),
YOGINI_BHADRIKA_DESC("Intelligence, communication, business success. Mercury's intellectual wit.", "बुद्धि, सञ्चार, व्यापार सफलता। बुधको बौद्धिक कुशलता।"),
YOGINI_ULKA("Ulka", "उल्का"),
YOGINI_ULKA_DESC("Hardship, discipline, eventual success. Saturn teaches patience.", "कठिनाई, अनुशासन, अन्ततः सफलता। शनिले धैर्य सिकाउँछ।"),
YOGINI_SIDDHA("Siddha", "सिद्धा"),
YOGINI_SIDDHA_DESC("Success, luxury, marriage, artistic achievements. Venus brings love.", "सफलता, विलासिता, विवाह, कलात्मक उपलब्धिहरू। शुक्रले प्रेम ल्याउँछ।"),
YOGINI_SANKATA("Sankata", "संकटा"),
YOGINI_SANKATA_DESC("Obstacles, foreign influences, sudden changes. Rahu brings transformation.", "अवरोधहरू, विदेशी प्रभाव, अचानक परिवर्तन। राहुले रूपान्तरण ल्याउँछ।"),
YOGINI_YEARS_1("1 Year", "१ वर्ष"),
YOGINI_YEARS_2("2 Years", "२ वर्ष"),
YOGINI_YEARS_3("3 Years", "३ वर्ष"),
YOGINI_YEARS_4("4 Years", "४ वर्ष"),
YOGINI_YEARS_5("5 Years", "५ वर्ष"),
YOGINI_YEARS_6("6 Years", "६ वर्ष"),
YOGINI_YEARS_7("7 Years", "७ वर्ष"),
YOGINI_YEARS_8("8 Years", "८ वर्ष"),
YOGINI_NATURE_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यन्त शुभ"),
YOGINI_NATURE_AUSPICIOUS("Auspicious", "शुभ"),
YOGINI_NATURE_MIXED("Mixed", "मिश्रित"),
YOGINI_NATURE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
YOGINI_NATURE_DIFFICULT("Difficult", "कठिन"),
YOGINI_GENERAL_EFFECTS("General Effects", "सामान्य प्रभावहरू"),
YOGINI_CAREER_EFFECTS("Career Effects", "क्यारियर प्रभावहरू"),
YOGINI_RELATIONSHIP_EFFECTS("Relationship Effects", "सम्बन्ध प्रभावहरू"),
YOGINI_HEALTH_EFFECTS("Health Effects", "स्वास्थ्य प्रभावहरू"),
YOGINI_SPIRITUAL_EFFECTS("Spiritual Effects", "आध्यात्मिक प्रभावहरू"),
YOGINI_CAUTION_AREAS("Caution Areas", "सावधानी क्षेत्रहरू"),
YOGINI_MANGALA_CAREER("Career brings emotional satisfaction. Good for nurturing professions, public relations, and hospitality industry.", "क्यारियरले भावनात्मक सन्तुष्टि ल्याउँछ। हेरचाह गर्ने पेशाहरू, जनसम्पर्क, र आतिथ्य उद्योगको लागि राम्रो।"),
YOGINI_MANGALA_RELATIONSHIP("Emotional connections deepen. Good for starting relationships. Mother's influence prominent. Nurturing partnerships.", "भावनात्मक सम्बन्ध गहिरो हुन्छ। सम्बन्ध सुरु गर्न राम्रो। आमाको प्रभाव प्रमुख। पालनपोषण गर्ने साझेदारी।"),
YOGINI_MANGALA_HEALTH("Generally good health. Focus on emotional and mental well-being. Water-related activities beneficial.", "सामान्यतया राम्रो स्वास्थ्य। भावनात्मक र मानसिक कल्याणमा ध्यान दिनुहोस्। पानी सम्बन्धित गतिविधिहरू लाभदायक।"),
YOGINI_MANGALA_SPIRITUAL("Devotional practices strengthen. Mother goddess worship beneficial. Emotional cleansing through meditation.", "भक्ति अभ्यास बलियो हुन्छ। मातृ देवीको पूजा लाभदायक। ध्यान मार्फत भावनात्मक सफाई।"),
YOGINI_MANGALA_REC_1("Wear pearl or moonstone", "मोती वा चन्द्रकान्त मणि लगाउनुहोस्"),
YOGINI_MANGALA_REC_2("Honor your mother and maternal figures", "आमा र मातृ व्यक्तित्वहरूको सम्मान गर्नुहोस्"),
YOGINI_MANGALA_REC_3("Practice moon salutations", "चन्द्र नमस्कार अभ्यास गर्नुहोस्"),
YOGINI_MANGALA_REC_4("Donate white items on Mondays", "सोमबार सेतो वस्तुहरू दान गर्नुहोस्"),
YOGINI_MANGALA_CAUTION_1("Emotional volatility", "भावनात्मक अस्थिरता"),
YOGINI_MANGALA_CAUTION_2("Over-attachment", "अत्यधिक लगाव"),
YOGINI_MANGALA_CAUTION_3("Water-related issues", "पानी सम्बन्धित समस्याहरू"),
YOGINI_PINGALA_CAREER("Leadership opportunities arise. Government jobs, authority positions, and recognition in career. Father may influence career.", "नेतृत्वको अवसर आउँछ। सरकारी जागिर, अधिकारिक पद, र क्यारियरमा मान्यता। पिताले क्यारियरलाई प्रभाव पार्न सक्छन्।"),
YOGINI_PINGALA_RELATIONSHIP("Relationships with authority figures. Father-related matters in marriage. May face ego conflicts with partners.", "अधिकारी वर्गसँग सम्बन्ध। विवाहमा पिता सम्बन्धित विषयहरू। साझेदारहरूसँग अहंकार द्वन्द्व हुन सक्छ।"),
YOGINI_PINGALA_HEALTH("Watch heart, eyes, and overall vitality. Morning sun exposure beneficial. Maintain healthy ego.", "मुटु, आँखा, र समग्र जीवनशक्तिमा ध्यान दिनुहोस्। बिहानी घाम लाभदायक। स्वस्थ अहंकार कायम राख्नुहोस्।"),
YOGINI_PINGALA_SPIRITUAL("Solar meditation and surya namaskar beneficial. Connection with divine father principle. Self-realization focus.", "सूर्य ध्यान र सूर्य नमस्कार लाभदायक। दिव्य पिता तत्त्वसँग सम्बन्ध। आत्म-साक्षात्कारमा ध्यान।"),
YOGINI_PINGALA_REC_1("Wear ruby if suitable", "उपयुक्त भएमा माणिक लगाउनुहोस्"),
YOGINI_PINGALA_REC_2("Practice Surya Namaskar at sunrise", "सूर्योदयमा सूर्य नमस्कार अभ्यास गर्नुहोस्"),
YOGINI_PINGALA_REC_3("Honor your father", "पिताको सम्मान गर्नुहोस्"),
YOGINI_PINGALA_REC_4("Donate wheat or jaggery on Sundays", "आइतबार गहुँ वा सख्खर दान गर्नुहोस्"),
YOGINI_PINGALA_CAUTION_1("Ego conflicts", "अहंकार द्वन्द्व"),
YOGINI_PINGALA_CAUTION_2("Eye problems", "आँखा समस्याहरू"),
YOGINI_PINGALA_CAUTION_3("Father's health", "पिताको स्वास्थ्य"),
YOGINI_DHANYA_CAREER("Expansion in career, promotions, and higher learning. Excellent for teaching, consulting, and advisory roles.", "क्यारियरमा विस्तार, पदोन्नति, र उच्च शिक्षा। शिक्षण, परामर्श, र सल्लाहकार भूमिकाको लागि उत्कृष्ट।"),
YOGINI_DHANYA_RELATIONSHIP("Excellent for marriage and childbirth. Spiritual connections in relationships. Teachers and mentors become important.", "विवाह र सन्तानको लागि उत्कृष्ट। सम्बन्धमा आध्यात्मिक सम्बन्ध। शिक्षक र गुरुहरू महत्त्वपूर्ण हुन्छन्।"),
YOGINI_DHANYA_HEALTH("Good health generally. Watch liver and weight. Spiritual practices enhance well-being.", "सामान्यतया राम्रो स्वास्थ्य। कलेजो र तौलमा ध्यान दिनुहोस्। आध्यात्मिक अभ्यासले कल्याण बढाउँछ।"),
YOGINI_DHANYA_SPIRITUAL("Excellent for spiritual growth and higher learning. Guru connection strengthens. Sacred knowledge flows.", "आध्यात्मिक वृद्धि र उच्च शिक्षाको लागि उत्कृष्ट। गुरु सम्बन्ध बलियो हुन्छ। पवित्र ज्ञान प्रवाहित हुन्छ।"),
YOGINI_DHANYA_REC_1("Wear yellow sapphire if suitable", "उपयुक्त भएमा पुष्पराज लगाउनुहोस्"),
YOGINI_DHANYA_REC_2("Seek blessings from teachers", "शिक्षकहरूबाट आशीर्वाद लिनुहोस्"),
YOGINI_DHANYA_REC_3("Study sacred texts", "पवित्र ग्रन्थहरूको अध्ययन गर्नुहोस्"),
YOGINI_DHANYA_REC_4("Donate to educational causes on Thursdays", "बिहीबार शैक्षिक कार्यमा दान गर्नुहोस्"),
YOGINI_DHANYA_CAUTION_1("Over-expansion", "अत्यधिक विस्तार"),
YOGINI_DHANYA_CAUTION_2("Weight issues", "तौल समस्याहरू"),
YOGINI_DHANYA_CAUTION_3("Over-optimism", "अत्यधिक आशावाद"),
YOGINI_BHRAMARI_CAREER("Active period in career with competition. Good for technical, engineering, and defense-related fields. Property dealings.", "प्रतिस्पर्धा सहित क्यारियरमा सक्रिय अवधि। प्राविधिक, इन्जिनियरिङ, र रक्षा सम्बन्धित क्षेत्रहरूको लागि राम्रो। सम्पत्ति कारोबार।"),
YOGINI_BHRAMARI_RELATIONSHIP("Passionate but potentially conflicting relationships. Brothers/sisters prominent. Physical attraction strong.", "जोसिलो तर सम्भावित द्वन्द्वपूर्ण सम्बन्ध। दाजुभाइ/दिदीबहिनी प्रमुख। शारीरिक आकर्षण बलियो।"),
YOGINI_BHRAMARI_HEALTH("Watch for injuries, inflammations, and accidents. Physical exercise important but avoid overexertion.", "चोटपटक, सुजन, र दुर्घटनाहरूबाट बच्नुहोस्। शारीरिक व्यायाम महत्त्वपूर्ण तर अत्यधिक परिश्रम नगर्नुहोस्।"),
YOGINI_BHRAMARI_SPIRITUAL("Active spiritual practices like yoga and pranayama. Kundalini may activate. Mars-related deity worship helps.", "योग र प्राणायाम जस्ता सक्रिय आध्यात्मिक अभ्यासहरू। कुण्डलिनी सक्रिय हुन सक्छ। मंगल सम्बन्धित देवता पूजाले मद्दत गर्छ।"),
YOGINI_BHRAMARI_REC_1("Wear red coral if suitable", "उपयुक्त भएमा मुगा लगाउनुहोस्"),
YOGINI_BHRAMARI_REC_2("Practice physical exercise regularly", "नियमित शारीरिक व्यायाम गर्नुहोस्"),
YOGINI_BHRAMARI_REC_3("Channel energy constructively", "ऊर्जालाई रचनात्मक रूपमा प्रयोग गर्नुहोस्"),
YOGINI_BHRAMARI_REC_4("Donate red items on Tuesdays", "मंगलबार रातो वस्तुहरू दान गर्नुहोस्"),
YOGINI_BHRAMARI_CAUTION_1("Anger management", "क्रोध व्यवस्थापन"),
YOGINI_BHRAMARI_CAUTION_2("Accidents", "दुर्घटनाहरू"),
YOGINI_BHRAMARI_CAUTION_3("Property disputes", "सम्पत्ति विवाद"),
YOGINI_BHADRIKA_CAREER("Business acumen peaks. Excellent for trade, communication, writing, and intellectual pursuits. Good for learning new skills.", "व्यापारिक कौशल शिखरमा। व्यापार, सञ्चार, लेखन, र बौद्धिक कार्यहरूको लागि उत्कृष्ट। नयाँ सीपहरू सिक्न राम्रो।"),
YOGINI_BHADRIKA_RELATIONSHIP("Communication improves relationships. Intellectual compatibility matters. Good for understanding partners better.", "सञ्चारले सम्बन्ध सुधार गर्छ। बौद्धिक अनुकूलता महत्त्वपूर्ण छ। साझेदारहरूलाई राम्रोसँग बुझ्नको लागि राम्रो।"),
YOGINI_BHADRIKA_HEALTH("Nervous system needs attention. Skin issues possible. Mental relaxation techniques helpful.", "स्नायु प्रणालीमा ध्यान आवश्यक छ। छाला समस्याहरू सम्भव छ। मानसिक विश्राम प्रविधिहरू लाभदायक।"),
YOGINI_BHADRIKA_SPIRITUAL("Intellectual approach to spirituality. Study of scriptures beneficial. Mantra practice effective.", "आध्यात्मिकतामा बौद्धिक दृष्टिकोण। शास्त्रहरूको अध्ययन लाभदायक। मन्त्र अभ्यास प्रभावकारी।"),
YOGINI_BHADRIKA_REC_1("Wear emerald if suitable", "उपयुक्त भएमा पन्ना लगाउनुहोस्"),
YOGINI_BHADRIKA_REC_2("Engage in learning and communication", "सिक्ने र सञ्चारमा संलग्न हुनुहोस्"),
YOGINI_BHADRIKA_REC_3("Write and express yourself", "लेख्नुहोस् र आफूलाई व्यक्त गर्नुहोस्"),
YOGINI_BHADRIKA_REC_4("Donate green items on Wednesdays", "बुधबार हरियो वस्तुहरू दान गर्नुहोस्"),
YOGINI_BHADRIKA_CAUTION_1("Nervousness", "घबराहट"),
YOGINI_BHADRIKA_CAUTION_2("Overthinking", "अत्यधिक सोच"),
YOGINI_BHADRIKA_CAUTION_3("Skin issues", "छाला समस्याहरू"),
YOGINI_ULKA_CAREER("Slow but steady career progress. Hard work brings delayed rewards. Good for perseverance in long-term projects.", "सुस्त तर स्थिर क्यारियर प्रगति। कडा परिश्रमले ढिलो पुरस्कार ल्याउँछ। दीर्घकालीन परियोजनाहरूमा धैर्यताको लागि राम्रो।"),
YOGINI_ULKA_RELATIONSHIP("Delays or challenges in relationships. Karmic partners appear. Long-distance relationships possible.", "सम्बन्धमा ढिलाइ वा चुनौतीहरू। कार्मिक साझेदारहरू देखा पर्छन्। लामो-दूरीको सम्बन्ध सम्भव छ।"),
YOGINI_ULKA_HEALTH("Chronic issues may arise. Bones, joints, and teeth need care. Patience in recovery.", "दीर्घकालीन समस्याहरू उत्पन्न हुन सक्छ। हड्डी, जोर्नी, र दाँतको हेरचाह आवश्यक। निको हुन धैर्यता।"),
YOGINI_ULKA_SPIRITUAL("Deep karmic cleansing period. Meditation on impermanence. Service-oriented spirituality.", "गहिरो कार्मिक सफाई अवधि। अनित्यतामा ध्यान। सेवा-उन्मुख आध्यात्मिकता।"),
YOGINI_ULKA_REC_1("Wear blue sapphire with caution", "सावधानीपूर्वक नीलम लगाउनुहोस्"),
YOGINI_ULKA_REC_2("Practice patience and discipline", "धैर्य र अनुशासन अभ्यास गर्नुहोस्"),
YOGINI_ULKA_REC_3("Serve the elderly and disadvantaged", "वृद्ध र विपन्नहरूको सेवा गर्नुहोस्"),
YOGINI_ULKA_REC_4("Donate oil and black items on Saturdays", "शनिबार तेल र कालो वस्तुहरू दान गर्नुहोस्"),
YOGINI_ULKA_CAUTION_1("Depression", "अवसाद"),
YOGINI_ULKA_CAUTION_2("Delays", "ढिलाइ"),
YOGINI_ULKA_CAUTION_3("Chronic health issues", "दीर्घकालीन स्वास्थ्य समस्याहरू"),
YOGINI_SIDDHA_CAREER("Career success through creativity and charm. Excellent for arts, entertainment, luxury goods, and beauty industries.", "सृजनशीलता र आकर्षण मार्फत क्यारियर सफलता। कला, मनोरञ्जन, विलासिताका सामान, र सौन्दर्य उद्योगका लागि उत्कृष्ट।"),
YOGINI_SIDDHA_RELATIONSHIP("Excellent for romance, marriage, and love. Harmonious relationships. Beauty and pleasure in partnerships.", "रोमान्स, विवाह, र प्रेमको लागि उत्कृष्ट। सामंजस्यपूर्ण सम्बन्ध। साझेदारीमा सौन्दर्य र आनन्द।"),
YOGINI_SIDDHA_HEALTH("Generally good health. Watch reproductive system. Beauty treatments beneficial.", "सामान्यतया राम्रो स्वास्थ्य। प्रजनन प्रणालीमा ध्यान दिनुहोस्। सौन्दर्य उपचार लाभदायक।"),
YOGINI_SIDDHA_SPIRITUAL("Tantric practices may attract. Beauty in spirituality. Heart-centered practices beneficial.", "तान्त्रिक अभ्यासहरूले आकर्षित गर्न सक्छ। आध्यात्मिकतामा सौन्दर्य। हृदय-केन्द्रित अभ्यासहरू लाभदायक।"),
YOGINI_SIDDHA_REC_1("Wear diamond or white sapphire if suitable", "उपयुक्त भएमा हीरा वा सेतो पुखराज लगाउनुहोस्"),
YOGINI_SIDDHA_REC_2("Engage in arts and creativity", "कला र सृजनशीलतामा संलग्न हुनुहोस्"),
YOGINI_SIDDHA_REC_3("Cultivate harmonious relationships", "सामंजस्यपूर्ण सम्बन्ध विकास गर्नुहोस्"),
YOGINI_SIDDHA_REC_4("Donate white items on Fridays", "शुक्रबार सेतो वस्तुहरू दान गर्नुहोस्"),
YOGINI_SIDDHA_CAUTION_1("Indulgence", "भोगविला"),
YOGINI_SIDDHA_CAUTION_2("Relationship complications", "सम्बन्ध जटिलताहरू"),
YOGINI_SIDDHA_CAUTION_3("Luxury overspending", "विलासितामा अत्यधिक खर्च"),
YOGINI_SANKATA_CAREER("Unconventional career paths, foreign opportunities. May bring sudden changes in profession. Research and technology favored.", "अपरम्परागत क्यारियर पथहरू, विदेशी अवसरहरू। पेशामा अचानक परिवर्तन ल्याउन सक्छ। अनुसन्धान र प्रविधि अनुकूल।"),
YOGINI_SANKATA_RELATIONSHIP("Unusual or foreign partners. Sudden attractions or separations. Need to address karmic relationship patterns.", "असामान्य वा विदेशी साझेदारहरू। अचानक आकर्षण वा अलगाव। कार्मिक सम्बन्ध ढाँचाहरू सम्बोधन गर्न आवश्यक।"),
YOGINI_SANKATA_HEALTH("Unusual or hard-to-diagnose health issues. Mental health important. Alternative therapies may help.", "असामान्य वा निदान गर्न गाह्रो स्वास्थ्य समस्याहरू। मानसिक स्वास्थ्य महत्त्वपूर्ण। वैकल्पिक उपचारले मद्दत गर्न सक्छ।"),
YOGINI_SANKATA_SPIRITUAL("Deep transformation possible. Occult interests may arise. Breaking free from illusions.", "गहिरो रूपान्तरण सम्भव छ। तन्त्रमन्त्रमा रुचि जाग्न सक्छ। भ्रमबाट मुक्ति।"),
YOGINI_SANKATA_REC_1("Wear hessonite after careful analysis", "सावधानीपूर्वक विश्लेषण पछि गोमेद लगाउनुहोस्"),
YOGINI_SANKATA_REC_2("Stay grounded during sudden changes", "अचानक परिवर्तनको समयमा स्थिर रहनुहोस्"),
YOGINI_SANKATA_REC_3("Address past-life patterns through meditation", "ध्यान मार्फत पूर्व-जन्मका ढाँचाहरू सम्बोधन गर्नुहोस्"),
YOGINI_SANKATA_REC_4("Donate blue/black items on Saturdays", "शनिबार निलो/कालो वस्तुहरू दान गर्नुहोस्"),
YOGINI_SANKATA_CAUTION_1("Sudden obstacles", "अचानक अवरोधहरू"),
YOGINI_SANKATA_CAUTION_2("Confusion", "भ्रम"),
YOGINI_SANKATA_CAUTION_3("Unusual diseases", "असामान्य रोगहरू"),
YOGINI_ANTAR_FRIENDLY("%s-%s: Harmonious sub-period with complementary energies. %s's significations blend well with %s's ongoing influence. Good for collaborative efforts and relationship building.", "%s-%s: पूरक ऊर्जाको साथ सामंजस्यपूर्ण उप-अवधि। %s को प्रभावहरू %s को चलिरहेको प्रभावसँग राम्रोसँग मिल्छन्। सहयोगात्मक प्रयास र सम्बन्ध निर्माणको लागि राम्रो।"),
YOGINI_ANTAR_HOSTILE("%s-%s: Potentially challenging sub-period with conflicting energies. %s may create tension with %s's ongoing themes. Requires patience, remedies, and conscious effort for harmony.", "%s-%s: द्वन्द्वपूर्ण ऊर्जाको साथ सम्भावित चुनौतीपूर्ण उप-अवधि। %s ले %s को चलिरहेको विषयहरूसँग तनाव सिर्जना गर्न सक्छ। धैर्य, उपाय, र सद्भावको लागि सचेत प्रयास आवश्यक।"),
YOGINI_ANTAR_NEUTRAL("%s-%s: Balanced sub-period requiring conscious integration. %s's themes activate within %s's framework. Results depend on individual chart placements.", "%s-%s: सचेत एकीकरण आवश्यक पर्ने सन्तुलित उप-अवधि। %s को विषयहरू %s को ढाँचा भित्र सक्रिय हुन्छन्। परिणामहरू व्यक्तिगत कुण्डली स्थितिमा निर्भर हुन्छन्।"),
YOGINI_APP_UNIVERSAL("Yogini Dasha is universally applicable for timing specific events", "विशिष्ट घटनाहरूको समय निर्धारणको लागि योगिनी दशा सर्वव्यापी रूपमा लागू हुन्छ"),
YOGINI_APP_FEMALE("Yogini Dasha is traditionally considered more accurate for female horoscopes", "योगिनी दशा परम्परागत रूपमा महिला कुण्डलीको लागि बढी सही मानिन्छ"),
YOGINI_APP_STRONG_MOON("Strong Moon in %s enhances Yogini Dasha applicability", "%s मा बलियो चन्द्रले योगिनी दशाको प्रयोज्यता बढाउँछ"),
YOGINI_APP_NIGHT_BIRTH("Night birth traditionally favors Yogini Dasha", "रात्रि जन्मले परम्परागत रूपमा योगिनी दशालाई पक्ष दिन्छ"),
YOGINI_APP_RELATIONSHIP("Yogini Dasha excels at timing relationship and marriage events", "योगिनी दशा सम्बन्ध र विवाह घटनाहरूको समय निर्धारणमा उत्कृष्ट छ"),
YOGINI_APP_VALIDATION("Can be used alongside Vimsottari Dasha for validation", "पुष्टिको लागि विंशोत्तरी दशासँगै प्रयोग गर्न सकिन्छ"),
CHARA_DASHA_TITLE("Chara Dasha", "चर दशा"),
CHARA_DASHA_SUBTITLE("Jaimini Sign-Based Dasha", "जैमिनी राशि-आधारित दशा"),
CHARA_DASHA_ABOUT("About Chara Dasha", "चर दशाको बारेमा"),
CHARA_DASHA_ABOUT_DESC("Chara Dasha is Jaimini's primary sign-based timing system. Unlike Vimsottari which uses planets, Chara Dasha uses zodiac signs as periods, providing unique insights into life events.", "चर दशा जैमिनीको प्राथमिक राशि-आधारित समय प्रणाली हो। विम्सोत्तरी जसले ग्रह प्रयोग गर्छ त्यसको विपरीत, चर दशाले अवधिको रूपमा राशिहरू प्रयोग गर्छ, जीवनका घटनाहरूमा अद्वितीय अन्तर्दृष्टि प्रदान गर्छ।"),
CHARA_DASHA_CURRENT("Current Sign Dasha", "वर्तमान राशि दशा"),
CHARA_DASHA_ANTARDASHA("Current Antardasha", "वर्तमान अन्तर्दशा"),
CHARA_DASHA_SEQUENCE("Dasha Sequence", "दशा क्रम"),
CHARA_DASHA_DIRECTION("Dasha Direction", "दशा दिशा"),
    CHARA_DASHA_DIRECT("Direct (Zodiacal)", "Direct (Zodiacal)"),
    CHARA_DASHA_REVERSE("Reverse (Anti-zodiacal)", "Reverse (Anti-zodiacal)"),
CHARA_DASHA_ODD_LAGNA("Odd Sign Lagna", "विषम राशि लग्न"),
CHARA_DASHA_EVEN_LAGNA("Even Sign Lagna", "सम राशि लग्न"),
CHARA_DASHA_YEARS("Years: %d", "वर्ष: %d"),
CHARA_DASHA_TIMELINE("Chara Dasha Timeline", "चर दशा समयरेखा"),
ASHTOTTARI_DASHA_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
ASHTOTTARI_DASHA_SUBTITLE("108-Year Dasha Cycle", "१०८-वर्षे दशा चक्र"),
ASHTOTTARI_DASHA_ABOUT("About Ashtottari Dasha", "अष्टोत्तरी दशाको बारेमा"),
    ASHTOTTARI_DASHA_ABOUT_DESC("Ashtottari Dasha is a 108-year cycle using 8 planets (excluding Ketu)", "Ashtottari Dasha is a 108-year cycle using 8 planets (excluding Ketu)"),
ASHTOTTARI_APPLICABLE("Applicable", "लागू"),
ASHTOTTARI_NOT_APPLICABLE("Not Applicable", "लागू हुँदैन"),
ASHTOTTARI_REASON("Applicability Reason", "प्रयोज्यता कारण"),
ASHTOTTARI_RAHU_FROM_LAGNA_LORD("Rahu from Lagna Lord", "लग्नेशबाट राहु"),
ASHTOTTARI_CURRENT_MD("Current Mahadasha", "वर्तमान महादशा"),
ASHTOTTARI_CURRENT_AD("Current Antardasha", "वर्तमान अन्तर्दशा"),
ASHTOTTARI_BALANCE_AT_BIRTH("Balance at Birth", "जन्ममा सन्तुलन"),
ASHTOTTARI_STARTING_LORD("Starting Dasha Lord", "सुरुवात दशा स्वामी"),
    ASHTOTTARI_PERIOD_YEARS("Period (Years)", "Period (Years)"),
ASHTOTTARI_COMPARISON("Vimsottari vs Ashtottari", "विंशोत्तरी बनाम अष्टोत्तरी"),
ASHTOTTARI_IN_AGREEMENT("Both systems agree", "दुवै प्रणाली सहमत"),
ASHTOTTARI_DIFFERENT("Systems show different planets", "प्रणालीहरूले फरक ग्रह देखाउँछन्"),
ASHTOTTARI_FRIEND("Friendly Period", "मैत्रीपूर्ण अवधि"),
ASHTOTTARI_ENEMY("Challenging Period", "चुनौतीपूर्ण अवधि"),
ASHTOTTARI_NEUTRAL("Neutral Period", "तटस्थ अवधि"),
ASHTOTTARI_SAME("Intensified Period", "तीव्र अवधि"),
SUDARSHANA_CHAKRA_TITLE("Sudarshana Chakra", "सुदर्शन चक्र"),
SUDARSHANA_CHAKRA_SUBTITLE("Triple Reference Annual Analysis", "त्रिगुण सन्दर्भ वार्षिक विश्लेषण"),
SUDARSHANA_CHAKRA_ABOUT("About Sudarshana Chakra", "सुदर्शन चक्रको बारेमा"),
SUDARSHANA_CHAKRA_ABOUT_DESC("Sudarshana Chakra analyzes yearly results from three references: Lagna, Moon, and Sun. Each house progresses one year at a time in a 12-year cycle.", "सुदर्शन चक्रले तीन सन्दर्भबाट वार्षिक परिणाम विश्लेषण गर्छ: लग्न, चन्द्र, र सूर्य। प्रत्येक भाव १२-वर्षे चक्रमा एक पटकमा एक वर्ष अगाडि बढ्छ।"),
SUDARSHANA_CURRENT_AGE("Current Age", "वर्तमान उमेर"),
SUDARSHANA_LAGNA_REFERENCE("Lagna Reference", "लग्न सन्दर्भ"),
SUDARSHANA_CHANDRA_REFERENCE("Moon Reference", "चन्द्र सन्दर्भ"),
SUDARSHANA_SURYA_REFERENCE("Sun Reference", "सूर्य सन्दर्भ"),
SUDARSHANA_ACTIVE_HOUSE("Active House", "सक्रिय भाव"),
SUDARSHANA_ACTIVE_SIGN("Active Sign", "सक्रिय राशि"),
SUDARSHANA_SIGN_LORD("Sign Lord", "राशि स्वामी"),
SUDARSHANA_CYCLE_NUMBER("Cycle Number", "चक्र संख्या"),
SUDARSHANA_HOUSE_THEMES("House Themes", "भाव विषयहरू"),
SUDARSHANA_SYNTHESIS("Synthesis", "संश्लेषण"),
SUDARSHANA_COMBINED_STRENGTH("Combined Strength", "संयुक्त बल"),
SUDARSHANA_COMMON_THEMES("Common Themes", "साझा विषयहरू"),
SUDARSHANA_CONFLICTING_THEMES("Conflicting Themes", "विरोधाभासी विषयहरू"),
SUDARSHANA_PRIMARY_FOCUS("Primary Focus", "प्राथमिक केन्द्र"),
SUDARSHANA_SECONDARY_FOCUS("Secondary Focus", "माध्यमिक केन्द्र"),
SUDARSHANA_YEARLY_PROGRESSION("Yearly Progression", "वार्षिक प्रगति"),
SUDARSHANA_PREVIOUS_YEAR("Previous Year", "गत वर्ष"),
SUDARSHANA_CURRENT_YEAR("Current Year", "वर्तमान वर्ष"),
SUDARSHANA_NEXT_YEAR("Next Year", "आगामी वर्ष"),
SUDARSHANA_TREND("Trend", "प्रवृत्ति"),
SUDARSHANA_EXCELLENT("Excellent", "उत्कृष्ट"),
SUDARSHANA_GOOD("Good", "राम्रो"),
SUDARSHANA_MODERATE("Moderate", "मध्यम"),
SUDARSHANA_WEAK("Weak", "कमजोर"),
SUDARSHANA_VERY_WEAK("Very Weak", "अति कमजोर"),
ASHTOTTARI_TITLE("Ashtottari Dasha", "अष्टोत्तरी दशा"),
ASHTOTTARI_BALANCE("Balance at Birth", "जन्ममा शेष"),
ASHTOTTARI_SUBTITLE("108-Year Conditional Dasha System", "१०८ वर्षको सशर्त दशा प्रणाली"),
ASHTOTTARI_ABOUT("About Ashtottari Dasha", "अष्टोत्तरी दशाको बारेमा"),
    ASHTOTTARI_ABOUT_DESC("Ashtottari Dasha is a conditional planetary period system spanning 108 years. It uses 8 planets (excluding Ketu)", "Ashtottari Dasha is a conditional planetary period system spanning 108 years. It uses 8 planets (excluding Ketu)"),
ASHTOTTARI_APPLICABILITY("Applicability Check", "लागू हुने जाँच"),
ASHTOTTARI_IDEAL_CONDITION("Ideal Condition: Day birth with Krishna Paksha Moon or Night birth with Shukla Paksha Moon", "आदर्श अवस्था: कृष्ण पक्षको चन्द्रमासहित दिनको जन्म वा शुक्ल पक्षको चन्द्रमासहित रातको जन्म"),
ASHTOTTARI_TOTAL_YEARS("Total Cycle: 108 Years", "कुल चक्र: १०८ वर्ष"),
    ASHTOTTARI_PLANETS_USED("8 Planets Used (No Sun, No Ketu)", "8 Planets Used (No Sun, No Ketu)"),
ASHTOTTARI_CURRENT_PERIOD("Current Period", "वर्तमान अवधि"),
ASHTOTTARI_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
ASHTOTTARI_SUN_DURATION("Sun: 6 years", "सूर्य: ६ वर्ष"),
ASHTOTTARI_MOON_DURATION("Moon: 15 years", "चन्द्र: १५ वर्ष"),
ASHTOTTARI_MARS_DURATION("Mars: 8 years", "मंगल: ८ वर्ष"),
ASHTOTTARI_MERCURY_DURATION("Mercury: 17 years", "बुध: १७ वर्ष"),
ASHTOTTARI_SATURN_DURATION("Saturn: 10 years", "शनि: १० वर्ष"),
ASHTOTTARI_JUPITER_DURATION("Jupiter: 19 years", "बृहस्पति: १९ वर्ष"),
ASHTOTTARI_RAHU_DURATION("Rahu: 12 years", "राहु: १२ वर्ष"),
CHARA_DASHA_TYPE("Type", "प्रकार"),
ASHTOTTARI_VENUS_DURATION("Venus: 21 years", "शुक्र: २१ वर्ष"),
SUDARSHANA_TITLE("Sudarshana Chakra Dasha", "सुदर्शन चक्र दशा"),
SUDARSHANA_SUBTITLE("Triple-Reference Timing System", "त्रि-सन्दर्भ समय प्रणाली"),
SUDARSHANA_ABOUT("About Sudarshana Chakra", "सुदर्शन चक्रको बारेमा"),
SUDARSHANA_ABOUT_TITLE("About Sudarshana Chakra", "सुदर्शन चक्र दशा बारे"),
SUDARSHANA_ABOUT_DESC("Sudarshana Chakra Dasha simultaneously considers the Lagna, Chandra, and Surya charts. Each year progresses through signs from these three reference points, giving a holistic view of life events.", "सुदर्शन चक्र दशाले लग्न, चन्द्र र सूर्य कुण्डली एकैसाथ विचार गर्दछ। प्रत्येक वर्ष यी तीन सन्दर्भ बिन्दुहरूबाट राशिहरू मार्फत अगाडि बढ्छ।"),
SUDARSHANA_LAGNA_CHAKRA("Lagna Chakra", "लग्न चक्र"),
SUDARSHANA_CHANDRA_CHAKRA("Chandra Chakra", "चन्द्र चक्र"),
SUDARSHANA_SURYA_CHAKRA("Surya Chakra", "सूर्य चक्र"),
SUDARSHANA_AGE("Age", "उमेर"),
SUDARSHANA_COMBINED_ANALYSIS("Combined Period Analysis", "संयुक्त अवधि विश्लेषण"),
SUDARSHANA_CONVERGENCE("Convergence Analysis", "अभिसरण विश्लेषण"),
SUDARSHANA_TRIPLE_VIEW("Triple View", "त्रिगुण दृश्य"),
SUDARSHANA_YEAR_ANALYSIS("Year Analysis", "वार्षिक विश्लेषण"),
SUDARSHANA_LAGNA_INFLUENCE("Lagna Influence", "लग्न प्रभाव"),
SUDARSHANA_CHANDRA_INFLUENCE("Chandra Influence", "चन्द्र प्रभाव"),
SUDARSHANA_SURYA_INFLUENCE("Surya Influence", "सूर्य प्रभाव"),
SUDARSHANA_CURRENT_SIGNS("Current Signs", "वर्तमान राशिहरू"),
SUDARSHANA_HOUSE_SIGNIFICATIONS("House Significations", "भाव अर्थहरू"),
SUDARSHANA_PLANETS_IN_SIGN("Planets in Sign", "राशिमा ग्रहहरू"),
SUDARSHANA_ASPECTS_RECEIVED("Aspects Received", "प्राप्त दृष्टिहरू"),
SUDARSHANA_STRONG_CONVERGENCE("Strong Convergence", "बलियो अभिसरण"),
SUDARSHANA_WEAK_CONVERGENCE("Weak Convergence", "कमजोर अभिसरण"),
    KALACHAKRA_GROUP_SAVYA("Savya (Direct)", "Savya (Direct)"),
    KALACHAKRA_GROUP_APSAVYA("Apsavya (Retrograde)", "Apsavya (Retrograde)"),
KALACHAKRA_DESC_SAVYA("Clockwise progression through signs - generally smoother life flow", "राशिहरूको घडीको दिशामा प्रगति - सामान्यतया सहज जीवन प्रवाह"),
KALACHAKRA_DESC_APSAVYA("Anti-clockwise progression - more karmic intensity and transformation", "राशिहरूको घडीको विपरीत दिशामा प्रगति - अधिक कार्मिक तीव्रता र परिवर्तन"),
KALACHAKRA_HEALTH_EXCELLENT("Excellent", "उत्कृष्ट"),
KALACHAKRA_HEALTH_GOOD("Good", "राम्रो"),
KALACHAKRA_HEALTH_MODERATE("Moderate", "मध्यम"),
KALACHAKRA_HEALTH_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
KALACHAKRA_HEALTH_CRITICAL("Critical", "गम्भीर"),
KALACHAKRA_HEALTH_DESC_EXCELLENT("Very favorable for health and vitality", "स्वास्थ्य र जोसका लागि धेरै अनुकूल"),
KALACHAKRA_HEALTH_DESC_GOOD("Generally supportive of health", "सामान्यतया स्वास्थ्यको लागि सहयोगी"),
KALACHAKRA_HEALTH_DESC_MODERATE("Mixed health indications", "मिश्रित स्वास्थ्य संकेतहरू"),
KALACHAKRA_HEALTH_DESC_CHALLENGING("Need to take care of health", "स्वास्थ्यको ख्याल राख्नु आवश्यक"),
KALACHAKRA_HEALTH_DESC_CRITICAL("Extra caution needed - follow remedies", "अतिरिक्त सावधानी आवश्यक - उपायहरू अपनाउनुहोस्"),
KALACHAKRA_REL_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
KALACHAKRA_REL_SUPPORTIVE("Supportive", "सहयोगी"),
KALACHAKRA_REL_NEUTRAL("Neutral", "तटस्थ"),
KALACHAKRA_REL_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
KALACHAKRA_REL_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
KALACHAKRA_REL_DESC_HARMONIOUS("Body and soul are aligned - good health and spiritual progress", "शरिर र आत्मा एकरुप छन् - राम्रो स्वास्थ्य र आध्यात्मिक प्रगति"),
KALACHAKRA_REL_DESC_SUPPORTIVE("Jeeva supports Deha - spiritual practices benefit health", "जीवले देहलाई सहयोग गर्छ - आध्यात्मिक अभ्यासले स्वास्थ्यलाई फाइदा पुर्‍याउँछ"),
KALACHAKRA_REL_DESC_NEUTRAL("Independent functioning of body and spirit", "शरिर र आत्माको स्वतन्त्र कार्य"),
KALACHAKRA_REL_DESC_CHALLENGING("Some friction between material and spiritual needs", "भौतिक र आध्यात्मिक आवश्यकताहरू बीच केही घर्षण"),
KALACHAKRA_REL_DESC_TRANSFORMATIVE("Deep karmic work needed to align body and soul", "शरिर र आत्मा मिलाउन गहिरो कार्मिक कार्य आवश्यक"),
    KALACHAKRA_OVERVIEW_TEXT("Kalachakra Dasha is a sophisticated timing system particularly useful for health predictions and spiritual transformation timing. It operates on the principle that body (Deha)", "Kalachakra Dasha is a sophisticated timing system particularly useful for health predictions and spiritual transformation timing. It operates on the principle that body (Deha)"),
KALACHAKRA_GUIDANCE_1("Monitor transits over Deha Rashi for physical health events", "शारीरिक स्वास्थ्य घटनाहरूको लागि देह राशि माथिको गोचर निगरानी गर्नुहोस्"),
KALACHAKRA_GUIDANCE_2("Observe transits over Jeeva Rashi for spiritual opportunities", "आध्यात्मिक अवसरहरूको लागि जीव राशि माथिको गोचर अवलोकन गर्नुहोस्"),
KALACHAKRA_GUIDANCE_3("When Deha and Jeeva sign lords are strong in transit, both health and spiritual progress are favored", "जब देह र जीव राशिका स्वामीहरू गोचरमा बलियो हुन्छन्, स्वास्थ्य र आध्यात्मिक प्रगति दुबै अनुकूल हुन्छन्"),
KALACHAKRA_GUIDANCE_4("Use Kalachakra Dasha alongside Vimsottari for comprehensive analysis", "विस्तृत विश्लेषणको लागि विंशोत्तरी सँगै कालचक्र दशा प्रयोग गर्नुहोस्"),
KALACHAKRA_GUIDANCE_5("Pay special attention when malefics transit your Deha Rashi", "जब पापी ग्रहहरूले तपाईंको देह राशिमा गोचर गर्छन् विशेष ध्यान दिनुहोस्"),
KALACHAKRA_EFFECT_ARIES("Period of initiative, new beginnings, and physical vitality. Mars energy brings action and courage.", "पहल, नयाँ शुरुआत र शारीरिक जोसको अवधि। मंगलको ऊर्जाले कर्म र साहस ल्याउँछ।"),
KALACHAKRA_EFFECT_TAURUS("Focus on stability, wealth accumulation, and sensory pleasures. Venus brings comfort and beauty.", "स्थिरता, धन सञ्चय र इन्द्रिय सुखमा ध्यान। शुक्रले आराम र सौन्दर्य ल्याउँछ।"),
KALACHAKRA_EFFECT_GEMINI("Communication, learning, and intellectual pursuits are highlighted. Mercury brings versatility.", "सञ्चार, सिकाइ र बौद्धिक प्रयासहरूलाई जोड दिइन्छ। बुधले बहुमुखी प्रतिभा ल्याउँछ।"),
KALACHAKRA_EFFECT_CANCER("Emotional growth, home, and family matters take center stage. Moon brings nurturing energy.", "भावनात्मक वृद्धि, घर र पारिवारिक मामिलाहरू मुख्य हुन्छन्। चन्द्रमाले पोषण गर्ने ऊर्जा ल्याउँछ।"),
KALACHAKRA_EFFECT_LEO("Recognition, authority, and creative self-expression. Sun brings confidence and vitality.", "मान्यता, अधिकार र रचनात्मक आत्म-अभिव्यक्ति। सूर्यले आत्मविश्वास र जोस ल्याउँछ।"),
KALACHAKRA_EFFECT_VIRGO("Analysis, health consciousness, and service. Mercury brings discrimination and healing potential.", "विश्लेषण, स्वास्थ्य चेतना र सेवा। बुधले विवेक र निको पार्ने क्षमता ल्याउँछ।"),
KALACHAKRA_EFFECT_LIBRA("Partnerships, balance, and aesthetic pursuits. Venus brings harmony and relationships.", "साझेदारी, सन्तुलन र सौन्दर्य प्रयासहरू। शुक्रले सद्भाव र सम्बन्धहरू ल्याउँछ।"),
KALACHAKRA_EFFECT_SCORPIO("Deep transformation, hidden matters, and research. Mars/Ketu bring intensity and rebirth.", "गहिरो रूपान्तरण, गुप्त मामिला र अनुसन्धान। मंगल/केतुले तीव्रता र पुनर्जन्म ल्याउँछन्।"),
KALACHAKRA_EFFECT_SAGITTARIUS("Higher learning, philosophy, and expansion. Jupiter brings wisdom and fortune.", "उच्च सिकाइ, दर्शन र विस्तार। बृहस्पतिले ज्ञान र भाग्य ल्याउँछ।"),
KALACHAKRA_EFFECT_CAPRICORN("Career, discipline, and long-term achievements. Saturn brings structure and maturity.", "क्यारियर, अनुशासन र दीर्घकालीन उपलब्धिहरू। शनिले संरचना र परिपक्वता ल्याउँछ।"),
KALACHAKRA_EFFECT_AQUARIUS("Innovation, humanitarian concerns, and group activities. Saturn/Rahu bring progressive change.", "नवप्रवर्तन, मानवीय चासो र समूह गतिविधिहरू। शनि/राहुले प्रगतिशील परिवर्तन ल्याउँछन्।"),
KALACHAKRA_EFFECT_PISCES("Spirituality, imagination, and transcendence. Jupiter brings divine connection and liberation.", "आध्यात्मिकता, कल्पना र पारलौकिकता। बृहस्पतिले ईश्वरीय सम्बन्ध र मुक्ति ल्याउँछ।"),
KALACHAKRA_BRIEF_ARIES("Energy, initiative, new starts.", "ऊर्जा, पहल, नयाँ शुरुआत।"),
KALACHAKRA_BRIEF_TAURUS("Stability, wealth, comfort.", "स्थिरता, धन, आराम।"),
KALACHAKRA_BRIEF_GEMINI("Communication, learning, versatility.", "सञ्चार, सिकाइ, बहुमुखी प्रतिभा।"),
KALACHAKRA_BRIEF_CANCER("Emotions, home, nurturing.", "भावनाहरू, घर, पालनपोषण।"),
KALACHAKRA_BRIEF_LEO("Recognition, creativity, authority.", "मान्यता, रचनात्मकता, अधिकार।"),
KALACHAKRA_BRIEF_VIRGO("Analysis, health, service.", "विश्लेषण, स्वास्थ्य, सेवा।"),
KALACHAKRA_BRIEF_LIBRA("Balance, relationships, harmony.", "सन्तुलन, सम्बन्ध, सद्भाव।"),
KALACHAKRA_BRIEF_SCORPIO("Transformation, depth, intensity.", "रूपान्तरण, गहिराई, तीव्रता।"),
KALACHAKRA_BRIEF_SAGITTARIUS("Expansion, wisdom, fortune.", "विस्तार, ज्ञान, भाग्य।"),
KALACHAKRA_BRIEF_CAPRICORN("Career, discipline, achievement.", "क्यारियर, अनुशासन, उपलब्धि।"),
KALACHAKRA_BRIEF_AQUARIUS("Innovation, humanity, progress.", "नवप्रवर्तन, मानवता, प्रगति।"),
KALACHAKRA_BRIEF_PISCES("Spirituality, imagination, liberation.", "आध्यात्मिकता, कल्पना, मुक्ति।"),
KALACHAKRA_SPIR_FIRE("Spiritual growth through action and courage. Karma yoga is favored.", "कर्म र साहस मार्फत आध्यात्मिक वृद्धि। कर्म योग अनुकूल छ।"),
KALACHAKRA_SPIR_EARTH("Spiritual grounding through service. Seva is emphasized.", "सेवा मार्फत आध्यात्मिक स्थिरता। सेवामा जोड दिइन्छ।"),
KALACHAKRA_SPIR_AIR("Spiritual development through knowledge. Jnana yoga is favored.", "ज्ञान मार्फत आध्यात्मिक विकास। ज्ञान योग अनुकूल छ।"),
KALACHAKRA_SPIR_WATER("Spiritual awakening through devotion. Bhakti yoga is emphasized.", "भक्ति मार्फत आध्यात्मिक जागरण। भक्ति योगमा जोड दिइन्छ।"),
KALACHAKRA_SPIR_GEN("Balanced spiritual development.", "सन्तुलित आध्यात्मिक विकास।"),
KALACHAKRA_MAT_H1("focus on self and physical initiatives.", "स्वयं र शारीरिक पहलमा ध्यान।"),
KALACHAKRA_MAT_H2("focus on wealth and resources.", "धन र स्रोतहरूमा ध्यान।"),
KALACHAKRA_MAT_H3("focus on courage and communication.", "साहस र संचारमा ध्यान।"),
KALACHAKRA_MAT_H4("focus on property and home.", "सम्पत्ति र घरमा ध्यान।"),
KALACHAKRA_MAT_H5("focus on creativity and children.", "रचनात्मकता र सन्तानमा ध्यान।"),
KALACHAKRA_MAT_H6("focus on service and health.", "सेवा र स्वास्थ्यमा ध्यान।"),
KALACHAKRA_MAT_H7("focus on partnerships and marriage.", "साझेदारी र विवाहमा ध्यान।"),
KALACHAKRA_MAT_H8("focus on transformation and research.", "रूपान्तरण र अनुसन्धानमा ध्यान।"),
KALACHAKRA_MAT_H9("focus on fortune and higher learning.", "भाग्य र उच्च शिक्षामा ध्यान।"),
KALACHAKRA_MAT_H10("focus on career and status.", "करियर र प्रतिष्ठामा ध्यान।"),
KALACHAKRA_MAT_H11("focus on gains and networking.", "लाभ र नेटवर्किङमा ध्यान।"),
KALACHAKRA_MAT_H12("focus on spirituality and foreign matters.", "आध्यात्मिकता र वैदेशिक मामिलामा ध्यान।"),
KALACHAKRA_PRED_INTRO_DEHA("Based on Deha lord's %1\$2 status and %2\$2 Deha-Jeeva relationship: ", "देह स्वामीको %1\$2 अवस्था र %2\$2 देह-जीव सम्बन्धको आधारमा: "),
KALACHAKRA_PRED_INTRO_JEEVA("Jeeva lord's %1\$2 condition indicates ", "जीव स्वामीको %1\$2 अवस्थाले संकेत गर्दछ "),
KALACHAKRA_HEALTH_PRED_HARMONIOUS("Physical health is well-supported by spiritual practices. Body responds well to holistic healing.", "शारीरिक स्वास्थ्यलाई आध्यात्मिक अभ्यासहरूले राम्रो समर्थन गर्दछ। शरीरले समग्र उपचारलाई राम्रो प्रतिक्रिया दिन्छ।"),
KALACHAKRA_HEALTH_PRED_SUPPORTIVE("Good baseline health with spiritual practices enhancing physical wellbeing.", "राम्रो आधारभूत स्वास्थ्यको साथ आध्यात्मिक अभ्यासहरूले शारीरिक कल्याण बढाउँछ।"),
KALACHAKRA_HEALTH_PRED_NEUTRAL("Health matters follow their natural course. Maintain regular routines.", "स्वास्थ्य मामिलाहरूले आफ्नो प्राकृतिक मार्ग पछ्याउँछन्। नियमित दिनचर्या कायम राख्नुहोस्।"),
KALACHAKRA_HEALTH_PRED_CHALLENGING("May experience tension between physical demands and spiritual aspirations. Balance is key.", "शारीरिक माग र आध्यात्मिक आकांक्षाहरू बीच तनाव अनुभव हुन सक्छ। सन्तुलन कुञ्जी हो।"),
KALACHAKRA_HEALTH_PRED_TRANSFORMATIVE("Health challenges may serve as catalysts for spiritual growth. Deep healing possible.", "स्वास्थ्य चुनौतीहरूले आध्यात्मिक वृद्धिको लागि उत्प्रेरकको रूपमा काम गर्न सक्छन्। गहिरो उपचार सम्भव छ।"),
KALACHAKRA_SPIRITUAL_PRED_HARMONIOUS("natural spiritual progress. Meditation and dharmic practices flow easily.", "प्राकृतिक आध्यात्मिक प्रगति। ध्यान र धार्मिक अभ्यासहरू सजिलै प्रवाहित हुन्छन्।"),
KALACHAKRA_SPIRITUAL_PRED_SUPPORTIVE("spiritual growth through practical application of wisdom.", "ज्ञानको व्यावहारिक प्रयोग मार्फत आध्यात्मिक वृद्धि।"),
KALACHAKRA_SPIRITUAL_PRED_NEUTRAL("steady spiritual development through consistent practice.", "निरन्तर अभ्यास मार्फत स्थिर आध्यात्मिक विकास।"),
KALACHAKRA_SPIRITUAL_PRED_CHALLENGING("spiritual growth through overcoming material attachments.", "भौतिक आसक्तिहरू जितेर आध्यात्मिक वृद्धि।"),
KALACHAKRA_SPIRITUAL_PRED_TRANSFORMATIVE("profound spiritual transformation through life's challenges.", "जीवनका चुनौतीहरू मार्फत गहिरो आध्यात्मिक रूपान्तरण।"),
    KALACHAKRA_REC_DEHA_LORD("Strengthen Deha lord (%1\$2)", "Strengthen Deha lord (%1\$2)"),
    KALACHAKRA_REC_JEEVA_LORD("Honor Jeeva lord (%1\$2)", "Honor Jeeva lord (%1\$2)"),
KALACHAKRA_REC_HARMONIOUS_1("Continue current spiritual and health practices - they are aligned", "वर्तमान आध्यात्मिक र स्वास्थ्य अभ्यासहरू जारी राख्नुहोस् - तिनीहरू पङ्क्तिबद्ध छन्"),
KALACHAKRA_REC_HARMONIOUS_2("Use this favorable period for deepening meditation", "यो अनुकूल अवधिलाई ध्यान गहिरो बनाउन प्रयोग गर्नुहोस्"),
KALACHAKRA_REC_SUPPORTIVE_1("Integrate physical yoga with spiritual practices", "शारीरिक योगलाई आध्यात्मिक अभ्यासहरूसँग एकीकृत गर्नुहोस्"),
KALACHAKRA_REC_SUPPORTIVE_2("Serve others as part of spiritual path", "आध्यात्मिक मार्गको भागको रूपमा अरूको सेवा गर्नुहोस्"),
KALACHAKRA_REC_NEUTRAL_1("Establish regular routines for both physical and spiritual health", "शारीरिक र आध्यात्मिक स्वास्थ्य दुवैको लागि नियमित दिनचर्या स्थापना गर्नुहोस्"),
KALACHAKRA_REC_NEUTRAL_2("Create balance between material and spiritual pursuits", "भौतिक र आध्यात्मिक प्रयासहरू बीच सन्तुलन सिर्जना गर्नुहोस्"),
KALACHAKRA_REC_CHALLENGING_1("Practice patience and acceptance with physical limitations", "शारीरिक सीमाहरूसँग धैर्य र स्वीकृति अभ्यास गर्नुहोस्"),
KALACHAKRA_REC_CHALLENGING_2("Transform challenges into spiritual growth opportunities", "चुनौतीहरूलाई आध्यात्मिक वृद्धिको अवसरमा रूपान्तरण गर्नुहोस्"),
KALACHAKRA_REC_TRANSFORMATIVE_1("Embrace transformation as part of soul's journey", "रूपान्तरणलाई आत्माको यात्राको भागको रूपमा अँगाल्नुहोस्"),
KALACHAKRA_REC_TRANSFORMATIVE_2("Seek guidance from spiritual teachers during difficult periods", "कठिन समयमा आध्यात्मिक गुरुहरूबाट मार्गदर्शन लिनुहोस्"),
ASHTOTTARI_CURRENT_TITLE("Current Ashtottari Period", "वर्तमान अष्टोत्तरी अवधि"),
ASHTOTTARI_BIRTH_NAKSHATRA_HEADER("BIRTH NAKSHATRA", "जन्म नक्षत्र"),
ASHTOTTARI_LORD_HEADER("LORD", "स्वामी"),
ASHTOTTARI_MAHADASHA_LABEL("Mahadasha", "महादशा"),
ASHTOTTARI_ANTARDASHA_LABEL("Antardasha", "अन्तर्दशा"),
ASHTOTTARI_PERIOD_INSIGHTS("Period Insights", "अवधि अन्तर्दृष्टि"),
ASHTOTTARI_ABOUT_TITLE("About Ashtottari Dasha", "अष्टोत्तरी दशा बारे"),
    ASHTOTTARI_ABOUT_DESC_FULL("The Ashtottari Dasha system is a 108-year planetary period cycle, traditionally used for charts where the Moon is in Krishna Paksha (waning phase)", "The Ashtottari Dasha system is a 108-year planetary period cycle, traditionally used for charts where the Moon is in Krishna Paksha (waning phase)"),
    ASHTOTTARI_PERIOD_LIST_HEADER("Planet Periods (108 Years Total)", "Planet Periods (108 Years Total)"),
ASHTOTTARI_TIMELINE_TITLE("Ashtottari Timeline", "अष्टोत्तरी समयरेखा"),
ASHTOTTARI_TIMELINE_DESC("108-Year Planetary Cycle", "१०८-वर्षे ग्रह चक्र"),
ASHTOTTARI_ANTARDASHAS_TITLE("Antardashas", "अन्तर्दशाहरू"),
ASHTOTTARI_SUB_PERIODS_FMT("%d sub-periods", "%d उप-अवधिहरू"),
ASHTOTTARI_UNABLE_CALC("Unable to calculate current period", "वर्तमान अवधि गणना गर्न असमर्थ"),
SUDARSHANA_YEAR_HEADER("Sudarshana Chakra - %d", "सुदर्शन चक्र - %d"),
SUDARSHANA_TRIPLE_DESC("Triple-Reference Annual Analysis", "त्रि-सन्दर्भ वार्षिक विश्लेषण"),
SUDARSHANA_YEAR_STRENGTH("OVERALL YEAR STRENGTH", "समग्र वर्ष बल"),
SUDARSHANA_YEAR_THEMES("Year Themes", "वर्षका विषयहरू"),
SUDARSHANA_BIRTH_REF_TITLE("Birth Reference Points", "जन्म सन्दर्भ बिन्दुहरू"),
SUDARSHANA_BIRTH_REF_DESC("Starting positions for chakra progression", "चक्र प्रगतिका लागि सुरुवाती स्थिति"),
SUDARSHANA_PERSPECTIVES_TITLE("Three Perspectives", "तीन दृष्टिकोण"),
SUDARSHANA_LAGNA_CHAKRA_DESC("Physical body, appearance, overall life direction", "भौतिक शरीर, रूप, समग्र जीवन दिशा"),
SUDARSHANA_MOON_CHAKRA_DESC("Mind, emotions, mother, public image", "मन, भावना, आमा, सार्वजनिक छवि"),
SUDARSHANA_SUN_CHAKRA_DESC("Soul, authority, father, career recognition", "आत्मा, अधिकार, बुबा, करियर मान्यता"),
SUDARSHANA_COMBINED_NOTE("The combined analysis of all three chakras gives the most accurate prediction of annual themes and events.", "सबै तीन चक्रहरूको संयुक्त विश्लेषणले वार्षिक विषय र घटनाहरूको सबैभन्दा सटीक भविष्यवाणी दिन्छ।"),
SUDARSHANA_YEARS_COUNT_FMT("%d years", "%d वर्ष"),
SUDARSHANA_AGE_FMT("Age %d", "उमेर %d"),
SUDARSHANA_UNABLE_CALC("Current year analysis not available", "वर्तमान वर्षको विश्लेषण उपलब्ध छैन"),
YOGINI_ERROR_MOON("Unable to determine Moon's Nakshatra position. Please verify birth data.", "चन्द्रमाको नक्षत्र स्थिति निर्धारण गर्न असमर्थ। कृपया जन्म डाटा प्रमाणित गर्नुहोस्।"),
YOGINI_ERROR_BIRTH("Invalid birth data provided. Please check date, time, and location.", "अमान्य जन्म डाटा प्रदान गरियो। कृपया मिति, समय र स्थान जाँच गर्नुहोस्।"),
YOGINI_ERROR_NAKSHATRA("Unable to calculate Yogini Dasha. Nakshatra calculation error.", "योगिनी दशा गणना गर्न असमर्थ। नक्षत्र गणना त्रुटि।"),
YOGINI_ERROR_GENERIC("Failed to calculate Yogini Dasha. Please try again.", "योगिनी दशा गणना गर्न असफल। कृपया फेरि प्रयास गर्नुहोस्।"),
KALACHAKRA_DASHA_TITLE("Kalachakra Dasha", "कालचक्र दशा"),
KALACHAKRA_DASHA_SUBTITLE("Body-Soul Timing System", "देह-आत्मा समय प्रणाली"),
KALACHAKRA_DASHA_ABOUT("About Kalachakra Dasha", "कालचक्र दशाको बारेमा"),
    KALACHAKRA_DASHA_ABOUT_DESC("Kalachakra Dasha is a highly respected Nakshatra-based timing system from BPHS, particularly useful for health predictions and spiritual transformation. It operates on the principle that body (Deha)", "Kalachakra Dasha is a highly respected Nakshatra-based timing system from BPHS, particularly useful for health predictions and spiritual transformation. It operates on the principle that body (Deha)"),
KALACHAKRA_CURRENT("Current Period", "वर्तमान अवधि"),
KALACHAKRA_TIMELINE("Timeline", "समयरेखा"),
KALACHAKRA_DEHA_JEEVA("Deha-Jeeva", "देह-जीव"),
KALACHAKRA_DEHA_JEEVA_TITLE("Deha-Jeeva Analysis", "देह-जीव विश्लेषण"),
KALACHAKRA_DEHA_JEEVA_SUBTITLE("Body and Soul Relationship", "शरीर र आत्माको सम्बन्ध"),
KALACHAKRA_DEHA("Deha", "देह"),
KALACHAKRA_JEEVA("Jeeva", "जीव"),
KALACHAKRA_BODY("Body", "शरीर"),
KALACHAKRA_SOUL("Soul", "आत्मा"),
KALACHAKRA_EFFECTS("Current Effects", "वर्तमान प्रभावहरू"),
KALACHAKRA_NAKSHATRA_GROUP("Nakshatra Group", "नक्षत्र समूह"),
KALACHAKRA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
KALACHAKRA_PADA("Pada", "पाद")
}
