package com.astro.storm.core.common
enum class StringKeyDoshaPart2(override val en: String, override val ne: String) : StringKeyInterface {
BHRIGU_BINDU_STRENGTH("Strength Assessment", "शक्ति मूल्यांकन"),
BHRIGU_BINDU_EXCELLENT("Excellent", "उत्कृष्ट"),
BHRIGU_BINDU_GOOD("Good", "राम्रो"),
BHRIGU_BINDU_MODERATE("Moderate", "मध्यम"),
BHRIGU_BINDU_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
BHRIGU_BINDU_DIFFICULT("Difficult", "कठिन"),
BHRIGU_BINDU_ASPECTS("Aspecting Planets", "दृष्टि गर्ने ग्रहहरू"),
BHRIGU_BINDU_CONJUNCTIONS("Conjunct Planets", "युति ग्रहहरू"),
BHRIGU_BINDU_TRANSITS("Transit Analysis", "गोचर विश्लेषण"),
BHRIGU_BINDU_KARMIC_SIGNIFICANCE("Karmic Significance", "कार्मिक महत्त्व"),
BHRIGU_BINDU_LIFE_AREAS("Life Area Influences", "जीवन क्षेत्र प्रभावहरू"),
BHRIGU_BINDU_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
BHRIGU_BINDU_AUSPICIOUS_DAYS("Auspicious Days", "शुभ दिनहरू"),
BHRIGU_BINDU_REMEDIES("Remedial Measures", "उपचारात्मक उपायहरू"),
BHRIGU_BINDU_ABOUT("About Bhrigu Bindu", "भृगु बिन्दुको बारेमा"),
BHRIGU_BINDU_ABOUT_DESC("Bhrigu Bindu is a sensitive point calculated from the midpoint of Rahu and Moon. It indicates where significant karmic events manifest in life and is used for precise event timing.", "भृगु बिन्दु राहु र चन्द्रको मध्यबिन्दुबाट गणना गरिएको संवेदनशील बिन्दु हो। यसले जीवनमा महत्त्वपूर्ण कार्मिक घटनाहरू कहाँ प्रकट हुन्छन् भनेर संकेत गर्छ र सटीक घटना समयको लागि प्रयोग गरिन्छ।"),
    BHRIGU_BINDU_CALCULATION("Calculation: (Rahu + Moon)", "Calculation: (Rahu + Moon)"),
BHRIGU_BINDU_RAHU_POSITION("Rahu Position", "राहु स्थिति"),
BHRIGU_BINDU_MOON_POSITION("Moon Position", "चन्द्र स्थिति"),
ARGALA_TITLE("Argala Analysis", "अर्गला विश्लेषण"),
ARGALA_SUBTITLE("Jaimini Intervention System", "जैमिनी हस्तक्षेप प्रणाली"),
ARGALA_ABOUT("About Argala", "अर्गलाको बारेमा"),
    ARGALA_ABOUT_DESC("Argala is a Jaimini system showing how planets in certain houses create interventions (Argala)", "Argala is a Jaimini system showing how planets in certain houses create interventions (Argala)"),
ARGALA_PRIMARY("Primary Argala", "प्राथमिक अर्गला"),
ARGALA_SECONDARY("Secondary Argala", "माध्यमिक अर्गला"),
    ARGALA_VIRODHA("Virodha Argala (Obstruction)", "Virodha Argala (Obstruction)"),
    ARGALA_SHUBHA("Shubha Argala (Benefic)", "Shubha Argala (Benefic)"),
    ARGALA_ASHUBHA("Ashubha Argala (Malefic)", "Ashubha Argala (Malefic)"),
ARGALA_UNOBSTRUCTED("Unobstructed Argala", "अबाधित अर्गला"),
ARGALA_OBSTRUCTED("Obstructed Argala", "बाधित अर्गला"),
ARGALA_NET_EFFECT("Net Effect", "शुद्ध प्रभाव"),
ARGALA_POSITIVE("Positive", "सकारात्मक"),
ARGALA_NEGATIVE("Negative", "नकारात्मक"),
ARGALA_MIXED("Mixed", "मिश्रित"),
ARGALA_FROM_HOUSE("From House %d", "भाव %d बाट"),
ARGALA_TO_HOUSE("To House %d", "भाव %d मा"),
ARGALA_SECOND_HOUSE("2nd House Argala", "द्वितीय भाव अर्गला"),
ARGALA_FOURTH_HOUSE("4th House Argala", "चतुर्थ भाव अर्गला"),
ARGALA_ELEVENTH_HOUSE("11th House Argala", "एकादश भाव अर्गला"),
ARGALA_FIFTH_HOUSE("5th House Argala", "पञ्चम भाव अर्गला"),
ARGALA_KARMA_DHARMA("Dharma Argala", "धर्म अर्गला"),
ARGALA_KARMA_ARTHA("Artha Argala", "अर्थ अर्गला"),
ARGALA_KARMA_KAMA("Kama Argala", "काम अर्गला"),
ARGALA_KARMA_MOKSHA("Moksha Argala", "मोक्ष अर्गला"),
ARGALA_HOUSE_STRENGTH("House Argala Strength", "भाव अर्गला बल"),
ARGALA_PLANET_CAUSES("Planet Argala Effects", "ग्रह अर्गला प्रभाव"),
KARAKA_TITLE("Chara Karakas", "चर कारकहरू"),
KARAKA_SUBTITLE("Jaimini Variable Significators", "जैमिनी परिवर्तनशील कारकहरू"),
KARAKA_ABOUT("About Chara Karakas", "चर कारकको बारेमा"),
KARAKA_ABOUT_DESC("Chara Karakas are Jaimini's system of variable significators based on planetary degrees. Unlike fixed karakas, these change based on each chart.", "चर कारकहरू ग्रहको अंशमा आधारित जैमिनीको परिवर्तनशील कारक प्रणाली हो। स्थिर कारकहरूको विपरीत, यी प्रत्येक कुण्डली अनुसार परिवर्तन हुन्छन्।"),
    KARAKA_AK("Atmakaraka (AK)", "Atmakaraka (AK)"),
KARAKA_AK_DESC("Soul significator - Highest degree planet, represents the self and spiritual evolution", "आत्मा कारक - उच्चतम अंश ग्रह, आत्म र आध्यात्मिक विकासको प्रतिनिधित्व"),
    KARAKA_AMK("Amatyakaraka (AmK)", "Amatyakaraka (AmK)"),
KARAKA_AMK_DESC("Minister significator - Career, profession, and life purpose", "मन्त्री कारक - क्यारियर, पेशा, र जीवन उद्देश्य"),
    KARAKA_BK("Bhratrikaraka (BK)", "Bhratrikaraka (BK)"),
KARAKA_BK_DESC("Sibling significator - Brothers, sisters, and courage", "भाइबहिनी कारक - भाइ, बहिनी, र साहस"),
    KARAKA_MK("Matrikaraka (MK)", "Matrikaraka (MK)"),
KARAKA_MK_DESC("Mother significator - Mother, nurturing, emotional foundation", "आमा कारक - आमा, पालनपोषण, भावनात्मक आधार"),
    KARAKA_PIK("Pitrikaraka (PiK)", "Pitrikaraka (PiK)"),
KARAKA_PIK_DESC("Father significator - Father, authority, guidance", "बुबा कारक - बुबा, अधिकार, मार्गदर्शन"),
    KARAKA_PUK("Putrakaraka (PuK)", "Putrakaraka (PuK)"),
KARAKA_PUK_DESC("Children significator - Children, creativity, intelligence", "सन्तान कारक - सन्तान, सृजनशीलता, बुद्धि"),
    KARAKA_GK("Gnatikaraka (GK)", "Gnatikaraka (GK)"),
KARAKA_GK_DESC("Relative significator - Relatives, obstacles, competition", "सम्बन्धी कारक - आफन्त, बाधा, प्रतिस्पर्धा"),
    KARAKA_DK("Darakaraka (DK)", "Darakaraka (DK)"),
KARAKA_DK_DESC("Spouse significator - Marriage partner, business partners", "जीवनसाथी कारक - विवाह साथी, व्यापार साझेदार"),
KARAKAMSHA_TITLE("Karakamsha", "कारकांश"),
KARAKAMSHA_DESC("Navamsa sign of Atmakaraka - Key for spiritual and material destiny", "आत्मकारकको नवांश राशि - आध्यात्मिक र भौतिक भाग्यको लागि महत्त्वपूर्ण"),
    SHADVARGA_BALA("Shadvarga Bala (6-Varga)", "Shadvarga Bala (6-Varga)"),
    SAPTAVARGA_BALA("Saptavarga Bala (7-Varga)", "Saptavarga Bala (7-Varga)"),
    DASHAVARGA_BALA("Dashavarga Bala (10-Varga)", "Dashavarga Bala (10-Varga)"),
VIMSOPAKA_BALA("Vimsopaka Bala", "विम्शोपक बल"),
VIMSOPAKA_POORVA("Poorva Scheme", "पूर्व योजना"),
VIMSOPAKA_MADHYA("Madhya Scheme", "मध्य योजना"),
VIMSOPAKA_PARA("Para Scheme", "पर योजना"),
VARGOTTAMA_TITLE("Vargottama Planets", "वर्गोत्तम ग्रहहरू"),
VARGOTTAMA_DESC("Planet in same sign in D1 and divisional chart", "D1 र विभाजन चार्टमा समान राशिमा ग्रह"),
VARGOTTAMA_NAVAMSA("Navamsa Vargottama", "नवांश वर्गोत्तम"),
VARGOTTAMA_DASHAMSA("Dashamsa Vargottama", "दशांश वर्गोत्तम"),
STRONGEST_PLANET("Strongest Planet", "बलवान ग्रह"),
WEAKEST_PLANET("Weakest Planet", "दुर्बल ग्रह"),
AVERAGE_STRENGTH("Average Strength", "औसत बल"),
KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टि"),
MRITYU_BHAGA_TITLE("Mrityu Bhaga Analysis", "मृत्यु भाग विश्लेषण"),
MRITYU_BHAGA_SUBTITLE("Sensitive Degrees Analysis", "संवेदनशील अंश विश्लेषण"),
MRITYU_BHAGA_ABOUT("About Mrityu Bhaga", "मृत्यु भागको बारेमा"),
MRITYU_BHAGA_ABOUT_DESC("Mrityu Bhaga indicates critical degrees where planets become vulnerable. Analysis includes Gandanta junctions and auspicious Pushkara placements.", "मृत्यु भागले ग्रहहरू कमजोर हुने महत्त्वपूर्ण अंशहरू देखाउँछ। विश्लेषणमा गण्डान्त सन्धिहरू र शुभ पुष्कर स्थितिहरू समावेश छन्।"),
MRITYU_BHAGA_EXACT("Exact", "यथार्थ"),
MRITYU_BHAGA_VERY_CLOSE("Very Close", "अति नजिक"),
MRITYU_BHAGA_WITHIN_ORB("Within Orb", "परिधि भित्र"),
MRITYU_BHAGA_APPROACHING("Approaching", "नजिक आउँदै"),
MRITYU_BHAGA_SAFE("Safe", "सुरक्षित"),
MRITYU_BHAGA_DEGREE("Mrityu Bhaga Degree", "मृत्यु भाग अंश"),
MRITYU_BHAGA_DISTANCE("Distance from Critical Degree", "महत्त्वपूर्ण अंशबाट दूरी"),
MRITYU_BHAGA_EFFECTS("Effects", "प्रभावहरू"),
MRITYU_BHAGA_VULNERABILITIES("Vulnerability Areas", "कमजोर क्षेत्रहरू"),
GANDANTA_TITLE("Gandanta Analysis", "गण्डान्त विश्लेषण"),
GANDANTA_SUBTITLE("Water-Fire Sign Junction Points", "जल-अग्नि राशि सन्धि बिन्दुहरू"),
GANDANTA_EXACT_JUNCTION("Exact Junction", "यथार्थ सन्धि"),
GANDANTA_CRITICAL("Critical", "गम्भीर"),
GANDANTA_SEVERE("Severe", "तीव्र"),
GANDANTA_MODERATE("Moderate", "मध्यम"),
GANDANTA_MILD("Mild", "हल्का"),
    GANDANTA_BRAHMA("Brahma Gandanta (Cancer-Leo)", "Brahma Gandanta (Cancer-Leo)"),
    GANDANTA_VISHNU("Vishnu Gandanta (Scorpio-Sagittarius)", "Vishnu Gandanta (Scorpio-Sagittarius)"),
    GANDANTA_SHIVA("Shiva Gandanta (Pisces-Aries)", "Shiva Gandanta (Pisces-Aries)"),
PUSHKARA_NAVAMSA_TITLE("Pushkara Navamsa", "पुष्कर नवांश"),
PUSHKARA_NAVAMSA_DESC("Highly auspicious navamsa placements providing protection", "सुरक्षा प्रदान गर्ने अत्यधिक शुभ नवांश स्थितिहरू"),
PUSHKARA_BHAGA_TITLE("Pushkara Bhaga", "पुष्कर भाग"),
PUSHKARA_BHAGA_DESC("Single auspicious degrees providing nourishment", "पोषण प्रदान गर्ने एकल शुभ अंशहरू"),
SENSITIVE_DEGREES_CRITICAL("Critical Planets", "महत्त्वपूर्ण ग्रहहरू"),
SENSITIVE_DEGREES_AUSPICIOUS("Auspicious Planets", "शुभ ग्रहहरू"),
SENSITIVE_DEGREES_NEEDS_ATTENTION("Needs Attention", "ध्यान आवश्यक"),
SENSITIVE_DEGREES_MODERATE_CONCERN("Moderate Concern", "मध्यम चिन्ता"),
SENSITIVE_DEGREES_BALANCED("Balanced", "सन्तुलित"),
SENSITIVE_DEGREES_POSITIVE("Generally Positive", "सामान्यतया सकारात्मक"),
SENSITIVE_DEGREES_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यधिक शुभ"),
UPACHAYA_TRANSIT_TITLE("Upachaya Transits", "उपचय गोचर"),
UPACHAYA_TRANSIT_SUBTITLE("Growth House Transit Analysis", "वृद्धि भाव गोचर विश्लेषण"),
UPACHAYA_TRANSIT_ABOUT("About Upachaya Houses", "उपचय भावहरूको बारेमा"),
    UPACHAYA_TRANSIT_ABOUT_DESC("Upachaya houses (3, 6, 10, 11)", "Upachaya houses (3, 6, 10, 11)"),
    UPACHAYA_HOUSE_3("3rd House (Courage)", "3rd House (Courage)"),
    UPACHAYA_HOUSE_6("6th House (Enemies)", "6th House (Enemies)"),
    UPACHAYA_HOUSE_10("10th House (Career)", "10th House (Career)"),
    UPACHAYA_HOUSE_11("11th House (Gains)", "11th House (Gains)"),
UPACHAYA_FROM_MOON("From Moon", "चन्द्रबाट"),
UPACHAYA_FROM_LAGNA("From Lagna", "लग्नबाट"),
UPACHAYA_TRANSIT_QUALITY("Transit Quality", "गोचर गुणस्तर"),
UPACHAYA_QUALITY_EXCELLENT("Excellent", "उत्कृष्ट"),
UPACHAYA_QUALITY_GOOD("Good", "राम्रो"),
UPACHAYA_QUALITY_FAVORABLE("Favorable", "अनुकूल"),
UPACHAYA_QUALITY_NEUTRAL("Neutral", "तटस्थ"),
UPACHAYA_SIGNIFICANCE("Significance", "महत्त्व"),
UPACHAYA_DURATION("Duration", "अवधि"),
UPACHAYA_ACTIVE_TRANSITS("Active Upachaya Transits", "सक्रिय उपचय गोचरहरू"),
UPACHAYA_MOST_SIGNIFICANT("Most Significant Transits", "सबैभन्दा महत्त्वपूर्ण गोचरहरू"),
UPACHAYA_HOUSE_WISE("House-wise Analysis", "भाव-अनुसार विश्लेषण"),
UPACHAYA_ASSESSMENT("Overall Assessment", "समग्र मूल्यांकन"),
UPACHAYA_LEVEL_EXCEPTIONAL("Exceptional Period", "असाधारण अवधि"),
UPACHAYA_LEVEL_HIGH("High Activity", "उच्च सक्रियता"),
UPACHAYA_LEVEL_MODERATE("Moderate Activity", "मध्यम सक्रियता"),
UPACHAYA_LEVEL_LOW("Low Activity", "कम सक्रियता"),
UPACHAYA_ALERTS("Transit Alerts", "गोचर सचेतनाहरू"),
UPACHAYA_ALERT_OPPORTUNITY("Opportunity", "अवसर"),
UPACHAYA_ALERT_MAJOR_TRANSIT("Major Transit", "प्रमुख गोचर"),
UPACHAYA_ALERT_FORTUNE("Fortune", "भाग्य"),
UPACHAYA_UPCOMING("Upcoming Transits", "आगामी गोचरहरू"),
UPACHAYA_HOUSE_INACTIVE("Inactive", "निष्क्रिय"),
UPACHAYA_HOUSE_MILD("Mild", "हल्का"),
UPACHAYA_HOUSE_MODERATE("Moderate", "मध्यम"),
UPACHAYA_HOUSE_STRONG("Strong", "बलियो"),
UPACHAYA_HOUSE_VERY_STRONG("Very Strong", "अति बलियो"),
UPACHAYA_EFFECT_COURAGE("Courage and initiative enhanced", "साहस र पहल वृद्धि"),
UPACHAYA_EFFECT_TRAVELS("Short travels and communications favored", "छोटो यात्रा र सञ्चार अनुकूल"),
UPACHAYA_EFFECT_SIBLINGS("Sibling relationships in focus", "भाइबहिनीको सम्बन्धमा ध्यान"),
UPACHAYA_EFFECT_SKILLS("Skills and hobbies development", "सीप र शौकको विकास"),
UPACHAYA_EFFECT_ENEMIES("Victory over enemies and competitors", "शत्रु र प्रतिस्पर्धीहरूमाथि विजय"),
UPACHAYA_EFFECT_HEALTH_IMPROVE("Health improvements through discipline", "अनुशासन मार्फत स्वास्थ्यमा सुधार"),
UPACHAYA_EFFECT_SERVICE("Service opportunities arise", "सेवाका अवसरहरू प्राप्त"),
UPACHAYA_EFFECT_DEBTS("Debt resolution possibilities", "ऋण समाधानको सम्भावना"),
UPACHAYA_EFFECT_CAREER_ADVANCE("Career advancement opportunities", "क्यारियर प्रगतिका अवसरहरू"),
UPACHAYA_EFFECT_PROFESSIONAL("Professional recognition possible", "व्यावसायिक मान्यता सम्भव"),
UPACHAYA_EFFECT_STATUS("Authority and status improvements", "अधिकार र स्थितिमा सुधार"),
UPACHAYA_EFFECT_GOVT_FAVORED("Government-related matters favored", "सरकारी सम्बन्धित मामिलाहरू अनुकूल"),
UPACHAYA_EFFECT_GAINS("Gains and income increase likely", "लाभ र आयमा वृद्धिको सम्भावना"),
UPACHAYA_EFFECT_DESIRES("Desires and aspirations fulfilled", "इच्छा र आकांक्षाहरू पूरा"),
UPACHAYA_EFFECT_FRIENDSHIP("Friendships and social network expansion", "मित्रता र सामाजिक सञ्जाल विस्तार"),
UPACHAYA_EFFECT_ELDER_SIBLINGS("Elder siblings related benefits", "ठूला भाइबहिनीबाट लाभ"),
UPACHAYA_PLANET_SATURN_1("Slow but lasting results through discipline", "अनुशासन मार्फत ढिलो तर स्थायी परिणाम"),
UPACHAYA_PLANET_SATURN_2("Karmic rewards for past efforts", "विगतका प्रयासहरूका लागि कार्मिक पुरस्कार"),
UPACHAYA_PLANET_SATURN_3("Structure and organization bring success", "संरचना र संगठनले सफलता ल्याउँछ"),
UPACHAYA_PLANET_MARS_1("Energy and drive for action", "कार्यका लागि ऊर्जा र प्रेरणा"),
UPACHAYA_PLANET_MARS_2("Competitive success possible", "प्रतिस्पर्धात्मक सफलता सम्भव"),
UPACHAYA_PLANET_MARS_3("Physical activities favored", "शारीरिक गतिविधिहरू अनुकूल"),
UPACHAYA_PLANET_RAHU_1("Unconventional opportunities arise", "अपरम्परागत अवसरहरू प्राप्त"),
UPACHAYA_PLANET_RAHU_2("Foreign connections beneficial", "विदेशी सम्बन्धहरू लाभदायक"),
UPACHAYA_PLANET_RAHU_3("Technology and innovation favored", "प्रविधि र नवीनता अनुकूल"),
UPACHAYA_PLANET_KETU_1("Spiritual insights through practical matters", "व्यावहारिक मामिलाहरू मार्फत आध्यात्मिक अन्तर्दृष्टि"),
UPACHAYA_PLANET_KETU_2("Detachment brings clarity", "वैराग्यले स्पष्टता ल्याउँछ"),
UPACHAYA_PLANET_KETU_3("Past karma resolution", "विगतको कर्म समाधान"),
UPACHAYA_PLANET_JUPITER_1("Wisdom and expansion in %s matters", "%s मामिलाहरूमा ज्ञान र विस्तार"),
UPACHAYA_PLANET_JUPITER_2("Teachers and guides appear", "शिक्षक र मार्गदर्शकहरू देखा पर्छन्"),
UPACHAYA_PLANET_JUPITER_3("Fortune through righteous action", "धार्मिक कार्य मार्फत भाग्य"),
UPACHAYA_PLANET_SUN_1("Authority and confidence boosted", "अधिकार र आत्मविश्वास वृद्धि"),
UPACHAYA_PLANET_SUN_2("Government favor possible", "सरकारी कृपा सम्भव"),
UPACHAYA_PLANET_SUN_3("Leadership opportunities", "नेतृत्वका अवसरहरू"),
UPACHAYA_PLANET_GENERIC("%s influences %s house themes", "%s ले %s भावको विषयवस्तुहरूलाई प्रभाव पार्छ"),
UPACHAYA_DURATION_MOON("~2.5 days per sign", "नजिकै २.५ दिन प्रति राशि"),
UPACHAYA_DURATION_SUN("~1 month per sign", "नजिकै १ महिना प्रति राशि"),
UPACHAYA_DURATION_MERCURY("~3-4 weeks per sign", "नजिकै ३-४ हप्ता प्रति राशि"),
UPACHAYA_DURATION_VENUS("~3-4 weeks per sign", "नजिकै ३-४ हप्ता प्रति राशि"),
UPACHAYA_DURATION_MARS("~6-8 weeks per sign", "नजिकै ६-८ हप्ता प्रति राशि"),
UPACHAYA_DURATION_JUPITER("~1 year per sign", "नजिकै १ वर्ष प्रति राशि"),
UPACHAYA_DURATION_SATURN("~2.5 years per sign", "नजिकै २.५ वर्ष प्रति राशि"),
UPACHAYA_DURATION_RAHU("~1.5 years per sign", "नजिकै १.५ वर्ष प्रति राशि"),
UPACHAYA_REC_HOUSE_3_1("Take initiative on pending matters", "बाँकी मामिलाहरूमा पहल गर्नुहोस्"),
UPACHAYA_REC_HOUSE_3_2("Communicate your ideas boldly", "आफ्ना विचारहरू साहसका साथ व्यक्त गर्नुहोस्"),
UPACHAYA_REC_HOUSE_3_3("Learn a new skill or hobby", "नयाँ सीप वा शौक सिक्नुहोस्"),
UPACHAYA_REC_HOUSE_6_1("Address health matters proactively", "स्वास्थ्य मामिलाहरूमा सक्रिय रूपमा ध्यान दिनुहोस्"),
UPACHAYA_REC_HOUSE_6_2("Resolve conflicts decisively", "विवादहरू निर्णायक रूपठप्पा समाधान गर्नुहोस्"),
UPACHAYA_REC_HOUSE_6_3("Organize daily routines", "दैनिक दिनचर्या व्यवस्थित गर्नुहोस्"),
UPACHAYA_REC_HOUSE_10_1("Focus on career goals", "क्यारियर लक्ष्यहरूमा ध्यान दिनुहोस्"),
UPACHAYA_REC_HOUSE_10_2("Seek recognition for your work", "आफ्नो कामका लागि मान्यता खोज्नुहोस्"),
UPACHAYA_REC_HOUSE_10_3("Take on leadership responsibilities", "नेतृत्वको जिम्मेवारी लिनुहोस्"),
UPACHAYA_REC_HOUSE_11_1("Network and expand connections", "नेटवर्क र सम्बन्धहरू विस्तार गर्नुहोस्"),
UPACHAYA_REC_HOUSE_11_2("Pursue financial opportunities", "आर्थिक अवसरहरू पछ्याउनुहोस्"),
UPACHAYA_REC_HOUSE_11_3("Support friends and community", "साथीहरू र समुदायलाई समर्थन गर्नुहोस्"),
UPACHAYA_REC_SATURN_1("Work with discipline and patience", "अनुशासन र धैर्यका साथ काम गर्नुहोस्"),
UPACHAYA_REC_SATURN_2("Don't expect quick results", "छिटो परिणामको आशा नगर्नुहोस्"),
UPACHAYA_REC_SATURN_3("Honor commitments and responsibilities", "प्रतिबद्धता र जिम्मेवारीहरूको सम्मान गर्नुहोस्"),
UPACHAYA_REC_MARS_1("Channel energy constructively", "ऊर्जालाई रचनात्मक रूपमा प्रयोग गर्नुहोस्"),
UPACHAYA_REC_MARS_2("Avoid impulsive actions", "आवेगी कार्यहरूबाट बच्नुहोस्"),
UPACHAYA_REC_MARS_3("Physical exercise recommended", "शारीरिक व्यायाम सिफारिस गरिन्छ"),
UPACHAYA_REC_RAHU_1("Stay grounded amid opportunities", "अवसरहरूको बीचमा संयमित रहनुहोस्"),
UPACHAYA_REC_RAHU_2("Avoid shortcuts", "छोटो बाटोहरू नखोज्नुहोस्"),
UPACHAYA_REC_RAHU_3("Embrace innovation carefully", "सावधानीपूर्वक नवीनता अपनाउनुहोस्"),
UPACHAYA_REC_JUPITER_1("Expand through wisdom", "ज्ञान मार्फत विस्तार गर्नुहोस्"),
UPACHAYA_REC_JUPITER_2("Share knowledge generously", "उदारतापूर्वक ज्ञान साझा गर्नुहोस्"),
UPACHAYA_REC_JUPITER_3("Maintain ethical standards", "नैतिक मापदण्डहरू कायम राख्नुहोस्"),
UPACHAYA_HOUSE_NO_TRANSIT("No active Upachaya transits in %s house", "%s भावमा कुनै सक्रिय उपचय गोचर छैन"),
    UPACHAYA_HOUSE_PLANETS_COUNT("%d planet(s)", "%d planet(s)"),
UPACHAYA_SATURN_PROGRESS("Saturn brings slow, steady progress in %s", "शनिले %s मा ढिलो तर स्थिर प्रगति ल्याउँछ"),
UPACHAYA_MARS_PROGRESS("Mars energizes action in %s", "मंगलले %s मा कार्यलाई ऊर्जित गर्छ"),
UPACHAYA_JUPITER_PROGRESS("Jupiter expands opportunities in %s", "बृहस्पतिले %s मा अवसरहरू विस्तार गर्छ"),
UPACHAYA_ASSESS_NO_ACTIVE("No significant Upachaya transits currently active", "हाल कुनै महत्त्वपूर्ण उपचय गोचर सक्रिय छैन"),
UPACHAYA_ASSESS_WAIT("Wait for slow planets to enter Upachaya houses", "ढिलो हिड्ने ग्रहहरू उपचय भावहरूमा प्रवेश गर्ने प्रतीक्षा गर्नुहोस्"),
UPACHAYA_ASSESS_EXCEPTIONAL("Exceptional period! Multiple powerful transits favor growth in career, gains, and overcoming obstacles", "असाधारण अवधि! बहु शक्तिशाली गोचरहरूले क्यारियर, लाभ र बाधाहरू पार गर्न मद्दत गर्छन्"),
UPACHAYA_ASSESS_HIGH("Favorable period with strong Upachaya transits supporting professional and material growth", "व्यावसायिक र भौतिक वृद्धिलाई समर्थन गर्ने बलियो उपचय गोचरसहितको अनुकूल अवधि"),
UPACHAYA_ASSESS_MODERATE("Moderate Upachaya support - steady progress possible with focused effort", "मध्यम उपचय समर्थन - केन्द्रित प्रयासको साथ स्थिर प्रगति सम्भव छ"),
UPACHAYA_ASSESS_LOW("Limited Upachaya activation - focus on preparation for upcoming favorable transits", "सीमित उपचय सक्रियता - आगामी अनुकूल गोचरहरूको तयारीमा ध्यान दिनुहोस्"),
UPACHAYA_ASSESS_KEY_TRANSIT("%s in %s house is the key transit", "%s भावमा %s मुख्य गोचर हो"),
UPACHAYA_ASSESS_DAILY_ACTION("Focus on daily actions to maximize current transits", "वर्तमान गोचरहरूलाई अधिकतम बनाउन दैनिक कार्यहरूमा ध्यान दिनुहोस्"),
UPACHAYA_REC_BOLD_INITIATIVE("Take bold initiatives - courage is supported now", "साहसी पहलहरू गर्नुहोस् - साहस अहिले समर्थित छ"),
UPACHAYA_REC_HEALTH_CONFLICTS("Address health and resolve conflicts - victory over obstacles favored", "स्वास्थ्य र विवाद समाधानमा ध्यान दिनुहोस् - बाधाहरूमाथि विजय अनुकूल छ"),
UPACHAYA_REC_CAREER_FOCUS("Focus on career advancement - professional recognition possible", "क्यारियर प्रगतिमा ध्यान दिनुहोस् - व्यावसायिक मान्यता सम्भव छ"),
UPACHAYA_REC_FINANCIAL_GOALS("Pursue financial goals - gains and fulfillment of desires supported", "आर्थिक लक्ष्यहरू पछ्याउनुहोस् - लाभ र इच्छाहरूको पूर्ति समर्थित छ"),
UPACHAYA_REC_SLOW_PLANET("Major slow-planet transit active - commit to long-term goals", "प्रमुख ढिलो ग्रह गोचर सक्रिय छ - दीर्घकालीन लक्ष्यहरूमा प्रतिबद्ध रहनुहोस्"),
UPACHAYA_REC_PREPARE_UPCOMING("Prepare for upcoming Upachaya transits by organizing current affairs", "वर्तमान मामिलाहरू व्यवस्थित गरेर आगामी उपचय गोचरहरूको लागि तयारी गर्नुहोस्"),
UPACHAYA_ALERT_EXCELLENT("%s in %s house - Excellent opportunity period!", "%s भावमा %s - उत्कृष्ट अवसर अवधि!"),
UPACHAYA_ALERT_SATURN_10("Saturn transiting 10th house - Major career period! Work hard for lasting results", "शनिको १०औं भावमा गोचर - प्रमुख क्यारियर अवधि! स्थायी परिणामका लागि कडा परिश्रम गर्नुहोस्"),
UPACHAYA_ALERT_JUPITER_11("Jupiter transiting 11th house - Excellent for gains and fulfillment of desires!", "बृहस्पतिको ११औं भावमा गोचर - लाभ र इच्छाहरूको पूर्तिका लागि उत्कृष्ट!"),
UPACHAYA_UPCOMING_SIGNIFICANCE("When %s enters %s - %s activated", "जब %s ले %s मा प्रवेश गर्छ - %s सक्रिय हुन्छ"),
UPACHAYA_UPCOMING_REC("Prepare for %s related activities", "%s सम्बन्धित गतिविधिहरूको तयारी गर्नुहोस्"),
LAL_KITAB_TITLE("Lal Kitab Analysis", "लाल किताब विश्लेषण"),
LAL_KITAB_SUBTITLE("Traditional Remedial System", "परम्परागत उपचार प्रणाली"),
LAL_KITAB_ABOUT("About Lal Kitab", "लाल किताबको बारेमा"),
LAL_KITAB_ABOUT_DESC("Lal Kitab is a distinct astrological system with practical, cost-effective remedies. It differs from classical Vedic astrology in house analysis and remedy approach.", "लाल किताब व्यावहारिक, लागत-प्रभावी उपचारहरू भएको एक विशिष्ट ज्योतिष प्रणाली हो। यो भाव विश्लेषण र उपचार दृष्टिकोणमा शास्त्रीय वैदिक ज्योतिषभन्दा फरक छ।"),
LAL_KITAB_SYSTEM_NOTE("System Note", "प्रणाली नोट"),
LAL_KITAB_PLANETARY_AFFLICTIONS("Planetary Afflictions", "ग्रह पीडाहरू"),
    LAL_KITAB_KARMIC_DEBTS("Karmic Debts (Rin)", "Karmic Debts (Rin)"),
LAL_KITAB_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
LAL_KITAB_REMEDIES("Remedies", "उपायहरू"),
LAL_KITAB_COLOR_REMEDIES("Color Remedies", "रंग उपायहरू"),
LAL_KITAB_DIRECTION_REMEDIES("Direction Remedies", "दिशा उपायहरू"),
LAL_KITAB_ANNUAL_CALENDAR("Weekly Remedy Calendar", "साप्ताहिक उपाय पात्रो"),
LAL_KITAB_GENERAL_RECOMMENDATIONS("General Recommendations", "सामान्य सिफारिसहरू"),
LAL_KITAB_AFFLICTION_TYPE("Affliction Type", "पीडा प्रकार"),
LAL_KITAB_AFFLICTION_SEVERITY("Severity", "गम्भीरता"),
LAL_KITAB_PITRU_DOSH("Pitru Dosh", "पितृ दोष"),
LAL_KITAB_MATRU_RIN("Matru Rin", "मातृ ऋण"),
LAL_KITAB_STRI_RIN("Stri Rin", "स्त्री ऋण"),
LAL_KITAB_KANYA_RIN("Kanya Rin", "कन्या ऋण"),
LAL_KITAB_GRAHAN_DOSH("Grahan Dosh", "ग्रहण दोष"),
LAL_KITAB_SHANI_PEEDA("Shani Peeda", "शनि पीडा"),
LAL_KITAB_SEVERITY_MINIMAL("Minimal", "न्यूनतम"),
LAL_KITAB_SEVERITY_MILD("Mild", "हल्का"),
LAL_KITAB_SEVERITY_MODERATE("Moderate", "मध्यम"),
LAL_KITAB_SEVERITY_SEVERE("Severe", "गम्भीर"),
LAL_KITAB_DEBT_TYPE("Debt Type", "ऋण प्रकार"),
LAL_KITAB_DEBT_INDICATORS("Indicators", "सूचकहरू"),
LAL_KITAB_DEBT_EFFECTS("Effects", "प्रभावहरू"),
LAL_KITAB_HOUSE_STATUS("House Status", "भाव स्थिति"),
LAL_KITAB_HOUSE_EMPTY("Empty", "खाली"),
LAL_KITAB_HOUSE_OCCUPIED("Occupied", "भरिएको"),
LAL_KITAB_HOUSE_BENEFIC("Benefic Influence", "शुभ प्रभाव"),
LAL_KITAB_HOUSE_AFFLICTED("Afflicted", "पीडित"),
LAL_KITAB_REMEDY_CATEGORY("Remedy Category", "उपाय श्रेणी"),
LAL_KITAB_CATEGORY_PLANETARY("Planetary Remedy", "ग्रह उपाय"),
LAL_KITAB_CATEGORY_KARMIC("Karmic Debt Remedy", "कार्मिक ऋण उपाय"),
LAL_KITAB_CATEGORY_HOUSE("House-based Remedy", "भाव-आधारित उपाय"),
LAL_KITAB_CATEGORY_GENERAL("General Remedy", "सामान्य उपाय"),
LAL_KITAB_REMEDY_METHOD("Method", "विधि"),
LAL_KITAB_REMEDY_FREQUENCY("Frequency", "आवृत्ति"),
LAL_KITAB_REMEDY_DURATION("Duration", "अवधि"),
LAL_KITAB_REMEDY_EFFECTIVENESS("Effectiveness", "प्रभावकारिता"),
LAL_KITAB_FAVORABLE_COLORS("Favorable Colors", "शुभ रंगहरू"),
LAL_KITAB_AVOID_COLORS("Colors to Avoid", "परिहार गर्ने रंगहरू"),
LAL_KITAB_COLOR_APPLICATION("Application", "प्रयोग"),
LAL_KITAB_FAVORABLE_DIRECTION("Favorable Direction", "शुभ दिशा"),
LAL_KITAB_AVOID_DIRECTION("Direction to Avoid", "परिहार गर्ने दिशा"),
LAL_KITAB_DIRECTION_APPLICATION("Direction Application", "दिशा प्रयोग"),
LAL_KITAB_SUNDAY("Sunday - Sun", "आइतबार - सूर्य"),
LAL_KITAB_MONDAY("Monday - Moon", "सोमबार - चन्द्र"),
LAL_KITAB_TUESDAY("Tuesday - Mars", "मंगलबार - मंगल"),
LAL_KITAB_WEDNESDAY("Wednesday - Mercury", "बुधबार - बुध"),
LAL_KITAB_THURSDAY("Thursday - Jupiter", "बिहीबार - बृहस्पति"),
LAL_KITAB_FRIDAY("Friday - Venus", "शुक्रबार - शुक्र"),
LAL_KITAB_SATURDAY("Saturday - Saturn", "शनिबार - शनि"),
BHRIGU_BINDU_CALC_ERROR("Unable to calculate Bhrigu Bindu. Please check chart data.", "भृगु बिन्दु गणना गर्न असमर्थ। कृपया कुण्डली डाटा जाँच गर्नुहोस्।"),
POSITION_INTERPRETATION("Position Interpretation", "स्थिति व्याख्या"),
CURRENT_PLANETARY_POSITIONS("Current Planetary Positions", "वर्तमान ग्रह स्थितिहरू"),
UPCOMING_TRANSITS("Upcoming Significant Transits", "आगामी महत्त्वपूर्ण गोचरहरू"),
CONJUNCT("Conjunct", "युति"),
APPLYING("Applying", "लागू हुँदै"),
NAVAMSA_MARRIAGE_TITLE("Navamsa Marriage Analysis", "नवांश विवाह विश्लेषण"),
NAVAMSA_MARRIAGE_SUBTITLE("D-9 Partnership Timing", "D-9 साझेदारी समय"),
NAVAMSA_MARRIAGE_ABOUT("About Navamsa for Marriage", "विवाहको लागि नवांशको बारेमा"),
NAVAMSA_MARRIAGE_ABOUT_DESC("Navamsa is the most important divisional chart for marriage timing, spouse characteristics, and relationship quality.", "नवांश विवाह समय, जीवनसाथी विशेषताहरू, र सम्बन्ध गुणस्तरको लागि सबैभन्दा महत्त्वपूर्ण विभाजन चार्ट हो।"),
NAVAMSA_VENUS_POSITION("Venus in Navamsa", "नवांशमा शुक्र"),
NAVAMSA_7TH_LORD("7th Lord in Navamsa", "नवांशमा ७म स्वामी"),
NAVAMSA_SPOUSE_INDICATORS("Spouse Indicators", "जीवनसाथी सूचकहरू"),
NAVAMSA_MARRIAGE_TIMING("Marriage Timing", "विवाह समय"),
NAVAMSA_RELATIONSHIP_QUALITY("Relationship Quality", "सम्बन्ध गुणस्तर"),
    DASHAMSA_CAREER_TITLE("Dashamsa (D-10)", "Dashamsa (D-10)"),
DASHAMSA_CAREER_SUBTITLE("Professional Life and Status", "व्यावसायिक जीवन र स्थिति"),
DASHAMSA_CAREER_ABOUT("About Dashamsa Chart", "दशांश चार्टको बारेमा"),
DASHAMSA_CAREER_ABOUT_DESC("Dashamsa reveals career potential, professional achievements, and worldly status through 10th harmonic analysis.", "दशांशले १०औं हार्मोनिक विश्लेषण मार्फत करियर सम्भावना, व्यावसायिक उपलब्धि, र सांसारिक स्थिति प्रकट गर्दछ।"),
DASHAMSA_10TH_LORD("10th Lord in D-10", "D-10 मा १०औं स्वामी"),
DASHAMSA_LAGNA_LORD("D-10 Lagna Lord", "D-10 लग्न स्वामी"),
DASHAMSA_CAREER_HOUSES("Career Houses Analysis", "करियर भाव विश्लेषण"),
DASHAMSA_PROFESSION_TYPE("Profession Indicators", "पेशा सूचकहरू"),
DASHAMSA_STATUS_POTENTIAL("Status Potential", "स्थिति सम्भावना"),
    DWADASAMSA_TITLE("Dwadasamsa (D-12)", "Dwadasamsa (D-12)"),
DWADASAMSA_SUBTITLE("Parents and Ancestral Karma", "अभिभावक र पूर्वज कर्म"),
DWADASAMSA_ABOUT("About Dwadasamsa Chart", "द्वादशांश चार्टको बारेमा"),
DWADASAMSA_ABOUT_DESC("Dwadasamsa reveals parental relationships, ancestral inheritance, and genetic predispositions through 12th harmonic analysis.", "द्वादशांशले १२औं हार्मोनिक विश्लेषण मार्फत अभिभावक सम्बन्ध, पैतृक विरासत, र आनुवंशिक प्रवृत्तिहरू प्रकट गर्दछ।"),
    DWADASAMSA_SUN_POSITION("Sun in D-12 (Father)", "Sun in D-12 (Father)"),
    DWADASAMSA_MOON_POSITION("Moon in D-12 (Mother)", "Moon in D-12 (Mother)"),
DWADASAMSA_FATHER_ANALYSIS("Father Analysis", "बुबा विश्लेषण"),
DWADASAMSA_MOTHER_ANALYSIS("Mother Analysis", "आमा विश्लेषण"),
DWADASAMSA_ANCESTRAL_KARMA("Ancestral Karma", "पैतृक कर्म"),
DWADASAMSA_INHERITANCE("Inheritance Potential", "विरासत सम्भावना"),
    DIVISIONAL_HORA_TAB("Hora (D-2)", "Hora (D-2)"),
    DIVISIONAL_DREKKANA_TAB("Drekkana (D-3)", "Drekkana (D-3)"),
    DIVISIONAL_NAVAMSA_TAB("Navamsa (D-9)", "Navamsa (D-9)"),
    DIVISIONAL_DASHAMSA_TAB("Dashamsa (D-10)", "Dashamsa (D-10)"),
    DIVISIONAL_DWADASAMSA_TAB("Dwadasamsa (D-12)", "Dwadasamsa (D-12)"),
COURAGE_EXCEPTIONAL("Exceptional Courage", "असाधारण साहस"),
COURAGE_HIGH("High Courage", "उच्च साहस"),
COURAGE_MODERATE("Moderate Courage", "मध्यम साहस"),
COURAGE_DEVELOPING("Developing Courage", "विकासशील साहस"),
COURAGE_NEEDS_WORK("Needs Work", "काम आवश्यक"),
NAVAMSA_SPOUSE_TITLE("Spouse Characteristics", "जीवनसाथी विशेषताहरू"),
NAVAMSA_TIMING_TITLE("Marriage Timing", "विवाह समय"),
NAVAMSA_KEY_PLANETS_TITLE("Key Planets", "मुख्य ग्रहहरू"),
NAVAMSA_NATURE("General Nature", "सामान्य प्रकृति"),
NAVAMSA_PHYSICAL_TRAITS("Physical Traits", "शारीरिक लक्षण"),
NAVAMSA_FAMILY_BACKGROUND("Family Background", "पारिवारिक पृष्ठभूमि"),
NAVAMSA_DIRECTION("Direction", "दिशा"),
NAVAMSA_PROBABLE_PROFESSIONS("Probable Professions", "सम्भावित पेशाहरू"),
NAVAMSA_VENUS("Venus", "शुक्र"),
NAVAMSA_JUPITER("Jupiter", "बृहस्पति"),
NAVAMSA_7TH_LORD_LABEL("7th Lord", "७म स्वामी"),
NAVAMSA_DARAKARAKA("Darakaraka", "दाराकारक"),
NAVAMSA_FAVORABLE_DASHA("Favorable Dasha", "शुभ दशा"),
NAVAMSA_UPAPADA("Upapada Lagna", "उपपद लग्न"),
NAVAMSA_RELATIONSHIP_STABILITY("Relationship Stability", "सम्बन्ध स्थिरता"),
NAVAMSA_AREAS_ATTENTION("Areas for Attention", "ध्यान दिनुपर्ने क्षेत्रहरू"),
NAVAMSA_PROTECTIVE_FACTORS("Protective Factors", "रक्षात्मक कारकहरू"),
DASHAMSA_BUSINESS_VS_SERVICE("Business vs Service", "व्यापार बनाम सेवा"),
DASHAMSA_BUSINESS("Business Aptitude", "व्यापार योग्यता"),
DASHAMSA_SERVICE("Service Aptitude", "सेवा योग्यता"),
DASHAMSA_GOVT_SERVICE_TITLE("Government Service", "सरकारी सेवा"),
DASHAMSA_POTENTIAL("Potential", "सम्भावना"),
DASHAMSA_RECOMMENDED_AREAS("Recommended Areas", "सिफारिस गरिएका क्षेत्रहरू"),
DASHAMSA_PROFESSIONAL_STRENGTHS("Professional Strengths", "व्यावसायिक शक्तिहरू"),
DWADASAMSA_FATHER("Father", "बुबा"),
DWADASAMSA_MOTHER("Mother", "आमा"),
DWADASAMSA_INHERITANCE_TITLE("Inheritance Analysis", "विरासत विश्लेषण"),
DWADASAMSA_ANCESTRAL_PROPERTY("Ancestral Property", "पैतृक सम्पत्ति"),
DWADASAMSA_LONGEVITY_TITLE("Parental Longevity", "अभिभावक दीर्घायु"),
DWADASAMSA_POTENTIAL("Potential", "सम्भावना"),
DWADASAMSA_TIMING("Timing", "समय"),
DWADASAMSA_SOURCES("Sources", "स्रोतहरू"),
DWADASAMSA_SIGNIFICATOR("Significator", "कारक"),
DWADASAMSA_HOUSE_LORD("House Lord", "भाव स्वामी"),
DWADASAMSA_CHARACTERISTICS("Characteristics", "विशेषताहरू"),
DWADASAMSA_RELATIONSHIP("Relationship", "सम्बन्ध"),
MRITYU_BHAGA_SCREEN_TITLE("Mrityu Bhaga Analysis", "मृत्यु भाग विश्लेषण"),
MRITYU_BHAGA_SCREEN_SUBTITLE("Sensitive Degrees in Chart", "कुण्डलीमा संवेदनशील अंशहरू"),
MRITYU_BHAGA_SCREEN_ABOUT("About Mrityu Bhaga", "मृत्यु भागको बारेमा"),
MRITYU_BHAGA_SCREEN_ABOUT_DESC("Mrityu Bhaga refers to specific sensitive degrees in each zodiac sign. When planets occupy these degrees, they indicate areas of life requiring extra attention. These are sensitive points that may indicate health vulnerabilities or significant life challenges.", "मृत्यु भागले प्रत्येक राशिमा विशेष संवेदनशील अंशहरूलाई जनाउँछ। जब ग्रहहरू यी अंशहरूमा हुन्छन्, तिनीहरूले थप ध्यान चाहिने जीवनका क्षेत्रहरू संकेत गर्दछन्।"),
MRITYU_BHAGA_PLANETS_AFFECTED("Planets in Mrityu Bhaga", "मृत्यु भागमा ग्रहहरू"),
MRITYU_BHAGA_NO_PLANETS("No planets in Mrityu Bhaga", "मृत्यु भागमा कुनै ग्रह छैन"),
MRITYU_BHAGA_SENSITIVE_DEGREE("Sensitive Degree", "संवेदनशील अंश"),
MRITYU_BHAGA_ORB("Orb", "कोणान्तर"),
MRITYU_BHAGA_SEVERITY("Severity Level", "गम्भीरता स्तर"),
MRITYU_BHAGA_LIFE_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
MRITYU_BHAGA_REMEDIES_SECTION("Suggested Remedies", "सुझाव गरिएका उपायहरू"),
MRITYU_BHAGA_TRANSIT_WARNING("Transit Alerts", "गोचर चेतावनीहरू"),
MRITYU_BHAGA_SIGN_DEGREES("Mrityu Bhaga Degrees by Sign", "राशि अनुसार मृत्यु भाग अंशहरू"),
MRITYU_BHAGA_ALL_SIGNS("All Signs Reference", "सबै राशि सन्दर्भ"),
MRITYU_BHAGA_PRECAUTIONS("Precautionary Measures", "सावधानीका उपायहरू"),
MRITYU_BHAGA_GANDANTA_PLACEMENTS("Gandanta Placements", "गण्डान्त स्थितिहरू"),
MRITYU_BHAGA_AUSPICIOUS_PLACEMENTS("Auspicious Placements", "शुभ स्थितिहरू"),
MRITYU_BHAGA_NO_CRITICAL("Your chart is free from critical Mrityu Bhaga placements.", "तपाईंको कुण्डली गम्भीर मृत्यु भाग स्थितिहरूबाट मुक्त छ।"),
MRITYU_BHAGA_LEVEL_NEEDS_ATTENTION("Needs Attention", "ध्यान दिन आवश्यक"),
MRITYU_BHAGA_LEVEL_MODERATE_CONCERN("Moderate Concern", "मध्यम चिन्ता"),
MRITYU_BHAGA_LEVEL_BALANCED("Balanced", "सन्तुलित"),
MRITYU_BHAGA_LEVEL_GENERALLY_POSITIVE("Generally Positive", "सामान्यतया सकारात्मक")
}
