package com.astro.storm.core.common
enum class StringKeyUI(override val en: String, override val ne: String) : StringKeyInterface {
LABEL_UNKNOWN("Unknown", "अज्ञात"),
LABEL_REQUIRED("Required:", "आवश्यक:"),
LABEL_REQUIRED_VALUE("Required: %s", "आवश्यक: %s"),
LABEL_RUPAS("Rupas", "रूपा"),
LABEL_PERCENT_REQUIRED("% of required", "आवश्यकको %"),
LABEL_PERCENT_REQUIRED_VALUE("%s%% of required", "आवश्यकको %s%%"),
LABEL_TODAY("Today", "आज"),
LABEL_PREVIOUS_MONTH("Previous month", "अघिल्लो महिना"),
LABEL_NEXT_MONTH("Next month", "अर्को महिना"),
LABEL_AD("AD", "ई.सं."),
LABEL_BS("BS", "बि.सं."),
COLOR_RED_ORANGE_GOLD("Red, Orange, or Gold", "रातो, सुन्तला, वा सुनौलो"),
COLOR_GREEN_BROWN_WHITE("Green, Brown, or White", "हरियो, खैरो, वा सेतो"),
COLOR_BLUE_LIGHT_SILVER("Blue, Light Blue, or Silver", "निलो, हल्का निलो, वा चाँदी"),
COLOR_WHITE_CREAM_SEA("White, Cream, or Sea Green", "सेतो, क्रिम, वा समुद्री हरियो"),
GEMSTONE_RUBY("Ruby", "माणिक"),
GEMSTONE_PEARL("Pearl", "मोती"),
GEMSTONE_RED_CORAL("Red Coral", "मूंगा"),
GEMSTONE_EMERALD("Emerald", "पन्ना"),
GEMSTONE_YELLOW_SAPPHIRE("Yellow Sapphire", "पुखराज"),
GEMSTONE_DIAMOND("Diamond/White Sapphire", "हीरा/सेतो नीलम"),
GEMSTONE_BLUE_SAPPHIRE("Blue Sapphire", "नीलम"),
GEMSTONE_HESSONITE("Hessonite", "गोमेद"),
GEMSTONE_CATS_EYE("Cat's Eye", "लहसुनिया"),
DIGNITY_EXALTED("Exalted", "उच्च"),
DIGNITY_MOOLATRIKONA("Moolatrikona", "मूलत्रिकोण"),
DIGNITY_OWN_SIGN("Own Sign", "स्वराशि"),
DIGNITY_GREAT_FRIEND("Great Friend", "अधिमित्र"),
DIGNITY_FRIEND("Friend", "मित्र"),
DIGNITY_NEUTRAL("Neutral", "सम"),
DIGNITY_ENEMY("Enemy", "शत्रु"),
DIGNITY_GREAT_ENEMY("Great Enemy", "अधिशत्रु"),
DIGNITY_DEBILITATED("Debilitated", "नीच"),
STRENGTH_EXCELLENT("Excellent", "उत्कृष्ट"),
STRENGTH_GOOD("Good", "राम्रो"),
STRENGTH_AVERAGE("Average", "औसत"),
STRENGTH_WEAK("Weak", "कमजोर"),
STRENGTH_VERY_WEAK("Very Weak", "अति कमजोर"),
STRENGTH_FACTORS("Strength Factors", "बल कारकहरू"),
STRENGTH_LABEL("Strength", "बल"),
SCREEN_CALCULATING("Calculating analysis...", "विश्लेषण गणना गर्दै..."),
SCREEN_NO_DATA("No data available", "कुनै डाटा उपलब्ध छैन"),
SCREEN_ERROR_CALCULATION("Error calculating results", "परिणाम गणनामा त्रुटि"),
SCREEN_OVERVIEW("Overview", "सिंहावलोकन"),
SCREEN_DETAILS("Details", "विवरणहरू"),
SCREEN_TIMELINE("Timeline", "समयरेखा"),
SCREEN_INTERPRETATION("Interpretation", "व्याख्या"),
SCREEN_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
BTN_GOT_IT("Got it", "बुझें"),
UI_NO_CHART_DATA("No Chart Data", "कुन्डली डाटा उपलब्ध छैन"),
UI_NO_BIRTH_CHART("No Birth Chart", "कुनै जन्म कुन्डली छैन"),
UI_SELECT_CHART("Please select a birth chart", "कृपया जन्म कुन्डली चयन गर्नुहोस्"),
UI_ERROR_LOADING("Error loading chart", "कुन्डली लोड गर्दा त्रुटि"),
UI_NO_ASHTAKAVARGA_DATA("No Ashtakavarga Data", "अष्टकवर्ग डाटा छैन"),
UI_NO_ARUDHA_YOGAS("No significant Arudha Yogas found", "कुनै महत्त्वपूर्ण आरुढ योग फेला परेन"),
UI_NO_ACTIVE_SANDHI("No Active Sandhi", "कुनै सक्रिय सन्धि छैन"),
UI_NO_UPCOMING_SANDHI("No upcoming Sandhi periods in the analysis window.", "विश्लेषण अवधिमा कुनै आगामी सन्धि अवधि छैन।"),
UI_NO_CALENDAR_ENTRIES("No calendar entries available.", "कुनै क्यालेन्डर प्रविष्टिहरू उपलब्ध छैनन्।"),
UI_NO_ACTIVE_VEDHAS("No Active Vedhas", "कुनै सक्रिय वेध छैन"),
UI_NO_PLANET_WARS("No Active Planetary Wars", "कुनै सक्रिय ग्रह युद्ध छैन"),
UI_NO_WAR_DASHA("No War-Related Dasha Effects", "कुनै युद्ध-सम्बन्धित दशा प्रभावहरू छैन"),
UI_NO_WAR_REMEDIES("No Specific Remedies Needed", "कुनै विशिष्ट उपाय आवश्यक छैन"),
UI_NO_ACTIVE_WAR_REMEDIES("No active wars to remediate", "उपचार गर्न कुनै सक्रिय युद्ध छैन"),
UI_KEMADRUMA_CONDITION_MET("No planets in houses adjacent to Moon - Kemadruma condition met", "चन्द्रमाको छेउका भावहरूमा कुनै ग्रह छैन - केमद्रुम अवस्था पूरा भयो"),
UI_NO_REMEDIES_NEEDED("No Remedies Needed", "कुनै उपाय आवश्यक छैन"),
UI_NO_YOGAS_FORMED("No Yogas Formed", "कुनै योग बनेको छैन"),
UI_NO_YOGAS_DISPLAY("No Yogas to Display", "देखाउनको लागि कुनै योग छैन"),
UI_INTERPRETATION("Interpretation", "व्याख्या"),
UI_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
UI_OVERVIEW("Overview", "अवलोकन"),
UI_YOGAS("Yogas", "योगहरू"),
UI_EFFECTS("Effects", "प्रभावहरू"),
UI_TIMING("Timing", "समय"),
UI_REMEDIES("Remedies", "उपायहरू"),
UI_TRANSITS("Transits", "गोचरहरू"),
UI_CURRENT("Current", "वर्तमान"),
UI_UPCOMING("Upcoming", "आगामी"),
UI_CALENDAR("Calendar", "पात्रो"),
UI_KEY_INSIGHTS("Key Insights", "मुख्य अन्तरदृष्टिहरू"),
UI_START("Start:", "सुरु:"),
UI_END("End:", "अन्त्य:"),
COLOR_ORANGE("Orange", "सुन्तला"),
COLOR_GOLD("Gold", "सुनौलो"),
COLOR_RED("Red", "रातो"),
COLOR_WHITE("White", "सेतो"),
COLOR_SILVER("Silver", "चाँदी"),
COLOR_PEARL("Pearl White", "मोती"),
COLOR_CORAL("Coral", "मुगा रंग"),
COLOR_SCARLET("Scarlet", "सिन्दूरे"),
COLOR_GREEN("Green", "हरियो"),
COLOR_EMERALD("Emerald", "पन्ना"),
COLOR_TURQUOISE("Turquoise", "फिरोजा"),
COLOR_YELLOW("Yellow", "हेलों"),
COLOR_PINK("Pink", "गुलाबी"),
COLOR_PASTEL("Pastel", "पास्टेल"),
COLOR_BLUE("Blue", "नीलो"),
COLOR_BLACK("Black", "कालो"),
COLOR_DARK("Dark colors", "गाढा रंगहरू"),
COLOR_SMOKY("Smoky", "धुवाँ"),
COLOR_GREY("Grey", "खरानी"),
COLOR_MIXED("Mixed colors", "मिश्रित रंगहरू"),
COLOR_BROWN("Brown", "खैरो"),
COLOR_MULTI("Multi-colored", "बहुरंगी"),
UI_DETAILS("Details", "विवरण"),
UI_ANALYSIS_ERROR("Analysis Error", "विश्लेषण त्रुटि"),
UI_FAVORABLE_PERIOD("Favorable Period", "अनुकूल अवधि"),
UI_MIXED_PERIOD("Mixed Period", "मिश्रित अवधि"),
UI_CAUTION_PERIOD("Caution Period", "सावधानी अवधि"),
UI_TRANSIT_SUMMARY("Transit Summary", "गोचर सारांश"),
UI_AFFECTED_AREAS("Affected Areas", "प्रभावित क्षेत्रहरू"),
UI_UPCOMING_TRANSITS("Upcoming Transits", "आगामी गोचरहरू"),
UI_VERY_HIGH("Very High", "अत्यन्त उच्च"),
UI_HIGH("High", "उच्च"),
UI_MODERATE("Moderate", "मध्यम"),
UI_LOW("Low", "न्यून"),
UI_NONE("None", "केही छैन"),
UI_BIRTH_PANCHANGA("Birth Panchanga", "जन्म पञ्चाङ्ग"),
UI_BIRTH_DAY_SIGNIFICANCE("Birth Day Significance", "जन्म दिनको महत्त्व"),
UI_PANCHANGA_UNAVAILABLE("Panchanga Unavailable", "पञ्चाङ्ग उपलब्ध छैन"),
UI_UNABLE_CALC_PANCHANGA("Unable to calculate Panchanga for today", "आजको पञ्चाङ्ग गणना गर्न असमर्थ"),
UI_SELECT_CHART_PANCHANGA("Please select a birth chart to view birth Panchanga", "जन्म पञ्चाङ्ग हेर्न कृपया जन्म कुण्डली छान्नुहोस्"),
UI_AVOID_ACTIVITIES("Avoid important activities", "महत्त्वपूर्ण गतिविधिहरूबाट बच्नुहोस्"),
UI_AUSPICIOUS_TIMING("Auspicious timing", "शुभ समय"),
UI_IN_DAYS_FMT("In %d days", "%d दिनमा"),
UI_YOGAS_FOUND_FMT("%1\$d yogas found - %2\$s", "%2\$s मा %1\$d योगहरू फेला परे"),
UI_ALL_COUNT_FMT("All (%d)", "सबै (%d)"),
UI_SORT_BY("Sort by", "क्रमबद्ध गर्नुहोस्"),
UI_EXIT_DATE("Exit Date", "निस्कने मिति"),
UI_FROM_MOON("From Moon", "चन्द्रबाट"),
UI_FROM_LAGNA("From Lagna", "लग्नबाट"),
UI_SIGNIFICANT_ONLY("Significant only", "महत्त्वपूर्ण मात्र"),
UI_FAVORABLE_SIGNS("Favorable Signs", "अनुकूल राशिहरू"),
UI_UNFAVORABLE_SIGNS("Unfavorable Signs", "प्रतिकूल राशिहरू"),
UI_GENERAL_NATURE("General Nature", "सामान्य प्रकृति"),
UI_HEALTH_INDICATIONS("Health Indications", "स्वास्थ्य संकेतहरू"),
UI_FINANCIAL_INDICATIONS("Financial Indications", "आर्थिक संकेतहरू"),
UI_RELATIONSHIP_INDICATIONS("Relationship Indications", "सम्बन्ध संकेतहरू"),
UI_TIMING_GUIDANCE("Timing Guidance", "समय मार्गदर्शन"),
UI_BEST_HOURS("Best Hours", "उत्तम समय"),
UI_HOURS_TO_AVOID("Hours to Avoid", "बच्नुपर्ने समय"),
UI_BENEFIC_STRENGTH("Benefic Strength", "शुभ बल"),
UI_MALEFIC_STRENGTH("Malefic Strength", "अशुभ बल"),
UI_NET_STRENGTH_FMT("Net Strength: %s", "कुल बल: %s"),
UI_ARGALA_INFLUENCES("Argala Influences", "अर्गला प्रभावहरू"),
UI_OBSTRUCTIONS_RECEIVED("Obstructions Received", "प्राप्त अवरोधहरू"),
UI_KEY_CONCEPTS("Key Concepts:", "मुख्य अवधारणाहरू:"),
UI_JAIMINI_SOURCE("Source: Jaimini Sutras (Chapter 1, Pada 1, Sutras 5-8)", "स्रोत: जैमिनी सूत्र (अध्याय १, पाद १, सूत्र ५-८)"),
UI_NO_AI_MODEL("No AI model configured. Please set up an AI provider in settings.", "कुनै AI मोडेल कन्फिगर गरिएको छैन। कृपया सेटिङ्समा AI प्रदायक सेटअप गर्नुहोस्।"),
UI_FAILED_GENERATE_INSIGHT("Failed to generate insight", "अन्तर्दृष्टि उत्पन्न गर्न असफल"),
UI_YES("Yes", "हो"),
UI_NO("No", "होइन"),
UI_WAXING("Waxing", "शुक्ल पक्ष"),
UI_WANING("Waning", "कृष्ण पक्ष"),
UI_RISING_SIGN("Rising Sign", "उदित राशि"),
UI_IN_HOUSE_FMT("In House %d", "भाव %d मा"),
DIGNITY_FRIENDLY("in the friendly sign of %s", "%s मित्र राशिमा"),
DIGNITY_KENDRA("in an angular house (Kendra)", "केन्द्र भावमा"),
DIGNITY_TRIKONA("in a trine house (Trikona)", "त्रिकोण भावमा"),
DIGNITY_GAINS("in a house of gains", "लाभ भावमा"),
DIGNITY_UPACHAYA("in an upachaya house", "उपचय भावमा"),
DIGNITY_DUSTHANA("in a challenging house (Dusthana)", "दुःस्थान भावमा"),
DIGNITY_RETROGRADE("and is retrograde", "र वक्री छ"),
DIGNITY_YEARLORD_DESC("The Year Lord %s is %s. This suggests its influence will be potent and its results will manifest clearly throughout the year.", "वर्ष स्वामी %s %s छ। यसले संकेत गर्छ कि यसको प्रभाव शक्तिशाली हुनेछ र यसको परिणामहरू वर्षभर स्पष्ट रूपमा प्रकट हुनेछन्।"),
DIGNITY_EXALTED_STATUS("Exalted", "उच्च"),
DIGNITY_DEBILITATED_STATUS("Debilitated", "नीच"),
DIGNITY_OWN_SIGN_STATUS("Own Sign", "स्वराशि"),
DIGNITY_NEUTRAL_STATUS("Neutral", "तटस्थ"),
STRENGTH_EXTREMELY_WEAK("Extremely Weak", "अत्यन्त कमजोर"),
STRENGTH_BELOW_AVERAGE("Below Average", "औसतभन्दा कम"),
STRENGTH_ABOVE_AVERAGE("Above Average", "औसतभन्दा माथि"),
STRENGTH_STRONG("Strong", "बलियो"),
STRENGTH_VERY_STRONG("Very Strong", "अत्यन्त बलियो"),
STRENGTH_EXTREMELY_STRONG("Extremely Strong", "अति शक्तिशाली"),
STRENGTH_MODERATE("Moderate", "मध्यम"),
STRENGTH_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
STRENGTH_DIFFICULT("Difficult", "कठिन"),
GENDER_MALE("Male", "पुरुष"),
GENDER_FEMALE("Female", "स्त्री"),
STRENGTH_ERROR("Error", "त्रुटि"),
STRENGTH_ASCENDANT("Ascendant", "लग्न"),
COLOR_LIGHT_BLUE("Light Blue", "हल्का नीलो"),
COLOR_SEA_GREEN("Sea Green", "समुद्री हरियो"),
COLOR_PURPLE("Purple", "बैजनी"),
COLOR_CREAM("Cream", "क्रीम"),
COLOR_MAROON("Maroon", "मरुन"),
COLOR_INDIGO("Indigo", "इन्डिगो"),
UI_CONJUNCTION("conjunction", "युति"),
UI_ASPECT("aspect", "दृष्टि"),
UI_EXCHANGE("exchange", "परिवर्तन"),
UI_THROUGHOUT_LIFE("Throughout life", "जीवनभर"),
UI_PRESENT("Present", "उपस्थित"),
UI_ASCENDING("Ascending", "आरोही"),
UI_DESCENDING("Descending", "अवरोही"),
UI_NAKSHATRAS("nakshatras", "नक्षत्रहरू"),
TAB_OVERVIEW("Overview", "सिंहावलोकन"),
TAB_REMEDIES("Remedies", "उपायहरू"),
TAB_PLANETS("Planets", "ग्रहहरू"),
TAB_TODAY("Today", "आज"),
TAB_FIND_MUHURTA("Find Muhurta", "मुहूर्त खोज्नुहोस्"),
TAB_TAJIKA("Tajika", "ताजिक"),
TAB_SAHAMS("Sahams", "सहमहरू"),
TAB_DASHA("Dasha", "दशा"),
TAB_HOUSES("Houses", "भावहरू"),
TAB_ANALYSIS("Analysis", "विश्लेषण"),
TAB_DETAILS("Details", "विवरणहरू"),
TAB_TRANSITS("Transits", "गोचर"),
TAB_ASPECTS("Aspects", "दृष्टि"),
TAB_STRENGTH("Strength", "बल"),
TAB_DIGNITIES("Dignities", "मर्यादाहरू"),
ACC_VIEW_DETAILS("View details", "विवरण हेर्नुहोस्"),
ACC_COLLAPSE("Collapse", "लुकाउनुहोस्"),
ACC_EXPAND("Expand", "देखाउनुहोस्"),
ACC_FULLSCREEN("View fullscreen", "पूरा स्क्रीन हेर्नुहोस्"),
ACC_CHART_ANALYSIS("Chart analysis", "कुण्डली विश्लेषण"),
ACC_COMING_SOON("Coming soon", "चाँडै आउँदैछ"),
ACC_PROFILE_AVATAR("Profile avatar", "प्रोफाइल अवतार"),
LABEL_NA("N/A", "-"),
LABEL_DASH("-", "-"),
BTN_CREATE_CHART("Create New Chart", "नयाँ कुण्डली बनाउनुहोस्"),
BTN_VIEW_DETAILS("View Details", "विवरण हेर्नुहोस्"),
BTN_RETRY("Retry", "फेरि प्रयास गर्नुहोस्"),
BTN_TRY_AGAIN("Try Again", "फेरि प्रयास गर्नुहोस्"),
BTN_PREVIEW("Preview", "पूर्वावलोकन"),
BTN_DELETE("Delete", "मेटाउनुहोस्"),
BTN_CANCEL("Cancel", "रद्ध गर्नुहोस्"),
TAB_HOME("Home", "गृह"),
TAB_INSIGHTS("Insights", "अन्तर्दृष्टि"),
TAB_CHAT("Chat", "च्याट"),
TAB_SETTINGS("Settings", "सेटिङ्स"),
BTN_DETAILS("Details", "विवरण"),
BTN_OK("OK", "ठीक छ"),
BTN_JUMP_TODAY("Jump to today", "आजमा जानुहोस्"),
BTN_EDIT("Edit", "सम्पादन गर्नुहोस्"),
BTN_SAVE("Save", "सेभ गर्नुहोस्"),
BTN_GENERATE("Generate", "उत्पन्न गर्नुहोस्"),
BTN_GENERATE_SAVE("Generate & Save", "उत्पन्न गर्नुहोस् र सेभ गर्नुहोस्"),
BTN_UPDATE_SAVE("Update & Save", "अपडेट गर्नुहोस् र सेभ गर्नुहोस्"),
BTN_GO_BACK("Go back", "पछाडि जानुहोस्"),
BTN_BACK("Back", "पछाडि"),
BTN_CLOSE("Close", "बन्द गर्नुहोस्"),
BTN_REFRESH("Refresh", "रिफ्रेस"),
BTN_REGENERATE("Regenerate", "पुन: उत्पन्न"),
GENDER_OTHER("Other", "अन्य"),
TAB_BY_PLANET("By Planet", "ग्रहानुसार"),
TAB_BY_HOUSE("By House", "भावानुसार"),
TAB_ELEMENTS("Elements", "तत्वहरू"),
TAB_BIRTH_DAY("Birth Day", "जन्म दिन"),
TAB_CURRENT_POSITIONS("Current Positions", "हालको स्थिति"),
TAB_UPCOMING("Upcoming", "आगामी"),
TAB_SARVASHTAKAVARGA("Sarvashtakavarga", "सर्वाष्टकवर्ग"),
A11Y_EXPAND("Expand", "विस्तार गर्नुहोस्"),
A11Y_COLLAPSE("Collapse", "संक्षिप्त गर्नुहोस्"),
A11Y_NAVIGATE_BACK("Navigate back", "पछाडि जानुहोस्"),
A11Y_SHOW_INFO("Show information", "जानकारी देखाउनुहोस्")
}
