package com.astro.storm.core.common
enum class StringKeyMatchPart2(override val en: String, override val ne: String) : StringKeyInterface {
ACTION_LEGAL_MATTERS("Legal matters", "कानुनी मामिलाहरू"),
NAV_BACK("Back", "पछाडि"),
NAV_NAVIGATE_BACK("Navigate back", "पछाडि जानुहोस्"),
NAV_PREVIOUS("Previous", "अघिल्लो"),
NAV_NEXT("Next", "अर्को"),
NAV_PREVIOUS_YEAR("Previous year", "अघिल्लो वर्ष"),
NAV_NEXT_YEAR("Next year", "अर्को वर्ष"),
NAV_PREVIOUS_DAY("Previous day", "अघिल्लो दिन"),
NAV_NEXT_DAY("Next day", "अर्को दिन"),
ACTION_EXPORT("Export", "निर्यात गर्नुहोस्"),
ACTION_CLEAR("Clear", "खाली गर्नुहोस्"),
ACTION_CLEAR_SEARCH("Clear search", "खोज खाली गर्नुहोस्"),
ACTION_COPY("Copy", "कपी गर्नुहोस्"),
ACTION_COPY_MANTRA("Copy mantra", "मन्त्र कपी गर्नुहोस्"),
ACTION_VIEW_DETAILS("View details", "विवरणहरू हेर्नुहोस्"),
ACTION_VIEW_FULLSCREEN("View fullscreen", "पूर्ण स्क्रिनमा हेर्नुहोस्"),
ACTION_NEW_QUESTION("New question", "नयाँ प्रश्न"),
ACTION_SEARCH("Search", "खोज्नुहोस्"),
MISC_DAYS_LEFT("days left", "दिन बाँकी"),
MISC_MONTHS("months", "महिना"),
MISC_CURRENT("Current", "वर्तमान"),
MISC_YEARS("years", "वर्ष"),
DASHA_NO_CURRENT_PERIOD("No current period active", "कुनै वर्तमान अवधि सक्रिय छैन"),
DASHA_LEVEL_ANTARDASHAS("Antardashas", "अन्तर्दशाहरू"),
INTERPRETATION_TITLE("Interpretation", "व्याख्या"),
INTERPRETATION_GENERAL("General Effects", "सामान्य प्रभावहरू"),
INTERPRETATION_LORD_EFFECTS("Lord Effects", "स्वामी प्रभावहरू"),
INTERPRETATION_FAVORABLE("Favorable Areas", "अनुकूल क्षेत्रहरू"),
INTERPRETATION_CHALLENGES("Challenges", "चुनौतीहरू"),
INTERPRETATION_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
DASHA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
CHART_LAGNA("Lagna", "लग्न"),
CHART_MOON("Moon", "चन्द्रमा"),
CHART_SUN("Sun", "सूर्य"),
CHART_NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
CHART_ASCENDANT_LABEL("Ascendant", "लग्न"),
THEME_LIGHT("Light", "उज्यालो"),
THEME_DARK("Dark", "गाढा"),
THEME_SYSTEM("System", "सिस्टम"),
THEME_DESC_LIGHT("Always use light theme", "सधैं उज्यालो थीम प्रयोग गर्नुहोस्"),
THEME_DESC_DARK("Always use dark theme", "सधैं गाढा थीम प्रयोग गर्नुहोस्"),
THEME_DESC_SYSTEM("Follow device settings", "डिभाइस सेटिङ अनुसरण गर्नुहोस्"),
SETTINGS_THEME_TITLE("Theme", "थीम"),
NAV_HOME("Home", "गृह"),
NAV_INSIGHTS("Insights", "अन्तर्दृष्टि"),
NAV_CHAT("Chat", "कुराकानी"),
NAV_SETTINGS("Settings", "सेटिङहरू"),
HOME_CHART_ANALYSIS("Your Chart Analysis", "तपाईंको कुण्डली विश्लेषण"),
HOME_COMING_SOON("Coming Soon", "चाँडै आउँदैछ"),
HOME_SOON_BADGE("Soon", "चाँडै"),
NO_PROFILE_SELECTED("No Profile Selected", "कुनै प्रोफाइल छानिएको छैन"),
NO_PROFILE_MESSAGE("Create or select a profile to view personalized insights and charts.", "व्यक्तिगत अन्तर्दृष्टि र कुण्डलीहरू हेर्न प्रोफाइल बनाउनुहोस् वा छान्नुहोस्।"),
TRANSITS_MOON_IN("Moon in {0}", "{0}मा चन्द्रमा"),
SETTINGS_PROFILE("Profile", "प्रोफाइल"),
SETTINGS_EDIT_PROFILE("Edit Profile", "प्रोफाइल सम्पादन गर्नुहोस्"),
SETTINGS_EDIT_PROFILE_DESC("Modify current charts details", "हालको कुण्डली विवरण परिमार्जन गर्नुहोस्"),
SETTINGS_MANAGE_PROFILES("Manage Profiles", "प्रोफाइलहरू व्यवस्थापन गर्नुहोस्"),
SETTINGS_NO_PROFILE("No Profile", "कुनै प्रोफाइल छैन"),
SETTINGS_TAP_TO_SELECT("Tap to create or select a profile", "प्रोफाइल बनाउन वा छान्न ट्याप गर्नुहोस्"),
SETTINGS_EXPORT("Export", "निर्यात"),
SETTINGS_EXPORT_PDF("Export as PDF", "PDF को रूपमा निर्यात गर्नुहोस्"),
SETTINGS_EXPORT_PDF_DESC("Save chart details as PDF file", "कुण्डली विवरण PDF फाइलको रूपमा बचत गर्नुहोस्"),
SETTINGS_AI_CHAT("AI & Chat", "AI र कुराकानी"),
SETTINGS_AI_MODELS("AI Models", "AI मोडेलहरू"),
SETTINGS_AI_MODELS_DESC("Configure AI model settings", "AI मोडेल सेटिङहरू कन्फिगर गर्नुहोस्"),
SETTINGS_PREFERENCES("Preferences", "प्राथमिकताहरू"),
SETTINGS_LANGUAGE("Language", "भाषा"),
SETTINGS_HOUSE_SYSTEM("House System", "भाव प्रणाली"),
SETTINGS_ABOUT("About", "बारेमा"),
SETTINGS_ABOUT_APP("AstroStorm", "एस्ट्रोस्टर्म"),
SETTINGS_VERSION("Version {0}", "संस्करण {0}"),
SETTINGS_CALC_ENGINE("Calculation Engine", "गणना इन्जिन"),
SETTINGS_CALC_ENGINE_DESC("Swiss Ephemeris & Vedic Algorithms", "स्विस एफिमेरिस र वैदिक एल्गोरिदमहरू"),
DIALOG_DELETE_PROFILE("Delete Profile", "प्रोफाइल मेटाउनुहोस्"),
DIALOG_DELETE_CONFIRM("Are you sure you want to delete profile ''{0}''? This action cannot be undone.", "के तपाईं साँच्चिकै ''{0}'' प्रोफाइल मेटाउन चाहनुहुन्छ? यो कार्य पूर्ववत गर्न सकिँदैन।")
}
