package com.astro.storm.core.common

enum class StringKeyGeneralPart8(override val en: String, override val ne: String) : StringKeyInterface {
    PLACEMENT_INTERP_SUN_1("Strong personality with natural leadership abilities. You have a prominent presence and strong willpower. May indicate good health and vitality.", "प्राकृतिक नेतृत्व क्षमताको साथ बलियो व्यक्तित्व। तपाईंसँग प्रमुख उपस्थिति र बलियो इच्छाशक्ति छ। राम्रो स्वास्थ्य र जीवनशक्तिको संकेत गर्न सक्छ।"),
    PLACEMENT_INTERP_SUN_10("Excellent position for career success and recognition. Natural authority in professional life. Government positions or leadership roles favored.", "करियर सफलता र मान्यताको लागि उत्कृष्ट स्थिति। व्यावसायिक जीवनमा प्राकृतिक अधिकार। सरकारी पद वा नेतृत्व भूमिकाहरू अनुकूल छन्।"),
    PLACEMENT_INTERP_VENUS_4("Luxurious home and vehicles. Good relationship with mother. Domestic happiness and artistic home environment.", "विलासी घर र सवारी साधनहरू। आमासँग राम्रो सम्बन्ध। पारिवारिक खुसी र कलात्मक घरको वातावरण।"),
    PLACEMENT_INTERP_VENUS_7("Beautiful spouse and harmonious marriage. Success in partnerships and business. Diplomatic abilities.", "सुन्दर जीवनसाथी र सामंजस्यपूर्ण विवाह। साझेदारी र व्यापारमा सफलता। कूटनीतिक क्षमताहरू।"),
    PLANET("Planet", "ग्रह"),
    PLANETARY_STATUS_COMBUST("Combust", "अस्त"),
    PLANETARY_STATUS_DEBILITATED("Debilitated", "नीच"),
    PLANETARY_STATUS_ENEMY_SIGN("Enemy Sign", "शत्रु राशि"),
    PLANETARY_STATUS_EXALTED("Exalted", "उच्च"),
    PLANETARY_STATUS_FRIENDLY("Friendly", "मित्र"),
    PLANETARY_STATUS_MOOLATRIKONA("Moolatrikona", "मूलत्रिकोण"),
    PLANETARY_STATUS_OWN_SIGN("Own Sign", "स्वराशि"),
    PLANETARY_STATUS_RETROGRADE("Retrograde", "वक्री"),
    PLANETARY_STRENGTH_AFFLICTED("Afflicted", "पीडित"),
    PLANETARY_STRENGTH_MODERATE("Moderate", "मध्यम"),
    PLANETARY_STRENGTH_STRONG("Strong", "बलियो"),
    PLANETARY_STRENGTH_VERY_STRONG("Very Strong", "धेरै बलियो"),
    PLANETARY_STRENGTH_VERY_WEAK("Very Weak", "धेरै कमजोर"),
    PLANETARY_STRENGTH_WEAK("Weak", "कमजोर"),
    PLANETS_AT_WAR("At War", "युद्धमा"),
    PLANETS_COMBUST("Combust", "अस्त"),
    PLANETS_CONDITIONS("Planetary Conditions", "ग्रह अवस्थाहरू"),
    PLANETS_HOUSE_FORMAT("House %d", "भाव %d"),
    PLANETS_OVERALL("Overall", "समग्र"),
    PLANETS_PLANETARY_WAR("Planetary War", "ग्रहयुद्ध"),
    PLANETS_RETROGRADE("Retrograde", "वक्री"),
    PLANETS_RUPAS("%s / %s rupas (%s%%)", "%s / %s रुपा (%s%%)"),
    PLANETS_SHADBALA("Shadbala", "षड्बल"),
    PLANETS_SHADBALA_SUMMARY("Shadbala Summary", "षड्बल सारांश"),
    PLANETS_TAP_FOR_DETAILS("Tap for details", "विवरणको लागि ट्याप गर्नुहोस्"),
    PLANETS_TITLE("Transiting Planets", "गोचर ग्रहहरू"),
    PLANETS_VIEW_DETAILS("View Details", "विवरण हेर्नुहोस्"),
    PLANET_DAY_JUPITER("Thursday", "बिहिबार"),
    PLANET_DAY_KETU("Tuesday", "मंगलबार"),
    PLANET_DAY_MARS("Tuesday", "मंगलबार"),
    PLANET_DAY_MERCURY("Wednesday", "बुधबार"),
    PLANET_DAY_MOON("Monday", "सोमबार"),
    PLANET_DAY_RAHU("Saturday", "शनिबार"),
    PLANET_DAY_SATURN("Saturday", "शनिबार"),
    PLANET_DAY_SUN("Sunday", "आइतबार"),
    PLANET_DAY_VENUS("Friday", "शुक्रबार"),
    PLANET_HEALTH_TITLE("Planetary Health Influences", "ग्रहीय स्वास्थ्य प्रभावहरू"),
    PLANET_INFLUENCE_TITLE("Planetary Personality Influences", "ग्रहीय व्यक्तित्व प्रभावहरू"),
    PLANET_IN_SIGN_ACCESSIBILITY("%1\$s in %2\$s", "%2\$sमा %1\$s"),
    PLANET_JUPITER("Jupiter", "बृहस्पति"),
    PLANET_JUPITER_ABBR("Ju", "गु"),
    PLANET_JUPITER_BODY_PARTS("Liver, Fat tissue, Ears, Thighs", "कलेजो, बोसो, कान, जाँघ"),
    PLANET_JUPITER_ELEMENT("Ether", "आकाश"),
    PLANET_JUPITER_NATURE("Benefic", "शुभ"),
    PLANET_JUPITER_PROFESSIONS("Teaching, Law, Priesthood, Banking, Counseling", "शिक्षण, कानून, पुरोहित, बैंकिङ, परामर्श"),
    PLANET_JUPITER_REPRESENTS_1("Wisdom, Knowledge", "ज्ञान, विद्या"),
    PLANET_JUPITER_REPRESENTS_2("Teachers, Gurus", "शिक्षकहरू, गुरुहरू"),
    PLANET_JUPITER_REPRESENTS_3("Fortune, Luck", "भाग्य, किस्मत"),
    PLANET_JUPITER_REPRESENTS_4("Children, Dharma", "सन्तान, धर्म"),
    PLANET_JUPITER_REPRESENTS_5("Expansion, Growth", "विस्तार, वृद्धि"),
    PLANET_KETU("Ketu", "केतु"),
    PLANET_KETU_ABBR("Ke", "के"),
    PLANET_KETU_BODY_PARTS("Skin, Spine, Nervous system", "छाला, मेरुदण्ड, स्नायु प्रणाली"),
    PLANET_KETU_ELEMENT("Fire", "अग्नि"),
    PLANET_KETU_NATURE("Malefic", "पापी"),
    PLANET_KETU_PROFESSIONS("Spirituality, Research, Healing, Astrology, Philosophy", "आध्यात्मिकता, अनुसन्धान, उपचार, ज्योतिष, दर्शन"),
    PLANET_KETU_REPRESENTS_1("Spirituality, Liberation", "आध्यात्मिकता, मोक्ष"),
    PLANET_KETU_REPRESENTS_2("Past life karma", "पूर्वजन्मको कर्म"),
    PLANET_KETU_REPRESENTS_3("Detachment, Isolation", "वैराग्य, एकान्त"),
    PLANET_KETU_REPRESENTS_4("Occult, Mysticism", "गुप्त विद्या, रहस्यवाद"),
    PLANET_KETU_REPRESENTS_5("Healing abilities", "उपचार क्षमता"),
    PLANET_LIFE_AREA_JUPITER("wisdom, children, wealth, spirituality, teachers, dharma", "ज्ञान, सन्तान, धन, आध्यात्मिकता, गुरु, धर्म"),
    PLANET_LIFE_AREA_KETU("spirituality, liberation, past karma, psychic abilities", "आध्यात्मिकता, मोक्ष, पूर्व कर्म, मानसिक क्षमता"),
    PLANET_LIFE_AREA_MARS("courage, siblings, property matters, physical strength, competition", "साहस, भाइबहिनी, सम्पत्ति मामिला, शारीरिक शक्ति, प्रतिस्पर्धा"),
    PLANET_LIFE_AREA_MERCURY("intellect, communication, business, education, nervous system", "बुद्धि, सञ्चार, व्यापार, शिक्षा, स्नायु प्रणाली"),
    PLANET_LIFE_AREA_MOON("mental peace, mother's health, emotional stability, public relations", "मानसिक शान्ति, आमाको स्वास्थ्य, भावनात्मक स्थिरता, जनसम्पर्क"),
    PLANET_LIFE_AREA_RAHU("foreign connections, unconventional success, material desires", "विदेशी सम्बन्ध, अपरम्परागत सफलता, भौतिक इच्छा"),
    PLANET_LIFE_AREA_SATURN("longevity, service, discipline, karma, delays, chronic issues", "दीर्घायु, सेवा, अनुशासन, कर्म, ढिलाइ, दीर्घकालीन समस्या"),
    PLANET_LIFE_AREA_SUN("authority, career, government favor, father's health, self-confidence", "अधिकार, करियर, सरकारी कृपा, बुबाको स्वास्थ्य, आत्मविश्वास"),
    PLANET_LIFE_AREA_VENUS("marriage, love, luxury, art, vehicles, pleasure", "विवाह, प्रेम, विलासिता, कला, सवारी, आनन्द"),
    PLANET_MARS("Mars", "मंगल"),
    PLANET_MARS_ABBR("Ma", "मं"),
    PLANET_MARS_BODY_PARTS("Blood, Muscles, Marrow, Head injuries", "रगत, मांसपेशी, मज्जा, टाउकोमा चोटपटक"),
    PLANET_MARS_ELEMENT("Fire", "अग्नि"),
    PLANET_MARS_NATURE("Malefic", "पापी"),
    PLANET_MARS_PROFESSIONS("Military, Police, Surgery, Engineering, Sports, Real Estate", "सेना, प्रहरी, शल्यक्रिया, इन्जिनियरिङ, खेलकुद, घरजग्गा"),
    PLANET_MARS_REPRESENTS_1("Energy, Action, Courage", "ऊर्जा, कार्य, साहस"),
    PLANET_MARS_REPRESENTS_2("Siblings, Younger Brothers", "भाइबहिनी, सानो भाइ"),
    PLANET_MARS_REPRESENTS_3("Property, Land", "सम्पत्ति, जमिन"),
    PLANET_MARS_REPRESENTS_4("Competition, Sports", "प्रतिस्पर्धा, खेलकुद"),
    PLANET_MARS_REPRESENTS_5("Technical Skills", "प्राविधिक सीपहरू"),
    PLANET_MERCURY("Mercury", "बुध"),
    PLANET_MERCURY_ABBR("Me", "बु"),
    PLANET_MERCURY_BODY_PARTS("Nervous system, Skin, Speech, Hands", "स्नायु प्रणाली, छाला, वाणी, हातहरू"),
    PLANET_MERCURY_ELEMENT("Earth", "पृथ्वी"),
    PLANET_MERCURY_NATURE("Benefic", "शुभ"),
    PLANET_MERCURY_PROFESSIONS("Writing, Teaching, Accounting, Trading, IT, Media", "लेखन, शिक्षण, लेखा, व्यापार, आईटी, मिडिया"),
    PLANET_MERCURY_REPRESENTS_1("Intelligence, Communication", "बुद्धि, सञ्चार"),
    PLANET_MERCURY_REPRESENTS_2("Learning, Education", "सिकाइ, शिक्षा"),
    PLANET_MERCURY_REPRESENTS_3("Business, Trade", "व्यापार, व्यवसाय"),
    PLANET_MERCURY_REPRESENTS_4("Writing, Speech", "लेखन, वाणी"),
    PLANET_MERCURY_REPRESENTS_5("Siblings, Friends", "भाइबहिनी, साथीहरू"),
    PLANET_MOON("Moon", "चन्द्र"),
    PLANET_MOON_ABBR("Mo", "च"),
    PLANET_MOON_BODY_PARTS("Mind, Left Eye, Breast, Blood, Fluids", "मन, बायाँ आँखा, स्तन, रगत, तरल पदार्थ"),
    PLANET_MOON_ELEMENT("Water", "जल"),
    PLANET_MOON_NATURE("Benefic", "शुभ"),
    PLANET_MOON_PROFESSIONS("Nursing, Hotel industry, Shipping, Agriculture, Psychology", "नर्सिङ, होटल उद्योग, जहाजरानी, कृषि, मनोविज्ञान"),
    PLANET_MOON_REPRESENTS_1("Mind, Emotions", "मन, भावनाहरू"),
    PLANET_MOON_REPRESENTS_2("Mother, Nurturing", "आमा, पालनपोषण"),
    PLANET_MOON_REPRESENTS_3("Public, Masses", "जनता, समुदाय"),
    PLANET_MOON_REPRESENTS_4("Comforts, Happiness", "आराम, खुशी"),
    PLANET_MOON_REPRESENTS_5("Memory, Imagination", "स्मृति, कल्पना"),
    PLANET_NATURE_JUPITER("wisdom and opportunity", "बुद्धि र अवसर"),
    PLANET_NATURE_KETU("spiritual depth and detachment", "आध्यात्मिक गहिराइ र वैराग्य"),
    PLANET_NATURE_MARS("energy and initiative", "ऊर्जा र पहल"),
    PLANET_NATURE_MERCURY("communication and skills", "सञ्चार र सीप"),
    PLANET_NATURE_MOON("emotional connection and growth", "भावनात्मक सम्बन्ध र विकास"),
    PLANET_NATURE_RAHU("ambition and innovation", "महत्त्वाकांक्षा र नवीनता"),
    PLANET_NATURE_SATURN("discipline and persistence", "अनुशासन र दृढता"),
    PLANET_NATURE_SUN("vitality and authority", "जीवनशक्ति र अधिकार"),
    PLANET_NATURE_VENUS("creativity and harmony", "सिर्जनशीलता र सद्भाव"),
    PLANET_NEPTUNE("Neptune", "नेप्च्युन"),
    PLANET_NEPTUNE_ABBR("Ne", "ने"),
    PLANET_PLUTO("Pluto", "प्लुटो"),
    PLANET_PLUTO_ABBR("Pl", "प्लु"),
    PLANET_RAHU("Rahu", "राहु"),
    PLANET_RAHU_ABBR("Ra", "रा"),
    PLANET_RAHU_BODY_PARTS("Skin diseases, Nervous disorders", "छालाका रोगहरू, स्नायु विकारहरू"),
    PLANET_RAHU_ELEMENT("Air", "वायु"),
    PLANET_RAHU_NATURE("Malefic", "पापी"),
    PLANET_RAHU_PROFESSIONS("Technology, Foreign affairs, Aviation, Politics, Research", "प्रविधि, विदेशी मामिला, उड्डयन, राजनीति, अनुसन्धान"),
    PLANET_RAHU_REPRESENTS_1("Obsession, Illusion", "जुनून, भ्रम"),
    PLANET_RAHU_REPRESENTS_2("Foreign lands, Travel", "विदेश, यात्रा"),
    PLANET_RAHU_REPRESENTS_3("Technology, Innovation", "प्रविधि, नवीनता"),
    PLANET_RAHU_REPRESENTS_4("Unconventional paths", "अपरंपरागत मार्गहरू"),
    PLANET_RAHU_REPRESENTS_5("Material desires", "भौतिक इच्छाहरू"),
    PLANET_RETROGRADE("Retrograde", "वक्री"),
    PLANET_RETROGRADE_SHORT("(R)", "(व)"),
    PLANET_SATURN("Saturn", "शनि"),
    PLANET_SATURN_ABBR("Sa", "श"),
    PLANET_SATURN_BODY_PARTS("Bones, Teeth, Knees, Joints, Nerves", "हड्डी, दाँत, घुँडा, जोर्नीहरू, स्नायु"),
    PLANET_SATURN_ELEMENT("Air", "वायु"),
    PLANET_SATURN_NATURE("Malefic", "पापी"),
    PLANET_SATURN_PROFESSIONS("Mining, Agriculture, Labor, Judiciary, Real Estate", "खनन, कृषि, श्रम, न्यायपालिका, घरजग्गा"),
    PLANET_SATURN_REPRESENTS_1("Discipline, Hard work", "अनुशासन, कडा परिश्रम"),
    PLANET_SATURN_REPRESENTS_2("Karma, Delays", "कर्म, ढिलाइ"),
    PLANET_SATURN_REPRESENTS_3("Longevity, Service", "दीर्घायु, सेवा"),
    PLANET_SATURN_REPRESENTS_4("Laborers, Servants", "श्रमिकहरू, सेवकहरू"),
    PLANET_SATURN_REPRESENTS_5("Chronic issues", "दीर्घकालीन समस्याहरू"),
    PLANET_STRENGTH_DEBILITATED("Debilitated - Weak", "नीच - कमजोर"),
    PLANET_STRENGTH_EXALTED("Exalted - Very Strong", "उच्च - धेरै बलियो"),
    PLANET_STRENGTH_MODERATE("Moderate", "मध्यम"),
    PLANET_STRENGTH_OWN_SIGN("Own Sign - Strong", "स्वराशि - बलियो"),
    PLANET_STRENGTH_RETROGRADE("Retrograde - Introspective", "बक्री - आत्मनिरीक्षक"),
    PLANET_STRENGTH_UNKNOWN("Unknown", "अज्ञात"),
    PLANET_SUN("Sun", "सूर्य"),
    PLANET_SUN_ABBR("Su", "सू"),
    PLANET_SUN_BODY_PARTS("Heart, Spine, Right Eye, Bones", "हृदय, मेरुदण्ड, दाहिने आँखा, हड्डी"),
    PLANET_SUN_ELEMENT("Fire", "अग्नि"),
    PLANET_SUN_NATURE("Malefic", "पापी"),
    PLANET_SUN_PROFESSIONS("Government jobs, Politics, Medicine, Administration, Leadership roles", "सरकारी जागिर, राजनीति, चिकित्सा, प्रशासन, नेतृत्व भूमिकाहरू"),
    PLANET_SUN_REPRESENTS_1("Soul, Self, Ego", "आत्मा, स्वयं, अहंकार"),
    PLANET_SUN_REPRESENTS_2("Father, Authority Figures", "पिता, अधिकारीहरू"),
    PLANET_SUN_REPRESENTS_3("Government, Power", "सरकार, शक्ति"),
    PLANET_SUN_REPRESENTS_4("Health, Vitality", "स्वास्थ्य, जीवनशक्ति"),
    PLANET_SUN_REPRESENTS_5("Fame, Recognition", "प्रसिद्धि, मान्यता"),
    PLANET_URANUS("Uranus", "युरेनस"),
    PLANET_URANUS_ABBR("Ur", "यु"),
    PLANET_VENUS("Venus", "शुक्र"),
    PLANET_VENUS_ABBR("Ve", "शु"),
    PLANET_VENUS_BODY_PARTS("Reproductive system, Face, Skin, Throat", "प्रजनन प्रणाली, अनुहार, छाला, घाँटी"),
    PLANET_VENUS_ELEMENT("Water", "जल"),
    PLANET_VENUS_NATURE("Benefic", "शुभ"),
    PLANET_VENUS_PROFESSIONS("Entertainment, Fashion, Art, Hospitality, Beauty industry", "मनोरञ्जन, फेसन, कला, आतिथ्य, सौन्दर्य उद्योग"),
    PLANET_VENUS_REPRESENTS_1("Love, Beauty, Art", "प्रेम, सौन्दर्य, कला"),
    PLANET_VENUS_REPRESENTS_2("Marriage, Relationships", "विवाह, सम्बन्धहरू"),
    PLANET_VENUS_REPRESENTS_3("Luxuries, Comforts", "विलासिता, आराम"),
    PLANET_VENUS_REPRESENTS_4("Vehicles, Pleasures", "सवारी, आनन्द"),
    PLANET_VENUS_REPRESENTS_5("Creativity", "सिर्जनशीलता"),
    PLEASURE_SEEKING("Pleasure Seeking", "आनन्द खोज"),
    POSITION_INTERPRETATION("Position Interpretation", "स्थिति व्याख्या"),
    POSITIVE_FACTORS("Positive Factors", "सकारात्मक कारकहरू"),
    POS_1_AGNI("Agni (Fire)", "अग्नि"),
    POS_1_DESC("Southeast - Initiative, energy, passion, transformation", "आग्नेय - पहल, ऊर्जा, जोश, रूपान्तरण"),
    POS_2_DESC("East - Success, authority, power, achievements", "पूर्व - सफलता, अधिकार, शक्ति, उपलब्धि"),
    POS_2_INDRA("Indra (King)", "इन्द्र"),
    POS_3_DESC("South - Endings, karma, justice, life lessons", "दक्षिण - अन्त्य, कर्म, न्याय, जीवन पाठ"),
    POS_3_YAMA("Yama (Death)", "यम"),
    POS_4_DESC("Southwest - Obstacles, hidden enemies, dissolution", "नैऋत्य - बाधाहरू, लुकेका शत्रु, विघटन"),
    POS_4_NIRRITI("Nirriti (Decay)", "निऋति"),
    POS_5_DESC("West - Emotions, intuition, healing, purification", "पश्चिम - भावना, अन्तर्ज्ञान, उपचार, शुद्धि"),
    POS_5_VARUNA("Varuna (Water)", "वरुण"),
    POS_6_DESC("Northwest - Communication, travel, change, movement", "वायव्य - सञ्चार, यात्रा, परिवर्तन, गति"),
    POS_6_VAYU("Vayu (Wind)", "वायु"),
    POS_7_DESC("North - Wealth, prosperity, resources, stability", "उत्तर - धन, समृद्धि, स्रोत, स्थिरता"),
    POS_7_KUBERA("Kubera (Wealth)", "कुबेर"),
    POS_8_DESC("Northeast - Spirituality, wisdom, divine grace", "ईशान - आध्यात्म, ज्ञान, दैवी कृपा"),
    POS_8_ISHANA("Ishana (Divine)", "ईशान"),
    POS_ACTIVE("Active Positions", "सक्रिय स्थितिहरू"),
    POS_DEITY("Ruling Deity", "शासक देवता"),
    POS_DOMINANT("Dominant Direction", "प्रभावशाली दिशा"),
    POS_EFFECT("Effect on Query", "प्रश्नमा प्रभाव"),
    POS_ELEMENT("Element", "तत्व"),
    POS_SIGNIFICATION("Signification", "अर्थ"),
    POS_STRENGTH_SCORE("Position Strength", "स्थिति बल"),
    POTENTIAL_AILMENTS("Potential Ailments", "सम्भावित रोगहरू"),
    PRACTICE_BENEFITS("Benefits", "फाइदाहरू"),
    PRACTICE_GUIDELINES("Guidelines", "दिशानिर्देशहरू"),
    PRACTICE_NAME("Practice Name", "अभ्यास नाम"),
    PRAVRAJYA_YOGA("Pravrajya Yoga", "प्रव्रज्या योग"),
    PREC_AWARENESS("Maintain awareness without excessive worry - these are tendencies, not certainties", "धेरै चिन्ता नगरी सजगता अपनाउनुहोस् - यी प्रवृत्ति हुन्, निश्चितता होइनन्"),
    PREC_DASHA("Be extra cautious during Dasha/Antardasha periods of planets in Mrityu Bhaga", "मृत्यु भागमा रहेका ग्रहहरूको दशा/अन्तर्दशा अवधिमा विशेष सावधान रहनुहोस्"),
    PREC_SPIRITUAL("Regular spiritual practices provide natural protection", "नियमित आध्यात्मिक अभ्यासले प्राकृतिक सुरक्षा प्रदान गर्दछ"),
    PREC_TRANSIT("Avoid major decisions during critical transit periods", "महत्त्वपूर्ण गोचर अवधिहरूमा ठूला निर्णयहरू नगर्नुहोस्"),
    PREDICTIONS_ACTIVE_TRANSITS("Active Transits", "सक्रिय गोचर"),
    PREDICTIONS_ACTIVE_YOGAS("Active Yogas", "सक्रिय योगहरू"),
    PREDICTIONS_BEST_FOR("Best for", "को लागि उत्तम"),
    PREDICTIONS_CALCULATING("Calculating Predictions...", "भविष्यवाणी गणना गर्दै..."),
    PREDICTIONS_CALC_FAILED("Failed to calculate predictions", "भविष्यवाणी गणना गर्न असफल"),
    PREDICTIONS_CAREER_PROFESSION("Career & Profession", "क्यारियर र पेशा"),
    PREDICTIONS_CAUTION_FOR("Caution for", "को लागि सावधानी"),
    PREDICTIONS_CAUTION_PERIODS("Periods Needing Caution", "सावधानी चाहिने अवधिहरू"),
    PREDICTIONS_CURRENT_CHALLENGES("Current Challenges", "वर्तमान चुनौतीहरू"),
    PREDICTIONS_CURRENT_PERIOD("Current Period", "वर्तमान अवधि"),
    PREDICTIONS_DAYS_LEFT("days left", "दिन बाँकी"),
    PREDICTIONS_EDUCATION_LEARNING("Education & Learning", "शिक्षा र सिकाइ"),
    PREDICTIONS_ENERGY_LEVEL("Energy Level", "ऊर्जा स्तर"),
    PREDICTIONS_ERROR_LOADING("Error Loading Predictions", "भविष्यवाणी लोड गर्न त्रुटि"),
    PREDICTIONS_FAMILY_HOME("Family & Home", "परिवार र घर"),
    PREDICTIONS_FAVORABLE_PERIODS("Favorable Periods", "अनुकूल अवधिहरू"),
    PREDICTIONS_FINANCE_WEALTH("Finance & Wealth", "वित्त र सम्पत्ति"),
    PREDICTIONS_GO_BACK("Go Back", "फर्कनुहोस्"),
    PREDICTIONS_HEALTH_WELLBEING("Health & Wellbeing", "स्वास्थ्य र कल्याण"),
    PREDICTIONS_IMPORTANT_DATES("Important Dates", "महत्त्वपूर्ण मितिहरू"),
    PREDICTIONS_KEY_STRENGTHS("Key Strengths", "मुख्य शक्तिहरू"),
    PREDICTIONS_LIFE_AREAS_GLANCE("Life Areas at a Glance", "एक नजरमा जीवन क्षेत्रहरू"),
    PREDICTIONS_LONG_TERM("Long-term (1-2 years)", "दीर्घकालीन (१-२ वर्ष)"),
    PREDICTIONS_MEDIUM_TERM("Medium-term (6-12 months)", "मध्यमकालीन (६-१२ महिना)"),
    PREDICTIONS_MONTHS("months", "महिना"),
    PREDICTIONS_NO_CHART_SELECTED("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
    PREDICTIONS_OPPORTUNITIES("Opportunities", "अवसरहरू"),
    PREDICTIONS_RELATIONSHIPS_MARRIAGE("Relationships & Marriage", "सम्बन्ध र विवाह"),
    PREDICTIONS_REMEDIAL_SUGGESTIONS("Remedial Suggestions", "उपचारात्मक सुझावहरू"),
    PREDICTIONS_SELECT_CHART_MESSAGE("Please select a birth chart to view predictions", "कृपया भविष्यवाणी हेर्न जन्म कुण्डली छान्नुहोस्"),
    PREDICTIONS_SHORT_TERM("Short-term (3-6 months)", "अल्पकालीन (३-६ महिना)"),
    PREDICTIONS_SPIRITUAL_PATH("Spiritual Path", "आध्यात्मिक मार्ग"),
    PREDICTIONS_TAB_LIFE_AREAS("Life Areas", "जीवन क्षेत्रहरू"),
    PREDICTIONS_TAB_OVERVIEW("Overview", "सारांश"),
    PREDICTIONS_TAB_REMEDIES("Remedies", "उपाय"),
    PREDICTIONS_TAB_TIMING("Timing", "समय"),
    PREDICTIONS_YOUR_LIFE_PATH("Your Life Path", "तपाईंको जीवन मार्ग"),
    PRED_AD_DEFAULT("additional influences", "थप प्रभावहरू"),
    PRED_AD_EFFECT_SUB_TEMPLATE("The %s sub-period adds %s.", "%s उप-अवधिले %s थप्छ।"),
    PRED_AD_JUPITER("blessings and fortunate opportunities", " आशीर्वाद र भाग्यशाली अवसरहरू"),
    PRED_AD_KETU("spiritual insights and letting go", "आध्यात्मिक अन्तरदृष्टि र त्याग"),
    PRED_AD_MARS("increased drive and assertiveness", "बढेको उत्साह र दृढता"),
    PRED_AD_MERCURY("enhanced mental clarity", "बढेको मानसिक स्पष्टता"),
    PRED_AD_MOON("heightened emotional sensitivity", "बढेको भावनात्मक संवेदनशीलता"),
    PRED_AD_RAHU("sudden changes and ambition", "अचानक परिवर्तन र महत्त्वाकांक्षा"),
    PRED_AD_SATURN("patience and perseverance requirements", "धैर्य र लगनशीलताको आवश्यकता"),
    PRED_AD_SUN("emphasis on leadership and recognition", "नेतृत्व र मान्यता मा जोड"),
    PRED_AD_VENUS("pleasure and harmonious experiences", "आनन्द र सामंजस्यपूर्ण अनुभवहरू"),
    PRED_ASC_AQUARIUS("innovation, humanitarian ideals, and progressive thinking", "नवप्रवर्तन, मानवीय आदर्श र प्रगतिशील सोच"),
    PRED_ASC_ARIES("courage, independence, and pioneering spirit", "साहस, स्वतन्त्रता र अग्रगामी भावना"),
    PRED_ASC_CANCER("nurturing, emotional depth, and family connections", "हेरचाह, भावनात्मक गहिराई र पारिवारिक सम्बन्धहरू"),
    PRED_ASC_CAPRICORN("discipline, ambition, and long-term achievement", "अनुशासन, महत्त्वाकांक्षा र दीर्घकालीन उपलब्धि"),
    PRED_ASC_GEMINI("communication, versatility, and intellectual pursuits", "सञ्चार, बहुमुखी प्रतिभा र बौद्धिक कार्यहरू"),
    PRED_ASC_LEO("leadership, creativity, and self-expression", "नेतृत्व, रचनात्मकता र आत्म-अभिव्यक्ति"),
    PRED_ASC_LIBRA("harmony, relationships, and balanced judgment", "सद्भाव, सम्बन्ध र सन्तुलित निर्णय"),
    PRED_ASC_PISCES("spirituality, compassion, and transcendent wisdom", "आध्यात्मिकता, करुणा र उत्कृष्ट ज्ञान"),
    PRED_ASC_SAGITTARIUS("wisdom, exploration, and philosophical understanding", "ज्ञान, अन्वेषण र दार्शनिक समझ"),
    PRED_ASC_SCORPIO("transformation, intensity, and deep research", "रूपान्तरण, गहनता र गहिरो अनुसन्धान"),
    PRED_ASC_TAURUS("stability, material security, and perseverance", "स्थिरता, भौतिक सुरक्षा र दृढता"),
    PRED_ASC_VIRGO("service, analysis, and practical perfection", "सेवा, विश्लेषण र व्यावहारिक पूर्णता"),
    PRED_CALC_PROGRESS("Current period influences are being calculated.", "वर्तमान अवधिको प्रभावहरू गणना गरिँदैछ।"),
    PRED_CAREER_1("Career matters require extra attention. Avoid major decisions today.", "करियरका मामिलाहरूमा विशेष ध्यान आवश्यक छ। आज ठूला निर्णयहरू नगर्नुहोस्।"),
    PRED_CAREER_2("Some workplace challenges may arise. Stay patient and diplomatic.", "कार्यस्थलमा केही चुनौतीहरू आउन सक्छन्। धैर्यवान र कूटनीतिक रहनुहोस्।"),
    PRED_CAREER_3("Steady progress in professional matters. Maintain consistency in your efforts.", "व्यावसायिक मामिलाहरूमा स्थिर प्रगति। आफ्नो प्रयासमा निरन्तरता कायम राख्नुहोस्।"),
    PRED_CAREER_4("Good energy for career activities. Focus on important projects and networking.", "करियर गतिविधिहरूको लागि राम्रो ऊर्जा। महत्त्वपूर्ण परियोजनाहरू र नेटवर्किङमा ध्यान दिनुहोस्।"),
    PRED_CAREER_5("Excellent day for professional advancement. Your %s period brings recognition and success in work matters.", "व्यावसायिक उन्नतिका लागि उत्कृष्ट दिन। तपाईंको %s अवधिले कामको मामिलामा मान्यता र सफलता ल्याउँछ।"),
    PRED_CAREER_ADVICE("Take calculated risks and invest in professional development. Network actively and stay open to new opportunities.", "जोखिम मोल्नुहोस् र व्यावसायिक विकासमा लगानी गर्नुहोस्। सक्रिय रूपमा नेटवर्क बनाउनुहोस् र नयाँ अवसरहरूका लागि खुला रहनुहोस्।"),
    PRED_CAREER_KEY_1("Professional networking", "व्यावसायिक नेटवर्किङ"),
    PRED_CAREER_KEY_2("Skill enhancement", "सीप वृद्धि"),
    PRED_CAREER_KEY_3("Leadership development", "नेतृत्व विकास"),
    PRED_CAREER_LONG("Establishment as authority in your field. Long-term career goals manifest.", "आफ्नो क्षेत्रमा अधिकारको रूपमा स्थापना। दीर्घकालीन करियर लक्ष्यहरू पूरा हुन्छन्।"),
    PRED_CAREER_MED("Significant professional advancement possible. Leadership opportunities may present themselves.", "महत्त्वपूर्ण व्यावसायिक प्रगति सम्भव छ। नेतृत्वका अवसरहरू आउन सक्छन्।"),
    PRED_CAREER_SHORT("Focus on current projects and networking. New opportunities may emerge through professional contacts.", "हालका परियोजनाहरू र नेटवर्किङमा ध्यान दिनुहोस्। व्यावसायिक सम्पर्कहरू मार्फत नयाँ अवसरहरू आउन सक्छन्।"),
    PRED_CHALLENGE_CAREER_TRANS_DESC("Period of professional reassessment and potential changes", "व्यावसायिक पुनर्मूल्यांकन र सम्भावित परिवर्तनहरूको अवधि"),
    PRED_CHALLENGE_CAREER_TRANS_MIT("Focus on skill development and networking", "सीप विकास र नेटवर्किङमा ध्यान दिनुहोस्"),
    PRED_CHALLENGE_CAREER_TRANS_NAME("Career Transitions", "करियर संक्रमण"),
    PRED_CURRENT("Current", "वर्तमान"),
    PRED_DASHA_DEFAULT("various life experiences", "विभिन्न जीवन अनुभवहरू"),
    PRED_DASHA_EFFECT_TEMPLATE("The %s period brings focus on %s. %s", "%s अवधिले %s मा ध्यान केन्द्रित गर्दछ। %s"),
    PRED_DASHA_INFO_TEMPLATE("%s Mahadasha - %s Antardasha", "%s महादशा - %s अन्तर्दशा"),
    PRED_DASHA_JUPITER("wisdom, expansion, and spiritual growth", "ज्ञान, विस्तार र आध्यात्मिक वृद्धि"),
    PRED_DASHA_KETU("spirituality, detachment, and moksha", "आध्यात्मिकता, वैराग्य र मोक्ष"),
    PRED_DASHA_MARS("energy, courage, and taking action", "ऊर्जा, साहस र कार्य गर्ने क्षमता"),
    PRED_DASHA_MERCURY("communication, intellect, and business", "सञ्चार, बुद्धि र व्यापार"),
    PRED_DASHA_MOON("emotions, mind, and mother-related matters", "भावना, मन र आमा सम्बन्धी मामिलाहरू"),
    PRED_DASHA_PERIOD_DEFAULT("Dasha Period", "दशा अवधि"),
    PRED_DASHA_RAHU("worldly desires, unconventional paths, and material success", "सांसारिक इच्छाहरू, अपरम्परागत मार्ग र भौतिक सफलता"),
    PRED_DASHA_SATURN("discipline, karmic lessons, and hard work", "अनुशासन, कर्मिक पाठ र कडा परिश्रम"),
    PRED_DASHA_SUN("self-confidence, authority, and father-related matters", "आत्मविश्वास, अधिकार र पिता सम्बन्धी मामिलाहरू"),
    PRED_DASHA_VENUS("relationships, luxury, and artistic pursuits", "सम्बन्ध, विलासिता र कलात्मक कार्यहरू"),
    PRED_EDU_ADVICE("Apply theoretical knowledge practically. Seek mentors and engage in continuous learning.", "सैद्धान्तिक ज्ञानलाई व्यावहारिक रूपमा लागू गर्नुहोस्। मेन्टरहरू खोज्नुहोस् र निरन्तर सिकाइमा संलग्न हुनुहोस्।"),
    PRED_EDU_KEY_1("Consistent study", "निरन्तर अध्ययन"),
    PRED_EDU_KEY_2("Practical application", "व्यावहारिक प्रयोग"),
    PRED_EDU_KEY_3("Mentor guidance", "मेन्टर मार्गदर्शन"),
    PRED_EDU_LONG("Mastery in chosen field. Potential to become teacher or expert.", "रोजिएको क्षेत्रमा निपुणता। शिक्षक वा विशेषज्ञ बन्ने सम्भावना।"),
    PRED_EDU_MED("Major educational achievements or certifications. Academic success likely.", "प्रमुख शैक्षिक उपलब्धिहरू वा प्रमाणपत्रहरू। शैक्षिक सफलताको सम्भावना।"),
    PRED_EDU_SHORT("Good period for learning and skill development. Short courses bring benefits.", "सिकाइ र सीप विकासका लागि राम्रो अवधि। छोटो पाठ्यक्रमहरूले फाइदा ल्याउँछन्।"),
    PRED_FAMILY_1("Family dynamics need attention. Prioritize peace and harmony.", "पारिवारिक गतिशीलतामा ध्यान दिन आवश्यक छ। शान्ति र सद्भावलाई प्राथमिकता दिनुहोस्।"),
    PRED_FAMILY_2("Minor family tensions possible. Practice understanding.", "सानोतिनो पारिवारिक तनाव हुन सक्छ। समझदारीको अभ्यास गर्नुहोस्।"),
    PRED_FAMILY_3("Steady domestic atmosphere. Focus on routine family matters.", "स्थिर घरेलु वातावरण। नियमित पारिवारिक मामिलाहरूमा ध्यान दिनुहोस्।"),
    PRED_FAMILY_4("Good time for family bonding. Support flows both ways.", "पारिवारिक बन्धनका लागि राम्रो समय। दुवै तर्फबाट सहयोग प्राप्त हुनेछ।"),
    PRED_FAMILY_5("Harmonious family energy. Celebrations and joyful gatherings are favored.", "सामञ्जस्यपूर्ण पारिवारिक ऊर्जा। उत्सव र रमाइलो जमघटहरू अनुकूल छन्।"),
    PRED_FAMILY_ADVICE("Balance personal and family time. Address conflicts with patience and understanding.", "व्यक्तिगत र पारिवारिक समय सन्तुलन गर्नुहोस्। धैर्य र समझदारीका साथ द्वन्द्वहरू सम्बोधन गर्नुहोस्।"),
    PRED_FAMILY_KEY_1("Quality time", "गुणस्तरीय समय"),
    PRED_FAMILY_KEY_2("Mutual respect", "आपसी सम्मान"),
    PRED_FAMILY_KEY_3("Emotional support", "भावनात्मक सहयोग"),
    PRED_FAMILY_LONG("Strong family foundation. Ancestral blessings and property matters resolved.", "बलियो पारिवारिक आधार। पुर्ख्यौली आशीर्वाद र सम्पत्ति मामिलाहरू समाधान।"),
    PRED_FAMILY_MED("Family expansions or property matters. Supportive period for family bonds.", "पारिवारिक विस्तार वा सम्पत्ति मामिलाहरू। पारिवारिक बन्धनका लागि सहयोगी अवधि।"),
    PRED_FAMILY_SHORT("Harmonious domestic atmosphere. Small celebrations or gatherings bring joy.", "सामंजस्यपूर्ण घरेलु वातावरण। साना उत्सव वा जमघटले आनन्द ल्याउँछ।"),
    PRED_FINANCE_1("Financial caution advised. Postpone major financial decisions.", "वित्तीय सावधानीको सल्लाह दिइन्छ। ठूला वित्तीय निर्णयहरू स्थगित गर्नुहोस्।"),
    PRED_FINANCE_2("Be cautious with expenditures. Avoid impulsive purchases.", "खर्चमा सावधानी अपनाउनुहोस्। आवेगपूर्ण खरिदहरूबाट बच्नुहोस्।"),
    PRED_FINANCE_3("Stable financial period. Stick to your budget.", "स्थिर वित्तीय अवधि। आफ्नो बजेटमा अडिग रहनुहोस्।"),
    PRED_FINANCE_4("Positive financial energy. Good for planned investments.", "सकारात्मक वित्तीय ऊर्जा। योजनाबद्ध लगानीका लागि राम्रो।"),
    PRED_FINANCE_5("Excellent day for financial matters. Opportunities for gains are strong.", "वित्तीय मामिलाहरूको लागि उत्कृष्ट दिन। लाभको अवसरहरू बलियो छन्।"),
    PRED_FINANCE_ADVICE("Create diversified income sources and maintain financial discipline. Seek expert advice for major investments.", "विविध आय स्रोतहरू सिर्जना गर्नुहोस् र आर्थिक अनुशासन कायम राख्नुहोस्। ठूला लगानीका लागि विशेषज्ञको सल्लाह लिनुहोस्।"),
    PRED_FINANCE_KEY_1("Strategic investments", "रणनीतिक लगानी"),
    PRED_FINANCE_KEY_2("Multiple income streams", "बहु आय स्रोतहरू"),
    PRED_FINANCE_KEY_3("Financial discipline", "आर्थिक अनुशासन"),
    PRED_FINANCE_LONG("Wealth accumulation and financial independence. Legacy building period.", "धन सञ्चय र आर्थिक स्वतन्त्रता। विरासत निर्माण अवधि।"),
    PRED_FINANCE_MED("Potential for larger gains through investments or promotions. Financial security strengthens.", "लगानी वा पदोन्नति मार्फत ठूलो लाभको सम्भावना। आर्थिक सुरक्षा बलियो हुन्छ।"),
    PRED_FINANCE_SHORT("Steady income flow with potential for incremental growth. Good time to review budget and savings.", "क्रमिक वृद्धिको सम्भावना सहित स्थिर आय प्रवाह। बजेट र बचत समीक्षा गर्ने राम्रो समय।"),
    PRED_HEALTH_1("Health needs attention. Take it easy and avoid overexertion.", "स्वास्थ्यमा ध्यान दिनु आवश्यक छ। आराम गर्नुहोस् र बढी परिश्रम नगर्नुहोस्।"),
    PRED_HEALTH_2("Energy may fluctuate. Prioritize adequate rest.", "ऊर्जा उतार-चढाव हुन सक्छ। पर्याप्त आरामलाई प्राथमिकता दिनुहोस्।"),
    PRED_HEALTH_3("Steady health. Focus on rest and balanced nutrition.", "स्थिर स्वास्थ्य। आराम र सन्तुलित पोषणमा ध्यान दिनुहोस्।"),
    PRED_HEALTH_4("Good health energy. Maintain your wellness practices.", "राम्रो स्वास्थ्य ऊर्जा। आफ्नो स्वास्थ्य अभ्यासहरू कायम राख्नुहोस्।"),
    PRED_HEALTH_5("Vitality is strong. Great day for physical activities and wellness routines.", "जीवनशक्ति बलियो छ। शारीरिक गतिविधि र स्वास्थ्य दिनचर्याका लागि उत्कृष्ट दिन।"),
    PRED_HEALTH_ADVICE("Establish sustainable wellness routines. Prevention is better than cure - regular check-ups recommended.", "दिगो कल्याण दिनचर्याहरू स्थापना गर्नुहोस्। उपचार भन्दा रोकथाम राम्रो हो - नियमित चेक-अप सिफारिस गरिन्छ।"),
    PRED_HEALTH_KEY_1("Regular exercise", "नियमित व्यायाम"),
    PRED_HEALTH_KEY_2("Balanced nutrition", "सन्तुलित पोषण"),
    PRED_HEALTH_KEY_3("Stress management", "तनाव व्यवस्थापन"),
    PRED_HEALTH_LONG("Strong vitality and longevity indicators. Healthy lifestyle becomes natural.", "बलियो जाँगर र दीर्घायु सूचकहरू। स्वस्थ जीवनशैली स्वाभाविक बन्छ।"),
    PRED_HEALTH_MED("Vitality improves with consistent practices. Consider preventive health measures.", "लगातार अभ्यासले जाँगर सुधार हुन्छ। रोकथाम स्वास्थ्य उपायहरू विचार गर्नुहोस्।"),
    PRED_HEALTH_SHORT("Maintain regular exercise and balanced diet. Energy levels are stable.", "नियमित व्यायाम र सन्तुलित आहार कायम राख्नुहोस्। ऊर्जा स्तर स्थिर छ।"),
    PRED_LABEL_ADVICE("Advice", "सल्लाह"),
    PRED_LABEL_KEY_FACTORS("Key Factors", "मुख्य कारकहरू"),
    PRED_LIFE_THEME_TEMPLATE("Path of %s", "%s को मार्ग"),
    PRED_LOVE_1("Relationships need nurturing. Avoid conflicts and be extra considerate.", "सम्बन्धहरूलाई पोषण चाहिन्छ। द्वन्द्वबाट बच्नुहोस् र थप विचारशील हुनुहोस्।"),
    PRED_LOVE_2("Minor misunderstandings possible. Practice patience with loved ones.", "सानोतिनो गलतफहमी हुन सक्छ। प्रियजनहरूसँग धैर्यताको अभ्यास गर्नुहोस्।"),
    PRED_LOVE_3("Balanced energy in partnerships. Focus on understanding and compromise.", "साझेदारीमा सन्तुलित ऊर्जा। समझदारी र सम्झौतामा ध्यान दिनुहोस्।"),
    PRED_LOVE_4("Favorable time for relationships. Express your feelings openly.", "सम्बन्धका लागि अनुकूल समय। आफ्ना भावनाहरू खुलेर व्यक्त गर्नुहोस्।"),
    PRED_LOVE_5("Romantic energy is at its peak. Deep connections and meaningful conversations await.", "रोमान्टिक ऊर्जा चरम सीमामा छ। गहिरो सम्बन्ध र अर्थपूर्ण कुराकानीहरू प्रतीक्षामा छन्।"),
    PRED_MAHADASHA_LABEL("%s Mahadasha", "%s महादशा"),
    PRED_MOON_AQUARIUS("freedom and humanitarian connection", "स्वतन्त्रता र मानवीय सम्बन्ध"),
    PRED_MOON_ARIES("excitement and action", "उत्साह र कार्य"),
    PRED_MOON_CANCER("security and emotional connection", "सुरक्षा र भावनात्मक सम्बन्ध"),
    PRED_MOON_CAPRICORN("achievement and respect", "उपलब्धि र सम्मान"),
    PRED_MOON_DEFAULT("emotional fulfillment", "भावनात्मक पूर्ति"),
    PRED_MOON_GEMINI("variety and mental stimulation", "विविधता र मानसिक उत्तेजना"),
    PRED_MOON_LEO("recognition and warmth", "मान्यता र न्यानोपन"),
    PRED_MOON_LIBRA("partnership and aesthetic beauty", "साझेदारी र सौन्दर्य"),
    PRED_MOON_PISCES("unity and spiritual transcendence", "एकता र आध्यात्मिक उत्कृष्टता"),
    PRED_MOON_SAGITTARIUS("meaning and philosophical truth", "अर्थ र दार्शनिक सत्य"),
    PRED_MOON_SCORPIO("depth and emotional transformation", "गहिराई र भावनात्मक रूपान्तरण"),
    PRED_MOON_TAURUS("comfort and stability", "आराम र स्थिरता"),
    PRED_MOON_VIRGO("order and practical service", "व्यवस्था र व्यावहारिक सेवा"),
    PRED_OPP_FINANCE_DESC("Favorable period for investments and wealth accumulation", "लगानी र धन सञ्चयका लागि शुभ अवधि"),
    PRED_OPP_FINANCE_LEV("Explore new income sources and strategic investments", "नयाँ आय स्रोतहरू र रणनीतिक लगानीहरू अन्वेषण गर्नुहोस्"),
    PRED_OPP_FINANCE_NAME("Financial Growth", "आर्थिक वृद्धि"),
    PRED_OPP_PERSONAL_DESC("Excellent time for learning and self-improvement", "सिकाइ र आत्म-सुधारका लागि उत्कृष्ट समय"),
    PRED_OPP_PERSONAL_LEV("Enroll in courses, read extensively, seek mentorship", "पाठ्यक्रमहरूमा भर्ना हुनुहोस्, व्यापक रूपमा पढ्नुहोस्, मार्गदर्शन लिनुहोस्"),
    PRED_OPP_PERSONAL_NAME("Personal Development", "व्यक्तिगत विकास"),
    PRED_OPP_TIMING_6M("Next 6 months", "आगामी ६ महिना"),
    PRED_PATH_TEMPLATE("Your life path is shaped by your %s ascendant, indicating a personality focused on %s. With your Moon in %s, your emotional nature seeks %s.", "तपाईंको जीवन मार्ग तपाईंको %s लग्नद्वारा निर्देशित छ, जसले %s मा केन्द्रित व्यक्तित्वलाई संकेत गर्दछ। %s मा तपाईंको चन्द्रमाको साथ, तपाईंको भावनात्मक प्रकृतिले %s खोज्छ।"),
    PRED_PATH_TEMPLATE_UNKNOWN_MOON("Your life path is shaped by your %s ascendant, indicating a personality focused on %s.", "तपाईंको जीवन मार्ग तपाईंको %s लग्नद्वारा निर्देशित छ, जसले %s मा केन्द्रित व्यक्तित्वलाई संकेत गर्दछ।"),
    PRED_REL_ADVICE("Practice active listening and express appreciation regularly. Invest quality time in nurturing bonds.", "सक्रिय सुन्ने अभ्यास गर्नुहोस् र नियमित रूपमा प्रशंसा व्यक्त गर्नुहोस्। सम्बन्धहरू पोषण गर्न गुणस्तरीय समय लगानी गर्नुहोस्।"),
    PRED_REL_KEY_1("Communication quality", "सञ्चार गुणस्तर"),
    PRED_REL_KEY_2("Emotional maturity", "भावनात्मक परिपक्वता"),
    PRED_REL_KEY_3("Shared values", "साझा मानहरू"),
    PRED_REL_LONG("Mature, stable partnerships. Family life flourishes with mutual support.", "परिपक्व, स्थिर साझेदारीहरू। आपसी सहयोगमा पारिवारिक जीवन फस्टाउँछ।"),
    PRED_REL_MED("Important relationship milestones. Marriage or commitment possibilities for singles.", "महत्त्वपूर्ण सम्बन्ध कोसेढुङ्गाहरू। अविवाहितहरूका लागि विवाह वा प्रतिबद्धताको सम्भावना।"),
    PRED_REL_SHORT("Existing relationships deepen. Communication is key for resolving minor conflicts.", "अवस्थित सम्बन्धहरू गहिरो हुन्छन्। सानातिना विवादहरू समाधान गर्न सञ्चार मुख्य हो।"),
    PRED_REMEDY_DONATE("Donate items associated with %s on appropriate days", "उपयुक्त दिनहरूमा %s सँग सम्बन्धित वस्तुहरू दान गर्नुहोस्"),
    PRED_REMEDY_FOR_PERIOD("For your current %s period:", "तपाईंको वर्तमान %s अवधिको लागि:"),
    PRED_REMEDY_GEM("Wear gemstone related to %s after proper consultation", "उचित परामर्श पछि %s सँग सम्बन्धित रत्न लगाउनुहोस्"),
    PRED_REMEDY_MANTRA("Perform %s mantra recitation during morning hours", "बिहानको समयमा %s मन्त्र जप गर्नुहोस्"),
    PRED_REMEDY_WORSHIP("Maintain regular worship and spiritual practices", "नियमित पूजा र आध्यात्मिक अभ्यासहरू कायम राख्नुहोस्"),
    PRED_REMEDY_YOGA("Practice meditation and yoga to balance planetary energies", "ग्रह उर्जाहरू सन्तुलन गर्न ध्यान र योग अभ्यास गर्नुहोस्"),
    PRED_SPIRIT_1("Inner turbulence possible. Ground yourself through simple practices.", "आन्तरिक अशान्ति हुन सक्छ। सरल अभ्यासहरू मार्फत आफूलाई स्थिर राख्नुहोस्।"),
    PRED_SPIRIT_2("Spiritual connection may feel distant. Keep faith.", "आध्यात्मिक सम्बन्ध टाढा महसुस हुन सक्छ। विश्वास राख्नुहोस्।"),
    PRED_SPIRIT_3("Steady spiritual energy. Maintain your regular practices.", "स्थिर आध्यात्मिक ऊर्जा। आफ्नो नियमित अभ्यासहरू कायम राख्नुहोस्।"),
    PRED_SPIRIT_4("Good day for spiritual practices. Inner guidance is strong.", "आध्यात्मिक अभ्यासका लागि राम्रो दिन। आन्तरिक मार्गदर्शन बलियो छ।"),
    PRED_SPIRIT_5("Profound spiritual insights available. Meditation and reflection are highly beneficial.", "गहिरो आध्यात्मिक अन्तर्दृष्टि उपलब्ध छ। ध्यान र चिन्तन अत्यन्तै लाभदायक छ।"),
    PRED_SPIRIT_ADVICE("Maintain daily spiritual practices. Connect with like-minded seekers and serve others.", "दैनिक आध्यात्मिक अभ्यासहरू कायम राख्नुहोस्। समान विचारधारा भएका साधकहरूसँग जोड्नुहोस् र अरूको सेवा गर्नुहोस्।"),
    PRED_SPIRIT_AQUARIUS("universal love and detachment", "विश्वव्यापी प्रेम र वैराग्य"),
    PRED_SPIRIT_ARIES("self-realization through action", "कार्य मार्फत आत्म-साक्षात्कार"),
    PRED_SPIRIT_CANCER("emotional mastery and nurturing wisdom", "भावनात्मक निपुणता र हेरचाह ज्ञान"),
    PRED_SPIRIT_CAPRICORN("mastery and enlightened leadership", "निपुणता र प्रबुद्ध नेतृत्व"),
    PRED_SPIRIT_DEFAULT("spiritual awakening", "आध्यात्मिक जागरण"),
    PRED_SPIRIT_GEMINI("integration of duality", "द्वैतको एकीकरण"),
    PRED_SPIRIT_KEY_1("Daily practice", "दैनिक अभ्यास")
}
