package com.astro.storm.core.common

enum class StringKeyDashaPart2(override val en: String, override val ne: String) : StringKeyInterface {
    KALACHAKRA_GUIDANCE_4("Use Kalachakra Dasha alongside Vimsottari for comprehensive analysis", "विस्तृत विश्लेषणको लागि विंशोत्तरी सँगै कालचक्र दशा प्रयोग गर्नुहोस्"),
    KALACHAKRA_GUIDANCE_5("Pay special attention when malefics transit your Deha Rashi", "जब पापी ग्रहहरूले तपाईंको देह राशिमा गोचर गर्छन् विशेष ध्यान दिनुहोस्"),
    KALACHAKRA_HEALTH_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KALACHAKRA_HEALTH_CRITICAL("Critical", "गम्भीर"),
    KALACHAKRA_HEALTH_DESC_CHALLENGING("Need to take care of health", "स्वास्थ्यको ख्याल राख्नु आवश्यक"),
    KALACHAKRA_HEALTH_DESC_CRITICAL("Extra caution needed - follow remedies", "अतिरिक्त सावधानी आवश्यक - उपायहरू अपनाउनुहोस्"),
    KALACHAKRA_HEALTH_DESC_EXCELLENT("Very favorable for health and vitality", "स्वास्थ्य र जोसका लागि धेरै अनुकूल"),
    KALACHAKRA_HEALTH_DESC_GOOD("Generally supportive of health", "सामान्यतया स्वास्थ्यको लागि सहयोगी"),
    KALACHAKRA_HEALTH_DESC_MODERATE("Mixed health indications", "मिश्रित स्वास्थ्य संकेतहरू"),
    KALACHAKRA_HEALTH_EXCELLENT("Excellent", "उत्कृष्ट"),
    KALACHAKRA_HEALTH_GOOD("Good", "राम्रो"),
    KALACHAKRA_HEALTH_INDICATOR("Health Outlook", "स्वास्थ्य दृष्टिकोण"),
    KALACHAKRA_HEALTH_MODERATE("Moderate", "मध्यम"),
    KALACHAKRA_HEALTH_PRED_CHALLENGING("May experience tension between physical demands and spiritual aspirations. Balance is key.", "शारीरिक माग र आध्यात्मिक आकांक्षाहरू बीच तनाव अनुभव हुन सक्छ। सन्तुलन कुञ्जी हो।"),
    KALACHAKRA_HEALTH_PRED_HARMONIOUS("Physical health is well-supported by spiritual practices. Body responds well to holistic healing.", "शारीरिक स्वास्थ्यलाई आध्यात्मिक अभ्यासहरूले राम्रो समर्थन गर्दछ। शरीरले समग्र उपचारलाई राम्रो प्रतिक्रिया दिन्छ।"),
    KALACHAKRA_HEALTH_PRED_NEUTRAL("Health matters follow their natural course. Maintain regular routines.", "स्वास्थ्य मामिलाहरूले आफ्नो प्राकृतिक मार्ग पछ्याउँछन्। नियमित दिनचर्या कायम राख्नुहोस्।"),
    KALACHAKRA_HEALTH_PRED_SUPPORTIVE("Good baseline health with spiritual practices enhancing physical wellbeing.", "राम्रो आधारभूत स्वास्थ्यको साथ आध्यात्मिक अभ्यासहरूले शारीरिक कल्याण बढाउँछ।"),
    KALACHAKRA_HEALTH_PRED_TRANSFORMATIVE("Health challenges may serve as catalysts for spiritual growth. Deep healing possible.", "स्वास्थ्य चुनौतीहरूले आध्यात्मिक वृद्धिको लागि उत्प्रेरकको रूपमा काम गर्न सक्छन्। गहिरो उपचार सम्भव छ।"),
    KALACHAKRA_INTERPRETATION("Interpretation & Guidance", "व्याख्या र मार्गदर्शन"),
    KALACHAKRA_INTERP_CLOSING("Use this period to align with your %s-ruled energies for maximum growth.", "अधिकतम वृद्धिको लागि तपाईंको %s-शासित ऊर्जाहरूसँग पङ्क्तिबद्ध हुन यो अवधि प्रयोग गर्नुहोस्।"),
    KALACHAKRA_INTERP_CURRENT_PHASE("Currently in %s Mahadasha (%d years). Health outlook: %s. %s", "हाल %s महादशामा (%d वर्ष)। स्वास्थ्य दृष्टिकोण: %s। %s"),
    KALACHAKRA_INTERP_DEHA_JEEVA_SUMMARY("Deha (Body) Rashi: %s, Jeeva (Soul) Rashi: %s. Relationship: %s", "देह (शरीर) राशि: %s, जीव (आत्मा) राशि: %s। सम्बन्ध: %s"),
    KALACHAKRA_INTERP_GROUP_ANALYSIS("Your Moon falls in %s group. %s This influences the direction and nature of your life's unfoldment.", "तपाईंको चन्द्रमा %s समूहमा पर्दछ। %s यसले तपाईंको जीवनको विकासको दिशा र प्रकृतिलाई प्रभाव पार्छ।"),
    KALACHAKRA_INTERP_HEALTH_SPIRITUAL("Health & Spiritual Outlook", "स्वास्थ्य र आध्यात्मिक दृष्टिकोण"),
    KALACHAKRA_INTERP_MATERIAL_GUIDANCE("Material & General Guidance", "भौतिक र सामान्य मार्गदर्शन"),
    KALACHAKRA_INTERP_NO_CURRENT("Current Mahadasha extends beyond calculated range.", "वर्तमान महादशा गणना गरिएको दायरा भन्दा बाहिर छ।"),
    KALACHAKRA_JEEVA("Jeeva", "जीव"),
    KALACHAKRA_JEEVA_ANALYSIS("Jeeva (Soul) Analysis", "जीव (आत्मा) विश्लेषण"),
    KALACHAKRA_JEEVA_LORD("Jeeva Lord", "जीव स्वामी"),
    KALACHAKRA_MATERIAL_GENERAL_PROGRESS("general material progression.", "सामान्य भौतिक प्रगति।"),
    KALACHAKRA_MATERIAL_H1("self-focused material gains.", "आत्म-केन्द्रित भौतिक लाभ।"),
    KALACHAKRA_MATERIAL_H10("career advancement and public recognition.", "करियर उन्नति र सार्वजनिक पहिचान।"),
    KALACHAKRA_MATERIAL_H11("fulfillment of desires and network gains.", "इच्छा पूर्ति र नेटवर्क लाभ।"),
    KALACHAKRA_MATERIAL_H12("spiritual investments and foreign connections.", "आध्यात्मिक लगानी र विदेशी सम्बन्ध।"),
    KALACHAKRA_MATERIAL_H2("wealth and resource accumulation.", "धन र स्रोत संकलन।"),
    KALACHAKRA_MATERIAL_H3("gains through courage and communication.", "साहस र संचार मार्फत लाभ।"),
    KALACHAKRA_MATERIAL_H4("property and domestic comfort.", "सम्पत्ति र पारिवारिक सुख।"),
    KALACHAKRA_MATERIAL_H5("creative and speculative gains.", "रचनात्मक र सट्टा लाभ।"),
    KALACHAKRA_MATERIAL_H6("gains through service and overcoming obstacles.", "सेवा र अवरोधहरू पार गरेर लाभ।"),
    KALACHAKRA_MATERIAL_H7("partnership-related material matters.", "साझेदारी सम्बन्धित भौतिक मामिलाहरू।"),
    KALACHAKRA_MATERIAL_H8("transformation of resources, inheritance.", "स्रोतहरूको रूपान्तरण, पैतृक सम्पत्ति।"),
    KALACHAKRA_MATERIAL_H9("fortune through dharma and higher pursuits.", "धर्म र उच्च खोज मार्फत भाग्य।"),
    KALACHAKRA_MATERIAL_LORD_POS("Sign lord %s in House %d indicates ", "राशि स्वामी %s भाव %d मा हुनुले "),
    KALACHAKRA_MATERIAL_SIGN_FOCUS("Material focus on %s matters.", "%s मामिलाहरूमा भौतिक ध्यान।"),
    KALACHAKRA_MAT_H1("focus on self and physical initiatives.", "स्वयं र शारीरिक पहलमा ध्यान।"),
    KALACHAKRA_MAT_H10("focus on career and status.", "करियर र प्रतिष्ठामा ध्यान।"),
    KALACHAKRA_MAT_H11("focus on gains and networking.", "लाभ र नेटवर्किङमा ध्यान।"),
    KALACHAKRA_MAT_H12("focus on spirituality and foreign matters.", "आध्यात्मिकता र वैदेशिक मामिलामा ध्यान।"),
    KALACHAKRA_MAT_H2("focus on wealth and resources.", "धन र स्रोतहरूमा ध्यान।"),
    KALACHAKRA_MAT_H3("focus on courage and communication.", "साहस र संचारमा ध्यान।"),
    KALACHAKRA_MAT_H4("focus on property and home.", "सम्पत्ति र घरमा ध्यान।"),
    KALACHAKRA_MAT_H5("focus on creativity and children.", "रचनात्मकता र सन्तानमा ध्यान।"),
    KALACHAKRA_MAT_H6("focus on service and health.", "सेवा र स्वास्थ्यमा ध्यान।"),
    KALACHAKRA_MAT_H7("focus on partnerships and marriage.", "साझेदारी र विवाहमा ध्यान।"),
    KALACHAKRA_MAT_H8("focus on transformation and research.", "रूपान्तरण र अनुसन्धानमा ध्यान।"),
    KALACHAKRA_MAT_H9("focus on fortune and higher learning.", "भाग्य र उच्च शिक्षामा ध्यान।"),
    KALACHAKRA_NAKSHATRA_GROUP("Nakshatra Group", "नक्षत्र समूह"),
    KALACHAKRA_OVERVIEW_TEXT("Kalachakra Dasha is a sophisticated timing system particularly useful for health predictions and spiritual transformation timing. It operates on the principle that body (Deha) and soul (Jeeva) follow different but related cycles.", "कालचक्र दशा स्वास्थ्य भविष्यवाणी र आध्यात्मिक रूपान्तरण समयको लागि विशेष गरी उपयोगी एक परिष्कृत समय प्रणाली हो। यो शरीर (देह) र आत्मा (जीव) ले फरक तर सम्बन्धित चक्रहरू पछ्याउँछन् भन्ने सिद्धान्तमा काम गर्दछ।"),
    KALACHAKRA_PADA("Pada", "पाद"),
    KALACHAKRA_PARAMA_AYUSH("Parama Ayush Sign - Special longevity indicator", "परम आयुष राशि - विशेष दीर्घायु सूचक"),
    KALACHAKRA_PRED_INTRO_DEHA("Based on Deha lord's %1\$2 status and %2\$2 Deha-Jeeva relationship: ", "देह स्वामीको %1\$2 अवस्था र %2\$2 देह-जीव सम्बन्धको आधारमा: "),
    KALACHAKRA_PRED_INTRO_JEEVA("Jeeva lord's %1\$2 condition indicates ", "जीव स्वामीको %1\$2 अवस्थाले संकेत गर्दछ "),
    KALACHAKRA_REC_CHALLENGING_1("Practice patience and acceptance with physical limitations", "शारीरिक सीमाहरूसँग धैर्य र स्वीकृति अभ्यास गर्नुहोस्"),
    KALACHAKRA_REC_CHALLENGING_2("Transform challenges into spiritual growth opportunities", "चुनौतीहरूलाई आध्यात्मिक वृद्धिको अवसरमा रूपान्तरण गर्नुहोस्"),
    KALACHAKRA_REC_DEHA_LORD("Strengthen Deha lord (%1\$2) through appropriate mantras and gemstones", "उपयुक्त मन्त्र र रत्नहरू मार्फत देह स्वामी (%1\$2) लाई बलियो बनाउनुहोस्"),
    KALACHAKRA_REC_HARMONIOUS_1("Continue current spiritual and health practices - they are aligned", "वर्तमान आध्यात्मिक र स्वास्थ्य अभ्यासहरू जारी राख्नुहोस् - तिनीहरू पङ्क्तिबद्ध छन्"),
    KALACHAKRA_REC_HARMONIOUS_2("Use this favorable period for deepening meditation", "यो अनुकूल अवधिलाई ध्यान गहिरो बनाउन प्रयोग गर्नुहोस्"),
    KALACHAKRA_REC_JEEVA_LORD("Honor Jeeva lord (%1\$2) through spiritual practices", "आध्यात्मिक अभ्यासहरू मार्फत जीव स्वामी (%1\$2) लाई सम्मान गर्नुहोस्"),
    KALACHAKRA_REC_NEUTRAL_1("Establish regular routines for both physical and spiritual health", "शारीरिक र आध्यात्मिक स्वास्थ्य दुवैको लागि नियमित दिनचर्या स्थापना गर्नुहोस्"),
    KALACHAKRA_REC_NEUTRAL_2("Create balance between material and spiritual pursuits", "भौतिक र आध्यात्मिक प्रयासहरू बीच सन्तुलन सिर्जना गर्नुहोस्"),
    KALACHAKRA_REC_SUPPORTIVE_1("Integrate physical yoga with spiritual practices", "शारीरिक योगलाई आध्यात्मिक अभ्यासहरूसँग एकीकृत गर्नुहोस्"),
    KALACHAKRA_REC_SUPPORTIVE_2("Serve others as part of spiritual path", "आध्यात्मिक मार्गको भागको रूपमा अरूको सेवा गर्नुहोस्"),
    KALACHAKRA_REC_TRANSFORMATIVE_1("Embrace transformation as part of soul's journey", "रूपान्तरणलाई आत्माको यात्राको भागको रूपमा अँगाल्नुहोस्"),
    KALACHAKRA_REC_TRANSFORMATIVE_2("Seek guidance from spiritual teachers during difficult periods", "कठिन समयमा आध्यात्मिक गुरुहरूबाट मार्गदर्शन लिनुहोस्"),
    KALACHAKRA_RELATIONSHIP("Deha-Jeeva Relationship", "देह-जीव सम्बन्ध"),
    KALACHAKRA_RELATIONSHIP_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KALACHAKRA_RELATIONSHIP_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
    KALACHAKRA_RELATIONSHIP_NEUTRAL("Neutral", "तटस्थ"),
    KALACHAKRA_RELATIONSHIP_SUPPORTIVE("Supportive", "सहयोगी"),
    KALACHAKRA_RELATIONSHIP_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
    KALACHAKRA_REL_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    KALACHAKRA_REL_DESC_CHALLENGING("Some friction between material and spiritual needs", "भौतिक र आध्यात्मिक आवश्यकताहरू बीच केही घर्षण"),
    KALACHAKRA_REL_DESC_HARMONIOUS("Body and soul are aligned - good health and spiritual progress", "शरिर र आत्मा एकरुप छन् - राम्रो स्वास्थ्य र आध्यात्मिक प्रगति"),
    KALACHAKRA_REL_DESC_NEUTRAL("Independent functioning of body and spirit", "शरिर र आत्माको स्वतन्त्र कार्य"),
    KALACHAKRA_REL_DESC_SUPPORTIVE("Jeeva supports Deha - spiritual practices benefit health", "जीवले देहलाई सहयोग गर्छ - आध्यात्मिक अभ्यासले स्वास्थ्यलाई फाइदा पुर्‍याउँछ"),
    KALACHAKRA_REL_DESC_TRANSFORMATIVE("Deep karmic work needed to align body and soul", "शरिर र आत्मा मिलाउन गहिरो कार्मिक कार्य आवश्यक"),
    KALACHAKRA_REL_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
    KALACHAKRA_REL_NEUTRAL("Neutral", "तटस्थ"),
    KALACHAKRA_REL_SUPPORTIVE("Supportive", "सहयोगी"),
    KALACHAKRA_REL_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
    KALACHAKRA_REMEDY_AIR("Pranayama and breath-related practices", "प्राणायाम र श्वास सम्बन्धी अभ्यासहरू"),
    KALACHAKRA_REMEDY_DEITY("Honor the sign deity through appropriate worship", "उपयुक्त पूजा मार्फत राशि देवताको सम्मान गर्नुहोस्"),
    KALACHAKRA_REMEDY_EARTH("Service to earth (gardening, feeding, grounding practices)", "पृथ्वीको सेवा (बगैंचा, खुवाउने, ग्राउन्डिङ अभ्यास) गर्नुहोस्"),
    KALACHAKRA_REMEDY_FIRE("Perform Agni-related rituals (Homa, lighting lamp)", "अग्नि सम्बन्धित विधि (होम, दीप बाल्ने) गर्नुहोस्"),
    KALACHAKRA_REMEDY_MANTRA("Chant %s mantra for strengthening this period", "यो अवधिलाई बलियो बनाउन %s मन्त्र जप गर्नुहोस्"),
    KALACHAKRA_REMEDY_WATER("Water offerings, visiting sacred water bodies", "जल अर्पण, पवित्र जलाशयको भ्रमण"),
    KALACHAKRA_SAVYA("Savya (Direct)", "सव्य (सीधो)"),
    KALACHAKRA_SOUL("Soul", "आत्मा"),
    KALACHAKRA_SPIRITUAL_AIR("Spiritual development through knowledge, study, and intellectual understanding. Jnana yoga is favored.", "ज्ञान, अध्ययन र बौद्धिक समझ मार्फत आध्यात्मिक विकास। ज्ञान योग अनुकूल छ।"),
    KALACHAKRA_SPIRITUAL_EARTH("Spiritual grounding through practical service and material detachment. Seva is emphasized.", "व्यावहारिक सेवा र भौतिक अनासक्ति मार्फत आध्यात्मिक स्थिरता। सेवामा जोड दिइन्छ।"),
    KALACHAKRA_SPIRITUAL_FIRE("Spiritual growth through action, courage, and self-assertion. Karma yoga is favored.", "कार्य, साहस र आत्म-दावी मार्फत आध्यात्मिक वृद्धि। कर्म योग अनुकूल छ।"),
    KALACHAKRA_SPIRITUAL_GENERAL("Balanced spiritual development across all paths.", "सबै मार्गहरूमा सन्तुलित आध्यात्मिक विकास।"),
    KALACHAKRA_SPIRITUAL_PRED_CHALLENGING("spiritual growth through overcoming material attachments.", "भौतिक आसक्तिहरू जितेर आध्यात्मिक वृद्धि।"),
    KALACHAKRA_SPIRITUAL_PRED_HARMONIOUS("natural spiritual progress. Meditation and dharmic practices flow easily.", "प्राकृतिक आध्यात्मिक प्रगति। ध्यान र धार्मिक अभ्यासहरू सजिलै प्रवाहित हुन्छन्।"),
    KALACHAKRA_SPIRITUAL_PRED_NEUTRAL("steady spiritual development through consistent practice.", "निरन्तर अभ्यास मार्फत स्थिर आध्यात्मिक विकास।"),
    KALACHAKRA_SPIRITUAL_PRED_SUPPORTIVE("spiritual growth through practical application of wisdom.", "ज्ञानको व्यावहारिक प्रयोग मार्फत आध्यात्मिक वृद्धि।"),
    KALACHAKRA_SPIRITUAL_PRED_TRANSFORMATIVE("profound spiritual transformation through life's challenges.", "जीवनका चुनौतीहरू मार्फत गहिरो आध्यात्मिक रूपान्तरण।"),
    KALACHAKRA_SPIRITUAL_WATER("Spiritual awakening through devotion, intuition, and emotional surrender. Bhakti yoga is emphasized.", "भक्ति, अन्तर्ज्ञान र भावनात्मक समर्पण मार्फत आध्यात्मिक जागरण। भक्ति योगमा जोड दिइन्छ।"),
    KALACHAKRA_SPIR_AIR("Spiritual development through knowledge. Jnana yoga is favored.", "ज्ञान मार्फत आध्यात्मिक विकास। ज्ञान योग अनुकूल छ।"),
    KALACHAKRA_SPIR_EARTH("Spiritual grounding through service. Seva is emphasized.", "सेवा मार्फत आध्यात्मिक स्थिरता। सेवामा जोड दिइन्छ।"),
    KALACHAKRA_SPIR_FIRE("Spiritual growth through action and courage. Karma yoga is favored.", "कर्म र साहस मार्फत आध्यात्मिक वृद्धि। कर्म योग अनुकूल छ।"),
    KALACHAKRA_SPIR_GEN("Balanced spiritual development.", "सन्तुलित आध्यात्मिक विकास।"),
    KALACHAKRA_SPIR_WATER("Spiritual awakening through devotion. Bhakti yoga is emphasized.", "भक्ति मार्फत आध्यात्मिक जागरण। भक्ति योगमा जोड दिइन्छ।"),
    KALACHAKRA_STRENGTH("Strength", "बल"),
    KALACHAKRA_TIMELINE("Timeline", "समयरेखा"),
    MAHADASHA_ADVICE("Period Advice", "अवधि सल्लाह"),
    MAHADASHA_CHALLENGES("Period Challenges", "अवधि चुनौतीहरू"),
    MAHADASHA_DEFAULT_INTERP(
        "A period of transformation and karmic unfolding according to planetary influences.",
        "ग्रह प्रभावहरू अनुसार रूपान्तरण र कर्मिक प्रकटीकरणको अवधि।"
    ),
    MAHADASHA_EFFECTS("Life Area Effects", "जीवन क्षेत्र प्रभावहरू"),
    MAHADASHA_JUPITER_INTERP(
        "A period of wisdom, expansion, prosperity, and divine grace (Guru's blessings). Focus on spirituality, higher learning, teaching, children, law, and philosophical pursuits. Fortune favors righteous endeavors. Faith and optimism increase. Excellent for marriage, progeny, and spiritual advancement.",
        "ज्ञान, विस्तार, समृद्धि र दैवीय कृपा (गुरुको आशीर्वाद) को अवधि। ध्यान आध्यात्मिकता, उच्च शिक्षा, शिक्षण, सन्तान, कानून र दार्शनिक कार्यहरूमा केन्द्रित हुन्छ। भाग्यले धार्मिक प्रयासहरूलाई साथ दिन्छ। विश्वास र आशावाद बढ्छ। विवाह, सन्तान र आध्यात्मिक उन्नतिको लागि उत्कृष्ट।"
    ),
    MAHADASHA_KETU_INTERP(
        "A period of spirituality, detachment, and profound inner transformation. Focus on liberation (moksha), occult research, healing practices, and resolving past-life karma. Deep introspection yields spiritual insights. Material attachments may dissolve. Excellent for meditation, research, and spiritual practices.",
        "आध्यात्मिकता, वैराग्य र गहिरो आन्तरिक रूपान्तरणको अवधि। ध्यान मुक्ति (मोक्ष), तन्त्रमन्त्र अनुसन्धान, उपचार अभ्यास र पूर्वजन्मको कर्म समाधानमा केन्द्रित हुन्छ। गहिरो आत्म-चिन्तनले आध्यात्मिक अन्तरदृष्टि दिन्छ। भौतिक मोह भंग हुन सक्छ। ध्यान, अनुसन्धान र आध्यात्मिक अभ्यासहरूको लागि उत्कृष्ट।"
    ),
    MAHADASHA_MARS_INTERP(
        "A period of heightened energy, courage, initiative, and competitive drive. Focus on property matters, real estate, siblings, technical and engineering pursuits, sports, and surgery. Decisive action is favored. Physical vitality increases. Good for tackling challenges requiring strength and determination.",
        "बढेको ऊर्जा, साहस, पहल र प्रतिस्पर्धात्मक उत्साहको अवधि। ध्यान सम्पत्ति मामिलाहरू, घरजग्गा, भाइबहिनी, प्राविधिक र इन्जिनियरिङ कार्यहरू, खेलकुद र शल्यक्रियामा केन्द्रित हुन्छ। निर्णायक कारबाही अनुकूल छ। शारीरिक जीवनशक्ति बढ्छ। शक्ति र दृढता चाहिने चुनौतीहरू सामना गर्न राम्रो छ।"
    ),
    MAHADASHA_MERCURY_INTERP(
        "A period of enhanced learning, communication, analytical thinking, and commerce. Focus on education, writing, publishing, accounting, trade, and intellectual pursuits. Social connections expand through skillful communication. Good for developing skills, starting businesses, and mastering information.",
        "बढेको सिकाइ, सञ्चार, विश्लेषणात्मक सोच र वाणिज्यको अवधि। ध्यान शिक्षा, लेखन, प्रकाशन, लेखा, व्यापार र बौद्धिक कार्यहरूमा केन्द्रित हुन्छ। कुशल सञ्चार मार्फत सामाजिक सम्बन्धहरू विस्तार हुन्छन्। सीप विकास गर्न, व्यवसाय सुरु गर्न र जानकारीमा निपुणता हासिल गर्न राम्रो छ।"
    ),
    MAHADASHA_MOON_INTERP(
        "An emotionally rich and intuitive period emphasizing mental peace, nurturing, and receptivity. Focus on mother, home life, public image, travel across water, and emotional well-being. Creativity and imagination flourish. Memory and connection to the past strengthen. Relationships with women and the public become significant.",
        "मानसिक शान्ति, पोषण र ग्रहणशीलतामा जोड दिने भावनात्मक रूपमा समृद्ध र अन्तर्ज्ञानी अवधि। ध्यान आमा, गृहस्थ जीवन, सार्वजनिक छवि, जल यात्रा र भावनात्मक कल्याणमा केन्द्रित हुन्छ। सिर्जनशीलता र कल्पना फस्टाउँछ। स्मृति र विगतसँगको सम्बन्ध बलियो हुन्छ। महिला र जनतासँगको सम्बन्ध महत्त्वपूर्ण हुन्छ।"
    ),
    MAHADASHA_PERIOD("Mahadasha Period", "महादशा अवधि"),
    MAHADASHA_PLANET("Mahadasha Planet", "महादशा ग्रह"),
    MAHADASHA_RAHU_INTERP(
        "A period of intense worldly ambition, unconventional paths, and material desires. Focus on foreign connections, technology, innovation, and breaking traditional boundaries. Sudden opportunities and unexpected changes arise. Material gains through unusual or non-traditional means. Beware of illusions.",
        "तीव्र सांसारिक महत्त्वाकांक्षा, अपरम्परागत मार्ग र भौतिक इच्छाहरूको अवधि। ध्यान विदेशी सम्बन्ध, प्रविधि, नवप्रवर्तन र परम्परागत सीमाहरू तोड्नमा केन्द्रित हुन्छ। अचानक अवसरहरू र अप्रत्याशित परिवर्तनहरू उत्पन्न हुन्छन्। असामान्य वा गैर-परम्परागत माध्यमबाट भौतिक लाभ। भ्रमबाट सावधान रहनुहोस्।"
    ),
    MAHADASHA_SATURN_INTERP(
        "A period of discipline, karmic lessons, perseverance, and structural growth. Focus on service, responsibility, hard work, long-term projects, and lessons through patience. Delays and obstacles ultimately lead to lasting success and maturity. Time to build solid foundations and pay karmic debts.",
        "अनुशासन, कर्मिक पाठ, लगनशीलता र संरचनात्मक वृद्धिको अवधि। ध्यान सेवा, जिम्मेवारी, कडा परिश्रम, दीर्घकालीन परियोजनाहरू र धैर्य मार्फत पाठहरूमा केन्द्रित हुन्छ। ढिलाइ र बाधाहरूले अन्ततः स्थायी सफलता र परिपक्वतातिर लैजान्छ। ठोस जग निर्माण गर्ने र कर्मिक ऋण तिर्ने समय।"
    ),
    MAHADASHA_STRENGTHS("Period Strengths", "अवधि शक्तिहरू"),
    MAHADASHA_SUN_INTERP(
        "A period of heightened self-expression, authority, and recognition. Focus turns to career advancement, leadership roles, government dealings, and matters related to father. Soul purpose becomes clearer. Health of heart and vitality gains prominence. Good for developing confidence and establishing one's identity in the world.",
        "आत्म-अभिव्यक्ति, अधिकार र मान्यता बढ्ने अवधि। ध्यान करियर उन्नति, नेतृत्व भूमिका, सरकारी कारोबार र पितासँग सम्बन्धित मामिलाहरूमा जान्छ। आत्माको उद्देश्य स्पष्ट हुन्छ। हृदय र जीवनशक्तिको स्वास्थ्य प्रमुखता पाउँछ। आत्मविश्वास विकास गर्न र संसारमा आफ्नो पहिचान स्थापित गर्न राम्रो छ।"
    ),
    MAHADASHA_THEME("Overall Theme", "समग्र विषय"),
    MAHADASHA_TITLE("Current Mahadasha", "वर्तमान महादशा"),
    MAHADASHA_VENUS_INTERP(
        "A period of luxury, beauty, relationships, artistic expression, and material comforts. Focus on marriage, partnerships, arts, music, dance, vehicles, jewelry, and sensory pleasures. Creativity and romance blossom. Refinement in all areas of life. Good for enhancing beauty, wealth, and experiencing life's pleasures.",
        "विलासिता, सौन्दर्य, सम्बन्ध, कलात्मक अभिव्यक्ति र भौतिक सुखसुविधाहरूको अवधि। ध्यान विवाह, साझेदारी, कला, संगीत, नृत्य, सवारी साधन, गहना र इन्द्रिय सुखहरूमा केन्द्रित हुन्छ। सिर्जनशीलता र रोमान्स फस्टाउँछ। जीवनका सबै क्षेत्रहरूमा परिष्कार। सौन्दर्य, धन बढाउन र जीवनका सुखहरू अनुभव गर्न राम्रो छ।"
    ),
    SHOOLA_ALL_PERIODS("All Shoola Periods", "सबै शूल अवधिहरू"),
    SHOOLA_ALPAYU("Alpayu - Short (8-32 years)", "अल्पायु (८-३२ वर्ष)"),
    SHOOLA_AMITAYU("Amitayu - Extended (100+ years)", "अमितायु (१००+ वर्ष)"),
    SHOOLA_ANTARDASHA("Antardasha", "अन्तर्दशा"),
    SHOOLA_APPLICABILITY_HIGH("Highly Applicable", "अत्यधिक प्रयोज्य"),
    SHOOLA_APPLICABILITY_LOW("Less Applicable", "कम प्रयोज्य"),
    SHOOLA_APPLICABILITY_MEDIUM("Moderately Applicable", "मध्यम प्रयोज्य"),
    SHOOLA_BALARISHTA("Balarishta (0-8 years)", "बालारिष्ट (०-८ वर्ष)"),
    SHOOLA_BEST_DAY("Best Day", "उत्तम दिन"),
    SHOOLA_BODY_PARTS("Affected Body Parts", "प्रभावित शरीर भागहरू"),
    SHOOLA_BRAHMA("Brahma (Creator)", "ब्रह्मा (सृष्टिकर्ता)"),
    SHOOLA_BRAHMA_DESC("Protective benefic in trikona positions", "त्रिकोण स्थितिहरूमा सुरक्षात्मक शुभ ग्रह"),
    SHOOLA_BRAHMA_STRENGTH("Brahma Strength", "ब्रह्मा शक्ति"),
    SHOOLA_CHALLENGING_FACTORS("Challenging Factors", "चुनौतीपूर्ण कारकहरू"),
    SHOOLA_CURRENT("Current", "वर्तमान"),
    SHOOLA_CURRENT_PERIOD("Current Shoola Dasha", "वर्तमान शूल दशा"),
    SHOOLA_DEITY("Deity", "देवता"),
    SHOOLA_DESC("Jaimini timing system for health, accidents, and critical life events", "स्वास्थ्य, दुर्घटना, र गम्भीर जीवन घटनाहरूको लागि जैमिनी समय प्रणाली"),
    SHOOLA_DIRECT("Direct (Zodiacal)", "प्रत्यक्ष (राशिक्रम)"),
    SHOOLA_DIRECTION("Dasha Direction", "दशा दिशा"),
    SHOOLA_EFFECTIVENESS("Effectiveness", "प्रभावकारिता"),
    SHOOLA_FUTURE("Future", "भविष्य"),
    SHOOLA_HEALTH_CONCERNS("Health Concerns", "स्वास्थ्य चिन्ताहरू"),
    SHOOLA_HEALTH_SEVERITY("Health Vigilance Level", "स्वास्थ्य सतर्कता स्तर"),
    SHOOLA_INFO_DESC("Shoola Dasha is a Jaimini sign-based dasha system specifically used for timing health issues, accidents, and critical life events. The word 'Shoola' means 'thorn' or 'pain.' This system identifies Rudra (malefic controller) and tracks periods of heightened health vigilance.", "शूल दशा जैमिनी राशि-आधारित दशा प्रणाली हो जुन विशेष गरी स्वास्थ्य समस्याहरू, दुर्घटनाहरू, र गम्भीर जीवन घटनाहरूको समय निर्धारण गर्न प्रयोग गरिन्छ। 'शूल' शब्दको अर्थ 'काँडा' वा 'पीडा' हो। यस प्रणालीले रुद्र (पाप नियन्त्रक) पहिचान गर्छ र स्वास्थ्य सतर्कताका अवधिहरू ट्र्याक गर्छ।"),
    SHOOLA_INFO_TITLE("About Shoola Dasha", "शूल दशाको बारेमा"),
    SHOOLA_LONGEVITY("Longevity Assessment", "आयु मूल्यांकन"),
    SHOOLA_LONGEVITY_CATEGORY("Longevity Category", "आयु वर्ग"),
    SHOOLA_LONGEVITY_RANGE("Estimated Range", "अनुमानित दायरा"),
    SHOOLA_MADHYAYU("Madhyayu - Medium (32-70 years)", "मध्यायु (३२-७० वर्ष)"),
    SHOOLA_MAHADASHA("Mahadasha", "महादशा"),
    SHOOLA_MAHAMRITYUNJAYA("Mahamrityunjaya Mantra", "महामृत्युञ्जय मन्त्र"),
    SHOOLA_MAHAMRITYUNJAYA_DESC("Most powerful mantra for health protection and longevity", "स्वास्थ्य सुरक्षा र दीर्घायुको लागि सबैभन्दा शक्तिशाली मन्त्र"),
    SHOOLA_MAHESHWARA("Maheshwara (Death Lord)", "महेश्वर (मृत्युको स्वामी)"),
    SHOOLA_MAHESHWARA_DESC("8th lord - death and transformation significator", "आठौं भाव स्वामी - मृत्यु र रूपान्तरणको कारक"),
    SHOOLA_NATURE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    SHOOLA_NATURE_FAVORABLE("Favorable", "अनुकूल"),
    SHOOLA_NATURE_MIXED("Mixed", "मिश्रित"),
    SHOOLA_NATURE_SUPPORTIVE("Supportive", "सहायक"),
    SHOOLA_NATURE_VERY_CHALLENGING("Very Challenging", "अत्यन्त चुनौतीपूर्ण"),
    SHOOLA_NO_CRITICAL("No critical periods in next 5 years", "अर्को ५ वर्षमा कुनै गम्भीर अवधि छैन"),
    SHOOLA_PAST("Past", "बितेको"),
    SHOOLA_PERIOD_DURATION("Duration: %d years", "अवधि: %d वर्ष"),
    SHOOLA_PERIOD_NATURE("Period Nature", "अवधि प्रकृति"),
    SHOOLA_PERIOD_PROGRESS("Progress: %.1f%%", "प्रगति: %.1f%%"),
    SHOOLA_POORNAYU("Poornayu - Full (70-100 years)", "पूर्णायु (७०-१०० वर्ष)"),
    SHOOLA_PRECAUTIONS("Precautions", "सावधानीहरू"),
    SHOOLA_PRIMARY_RUDRA("Primary Rudra", "प्राथमिक रुद्र"),
    SHOOLA_REMEDY_DONATION("Donation Remedy", "दान उपाय"),
    SHOOLA_REMEDY_FASTING("Fasting Remedy", "व्रत उपाय"),
    SHOOLA_REMEDY_GEMSTONE("Gemstone Remedy", "रत्न उपाय"),
    SHOOLA_REMEDY_LIFESTYLE("Lifestyle Change", "जीवनशैली परिवर्तन"),
    SHOOLA_REMEDY_MANTRA("Mantra Remedy", "मन्त्र उपाय"),
    SHOOLA_REMEDY_PUJA("Puja Remedy", "पूजा उपाय"),
    SHOOLA_REMEDY_YANTRA("Yantra Remedy", "यन्त्र उपाय"),
    SHOOLA_REVERSE("Reverse (Anti-zodiacal)", "विपरीत (राशिविरुद्ध)"),
    SHOOLA_RUDRA("Rudra (Destroyer)", "रुद्र (संहारक)"),
    SHOOLA_RUDRA_DESC("Primary malefic controlling health matters", "स्वास्थ्य मामिलाहरू नियन्त्रण गर्ने प्राथमिक पाप ग्रह"),
    SHOOLA_RUDRA_STRENGTH("Rudra Strength", "रुद्र शक्ति"),
    SHOOLA_SECONDARY_RUDRA("Secondary Rudra", "द्वितीयक रुद्र"),
    SHOOLA_SEVERITY_CRITICAL("Critical", "गम्भीर"),
    SHOOLA_SEVERITY_HIGH("High Risk", "उच्च जोखिम"),
    SHOOLA_SEVERITY_LOW("Low Risk", "न्यून जोखिम"),
    SHOOLA_SEVERITY_MINIMAL("Minimal Risk", "न्यूनतम जोखिम"),
    SHOOLA_SEVERITY_MODERATE("Moderate Risk", "मध्यम जोखिम"),
    SHOOLA_SEVERITY_NONE("No Specific Risk", "कुनै विशेष जोखिम छैन"),
    SHOOLA_SIGNIFICANT_PLANETS("Significant Planets", "महत्त्वपूर्ण ग्रहहरू"),
    SHOOLA_SIGN_LORD("Sign Lord", "राशि स्वामी"),
    SHOOLA_STARTING_SIGN("Starting Sign", "प्रारम्भिक राशि"),
    SHOOLA_SUBTITLE("Health & Critical Period Analysis", "स्वास्थ्य र गम्भीर अवधि विश्लेषण"),
    SHOOLA_SUB_PERIOD("Sub-period", "उप-अवधि"),
    SHOOLA_SUMMARY_EN("Overall health and longevity assessment based on Rudra and Tri Murti analysis.", "समग्र स्वास्थ्य र दीर्घायु मूल्याङ्कन।"),
    SHOOLA_SUMMARY_NE("Overall health and longevity assessment based on Rudra and Tri Murti analysis.", "समग्र स्वास्थ्य र दीर्घायु मूल्याङ्कन।"),
    SHOOLA_SUPPORTING_FACTORS("Protective Factors", "सुरक्षात्मक कारकहरू"),
    SHOOLA_SYSTEM_APPLICABILITY("System Applicability", "प्रणाली प्रयोज्यता"),
    SHOOLA_TAB_HEALTH("Health", "स्वास्थ्य"),
    SHOOLA_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    SHOOLA_TAB_PERIODS("Periods", "अवधिहरू"),
    SHOOLA_TAB_REMEDIES("Remedies", "उपाय"),
    SHOOLA_TITLE("Shoola Dasha", "शूल दशा"),
    SHOOLA_TRI_MURTI("Tri-Murti Analysis", "त्रिमूर्ति विश्लेषण"),
    SHOOLA_UNABLE_CALCULATE("Unable to calculate Shoola Dasha", "शूल दशा गणना गर्न सकिएन"),
    SHOOLA_UPCOMING_CRITICAL("Upcoming Critical Periods", "आउँदा गम्भीर अवधिहरू"),
    SHOOLA_VEDIC_REF("Vedic Reference: Jaimini Sutras, BPHS Ayurdaya chapter", "वैदिक सन्दर्भ: जैमिनी सूत्र, बृहत् पाराशर होरा शास्त्र आयुर्दाय अध्याय"),
    SHOOLA_VULNERABILITY_PERIODS("Vulnerability Periods", "संवेदनशील अवधिहरू"),
    SUDARSHANA_ABOUT("About Sudarshana Chakra", "सुदर्शन चक्रको बारेमा"),
    SUDARSHANA_ABOUT_DESC("Sudarshana Chakra Dasha simultaneously considers the Lagna, Chandra, and Surya charts. Each year progresses through signs from these three reference points, giving a holistic view of life events.", "सुदर्शन चक्र दशाले लग्न, चन्द्र र सूर्य कुण्डली एकैसाथ विचार गर्दछ। प्रत्येक वर्ष यी तीन सन्दर्भ बिन्दुहरूबाट राशिहरू मार्फत अगाडि बढ्छ।"),
    SUDARSHANA_ABOUT_TITLE("About Sudarshana Chakra", "सुदर्शन चक्र दशा बारे"),
    SUDARSHANA_ACTIVE_HOUSE("Active House", "सक्रिय भाव"),
    SUDARSHANA_ACTIVE_SIGN("Active Sign", "सक्रिय राशि"),
    SUDARSHANA_AGE("Age", "उमेर"),
    SUDARSHANA_AGE_FMT("Age %d", "उमेर %d"),
    SUDARSHANA_ASPECTS_RECEIVED("Aspects Received", "प्राप्त दृष्टिहरू"),
    SUDARSHANA_ASSESSMENT_CHALLENGING("Challenging year requiring extra effort and remedial measures", "अतिरिक्त प्रयास र उपचारात्मक उपायहरू आवश्यक पर्ने चुनौतीपूर्ण वर्ष"),
    SUDARSHANA_ASSESSMENT_HIGHLY_FAVORABLE("Highly favorable year with aligned energies from all three references", "तीनै सन्दर्भहरूबाट समान ऊर्जासहित अत्यन्त अनुकूल वर्ष"),
    SUDARSHANA_ASSESSMENT_MIXED("Mixed year requiring balanced approach to different life areas", "विभिन्न जीवन क्षेत्रहरूमा सन्तुलित दृष्टिकोण आवश्यक पर्ने मिश्रित वर्ष"),
    SUDARSHANA_ASSESSMENT_POSITIVE("Generally positive year with good support from chart references", "कुण्डली सन्दर्भहरूबाट राम्रो समर्थनसहित सामान्यतया सकारात्मक वर्ष"),
    SUDARSHANA_BIRTH_REF_DESC("Starting positions for chakra progression", "चक्र प्रगतिका लागि सुरुवाती स्थिति"),
    SUDARSHANA_BIRTH_REF_TITLE("Birth Reference Points", "जन्म सन्दर्भ बिन्दुहरू"),
    SUDARSHANA_CHAKRA_ABOUT("About Sudarshana Chakra", "सुदर्शन चक्रको बारेमा"),
    SUDARSHANA_CHAKRA_ABOUT_DESC("Sudarshana Chakra analyzes yearly results from three references: Lagna, Moon, and Sun. Each house progresses one year at a time in a 12-year cycle.", "सुदर्शन चक्रले तीन सन्दर्भबाट वार्षिक परिणाम विश्लेषण गर्छ: लग्न, चन्द्र, र सूर्य। प्रत्येक भाव १२-वर्षे चक्रमा एक पटकमा एक वर्ष अगाडि बढ्छ।"),
    SUDARSHANA_CHAKRA_SUBTITLE("Triple Reference Annual Analysis", "त्रिगुण सन्दर्भ वार्षिक विश्लेषण"),
    SUDARSHANA_CHAKRA_TITLE("Sudarshana Chakra", "सुदर्शन चक्र"),
    SUDARSHANA_CHANDRA_CHAKRA("Chandra Chakra", "चन्द्र चक्र"),
    SUDARSHANA_CHANDRA_INFLUENCE("Chandra Influence", "चन्द्र प्रभाव"),
    SUDARSHANA_CHANDRA_REFERENCE("Moon Reference", "चन्द्र सन्दर्भ"),
    SUDARSHANA_COMBINED_ANALYSIS("Combined Period Analysis", "संयुक्त अवधि विश्लेषण"),
    SUDARSHANA_COMBINED_NOTE("The combined analysis of all three chakras gives the most accurate prediction of annual themes and events.", "सबै तीन चक्रहरूको संयुक्त विश्लेषणले वार्षिक विषय र घटनाहरूको सबैभन्दा सटीक भविष्यवाणी दिन्छ।"),
    SUDARSHANA_COMBINED_STRENGTH("Combined Strength", "संयुक्त बल"),
    SUDARSHANA_COMMON_THEMES("Common Themes", "साझा विषयहरू"),
    SUDARSHANA_CONFLICTING_THEMES("Conflicting Themes", "विरोधाभासी विषयहरू"),
    SUDARSHANA_CONTRIB_CHANDRA("Mind, emotions, and public life - %s", "मन, भावना, र सार्वजनिक जीवन - %s"),
    SUDARSHANA_CONTRIB_LAGNA("Physical matters, personality, and health - %s", "भौतिक मामिला, व्यक्तित्व, र स्वास्थ्य - %s"),
    SUDARSHANA_CONTRIB_SURYA("Soul, authority, and career - %s", "आत्मा, अधिकार, र करियर - %s"),
    SUDARSHANA_CONVERGENCE("Convergence Analysis", "अभिसरण विश्लेषण"),
    SUDARSHANA_CURRENT_AGE("Current Age", "वर्तमान उमेर"),
    SUDARSHANA_CURRENT_SIGNS("Current Signs", "वर्तमान राशिहरू"),
    SUDARSHANA_CURRENT_YEAR("Current Year", "वर्तमान वर्ष"),
    SUDARSHANA_CYCLE_NUMBER("Cycle Number", "चक्र संख्या"),
    SUDARSHANA_DIG_DEBILITATED("Debilitated", "नीच"),
    SUDARSHANA_DIG_EXALTED("Exalted", "उच्च"),
    SUDARSHANA_DIG_NORMAL("Normal", "सामान्य"),
    SUDARSHANA_DIG_OWN("Own Sign", "स्वराशि"),
    SUDARSHANA_EFFECT_ACTIVATED("%s activated - %s element emphasized", "%s सक्रिय - %s तत्वलाई जोड"),
    SUDARSHANA_EFFECT_DEBILITATED("Sign lord is debilitated - extra efforts needed", "राशि स्वामी नीच - अतिरिक्त प्रयास आवश्यक"),
    SUDARSHANA_EFFECT_DUAL("Dual sign - adaptability and flexibility needed", "द्विस्वभाव राशि - अनुकूलनशीलता र लचिलोपन आवश्यक"),
    SUDARSHANA_EFFECT_EXALTED("Sign lord is exalted - strong positive results", "राशि स्वामी उच्च - बलियो सकारात्मक परिणाम"),
    SUDARSHANA_EFFECT_FIXED("Fixed sign - stability and consolidation emphasized", "स्थिर राशि - स्थिरता र समेकनलाई जोड"),
    SUDARSHANA_EFFECT_LORD_POS("Lord %s in %d from active sign", "स्वामी %s सक्रिय राशिबाट %d मा"),
    SUDARSHANA_EFFECT_MOVABLE("Movable sign - new initiatives and changes favored", "चर राशि - नयाँ पहल र परिवर्तनहरू अनुकूल"),
    SUDARSHANA_EFFECT_NORMAL("Sign lord is in normal dignity", "राशि स्वामी सामान्य अवस्थामा"),
    SUDARSHANA_EXCELLENT("Excellent", "उत्कृष्ट"),
    SUDARSHANA_FACTOR_ASPECTS("%d planets aspecting", "%d ग्रहहरूको दृष्टि"),
    SUDARSHANA_FACTOR_DIGNITY("Sign lord %s dignity: %s", "राशि स्वामी %s अवस्था: %s"),
    SUDARSHANA_FACTOR_PLANETS("%d planets in active sign", "%d ग्रहहरू सक्रिय राशिमा"),
    SUDARSHANA_FOCUS_FROM("%s from %s reference", "%s सन्दर्भबाट %s"),
    SUDARSHANA_FOCUS_GENERAL("General matters", "सामान्य मामिलाहरू"),
    SUDARSHANA_GOOD("Good", "राम्रो"),
    SUDARSHANA_HOUSE_10_DESC("Year of career growth, recognition, and professional achievements", "करियर वृद्धि, मान्यता, र व्यावसायिक उपलब्धिहरूको वर्ष"),
    SUDARSHANA_HOUSE_11_DESC("Year of gains, fulfillment of desires, and social expansion", "लाभ, इच्छाहरूको पूर्ति, र सामाजिक विस्तारको वर्ष"),
    SUDARSHANA_HOUSE_12_DESC("Year of spiritual growth, foreign connections, and completion of cycles", "आध्यात्मिक वृद्धि, विदेशी सम्बन्ध, र चक्रहरूको समापनको वर्ष"),
    SUDARSHANA_HOUSE_1_DESC("Year of self-focus, health matters, and personal initiatives", "आत्म-केन्द्रित, स्वास्थ्य मामिला, र व्यक्तिगत पहलहरूको वर्ष"),
    SUDARSHANA_HOUSE_2_DESC("Year of financial matters, family affairs, and resource building", "आर्थिक मामिला, पारिवारिक मामिला, र स्रोत निर्माणको वर्ष"),
    SUDARSHANA_HOUSE_3_DESC("Year of courage, communication, and sibling matters", "साहस, संचार, र भाईबहिनी मामिलाहरूको वर्ष"),
    SUDARSHANA_HOUSE_4_DESC("Year of home, mother, property, and emotional well-being", "घर, आमा, सम्पत्ति, र भावनात्मक कल्याणको वर्ष"),
    SUDARSHANA_HOUSE_5_DESC("Year of children, romance, creativity, and spiritual practices", "सन्तान, रोमान्स, रचनात्मकता, र आध्यात्मिक अभ्यासहरूको वर्ष"),
    SUDARSHANA_HOUSE_6_DESC("Year of health focus, overcoming obstacles, and service", "स्वास्थ्यमा ध्यान, बाधाहरू पार गर्ने, र सेवाको वर्ष"),
    SUDARSHANA_HOUSE_7_DESC("Year of relationships, partnerships, and public dealings", "सम्बन्ध, साझेदारी, र सार्वजनिक व्यवहारहरूको वर्ष"),
    SUDARSHANA_HOUSE_8_DESC("Year of transformation, research, and handling sudden events", "रूपान्तरण, अनुसन्धान, र अचानक घटनाहरू संहाल्ने वर्ष"),
    SUDARSHANA_HOUSE_9_DESC("Year of fortune, spiritual growth, and father-related matters", "भाग्य, आध्यात्मिक वृद्धि, र पितासम्बन्धी मामिलाहरूको वर्ष"),
    SUDARSHANA_HOUSE_SIGNIFICATIONS("House Significations", "भाव अर्थहरू"),
    SUDARSHANA_HOUSE_THEMES("House Themes", "भाव विषयहरू"),
    SUDARSHANA_INFLUENCE_ASPECT("%s aspects from %s", "%s ले %s बाट दृष्टि दिन्छ"),
    SUDARSHANA_INFLUENCE_PRESENT("%s present - direct influence on year's themes", "%s उपस्थित - वर्षका विषयहरूमा प्रत्यक्ष प्रभाव"),
    SUDARSHANA_LAGNA_CHAKRA("Lagna Chakra", "लग्न चक्र"),
    SUDARSHANA_LAGNA_CHAKRA_DESC("Physical body, appearance, overall life direction", "भौतिक शरीर, रूप, समग्र जीवन दिशा"),
    SUDARSHANA_LAGNA_INFLUENCE("Lagna Influence", "लग्न प्रभाव"),
    SUDARSHANA_LAGNA_REFERENCE("Lagna Reference", "लग्न सन्दर्भ"),
    SUDARSHANA_MODERATE("Moderate", "मध्यम"),
    SUDARSHANA_MOON_CHAKRA_DESC("Mind, emotions, mother, public image", "मन, भावना, आमा, सार्वजनिक छवि"),
    SUDARSHANA_NEXT_YEAR("Next Year", "आगामी वर्ष"),
    SUDARSHANA_PERSPECTIVES_TITLE("Three Perspectives", "तीन दृष्टिकोण"),
    SUDARSHANA_PLANETS_IN_SIGN("Planets in Sign", "राशिमा ग्रहहरू"),
    SUDARSHANA_PREVIOUS_YEAR("Previous Year", "गत वर्ष"),
    SUDARSHANA_PRIMARY_FOCUS("Primary Focus", "प्राथमिक केन्द्र"),
    SUDARSHANA_REC_BALANCED("Balanced approach needed - focus on %s", "सन्तुलित दृष्टिकोण आवश्यक - %s मा ध्यान दिनुहोस्"),
    SUDARSHANA_REC_CHALLENGING("Challenging year - strengthen remedies for weak areas", "चुनौतीपूर्ण वर्ष - कमजोर क्षेत्रहरूको लागि उपायहरू बलियो बनाउनुहोस्"),
    SUDARSHANA_REC_EXPAND("Expand activities related to %s", "%s सम्बन्धी गतिविधिहरू विस्तार गर्नुहोस्"),
    SUDARSHANA_REC_FAVORABLE("Favorable year - take initiative in %s", "अनुकूल वर्ष - %s मा पहल गर्नुहोस्"),
    SUDARSHANA_REC_PATIENCE("Be patient with %s", "%s सँग धैर्य राख्नुहोस्"),
    SUDARSHANA_REC_REVIEW("Review all three references monthly for detailed guidance", "विस्तृत मार्गदर्शनको लागि मासिक रूपमा तीनै सन्दर्भहरू समीक्षा गर्नुहोस्"),
    SUDARSHANA_REC_SPIRITUAL("Focus on spiritual practices and patience", "आध्यात्मिक अभ्यास र धैर्यमा ध्यान दिनुहोस्"),
    SUDARSHANA_SECONDARY_FOCUS("Secondary Focus", "माध्यमिक केन्द्र"),
    SUDARSHANA_SIGN_LORD("Sign Lord", "राशि स्वामी"),
    SUDARSHANA_STRONG_CONVERGENCE("Strong Convergence", "बलियो अभिसरण"),
    SUDARSHANA_SUBTITLE("Triple-Reference Timing System", "त्रि-सन्दर्भ समय प्रणाली"),
    SUDARSHANA_SUN_CHAKRA_DESC("Soul, authority, father, career recognition", "आत्मा, अधिकार, बुबा, करियर मान्यता"),
    SUDARSHANA_SURYA_CHAKRA("Surya Chakra", "सूर्य चक्र"),
    SUDARSHANA_SURYA_INFLUENCE("Surya Influence", "सूर्य प्रभाव"),
    SUDARSHANA_SURYA_REFERENCE("Sun Reference", "सूर्य सन्दर्भ"),
    SUDARSHANA_SYNTHESIS("Synthesis", "संश्लेषण"),
    SUDARSHANA_THEME_ACTIVATED("%s activated from multiple references", "%s धेरै सन्दर्भहरूबाट सक्रिय"),
    SUDARSHANA_THEME_H10_1("Career", "करियर"),
    SUDARSHANA_THEME_H10_2("Status", "प्रतिष्ठा"),
    SUDARSHANA_THEME_H11_1("Gains", "लाभ"),
    SUDARSHANA_THEME_H11_2("Income", "आम्दानी"),
    SUDARSHANA_THEME_H12_1("Losses", "हानि"),
    SUDARSHANA_THEME_H12_2("Expenses", "खर्च"),
    SUDARSHANA_THEME_H1_1("Self", "स्वयं"),
    SUDARSHANA_THEME_H1_2("Body", "शरीर"),
    SUDARSHANA_THEME_H2_1("Wealth", "धन"),
    SUDARSHANA_THEME_H2_2("Family", "परिवार"),
    SUDARSHANA_THEME_H3_1("Siblings", "भाईबहिनी"),
    SUDARSHANA_THEME_H3_2("Courage", "साहस"),
    SUDARSHANA_THEME_H4_1("Mother", "आमा"),
    SUDARSHANA_THEME_H4_2("Home", "घर"),
    SUDARSHANA_THEME_H5_1("Children", "सन्तान"),
    SUDARSHANA_THEME_H5_2("Romance", "प्रेम"),
    SUDARSHANA_THEME_H6_1("Health", "स्वास्थ्य"),
    SUDARSHANA_THEME_H6_2("Enemies", "शत्रु"),
    SUDARSHANA_THEME_H7_1("Marriage", "विवाह"),
    SUDARSHANA_THEME_H7_2("Partnership", "साझेदारी"),
    SUDARSHANA_THEME_H8_1("Transformation", "रूपान्तरण"),
    SUDARSHANA_THEME_H8_2("Longevity", "आयु"),
    SUDARSHANA_THEME_H9_1("Fortune", "भाग्य"),
    SUDARSHANA_THEME_H9_2("Father", "पिता"),
    SUDARSHANA_THEME_MULTIPLE("Multiple references point to %s house themes", "धेरै सन्दर्भहरूले %s भाव विषयहरूलाई औंल्याउँछन्"),
    SUDARSHANA_THEME_VARIATION("Significant variation in strength across references - uneven year expected", "सन्दर्भहरूमा शक्तिको महत्त्वपूर्ण भिन्नता - असमान वर्षको अपेक्षा"),
    SUDARSHANA_TITLE("Sudarshana Chakra Dasha", "सुदर्शन चक्र दशा"),
    SUDARSHANA_TREND("Trend", "प्रवृत्ति"),
    SUDARSHANA_TREND_CHALLENGING("Challenging period requiring extra attention", "अतिरिक्त ध्यान आवश्यक पर्ने चुनौतीपूर्ण अवधि"),
    SUDARSHANA_TREND_FAVORABLE("Favorable period in annual cycle", "वार्षिक चक्रमा अनुकूल अवधि"),
    SUDARSHANA_TREND_NEUTRAL("Neutral period with mixed opportunities", "मिश्रित अवसरहरूसहित तटस्थ अवधि"),
    SUDARSHANA_TRIPLE_DESC("Triple-Reference Annual Analysis", "त्रि-सन्दर्भ वार्षिक विश्लेषण"),
    SUDARSHANA_TRIPLE_VIEW("Triple View", "त्रिगुण दृश्य"),
    SUDARSHANA_UNABLE_CALC("Current year analysis not available", "वर्तमान वर्षको विश्लेषण उपलब्ध छैन"),
    SUDARSHANA_VERY_WEAK("Very Weak", "अति कमजोर"),
    SUDARSHANA_WEAK("Weak", "कमजोर"),
    SUDARSHANA_WEAK_CONVERGENCE("Weak Convergence", "कमजोर अभिसरण"),
    SUDARSHANA_YEARLY_PROGRESSION("Yearly Progression", "वार्षिक प्रगति"),
    SUDARSHANA_YEARS_COUNT_FMT("%d years", "%d वर्ष"),
    SUDARSHANA_YEAR_ANALYSIS("Year Analysis", "वार्षिक विश्लेषण"),
    SUDARSHANA_YEAR_HEADER("Sudarshana Chakra - %d", "सुदर्शन चक्र - %d"),
    SUDARSHANA_YEAR_STRENGTH("OVERALL YEAR STRENGTH", "समग्र वर्ष बल"),
    SUDARSHANA_YEAR_SUMMARY("Age %d: %s house activated - %s", "उमेर %d: %s भाव सक्रिय - %s"),
    SUDARSHANA_YEAR_THEMES("Year Themes", "वर्षका विषयहरू"),
    YOGINI_ANTAR_FRIENDLY(
        "%s-%s: Harmonious sub-period with complementary energies. %s's significations blend well with %s's ongoing influence. Good for collaborative efforts and relationship building.",
        "%s-%s: पूरक ऊर्जाको साथ सामंजस्यपूर्ण उप-अवधि। %s को प्रभावहरू %s को चलिरहेको प्रभावसँग राम्रोसँग मिल्छन्। सहयोगात्मक प्रयास र सम्बन्ध निर्माणको लागि राम्रो।"
    ),
    YOGINI_ANTAR_HOSTILE(
        "%s-%s: Potentially challenging sub-period with conflicting energies. %s may create tension with %s's ongoing themes. Requires patience, remedies, and conscious effort for harmony.",
        "%s-%s: द्वन्द्वपूर्ण ऊर्जाको साथ सम्भावित चुनौतीपूर्ण उप-अवधि। %s ले %s को चलिरहेको विषयहरूसँग तनाव सिर्जना गर्न सक्छ। धैर्य, उपाय, र सद्भावको लागि सचेत प्रयास आवश्यक।"
    ),
    YOGINI_ANTAR_NEUTRAL(
        "%s-%s: Balanced sub-period requiring conscious integration. %s's themes activate within %s's framework. Results depend on individual chart placements.",
        "%s-%s: सचेत एकीकरण आवश्यक पर्ने सन्तुलित उप-अवधि। %s को विषयहरू %s को ढाँचा भित्र सक्रिय हुन्छन्। परिणामहरू व्यक्तिगत कुण्डली स्थितिमा निर्भर हुन्छन्।"
    ),
    YOGINI_APP_FEMALE("Yogini Dasha is traditionally considered more accurate for female horoscopes", "योगिनी दशा परम्परागत रूपमा महिला कुण्डलीको लागि बढी सही मानिन्छ"),
    YOGINI_APP_NIGHT_BIRTH("Night birth traditionally favors Yogini Dasha", "रात्रि जन्मले परम्परागत रूपमा योगिनी दशालाई पक्ष दिन्छ"),
    YOGINI_APP_RELATIONSHIP("Yogini Dasha excels at timing relationship and marriage events", "योगिनी दशा सम्बन्ध र विवाह घटनाहरूको समय निर्धारणमा उत्कृष्ट छ"),
    YOGINI_APP_STRONG_MOON("Strong Moon in %s enhances Yogini Dasha applicability", "%s मा बलियो चन्द्रले योगिनी दशाको प्रयोज्यता बढाउँछ"),
    YOGINI_APP_UNIVERSAL("Yogini Dasha is universally applicable for timing specific events", "विशिष्ट घटनाहरूको समय निर्धारणको लागि योगिनी दशा सर्वव्यापी रूपमा लागू हुन्छ"),
    YOGINI_APP_VALIDATION("Can be used alongside Vimsottari Dasha for validation", "पुष्टिको लागि विंशोत्तरी दशासँगै प्रयोग गर्न सकिन्छ"),
    YOGINI_BHADRIKA("Bhadrika", "भद्रिका"),
    YOGINI_BHADRIKA_CAREER("Business acumen peaks. Excellent for trade, communication, writing, and intellectual pursuits. Good for learning new skills.", "व्यापारिक कौशल शिखरमा। व्यापार, सञ्चार, लेखन, र बौद्धिक कार्यहरूको लागि उत्कृष्ट। नयाँ सीपहरू सिक्न राम्रो।"),
    YOGINI_BHADRIKA_CAUTION_1("Nervousness", "घबराहट"),
    YOGINI_BHADRIKA_CAUTION_2("Overthinking", "अत्यधिक सोच"),
    YOGINI_BHADRIKA_CAUTION_3("Skin issues", "छाला समस्याहरू"),
    YOGINI_BHADRIKA_DESC("Intelligence, communication, business success. Mercury's intellectual wit.", "बुद्धि, सञ्चार, व्यापार सफलता। बुधको बौद्धिक कुशलता।"),
    YOGINI_BHADRIKA_HEALTH("Nervous system needs attention. Skin issues possible. Mental relaxation techniques helpful.", "स्नायु प्रणालीमा ध्यान आवश्यक छ। छाला समस्याहरू सम्भव छ। मानसिक विश्राम प्रविधिहरू लाभदायक।"),
    YOGINI_BHADRIKA_REC_1("Wear emerald if suitable", "उपयुक्त भएमा पन्ना लगाउनुहोस्"),
    YOGINI_BHADRIKA_REC_2("Engage in learning and communication", "सिक्ने र सञ्चारमा संलग्न हुनुहोस्"),
    YOGINI_BHADRIKA_REC_3("Write and express yourself", "लेख्नुहोस् र आफूलाई व्यक्त गर्नुहोस्"),
    YOGINI_BHADRIKA_REC_4("Donate green items on Wednesdays", "बुधबार हरियो वस्तुहरू दान गर्नुहोस्"),
    YOGINI_BHADRIKA_RELATIONSHIP("Communication improves relationships. Intellectual compatibility matters. Good for understanding partners better.", "सञ्चारले सम्बन्ध सुधार गर्छ। बौद्धिक अनुकूलता महत्त्वपूर्ण छ। साझेदारहरूलाई राम्रोसँग बुझ्नको लागि राम्रो।"),
    YOGINI_BHADRIKA_SPIRITUAL("Intellectual approach to spirituality. Study of scriptures beneficial. Mantra practice effective.", "आध्यात्मिकतामा बौद्धिक दृष्टिकोण। शास्त्रहरूको अध्ययन लाभदायक। मन्त्र अभ्यास प्रभावकारी।"),
    YOGINI_BHRAMARI("Bhramari", "भ्रामरी"),
    YOGINI_BHRAMARI_CAREER("Active period in career with competition. Good for technical, engineering, and defense-related fields. Property dealings.", "प्रतिस्पर्धा सहित क्यारियरमा सक्रिय अवधि। प्राविधिक, इन्जिनियरिङ, र रक्षा सम्बन्धित क्षेत्रहरूको लागि राम्रो। सम्पत्ति कारोबार।"),
    YOGINI_BHRAMARI_CAUTION_1("Anger management", "क्रोध व्यवस्थापन"),
    YOGINI_BHRAMARI_CAUTION_2("Accidents", "दुर्घटनाहरू"),
    YOGINI_BHRAMARI_CAUTION_3("Property disputes", "सम्पत्ति विवाद"),
    YOGINI_BHRAMARI_DESC("Energy, conflicts, property matters. Mars brings action and courage.", "ऊर्जा, द्वन्द्व, सम्पत्ति मामिलाहरू। मंगलले कार्य र साहस ल्याउँछ।"),
    YOGINI_BHRAMARI_HEALTH("Watch for injuries, inflammations, and accidents. Physical exercise important but avoid overexertion.", "चोटपटक, सुजन, र दुर्घटनाहरूबाट बच्नुहोस्। शारीरिक व्यायाम महत्त्वपूर्ण तर अत्यधिक परिश्रम नगर्नुहोस्।"),
    YOGINI_BHRAMARI_REC_1("Wear red coral if suitable", "उपयुक्त भएमा मुगा लगाउनुहोस्"),
    YOGINI_BHRAMARI_REC_2("Practice physical exercise regularly", "नियमित शारीरिक व्यायाम गर्नुहोस्"),
    YOGINI_BHRAMARI_REC_3("Channel energy constructively", "ऊर्जालाई रचनात्मक रूपमा प्रयोग गर्नुहोस्"),
    YOGINI_BHRAMARI_REC_4("Donate red items on Tuesdays", "मंगलबार रातो वस्तुहरू दान गर्नुहोस्"),
    YOGINI_BHRAMARI_RELATIONSHIP("Passionate but potentially conflicting relationships. Brothers/sisters prominent. Physical attraction strong.", "जोसिलो तर सम्भावित द्वन्द्वपूर्ण सम्बन्ध। दाजुभाइ/दिदीबहिनी प्रमुख। शारीरिक आकर्षण बलियो।"),
    YOGINI_BHRAMARI_SPIRITUAL("Active spiritual practices like yoga and pranayama. Kundalini may activate. Mars-related deity worship helps.", "योग र प्राणायाम जस्ता सक्रिय आध्यात्मिक अभ्यासहरू। कुण्डलिनी सक्रिय हुन सक्छ। मंगल सम्बन्धित देवता पूजाले मद्दत गर्छ।"),
    YOGINI_BUDHA("Budha (Mercury)", "बुध"),
    YOGINI_CAREER_EFFECTS("Career Effects", "क्यारियर प्रभावहरू"),
    YOGINI_CAUTION_AREAS("Caution Areas", "सावधानी क्षेत्रहरू"),
    YOGINI_CHANDRA("Chandra (Moon)", "चन्द्र"),
    YOGINI_DASHA_ABOUT("About Yogini Dasha", "योगिनी दशाको बारेमा"),
    YOGINI_DASHA_ABOUT_DESC("Yogini Dasha is a nakshatra-based timing system with a 36-year cycle. It is particularly effective for female horoscopes and relationship timing.", "योगिनी दशा ३६-वर्षे चक्रको साथ नक्षत्रमा आधारित समय प्रणाली हो। यो महिला कुण्डली र सम्बन्ध समयको लागि विशेष प्रभावकारी छ।")
}
