package com.astro.storm.core.common
enum class StringKeyDoshaPart3(override val en: String, override val ne: String) : StringKeyInterface {
MRITYU_BHAGA_LEVEL_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यधिक शुभ"),
MRITYU_BHAGA_CRITICAL_COUNT("Critical", "गम्भीर"),
MRITYU_BHAGA_AUSPICIOUS_COUNT("Auspicious", "शुभ"),
MRITYU_BHAGA_GANDANTA_BRAHMA("Brahma Gandanta", "ब्रह्म गण्डान्त"),
MRITYU_BHAGA_GANDANTA_VISHNU("Vishnu Gandanta", "विष्णु गण्डान्त"),
MRITYU_BHAGA_GANDANTA_SHIVA("Shiva Gandanta", "शिव गण्डान्त"),
MRITYU_BHAGA_JUNCTION_DESC("Junction between %1\$2 and %2\$2", "%1\$2 र %2\$2 बीचको सन्धि"),
MRITYU_BHAGA_DISTANCE_JUNCTION("Distance from Junction: %1\$2", "सन्धिबाट दूरी: %1\$2"),
MRITYU_BHAGA_PUSHKARA_NAVAMSA_TITLE("Pushkara Navamsa", "पुष्कर नवमांश"),
MRITYU_BHAGA_PUSHKARA_BHAGA_TITLE("Pushkara Bhaga", "पुष्कर भाग"),
MRITYU_BHAGA_BENEFITS("Benefits", "लाभहरू"),
MRITYU_BHAGA_OVERALL_ASSESSMENT("Overall Assessment", "समग्र मूल्यांकन"),
MB_SEV_EXACT("Exact", "पूर्ण"),
MB_SEV_VERY_CLOSE("Very Close", "धेरै नजिक"),
MB_SEV_WITHIN_ORB("Within Orb", "प्रभाव क्षेत्र भित्र"),
MB_SEV_APPROACHING("Approaching", "आउँदै गरेको"),
MB_SEV_SAFE("Safe", "सुरक्षित"),
GANDANTA_SEV_EXACT("Exact Junction", "पूर्ण सन्धि"),
GANDANTA_SEV_CRITICAL("Critical", "गम्भीर"),
GANDANTA_SEV_SEVERE("Severe", "कडा"),
GANDANTA_SEV_MODERATE("Moderate", "मध्यम"),
GANDANTA_SEV_MILD("Mild", "हल्का"),
LAL_KITAB_SCREEN_TITLE("Lal Kitab Remedies", "लाल किताब उपायहरू"),
LAL_KITAB_INDICATORS("Indicators", "संकेतहरू"),
LAL_KITAB_REMEDIES_LABEL("Remedies", "उपायहरू"),
LAL_KITAB_TYPES_TITLE("Types of Karmic Debts", "कार्मिक ऋणका प्रकारहरू"),
LAL_KITAB_DESC_PITRU("Debt towards father and ancestors", "पिता र पूर्वजहरूप्रति ऋण"),
LAL_KITAB_DESC_MATRU("Debt towards mother and maternal lineage", "आमा र मातृपक्षप्रति ऋण"),
LAL_KITAB_DESC_STRI("Debt towards wife/women", "पत्नी/स्त्रीहरूप्रति ऋण"),
LAL_KITAB_DESC_SELF("Debt towards self and karma", "स्वयं र कर्मप्रति ऋण"),
LAL_KITAB_DAILY_REMEDIES_DESC("Daily remedies for each planetary day as per Lal Kitab tradition", "लाल किताब परम्परा अनुसार प्रत्येक ग्रह बारका दैनिक उपायहरू"),
LAL_KITAB_FAVORABLE("Favorable", "अनुकूल"),
LAL_KITAB_AVOID("Avoid", "त्याग गर्नुहोस्"),
LAL_KITAB_DEBT_KANYA("Girl Child Debt", "कन्या ऋण"),
LAL_KITAB_SCREEN_SUBTITLE("Practical Karmic Remedies", "व्यावहारिक कार्मिक उपायहरू"),
LAL_KITAB_SCREEN_ABOUT("About Lal Kitab", "लाल किताबको बारेमा"),
LAL_KITAB_SCREEN_ABOUT_DESC("Lal Kitab offers simple, practical remedies using everyday items like turmeric, milk, honey, and specific actions. These remedies work on karmic debts and planetary afflictions without expensive rituals.", "लाल किताबले बेसार, दूध, मह जस्ता दैनिक वस्तुहरू प्रयोग गरी सरल, व्यावहारिक उपायहरू प्रदान गर्दछ। यी उपायहरूले महँगो विधि बिना कार्मिक ऋण र ग्रह पीडामा काम गर्दछन्।"),
PLANET_STRENGTH_EXALTED("Exalted - Very Strong", "उच्च - धेरै बलियो"),
PLANET_STRENGTH_OWN_SIGN("Own Sign - Strong", "स्वराशि - बलियो"),
PLANET_STRENGTH_DEBILITATED("Debilitated - Weak", "नीच - कमजोर"),
PLANET_STRENGTH_RETROGRADE("Retrograde - Introspective", "बक्री - आत्मनिरीक्षक"),
PLANET_STRENGTH_MODERATE("Moderate", "मध्यम"),
PLANET_STRENGTH_UNKNOWN("Unknown", "अज्ञात"),
    LAL_KITAB_SCREEN_KARMIC_DEBTS("Karmic Debts (Rin)", "Karmic Debts (Rin)"),
LAL_KITAB_SCREEN_PLANETARY_AFFLICTIONS("Planetary Afflictions", "ग्रह पीडाहरू"),
LAL_KITAB_HOUSE_REMEDIES("House-Based Remedies", "भाव-आधारित उपायहरू"),
LAL_KITAB_DAILY_REMEDIES("Daily Remedies", "दैनिक उपायहरू"),
LAL_KITAB_ITEM_BASED("Item-Based Remedies", "वस्तु-आधारित उपायहरू"),
LAL_KITAB_COLOR_THERAPY("Color Therapy", "रंग चिकित्सा"),
LAL_KITAB_DIRECTION_GUIDANCE("Direction Guidance", "दिशा मार्गदर्शन"),
LAL_KITAB_WEEKLY_SCHEDULE("Weekly Remedy Schedule", "साप्ताहिक उपाय तालिका"),
LAL_KITAB_REMEDY_ITEM("Remedy Item", "उपाय वस्तु"),
LAL_KITAB_REMEDY_ACTION("Action Required", "आवश्यक कार्य"),
LAL_KITAB_REMEDY_TIMING("Best Timing", "उत्तम समय"),
LAL_KITAB_EFFECTIVENESS_HIGH("Highly Effective", "अत्यधिक प्रभावकारी"),
LAL_KITAB_EFFECTIVENESS_MEDIUM("Moderately Effective", "मध्यम प्रभावकारी"),
    LAL_KITAB_DEBT_PITRU("Pitru Rin (Ancestral)", "Pitru Rin (Ancestral)"),
    LAL_KITAB_DEBT_MATRU("Matru Rin (Maternal)", "Matru Rin (Maternal)"),
    LAL_KITAB_DEBT_STRI("Stri Rin (Feminine)", "Stri Rin (Feminine)"),
    LAL_KITAB_DEBT_SELF("Swayam Rin (Self)", "Swayam Rin (Self)"),
DIVISIONAL_CHARTS_TITLE("Divisional Charts Analysis", "विभागीय कुण्डली विश्लेषण"),
DIVISIONAL_CHARTS_SUBTITLE("Detailed Varga Analysis", "विस्तृत वर्ग विश्लेषण"),
DIVISIONAL_CHARTS_ABOUT("About Divisional Charts", "विभागीय कुण्डलीको बारेमा"),
    DIVISIONAL_CHARTS_ABOUT_DESC("Divisional charts (Vargas)", "Divisional charts (Vargas)"),
DIVISIONAL_WEALTH_ANALYSIS("Wealth & Finance", "धन र वित्त"),
DIVISIONAL_SIBLING_ANALYSIS("Siblings & Courage", "भाइबहिनी र साहस"),
DIVISIONAL_MARRIAGE_ANALYSIS("Marriage & Dharma", "विवाह र धर्म"),
DIVISIONAL_CAREER_ANALYSIS("Career & Status", "क्यारियर र स्थिति"),
DIVISIONAL_PARENTS_ANALYSIS("Parents & Ancestry", "अभिभावक र वंश"),
DIVISIONAL_KEY_PLANETS("Key Planets", "मुख्य ग्रहहरू"),
DIVISIONAL_STRENGTH_ASSESSMENT("Strength Assessment", "बल मूल्याङ्कन"),
DIVISIONAL_DETAILED_RESULTS("Detailed Results", "विस्तृत परिणामहरू"),
UPACHAYA_SCREEN_TITLE("Upachaya Transits", "उपचय गोचर"),
UPACHAYA_SCREEN_SUBTITLE("Growth House Transit Tracker", "वृद्धि भाव गोचर ट्र्याकर"),
UPACHAYA_SCREEN_ABOUT("About Upachaya Houses", "उपचय भावहरूको बारेमा"),
    UPACHAYA_SCREEN_ABOUT_DESC("Upachaya houses (3, 6, 10, 11)", "Upachaya houses (3, 6, 10, 11)"),
    UPACHAYA_HOUSES("Upachaya Houses (3, 6, 10, 11)", "Upachaya Houses (3, 6, 10, 11)"),
UPACHAYA_SCREEN_FROM_MOON("Transit from Moon Sign", "चन्द्र राशिबाट गोचर"),
UPACHAYA_CURRENT_TRANSITS("Current Beneficial Transits", "वर्तमान लाभदायक गोचर"),
UPACHAYA_SCREEN_UPCOMING("Upcoming Favorable Periods", "आगामी अनुकूल अवधिहरू"),
UPACHAYA_SATURN_TRANSIT("Saturn in Upachaya", "उपचयमा शनि"),
UPACHAYA_MARS_TRANSIT("Mars in Upachaya", "उपचयमा मंगल"),
UPACHAYA_RAHU_TRANSIT("Rahu in Upachaya", "उपचयमा राहु"),
UPACHAYA_JUPITER_TRANSIT("Jupiter in Upachaya", "उपचयमा बृहस्पति"),
UPACHAYA_SCREEN_HOUSE_3("3rd House - Courage, Siblings, Communication", "तेस्रो भाव - साहस, भाइबहिनी, सञ्चार"),
UPACHAYA_SCREEN_HOUSE_6("6th House - Enemies, Service, Health", "छैटौं भाव - शत्रु, सेवा, स्वास्थ्य"),
UPACHAYA_SCREEN_HOUSE_10("10th House - Career, Status, Authority", "दसौं भाव - क्यारियर, स्थिति, अधिकार"),
UPACHAYA_SCREEN_HOUSE_11("11th House - Gains, Desires, Friends", "एघारौं भाव - लाभ, इच्छा, मित्र"),
UPACHAYA_GROWTH_INDICATOR("Growth Indicator", "वृद्धि सूचक"),
UPACHAYA_ACTIVE_NOW("Active Now", "अहिले सक्रिय"),
UPACHAYA_COMING_SOON("Coming Soon", "छिट्टै आउँदैछ"),
UPACHAYA_SCREEN_DURATION("Transit Duration", "गोचर अवधि"),
UPACHAYA_SCREEN_EFFECTS("Expected Effects", "अपेक्षित प्रभावहरू"),
UPACHAYA_IMPROVEMENT_AREAS("Areas of Improvement", "सुधारका क्षेत्रहरू"),
UPACHAYA_HOUSE_ANALYSIS("House Analysis", "भाव विश्लेषण"),
UPACHAYA_TRANSIT_DETAILS("Transit Details", "गोचर विवरण"),
UPACHAYA_UPCOMING_TRANSITS("Upcoming Transits", "आगामी गोचरहरू"),
UPACHAYA_ACTIVE_ALERTS("Active Alerts", "सक्रिय सूचनाहरू"),
UPACHAYA_SIGNIFICANT_TRANSITS("Significant Transits", "महत्त्वपूर्ण गोचरहरू"),
UPACHAYA_TRANSIT_ASSESSMENT("Transit Assessment", "गोचर मूल्याङ्कन"),
UPACHAYA_REFERENCE_POINTS("Reference Points", "सन्दर्भ बिन्दुहरू"),
UPACHAYA_ABOUT("About Upachaya", "उपचयको बारेमा"),
BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
BALANCE_LABEL("Balance at Birth", "जन्ममा सन्तुलन"),
ASHTAKAVARGA_SUMMARY_TITLE("Ashtakavarga Summary", "अष्टकवर्ग सारांश"),
ASHTAKAVARGA_DISTRIBUTION_TITLE("House Strength Distribution", "भाव बल विभाजन"),
ASHTAKAVARGA_TOTAL_BINDUS("Total Bindus", "कुल विन्दुहरू"),
ASHTAKAVARGA_AVG_PER_HOUSE("Avg/House", "औसत/भाव"),
ASHTAKAVARGA_STRENGTH("Strength", "बल"),
ASHTAKAVARGA_CHART_STRENGTH("Overall Chart Strength", "समग्र कुण्डली बल"),
ASHTAKAVARGA_LEGEND_STRONG(">30 Strong", ">३० बलियो"),
ASHTAKAVARGA_LEGEND_GOOD("25-30 Good", "२५-३० राम्रो"),
ASHTAKAVARGA_LEGEND_WEAK("<25 Weak", "<२५ कमजोर"),
KEY_THEMES("Key Themes", "मुख्य विषयहरू"),
EFFECTS_LABEL("Effects", "प्रभावहरू"),
CURRENT_LABEL("Current", "वर्तमान"),
PREVIOUS_LABEL("Previous", "अघिल्लो"),
NEXT_LABEL("Next", "अर्को"),
PRIMARY_LABEL("Primary", "प्राथमिक"),
SECONDARY_LABEL("Secondary", "माध्यमिक"),
LAGNA_LABEL("Lagna", "लग्न"),
MOON_LABEL("Moon", "चन्द्र"),
SUN_LABEL("Sun", "सूर्य"),
SIGN_LABEL("Sign", "राशि"),
HOUSE_LABEL("House", "भाव"),
RELATIONSHIP_FRIEND("Friendly", "मैत्रीपूर्ण"),
RELATIONSHIP_ENEMY("Inimical", "शत्रुतापूर्ण"),
RELATIONSHIP_NEUTRAL("Neutral", "तटस्थ"),
RELATIONSHIP_SAME("Intensified", "तीव्र"),
    PANCHA_EXCELLENT("Excellent (5+)", "Excellent (5+)"),
    PANCHA_GOOD("Good (4)", "Good (4)"),
    PANCHA_AVERAGE("Average (3)", "Average (3)"),
    PANCHA_BELOW_AVERAGE("Below Average (2)", "Below Average (2)"),
    PANCHA_WEAK("Weak (0-1)", "Weak (0-1)"),
DASHA_VIMSOTTARI("Vimsottari", "तपाईंको"),
DASHA_VIMSOTTARI_NAME("Vimsottari", "विंशोत्तरी"),
DASHA_VIMSOTTARI_DESC("Most widely used Nakshatra-based planetary period system", "सबैभन्दा बढी प्रयोग हुने नक्षत्र-आधारित ग्रह अवधि प्रणाली"),
DASHA_VIMSOTTARI_DURATION("120 years", "१२० वर्ष"),
DASHA_YOGINI("Yogini", "योगिनी"),
DASHA_YOGINI_DESC("Feminine energy-based system, especially for female charts", "स्त्री ऊर्जा-आधारित प्रणाली, विशेष गरी महिला कुण्डलीको लागि"),
DASHA_YOGINI_DURATION("36 years", "३६ वर्ष"),
DASHA_ASHTOTTARI("Ashtottari", "अष्टोत्तरी"),
DASHA_ASHTOTTARI_DESC("Traditional for night births, uses 8 planets", "रात्री जन्मको लागि परम्परागत, ८ ग्रहहरू प्रयोग गर्दछ"),
DASHA_ASHTOTTARI_DURATION("108 years", "१०८ वर्ष"),
DASHA_SUDARSHANA("Sudarshana", "सुदर्शन"),
DASHA_SUDARSHANA_DESC("Chakra Dasha from Lagna, Moon, and Sun simultaneously", "लग्न, चन्द्र र सूर्यबाट एक साथ चक्र दशा"),
DASHA_SUDARSHANA_DURATION("Triple view", "त्रिपक्षीय दृश्य"),
DASHA_CHARA("Chara", "कारा"),
DASHA_CHARA_DESC("Jaimini sign-based system with Karakamsha analysis", "जैमिनी राशि-आधारित प्रणाली, कारकांश विश्लेषण सहित"),
DASHA_CHARA_DURATION("Variable", "परिवर्तनशील"),
DASHA_TITLE_YOGINI("Yogini Dasha", "योगिनी दशा"),
DASHA_TITLE_CHARA("Chara Dasha", "कारा दशा"),
DASHA_VIEW_SYSTEM("View %s", "%s हेर्नुहोस्"),
DASHA_CYCLE_DURATION("Cycle Duration: %s", "चक्र अवधि: %s"),
DASHA_CALC_LOADING("Calculating %s Dasha timeline...", "%s दशा समयरेखा गणना गर्दै..."),
DASHA_NO_CHART("No chart selected. Please select a birth chart to view dasha periods.", "कुनै कुण्डली चयन गरिएको छैन। दशा अवधिहरू हेर्न कृपया जन्म कुण्डली चयन गर्नुहोस्।"),
DASHA_NOT_AVAILABLE("%s calculation not available for this chart.", "%s गणना यो कुण्डलीको लागि उपलब्ध छैन।"),
TARABALA_TITLE("Tarabala & Chandrabala", "ताराबल र चन्द्रबल"),
TARABALA_SUBTITLE("Daily Strength Analysis", "दैनिक बल विश्लेषण"),
TARABALA_TODAY("Today's Tarabala", "आजको ताराबल"),
TARABALA_WEEKLY("Weekly Forecast", "साप्ताहिक पूर्वानुमान"),
TARABALA_ALL_TARAS("All 27 Nakshatras", "सबै २७ नक्षत्रहरू"),
TARABALA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
TARABALA_TRANSIT_NAKSHATRA("Transit Nakshatra", "गोचर नक्षत्र"),
TARABALA_CYCLE("Cycle", "चक्र"),
TARABALA_FAVORABLE("Favorable", "अनुकूल"),
TARABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
TARABALA_DAILY_SCORE("Daily Strength Score", "दैनिक बल स्कोर"),
TARABALA_BEST_DAY("Best Day", "उत्तम दिन"),
TARABALA_WORST_DAY("Challenging Day", "चुनौतीपूर्ण दिन"),
TARABALA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
TARABALA_AVOID_ACTIVITIES("Activities to Avoid", "टाढा रहने गतिविधिहरू"),
TARABALA_GENERAL_ADVICE("General Advice", "सामान्य सल्लाह"),
TARABALA_WEEKLY_ADVICE("Weekly Guidance", "साप्ताहिक मार्गदर्शन"),
TARA_JANMA("Janma", "जन्म"),
TARA_SAMPAT("Sampat", "सम्पत्"),
TARA_VIPAT("Vipat", "विपत्"),
TARA_KSHEMA("Kshema", "क्षेम"),
TARA_PRATYARI("Pratyari", "प्रत्यारि"),
TARA_SADHAKA("Sadhaka", "साधक"),
TARA_VADHA("Vadha", "वध"),
TARA_MITRA("Mitra", "मित्र"),
TARA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),
TARA_JANMA_DESC("Birth star day - rest and introspection recommended", "जन्म नक्षत्र दिन - आराम र आत्मचिन्तन सिफारिस"),
TARA_SAMPAT_DESC("Wealth star - excellent for financial matters", "धन नक्षत्र - आर्थिक मामिलाहरूको लागि उत्कृष्ट"),
TARA_VIPAT_DESC("Danger star - avoid important activities", "विपत् नक्षत्र - महत्त्वपूर्ण गतिविधिहरू टाळ्नुहोस्"),
TARA_KSHEMA_DESC("Well-being star - favorable for health matters", "क्षेम नक्षत्र - स्वास्थ्य मामिलाहरूको लागि अनुकूल"),
TARA_PRATYARI_DESC("Obstacle star - expect minor hindrances", "प्रत्यारि नक्षत्र - सानातिना बाधाहरू अपेक्षा गर्नुहोस्"),
TARA_SADHAKA_DESC("Achievement star - good for completing goals", "साधक नक्षत्र - लक्ष्य पूरा गर्नको लागि राम्रो"),
TARA_VADHA_DESC("Death star - highly inauspicious, maximum caution", "वध नक्षत्र - अत्यन्त अशुभ, अधिकतम सावधानी"),
TARA_MITRA_DESC("Friend star - favorable for relationships", "मित्र नक्षत्र - सम्बन्धहरूको लागि अनुकूल"),
TARA_PARAMA_MITRA_DESC("Great friend star - most auspicious for everything", "परम मित्र नक्षत्र - सबैको लागि सबैभन्दा शुभ"),
CHANDRABALA_TITLE("Chandrabala Analysis", "चन्द्रबल विश्लेषण"),
CHANDRABALA_TRANSIT_MOON("Transit Moon Sign", "गोचर चन्द्र राशि"),
CHANDRABALA_NATAL_MOON("Natal Moon Sign", "जन्म चन्द्र राशि"),
CHANDRABALA_HOUSE_FROM_MOON("House from Moon", "चन्द्रबाट भाव"),
CHANDRABALA_EXCELLENT("Excellent", "उत्कृष्ट"),
CHANDRABALA_GOOD("Good", "राम्रो"),
CHANDRABALA_NEUTRAL("Neutral", "तटस्थ"),
CHANDRABALA_WEAK("Weak", "कमजोर"),
CHANDRABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
CHANDRABALA_SIGNIFICATIONS("House Significations", "भाव संकेतहरू"),
COMBINED_HIGHLY_FAVORABLE("Highly Favorable", "अत्यन्त अनुकूल"),
COMBINED_FAVORABLE("Favorable", "अनुकूल"),
COMBINED_MIXED("Mixed Results", "मिश्रित परिणाम"),
COMBINED_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
COMBINED_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
TRANSITION_FRIEND_FRIEND("Friend to Friend", "मित्रबाट मित्रमा"),
TRANSITION_FRIEND_NEUTRAL("Friend to Neutral", "मित्रबाट तटस्थमा"),
TRANSITION_FRIEND_ENEMY("Friend to Enemy", "मित्रबाट शत्रुमा"),
TRANSITION_NEUTRAL_FRIEND("Neutral to Friend", "तटस्थबाट मित्रमा"),
TRANSITION_NEUTRAL_NEUTRAL("Neutral to Neutral", "तटस्थबाट तटस्थमा"),
TRANSITION_NEUTRAL_ENEMY("Neutral to Enemy", "तटस्थबाट शत्रुमा"),
TRANSITION_ENEMY_FRIEND("Enemy to Friend", "शत्रुबाट मित्रमा"),
TRANSITION_ENEMY_NEUTRAL("Enemy to Neutral", "शत्रुबाट तटस्थमा"),
TRANSITION_ENEMY_ENEMY("Enemy to Enemy", "शत्रुबाट शत्रुमा"),
VEDHA_TITLE("Gochara Vedha Analysis", "गोचर वेध विश्लेषण"),
VEDHA_SUBTITLE("Transit Obstruction Analysis", "गोचर अवरोध विश्लेषण"),
VEDHA_OVERVIEW("Transit Overview", "गोचर सिंहावलोकन"),
VEDHA_ACTIVE("Active Vedhas", "सक्रिय वेधहरू"),
VEDHA_PLANET_TRANSITS("Planetary Transits", "ग्रह गोचरहरू"),
VEDHA_OVERALL_SCORE("Overall Transit Score", "समग्र गोचर स्कोर"),
VEDHA_FAVORABLE_COUNT("Favorable Transits", "अनुकूल गोचरहरू"),
VEDHA_OBSTRUCTED_COUNT("Obstructed Transits", "अवरुद्ध गोचरहरू"),
VEDHA_KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टिहरू"),
VEDHA_OBSTRUCTED_BY("Obstructed by", "द्वारा अवरुद्ध"),
VEDHA_LOST_BENEFITS("Lost Benefits", "गुमाएको फाइदाहरू"),
VEDHA_COMPLETE("Complete Obstruction", "पूर्ण अवरोध"),
VEDHA_STRONG("Strong Obstruction", "बलियो अवरोध"),
VEDHA_MODERATE("Moderate Obstruction", "मध्यम अवरोध"),
VEDHA_PARTIAL("Partial Obstruction", "आंशिक अवरोध"),
VEDHA_NONE("No Obstruction", "कुनै अवरोध छैन"),
KEMADRUMA_TITLE("Kemadruma Yoga Analysis", "केमद्रुम योग विश्लेषण"),
KEMADRUMA_SUBTITLE("Moon Support Analysis", "चन्द्र समर्थन विश्लेषण"),
KEMADRUMA_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
KEMADRUMA_FORMATION("Formation Details", "गठन विवरण"),
KEMADRUMA_CANCELLATIONS("Cancellation Factors", "रद्दीकरण कारकहरू"),
KEMADRUMA_EMOTIONAL("Emotional Impact", "भावनात्मक प्रभाव"),
KEMADRUMA_FINANCIAL("Financial Impact", "आर्थिक प्रभाव"),
KEMADRUMA_SOCIAL("Social Impact", "सामाजिक प्रभाव"),
KEMADRUMA_ACTIVATION("Activation Periods", "सक्रियता अवधिहरू"),
KEMADRUMA_MENTAL_PEACE("Mental Peace", "मानसिक शान्ति"),
KEMADRUMA_STABILITY("Emotional Stability", "भावनात्मक स्थिरता"),
KEMADRUMA_CONFIDENCE("Confidence Level", "आत्मविश्वास स्तर"),
KEMADRUMA_ANXIETY("Anxiety Tendency", "चिन्ता प्रवृत्ति"),
KEMADRUMA_DEPRESSION_RISK("Depression Risk", "अवसाद जोखिम"),
KEMADRUMA_WEALTH_RETENTION("Wealth Retention", "धन संरक्षण"),
KEMADRUMA_FAMILY_SUPPORT("Family Support", "पारिवारिक समर्थन"),
KEMADRUMA_FRIENDSHIP("Friendship Quality", "मित्रता गुणस्तर"),
KEMADRUMA_ISOLATION("Isolation Tendency", "एकान्त प्रवृत्ति"),
KEMADRUMA_NOT_PRESENT("Not Present", "उपस्थित छैन"),
KEMADRUMA_FULLY_CANCELLED("Fully Cancelled", "पूर्ण रूपमा रद्द"),
KEMADRUMA_MOSTLY_CANCELLED("Mostly Cancelled", "प्रायः रद्द"),
KEMADRUMA_PARTIALLY_CANCELLED("Partially Cancelled", "आंशिक रूपमा रद्द"),
KEMADRUMA_WEAKLY_CANCELLED("Weakly Cancelled", "कमजोर रूपमा रद्द"),
    KEMADRUMA_ACTIVE_MODERATE("Active (Moderate)", "Active (Moderate)"),
    KEMADRUMA_ACTIVE_SEVERE("Active (Severe)", "Active (Severe)"),
BHANGA_KENDRA_MOON("Planets in Kendra from Moon", "चन्द्रबाट केन्द्रमा ग्रहहरू"),
BHANGA_KENDRA_LAGNA("Planets in Kendra from Lagna", "लग्नबाट केन्द्रमा ग्रहहरू"),
BHANGA_MOON_KENDRA("Moon in Kendra from Lagna", "लग्नबाट केन्द्रमा चन्द्र"),
BHANGA_BENEFIC_ASPECT("Benefic planet aspects Moon", "शुभ ग्रहले चन्द्रलाई देख्छ"),
BHANGA_BENEFIC_CONJUNCTION("Benefic planet conjuncts Moon", "शुभ ग्रह चन्द्रसँग युति"),
BHANGA_MOON_EXALTED("Moon in exaltation", "चन्द्र उच्चमा"),
BHANGA_MOON_OWN("Moon in own sign", "चन्द्र स्वराशिमा"),
BHANGA_MOON_FRIEND("Moon in friendly sign", "चन्द्र मित्र राशिमा"),
BHANGA_FULL_MOON("Full or bright Moon", "पूर्ण वा उज्यालो चन्द्र"),
BHANGA_ANGULAR_MOON("Moon in angular house", "कोणीय भावमा चन्द्र"),
BHANGA_STRONG_DISPOSITOR("Strong dispositor", "बलियो राशीश"),
BHANGA_JUPITER_ASPECT("Jupiter aspects Moon", "बृहस्पतिले चन्द्रलाई देख्छ"),
BHANGA_VENUS_ASPECT("Venus aspects Moon", "शुक्रले चन्द्रलाई देख्छ"),
MOON_BRIGHTNESS_FULL("Full Moon", "पूर्णिमा"),
MOON_BRIGHTNESS_BRIGHT("Bright Moon", "उज्यालो चन्द्र"),
MOON_BRIGHTNESS_AVERAGE("Average Moon", "औसत चन्द्र"),
MOON_BRIGHTNESS_DIM("Dim Moon", "धमिलो चन्द्र"),
MOON_BRIGHTNESS_NEW("New Moon", "अमावस्या"),
PAKSHA_SHUKLA("Shukla Paksha", "शुक्ल पक्ष"),
PAKSHA_KRISHNA("Krishna Paksha", "कृष्ण पक्ष"),
IMPACT_SEVERE("Severe", "गम्भीर"),
IMPACT_HIGH("High", "उच्च"),
IMPACT_MODERATE("Moderate", "मध्यम"),
IMPACT_MILD("Mild", "हल्का"),
IMPACT_MINIMAL("Minimal", "न्यूनतम"),
IMPACT_POSITIVE("Positive", "सकारात्मक"),
CHAT_NEW("New Chat", "नयाँ च्याट"),
CHAT_DELETE("Delete Chat", "च्याट मेटाउनुहोस्"),
CHAT_DELETE_CONFIRM("Are you sure you want to delete \"%s\"? This cannot be undone.", "के तपाईं \"%s\" मेटाउन निश्चित हुनुहुन्छ? यो पूर्ववत गर्न सकिँदैन।"),
CHAT_DELETE_BTN("Delete", "मेटाउनुहोस्"),
CHAT_CANCEL_BTN("Cancel", "रद्द गर्नुहोस्"),
CHAT_ARCHIVE("Archive", "संग्रह"),
CHAT_MORE_OPTIONS("More options", "थप विकल्पहरू"),
CHAT_MESSAGES_COUNT("%d messages", "%d सन्देशहरू"),
CHAT_JUST_NOW("Just now", "अहिले भर्खरै"),
CHAT_MINUTES_AGO("%dm ago", "%dमि. पहिले"),
CHAT_HOURS_AGO("%dh ago", "%d घण्टा पहिले"),
CHAT_DAYS_AGO("%dd ago", "%d दिन पहिले"),
STORMY_TITLE("Stormy", "स्टर्मी"),
STORMY_MEET("Meet Stormy", "स्टर्मीलाई भेट्नुहोस्"),
STORMY_SUBTITLE("Your Vedic astrology AI assistant", "तपाईंको वैदिक ज्योतिष एआई सहायक"),
STORMY_INTRO("Ask about your birth chart, planetary periods, transits, compatibility, remedies, and more.", "आफ्नो जन्म कुण्डली, ग्रह अवधि, गोचर, अनुकूलता, उपाय र थप बारेमा सोध्नुहोस्।"),
STORMY_HELLO("Hello! I'm Stormy", "नमस्ते! म स्टर्मी हुँ"),
STORMY_HELLO_DESC("Your Vedic astrology assistant. Ask me anything about your birth chart, planetary periods, transits, compatibility, or remedies.", "तपाईंको वैदिक ज्योतिष सहायक। आफ्नो जन्म कुण्डली, ग्रह अवधि, गोचर, अनुकूलता, वा उपायहरूको बारेमा मलाई केही पनि सोध्नुहोस्।"),
STORMY_START_CHAT("Start New Chat", "नयाँ च्याट सुरु गर्नुहोस्"),
STORMY_CONFIGURE_MODELS("Configure AI Models", "एआई मोडेलहरू कन्फिगर गर्नुहोस्"),
STORMY_ENABLE_MODELS("Enable AI models to start chatting", "च्याट सुरु गर्न एआई मोडेलहरू सक्षम गर्नुहोस्"),
STORMY_ASK_PLACEHOLDER("Ask Stormy...", "स्टर्मीलाई सोध्नुहोस्..."),
STORMY_THINKING("Stormy is thinking...", "स्टर्मीले सोच्दैछ..."),
STORMY_REASONING("Stormy is reasoning...", "स्टर्मीले तर्क गर्दैछ..."),
STORMY_TYPING("Stormy is typing...", "स्टर्मीले टाइप गर्दैछ..."),
STORMY_ANALYZING("Stormy is analyzing...", "स्टर्मीले विश्लेषण गर्दैछ..."),
STORMY_ANALYZING_COMPATIBILITY("Stormy is analyzing compatibility...", "स्टर्मीले अनुकूलता विश्लेषण गर्दैछ..."),
STORMY_CALLING_TOOL("Calling %s...", "%s कल गर्दैछ..."),
STORMY_USING_TOOLS("Using tools: %s", "उपकरणहरू प्रयोग गर्दैछ: %s"),
STORMY_USING_TOOL("Using %s...", "%s प्रयोग गर्दैछ..."),
STORMY_REASONING_VEDIC("Reasoning through Vedic principles...", "वैदिक सिद्धान्तहरूमा तर्क गर्दैछ..."),
STORMY_GATHERING_DATA("Gathering astrological data...", "ज्योतिषीय डाटा संकलन गर्दैछ..."),
STORMY_COMPOSING("Composing response...", "प्रतिक्रिया रचना गर्दैछ..."),
STORMY_APPLYING_VEDIC("Applying Vedic principles...", "वैदिक सिद्धान्तहरू लागू गर्दैछ..."),
STORMY_PROCESSING("Processing...", "प्रशोधन गर्दैछ..."),
STORMY_NEEDS_INPUT("Stormy needs your input", "स्टर्मीलाई तपाईंको इनपुट चाहिन्छ"),
TOOL_STATUS_PENDING("Pending", "पर्खिएको"),
TOOL_STATUS_RUNNING("Running...", "चलिरहेको..."),
TOOL_STATUS_COMPLETED_IN("Completed in %s", "%s मा सम्पन्न"),
TOOL_STATUS_FAILED("Failed", "असफल"),
TOOLS_USED_LABEL("Used: %s", "प्रयोग गरियो: %s"),
TOOLS_MORE_COUNT(" +%d more", " +%d थप"),
TODO_IN_PROGRESS("In Progress", "प्रगतिमा"),
PLACEHOLDER_TYPE_RESPONSE("Type your response...", "तपाईंको प्रतिक्रिया टाइप गर्नुहोस्..."),
RESPONSE_SUBMITTED("Response submitted", "प्रतिक्रिया पेश गरियो"),
PROFILE_STATUS_PENDING("Pending", "पर्खिएको"),
PROFILE_STATUS_IN_PROGRESS("In Progress", "प्रगतिमा"),
PROFILE_STATUS_SUCCESS("Success", "सफल"),
PROFILE_STATUS_FAILED("Failed", "असफल"),
PROFILE_OP_CREATING("Creating Profile", "प्रोफाइल बनाउँदै"),
PROFILE_OP_UPDATING("Updating Profile", "प्रोफाइल अपडेट गर्दै"),
PROFILE_OP_DELETING("Deleting Profile", "प्रोफाइल हटाउँदै"),
PROFILE_OP_VIEWING("Viewing Profile", "प्रोफाइल हेर्दै"),
PROFILE_ID_LABEL("ID: %s", "आईडी: %s"),
AI_GENERATING("Generating...", "उत्पन्न गर्दैछ..."),
AI_ANALYZING_QUESTION("Analyzing your question...", "तपाईंको प्रश्न विश्लेषण गर्दै..."),
CHAT_SUGGESTION_DASHA("What's my current dasha period?", "मेरो हालको दशा अवधि के हो?"),
CHAT_SUGGESTION_CHART("Analyze my birth chart", "मेरो जन्म कुण्डली विश्लेषण गर्नुहोस्"),
CHAT_SUGGESTION_YOGAS("What yogas are present in my chart?", "मेरो कुण्डलीमा कुन योगहरू छन्?"),
CHAT_CLEAR("Clear Chat", "च्याट खाली गर्नुहोस्"),
CHAT_CLEAR_CONFIRM("Are you sure you want to clear all messages in this conversation?", "के तपाईं यस कुराकानीका सबै सन्देशहरू हटाउन निश्चित हुनुहुन्छ?"),
CHAT_CLEAR_BTN("Clear", "खाली गर्नुहोस्"),
CHAT_STOP("Stop", "रोक्नुहोस्"),
CHAT_SEND("Send", "पठाउनुहोस्"),
CHAT_BACK("Back", "पछाडि"),
CHAT_CHANGE_MODEL("Change model", "मोडेल परिवर्तन गर्नुहोस्"),
CHAT_MODEL_OPTIONS("Model options", "मोडेल विकल्पहरू"),
MODEL_OPTIONS_TITLE("Model Options", "मोडेल विकल्पहरू"),
MODEL_THINKING_MODE("Thinking Mode", "सोच्ने मोड"),
MODEL_THINKING_DESC("Extended reasoning before answering", "जवाफ दिनु अघि विस्तारित तर्क"),
MODEL_WEB_SEARCH("Web Search", "वेब खोज"),
MODEL_WEB_SEARCH_DESC("Search the web for current information", "वर्तमान जानकारीको लागि वेब खोज्नुहोस्"),
MODEL_DONE("Done", "सम्पन्न"),
MODEL_SELECT_TITLE("Select AI Model", "एआई मोडेल छान्नुहोस्"),
MODEL_AI_LABEL("AI Model", "एआई मोडेल"),
MODEL_SELECT_PROMPT("Select a model", "मोडेल छान्नुहोस्"),
MODEL_NONE_AVAILABLE("No models available", "कुनै मोडेल उपलब्ध छैन"),
MODEL_CONFIGURE("Configure Models", "मोडेलहरू कन्फिगर गर्नुहोस्"),
MODEL_MANAGE("Manage AI Models", "एआई मोडेलहरू व्यवस्थापन गर्नुहोस्"),
COURAGE_LEVEL("Level", "स्तर"),
COURAGE_PHYSICAL("Physical Courage", "शारीरिक साहस"),
COURAGE_MENTAL("Mental Courage", "मानसिक साहस"),
COURAGE_INITIATIVE("Initiative", "पहल"),
DWADASAMSA_HEALTH_CONCERNS("Health Concerns", "स्वास्थ्य चिन्ताहरू"),
AI_MODELS_TITLE("AI Models", "AI मोडेलहरू"),
AI_MODELS_ENABLED_COUNT("%d models enabled", "%d मोडेलहरू सक्षम"),
AI_MODELS_BACK("Back", "पछाडि"),
AI_MODELS_REFRESH("Refresh models", "मोडेलहरू रिफ्रेस गर्नुहोस्"),
AI_MODELS_FREE_TITLE("Free AI Models", "निःशुल्क AI मोडेलहरू"),
AI_MODELS_FREE_DESC("These models are provided by free API providers and don't require any API keys. Model availability may vary.", "यी मोडेलहरू निःशुल्क API प्रदायकहरूबाट प्रदान गरिएका हुन् र कुनै API कुञ्जी आवश्यक पर्दैन। मोडेल उपलब्धता फरक हुन सक्छ।"),
AI_MODELS_DEFAULT("Default Model", "पूर्वनिर्धारित मोडेल"),
AI_MODELS_NOT_SET("Not set", "सेट गरिएको छैन"),
AI_MODELS_SELECT_DEFAULT("Select Default Model", "पूर्वनिर्धारित मोडेल छान्नुहोस्"),
AI_MODELS_CANCEL("Cancel", "रद्द गर्नुहोस्"),
AI_MODELS_MODELS_ENABLED("%d/%d models enabled", "%d/%d मोडेलहरू सक्षम"),
AI_MODELS_ENABLE_ALL("Enable All", "सबै सक्षम गर्नुहोस्"),
AI_MODELS_DISABLE_ALL("Disable All", "सबै असक्षम गर्नुहोस्"),
AI_MODELS_TOOLS("Tools", "उपकरणहरू"),
AI_MODELS_REASONING("Reasoning", "तर्क"),
AI_MODELS_VISION("Vision", "दृष्टि"),
AI_MODELS_NONE("No Models Available", "कुनै मोडेल उपलब्ध छैन"),
AI_MODELS_NONE_DESC("Unable to fetch AI models. Check your internet connection and try again.", "AI मोडेलहरू प्राप्त गर्न असमर्थ। आफ्नो इन्टरनेट जडान जाँच गर्नुहोस् र पुन: प्रयास गर्नुहोस्।"),
AI_MODELS_RETRY("Retry", "पुन: प्रयास गर्नुहोस्"),
AI_PROVIDER_DEEPINFRA("DeepInfra", "डीपइन्फ्रा"),
AI_PROVIDER_QWEN("Qwen", "क्वेन"),
AI_PROVIDER_BLACKBOX("Blackbox AI", "ब्ल्याकबक्स AI"),
AI_PROVIDER_DDG("DuckDuckGo AI", "डकडकगो AI"),
UPACHAYA_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
UPACHAYA_LAGNA("Lagna", "लग्न"),
UPACHAYA_ACTIVE("Active", "सक्रिय"),
ARUDHA_SCREEN_TITLE("Arudha Pada", "आरुढ पद"),
ARUDHA_ANALYSIS_TITLE("Arudha Pada Analysis", "आरुढ पद विश्लेषण"),
ARUDHA_KEY_POSITIONS("Key Arudha Positions", "मुख्य आरुढ स्थितिहरू"),
ARUDHA_MANIFESTATION("Manifestation Strength", "प्रकटीकरण शक्ति"),
ARUDHA_PUBLIC_IMAGE("Public Image", "सार्वजनिक छवि"),
ARUDHA_CAREER("Career", "क्यारियर"),
ARUDHA_GAINS("Gains", "लाभ")
}
