package com.astro.storm.core.common
enum class StringKeyDoshaPart4(override val en: String, override val ne: String) : StringKeyInterface {
ARUDHA_RELATIONSHIPS("Relationships", "सम्बन्धहरू"),
ARUDHA_KEY_THEMES("Key Themes", "मुख्य विषयवस्तुहरू"),
ARUDHA_YOGAS_TITLE("Arudha Yogas", "आरुढ योगहरू"),
ARUDHA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
ARUDHA_CALCULATING("Calculating Arudha Padas...", "आरुढ पद गणना गर्दै..."),
ARUDHA_ABOUT_BTN("About Arudha Pada", "आरुढ पदको बारेमा"),
ASHTAKAVARGA_KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टि"),
ASHTAKAVARGA_DESC_FMT("Bindu strength analysis - %s", "विन्दु बल विश्लेषण - %s"),
ASHTAKAVARGA_DISTRIBUTION_DESC("Bindu distribution analysis", "विन्दु वितरण विश्लेषण"),
ASHTAKAVARGA_INFO_A11Y("Ashtakavarga info", "अष्टकवर्ग जानकारी"),
ASHTAKAVARGA_STRONGEST("STRONGEST HOUSES", "सबैभन्दा बलियो भावहरू"),
ASHTAKAVARGA_WEAKEST("WEAKEST HOUSES", "सबैभन्दा कमजोर भावहरू"),
ASHTAKAVARGA_PLANET_TOTALS("Planet Bindu Totals", "ग्रह बिन्दु योग"),
ASHTAKAVARGA_SARVA_DESC("Sarvashtakavarga is the combined bindu strength from all seven planets for each house/sign.", "सर्वाष्टकवर्ग प्रत्येक भाव/राशिको लागि सातै ग्रहहरूको संयुक्त बिन्दु शक्ति हो।"),
ASHTAKAVARGA_ABOUT_TITLE("About Ashtakavarga", "अष्टकवर्गको बारेमा"),
    ASHTAKAVARGA_ABOUT_DESC("Ashtakavarga is a unique Vedic system that calculates the strength of each house by analyzing beneficial points (bindus)", "Ashtakavarga is a unique Vedic system that calculates the strength of each house by analyzing beneficial points (bindus)"),
ASHTAKAVARGA_INTERPRETATION("Interpretation Guide:", "व्याख्या मार्गदर्शन:"),
ASHTAKAVARGA_GUIDE_TEXT("• 30+ bindus: Very strong, excellent results\n• 25-30 bindus: Good strength, favorable\n• 20-25 bindus: Average, mixed results\n• Below 20: Weak, challenges expected", "• ३०+ बिन्दु: धेरै बलियो, उत्कृष्ट परिणाम\n• २५-३० बिन्दु: राम्रो शक्ति, अनुकूल\n• २०-२५ बिन्दु: औसत, मिश्रित परिणाम\n• २० भन्दा कम: कमजोर, चुनौतीहरू अपेक्षित"),
ASHTAKAVARGA_BINDUS_SUFFIX("bindus", "बिन्दुहरू"),
HOUSE_SIG_1("Self, Body, Personality", "स्वयं, शरीर, व्यक्तित्व"),
HOUSE_SIG_2("Wealth, Speech, Family", "धन, वाणी, परिवार"),
HOUSE_SIG_3("Siblings, Courage", "दाजुभाइ, साहस"),
HOUSE_SIG_4("Home, Mother, Property", "घर, आमा, सम्पत्ति"),
HOUSE_SIG_5("Children, Education", "सन्तान, शिक्षा"),
HOUSE_SIG_6("Health, Enemies", "स्वास्थ्य, शत्रु"),
HOUSE_SIG_7("Marriage, Partnership", "विवाह, साझेदारी"),
HOUSE_SIG_8("Transformation", "रूपान्तरण"),
HOUSE_SIG_9("Fortune, Father", "भाग्य, पिता"),
HOUSE_SIG_10("Career, Fame", "क्यारियर, प्रसिद्धि"),
HOUSE_SIG_11("Gains, Wishes", "लाभ, इच्छा"),
HOUSE_SIG_12("Losses, Liberation", "हानी, मोक्ष"),
AVASTHA_SCREEN_TITLE("Planetary Avasthas", "ग्रह अवस्थाहरू"),
AVASTHA_SUBTITLE("Planetary States & Conditions", "ग्रह स्थिति र अवस्थाहरू"),
AVASTHA_NO_CHART_DESC("Create or select a birth chart to analyze planetary Avasthas.", "ग्रह अवस्थाहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
AVASTHA_ABOUT_TITLE("About Planetary Avasthas", "ग्रह अवस्थाहरूको बारेमा"),
    AVASTHA_ABOUT_DESC("Avasthas are planetary states that indicate how effectively a planet can deliver its results.\n\nFour Types of Avasthas:\n\n1. Baladi (Age-based)", "Avasthas are planetary states that indicate how effectively a planet can deliver its results.\n\nFour Types of Avasthas:\n\n1. Baladi (Age-based)"),
AVASTHA_OVERALL_STRENGTH("Overall Planetary Strength", "समग्र ग्रह बल"),
AVASTHA_STRONGEST("Strongest", "सबैभन्दा बलियो"),
AVASTHA_NEEDS_ATTENTION("Needs Attention", "ध्यान दिनुपर्ने"),
NITYA_SCREEN_TITLE("Nitya Yoga", "नित्य योग"),
NITYA_SUBTITLE("27 Daily Yogas", "२७ दैनिक योगहरू"),
NITYA_NO_DATA_DESC("Create or select a birth chart to view Nitya Yoga analysis.", "नित्य योग विश्लेषण हेर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
NITYA_ABOUT_TITLE("About Nitya Yoga", "नित्य योगको बारेमा"),
    NITYA_ABOUT_DESC("Nitya Yoga (Daily Yoga)", "Nitya Yoga (Daily Yoga)"),
NITYA_PROGRESS("Progress", "प्रगति"),
NITYA_POSITION("Position", "स्थिति"),
NITYA_NATURE("Nature", "प्रकृति"),
NITYA_CURRENT_PROGRESS("Progress in Current Yoga", "वर्तमान योगमा प्रगति"),
NITYA_SUITABLE("Suitable Activities", "उपयुक्त गतिविधिहरू"),
NITYA_AVOID("Activities to Avoid", "बच्नुपर्ने गतिविधिहरू"),
NITYA_NEXT("Next:", "अर्को:"),
NITYA_REMAINING("remaining", "बाँकी"),
PANCHA_SCREEN_TITLE("Panch Mahapurusha Yoga", "पञ्च महापुरुष योग"),
PANCHA_SUBTITLE("Five Great Person Yogas", "पाँच महापुरुष योगहरू"),
PANCHA_ABOUT_TITLE("About Panch Mahapurusha Yoga", "पञ्च महापुरुष योगको बारेमा"),
    PANCHA_ABOUT_DESC("Panch Mahapurusha Yoga (Five Great Person Yogas)", "Panch Mahapurusha Yoga (Five Great Person Yogas)"),
PANCHA_NO_YOGAS_DISPLAY("No Yogas to Display", "देखाउनको लागि कुनै योगहरू छैनन्"),
    PANCHA_NO_YOGAS_DESC("For a Mahapurusha Yoga to form, Mars, Mercury, Jupiter, Venus, or Saturn must be in Kendra (1,4,7,10)", "For a Mahapurusha Yoga to form, Mars, Mercury, Jupiter, Venus, or Saturn must be in Kendra (1,4,7,10)"),
    PANCHA_STATUS_FOUND("Yoga(s)", "Yoga(s)"),
    PANCHA_STATUS_FOUND_DESC("You have %1\$d Panch Mahapurusha Yoga(s)", "You have %1\$d Panch Mahapurusha Yoga(s)"),
PANCHA_STATUS_NONE_DESC("None of the five Mahapurusha Yogas are formed", "पाँच महापुरुष योगहरू मध्ये कुनै पनि बनेको छैन"),
PANCHA_COMBINED("Combined Effects", "संयुक्त प्रभावहरू"),
PANCHA_SYNERGIES("Synergies:", "समन्वयहरू:"),
PANCHA_NO_CHART_DESC("Create or select a birth chart to analyze Panch Mahapurusha Yogas.", "पञ्च महापुरुष योगहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
TARABALA_JANMA("Janma", "जन्म"),
TARABALA_SAMPAT("Sampat", "सम्पत"),
TARABALA_VIPAT("Vipat", "विफत"),
TARABALA_KSHEMA("Kshema", "क्षेम"),
TARABALA_PRATYARI("Pratyari", "प्रत्यरि"),
TARABALA_SADHAKA("Sadhaka", "साधक"),
TARABALA_VADHA("Vadha", "वध"),
TARABALA_MITRA("Mitra", "मित्र"),
TARABALA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),
TARABALA_DESC_JANMA("Birth star - challenging for new beginnings", "जन्म नक्षत्र - नयाँ सुरुवातीका लागि चुनौतीपूर्ण"),
TARABALA_DESC_SAMPAT("Wealth - favorable for financial matters", "सम्पत्ति - आर्थिक मामिलाका लागि शुभ"),
TARABALA_DESC_VIPAT("Danger - avoid important activities", "खतरा - महत्त्वपूर्ण कार्यहरू नगर्नुहोस्"),
TARABALA_DESC_KSHEMA("Well-being - favorable for health matters", "कल्याण - स्वास्थ्य मामिलाका लागि शुभ"),
TARABALA_DESC_PRATYARI("Obstacle - creates hindrances", "बाधा - अवरोधहरू सिर्जना गर्दछ"),
TARABALA_DESC_SADHAKA("Achievement - good for goals", "उपलब्धि - लक्ष्यका लागि राम्रो"),
TARABALA_DESC_VADHA("Death - highly inauspicious", "वध - अत्यन्त अशुभ"),
TARABALA_DESC_MITRA("Friend - favorable for relationships", "मित्र - सम्बन्धका लागि शुभ"),
TARABALA_DESC_PARAMA_MITRA("Great Friend - highly auspicious", "परम मित्र - अत्यन्त शुभ"),
GEM_RUBY("Ruby", "माणिक"),
GEM_PEARL("Pearl", "मोती"),
GEM_RED_CORAL("Red Coral", "मुगा"),
GEM_EMERALD("Emerald", "पन्ना"),
GEM_YELLOW_SAPPHIRE("Yellow Sapphire", "पुष्पराज"),
GEM_DIAMOND("Diamond", "हीरा"),
GEM_BLUE_SAPPHIRE("Blue Sapphire", "नीलम"),
GEM_HESSONITE("Hessonite", "गोमेद"),
GEM_CATS_EYE("Cat's Eye", "लहसुनिया"),
DAY_SUNDAY("Sunday", "आइतबार"),
DAY_MONDAY("Monday", "सोमबार"),
DAY_TUESDAY("Tuesday", "मङ्गलबार"),
DAY_WEDNESDAY("Wednesday", "बुधबार"),
DAY_THURSDAY("Thursday", "बिहीबार"),
DAY_FRIDAY("Friday", "शुक्रबार"),
DAY_SATURDAY("Saturday", "शनिबार"),
DAY_ANY("Any day", "कुनै पनि दिन"),
GOCHARA_SCREEN_TITLE("Gochara Vedha", "गोचर वेध"),
GOCHARA_SUBTITLE("Transit Obstructions", "गोचर अवरोधहरू"),
GOCHARA_ABOUT_TITLE("About Gochara Vedha", "गोचर वेधको बारेमा"),
    GOCHARA_ABOUT_DESC("Gochara refers to planetary transits, while Vedha means \", "Gochara refers to planetary transits, while Vedha means \"),
GOCHARA_SCORE("Overall Transit Score", "समग्र गोचर अङ्क"),
GOCHARA_FAVORABLE("Favorable", "शुभ"),
GOCHARA_OBSTRUCTED("Obstructed", "अवरोधित"),
GOCHARA_MOON_SIGN("Natal Moon Sign", "जन्म राशी"),
GOCHARA_ACTIVE_VEDHAS("Active Vedhas", "सक्रिय वेध"),
GOCHARA_TRANSITS_TRACKED("Transits Tracked", "ट्र्याक गरिएका गोचरहरू"),
GOCHARA_CURRENT_TRANSITS("Current Planetary Transits", "वर्तमान ग्रह गोचरहरू"),
GOCHARA_NATURALLY_FAVORABLE("Naturally Favorable", "स्वाभाविक रूपमा शुभ"),
GOCHARA_NATURALLY_UNFAVORABLE("Naturally Unfavorable", "स्वाभाविक रूपमा अशुभ"),
GOCHARA_VEDHA_LABEL("VEDHA", "वेध"),
GOCHARA_TRANSIT_EFFECTS("Transit Effects", "गोचर प्रभावहरू"),
GOCHARA_VEDHA_OBSTRUCTION("Vedha Obstruction", "वेध अवरोध"),
GOCHARA_FROM("From:", "बाट:"),
GOCHARA_SEVERITY("Severity:", "गम्भीरता:"),
GOCHARA_NO_CHART_DESC("Create or select a birth chart to analyze Gochara Vedha effects.", "गोचर वेध प्रभावहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
GOCHARA_VEDHAS("Vedhas", "वेधहरू"),
GOCHARA_FORECAST("Forecast", "पूर्वानुमान"),
GRAHA_SCREEN_TITLE("Graha Yuddha", "ग्रह युद्ध"),
GRAHA_SUBTITLE("Planetary War Analysis", "ग्रह युद्ध विश्लेषण"),
GRAHA_ACTIVE_WARS("Active Wars", "सक्रिय युद्धहरू"),
GRAHA_DASHA_EFFECTS("Dasha Effects", "दशा प्रभावहरू"),
GRAHA_ANALYZING("Analyzing Planetary Wars...", "ग्रह युद्ध विश्लेषण गर्दै..."),
GRAHA_WAR_STATUS("War Status", "युद्ध स्थिति"),
GRAHA_ANALYSIS_SUMMARY("Analysis Summary", "विश्लेषण सारांश"),
GRAHA_OVERALL_IMPACT("Overall War Impact", "समग्र युद्ध प्रभाव"),
GRAHA_VICTORY("Victorious", "विजयी"),
GRAHA_DEFEATED("Defeated", "पराजित"),
GRAHA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
GRAHA_NO_WARS("No Active Planetary Wars", "कुनै सक्रिय ग्रह युद्ध छैन"),
GRAHA_NO_WARS_DESC("All planets are operating peacefully", "सबै ग्रहहरू शान्तिपूर्ण रूपमा काम गरिरहेका छन्"),
GRAHA_VS("vs", "विरुद्ध"),
GRAHA_SEPARATION("Separation", "अन्तर"),
GRAHA_ADVANTAGE("Advantage", "फाइदा"),
GRAHA_NO_DASHA_EFFECTS("No War-Related Dasha Effects", "कुनै युद्ध-सम्बन्धित दशा प्रभावहरू छैनन्"),
GRAHA_NO_REMEDIES("No Specific Remedies Needed", "कुनै विशेष उपाय आवश्यक छैन"),
GRAHA_NO_DASHA_DESC("Planets in War not currently activated in Dasha/Antardasha.", "युद्धमा रहेका ग्रहहरू हाल दशा/अन्तर्दशामा सक्रिय छैनन्।"),
GRAHA_NO_REMEDIES_DESC("Since there are no active planetary wars, remedial measures are not required.", "कुनै सक्रिय ग्रह युद्ध नभएकोले, उपायहरू आवश्यक छैनन्।"),
GRAHA_ABOUT_TITLE("About Graha Yuddha", "ग्रह युद्धको बारेमा"),
    GRAHA_ABOUT_DESC("Graha Yuddha (Planetary War)", "Graha Yuddha (Planetary War)"),
GRAHA_DEFEATS_MSG("%1\$2 defeats %2\$2", "%1\$2 ले %2\$2 लाई जित्छ"),
    GRAHA_IN_HOUSE_MSG("in %1\$2 (House %2\$2)", "in %1\$2 (House %2\$2)"),
KEMA_SCREEN_TITLE("Kemadruma Yoga", "केमद्रुम योग"),
KEMA_SUBTITLE("Moon Isolation Analysis", "चन्द्रमा एक्लोपन विश्लेषण"),
KEMA_MOON("Moon", "चन्द्रमा"),
KEMA_CANCELLATIONS("Cancellations", "भंग"),
KEMA_IMPACTS("Impacts", "प्रभावहरू"),
KEMA_FORMED("Kemadruma Yoga is formed in this chart", "यो कुण्डलीमा केमद्रुम योग बनेको छ"),
KEMA_NOT_FORMED("Kemadruma Yoga is not formed", "केमद्रुम योग बनेको छैन"),
KEMA_FORMATION_DETAILS("Formation Details", "योग निर्माण विवरण"),
KEMA_MOON_POSITION("Moon Position", "चन्द्रमाको स्थिति"),
KEMA_SURROUNDING_HOUSES("Surrounding Houses Analysis", "वरपरका भावहरूको विश्लेषण"),
KEMA_BEFORE_MOON("Before Moon", "चन्द्रमा अघि"),
KEMA_AFTER_MOON("After Moon", "चन्द्रमा पछि"),
KEMA_MOON_HOUSE("Moon's House", "चन्द्रमाको भाव"),
KEMA_CONDITION_MET("No planets in houses adjacent to Moon - Kemadruma condition met", "चन्द्रमाको नजिकका भावहरूमा कुनै ग्रह छैन - केमद्रुम शर्त पूरा भयो"),
KEMA_NO_CANCELLATIONS("No Cancellations Found", "कुनै भंग फेला परेन"),
KEMA_NA("Not Applicable", "लागू हुँदैन"),
    KEMA_NO_CANCELLATIONS_DESC("No Kemadruma Bhanga (cancellation)", "No Kemadruma Bhanga (cancellation)"),
KEMA_NO_IMPACTS("No Negative Impacts", "कुनै नकारात्मक प्रभाव छैन"),
KEMA_NO_IMPACTS_DESC("Moon is well-supported, ensuring emotional stability and mental peace.", "चन्द्रमा राम्रोसँग समर्थित छ, जसले भावनात्मक स्थिरता र मानसिक शान्ति सुनिश्चित गर्दछ।"),
KEMA_NO_REMEDIES("No Remedies Needed", "कुनै उपाय आवश्यक छैन"),
KEMA_NO_REMEDIES_DESC("Since Kemadruma Yoga is not formed or is fully cancelled, no remedies are required.", "केमद्रुम योग नबनेको वा पूर्ण रूपमा भंग भएकोले, कुनै उपाय आवश्यक छैन।"),
KEMA_ABOUT_TITLE("About Kemadruma Yoga", "केमद्रुम योगको बारेमा"),
    KEMA_ABOUT_DESC("Kemadruma Yoga forms when the Moon has no planets (except Sun, Rahu, Ketu)", "Kemadruma Yoga forms when the Moon has no planets (except Sun, Rahu, Ketu)"),
    KEMA_CANCELLATIONS_FOUND("%1\$2 Cancellation(s)", "%1\$2 Cancellation(s)"),
KEMA_FORMATION_MAIN("Moon lacks planetary support in adjacent houses.", "चन्द्रमालाई नजिकका भावहरूमा ग्रहहरूको समर्थन छैन।"),
KEMA_FORMATION_2ND_EMPTY("2nd house from Moon is empty.", "चन्द्रमाबाट दोस्रो भाव खाली छ।"),
KEMA_FORMATION_12TH_EMPTY("12th house from Moon is empty.", "चन्द्रमाबाट बाह्रौं भाव खाली छ।"),
KEMA_FORMATION_UNASPECTED("Moon has no planetary conjunction.", "चन्द्रमाको कुनै ग्रहसँग युति छैन।"),
KEMA_REASON_2ND("No planets in 2nd house from Moon", "चन्द्रमाबाट दोस्रो भावमा कुनै ग्रह छैन"),
KEMA_REASON_12TH("No planets in 12th house from Moon", "चन्द्रमाबाट बाह्रौं भावमा कुनै ग्रह छैन"),
KEMA_REASON_CONJUNCT("Moon is not conjunct with any planet", "चन्द्रमा कुनै ग्रहसँग युतिमा छैन"),
KEMA_FORMATION_STRENGTH("Formation strength: %1\$2%%", "योग बल: %1\$2%%"),
KEMA_NAKSHATRA("Nakshatra", "नक्षत्र"),
KEMA_PAKSHA("Paksha", "पक्ष"),
KEMA_BRIGHTNESS("Brightness", "चमक"),
KEMA_MOON_STRENGTH("Moon Strength:", "चन्द्रमा बल:"),
LAL_KITAB_NOTE_DISTINCT("Lal Kitab remedies are unique and different from traditional Vedic remedies.", "लाल किताब उपायहरू अद्वितीय छन् र परम्परागत वैदिक उपायहरूभन्दा फरक छन्।"),
LAL_KITAB_RECOMMENDED_REMEDIES("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
    LAL_KITAB_AFFLICTION_KANYA("Kanya Rin (Debt of Young Women)", "Kanya Rin (Debt of Young Women)"),
LAL_KITAB_AFFLICTION_GRAHAN("Grahan Dosha", "ग्रहण दोष"),
LAL_KITAB_AFFLICTION_SHANI("Shani Affliction", "शनि पीडा"),
LAL_KITAB_AFFLICTION_GENERAL("General Affliction", "सामान्य पीडा"),
LAL_KITAB_SECTION_REMEDIES("Remedies", "उपायहरू"),
LAL_KITAB_GENERAL_PRINCIPLES("General Principles of Lal Kitab", "लाल किताबका सामान्य सिद्धान्तहरू"),
    LAL_KITAB_RIN_TITLE("Karmic Debts (Rin)", "Karmic Debts (Rin)"),
LAL_KITAB_RIN_DESC("Karmic debts indicate areas where remedial measures are needed to balance past karma.", "कर्म ऋणहरूले विगतको कर्म सन्तुलन गर्न उपायहरू आवश्यक पर्ने क्षेत्रहरू संकेत गर्दछ।"),
LAL_KITAB_RIN_NONE_TITLE("No Significant Karmic Debts", "कुनै महत्त्वपूर्ण कर्म ऋण छैन"),
LAL_KITAB_RIN_NONE_DESC("Your chart does not indicate major karmic debts requiring immediate remedies.", "तपाईंको कुण्डलीले तत्काल उपाय आवश्यक पर्ने प्रमुख कर्म ऋणहरू संकेत गर्दैन।"),
PANCHA_NO_YOGAS("No Yogas", "कुनै योग छैन"),
DASHA_SHORT_VIM("Vim", "विं"),
DASHA_SHORT_YOG("Yog", "यो"),
DASHA_SHORT_ASH("Ash", "अष्टो"),
DASHA_SHORT_SUD("Sud", "सुद"),
DASHA_SHORT_CHA("Cha", "चर"),
QUALITY_LABEL("Quality", "गुणस्तर"),
FROM_LABEL("from", "बाट"),
PLANETS_TITLE("Transiting Planets", "गोचर ग्रहहरू"),
UPACHAYA_TRANSITS_LABEL("Transits", "गोचरहरू"),
MARAKA_SCREEN_TITLE("Maraka Analysis", "मारक विश्लेषण"),
MARAKA_SUBTITLE("Longevity & Health Planets", "आयु र स्वास्थ्य ग्रहहरू"),
MARAKA_TAB_PLANETS("Planets", "ग्रहहरू"),
MARAKA_TAB_LONGEVITY("Longevity", "आयु"),
MARAKA_PRIMARY("Primary", "प्राथमिक"),
MARAKA_SECONDARY("Secondary", "माध्यमिक"),
MARAKA_PERIODS("Periods", "अवधि"),
MARAKA_LONGEVITY_SCORE("Longevity Score", "आयु स्कोर"),
MARAKA_PRIMARY_TITLE("Primary Maraka Planets", "प्राथमिक मारक ग्रहहरू"),
MARAKA_SECONDARY_TITLE("Secondary Maraka Planets", "माध्यमिक मारक ग्रहहरू"),
MARAKA_NO_SIGNIFICANT("No Significant Maraka Influences", "कुनै महत्त्वपूर्ण मारक प्रभाव छैन"),
MARAKA_PROTECTIVE("Protective Factors", "सुरक्षात्मक कारकहरू"),
MARAKA_AFFLICTIONS("Afflictions", "पीडाहरू"),
MARAKA_METHODS("Longevity Assessment Methods", "आयु मूल्याङ्कन विधिहरू"),
MARAKA_AMSAYURDAYA("Amsayurdaya", "अंशायुर्दाय"),
MARAKA_PINDAYURDAYA("Pindayurdaya", "पिण्डायुर्दाय"),
MARAKA_NISARGAYURDAYA("Nisargayurdaya", "निसर्गायुर्दाय"),
MARAKA_FACTORS("Longevity Factors", "आयु कारकहरू"),
MARAKA_POSITIVE("Positive Factors", "सकारात्मक कारकहरू"),
MARAKA_NEGATIVE("Negative Factors", "नकारात्मक कारकहरू"),
MARAKA_CRITICAL_PERIODS("Critical Dasha Periods", "महत्त्वपूर्ण दशा अवधि"),
MARAKA_NO_CRITICAL("No Critical Periods Identified", "कुनै महत्त्वपूर्ण अवधि पहिचान गरिएको छैन"),
MARAKA_NO_REMEDIES("No specific remedies needed at this time.", "यस समयमा कुनै विशेष उपाय आवश्यक छैन।"),
MARAKA_ANALYZING("Analyzing Maraka influences...", "मारक प्रभाव विश्लेषण गर्दै..."),
MARAKA_NO_CHART_DESC("Please generate a chart to view Maraka analysis.", "मारक विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
MARAKA_ABOUT_TITLE("About Maraka Analysis", "मारक विश्लेषणको बारेमा"),
    MARAKA_ABOUT_DESC("Maraka planets are associated with the 2nd and 7th houses, which are maraka sthanas (death-inflicting houses)", "Maraka planets are associated with the 2nd and 7th houses, which are maraka sthanas (death-inflicting houses)"),
BADHAKA_SCREEN_TITLE("Badhaka Analysis", "बाधक विश्लेषण"),
BADHAKA_SUBTITLE("Obstruction Analysis", "अवरोध विश्लेषण"),
BADHAKA_TAB_PLANETS("Planets", "ग्रहहरू"),
BADHAKA_TAB_OBSTACLES("Obstacles", "अवरोधहरू"),
BADHAKA_STHANA("Badhaka Sthana", "बाधक स्थान"),
BADHAKA_PRIMARY("Primary", "प्राथमिक"),
BADHAKA_SECONDARY("Secondary", "माध्यमिक"),
BADHAKA_SEVERITY("Severity", "गम्भीरता"),
BADHAKA_PRIMARY_TITLE("Primary Badhaka Planets", "प्राथमिक बाधक ग्रहहरू"),
BADHAKA_SECONDARY_TITLE("Secondary Badhaka Planets", "माध्यमिक बाधक ग्रहहरू"),
BADHAKA_NO_SIGNIFICANT("No Significant Badhaka Influences", "कुनै महत्त्वपूर्ण बाधक प्रभाव छैन"),
BADHAKA_MITIGATING("Mitigating Factors", "न्यूनीकरण कारकहरू"),
BADHAKA_LORD("Badhaka Lord", "बाधक स्वामी"),
BADHAKA_OBSTACLE_TYPES("Obstacle Types", "अवरोध प्रकारहरू"),
BADHAKA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
BADHAKA_NO_AREAS("No significantly affected areas identified.", "कुनै महत्त्वपूर्ण प्रभावित क्षेत्र पहिचान गरिएको छैन।"),
BADHAKA_NATURE("Nature of Obstacles", "अवरोधको प्रकृति"),
BADHAKA_CRITICAL_PERIODS("Critical Obstruction Periods", "महत्त्वपूर्ण अवरोध अवधि"),
BADHAKA_NO_CRITICAL("No Critical Periods Identified", "कुनै महत्त्वपूर्ण अवधि पहिचान गरिएको छैन"),
BADHAKA_NO_REMEDIES("No specific remedies needed at this time.", "यस समयमा कुनै विशेष उपाय आवश्यक छैन।"),
BADHAKA_ANALYZING("Analyzing Badhaka influences...", "बाधक प्रभाव विश्लेषण गर्दै..."),
BADHAKA_NO_CHART_DESC("Please generate a chart to view Badhaka analysis.", "बाधक विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
BADHAKA_ABOUT_TITLE("About Badhaka Analysis", "बाधक विश्लेषणको बारेमा"),
    BADHAKA_ABOUT_DESC("Badhaka planets create obstacles and hindrances in life. The Badhaka Sthana (obstructing house)", "Badhaka planets create obstacles and hindrances in life. The Badhaka Sthana (obstructing house)"),
VIPAREETA_SCREEN_TITLE("Vipareeta Raja Yoga", "विपरीत राजयोग"),
VIPAREETA_SUBTITLE("Reverse Fortune Yogas", "उल्टो भाग्य योगहरू"),
VIPAREETA_TAB_BENEFITS("Benefits", "लाभहरू"),
VIPAREETA_TAB_FACTORS("Factors", "कारकहरू"),
VIPAREETA_NO_YOGAS("No Vipareeta Raja Yogas", "कुनै विपरीत राजयोग छैन"),
VIPAREETA_ONE_YOGA("One Vipareeta Raja Yoga", "एक विपरीत राजयोग"),
VIPAREETA_TWO_YOGAS("Two Vipareeta Raja Yogas", "दुई विपरीत राजयोग"),
VIPAREETA_ALL_YOGAS("All Three Vipareeta Raja Yogas!", "तीनवटै विपरीत राजयोग!"),
VIPAREETA_STRENGTH("Overall Strength", "समग्र शक्ति"),
VIPAREETA_YOGAS_FORMED("Yogas Formed", "बनेका योगहरू"),
VIPAREETA_EXCHANGES("Exchanges", "परिवर्तनहरू"),
VIPAREETA_ACTIVATIONS("Activations", "सक्रियताहरू"),
    VIPAREETA_EXCHANGES_TITLE("Dusthana Parivartana (Exchanges)", "Dusthana Parivartana (Exchanges)"),
VIPAREETA_BENEFITS("Benefits", "लाभहरू"),
VIPAREETA_PRIMARY_BENEFITS("Primary Benefits", "प्राथमिक लाभहरू"),
VIPAREETA_NO_BENEFITS("No specific benefits identified without active yogas.", "सक्रिय योग बिना कुनै विशेष लाभ पहिचान गरिएको छैन।"),
VIPAREETA_ACTIVATION_PERIODS("Activation Periods", "सक्रियता अवधि"),
VIPAREETA_NO_TIMING("No activation periods without active yogas.", "सक्रिय योग बिना कुनै सक्रियता अवधि छैन।"),
VIPAREETA_ENHANCEMENT("Enhancement Factors", "वृद्धि कारकहरू"),
VIPAREETA_CANCELLATION("Cancellation Factors", "रद्द कारकहरू"),
VIPAREETA_NO_FACTORS("No significant enhancement or cancellation factors.", "कुनै महत्त्वपूर्ण वृद्धि वा रद्द कारकहरू छैनन्।"),
VIPAREETA_ANALYZING("Analyzing Vipareeta Raja Yogas...", "विपरीत राजयोग विश्लेषण गर्दै..."),
VIPAREETA_NO_CHART_DESC("Please generate a chart to view Vipareeta Raja Yoga analysis.", "विपरीत राजयोग विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
VIPAREETA_ABOUT_TITLE("About Vipareeta Raja Yoga", "विपरीत राजयोगको बारेमा"),
    VIPAREETA_ABOUT_DESC("Vipareeta Raja Yogas are formed when lords of dusthana houses (6th, 8th, 12th)", "Vipareeta Raja Yogas are formed when lords of dusthana houses (6th, 8th, 12th)"),
ISHTA_KASHTA_SCREEN_TITLE("Ishta Kashta Phala", "इष्ट कष्ट फल"),
ISHTA_KASHTA_SUBTITLE("Benefic & Malefic Results", "शुभ र अशुभ फलहरू"),
ISHTA_KASHTA_TAB_PLANETS("Planets", "ग्रहहरू"),
ISHTA_KASHTA_TAB_LIFE_AREAS("Life Areas", "जीवन क्षेत्रहरू"),
    ISHTA_KASHTA_ISHTA("Ishta (Benefic)", "Ishta (Benefic)"),
    ISHTA_KASHTA_KASHTA("Kashta (Malefic)", "Kashta (Malefic)"),
ISHTA_KASHTA_BENEFIC("Benefic", "शुभ"),
ISHTA_KASHTA_NEUTRAL("Neutral", "तटस्थ"),
ISHTA_KASHTA_MALEFIC("Malefic", "अशुभ"),
ISHTA_KASHTA_MOST_BENEFIC("Most Benefic", "सबैभन्दा शुभ"),
ISHTA_KASHTA_MOST_MALEFIC("Most Malefic", "सबैभन्दा अशुभ"),
ISHTA_KASHTA_UCCHA_BALA("Uccha Bala", "उच्च बल"),
ISHTA_KASHTA_CHESTA_BALA("Chesta Bala", "चेष्टा बल"),
ISHTA_KASHTA_AFFECTS("Affects", "प्रभाव"),
ISHTA_KASHTA_LIFE_AREAS("Life Area Impact Analysis", "जीवन क्षेत्र प्रभाव विश्लेषण"),
ISHTA_KASHTA_INFLUENCED_BY("Influenced by:", "प्रभावित:"),
ISHTA_KASHTA_PERIOD_PREDICTIONS("Dasha Period Predictions", "दशा अवधि भविष्यवाणी"),
ISHTA_KASHTA_BENEFITS("Expected Benefits", "अपेक्षित लाभहरू"),
ISHTA_KASHTA_CHALLENGES("Potential Challenges", "सम्भावित चुनौतीहरू"),
ISHTA_KASHTA_ANALYZING("Analyzing Ishta Kashta Phala...", "इष्ट कष्ट फल विश्लेषण गर्दै..."),
ISHTA_KASHTA_NO_CHART_DESC("Please generate a chart to view Ishta Kashta Phala analysis.", "इष्ट कष्ट फल विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
ISHTA_KASHTA_ABOUT_TITLE("About Ishta Kashta Phala", "इष्ट कष्ट फलको बारेमा"),
    ISHTA_KASHTA_ABOUT_DESC("Ishta Kashta Phala is derived from Shadbala calculations per BPHS. Ishta Phala (benefic result)", "Ishta Kashta Phala is derived from Shadbala calculations per BPHS. Ishta Phala (benefic result)"),
PANCHA_STRENGTH("Strength", "बल"),
PANCHA_PERIODS("Periods", "अवधिहरू"),
PANCHA_EFFECTS_TITLE("%s Effects", "%s प्रभावहरू"),
PANCHA_PHYSICAL("Physical", "शारीरिक"),
PANCHA_MENTAL("Mental", "मानसिक"),
PANCHA_CAREER("Career", "करियर"),
PANCHA_SPIRITUAL("Spiritual", "आध्यात्मिक"),
PANCHA_RELATIONSHIPS("Relationships", "सम्बन्ध"),
PANCHA_ACTIVATION_PERIODS("Activation Periods", "सक्रियता अवधिहरू"),
PANCHA_RECOMMENDATIONS_TITLE("%s Recommendations", "%s सिफारिसहरू"),
PANCHA_TIMING_LABEL("Timing: %s", "समय: %s"),
PANCHA_DETAILS_EMPTY_DESC("This section will show details when Mahapurusha Yogas are present in the chart.", "यस खण्डले कुण्डलीमा महापुरुष योगहरू उपस्थित हुँदा विवरणहरू देखाउनेछ।"),
PANCHA_ANALYZING("Analyzing Panch Mahapurusha Yogas...", "पञ्च महापुरुष योगहरू विश्लेषण गर्दै..."),
DOSHA_MANGLIK("Manglik Dosha", "मांगलिक दोष"),
DOSHA_NADI("Nadi Dosha", "नाडी दोष"),
DOSHA_BHAKOOT("Bhakoot Dosha", "भकूट दोष"),
DOSHA_PRESENT("Present", "उपस्थित"),
DOSHA_ABSENT("Absent", "अनुपस्थित"),
DOSHA_CANCELLED("Cancelled", "रद्द"),
DOSHA_REMEDIES_AVAILABLE("Remedies Available", "उपायहरू उपलब्ध"),
MANGLIK_NONE("No Manglik Dosha", "मांगलिक दोष छैन"),
MANGLIK_PARTIAL("Partial Manglik", "आंशिक मांगलिक"),
MANGLIK_FULL("Full Manglik", "पूर्ण मांगलिक"),
    MANGLIK_DOUBLE("Double Manglik (Severe)", "Double Manglik (Severe)"),
MANGLIK_NO_DOSHA_DESC("No Manglik Dosha present.", "मांगलिक दोष छैन।"),
MANGLIK_DETECTED("detected", "पत्ता लाग्यो"),
MANGLIK_INTENSITY("intensity", "तीव्रता"),
MANGLIK_MARS_IN("Mars in", "मंगल"),
MANGLIK_FACTOR_FROM_LAGNA("Mars in House {house} from Lagna", "लग्नबाट भाव {house} मा मंगल"),
MANGLIK_FACTOR_FROM_MOON("Mars in House {house} from Moon", "चन्द्रबाट भाव {house} मा मंगल"),
MANGLIK_FACTOR_FROM_VENUS("Mars in House {house} from Venus", "शुक्रबाट भाव {house} मा मंगल"),
MANGLIK_BOTH_NON("Both non-Manglik - No concerns", "दुवै गैर-मांगलिक - कुनै चिन्ता छैन"),
    MANGLIK_BOTH_MATCH("Both Manglik - Doshas cancel each other (Manglik to Manglik match is recommended)", "Both Manglik - Doshas cancel each other (Manglik to Manglik match is recommended)"),
MANGLIK_MINOR_IMBALANCE("Minor Manglik imbalance - Manageable with remedies", "सानो मांगलिक असन्तुलन - उपायहरूद्वारा व्यवस्थापनयोग्य"),
MANGLIK_BRIDE_ONLY("Bride is Manglik while Groom is not - Kumbh Vivah or other remedies advised", "दुलही मांगलिक छिन् जबकि दुलाहा छैनन् - कुम्भ विवाह वा अन्य उपायहरू सल्लाह दिइएको"),
MANGLIK_GROOM_ONLY("Groom is Manglik while Bride is not - Remedies strongly recommended", "दुलाहा मांगलिक छन् जबकि दुलही छैनन् - उपायहरू दृढतापूर्वक सिफारिस गरिएको"),
MANGLIK_SIGNIFICANT_IMBALANCE("Significant Manglik imbalance - Careful consideration and remedies essential", "महत्त्वपूर्ण मांगलिक असन्तुलन - सावधानीपूर्ण विचार र उपायहरू आवश्यक"),
DOSHA_CANCEL_EXPLAINED("Dosha Cancellation Factors Explained", "दोष रद्द कारकहरू व्याख्या"),
    MANGLIK_CANCEL_EXPLANATION("Manglik Dosha can be cancelled through various factors: both partners being Manglik (mutual cancellation)", "Manglik Dosha can be cancelled through various factors: both partners being Manglik (mutual cancellation)"),
MANGLIK_QUICK_NONE("No Dosha", "दोष छैन"),
MANGLIK_QUICK_BOTH("Both Manglik", "दुवै मांगलिक"),
MANGLIK_QUICK_BRIDE("Bride Only", "दुलही मात्र"),
MANGLIK_QUICK_GROOM("Groom Only", "दुलाहा मात्र")
}
