package com.astro.storm.core.common

enum class StringKeyVargaPart2(override val en: String, override val ne: String) : StringKeyInterface {
    VARGA_D20_TITLE("Vimsamsa (D20)", "विंशांश (D20)"),
    VARGA_D24_DESC("Education, Learning", "शिक्षा, सिकाइ"),
    VARGA_D24_DESC_FULL("Education, Learning", "शिक्षा, सिकाइ"),
    VARGA_D24_NAME("Siddhamsa Chart", "चतुर्विंशांश कुण्डली"),
    VARGA_D24_TITLE("Siddhamsa (D24)", "सिद्धांश (D24)"),
    VARGA_D27_DESC("Strength, Weakness", "बल, कमजोरी"),
    VARGA_D27_DESC_FULL("Strength, Weakness", "बल, कमजोरी"),
    VARGA_D27_NAME("Bhamsa Chart", "सप्तविंशांश कुण्डली"),
    VARGA_D27_TITLE("Bhamsa (D27)", "भांश (D27)"),
    VARGA_D2_DESC("Wealth, Prosperity", "धन, समृद्धि"),
    VARGA_D2_NAME("Hora Chart", "होरा कुण्डली"),
    VARGA_D2_TITLE("Hora (D2)", "होरा (D2)"),
    VARGA_D30_DESC("Evils, Misfortunes", "अशुभ, दुर्भाग्य"),
    VARGA_D30_DESC_FULL("Evils, Misfortunes", "दुर्भाग्य, विपत्ति"),
    VARGA_D30_NAME("Trimsamsa Chart", "त्रिंशांश कुण्डली"),
    VARGA_D30_TITLE("Trimsamsa (D30)", "त्रिंशांश (D30)"),
    VARGA_D3_DESC("Siblings, Courage", "भाइबहिनी, साहस"),
    VARGA_D3_DESC_FULL("Siblings, Courage, Vitality", "भाइबहिनी, साहस, जीवनशक्ति"),
    VARGA_D3_NAME("Drekkana Chart", "द्रेक्काण कुण्डली"),
    VARGA_D3_TITLE("Drekkana (D3)", "द्रेक्काण (D3)"),
    VARGA_D40_DESC("Auspicious/Inauspicious Effects", "शुभाशुभ प्रभावहरू"),
    VARGA_D40_TITLE("Khavedamsa (D40)", "खवेदांश (D40)"),
    VARGA_D45_DESC("General Indications", "सामान्य सङ्केतहरू"),
    VARGA_D45_TITLE("Akshavedamsa (D45)", "अक्षवेदांश (D45)"),
    VARGA_D4_DESC("Fortune, Property", "भाग्य, सम्पत्ति"),
    VARGA_D4_NAME("Chaturthamsa Chart", "चतुर्थांश कुण्डली"),
    VARGA_D4_TITLE("Chaturthamsa (D4)", "चतुर्थांश (D4)"),
    VARGA_D5_DESC("Fame, Power, Authority", "ख्याति, शक्ति, अधिकार"),
    VARGA_D5_TITLE("Panchamsa (D5)", "पञ्चमांश (D5)"),
    VARGA_D60_DESC("Past Life Karma", "पूर्वजन्मको कर्म"),
    VARGA_D60_DESC_FULL("Past Life Karma", "पूर्वजन्मको कर्म"),
    VARGA_D60_NAME("Shashtiamsa Chart", "षष्टिांश कुण्डली"),
    VARGA_D60_TITLE("Shashtiamsa (D60)", "षष्ट्यंश (D60)"),
    VARGA_D6_DESC("Health, Debts, Enemies", "स्वास्थ्य, ऋण, शत्रु"),
    VARGA_D6_TITLE("Shasthamsa (D6)", "षष्ठांश (D6)"),
    VARGA_D7_DESC("Children, Progeny", "सन्तान"),
    VARGA_D7_NAME("Saptamsa Chart", "सप्तांश कुण्डली"),
    VARGA_D7_TITLE("Saptamsa (D7)", "सप्तमांश (D7)"),
    VARGA_D81_DESC("Hidden Potentials, Deep Navamsa", "लुकेका सम्भावनाहरू"),
    VARGA_D81_TITLE("Navnavamsa (D81)", "नवनवांश (D81)"),
    VARGA_D8_DESC("Longevity, Transformation", "आयु, रूपान्तरण"),
    VARGA_D8_TITLE("Ashtamsa (D8)", "अष्टमांश (D8)"),
    VARGA_D9_DESC("Marriage, Dharma", "विवाह, धर्म"),
    VARGA_D9_DESC_FULL("Marriage, Dharma, Fortune", "विवाह, धर्म, भाग्य"),
    VARGA_D9_NAME("Navamsa Chart", "नवांश कुण्डली"),
    VARGA_D9_TITLE("Navamsa (D9)", "नवमांश (D9)"),
    VARGA_DASAMSA("Dasamsa", "दशांश"),
    VARGA_DREKKANA("Drekkana", "द्रेक्काण"),
    VARGA_HORA("Hora", "होरा"),
    VARGA_LAGNA("Lagna", "लग्न"),
    VARGA_NAVAMSA("Navamsa", "नवांश"),
    VARGA_PLANETARY_POSITIONS("PLANETARY POSITIONS", "ग्रह स्थितिहरू"),
    VARGA_POSITIONS("Varga Positions", "वर्ग स्थितिहरू"),
    VARGA_SAPTAMSA("Saptamsa", "सप्तांश")
}
