package com.astro.storm.core.common

enum class StringKeyGeneralPart2(override val en: String, override val ne: String) : StringKeyInterface {
    ASHTAK_WEAKEST("Weakest", "सबैभन्दा कमजोर"),
    ASHTAVARGA_AVERAGE("Average (22-25 SAV)", "औसत (२२-२५ सर्वाष्टकवर्ग)"),
    ASHTAVARGA_BAV_SCORE("BAV Score", "भिन्नाष्टकवर्ग स्कोर"),
    ASHTAVARGA_BINDU_THRESHOLD("Bindu Threshold", "बिन्दु सीमा"),
    ASHTAVARGA_CURRENT_TRANSIT("Current Transit Analysis", "वर्तमान गोचर विश्लेषण"),
    ASHTAVARGA_EKADHIPATYA_REDUCTION("Ekadhipatya Reduction", "एकाधिपत्य घटाउ"),
    ASHTAVARGA_EVENT_PROBABILITY("Event Probability", "घटना सम्भावना"),
    ASHTAVARGA_FAVORABLE_SIGNS("Favorable Transit Signs", "अनुकूल गोचर राशिहरू"),
    ASHTAVARGA_HIGH_BINDU("High Bindu (30+)", "उच्च बिन्दु (३०+)"),
    ASHTAVARGA_HIGH_PROBABILITY("High Probability", "उच्च सम्भावना"),
    ASHTAVARGA_LOW_BINDU("Low Bindu (<25)", "न्यून बिन्दु (<२५)"),
    ASHTAVARGA_LOW_PROBABILITY("Low Probability", "न्यून सम्भावना"),
    ASHTAVARGA_MEDIUM_BINDU("Medium Bindu (25-30)", "मध्यम बिन्दु (२५-३०)"),
    ASHTAVARGA_MEDIUM_PROBABILITY("Medium Probability", "मध्यम सम्भावना"),
    ASHTAVARGA_PLANET_POSITION("Planet Position", "ग्रह स्थिति"),
    ASHTAVARGA_REDUCED_SAV("Reduced SAV (Shodya Pinda)", "घटाइएको सर्वाष्टकवर्ग (शोध्य पिण्ड)"),
    ASHTAVARGA_REDUCTION_RULES("Reduction Rules Applied", "घटाउने नियमहरू लागू"),
    ASHTAVARGA_SAV_SCORE("SAV Score", "सर्वाष्टकवर्ग स्कोर"),
    ASHTAVARGA_SIGN_BAV("Planet's BAV", "ग्रहको भिन्नाष्टकवर्ग"),
    ASHTAVARGA_SIGN_SAV("Sign SAV", "राशि सर्वाष्टकवर्ग"),
    ASHTAVARGA_STRONG("Strong (26-30 SAV)", "बलियो (२६-३० सर्वाष्टकवर्ग)"),
    ASHTAVARGA_TAB_ANALYSIS("Analysis", "विश्लेषण"),
    ASHTAVARGA_TAB_BY_PLANET("By Planet", "ग्रहानुसार"),
    ASHTAVARGA_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    ASHTAVARGA_TAB_TIMELINE("Timeline", "समयरेखा"),
    ASHTAVARGA_TRANSIT_ABOUT("About Ashtavarga Transits", "अष्टकवर्ग गोचर बारेमा"),
    ASHTAVARGA_TRANSIT_BEST_SIGN("Best Sign", "उत्तम राशि"),
    ASHTAVARGA_TRANSIT_DESC("Ashtavarga Transit method is a powerful Vedic astrology technique that measures transit effects based on bindu points from the natal chart.", "अष्टकवर्ग गोचर विधि एक शक्तिशाली वैदिक ज्योतिष प्रविधि हो जसले जन्म कुण्डलीको विन्दु बिन्दुहरूको आधारमा गोचर प्रभावहरू मापन गर्दछ।"),
    ASHTAVARGA_TRANSIT_EKADHIPATYA("Ekadhipatya Shodhana", "एकाधिपत्य शोधन"),
    ASHTAVARGA_TRANSIT_HIGHLIGHTS("Current Transit Highlights", "हालको गोचर हाइलाइटहरू"),
    ASHTAVARGA_TRANSIT_INFO_DESC("Ashtavarga Transit Predictions use the bindu contribution from each planet to predict transit intensity. High SAV scores (30+) indicate favorable periods, while low scores (<25) suggest caution.", "अष्टकवर्ग गोचर भविष्यवाणीहरूले गोचर तीव्रता भविष्यवाणी गर्न प्रत्येक ग्रहबाट बिन्दु योगदान प्रयोग गर्छन्। उच्च सर्वाष्टकवर्ग स्कोर (३०+) अनुकूल अवधिहरू संकेत गर्छन्, जबकि कम स्कोर (<२५) सावधानी सुझाव दिन्छन्।"),
    ASHTAVARGA_TRANSIT_INFO_TITLE("About Ashtavarga Transit", "अष्टकवर्ग गोचरको बारेमा"),
    ASHTAVARGA_TRANSIT_LIFE_AREA("Life Area Impact", "जीवन क्षेत्र प्रभाव"),
    ASHTAVARGA_TRANSIT_NEXT("Next Significant Transit", "अर्को महत्त्वपूर्ण गोचर"),
    ASHTAVARGA_TRANSIT_REDUCTION("Shodhana (Reduction) Results", "शोधन (न्यूनीकरण) परिणामहरू"),
    ASHTAVARGA_TRANSIT_SCORE("Overall Transit Score", "समग्र गोचर अङ्क"),
    ASHTAVARGA_TRANSIT_STRENGTH("Transit Strength", "गोचर बल"),
    ASHTAVARGA_TRANSIT_SUBTITLE("Transit Intensity by Bindu Score", "बिन्दु स्कोरद्वारा गोचर तीव्रता"),
    ASHTAVARGA_TRANSIT_SUMMARY("Transit Summary", "गोचर सारांश"),
    ASHTAVARGA_TRANSIT_TITLE("Ashtavarga Transits", "अष्टकवर्ग गोचर"),
    ASHTAVARGA_TRANSIT_TRIKONA("Trikona Shodhana", "त्रिकोण शोधन"),
    ASHTAVARGA_TRANSIT_UNABLE("Unable to calculate Ashtavarga transits", "अष्टकवर्ग गोचर गणना गर्न सकिएन"),
    ASHTAVARGA_TRANSIT_VEDIC_REF("Vedic Reference: BPHS Ashtakavarga chapters, Jataka Parijata", "वैदिक सन्दर्भ: बृहत् पाराशर होरा शास्त्र अष्टकवर्ग अध्यायहरू, जातक पारिजात"),
    ASHTAVARGA_TRANSIT_WEAK_SIGN("Weak Sign", "कमजोर राशि"),
    ASHTAVARGA_TRIKONA_REDUCTION("Trikona Reduction", "त्रिकोण घटाउ"),
    ASHTAVARGA_UNFAVORABLE_SIGNS("Unfavorable Transit Signs", "प्रतिकूल गोचर राशिहरू"),
    ASHTAVARGA_UPCOMING_TRANSITS("Upcoming Important Transits", "आउँदा महत्त्वपूर्ण गोचरहरू"),
    ASHTAVARGA_VERY_STRONG("Very Strong (30+ SAV)", "अत्यन्त बलियो (३०+ सर्वाष्टकवर्ग)"),
    ASHTAVARGA_WEAK("Weak (<22 SAV)", "कमजोर (<२२ सर्वाष्टकवर्ग)"),
    ASPECT_APPLYING("Applying", "समीप आउँदै"),
    ASPECT_CASTS_ON("%s casts %s on %s", "%s ले %s मा %s दृष्टि राख्छ"),
    ASPECT_CONJUNCTION("Conjunction", "युति"),
    ASPECT_DRISHTI_BALA("Drishti Bala", "दृष्टि बल"),
    ASPECT_DURAPHA_EFFECT("Hard aspect creates challenges that strengthen through difficulty", "कडा पक्षले कठिनाइद्वारा बलियो बनाउने चुनौतीहरू सिर्जना गर्छ"),
    ASPECT_EASARAPHA_EFFECT("Separating aspect suggests matters are concluding", "विलग पक्षले मामिलाहरू समाप्त हुँदैछन् भनी सुझाव दिन्छ"),
    ASPECT_FAVORABLE_FOR("favorable", "अनुकूल"),
    ASPECT_GENERIC_EFFECT("%s influences matters with %s energy", "%s ले %s ऊर्जासहित मामिलाहरूलाई प्रभाव पार्छ"),
    ASPECT_INTERP_BENEFIC("Transit %1\$s %2\$s natal %3\$s (%4\$s) - mixed but generally supportive", "गोचर %1\$s %2\$s जन्म %3\$s (%4\$s) - मिश्रित तर सामान्यतया सहयोगी"),
    ASPECT_INTERP_BENEFIC_HARMONIC("Favorable: Transit %1\$s %2\$s natal %3\$s (%4\$s) - beneficial influence", "शुभ: गोचर %1\$s %2\$s जन्म %3\$s (%4\$s) - लाभदायक प्रभाव"),
    ASPECT_INTERP_CHALLENGING("Transit %1\$s %2\$s natal %3\$s (%4\$s) - requires attention", "गोचर %1\$s %2\$s जन्म %3\$s (%4\$s) - ध्यान दिन आवश्यक"),
    ASPECT_INTERP_HARMONIC("Transit %1\$s %2\$s natal %3\$s (%4\$s) - harmonious connection", "गोचर %1\$s %2\$s जन्म %3\$s (%4\$s) - सामंजस्यपूर्ण सम्बन्ध"),
    ASPECT_ITHASALA_EFFECT("%s applying to %s promises fulfillment", "%s %s मा निकटवर्ती हुँदा पूर्तिको वाचा"),
    ASPECT_KAMBOOLA_EFFECT("Powerful angular conjunction promises prominent success", "शक्तिशाली केन्द्रीय युतिले प्रमुख सफलताको वाचा गर्छ"),
    ASPECT_MODERATE("Moderate", "मध्यम"),
    ASPECT_NATURE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    ASPECT_NATURE_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
    ASPECT_NATURE_SIGNIFICANT("Significant", "महत्त्वपूर्ण"),
    ASPECT_NATURE_VARIABLE("Variable", "परिवर्तनशील"),
    ASPECT_OPPOSITION("Opposition", "दृष्टि"),
    ASPECT_PREDICTION_TEMPLATE("The %s between %s and %s is %s for matters of %s.", "%s र %s बीचको %s %s को मामिलाहरूको लागि %s छ।"),
    ASPECT_RADDA_EFFECT("Retrograde motion causes delays or reversals", "वक्री गतिले ढिलाइ वा उल्टो परिणाम ल्याउँछ"),
    ASPECT_REQUIRING_ATTENTION("requiring attention", "ध्यान चाहिने"),
    ASPECT_SEPARATING("Separating", "टाढा हुँदै"),
    ASPECT_SEXTILE("Sextile", "षडाष्टक"),
    ASPECT_SQUARE("Square", "केन्द्र"),
    ASPECT_STRENGTH_ADHIKA("Strong (Adhika)", "अधिक (बलियो)"),
    ASPECT_STRENGTH_ALPA("Weak (Alpa)", "अल्प (कमजोर)"),
    ASPECT_STRENGTH_EXACT("Exact (Purna)", "पूर्ण (एकदम सटीक)"),
    ASPECT_STRENGTH_MADHYA("Medium (Madhya)", "मध्यम"),
    ASPECT_STRENGTH_SUNYA("Negligible (Sunya)", "शून्य (नगण्य)"),
    ASPECT_STRONG("Strong", "बलियो"),
    ASPECT_SUPPORTIVE("supportive", "समर्थनात्मक"),
    ASPECT_TRINE("Trine", "त्रिकोण"),
    ASPECT_TYPE_7TH("7th Aspect", "सप्तम दृष्टि"),
    ASPECT_TYPE_CONJUNCTION("Conjunction", "युति"),
    ASPECT_TYPE_JUPITER_5TH("Jupiter 5th Aspect", "गुरुको पञ्चम दृष्टि"),
    ASPECT_TYPE_JUPITER_9TH("Jupiter 9th Aspect", "गुरुको नवम दृष्टि"),
    ASPECT_TYPE_MARS_4TH("Mars 4th Aspect", "मंगलको चतुर्थ दृष्टि"),
    ASPECT_TYPE_MARS_8TH("Mars 8th Aspect", "मंगलको अष्टम दृष्टि"),
    ASPECT_TYPE_SATURN_10TH("Saturn 10th Aspect", "शनिको दशम दृष्टि"),
    ASPECT_TYPE_SATURN_3RD("Saturn 3rd Aspect", "शनिको तृतीय दृष्टि"),
    ASPECT_VERY_STRONG("Very Strong", "अति बलियो"),
    ASPECT_VERY_WEAK("Very Weak", "अति कमजोर"),
    ASPECT_WEAK("Weak", "कमजोर"),
    ASSESS_BALANCED("Balance of challenging and supportive placements", "चुनौतीपूर्ण र सहयोगी स्थितिहरूको सन्तुलन"),
    ASSESS_GEN_POS("Generally favorable placement pattern", "सामान्यतया अनुकूल स्थिति ढाँचा"),
    ASSESS_HIGHLY_AUSP("Multiple auspicious Pushkara placements provide natural protection", "धेरै शुभ पुष्कर स्थितिहरूले प्राकृतिक सुरक्षा प्रदान गर्दछ"),
    ASSESS_MODERATE("Some sensitive placements present; recommended remedies will help", "केही संवेदनशील स्थितिहरू छन्; सिफारिस गरिएका उपायहरूले मद्दत गर्नेछन्"),
    ASSESS_NEEDS_ATTN("Multiple sensitive placements require attention and regular remedies", "धेरै संवेदनशील स्थितिहरूलाई ध्यान र नियमित उपायहरूको आवश्यकता छ"),
    ATMAKARAKA_KARMIC_LESSON("Karmic Lesson", "कार्मिक पाठ"),
    ATMAKARAKA_SOUL_DESIRE("Soul's Desire", "आत्माको इच्छा"),
    ATMAKARAKA_SPIRITUAL_PATH("Spiritual Path", "आध्यात्मिक मार्ग"),
    ATMAKARAKA_TITLE("Soul Significator (Atmakaraka)", "आत्म संकेतक (आत्मकारक)"),
    ATTACHMENT_STYLE("Attachment Style", "आसक्ति शैली"),
    ATTRACTION_STYLE("Attraction Style", "आकर्षण शैली"),
    AUSPICIOUSNESS_AUSPICIOUS("Auspicious", "शुभ"),
    AUSPICIOUSNESS_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यन्त शुभ"),
    AUSPICIOUSNESS_HIGHLY_INAUSPICIOUS("Highly Inauspicious", "अत्यन्त अशुभ"),
    AUSPICIOUSNESS_INAUSPICIOUS("Inauspicious", "अशुभ"),
    AUSPICIOUSNESS_NEUTRAL("Neutral", "तटस्थ"),
    AUTHORITY_RELATIONSHIP("Relationship with Authority", "अधिकारसँगको सम्बन्ध"),
    AUTHORITY_STYLE("Your Authority Style", "तपाईंको अधिकार शैली"),
    AUTHORITY_TITLE("Authority Dynamics", "अधिकार गतिशीलता"),
    AVERAGE_STRENGTH("Average Strength", "औसत बल"),
    AYANAMSA_KRISHNAMURTI("Krishnamurti", "कृष्णमूर्ति"),
    AYANAMSA_LAHIRI("Lahiri", "लहिरी"),
    AYANAMSA_RAMAN("Raman", "रमण"),
    AYANAMSA_TRUE_CHITRAPAKSHA("True Chitrapaksha", "सत्य चित्रपक्ष"),
    AYURVEDIC_RECS("Ayurvedic Recommendations", "आयुर्वेदिक सिफारिसहरू"),
    BADHAKA_ABOUT_DESC("Badhaka planets create obstacles and hindrances in life. The Badhaka Sthana (obstructing house) varies based on the modality of the ascendant sign: 11th for movable signs, 9th for fixed signs, and 7th for dual signs. Understanding Badhaka influences helps navigate challenging periods and apply appropriate remedies.", "बाधक ग्रहहरूले जीवनमा अवरोध र बाधाहरू सिर्जना गर्दछन्। बाधक स्थान लग्न राशिको प्रकृति अनुसार फरक हुन्छ: चर राशिको लागि ११औं, स्थिर राशिको लागि ९औं, र द्विस्वभाव राशिको लागि ७औं। बाधक प्रभावहरू बुझ्दा चुनौतीपूर्ण अवधिहरू पार गर्न र उचित उपायहरू लागू गर्न मद्दत गर्दछ।"),
    BADHAKA_ABOUT_TITLE("About Badhaka Analysis", "बाधक विश्लेषणको बारेमा"),
    BADHAKA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    BADHAKA_ANALYZING("Analyzing Badhaka influences...", "बाधक प्रभाव विश्लेषण गर्दै..."),
    BADHAKA_CRITICAL_PERIODS("Critical Obstruction Periods", "महत्त्वपूर्ण अवरोध अवधि"),
    BADHAKA_LORD("Badhaka Lord", "बाधक स्वामी"),
    BADHAKA_MITIGATING("Mitigating Factors", "न्यूनीकरण कारकहरू"),
    BADHAKA_NATURE("Nature of Obstacles", "अवरोधको प्रकृति"),
    BADHAKA_NO_AREAS("No significantly affected areas identified.", "कुनै महत्त्वपूर्ण प्रभावित क्षेत्र पहिचान गरिएको छैन।"),
    BADHAKA_NO_CHART_DESC("Please generate a chart to view Badhaka analysis.", "बाधक विश्लेषण हेर्न कृपया कुण्डली बनाउनुहोस्।"),
    BADHAKA_NO_CRITICAL("No Critical Periods Identified", "कुनै महत्त्वपूर्ण अवधि पहिचान गरिएको छैन"),
    BADHAKA_NO_REMEDIES("No specific remedies needed at this time.", "यस समयमा कुनै विशेष उपाय आवश्यक छैन।"),
    BADHAKA_NO_SIGNIFICANT("No Significant Badhaka Influences", "कुनै महत्त्वपूर्ण बाधक प्रभाव छैन"),
    BADHAKA_OBSTACLE_TYPES("Obstacle Types", "अवरोध प्रकारहरू"),
    BADHAKA_PRIMARY("Primary", "प्राथमिक"),
    BADHAKA_PRIMARY_TITLE("Primary Badhaka Planets", "प्राथमिक बाधक ग्रहहरू"),
    BADHAKA_SCREEN_TITLE("Badhaka Analysis", "बाधक विश्लेषण"),
    BADHAKA_SECONDARY("Secondary", "माध्यमिक"),
    BADHAKA_SECONDARY_TITLE("Secondary Badhaka Planets", "माध्यमिक बाधक ग्रहहरू"),
    BADHAKA_SEVERITY("Severity", "गम्भीरता"),
    BADHAKA_STHANA("Badhaka Sthana", "बाधक स्थान"),
    BADHAKA_SUBTITLE("Obstruction Analysis", "अवरोध विश्लेषण"),
    BADHAKA_TAB_OBSTACLES("Obstacles", "अवरोधहरू"),
    BADHAKA_TAB_PLANETS("Planets", "ग्रहहरू"),
    BALANCE_LABEL("Balance at Birth", "जन्ममा सन्तुलन"),
    BEEJA_MANTRA("Beeja Mantra", "बीज मन्त्र"),
    BENEFIC("Benefic", "शुभ"),
    BENEFIT_DEBTS("Overcoming debts and financial obligations", "ऋण र आर्थिक दायित्वहरूबाट पार पाउनु"),
    BENEFIT_FAME_DEATH("Fame and recognition after death", "मृत्युपछि प्रसिद्धि र मान्यता"),
    BENEFIT_FEARLESS("Freedom from fear and anxiety", "डर र चिन्ताबाट मुक्ति"),
    BENEFIT_FOREIGN("Success in foreign lands", "विदेशी भूमिमा सफलता"),
    BENEFIT_HEALTH("Good health despite challenging health indications", "चुनौतीपूर्ण स्वास्थ्य संकेतहरूको बावजुद राम्रो स्वास्थ्य"),
    BENEFIT_INHERITANCE("Gains through inheritance and legacy", "उत्तराधिकार र विरासतबाट लाभ"),
    BENEFIT_LIBERATION("Liberation from bondage", "बन्धनबाट मुक्ति"),
    BENEFIT_LITIGATION("Success in litigation and legal matters", "मुद्दा मामिला र कानुनी मामिलाहरूमा सफलता"),
    BENEFIT_LONGEVITY("Potential for longevity", "दीर्घायुको सम्भावना"),
    BENEFIT_MOKSHA("Spiritual advancement and moksha", "आध्यात्मिक उन्नति र मोक्ष"),
    BENEFIT_OCCULT("Success in occult and esoteric studies", "तन्त्रमन्त्र र रहस्यमयी अध्ययनमा सफलता"),
    BENEFIT_REDUCED_LOSS("Reduced expenditure and losses", "खर्च र घाटामा कमी"),
    BENEFIT_SERVICE("Happiness through service and daily work", "सेवा र दैनिक कार्यबाट सुख"),
    BENEFIT_TRANSFORM("Transformation through difficulties", "कठिनाइहरू मार्फत रूपान्तरण"),
    BENEFIT_VICTORY("Victory over enemies and competitors", "शत्रु र प्रतिस्पर्धीहरूमाथि विजय"),
    BEST_DAY("Best Day", "सर्वोत्तम दिन"),
    BEST_TIME("Best Time", "सर्वोत्तम समय"),
    BEST_TIMES("Best Meditation Times", "सर्वोत्तम ध्यान समयहरू"),
    BHAKOOT_2_12("Dhan-Vyaya (2-12) Bhakoot Dosha - financial concerns possible.", "धन-व्यय (२-१२) भकुट दोष - आर्थिक चिन्ता सम्भव।"),
    BHAKOOT_2_12_DESC("May cause financial fluctuations and differences in spending habits.", "आर्थिक उतार-चढाव र खर्च बानीमा भिन्नता हुन सक्छ।"),
    BHAKOOT_5_9("Signs are in 5-9 (Trine) relationship - actually favorable.", "राशिहरू ५-९ (त्रिकोण) सम्बन्धमा छन् - वास्तवमा अनुकूल।"),
    BHAKOOT_5_9_DESC("Trine relationship is auspicious for progeny, dharma, and spiritual growth.", "त्रिकोण सम्बन्ध सन्तान, धर्म र आध्यात्मिक विकासको लागि शुभ छ।"),
    BHAKOOT_6_8("Shadashtak (6-8) Bhakoot Dosha - health concerns may arise.", "षडाष्टक (६-८) भकुट दोष - स्वास्थ्य चिन्ता हुन सक्छ।"),
    BHAKOOT_6_8_DESC("May affect health and cause separation tendencies. Most serious Bhakoot dosha.", "स्वास्थ्यमा असर पार्न र विच्छेद प्रवृत्ति हुन सक्छ। सबैभन्दा गम्भीर भकुट दोष।"),
    BHAKOOT_CANCELLED("Bhakoot dosha cancelled by same sign lord - no adverse effects.", "उही राशि स्वामीद्वारा भकुट दोष रद्द - कुनै प्रतिकूल प्रभाव छैन।"),
    BHAKOOT_CANCEL_ELEMENT("Both Moon signs share same element ({element}) - Partial Cancellation", "दुवै चन्द्र राशिले एउटै तत्व ({element}) साझा गर्छन् - आंशिक रद्द"),
    BHAKOOT_CANCEL_EXALTATION("Lord is exalted in partner's sign - Partial Cancellation", "स्वामी साथीको राशिमा उच्च छ - आंशिक रद्द"),
    BHAKOOT_CANCEL_EXPLANATION("Bhakoot Dosha cancellation occurs when deeper planetary relationships indicate harmony. Even though Moon signs are in challenging positions, the underlying planetary friendships or same lords can neutralize the dosha effects.", "भकुट दोष रद्द गहन ग्रह सम्बन्धहरूले सामञ्जस्य संकेत गर्दा हुन्छ। यद्यपि चन्द्र राशिहरू चुनौतीपूर्ण स्थानमा छन्, अन्तर्निहित ग्रह मित्रता वा उही स्वामीहरूले दोष प्रभावहरू निष्क्रिय पार्न सक्छन्।"),
    BHAKOOT_CANCEL_FRIENDLY("Moon sign lords have friendly disposition - Partial Cancellation", "चन्द्र राशि स्वामीहरूको मैत्रीपूर्ण स्वभाव छ - आंशिक रद्द"),
    BHAKOOT_CANCEL_MUTUAL_FRIENDS("Moon sign lords ({lord1} & {lord2}) are mutual friends - Full Cancellation", "चन्द्र राशि स्वामी ({lord1} र {lord2}) पारस्परिक मित्र हुन् - पूर्ण रद्द"),
    BHAKOOT_CANCEL_SAME_LORD("Same lord ({lord}) rules both Moon signs - Full Cancellation", "उही स्वामी ({lord}) ले दुवै चन्द्र राशि शासन गर्छ - पूर्ण रद्द"),
    BHAKOOT_DESC("Love, health, and financial compatibility", "प्रेम, स्वास्थ्य र आर्थिक अनुकूलता"),
    BHAKOOT_DOSHA_TYPES("No dosha = 7 points. 2-12 position (Dhan-Vyaya dosha) = Financial concerns. 6-8 position (Shadashtak dosha) = Health and separation concerns (most serious).", "कुनै दोष छैन = ७ अंक। २-१२ स्थिति (धन-व्यय दोष) = आर्थिक चिन्ता। ६-८ स्थिति (षडाष्टक दोष) = स्वास्थ्य र विच्छेद चिन्ता (सबैभन्दा गम्भीर)।"),
    BHAKOOT_FAVORABLE("Signs are in favorable positions for marital harmony.", "राशिहरू वैवाहिक सामञ्जस्यको लागि अनुकूल स्थानमा छन्।"),
    BHAKOOT_IMPORTANCE("Bhakoot assesses emotional love, family welfare, and financial prosperity. It's based on sign positions and is crucial for long-term happiness.", "भकुटले भावनात्मक प्रेम, पारिवारिक कल्याण र आर्थिक समृद्धि मूल्याङ्कन गर्दछ। यो राशि स्थितिहरूमा आधारित छ र दीर्घकालीन खुशीको लागि महत्त्वपूर्ण छ।"),
    BHAKOOT_NO_DOSHA("No Bhakoot dosha - excellent compatibility for love, health, and finances.", "भकुट दोष छैन - प्रेम, स्वास्थ्य र वित्तको लागि उत्कृष्ट अनुकूलता।"),
    BHAKOOT_REMEDY_LOW("Remedy: Perform Graha Shanti puja for Moon sign lords of both partners. Chant Vishnu Sahasranama on Thursdays for 21 weeks. Donate white items, rice, and silver on Mondays. Financial planning together is essential.", "उपाय: दुवै साझेदारको चन्द्र राशि स्वामीको ग्रह शान्ति पूजा गर्नुहोस्। २१ हप्ता बिहीबारमा विष्णु सहस्रनाम जाप गर्नुहोस्। सोमबारमा सेता वस्तुहरू, चामल र चाँदी दान गर्नुहोस्। सँगै वित्तीय योजना आवश्यक छ।"),
    BHANGA_ANGULAR_MOON("Moon in angular house", "कोणीय भावमा चन्द्र"),
    BHANGA_BENEFIC_ASPECT("Benefic planet aspects Moon", "शुभ ग्रहले चन्द्रलाई देख्छ"),
    BHANGA_BENEFIC_CONJUNCTION("Benefic planet conjuncts Moon", "शुभ ग्रह चन्द्रसँग युति"),
    BHANGA_FULL_MOON("Full or bright Moon", "पूर्ण वा उज्यालो चन्द्र"),
    BHANGA_JUPITER_ASPECT("Jupiter aspects Moon", "बृहस्पतिले चन्द्रलाई देख्छ"),
    BHANGA_KENDRA_LAGNA("Planets in Kendra from Lagna", "लग्नबाट केन्द्रमा ग्रहहरू"),
    BHANGA_KENDRA_MOON("Planets in Kendra from Moon", "चन्द्रबाट केन्द्रमा ग्रहहरू"),
    BHANGA_MOON_EXALTED("Moon in exaltation", "चन्द्र उच्चमा"),
    BHANGA_MOON_FRIEND("Moon in friendly sign", "चन्द्र मित्र राशिमा"),
    BHANGA_MOON_KENDRA("Moon in Kendra from Lagna", "लग्नबाट केन्द्रमा चन्द्र"),
    BHANGA_MOON_OWN("Moon in own sign", "चन्द्र स्वराशिमा"),
    BHANGA_STRONG_DISPOSITOR("Strong dispositor", "बलियो राशीश"),
    BHANGA_VENUS_ASPECT("Venus aspects Moon", "शुक्रले चन्द्रलाई देख्छ"),
    BIRTH_DATA_SUMMARY("Birth Data Summary", "जन्म डाटा सारांश"),
    BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    BLESSINGS_BHADRA("Intelligence, Eloquence, Business success, Learning ability, Youthfulness", "बुद्धि, वाक्पटुता, व्यापार सफलता, सिक्ने क्षमता, यौवन"),
    BLESSINGS_HAMSA("Wisdom, Fortune, Spiritual growth, Good character, Respected status", "ज्ञान, भाग्य, आध्यात्मिक वृद्धि, राम्रो चरित्र, सम्मानित स्थिति"),
    BLESSINGS_MALAVYA("Beauty, Luxury, Artistic ability, Happy marriage, Vehicles", "सौन्दर्य, विलासिता, कलात्मक क्षमता, सुखी विवाह, सवारी साधन"),
    BLESSINGS_RECEIVED("Blessings Received", "प्राप्त आशीर्वादहरू"),
    BLESSINGS_RUCHAKA("Courage, Leadership, Physical strength, Victory over enemies, Land/property", "साहस, नेतृत्व, शारीरिक शक्ति, शत्रुहरूमाथि विजय, जग्गा/सम्पत्ति"),
    BLESSINGS_SASHA("Longevity, Authority, Discipline, Servants, Success through perseverance", "दीर्घायु, अधिकार, अनुशासन, सेवकहरू, दृढताद्वारा सफलता"),
    BODY_ANKLES("Ankles & Calves", "गोलीगाँठाहरू र पिँडौलाहरू"),
    BODY_ARMS("Arms & Shoulders", "हातहरू र काँधहरू"),
    BODY_CHEST("Chest & Heart", "छाती र मुटु"),
    BODY_FEET("Feet", "खुट्टाहरू"),
    BODY_FRAME("Body Frame", "शरीर फ्रेम"),
    BODY_HEAD("Head & Face", "टाउको र अनुहार"),
    BODY_INTESTINES("Intestines", "आन्द्राहरू"),
    BODY_KNEES("Knees", "घुँडाहरू"),
    BODY_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
    BODY_PART_ARMS("Arms/Shoulders", "पाखुरा/काँध"),
    BODY_PART_BELOW_NAVEL("Below Navel", "नाभिमुनि"),
    BODY_PART_CALVES("Calves/Shins", "पिँडौला"),
    BODY_PART_CHEST("Chest", "छाती"),
    BODY_PART_FACE("Face/Mouth", "अनुहार/मुख"),
    BODY_PART_FACE_EYES("Face/Eyes", "अनुहार/आँखा"),
    BODY_PART_FEET("Feet", "खुट्टा"),
    BODY_PART_FEET_ANKLES("Feet/Ankles", "पाइताला/कुर्कुच्चा"),
    BODY_PART_HANDS_STOMACH("Hands/Stomach", "हात/पेट"),
    BODY_PART_HEAD("Head", "टाउको"),
    BODY_PART_HEART_BACK("Heart/Back", "मुटु/ढाड"),
    BODY_PART_KNEES("Knees", "घुँडा"),
    BODY_PART_KNEES_LEGS("Knees/Legs", "घुँडा/खुट्टा"),
    BODY_PART_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
    BODY_PART_NECK_SHOULDERS("Neck/Shoulders", "घाँटी/काँध"),
    BODY_PART_REPRODUCTIVE("Reproductive organs", "प्रजनन अंगहरू"),
    BODY_PART_THIGHS("Thighs", "जाँघ"),
    BODY_PART_UPPER_ABDOMEN("Upper Abdomen", "माथिल्लो पेट"),
    BODY_REPRODUCTIVE("Reproductive System", "प्रजनन प्रणाली"),
    BODY_STOMACH("Stomach & Digestion", "पेट र पाचन"),
    BODY_THIGHS("Thighs", "थाईहरू"),
    BODY_THROAT("Throat & Neck", "घाँटी र घाँटी"),
    BRIDE("Bride", "दुलही"),
    BS_DATE_PICKER_TITLE("Select BS Date", "वि.सं. मिति छान्नुहोस्"),
    BS_DAY("Day", "दिन"),
    BS_MONTH("Month", "महिना"),
    BS_MONTH_ASHADH("Ashadh", "असार"),
    BS_MONTH_ASHWIN("Ashwin", "असोज"),
    BS_MONTH_BAISHAKH("Baishakh", "बैशाख"),
    BS_MONTH_BHADRA("Bhadra", "भदौ"),
    BS_MONTH_CHAITRA("Chaitra", "चैत्र"),
    BS_MONTH_FALGUN("Falgun", "फाल्गुन"),
    BS_MONTH_JESTHA("Jestha", "जेठ"),
    BS_MONTH_KARTIK("Kartik", "कार्तिक"),
    BS_MONTH_MAGH("Magh", "माघ"),
    BS_MONTH_MANGSIR("Mangsir", "मंसिर"),
    BS_MONTH_POUSH("Poush", "पुष"),
    BS_MONTH_SHRAWAN("Shrawan", "साउन"),
    BS_YEAR("Year", "वर्ष"),
    CALCULATING("Calculating Sahams...", "सहमहरू गणना गर्दै..."),
    CALCULATING_CHARA_DASHA("Calculating Chara Dasha periods...", "कारा दशा अवधि गणना गर्दै..."),
    CALCULATION_ERROR("Calculation Error", "गणना त्रुटि"),
    CAREERS_BHADRA("Writing, Teaching, Commerce, Accounting, IT, Journalism, Astrology", "लेखन, अध्यापन, वाणिज्य, लेखा, आईटी, पत्रकारिता, ज्योतिष"),
    CAREERS_HAMSA("Education, Law, Finance, Consulting, Priesthood, Philosophy, Judiciary", "शिक्षा, कानुन, वित्त, परामर्श, पुरोहित्याइँ, दर्शन, न्यायपालिका"),
    CAREERS_MALAVYA("Arts, Entertainment, Fashion, Hospitality, Luxury goods, Interior design, Music", "कला, मनोरञ्जन, फेसन, आतिथ्य, विलासी सामान, आन्तरिक डिजाइन, संगीत"),
    CAREERS_RUCHAKA("Military, Police, Sports, Surgery, Engineering, Real estate, Martial arts", "सेना, प्रहरी, खेलकुद, शल्यक्रिया, इन्जिनियरिङ, घरजग्गा, मार्सल आर्ट"),
    CAREERS_SASHA("Government, Construction, Mining, Management, Agriculture, Real estate, Manufacturing", "सरकार, निर्माण, खानी, व्यवस्थापन, कृषि, घरजग्गा, उत्पादन"),
    CAREER_10TH_LORD_STATUS("Your 10th house lord is %s in the %s house, which %s for career growth.",
        "तपाईंको १०औं भावको स्वामी %s %s भावमा छ, जुन क्यारियर वृद्धिको लागि %s।"),
    CAREER_10TH_STATUS_CHALLENGING("faces some challenges", "केही चुनौतीहरूको सामना गर्छ"),
    CAREER_10TH_STATUS_EXCELLENT("is excellently placed", "उत्कृष्ट रूपमा राखिएको छ"),
    CAREER_10TH_STATUS_GOOD("is well placed", "राम्रो राखिएको छ"),
    CAREER_ADVICE("Career Advice", "क्यारियर सल्लाह"),
    CAREER_AGRICULTURE("Agriculture", "कृषि"),
    CAREER_ARTS("Arts", "कला"),
    CAREER_BEAUTY_INDUSTRY("Beauty industry", "सौन्दर्य उद्योग"),
    CAREER_CHALLENGES("Career Challenges", "क्यारियर चुनौतीहरू"),
    CAREER_CLERGY("Clergy", "धार्मिक गुरु"),
    CAREER_CONSULTING("Consulting", "परामर्श सेवा"),
    CAREER_COOKING("Cooking", "भान्छा"),
    CAREER_COUNSELING("Counseling", "परामर्श"),
    CAREER_EMERGENCY_SERVICES("Emergency services", "आपतकालीन सेवाहरू"),
    CAREER_ENGINEERING("Engineering", "इन्जिनियरिङ"),
    CAREER_ENTERTAINMENT("Entertainment", "मनोरञ्जन"),
    CAREER_ENVIRONMENT("Ideal Work Environment", "आदर्श कार्य वातावरण"),
    CAREER_FASHION("Fashion", "फेसन"),
    CAREER_FOOD_INDUSTRY("Food industry", "खाद्य उद्योग"),
    CAREER_INDICATOR_TITLE("Career Indicators", "क्यारियर सूचकहरू"),
    CAREER_JUPITER_STRONG("Strong Jupiter favors teaching, law, spirituality, finance, advisory roles, or positions of wisdom and guidance.",
        "बलियो बृहस्पतिले शिक्षण, कानून, आध्यात्मिकता, वित्त, सल्लाहकार भूमिकाहरू, वा ज्ञान र मार्गदर्शनको पदहरूलाई अनुकूल बनाउँछ।"),
    CAREER_KETU_INFLUENCE("Ketu influence indicates spiritual pursuits, research, investigation, or work requiring intuition and detachment.",
        "केतुको प्रभावले आध्यात्मिक खोज, अनुसन्धान, अनुसन्धान, वा अन्तर्ज्ञान र विरक्ति आवश्यक पर्ने कार्य संकेत गर्छ।"),
    CAREER_LEGAL_PROFESSION("Legal profession", "कानूनी पेशा"),
    CAREER_MANAGEMENT("Management", "व्यवस्थापन"),
    CAREER_MARS_STRONG("Strong Mars excels in military, police, sports, surgery, engineering, or entrepreneurship requiring courage and action.",
        "बलियो मंगलले सेना, प्रहरी, खेलकुद, शल्यचिकित्सा, इन्जिनियरिङ, वा साहस र कार्य आवश्यक पर्ने उद्यमशीलतामा उत्कृष्ट प्रदर्शन गर्छ।"),
    CAREER_MEDICINE("Medicine", "चिकित्सा"),
    CAREER_MERCURY_STRONG("Strong Mercury indicates success in communication, writing, commerce, accounting, technology, or intellectual pursuits.",
        "बलियो बुधले सञ्चार, लेखन, वाणिज्य, लेखा, प्रविधि, वा बौद्धिक कार्यहरूमा सफलता संकेत गर्छ।"),
    CAREER_MILITARY("Military", "सैन्य"),
    CAREER_MOON_STRONG("Strong Moon favors careers in hospitality, nursing, public relations, marine activities, or creative arts.",
        "बलियो चन्द्रमाले होटल व्यवसाय, नर्सिङ, जनसम्पर्क, समुद्री गतिविधिहरू, वा रचनात्मक कलाहरूमा क्यारियरलाई अनुकूल बनाउँछ।"),
    CAREER_OPPORTUNITIES("Career Opportunities", "क्यारियर अवसरहरू"),
    CAREER_OUTLOOK("Career Outlook", "क्यारियर दृष्टिकोण"),
    CAREER_OVERVIEW_TEMPLATE("Based on your 10th house lord %s in %s, and the position of Sun and Saturn, your career path shows strong potential in %s.",
        "तपाईंको १०औं भावको स्वामी %s %s मा, र सूर्य र शनिको स्थितिको आधारमा, तपाईंको पेशागत मार्गले %s मा बलियो क्षमता देखाउँछ।"),
    CAREER_PUBLISHING("Publishing", "प्रकाशन"),
    CAREER_RAHU_INFLUENCE("Rahu influence suggests unconventional careers, foreign connections, technology, or media-related professions.",
        "राहुको प्रभावले अपरम्परागत क्यारियर, विदेशी सम्बन्धहरू, प्रविधि, वा मिडिया-सम्बन्धित पेशाहरू सुझाव गर्छ।"),
    CAREER_REAL_ESTATE("Real estate", "घरजग्गा"),
    CAREER_RESEARCH("Research", "अनुसन्धान"),
    CAREER_SATURN_STRONG("Strong Saturn indicates success through hard work in construction, agriculture, mining, research, or administrative roles.",
        "बलियो शनिले निर्माण, कृषि, खनन, अनुसन्धान, वा प्रशासनिक भूमिकाहरूमा कडा परिश्रमबाट सफलता संकेत गर्छ।"),
    CAREER_SCORE("Career Strength Score", "क्यारियर शक्ति स्कोर"),
    CAREER_SPORTS("Sports", "खेलकुद"),
    CAREER_STRENGTHS("Career Strengths", "क्यारियर शक्तिहरू"),
    CAREER_SUMMARY("Career Summary", "क्यारियर सारांश"),
    CAREER_SUN_STRONG("Strong Sun indicates success in government, administration, politics, or leadership positions. You naturally command respect.",
        "बलियो सूर्यले सरकार, प्रशासन, राजनीति, वा नेतृत्व पदहरूमा सफलता संकेत गर्छ। तपाईंले स्वाभाविक रूपमा सम्मान आदेश गर्नुहुन्छ।"),
    CAREER_SURGERY("Surgery", "शल्यक्रिया"),
    CAREER_TEACHING("Teaching", "शिक्षण"),
    CAREER_TECHNOLOGY("Technology", "प्रविधि"),
    CAREER_TIMELINE_TITLE("Career Timeline", "क्यारियर समयरेखा"),
    CAREER_TIMING("Career Timing Analysis", "क्यारियर समय विश्लेषण"),
    CAREER_TRANSPORT("Transport", "यातायात"),
    CAREER_VENUS_STRONG("Strong Venus excels in arts, entertainment, luxury goods, beauty industry, hospitality, or diplomatic services.",
        "बलियो शुक्रले कला, मनोरञ्जन, विलासी सामान, सौन्दर्य उद्योग, आतिथ्य, वा कूटनीतिक सेवाहरूमा उत्कृष्ट प्रदर्शन गर्छ।"),
    CAREER_YOGA_TITLE("Career Yogas", "क्यारियर योगहरू"),
    CATEGORY_ADVANCED("Advanced Techniques", "उन्नत प्रविधि"),
    CATEGORY_ADVANCED_DESC("Jaimini, Nadi & specialized systems", "जैमिनी, नाडी र विशेष प्रणाली"),
    CATEGORY_CAREER("Career & Profession", "क्यारियर र पेशा"),
    CATEGORY_CORE_ANALYSIS("Core Analysis", "मुख्य विश्लेषण"),
    CATEGORY_CORE_DESC("Charts, planets, nakshatras & vargas", "कुण्डली, ग्रह, नक्षत्र र वर्गहरू"),
    CATEGORY_FAMILY("Family & Home", "परिवार र घर"),
    CATEGORY_HEALTH("Health & Vitality", "स्वास्थ्य र जीवनशक्ति"),
    CATEGORY_OTHER("Other Areas", "अन्य क्षेत्रहरू"),
    CATEGORY_PREDICTIONS("Predictions & Yogas", "भविष्यवाणी र योग"),
    CATEGORY_PREDICTIONS_DESC("Life predictions & combinations", "जीवन भविष्यवाणी र संयोजन"),
    CATEGORY_RELATIONSHIPS("Love & Relationships", "प्रेम र सम्बन्ध"),
    CATEGORY_REMEDIAL("Remedies & Compatibility", "उपाय र अनुकूलता"),
    CATEGORY_REMEDIAL_DESC("Remedies, matching & muhurta", "उपाय, मिलान र मुहूर्त"),
    CATEGORY_SPIRITUAL("Spiritual & Religious", "आध्यात्मिक र धार्मिक"),
    CATEGORY_STRENGTH_ANALYSIS("Strength Analysis", "बल विश्लेषण"),
    CATEGORY_STRENGTH_DESC("Shadbala & planetary strength", "षड्बल र ग्रह बल"),
    CATEGORY_TIMING_DESC("Dashas & planetary periods", "दशा र ग्रह अवधिहरू"),
    CATEGORY_TIMING_SYSTEMS("Timing Systems", "समय प्रणाली"),
    CATEGORY_WEALTH("Wealth & Finance", "धन र वित्त"),
    CAT_CAREER("Career & Work", "क्यारियर र काम"),
    CAT_CAREER_DESC("Job, business, profession queries", "नोकरी, व्यापार, पेशा प्रश्नहरू"),
    CAT_CHARITY("Charity", "दान"),
    CAT_COLOR("Color Therapy", "रंग चिकित्सा"),
    CAT_DEITY("Deity Worship", "देवी-देवता पूजा"),
    CAT_FASTING("Fasting", "व्रत"),
    CAT_GEMSTONE("Gemstone", "रत्न"),
    CAT_HEALTH("Health & Wellbeing", "स्वास्थ्य र कल्याण"),
    CAT_HEALTH_DESC("Recovery, illness, vitality queries", "निको हुने, रोग, जीवनी शक्ति प्रश्नहरू"),
    CAT_LIFESTYLE("Lifestyle", "जीवनशैली"),
    CAT_LITIGATION("Litigation & Disputes", "मुद्दा र विवाद"),
    CAT_LITIGATION_DESC("Legal matters, conflicts, competitions", "कानूनी मामिला, द्वन्द्व, प्रतिस्पर्धा"),
    CAT_LOST("Lost Objects", "हराएका वस्तुहरू"),
    CAT_LOST_DESC("Finding missing items or valuables", "हराएका सामान वा बहुमूल्य वस्तुहरू खोज्ने"),
    CAT_MANTRA("Mantra", "मन्त्र"),
    CAT_METAL("Metal", "धातु"),
    CAT_RELATIONSHIP("Relationships", "सम्बन्धहरू"),
    CAT_RELATIONSHIP_DESC("Marriage, partnerships, family", "विवाह, साझेदारी, परिवार"),
    CAT_RUDRAKSHA("Rudraksha", "रुद्राक्ष"),
    CAT_SELECT("Select your query type", "आफ्नो प्रश्न प्रकार छान्नुहोस्"),
    CAT_SPIRITUAL("Spiritual Progress", "आध्यात्मिक प्रगति"),
    CAT_SPIRITUAL_DESC("Moksha, sadhana, divine blessings", "मोक्ष, साधना, दैवी आशीर्वाद"),
    CAT_TITLE("Question Category", "प्रश्न श्रेणी"),
    CAT_TRAVEL("Travel & Movement", "यात्रा र गति"),
    CAT_TRAVEL_DESC("Journeys, relocation, migrations", "यात्राहरू, स्थानान्तरण, बसाइँसराइ"),
    CAT_WEALTH("Wealth & Finance", "धन र वित्त"),
    CAT_WEALTH_DESC("Money, investments, material gains", "पैसा, लगानी, भौतिक लाभ"),
    CAT_YANTRA("Yantra", "यन्त्र"),
    CAUTIONARY_INVESTMENTS("Investments to Avoid", "बेवास्ता गर्नुपर्ने लगानीहरू"),
    CAUTIONS("Cautions", "सावधानी"),
    CAUTION_KETU("Don't neglect practical responsibilities for escapism.", "पलायनवादको लागि व्यावहारिक जिम्मेवारीहरूलाई बेवास्ता नगर्नुहोस्।"),
    CAUTION_MARS("Control impulsive reactions and avoid conflicts.", "आवेगपूर्ण प्रतिक्रियाहरू नियन्त्रण गर्नुहोस् र विवादहरूबाट बच्नुहोस्।"),
    CAUTION_RAHU("Be wary of deception and unrealistic expectations.", "छलकपट र अवास्तविक अपेक्षाहरूबाट सावधान रहनुहोस्।"),
    CAUTION_RETROGRADE("%s is retrograde - review and reconsider rather than initiate.", "%s वक्री छ - नयाँ सुरुवात गर्नु भन्दा समीक्षा र पुनर्विचार गर्नुहोस्।"),
    CAUTION_SATURN("Avoid rushing into decisions. Patience is key.", "निर्णयहरूमा हतार नगर्नुहोस्। धैर्य महत्त्वपूर्ण छ।"),
    CHALLENGES("Challenges", "चुनौतिहरू"),
    CHALLENGE_ANXIETY("Anxiety tendencies", "चिन्ता प्रवृत्तिहरू"),
    CHALLENGE_CRITICISM("Over-critical nature", "अति-आलोचनात्मक स्वभाव"),
    CHALLENGE_DETACHMENT("Emotional detachment", "भावनात्मक अलगाव"),
    CHALLENGE_ESCAPISM("Tendency to escapism", "पलायनवादको प्रवृत्ति"),
    CHALLENGE_IMPULSIVENESS("Impulsiveness", "आवेग"),
    CHALLENGE_INDECISION("Indecisiveness", "अनिर्णय"),
    CHALLENGE_INDICATORS("Challenge Indicators", "चुनौती सूचकहरू"),
    CHALLENGE_INTENSITY("Emotional intensity", "भावनात्मक तीव्रता"),
    CHALLENGE_OVERSENSITIVITY("Over-sensitivity", "अति-संवेदनशीलता"),
    CHALLENGE_PRIDE("Excessive pride", "अत्यधिक गर्व"),
    CHALLENGE_REMEDIES("Challenge Remedies", "चुनौती उपचारहरू"),
    CHALLENGE_RESTLESSNESS("Restlessness", "बेचैनी"),
    CHALLENGE_RIGIDITY("Rigidity", "कठोरता"),
    CHALLENGE_STUBBORNNESS("Stubbornness", "हठ"),
    CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    CHALLENGING_DATES("Challenging Dates", "चुनौतीपूर्ण मितिहरू"),
    CHALLENGING_FACTORS("Challenging Factors", "चुनौतीपूर्ण कारकहरू"),
    CHALLENGING_PERIODS("Challenging Marriage Periods", "चुनौतीपूर्ण विवाह अवधिहरू"),
    CHANDRABALA_EXCELLENT("Excellent", "उत्कृष्ट"),
    CHANDRABALA_EXPLANATION("Explanation", "व्याख्या"),
    CHANDRABALA_GOOD("Good", "राम्रो"),
    CHANDRABALA_HOUSE("House", "भाव"),
    CHANDRABALA_HOUSE_FROM_MOON("House from Moon", "चन्द्रबाट भाव"),
    CHANDRABALA_LABEL("Chandrabala", "चन्द्रबल"),
    CHANDRABALA_MOON_STRENGTH("Moon Strength", "चन्द्र शक्ति"),
    CHANDRABALA_NATAL_MOON("Natal Moon Sign", "जन्म चन्द्र राशि"),
    CHANDRABALA_NEUTRAL("Neutral", "तटस्थ"),
    CHANDRABALA_SIGNIFICATIONS("House Significations", "भाव संकेतहरू"),
    CHANDRABALA_TITLE("Chandrabala Analysis", "चन्द्रबल विश्लेषण"),
    CHANDRABALA_TRANSIT_MOON("Transit Moon Sign", "गोचर चन्द्र राशि"),
    CHANDRABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    CHANDRABALA_WEAK("Weak", "कमजोर"),
    CHANDRA_MANGALA("Chandra-Mangala Yoga", "चन्द्र-मंगल योग"),
    CHANDRA_REC_10_1("Career advancement", "क्यारियर प्रगति"),
    CHANDRA_REC_10_2("Professional success", "व्यावसायिक सफलता")
}
