package com.astro.storm.core.common

enum class StringKeyGeneralPart3(override val en: String, override val ne: String) : StringKeyInterface {
    CHANDRA_REC_10_3("Authority recognition", "अधिकारको मान्यता"),
    CHANDRA_REC_10_4("Best for work matters", "कामका मामिलाहरूको लागि उत्तम"),
    CHANDRA_REC_11_1("Maximum gains possible", "अधिकतम लाभ सम्भव छ"),
    CHANDRA_REC_11_2("Friends bring opportunities", "साथीहरूले अवसर ल्याउँछन्"),
    CHANDRA_REC_11_3("Wishes get fulfilled", "इच्छाहरू पूरा हुन्छन्"),
    CHANDRA_REC_11_4("Income increases", "आय बढ्छ"),
    CHANDRA_REC_12_1("Expenses may increase", "खर्च बढ्न सक्छ"),
    CHANDRA_REC_12_2("Rest and recuperation needed", "आराम र स्वास्थ्य लाभ आवश्यक छ"),
    CHANDRA_REC_12_3("Spiritual practices beneficial", "आध्यात्मिक अभ्यासहरू लाभदायक छन्"),
    CHANDRA_REC_12_4("Foreign matters need care", "विदेशी मामिलामा ध्यान दिनुहोस्"),
    CHANDRA_REC_1_1("Personal matters are neutral", "व्यक्तिगत मामिलाहरू तटस्थ छन्"),
    CHANDRA_REC_1_2("Self-reflection day", "आत्म-चिन्तन गर्ने दिन"),
    CHANDRA_REC_1_3("Health awareness needed", "स्वास्थ्य सचेतना आवश्यक छ"),
    CHANDRA_REC_2_1("Good for family matters", "पारिवारिक मामिलाहरूको लागि राम्रो"),
    CHANDRA_REC_2_2("Favorable for financial discussions", "वित्तीय छलफलको लागि अनुकूल"),
    CHANDRA_REC_2_3("Speech brings benefits", "वाणीले लाभ ल्याउँछ"),
    CHANDRA_REC_3_1("Excellent courage and initiative", "उत्कृष्ट साहस र पहल"),
    CHANDRA_REC_3_2("Best for bold actions", "साहसी कार्यहरूको लागि उत्तम"),
    CHANDRA_REC_3_3("Travel is favorable", "यात्रा अनुकूल छ"),
    CHANDRA_REC_3_4("Communications succeed", "सञ्चार सफल हुन्छ"),
    CHANDRA_REC_4_1("Focus on home comforts", "घरको सुख-सुविधामा ध्यान दिनुहोस्"),
    CHANDRA_REC_4_2("Mother may need attention", "आमालाई ध्यान दिनुपर्ने हुन सक्छ"),
    CHANDRA_REC_4_3("Avoid property decisions", "सम्पत्ति सम्बन्धी निर्णयहरूबाट बच्नुहोस्"),
    CHANDRA_REC_5_1("Intelligence enhanced", "बुद्धिमत्ता बढ्छ"),
    CHANDRA_REC_5_2("Good for education", "शिक्षाका लागि राम्रो"),
    CHANDRA_REC_5_3("Children bring joy", "सन्तानले खुशी ल्याउँछन्"),
    CHANDRA_REC_5_4("Romance may blossom", "रोमान्स फस्टाउन सक्छ"),
    CHANDRA_REC_6_1("Victory over enemies", "शत्रुहरूमाथि विजय"),
    CHANDRA_REC_6_2("Competitions favored", "प्रतिस्पर्धाहरू अनुकूल छन्"),
    CHANDRA_REC_6_3("Health improves", "स्वास्थ्यमा सुधार हुन्छ"),
    CHANDRA_REC_6_4("Service brings rewards", "सेवाले पुरस्कार ल्याउँछ"),
    CHANDRA_REC_7_1("Partnerships favorable", "साझेदारीहरू अनुकूल छन्"),
    CHANDRA_REC_7_2("Business dealings good", "व्यापारिक कारोबार राम्रो छ"),
    CHANDRA_REC_7_3("Marriage matters positive", "विवाह सम्बन्धी मामिलाहरू सकारात्मक छन्"),
    CHANDRA_REC_8_1("Avoid risky activities", "जोखिमपूर्ण गतिविधिहरूबाट बच्नुहोस्"),
    CHANDRA_REC_8_2("Hidden matters surface", "लुकेका कुराहरू सतहमा आउँछन्"),
    CHANDRA_REC_8_3("Transformation possible", "रूपान्तरण सम्भव छ"),
    CHANDRA_REC_8_4("Caution advised", "सावधानी अपनाउन सल्लाह दिइन्छ"),
    CHANDRA_REC_9_1("Fortune smiles", "भाग्य मुस्कुराउँछ"),
    CHANDRA_REC_9_2("Long journeys favorable", "लामो यात्राहरू अनुकूल छन्"),
    CHANDRA_REC_9_3("Spiritual growth", "आध्यात्मिक वृद्धि"),
    CHANDRA_REC_9_4("Father may help", "बुबाले मद्दत गर्न सक्नुहुन्छ"),
    CHANT_COUNT("Chant Count", "जप गणना"),
    CHARITABLE_REMEDIES("Charitable Remedies", "दान उपचारहरू"),
    CHART_ASCENDANT("Ascendant", "लग्न"),
    CHART_ASCENDANT_LABEL("Ascendant", "लग्न"),
    CHART_ASCENDANT_LAGNA("Ascendant (Lagna)", "लग्न"),
    CHART_ASC_ABBR("Asc", "ल"),
    CHART_ASTRONOMICAL_DATA("Astronomical Data", "खगोलीय तथ्याङ्क"),
    CHART_AYANAMSA("Ayanamsa", "अयनांश"),
    CHART_BIRTH_DETAILS("Birth Details", "जन्म विवरण"),
    CHART_CONFLICTS("Chart Shows Conflict", "कुण्डलीले विरोध देखाउँछ"),
    CHART_DATE("Date", "मिति"),
    CHART_HOUSE("House", "भाव"),
    CHART_HOUSE_CUSPS("House Cusps", "भाव सन्धि"),
    CHART_HOUSE_SYSTEM("House System", "भाव पद्धति"),
    CHART_INTEGRATION("Chart Integration", "कुण्डली एकीकरण"),
    CHART_JULIAN_DAY("Julian Day", "जुलियन दिन"),
    CHART_LAGNA("Lagna", "लग्न"),
    CHART_LAGNA_EFFECT("Prashna Lagna Effect", "प्रश्न लग्न प्रभाव"),
    CHART_LEGEND_COMBUST("Combust", "अस्त"),
    CHART_LEGEND_COMBUST_SHORT("Comb", "अस्त"),
    CHART_LEGEND_DEBILITATED("Debilitated", "नीच"),
    CHART_LEGEND_DEB_SHORT("Deb", "नीच"),
    CHART_LEGEND_EXALTED("Exalted", "उच्च"),
    CHART_LEGEND_EXALT_SHORT("Exalt", "उच्च"),
    CHART_LEGEND_MOOL_TRI("Mool Tri.", "मूलत्रि."),
    CHART_LEGEND_OWN_SHORT("Own", "स्व"),
    CHART_LEGEND_OWN_SIGN("Own Sign", "स्वराशि"),
    CHART_LEGEND_RETRO("Retro", "वक्री"),
    CHART_LEGEND_RETRO_SHORT("Retro", "वक्री"),
    CHART_LEGEND_VARGOTTAMA("Vargottama", "वर्गोत्तम"),
    CHART_LEGEND_VARGO_SHORT("Vargo", "वर्गो"),
    CHART_LOCATION("Location", "स्थान"),
    CHART_MIDHEAVEN("Midheaven", "मध्याकाश"),
    CHART_MOON("Moon", "चन्द्रमा"),
    CHART_MOON_EFFECT("Moon's Position Effect", "चन्द्रमाको स्थिति प्रभाव"),
    CHART_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
    CHART_NAKSHATRA("Nakshatra", "नक्षत्र"),
    CHART_NAKSHATRA_LABEL("Nakshatra", "नक्षत्र"),
    CHART_NAVAMSA("Navamsa Chart (D9)", "नवांश कुण्डली (D9)"),
    CHART_NEUTRAL_EFFECT("Chart Neutral", "कुण्डली तटस्थ"),
    CHART_PLANETARY_POSITIONS("Planetary Positions", "ग्रह स्थितिहरू"),
    CHART_RASHI("Rashi Chart (D1)", "राशि कुण्डली (D1)"),
    CHART_STRENGTH("Chart Strength", "कुण्डली बल"),
    CHART_SUN("Sun", "सूर्य"),
    CHART_SUPPORTS("Chart Supports Reading", "कुण्डलीले पठनलाई समर्थन गर्छ"),
    CHART_TAP_FOR_DETAILS("Tap for details", "विवरणको लागि ट्याप गर्नुहोस्"),
    CHART_TAP_FULLSCREEN("Tap chart to view fullscreen", "पूर्ण स्क्रिनमा हेर्न चार्ट ट्याप गर्नुहोस्"),
    CHART_TAP_HOUSE_FOR_DETAILS("Tap house for details", "विवरणको लागि भाव ट्याप गर्नुहोस्"),
    CHART_TAP_TO_EXPAND("Tap to expand", "विस्तार गर्न ट्याप गर्नुहोस्"),
    CHART_TIME("Time", "समय"),
    CHART_VALIDATION("Prashna Chart Validation", "प्रश्न कुण्डली प्रमाणीकरण"),
    CHAR_AQUARIUS_ASC("You are innovative, humanitarian, and independent-minded. Your original thinking and progressive ideas benefit society at large.",
        "तपाईं नवीन, मानवतावादी र स्वतन्त्र सोचाइ भएको हुनुहुन्छ। तपाईंको मौलिक सोच र प्रगतिशील विचारहरूले समाजलाई फाइदा पुर्‍याउँछ।"),
    CHAR_ARIES_ASC("You are a natural leader with pioneering spirit, courage, and dynamic energy. Your assertive nature drives you to take initiative in all matters.",
        "तपाईं प्राकृतिक नेता हुनुहुन्छ अग्रगामी भावना, साहस र गतिशील ऊर्जाको साथ। तपाईंको दृढ स्वभावले तपाईंलाई सबै कुरामा पहल गर्न प्रेरित गर्छ।"),
    CHAR_CANCER_ASC("You are emotionally intuitive, nurturing, and protective. Your strong connection to family and home brings you deep fulfillment.",
        "तपाईं भावनात्मक रूपमा अन्तर्ज्ञानी, पालनपोषण गर्ने र सुरक्षात्मक हुनुहुन्छ। परिवार र घरसँगको तपाईंको बलियो सम्बन्धले तपाईंलाई गहिरो सन्तुष्टि दिन्छ।"),
    CHAR_CAPRICORN_ASC("You are ambitious, disciplined, and practical. Your patient approach and strong work ethic lead to lasting achievements.",
        "तपाईं महत्वाकांक्षी, अनुशासित र व्यावहारिक हुनुहुन्छ। तपाईंको धैर्यपूर्ण दृष्टिकोण र बलियो कार्य नैतिकताले स्थायी उपलब्धिहरूमा पुर्‍याउँछ।"),
    CHAR_GEMINI_ASC("You are intellectually curious, adaptable, and communicative. Your versatile mind excels in learning and social interactions.",
        "तपाईं बौद्धिक रूपमा जिज्ञासु, अनुकूलनशील र संवादशील हुनुहुन्छ। तपाईंको बहुमुखी मनले सिक्ने र सामाजिक अन्तरक्रियामा उत्कृष्ट प्रदर्शन गर्छ।"),
    CHAR_LEO_ASC("You possess natural charisma, creativity, and leadership qualities. Your generous heart and confident demeanor inspire those around you.",
        "तपाईंसँग प्राकृतिक करिश्मा, रचनात्मकता र नेतृत्व गुणहरू छन्। तपाईंको उदार हृदय र आत्मविश्वासपूर्ण व्यवहारले वरिपरिका मानिसहरूलाई प्रेरित गर्छ।"),
    CHAR_LIBRA_ASC("You value harmony, balance, and beauty in all aspects of life. Your diplomatic nature and sense of justice make you an excellent mediator.",
        "तपाईं जीवनका सबै पक्षहरूमा सामंजस्य, सन्तुलन र सौन्दर्यलाई मूल्यवान मान्नुहुन्छ। तपाईंको कूटनीतिक स्वभाव र न्यायको भावनाले तपाईंलाई उत्कृष्ट मध्यस्थकर्ता बनाउँछ।"),
    CHAR_PISCES_ASC("You are compassionate, intuitive, and spiritually inclined. Your artistic sensibility and empathetic nature connect you deeply with others.",
        "तपाईं करुणामय, अन्तर्ज्ञानी र आध्यात्मिक प्रवृत्तिका हुनुहुन्छ। तपाईंको कलात्मक संवेदनशीलता र सहानुभूतिपूर्ण स्वभावले तपाईंलाई अरूसँग गहिरो रूपमा जोड्छ।"),
    CHAR_SAGITTARIUS_ASC("You are philosophical, adventurous, and optimistic. Your love for knowledge and exploration expands your horizons continually.",
        "तपाईं दार्शनिक, साहसिक र आशावादी हुनुहुन्छ। ज्ञान र अन्वेषणको तपाईंको प्रेमले तपाईंको क्षितिजलाई निरन्तर विस्तार गर्छ।"),
    CHAR_SCORPIO_ASC("You possess intense emotional depth, transformative power, and strong intuition. Your determination and resilience help you overcome any obstacle.",
        "तपाईंसँग तीव्र भावनात्मक गहिराइ, परिवर्तनकारी शक्ति र बलियो अन्तर्ज्ञान छ। तपाईंको दृढता र लचिलोपनले तपाईंलाई कुनै पनि बाधा पार गर्न मद्दत गर्छ।"),
    CHAR_TAURUS_ASC("You possess a stable, practical nature with strong aesthetic sensibilities. Your patience and determination bring steady progress in life.",
        "तपाईंसँग स्थिर, व्यावहारिक स्वभाव छ बलियो सौन्दर्य बोधको साथ। तपाईंको धैर्य र दृढताले जीवनमा स्थिर प्रगति ल्याउँछ।"),
    CHAR_VIRGO_ASC("You are analytical, detail-oriented, and service-minded. Your practical approach and perfectionist tendencies ensure quality in all endeavors.",
        "तपाईं विश्लेषणात्मक, विस्तार-उन्मुख र सेवा-भावित हुनुहुन्छ। तपाईंको व्यावहारिक दृष्टिकोण र पूर्णतावादी प्रवृत्तिले सबै प्रयासहरूमा गुणस्तर सुनिश्चित गर्छ।"),
    CHAT_ARCHIVE("Archive", "संग्रह"),
    CHAT_BACK("Back", "पछाडि"),
    CHAT_CANCEL_BTN("Cancel", "रद्द गर्नुहोस्"),
    CHAT_CHANGE_MODEL("Change model", "मोडेल परिवर्तन गर्नुहोस्"),
    CHAT_CLEAR("Clear Chat", "च्याट खाली गर्नुहोस्"),
    CHAT_CLEAR_BTN("Clear", "खाली गर्नुहोस्"),
    CHAT_CLEAR_CONFIRM("Are you sure you want to clear all messages in this conversation?", "के तपाईं यस कुराकानीका सबै सन्देशहरू हटाउन निश्चित हुनुहुन्छ?"),
    CHAT_DAYS_AGO("%dd ago", "%d दिन पहिले"),
    CHAT_DELETE("Delete Chat", "च्याट मेटाउनुहोस्"),
    CHAT_DELETE_BTN("Delete", "मेटाउनुहोस्"),
    CHAT_DELETE_CONFIRM("Are you sure you want to delete \"%s\"? This cannot be undone.", "के तपाईं \"%s\" मेटाउन निश्चित हुनुहुन्छ? यो पूर्ववत गर्न सकिँदैन।"),
    CHAT_HOURS_AGO("%dh ago", "%d घण्टा पहिले"),
    CHAT_JUST_NOW("Just now", "अहिले भर्खरै"),
    CHAT_MESSAGES_COUNT("%d messages", "%d सन्देशहरू"),
    CHAT_MINUTES_AGO("%dm ago", "%dमि. पहिले"),
    CHAT_MODEL_OPTIONS("Model options", "मोडेल विकल्पहरू"),
    CHAT_MORE_OPTIONS("More options", "थप विकल्पहरू"),
    CHAT_NEW("New Chat", "नयाँ च्याट"),
    CHAT_SEND("Send", "पठाउनुहोस्"),
    CHAT_STOP("Stop", "रोक्नुहोस्"),
    CHAT_SUGGESTION_CHART("Analyze my birth chart", "मेरो जन्म कुण्डली विश्लेषण गर्नुहोस्"),
    CHAT_SUGGESTION_DASHA("What's my current dasha period?", "मेरो हालको दशा अवधि के हो?"),
    CHAT_SUGGESTION_YOGAS("What yogas are present in my chart?", "मेरो कुण्डलीमा कुन योगहरू छन्?"),
    CHOGHADIYA_AMRIT("Amrit", "अमृत"),
    CHOGHADIYA_CHAR("Char", "चर"),
    CHOGHADIYA_KAAL("Kaal", "काल"),
    CHOGHADIYA_LABH("Labh", "लाभ"),
    CHOGHADIYA_NATURE_AUSPICIOUS("Auspicious", "शुभ"),
    CHOGHADIYA_NATURE_INAUSPICIOUS("Inauspicious", "अशुभ"),
    CHOGHADIYA_NATURE_MIXED("Mixed", "मिश्रित"),
    CHOGHADIYA_ROG("Rog", "रोग"),
    CHOGHADIYA_SHUBH("Shubh", "शुभ"),
    CHOGHADIYA_UDVEG("Udveg", "उद्वेग"),
    CHRONIC_PATTERNS("Chronic Health Patterns", "दीर्घकालीन स्वास्थ्य ढाँचाहरू"),
    COMBINED_CAREER_BHADRA_HAMSA("Excellent for teaching, writing, law, philosophy", "शिक्षण, लेखन, कानुन, दर्शनको लागि उत्कृष्ट"),
    COMBINED_CAREER_HAMSA_MALAVYA("Excellent for careers in education, arts, counseling", "शिक्षा, कला, परामर्शमा करियरको लागि उत्कृष्ट"),
    COMBINED_CAREER_RUCHAKA_SASHA("Excellent for leadership, military, engineering management", "नेतृत्व, सेना, इन्जिनियरिङ व्यवस्थापनको लागि उत्कृष्ट"),
    COMBINED_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    COMBINED_FAVORABLE("Favorable", "अनुकूल"),
    COMBINED_HIGHLY_FAVORABLE("Highly Favorable", "अत्यन्त अनुकूल"),
    COMBINED_INTERPRET("Having {0} Mahapurusha Yogas is {1}. The combined influence of {2} creates a multifaceted personality with diverse talents and blessings.", "{0} महापुरुष योग हुनु {1} हो। {2} को संयुक्त प्रभावले विविध प्रतिभा र आशीर्वादसहितको बहुआयामिक व्यक्तित्व सिर्जना गर्दछ।"),
    COMBINED_MIXED("Mixed Results", "मिश्रित परिणाम"),
    COMBINED_RARE_COUNT("Rare combination of {0} Mahapurusha Yogas indicates a highly blessed chart", "{0} महापुरुष योगहरूको दुर्लभ संयोजनले एक उच्च आशीर्वादित कुण्डली संकेत गर्दछ"),
    COMBINED_SYNERGY_BHADRA_HAMSA("Bhadra-Hamsa combination: Intelligence with wisdom, communication with knowledge", "भद्रा-हंस संयोजन: ज्ञानको साथ बुद्धि, ज्ञानको साथ सञ्चार"),
    COMBINED_SYNERGY_HAMSA_MALAVYA("Hamsa-Malavya combination: Wisdom with beauty, spiritual with material balance", "हंस-मालव्य संयोजन: सौन्दर्यको साथ ज्ञान, भौतिक र आध्यात्मिक सन्तुलन"),
    COMBINED_SYNERGY_RUCHAKA_SASHA("Ruchaka-Sasha combination: Courage with discipline, action with patience", "रुचक-शश संयोजन: अनुशासनको साथ साहस, धैर्यको साथ कार्य"),
    COMBINED_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    COMBUSTION_APPROACHING("Approaching Combustion", "अस्त नजिक"),
    COMBUSTION_CAZIMI("Cazimi", "काजिमी"),
    COMBUSTION_COMBUST("Combust", "अस्त"),
    COMBUSTION_DEEP_COMBUST("Deep Combustion", "गहिरो अस्त"),
    COMBUSTION_NOT_COMBUST("Not Combust", "अस्त छैन"),
    COMBUSTION_SEPARATING("Separating", "विभाजन"),
    COMBUST_APPROACHING("Approaching Combustion", "अस्त हुँदै"),
    COMBUST_CAZIMI("Cazimi", "कज़िमी"),
    COMBUST_COMBUST("Combust", "अस्त"),
    COMBUST_DEEP("Deep Combustion", "गहिरो अस्त"),
    COMBUST_NOT("Not Combust", "अस्त छैन"),
    COMBUST_SEPARATING("Separating", "अलग हुँदै"),
    COMMON_CLOSE("Close", "बन्द गर्नुहोस्"),
    COMMON_CURRENT("Current", "वर्तमान"),
    COMMON_DAYS("days", "दिन"),
    COMMON_DETAILS("Details", "विवरण"),
    COMMON_DURATION("Duration", "अवधि"),
    COMMON_ERROR("Error", "त्रुटि"),
    COMMON_EXCELLENT("Excellent", "उत्कृष्ट"),
    COMMON_FAIR("Fair", "ठीक"),
    COMMON_FROM("From", "देखि"),
    COMMON_GOOD("Good", "राम्रो"),
    COMMON_GOT_IT("Got It", "बुझें"),
    COMMON_HOURS("hours", "घण्टा"),
    COMMON_INTERPRETATION("Interpretation", "व्याख्या"),
    COMMON_LOADING("Loading...", "लोड हुँदैछ..."),
    COMMON_MINUTES("minutes", "मिनेट"),
    COMMON_MONTHS("months", "महिना"),
    COMMON_PAST("Past", "बितेको"),
    COMMON_POOR("Poor", "कमजोर"),
    COMMON_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    COMMON_REQUIRED_MIN("Required Minimum", "आवश्यक न्यूनतम"),
    COMMON_RETRY("Retry", "पुनः प्रयास"),
    COMMON_RUPAS("Rupas", "रूपा"),
    COMMON_SHASHTIAMSAS("Shashtiamsas", "षष्ट्यंश"),
    COMMON_STRENGTH("Strength", "बल"),
    COMMON_SUMMARY("Summary", "सारांश"),
    COMMON_TO("To", "सम्म"),
    COMMON_UPCOMING("Upcoming", "आउँदा"),
    COMMON_VIEW_DETAILS("View Details", "विवरण हेर्नुहोस्"),
    COMMON_VIRUPAS("Virupas", "विरूपा"),
    COMMON_YEARS("years", "वर्ष"),
    COMMUNICATION_REL("Communication in Relationship", "सम्बन्धमा सञ्चार"),
    COMMUNICATION_SKILL("Communication Skill", "सञ्चार कौशल"),
    COMMUNICATION_STYLE("Communication Style", "सञ्चार शैली"),
    COMPATIBLE("Compatible", "अनुकूल"),
    CONCENTRATION("Concentration Ability", "एकाग्रता क्षमता"),
    CONFLICT_RESOLUTION("Conflict Resolution", "द्वन्द्व समाधान"),
    CONJUNCT("Conjunct", "युति"),
    CONSTITUTION_DESC("Constitution Description", "संविधान विवरण"),
    CONSTITUTION_TITLE("Ayurvedic Constitution", "आयुर्वेदिक संविधान"),
    COSMIC_BOND("Cosmic Bond", "ब्रह्माण्डीय बन्धन"),
    COURAGE_DEVELOPING("Developing Courage", "विकासशील साहस"),
    COURAGE_EXCEPTIONAL("Exceptional Courage", "असाधारण साहस"),
    COURAGE_HIGH("High Courage", "उच्च साहस"),
    COURAGE_INITIATIVE("Initiative", "पहल"),
    COURAGE_LEVEL("Level", "स्तर"),
    COURAGE_MENTAL("Mental Courage", "मानसिक साहस"),
    COURAGE_MODERATE("Moderate Courage", "मध्यम साहस"),
    COURAGE_NEEDS_WORK("Needs Work", "काम आवश्यक"),
    COURAGE_PHYSICAL("Physical Courage", "शारीरिक साहस"),
    COWRIE_CAST("Cast Shells", "कौडी फाल्नुहोस्"),
    COWRIE_CLOSED("Closed (Face Down)", "बन्द (मुख तल)"),
    COWRIE_INSTRUCTION("Focus on your question and cast the shells", "आफ्नो प्रश्नमा ध्यान केन्द्रित गर्नुहोस् र कौडी फाल्नुहोस्"),
    COWRIE_OPEN("Open (Face Up)", "खुला (मुख माथि)"),
    COWRIE_RATIO("Open:Closed Ratio", "खुला:बन्द अनुपात"),
    COWRIE_RECAST("Recast", "फेरि फाल्नुहोस्"),
    COWRIE_RESULT("Shell Count", "कौडी गणना"),
    COWRIE_TITLE("Cowrie Shell Throw", "कौडी फाल्ने"),
    COWRIE_TOTAL("Total Shells: 8", "जम्मा कौडी: ८"),
    CREATIVE_INTELLIGENCE("Creative Intelligence", "रचनात्मक बुद्धिमत्ता"),
    CRITICAL_ADVICE("Period Advice", "अवधि सल्लाह"),
    CRITICAL_AREA("Area Affected", "प्रभावित क्षेत्र"),
    CRITICAL_DURATION("Duration", "अवधि"),
    CRITICAL_NAME("Period Name", "अवधि नाम"),
    CRITICAL_NATURE("Period Nature", "अवधि प्रकृति"),
    CRITICAL_PERIODS("Critical Health Periods", "महत्वपूर्ण स्वास्थ्य अवधिहरू"),
    CRITICAL_TITLE("Critical Periods", "महत्वपूर्ण अवधिहरू"),
    CURRENT_CAREER_PHASE("Current Career Phase", "वर्तमान क्यारियर चरण"),
    CURRENT_EDU_PHASE("Current Education Phase", "वर्तमान शिक्षा चरण"),
    CURRENT_HEALTH_PHASE("Current Health Phase", "वर्तमान स्वास्थ्य चरण"),
    CURRENT_LABEL("Current", "वर्तमान"),
    CURRENT_MAHA_DASHA("Current Maha Dasha", "हालको महा दशा"),
    CURRENT_PLANETARY_POSITIONS("Current Planetary Positions", "वर्तमान ग्रह स्थितिहरू"),
    CURRENT_REL_PHASE("Current Relationship Phase", "वर्तमान सम्बन्ध चरण"),
    CURRENT_SPIRITUAL_PHASE("Current Spiritual Phase", "वर्तमान आध्यात्मिक चरण"),
    CURRENT_WEALTH_PHASE("Current Wealth Phase", "वर्तमान धन चरण"),
    D10_10TH_SIGN("D10 10th Sign", "D10 दशम राशि"),
    D10_ASCENDANT("D10 Ascendant", "D10 लग्न"),
    D10_CAREER_REFINEMENT("Career Refinement from D10", "D10 बाट क्यारियर परिष्करण"),
    D10_GROWTH_PATTERN("Professional Growth Pattern", "व्यावसायिक विकास ढाँचा"),
    D10_MOON_POSITION("D10 Moon Position", "D10 चन्द्रमा स्थिति"),
    D10_SUN_POSITION("D10 Sun Position", "D10 सूर्य स्थिति"),
    D9_7TH_LORD("D9 7th Lord Position", "D9 सप्तम स्वामी स्थिति"),
    D9_ASCENDANT("D9 Ascendant", "D9 लग्न"),
    D9_MARRIAGE_QUALITY("Marriage Quality from D9", "D9 बाट विवाह गुणस्तर"),
    D9_SPOUSE_NATURE("Spouse Nature from D9", "D9 बाट जीवनसाथी स्वभाव"),
    D9_VENUS("D9 Venus Position", "D9 शुक्र स्थिति"),
    DAILY_YOGA_ATIGANDA("Atiganda", "अतिगण्ड"),
    DAILY_YOGA_AYUSHMAN("Ayushman", "आयुष्मान"),
    DAILY_YOGA_BRAHMA("Brahma", "ब्रह्म"),
    DAILY_YOGA_DHRITI("Dhriti", "धृति"),
    DAILY_YOGA_DHRUVA("Dhruva", "ध्रुव"),
    DAILY_YOGA_GANDA("Ganda", "गण्ड"),
    DAILY_YOGA_HARSHANA("Harshana", "हर्षण"),
    DAILY_YOGA_INDRA("Indra", "इन्द्र"),
    DAILY_YOGA_PARIGHA("Parigha", "परिघ"),
    DAILY_YOGA_PRITI("Priti", "प्रीति"),
    DAILY_YOGA_SADHYA("Sadhya", "साध्य"),
    DAILY_YOGA_SAUBHAGYA("Saubhagya", "सौभाग्य"),
    DAILY_YOGA_SHIVA("Shiva", "शिव"),
    DAILY_YOGA_SHOBHANA("Shobhana", "शोभन"),
    DAILY_YOGA_SHOOLA("Shoola", "शूल"),
    DAILY_YOGA_SHUBHA("Shubha", "शुभ"),
    DAILY_YOGA_SHUKLA("Shukla", "शुक्ल"),
    DAILY_YOGA_SIDDHA("Siddha", "सिद्ध"),
    DAILY_YOGA_SIDDHI("Siddhi", "सिद्धि"),
    DAILY_YOGA_SUKARMA("Sukarma", "सुकर्म"),
    DAILY_YOGA_VAIDHRITI("Vaidhriti", "वैधृति"),
    DAILY_YOGA_VAJRA("Vajra", "वज्र"),
    DAILY_YOGA_VARIYANA("Variyana", "वरीयान"),
    DAILY_YOGA_VISHKUMBHA("Vishkumbha", "विष्कम्भ"),
    DAILY_YOGA_VRIDDHI("Vriddhi", "वृद्धि"),
    DAILY_YOGA_VYAGHATA("Vyaghata", "व्याघात"),
    DAILY_YOGA_VYATIPATA("Vyatipata", "व्यतीपात"),
    DASHAVARGA_BALA("Dashavarga Bala (10-Varga)", "दशवर्ग बल (१०-वर्ग)"),
    DAYS("days", "दिन"),
    DAYS_SHORT("d", "दि"),
    DAY_ANY("Any day", "कुनै पनि दिन"),
    DAY_BIRTH("Day Birth", "दिवा जन्म"),
    DAY_BIRTH_CHART("Day Birth Chart", "दिवा जन्म कुण्डली"),
    DAY_FRIDAY("Friday", "शुक्रबार"),
    DAY_JUPITER("Jupiter's day - auspicious for growth", "बृहस्पतिको दिन - वृद्धिको लागि शुभ"),
    DAY_MONDAY("Monday", "सोमबार"),
    DAY_SATURDAY("Saturday", "शनिबार"),
    DAY_SUNDAY("Sunday", "आइतबार"),
    DAY_THURSDAY("Thursday", "बिहीबार"),
    DAY_TUESDAY("Tuesday", "मङ्गलबार"),
    DAY_VENUS("Venus's day - favorable for relationships", "शुक्रको दिन - सम्बन्धका लागि अनुकूल"),
    DAY_WEDNESDAY("Wednesday", "बुधबार"),
    DEBILITATED(" Debilitated - results weakened.", " नीच - परिणाम कमजोर।"),
    DEBT_KANYA_DESC("Debt towards unmarried girls/daughters", "अविवाहित केटी/छोरीहरूप्रतिको ऋण"),
    DEBT_KANYA_EFF_1("Daughter's welfare concerns", "छोरीको कल्याणमा चिन्ता"),
    DEBT_KANYA_EFF_2("Education obstacles", "शिक्षामा अवरोध"),
    DEBT_KANYA_EFF_3("Business communication issues", "व्यापारिक सञ्चारमा समस्या"),
    DEBT_KANYA_REM_1("Donate green items to unmarried girls", "अविवाहित केटीहरूलाई हरियो वस्तुहरू दान गर्नुहोस्"),
    DEBT_KANYA_REM_2("Support girls' education", "केटीहरूको शिक्षामा सहयोग गर्नुहोस्"),
    DEBT_KANYA_REM_3("Bury green glass bottle filled with honey", "महले भरिएको हरियो काँचको बोतल गाड्नुहोस्"),
    DEBT_KANYA_REM_4("Feed green vegetables to goats on Wednesdays", "बुधबार बाख्रालाई हरियो तरकारी खुवाउनुहोस्"),
    DEBT_MATRU_DESC("Debt towards mother and maternal lineage", "आमा र मातृवंशप्रतिको ऋण"),
    DEBT_MATRU_EFF_1("Mental peace disturbed", "मानसिक शान्ति बिग्रिएको"),
    DEBT_MATRU_EFF_2("Mother's health concerns", "आमाको स्वास्थ्यमा चिन्ता"),
    DEBT_MATRU_EFF_3("Property and comfort issues", "सम्पत्ति र सुविधामा समस्या"),
    DEBT_MATRU_REM_1("Serve milk or rice to mother daily", "दैनिक आमालाई दूध वा चामल खुवाउनुहोस्"),
    DEBT_MATRU_REM_2("Donate white items on Mondays", "सोमबार सेतो वस्तुहरू दान गर्नुहोस्"),
    DEBT_MATRU_REM_3("Keep silver coin given by mother", "आमाले दिएको चाँदीको सिक्का राख्नुहोस्"),
    DEBT_MATRU_REM_4("Respect and serve elderly women", "वृद्ध महिलाहरूको सम्मान र सेवा गर्नुहोस्"),
    DEBT_PITRU_DESC("Debt towards father and ancestors", "पिता र पूर्वजहरूप्रतिको ऋण"),
    DEBT_PITRU_EFF_1("Obstacles in career and authority", "करियर र अधिकारमा अवरोध"),
    DEBT_PITRU_EFF_2("Father's health or relationship issues", "बुबाको स्वास्थ्य वा सम्बन्धमा समस्या"),
    DEBT_PITRU_EFF_3("Children face delays or challenges", "सन्तानले ढिलाइ वा चुनौतीको सामना गर्ने"),
    DEBT_PITRU_REM_1("Offer water to Sun at sunrise daily", "दैनिक सूर्योदयमा सूर्यलाई जल अर्पण गर्नुहोस्"),
    DEBT_PITRU_REM_2("Feed crows with sweet bread on Saturdays", "शनिबार कागलाई गुलियो रोटी खुवाउनुहोस्"),
    DEBT_PITRU_REM_3("Perform Shraddha rituals for ancestors", "पूर्वजहरूको लागि श्राद्ध अनुष्ठान गर्नुहोस्"),
    DEBT_PITRU_REM_4("Help elderly people, especially fathers", "वृद्धहरूलाई, विशेष गरी बुबाहरूलाई मद्दत गर्नुहोस्"),
    DEBT_STRI_DESC("Debt towards wife and women", "पत्नी र महिलाहरूप्रतिको ऋण"),
    DEBT_STRI_EFF_1("Marriage delays or conflicts", "विवाहमा ढिलाइ वा द्वन्द्व"),
    DEBT_STRI_EFF_2("Relationship troubles", "सम्बन्धमा समस्याहरू"),
    DEBT_STRI_EFF_3("Financial instability", "आर्थिक अस्थिरता"),
    DEBT_STRI_REM_1("Donate white clothes to women on Fridays", "शुक्रबार महिलाहरूलाई सेतो कपडा दान गर्नुहोस्"),
    DEBT_STRI_REM_2("Respect wife and all women", "पत्नी र सबै महिलाहरूको सम्मान गर्नुहोस्"),
    DEBT_STRI_REM_3("Offer rice and camphor at Goddess temple", "देवीको मन्दिरमा चामल र कपूर चढाउनुहोस्"),
    DEBT_STRI_REM_4("Avoid exploiting women in any way", "कुनै पनि किसिमले महिलाहरूको शोषण नगर्नुहोस्"),
    DEBUG_COPY_LOG("Copy", "कपी गर्नुहोस्"),
    DEBUG_CRASH_LOG("Crash Log", "क्र्यास लग"),
    DEBUG_ERROR_OCCURRED("An unexpected error occurred.", "एउटा अप्रत्याशित त्रुटि भयो।"),
    DEBUG_RESTART_APP("Restart", "पुनः सुरु गर्नुहोस्"),
    DEBUG_UNHANDLED_EXCEPTION("Unhandled Exception", "अप्रत्याशित त्रुटि"),
    DEGREE_FORMAT("%s° %s'", "%s° %s'"),
    DEGREE_LABEL("Degree", "अंश"),
    DEGREE_SUCCESS("Degree Completion Success", "डिग्री पूर्णता सफलता"),
    DESC_BHADRA("Bhadra Yoga is formed when Mercury is in Kendra in its own sign (Gemini/Virgo) or exaltation (Virgo). It bestows exceptional intelligence, communication skills, business acumen, and scholarly abilities.", "भद्रा योग तब बन्छ जब बुध केन्द्र भावमा आफ्नो राशि (मिथुन/कन्या) वा उच्च राशि (कन्या) मा हुन्छ। यसले असाधारण बुद्धि, सञ्चार कौशल, व्यापारिक चातुर्य र विद्वता प्रदान गर्दछ।"),
    DESC_HAMSA("Hamsa Yoga is formed when Jupiter is in Kendra in its own sign (Sagittarius/Pisces) or exaltation (Cancer). It bestows wisdom, righteousness, fortune, and spiritual inclination.", "हंस योग तब बन्छ जब बृहस्पति केन्द्र भावमा आफ्नो राशि (धनु/मीन) वा उच्च राशि (कर्कट) मा हुन्छ। यसले ज्ञान, धार्मिकता, भाग्य र आध्यात्मिक झुकाव प्रदान गर्दछ।"),
    DESC_MALAVYA("Malavya Yoga is formed when Venus is in Kendra in its own sign (Taurus/Libra) or exaltation (Pisces). It bestows beauty, luxury, artistic talents, and harmonious relationships.", "मालव्य योग तब बन्छ जब शुक्र केन्द्र भावमा आफ्नो राशि (वृष/तुला) वा उच्च राशि (मीन) मा हुन्छ। यसले सौन्दर्य, विलासिता, कलात्मक प्रतिभा र सामञ्जस्यपूर्ण सम्बन्ध प्रदान गर्दछ।"),
    DESC_RUCHAKA("Ruchaka Yoga is formed when Mars is in Kendra in its own sign (Aries/Scorpio) or exaltation (Capricorn). It bestows courage, leadership abilities, physical strength, and success in competitive fields.", "रुचक योग तब बन्छ जब मंगल केन्द्र भावमा आफ्नो राशि (मेष/वृश्चिक) वा उच्च राशि (मकर) मा हुन्छ। यसले साहस, नेतृत्व क्षमता, शारीरिक शक्ति र प्रतिस्पर्धात्मक क्षेत्रहरूमा सफलता प्रदान गर्दछ।"),
    DESC_SASHA("Sasha Yoga is formed when Saturn is in Kendra in its own sign (Capricorn/Aquarius) or exaltation (Libra). It bestows discipline, longevity, authority, and success through persistent effort.", "शश योग तब बन्छ जब शनि केन्द्र भावमा आफ्नो राशि (मकर/कुम्भ) वा उच्च राशि (तुला) मा हुन्छ। यसले अनुशासन, दीर्घायु, अधिकार र निरन्तर प्रयासद्वारा सफलता प्रदान गर्दछ।"),
    DETACHMENT_AREAS("Detachment Areas", "विरक्ति क्षेत्रहरू"),
    DETAILED_TITLE("DETAILED MATCHMAKING ANALYSIS", "विस्तृत मिलान विश्लेषण"),
    DETAILS("Details", "विवरण"),
    DHANA_YOGA_EFFECT("Wealth Effect", "धन प्रभाव"),
    DHANA_YOGA_STRENGTH("Dhana Yoga Strength", "धन योग बल"),
    DHANA_YOGA_TITLE("Dhana Yogas Present", "धन योगहरू उपस्थित"),
    DHARMA_PATH("Dharmic Path", "धार्मिक मार्ग"),
    DIETARY_RECS("Dietary Recommendations", "आहार सिफारिसहरू"),
    DIRECTION_TO_SEARCH("Direction to search", "खोज्ने दिशा"),
    DIR_APP_JUP("Prayer area in northeast, face northeast for Jupiter remedies", "उत्तर-पूर्वमा पूजा क्षेत्र, बृहस्पतिको उपायका लागि उत्तर-पूर्व फर्किनुहोस्"),
    DIR_APP_KETU("Northwest direction for spiritual practices", "आध्यात्मिक अभ्यासका लागि उत्तर-पश्चिम दिशा"),
    DIR_APP_MARS("Keep red items in south, face south for Mars mantras", "दक्षिणमा राता वस्तुहरू राख्नुहोस्, मंगल मन्त्रका लागि दक्षिण फर्किनुहोस्"),
    DIR_APP_MERC("Study/work area in north direction is beneficial", "उत्तर दिशामा अध्ययन/कार्य क्षेत्र हुनु लाभदायक हुन्छ"),
    DIR_APP_MOON("Sleep with head towards northwest for mental peace", "मानसिक शान्तिको लागि उत्तर-पश्चिम तर्फ शिर राखेर सुत्नुहोस्"),
    DIR_APP_RAHU("Perform Rahu remedies facing southwest", "दक्षिण-पश्चिम फर्केर राहुका उपायहरू गर्नुहोस्"),
    DIR_APP_SAT("West direction work benefits, donate facing west on Saturdays", "पश्चिम दिशाको कामले फाइदा दिन्छ, शनिबार पश्चिम फर्केर दान गर्नुहोस्"),
    DIR_APP_SUN("Face east during Sun remedies, keep important items in east", "सूर्यको उपाय गर्दा पूर्व फर्किनुहोस्, महत्त्वपूर्ण कुरा पूर्वमा राख्नुहोस्"),
    DIR_APP_VENUS("Keep bedroom in southeast if possible", "सम्भव भएमा सुत्ने कोठा दक्षिण-पूर्वमा राख्नुहोस्"),
    DIR_EAST("East", "पूर्व"),
    DIR_NORTH("North", "उत्तर"),
    DIR_NORTH_EAST("North-East", "उत्तर-पूर्व (ईशान)"),
    DIR_NORTH_WEST("North-West", "उत्तर-पश्चिम (वायव्य)"),
    DIR_SOUTH("South", "दक्षिण"),
    DIR_SOUTH_EAST("South-East", "दक्षिण-पूर्व (आग्नेय)"),
    DIR_SOUTH_WEST("South-West", "दक्षिण-पश्चिम (नैऋत्य)"),
    DIR_WEST("West", "पश्चिम"),
    DISEASE_RESISTANCE("Disease Resistance", "रोग प्रतिरोध"),
    DIVISIONAL_CAREER_ANALYSIS("Career & Status", "क्यारियर र स्थिति"),
    DIVISIONAL_CHARTS_ABOUT("About Divisional Charts", "विभागीय कुण्डलीको बारेमा"),
    DIVISIONAL_CHARTS_ABOUT_DESC("Divisional charts (Vargas) provide deeper insights into specific life areas. D-2 for wealth, D-3 for siblings, D-9 for marriage, D-10 for career, D-12 for parents.", "विभागीय कुण्डलीहरूले विशेष जीवन क्षेत्रहरूमा गहिरो अन्तर्दृष्टि प्रदान गर्दछन्। D-2 धनको लागि, D-3 भाइबहिनीको लागि, D-9 विवाहको लागि, D-10 क्यारियरको लागि, D-12 अभिभावकको लागि।"),
    DIVISIONAL_CHARTS_SUBTITLE("Detailed Varga Analysis", "विस्तृत वर्ग विश्लेषण"),
    DIVISIONAL_CHARTS_TITLE("Divisional Charts Analysis", "विभागीय कुण्डली विश्लेषण"),
    DIVISIONAL_DASHAMSA_TAB("Dashamsa (D-10)", "दशांश (D-10)"),
    DIVISIONAL_DETAILED_RESULTS("Detailed Results", "विस्तृत परिणामहरू"),
    DIVISIONAL_DOMINANT_PLANET("Dominant Planet", "प्रमुख ग्रह"),
    DIVISIONAL_DREKKANA_TAB("Drekkana (D-3)", "द्रेष्काण (D-3)"),
    DIVISIONAL_DWADASAMSA_TAB("Dwadasamsa (D-12)", "द्वादशांश (D-12)"),
    DIVISIONAL_HORA_TAB("Hora (D-2)", "होरा (D-2)"),
    DIVISIONAL_HOUSE_EMPTY("Empty", "खाली"),
    DIVISIONAL_HOUSE_OCCUPIED("Occupied", "भरिएको"),
    DIVISIONAL_HOUSE_PLACEMENTS("House Placements", "भाव स्थितिहरू"),
    DIVISIONAL_KEY_PLANETS("Key Planets", "मुख्य ग्रहहरू"),
    DIVISIONAL_MARRIAGE_ANALYSIS("Marriage & Dharma", "विवाह र धर्म"),
    DIVISIONAL_NAVAMSA_TAB("Navamsa (D-9)", "नवांश (D-9)"),
    DIVISIONAL_OVERALL_STRENGTH("Overall Strength", "समग्र बल"),
    DIVISIONAL_PARENTS_ANALYSIS("Parents & Ancestry", "अभिभावक र वंश"),
    DIVISIONAL_PLANETS_SAME_SIGN_DESC("Planets in same sign as Rashi (D1):", "राशि (D1) जस्तै समान राशिमा रहेका ग्रहहरू:"),
    DIVISIONAL_REMEDIES_DESC("Consider remedies for %s to improve its results.", "%s को नतिजा सुधार गर्न उपायहरू विचार गर्नुहोस्।"),
    DIVISIONAL_SIBLING_ANALYSIS("Siblings & Courage", "भाइबहिनी र साहस"),
    DIVISIONAL_STRENGTH_ASSESSMENT("Strength Assessment", "बल मूल्याङ्कन"),
    DIVISIONAL_STRENGTH_DESC("Utilize the strength of %s in this varga.", "यस वर्गमा %s को शक्ति सदुपयोग गर्नुहोस्।"),
    DIVISIONAL_VARGOTTAMA_PLANETS("Vargottama Planets", "वर्गोत्तम ग्रहहरू"),
    DIVISIONAL_WEALTH_ANALYSIS("Wealth & Finance", "धन र वित्त"),
    DOMINANT("Dominant", "प्रभावशाली"),
    DOMINANT_STYLE("Dominant Learning Style", "प्रधान सिक्ने शैली"),
    DONATION_GUIDELINES("Guidelines", "दिशानिर्देशहरू"),
    DONATION_ITEMS("Donation Items", "दान वस्तुहरू"),
    DREAM_LIFE("Dream Life & Subconscious", "सपना जीवन र अवचेतन"),
    DRIG_ANALYZING("Analyzing Drig Bala...", "दृग्बल विश्लेषण गर्दै..."),
    DRIG_ASPECT_FROM("Aspect From", "बाट दृष्टि"),
    DRIG_ASPECT_STRENGTH("Aspect Strength", "दृष्टि बल"),
    DRIG_ASPECT_TO("Aspect To", "मा दृष्टि")
}
