package com.astro.storm.core.common

enum class StringKeyVarshaphala(override val en: String, override val ne: String) : StringKeyInterface {
    MUNTHA_AUTHORITY("Authority", "अधिकार"),
    MUNTHA_BUSINESS("Business", "व्यापार"),
    MUNTHA_CAREER_ADVANCEMENT("Career Advancement", "क्यारियर प्रगति"),
    MUNTHA_CHILDREN("Children", "सन्तान"),
    MUNTHA_COMMUNICATION("Communication", "सञ्चार"),
    MUNTHA_COMPETITION("Competition", "प्रतिस्पर्धा"),
    MUNTHA_CREATIVITY("Creativity", "सिर्जनशीलता"),
    MUNTHA_EXPENSES("Expenses", "खर्चहरू"),
    MUNTHA_FAMILY_MATTERS("Family Matters", "पारिवारिक मामिलाहरू"),
    MUNTHA_FINANCIAL_GAINS("Financial Gains", "आर्थिक लाभ"),
    MUNTHA_FOREIGN_LANDS("Foreign Lands", "विदेश"),
    MUNTHA_FORTUNE("Fortune", "भाग्य"),
    MUNTHA_FRIENDS("Friends", "मित्रहरू"),
    MUNTHA_FULFILLED_WISHES("Fulfilled Wishes", "पूरा भएका इच्छाहरू"),
    MUNTHA_GAINS("Gains", "लाभ"),
    MUNTHA_GENERAL_GROWTH("General Growth", "सामान्य विकास"),
    MUNTHA_HEALTH_FOCUS("Health Focus", "स्वास्थ्य फोकस"),
    MUNTHA_HEALTH_ISSUES("Health Issues", "स्वास्थ्य समस्याहरू"),
    MUNTHA_HIGHER_LEARNING("Higher Learning", "उच्च शिक्षा"),
    MUNTHA_HOME_AFFAIRS("Home Affairs", "घरेलु मामिलाहरू"),
    MUNTHA_INHERITANCE("Inheritance", "विरासत"),
    MUNTHA_INNER_PEACE("Inner Peace", "आन्तरिक शान्ति"),
    MUNTHA_INTERPRETATION_TEMPLATE("Muntha in %1\$s in the %2\$d%3\$s house focuses the year's energy on %4\$s. The Muntha lord %5\$s in house %6\$d provides %7\$s support for these matters.", "%2\$d%3\$s भावमा %1\$s मा मुन्थले वर्षको ऊर्जालाई %4\$s मा केन्द्रित गर्दछ। मुन्थ स्वामी %5\$s भाव %6\$d मा यी मामिलाहरूको लागि %7\$s समर्थन प्रदान गर्दछ।"),
    MUNTHA_LONG_TRAVEL("Long Travel", "लामो यात्रा"),
    MUNTHA_MARRIAGE("Marriage", "विवाह"),
    MUNTHA_NEW_BEGINNINGS("New Beginnings", "नयाँ शुरुवातहरू"),
    MUNTHA_PARTNERSHIPS("Partnerships", "साझेदारीहरू"),
    MUNTHA_PERSONAL_GROWTH("Personal Growth", "व्यक्तिगत विकास"),
    MUNTHA_PROPERTY("Property", "सम्पत्ति"),
    MUNTHA_RECOGNITION("Recognition", "मान्यता"),
    MUNTHA_RESEARCH("Research", "अनुसन्धान"),
    MUNTHA_ROMANCE("Romance", "रोमान्स"),
    MUNTHA_SERVICE("Service", "सेवा"),
    MUNTHA_SHORT_TRAVELS("Short Travels", "छोटो यात्राहरू"),
    MUNTHA_SIBLINGS("Siblings", "भाइबहिनी"),
    MUNTHA_SPEECH("Speech", "वाणी"),
    MUNTHA_SPIRITUALITY("Spirituality", "आध्यात्मिकता"),
    MUNTHA_SUPPORT_CHALLENGING("challenging but growth-oriented", "चुनौतीपूर्ण तर विकासोन्मुख"),
    MUNTHA_SUPPORT_EXCELLENT("excellent", "उत्कृष्ट"),
    MUNTHA_SUPPORT_FAVORABLE("favorable", "अनुकूल"),
    MUNTHA_SUPPORT_VARIABLE("variable", "परिवर्तनशील"),
    MUNTHA_TRANSFORMATION("Transformation", "रूपान्तरण"),
    SAHAM_ACTIVATION("Activation Period", "सक्रियता अवधि"),
    SAHAM_ANALYZING("Analyzing Sahams...", "सहम विश्लेषण गर्दै..."),
    SAHAM_AROGYA("Arogya Saham", "आरोग्य सहम"),
    SAHAM_AROGYA_DESC("Health", "स्वास्थ्य"),
    SAHAM_ASHA("Asha Saham", "आशा सहम"),
    SAHAM_ASHA_DESC("Hopes/Wishes", "आशा/इच्छा"),
    SAHAM_ASHA_SANSKRIT("Asha Saham", "आशा सहम"),
    SAHAM_BANDHANA("Bondage", "बन्धन"),
    SAHAM_BANDHANA_DESC("Restrictions and obstacles", "प्रतिबन्ध र बाधाहरू"),
    SAHAM_BANDHANA_SANSKRIT("Bandhana Saham", "बन्धन सहम"),
    SAHAM_BANDHU("Bandhu Saham", "बन्धु सहम"),
    SAHAM_BANDHU_DESC("Relatives", "नातेदार"),
    SAHAM_BHRATRI("Bhratri Saham", "भ्रातृ सहम"),
    SAHAM_BHRATRI_DESC("Siblings", "भाइबहिनी"),
    SAHAM_BHRATRI_SANSKRIT("Bhratri Saham", "भ्रातृ सहम"),
    SAHAM_CHILDREN("Part of Children", "सन्तान सहम"),
    SAHAM_COMMERCE("Part of Commerce", "व्यापार सहम"),
    SAHAM_COURAGE("Part of Courage", "साहस सहम"),
    SAHAM_DEATH("Part of Death", "मृत्यु सहम"),
    SAHAM_DESC("Sensitive points calculated from three chart factors", "तीन चार्ट कारकहरूबाट गणना गरिएका संवेदनशील बिन्दुहरू"),
    SAHAM_DHANA("Dhana Saham", "धन सहम"),
    SAHAM_DHANA_DESC("Wealth", "धन"),
    SAHAM_DHANA_SANSKRIT("Dhana Saham", "धन सहम"),
    SAHAM_EDUCATION("Education Saham", "शिक्षा सहम"),
    SAHAM_ENEMIES("Part of Enemies", "शत्रु सहम"),
    SAHAM_EROS("Part of Eros", "इरोस सहम"),
    SAHAM_FAITH("Part of Faith", "धर्म सहम"),
    SAHAM_FAME("Part of Fame", "प्रसिद्धि सहम"),
    SAHAM_FATHER("Part of Father", "पिता सहम"),
    SAHAM_FORMULA("Formula", "सूत्र"),
    SAHAM_FORTUNE("Part of Fortune", "भाग्य सहम"),
    SAHAM_FRIENDS("Part of Friends", "मित्र सहम"),
    SAHAM_GAURAVA("Gaurava Saham", "गौरव सहम"),
    SAHAM_GAURAVA_DESC("Honor/Respect", "सम्मान/इज्जत"),
    SAHAM_HEALTH("Health Saham", "स्वास्थ्य सहम"),
    SAHAM_HIDDEN("Part of Hidden Matters", "गोप्य विषय सहम"),
    SAHAM_HOUSE("House", "भाव"),
    SAHAM_ILLNESS("Part of Illness", "रोग सहम"),
    SAHAM_IMPRISONMENT("Part of Imprisonment", "बन्दी सहम"),
    SAHAM_INDICATES("indicates specific life areas", "विशिष्ट जीवन क्षेत्रहरू संकेत गर्दछ"),
    SAHAM_INFO_DESC("Saham (Arabic Parts) are sensitive points calculated from Ascendant, planet, and house cusps. Each Saham represents a specific life area. When transits or dashas activate a Saham, related events manifest.", "सहम (अरबी बिन्दु) लग्न, ग्रह, र भाव सन्धिबाट गणना गरिएका संवेदनशील बिन्दुहरू हुन्। प्रत्येक सहमले विशेष जीवन क्षेत्र प्रतिनिधित्व गर्छ। गोचर वा दशाले सहम सक्रिय गर्दा, सम्बन्धित घटनाहरू प्रकट हुन्छन्।"),
    SAHAM_INFO_TITLE("About Saham", "सहमको बारेमा"),
    SAHAM_INHERITANCE("Part of Inheritance", "विरासत सहम"),
    SAHAM_INTERPRETATION("Interpretation", "व्याख्या"),
    SAHAM_INTERPRETATION_TEMPLATE("The %s Saham in %s (House %d) relates to %s this year. Its lord %s in House %d is %s.", "%s सहम %s मा (भाव %d) यस वर्ष %s सँग सम्बन्धित छ। यसको स्वामी %s भाव %d मा %s छ।"),
    SAHAM_KARMA("Karma Saham", "कर्म सहम"),
    SAHAM_KARMA_DESC("Career/Action", "क्यारियर/कर्म"),
    SAHAM_KARMA_SANSKRIT("Karma Saham", "कर्म सहम"),
    SAHAM_KARYASIDDHI("Karyasiddhi Saham", "कार्यसिद्धि सहम"),
    SAHAM_KARYASIDDHI_TYPE("Success", "कार्यसिद्धि"),
    SAHAM_KARYASIDDHI_TYPE_DESC("Accomplishment of goals", "लक्ष्य प्राप्ति"),
    SAHAM_KARYASIDDHI_TYPE_SANSKRIT("Karyasiddhi Saham", "कार्यसिद्धि सहम"),
    SAHAM_KNOWLEDGE("Part of Knowledge", "ज्ञान सहम"),
    SAHAM_LORD("Lord", "स्वामी"),
    SAHAM_LORD_ATTENTION("requiring attention and effort", "ध्यान र प्रयास चाहिने"),
    SAHAM_LORD_REASONABLE("providing reasonable support", "उचित समर्थन प्रदान गर्दै"),
    SAHAM_LORD_VARIABLE("influencing matters variably", "मामिलाहरूलाई परिवर्तनशील रूपमा प्रभाव पार्दै"),
    SAHAM_LORD_WELL_PLACED("well-placed, promising positive outcomes", "राम्ररी स्थित, सकारात्मक परिणामहरूको वाचा"),
    SAHAM_LOVE("Part of Love", "प्रेम सहम"),
    SAHAM_MAHATMYA("Mahatmya Saham", "महात्म्य सहम"),
    SAHAM_MAHATMYA_DESC("Greatness/Spirituality", "महानता/आध्यात्मिकता"),
    SAHAM_MAHATMYA_SANSKRIT("Mahatmya Saham", "महात्म्य सहम"),
    SAHAM_MARRIAGE("Part of Marriage", "विवाह सहम"),
    SAHAM_MATRI("Matri Saham", "मातृ सहम"),
    SAHAM_MATRI_DESC("Mother", "आमा"),
    SAHAM_MATRI_SANSKRIT("Matri Saham", "मातृ सहम"),
    SAHAM_MITRA("Mitra Saham", "मित्र सहम"),
    SAHAM_MITRA_DESC("Friends/Allies", "मित्र/साथी"),
    SAHAM_MITRA_SANSKRIT("Mitra Saham", "मित्र सहम"),
    SAHAM_MOTHER("Part of Mother", "माता सहम"),
    SAHAM_MRITYU("Mrityu Saham", "मृत्यु सहम"),
    SAHAM_MRITYU_DESC("Death/Longevity", "मृत्यु/आयु"),
    SAHAM_MRITYU_SANSKRIT("Mrityu Saham", "मृत्यु सहम"),
    SAHAM_NAKSHATRA("Nakshatra", "नक्षत्र"),
    SAHAM_NECESSITY("Part of Necessity", "आवश्यकता सहम"),
    SAHAM_PARADESA("Paradesa Saham", "परदेश सहम"),
    SAHAM_PARADESA_DESC("Foreign/Travel", "विदेश/यात्रा"),
    SAHAM_PARADESA_SANSKRIT("Paradesa Saham", "परदेश सहम"),
    SAHAM_PITRI("Pitri Saham", "पितृ सहम"),
    SAHAM_PITRI_DESC("Father", "पिता"),
    SAHAM_PITRI_SANSKRIT("Pitri Saham", "पितृ सहम"),
    SAHAM_POSITION("Position", "स्थान"),
    SAHAM_PROFESSION("Part of Profession", "पेशा सहम"),
    SAHAM_PROPERTY("Part of Property", "सम्पत्ति सहम"),
    SAHAM_PUNYA("Punya Saham", "पुण्य सहम"),
    SAHAM_PUNYA_DESC("Fortune/Merit point", "भाग्य/पुण्य बिन्दु"),
    SAHAM_PUNYA_SANSKRIT("Punya Saham", "पुण्य सहम"),
    SAHAM_PUTRA("Putra Saham", "पुत्र सहम"),
    SAHAM_PUTRA_DESC("Children", "सन्तान"),
    SAHAM_PUTRA_SANSKRIT("Putra Saham", "पुत्र सहम"),
    SAHAM_RAJA("Power", "राज"),
    SAHAM_RAJA_DESC("Authority and position", "अधिकार र पद"),
    SAHAM_RAJA_SANSKRIT("Raja Saham", "राज सहम"),
    SAHAM_ROGA("Disease", "रोग"),
    SAHAM_ROGA_DESC("Health challenges", "स्वास्थ्य चुनौतीहरू"),
    SAHAM_ROGA_SANSKRIT("Roga Saham", "रोग सहम"),
    SAHAM_SAMARTHA("Samartha Saham", "समर्थ सहम"),
    SAHAM_SAMARTHA_DESC("Capability/Skill", "क्षमता/सीप"),
    SAHAM_SAMARTHA_SANSKRIT("Samartha Saham", "समर्थ सहम"),
    SAHAM_SARPA("Sarpa Saham", "सर्प सहम"),
    SAHAM_SARPA_DESC("Serpent/Hidden enemies", "सर्प/लुकेका शत्रु"),
    SAHAM_SIBLINGS("Part of Siblings", "भाइबहिनी सहम"),
    SAHAM_SIGN("Sign", "राशि"),
    SAHAM_SPIRIT("Part of Spirit", "आत्मा सहम"),
    SAHAM_STRENGTH("Saham Strength", "सहम बल"),
    SAHAM_SUBTITLE("Arabic Parts / Lots", "अरबी बिन्दुहरू"),
    SAHAM_SUCCESS("Success", "सफलता"),
    SAHAM_SUDDEN_EVENTS("Part of Sudden Events", "आकस्मिक घटना सहम"),
    SAHAM_SURGERY("Part of Surgery", "शल्यक्रिया सहम"),
    SAHAM_TAB_MAJOR("Major", "प्रमुख"),
    SAHAM_TAB_MINOR("Minor", "सामान्य"),
    SAHAM_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    SAHAM_TAB_PRASHNA("Prashna", "प्रश्न"),
    SAHAM_TITLE("Saham", "सहम"),
    SAHAM_TRAVEL("Part of Travel", "यात्रा सहम"),
    SAHAM_UNABLE("Unable to calculate Sahams", "सहम गणना गर्न सकिएन"),
    SAHAM_VEDIC_REF("Vedic Reference: Tajika Neelakanthi, Prashna Marga", "वैदिक सन्दर्भ: ताजिक नीलकण्ठी, प्रश्न मार्ग"),
    SAHAM_VICTORY("Part of Victory", "विजय सहम"),
    SAHAM_VIDYA("Vidya Saham", "विद्या सहम"),
    SAHAM_VIDYA_DESC("Education/Knowledge", "शिक्षा/ज्ञान"),
    SAHAM_VIDYA_SANSKRIT("Vidya Saham", "विद्या सहम"),
    SAHAM_VIVAHA("Vivaha Saham", "विवाह सहम"),
    SAHAM_VIVAHA_DESC("Marriage", "विवाह"),
    SAHAM_VIVAHA_SANSKRIT("Vivaha Saham", "विवाह सहम"),
    SAHAM_WEALTH("Wealth Saham", "धन सहम"),
    SAHAM_YASHAS("Yashas Saham", "यश सहम"),
    SAHAM_YASHAS_DESC("Fame/Reputation", "यश/प्रतिष्ठा"),
    SAHAM_YASHAS_SANSKRIT("Yashas Saham", "यश सहम"),
    TAJIKA_DUHPHALI_KUTTHA("Duhphali-Kuttha", "दुःफली-कुट्ठ"),
    TAJIKA_DUHPHALI_KUTTHA_DESC("Malefic intervention prevents completion", "पापग्रह हस्तक्षेपले पूर्णता रोक्छ"),
    TAJIKA_DURAPHA("Durapha", "दुराफ"),
    TAJIKA_DURAPHA_DESC("Hard aspect causing difficulties", "कठिनाइहरू निम्त्याउने कडा पक्ष"),
    TAJIKA_DURAPHA_EFFECT("Durapha (Weak) - indicates weak results or lack of clear direction.", "दुराफ (कमजोर) - कमजोर नतिजाहरू वा स्पष्ट दिशाको अभाव संकेत गर्दछ।"),
    TAJIKA_EASARAPHA("Easarapha", "इसराफ"),
    TAJIKA_EASARAPHA_DESC("Separating aspect - event has passed or is fading", "विलग पक्ष - घटना बितिसकेको वा क्षीण हुँदैछ"),
    TAJIKA_EASARAPHA_EFFECT("Easarapha (Separation) - indicates matters passing or moving away from fruition.", "ईशराफ (विभाजन) - विषयहरू पूरा हुनबाट टाढा जाने संकेत गर्दछ।"),
    TAJIKA_GAIRI_KAMBOOLA("Gairi-Kamboola", "गैरी-कम्बूल"),
    TAJIKA_GAIRI_KAMBOOLA_DESC("Weaker form of Kamboola", "कम्बूलको कमजोर रूप"),
    TAJIKA_IKKABALA("Ikkabala", "इक्कबल"),
    TAJIKA_IKKABALA_DESC("Unity of strength between planets", "ग्रहहरू बीच बलको एकता"),
    TAJIKA_INFLUENCE_ENERGY("This aspect brings %s energy to %s matters.", "यो दृष्टिले %s मामिलामा %s ऊर्जा ल्याउँछ।"),
    TAJIKA_ITHASALA("Ithasala", "इतशाल"),
    TAJIKA_ITHASALA_DESC("Applying aspect - promises fulfillment of matters", "निकटवर्ती पक्ष - कार्यहरू पूर्ण हुने वाचा"),
    TAJIKA_ITHASALA_EFFECT("Ithasala (Favorable) - indicates fruition and success through active efforts.", "इत्थशाल (अनुकूल) - सक्रिय प्रयासहरू मार्फत फल प्राप्ति र सफलता संकेत गर्दछ।"),
    TAJIKA_KAMBOOLA("Kamboola", "कम्बूल"),
    TAJIKA_KAMBOOLA_DESC("Powerful Ithasala with angular placement", "केन्द्र स्थानसहित शक्तिशाली इतशाल"),
    TAJIKA_KAMBOOLA_EFFECT("Kamboola (Strong) - indicates very strong and certain results.", "कम्बूल (बलियो) - धेरै बलियो र निश्चित नतिजाहरू संकेत गर्दछ।"),
    TAJIKA_KHALASARA("Khalasara", "खलासर"),
    TAJIKA_KHALASARA_DESC("Mutual separation - dissolution of matters", "पारस्परिक विलगता - कार्यहरूको विघटन"),
    TAJIKA_KUTTHA("Kuttha", "कुट्ठ"),
    TAJIKA_KUTTHA_DESC("Impediment to aspect completion", "पक्ष पूर्णतामा बाधा"),
    TAJIKA_MANAU("Manau", "मनौ"),
    TAJIKA_MANAU_DESC("Reverse application - slower planet applies to faster", "उल्टो प्रयोग - ढिलो ग्रहले छिटोमा प्रयोग गर्छ"),
    TAJIKA_MUTHASHILA("Muthashila", "मुथशिल"),
    TAJIKA_MUTHASHILA_DESC("Mutual application between planets", "ग्रहहरू बीच पारस्परिक प्रयोग"),
    TAJIKA_NAKTA("Nakta", "नक्त"),
    TAJIKA_NAKTA_DESC("Transmission of light with reception - indirect completion", "ग्रहणसहित प्रकाश प्रसारण - अप्रत्यक्ष पूर्णता"),
    TAJIKA_PREDICTION_X_FOR_Y("%s for %s", "%s को लागि %s"),
    TAJIKA_RADDA("Radda", "रद्द"),
    TAJIKA_RADDA_DESC("Refranation - retrograde breaks the aspect", "भंग - वक्री गतिले पक्ष तोड्छ"),
    TAJIKA_RADDA_EFFECT("Radda (Obstruction) - indicates unexpected obstacles or reversals.", "रद्द (बाधा) - अप्रत्याशित बाधाहरू वा उल्टो नतिजाहरू संकेत गर्दछ।"),
    TAJIKA_TAMBIRA("Tambira", "तम्बीर"),
    TAJIKA_TAMBIRA_DESC("Indirect aspect through intermediary", "मध्यस्थ मार्फत अप्रत्यक्ष पक्ष"),
    TAJIKA_YAMAYA("Yamaya", "यमाया"),
    TAJIKA_YAMAYA_DESC("Translation of light - third planet connects significators", "प्रकाश अनुवाद - तेस्रो ग्रहले कारकहरू जोड्दछ"),
    VARSHAPHALA_ACTIVE("Active", "सक्रिय"),
    VARSHAPHALA_AGE("Age %d", "आयु %d"),
    VARSHAPHALA_AGE_FORMAT("Age %d", "उमेर %d"),
    VARSHAPHALA_ANNUAL_CHART("Annual Chart", "वार्षिक चार्ट"),
    VARSHAPHALA_ANNUAL_HOROSCOPE("Annual Horoscope", "वार्षिक राशिफल"),
    VARSHAPHALA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    VARSHAPHALA_CHART_LEGEND_ASC("Asc", "लग्न"),
    VARSHAPHALA_CHART_LEGEND_BENEFIC("Benefic", "शुभ"),
    VARSHAPHALA_CHART_LEGEND_MALEFIC("Malefic", "पाप"),
    VARSHAPHALA_CHART_LEGEND_MUNTHA("Muntha", "मुन्थ"),
    VARSHAPHALA_COMPUTING("Computing Annual Horoscope...", "वार्षिक राशिफल गणना गर्दै..."),
    VARSHAPHALA_COMPUTING_DESC("Calculating Tajika aspects, Sahams & Mudda Dasha", "तजिका पक्ष, सहम र मुद्द दशा गणना गर्दै"),
    VARSHAPHALA_CURRENT("CURRENT", "वर्तमान"),
    VARSHAPHALA_DAYS("%d days", "%d दिन"),
    VARSHAPHALA_DAYS_FORMAT("%d days", "%d दिन"),
    VARSHAPHALA_ERROR("Calculation Error", "गणना त्रुटि"),
    VARSHAPHALA_FAVORABLE("Favorable", "अनुकूल"),
    VARSHAPHALA_FIVEFOLD_STRENGTH("Five-fold Planetary Strength", "पञ्चवर्गीय ग्रह बल"),
    VARSHAPHALA_HOUSE("House", "भाव"),
    VARSHAPHALA_HOUSES_PREFIX("Houses: ", "भावहरू: "),
    VARSHAPHALA_HOUSE_SIGN("House %d - %s", "भाव %d - %s"),
    VARSHAPHALA_IMPORTANT_DATES("%d important dates", "%d महत्त्वपूर्ण मितिहरू"),
    VARSHAPHALA_IN_HOUSE("House %d", "भाव %d"),
    VARSHAPHALA_KEY_DATES("Key Dates", "महत्त्वपूर्ण मितिहरू"),
    VARSHAPHALA_LORD_IN_HOUSE("Lord: %s in H%d", "स्वामी: %s भाव%d मा"),
    VARSHAPHALA_LORD_PREFIX("Lord: %s", "स्वामी: %s"),
    VARSHAPHALA_MAJOR_THEMES("Major Themes", "मुख्य विषयहरू"),
    VARSHAPHALA_MONTHLY_OUTLOOK("Monthly Outlook", "मासिक दृष्टिकोण"),
    VARSHAPHALA_MUDDA_DASHA("Mudda Dasha", "मुद्द दशा"),
    VARSHAPHALA_MUDDA_DASHA_DESC("Annual planetary periods based on Moon's position", "चन्द्रको स्थितिमा आधारित वार्षिक ग्रह अवधिहरू"),
    VARSHAPHALA_MUNTHA("Muntha", "मुन्थ"),
    VARSHAPHALA_MUNTHA_LORD("Lord: %s", "स्वामी: %s"),
    VARSHAPHALA_NEXT_YEAR("Next year", "अर्को वर्ष"),
    VARSHAPHALA_NO_CHART("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
    VARSHAPHALA_NO_CHART_DESC("Select a birth chart to view Varshaphala", "वर्षफल हेर्न जन्म कुण्डली छान्नुहोस्"),
    VARSHAPHALA_NO_PLANETS("No planets", "कुनै ग्रह छैन"),
    VARSHAPHALA_OVERALL_PREDICTION("Overall Prediction", "समग्र भविष्यवाणी"),
    VARSHAPHALA_PANCHA_VARGIYA("Pancha Vargiya Bala", "पञ्च वर्गीय बल"),
    VARSHAPHALA_PLANETS("Planets: ", "ग्रहहरू: "),
    VARSHAPHALA_POSITION("Position", "स्थिति"),
    VARSHAPHALA_PREDICTIONS("Year Predictions", "वर्ष भविष्यवाणी"),
    VARSHAPHALA_PREV_YEAR("Previous year", "अघिल्लो वर्ष"),
    VARSHAPHALA_RESET_YEAR("Reset to Current Year", "वर्तमान वर्षमा रिसेट"),
    VARSHAPHALA_RETURN_DATE("Return Date", "प्रतिफल मिति"),
    VARSHAPHALA_RULES_HOUSES("Rules Houses: %s", "भावहरू शासन: %s"),
    VARSHAPHALA_SAHAMS("Sahams", "सहमहरू"),
    VARSHAPHALA_SAHAMS_DESC("Sensitive points calculated from planetary positions", "ग्रह स्थितिबाट गणना गरिएको संवेदनशील बिन्दुहरू"),
    VARSHAPHALA_SAHAMS_TITLE("Sahams (Arabic Parts)", "सहम (अरबी भाग)"),
    VARSHAPHALA_SELECT_CHART("Select a birth chart to view Varshaphala", "वर्षफल हेर्न जन्म कुण्डली छान्नुहोस्"),
    VARSHAPHALA_SELECT_YEAR("Select Year", "वर्ष चयन गर्नुहोस्"),
    VARSHAPHALA_SOLAR_RETURN("Solar Return", "सौर प्रतिफल"),
    VARSHAPHALA_SPECIFIC_INDICATIONS("Specific Indications:", "विशिष्ट संकेतहरू:"),
    VARSHAPHALA_SUN_RETURNS("Sun returns to natal position", "सूर्य जन्मकालीन स्थानमा फर्कन्छ"),
    VARSHAPHALA_TAB_DASHA("Dasha", "दशा"),
    VARSHAPHALA_TAB_HOUSES("Houses", "भावहरू"),
    VARSHAPHALA_TAB_OVERVIEW("Overview", "अवलोकन"),
    VARSHAPHALA_TAB_SAHAMS("Sahams", "सहम"),
    VARSHAPHALA_TAB_TAJIKA("Tajika", "तजिका"),
    VARSHAPHALA_TAJIKA("Tajika Aspects", "ताजिक दृष्टि"),
    VARSHAPHALA_TAJIKA_CHART("Tajika Annual Chart", "तजिका वार्षिक कुण्डली"),
    VARSHAPHALA_TAJIKA_SUMMARY("Tajika Yogas Summary", "तजिका योग सारांश"),
    VARSHAPHALA_THREE_FLAG("Three-flag Diagram", "त्रिपताकी चक्र"),
    VARSHAPHALA_TITLE("Varshaphala", "वर्षफल"),
    VARSHAPHALA_TOTAL("Total", "कुल"),
    VARSHAPHALA_TRI_PATAKI("Tri-Pataki Chakra", "त्रि-पतकी चक्र"),
    VARSHAPHALA_YEAR_LORD("Year Lord", "वर्ष स्वामी"),
    VARSHAPHALA_YEAR_OF_LIFE("Year %d of life", "जीवनको वर्ष %d"),
    VARSHAPHALA_YEAR_RANGE("%d - %d", "%d - %d"),
    VARSHAPHALA_YOGAS("Tajika Yogas", "ताजिक योग")
}
