package com.astro.storm.core.common

enum class StringKeyMatchmakingPart1(override val en: String, override val ne: String) : StringKeyInterface {
    COMPAT_AVERAGE("Average Match", "औसत मिलान"),
    COMPAT_AVERAGE_DESC("Acceptable with some remedies. Moderate compatibility requiring mutual understanding and effort.", "केही उपायहरूसहित स्वीकार्य। पारस्परिक बुझाइ र प्रयास आवश्यक पर्ने मध्यम अनुकूलता।"),
    COMPAT_BELOW_AVERAGE("Below Average", "औसतमुनि"),
    COMPAT_BELOW_AVERAGE_DESC("Caution advised. Several compatibility issues that need addressing through remedies and counseling.", "सावधानी आवश्यक। उपाय र परामर्शद्वारा सम्बोधन गर्नुपर्ने धेरै अनुकूलता समस्याहरू।"),
    COMPAT_BELOW_AVG("Below Average", "औसतभन्दा कम"),
    COMPAT_BELOW_AVG_DESC("Caution advised. Several compatibility issues that need addressing through remedies and counseling.", "सावधानी सल्लाह दिइएको। उपाय र परामर्शबाट सम्बोधन गर्नुपर्ने धेरै अनुकूलता समस्याहरू।"),
    COMPAT_EXCELLENT("Excellent Match", "उत्कृष्ट मिलान"),
    COMPAT_EXCELLENT_DESC("Highly recommended for marriage. Strong compatibility across all factors with harmonious planetary alignments.", "विवाहको लागि अत्यधिक सिफारिस गरिएको। सबै कारकहरूमा बलियो अनुकूलता र सामञ्जस्यपूर्ण ग्रह संरेखण।"),
    COMPAT_FOCUS_COMMUNICATION("Mental & Communication: Schedule regular check-ins, practice active listening, express appreciation daily, address conflicts calmly.", "मानसिक र सञ्चार: नियमित जाँच-पडताल तालिका बनाउनुहोस्, सक्रिय सुनाइ अभ्यास गर्नुहोस्, दैनिक प्रशंसा व्यक्त गर्नुहोस्, द्वन्द्वहरूलाई शान्तपूर्वक सम्बोधन गर्नुहोस्।"),
    COMPAT_FOCUS_FINANCIAL("Financial Harmony: Create joint financial plans, discuss money values openly, set shared goals, respect spending differences.", "आर्थिक सामञ्जस्य: संयुक्त वित्तीय योजनाहरू बनाउनुहोस्, पैसा मूल्यहरू खुलेर छलफल गर्नुहोस्, साझा लक्ष्यहरू सेट गर्नुहोस्, खर्च भिन्नताहरूलाई सम्मान गर्नुहोस्।"),
    COMPAT_FOCUS_HEALTH("Health & Progeny: Maintain healthy lifestyles, support each other's wellness, prepare mindfully for parenthood.", "स्वास्थ्य र सन्तान: स्वस्थ जीवनशैली कायम राख्नुहोस्, एकअर्काको कल्याणलाई समर्थन गर्नुहोस्, मातृत्व/पितृत्वको लागि सावधानीपूर्वक तयारी गर्नुहोस्।"),
    COMPAT_FOCUS_PHYSICAL("Physical Harmony: Prioritize physical affection, maintain health together, respect boundaries, create intimate connection rituals.", "शारीरिक सामञ्जस्य: शारीरिक स्नेहलाई प्राथमिकता दिनुहोस्, सँगै स्वास्थ्य कायम राख्नुहोस्, सीमाहरूको सम्मान गर्नुहोस्, अन्तरंग सम्बन्ध अनुष्ठानहरू सिर्जना गर्नुहोस्।"),
    COMPAT_FOCUS_SPIRITUAL("Spiritual Growth Together: Practice joint meditation, visit temples together, study spiritual texts, maintain shared spiritual practices.", "सँगै आध्यात्मिक विकास: संयुक्त ध्यान अभ्यास गर्नुहोस्, सँगै मन्दिरहरू भ्रमण गर्नुहोस्, आध्यात्मिक ग्रन्थहरू अध्ययन गर्नुहोस्, साझा आध्यात्मिक अभ्यासहरू कायम राख्नुहोस्।"),
    COMPAT_FOCUS_TEMPERAMENT("Temperamental Balance: Understand personality differences, practice patience, compromise consciously, celebrate individual strengths.", "स्वभावगत सन्तुलन: व्यक्तित्व भिन्नताहरू बुझ्नुहोस्, धैर्य अभ्यास गर्नुहोस्, सचेत रूपमा सम्झौता गर्नुहोस्, व्यक्तिगत शक्तिहरू मनाउनुहोस्।"),
    COMPAT_GOOD("Good Match", "राम्रो मिलान"),
    COMPAT_GOOD_DESC("Recommended. Good overall compatibility with minor differences that can be easily managed.", "सिफारिस गरिएको। सजिलैसँग व्यवस्थापन गर्न सकिने सानातिना भिन्नताहरूसहित राम्रो समग्र अनुकूलता।"),
    COMPAT_POOR("Poor Match", "कमजोर मिलान"),
    COMPAT_POOR_DESC("Not recommended. Significant compatibility challenges that may cause ongoing difficulties.", "सिफारिस गरिएको छैन। निरन्तर कठिनाइहरू ल्याउन सक्ने महत्त्वपूर्ण अनुकूलता चुनौतीहरू।"),
    COMPAT_RECOMMEND_MARRIAGE_TIMING("Recommended Marriage Timing", "सिफारिस गरिएको विवाह समय"),
    COMPAT_RECOMMEND_RELATIONSHIP_FOCUS("Relationship Focus Areas", "सम्बन्ध फोकस क्षेत्रहरू"),
    COMPAT_TIMING_AFTER_REMEDIES("Proceed after completing essential remedies (minimum 40-90 days). This allows remedial measures to strengthen weak areas before marriage.", "आवश्यक उपायहरू पूरा गरेपछि अगाडि बढ्नुहोस् (न्यूनतम ४०-९० दिन)। यसले विवाह अघि कमजोर क्षेत्रहरूलाई बलियो बनाउन उपचारात्मक उपायहरूलाई अनुमति दिन्छ।"),
    COMPAT_TIMING_EXTENDED_REMEDIES("Delay marriage for 6-12 months while performing comprehensive remedies. Use this time for counseling and conscious preparation.", "व्यापक उपायहरू गर्दै ६-१२ महिना विवाहमा ढिलाइ गर्नुहोस्। परामर्श र सचेत तयारीको लागि यो समय प्रयोग गर्नुहोस्।"),
    COMPAT_TIMING_IMMEDIATE("Marriage can proceed without delay. Choose an auspicious muhurta during favorable planetary transits for both charts.", "विवाह ढिलाइ बिना अगाडि बढ्न सक्छ। दुवै कुण्डलीको लागि अनुकूल ग्रह गोचरको समयमा शुभ मुहूर्त छान्नुहोस्।"),
    COMPAT_TIMING_RECONSIDER("Seriously reconsider this match. If proceeding, delay minimum 1 year with extensive remedies, counseling, and spiritual preparation.", "यस मिलानलाई गम्भीरतापूर्वक पुनर्विचार गर्नुहोस्। अगाडि बढ्दै हुनुहुन्छ भने, व्यापक उपाय, परामर्श र आध्यात्मिक तयारीसहित न्यूनतम १ वर्ष ढिलाइ गर्नुहोस्।"),
    GANA_COMPATIBILITY_DETAILS("Deva-Deva = 6 points (best). Manushya-Manushya = 6 points. Rakshasa-Rakshasa = 6 points. Deva-Manushya = 5 points. Manushya-Rakshasa = 2 points. Deva-Rakshasa = 0 points (worst).", "देव-देव = ६ अंक (उत्तम)। मनुष्य-मनुष्य = ६ अंक। राक्षस-राक्षस = ६ अंक। देव-मनुष्य = ५ अंक। मनुष्य-राक्षस = २ अंक। देव-राक्षस = ० अंक (सबैभन्दा खराब)।"),
    GANA_COMPATIBLE("Compatible Ganas - good temperamental harmony with minor differences.", "अनुकूल गण - सानातिना भिन्नताहरूसहित राम्रो स्वभावगत सामञ्जस्य।"),
    GANA_DESC("Temperament and behavior compatibility", "स्वभाव र व्यवहार अनुकूलता"),
    GANA_DEVA("Deva", "देव"),
    GANA_DEVA_DESC("Divine - Sattvik, gentle, spiritual", "दैवी - सात्त्विक, सौम्य, आध्यात्मिक"),
    GANA_DIFFERENT("Different temperaments - significant adjustment required. May cause lifestyle clashes.", "फरक स्वभाव - महत्त्वपूर्ण समायोजन आवश्यक। जीवनशैली टकराव हुन सक्छ।"),
    GANA_IMPORTANCE("Gana measures behavioral temperament and nature. It indicates how partners will behave in conflicts and daily life situations.", "गणले व्यवहारिक स्वभाव र प्रकृति मापन गर्दछ। यसले साझेदारहरूले द्वन्द्व र दैनिक जीवन परिस्थितिहरूमा कसरी व्यवहार गर्छन् भनेर संकेत गर्दछ।"),
    GANA_MANUSHYA("Manushya", "मनुष्य"),
    GANA_MANUSHYA_DESC("Human - Rajasik, balanced, worldly", "मानव - राजसिक, सन्तुलित, सांसारिक"),
    GANA_OPPOSITE("Opposite temperaments - major incompatibility. Frequent conflicts likely.", "विपरीत स्वभाव - प्रमुख असंगतता। बारम्बार द्वन्द्व हुन सक्छ।"),
    GANA_PARTIAL("Partially compatible - some temperamental adjustment needed.", "आंशिक अनुकूल - केही स्वभावगत समायोजन आवश्यक।"),
    GANA_RAKSHASA("Rakshasa", "राक्षस"),
    GANA_RAKSHASA_DESC("Demon - Tamasik, aggressive, dominant", "दानव - तामसिक, आक्रामक, प्रभावशाली"),
    GANA_REMEDY_LOW("Remedy: Chant Ganapati Atharvasheersham daily for 41 days. Perform joint Ganesh puja every month. Practice patience, tolerance, and conscious communication to bridge temperamental differences. Couples counseling may be beneficial.", "उपाय: ४१ दिन दैनिक गणपति अथर्वशीर्षम् जाप गर्नुहोस्। प्रत्येक महिना संयुक्त गणेश पूजा गर्नुहोस्। स्वभावगत भिन्नताहरू पाट्न धैर्य, सहनशीलता र सचेत सञ्चार अभ्यास गर्नुहोस्। जोडी परामर्श लाभदायक हुन सक्छ।"),
    GANA_SAME("Same Gana - perfect temperamental harmony. Similar approach to life and values.", "उही गण - उत्तम स्वभावगत सामञ्जस्य। जीवन र मूल्यहरूमा समान दृष्टिकोण।"),
    MAHENDRA_FAVORABLE("Mahendra favorable at position {count} - promotes longevity and progeny", "महेन्द्र स्थिति {count} मा अनुकूल - दीर्घायु र सन्तान प्रवर्धन गर्छ"),
    MAHENDRA_NOT_APPLICABLE("Mahendra position not in favorable sequence", "महेन्द्र स्थिति अनुकूल क्रममा छैन"),
    MANGLIK_BOTH_MATCH("Both Manglik - Doshas cancel each other (Manglik to Manglik match is recommended)", "दुवै मांगलिक - दोषहरू एकअर्कालाई निष्क्रिय गर्छन् (मांगलिकसँग मांगलिक मिलान सिफारिस गरिएको)"),
    MANGLIK_BOTH_NON("Both non-Manglik - No concerns", "दुवै गैर-मांगलिक - कुनै चिन्ता छैन"),
    MANGLIK_BRIDE_ONLY("Bride is Manglik while Groom is not - Kumbh Vivah or other remedies advised", "दुलही मांगलिक छिन् जबकि दुलाहा छैनन् - कुम्भ विवाह वा अन्य उपायहरू सल्लाह दिइएको"),
    MANGLIK_CANCELLATIONS("Cancellation Factors", "रद्द गर्ने कारकहरू"),
    MANGLIK_CANCEL_BENEFIC_ASC_DESC("For Aries/Cancer/Leo/Scorpio ascendants, Mars is benefic", "मेष/कर्कट/सिंह/वृश्चिक लग्नको लागि मंगल शुभ हो"),
    MANGLIK_CANCEL_BENEFIC_ASC_TITLE("Benefic Ascendant", "शुभ लग्न"),
    MANGLIK_CANCEL_EIGHTH_JUPITER_DESC("Mars in 8th in Sagittarius/Pisces reduces effects", "धनु/मीनमा ८औं भावमा मंगलले प्रभाव कम गर्छ"),
    MANGLIK_CANCEL_EIGHTH_JUPITER_TITLE("Mars in 8th Jupiter Sign", "गुरु राशिमा ८औं मंगल"),
    MANGLIK_CANCEL_EXALTED_DESC("Mars in Capricorn cancels Manglik Dosha completely", "मंगल मकरमा मांगलिक दोष पूर्ण रूपमा रद्द गर्छ"),
    MANGLIK_CANCEL_EXALTED_TITLE("Mars Exalted", "मंगल उच्च"),
    MANGLIK_CANCEL_EXPLANATION("Manglik Dosha can be cancelled through various factors: both partners being Manglik (mutual cancellation), Mars in certain houses (1st, 4th, 7th, 8th, 12th from specific references), Mars being in own sign or exalted, age over 28 years (Mars matures), or presence of benefic aspects. These factors indicate that Mars energy is channeled constructively.", "मांगलिक दोष विभिन्न कारकहरूद्वारा रद्द गर्न सकिन्छ: दुवै साझेदार मांगलिक हुनु (पारस्परिक रद्द), मंगल निश्चित भावहरूमा (विशेष सन्दर्भबाट १, ४, ७, ८, १२), मंगल आफ्नै राशि वा उच्चमा हुनु, २८ वर्ष भन्दा माथिको उमेर (मंगल परिपक्व हुन्छ), वा शुभ दृष्टिहरूको उपस्थिति। यी कारकहरूले संकेत गर्दछन् कि मंगल ऊर्जा रचनात्मक रूपमा च्यानल गरिएको छ।"),
    MANGLIK_CANCEL_FOURTH_OWN_DESC("Mars in 4th house in Aries/Scorpio cancels dosha", "मेष/वृश्चिकमा ४औं भावमा मंगलले दोष रद्द गर्छ"),
    MANGLIK_CANCEL_FOURTH_OWN_TITLE("Mars in 4th in Own Sign", "स्वराशिमा ४औं मंगल"),
    MANGLIK_CANCEL_JUPITER_ASPECT_DESC("Jupiter aspecting Mars reduces Manglik effects", "गुरुको मंगलमा दृष्टिले मांगलिक प्रभाव कम गर्छ"),
    MANGLIK_CANCEL_JUPITER_ASPECT_TITLE("Jupiter's Aspect", "गुरुको दृष्टि"),
    MANGLIK_CANCEL_JUPITER_CONJUNCT_DESC("Jupiter conjunct Mars cancels Manglik effects", "गुरुले मंगलसँग युतिले मांगलिक प्रभाव रद्द गर्छ"),
    MANGLIK_CANCEL_JUPITER_CONJUNCT_TITLE("Jupiter Conjunction", "गुरु युति"),
    MANGLIK_CANCEL_OWN_SIGN_DESC("Mars in Aries or Scorpio reduces Manglik effects", "मंगल मेष वा वृश्चिकमा मांगलिक प्रभाव कम गर्छ"),
    MANGLIK_CANCEL_OWN_SIGN_TITLE("Mars in Own Sign", "मंगल स्वराशिमा"),
    MANGLIK_CANCEL_SECOND_MERCURY_DESC("Mars in 2nd house in Gemini/Virgo cancels dosha", "मिथुन/कन्यामा २औं भावमा मंगलले दोष रद्द गर्छ"),
    MANGLIK_CANCEL_SECOND_MERCURY_TITLE("Mars in 2nd in Mercury Sign", "बुध राशिमा २औं मंगल"),
    MANGLIK_CANCEL_SEVENTH_SPECIAL_DESC("Mars in 7th in Cancer/Capricorn reduces effects", "कर्कट/मकरमा ७औं भावमा मंगलले प्रभाव कम गर्छ"),
    MANGLIK_CANCEL_SEVENTH_SPECIAL_TITLE("Mars in 7th Special", "७औं मंगल विशेष"),
    MANGLIK_CANCEL_TWELFTH_VENUS_DESC("Mars in 12th in Taurus/Libra cancels dosha", "वृषभ/तुलामा १२औं भावमा मंगलले दोष रद्द गर्छ"),
    MANGLIK_CANCEL_TWELFTH_VENUS_TITLE("Mars in 12th Venus Sign", "शुक्र राशिमा १२औं मंगल"),
    MANGLIK_CANCEL_VENUS_CONJUNCT_DESC("Venus conjunct Mars significantly reduces effects", "शुक्रले मंगलसँग युतिले प्रभाव उल्लेखनीय रूपमा कम गर्छ"),
    MANGLIK_CANCEL_VENUS_CONJUNCT_TITLE("Venus Conjunction", "शुक्र युति"),
    MANGLIK_COMPAT_AVERAGE(
        "Average compatibility - remedies recommended",
        "औसत मिलान - उपायहरू सिफारिस गरिन्छ"
    ),
    MANGLIK_COMPAT_BELOW_AVERAGE(
        "Below average - significant remedies required",
        "औसतभन्दा कम - महत्वपूर्ण उपायहरू आवश्यक"
    ),
    MANGLIK_COMPAT_EXCELLENT(
        "Excellent Manglik compatibility - no concerns",
        "उत्कृष्ट मांगलिक मिलान - कुनै चिन्ता छैन"
    ),
    MANGLIK_COMPAT_GOOD(
        "Good compatibility - minor remedies may help",
        "राम्रो मिलान - साना उपायहरू सहायक हुन सक्छ"
    ),
    MANGLIK_COMPAT_POOR(
        "Challenging combination - expert consultation advised",
        "कठिन संयोजन - विशेषज्ञ परामर्श सल्लाह दिइन्छ"
    ),
    MANGLIK_DETECTED("detected", "पत्ता लाग्यो"),
    MANGLIK_DOUBLE("Double Manglik (Severe)", "दोहोरो मांगलिक (गम्भीर)"),
    MANGLIK_EFFECTIVE_LEVEL("Effective Level", "प्रभावी स्तर"),
    MANGLIK_FACTOR_FROM_LAGNA("Mars in House {house} from Lagna", "लग्नबाट भाव {house} मा मंगल"),
    MANGLIK_FACTOR_FROM_MOON("Mars in House {house} from Moon", "चन्द्रबाट भाव {house} मा मंगल"),
    MANGLIK_FACTOR_FROM_VENUS("Mars in House {house} from Venus", "शुक्रबाट भाव {house} मा मंगल"),
    MANGLIK_FROM_LAGNA("From Lagna", "लग्नबाट"),
    MANGLIK_FROM_MOON("From Moon", "चन्द्रबाट"),
    MANGLIK_FROM_VENUS("From Venus", "शुक्रबाट"),
    MANGLIK_FULL("Full Manglik", "पूर्ण मांगलिक"),
    MANGLIK_FULL_LEVEL("Full Manglik", "पूर्ण मांगलिक"),
    MANGLIK_GROOM_ONLY("Groom is Manglik while Bride is not - Remedies strongly recommended", "दुलाहा मांगलिक छन् जबकि दुलही छैनन् - उपायहरू दृढतापूर्वक सिफारिस गरिएको"),
    MANGLIK_INTENSITY("intensity", "तीव्रता"),
    MANGLIK_INTERP_CANCELLATION_PRESENT("CANCELLATION FACTORS PRESENT:", "निरसन कारकहरू उपस्थित:"),
    MANGLIK_INTERP_EFFECTIVE_LEVEL("Effective Level After Cancellations:", "निरसन पछिको प्रभावकारी स्तर:"),
    MANGLIK_INTERP_FROM_LAGNA("From Lagna", "लग्नबाट"),
    MANGLIK_INTERP_FROM_MOON("From Moon", "चन्द्रबाट"),
    MANGLIK_INTERP_FROM_REFERENCE("ANALYSIS FROM THREE REFERENCE POINTS:", "तीन सन्दर्भ बिन्दुबाट विश्लेषण:"),
    MANGLIK_INTERP_FROM_VENUS("From Venus", "शुक्रबाट"),
    MANGLIK_INTERP_HEADER("MANGLIK DOSHA ANALYSIS", "मांगलिक दोष विश्लेषण"),
    MANGLIK_INTERP_HOUSE_SUFFIX_ND("nd", "औं"),
    MANGLIK_INTERP_HOUSE_SUFFIX_RD("rd", "औं"),
    MANGLIK_INTERP_HOUSE_SUFFIX_ST("st", "औं"),
    MANGLIK_INTERP_HOUSE_SUFFIX_TH("th", "औं"),
    MANGLIK_INTERP_INITIAL_LEVEL("Initial Level: {level}", "प्रारम्भिक स्तर: {level}"),
    MANGLIK_INTERP_IS_MANGLIK("Manglik", "मांगलिक"),
    MANGLIK_INTERP_MANGLIK_NO("NO", "छैन"),
    MANGLIK_INTERP_MANGLIK_YES("YES", "छ"),
    MANGLIK_INTERP_MARS_HOUSE("Mars in House {house}", "मंगल भाव {house} मा"),
    MANGLIK_INTERP_MARS_IN_HOUSE("Mars in house", "मंगल भावमा"),
    MANGLIK_INTERP_MARS_NOT_PLACED(
        "Mars is not placed in houses 1, 2, 4, 7, 8, or 12 from your Lagna, Moon, or Venus.",
        "मंगल तपाईंको लग्न, चन्द्र वा शुक्रबाट १, २, ४, ७, ८ वा १२ भावमा छैन।"
    ),
    MANGLIK_INTERP_MARS_POSITION("Mars Position: {sign} in House {house}", "मंगल स्थिति: {sign} भाव {house} मा"),
    MANGLIK_INTERP_MARS_RETROGRADE("Note: Mars is retrograde which can intensify or modify its effects.", "नोट: मंगल वक्री छ जसले यसको प्रभावहरू तीव्र वा परिमार्जन गर्न सक्छ।"),
    MANGLIK_INTERP_NO_DOSHA("NO MANGLIK DOSHA", "मांगलिक दोष छैन"),
    MANGLIK_INTERP_NO_DOSHA_DESC(
        "Mars is not placed in houses 1, 2, 4, 7, 8, or 12 from your Lagna, Moon, or Venus. There is no Manglik Dosha in your chart.",
        "मंगल तपाईंको लग्न, चन्द्र वा शुक्रबाट १, २, ४, ७, ८ वा १२औं भावमा छैन। तपाईंको कुण्डलीमा मांगलिक दोष छैन।"
    ),
    MANGLIK_INTERP_NO_DOSHA_TITLE("NO MANGLIK DOSHA", "मांगलिक दोष छैन"),
    MANGLIK_INTERP_THREE_REF("ANALYSIS FROM THREE REFERENCE POINTS:", "तीन सन्दर्भ बिन्दुबाट विश्लेषण:"),
    MANGLIK_INTERP_TITLE("MANGLIK DOSHA ANALYSIS", "मांगलिक दोष विश्लेषण"),
    MANGLIK_MARRIAGE_FULL_1("Full Manglik Dosha present.", "पूर्ण मांगलिक दोष उपस्थित।"),
    MANGLIK_MARRIAGE_FULL_2("Marriage with Manglik partner highly recommended.", "मांगलिक साझेदारसँग विवाह अत्यधिक सिफारिस।"),
    MANGLIK_MARRIAGE_FULL_3("Kumbh Vivah or equivalent ritual essential before marriage.", "विवाह अघि कुम्भ विवाह वा समतुल्य अनुष्ठान अनिवार्य।"),
    MANGLIK_MARRIAGE_FULL_4("Regular Mars propitiation recommended.", "नियमित मंगल शान्ति सिफारिस।"),
    MANGLIK_MARRIAGE_FULL_CANCELLATION(
        "NOTE: Full cancellation present - Manglik Dosha effectively nullified",
        "नोट: पूर्ण निरसन उपस्थित - मांगलिक दोष प्रभावकारी रूपमा शून्य"
    ),
    MANGLIK_MARRIAGE_FULL_CANCEL_NOTE("NOTE: Full cancellation present - Manglik Dosha effectively nullified.", "नोट: पूर्ण निरसन उपस्थित - मांगलिक दोष प्रभावकारी रूपमा शून्य।"),
    MANGLIK_MARRIAGE_FULL_KUMBH_ESSENTIAL(
        "Kumbh Vivah or equivalent ritual essential before marriage",
        "विवाह अघि कुम्भ विवाह वा समान अनुष्ठान आवश्यक"
    ),
    MANGLIK_MARRIAGE_FULL_PRESENT(
        "Full Manglik Dosha present",
        "पूर्ण मांगलिक दोष उपस्थित"
    ),
    MANGLIK_MARRIAGE_FULL_PROPITIATION(
        "Regular Mars propitiation recommended",
        "नियमित मंगल शान्ति सिफारिस गरिन्छ"
    ),
    MANGLIK_MARRIAGE_FULL_RECOMMENDED(
        "Marriage with Manglik partner highly recommended",
        "मांगलिक साझेदारसँग विवाह अत्यधिक सिफारिस"
    ),
    MANGLIK_MARRIAGE_HEADER("MARRIAGE CONSIDERATIONS", "विवाह विचार"),
    MANGLIK_MARRIAGE_MILD_1("Mild Manglik effects - marriage with non-Manglik is possible.", "हल्का मांगलिक प्रभाव - गैर-मांगलिकसँग विवाह सम्भव।"),
    MANGLIK_MARRIAGE_MILD_2("Simple remedies recommended before marriage.", "विवाह अघि सरल उपायहरू सिफारिस।"),
    MANGLIK_MARRIAGE_MILD_3("Matching with another Manglik is beneficial but not essential.", "अर्को मांगलिकसँग मिलान लाभदायक तर अनिवार्य होइन।"),
    MANGLIK_MARRIAGE_MILD_EFFECTS(
        "Mild Manglik effects - marriage with non-Manglik is possible",
        "हल्का मांगलिक प्रभाव - गैर-मांगलिकसँग विवाह सम्भव छ"
    ),
    MANGLIK_MARRIAGE_MILD_MATCHING(
        "Matching with another Manglik is beneficial but not essential",
        "अर्को मांगलिकसँग मिलान लाभदायक तर अनिवार्य होइन"
    ),
    MANGLIK_MARRIAGE_MILD_REMEDIES(
        "Simple remedies recommended before marriage",
        "विवाह अघि सरल उपायहरू सिफारिस गरिन्छ"
    ),
    MANGLIK_MARRIAGE_NONE_1("No restrictions based on Manglik Dosha.", "मांगलिक दोषमा आधारित कुनै प्रतिबन्ध छैन।"),
    MANGLIK_MARRIAGE_NONE_2("Compatible with both Manglik and non-Manglik partners.", "मांगलिक र गैर-मांगलिक दुवै साझेदारसँग मिल्दो।"),
    MANGLIK_MARRIAGE_NONE_COMPATIBLE(
        "Compatible with both Manglik and non-Manglik partners",
        "मांगलिक र गैर-मांगलिक दुवै साझेदारसँग मिल्दो"
    ),
    MANGLIK_MARRIAGE_NONE_NO_RESTRICTION(
        "No restrictions based on Manglik Dosha",
        "मांगलिक दोषको आधारमा कुनै प्रतिबन्ध छैन"
    ),
    MANGLIK_MARRIAGE_PARTIAL_1("Partial Manglik - remedies strongly recommended.", "आंशिक मांगलिक - उपायहरू जोडदार सिफारिस।"),
    MANGLIK_MARRIAGE_PARTIAL_2("Marriage with Manglik partner is preferable.", "मांगलिक साझेदारसँग विवाह उपयुक्त।"),
    MANGLIK_MARRIAGE_PARTIAL_3("If marrying non-Manglik, perform Kumbh Vivah.", "गैर-मांगलिकसँग विवाह गर्दा कुम्भ विवाह गर्नुहोस्।"),
    MANGLIK_MARRIAGE_PARTIAL_KUMBH(
        "If marrying non-Manglik, perform Kumbh Vivah",
        "गैर-मांगलिकसँग विवाह गर्दा कुम्भ विवाह गर्नुहोस्"
    ),
    MANGLIK_MARRIAGE_PARTIAL_PREFERABLE(
        "Marriage with Manglik partner is preferable",
        "मांगलिक साझेदारसँग विवाह उपयुक्त"
    ),
    MANGLIK_MARRIAGE_PARTIAL_REMEDIES(
        "Partial Manglik - remedies strongly recommended",
        "आंशिक मांगलिक - उपायहरू जोडदार सिफारिस"
    ),
    MANGLIK_MARRIAGE_SEVERE_1("Severe Manglik Dosha - careful consideration required.", "गम्भीर मांगलिक दोष - सावधानीपूर्ण विचार आवश्यक।"),
    MANGLIK_MARRIAGE_SEVERE_2("Only marry Manglik partner with similar intensity.", "समान तीव्रता भएको मांगलिक साझेदारसँग मात्र विवाह।"),
    MANGLIK_MARRIAGE_SEVERE_3("Multiple remedies required before and after marriage.", "विवाह अघि र पछि बहु उपायहरू आवश्यक।"),
    MANGLIK_MARRIAGE_SEVERE_4("Consider delaying marriage until after age 28 (Mars maturity).", "मंगल परिपक्वता (२८ वर्ष) सम्म विवाह ढिला गर्ने विचार गर्नुहोस्।"),
    MANGLIK_MARRIAGE_SEVERE_CONSIDERATION(
        "Severe Manglik Dosha - careful consideration required",
        "गम्भीर मांगलिक दोष - सावधानीपूर्ण विचार आवश्यक"
    ),
    MANGLIK_MARRIAGE_SEVERE_DELAY(
        "Consider delaying marriage until after age 28 (Mars maturity)",
        "मंगल परिपक्वता (२८ वर्ष) सम्म विवाह ढिला गर्ने विचार गर्नुहोस्"
    ),
    MANGLIK_MARRIAGE_SEVERE_MULTIPLE_REMEDIES(
        "Multiple remedies required before and after marriage",
        "विवाह अघि र पछि धेरै उपायहरू आवश्यक"
    ),
    MANGLIK_MARRIAGE_SEVERE_ONLY_MANGLIK(
        "Only marry Manglik partner with similar intensity",
        "समान तीव्रता भएको मांगलिक साझेदारसँग मात्र विवाह गर्नुहोस्"
    ),
    MANGLIK_MARRIAGE_TITLE("MARRIAGE CONSIDERATIONS", "विवाह सम्बन्धी विचारहरू"),
    MANGLIK_MARS_IN("Mars in", "मंगल"),
    MANGLIK_MILD("Mild Manglik", "हल्का मांगलिक"),
    MANGLIK_MINOR_IMBALANCE("Minor Manglik imbalance - Manageable with remedies", "सानो मांगलिक असन्तुलन - उपायहरूद्वारा व्यवस्थापनयोग्य"),
    MANGLIK_NONE("No Manglik Dosha", "मांगलिक दोष छैन"),
    MANGLIK_NONE_LEVEL("No Manglik Dosha", "मांगलिक दोष छैन"),
    MANGLIK_NO_DOSHA_DESC("No Manglik Dosha present.", "मांगलिक दोष छैन।"),
    MANGLIK_PARTIAL("Partial Manglik", "आंशिक मांगलिक"),
    MANGLIK_PARTIAL_LEVEL("Partial Manglik", "आंशिक मांगलिक"),
    MANGLIK_QUICK_BOTH("Both Manglik", "दुवै मांगलिक"),
    MANGLIK_QUICK_BRIDE("Bride Only", "दुलही मात्र"),
    MANGLIK_QUICK_GROOM("Groom Only", "दुलाहा मात्र"),
    MANGLIK_QUICK_NONE("No Dosha", "दोष छैन"),
    MANGLIK_REF_LAGNA("Lagna", "लग्न"),
    MANGLIK_REF_MOON("Moon", "चन्द्र"),
    MANGLIK_REF_VENUS("Venus", "शुक्र"),
    MANGLIK_SEVERE("Severe Manglik", "गम्भीर मांगलिक"),
    MANGLIK_SIGNIFICANT_IMBALANCE("Significant Manglik imbalance - Careful consideration and remedies essential", "महत्त्वपूर्ण मांगलिक असन्तुलन - सावधानीपूर्ण विचार र उपायहरू आवश्यक"),
    MANGLIK_SUBTITLE("Mars Placement Analysis for Marriage", "विवाहको लागि मंगल स्थिति विश्लेषण"),
    MANGLIK_SUMMARY_ABSENT("No Manglik Dosha in this chart", "यस कुण्डलीमा मांगलिक दोष छैन"),
    MANGLIK_SUMMARY_PRESENT("{level} present with {intensity}% intensity", "{level} {intensity}% तीव्रताका साथ उपस्थित"),
    MANGLIK_TITLE("Manglik Dosha Analysis", "मांगलिक दोष विश्लेषण"),
    MATCH_ABSENT("Absent", "अनुपस्थित"),
    MATCH_AI_ANALYZING("Analyzing compatibility...", "अनुकूलता विश्लेषण गर्दै..."),
    MATCH_AI_INSIGHT("AI Insight", "एआई अन्तर्दृष्टि"),
    MATCH_AI_INSIGHT_DESC("Get a deeper, personalized interpretation of your compatibility analysis using AI. The AI will analyze the Guna scores and Doshas to provide additional relationship guidance.", "एआई प्रयोग गरेर आफ्नो अनुकूलता विश्लेषणको गहिरो, व्यक्तिगत व्याख्या प्राप्त गर्नुहोस्। एआईले थप सम्बन्ध मार्गदर्शन प्रदान गर्न गुण स्कोर र दोषहरूको विश्लेषण गर्नेछ।"),
    MATCH_AI_INSIGHT_SUBTITLE("Powered by Stormy", "Stormy द्वारा संचालित"),
    MATCH_ANALYZING_COMPATIBILITY("Analyzing compatibility...", "अनुकूलता विश्लेषण गर्दै..."),
    MATCH_ASHTAKOOTA("Ashtakoota Points", "अष्टकूट अंकहरू"),
    MATCH_AVERAGE("Average", "औसत"),
    MATCH_BELOW_AVERAGE("Below Average", "औसतमुनि"),
    MATCH_BENEFICIAL("Beneficial", "लाभदायक"),
    MATCH_BHAKOOT("Bhakoot", "भकूट"),
    MATCH_BHAKOOT_DOSHA("Bhakoot Dosha", "भकूट दोष"),
    MATCH_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    MATCH_BIRTH_STAR("Birth Star", "जन्म नक्षत्र"),
    MATCH_BRIDE("Bride", "वधू"),
    MATCH_BRIDE_RASHI("Bride Rashi", "वधू राशि"),
    MATCH_CALCULATE("Calculate Match", "मिलान गणना गर्नुहोस्"),
    MATCH_CALCULATING("Calculating compatibility...", "अनुकूलता गणना गर्दै..."),
    MATCH_CALCULATING_DOSHAS("Calculating doshas...", "दोषहरू गणना गर्दै..."),
    MATCH_CALCULATION_ERROR("Calculation Error", "गणना त्रुटि"),
    MATCH_CANCELLATION_FACTORS("Cancellation Factors", "रद्द गर्ने कारकहरू"),
    MATCH_CHARTS_AVAILABLE("%d charts available", "%d कुण्डली उपलब्ध"),
    MATCH_CLEAR_SELECTION("Clear Selection", "छनौट हटाउनुहोस्"),
    MATCH_COMPATIBILITY("Compatibility", "अनुकूलता"),
    MATCH_COMPATIBLE("Compatible", "अनुकूल"),
    MATCH_CONFLICT("Conflict", "द्वन्द्व"),
    MATCH_CONNECTED("Connected", "जोडिएको"),
    MATCH_CONTRIBUTING_FACTORS("Contributing Factors", "योगदान गर्ने कारकहरू"),
    MATCH_COPY_FULL_DESC("Complete compatibility analysis", "पूर्ण अनुकूलता विश्लेषण"),
    MATCH_COPY_FULL_REPORT("Copy Full Report", "पूर्ण रिपोर्ट कपी गर्नुहोस्"),
    MATCH_COPY_REPORT("Copy Report", "रिपोर्ट कपी गर्नुहोस्"),
    MATCH_COPY_SCORES("Copy Scores", "अंकहरू कपी गर्नुहोस्"),
    MATCH_COPY_SCORES_DESC("Guna scores only", "गुण अंकहरू मात्र"),
    MATCH_COPY_SUMMARY("Copy Summary", "सारांश कपी गर्नुहोस्"),
    MATCH_COPY_SUMMARY_DESC("Brief compatibility overview", "संक्षिप्त अनुकूलता अवलोकन"),
    MATCH_CREATE_CHARTS("Create Charts", "कुण्डली बनाउनुहोस्"),
    MATCH_CREATE_CHARTS_FIRST("Create birth charts first to use matchmaking", "मिलान प्रयोग गर्न पहिले जन्म कुण्डली बनाउनुहोस्"),
    MATCH_DOSHAS("Doshas", "दोषहरू"),
    MATCH_DOSHA_PRESENT("Dosha Present", "दोष उपस्थित"),
    MATCH_EXCELLENT("Excellent", "उत्कृष्ट"),
    MATCH_FAVORABLE("Favorable", "अनुकूल"),
    MATCH_FINANCIAL_HARMONY("Financial Harmony", "आर्थिक सामञ्जस्य"),
    MATCH_GANA("Gana", "गण"),
    MATCH_GENERATE_AI_INSIGHT("Generate AI Insight", "एआई अन्तर्दृष्टि उत्पन्न गर्नुहोस्"),
    MATCH_GOOD("Good", "राम्रो"),
    MATCH_GROOM("Groom", "वर"),
    MATCH_GROOM_RASHI("Groom Rashi", "वर राशि"),
    MATCH_GUNAS("Gunas", "गुणहरू"),
    MATCH_GUNA_DISTRIBUTION("Guna Distribution", "गुण वितरण"),
    MATCH_HEALTH_PROGENY("Health & Progeny", "स्वास्थ्य र सन्तान"),
    MATCH_KEY_CONSIDERATIONS("Key Considerations", "मुख्य विचारहरू"),
    MATCH_LONGEVITY("Longevity", "दीर्घायु"),
    MATCH_MAHENDRA("Mahendra", "महेन्द्र"),
    MATCH_MANGLIK("Manglik", "मांगलिक"),
    MATCH_MANGLIK_DOSHA_ANALYSIS("Manglik Dosha Analysis", "मांगलिक दोष विश्लेषण"),
    MATCH_MARS_IN_HOUSE("Mars in House %d", "भाव %d मा मंगल"),
    MATCH_MARS_PLACEMENT("Mars Placement", "मंगल स्थिति"),
    MATCH_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
    MATCH_NADI("Nadi", "नाडी"),
    MATCH_NADI_DOSHA("Nadi Dosha", "नाडी दोष"),
    MATCH_NADI_WARNING("Same Nadi can indicate health and progeny concerns", "एउटै नाडीले स्वास्थ्य र सन्तान सम्बन्धी चिन्ता संकेत गर्न सक्छ"),
    MATCH_NAKSHATRA("Nakshatra", "नक्षत्र"),
    MATCH_NAKSHATRAS("Nakshatras", "नक्षत्रहरू"),
    MATCH_NAKSHATRA_COMPATIBILITY("Nakshatra Compatibility", "नक्षत्र अनुकूलता"),
    MATCH_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
    MATCH_NEEDS_ATTENTION("Needs Attention", "ध्यान आवश्यक"),
    MATCH_NONE("None", "कुनै पनि छैन"),
    MATCH_NOT_CONNECTED("Not Connected", "जोडिएको छैन"),
    MATCH_NO_CHARTS("No Charts", "कुनै कुण्डली छैन"),
    MATCH_NO_CHARTS_AVAILABLE("No charts available", "कुनै कुण्डली उपलब्ध छैन"),
    MATCH_NO_PROFILES("No profiles available", "कुनै प्रोफाइल उपलब्ध छैन"),
    MATCH_OBSTRUCTION_CHECK("Obstruction Check", "बाधा जाँच"),
    MATCH_OUT_OF("out of", "मध्ये"),
    MATCH_OVERVIEW("Overview", "अवलोकन"),
    MATCH_PADA("Pada", "पद"),
    MATCH_PADA_NUMBER("Pada %d", "पद %d"),
    MATCH_PERSON_1("Person 1", "व्यक्ति १"),
    MATCH_PERSON_2("Person 2", "व्यक्ति २"),
    MATCH_PREPARING_ANALYSIS("Preparing analysis...", "विश्लेषण तयार गर्दै..."),
    MATCH_PRESENT("Present", "उपस्थित"),
    MATCH_PROFILE_COMPARISON("Profile Comparison", "प्रोफाइल तुलना"),
    MATCH_PROSPERITY_FACTORS("Prosperity Factors", "समृद्धि कारकहरू"),
    MATCH_RAJJU_DESCRIPTION("Rajju indicates the body parts and their compatibility in marriage.", "रज्जुले शरीरका अंगहरू र विवाहमा तिनीहरूको अनुकूलता संकेत गर्दछ।"),
    MATCH_RAJJU_MATCHING("Rajju Matching", "रज्जु मिलान"),
    MATCH_REMEDIES("Remedies", "उपायहरू"),
    MATCH_REMEDIES_DISCLAIMER("Remedies should be performed under guidance of a qualified astrologer.", "उपायहरू योग्य ज्योतिषीको मार्गदर्शनमा गर्नुपर्छ।"),
    MATCH_REPORT_TITLE("Relationship Compatibility Report", "सम्बन्ध अनुकूलता रिपोर्ट"),
    MATCH_SELECTED("Selected", "छानिएको"),
    MATCH_SELECT_BOTH("Please select both profiles", "कृपया दुवै प्रोफाइल छान्नुहोस्"),
    MATCH_SELECT_BRIDE("Select Bride", "वधू छान्नुहोस्"),
    MATCH_SELECT_BRIDE_PROFILE("Select bride profile", "वधू प्रोफाइल छान्नुहोस्"),
    MATCH_SELECT_GROOM("Select Groom", "वर छान्नुहोस्"),
    MATCH_SELECT_GROOM_PROFILE("Select groom profile", "वर प्रोफाइल छान्नुहोस्"),
    MATCH_SELECT_PROFILES("Select Profiles", "प्रोफाइलहरू छान्नुहोस्"),
    MATCH_SELECT_TAP_CARDS("Select by tapping cards", "कार्डहरू ट्याप गरेर छान्नुहोस्"),
    MATCH_SHARE_AS_IMAGE("Share as Image", "छविको रूपमा साझा गर्नुहोस्"),
    MATCH_SHARE_AS_TEXT("Share as Text", "पाठको रूपमा साझा गर्नुहोस्"),
    MATCH_SHARE_REPORT("Share Report", "रिपोर्ट साझा गर्नुहोस्"),
    MATCH_STREE_DEERGHA("Stree Deergha", "स्त्री दीर्घ"),
    MATCH_STREE_DEERGHA_LABEL("Stree Deergha", "स्त्री दीर्घ"),
    MATCH_SUGGESTED_REMEDIES("Suggested Remedies", "सुझाव गरिएका उपायहरू"),
    MATCH_SWAP_PROFILES("Swap Profiles", "प्रोफाइलहरू स्वाप गर्नुहोस्"),
    MATCH_TAP_BRIDE_CARD("Tap bride card to select", "छान्न वधू कार्ड ट्याप गर्नुहोस्"),
    MATCH_TAP_GROOM_CARD("Tap groom card to select", "छान्न वर कार्ड ट्याप गर्नुहोस्"),
    MATCH_TAP_TO_SELECT("Tap to select", "छान्न ट्याप गर्नुहोस्"),
    MATCH_TITLE("Kundli Milan", "कुण्डली मिलान"),
    MATCH_TOTAL_POINTS("Total Points", "कुल अंकहरू"),
    MATCH_TOTAL_SCORE("Total Score", "कुल अंक"),
    MATCH_VEDHA_ANALYSIS("Vedha Analysis", "वेध विश्लेषण"),
    MATCH_VEDHA_DESCRIPTION("Vedha indicates mutual affliction between nakshatras.", "वेधले नक्षत्रहरू बीचको पारस्परिक पीडा संकेत गर्दछ।"),
    MATCH_VEDIC_RECOMMENDATIONS("Vedic Recommendations", "वैदिक सिफारिसहरू"),
    MATCH_VS("vs", "विरुद्ध"),
    MATCH_YONI("Yoni", "योनि"),
    NADI_ADI("Adi Nadi", "आदि नाडी"),
    NADI_ADI_DESC("Beginning - Wind element, controls movement and nervous system", "आदि - वायु तत्व, गति र स्नायु प्रणाली नियन्त्रण गर्छ"),
    NADI_ANTYA("Antya Nadi", "अन्त्य नाडी"),
    NADI_ANTYA_DESC("End - Water element, controls structure and lubrication", "अन्त्य - जल तत्व, संरचना र स्नेहन नियन्त्रण गर्छ"),
    NADI_CANCEL_DIFF_PADA("Same Nakshatra and Rashi but different Padas ({pada1} vs {pada2}) - Partial Cancellation", "उही नक्षत्र र राशि तर फरक पाद ({pada1} बनाम {pada2}) - आंशिक रद्द"),
    NADI_CANCEL_EXPLANATION("Nadi Dosha can be cancelled in several specific scenarios according to classical Vedic texts. These cancellations are based on deeper astrological principles that override the superficial Nadi match.", "नाडी दोष शास्त्रीय वैदिक ग्रन्थहरू अनुसार धेरै विशिष्ट परिस्थितिहरूमा रद्द गर्न सकिन्छ। यी रद्दहरू गहन ज्योतिषीय सिद्धान्तहरूमा आधारित छन् जसले सतही नाडी मिलानलाई ओभरराइड गर्दछ।"),
    NADI_CANCEL_LORDS_FRIENDS("Moon sign lords ({lord1} & {lord2}) are mutual friends - Partial Cancellation", "चन्द्र राशि स्वामी ({lord1} र {lord2}) पारस्परिक मित्र हुन् - आंशिक रद्द"),
    NADI_CANCEL_SAME_NAK_DIFF_RASHI("Same Nakshatra ({nakshatra}) but different Rashis - Full Cancellation", "उही नक्षत्र ({nakshatra}) तर फरक राशि - पूर्ण रद्द"),
    NADI_CANCEL_SAME_NAK_LORD("Both Nakshatras ruled by {lord} - Partial Cancellation", "दुवै नक्षत्र {lord} द्वारा शासित - आंशिक रद्द"),
    NADI_CANCEL_SAME_RASHI_DIFF_NAK("Same Rashi ({rashi}) but different Nakshatras - Full Cancellation", "उही राशि ({rashi}) तर फरक नक्षत्र - पूर्ण रद्द"),
    NADI_CANCEL_SPECIAL_PAIR("Special Nakshatra pair ({nak1}-{nak2}) cancels Nadi dosha per classical texts", "विशेष नक्षत्र जोडी ({nak1}-{nak2}) ले शास्त्रीय ग्रन्थ अनुसार नाडी दोष रद्द गर्छ"),
    NADI_CAREER_TIMING("Career Event Timing", "क्यारियर घटना समय"),
    NADI_CONFIDENCE("Rectification Confidence", "शुद्धिकरण विश्वास"),
    NADI_CURRENT_TIME("Current Birth Time", "वर्तमान जन्म समय"),
    NADI_DASHA_TIMING("Dasha-Antardasha Fine-Tuning", "दशा-अन्तर्दशा सूक्ष्म समायोजन"),
    NADI_DEGREE("Nadi Degree", "नाडी डिग्री"),
    NADI_DESC("High-precision divisional analysis for exact event timing and birth time rectification", "सटीक घटना समय र जन्म समय शुद्धिकरणको लागि उच्च-सटीक विभाजन विश्लेषण"),
    NADI_DIFFERENT("Different Nadis ({nadi1} & {nadi2}) - excellent health and progeny compatibility.", "फरक नाडी ({nadi1} र {nadi2}) - उत्कृष्ट स्वास्थ्य र सन्तान अनुकूलता।"),
    NADI_DOSHA_CANCELLED("Same Nadi but CANCELLED:", "उही नाडी तर रद्द:"),
    NADI_DOSHA_PRESENT("NADI DOSHA PRESENT: Same Nadi ({nadi}) without cancellation. Serious concern affecting health and progeny.", "नाडी दोष उपस्थित: रद्द बिना उही नाडी ({nadi})। स्वास्थ्य र सन्तानलाई असर गर्ने गम्भीर चिन्ता।"),
    NADI_ENTER_EVENT("Enter Known Life Events", "ज्ञात जीवन घटनाहरू प्रविष्ट गर्नुहोस्"),
    NADI_EVENTS_VERIFIED("Events Verified", "प्रमाणित घटनाहरू"),
    NADI_EVENT_WINDOW("Event Window", "घटना समय सीमा"),
    NADI_IMPORTANCE("Nadi is the MOST IMPORTANT guna (8 points) indicating genetic compatibility, health, and progeny. Same Nadi can cause serious health and conception issues.", "नाडी सबैभन्दा महत्त्वपूर्ण गुण (८ अंक) हो जसले आनुवंशिक अनुकूलता, स्वास्थ्य र सन्तान संकेत गर्दछ। उही नाडीले गम्भीर स्वास्थ्य र गर्भधारण समस्या ल्याउन सक्छ।"),
    NADI_INFO_DESC("Nadi Amsha (D-150) is the finest divisional chart, dividing each sign into 150 parts of 12 arc-minutes each. This level of precision allows for exact event timing and birth time rectification within minutes.", "नाडी अंश (D-150) सबैभन्दा सूक्ष्म विभाजन चार्ट हो, जसले प्रत्येक राशिलाई १२ आर्क-मिनेटको १५० भागमा विभाजन गर्छ। यो सटीकताको स्तरले मिनेटभित्र सटीक घटना समय र जन्म समय शुद्धिकरणको अनुमति दिन्छ।"),
    NADI_INFO_TITLE("About Nadi Amsha", "नाडी अंशको बारेमा"),
    NADI_LORD("Nadi Lord", "नाडी स्वामी"),
    NADI_MADHYA("Madhya Nadi", "मध्य नाडी"),
    NADI_MADHYA_DESC("Middle - Fire element, controls digestion and metabolism", "मध्य - अग्नि तत्व, पाचन र चयापचय नियन्त्रण गर्छ"),
    NADI_MALE_FEMALE_BALANCE("Male-Female Energy Balance", "पुरुष-स्त्री ऊर्जा सन्तुलन"),
    NADI_MARRIAGE_TIMING("Marriage Event Timing", "विवाह घटना समय"),
    NADI_NUMBER("Nadi Number (1-150)", "नाडी नम्बर (१-१५०)"),
    NADI_PAIR("Nadi Pair", "नाडी जोडी"),
    NADI_PLANET_POSITION("Planet Nadi Position", "ग्रह नाडी स्थिति"),
    NADI_PRECISE_TIMING("Precise Event Timing", "सटीक घटना समय"),
    NADI_RECTIFICATION_TITLE("Birth Time Rectification", "जन्म समय शुद्धिकरण"),
    NADI_REMEDY_LOW("Remedy: This is critical - consult qualified astrologer immediately. Perform Maha Mrityunjaya Jaap (108 times daily for 40 days). Donate grains, gold, or cow on auspicious day. Worship Lord Shiva and Goddess Parvati together on Mondays. Consider Kumbh Vivah if dosha is severe.", "उपाय: यो महत्त्वपूर्ण छ - तुरुन्त योग्य ज्योतिषीसँग परामर्श गर्नुहोस्। महा मृत्युञ्जय जाप गर्नुहोस् (४० दिन दैनिक १०८ पटक)। शुभ दिनमा अन्न, सुन वा गाई दान गर्नुहोस्। सोमबारमा भगवान शिव र देवी पार्वतीको सँगै पूजा गर्नुहोस्। दोष गम्भीर भएमा कुम्भ विवाह विचार गर्नुहोस्।"),
    NADI_SUBTITLE("150th Division Precision Timing", "१५०औं विभाजन सटीक समय"),
    NADI_SUB_LORD("Nadi Sub-Lord", "नाडी उप-स्वामी"),
    NADI_SUGGESTED_TIME("Suggested Corrected Time", "सुझाव गरिएको शुद्ध समय"),
    NADI_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    NADI_TAB_POSITIONS("Positions", "स्थितिहरू"),
    NADI_TAB_RECTIFICATION("Rectification", "शुद्धिकरण"),
    NADI_TAB_TIMING("Timing", "समय"),
    NADI_TITLE("Nadi Amsha (D-150)", "नाडी अंश (D-150)"),
    NADI_TRANSIT_TIMING("Transit Timing Enhancement", "गोचर समय वृद्धि"),
    NADI_TYPES_EXPLAINED("Adi (Vata): Wind element, nervous system, movement. Madhya (Pitta): Fire element, digestion, metabolism. Antya (Kapha): Water element, structure, lubrication. Same Nadi = physiological incompatibility.", "आदि (वात): वायु तत्व, स्नायु प्रणाली, गति। मध्य (पित्त): अग्नि तत्व, पाचन, चयापचय। अन्त्य (कफ): जल तत्व, संरचना, स्नेहन। उही नाडी = शारीरिक असंगतता।"),
    NADI_UNABLE_CALCULATE("Unable to calculate Nadi Amsha", "नाडी अंश गणना गर्न सकिएन"),
    NADI_VEDIC_REF("Vedic Reference: Brighu Nadi, Dhruva Nadi, South Indian Nadi traditions", "वैदिक सन्दर्भ: भृगु नाडी, ध्रुव नाडी, दक्षिण भारतीय नाडी परम्पराहरू"),
    NADI_ZERO_EXPLANATION("Zero points indicates Same Nadi without cancellation - this is the most serious dosha in matchmaking. Immediate astrological consultation and extensive remedies are mandatory.", "शून्य अंकले रद्द बिना उही नाडी संकेत गर्दछ - यो मिलानमा सबैभन्दा गम्भीर दोष हो। तत्काल ज्योतिषीय परामर्श र व्यापक उपायहरू अनिवार्य छन्।"),
    RAJJU_ASCENDING("Aarohana (Ascending)", "आरोहण"),
    RAJJU_COMPATIBLE("Different Rajju types - compatible, no concerns related to body part compatibility", "फरक रज्जु प्रकार - अनुकूल, शरीर भाग अनुकूलतासम्बन्धी कुनै चिन्ता छैन"),
    RAJJU_DESCENDING("Avarohana (Descending)", "अवरोहण"),
    RAJJU_KANTHA("Kantha Rajju", "कण्ठ रज्जु"),
    RAJJU_KANTHA_BODY("Neck", "घाँटी"),
    RAJJU_KANTHA_WARNING("May cause health issues to both", "दुवैलाई स्वास्थ्य समस्या हुन सक्छ"),
    RAJJU_KATI("Kati Rajju", "कटि रज्जु"),
    RAJJU_KATI_BODY("Waist", "कम्मर"),
    RAJJU_KATI_WARNING("May cause financial difficulties", "आर्थिक कठिनाइहरू हुन सक्छ"),
    RAJJU_NABHI("Nabhi Rajju", "नाभि रज्जु"),
    RAJJU_NABHI_BODY("Navel", "नाभि"),
    RAJJU_NABHI_WARNING("May affect children", "सन्तानमा असर पर्न सक्छ"),
    RAJJU_PADA("Pada Rajju", "पाद रज्जु"),
    RAJJU_PADA_BODY("Feet", "पाउ"),
    RAJJU_PADA_WARNING("May cause wandering tendencies", "भ्रमण प्रवृत्ति हुन सक्छ"),
    RAJJU_SAME_DIFF_ARUDHA("Same {rajju} but different Arudha ({arudha1} vs {arudha2}) - partially compatible, reduced concern", "उही {rajju} तर फरक अरुढा ({arudha1} बनाम {arudha2}) - आंशिक अनुकूल, कम चिन्ता"),
    RAJJU_SAME_SAME_ARUDHA("Same {rajju} ({body}) and same {arudha} - Rajju Dosha present. {warning}", "उही {rajju} ({body}) र उही {arudha} - रज्जु दोष उपस्थित। {warning}"),
    RAJJU_SIRO("Siro Rajju", "शिरो रज्जु"),
    RAJJU_SIRO_BODY("Head", "शिर"),
    RAJJU_SIRO_WARNING("Most serious - affects longevity of spouse", "सबैभन्दा गम्भीर - जीवनसाथीको आयुमा असर पार्छ"),
    VARNA_BRAHMIN("Brahmin", "ब्राह्मण"),
    VARNA_BRAHMIN_NATURE("Brahmin (Fire signs): Knowledge seekers, intellectual, teaching orientation, spiritual inclinations", "ब्राह्मण (अग्नि राशि): ज्ञान खोज्ने, बौद्धिक, शिक्षण अभिमुखीकरण, आध्यात्मिक झुकाव"),
    VARNA_COMPATIBLE("Compatible: Groom's Varna ({groom}) is equal to or higher than Bride's ({bride}). This indicates spiritual harmony.", "अनुकूल: दुलाहाको वर्ण ({groom}) दुलहीको ({bride}) बराबर वा माथि छ। यसले आध्यात्मिक सामञ्जस्य संकेत गर्छ।"),
    VARNA_DESC("Spiritual compatibility and ego harmony", "आध्यात्मिक अनुकूलता र अहंकार सामञ्जस्य"),
    VARNA_DETAILED_COMPATIBLE("This creates excellent spiritual harmony with natural respect flowing from bride to groom. Partners will have compatible life philosophies, values, and approaches to dharma. The groom's natural leadership in spiritual matters will be appreciated.", "यसले दुलहीबाट दुलाहातिर प्राकृतिक सम्मान प्रवाहसहित उत्कृष्ट आध्यात्मिक सामञ्जस्य सिर्जना गर्दछ। साझेदारहरूको जीवन दर्शन, मूल्यहरू र धर्मप्रति दृष्टिकोण मिल्नेछ। आध्यात्मिक विषयहरूमा दुलाहाको प्राकृतिक नेतृत्व सराहना गरिनेछ।"),
    VARNA_DETAILED_INCOMPATIBLE("This may create ego conflicts and power struggles. The bride may feel she has to compromise her values or suppress her intellect. Both partners need conscious effort to respect each other's perspectives and maintain balance.", "यसले अहंकार द्वन्द्व र शक्ति संघर्ष सिर्जना गर्न सक्छ। दुलहीले आफ्ना मूल्यहरूमा सम्झौता गर्नु परोस् वा आफ्नो बुद्धि दमन गर्नुपर्ला जस्तो महसुस गर्न सक्छिन्। दुवै साझेदारहरूले एकअर्काको दृष्टिकोणलाई सम्मान गर्न र सन्तुलन कायम राख्न सचेत प्रयास चाहिन्छ।"),
    VARNA_IMPORTANCE("Varna represents the spiritual evolution and work nature of the couple. It measures ego compatibility and mutual respect in the relationship.", "वर्णले जोडीको आध्यात्मिक विकास र कार्य प्रकृति प्रतिनिधित्व गर्दछ। यसले सम्बन्धमा अहंकार अनुकूलता र पारस्परिक सम्मान मापन गर्दछ।"),
    VARNA_INCOMPATIBLE("Mismatch: Bride's Varna ({bride}) is higher than Groom's ({groom}). May cause ego-related issues.", "बेमेल: दुलहीको वर्ण ({bride}) दुलाहाको ({groom}) भन्दा माथि छ। अहंकार-सम्बन्धित समस्या हुन सक्छ।"),
    VARNA_KSHATRIYA("Kshatriya", "क्षत्रिय"),
    VARNA_KSHATRIYA_NATURE("Kshatriya (Earth signs): Leaders, protectors, administrative skills, power-oriented", "क्षत्रिय (पृथ्वी राशि): नेता, रक्षक, प्रशासनिक कौशल, शक्ति-उन्मुख"),
    VARNA_SHUDRA("Shudra", "शूद्र"),
    VARNA_SHUDRA_NATURE("Shudra (Water signs): Service orientation, emotional depth, nurturing, supportive", "शूद्र (जल राशि): सेवा अभिमुखीकरण, भावनात्मक गहिराई, पालन-पोषण, सहयोगी"),
    VARNA_VAISHYA("Vaishya", "वैश्य"),
    VARNA_VAISHYA_NATURE("Vaishya (Air signs): Business minded, commerce, communication, wealth creation", "वैश्य (वायु राशि): व्यापार मानसिकता, वाणिज्य, सञ्चार, धन सिर्जना"),
    VASHYA_AQUATIC("Aquatic", "जलचर"),
    VASHYA_CHATUSHPADA("Quadruped", "चतुष्पद"),
    VASHYA_DESC("Mutual attraction and influence", "पारस्परिक आकर्षण र प्रभाव"),
    VASHYA_EXCELLENT("Excellent mutual attraction and influence. Both partners can positively influence each other.", "उत्कृष्ट पारस्परिक आकर्षण र प्रभाव। दुवै साझेदारहरू एकअर्कालाई सकारात्मक रूपमा प्रभाव पार्न सक्छन्।"),
    VASHYA_GOOD("Good compatibility with moderate mutual influence.", "मध्यम पारस्परिक प्रभावसहित राम्रो अनुकूलता।"),
    VASHYA_HUMAN("Human", "मनुष्य"),
    VASHYA_IMPORTANCE("Vashya indicates natural attraction, influence capacity, and control dynamics. It shows who holds sway in decision-making and emotional matters.", "वश्यले प्राकृतिक आकर्षण, प्रभाव क्षमता र नियन्त्रण गतिशीलता संकेत गर्दछ। यसले निर्णय लिने र भावनात्मक मामिलाहरूमा कसले प्रभाव राख्छ भनेर देखाउँछ।"),
    VASHYA_INCOMPATIBLE("Incompatible Vashya types. May cause power struggles in the relationship.", "असंगत वश्य प्रकारहरू। सम्बन्धमा शक्ति संघर्ष हुन सक्छ।"),
    VASHYA_INSECT("Insect", "कीट"),
    VASHYA_JALACHARA("Aquatic", "जलचर"),
    VASHYA_KEETA("Insect", "कीट"),
    VASHYA_MANAVA("Human", "मानव"),
    VASHYA_PARTIAL("Partial compatibility. One partner may dominate relationship dynamics.", "आंशिक अनुकूलता। एउटा साझेदारले सम्बन्धको गतिशीलतामा प्रभुत्व जमाउन सक्छ।"),
    VASHYA_POWER_BALANCE("Balanced Vashya creates equal partnership. Imbalance may lead to dominance issues but can work if both partners accept their natural roles.", "सन्तुलित वश्यले समान साझेदारी सिर्जना गर्दछ। असन्तुलनले प्रभुत्व समस्या ल्याउन सक्छ तर दुवै साझेदारहरूले आफ्नो प्राकृतिक भूमिका स्वीकार गरे काम गर्न सक्छ।"),
    VASHYA_QUADRUPED("Quadruped", "चतुष्पाद"),
    VASHYA_REMEDY_LOW("Remedy: Worship Lord Shiva and Goddess Parvati together on Mondays. Practice mutual respect and avoid trying to dominate each other. Strengthen Venus through Friday fasts and donations of white items.", "उपाय: सोमबारमा भगवान शिव र देवी पार्वतीको सँगै पूजा गर्नुहोस्। पारस्परिक सम्मान अभ्यास गर्नुहोस् र एकअर्कालाई हावी गर्न नगर्नुहोस्। शुक्रबार व्रत र सेतो वस्तुहरूको दानद्वारा शुक्रलाई बलियो बनाउनुहोस्।"),
    VASHYA_VANACHARA("Wild", "वनचर"),
    VASHYA_VERY_GOOD("Very good compatibility with balanced influence between partners.", "साझेदारहरू बीच सन्तुलित प्रभावसहित धेरै राम्रो अनुकूलता।"),
    VASHYA_WILD("Wild", "वन्य"),
    YONI_ANIMAL_BUFFALO("Buffalo", "भैंसी"),
    YONI_ANIMAL_CAT("Cat", "बिरालो"),
    YONI_ANIMAL_COW("Cow", "गाई"),
    YONI_ANIMAL_DEER("Deer", "मृग"),
    YONI_ANIMAL_DOG("Dog", "कुकुर"),
    YONI_ANIMAL_ELEPHANT("Elephant", "हात्ती"),
    YONI_ANIMAL_HORSE("Horse", "घोडा"),
    YONI_ANIMAL_LION("Lion", "सिंह"),
    YONI_ANIMAL_MONGOOSE("Mongoose", "न्यौरी"),
    YONI_ANIMAL_MONKEY("Monkey", "बाँदर"),
    YONI_ANIMAL_RAT("Rat", "मुसो"),
    YONI_ANIMAL_SERPENT("Serpent", "सर्प"),
    YONI_ANIMAL_SHEEP("Sheep", "भेडा"),
    YONI_ANIMAL_TIGER("Tiger", "बाघ"),
    YONI_DESC("Physical and sexual compatibility", "शारीरिक र यौन अनुकूलता"),
    YONI_ENEMY("Enemy Yonis - significant physical incompatibility. May face intimacy challenges.", "शत्रु योनि - महत्त्वपूर्ण शारीरिक असंगतता। अन्तरंगता चुनौतीहरू सामना गर्न सक्छ।")
}
