package com.astro.storm.core.common
enum class StringKeyAnalysisPart1(override val en: String, override val ne: String) : StringKeyInterface {
ASHTAVARGA_TRANSIT_TITLE("Ashtavarga Transits", "अष्टकवर्ग गोचर"),
ASHTAVARGA_TRANSIT_ABOUT("About Ashtavarga Transits", "अष्टकवर्ग गोचर बारेमा"),
ASHTAVARGA_TRANSIT_SUMMARY("Transit Summary", "गोचर सारांश"),
ASHTAVARGA_TRANSIT_SCORE("Overall Transit Score", "समग्र गोचर अङ्क"),
ASHTAVARGA_TRANSIT_HIGHLIGHTS("Current Transit Highlights", "हालको गोचर हाइलाइटहरू"),
ASHTAVARGA_TRANSIT_NEXT("Next Significant Transit", "अर्को महत्त्वपूर्ण गोचर"),
ASHTAVARGA_TRANSIT_BEST_SIGN("Best Sign", "उत्तम राशि"),
ASHTAVARGA_TRANSIT_WEAK_SIGN("Weak Sign", "कमजोर राशि"),
    ASHTAVARGA_TRANSIT_REDUCTION("Shodhana (Reduction)", "Shodhana (Reduction)"),
ASHTAVARGA_TRANSIT_TRIKONA("Trikona Shodhana", "त्रिकोण शोधन"),
ASHTAVARGA_TRANSIT_EKADHIPATYA("Ekadhipatya Shodhana", "एकाधिपत्य शोधन"),
ASHTAVARGA_TRANSIT_LIFE_AREA("Life Area Impact", "जीवन क्षेत्र प्रभाव"),
ASHTAVARGA_TRANSIT_DESC("Ashtavarga Transit method is a powerful Vedic astrology technique that measures transit effects based on bindu points from the natal chart.", "अष्टकवर्ग गोचर विधि एक शक्तिशाली वैदिक ज्योतिष प्रविधि हो जसले जन्म कुण्डलीको विन्दु बिन्दुहरूको आधारमा गोचर प्रभावहरू मापन गर्दछ।"),
QUALITY_EXCELLENT("Excellent", "उत्कृष्ट"),
QUALITY_GOOD("Good", "राम्रो"),
QUALITY_NEUTRAL("Neutral", "तटस्थ"),
QUALITY_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
QUALITY_INAUSPICIOUS("Inauspicious", "अशुभ"),
CHART_LEGEND_RETRO("Retro", "वक्री"),
CHART_LEGEND_COMBUST("Combust", "अस्त"),
CHART_LEGEND_VARGOTTAMA("Vargottama", "वर्गोत्तम"),
CHART_LEGEND_EXALTED("Exalted", "उच्च"),
CHART_LEGEND_DEBILITATED("Debilitated", "नीच"),
CHART_LEGEND_OWN_SIGN("Own Sign", "स्वराशि"),
CHART_LEGEND_MOOL_TRI("Mool Tri.", "मूलत्रि."),
CHART_BIRTH_DETAILS("Birth Details", "जन्म विवरण"),
CHART_PLANETARY_POSITIONS("Planetary Positions", "ग्रह स्थितिहरू"),
CHART_TAP_FOR_DETAILS("Tap for details", "विवरणको लागि ट्याप गर्नुहोस्"),
CHART_TAP_TO_EXPAND("Tap to expand", "विस्तार गर्न ट्याप गर्नुहोस्"),
CHART_TAP_HOUSE_FOR_DETAILS("Tap house for details", "विवरणको लागि भाव ट्याप गर्नुहोस्"),
    CHART_ASCENDANT_LAGNA("Ascendant (Lagna)", "Ascendant (Lagna)"),
CHART_HOUSE_CUSPS("House Cusps", "भाव सन्धि"),
CHART_ASTRONOMICAL_DATA("Astronomical Data", "खगोलीय तथ्याङ्क"),
CHART_JULIAN_DAY("Julian Day", "जुलियन दिन"),
CHART_MIDHEAVEN("Midheaven", "मध्याकाश"),
CHART_HOUSE_SYSTEM("House System", "भाव पद्धति"),
CHART_TAP_FULLSCREEN("Tap chart to view fullscreen", "पूर्ण स्क्रिनमा हेर्न चार्ट ट्याप गर्नुहोस्"),
CHART_DATE("Date", "मिति"),
CHART_TIME("Time", "समय"),
CHART_AYANAMSA("Ayanamsa", "अयनांश"),
CHART_LOCATION("Location", "स्थान"),
HOUSE("House", "भाव"),
LOCATION("Location", "स्थान"),
ASCENDANT("Ascendant", "लग्न"),
CHART_LAGNA("Lagna", "लग्न"),
    CHART_RASHI("Rashi Chart (D1)", "Rashi Chart (D1)"),
    CHART_NAVAMSA("Navamsa Chart (D9)", "Navamsa Chart (D9)"),
DIALOG_POSITION_DETAILS("Position Details", "स्थिति विवरण"),
DIALOG_ZODIAC_SIGN("Zodiac Sign", "राशि"),
DIALOG_DEGREE("Degree", "अंश"),
DIALOG_HOUSE("House", "भाव"),
DIALOG_NAKSHATRA("Nakshatra", "नक्षत्र"),
DIALOG_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी"),
DIALOG_NAKSHATRA_DEITY("Nakshatra Deity", "नक्षत्र देवता"),
DIALOG_MOTION("Motion", "गति"),
DIALOG_RETROGRADE("Retrograde", "वक्री"),
    DIALOG_STRENGTH_ANALYSIS("Strength Analysis (Shadbala)", "Strength Analysis (Shadbala)"),
    DIALOG_STRENGTH_BREAKDOWN("Strength Breakdown (Virupas)", "Strength Breakdown (Virupas)"),
    DIALOG_STHANA_BALA("Sthana Bala (Positional)", "Sthana Bala (Positional)"),
    DIALOG_DIG_BALA("Dig Bala (Directional)", "Dig Bala (Directional)"),
    DIALOG_KALA_BALA("Kala Bala (Temporal)", "Kala Bala (Temporal)"),
    DIALOG_CHESTA_BALA("Chesta Bala (Motional)", "Chesta Bala (Motional)"),
    DIALOG_NAISARGIKA_BALA("Naisargika Bala (Natural)", "Naisargika Bala (Natural)"),
    DIALOG_DRIK_BALA("Drik Bala (Aspectual)", "Drik Bala (Aspectual)"),
DIALOG_BENEFIC("Benefic", "शुभ"),
DIALOG_MALEFIC("Malefic", "पापी"),
DIALOG_ELEMENT("Element", "तत्व"),
DIALOG_REPRESENTS("Represents:", "प्रतिनिधित्व:"),
DIALOG_BODY_PARTS("Body Parts:", "शरीर अंग:"),
DIALOG_PROFESSIONS("Professions:", "पेशाहरू:"),
DIALOG_HOUSE_PLACEMENT("House %d Placement", "भाव %d स्थिति"),
DIALOG_STATUS_CONDITIONS("Status & Conditions", "स्थिति र अवस्था"),
DIALOG_DIGNITY("Dignity", "मर्यादा"),
DIALOG_COMBUSTION("Combustion", "अस्त"),
COMBUSTION_NOT_COMBUST("Not Combust", "अस्त छैन"),
COMBUSTION_APPROACHING("Approaching Combustion", "अस्त नजिक"),
COMBUSTION_COMBUST("Combust", "अस्त"),
COMBUSTION_DEEP_COMBUST("Deep Combustion", "गहिरो अस्त"),
COMBUSTION_CAZIMI("Cazimi", "काजिमी"),
COMBUSTION_SEPARATING("Separating", "विभाजन"),
DIALOG_PLANETARY_WAR("Planetary War", "ग्रहयुद्ध"),
DIALOG_AT_WAR_WITH("At war with %s", "%s सँग युद्धमा"),
DIALOG_INSIGHTS_PREDICTIONS("Insights & Predictions", "अन्तर्दृष्टि र भविष्यवाणी"),
DIALOG_OVERALL("Overall: %s / %s Rupas", "समग्र: %s / %s रुपा"),
DIALOG_REQUIRED_STRENGTH("Required", "आवश्यक"),
DIALOG_PERCENT_OF_REQUIRED("%s%% of required strength", "आवश्यक बलको %s%%"),
DIALOG_TOTAL_VIRUPAS("Total Virupas", "कुल विरुपा"),
    HOUSE_1_NAME("First House (Lagna)", "First House (Lagna)"),
    HOUSE_2_NAME("Second House (Dhana)", "Second House (Dhana)"),
    HOUSE_3_NAME("Third House (Sahaja)", "Third House (Sahaja)"),
    HOUSE_4_NAME("Fourth House (Sukha)", "Fourth House (Sukha)"),
    HOUSE_5_NAME("Fifth House (Putra)", "Fifth House (Putra)"),
    HOUSE_6_NAME("Sixth House (Ripu)", "Sixth House (Ripu)"),
    HOUSE_7_NAME("Seventh House (Kalatra)", "Seventh House (Kalatra)"),
    HOUSE_8_NAME("Eighth House (Ayur)", "Eighth House (Ayur)"),
    HOUSE_9_NAME("Ninth House (Dharma)", "Ninth House (Dharma)"),
    HOUSE_10_NAME("Tenth House (Karma)", "Tenth House (Karma)"),
    HOUSE_11_NAME("Eleventh House (Labha)", "Eleventh House (Labha)"),
    HOUSE_12_NAME("Twelfth House (Vyaya)", "Twelfth House (Vyaya)"),
HOUSE_1_SIG("Self, Body, Personality", "आत्म, शरीर, व्यक्तित्व"),
HOUSE_2_SIG("Wealth, Family, Speech", "धन, परिवार, वाणी"),
HOUSE_3_SIG("Siblings, Courage, Communication", "भाइबहिनी, साहस, सञ्चार"),
HOUSE_4_SIG("Home, Mother, Happiness", "घर, आमा, सुख"),
HOUSE_5_SIG("Children, Intelligence, Romance", "सन्तान, बुद्धि, प्रेम"),
HOUSE_6_SIG("Enemies, Health, Service", "शत्रु, स्वास्थ्य, सेवा"),
HOUSE_7_SIG("Marriage, Partnerships, Business", "विवाह, साझेदारी, व्यापार"),
HOUSE_8_SIG("Longevity, Transformation, Occult", "आयु, रूपान्तरण, तन्त्र"),
HOUSE_9_SIG("Fortune, Dharma, Father", "भाग्य, धर्म, पिता"),
HOUSE_10_SIG("Career, Status, Public Image", "क्यारियर, पद, सार्वजनिक छवि"),
HOUSE_11_SIG("Gains, Income, Desires", "लाभ, आय, इच्छाहरू"),
HOUSE_12_SIG("Losses, Expenses, Liberation", "हानि, खर्च, मोक्ष"),
    HOUSE_TYPE_KENDRA("Kendra (Angular)", "Kendra (Angular)"),
    HOUSE_TYPE_TRIKONA("Trikona (Trine)", "Trikona (Trine)"),
    HOUSE_TYPE_DUSTHANA("Dusthana (Malefic)", "Dusthana (Malefic)"),
    HOUSE_TYPE_UPACHAYA("Upachaya (Growth)", "Upachaya (Growth)"),
    HOUSE_TYPE_MARAKA("Maraka (Death-inflicting)", "Maraka (Death-inflicting)"),
HOUSE_TYPE_PANAPARA("Panapara", "पणफर"),
HOUSE_TYPE_APOKLIMA("Apoklima", "आपोक्लिम"),
DIALOG_CLOSE("Close", "बन्द गर्नुहोस्"),
DIALOG_RESET("Reset", "रिसेट"),
DIALOG_ZOOM_IN("Zoom In", "ठूलो पार्नुहोस्"),
DIALOG_ZOOM_OUT("Zoom Out", "सानो पार्नुहोस्"),
DIALOG_DOWNLOAD("Download", "डाउनलोड"),
DIALOG_SAVING("Saving...", "सेभ गर्दै..."),
DIALOG_CHART_SAVED("Chart saved to gallery!", "चार्ट ग्यालेरीमा सेभ भयो!"),
DIALOG_SAVE_FAILED("Failed to save chart", "चार्ट सेभ गर्न असफल"),
VARSHAPHALA_YEAR_RANGE("%d - %d", "%d - %d"),
DIALOG_BASIC_INFO("Basic Information", "आधारभूत जानकारी"),
DIALOG_NAKSHATRA_NATURE("Nakshatra Nature", "नक्षत्र प्रकृति"),
DIALOG_PADA_CHARACTERISTICS("Pada %d Characteristics", "पाद %d विशेषताहरू"),
DIALOG_GENERAL_CHARACTERISTICS("General Characteristics", "सामान्य विशेषताहरू"),
DIALOG_CAREER_INDICATIONS("Career Indications", "क्यारियर संकेतहरू"),
DIALOG_NUMBER("Number", "क्रमांक"),
DIALOG_DEGREE_RANGE("Degree Range", "अंश दायरा"),
DIALOG_NAVAMSA_SIGN("Navamsa Sign", "नवांश राशि"),
DIALOG_GENDER("Gender", "लिङ्ग"),
DIALOG_HOUSE_INFO("House Information", "भाव जानकारी"),
DIALOG_SIGNIFICATIONS("Significations & Nature", "करकत्व र प्रकृति"),
DIALOG_NATURE("Nature", "प्रकृति"),
DIALOG_PLANETS_IN_HOUSE("Planets in House", "भावमा ग्रहहरू"),
DIALOG_DETAILED_INTERPRETATION("Detailed Interpretation", "विस्तृत व्याख्या"),
DIALOG_CUSP_DEGREE("Cusp Degree", "सन्धि अंश"),
DIALOG_SIGN_LORD("Sign Lord", "राशि स्वामी"),
DIALOG_HOUSE_TYPE("House Type", "भाव प्रकार"),
DIALOG_SHADBALA_ANALYSIS("Shadbala Analysis", "षड्बल विश्लेषण"),
DIALOG_SIXFOLD_STRENGTH("Six-fold Planetary Strength", "छवटा ग्रह बल"),
DIALOG_OVERALL_SUMMARY("Overall Summary", "समग्र सारांश"),
DIALOG_CHART_STRENGTH("Chart Strength", "कुण्डली बल"),
DIALOG_STRONGEST("Strongest", "सबैभन्दा बलियो"),
DIALOG_WEAKEST("Weakest", "सबैभन्दा कमजोर"),
EXPORT_VEDIC_REPORT("VEDIC BIRTH CHART REPORT", "वैदिक जन्म कुण्डली रिपोर्ट"),
EXPORT_NAME("Name:", "नाम:"),
EXPORT_DATE_TIME("Date & Time:", "मिति र समय:"),
EXPORT_LOCATION("Location:", "स्थान:"),
EXPORT_COORDINATES("Coordinates:", "निर्देशांक:"),
EXPORT_PLANETARY_POSITIONS("PLANETARY POSITIONS", "ग्रह स्थितिहरू"),
EXPORT_ASTRONOMICAL_DATA("ASTRONOMICAL DATA", "खगोलीय तथ्याङ्क"),
EXPORT_HOUSE_CUSPS("HOUSE CUSPS", "भाव सन्धिहरू"),
EXPORT_YOGA_ANALYSIS("YOGA ANALYSIS", "योग विश्लेषण"),
EXPORT_TOTAL_YOGAS("Total Yogas Found:", "कुल योगहरू फेला परेको:"),
EXPORT_OVERALL_YOGA_STRENGTH("Overall Yoga Strength:", "समग्र योग बल:"),
EXPORT_KEY_YOGAS("Key Yogas:", "प्रमुख योगहरू:"),
EXPORT_CHALLENGING_YOGAS("Challenging Yogas:", "चुनौतीपूर्ण योगहरू:"),
EXPORT_MITIGATED_BY("Mitigated by:", "न्यूनीकरण:"),
EXPORT_PLANETARY_ASPECTS("PLANETARY ASPECTS", "ग्रह दृष्टिहरू"),
EXPORT_SHADBALA_ANALYSIS("SHADBALA ANALYSIS", "षड्बल विश्लेषण"),
EXPORT_OVERALL_CHART_STRENGTH("Overall Chart Strength:", "समग्र कुण्डली बल:"),
EXPORT_STRONGEST_PLANET("Strongest Planet:", "सबैभन्दा बलियो ग्रह:"),
EXPORT_WEAKEST_PLANET("Weakest Planet:", "सबैभन्दा कमजोर ग्रह:"),
EXPORT_STRENGTH_BREAKDOWN("Strength Breakdown:", "बल विभाजन:"),
EXPORT_ASHTAKAVARGA_ANALYSIS("ASHTAKAVARGA ANALYSIS", "अष्टकवर्ग विश्लेषण"),
    EXPORT_SARVASHTAKAVARGA("Sarvashtakavarga (Combined Strength)", "Sarvashtakavarga (Combined Strength)"),
    EXPORT_BHINNASHTAKAVARGA("Bhinnashtakavarga (Individual Planet Bindus)", "Bhinnashtakavarga (Individual Planet Bindus)"),
EXPORT_TRANSIT_GUIDE("Transit Interpretation Guide:", "गोचर व्याख्या गाइड:"),
EXPORT_SAV_EXCELLENT("SAV 30+ bindus: Excellent for transits - major positive events", "SAV ३०+ बिन्दु: गोचरको लागि उत्कृष्ट - प्रमुख सकारात्मक घटनाहरू"),
EXPORT_SAV_GOOD("SAV 28-29 bindus: Good for transits - favorable outcomes", "SAV २८-२९ बिन्दु: गोचरको लागि राम्रो - अनुकूल परिणामहरू"),
EXPORT_SAV_AVERAGE("SAV 25-27 bindus: Average - mixed results", "SAV २५-२७ बिन्दु: औसत - मिश्रित परिणामहरू"),
EXPORT_SAV_CHALLENGING("SAV below 25: Challenging - caution advised during transits", "SAV २५ भन्दा कम: चुनौतीपूर्ण - गोचरमा सावधानी आवश्यक"),
EXPORT_BAV_EXCELLENT("BAV 5+ bindus: Planet transit through this sign is highly beneficial", "BAV ५+ बिन्दु: यस राशिमा ग्रह गोचर अत्यन्त लाभदायक"),
EXPORT_BAV_GOOD("BAV 4 bindus: Good results from planet transit", "BAV ४ बिन्दु: ग्रह गोचरबाट राम्रो परिणामहरू"),
EXPORT_BAV_AVERAGE("BAV 3 bindus: Average results", "BAV ३ बिन्दु: औसत परिणामहरू"),
EXPORT_BAV_CHALLENGING("BAV 0-2 bindus: Difficult transit period for that planet", "BAV ०-२ बिन्दु: त्यो ग्रहको लागि कठिन गोचर अवधि"),
EXPORT_GENERATED_BY("Generated by AstroStorm - Ultra-Precision Vedic Astrology", "AstroStorm द्वारा उत्पन्न - अति-सटीक वैदिक ज्योतिष"),
EXPORT_PAGE("Page %d", "पृष्ठ %d"),
EXPORT_PLANET("Planet", "ग्रह"),
EXPORT_SIGN("Sign", "राशि"),
EXPORT_DEGREE("Degree", "अंश"),
EXPORT_NAKSHATRA("Nakshatra", "नक्षत्र"),
EXPORT_PADA("Pada", "पाद"),
EXPORT_HOUSE("House", "भाव"),
EXPORT_STATUS("Status", "स्थिति"),
EXPORT_TOTAL_RUPAS("Total Rupas", "कुल रुपा"),
EXPORT_REQUIRED("Required", "आवश्यक"),
EXPORT_PERCENT("%", "प्रतिशत"),
EXPORT_RATING("Rating", "मूल्याङ्कन"),
EXPORT_VIRUPAS("virupas", "विरुपा"),
EXPORT_BIRTH_INFO("BIRTH INFORMATION", "जन्म जानकारी"),
EXPORT_CHART_SUMMARY("CHART SUMMARY", "कुण्डली सारांश"),
    EXPORT_ASCENDANT_LAGNA("Ascendant (Lagna)", "Ascendant (Lagna)"),
    EXPORT_MOON_SIGN_RASHI("Moon Sign (Rashi)", "Moon Sign (Rashi)"),
EXPORT_SUN_SIGN("Sun Sign:", "सूर्य राशि:"),
EXPORT_BIRTH_NAKSHATRA("Birth Nakshatra:", "जन्म नक्षत्र:"),
EXPORT_TIMEZONE("Timezone:", "समय क्षेत्र:"),
    EXPORT_CALC_ENGINE("Calculation Engine: Swiss Ephemeris (JPL Mode)", "Calculation Engine: Swiss Ephemeris (JPL Mode)"),
EXPORT_ULTRA_PRECISION("Ultra-Precision Vedic Astrology Software", "अति-सटीक वैदिक ज्योतिष सफ्टवेयर"),
EXPORT_GENERATED_BY_SHORT("Generated by AstroStorm", "AstroStorm द्वारा उत्पन्न"),
EXPORT_GENERATED("Generated", "उत्पन्न"),
    EXPORT_MOON_SIGN("Moon Sign (Rashi)", "Moon Sign (Rashi)"),
PREDICTION_STRONG_PLANET("Strong %s", "बलियो %s"),
PREDICTION_STRONG_DESC("This planet has sufficient strength to deliver positive results. Its significations will manifest more easily in your life.", "यो ग्रहसँग सकारात्मक परिणामहरू दिनको लागि पर्याप्त बल छ। यसको करकत्वहरू तपाईंको जीवनमा सजिलैसँग प्रकट हुनेछन्।"),
PREDICTION_WEAK_PLANET("Weak %s", "कमजोर %s"),
PREDICTION_WEAK_DESC("This planet lacks sufficient strength. You may face challenges in areas it governs. Remedial measures may help.", "यो ग्रहमा पर्याप्त बल छैन। तपाईंले यसले शासन गर्ने क्षेत्रहरूमा चुनौतीहरू सामना गर्न सक्नुहुन्छ। उपाय उपायहरूले मद्दत गर्न सक्छ।"),
PREDICTION_EXALTED("Exalted Planet", "उच्च ग्रह"),
PREDICTION_EXALTED_DESC("%s is in its sign of exaltation, giving exceptional results in its significations.", "%s आफ्नो उच्च राशिमा छ, यसको करकत्वमा असाधारण परिणामहरू दिँदै।"),
PREDICTION_DEBILITATED("Debilitated Planet", "नीच ग्रह"),
PREDICTION_DEBILITATED_DESC("%s is in its fall. Its positive significations may be reduced or delayed.", "%s आफ्नो नीच राशिमा छ। यसको सकारात्मक करकत्वहरू कम वा ढिलो हुन सक्छन्।"),
PREDICTION_OWN_SIGN("Planet in Own Sign", "स्वराशिमा ग्रह"),
PREDICTION_OWN_SIGN_DESC("%s is comfortable in its own sign, giving stable and reliable results.", "%s आफ्नै राशिमा सहज छ, स्थिर र भरपर्दो परिणामहरू दिँदै।"),
PREDICTION_RETROGRADE("Retrograde Motion", "वक्री गति"),
PREDICTION_RETROGRADE_DESC("Retrograde planets work on an internal level. Results may be delayed but often more profound.", "वक्री ग्रहहरू आन्तरिक स्तरमा काम गर्छन्। परिणामहरू ढिलो हुन सक्छन् तर प्रायः अधिक गहिरो हुन्छन्।"),
PREDICTION_TRIKONA("Trikona Placement", "त्रिकोण स्थिति"),
    PREDICTION_TRIKONA_DESC("%s in house %d (Trikona)", "%s in house %d (Trikona)"),
PREDICTION_DUSTHANA("Dusthana Placement", "दुःस्थान स्थिति"),
PREDICTION_DUSTHANA_DESC("%s in house %d may face obstacles but can also give transformative experiences.", "भाव %d मा %s ले बाधाहरू सामना गर्न सक्छ तर रूपान्तरणकारी अनुभवहरू पनि दिन सक्छ।"),
PREDICTION_KENDRA("Kendra Placement", "केन्द्र स्थिति"),
    PREDICTION_KENDRA_DESC("%s in house %d (Kendra)", "%s in house %d (Kendra)"),
ASPECT_VERY_STRONG("Very Strong", "अति बलियो"),
ASPECT_STRONG("Strong", "बलियो"),
ASPECT_MODERATE("Moderate", "मध्यम"),
ASPECT_WEAK("Weak", "कमजोर"),
ASPECT_VERY_WEAK("Very Weak", "अति कमजोर"),
KEY_DATE_FAVORABLE("Favorable", "अनुकूल"),
KEY_DATE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
KEY_DATE_IMPORTANT("Important", "महत्त्वपूर्ण"),
KEY_DATE_TRANSIT("Transit", "गोचर"),
VARSHAPHALA_NO_CHART("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
VARSHAPHALA_NO_CHART_DESC("Select a birth chart to view Varshaphala", "वर्षफल हेर्न जन्म कुण्डली छान्नुहोस्"),
VARSHAPHALA_SUN_RETURNS("Sun returns to natal position", "सूर्य जन्मकालीन स्थानमा फर्कन्छ"),
VARSHAPHALA_RETURN_DATE("Return Date", "प्रतिफल मिति"),
VARSHAPHALA_AGE_FORMAT("Age %d", "उमेर %d"),
VARSHAPHALA_IN_HOUSE("House %d", "भाव %d"),
VARSHAPHALA_FIVEFOLD_STRENGTH("Five-fold Planetary Strength", "पञ्चवर्गीय ग्रह बल"),
VARSHAPHALA_THREE_FLAG("Three-flag Diagram", "त्रिपताकी चक्र"),
VARSHAPHALA_IMPORTANT_DATES("%d important dates", "%d महत्त्वपूर्ण मितिहरू"),
VARSHAPHALA_CHART_LEGEND_ASC("Asc", "लग्न"),
VARSHAPHALA_CHART_LEGEND_MUNTHA("Muntha", "मुन्थ"),
VARSHAPHALA_CHART_LEGEND_BENEFIC("Benefic", "शुभ"),
VARSHAPHALA_CHART_LEGEND_MALEFIC("Malefic", "पाप"),
VARSHAPHALA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
VARSHAPHALA_TOTAL("Total", "कुल"),
VARSHAPHALA_ACTIVE("Active", "सक्रिय"),
VARSHAPHALA_CURRENT("CURRENT", "वर्तमान"),
VARSHAPHALA_DAYS_FORMAT("%d days", "%d दिन"),
VARSHAPHALA_HOUSE_SIGN("House %d - %s", "भाव %d - %s"),
VARSHAPHALA_LORD_IN_HOUSE("Lord: %s in H%d", "स्वामी: %s भाव%d मा"),
VARSHAPHALA_RULES_HOUSES("Rules Houses: %s", "भावहरू शासन: %s"),
VARSHAPHALA_PLANETS("Planets: ", "ग्रहहरू: "),
VARSHAPHALA_NO_PLANETS("No planets", "कुनै ग्रह छैन"),
VARSHAPHALA_HOUSES_PREFIX("Houses: ", "भावहरू: "),
VARSHAPHALA_SPECIFIC_INDICATIONS("Specific Indications:", "विशिष्ट संकेतहरू:"),
VARSHAPHALA_LORD_PREFIX("Lord: %s", "स्वामी: %s"),
PANCHA_EXCELLENT("Excellent", "उत्कृष्ट"),
PANCHA_GOOD("Good", "राम्रो"),
PANCHA_AVERAGE("Average", "औसत"),
PANCHA_BELOW_AVERAGE("Below Average", "औसतमुनि"),
PANCHA_WEAK("Weak", "कमजोर"),
DASHA_KW_LEADERSHIP("Leadership", "नेतृत्व"),
DASHA_KW_VITALITY("Vitality", "जीवनशक्ति"),
DASHA_KW_FATHER("Father", "बुबा"),
DASHA_KW_EMOTIONS("Emotions", "भावनाहरू"),
DASHA_KW_MOTHER("Mother", "आमा"),
DASHA_KW_PUBLIC("Public", "सार्वजनिक"),
DASHA_KW_ACTION("Action", "कार्य"),
DASHA_KW_ENERGY("Energy", "ऊर्जा"),
DASHA_KW_COURAGE("Courage", "साहस"),
DASHA_KW_COMMUNICATION("Communication", "सञ्चार"),
DASHA_KW_LEARNING("Learning", "सिकाइ"),
DASHA_KW_WISDOM("Wisdom", "बुद्धि"),
DASHA_KW_GROWTH("Growth", "वृद्धि"),
DASHA_KW_LOVE("Love", "प्रेम"),
DASHA_KW_ART("Art", "कला"),
DASHA_KW_COMFORT("Comfort", "सुविधा"),
DASHA_KW_DISCIPLINE("Discipline", "अनुशासन"),
DASHA_KW_KARMA("Karma", "कर्म"),
DASHA_KW_DELAYS("Delays", "ढिलाइ"),
DASHA_KW_AMBITION("Ambition", "महत्त्वाकांक्षा"),
DASHA_KW_INNOVATION("Innovation", "नवीनता"),
DASHA_KW_FOREIGN("Foreign", "विदेशी"),
DASHA_KW_DETACHMENT("Detachment", "वैराग्य"),
DASHA_KW_PAST("Past", "भूतकाल"),
DASHA_KW_GENERAL("General", "सामान्य"),
DASHA_KW_SELF("Self", "आत्म"),
DASHA_KW_BODY("Body", "शरीर"),
DASHA_KW_WEALTH("Wealth", "धन"),
DASHA_KW_SPEECH("Speech", "वाणी"),
DASHA_KW_HOME("Home", "घर"),
DASHA_KW_PEACE("Peace", "शान्ति"),
DASHA_KW_CHILDREN("Children", "सन्तान"),
DASHA_KW_HEALTH("Health", "स्वास्थ्य"),
DASHA_KW_SERVICE("Service", "सेवा"),
DASHA_KW_MARRIAGE("Marriage", "विवाह"),
DASHA_KW_BUSINESS("Business", "व्यापार"),
DASHA_KW_TRANSFORMATION("Transformation", "रूपान्तरण"),
DASHA_KW_RESEARCH("Research", "अनुसन्धान"),
DASHA_KW_LUCK("Luck", "भाग्य"),
DASHA_KW_TRAVEL("Travel", "यात्रा"),
DASHA_KW_CAREER("Career", "क्यारियर"),
DASHA_KW_STATUS("Status", "स्थिति"),
DASHA_KW_GAINS("Gains", "लाभ"),
DASHA_KW_FRIENDS("Friends", "मित्रहरू"),
DASHA_KW_LOSSES("Losses", "हानि"),
KEY_DATE_SOLAR_RETURN("Solar Return", "सौर प्रतिफल"),
KEY_DATE_SOLAR_RETURN_DESC("Beginning of the annual horoscope year", "वार्षिक राशिफल वर्षको शुरुवात"),
KEY_DATE_DASHA_BEGINS("%s Dasha Begins", "%s दशा शुरु"),
    KEY_DATE_DASHA_DESC("Start of %s period (%d days)", "Start of %s period (%d days)"),
HOUSE_STRENGTH_EXCELLENT("Excellent", "उत्कृष्ट"),
HOUSE_STRENGTH_STRONG("Strong", "बलियो"),
HOUSE_STRENGTH_MODERATE("Moderate", "मध्यम"),
HOUSE_STRENGTH_WEAK("Weak", "कमजोर"),
HOUSE_STRENGTH_CHALLENGED("Challenged", "चुनौतीपूर्ण"),
ASPECT_ITHASALA_EFFECT("%s applying to %s promises fulfillment", "%s %s मा निकटवर्ती हुँदा पूर्तिको वाचा"),
ASPECT_EASARAPHA_EFFECT("Separating aspect suggests matters are concluding", "विलग पक्षले मामिलाहरू समाप्त हुँदैछन् भनी सुझाव दिन्छ"),
ASPECT_KAMBOOLA_EFFECT("Powerful angular conjunction promises prominent success", "शक्तिशाली केन्द्रीय युतिले प्रमुख सफलताको वाचा गर्छ"),
ASPECT_RADDA_EFFECT("Retrograde motion causes delays or reversals", "वक्री गतिले ढिलाइ वा उल्टो परिणाम ल्याउँछ"),
ASPECT_DURAPHA_EFFECT("Hard aspect creates challenges that strengthen through difficulty", "कडा पक्षले कठिनाइद्वारा बलियो बनाउने चुनौतीहरू सिर्जना गर्छ"),
ASPECT_GENERIC_EFFECT("%s influences matters with %s energy", "%s ले %s ऊर्जासहित मामिलाहरूलाई प्रभाव पार्छ"),
ASPECT_SUPPORTIVE("supportive", "समर्थनात्मक"),
ASPECT_PREDICTION_TEMPLATE("The %s between %s and %s is %s for matters of %s.", "%s र %s बीचको %s %s को मामिलाहरूको लागि %s छ।"),
ASPECT_FAVORABLE_FOR("favorable", "अनुकूल"),
ASPECT_REQUIRING_ATTENTION("requiring attention", "ध्यान चाहिने"),
MONTH_JAN("Jan", "जनवरी"),
MONTH_FEB("Feb", "फेब्रुअरी"),
MONTH_MAR("Mar", "मार्च"),
MONTH_APR("Apr", "अप्रिल"),
MONTH_MAY("May", "मे"),
MONTH_JUN("Jun", "जुन"),
MONTH_JUL("Jul", "जुलाई"),
MONTH_AUG("Aug", "अगस्ट"),
MONTH_SEP("Sep", "सेप्टेम्बर"),
MONTH_OCT("Oct", "अक्टोबर"),
MONTH_NOV("Nov", "नोभेम्बर"),
MONTH_DEC("Dec", "डिसेम्बर"),
ORDINAL_ST("st", "औं"),
ORDINAL_ND("nd", "औं"),
ORDINAL_RD("rd", "औं"),
ORDINAL_TH("th", "औं"),
DASHA_SUB_PERIOD_MODIFIER("The %s sub-period modifies these themes with its own energies.", "%s उप-अवधिले यी विषयहरूलाई आफ्नै ऊर्जाका साथ परिमार्जन गर्दछ।"),
ANALYSIS_CHART_ANALYSIS("Chart Analysis", "कुण्डली विश्लेषण"),
ANALYSIS_TAB_CHART("Chart", "कुण्डली"),
ANALYSIS_TAB_PLANETS("Planets", "ग्रहहरू"),
ANALYSIS_TAB_YOGAS("Yogas", "योगहरू"),
ANALYSIS_TAB_DASHAS("Dashas", "दशाहरू"),
ANALYSIS_TAB_TRANSITS("Transits", "गोचरहरू"),
ANALYSIS_TAB_ASHTAKAVARGA("Ashtakavarga", "अष्टकवर्ग"),
ANALYSIS_TAB_PANCHANGA("Panchanga", "पञ्चाङ्ग"),
PLANETS_CONDITIONS("Planetary Conditions", "ग्रह अवस्थाहरू"),
PLANETS_RETROGRADE("Retrograde", "वक्री"),
PLANETS_COMBUST("Combust", "अस्त"),
PLANETS_AT_WAR("At War", "युद्धमा"),
PLANETS_PLANETARY_WAR("Planetary War", "ग्रहयुद्ध"),
PLANETS_SHADBALA_SUMMARY("Shadbala Summary", "षड्बल सारांश"),
PLANETS_OVERALL("Overall", "समग्र"),
PLANETS_VIEW_DETAILS("View Details", "विवरण हेर्नुहोस्"),
PLANETS_TAP_FOR_DETAILS("Tap for details", "विवरणको लागि ट्याप गर्नुहोस्"),
PLANETS_SHADBALA("Shadbala", "षड्बल"),
    PLANETS_RUPAS("%s / %s rupas (%s%%)", "%s / %s rupas (%s%%)"),
PLANETS_HOUSE_FORMAT("House %d", "भाव %d"),
ASHTAK_SUMMARY("Ashtakavarga Summary", "अष्टकवर्ग सारांश"),
ASHTAK_TOTAL_SAV("Total SAV", "कुल SAV"),
ASHTAK_STRONGEST("Strongest", "सबैभन्दा बलियो"),
ASHTAK_WEAKEST("Weakest", "सबैभन्दा कमजोर"),
ASHTAK_QUICK_ANALYSIS("Quick Analysis", "द्रुत विश्लेषण"),
    ASHTAK_FAVORABLE_SIGNS("Favorable Signs (28+)", "Favorable Signs (28+)"),
    ASHTAK_CHALLENGING_SIGNS("Challenging Signs (<25)", "Challenging Signs (<25)"),
ASHTAK_SIGNS_COUNT("%d signs", "%d राशिहरू"),
    ASHTAK_SAV_TITLE("Sarvashtakavarga (SAV)", "Sarvashtakavarga (SAV)"),
ASHTAK_SAV_COMBINED_DESC("Combined strength of all planets in each sign", "प्रत्येक राशिमा सबै ग्रहहरूको संयुक्त बल"),
    ASHTAK_BAV_TITLE("Bhinnashtakavarga (BAV)", "Bhinnashtakavarga (BAV)"),
    ASHTAK_BAV_INDIVIDUAL_DESC("Individual planet strength in each sign (0-8 bindus)", "Individual planet strength in each sign (0-8 bindus)"),
ASHTAK_TOTAL("Total", "कुल"),
    ASHTAK_SAV_EXCELLENT("30+ (Excellent)", "30+ (Excellent)"),
    ASHTAK_SAV_GOOD("28-29 (Good)", "28-29 (Good)"),
    ASHTAK_SAV_AVERAGE("25-27 (Average)", "25-27 (Average)"),
    ASHTAK_SAV_WEAK("<25 (Weak)", "<25 (Weak)"),
    ASHTAK_BAV_STRONG("5+ (Strong)", "5+ (Strong)"),
    ASHTAK_BAV_GOOD("4 (Good)", "4 (Good)"),
    ASHTAK_BAV_AVERAGE("3 (Average)", "3 (Average)"),
    ASHTAK_BAV_WEAK("0-2 (Weak)", "0-2 (Weak)"),
ASHTAK_GUIDE_TITLE("Interpretation Guide", "व्याख्या गाइड"),
    ASHTAK_GUIDE_SAV_TITLE("Sarvashtakavarga (SAV)", "Sarvashtakavarga (SAV)"),
ASHTAK_GUIDE_SAV_30("30+ bindus: Excellent for transits - major positive events", "३०+ बिन्दु: गोचरको लागि उत्कृष्ट - प्रमुख सकारात्मक घटनाहरू"),
ASHTAK_GUIDE_SAV_28("28-29 bindus: Good for transits - favorable outcomes", "२८-२९ बिन्दु: गोचरको लागि राम्रो - अनुकूल परिणामहरू"),
ASHTAK_GUIDE_SAV_25("25-27 bindus: Average - mixed results expected", "२५-२७ बिन्दु: औसत - मिश्रित परिणामहरू अपेक्षित"),
ASHTAK_GUIDE_SAV_BELOW("Below 25: Challenging - caution during transits", "२५ भन्दा कम: चुनौतीपूर्ण - गोचरमा सावधानी"),
    ASHTAK_GUIDE_BAV_TITLE("Bhinnashtakavarga (BAV)", "Bhinnashtakavarga (BAV)"),
ASHTAK_GUIDE_BAV_5("5+ bindus: Planet transit highly beneficial", "५+ बिन्दु: ग्रह गोचर अत्यधिक लाभदायक"),
ASHTAK_GUIDE_BAV_4("4 bindus: Good results from transit", "४ बिन्दु: गोचरबाट राम्रो परिणाम"),
ASHTAK_GUIDE_BAV_3("3 bindus: Average, neutral results", "३ बिन्दु: औसत, तटस्थ परिणामहरू"),
ASHTAK_GUIDE_BAV_02("0-2 bindus: Difficult transit period", "०-२ बिन्दु: कठिन गोचर अवधि"),
ASHTAK_GUIDE_TRANSIT_TITLE("Transit Application", "गोचर अनुप्रयोग")
}
