package com.astro.storm.core.common

/**
 * Deep Analysis Localization Keys - Health & Longevity
 * 350+ localization keys for comprehensive health analysis
 */
enum class StringKeyDeepHealth(override val en: String, override val ne: String) : StringKeyInterface {
SECTION_HEALTH("Health Analysis", "स्वास्थ्य विश्लेषण"),
SECTION_CONSTITUTION("Constitution Analysis", "संविधान विश्लेषण"),
SECTION_6TH_HOUSE("6th House Analysis", "षष्ठ भाव विश्लेषण"),
SECTION_8TH_HOUSE("8th House Analysis", "अष्टम भाव विश्लेषण"),
SECTION_LONGEVITY("Longevity Analysis", "दीर्घायु विश्लेषण"),
SECTION_BODY_MAPPING("Body Part Mapping", "शरीर अंग म्यापिङ"),
SECTION_PREVENTIVE("Preventive Focus", "रोकथाम फोकस"),
CONSTITUTION_TITLE("Ayurvedic Constitution", "आयुर्वेदिक संविधान"),
PRIMARY_DOSHA("Primary Dosha", "प्राथमिक दोष"),
SECONDARY_DOSHA("Secondary Dosha", "माध्यमिक दोष"),
DOSHA_BALANCE("Dosha Balance", "दोष सन्तुलन"),
DOSHA_VATA("Vata Dosha", "वात दोष"),
DOSHA_PITTA("Pitta Dosha", "पित्त दोष"),
DOSHA_KAPHA("Kapha Dosha", "कफ दोष"),
CONSTITUTION_DESC("Constitution Description", "संविधान विवरण"),
DIETARY_RECS("Dietary Recommendations", "आहार सिफारिसहरू"),
LIFESTYLE_RECS("Lifestyle Recommendations", "जीवनशैली सिफारिसहरू"),
EXERCISE_RECS("Exercise Recommendations", "व्यायाम सिफारिसहरू"),
SIXTH_HOUSE_SIGN("6th House Sign", "षष्ठ भाव राशि"),
SIXTH_HOUSE_LORD("6th House Lord", "षष्ठ भाव स्वामी"),
SIXTH_HOUSE_PLANETS("Planets in 6th House", "षष्ठ भावमा ग्रहहरू"),
DISEASE_RESISTANCE("Disease Resistance", "रोग प्रतिरोध"),
IMMUNE_SYSTEM("Immune System Profile", "प्रतिरक्षा प्रणाली प्रोफाइल"),
POTENTIAL_AILMENTS("Potential Ailments", "सम्भावित रोगहरू"),
HEALING_CAPACITY("Healing Capacity", "उपचार क्षमता"),
EIGHTH_HOUSE_SIGN("8th House Sign", "अष्टम भाव राशि"),
EIGHTH_HOUSE_LORD("8th House Lord", "अष्टम भाव स्वामी"),
EIGHTH_HOUSE_PLANETS("Planets in 8th House", "अष्टम भावमा ग्रहहरू"),
CHRONIC_PATTERNS("Chronic Health Patterns", "दीर्घकालीन स्वास्थ्य ढाँचाहरू"),
REGENERATIVE_CAPACITY("Regenerative Capacity", "पुनर्जनन क्षमता"),
CRITICAL_PERIODS("Critical Health Periods", "महत्वपूर्ण स्वास्थ्य अवधिहरू"),
ASCENDANT_HEALTH("Ascendant Health Profile", "लग्न स्वास्थ्य प्रोफाइल"),
GENERAL_VITALITY("General Vitality", "सामान्य जीवनी शक्ति"),
PHYSICAL_CONSTITUTION("Physical Constitution", "शारीरिक संविधान"),
INNATE_PROWESS("Innate Physical Prowess", "जन्मजात शारीरिक शक्ति"),
BODY_FRAME("Body Frame", "शरीर फ्रेम"),
METABOLIC_TYPE("Metabolic Type", "चयापचय प्रकार"),
PLANET_HEALTH_TITLE("Planetary Health Influences", "ग्रहीय स्वास्थ्य प्रभावहरू"),
SUN_HEALTH("Sun Health Influence", "सूर्य स्वास्थ्य प्रभाव"),
MOON_HEALTH("Moon Health Influence", "चन्द्रमा स्वास्थ्य प्रभाव"),
MARS_HEALTH("Mars Health Influence", "मंगल स्वास्थ्य प्रभाव"),
MERCURY_HEALTH("Mercury Health Influence", "बुध स्वास्थ्य प्रभाव"),
JUPITER_HEALTH("Jupiter Health Influence", "बृहस्पति स्वास्थ्य प्रभाव"),
VENUS_HEALTH("Venus Health Influence", "शुक्र स्वास्थ्य प्रभाव"),
SATURN_HEALTH("Saturn Health Influence", "शनि स्वास्थ्य प्रभाव"),
BODY_HEAD("Head & Face", "टाउको र अनुहार"),
BODY_THROAT("Throat & Neck", "घाँटी र घाँटी"),
BODY_ARMS("Arms & Shoulders", "हातहरू र काँधहरू"),
BODY_CHEST("Chest & Heart", "छाती र मुटु"),
BODY_STOMACH("Stomach & Digestion", "पेट र पाचन"),
BODY_INTESTINES("Intestines", "आन्द्राहरू"),
BODY_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
BODY_REPRODUCTIVE("Reproductive System", "प्रजनन प्रणाली"),
BODY_THIGHS("Thighs", "थाईहरू"),
BODY_KNEES("Knees", "घुँडाहरू"),
BODY_ANKLES("Ankles & Calves", "गोलीगाँठाहरू र पिँडौलाहरू"),
BODY_FEET("Feet", "खुट्टाहरू"),
VULNERABILITIES_TITLE("Health Vulnerabilities", "स्वास्थ्य कमजोरीहरू"),
VULNERABILITY_AREA("Vulnerable Area", "कमजोर क्षेत्र"),
VULNERABILITY_SEVERITY("Severity Level", "गम्भीरता स्तर"),
PREVENTIVE_MEASURES("Preventive Measures", "रोकथाम उपायहरू"),
HEALTH_STRENGTHS("Health Strengths", "स्वास्थ्य शक्तिहरू"),
ROBUST_AREAS("Robust Health Areas", "बलियो स्वास्थ्य क्षेत्रहरू"),
PRIORITY_AREAS("Priority Focus Areas", "प्राथमिकता फोकस क्षेत्रहरू"),
SEASONAL_GUIDELINES("Seasonal Health Guidelines", "मौसमी स्वास्थ्य दिशानिर्देशहरू"),
YOGA_PRACTICES("Yoga Practices", "योग अभ्यासहरू"),
AYURVEDIC_RECS("Ayurvedic Recommendations", "आयुर्वेदिक सिफारिसहरू"),
HEALTH_TIMELINE("Health Timeline", "स्वास्थ्य समयरेखा"),
CURRENT_HEALTH_PHASE("Current Health Phase", "वर्तमान स्वास्थ्य चरण"),
DASHA_HEALTH_FOCUS("Dasha Period Health Focus", "दशा अवधि स्वास्थ्य फोकस"),
HEALTH_CONCERN_AREAS("Health Concern Areas", "स्वास्थ्य चिन्ता क्षेत्रहरू"),
LONGEVITY_TITLE("Longevity Profile", "दीर्घायु प्रोफाइल"),
LONGEVITY_CATEGORY("Longevity Category", "दीर्घायु श्रेणी"),
LONGEVITY_SHORT("Short Lifespan Indicators", "छोटो आयु सूचकहरू"),
LONGEVITY_MEDIUM("Medium Lifespan Indicators", "मध्यम आयु सूचकहरू"),
LONGEVITY_LONG("Long Lifespan Indicators", "लामो आयु सूचकहरू"),
SUPPORTING_FACTORS("Supporting Longevity Factors", "दीर्घायु समर्थन कारकहरू"),
CHALLENGING_FACTORS("Challenging Factors", "चुनौतीपूर्ण कारकहरू"),
HEALTH_SUMMARY("Health Summary", "स्वास्थ्य सारांश"),
HEALTH_SCORE("Health Strength Score", "स्वास्थ्य शक्ति स्कोर"),
HEALTH_ADVICE("Health Advice", "स्वास्थ्य सल्लाह")
}
