package com.astro.storm.core.common

enum class StringKeyGeneralPart10(override val en: String, override val ne: String) : StringKeyInterface {
    SANDHI_RELATIONSHIP_IMPACT("Relationship Impact", "सम्बन्ध प्रभाव"),
    SANDHI_REMEDIES("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
    SANDHI_SCREEN_TITLE("Dasha Sandhi", "दशा सन्धि"),
    SANDHI_SPIRITUAL("Spiritual Opportunities", "आध्यात्मिक अवसरहरू"),
    SANDHI_SUBTITLE("Period Junction Analysis", "अवधि जोड विश्लेषण"),
    SANDHI_TITLE("Dasha Sandhi Analysis", "दशा सन्धि विश्लेषण"),
    SANDHI_TO_PLANET("To", "मा"),
    SANDHI_TRANSITION("Transition", "संक्रमण"),
    SANDHI_UPCOMING("Upcoming Sandhis", "आगामी सन्धिहरू"),
    SANDHI_VOLATILITY("Volatility Score", "अस्थिरता स्कोर"),
    SANDHI_VOLATILITY_DESC("Based on current and upcoming period transitions", "वर्तमान र आगामी दशा परिवर्तनहरूमा आधारित"),
    SAPTAVARGA_BALA("Saptavarga Bala (7-Varga)", "सप्तवर्ग बल (७-वर्ग)"),
    SARVATOBHADRA_ANALYZING("Analyzing Sarvatobhadra Chakra...", "सर्वतोभद्र चक्र विश्लेषण गर्दै..."),
    SARVATOBHADRA_ASSOCIATED_VOWEL("Associated Vowel", "सम्बन्धित स्वर"),
    SARVATOBHADRA_BENEFIC("Benefic", "शुभ"),
    SARVATOBHADRA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    SARVATOBHADRA_CENTER("Center", "केन्द्र"),
    SARVATOBHADRA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    SARVATOBHADRA_CURRENT_TITHI("Current Tithi", "वर्तमान तिथि"),
    SARVATOBHADRA_CURRENT_TRANSITS("Current Transit Vedhas", "वर्तमान गोचर वेधहरू"),
    SARVATOBHADRA_DAY_QUALITY("Day Quality", "दिनको गुणस्तर"),
    SARVATOBHADRA_DESC("Traditional Vedha chakra for transit analysis, muhurta selection, and name compatibility", "गोचर विश्लेषण, मुहूर्त चयन, र नाम अनुकूलताको लागि परम्परागत वेध चक्र"),
    SARVATOBHADRA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल कार्यहरू"),
    SARVATOBHADRA_FAVORABLE_DAYS("Favorable Days", "अनुकूल दिनहरू"),
    SARVATOBHADRA_FAVORABLE_NAKSHATRAS("Favorable Nakshatras", "अनुकूल नक्षत्रहरू"),
    SARVATOBHADRA_FIRST_LETTER("First Letter", "पहिलो अक्षर"),
    SARVATOBHADRA_FULL_VEDHA("Full Vedha", "पूर्ण वेध"),
    SARVATOBHADRA_HALF_VEDHA("Half Vedha", "आधा वेध"),
    SARVATOBHADRA_HIGHLY_FAVORABLE("Highly Favorable", "अत्यन्त अनुकूल"),
    SARVATOBHADRA_INFO_DESC("Sarvatobhadra Chakra is a 9×9 grid showing relationships between nakshatras, vowels, weekdays, and tithis. It's used for transit analysis, muhurta selection, and name compatibility through vedha (obstruction) calculations.", "सर्वतोभद्र चक्र नक्षत्र, स्वर, वार, र तिथिहरू बीचको सम्बन्ध देखाउने ९×९ ग्रिड हो। यो वेध (अवरोध) गणनाहरू मार्फत गोचर विश्लेषण, मुहूर्त चयन, र नाम अनुकूलताको लागि प्रयोग गरिन्छ।"),
    SARVATOBHADRA_INFO_TITLE("About Sarvatobhadra Chakra", "सर्वतोभद्र चक्रको बारेमा"),
    SARVATOBHADRA_MALEFIC("Malefic", "अशुभ"),
    SARVATOBHADRA_MIXED("Mixed", "मिश्रित"),
    SARVATOBHADRA_MODERATELY_FAVORABLE("Moderately Favorable", "मध्यम अनुकूल"),
    SARVATOBHADRA_MOON_NAKSHATRA("Moon Nakshatra", "चन्द्र नक्षत्र"),
    SARVATOBHADRA_NAKSHATRA("Nakshatra", "नक्षत्र"),
    SARVATOBHADRA_NAME_ANALYSIS("Name Analysis", "नाम विश्लेषण"),
    SARVATOBHADRA_NEUTRAL("Neutral", "तटस्थ"),
    SARVATOBHADRA_NO_VEDHA("No Vedha", "वेध छैन"),
    SARVATOBHADRA_OVERALL_SCORE("Overall Score", "समग्र स्कोर"),
    SARVATOBHADRA_PLANETARY_INFLUENCE("Planetary Influence", "ग्रह प्रभाव"),
    SARVATOBHADRA_QUARTER_VEDHA("Quarter Vedha", "चौथाई वेध"),
    SARVATOBHADRA_SUBTITLE("9×9 Transit & Muhurta Chakra", "९×९ गोचर र मुहूर्त चक्र"),
    SARVATOBHADRA_TAB_CHAKRA("Chakra", "चक्र"),
    SARVATOBHADRA_TAB_DAILY("Daily", "दैनिक"),
    SARVATOBHADRA_TAB_NAME("Name", "नाम"),
    SARVATOBHADRA_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    SARVATOBHADRA_TAB_VEDHA("Vedhas", "वेधहरू"),
    SARVATOBHADRA_THREE_QUARTER_VEDHA("3/4 Vedha", "३/४ वेध"),
    SARVATOBHADRA_TITHI("Tithi", "तिथि"),
    SARVATOBHADRA_TITLE("Sarvatobhadra Chakra", "सर्वतोभद्र चक्र"),
    SARVATOBHADRA_TODAY("Today's Analysis", "आजको विश्लेषण"),
    SARVATOBHADRA_TRANSIT_SCORE("Transit Score", "गोचर स्कोर"),
    SARVATOBHADRA_UNABLE("Unable to calculate Sarvatobhadra", "सर्वतोभद्र गणना गर्न सकिएन"),
    SARVATOBHADRA_UNFAVORABLE_ACTIVITIES("Avoid Today", "आज नगर्नुहोस्"),
    SARVATOBHADRA_UNFAVORABLE_DAYS("Unfavorable Days", "प्रतिकूल दिनहरू"),
    SARVATOBHADRA_UNFAVORABLE_NAKSHATRAS("Unfavorable Nakshatras", "प्रतिकूल नक्षत्रहरू"),
    SARVATOBHADRA_VEDIC_REF("Vedic Reference: Muhurta Chintamani, Muhurta Martanda", "वैदिक सन्दर्भ: मुहूर्त चिन्तामणि, मुहूर्त मार्तण्ड"),
    SARVATOBHADRA_VOWEL("Vowel", "स्वर"),
    SARVATOBHADRA_WEEKDAY("Weekday", "वार"),
    SATISFIED("Satisfied", "सन्तुष्ट"),
    SATURN_HEALTH("Saturn Health Influence", "शनि स्वास्थ्य प्रभाव"),
    SATURN_TRANSIT("Saturn Transit", "शनि गोचर"),
    SAVINGS_ABILITY("Savings Ability", "बचत क्षमता"),
    SCORE_AVERAGE("Average compatibility. Score of 18-20 requires attention to problem areas and remedies.", "औसत अनुकूलता। १८-२० को अंकले समस्या क्षेत्रहरू र उपायहरूमा ध्यान आवश्यक पर्छ।"),
    SCORE_AVERAGE_GUIDANCE("Your compatibility is moderate with several areas requiring conscious effort and adjustment. While the match is acceptable, success depends on both partners' willingness to work through differences. Identify specific problem areas (especially low-scoring gunas) and actively address them. Consider performing recommended Vedic remedies to strengthen weak areas. Pre-marital counseling is strongly advised to establish communication patterns and conflict resolution strategies. With dedication and mutual respect, this relationship can thrive.", "तपाईंको अनुकूलता सचेत प्रयास र समायोजन आवश्यक पर्ने धेरै क्षेत्रहरूसहित मध्यम छ। मिलान स्वीकार्य भए पनि, सफलता दुवै साझेदारहरूको भिन्नताहरू समाधान गर्ने इच्छामा निर्भर गर्दछ। विशेष समस्या क्षेत्रहरू (विशेष गरी कम अंक पाएका गुणहरू) पहिचान गर्नुहोस् र सक्रिय रूपमा सम्बोधन गर्नुहोस्। कमजोर क्षेत्रहरूलाई बलियो बनाउन सिफारिस गरिएका वैदिक उपायहरू गर्ने विचार गर्नुहोस्। सञ्चार ढाँचा र द्वन्द्व समाधान रणनीतिहरू स्थापना गर्न विवाह-पूर्व परामर्श दृढतापूर्वक सल्लाह दिइन्छ। समर्पण र पारस्परिक सम्मानका साथ, यो सम्बन्ध फस्टाउन सक्छ।"),
    SCORE_BELOW_AVERAGE("Below average compatibility. Score of 14-17 indicates significant challenges requiring serious consideration.", "औसतमुनि अनुकूलता। १४-१७ को अंकले गम्भीर विचार आवश्यक पर्ने महत्त्वपूर्ण चुनौतीहरू संकेत गर्दछ।"),
    SCORE_BELOW_AVERAGE_GUIDANCE("Your compatibility score indicates notable challenges across multiple dimensions. This match faces significant obstacles that require serious consideration before proceeding. Multiple gunas showing low scores suggest fundamental differences in temperament, values, or life approaches. Extensive Vedic remedies are essential - consult a qualified Vedic astrologer for a comprehensive remedy plan. Professional couples counseling is strongly recommended. Both partners must be willing to make substantial adjustments and compromises. Carefully evaluate whether both are prepared for the level of conscious effort required to build a harmonious relationship.", "तपाईंको अनुकूलता अंकले विभिन्न आयामहरूमा उल्लेखनीय चुनौतीहरू संकेत गर्दछ। यो मिलानले अगाडि बढ्नु अघि गम्भीर विचार आवश्यक पर्ने महत्त्वपूर्ण बाधाहरूको सामना गर्दछ। धेरै गुणहरूले कम अंक देखाउनुले स्वभाव, मूल्यहरू वा जीवन दृष्टिकोणमा आधारभूत भिन्नताहरू सुझाव दिन्छ। व्यापक वैदिक उपायहरू आवश्यक छन् - व्यापक उपाय योजनाको लागि योग्य वैदिक ज्योतिषीसँग परामर्श गर्नुहोस्। पेशेवर जोडी परामर्श दृढतापूर्वक सिफारिस गरिएको छ। दुवै साझेदारहरू पर्याप्त समायोजन र सम्झौता गर्न इच्छुक हुनुपर्छ। सामञ्जस्यपूर्ण सम्बन्ध निर्माण गर्न आवश्यक सचेत प्रयासको स्तरको लागि दुवै तयार छन् कि छैनन् भनेर सावधानीपूर्वक मूल्याङ्कन गर्नुहोस्।"),
    SCORE_EXCELLENT("Excellent match! Score above 28 indicates highly favorable compatibility across all dimensions.", "उत्कृष्ट मिलान! २८ माथिको अंकले सबै आयामहरूमा अत्यन्त अनुकूल अनुकूलता संकेत गर्दछ।"),
    SCORE_EXCELLENT_GUIDANCE("Your compatibility across spiritual, mental, physical, and temperamental dimensions is outstanding. You share compatible values, communication styles, and life goals. This union has the blessings of celestial alignments. Focus on maintaining open communication and mutual respect to nurture this harmonious connection throughout your married life.", "तपाईंको आध्यात्मिक, मानसिक, शारीरिक र स्वभावगत आयामहरूमा अनुकूलता उत्कृष्ट छ। तपाईं अनुकूल मूल्यहरू, सञ्चार शैली र जीवन लक्ष्यहरू साझा गर्नुहुन्छ। यस संघमा आकाशीय संरेखणको आशीर्वाद छ। आफ्नो वैवाहिक जीवनभर यो सामञ्जस्यपूर्ण सम्बन्धलाई पोषण गर्न खुला सञ्चार र पारस्परिक सम्मान कायम राख्नमा ध्यान दिनुहोस्।"),
    SCORE_GOOD("Good match. Score of 21-27 suggests strong compatibility with minor areas to work on.", "राम्रो मिलान। २१-२७ को अंकले काम गर्नुपर्ने सानातिना क्षेत्रहरूसहित बलियो अनुकूलता सुझाव दिन्छ।"),
    SCORE_GOOD_GUIDANCE("You have strong overall compatibility with good harmony in most areas. While there are some minor differences, these can be easily managed through mutual understanding and effort. The relationship has solid foundations for a successful marriage. Focus on conscious communication, especially in areas where gunas scored lower. Regular discussions about expectations and compromise will strengthen your bond.", "तपाईं धेरै क्षेत्रहरूमा राम्रो सामञ्जस्यसहित बलियो समग्र अनुकूलता राख्नुहुन्छ। यद्यपि केही सानातिना भिन्नताहरू छन्, यी पारस्परिक बुझाइ र प्रयासद्वारा सजिलैसँग व्यवस्थापन गर्न सकिन्छ। सम्बन्धमा सफल विवाहको लागि ठोस आधारहरू छन्। सचेत सञ्चारमा ध्यान दिनुहोस्, विशेष गरी ती क्षेत्रहरूमा जहाँ गुणहरूले कम अंक पाएको छ। अपेक्षाहरू र सम्झौताको बारेमा नियमित छलफलले तपाईंको बन्धनलाई बलियो बनाउनेछ।"),
    SCORE_POOR("Poor compatibility. Score below 14 suggests major challenges. Marriage not recommended without extensive remedies.", "कमजोर अनुकूलता। १४ मुनिको अंकले प्रमुख चुनौतीहरू सुझाव दिन्छ। व्यापक उपायहरू बिना विवाह सिफारिस गरिएको छैन।"),
    SCORE_POOR_GUIDANCE("This match shows poor compatibility with fundamental incompatibilities across critical areas. Traditional Vedic astrology does not recommend proceeding with this marriage without addressing severe issues. The low score suggests conflicts in temperament, values, physical harmony, and mental compatibility. If you choose to proceed despite this assessment, the following are absolutely essential: 1) Consult multiple qualified Vedic astrologers for comprehensive remedy plans 2) Perform all recommended pujas, homas, and remedial measures diligently 3) Undergo extensive pre-marital and ongoing couples counseling 4) Both partners must have extraordinary commitment to conscious relationship work 5) Prepare for ongoing challenges requiring patience, tolerance, and spiritual growth. Consider whether alternative matches might offer better foundations for marital happiness.", "यो मिलानले महत्त्वपूर्ण क्षेत्रहरूमा आधारभूत असंगतताहरूसहित कमजोर अनुकूलता देखाउँछ। परम्परागत वैदिक ज्योतिष गम्भीर समस्याहरू सम्बोधन नगरी यस विवाहसँग अगाडि बढ्न सिफारिस गर्दैन। कम अंकले स्वभाव, मूल्यहरू, शारीरिक सामञ्जस्य र मानसिक अनुकूलतामा द्वन्द्व सुझाव दिन्छ। यदि तपाईं यस मूल्याङ्कनको बावजुद अगाडि बढ्न रोज्नुहुन्छ भने, निम्न कुराहरू एकदमै आवश्यक छन्: १) व्यापक उपाय योजनाको लागि धेरै योग्य वैदिक ज्योतिषीहरूसँग परामर्श गर्नुहोस् २) सबै सिफारिस गरिएका पूजा, होम र उपचारात्मक उपायहरू लगनशीलताका साथ गर्नुहोस् ३) व्यापक विवाह-पूर्व र निरन्तर जोडी परामर्श लिनुहोस् ४) दुवै साझेदारहरूसँग सचेत सम्बन्ध कार्यको लागि असाधारण प्रतिबद्धता हुनुपर्छ ५) धैर्य, सहनशीलता र आध्यात्मिक विकास आवश्यक पर्ने निरन्तर चुनौतीहरूको लागि तयार रहनुहोस्। वैकल्पिक मिलानहरूले वैवाहिक खुशीको लागि राम्रो आधारहरू प्रदान गर्न सक्छन् कि भनेर विचार गर्नुहोस्।"),
    SEARCH_SAHAMS("Search Sahams...", "सहमहरू खोज्नुहोस्..."),
    SEASONAL_GUIDELINES("Seasonal Health Guidelines", "मौसमी स्वास्थ्य दिशानिर्देशहरू"),
    SECONDARY_DOSHA("Secondary Dosha", "माध्यमिक दोष"),
    SECONDARY_INDICATORS("Secondary Career Indicators", "माध्यमिक क्यारियर सूचकहरू"),
    SECONDARY_LABEL("Secondary", "माध्यमिक"),
    SECONDARY_SOURCES("Secondary Wealth Sources", "माध्यमिक धन स्रोतहरू"),
    SECOND_HOUSE_LORD("2nd House Lord", "द्वितीय भाव स्वामी"),
    SECOND_HOUSE_PLANETS("Planets in 2nd House", "द्वितीय भावमा ग्रहहरू"),
    SECOND_HOUSE_SIGN("2nd House Sign", "द्वितीय भाव राशि"),
    SELECT_CHART_MESSAGE("Please select a birth chart to view Sahams", "सहमहरू हेर्न कृपया जन्म कुण्डली छान्नुहोस्"),
    SENSITIVE_DEGREES_AUSPICIOUS("Auspicious Planets", "शुभ ग्रहहरू"),
    SENSITIVE_DEGREES_BALANCED("Balanced", "सन्तुलित"),
    SENSITIVE_DEGREES_CRITICAL("Critical Planets", "महत्त्वपूर्ण ग्रहहरू"),
    SENSITIVE_DEGREES_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यधिक शुभ"),
    SENSITIVE_DEGREES_MODERATE_CONCERN("Moderate Concern", "मध्यम चिन्ता"),
    SENSITIVE_DEGREES_NEEDS_ATTENTION("Needs Attention", "ध्यान आवश्यक"),
    SENSITIVE_DEGREES_POSITIVE("Generally Positive", "सामान्यतया सकारात्मक"),
    SERVICE_VS_BUSINESS("Service vs Business", "सेवा बनाम व्यापार"),
    SETTINGS_ABOUT("About", "बारेमा"),
    SETTINGS_ABOUT_APP("About AstroStorm", "AstroStorm बारेमा"),
    SETTINGS_AI_CHAT("AI & Chat", "AI र च्याट"),
    SETTINGS_AI_MODELS("AI Models", "AI मोडेलहरू"),
    SETTINGS_AI_MODELS_DESC("Configure chat AI providers", "च्याट AI प्रदायकहरू कन्फिगर गर्नुहोस्"),
    SETTINGS_APP_DESC("Powered by Swiss Ephemeris with JPL planetary data for astronomical-grade accuracy in all calculations.", "सबै गणनाहरूमा खगोलीय-ग्रेड सटीकताको लागि JPL ग्रह डाटासहित स्विस ईफेमेरिसद्वारा संचालित।"),
    SETTINGS_APP_TAGLINE("Ultra-Precision Vedic Astrology", "अति-सटीक वैदिक ज्योतिष"),
    SETTINGS_AYANAMSA("Ayanamsa", "अयनांश"),
    SETTINGS_CALC_ENGINE("Calculation Engine", "गणना इन्जिन"),
    SETTINGS_CALC_ENGINE_DESC("Swiss Ephemeris (JPL Mode)", "स्विस ईफेमेरिस (JPL मोड)"),
    SETTINGS_DATE_SYSTEM("Date System", "मिति प्रणाली"),
    SETTINGS_EDIT_PROFILE("Edit Profile", "प्रोफाइल सम्पादन"),
    SETTINGS_EDIT_PROFILE_DESC("Modify birth details", "जन्म विवरण परिमार्जन गर्नुहोस्"),
    SETTINGS_EXPORT("Export", "निर्यात"),
    SETTINGS_EXPORT_CSV("CSV Data", "CSV डाटा"),
    SETTINGS_EXPORT_CSV_DESC("Spreadsheet format", "स्प्रेडसिट ढाँचा"),
    SETTINGS_EXPORT_IMAGE("Export as Image", "छविको रूपमा निर्यात"),
    SETTINGS_EXPORT_IMAGE_DESC("High-quality chart image", "उच्च गुणस्तर कुण्डली छवि"),
    SETTINGS_EXPORT_JSON("Export as JSON", "JSON को रूपमा निर्यात"),
    SETTINGS_EXPORT_JSON_DESC("Machine-readable format", "मेसिन-पठनयोग्य ढाँचा"),
    SETTINGS_EXPORT_PDF("Export as PDF", "PDF को रूपमा निर्यात"),
    SETTINGS_EXPORT_PDF_DESC("Complete chart report", "पूर्ण कुण्डली रिपोर्ट"),
    SETTINGS_HOUSE_SYSTEM("House System", "भाव पद्धति"),
    SETTINGS_LAHIRI("Lahiri Ayanamsa", "लहिरी अयनांश"),
    SETTINGS_LANGUAGE("Language", "भाषा"),
    SETTINGS_MANAGE_PROFILES("Manage Profiles", "प्रोफाइलहरू व्यवस्थापन"),
    SETTINGS_NODE_CALCULATION("Node Calculation", "राहु-केतु गणना"),
    SETTINGS_NODE_MEAN("Mean Node", "मध्यम राहु"),
    SETTINGS_NODE_TRUE("True Node", "स्पष्ट राहु"),
    SETTINGS_NO_PROFILE("No profile selected", "कुनै प्रोफाइल छानिएको छैन"),
    SETTINGS_PLACIDUS("Placidus Houses", "प्लासिडस भावहरू"),
    SETTINGS_PREFERENCES("Preferences", "प्राथमिकताहरू"),
    SETTINGS_PROFILE("Profile", "प्रोफाइल"),
    SETTINGS_TAP_TO_SELECT("Tap to select or create a profile", "प्रोफाइल छान्न वा बनाउन ट्याप गर्नुहोस्"),
    SETTINGS_THEME("Theme", "थिम"),
    SETTINGS_THEME_TITLE("Theme", "थीम"),
    SETTINGS_VERSION("Version %s", "संस्करण %s"),
    SEVENTH_HOUSE_ASPECTS("Aspects to 7th House", "सप्तम भावमा दृष्टिहरू"),
    SEVENTH_HOUSE_LORD("7th House Lord", "सप्तम भाव स्वामी"),
    SEVENTH_HOUSE_PLANETS("Planets in 7th House", "सप्तम भावमा ग्रहहरू"),
    SEVENTH_HOUSE_SIGN("7th House Sign", "सप्तम भाव राशि"),
    SEVENTH_HOUSE_STRENGTH("7th House Strength", "सप्तम भाव बल"),
    SEVERITY_INTENSE("Intense", "तीव्र"),
    SEVERITY_MILD("Mild", "हल्का"),
    SEVERITY_MODERATE("Moderate", "मध्यम"),
    SEVERITY_SIGNIFICANT("Significant", "महत्त्वपूर्ण"),
    SHADVARGA_BALA("Shadvarga Bala (6-Varga)", "षड्वर्ग बल (६-वर्ग)"),
    SHELLS("Shells", "कौडीहरू"),
    SHORT_DESC_BHADRA("Intelligence, communication, commerce", "बुद्धि, सञ्चार, वाणिज्य"),
    SHORT_DESC_HAMSA("Wisdom, spirituality, fortune", "ज्ञान, आध्यात्मिकता, भाग्य"),
    SHORT_DESC_MALAVYA("Beauty, luxury, artistic talents", "सौन्दर्य, विलासिता, कलात्मक प्रतिभा"),
    SHORT_DESC_RUCHAKA("Courage, leadership, physical prowess", "साहस, नेतृत्व, शारीरिक पराक्रम"),
    SHORT_DESC_SASHA("Discipline, authority, longevity", "अनुशासन, अधिकार, दीर्घायु"),
    SHORT_TERM("Short Term Outlook", "छोटो अवधि दृष्टिकोण"),
    SHOW_INFO("Show information", "जानकारी देखाउनुहोस्"),
    SIGN_AQUARIUS("Aquarius", "कुम्भ"),
    SIGN_ARIES("Aries", "मेष"),
    SIGN_CANCER("Cancer", "कर्कट"),
    SIGN_CAPRICORN("Capricorn", "मकर"),
    SIGN_GEMINI("Gemini", "मिथुन"),
    SIGN_LABEL("Sign", "राशि"),
    SIGN_LEO("Leo", "सिंह"),
    SIGN_LIBRA("Libra", "तुला"),
    SIGN_PISCES("Pisces", "मीन"),
    SIGN_SAGITTARIUS("Sagittarius", "धनु"),
    SIGN_SCORPIO("Scorpio", "वृश्चिक"),
    SIGN_TAURUS("Taurus", "वृष"),
    SIGN_VIRGO("Virgo", "कन्या"),
    SIG_1("Self, personality, health - the native's foundation", "स्वयं, व्यक्तित्व, स्वास्थ्य - जातकको आधार"),
    SIG_10("Career, status, karma - worldly achievement", "करियर, प्रतिष्ठा, कर्म - सांसारिक उपलब्धि"),
    SIG_11("Gains, income, aspirations - fulfillment", "लाभ, आय, आकांक्षाहरू - प्राप्ति"),
    SIG_12("Losses, moksha, foreign - spiritual liberation", "हानि, मोक्ष, विदेश - आध्यात्मिक मुक्ति"),
    SIG_2("Wealth, family, speech - material foundation", "धन, परिवार, वाणी - भौतिक आधार"),
    SIG_3("Siblings, courage, communication - personal effort", "भाइबहिनी, साहस, सञ्चार - व्यक्तिगत प्रयास"),
    SIG_4("Mother, property, happiness - emotional foundation", "आमा, सम्पत्ति, सुख - भावनात्मक आधार"),
    SIG_5("Children, intelligence, past merit - creative expression", "सन्तान, बुद्धि, पूर्व पुण्य - सिर्जनात्मक अभिव्यक्ति"),
    SIG_6("Enemies, disease, service - challenges to overcome", "शत्रु, रोग, सेवा - पार गर्नुपर्ने चुनौतीहरू"),
    SIG_7("Marriage, partnership, public - relationships", "विवाह, साझेदारी, सार्वजनिक - सम्बन्ध"),
    SIG_8("Longevity, inheritance, occult - transformation", "दीर्घायु, पैतृक सम्पत्ति, तन्त्र - रूपान्तरण"),
    SIG_9("Fortune, father, dharma - blessings and guidance", "भाग्य, बुबा, धर्म - आशीर्वाद र मार्गदर्शन"),
    SIG_GEN("General house matters", "सामान्य भावका मामिलाहरू"),
    SIXTH_HOUSE_LORD("6th House Lord", "षष्ठ भाव स्वामी"),
    SIXTH_HOUSE_PLANETS("Planets in 6th House", "षष्ठ भावमा ग्रहहरू"),
    SIXTH_HOUSE_SIGN("6th House Sign", "षष्ठ भाव राशि"),
    SMALL_PANOTI_ACTIVE_SUMMARY("{type} is active", "{type} सक्रिय छ"),
    SMALL_PANOTI_EIGHTH("Ashtama Shani (8th from Moon)", "अष्टम शनि (चन्द्रबाट ८औं)"),
    SMALL_PANOTI_FOURTH("Kantak Shani (4th from Moon)", "कण्टक शनि (चन्द्रबाट ४औं)"),
    SOCIAL_CHALLENGES("Social Challenges", "सामाजिक चुनौतीहरू"),
    SOCIAL_ORIENTATION("Social Orientation", "सामाजिक अभिमुखीकरण"),
    SOCIAL_STRENGTHS("Social Strengths", "सामाजिक शक्तिहरू"),
    SOCIAL_TITLE("Social Profile", "सामाजिक प्रोफाइल"),
    SOURCE_BUSINESS("Business Income", "व्यापार आय"),
    SOURCE_CAREER("Career Earnings", "क्यारियर आय"),
    SOURCE_FOREIGN("Foreign Earnings", "विदेशी आय"),
    SOURCE_INHERITANCE("Inheritance", "विरासत"),
    SOURCE_PARTNERSHIP("Partnership Income", "साझेदारी आय"),
    SOURCE_PROPERTY("Property & Real Estate", "सम्पत्ति र अचल सम्पत्ति"),
    SOURCE_SPECULATION("Speculation & Investments", "सट्टेबाजी र लगानी"),
    SOURCE_UNEXPECTED("Unexpected Gains", "अप्रत्याशित लाभ"),
    SPECIAL_7TH_LORDS_ENEMY("7TH HOUSE LORDS INCOMPATIBLE: {lord1} and {lord2} are mutual enemies. Marriage house lords in conflict.", "७औं भाव स्वामी असंगत: {lord1} र {lord2} पारस्परिक शत्रु हुन्। विवाह भाव स्वामीहरू द्वन्द्वमा।"),
    SPECIAL_BHAKOOT_DOSHA("BHAKOOT DOSHA present: {analysis}. May affect love, finances, or health.", "भकुट दोष उपस्थित: {analysis}। प्रेम, वित्त, वा स्वास्थ्यमा असर पर्न सक्छ।"),
    SPECIAL_BRIDE_MANGLIK("MANGLIK IMBALANCE: Bride has {dosha} while Groom is non-Manglik. Kumbh Vivah or remedies strongly advised.", "मांगलिक असन्तुलन: दुलहीमा {dosha} छ जबकि दुलाहा गैर-मांगलिक छन्। कुम्भ विवाह वा उपायहरू दृढतापूर्वक सल्लाह दिइएको।"),
    SPECIAL_GANA_INCOMPAT("GANA INCOMPATIBILITY: Opposite temperaments (Deva-Rakshasa). May cause frequent conflicts without conscious effort.", "गण असंगतता: विपरीत स्वभाव (देव-राक्षस)। सचेत प्रयास बिना बारम्बार द्वन्द्व हुन सक्छ।"),
    SPECIAL_GROOM_MANGLIK("MANGLIK IMBALANCE: Groom has {dosha} while Bride is non-Manglik. Remedies strongly recommended.", "मांगलिक असन्तुलन: दुलाहामा {dosha} छ जबकि दुलही गैर-मांगलिक छिन्। उपायहरू दृढतापूर्वक सिफारिस गरिएको।"),
    SPECIAL_HEALTH_RECOVERY("Health Recovery", "स्वास्थ्य सुधार"),
    SPECIAL_INSIGHTS("Special Insights", "विशेष अन्तर्दृष्टि"),
    SPECIAL_LITIGATION_WIN("Litigation Success", "मुद्दामा जित"),
    SPECIAL_LOST_DIRECTION("Lost Object Direction", "हराएको वस्तुको दिशा"),
    SPECIAL_LOST_RECOVERY("Recovery Possibility", "प्राप्ति सम्भावना"),
    SPECIAL_MARRIAGE_TIMING("Marriage Timing", "विवाह समय"),
    SPECIAL_MULTIPLE_LOW("MULTIPLE CONCERNS: {count} Gunas scored below threshold. Overall compatibility requires attention.", "बहु चिन्ताहरू: {count} गुणले न्यूनतम भन्दा कम अंक पाए। समग्र अनुकूलतामा ध्यान आवश्यक।"),
    SPECIAL_NADI_DOSHA("NADI DOSHA: Same Nadi can affect health and progeny. Consider remedies before proceeding.", "नाडी दोष: उही नाडीले स्वास्थ्य र सन्तानमा असर पार्न सक्छ। अगाडि बढ्नु अघि उपायहरू विचार गर्नुहोस्।"),
    SPECIAL_NO_ISSUES("No significant special concerns noted. The match appears harmonious across additional factors.", "कुनै महत्त्वपूर्ण विशेष चिन्ता छैन। मिलान अतिरिक्त कारकहरूमा सामञ्जस्यपूर्ण देखिन्छ।"),
    SPECIAL_RAJJU("RAJJU DOSHA: {details}. Related body part may face health concerns in marriage.", "रज्जु दोष: {details}। सम्बन्धित शरीर भागमा विवाहमा स्वास्थ्य चिन्ता हुन सक्छ।"),
    SPECIAL_STREE_DEERGHA("STREE DEERGHA not satisfied: Nakshatra difference is {diff} (requires 13+). Bride's prosperity may need attention.", "स्त्री दीर्घ सन्तुष्ट छैन: नक्षत्र भिन्नता {diff} छ (१३+ आवश्यक)। दुलहीको समृद्धिमा ध्यान दिनुपर्ने हुन सक्छ।"),
    SPECIAL_TRAVEL_SAFE("Travel Safety", "यात्रा सुरक्षा"),
    SPECIAL_VEDHA("VEDHA PRESENT: {details}. Nakshatra obstruction may cause challenges in specific life areas.", "वेध उपस्थित: {details}। नक्षत्र बाधाले जीवनका विशेष क्षेत्रहरूमा चुनौतीहरू ल्याउन सक्छ।"),
    SPECIAL_YONI_INCOMPAT("YONI INCOMPATIBILITY: Enemy Yonis present. Physical and instinctual harmony may require extra effort.", "योनि असंगतता: शत्रु योनि उपस्थित। शारीरिक र सहज सामञ्जस्यको लागि अतिरिक्त प्रयास आवश्यक पर्न सक्छ।"),
    SPEECH_AND_FAMILY("Speech & Family Wealth", "वाणी र पारिवारिक धन"),
    SPEED_FAST("Fast", "छिटो"),
    SPEED_NORMAL("Normal", "सामान्य"),
    SPEED_RETROGRADE_MOTION("Retrograde Motion", "वक्री गति"),
    SPEED_SLOW("Slow", "ढिलो"),
    SPEED_STATIONARY("Stationary", "स्थिर"),
    SPEED_VERY_FAST("Very Fast", "अति छिटो"),
    SPEED_VERY_SLOW("Very Slow", "अति ढिलो"),
    SPIRITUAL_12TH_ACTIVE("Active 12th house indicates potential for spiritual practices, meditation, and inner growth.",
        "सक्रिय १२औं भावले आध्यात्मिक अभ्यासहरू, ध्यान, र आन्तरिक वृद्धिको सम्भावना संकेत गर्छ।"),
    SPIRITUAL_9TH_STRONG("Strong 9th house blesses you with faith, higher wisdom, and guidance from teachers.",
        "बलियो ९औं भावले तपाईंलाई विश्वास, उच्च ज्ञान, र गुरुहरूबाट मार्गदर्शनको आशीर्वाद दिन्छ।"),
    SPIRITUAL_CHALLENGES("Spiritual Challenges", "आध्यात्मिक चुनौतीहरू"),
    SPIRITUAL_GROWTH("Spiritual Growth Pattern", "आध्यात्मिक विकास ढाँचा"),
    SPIRITUAL_JUPITER_STRONG("Strong Jupiter indicates a natural inclination toward spirituality, philosophy, and righteous living.",
        "बलियो बृहस्पतिले आध्यात्मिकता, दर्शन, र धार्मिक जीवनतर्फ प्राकृतिक झुकाव संकेत गर्छ।"),
    SPIRITUAL_KETU_INFLUENCE("Ketu's placement shows your past life spiritual attainments and current path toward liberation.",
        "केतुको स्थानले तपाईंको विगत जीवनको आध्यात्मिक उपलब्धिहरू र मुक्तितर्फको वर्तमान मार्ग देखाउँछ।"),
    SPIRITUAL_KNOWLEDGE("Spiritual Knowledge", "आध्यात्मिक ज्ञान"),
    SPIRITUAL_OVERVIEW("Your spiritual inclinations are analyzed through the 9th house (dharma), 12th house (moksha), and Ketu's placement.",
        "तपाईंको आध्यात्मिक झुकावहरू ९औं भाव (धर्म), १२औं भाव (मोक्ष), र केतुको स्थान मार्फत विश्लेषण गरिएको छ।"),
    SPIRITUAL_PATH_TEMPLATE("Your spiritual path aligns with %s. Practices like %s would be particularly beneficial.",
        "तपाईंको आध्यात्मिक मार्ग %s सँग मिल्दछ। %s जस्ता अभ्यासहरू विशेष रूपमा लाभदायक हुनेछन्।"),
    SPIRITUAL_STRENGTHS("Spiritual Strengths", "आध्यात्मिक शक्तिहरू"),
    SPIRITUAL_SUMMARY("Spiritual Path Summary", "आध्यात्मिक मार्ग सारांश"),
    SPIRITUAL_TALENTS("Natural Spiritual Talents", "प्राकृतिक आध्यात्मिक प्रतिभाहरू"),
    SPIRITUAL_TIMELINE("Spiritual Timeline", "आध्यात्मिक समयरेखा"),
    SPIRITUAL_YOGA_TITLE("Spiritual Yogas", "आध्यात्मिक योगहरू"),
    SPOUSE_NATURE_TEMPLATE("Your spouse is likely to be %s, with qualities influenced by %s in your 7th house.",
        "तपाईंको जीवनसाथी %s हुने सम्भावना छ, तपाईंको ७औं भावमा %s द्वारा प्रभावित गुणहरूको साथ।"),
    STATUS("Status", "स्थिति"),
    STATUS_CANCELLED("Cancelled by Afflictions", "पीडाहरूद्वारा रद्द"),
    STATUS_DORMANT("Dormant", "निष्क्रिय"),
    STATUS_FULLY_ACTIVE("Fully Active", "पूर्ण सक्रिय"),
    STATUS_LATENT("Latent - Awaiting Activation", "सुप्त - सक्रियताको पर्खाइमा"),
    STATUS_PARTIALLY_ACTIVE("Partially Active", "आंशिक सक्रिय"),
    STHANA_ACTUAL("Actual", "वास्तविक"),
    STHANA_ANALYZING("Analyzing Sthana Bala...", "स्थानबल विश्लेषण गर्दै..."),
    STHANA_AVERAGE("Average", "औसत"),
    STHANA_DESC("Shadbala component measuring strength from sign, house, and dignity placement", "राशि, भाव, र गरिमा स्थानबाट बल मापन गर्ने षड्बल घटक"),
    STHANA_DREKKANA("Drekkana Bala", "द्रेक्काण बल"),
    STHANA_DREKKANA_DESC("Decanate position strength", "द्रेक्काण स्थान बल"),
    STHANA_INFO_DESC("Sthana Bala measures positional strength through 5 components: Uccha (exaltation), Saptavargaja (7 vargas), Ojhayugma (odd/even), Kendradi (angular), and Drekkana (decanate). It forms a major portion of Shadbala.", "स्थानबलले ५ घटकहरू मार्फत स्थानगत बल मापन गर्छ: उच्च, सप्तवर्गज, ओज्हयुग्म, केन्द्रादि, र द्रेक्काण। यसले षड्बलको प्रमुख भाग बनाउँछ।"),
    STHANA_INFO_TITLE("About Sthana Bala", "स्थानबलको बारेमा"),
    STHANA_KENDRADI("Kendradi Bala", "केन्द्रादि बल"),
    STHANA_KENDRADI_DESC("Angular house strength", "केन्द्र भाव बल"),
    STHANA_OJHAYUGMA("Ojhayugma Bala", "ओज्हयुग्म बल"),
    STHANA_OJHAYUGMA_DESC("Odd/Even sign placement", "ओज/युग्म राशि स्थान"),
    STHANA_RATIO("Ratio", "अनुपात"),
    STHANA_REQUIRED("Required", "आवश्यक"),
    STHANA_SAPTAVARGAJA("Saptavargaja Bala", "सप्तवर्गज बल"),
    STHANA_SAPTAVARGAJA_DESC("Strength from 7 divisional charts", "७ विभागीय चार्टबाट बल"),
    STHANA_STRONG("Strong", "बलियो"),
    STHANA_SUBTITLE("Positional Strength Analysis", "स्थानगत बल विश्लेषण"),
    STHANA_TAB_COMPONENTS("Components", "घटकहरू"),
    STHANA_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    STHANA_TAB_PLANETS("Planets", "ग्रहहरू"),
    STHANA_TITLE("Sthana Bala", "स्थानबल"),
    STHANA_TOTAL("Total Sthana Bala", "कुल स्थानबल"),
    STHANA_UCCHA_BALA("Uccha Bala", "उच्च बल"),
    STHANA_UCCHA_DESC("Exaltation strength (0-60 virupas)", "उच्च बल (०-६० विरूपा)"),
    STHANA_UNABLE("Unable to calculate Sthana Bala", "स्थानबल गणना गर्न सकिएन"),
    STHANA_VEDIC_REF("Vedic Reference: BPHS Chapter 27, Graha Sutras", "वैदिक सन्दर्भ: बृहत् पाराशर होरा शास्त्र अध्याय २७, ग्रह सूत्र"),
    STHANA_WEAK("Weak", "कमजोर"),
    STORMY_ANALYZING("Stormy is analyzing...", "स्टर्मीले विश्लेषण गर्दैछ..."),
    STORMY_ANALYZING_COMPATIBILITY("Stormy is analyzing compatibility...", "स्टर्मीले अनुकूलता विश्लेषण गर्दैछ..."),
    STORMY_APPLYING_VEDIC("Applying Vedic principles...", "वैदिक सिद्धान्तहरू लागू गर्दैछ..."),
    STORMY_ASK_PLACEHOLDER("Ask Stormy...", "स्टर्मीलाई सोध्नुहोस्..."),
    STORMY_CALLING_TOOL("Calling %s...", "%s कल गर्दैछ..."),
    STORMY_COMPOSING("Composing response...", "प्रतिक्रिया रचना गर्दैछ..."),
    STORMY_CONFIGURE_MODELS("Configure AI Models", "एआई मोडेलहरू कन्फिगर गर्नुहोस्"),
    STORMY_ENABLE_MODELS("Enable AI models to start chatting", "च्याट सुरु गर्न एआई मोडेलहरू सक्षम गर्नुहोस्"),
    STORMY_GATHERING_DATA("Gathering astrological data...", "ज्योतिषीय डाटा संकलन गर्दैछ..."),
    STORMY_HELLO("Hello! I'm Stormy", "नमस्ते! म स्टर्मी हुँ"),
    STORMY_HELLO_DESC("Your Vedic astrology assistant. Ask me anything about your birth chart, planetary periods, transits, compatibility, or remedies.", "तपाईंको वैदिक ज्योतिष सहायक। आफ्नो जन्म कुण्डली, ग्रह अवधि, गोचर, अनुकूलता, वा उपायहरूको बारेमा मलाई केही पनि सोध्नुहोस्।"),
    STORMY_INTRO("Ask about your birth chart, planetary periods, transits, compatibility, remedies, and more.", "आफ्नो जन्म कुण्डली, ग्रह अवधि, गोचर, अनुकूलता, उपाय र थप बारेमा सोध्नुहोस्।"),
    STORMY_MEET("Meet Stormy", "स्टर्मीलाई भेट्नुहोस्"),
    STORMY_NEEDS_INPUT("Stormy needs your input", "स्टर्मीलाई तपाईंको इनपुट चाहिन्छ"),
    STORMY_PROCESSING("Processing...", "प्रशोधन गर्दैछ..."),
    STORMY_REASONING("Stormy is reasoning...", "स्टर्मीले तर्क गर्दैछ..."),
    STORMY_REASONING_VEDIC("Reasoning through Vedic principles...", "वैदिक सिद्धान्तहरूमा तर्क गर्दैछ..."),
    STORMY_START_CHAT("Start New Chat", "नयाँ च्याट सुरु गर्नुहोस्"),
    STORMY_SUBTITLE("Your Vedic astrology AI assistant", "तपाईंको वैदिक ज्योतिष एआई सहायक"),
    STORMY_THINKING("Stormy is thinking...", "स्टर्मीले सोच्दैछ..."),
    STORMY_TITLE("Stormy", "स्टर्मी"),
    STORMY_TYPING("Stormy is typing...", "स्टर्मीले टाइप गर्दैछ..."),
    STORMY_USING_TOOL("Using %s...", "%s प्रयोग गर्दैछ..."),
    STORMY_USING_TOOLS("Using tools: %s", "उपकरणहरू प्रयोग गर्दैछ: %s"),
    STRENGTH("Strength", "बल"),
    STRESS_COPING("Coping Mechanisms", "सामना गर्ने तंत्रहरू"),
    STRESS_HANDLING("Stress Handling", "तनाव सम्हाल्ने"),
    STRESS_RESPONSE_TITLE("Stress Response", "तनाव प्रतिक्रिया"),
    STRESS_TRIGGERS("Stress Triggers", "तनाव ट्रिगरहरू"),
    STRONGEST_PLANET("Strongest Planet", "बलवान ग्रह"),
    STRONG_PLANET_INFLUENCE("Strong Planet Influence", "बलियो ग्रह प्रभाव"),
    STUDY_ENVIRONMENT("Preferred Study Environment", "मनपर्ने अध्ययन वातावरण"),
    STYLE_ANALYTICAL("Analytical Learning", "विश्लेषणात्मक सिक्ने"),
    STYLE_AUDITORY("Auditory Learning", "श्रव्य सिक्ने"),
    STYLE_INTUITIVE("Intuitive Learning", "अन्तर्ज्ञानी सिक्ने"),
    STYLE_KINESTHETIC("Kinesthetic Learning", "गतिशील सिक्ने"),
    STYLE_VISUAL("Visual Learning", "दृश्य सिक्ने"),
    SUBJECT_AFFINITY_TITLE("Subject Affinity Analysis", "विषय आत्मीयता विश्लेषण"),
    SUBJECT_ARTS("Arts & Humanities", "कला र मानविकी"),
    SUBJECT_COMMERCE("Commerce & Business", "वाणिज्य र व्यापार"),
    SUBJECT_ENGINEERING("Engineering & Technical", "इन्जिनियरिङ र प्राविधिक"),
    SUBJECT_LAW("Law & Political Science", "कानुन र राजनीति विज्ञान"),
    SUBJECT_MEDICINE("Medicine & Healthcare", "चिकित्सा र स्वास्थ्य सेवा"),
    SUBJECT_SCIENCE("Science & Technology", "विज्ञान र प्रविधि"),
    SUBTITLE("Sensitive points calculated from planetary positions", "ग्रह स्थितिबाट गणना गरिएको संवेदनशील बिन्दुहरू"),
    SUCCESS_PROBABILITY("Success probability", "सफलताको सम्भावना"),
    SUITABLE_PRACTICES("Suitable Practices", "उपयुक्त अभ्यासहरू"),
    SUITABLE_PROFESSIONS("Suitable Professions", "उपयुक्त पेशाहरू"),
    SUMMARY_ADDITIONAL("Additional Factors", "अतिरिक्त कारकहरू"),
    SUMMARY_CHALLENGING("Challenging period requiring patience. %s may create obstacles. Focus on steady progress.", "धैर्य चाहिने चुनौतीपूर्ण अवधि। %s ले बाधाहरू सिर्जना गर्न सक्छन्। स्थिर प्रगतिमा ध्यान दिनुहोस्।"),
    SUMMARY_CONCERNS("Areas of Concern", "चिन्ताका क्षेत्रहरू"),
    SUMMARY_DIFFICULT("Difficult transit period. %s create significant challenges. Exercise caution and avoid major decisions.", "कठिन गोचर अवधि। %s ले महत्त्वपूर्ण चुनौतीहरू सिर्जना गर्छन्। सावधानी अपनाउनुहोस् र ठूला निर्णयहरूबाट बच्नुहोस्।"),
    SUMMARY_EXCELLENT("This is an excellent transit period. %s are well-placed from Moon, supporting growth and positive developments.", "यो उत्कृष्ट गोचर अवधि हो। %s चन्द्रमाबाट राम्रो स्थानमा छन्, जसले वृद्धि र सकारात्मक विकासलाई सहयोग गर्छ।"),
    SUMMARY_FAVORABLE("Your planetary positions are generally favorable. Continue with positive practices to maintain balance.", "तपाईंको ग्रह स्थिति सामान्यतया अनुकूल छ। सन्तुलन कायम राख्न सकारात्मक अभ्यासहरू जारी राख्नुहोस्।"),
    SUMMARY_FOCUS("PRIMARY FOCUS PLANETS: %s", "प्राथमिक फोकस ग्रहहरू: %s"),
    SUMMARY_GOOD("Overall favorable transit period. %s provide support. Good time for important initiatives.", "समग्रमा शुभ गोचर अवधि। %s ले सहयोग प्रदान गर्छन्। महत्त्वपूर्ण पहलहरूको लागि राम्रो समय।"),
    SUMMARY_GUIDANCE("GENERAL GUIDANCE:", "सामान्य मार्गदर्शन:"),
    SUMMARY_GUIDANCE_1("• Start with one or two remedies, then gradually add more", "• एक वा दुई उपायहरूबाट सुरु गर्नुहोस्, त्यसपछि बिस्तारै थप थप्नुहोस्"),
    SUMMARY_GUIDANCE_2("• Consistency is key - regular practice beats occasional intensity", "• निरन्तरता मुख्य हो - नियमित अभ्यासले कहिलेकाहीँको तीव्रतालाई जित्छ"),
    SUMMARY_GUIDANCE_3("• Remedies work best with positive attitude and good deeds", "• सकारात्मक दृष्टिकोण र राम्रो कामहरूसँग उपायहरूले राम्रो काम गर्छन्"),
    SUMMARY_GUIDANCE_4("• Results manifest according to karmic timing", "• नतिजाहरू कार्मिक समय अनुसार प्रकट हुन्छन्"),
    SUMMARY_GUIDANCE_5("• During difficult Dashas, increase remedy intensity", "• कठिन दशाको समयमा, उपायको तीव्रता बढाउनुहोस्"),
    SUMMARY_GUIDANCE_POINT_1("• Start with one or two remedies, then gradually add more", "• एक वा दुई उपायहरूबाट सुरु गर्नुहोस्, त्यसपछि बिस्तारै थप्नुहोस्"),
    SUMMARY_GUIDANCE_POINT_2("• Consistency is key - regular practice beats occasional intensity", "• निरन्तरता मुख्य कुरा हो - नियमित अभ्यासले कहिलेकाहीँको तीव्रता भन्दा राम्रो काम गर्छ"),
    SUMMARY_GUIDANCE_POINT_3("• Remedies work best with positive attitude and good deeds", "• सकारात्मक दृष्टिकोण र राम्रो कामहरूका साथ उपायहरूले राम्रो काम गर्छन्"),
    SUMMARY_GUIDANCE_POINT_4("• Results manifest according to karmic timing", "• नतिजाहरू कार्मिक समय अनुसार प्रकट हुन्छन्"),
    SUMMARY_GUIDANCE_POINT_5("• During difficult Dashas, increase remedy intensity", "• कठिन दशा अवधिहरूमा, उपायको तीव्रता बढाउनुहोस्"),
    SUMMARY_GUIDANCE_TITLE("GENERAL GUIDANCE:", "सामान्य मार्गदर्शन:"),
    SUMMARY_MAINTENANCE("RECOMMENDED MAINTENANCE PRACTICES:", "सिफारिस गरिएको मर्मत अभ्यासहरू:"),
    SUMMARY_MAINTENANCE_1("• Daily meditation and pranayama", "• दैनिक ध्यान र प्राणायाम"),
    SUMMARY_MAINTENANCE_2("• Weekly temple visits", "• साप्ताहिक मन्दिर दर्शन"),
    SUMMARY_MAINTENANCE_3("• Regular charity and service", "• नियमित दान र सेवा"),
    SUMMARY_MAINTENANCE_4("• Ethical living and positive thinking", "• नैतिक जीवन र सकारात्मक सोच"),
    SUMMARY_MANGLIK("Manglik Status", "मांगलिक स्थिति"),
    SUMMARY_MIXED("Mixed transit influences present. Balance %s positives against %s challenges.", "मिश्रित गोचर प्रभावहरू उपस्थित छन्। %s सकारात्मक पक्षहरूलाई %s चुनौतीहरूसँग सन्तुलन गर्नुहोस्।"),
    SUMMARY_NONE("No Panch Mahapurusha Yoga is formed in this chart. These special yogas require Mars, Mercury, Jupiter, Venus, or Saturn to be in Kendra houses (1, 4, 7, 10) in their own or exaltation signs. While these yogas are not present, other yogas and planetary combinations in your chart provide their own blessings.", "यस कुण्डलीमा कुनै पञ्च महापुरुष योग बनेको छैन। यी विशेष योगहरूका लागि मंगल, बुध, बृहस्पति, शुक्र वा शनि केन्द्र भाव (१, ४, ७, १०) मा आफ्नै राशि वा उच्च राशिमा हुनुपर्छ। यद्यपि यी योगहरू उपस्थित छैनन्, तपाईंको कुण्डलीमा रहेका अन्य योग र ग्रह संयोजनहरूले आफ्नै आशीर्वाद प्रदान गर्छन्।"),
    SUMMARY_OVERALL_SCORE("Overall Score", "समग्र अंक"),
    SUMMARY_PRESENT("This chart has {0} Panch Mahapurusha Yoga(s): {1}. These are among the most auspicious yogas in Vedic astrology, indicating a soul that has earned special blessings through past-life merit. The native is blessed with the positive qualities of the yoga-forming planets.", "यस कुण्डलीमा {0} पञ्च महापुरुष योग(हरू) छन्: {1}। यी वैदिक ज्योतिषमा सबैभन्दा शुभ योगहरू मध्ये हुन्, जसले पूर्वजन्मको पुण्यबाट विशेष आशीर्वाद प्राप्त गरेको आत्मालाई संकेत गर्दछ। जातक योग बनाउने ग्रहहरूको सकारात्मक गुणहरूले आशीर्वादित हुन्छ।"),
    SUMMARY_PRIORITY("REMEDY PRIORITY ORDER:", "उपाय प्राथमिकता क्रम:"),
    SUMMARY_PRIORITY_1("1. MANTRAS (Start here - safest, most effective)", "१. मन्त्र (यहाँबाट सुरु गर्नुहोस् - सबैभन्दा सुरक्षित, सबैभन्दा प्रभावकारी)"),
    SUMMARY_PRIORITY_1_A("   • No side effects, can be done by anyone", "   • कुनै साइड इफेक्ट छैन, जो कोहीले गर्न सक्छ"),
    SUMMARY_PRIORITY_1_B("   • Chant daily, preferably 108 times or more", "   • दैनिक जप गर्नुहोस्, प्राथमिकता १०८ पटक वा बढी"),
    SUMMARY_PRIORITY_1_C("   • Best performed during brahma muhurta (before sunrise)", "   • ब्रह्म मुहूर्त (सूर्योदय अघि) मा गर्नु उत्तम हुन्छ"),
    SUMMARY_PRIORITY_2("2. CHARITY (Universal benefit)", "२. दान (विश्वव्यापी लाभ)"),
    SUMMARY_PRIORITY_2_A("   • Donate on the planet's weekday", "   • ग्रहको बारमा दान गर्नुहोस्"),
    SUMMARY_PRIORITY_2_B("   • Give with pure intention without expectation", "   • अपेक्षा बिना शुद्ध मनसायले दिनुहोस्"),
    SUMMARY_PRIORITY_3("3. FASTING (Powerful purification)", "३. व्रत (शक्तिशाली शुद्धिकरण)"),
    SUMMARY_PRIORITY_3_A("   • Observe on the planet's day", "   • ग्रहको दिनमा मनाउनुहोस्"),
    SUMMARY_PRIORITY_3_B("   • Even partial fasting is beneficial", "   • आंशिक व्रत पनि फाइदाजनक हुन्छ"),
    SUMMARY_PRIORITY_4("4. DEITY WORSHIP (Divine connection)", "४. देवी-देवता पूजा (ईश्वरीय सम्बन्ध)"),
    SUMMARY_PRIORITY_4_A("   • Visit relevant temples regularly", "   • सम्बन्धित मन्दिरहरूमा नियमित जानुहोस्"),
    SUMMARY_PRIORITY_4_B("   • Perform home worship with devotion", "   • भक्तिका साथ घरमा पूजा गर्नुहोस्"),
    SUMMARY_PRIORITY_5("5. GEMSTONES (Use with caution)", "५. रत्न (सावधानीपूर्वक प्रयोग गर्नुहोस्)"),
    SUMMARY_PRIORITY_5_A("   • Only for functional benefics of your Lagna", "   • मात्र तपाईंको लग्नको शुभ ग्रहहरूको लागि"),
    SUMMARY_PRIORITY_5_B("   • Consult an expert before wearing", "   • लगाउनु अघि विशेषज्ञसँग परामर्श गर्नुहोस्"),
    SUMMARY_PRIORITY_5_C("   • Always observe trial period first", "   • सधैं पहिले परीक्षण अवधि अवलोकन गर्नुहोस्"),
    SUMMARY_RATING("Rating", "मूल्यांकन"),
    SUMMARY_RECOMMENDATION("Recommendation", "सिफारिस"),
    SUMMARY_STRENGTHS("Strengths", "शक्तिहरू"),
    SUMMARY_THESE_PLANETS("these planets", "यी ग्रहहरू"),
    SUMMARY_THIS_PLANET("this planet", "यो ग्रह"),
    SUMMARY_TITLE("REMEDIES SUMMARY FOR %s ASCENDANT", "%s लग्नको लागि उपाय सारांश"),
    SUMMARY_VIP_DOUBLE("Two Vipareeta Raja Yogas: {0}. Overall strength: {1}.", "दुई विपरीत राज योगहरू: {0}। समग्र बल: {1}।"),
    SUMMARY_VIP_NONE("No Vipareeta Raja Yogas formed in this chart.", "यस कुण्डलीमा कुनै विपरीत राज योग बनेको छैन।"),
    SUMMARY_VIP_SINGLE("{0} is present with {1} strength.", "{0} {1} बलका साथ उपस्थित छ।"),
    SUMMARY_VIP_TRIPLE("All three Vipareeta Raja Yogas (Harsha, Sarala, Vimala) are present - a rare and powerful combination! Overall strength: {0}.", "तीनै विपरीत राज योगहरू (हर्ष, सरल, विमल) उपस्थित छन् - एक दुर्लभ र शक्तिशाली संयोजन! समग्र बल: {0}।"),
    SUMMARY_YOGAKARAKA("IMPORTANT: %s is/are your Yogakaraka planet(s). Strengthening %s will bring maximum positive results.", "महत्त्वपूर्ण: %s तपाईंको योगकारक ग्रह(हरू) हो/हुन्। %s लाई बलियो बनाउँदा अधिकतम सकारात्मक परिणामहरू प्राप्त हुनेछन्।"),
    SUN_AUTHORITY_REL("Authority Relationship", "अधिकार सम्बन्ध"),
    SUN_CORE_IDENTITY("Core Identity", "मूल पहिचान"),
    SUN_EGO_EXPRESSION("Ego Expression", "अहंकार अभिव्यक्ति"),
    SUN_HEALTH("Sun Health Influence", "सूर्य स्वास्थ्य प्रभाव"),
    SUN_LABEL("Sun", "सूर्य"),
    SUN_LEADERSHIP("Leadership Style", "नेतृत्व शैली"),
    SUN_VITALITY("Vitality Level", "जीवनी शक्ति स्तर"),
    SUPPORTING_FACTORS("Supporting Longevity Factors", "दीर्घायु समर्थन कारकहरू"),
    SUPPORT_CHALLENGES("challenges", "चुनौतीहरू"),
    SUPPORT_NEUTRAL("neutral", "तटस्थ"),
    SUPPORT_POSITIVE("positive", "सकारात्मक"),
    SUPPORT_SUPPORT("support", "सहयोग"),
    SYMBOL_ANURADHA("Lotus", "कमल"),
    SYMBOL_ARDRA("Teardrop/Diamond", "आँसुको थोपा/हीरा"),
    SYMBOL_ASHLESHA("Coiled Serpent", "कुण्डली मारेको सर्प"),
    SYMBOL_ASHWINI("Horse's Head", "घोडाको टाउको"),
    SYMBOL_BHARANI("Yoni (Female Organ)", "योनी"),
    SYMBOL_CHITRA("Bright Pearl/Gem", "चम्किलो मोती/रत्न"),
    SYMBOL_DHANISHTHA("Drum/Flute", "डमरु/बाँसुरी"),
    SYMBOL_HASTA("Hand/Palm", "हात/हत्केला"),
    SYMBOL_JYESHTHA("Earring/Talisman", "कुण्डल/ताबीज"),
    SYMBOL_KRITTIKA("Razor/Flame", "छुरा/ज्वाला"),
    SYMBOL_MAGHA("Royal Throne", "शाही सिंहासन"),
    SYMBOL_MRIGASHIRA("Deer's Head", "मृगको टाउको"),
    SYMBOL_MULA("Tied Roots", "बाँधिएको जरा"),
    SYMBOL_PUNARVASU("Bow/House", "धनुष/घर")
}
