package com.astro.storm.core.common
enum class StringKeyDashaInterpretationsPart2(override val en: String, override val ne: String) : StringKeyInterface {
KALACHAKRA_APPLICABILITY("System Applicability", "प्रणाली प्रयोज्यता"),
KALACHAKRA_HEALTH_INDICATOR("Health Outlook", "स्वास्थ्य दृष्टिकोण"),
KALACHAKRA_PARAMA_AYUSH("Parama Ayush Sign - Special longevity indicator", "परम आयुष राशि - विशेष दीर्घायु सूचक"),
KALACHAKRA_INTERPRETATION("Interpretation & Guidance", "व्याख्या र मार्गदर्शन"),
KALACHAKRA_GUIDANCE("Guidance", "मार्गदर्शन"),
    KALACHAKRA_DEHA_ANALYSIS("Deha (Body)", "Deha (Body)"),
    KALACHAKRA_JEEVA_ANALYSIS("Jeeva (Soul)", "Jeeva (Soul)"),
KALACHAKRA_DEHA_LORD("Deha Lord", "देह स्वामी"),
KALACHAKRA_JEEVA_LORD("Jeeva Lord", "जीव स्वामी"),
KALACHAKRA_STRENGTH("Strength", "बल"),
KALACHAKRA_RELATIONSHIP("Deha-Jeeva Relationship", "देह-जीव सम्बन्ध"),
    KALACHAKRA_SAVYA("Savya (Direct)", "Savya (Direct)"),
    KALACHAKRA_APSAVYA("Apsavya (Retrograde)", "Apsavya (Retrograde)"),
KALACHAKRA_RELATIONSHIP_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
KALACHAKRA_RELATIONSHIP_SUPPORTIVE("Supportive", "सहयोगी"),
KALACHAKRA_RELATIONSHIP_NEUTRAL("Neutral", "तटस्थ"),
KALACHAKRA_RELATIONSHIP_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
KALACHAKRA_RELATIONSHIP_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
KALACHAKRA_SPIRITUAL_FIRE("Spiritual growth through action, courage, and self-assertion. Karma yoga is favored.", "कार्य, साहस र आत्म-दावी मार्फत आध्यात्मिक वृद्धि। कर्म योग अनुकूल छ।"),
KALACHAKRA_SPIRITUAL_EARTH("Spiritual grounding through practical service and material detachment. Seva is emphasized.", "व्यावहारिक सेवा र भौतिक अनासक्ति मार्फत आध्यात्मिक स्थिरता। सेवामा जोड दिइन्छ।"),
KALACHAKRA_SPIRITUAL_AIR("Spiritual development through knowledge, study, and intellectual understanding. Jnana yoga is favored.", "ज्ञान, अध्ययन र बौद्धिक समझ मार्फत आध्यात्मिक विकास। ज्ञान योग अनुकूल छ।"),
KALACHAKRA_SPIRITUAL_WATER("Spiritual awakening through devotion, intuition, and emotional surrender. Bhakti yoga is emphasized.", "भक्ति, अन्तर्ज्ञान र भावनात्मक समर्पण मार्फत आध्यात्मिक जागरण। भक्ति योगमा जोड दिइन्छ।"),
KALACHAKRA_SPIRITUAL_GENERAL("Balanced spiritual development across all paths.", "सबै मार्गहरूमा सन्तुलित आध्यात्मिक विकास।"),
KALACHAKRA_MATERIAL_SIGN_FOCUS("Material focus on %s matters.", "%s मामिलाहरूमा भौतिक ध्यान।"),
KALACHAKRA_MATERIAL_LORD_POS("Sign lord %s in House %d indicates ", "राशि स्वामी %s भाव %d मा हुनुले "),
KALACHAKRA_MATERIAL_H1("self-focused material gains.", "आत्म-केन्द्रित भौतिक लाभ।"),
KALACHAKRA_MATERIAL_H2("wealth and resource accumulation.", "धन र स्रोत संकलन।"),
KALACHAKRA_MATERIAL_H3("gains through courage and communication.", "साहस र संचार मार्फत लाभ।"),
KALACHAKRA_MATERIAL_H4("property and domestic comfort.", "सम्पत्ति र पारिवारिक सुख।"),
KALACHAKRA_MATERIAL_H5("creative and speculative gains.", "रचनात्मक र सट्टा लाभ।"),
KALACHAKRA_MATERIAL_H6("gains through service and overcoming obstacles.", "सेवा र अवरोधहरू पार गरेर लाभ।"),
KALACHAKRA_MATERIAL_H7("partnership-related material matters.", "साझेदारी सम्बन्धित भौतिक मामिलाहरू।"),
KALACHAKRA_MATERIAL_H8("transformation of resources, inheritance.", "स्रोतहरूको रूपान्तरण, पैतृक सम्पत्ति।"),
KALACHAKRA_MATERIAL_H9("fortune through dharma and higher pursuits.", "धर्म र उच्च खोज मार्फत भाग्य।"),
KALACHAKRA_MATERIAL_H10("career advancement and public recognition.", "करियर उन्नति र सार्वजनिक पहिचान।"),
KALACHAKRA_MATERIAL_H11("fulfillment of desires and network gains.", "इच्छा पूर्ति र नेटवर्क लाभ।"),
KALACHAKRA_MATERIAL_H12("spiritual investments and foreign connections.", "आध्यात्मिक लगानी र विदेशी सम्बन्ध।"),
KALACHAKRA_MATERIAL_GENERAL_PROGRESS("general material progression.", "सामान्य भौतिक प्रगति।"),
KALACHAKRA_CAUTION_HEALTH("Physical health requires attention", "शारीरिक स्वास्थ्यमा ध्यान दिनु आवश्यक छ"),
KALACHAKRA_CAUTION_ARIES("Head injuries, fevers, impulsive actions", "टाउकोको चोट, ज्वरो, आवेगपूर्ण कार्यहरू"),
KALACHAKRA_CAUTION_TAURUS("Throat issues, dietary excess, stubbornness", "घाँटीको समस्या, खानपानमा अधिकता, जिद्दीपन"),
KALACHAKRA_CAUTION_GEMINI("Nervous tension, respiratory issues, inconsistency", "स्नायु तनाव, श्वासप्रश्वासको समस्या, अस्थिरता"),
KALACHAKRA_CAUTION_CANCER("Emotional sensitivity, digestive issues, attachment", "भावनात्मक संवेदनशीलता, पाचन समस्या, मोह"),
KALACHAKRA_CAUTION_LEO("Heart issues, ego conflicts, excessive pride", "मुटुको समस्या, अहंकार विवाद, अत्यधिक गर्व"),
KALACHAKRA_CAUTION_VIRGO("Digestive problems, anxiety, over-criticism", "पाचन समस्या, चिन्ता, अत्यधिक आलोचना"),
KALACHAKRA_CAUTION_LIBRA("Kidney issues, indecision, relationship dependency", "मृगौलाको समस्या, अनिर्णय, सम्बन्धमा निर्भरता"),
KALACHAKRA_CAUTION_SCORPIO("Reproductive issues, intensity, control issues", "प्रजनन समस्या, तीव्रता, नियन्त्रण समस्या"),
KALACHAKRA_CAUTION_SAGITTARIUS("Liver issues, over-expansion, dogmatism", "कलेजोको समस्या, अत्यधिक विस्तार, कट्टरता"),
KALACHAKRA_CAUTION_CAPRICORN("Joint problems, depression, workaholism", "जोर्नीको समस्या, निराशा, कामको लत"),
KALACHAKRA_CAUTION_AQUARIUS("Circulation issues, detachment, rebellion", "रक्तसञ्चार समस्या, वैराग्य, विद्रोह"),
KALACHAKRA_CAUTION_PISCES("Foot problems, escapism, boundary issues", "खुट्टाको समस्या, पलायनवाद, सीमा समस्या"),
KALACHAKRA_REMEDY_MANTRA("Chant %s mantra for strengthening this period", "यो अवधिलाई बलियो बनाउन %s मन्त्र जप गर्नुहोस्"),
    KALACHAKRA_REMEDY_FIRE("Perform Agni-related rituals (Homa, lighting lamp)", "Perform Agni-related rituals (Homa, lighting lamp)"),
    KALACHAKRA_REMEDY_EARTH("Service to earth (gardening, feeding, grounding practices)", "Service to earth (gardening, feeding, grounding practices)"),
KALACHAKRA_REMEDY_AIR("Pranayama and breath-related practices", "प्राणायाम र श्वास सम्बन्धी अभ्यासहरू"),
KALACHAKRA_REMEDY_WATER("Water offerings, visiting sacred water bodies", "जल अर्पण, पवित्र जलाशयको भ्रमण"),
KALACHAKRA_REMEDY_DEITY("Honor the sign deity through appropriate worship", "उपयुक्त पूजा मार्फत राशि देवताको सम्मान गर्नुहोस्"),
KALACHAKRA_INTERP_GROUP_ANALYSIS("Your Moon falls in %s group. %s This influences the direction and nature of your life's unfoldment.", "तपाईंको चन्द्रमा %s समूहमा पर्दछ। %s यसले तपाईंको जीवनको विकासको दिशा र प्रकृतिलाई प्रभाव पार्छ।"),
    KALACHAKRA_INTERP_DEHA_JEEVA_SUMMARY("Deha (Body)", "Deha (Body)"),
    KALACHAKRA_INTERP_CURRENT_PHASE("Currently in %s Mahadasha (%d years)", "Currently in %s Mahadasha (%d years)"),
KALACHAKRA_INTERP_NO_CURRENT("Current Mahadasha extends beyond calculated range.", "वर्तमान महादशा गणना गरिएको दायरा भन्दा बाहिर छ।"),
KALACHAKRA_INTERP_HEALTH_SPIRITUAL("Health & Spiritual Outlook", "स्वास्थ्य र आध्यात्मिक दृष्टिकोण"),
KALACHAKRA_INTERP_MATERIAL_GUIDANCE("Material & General Guidance", "भौतिक र सामान्य मार्गदर्शन"),
KALACHAKRA_INTERP_CLOSING("Use this period to align with your %s-ruled energies for maximum growth.", "अधिकतम वृद्धिको लागि तपाईंको %s-शासित ऊर्जाहरूसँग पङ्क्तिबद्ध हुन यो अवधि प्रयोग गर्नुहोस्।"),
SUDARSHANA_HOUSE_1_DESC("Year of self-focus, health matters, and personal initiatives", "आत्म-केन्द्रित, स्वास्थ्य मामिला, र व्यक्तिगत पहलहरूको वर्ष"),
SUDARSHANA_HOUSE_2_DESC("Year of financial matters, family affairs, and resource building", "आर्थिक मामिला, पारिवारिक मामिला, र स्रोत निर्माणको वर्ष"),
SUDARSHANA_HOUSE_3_DESC("Year of courage, communication, and sibling matters", "साहस, संचार, र भाईबहिनी मामिलाहरूको वर्ष"),
SUDARSHANA_HOUSE_4_DESC("Year of home, mother, property, and emotional well-being", "घर, आमा, सम्पत्ति, र भावनात्मक कल्याणको वर्ष"),
SUDARSHANA_HOUSE_5_DESC("Year of children, romance, creativity, and spiritual practices", "सन्तान, रोमान्स, रचनात्मकता, र आध्यात्मिक अभ्यासहरूको वर्ष"),
SUDARSHANA_HOUSE_6_DESC("Year of health focus, overcoming obstacles, and service", "स्वास्थ्यमा ध्यान, बाधाहरू पार गर्ने, र सेवाको वर्ष"),
SUDARSHANA_HOUSE_7_DESC("Year of relationships, partnerships, and public dealings", "सम्बन्ध, साझेदारी, र सार्वजनिक व्यवहारहरूको वर्ष"),
SUDARSHANA_HOUSE_8_DESC("Year of transformation, research, and handling sudden events", "रूपान्तरण, अनुसन्धान, र अचानक घटनाहरू संहाल्ने वर्ष"),
SUDARSHANA_HOUSE_9_DESC("Year of fortune, spiritual growth, and father-related matters", "भाग्य, आध्यात्मिक वृद्धि, र पितासम्बन्धी मामिलाहरूको वर्ष"),
SUDARSHANA_HOUSE_10_DESC("Year of career growth, recognition, and professional achievements", "करियर वृद्धि, मान्यता, र व्यावसायिक उपलब्धिहरूको वर्ष"),
SUDARSHANA_HOUSE_11_DESC("Year of gains, fulfillment of desires, and social expansion", "लाभ, इच्छाहरूको पूर्ति, र सामाजिक विस्तारको वर्ष"),
SUDARSHANA_HOUSE_12_DESC("Year of spiritual growth, foreign connections, and completion of cycles", "आध्यात्मिक वृद्धि, विदेशी सम्बन्ध, र चक्रहरूको समापनको वर्ष"),
SUDARSHANA_EFFECT_ACTIVATED("%s activated - %s element emphasized", "%s सक्रिय - %s तत्वलाई जोड"),
SUDARSHANA_EFFECT_MOVABLE("Movable sign - new initiatives and changes favored", "चर राशि - नयाँ पहल र परिवर्तनहरू अनुकूल"),
SUDARSHANA_EFFECT_FIXED("Fixed sign - stability and consolidation emphasized", "स्थिर राशि - स्थिरता र समेकनलाई जोड"),
SUDARSHANA_EFFECT_DUAL("Dual sign - adaptability and flexibility needed", "द्विस्वभाव राशि - अनुकूलनशीलता र लचिलोपन आवश्यक"),
SUDARSHANA_EFFECT_LORD_POS("Lord %s in %d from active sign", "स्वामी %s सक्रिय राशिबाट %d मा"),
SUDARSHANA_EFFECT_EXALTED("Sign lord is exalted - strong positive results", "राशि स्वामी उच्च - बलियो सकारात्मक परिणाम"),
SUDARSHANA_EFFECT_DEBILITATED("Sign lord is debilitated - extra efforts needed", "राशि स्वामी नीच - अतिरिक्त प्रयास आवश्यक"),
SUDARSHANA_EFFECT_NORMAL("Sign lord is in normal dignity", "राशि स्वामी सामान्य अवस्थामा"),
SUDARSHANA_INFLUENCE_PRESENT("%s present - direct influence on year's themes", "%s उपस्थित - वर्षका विषयहरूमा प्रत्यक्ष प्रभाव"),
SUDARSHANA_INFLUENCE_ASPECT("%s aspects from %s", "%s ले %s बाट दृष्टि दिन्छ"),
SUDARSHANA_FACTOR_DIGNITY("Sign lord %s dignity: %s", "राशि स्वामी %s अवस्था: %s"),
SUDARSHANA_FACTOR_PLANETS("%d planets in active sign", "%d ग्रहहरू सक्रिय राशिमा"),
SUDARSHANA_FACTOR_ASPECTS("%d planets aspecting", "%d ग्रहहरूको दृष्टि"),
SUDARSHANA_ASSESSMENT_HIGHLY_FAVORABLE("Highly favorable year with aligned energies from all three references", "तीनै सन्दर्भहरूबाट समान ऊर्जासहित अत्यन्त अनुकूल वर्ष"),
SUDARSHANA_ASSESSMENT_POSITIVE("Generally positive year with good support from chart references", "कुण्डली सन्दर्भहरूबाट राम्रो समर्थनसहित सामान्यतया सकारात्मक वर्ष"),
SUDARSHANA_ASSESSMENT_MIXED("Mixed year requiring balanced approach to different life areas", "विभिन्न जीवन क्षेत्रहरूमा सन्तुलित दृष्टिकोण आवश्यक पर्ने मिश्रित वर्ष"),
SUDARSHANA_ASSESSMENT_CHALLENGING("Challenging year requiring extra effort and remedial measures", "अतिरिक्त प्रयास र उपचारात्मक उपायहरू आवश्यक पर्ने चुनौतीपूर्ण वर्ष"),
SUDARSHANA_REC_FAVORABLE("Favorable year - take initiative in %s", "अनुकूल वर्ष - %s मा पहल गर्नुहोस्"),
SUDARSHANA_REC_EXPAND("Expand activities related to %s", "%s सम्बन्धी गतिविधिहरू विस्तार गर्नुहोस्"),
SUDARSHANA_REC_BALANCED("Balanced approach needed - focus on %s", "सन्तुलित दृष्टिकोण आवश्यक - %s मा ध्यान दिनुहोस्"),
SUDARSHANA_REC_PATIENCE("Be patient with %s", "%s सँग धैर्य राख्नुहोस्"),
SUDARSHANA_REC_CHALLENGING("Challenging year - strengthen remedies for weak areas", "चुनौतीपूर्ण वर्ष - कमजोर क्षेत्रहरूको लागि उपायहरू बलियो बनाउनुहोस्"),
SUDARSHANA_REC_SPIRITUAL("Focus on spiritual practices and patience", "आध्यात्मिक अभ्यास र धैर्यमा ध्यान दिनुहोस्"),
SUDARSHANA_REC_REVIEW("Review all three references monthly for detailed guidance", "विस्तृत मार्गदर्शनको लागि मासिक रूपमा तीनै सन्दर्भहरू समीक्षा गर्नुहोस्"),
SUDARSHANA_THEME_MULTIPLE("Multiple references point to %s house themes", "धेरै सन्दर्भहरूले %s भाव विषयहरूलाई औंल्याउँछन्"),
SUDARSHANA_THEME_ACTIVATED("%s activated from multiple references", "%s धेरै सन्दर्भहरूबाट सक्रिय"),
SUDARSHANA_THEME_VARIATION("Significant variation in strength across references - uneven year expected", "सन्दर्भहरूमा शक्तिको महत्त्वपूर्ण भिन्नता - असमान वर्षको अपेक्षा"),
SUDARSHANA_FOCUS_GENERAL("General matters", "सामान्य मामिलाहरू"),
SUDARSHANA_FOCUS_FROM("%s from %s reference", "%s सन्दर्भबाट %s"),
SUDARSHANA_CONTRIB_LAGNA("Physical matters, personality, and health - %s", "भौतिक मामिला, व्यक्तित्व, र स्वास्थ्य - %s"),
SUDARSHANA_CONTRIB_CHANDRA("Mind, emotions, and public life - %s", "मन, भावना, र सार्वजनिक जीवन - %s"),
SUDARSHANA_CONTRIB_SURYA("Soul, authority, and career - %s", "आत्मा, अधिकार, र करियर - %s"),
SUDARSHANA_YEAR_SUMMARY("Age %d: %s house activated - %s", "उमेर %d: %s भाव सक्रिय - %s"),
SUDARSHANA_TREND_FAVORABLE("Favorable period in annual cycle", "वार्षिक चक्रमा अनुकूल अवधि"),
SUDARSHANA_TREND_CHALLENGING("Challenging period requiring extra attention", "अतिरिक्त ध्यान आवश्यक पर्ने चुनौतीपूर्ण अवधि"),
SUDARSHANA_TREND_NEUTRAL("Neutral period with mixed opportunities", "मिश्रित अवसरहरूसहित तटस्थ अवधि"),
SUDARSHANA_DIG_EXALTED("Exalted", "उच्च"),
SUDARSHANA_DIG_OWN("Own Sign", "स्वराशि"),
SUDARSHANA_DIG_DEBILITATED("Debilitated", "नीच"),
SUDARSHANA_DIG_NORMAL("Normal", "सामान्य"),
SUDARSHANA_THEME_H1_1("Self", "स्वयं"),
SUDARSHANA_THEME_H1_2("Body", "शरीर"),
SUDARSHANA_THEME_H2_1("Wealth", "धन"),
SUDARSHANA_THEME_H2_2("Family", "परिवार"),
SUDARSHANA_THEME_H3_1("Siblings", "भाईबहिनी"),
SUDARSHANA_THEME_H3_2("Courage", "साहस"),
SUDARSHANA_THEME_H4_1("Mother", "आमा"),
SUDARSHANA_THEME_H4_2("Home", "घर"),
SUDARSHANA_THEME_H5_1("Children", "सन्तान"),
SUDARSHANA_THEME_H5_2("Romance", "प्रेम"),
SUDARSHANA_THEME_H6_1("Health", "स्वास्थ्य"),
SUDARSHANA_THEME_H6_2("Enemies", "शत्रु"),
SUDARSHANA_THEME_H7_1("Marriage", "विवाह"),
SUDARSHANA_THEME_H7_2("Partnership", "साझेदारी"),
SUDARSHANA_THEME_H8_1("Transformation", "रूपान्तरण"),
SUDARSHANA_THEME_H8_2("Longevity", "आयु"),
SUDARSHANA_THEME_H9_1("Fortune", "भाग्य"),
SUDARSHANA_THEME_H9_2("Father", "पिता"),
SUDARSHANA_THEME_H10_1("Career", "करियर"),
SUDARSHANA_THEME_H10_2("Status", "प्रतिष्ठा"),
SUDARSHANA_THEME_H11_1("Gains", "लाभ"),
SUDARSHANA_THEME_H11_2("Income", "आम्दानी"),
SUDARSHANA_THEME_H12_1("Losses", "हानि"),
SUDARSHANA_THEME_H12_2("Expenses", "खर्च"),
YOGINI_SEQUENCE("Yogini Sequence", "योगिनी क्रम"),
KALACHAKRA_AREA_LEADERSHIP("Leadership", "नेतृत्व"),
KALACHAKRA_AREA_SPORTS("Sports", "खेलकुद"),
KALACHAKRA_AREA_ENGINEERING("Engineering", "इन्जिनियरिङ"),
KALACHAKRA_AREA_MILITARY("Military", "सैनिक"),
KALACHAKRA_AREA_FINANCE("Finance", "वित्त"),
KALACHAKRA_AREA_REAL_ESTATE("Real estate", "घरजग्गा"),
KALACHAKRA_AREA_AGRICULTURE("Agriculture", "कृषि"),
KALACHAKRA_AREA_CONSTRUCTION("Construction", "निर्माण"),
KALACHAKRA_AREA_COMMUNICATION("Communication", "सञ्चार"),
KALACHAKRA_AREA_EDUCATION("Education", "शिक्षा"),
KALACHAKRA_AREA_TRAVEL("Travel", "यात्रा"),
KALACHAKRA_AREA_TECHNOLOGY("Technology", "प्रविधि"),
KALACHAKRA_AREA_HEALING("Healing", "उपचार"),
KALACHAKRA_AREA_ARTS("Arts", "कला"),
KALACHAKRA_AREA_PSYCHOLOGY("Psychology", "मनोविज्ञान"),
KALACHAKRA_AREA_SPIRITUALITY("Spirituality", "अध्यात्म"),
DASHA_INTERP_MAHADASHA_SUN("A period of heightened self-expression, authority, and recognition. Focus turns to career advancement, leadership roles, government dealings, and matters related to father. Soul purpose becomes clearer. Health of heart and vitality gains prominence. Good for developing confidence and establishing one's identity in the world.", "आत्म-अभिव्यक्ति, अधिकार र मान्यताको उच्च अवधि। क्यारियर प्रगति, नेतृत्व भूमिका, सरकारी व्यवहार र बुबासँग सम्बन्धित मामिलाहरूमा ध्यान केन्द्रित हुन्छ। आत्माको उद्देश्य स्पष्ट हुन्छ। हृदय र जीवनशक्तिको स्वास्थ्यले प्रमुखता पाउँछ। आत्मविश्वास विकास गर्न र संसारमा आफ्नो पहिचान स्थापित गर्न राम्रो।"),
DASHA_INTERP_MAHADASHA_MOON("An emotionally rich and intuitive period emphasizing mental peace, nurturing, and receptivity. Focus on mother, home life, public image, travel across water, and emotional well-being. Creativity and imagination flourish. Memory and connection to the past strengthen. Relationships with women and the public become significant.", "भावनात्मक रूपले समृद्ध र अन्तर्ज्ञानात्मक अवधि जसले मानसिक शान्ति, पालनपोषण र ग्रहणशीलतामा जोड दिन्छ। आमा, घरेलु जीवन, सार्वजनिक छवि, पानी पार यात्रा र भावनात्मक कल्याणमा ध्यान केन्द्रित। सिर्जनशीलता र कल्पना फस्टाउँछ। स्मृति र भूतकालसँगको सम्बन्ध बलियो हुन्छ। महिलाहरू र जनतासँगको सम्बन्ध महत्त्वपूर्ण हुन्छ।"),
DASHA_INTERP_MAHADASHA_MARS("A period of heightened energy, courage, initiative, and competitive drive. Focus on property matters, real estate, siblings, technical and engineering pursuits, sports, and surgery. Decisive action is favored. Physical vitality increases. Good for tackling challenges requiring strength and determination.", "ऊर्जा, साहस, पहल र प्रतिस्पर्धात्मक उत्प्रेरणाको उच्च अवधि। सम्पत्ति मामिला, घरजग्गा, भाइबहिनी, प्राविधिक र इन्जिनियरिङ, खेलकुद र शल्यक्रियामा ध्यान केन्द्रित। निर्णायक कार्यलाई प्राथमिकता दिइन्छ। शारीरिक जीवनशक्ति बढ्छ। बल र दृढ संकल्प चाहिने चुनौतीहरू सामना गर्न राम्रो।"),
DASHA_INTERP_MAHADASHA_MERCURY("A period of enhanced learning, communication, analytical thinking, and commerce. Focus on education, writing, publishing, accounting, trade, and intellectual pursuits. Social connections expand through skillful communication. Good for developing skills, starting businesses, and mastering information.", "सिकाइ, सञ्चार, विश्लेषणात्मक सोच र वाणिज्यको उन्नत अवधि। शिक्षा, लेखन, प्रकाशन, लेखा, व्यापार र बौद्धिक खोजमा ध्यान केन्द्रित। दक्ष सञ्चार मार्फत सामाजिक सम्बन्ध विस्तार हुन्छ। सीप विकास, व्यवसाय सुरु गर्न र जानकारीमा दक्षता हासिल गर्न राम्रो।"),
    DASHA_INTERP_MAHADASHA_JUPITER("A period of wisdom, expansion, prosperity, and divine grace (Guru's blessings)", "A period of wisdom, expansion, prosperity, and divine grace (Guru's blessings)"),
DASHA_INTERP_MAHADASHA_VENUS("A period of luxury, beauty, relationships, artistic expression, and material comforts. Focus on marriage, partnerships, arts, music, dance, vehicles, jewelry, and sensory pleasures. Creativity and romance blossom. Refinement in all areas of life. Good for enhancing beauty, wealth, and experiencing life's pleasures.", "विलासिता, सौन्दर्य, सम्बन्ध, कलात्मक अभिव्यक्ति र भौतिक सुविधाहरूको अवधि। विवाह, साझेदारी, कला, सङ्गीत, नृत्य, सवारीसाधन, गहना र इन्द्रिय आनन्दमा ध्यान केन्द्रित। सिर्जनशीलता र रोमान्स फस्टाउँछ। जीवनका सबै क्षेत्रमा परिष्करण। सौन्दर्य, सम्पत्ति बढाउन र जीवनका आनन्दहरू अनुभव गर्न राम्रो।"),
DASHA_INTERP_MAHADASHA_SATURN("A period of discipline, karmic lessons, perseverance, and structural growth. Focus on service, responsibility, hard work, long-term projects, and lessons through patience. Delays and obstacles ultimately lead to lasting success and maturity. Time to build solid foundations and pay karmic debts.", "अनुशासन, कार्मिक पाठ, दृढता र संरचनात्मक विकासको अवधि। सेवा, जिम्मेवारी, कठिन परिश्रम, दीर्घकालीन परियोजना र धैर्य मार्फत पाठहरूमा ध्यान केन्द्रित। ढिलाइ र बाधाहरूले अन्ततः स्थायी सफलता र परिपक्वता ल्याउँछ। ठोस आधार निर्माण गर्ने र कार्मिक ऋण चुक्ता गर्ने समय।"),
DASHA_INTERP_MAHADASHA_RAHU("A period of intense worldly ambition, unconventional paths, and material desires. Focus on foreign connections, technology, innovation, and breaking traditional boundaries. Sudden opportunities and unexpected changes arise. Material gains through unusual or non-traditional means. Beware of illusions.", "तीव्र सांसारिक महत्त्वाकांक्षा, अपरम्परागत मार्ग र भौतिक इच्छाको अवधि। विदेशी सम्बन्ध, प्रविधि, नवीनता र परम्परागत सीमाहरू तोड्नमा ध्यान केन्द्रित। अचानक अवसरहरू र अप्रत्याशित परिवर्तनहरू आउँछन्। असामान्य वा गैर-परम्परागत माध्यमबाट भौतिक लाभ। भ्रमबाट सावधान रहनुहोस्।"),
    DASHA_INTERP_MAHADASHA_KETU("A period of spirituality, detachment, and profound inner transformation. Focus on liberation (moksha)", "A period of spirituality, detachment, and profound inner transformation. Focus on liberation (moksha)"),
DASHA_INTERP_MAHADASHA_DEFAULT("A period of transformation and karmic unfolding according to planetary influences.", "ग्रहीय प्रभाव अनुसार रूपान्तरण र कार्मिक विकासको अवधि।"),
    DASHA_INTERP_ANTARDASHA_SUN("Current sub-period (Bhukti)", "Current sub-period (Bhukti)"),
DASHA_INTERP_ANTARDASHA_MOON("Current sub-period emphasizes emotional matters, mental peace, mother, public image, domestic affairs, and connection with women. Intuition heightens.", "हालको उप-अवधिले भावनात्मक मामिला, मानसिक शान्ति, आमा, सार्वजनिक छवि, घरेलु मामिला र महिलाहरूसँगको सम्बन्धमा जोड दिन्छ। अन्तर्ज्ञान तीव्र हुन्छ।"),
DASHA_INTERP_ANTARDASHA_MARS("Current sub-period brings increased energy, drive for action, courage, and matters involving property, siblings, competition, or technical endeavors.", "हालको उप-अवधिले बढेको ऊर्जा, कार्यको लागि उत्प्रेरणा, साहस र सम्पत्ति, भाइबहिनी, प्रतिस्पर्धा वा प्राविधिक प्रयासका मामिलाहरू ल्याउँछ।"),
DASHA_INTERP_ANTARDASHA_MERCURY("Current sub-period emphasizes communication, learning, business transactions, intellectual activities, and connections with younger people or merchants.", "हालको उप-अवधिले सञ्चार, सिकाइ, व्यापारिक लेनदेन, बौद्धिक गतिविधिहरू र साना मानिसहरू वा व्यापारीहरूसँगको सम्बन्धमा जोड दिन्छ।"),
DASHA_INTERP_ANTARDASHA_JUPITER("Current sub-period brings wisdom, expansion, good fortune, and focus on spirituality, teachers, children, higher education, or legal matters.", "हालको उप-अवधिले बुद्धि, विस्तार, सुभाग्य र आध्यात्मिकता, शिक्षकहरू, सन्तान, उच्च शिक्षा वा कानुनी मामिलाहरूमा ध्यान केन्द्रित गर्छ।"),
DASHA_INTERP_ANTARDASHA_VENUS("Current sub-period emphasizes relationships, romance, creativity, luxury, artistic pursuits, material comforts, and partnership matters.", "हालको उप-अवधिले सम्बन्ध, रोमान्स, सिर्जनशीलता, विलासिता, कलात्मक खोज, भौतिक सुविधा र साझेदारी मामिलाहरूमा जोड दिन्छ।"),
DASHA_INTERP_ANTARDASHA_SATURN("Current sub-period brings discipline, responsibility, hard work, delays, and lessons requiring patience. Focus on service and long-term efforts.", "हालको उप-अवधिले अनुशासन, जिम्मेवारी, कठिन परिश्रम, ढिलाइ र धैर्य चाहिने पाठहरू ल्याउँछ। सेवा र दीर्घकालीन प्रयासमा ध्यान केन्द्रित।"),
DASHA_INTERP_ANTARDASHA_RAHU("Current sub-period emphasizes worldly ambitions, unconventional approaches, foreign matters, technology, and sudden changes or opportunities.", "हालको उप-अवधिले सांसारिक महत्त्वाकांक्षा, अपरम्परागत दृष्टिकोण, विदेशी मामिला, प्रविधि र अचानक परिवर्तन वा अवसरहरूमा जोड दिन्छ।"),
DASHA_INTERP_ANTARDASHA_KETU("Current sub-period brings spiritual insights, detachment, introspection, research, and resolution of past karmic patterns. Material concerns recede.", "हालको उप-अवधिले आध्यात्मिक अन्तर्दृष्टि, वैराग्य, आत्मनिरीक्षण, अनुसन्धान र पूर्व कार्मिक ढाँचाको समाधान ल्याउँछ। भौतिक चिन्ताहरू पछाडि हट्छन्।"),
DASHA_INTERP_ANTARDASHA_DEFAULT("Current sub-period brings mixed planetary influences requiring careful navigation.", "हालको उप-अवधिले सावधानीपूर्वक मार्गदर्शन चाहिने मिश्रित ग्रहीय प्रभावहरू ल्याउँछ।"),
CHARA_DASHA_CALC_ERROR("Unknown error calculating Chara Dasha", "कारा दशा गणना गर्दा अज्ञात त्रुटि"),
CHARA_DASHA_TYPE("Type", "प्रकार"),
YOGINI_MANGALA("Mangala", "मङ्गला"),
YOGINI_PINGALA("Pingala", "पिङ्गला"),
YOGINI_DHANYA("Dhanya", "धन्या"),
YOGINI_BHRAMARI("Bhramari", "भ्रामरी"),
YOGINI_BHADRIKA("Bhadrika", "भद्रिका"),
YOGINI_ULKA("Ulka", "उल्का"),
YOGINI_SIDDHA("Siddha", "सिद्धा"),
YOGINI_SANKATA("Sankata", "सङ्कटा"),
    YOGINI_DEITY_CHANDRA("Chandra (Moon)", "Chandra (Moon)"),
    YOGINI_DEITY_SURYA("Surya (Sun)", "Surya (Sun)"),
    YOGINI_DEITY_GURU("Guru (Jupiter)", "Guru (Jupiter)"),
    YOGINI_DEITY_MANGAL("Mangal (Mars)", "Mangal (Mars)"),
    YOGINI_DEITY_BUDHA("Budha (Mercury)", "Budha (Mercury)"),
    YOGINI_DEITY_SHANI("Shani (Saturn)", "Shani (Saturn)"),
    YOGINI_DEITY_SHUKRA("Shukra (Venus)", "Shukra (Venus)"),
YOGINI_DEITY_RAHU("Rahu", "राहु")
}
