package com.astro.storm.core.common
enum class StringKeyVarshaphala(override val en: String, override val ne: String) : StringKeyInterface {
VARSHA_RESET_YEAR("Reset to Current Year", "हालको वर्षमा रिसेट गर्नुहोस्"),
VARSHA_FORMAT_DATE_FULL("EEEE, MMMM d, yyyy", "EEEE, MMMM d, yyyy"),
VARSHA_FORMAT_TIME_FULL("h:mm:ss a", "h:mm:ss a"),
VARSHA_FORMAT_DATE_SHORT("MMM d", "MMM d"),
VARSHA_COORD_FORMAT("%.1f°", "%.1f°"),
VARSHA_SIGN_DEGREE_FORMAT("%1\$s %2\$.1f°", "%1\$s %2\$.1f°"),
VARSHA_MUNTHA_POS_FORMAT("House %1\$d • %2\$.1f°", "भाव %1\$d • %2\$.1f°"),
TAJIKA_ITHASALA("Ithasala", "इतशाल"),
TAJIKA_ITHASALA_DESC("Applying aspect - promises fulfillment of matters", "निकटवर्ती पक्ष - कार्यहरू पूर्ण हुने वाचा"),
TAJIKA_EASARAPHA("Easarapha", "इसराफ"),
TAJIKA_EASARAPHA_DESC("Separating aspect - event has passed or is fading", "विलग पक्ष - घटना बितिसकेको वा क्षीण हुँदैछ"),
TAJIKA_NAKTA("Nakta", "नक्त"),
TAJIKA_NAKTA_DESC("Transmission of light with reception - indirect completion", "ग्रहणसहित प्रकाश प्रसारण - अप्रत्यक्ष पूर्णता"),
TAJIKA_YAMAYA("Yamaya", "यमाया"),
TAJIKA_YAMAYA_DESC("Translation of light - third planet connects significators", "प्रकाश अनुवाद - तेस्रो ग्रहले कारकहरू जोड्दछ"),
TAJIKA_MANAU("Manau", "मनौ"),
TAJIKA_MANAU_DESC("Reverse application - slower planet applies to faster", "उल्टो प्रयोग - ढिलो ग्रहले छिटोमा प्रयोग गर्छ"),
TAJIKA_KAMBOOLA("Kamboola", "कम्बूल"),
TAJIKA_KAMBOOLA_DESC("Powerful Ithasala with angular placement", "केन्द्र स्थानसहित शक्तिशाली इतशाल"),
TAJIKA_GAIRI_KAMBOOLA("Gairi-Kamboola", "गैरी-कम्बूल"),
TAJIKA_GAIRI_KAMBOOLA_DESC("Weaker form of Kamboola", "कम्बूलको कमजोर रूप"),
TAJIKA_KHALASARA("Khalasara", "खलासर"),
TAJIKA_KHALASARA_DESC("Mutual separation - dissolution of matters", "पारस्परिक विलगता - कार्यहरूको विघटन"),
TAJIKA_RADDA("Radda", "रद्द"),
TAJIKA_RADDA_DESC("Refranation - retrograde breaks the aspect", "भंग - वक्री गतिले पक्ष तोड्छ"),
TAJIKA_DUHPHALI_KUTTHA("Duhphali-Kuttha", "दुःफली-कुट्ठ"),
TAJIKA_DUHPHALI_KUTTHA_DESC("Malefic intervention prevents completion", "पापग्रह हस्तक्षेपले पूर्णता रोक्छ"),
TAJIKA_TAMBIRA("Tambira", "तम्बीर"),
TAJIKA_TAMBIRA_DESC("Indirect aspect through intermediary", "मध्यस्थ मार्फत अप्रत्यक्ष पक्ष"),
TAJIKA_KUTTHA("Kuttha", "कुट्ठ"),
TAJIKA_KUTTHA_DESC("Impediment to aspect completion", "पक्ष पूर्णतामा बाधा"),
TAJIKA_DURAPHA("Durapha", "दुराफ"),
TAJIKA_DURAPHA_DESC("Hard aspect causing difficulties", "कठिनाइहरू निम्त्याउने कडा पक्ष"),
TAJIKA_MUTHASHILA("Muthashila", "मुथशिल"),
TAJIKA_MUTHASHILA_DESC("Mutual application between planets", "ग्रहहरू बीच पारस्परिक प्रयोग"),
TAJIKA_IKKABALA("Ikkabala", "इक्कबल"),
TAJIKA_IKKABALA_DESC("Unity of strength between planets", "ग्रहहरू बीच बलको एकता"),
SAHAM_PUNYA("Fortune", "पुण्य"),
SAHAM_PUNYA_SANSKRIT("Punya Saham", "पुण्य सहम"),
SAHAM_PUNYA_DESC("Overall luck and prosperity", "समग्र भाग्य र समृद्धि"),
SAHAM_VIDYA("Education", "विद्या"),
SAHAM_VIDYA_SANSKRIT("Vidya Saham", "विद्या सहम"),
SAHAM_VIDYA_DESC("Learning and knowledge", "सिकाइ र ज्ञान"),
SAHAM_YASHAS("Fame", "यश"),
SAHAM_YASHAS_SANSKRIT("Yashas Saham", "यश सहम"),
SAHAM_YASHAS_DESC("Reputation and recognition", "प्रतिष्ठा र मान्यता"),
SAHAM_MITRA("Friends", "मित्र"),
SAHAM_MITRA_SANSKRIT("Mitra Saham", "मित्र सहम"),
SAHAM_MITRA_DESC("Friendship and alliances", "मित्रता र गठबन्धन"),
SAHAM_MAHATMYA("Greatness", "महात्म्य"),
SAHAM_MAHATMYA_SANSKRIT("Mahatmya Saham", "महात्म्य सहम"),
SAHAM_MAHATMYA_DESC("Spiritual achievement", "आध्यात्मिक उपलब्धि"),
SAHAM_ASHA("Hope", "आशा"),
SAHAM_ASHA_SANSKRIT("Asha Saham", "आशा सहम"),
SAHAM_ASHA_DESC("Aspirations and wishes", "आकांक्षा र इच्छाहरू"),
SAHAM_SAMARTHA("Capability", "समर्थ"),
SAHAM_SAMARTHA_SANSKRIT("Samartha Saham", "समर्थ सहम"),
SAHAM_SAMARTHA_DESC("Ability and competence", "क्षमता र योग्यता"),
SAHAM_BHRATRI("Siblings", "भ्रातृ"),
SAHAM_BHRATRI_SANSKRIT("Bhratri Saham", "भ्रातृ सहम"),
SAHAM_BHRATRI_DESC("Brothers and sisters", "दाजुभाइ र दिदीबहिनी"),
SAHAM_PITRI("Father", "पितृ"),
SAHAM_PITRI_SANSKRIT("Pitri Saham", "पितृ सहम"),
SAHAM_PITRI_DESC("Father's welfare", "बुबाको कल्याण"),
SAHAM_MATRI("Mother", "मातृ"),
SAHAM_MATRI_SANSKRIT("Matri Saham", "मातृ सहम"),
SAHAM_MATRI_DESC("Mother's welfare", "आमाको कल्याण"),
SAHAM_PUTRA("Children", "पुत्र"),
SAHAM_PUTRA_SANSKRIT("Putra Saham", "पुत्र सहम"),
SAHAM_PUTRA_DESC("Offspring and progeny", "सन्तान"),
SAHAM_VIVAHA("Marriage", "विवाह"),
SAHAM_VIVAHA_SANSKRIT("Vivaha Saham", "विवाह सहम"),
SAHAM_VIVAHA_DESC("Matrimony and partnership", "विवाह र साझेदारी"),
SAHAM_KARMA("Career", "कर्म"),
SAHAM_KARMA_SANSKRIT("Karma Saham", "कर्म सहम"),
SAHAM_KARMA_DESC("Profession and livelihood", "पेशा र जीविका"),
SAHAM_ROGA("Disease", "रोग"),
SAHAM_ROGA_SANSKRIT("Roga Saham", "रोग सहम"),
SAHAM_ROGA_DESC("Health challenges", "स्वास्थ्य चुनौतीहरू"),
SAHAM_MRITYU("Longevity", "मृत्यु"),
SAHAM_MRITYU_SANSKRIT("Mrityu Saham", "मृत्यु सहम"),
SAHAM_MRITYU_DESC("Life span indicators", "जीवन अवधि संकेतकहरू"),
SAHAM_PARADESA("Foreign", "परदेश"),
SAHAM_PARADESA_SANSKRIT("Paradesa Saham", "परदेश सहम"),
SAHAM_PARADESA_DESC("Travel and foreign lands", "यात्रा र विदेश"),
SAHAM_DHANA("Wealth", "धन"),
SAHAM_DHANA_SANSKRIT("Dhana Saham", "धन सहम"),
SAHAM_DHANA_DESC("Financial prosperity", "आर्थिक समृद्धि"),
SAHAM_RAJA("Power", "राज"),
SAHAM_RAJA_SANSKRIT("Raja Saham", "राज सहम"),
SAHAM_RAJA_DESC("Authority and position", "अधिकार र पद"),
SAHAM_BANDHANA("Bondage", "बन्धन"),
SAHAM_BANDHANA_SANSKRIT("Bandhana Saham", "बन्धन सहम"),
SAHAM_BANDHANA_DESC("Restrictions and obstacles", "प्रतिबन्ध र बाधाहरू"),
SAHAM_KARYASIDDHI_TYPE("Success", "कार्यसिद्धि"),
SAHAM_KARYASIDDHI_TYPE_SANSKRIT("Karyasiddhi Saham", "कार्यसिद्धि सहम"),
SAHAM_KARYASIDDHI_TYPE_DESC("Accomplishment of goals", "लक्ष्य प्राप्ति"),
MUNTHA_PERSONAL_GROWTH("Personal Growth", "व्यक्तिगत विकास"),
MUNTHA_NEW_BEGINNINGS("New Beginnings", "नयाँ शुरुवातहरू"),
MUNTHA_HEALTH_FOCUS("Health Focus", "स्वास्थ्य फोकस"),
MUNTHA_FINANCIAL_GAINS("Financial Gains", "आर्थिक लाभ"),
MUNTHA_FAMILY_MATTERS("Family Matters", "पारिवारिक मामिलाहरू"),
MUNTHA_SPEECH("Speech", "वाणी"),
MUNTHA_COMMUNICATION("Communication", "सञ्चार"),
MUNTHA_SHORT_TRAVELS("Short Travels", "छोटो यात्राहरू"),
MUNTHA_SIBLINGS("Siblings", "भाइबहिनी"),
MUNTHA_HOME_AFFAIRS("Home Affairs", "घरेलु मामिलाहरू"),
MUNTHA_PROPERTY("Property", "सम्पत्ति"),
MUNTHA_INNER_PEACE("Inner Peace", "आन्तरिक शान्ति"),
MUNTHA_CREATIVITY("Creativity", "सिर्जनशीलता"),
MUNTHA_ROMANCE("Romance", "रोमान्स"),
MUNTHA_CHILDREN("Children", "सन्तान"),
MUNTHA_SERVICE("Service", "सेवा"),
MUNTHA_HEALTH_ISSUES("Health Issues", "स्वास्थ्य समस्याहरू"),
MUNTHA_COMPETITION("Competition", "प्रतिस्पर्धा"),
MUNTHA_PARTNERSHIPS("Partnerships", "साझेदारीहरू"),
MUNTHA_MARRIAGE("Marriage", "विवाह"),
MUNTHA_BUSINESS("Business", "व्यापार"),
MUNTHA_TRANSFORMATION("Transformation", "रूपान्तरण"),
MUNTHA_RESEARCH("Research", "अनुसन्धान"),
MUNTHA_INHERITANCE("Inheritance", "विरासत"),
MUNTHA_FORTUNE("Fortune", "भाग्य"),
MUNTHA_LONG_TRAVEL("Long Travel", "लामो यात्रा"),
MUNTHA_HIGHER_LEARNING("Higher Learning", "उच्च शिक्षा"),
MUNTHA_CAREER_ADVANCEMENT("Career Advancement", "क्यारियर प्रगति"),
MUNTHA_RECOGNITION("Recognition", "मान्यता"),
MUNTHA_AUTHORITY("Authority", "अधिकार"),
MUNTHA_GAINS("Gains", "लाभ"),
MUNTHA_FRIENDS("Friends", "मित्रहरू"),
MUNTHA_FULFILLED_WISHES("Fulfilled Wishes", "पूरा भएका इच्छाहरू"),
MUNTHA_SPIRITUALITY("Spirituality", "आध्यात्मिकता"),
MUNTHA_FOREIGN_LANDS("Foreign Lands", "विदेश"),
MUNTHA_EXPENSES("Expenses", "खर्चहरू"),
MUNTHA_GENERAL_GROWTH("General Growth", "सामान्य विकास"),
VARSHA_HOUSE_1_SIG("personal development and health", "व्यक्तिगत विकास र स्वास्थ्य"),
VARSHA_HOUSE_2_SIG("finances and family", "वित्त र परिवार"),
VARSHA_HOUSE_3_SIG("communication and siblings", "सञ्चार र भाइबहिनी"),
VARSHA_HOUSE_4_SIG("home and property", "घर र सम्पत्ति"),
VARSHA_HOUSE_5_SIG("creativity and children", "सिर्जनशीलता र सन्तान"),
VARSHA_HOUSE_6_SIG("health and service", "स्वास्थ्य र सेवा"),
VARSHA_HOUSE_7_SIG("partnerships and marriage", "साझेदारी र विवाह"),
VARSHA_HOUSE_8_SIG("transformation and inheritance", "रूपान्तरण र विरासत"),
VARSHA_HOUSE_9_SIG("fortune and higher learning", "भाग्य र उच्च शिक्षा"),
VARSHA_HOUSE_10_SIG("career and status", "क्यारियर र स्थिति"),
VARSHA_HOUSE_11_SIG("gains and friendships", "लाभ र मित्रता"),
VARSHA_HOUSE_12_SIG("spirituality and foreign matters", "आध्यात्मिकता र विदेशी मामिलाहरू"),
VARSHA_HOUSE_VARIOUS("various life areas", "विभिन्न जीवन क्षेत्रहरू"),
VARSHA_SUN_NATURE("vitality, authority, and self-expression", "जीवनशक्ति, अधिकार र आत्म-अभिव्यक्ति"),
VARSHA_MOON_NATURE("emotions, nurturing, and public connections", "भावनाहरू, पालनपोषण र सार्वजनिक सम्बन्धहरू"),
VARSHA_MARS_NATURE("energy, initiative, and competitive drive", "ऊर्जा, पहल र प्रतिस्पर्धात्मक उत्प्रेरणा"),
VARSHA_MERCURY_NATURE("communication, learning, and business", "सञ्चार, सिकाइ र व्यापार"),
VARSHA_JUPITER_NATURE("wisdom, expansion, and good fortune", "बुद्धि, विस्तार र सुभाग्य"),
VARSHA_VENUS_NATURE("relationships, creativity, and pleasures", "सम्बन्धहरू, सिर्जनशीलता र आनन्द"),
VARSHA_SATURN_NATURE("discipline, responsibility, and long-term goals", "अनुशासन, जिम्मेवारी र दीर्घकालीन लक्ष्यहरू"),
VARSHA_RAHU_NATURE("ambition, innovation, and unconventional paths", "महत्त्वाकांक्षा, नवीनता र अपरम्परागत मार्गहरू"),
VARSHA_KETU_NATURE("spirituality, detachment, and past karma", "आध्यात्मिकता, वैराग्य र पूर्व कर्म"),
VARSHA_GENERAL_NATURE("general influences", "सामान्य प्रभावहरू"),
VARSHA_STRENGTH_EXALTED("Exalted", "उच्च"),
VARSHA_STRENGTH_STRONG("Strong", "बलियो"),
VARSHA_STRENGTH_MODERATE("Moderate", "मध्यम"),
VARSHA_STRENGTH_ANGULAR("Angular", "केन्द्रीय"),
VARSHA_STRENGTH_RETROGRADE("Retrograde", "वक्री"),
VARSHA_STRENGTH_DEBILITATED("Debilitated", "नीच"),
VARSHA_STRENGTH_UNKNOWN("Unknown", "अज्ञात"),
VARSHA_PERIOD_EXCEPTIONAL("This period promises exceptional results", "यो अवधिले असाधारण परिणामहरूको वाचा गर्छ"),
VARSHA_PERIOD_WELL_SUPPORTED("This period is well-supported for success", "यो अवधि सफलताको लागि राम्ररी समर्थित छ"),
VARSHA_PERIOD_EXTRA_EFFORT("This period requires extra effort and patience", "यो अवधिमा थप प्रयास र धैर्य चाहिन्छ"),
VARSHA_PERIOD_MIXED("This period brings mixed but manageable influences", "यो अवधिले मिश्रित तर व्यवस्थापनयोग्य प्रभावहरू ल्याउँछ"),
VARSHA_DURING_PERIOD("During this %s period, focus shifts to %s, particularly affecting %s. %s.", "यो %s अवधिमा, %s मा फोकस सर्छ, विशेष गरी %s लाई असर गर्दछ। %s।"),
VARSHA_YEARLORD_SUN("Year Lord Sun brings focus on leadership, authority, and self-expression.", "वर्ष स्वामी सूर्यले नेतृत्व, अधिकार र आत्म-अभिव्यक्तिमा फोकस ल्याउँछ।"),
VARSHA_YEARLORD_MOON("Year Lord Moon emphasizes emotional wellbeing and public connections.", "वर्ष स्वामी चन्द्रमाले भावनात्मक कल्याण र सार्वजनिक सम्बन्धहरूमा जोड दिन्छ।"),
VARSHA_YEARLORD_MARS("Year Lord Mars energizes initiatives and competitive endeavors.", "वर्ष स्वामी मंगलले पहलहरू र प्रतिस्पर्धात्मक प्रयासहरूलाई ऊर्जित गर्छ।"),
VARSHA_YEARLORD_MERCURY("Year Lord Mercury enhances communication and business activities.", "वर्ष स्वामी बुधले सञ्चार र व्यापारिक गतिविधिहरू बढाउँछ।"),
VARSHA_YEARLORD_JUPITER("Year Lord Jupiter bestows wisdom, expansion, and good fortune.", "वर्ष स्वामी बृहस्पतिले बुद्धि, विस्तार र सुभाग्य प्रदान गर्छ।"),
VARSHA_YEARLORD_VENUS("Year Lord Venus brings harmony to relationships and creativity.", "वर्ष स्वामी शुक्रले सम्बन्धहरू र सिर्जनशीलतामा सामञ्जस्य ल्याउँछ।"),
VARSHA_YEARLORD_SATURN("Year Lord Saturn teaches discipline and responsibility.", "वर्ष स्वामी शनिले अनुशासन र जिम्मेवारी सिकाउँछ।"),
VARSHA_YEARLORD_GENERIC("The Year Lord influences various aspects with balanced energy.", "वर्ष स्वामीले सन्तुलित ऊर्जासहित विभिन्न पक्षहरूलाई प्रभाव पार्छ।"),
    TRIPATAKI_DHARMA("Dharma (1, 5, 9)", "Dharma (1, 5, 9)"),
    TRIPATAKI_ARTHA("Artha (2, 6, 10)", "Artha (2, 6, 10)"),
    TRIPATAKI_KAMA("Kama (3, 7, 11)", "Kama (3, 7, 11)"),
TRIPATAKI_DHARMA_DOMINANT("Spiritual growth and righteous pursuits dominate", "आध्यात्मिक वृद्धि र धार्मिक खोजीहरू प्रभावी"),
TRIPATAKI_ARTHA_DOMINANT("Material prosperity and career emphasis", "भौतिक समृद्धि र क्यारियर जोड"),
TRIPATAKI_KAMA_DOMINANT("Relationships and desires take center stage", "सम्बन्धहरू र इच्छाहरू केन्द्रमा"),
TRIPATAKI_BALANCED("Balanced influences across all areas", "सबै क्षेत्रहरूमा सन्तुलित प्रभाव"),
TRIPATAKI_NO_PLANETS("No planets in %s sector - quieter year for these matters.", "%s क्षेत्रमा कुनै ग्रह छैन - यी मामिलाहरूको लागि शान्त वर्ष।"),
TRIPATAKI_BENEFIC_INFLUENCE("Benefic %s bring favorable influences.", "शुभ %s ले अनुकूल प्रभावहरू ल्याउँछ।"),
TRIPATAKI_MALEFIC_INFLUENCE("Malefic %s bring challenges requiring effort.", "पाप %s ले प्रयास चाहिने चुनौतीहरू ल्याउँछ।"),
TRIPATAKI_MIXED_INFLUENCE("Mixed influences suggest variable results.", "मिश्रित प्रभावहरूले परिवर्तनशील परिणामहरू सुझाव दिन्छ।"),
TRIPATAKI_DHARMA_AREA("righteousness, fortune, and higher learning", "धार्मिकता, भाग्य र उच्च शिक्षा"),
TRIPATAKI_ARTHA_AREA("wealth, career, and practical achievements", "धन, क्यारियर र व्यावहारिक उपलब्धिहरू"),
TRIPATAKI_KAMA_AREA("relationships, desires, and social connections", "सम्बन्धहरू, इच्छाहरू र सामाजिक सम्बन्धहरू"),
    TRIPATAKI_PLANETS_IN_TRIKONA("%d planet(s)", "%d planet(s)"),
TRIPATAKI_BALANCED_DISTRIBUTION("Balanced distribution of planetary energies across all life sectors.", "सबै जीवन क्षेत्रहरूमा ग्रह ऊर्जाहरूको सन्तुलित वितरण।"),
VARSHA_TONE_EXCELLENT("excellent", "उत्कृष्ट"),
VARSHA_TONE_FAVORABLE("favorable", "अनुकूल"),
VARSHA_TONE_POSITIVE("positive", "सकारात्मक"),
VARSHA_TONE_CHALLENGING("challenging but growth-oriented", "चुनौतीपूर्ण तर विकासोन्मुख"),
VARSHA_TONE_BALANCED("balanced", "सन्तुलित"),
VARSHA_LORD_EXCELLENT("is excellently placed for positive outcomes.", "सकारात्मक परिणामहरूको लागि उत्कृष्ट रूपमा स्थित छ।"),
VARSHA_LORD_WELL_POSITIONED("is well-positioned for success.", "सफलताको लागि राम्ररी स्थित छ।"),
VARSHA_LORD_MODERATE_SUPPORT("provides moderate support.", "मध्यम समर्थन प्रदान गर्दछ।"),
VARSHA_LORD_CHALLENGES("faces challenges requiring attention.", "ध्यान चाहिने चुनौतीहरूको सामना गर्दछ।"),
VARSHA_LORD_VARIABLE("influences results variably.", "परिणामहरूलाई परिवर्तनशील रूपमा प्रभाव पार्छ।"),
VARSHA_BENEFICS_ENHANCE(" %s enhance positive outcomes.", " %s ले सकारात्मक परिणामहरू बढाउँछ।"),
VARSHA_MALEFICS_CHALLENGE(" %s may bring challenges.", " %s ले चुनौतीहरू ल्याउन सक्छ।"),
VARSHA_MIXED_PLANETS(" Mixed influences from %s.", " %s बाट मिश्रित प्रभावहरू।"),
VARSHA_DEPENDS_LORD(" Results depend primarily on the lord's position.", " परिणामहरू मुख्यतया स्वामीको स्थितिमा निर्भर छन्।"),
VARSHA_MUNTHA_EMPHASIS(" Muntha emphasizes these matters this year.", " मुन्थले यस वर्ष यी मामिलाहरूमा जोड दिन्छ।"),
VARSHA_YEARLORD_RULES(" Year Lord rules this house - significant developments expected.", " वर्ष स्वामीले यो भाव शासन गर्छ - महत्त्वपूर्ण विकासहरू अपेक्षित।"),
VARSHA_HOUSE_GOVERNS("House %d in %s governs %s.", "भाव %d %s मा %s शासन गर्दछ।"),
VARSHA_LORD_IN_HOUSE("The lord %s in house %d ", "स्वामी %s भाव %d मा "),
VARSHA_EVENT_VITALITY("Increased vitality and personal confidence", "बढेको जीवनशक्ति र व्यक्तिगत आत्मविश्वास"),
VARSHA_EVENT_NEW_VENTURES("Favorable for starting new ventures", "नयाँ उद्यमहरू सुरु गर्न अनुकूल"),
VARSHA_EVENT_SPIRITUAL("Spiritual growth and wisdom", "आध्यात्मिक वृद्धि र बुद्धि"),
VARSHA_EVENT_ACCIDENTS("Increased energy - watch for accidents", "बढेको ऊर्जा - दुर्घटनाबाट सावधान"),
VARSHA_EVENT_FINANCIAL("Financial gains and wealth accumulation", "आर्थिक लाभ र धन संचय"),
VARSHA_EVENT_FAMILY("Improvement in family relationships", "पारिवारिक सम्बन्धमा सुधार"),
VARSHA_EVENT_LUXURY("Acquisition of luxury items", "विलासी वस्तुहरूको प्राप्ति"),
VARSHA_EVENT_CREATIVE("Creative success and recognition", "सिर्जनात्मक सफलता र मान्यता"),
VARSHA_EVENT_CHILDREN_MATTERS("Favorable for children's matters", "सन्तान सम्बन्धी मामिलाहरूको लागि अनुकूल"),
VARSHA_EVENT_ACADEMIC("Academic success or childbirth possible", "शैक्षिक सफलता वा सन्तान जन्म सम्भव"),
VARSHA_EVENT_ROMANTIC("Romantic happiness", "रोमान्टिक खुशी"),
VARSHA_EVENT_PARTNERSHIPS("Strengthening of partnerships", "साझेदारीहरूको सुदृढीकरण"),
VARSHA_EVENT_MARRIAGE_BUSINESS("Favorable for marriage or business", "विवाह वा व्यापारको लागि अनुकूल"),
VARSHA_EVENT_ROMANTIC_FULFILL("Romantic fulfillment", "रोमान्टिक पूर्णता"),
VARSHA_EVENT_CAREER_ADVANCE("Career advancement or promotion", "क्यारियर प्रगति वा पदोन्नति"),
VARSHA_EVENT_RECOGNITION("Recognition from authorities", "अधिकारीहरूबाट मान्यता"),
VARSHA_EVENT_GOVT_FAVOR("Government favor or leadership role", "सरकारी कृपा वा नेतृत्व भूमिका"),
VARSHA_EVENT_DESIRES("Fulfillment of desires and wishes", "इच्छाहरू र कामनाहरूको पूर्ति"),
VARSHA_EVENT_MULTIPLE_GAINS("Gains from multiple sources", "विभिन्न स्रोतहरूबाट लाभ"),
VARSHA_OVERALL_TEMPLATE("This Varshaphala year presents an overall %s outlook. %s %s The Tajika aspects show %d favorable and %d challenging configurations. By understanding these influences, the year's potential can be maximized.", "यो वर्षफल वर्षले समग्र %s दृष्टिकोण प्रस्तुत गर्दछ। %s %s ताजिक पक्षहरूले %d अनुकूल र %d चुनौतीपूर्ण विन्यासहरू देखाउँछन्। यी प्रभावहरूलाई बुझेर, वर्षको सम्भावनालाई अधिकतम बनाउन सकिन्छ।"),
    VARSHA_MUNTHA_DIRECTS("Muntha in House %d (%s)", "Muntha in House %d (%s)"),
    SAHAM_INTERPRETATION_TEMPLATE("The %s Saham in %s (House %d)", "The %s Saham in %s (House %d)"),
SAHAM_LORD_WELL_PLACED("well-placed, promising positive outcomes", "राम्ररी स्थित, सकारात्मक परिणामहरूको वाचा"),
SAHAM_LORD_REASONABLE("providing reasonable support", "उचित समर्थन प्रदान गर्दै"),
SAHAM_LORD_ATTENTION("requiring attention and effort", "ध्यान र प्रयास चाहिने"),
SAHAM_LORD_VARIABLE("influencing matters variably", "मामिलाहरूलाई परिवर्तनशील रूपमा प्रभाव पार्दै"),
SAHAM_INDICATES("indicates specific life areas", "विशिष्ट जीवन क्षेत्रहरू संकेत गर्दछ"),
    VARSHA_REPORT_TITLE("VARSHAPHALA (ANNUAL HOROSCOPE)", "VARSHAPHALA (ANNUAL HOROSCOPE)"),
VARSHA_REPORT_NAME("Name: %s", "नाम: %s"),
    VARSHA_REPORT_YEAR("Year: %d (Age: %d)", "Year: %d (Age: %d)"),
VARSHA_REPORT_SOLAR_RETURN("Solar Return: %s", "सौर प्रतिफल: %s"),
VARSHA_REPORT_YEAR_RATING("Year Rating: %s/5.0", "वर्ष मूल्याङ्कन: %s/५.०"),
VARSHA_REPORT_SECTION_YEARLORD("YEAR LORD", "वर्ष स्वामी"),
    VARSHA_REPORT_YEARLORD_LINE("Year Lord: %s (%s)", "Year Lord: %s (%s)"),
VARSHA_REPORT_POSITION("Position: House %d", "स्थिति: भाव %d"),
VARSHA_REPORT_SECTION_MUNTHA("MUNTHA", "मुन्थ"),
VARSHA_REPORT_MUNTHA_POSITION("Muntha Position: %s° %s", "मुन्थ स्थिति: %s° %s"),
VARSHA_REPORT_MUNTHA_HOUSE("Muntha House: %d", "मुन्थ भाव: %d"),
VARSHA_REPORT_MUNTHA_LORD("Muntha Lord: %s in House %d", "मुन्थ स्वामी: %s भाव %d मा"),
VARSHA_REPORT_SECTION_THEMES("MAJOR THEMES", "मुख्य विषयहरू"),
VARSHA_REPORT_SECTION_MUDDA("MUDDA DASHA PERIODS", "मुद्द दशा अवधिहरू"),
    VARSHA_REPORT_DASHA_LINE("%s: %s to %s (%d days)", "%s: %s to %s (%d days)"),
VARSHA_REPORT_CURRENT_MARKER(" [CURRENT]", " [वर्तमान]"),
VARSHA_REPORT_FAVORABLE_MONTHS("FAVORABLE MONTHS: %s", "अनुकूल महिनाहरू: %s"),
VARSHA_REPORT_CHALLENGING_MONTHS("CHALLENGING MONTHS: %s", "चुनौतीपूर्ण महिनाहरू: %s"),
VARSHA_REPORT_SECTION_PREDICTION("OVERALL PREDICTION", "समग्र भविष्यवाणी"),
VARSHA_REPORT_FOOTER("Generated by AstroStorm - Ultra-Precision Vedic Astrology", "AstroStorm द्वारा उत्पन्न - अति-सटीक वैदिक ज्योतिष"),
MUNTHA_INTERPRETATION_TEMPLATE("Muntha in %1\$s in the %2\$d%3\$s house focuses the year's energy on %4\$s. The Muntha lord %5\$s in house %6\$d provides %7\$s support for these matters.", "%2\$d%3\$s भावमा %1\$s मा मुन्थले वर्षको ऊर्जालाई %4\$s मा केन्द्रित गर्दछ। मुन्थ स्वामी %5\$s भाव %6\$d मा यी मामिलाहरूको लागि %7\$s समर्थन प्रदान गर्दछ।"),
MUNTHA_SUPPORT_EXCELLENT("excellent", "उत्कृष्ट"),
MUNTHA_SUPPORT_FAVORABLE("favorable", "अनुकूल"),
MUNTHA_SUPPORT_CHALLENGING("challenging but growth-oriented", "चुनौतीपूर्ण तर विकासोन्मुख"),
MUNTHA_SUPPORT_VARIABLE("variable", "परिवर्तनशील"),
VARSHA_SAHAM_RELATES("relates to %s", "%s सँग सम्बन्धित छ"),
VARSHA_SAHAM_LORD_SUPPORT("The lord %s provides %s support.", "स्वामी %s ले %s समर्थन प्रदान गर्दछ।"),
VARSHA_TONE_SUPPORTIVE("supportive", "सहयोगी"),
    TAJIKA_ITHASALA_EFFECT("Ithasala (Favorable)", "Ithasala (Favorable)"),
    TAJIKA_EASARAPHA_EFFECT("Easarapha (Separation)", "Easarapha (Separation)"),
    TAJIKA_KAMBOOLA_EFFECT("Kamboola (Strong)", "Kamboola (Strong)"),
    TAJIKA_RADDA_EFFECT("Radda (Obstruction)", "Radda (Obstruction)"),
    TAJIKA_DURAPHA_EFFECT("Durapha (Weak)", "Durapha (Weak)"),
TAJIKA_INFLUENCE_ENERGY("This aspect brings %s energy to %s matters.", "यो दृष्टिले %s मामिलामा %s ऊर्जा ल्याउँछ।"),
TAJIKA_PREDICTION_X_FOR_Y("%s for %s", "%s को लागि %s"),
VARSHA_DASHA_PERIOD_FORMAT("%1\$s - %2\$s Period", "%1\$s - %2\$s अवधि"),
VARSHA_DASHA_EXCEPTIONAL("An exceptional period for %s, bringing significant rewards.", "%s को लागि एक असाधारण अवधि, महत्त्वपूर्ण पुरस्कार ल्याउँदै।"),
VARSHA_DASHA_SUPPORTED("A well-supported time for %s and positive developments.", "%s र सकारात्मक विकासका लागि राम्रो समर्थन भएको समय।"),
VARSHA_DASHA_CHALLENGING("A challenging phase for %s requiring extra effort and caution.", "अतिरिक्त प्रयास र सावधानी आवश्यक पर्ने %s को लागि एक चुनौतीपूर्ण चरण।"),
VARSHA_DASHA_MIXED("A mixed period for %s with both opportunities and minor hurdles.", "अवसर र साना बाधाहरू दुवै भएको %s को लागि एक मिश्रित अवधि।"),
VARSHA_DASHA_PREDICTION_FORMAT("%s focuses on %s. %s", "%s ले %s मा ध्यान केन्द्रित गर्दछ। %s"),
VARSHA_STRENGTH_EXCELLENT("Excellent", "उत्कृष्ट"),
VARSHA_STRENGTH_WEAK("Weak", "कमजोर"),
VARSHA_STRENGTH_CHALLENGED("Challenged", "चुनौतीपूर्ण"),
VARSHA_HOUSE_LORD_POSITION("The house lord %s is positioned in H%d.", "भाव स्वामी %s भाव%d मा स्थित छ।"),
VARSHA_HOUSE_LORD_EXCELLENT("This position is exceptionally strong, promising major success in %s.", "यो स्थिति असाधारण रूपमा बलियो छ, जसले %s मा ठूलो सफलताको वाचा गर्दछ।"),
VARSHA_HOUSE_LORD_STRONG("The lord is well-placed, supporting steady growth and positive results in %s.", "स्वामी राम्रो स्थानमा छ, जसले %s मा स्थिर विकास र सकारात्मक नतिजाहरूलाई समर्थन गर्दछ।"),
VARSHA_HOUSE_LORD_MODERATE("The lord's position is moderate, indicating balanced results for %s.", "स्वामीको स्थिति मध्यम छ, जसले %s को लागि सन्तुलित नतिजाहरू संकेत गर्दछ।"),
VARSHA_HOUSE_LORD_CHALLENGED("The lord faces challenges here, requiring caution and extra effort regarding %s.", "स्वामीले यहाँ चुनौतीहरूको सामना गर्नु पर्छ, जसले %s को सम्बन्धमा सावधानी र अतिरिक्त प्रयासको आवश्यकता देखाउँछ।"),
VARSHA_HOUSE_LORD_VARIABLE("Current placement indicates variable or inconsistent results for %s.", "वर्तमान स्थितिले %s को लागि परिवर्तनशील वा अस्थिर नतिजाहरू संकेत गर्दछ।"),
VARSHA_HOUSE_BENEFICS_ENHANCE("Presence of benefic planets enhances the themes of %s.", "शुभ ग्रहहरूको उपस्थितिले %s का विषयहरूलाई सुधार्छ।"),
VARSHA_HOUSE_MALEFICS_CHALLENGE("Presence of malefic planets may challenge the stability of %s.", "पाप ग्रहहरूको उपस्थितिले %s को स्थिरतालाई चुनौती दिन सक्छ।"),
VARSHA_HOUSE_MIXED_INF("Mixed planetary influences suggest a period of ups and downs for %s.", "मिश्रित ग्रह प्रभावले %s को लागि उतारचढावको अवधि संकेत गर्दछ।"),
VARSHA_HOUSE_LORD_DEPENDENT("Success in %s depends heavily on other planetary configurations.", "%s मा सफलता धेरै हदसम्म अन्य ग्रह विन्यासमा निर्भर गर्दछ।"),
VARSHA_HOUSE_MUNTHA_EMPHASIS("Muntha's presence here significantly increases the priority of %s this year.", "यहाँ मुन्थको उपस्थितिले यस वर्ष %s को प्राथमिकतालाई महत्त्वपूर्ण रूपमा बढाउँछ।"),
VARSHA_HOUSE_YEARLORD_RULE("Year Lord's rule over this house elevates the importance of %s matters.", "यस भावमा वर्ष स्वामीको शासनले %s मामिलाहरूको महत्त्व बढाउँछ।"),
    VARSHA_HOUSE_PREDICTION_FORMAT("House %1\$d (%2\$s)", "House %1\$d (%2\$s)"),
    VARSHA_YEARLORD_DIGNITY_FORMAT("%1\$s is in %2\$s (House %3\$d)", "%1\$s is in %2\$s (House %3\$d)"),
VARSHA_EVENT_SPIRITUAL_GROWTH("Spiritual growth and self-discovery", "आध्यात्मिक विकास र आत्म-खोज"),
VARSHA_EVENT_INCREASED_ENERGY("Increased energy and dynamic activity", "बढेको ऊर्जा र गतिशील गतिविधि"),
VARSHA_EVENT_FINANCIAL_GAINS("Significant financial gains or new income sources", "महत्त्वपूर्ण आर्थिक लाभ वा नयाँ आय स्रोत"),
VARSHA_EVENT_FAMILY_RELATIONS("Strengthening of family bonds and values", "पारिवारिक सम्बन्ध र मूल्य मान्यताको सुदृढीकरण"),
VARSHA_EVENT_LUXURY_ACQUISITION("Acquisition of luxury items or increased comforts", "लक्जरी वस्तुहरूको प्राप्ति वा बढेको सुखसुविधा"),
VARSHA_EVENT_CREATIVE_SUCCESS("Success in creative pursuits and self-expression", "सिर्जनात्मक प्रयास र आत्म-अभिव्यक्तिमा सफलता"),
VARSHA_EVENT_ACADEMIC_SUCCESS("Academic success or new learning opportunities", "शैक्षिक सफलता वा नयाँ सिकाइका अवसरहरू"),
VARSHA_EVENT_ROMANTIC_HAPPINESS("Happiness in romantic relationships or with children", "रोमान्टिक सम्बन्ध वा सन्तानसँगको खुशी"),
VARSHA_EVENT_PARTNERSHIP_STRENGTH("Strengthening of business or personal partnerships", "व्यापार वा व्यक्तिगत साझेदारीको सुदृढीकरण"),
VARSHA_EVENT_MARRIAGE_FAVORABLE("Favorable conditions for marriage or long-term commitments", "विवाह वा दीर्घकालीन प्रतिबद्धताको लागि अनुकूल परिस्थिति"),
VARSHA_EVENT_ROMANTIC_FULFILLMENT("Emotional fulfillment through significant others", "महत्त्वपूर्ण व्यक्तिहरू मार्फत भावनात्मक सन्तुष्टि"),
VARSHA_EVENT_CAREER_ADVANCEMENT("Advancement in career or professional recognition", "क्यारियरमा प्रगति वा व्यावसायिक मान्यता"),
VARSHA_EVENT_AUTHORITY_RECOGNITION("Gain of authority, fame, or social status", "अधिकार, नाम वा सामाजिक स्थितिको प्राप्ति"),
VARSHA_EVENT_GOVERNMENT_FAVOR("Favor from government or influential figures", "सरकार वा प्रभावशाली व्यक्तिहरूबाट सहयोग"),
VARSHA_EVENT_DESIRE_FULFILLMENT("Fulfillment of long-held desires and ambitions", "लामो समयदेखिका इच्छाहरू र महत्त्वाकांक्षाहरूको पूर्ति"),
    VARSHA_THEME_YEARLORD("Year Lord (%s Influence)", "Year Lord (%s Influence)"),
VARSHA_THEME_MUNTHA("Muntha Focus: House %1\$d - %2\$s", "मुन्थ फोकस: भाव %1\$d - %2\$s"),
VARSHA_THEME_TRIPATAKI("Tri-Pataki Activation in %s", "%s मा त्रिपताकी सक्रियता"),
VARSHA_THEME_FAVORABLE("Favorable year for overall progress", "समग्र प्रगतिको लागि अनुकूल वर्ष"),
    VARSHA_THEME_TAJIKA("Tajika Aspect Influence: %1\$s (%2\$d/%3\$d)", "Tajika Aspect Influence: %1\$s (%2\$d/%3\$d)"),
VARSHA_EVENT_SOLAR_RETURN("Solar Return Activation", "सौर्य फिर्ती सक्रियता"),
VARSHA_EVENT_SOLAR_RETURN_DESC("The precise moment the Sun returns to your birth position.", "सूर्य तपाईंको जन्म स्थितिमा फर्कने सटीक क्षण।"),
VARSHA_EVENT_DASHA_BEGINS("%s Dasha Begins", "%s दशा सुरु हुन्छ"),
VARSHA_EVENT_DASHA_BEGINS_DESC("A minor period of %s influence starts today.", "%s प्रभावको एक सानो अवधि आजदेखि सुरु हुन्छ।"),
VARSHA_TONE_CHALLENGING_GROWTH("challenging but growth-oriented", "चुनौतीपूर्ण तर विकास उन्मुख"),
VARSHA_YEARLORD_GENERAL("The year is ruled by %s, bringing %s focus. ", "यो वर्ष %s द्वारा शासित छ, जसले %s ध्यान ल्याउँछ।"),
VARSHA_MUNTHA_INFLUENCE("Muntha in %s suggests emphasis on %s. ", "%s मा मुन्थले %s मा जोड दिने संकेत गर्दछ।"),
VARSHA_OVERALL_TONE("Overall, the year appears to be %s. ", "समग्रमा, वर्ष %s देखिन्छ।"),
VARSHA_ASPECT_SUMMARY("Planetary aspects highlight %s. ", "ग्रहका दृष्टिहरूले %s लाई उजागर गर्दछ।"),
VARSHA_POTENTIAL_MAXIMIZED("Success can be maximized by focusing on %s.", "%s मा ध्यान केन्द्रित गरेर सफलतालाई अधिकतम बनाउन सकिन्छ।"),
VARSHA_HOUSE_GENERAL_SIG("general life matters", "सामान्य जीवनका मामिलाहरू"),
SAHAM_KARYASIDDHI("Karyasiddhi Saham", "कार्यसिद्धि सहम"),
SAHAM_SUCCESS("Success", "सफलता"),
SAHAM_FORTUNE("Fortune Saham", "भाग्य सहम"),
SAHAM_WEALTH("Wealth Saham", "धन सहम"),
SAHAM_MARRIAGE("Marriage Saham", "विवाह सहम"),
SAHAM_CHILDREN("Children Saham", "सन्तान सहम"),
SAHAM_HEALTH("Health Saham", "स्वास्थ्य सहम"),
SAHAM_EDUCATION("Education Saham", "शिक्षा सहम"),
SAHAM_TRAVEL("Travel Saham", "यात्रा सहम"),
SAHAM_PROFESSION("Profession Saham", "पेशा सहम")
}
