package com.astro.storm.core.common

/**
 * Career and Profession Localization Keys
 */
enum class StringKeyCareer(override val en: String, override val ne: String, override val hi: String) : StringKeyInterface {
    CAT_GOV_ADMIN("Government & Administration", "सरकारी र प्रशासन", "सरकारी और प्रशासन"),
    ,
    CAT_MILITARY_POLICE("Military & Police", "सेना र प्रहरी", "सेना और प्रहरी"),
    ,
    CAT_MEDICINE_HEALTHCARE("Medicine & Healthcare", "चिकित्सा र स्वास्थ्य", "चिकित्सा और स्वास्थ्य"),
    ,
    CAT_LAW_JUDICIARY("Law & Judiciary", "कानून र न्यायपालिका", "कानून और न्यायपालि के"),
    ,
    CAT_EDUCATION_TEACHING("Education & Teaching", "शिक्षा र शिक्षण", "शिक्षा और शिक्षण"),
    ,
    CAT_FINANCE_BANKING("Finance & Banking", "वित्त र बैंकिङ", "वित्त और बैंकिङ"),
    ,
    CAT_TECHNOLOGY_IT("Technology & IT", "प्रविधि र आईटी", "प्रविधि और आईटी"),
    ,
    CAT_ARTS_ENTERTAINMENT("Arts & Entertainment", "कला र मनोरञ्जन", "कला और मनोरञ्जन"),
    ,
    CAT_MEDIA_JOURNALISM("Media & Journalism", "मिडिया र पत्रकारिता", "मिडिया और पत्रकारिता"),
    ,
    CAT_BUSINESS_COMMERCE("Business & Commerce", "व्यापार र वाणिज्य", "व्यापार और वाणिज्य"),
    ,
    CAT_ENGINEERING_TECHNICAL("Engineering & Technical", "इन्जिनियरिङ र प्राविधिक", "इन्जिनियरिङ और प्राविधिक"),
    ,
    CAT_SCIENCE_RESEARCH("Science & Research", "विज्ञान र अनुसन्धान", "विज्ञान और अनुसन्धान"),
    ,
    CAT_HOSPITALITY_SERVICE("Hospitality & Service", "आतिथ्य र सेवा", "आतिथ्य और सेवा"),
    ,
    CAT_REAL_ESTATE_CONSTRUCTION("Real Estate & Construction", "घरजग्गा र निर्माण", "घरजग्गा और निर्माण"),
    ,
    CAT_AGRICULTURE_FARMING("Agriculture & Farming", "कृषि र खेती", "कृषि और खेती"),
    ,
    CAT_SPIRITUALITY_RELIGIOUS("Spirituality & Religious", "आध्यात्मिकता र धार्मिक", "आध्यात्मिकता और धार्मिक"),
    ,
    CAT_SPORTS_FITNESS("Sports & Fitness", "खेलकुद र फिटनेस", "खेलकुद और फिटनेस"),
    ,
    CAT_TRANSPORTATION_LOGISTICS("Transportation & Logistics", "यातायात र रसद", "यातायात और रसद"),
    ,
    CAT_FOREIGN_SERVICES("Foreign Services", "परराष्ट्र सेवा", "परराष्ट्र सेवा"),
    ,
    CAT_FREELANCE_CONSULTING("Freelance & Consulting", "फ्रिल्यान्स र परामर्श", "फ्रिल्यान्स और परामर्श"),
,
}
