package com.astro.storm.core.common

enum class StringKeyDashaPart3(override val en: String, override val ne: String) : StringKeyInterface {
    YOGINI_DASHA_ANTARDASHA("Current Antardasha", "वर्तमान अन्तर्दशा"),
    YOGINI_DASHA_APPLICABILITY("Applicability", "प्रयोज्यता"),
    YOGINI_DASHA_BALANCE("Balance at Birth", "जन्ममा सन्तुलन"),
    YOGINI_DASHA_CURRENT("Current Yogini", "वर्तमान योगिनी"),
    YOGINI_DASHA_RECOMMENDED("Recommended for this chart", "यो कुण्डलीको लागि सिफारिस"),
    YOGINI_DASHA_SEQUENCE("Yogini Sequence", "योगिनी क्रम"),
    YOGINI_DASHA_SUBTITLE("36-Year Cycle Dasha System", "३६-वर्षे चक्र दशा प्रणाली"),
    YOGINI_DASHA_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
    YOGINI_DASHA_TITLE("Yogini Dasha", "योगिनी दशा"),
    YOGINI_DEITY_BUDHA("Budha (Mercury)", "बुध"),
    YOGINI_DEITY_CHANDRA("Chandra (Moon)", "चन्द्र"),
    YOGINI_DEITY_GURU("Guru (Jupiter)", "गुरु (बृहस्पति)"),
    YOGINI_DEITY_MANGAL("Mangal (Mars)", "मङ्गल"),
    YOGINI_DEITY_RAHU("Rahu", "राहु"),
    YOGINI_DEITY_SHANI("Shani (Saturn)", "शनि"),
    YOGINI_DEITY_SHUKRA("Shukra (Venus)", "शुक्र"),
    YOGINI_DEITY_SURYA("Surya (Sun)", "सूर्य"),
    YOGINI_DHANYA("Dhanya", "धान्या"),
    YOGINI_DHANYA_CAREER("Expansion in career, promotions, and higher learning. Excellent for teaching, consulting, and advisory roles.", "क्यारियरमा विस्तार, पदोन्नति, र उच्च शिक्षा। शिक्षण, परामर्श, र सल्लाहकार भूमिकाको लागि उत्कृष्ट।"),
    YOGINI_DHANYA_CAUTION_1("Over-expansion", "अत्यधिक विस्तार"),
    YOGINI_DHANYA_CAUTION_2("Weight issues", "तौल समस्याहरू"),
    YOGINI_DHANYA_CAUTION_3("Over-optimism", "अत्यधिक आशावाद"),
    YOGINI_DHANYA_DESC("Wealth, wisdom, children, spiritual growth. Jupiter's expansive grace.", "धन, ज्ञान, सन्तान, आध्यात्मिक वृद्धि। गुरुको विस्तारित कृपा।"),
    YOGINI_DHANYA_HEALTH("Good health generally. Watch liver and weight. Spiritual practices enhance well-being.", "सामान्यतया राम्रो स्वास्थ्य। कलेजो र तौलमा ध्यान दिनुहोस्। आध्यात्मिक अभ्यासले कल्याण बढाउँछ।"),
    YOGINI_DHANYA_REC_1("Wear yellow sapphire if suitable", "उपयुक्त भएमा पुष्पराज लगाउनुहोस्"),
    YOGINI_DHANYA_REC_2("Seek blessings from teachers", "शिक्षकहरूबाट आशीर्वाद लिनुहोस्"),
    YOGINI_DHANYA_REC_3("Study sacred texts", "पवित्र ग्रन्थहरूको अध्ययन गर्नुहोस्"),
    YOGINI_DHANYA_REC_4("Donate to educational causes on Thursdays", "बिहीबार शैक्षिक कार्यमा दान गर्नुहोस्"),
    YOGINI_DHANYA_RELATIONSHIP("Excellent for marriage and childbirth. Spiritual connections in relationships. Teachers and mentors become important.", "विवाह र सन्तानको लागि उत्कृष्ट। सम्बन्धमा आध्यात्मिक सम्बन्ध। शिक्षक र गुरुहरू महत्त्वपूर्ण हुन्छन्।"),
    YOGINI_DHANYA_SPIRITUAL("Excellent for spiritual growth and higher learning. Guru connection strengthens. Sacred knowledge flows.", "आध्यात्मिक वृद्धि र उच्च शिक्षाको लागि उत्कृष्ट। गुरु सम्बन्ध बलियो हुन्छ। पवित्र ज्ञान प्रवाहित हुन्छ।"),
    YOGINI_ERROR_BIRTH("Invalid birth data provided. Please check date, time, and location.", "अमान्य जन्म डाटा प्रदान गरियो। कृपया मिति, समय र स्थान जाँच गर्नुहोस्।"),
    YOGINI_ERROR_GENERIC("Failed to calculate Yogini Dasha. Please try again.", "योगिनी दशा गणना गर्न असफल। कृपया फेरि प्रयास गर्नुहोस्।"),
    YOGINI_ERROR_MOON("Unable to determine Moon's Nakshatra position. Please verify birth data.", "चन्द्रमाको नक्षत्र स्थिति निर्धारण गर्न असमर्थ। कृपया जन्म डाटा प्रमाणित गर्नुहोस्।"),
    YOGINI_ERROR_NAKSHATRA("Unable to calculate Yogini Dasha. Nakshatra calculation error.", "योगिनी दशा गणना गर्न असमर्थ। नक्षत्र गणना त्रुटि।"),
    YOGINI_GENERAL_EFFECTS("General Effects", "सामान्य प्रभावहरू"),
    YOGINI_GURU("Guru (Jupiter)", "गुरु"),
    YOGINI_HEALTH_EFFECTS("Health Effects", "स्वास्थ्य प्रभावहरू"),
    YOGINI_MANGAL("Mangal (Mars)", "मंगल"),
    YOGINI_MANGALA("Mangala", "मंगला"),
    YOGINI_MANGALA_CAREER("Career brings emotional satisfaction. Good for nurturing professions, public relations, and hospitality industry.", "क्यारियरले भावनात्मक सन्तुष्टि ल्याउँछ। हेरचाह गर्ने पेशाहरू, जनसम्पर्क, र आतिथ्य उद्योगको लागि राम्रो।"),
    YOGINI_MANGALA_CAUTION_1("Emotional volatility", "भावनात्मक अस्थिरता"),
    YOGINI_MANGALA_CAUTION_2("Over-attachment", "अत्यधिक लगाव"),
    YOGINI_MANGALA_CAUTION_3("Water-related issues", "पानी सम्बन्धित समस्याहरू"),
    YOGINI_MANGALA_DESC("Auspicious beginnings, prosperity, and happiness. Moon's nurturing energy.", "शुभ शुरुआत, समृद्धि, र खुशी। चन्द्रको पोषणकारी ऊर्जा।"),
    YOGINI_MANGALA_HEALTH("Generally good health. Focus on emotional and mental well-being. Water-related activities beneficial.", "सामान्यतया राम्रो स्वास्थ्य। भावनात्मक र मानसिक कल्याणमा ध्यान दिनुहोस्। पानी सम्बन्धित गतिविधिहरू लाभदायक।"),
    YOGINI_MANGALA_REC_1("Wear pearl or moonstone", "मोती वा चन्द्रकान्त मणि लगाउनुहोस्"),
    YOGINI_MANGALA_REC_2("Honor your mother and maternal figures", "आमा र मातृ व्यक्तित्वहरूको सम्मान गर्नुहोस्"),
    YOGINI_MANGALA_REC_3("Practice moon salutations", "चन्द्र नमस्कार अभ्यास गर्नुहोस्"),
    YOGINI_MANGALA_REC_4("Donate white items on Mondays", "सोमबार सेतो वस्तुहरू दान गर्नुहोस्"),
    YOGINI_MANGALA_RELATIONSHIP("Emotional connections deepen. Good for starting relationships. Mother's influence prominent. Nurturing partnerships.", "भावनात्मक सम्बन्ध गहिरो हुन्छ। सम्बन्ध सुरु गर्न राम्रो। आमाको प्रभाव प्रमुख। पालनपोषण गर्ने साझेदारी।"),
    YOGINI_MANGALA_SPIRITUAL("Devotional practices strengthen. Mother goddess worship beneficial. Emotional cleansing through meditation.", "भक्ति अभ्यास बलियो हुन्छ। मातृ देवीको पूजा लाभदायक। ध्यान मार्फत भावनात्मक सफाई।"),
    YOGINI_NATURE_AUSPICIOUS("Auspicious", "शुभ"),
    YOGINI_NATURE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    YOGINI_NATURE_DIFFICULT("Difficult", "कठिन"),
    YOGINI_NATURE_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यन्त शुभ"),
    YOGINI_NATURE_MIXED("Mixed", "मिश्रित"),
    YOGINI_PINGALA("Pingala", "पिंगला"),
    YOGINI_PINGALA_CAREER("Leadership opportunities arise. Government jobs, authority positions, and recognition in career. Father may influence career.", "नेतृत्वको अवसर आउँछ। सरकारी जागिर, अधिकारिक पद, र क्यारियरमा मान्यता। पिताले क्यारियरलाई प्रभाव पार्न सक्छन्।"),
    YOGINI_PINGALA_CAUTION_1("Ego conflicts", "अहंकार द्वन्द्व"),
    YOGINI_PINGALA_CAUTION_2("Eye problems", "आँखा समस्याहरू"),
    YOGINI_PINGALA_CAUTION_3("Father's health", "पिताको स्वास्थ्य"),
    YOGINI_PINGALA_DESC("Authority, father-related matters, recognition. Sun's illuminating energy.", "अधिकार, पिता-सम्बन्धित मामिलाहरू, मान्यता। सूर्यको प्रकाशित ऊर्जा।"),
    YOGINI_PINGALA_HEALTH("Watch heart, eyes, and overall vitality. Morning sun exposure beneficial. Maintain healthy ego.", "मुटु, आँखा, र समग्र जीवनशक्तिमा ध्यान दिनुहोस्। बिहानी घाम लाभदायक। स्वस्थ अहंकार कायम राख्नुहोस्।"),
    YOGINI_PINGALA_REC_1("Wear ruby if suitable", "उपयुक्त भएमा माणिक लगाउनुहोस्"),
    YOGINI_PINGALA_REC_2("Practice Surya Namaskar at sunrise", "सूर्योदयमा सूर्य नमस्कार अभ्यास गर्नुहोस्"),
    YOGINI_PINGALA_REC_3("Honor your father", "पिताको सम्मान गर्नुहोस्"),
    YOGINI_PINGALA_REC_4("Donate wheat or jaggery on Sundays", "आइतबार गहुँ वा सख्खर दान गर्नुहोस्"),
    YOGINI_PINGALA_RELATIONSHIP("Relationships with authority figures. Father-related matters in marriage. May face ego conflicts with partners.", "अधिकारी वर्गसँग सम्बन्ध। विवाहमा पिता सम्बन्धित विषयहरू। साझेदारहरूसँग अहंकार द्वन्द्व हुन सक्छ।"),
    YOGINI_PINGALA_SPIRITUAL("Solar meditation and surya namaskar beneficial. Connection with divine father principle. Self-realization focus.", "सूर्य ध्यान र सूर्य नमस्कार लाभदायक। दिव्य पिता तत्त्वसँग सम्बन्ध। आत्म-साक्षात्कारमा ध्यान।"),
    YOGINI_RAHU("Rahu", "राहु"),
    YOGINI_RELATIONSHIP_EFFECTS("Relationship Effects", "सम्बन्ध प्रभावहरू"),
    YOGINI_SANKATA("Sankata", "संकटा"),
    YOGINI_SANKATA_CAREER("Unconventional career paths, foreign opportunities. May bring sudden changes in profession. Research and technology favored.", "अपरम्परागत क्यारियर पथहरू, विदेशी अवसरहरू। पेशामा अचानक परिवर्तन ल्याउन सक्छ। अनुसन्धान र प्रविधि अनुकूल।"),
    YOGINI_SANKATA_CAUTION_1("Sudden obstacles", "अचानक अवरोधहरू"),
    YOGINI_SANKATA_CAUTION_2("Confusion", "भ्रम"),
    YOGINI_SANKATA_CAUTION_3("Unusual diseases", "असामान्य रोगहरू"),
    YOGINI_SANKATA_DESC("Obstacles, foreign influences, sudden changes. Rahu brings transformation.", "अवरोधहरू, विदेशी प्रभाव, अचानक परिवर्तन। राहुले रूपान्तरण ल्याउँछ।"),
    YOGINI_SANKATA_HEALTH("Unusual or hard-to-diagnose health issues. Mental health important. Alternative therapies may help.", "असामान्य वा निदान गर्न गाह्रो स्वास्थ्य समस्याहरू। मानसिक स्वास्थ्य महत्त्वपूर्ण। वैकल्पिक उपचारले मद्दत गर्न सक्छ।"),
    YOGINI_SANKATA_REC_1("Wear hessonite after careful analysis", "सावधानीपूर्वक विश्लेषण पछि गोमेद लगाउनुहोस्"),
    YOGINI_SANKATA_REC_2("Stay grounded during sudden changes", "अचानक परिवर्तनको समयमा स्थिर रहनुहोस्"),
    YOGINI_SANKATA_REC_3("Address past-life patterns through meditation", "ध्यान मार्फत पूर्व-जन्मका ढाँचाहरू सम्बोधन गर्नुहोस्"),
    YOGINI_SANKATA_REC_4("Donate blue/black items on Saturdays", "शनिबार निलो/कालो वस्तुहरू दान गर्नुहोस्"),
    YOGINI_SANKATA_RELATIONSHIP("Unusual or foreign partners. Sudden attractions or separations. Need to address karmic relationship patterns.", "असामान्य वा विदेशी साझेदारहरू। अचानक आकर्षण वा अलगाव। कार्मिक सम्बन्ध ढाँचाहरू सम्बोधन गर्न आवश्यक।"),
    YOGINI_SANKATA_SPIRITUAL("Deep transformation possible. Occult interests may arise. Breaking free from illusions.", "गहिरो रूपान्तरण सम्भव छ। तन्त्रमन्त्रमा रुचि जाग्न सक्छ। भ्रमबाट मुक्ति।"),
    YOGINI_SEQUENCE("Yogini Sequence", "योगिनी क्रम"),
    YOGINI_SHANI("Shani (Saturn)", "शनि"),
    YOGINI_SHUKRA("Shukra (Venus)", "शुक्र"),
    YOGINI_SIDDHA("Siddha", "सिद्धा"),
    YOGINI_SIDDHA_CAREER("Career success through creativity and charm. Excellent for arts, entertainment, luxury goods, and beauty industries.", "सृजनशीलता र आकर्षण मार्फत क्यारियर सफलता। कला, मनोरञ्जन, विलासिताका सामान, र सौन्दर्य उद्योगका लागि उत्कृष्ट।"),
    YOGINI_SIDDHA_CAUTION_1("Indulgence", "भोगविला"),
    YOGINI_SIDDHA_CAUTION_2("Relationship complications", "सम्बन्ध जटिलताहरू"),
    YOGINI_SIDDHA_CAUTION_3("Luxury overspending", "विलासितामा अत्यधिक खर्च"),
    YOGINI_SIDDHA_DESC("Success, luxury, marriage, artistic achievements. Venus brings love.", "सफलता, विलासिता, विवाह, कलात्मक उपलब्धिहरू। शुक्रले प्रेम ल्याउँछ।"),
    YOGINI_SIDDHA_HEALTH("Generally good health. Watch reproductive system. Beauty treatments beneficial.", "सामान्यतया राम्रो स्वास्थ्य। प्रजनन प्रणालीमा ध्यान दिनुहोस्। सौन्दर्य उपचार लाभदायक।"),
    YOGINI_SIDDHA_REC_1("Wear diamond or white sapphire if suitable", "उपयुक्त भएमा हीरा वा सेतो पुखराज लगाउनुहोस्"),
    YOGINI_SIDDHA_REC_2("Engage in arts and creativity", "कला र सृजनशीलतामा संलग्न हुनुहोस्"),
    YOGINI_SIDDHA_REC_3("Cultivate harmonious relationships", "सामंजस्यपूर्ण सम्बन्ध विकास गर्नुहोस्"),
    YOGINI_SIDDHA_REC_4("Donate white items on Fridays", "शुक्रबार सेतो वस्तुहरू दान गर्नुहोस्"),
    YOGINI_SIDDHA_RELATIONSHIP("Excellent for romance, marriage, and love. Harmonious relationships. Beauty and pleasure in partnerships.", "रोमान्स, विवाह, र प्रेमको लागि उत्कृष्ट। सामंजस्यपूर्ण सम्बन्ध। साझेदारीमा सौन्दर्य र आनन्द।"),
    YOGINI_SIDDHA_SPIRITUAL("Tantric practices may attract. Beauty in spirituality. Heart-centered practices beneficial.", "तान्त्रिक अभ्यासहरूले आकर्षित गर्न सक्छ। आध्यात्मिकतामा सौन्दर्य। हृदय-केन्द्रित अभ्यासहरू लाभदायक।"),
    YOGINI_SPIRITUAL_EFFECTS("Spiritual Effects", "आध्यात्मिक प्रभावहरू"),
    YOGINI_SURYA("Surya (Sun)", "सूर्य"),
    YOGINI_ULKA("Ulka", "उल्का"),
    YOGINI_ULKA_CAREER("Slow but steady career progress. Hard work brings delayed rewards. Good for perseverance in long-term projects.", "सुस्त तर स्थिर क्यारियर प्रगति। कडा परिश्रमले ढिलो पुरस्कार ल्याउँछ। दीर्घकालीन परियोजनाहरूमा धैर्यताको लागि राम्रो।"),
    YOGINI_ULKA_CAUTION_1("Depression", "अवसाद"),
    YOGINI_ULKA_CAUTION_2("Delays", "ढिलाइ"),
    YOGINI_ULKA_CAUTION_3("Chronic health issues", "दीर्घकालीन स्वास्थ्य समस्याहरू"),
    YOGINI_ULKA_DESC("Hardship, discipline, eventual success. Saturn teaches patience.", "कठिनाई, अनुशासन, अन्ततः सफलता। शनिले धैर्य सिकाउँछ।"),
    YOGINI_ULKA_HEALTH("Chronic issues may arise. Bones, joints, and teeth need care. Patience in recovery.", "दीर्घकालीन समस्याहरू उत्पन्न हुन सक्छ। हड्डी, जोर्नी, र दाँतको हेरचाह आवश्यक। निको हुन धैर्यता।"),
    YOGINI_ULKA_REC_1("Wear blue sapphire with caution", "सावधानीपूर्वक नीलम लगाउनुहोस्"),
    YOGINI_ULKA_REC_2("Practice patience and discipline", "धैर्य र अनुशासन अभ्यास गर्नुहोस्"),
    YOGINI_ULKA_REC_3("Serve the elderly and disadvantaged", "वृद्ध र विपन्नहरूको सेवा गर्नुहोस्"),
    YOGINI_ULKA_REC_4("Donate oil and black items on Saturdays", "शनिबार तेल र कालो वस्तुहरू दान गर्नुहोस्"),
    YOGINI_ULKA_RELATIONSHIP("Delays or challenges in relationships. Karmic partners appear. Long-distance relationships possible.", "सम्बन्धमा ढिलाइ वा चुनौतीहरू। कार्मिक साझेदारहरू देखा पर्छन्। लामो-दूरीको सम्बन्ध सम्भव छ।"),
    YOGINI_ULKA_SPIRITUAL("Deep karmic cleansing period. Meditation on impermanence. Service-oriented spirituality.", "गहिरो कार्मिक सफाई अवधि। अनित्यतामा ध्यान। सेवा-उन्मुख आध्यात्मिकता।"),
    YOGINI_YEARS_1("1 Year", "१ वर्ष"),
    YOGINI_YEARS_2("2 Years", "२ वर्ष"),
    YOGINI_YEARS_3("3 Years", "३ वर्ष"),
    YOGINI_YEARS_4("4 Years", "४ वर्ष"),
    YOGINI_YEARS_5("5 Years", "५ वर्ष"),
    YOGINI_YEARS_6("6 Years", "६ वर्ष"),
    YOGINI_YEARS_7("7 Years", "७ वर्ष"),
    YOGINI_YEARS_8("8 Years", "८ वर्ष")
}
