package com.astro.storm.core.common

/**
 * String keys for Timing & Transit Analysis Screens
 * Includes: Tarabala, Chandrabala, Dasha Sandhi, Gochara Vedha, Kemadruma, Graha Yuddha
 */
enum class StringKeyDoshaTiming(
    override val en: String,
    override val ne: String,
) : StringKeyInterface {

    // ============================================
    // TARABALA AND CHANDRABALA
    // ============================================
    TARABALA_TITLE("Tarabala & Chandrabala", "ताराबल र चन्द्रबल"),
    TARABALA_SUBTITLE("Daily Strength Analysis", "दैनिक बल विश्लेषण"),
    TARABALA_TODAY("Today's Tarabala", "आजको ताराबल"),
    TARABALA_WEEKLY("Weekly Forecast", "साप्ताहिक पूर्वानुमान"),
    TARABALA_ALL_TARAS("All 27 Nakshatras", "सबै २७ नक्षत्रहरू"),
    TARABALA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    TARABALA_TRANSIT_NAKSHATRA("Transit Nakshatra", "गोचर नक्षत्र"),
    TARABALA_CYCLE("Cycle", "चक्र"),
    TARABALA_FAVORABLE("Favorable", "अनुकूल"),
    TARABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    TARABALA_DAILY_SCORE("Daily Strength Score", "दैनिक बल स्कोर"),
    TARABALA_BEST_DAY("Best Day", "उत्तम दिन"),
    TARABALA_WORST_DAY("Challenging Day", "चुनौतीपूर्ण दिन"),
    TARABALA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
    TARABALA_AVOID_ACTIVITIES("Activities to Avoid", "टाढा रहने गतिविधिहरू"),
    TARABALA_GENERAL_ADVICE("General Advice", "सामान्य सल्लाह"),
    TARABALA_WEEKLY_ADVICE("Weekly Guidance", "साप्ताहिक मार्गदर्शन"),

    // Nine Taras
    TARA_JANMA("Janma", "जन्म"),
    TARA_SAMPAT("Sampat", "सम्पत्"),
    TARA_VIPAT("Vipat", "विपत्"),
    TARA_KSHEMA("Kshema", "क्षेम"),
    TARA_PRATYARI("Pratyari", "प्रत्यारि"),
    TARA_SADHAKA("Sadhaka", "साधक"),
    TARA_VADHA("Vadha", "वध"),
    TARA_MITRA("Mitra", "मित्र"),
    TARA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),

    // Tara Descriptions
    TARA_JANMA_DESC("Birth star day - rest and introspection recommended", "जन्म नक्षत्र दिन - आराम र आत्मचिन्तन सिफारिस"),
    TARA_SAMPAT_DESC("Wealth star - excellent for financial matters", "धन नक्षत्र - आर्थिक मामिलाहरूको लागि उत्कृष्ट"),
    TARA_VIPAT_DESC("Danger star - avoid important activities", "विपत् नक्षत्र - महत्त्वपूर्ण गतिविधिहरू टाळ्नुहोस्"),
    TARA_KSHEMA_DESC("Well-being star - favorable for health matters", "क्षेम नक्षत्र - स्वास्थ्य मामिलाहरूको लागि अनुकूल"),
    TARA_PRATYARI_DESC("Obstacle star - expect minor hindrances", "प्रत्यारि नक्षत्र - सानातिना बाधाहरू अपेक्षा गर्नुहोस्"),
    TARA_SADHAKA_DESC("Achievement star - good for completing goals", "साधक नक्षत्र - लक्ष्य पूरा गर्नको लागि राम्रो"),
    TARA_VADHA_DESC("Death star - highly inauspicious, maximum caution", "वध नक्षत्र - अत्यन्त अशुभ, अधिकतम सावधानी"),
    TARA_MITRA_DESC("Friend star - favorable for relationships", "मित्र नक्षत्र - सम्बन्धहरूको लागि अनुकूल"),
    TARA_PARAMA_MITRA_DESC("Great friend star - most auspicious for everything", "परम मित्र नक्षत्र - सबैको लागि सबैभन्दा शुभ"),

    // Tarabala (Alternative naming used in some screens)
    TARABALA_JANMA("Janma", "जन्म"),
    TARABALA_SAMPAT("Sampat", "सम्पत"),
    TARABALA_VIPAT("Vipat", "विफत"),
    TARABALA_KSHEMA("Kshema", "क्षेम"),
    TARABALA_PRATYARI("Pratyari", "प्रत्यरि"),
    TARABALA_SADHAKA("Sadhaka", "साधक"),
    TARABALA_VADHA("Vadha", "वध"),
    TARABALA_MITRA("Mitra", "मित्र"),
    TARABALA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),

    // Tarabala Descriptions (Alternative)
    TARABALA_DESC_JANMA("Birth star - challenging for new beginnings", "जन्म नक्षत्र - नयाँ सुरुवातीका लागि चुनौतीपूर्ण"),
    TARABALA_DESC_SAMPAT("Wealth - favorable for financial matters", "सम्पत्ति - आर्थिक मामिलाका लागि शुभ"),
    TARABALA_DESC_VIPAT("Danger - avoid important activities", "खतरा - महत्त्वपूर्ण कार्यहरू नगर्नुहोस्"),
    TARABALA_DESC_KSHEMA("Well-being - favorable for health matters", "कल्याण - स्वास्थ्य मामिलाका लागि शुभ"),
    TARABALA_DESC_PRATYARI("Obstacle - creates hindrances", "बाधा - अवरोधहरू सिर्जना गर्दछ"),
    TARABALA_DESC_SADHAKA("Achievement - good for goals", "उपलब्धि - लक्ष्यका लागि राम्रो"),
    TARABALA_DESC_VADHA("Death - highly inauspicious", "वध - अत्यन्त अशुभ"),
    TARABALA_DESC_MITRA("Friend - favorable for relationships", "मित्र - सम्बन्धका लागि शुभ"),
    TARABALA_DESC_PARAMA_MITRA("Great Friend - highly auspicious", "परम मित्र - अत्यन्त शुभ"),

    // Chandrabala
    CHANDRABALA_TITLE("Chandrabala Analysis", "चन्द्रबल विश्लेषण"),
    CHANDRABALA_TRANSIT_MOON("Transit Moon Sign", "गोचर चन्द्र राशि"),
    CHANDRABALA_NATAL_MOON("Natal Moon Sign", "जन्म चन्द्र राशि"),
    CHANDRABALA_HOUSE_FROM_MOON("House from Moon", "चन्द्रबाट भाव"),
    CHANDRABALA_EXCELLENT("Excellent", "उत्कृष्ट"),
    CHANDRABALA_GOOD("Good", "राम्रो"),
    CHANDRABALA_NEUTRAL("Neutral", "तटस्थ"),
    CHANDRABALA_WEAK("Weak", "कमजोर"),
    CHANDRABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    CHANDRABALA_SIGNIFICATIONS("House Significations", "भाव संकेतहरू"),

    // Combined Strength
    COMBINED_HIGHLY_FAVORABLE("Highly Favorable", "अत्यन्त अनुकूल"),
    COMBINED_FAVORABLE("Favorable", "अनुकूल"),
    COMBINED_MIXED("Mixed Results", "मिश्रित परिणाम"),
    COMBINED_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    COMBINED_UNFAVORABLE("Unfavorable", "प्रतिकूल"),

    // ============================================
    // DASHA SANDHI ANALYSIS
    // ============================================
    SANDHI_TITLE("Dasha Sandhi Analysis", "दशा सन्धि विश्लेषण"),
    SANDHI_SUBTITLE("Period Junction Analysis", "अवधि जोड विश्लेषण"),
    SANDHI_CURRENT("Current Sandhi", "वर्तमान सन्धि"),
    SANDHI_UPCOMING("Upcoming Sandhis", "आगामी सन्धिहरू"),
    SANDHI_RECENT("Recent Sandhis", "हालैका सन्धिहरू"),
    SANDHI_CALENDAR("Sandhi Calendar", "सन्धि क्यालेन्डर"),
    SANDHI_VOLATILITY("Volatility Score", "अस्थिरता स्कोर"),
    SANDHI_TRANSITION("Transition", "संक्रमण"),
    SANDHI_FROM_PLANET("From", "बाट"),
    SANDHI_TO_PLANET("To", "मा"),
    SANDHI_DAYS_UNTIL("Days Until Transition", "संक्रमणसम्म दिन"),
    SANDHI_PROGRESS("Sandhi Progress", "सन्धि प्रगति"),
    SANDHI_KEY_DATES("Key Dates", "मुख्य मितिहरू"),
    SANDHI_PREDICTIONS("Predictions", "भविष्यवाणीहरू"),
    SANDHI_CAREER_EFFECTS("Career Effects", "क्यारियर प्रभावहरू"),
    SANDHI_HEALTH_CONCERNS("Health Considerations", "स्वास्थ्य विचारणाहरू"),
    SANDHI_RELATIONSHIP_IMPACT("Relationship Impact", "सम्बन्ध प्रभाव"),
    SANDHI_FINANCIAL_TREND("Financial Trend", "आर्थिक प्रवृत्ति"),
    SANDHI_SPIRITUAL("Spiritual Opportunities", "आध्यात्मिक अवसरहरू"),
    SANDHI_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    SANDHI_GENERAL_GUIDANCE("General Guidance", "सामान्य मार्गदर्शन"),

    // Sandhi Screen
    SANDHI_SCREEN_TITLE("Dasha Sandhi", "दशा सन्धि"),
    SANDHI_ABOUT_TITLE("About Dasha Sandhi", "दशा सन्धिको बारेमा"),
    SANDHI_ABOUT_DESC("Dasha Sandhi refers to the junction or transition point between two planetary periods (Dashas) in Vedic astrology.\n\nThese transition periods are considered sensitive times when:\n• The energy shifts from one planetary influence to another\n• Both planets' effects may be felt simultaneously\n• Major life changes often occur\n• Careful planning is advised\n\nThe intensity of a Sandhi depends on:\n• The nature of the transitioning planets\n• Their relationship in your chart\n• Current transits and aspects\n\nUnderstanding your Sandhi periods helps you prepare for and navigate these significant life transitions.", "दशा सन्धि भन्नाले वैदिक ज्योतिषमा दुई ग्रह दशा (समय अवधि) बीचको मिलन वा संक्रमण बिन्दुलाई जनाउँछ।\n\nयी संक्रमण अवधिहरूलाई संवेदनशील समय मानिन्छ जब:\n• ऊर्जा एक ग्रहको प्रभावबाट अर्कोमा सर्छ\n• दुबै ग्रहका प्रभावहरू एक साथ महसुस हुन सक्छ\n• अक्सर ठूला जीवन परिवर्तनहरू हुन्छन्\n• सावधानीपूर्वक योजना बनाउन सल्लाह दिइन्छ\n\nसन्धिको तीव्रता यसमा निर्भर गर्दछ:\n• संक्रमण भइरहेका ग्रहहरूको प्रकृति\n• तपाईंको कुण्डलीमा तिनीहरूको सम्बन्ध\n• वर्तमान गोचर र दृष्टिहरू\n\nतपाईंको सन्धि अवधिहरू बुझ्नाले तपाईंलाई यी महत्त्वपूर्ण जीवन संक्रमणहरूको तयारी गर्न र नेभिगेट गर्न मद्दत गर्छ।"),
    SANDHI_VOLATILITY_DESC("Based on current and upcoming period transitions", "वर्तमान र आगामी दशा परिवर्तनहरूमा आधारित"),
    SANDHI_ACTIVE("Active", "सक्रिय"),
    SANDHI_GUIDANCE("General Guidance", "सामान्य मार्गदर्शन"),
    SANDHI_CURRENT_ACTIVE("Currently in Sandhi Period", "वर्तमानमा सन्धि अवधिमा"),
    SANDHI_INTENSITY("Intensity:", "तीव्रता:"),
    SANDHI_ENDS("Ends:", "अन्त्य:"),
    SANDHI_NO_ACTIVE("No Active Sandhi", "कुनै सक्रिय सन्धि छैन"),
    SANDHI_NO_ACTIVE_DESC("You are not currently in a Dasha Sandhi period. Check the Upcoming tab for future transitions.", "तपाईं हाल दशा सन्धि अवधिमा हुनुहुन्न। भविष्यका परिवर्तनहरूको लागि आगामी ट्याब जाँच गर्नुहोस्।"),
    SANDHI_IMPACTS("Life Area Impacts", "जीवन क्षेत्र प्रभावहरू"),
    SANDHI_REMEDIES("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
    SANDHI_NO_CHART_DESC("Create or select a birth chart to analyze Dasha Sandhi periods.", "दशा सन्धि अवधिहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    SANDHI_NO_UPCOMING("No upcoming Sandhi periods in the analysis window.", "विश्लेषण अवधिमा कुनै आगामी सन्धि अवधिहरू छैनन्।"),
    SANDHI_NO_CALENDAR("No calendar entries available.", "कुनै पात्रो प्रविष्टिहरू उपलब्ध छैनन्।"),

    // Sandhi Intensity
    SANDHI_INTENSITY_CRITICAL("Critical", "गम्भीर"),
    SANDHI_INTENSITY_HIGH("High", "उच्च"),
    SANDHI_INTENSITY_MODERATE("Moderate", "मध्यम"),
    SANDHI_INTENSITY_MILD("Mild", "हल्का"),
    SANDHI_INTENSITY_MINIMAL("Minimal", "न्यूनतम"),

    // Transition Types
    TRANSITION_FRIEND_FRIEND("Friend to Friend", "मित्रबाट मित्रमा"),
    TRANSITION_FRIEND_NEUTRAL("Friend to Neutral", "मित्रबाट तटस्थमा"),
    TRANSITION_FRIEND_ENEMY("Friend to Enemy", "मित्रबाट शत्रुमा"),
    TRANSITION_NEUTRAL_FRIEND("Neutral to Friend", "तटस्थबाट मित्रमा"),
    TRANSITION_NEUTRAL_NEUTRAL("Neutral to Neutral", "तटस्थबाट तटस्थमा"),
    TRANSITION_NEUTRAL_ENEMY("Neutral to Enemy", "तटस्थबाट शत्रुमा"),
    TRANSITION_ENEMY_FRIEND("Enemy to Friend", "शत्रुबाट मित्रमा"),
    TRANSITION_ENEMY_NEUTRAL("Enemy to Neutral", "शत्रुबाट तटस्थमा"),
    TRANSITION_ENEMY_ENEMY("Enemy to Enemy", "शत्रुबाट शत्रुमा"),

    // ============================================
    // GOCHARA VEDHA ANALYSIS
    // ============================================
    VEDHA_TITLE("Gochara Vedha Analysis", "गोचर वेध विश्लेषण"),
    VEDHA_SUBTITLE("Transit Obstruction Analysis", "गोचर अवरोध विश्लेषण"),
    VEDHA_OVERVIEW("Transit Overview", "गोचर सिंहावलोकन"),
    VEDHA_ACTIVE("Active Vedhas", "सक्रिय वेधहरू"),
    VEDHA_PLANET_TRANSITS("Planetary Transits", "ग्रह गोचरहरू"),
    VEDHA_OVERALL_SCORE("Overall Transit Score", "समग्र गोचर स्कोर"),
    VEDHA_FAVORABLE_COUNT("Favorable Transits", "अनुकूल गोचरहरू"),
    VEDHA_OBSTRUCTED_COUNT("Obstructed Transits", "अवरुद्ध गोचरहरू"),
    VEDHA_KEY_INSIGHTS("Key Insights", "मुख्य अन्तर्दृष्टिहरू"),
    VEDHA_OBSTRUCTED_BY("Obstructed by", "द्वारा अवरुद्ध"),
    VEDHA_LOST_BENEFITS("Lost Benefits", "गुमाएको फाइदाहरू"),

    // Vedha Severity
    VEDHA_COMPLETE("Complete Obstruction", "पूर्ण अवरोध"),
    VEDHA_STRONG("Strong Obstruction", "बलियो अवरोध"),
    VEDHA_MODERATE("Moderate Obstruction", "मध्यम अवरोध"),
    VEDHA_PARTIAL("Partial Obstruction", "आंशिक अवरोध"),
    VEDHA_NONE("No Obstruction", "कुनै अवरोध छैन"),

    // Transit Effectiveness
    TRANSIT_EXCELLENT("Excellent", "उत्कृष्ट"),
    TRANSIT_GOOD("Good", "राम्रो"),
    TRANSIT_MODERATE("Moderate", "मध्यम"),
    TRANSIT_WEAK("Weak", "कमजोर"),
    TRANSIT_NULLIFIED("Nullified by Vedha", "वेधद्वारा रद्द"),
    TRANSIT_UNFAVORABLE("Unfavorable Transit", "प्रतिकूल गोचर"),

    // Gochara Screen
    GOCHARA_SCREEN_TITLE("Gochara Vedha", "गोचर वेध"),
    GOCHARA_SUBTITLE("Transit Obstructions", "गोचर अवरोधहरू"),
    GOCHARA_ABOUT_TITLE("About Gochara Vedha", "गोचर वेधको बारेमा"),
    GOCHARA_ABOUT_DESC("Gochara refers to planetary transits, while Vedha means \"obstruction\" in Sanskrit.\n\nWhen a planet transits through a favorable house from your natal Moon, its positive effects can be blocked (Vedha) by another planet positioned in specific houses.\n\nKey concepts:\n• Each house has specific Vedha points\n• Benefic transits can be nullified by malefic planets\n• The severity of Vedha varies based on planetary combinations\n• Understanding Vedha helps predict when good transits may not deliver expected results\n\nThis analysis helps you identify periods when planetary energies are blocked and plan accordingly.", "गोचर भन्नाले ग्रहहरूको वर्तमान चाललाई जनाउँछ, जबकि वेधको अर्थ संस्कृतमा \"अवरोध\" हो।\n\nजब कुनै ग्रह तपाईंको जन्म चन्द्रमाबाट शुभ भावमा गोचर गर्छ, यसको सकारात्मक प्रभावहरू विशिष्ट भावहरूमा रहेका अन्य ग्रहहरूद्वारा अवरोधित (वेध) हुन सक्छन्।\n\nमुख्य अवधारणाहरू:\n• प्रत्येक भावका विशिष्ट वेध बिन्दुहरू हुन्छन्\n• शुभ गोचरहरू पाप ग्रहहरूद्वारा निष्फल हुन सक्छन्\n• वेधको गम्भीरता ग्रह संयोजनहरूमा आधारित हुन्छ\n• वेध बुझ्नाले राम्रो गोचरले कहिले अपेक्षित नतिजा नदिन सक्छ भनी अनुमान गर्न मद्दत गर्छ\n\nयो विश्लेषणले तपाईंलाई ग्रह उर्जाहरू कहिले अवरोधित हुन्छन् भनी पहिचान गर्न र सोही अनुसार योजना बनाउन मद्दत गर्छ।"),
    GOCHARA_SCORE("Overall Transit Score", "समग्र गोचर अङ्क"),
    GOCHARA_FAVORABLE("Favorable", "शुभ"),
    GOCHARA_OBSTRUCTED("Obstructed", "अवरोधित"),
    GOCHARA_MOON_SIGN("Natal Moon Sign", "जन्म राशी"),
    GOCHARA_ACTIVE_VEDHAS("Active Vedhas", "सक्रिय वेध"),
    GOCHARA_TRANSITS_TRACKED("Transits Tracked", "ट्र्याक गरिएका गोचरहरू"),
    GOCHARA_CURRENT_TRANSITS("Current Planetary Transits", "वर्तमान ग्रह गोचरहरू"),
    GOCHARA_NATURALLY_FAVORABLE("Naturally Favorable", "स्वाभाविक रूपमा शुभ"),
    GOCHARA_NATURALLY_UNFAVORABLE("Naturally Unfavorable", "स्वाभाविक रूपमा अशुभ"),
    GOCHARA_VEDHA_LABEL("VEDHA", "वेध"),
    GOCHARA_TRANSIT_EFFECTS("Transit Effects", "गोचर प्रभावहरू"),
    GOCHARA_VEDHA_OBSTRUCTION("Vedha Obstruction", "वेध अवरोध"),
    GOCHARA_FROM("From:", "बाट:"),
    GOCHARA_SEVERITY("Severity:", "गम्भीरता:"),
    GOCHARA_NO_CHART_DESC("Create or select a birth chart to analyze Gochara Vedha effects.", "गोचर वेध प्रभावहरू विश्लेषण गर्न जन्म कुण्डली सिर्जना गर्नुहोस् वा छान्नुहोस्।"),
    GOCHARA_VEDHAS("Vedhas", "वेधहरू"),
    GOCHARA_FORECAST("Forecast", "पूर्वानुमान"),

    // ============================================
    // KEMADRUMA YOGA ANALYSIS
    // ============================================
    KEMADRUMA_TITLE("Kemadruma Yoga Analysis", "केमद्रुम योग विश्लेषण"),
    KEMADRUMA_SUBTITLE("Moon Support Analysis", "चन्द्र समर्थन विश्लेषण"),
    KEMADRUMA_MOON_ANALYSIS("Moon Analysis", "चन्द्र विश्लेषण"),
    KEMADRUMA_FORMATION("Formation Details", "गठन विवरण"),
    KEMADRUMA_CANCELLATIONS("Cancellation Factors", "रद्दीकरण कारकहरू"),
    KEMADRUMA_EMOTIONAL("Emotional Impact", "भावनात्मक प्रभाव"),
    KEMADRUMA_FINANCIAL("Financial Impact", "आर्थिक प्रभाव"),
    KEMADRUMA_SOCIAL("Social Impact", "सामाजिक प्रभाव"),
    KEMADRUMA_ACTIVATION("Activation Periods", "सक्रियता अवधिहरू"),
    KEMADRUMA_MENTAL_PEACE("Mental Peace", "मानसिक शान्ति"),
    KEMADRUMA_STABILITY("Emotional Stability", "भावनात्मक स्थिरता"),
    KEMADRUMA_CONFIDENCE("Confidence Level", "आत्मविश्वास स्तर"),
    KEMADRUMA_ANXIETY("Anxiety Tendency", "चिन्ता प्रवृत्ति"),
    KEMADRUMA_DEPRESSION_RISK("Depression Risk", "अवसाद जोखिम"),
    KEMADRUMA_WEALTH_RETENTION("Wealth Retention", "धन संरक्षण"),
    KEMADRUMA_FAMILY_SUPPORT("Family Support", "पारिवारिक समर्थन"),
    KEMADRUMA_FRIENDSHIP("Friendship Quality", "मित्रता गुणस्तर"),
    KEMADRUMA_ISOLATION("Isolation Tendency", "एकान्त प्रवृत्ति"),

    // Kemadruma Status
    KEMADRUMA_NOT_PRESENT("Not Present", "उपस्थित छैन"),
    KEMADRUMA_FULLY_CANCELLED("Fully Cancelled", "पूर्ण रूपमा रद्द"),
    KEMADRUMA_MOSTLY_CANCELLED("Mostly Cancelled", "प्रायः रद्द"),
    KEMADRUMA_PARTIALLY_CANCELLED("Partially Cancelled", "आंशिक रूपमा रद्द"),
    KEMADRUMA_WEAKLY_CANCELLED("Weakly Cancelled", "कमजोर रूपमा रद्द"),
    KEMADRUMA_ACTIVE_MODERATE("Active (Moderate)", "सक्रिय (मध्यम)"),
    KEMADRUMA_ACTIVE_SEVERE("Active (Severe)", "सक्रिय (गम्भीर)"),

    // Bhanga (Cancellation) Types
    BHANGA_KENDRA_MOON("Planets in Kendra from Moon", "चन्द्रबाट केन्द्रमा ग्रहहरू"),
    BHANGA_KENDRA_LAGNA("Planets in Kendra from Lagna", "लग्नबाट केन्द्रमा ग्रहहरू"),
    BHANGA_MOON_KENDRA("Moon in Kendra from Lagna", "लग्नबाट केन्द्रमा चन्द्र"),
    BHANGA_BENEFIC_ASPECT("Benefic planet aspects Moon", "शुभ ग्रहले चन्द्रलाई देख्छ"),
    BHANGA_BENEFIC_CONJUNCTION("Benefic planet conjuncts Moon", "शुभ ग्रह चन्द्रसँग युति"),
    BHANGA_MOON_EXALTED("Moon in exaltation", "चन्द्र उच्चमा"),
    BHANGA_MOON_OWN("Moon in own sign", "चन्द्र स्वराशिमा"),
    BHANGA_MOON_FRIEND("Moon in friendly sign", "चन्द्र मित्र राशिमा"),
    BHANGA_FULL_MOON("Full or bright Moon", "पूर्ण वा उज्यालो चन्द्र"),
    BHANGA_ANGULAR_MOON("Moon in angular house", "कोणीय भावमा चन्द्र"),
    BHANGA_STRONG_DISPOSITOR("Strong dispositor", "बलियो राशीश"),
    BHANGA_JUPITER_ASPECT("Jupiter aspects Moon", "बृहस्पतिले चन्द्रलाई देख्छ"),
    BHANGA_VENUS_ASPECT("Venus aspects Moon", "शुक्रले चन्द्रलाई देख्छ"),

    // Moon Brightness
    MOON_BRIGHTNESS_FULL("Full Moon", "पूर्णिमा"),
    MOON_BRIGHTNESS_BRIGHT("Bright Moon", "उज्यालो चन्द्र"),
    MOON_BRIGHTNESS_AVERAGE("Average Moon", "औसत चन्द्र"),
    MOON_BRIGHTNESS_DIM("Dim Moon", "धमिलो चन्द्र"),
    MOON_BRIGHTNESS_NEW("New Moon", "अमावस्या"),

    // Lunar Paksha
    PAKSHA_SHUKLA("Shukla Paksha", "शुक्ल पक्ष"),
    PAKSHA_KRISHNA("Krishna Paksha", "कृष्ण पक्ष"),

    // Impact Levels
    IMPACT_SEVERE("Severe", "गम्भीर"),
    IMPACT_HIGH("High", "उच्च"),
    IMPACT_MODERATE("Moderate", "मध्यम"),
    IMPACT_MILD("Mild", "हल्का"),
    IMPACT_MINIMAL("Minimal", "न्यूनतम"),
    IMPACT_POSITIVE("Positive", "सकारात्मक"),

    // Kemadruma Screen
    KEMA_SCREEN_TITLE("Kemadruma Yoga", "केमद्रुम योग"),
    KEMA_SUBTITLE("Moon Isolation Analysis", "चन्द्रमा एक्लोपन विश्लेषण"),
    KEMA_MOON("Moon", "चन्द्रमा"),
    KEMA_CANCELLATIONS("Cancellations", "भंग"),
    KEMA_IMPACTS("Impacts", "प्रभावहरू"),
    KEMA_FORMED("Kemadruma Yoga is formed in this chart", "यो कुण्डलीमा केमद्रुम योग बनेको छ"),
    KEMA_NOT_FORMED("Kemadruma Yoga is not formed", "केमद्रुम योग बनेको छैन"),
    KEMA_FORMATION_DETAILS("Formation Details", "योग निर्माण विवरण"),
    KEMA_MOON_POSITION("Moon Position", "चन्द्रमाको स्थिति"),
    KEMA_SURROUNDING_HOUSES("Surrounding Houses Analysis", "वरपरका भावहरूको विश्लेषण"),
    KEMA_BEFORE_MOON("Before Moon", "चन्द्रमा अघि"),
    KEMA_AFTER_MOON("After Moon", "चन्द्रमा पछि"),
    KEMA_MOON_HOUSE("Moon's House", "चन्द्रमाको भाव"),
    KEMA_CONDITION_MET("No planets in houses adjacent to Moon - Kemadruma condition met", "चन्द्रमाको नजिकका भावहरूमा कुनै ग्रह छैन - केमद्रुम शर्त पूरा भयो"),
    KEMA_NO_CANCELLATIONS("No Cancellations Found", "कुनै भंग फेला परेन"),
    KEMA_NA("Not Applicable", "लागू हुँदैन"),
    KEMA_NO_CANCELLATIONS_DESC("No Kemadruma Bhanga (cancellation) factors were found in your chart.", "तपाईंको कुण्डलीमा कुनै केमद्रुम भंग कारकहरू फेला परेनन्।"),
    KEMA_NO_IMPACTS("No Negative Impacts", "कुनै नकारात्मक प्रभाव छैन"),
    KEMA_NO_IMPACTS_DESC("Moon is well-supported, ensuring emotional stability and mental peace.", "चन्द्रमा राम्रोसँग समर्थित छ, जसले भावनात्मक स्थिरता र मानसिक शान्ति सुनिश्चित गर्दछ।"),
    KEMA_NO_REMEDIES("No Remedies Needed", "कुनै उपाय आवश्यक छैन"),
    KEMA_NO_REMEDIES_DESC("Since Kemadruma Yoga is not formed or is fully cancelled, no remedies are required.", "केमद्रुम योग नबनेको वा पूर्ण रूपमा भंग भएकोले, कुनै उपाय आवश्यक छैन।"),
    KEMA_ABOUT_TITLE("About Kemadruma Yoga", "केमद्रुम योगको बारेमा"),
    KEMA_ABOUT_DESC("Kemadruma Yoga forms when the Moon has no planets (except Sun, Rahu, Ketu) in the 2nd and 12th houses from it, and no planets are in Kendra from the Moon or Lagna.\n\nIt is considered an inauspicious yoga indicating loneliness, mental unrest, and financial instability. However, it is often cancelled (Bhanga) by the presence of planets in Kendra houses or if the Moon interacts with other planets.", "केमद्रुम योग तब बन्छ जब चन्द्रमाको दोस्रो र बाह्रौं भावमा कुनै ग्रहहरू (सूर्य, राहु, केतु बाहेक) हुँदैनन्, र चन्द्रमा वा लग्नबाट केन्द्रमा कुनै ग्रहहरू हुँदैनन्।\n\nयसलाई अशुभ योग मानिन्छ जसले एक्लोपन, मानसिक अशान्ति र आर्थिक अस्थिरतालाई संकेत गर्दछ। यद्यपि, केन्द्र भावहरूमा ग्रहहरूको उपस्थिति वा चन्द्रमाले अन्य ग्रहहरूसँग अन्तरक्रिया गरेमा यो अक्सर भंग हुन्छ।"),
    KEMA_CANCELLATIONS_FOUND("%1\$2 Cancellation(s) Found", "%1\$2 भंग(हरू) फेला पर्यो"),
    KEMA_FORMATION_MAIN("Moon lacks planetary support in adjacent houses.", "चन्द्रमालाई नजिकका भावहरूमा ग्रहहरूको समर्थन छैन।"),
    KEMA_FORMATION_2ND_EMPTY("2nd house from Moon is empty.", "चन्द्रमाबाट दोस्रो भाव खाली छ।"),
    KEMA_FORMATION_12TH_EMPTY("12th house from Moon is empty.", "चन्द्रमाबाट बाह्रौं भाव खाली छ।"),
    KEMA_FORMATION_UNASPECTED("Moon has no planetary conjunction.", "चन्द्रमाको कुनै ग्रहसँग युति छैन।"),
    KEMA_REASON_2ND("No planets in 2nd house from Moon", "चन्द्रमाबाट दोस्रो भावमा कुनै ग्रह छैन"),
    KEMA_REASON_12TH("No planets in 12th house from Moon", "चन्द्रमाबाट बाह्रौं भावमा कुनै ग्रह छैन"),
    KEMA_REASON_CONJUNCT("Moon is not conjunct with any planet", "चन्द्रमा कुनै ग्रहसँग युतिमा छैन"),
    KEMA_FORMATION_STRENGTH("Formation strength: %1\$2%%", "योग बल: %1\$2%%"),
    KEMA_NAKSHATRA("Nakshatra", "नक्षत्र"),
    KEMA_PAKSHA("Paksha", "पक्ष"),
    KEMA_BRIGHTNESS("Brightness", "चमक"),
    KEMA_MOON_STRENGTH("Moon Strength:", "चन्द्रमा बल:"),

    // ============================================
    // GRAHA YUDDHA (PLANETARY WAR)
    // ============================================
    GRAHA_SCREEN_TITLE("Graha Yuddha", "ग्रह युद्ध"),
    GRAHA_SUBTITLE("Planetary War Analysis", "ग्रह युद्ध विश्लेषण"),
    GRAHA_ACTIVE_WARS("Active Wars", "सक्रिय युद्धहरू"),
    GRAHA_DASHA_EFFECTS("Dasha Effects", "दशा प्रभावहरू"),
    GRAHA_ANALYZING("Analyzing Planetary Wars...", "ग्रह युद्ध विश्लेषण गर्दै..."),
    GRAHA_WAR_STATUS("War Status", "युद्ध स्थिति"),
    GRAHA_ANALYSIS_SUMMARY("Analysis Summary", "विश्लेषण सारांश"),
    GRAHA_OVERALL_IMPACT("Overall War Impact", "समग्र युद्ध प्रभाव"),
    GRAHA_VICTORY("Victorious", "विजयी"),
    GRAHA_DEFEATED("Defeated", "पराजित"),
    GRAHA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    GRAHA_NO_WARS("No Active Planetary Wars", "कुनै सक्रिय ग्रह युद्ध छैन"),
    GRAHA_NO_WARS_DESC("All planets are operating peacefully", "सबै ग्रहहरू शान्तिपूर्ण रूपमा काम गरिरहेका छन्"),
    GRAHA_VS("vs", "विरुद्ध"),
    GRAHA_SEPARATION("Separation", "अन्तर"),
    GRAHA_ADVANTAGE("Advantage", "फाइदा"),
    GRAHA_NO_DASHA_EFFECTS("No War-Related Dasha Effects", "कुनै युद्ध-सम्बन्धित दशा प्रभावहरू छैनन्"),
    GRAHA_NO_REMEDIES("No Specific Remedies Needed", "कुनै विशेष उपाय आवश्यक छैन"),
    GRAHA_NO_DASHA_DESC("Planets in War not currently activated in Dasha/Antardasha.", "युद्धमा रहेका ग्रहहरू हाल दशा/अन्तर्दशामा सक्रिय छैनन्।"),
    GRAHA_NO_REMEDIES_DESC("Since there are no active planetary wars, remedial measures are not required.", "कुनै सक्रिय ग्रह युद्ध नभएकोले, उपायहरू आवश्यक छैनन्।"),
    GRAHA_ABOUT_TITLE("About Graha Yuddha", "ग्रह युद्धको बारेमा"),
    GRAHA_ABOUT_DESC("Graha Yuddha (Planetary War) occurs when two planets (excluding Sun and Moon) are within 1 degree of each other.\n\nThe planet with the lower longitude is usually considered the winner, while the one with higher longitude is the loser.\n\nImpacts:\n• The losing planet's significations may suffer\n• If the losing planet rules important houses, those areas may be affected\n• The war is most intense during close conjunctions", "ग्रह युद्ध तब हुन्छ जब दुई ग्रहहरू (सूर्य र चन्द्रमा बाहेक) एक अर्काको १ डिग्री भित्र हुन्छन्।\n\nकम देशान्तर भएको ग्रहलाई सामान्यतया विजेता मानिन्छ, जबकि उच्च देशान्तर भएको ग्रहलाई पराजित मानिन्छ।\n\nप्रभावहरू:\n• पराजित ग्रहका कारकत्वहरूमा असर पर्न सक्छ\n• यदि पराजित ग्रहले महत्त्वपूर्ण भावहरूको स्वामी हो भने, ती क्षेत्रहरू प्रभावित हुन सक्छन्\n• नजिकको युतिमा युद्ध सबैभन्दा तीव्र हुन्छ"),
    GRAHA_DEFEATS_MSG("%1\$2 defeats %2\$2", "%1\$2 ले %2\$2 लाई जित्छ"),
    GRAHA_IN_HOUSE_MSG("in %1\$2 (House %2\$2)", "%1\$2 (भाव %2\$2) मा"),
;
}
