package com.astro.storm.core.common

enum class StringKeyGeneralPart4(override val en: String, override val ne: String) : StringKeyInterface {
    DRIG_BENEFIC_ASPECTS("Benefic Aspects", "शुभ दृष्टिहरू"),
    DRIG_DESC("Shadbala component measuring strength from planetary aspects", "ग्रह दृष्टिबाट बल मापन गर्ने षड्बल घटक"),
    DRIG_FULL_ASPECT("Full Aspect (100%)", "पूर्ण दृष्टि (१००%)"),
    DRIG_HALF_ASPECT("Half Aspect (50%)", "आधा दृष्टि (५०%)"),
    DRIG_INFO_DESC("Drig Bala measures aspectual strength - the positive or negative influence from planetary aspects. Benefic aspects add strength while malefic aspects reduce it. Net Drig Bala determines overall aspectual support.", "दृग्बलले दृष्टि बल मापन गर्छ - ग्रह दृष्टिबाट सकारात्मक वा नकारात्मक प्रभाव। शुभ दृष्टिले बल थप्छ जबकि अशुभ दृष्टिले घटाउँछ। शुद्ध दृग्बलले समग्र दृष्टि समर्थन निर्धारण गर्छ।"),
    DRIG_INFO_TITLE("About Drig Bala", "दृग्बलको बारेमा"),
    DRIG_MALEFIC_ASPECTS("Malefic Aspects", "अशुभ दृष्टिहरू"),
    DRIG_NEGATIVE("Negative", "नकारात्मक"),
    DRIG_NET_STRENGTH("Net Aspectual Strength", "शुद्ध दृष्टि बल"),
    DRIG_PLANET_CASTING("Aspects Cast", "दिइएको दृष्टि"),
    DRIG_PLANET_RECEIVING("Aspects Received", "प्राप्त दृष्टि"),
    DRIG_POSITIVE("Positive", "सकारात्मक"),
    DRIG_QUARTER_ASPECT("Quarter Aspect (25%)", "चौथाई दृष्टि (२५%)"),
    DRIG_SPECIAL_ASPECT("Special Aspect", "विशेष दृष्टि"),
    DRIG_SUBTITLE("Aspectual Strength Analysis", "दृष्टि बल विश्लेषण"),
    DRIG_TAB_ASPECTS("Aspects", "दृष्टिहरू"),
    DRIG_TAB_HOUSES("Houses", "भावहरू"),
    DRIG_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    DRIG_TAB_PLANETS("Planets", "ग्रहहरू"),
    DRIG_THREE_QUARTER("3/4 Aspect (75%)", "३/४ दृष्टि (७५%)"),
    DRIG_TITLE("Drig Bala", "दृग्बल"),
    DRIG_TOTAL_SCORE("Total Drig Bala", "कुल दृग्बल"),
    DRIG_UNABLE("Unable to calculate Drig Bala", "दृग्बल गणना गर्न सकिएन"),
    DRIG_VEDIC_REF("Vedic Reference: BPHS Shadbala chapter, Graha Sutras", "वैदिक सन्दर्भ: बृहत् पाराशर होरा शास्त्र षड्बल अध्याय, ग्रह सूत्र"),
    DRIG_VIRUPAS("Virupas", "विरूपा"),
    EARNING_PATTERNS("Earning Patterns", "आय ढाँचाहरू"),
    EARNING_POTENTIAL("Earning Potential", "आय क्षमता"),
    EARNING_TITLE("Earning Analysis", "आय विश्लेषण"),
    EDIT_PROFILE_NO_DATA("No chart data available. Please select a profile to edit.", "कुनै कुण्डली डाटा उपलब्ध छैन। कृपया सम्पादन गर्न प्रोफाइल छान्नुहोस्।"),
    EDIT_PROFILE_TITLE("Edit Profile", "प्रोफाइल सम्पादन"),
    EDUCATIONAL_ENVIRONMENT("Educational Environment", "शैक्षिक वातावरण"),
    EDUCATION_5TH_STRONG("Strong 5th house indicates academic excellence, creative intelligence, and success in competitive exams.",
        "बलियो ५औं भावले शैक्षिक उत्कृष्टता, रचनात्मक बुद्धिमत्ता, र प्रतिस्पर्धात्मक परीक्षाहरूमा सफलता संकेत गर्छ।"),
    EDUCATION_FIELDS_TEMPLATE("Favorable fields of study: %s. These align with your natural intellectual strengths.",
        "अनुकूल अध्ययन क्षेत्रहरू: %s। यी तपाईंको प्राकृतिक बौद्धिक शक्तिहरूसँग मिल्दछन्।"),
    EDUCATION_JUPITER_ASPECT("Jupiter's influence on education houses indicates success in higher studies and wisdom acquisition.",
        "शिक्षा भावहरूमा बृहस्पतिको प्रभावले उच्च अध्ययन र ज्ञान प्राप्तिमा सफलता संकेत गर्छ।"),
    EDUCATION_MERCURY_STRONG("Strong Mercury blesses you with excellent learning abilities, communication skills, and analytical thinking.",
        "बलियो बुधले तपाईंलाई उत्कृष्ट सिक्ने क्षमता, सञ्चार कौशल, र विश्लेषणात्मक सोचको आशीर्वाद दिन्छ।"),
    EDUCATION_OVERVIEW("Educational prospects are analyzed through the 4th house (basic education), 5th house (higher learning), and Mercury's placement.",
        "शैक्षिक सम्भावनाहरू ४औं भाव (आधारभूत शिक्षा), ५औं भाव (उच्च शिक्षा), र बुधको स्थान मार्फत विश्लेषण गरिएको छ।"),
    EDU_SUMMARY("Education Summary", "शिक्षा सारांश"),
    EDU_TIMELINE("Education Timeline", "शिक्षा समयरेखा"),
    EFFECTS_LABEL("Effects", "प्रभावहरू"),
    EFFECT_AKHANDA_SAMRAJYA_EXP("Unbroken empire, sustained authority throughout life.", "अखण्डित साम्राज्य, जीवनभर निरन्तर अधिकार।"),
    EFFECT_BALARISHTA("Early childhood health concerns, requires remedies.", "बाल्यकालमा स्वास्थ्य चिन्ता, उपचार आवश्यक।"),
    EFFECT_BANDHANA("Confinement, imprisonment, or restrictions.", "कैद, बन्धन, वा प्रतिबन्ध।"),
    EFFECT_BHARATHI("Exceptional intelligence, scholarship, fame, wealth, religious nature.", "असाधारण बुद्धि, विद्वता, प्रसिद्धि, धन, धार्मिक स्वभाव।"),
    EFFECT_BHERI("Wealthy, good health, happy family, religious.", "धनी, राम्रो स्वास्थ्य, सुखी परिवार, धार्मिक।"),
    EFFECT_BUDHA_DIGNITY("Mercury well-placed giving intelligence.", "राम्रो स्थानमा बुधले बुद्धि दिने।"),
    EFFECT_BUSINESS("Success in commercial ventures and trade.", "व्यापारिक उद्यम र व्यापारमा सफलता।"),
    EFFECT_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    EFFECT_CHANDRA_DIGNITY("Moon in favorable position giving mental peace.", "अनुकूल स्थानमा चन्द्रले मानसिक शान्ति दिने।"),
    EFFECT_CHATUSSAGARA("Fame spreading to four directions, international recognition.", "चारैतिर प्रसिद्धि फैलिने, अन्तर्राष्ट्रिय मान्यता।"),
    EFFECT_COMBUSTION("Planet too close to Sun, diminished significations.", "ग्रह सूर्यको धेरै नजिक, कमजोर महत्व।"),
    EFFECT_DAINYA_PARIVARTTANA("Exchange involving 6th/8th/12th, challenging but transformative.", "६/८/१२ समावेश आदानप्रदान, चुनौतीपूर्ण तर रूपान्तरणकारी।"),
    EFFECT_DANDA("Staff yoga, authority and punishment capacity.", "दण्ड योग, अधिकार र दण्ड क्षमता।"),
    EFFECT_DARIDRA_EXP("Poverty, financial struggles, difficulties in accumulating wealth.", "गरिबी, आर्थिक संघर्ष, धन संचयमा कठिनाई।"),
    EFFECT_DHANA_KARAKA("Natural significator of wealth giving prosperity.", "धनको प्राकृतिक कारकले समृद्धि दिने।"),
    EFFECT_DIFFICULT("Difficult", "कठिन"),
    EFFECT_DIGBALA_RAJA("Directional strength giving kingly results.", "दिशाको बलले राजकीय परिणाम दिने।"),
    EFFECT_DURYOGA("General misfortune, obstacles in progress.", "सामान्य दुर्भाग्य, प्रगतिमा बाधा।"),
    EFFECT_EXCELLENT("Excellent", "उत्कृष्ट"),
    EFFECT_GANDANTA("Junction point between water and fire signs, karmic knot.", "जल र अग्नि राशि बीचको जंक्शन, कार्मिक गाँठो।"),
    EFFECT_GENERIC_BAD("Challenging placement causing difficulties related to {0} and {1}.", "{0} र {1} सँग सम्बन्धित कठिनाइहरू निम्त्याउने चुनौतीपूर्ण स्थिति।"),
    EFFECT_GENERIC_GOOD("Favorable placement bringing positive results related to {0} and {1}.", "{0} र {1} सँग सम्बन्धित सकारात्मक परिणाम ल्याउने अनुकूल स्थिति।"),
    EFFECT_GENERIC_MIXED("Mixed results giving both success and challenges in {0}.", "{0} मा सफलता र चुनौती दुवै दिने मिश्रित परिणाम।"),
    EFFECT_GOOD("Good", "राम्रो"),
    EFFECT_GOURI("Beautiful, religious, wealthy, famous, blessed with a good family.", "सुन्दर, धार्मिक, धनी, प्रसिद्ध, राम्रो परिवारको साथ आशिष्।"),
    EFFECT_GURU_DIGNITY("Jupiter strong giving wisdom and prosperity.", "बलियो गुरुले ज्ञान र समृद्धि दिने।"),
    EFFECT_HARIHARA_BRAHMA("Scholar, truthful, happy, helpful.", "विद्वान, सत्यवादी, खुसी, सहयोगी।"),
    EFFECT_INDU_LAGNA_EXP("Wealth through Moon ascendant calculations.", "चन्द्र लग्न गणनाद्वारा धन।"),
    EFFECT_INHERITANCE("Wealth through inheritance, hidden treasures.", "उत्तराधिकार, गुप्त धनबाट सम्पत्ति।"),
    EFFECT_JUPITER_SATURN("Dharma-Karma Adhipati (potentially), responsible, philosophical.", "धर्म-कर्माधिपति (सम्भावित), जिम्मेवार, दार्शनिक।"),
    EFFECT_JUPITER_VENUS("Generous, wealthy, learned, maybe conflicts in philosophy.", "उदार, धनी, विद्वान, दर्शनमा द्वन्द्व हुन सक्छ।"),
    EFFECT_JUP_CHILD("Children-related challenges", "सन्तान सम्बन्धी चुनौतीहरू"),
    EFFECT_JUP_GEN("Fortune matters affected", "भाग्यका मामिलाहरू प्रभावित"),
    EFFECT_JUP_SPIRIT("Spiritual obstacles", "आध्यात्मिक अवरोधहरू"),
    EFFECT_JUP_WISDOM("Wisdom blocked", "ज्ञानमा अवरोध"),
    EFFECT_KALANIDHI("Respected, healthy, wealthy, learned.", "सम्मानित, स्वस्थ, धनी, विद्वान।"),
    EFFECT_KAMALA("Lotus yoga, planets in kendras, wealth and fame.", "कमल योग, केन्द्रमा ग्रह, धन र प्रसिद्धि।"),
    EFFECT_KETU_CHILD("Children-related concerns", "सन्तान सम्बन्धी चिन्ता"),
    EFFECT_KETU_GEN("Detachment themes activated", "विरक्तिका विषयहरू सक्रिय"),
    EFFECT_KETU_KARMA("Past karma surfacing", "विगतको कर्म बाहिर आउने"),
    EFFECT_KETU_MOKSHA("Spiritual liberation through Ketu's grace.", "केतुको कृपाद्वारा आध्यात्मिक मुक्ति।"),
    EFFECT_KETU_WEALTH("Family wealth affected", "पारिवारिक धन प्रभावित"),
    EFFECT_KHADGA("Learned, skilled, wealthy, successful.", "विद्वान, दक्ष, धनी, सफल।"),
    EFFECT_KHALA_PARIVARTTANA("Exchange involving 3rd lord, mixed results.", "तृतीयेश समावेश आदानप्रदान, मिश्रित परिणाम।"),
    EFFECT_KUBERA_EXP("Treasurer of the gods, immense wealth accumulation.", "देवताहरूको कोषाध्यक्ष, अपार धन संचय।"),
    EFFECT_KURMA("Stable wealth, happy, grateful, helpful.", "स्थिर धन, खुसी, कृतज्ञ, सहयोगी।"),
    EFFECT_KUSUMA_EXP("Charitable, protector, head of town/group.", "दानशील, रक्षक, गाउँ/समूहको प्रमुख।"),
    EFFECT_KUTA("Peak yoga, rise to high positions.", "शिखर योग, उच्च पदमा उदय।"),
    EFFECT_LAGNA_ADHI("Benefics in 6th, 7th, 8th from Lagna giving protection.", "६, ७, ८मा शुभ ग्रहले सुरक्षा दिने।"),
    EFFECT_LAGNESH_STRENGTH("Strong ascendant lord giving vitality and success.", "बलियो लग्नेशले जीवनशक्ति र सफलता दिने।"),
    EFFECT_LORD_1_IN_1("Strong health, vitality, leadership ability, self-made success.", "बलियो स्वास्थ्य, जीवनशक्ति, नेतृत्व क्षमता, स्व-निर्मित सफलता।"),
    EFFECT_LORD_1_IN_10("Career success, professional honor, recognition, paternal happiness.", "करियर सफलता, व्यावसायिक सम्मान, मान्यता, पैतृक सुख।"),
    EFFECT_LORD_1_IN_11("Gains, profits, elder sibling happiness, fulfillment of desires.", "लाभ, नाफा, दाजुभाइको सुख, इच्छाहरूको पूर्ति।"),
    EFFECT_LORD_1_IN_12("Expenses, foreign travel, spiritual inclination, maybe losses.", "खर्च, विदेश यात्रा, आध्यात्मिक झुकाव, सायद नोक्सान।"),
    EFFECT_LORD_1_IN_2("Wealthy, good speaker, family-oriented, foresight.", "धनी, राम्रो वक्ता, परिवार-उन्मुख, दूरदर्शिता।"),
    EFFECT_LORD_1_IN_3("Courageous, wealthy, honorable, intelligent, happy with siblings.", "साहसी, धनी, सम्माननीय, बुद्धिमान, दाजुभाइसँग खुसी।"),
    EFFECT_LORD_1_IN_4("Parental happiness, many vehicles, landed property, domestic peace.", "आमाबुबाको सुख, धेरै सवारी साधन, जग्गा जमिन, घरेलु शान्ति।"),
    EFFECT_LORD_1_IN_5("Intelligent, famous, happiness from children, authority.", "बुद्धिमान, प्रसिद्ध, सन्तानसुख, अधिकार।"),
    EFFECT_LORD_1_IN_6("Debts, enemies, health issues, struggle for success.", "ऋण, शत्रु, स्वास्थ्य समस्या, सफलताको लागि संघर्ष।"),
    EFFECT_LORD_1_IN_7("Traveler, success in partnership/business, maybe somewhat wandering nature.", "यात्री, साझेदारी/व्यापारमा सफलता, केही हदसम्म घुमन्ते स्वभाव।"),
    EFFECT_LORD_1_IN_8("Sudden changes, obstacles, occult interests, health fluctuations.", "अचानक परिवर्तन, अवरोध, गुप्त रुचि, स्वास्थ्य उतार-चढाव।"),
    EFFECT_LORD_1_IN_9("Fortunate, popular, religious, patrimony, good character.", "भाग्यशाली, लोकप्रिय, धार्मिक, पैतृक सम्पत्ति, राम्रो चरित्र।"),
    EFFECT_MAHALAKSHMI("Great wealth, luxuries, blessed by goddess Lakshmi.", "महान धन, विलासिता, देवी लक्ष्मीको कृपा।"),
    EFFECT_MAHA_PARIVARTTANA("Powerful exchange between benefic house lords.", "शुभ भाव अधिपतिहरू बीच शक्तिशाली आदानप्रदान।"),
    EFFECT_MANGAL_DIGNITY("Mars in powerful position giving courage.", "शक्तिशाली स्थानमा मंगलले साहस दिने।"),
    EFFECT_MARS_ACC("Accident-prone periods", "दुर्घटनाको जोखिम हुने अवधि"),
    EFFECT_MARS_GEN("Energy and courage matters affected", "ऊर्जा र साहसका मामिलाहरू प्रभावित"),
    EFFECT_MARS_JUPITER("Guru-Mangala Yoga: Leader, energetic, righteous, wealthy.", "गुरु-मंगल योग: नेता, ऊर्जावान, धार्मिक, धनी।"),
    EFFECT_MARS_MERCURY("Technical skill, quick wit, maybe argumentative.", "प्राविधिक कौशल, छिटो बुद्धि, तर्क वितर्क गर्ने।"),
    EFFECT_MARS_PROP("Property disputes possible", "सम्पत्ति विवादको सम्भावना"),
    EFFECT_MARS_REL("Relationship conflicts", "सम्बन्धमा द्वन्द्व"),
    EFFECT_MARS_SATURN("Disciplined energy, technical ability, struggles.", "अनुशासित ऊर्जा, प्राविधिक क्षमता, संघर्ष।"),
    EFFECT_MARS_VENUS("Passionate, artistic, charming, relationship focused.", "भावुक, कलात्मक, आकर्षक, सम्बन्ध केन्द्रित।"),
    EFFECT_MATSYA("Kind, religious, learned, strong character.", "दयालु, धार्मिक, विद्वान, बलियो चरित्र।"),
    EFFECT_MERCURY_JUPITER("Learned, eloquent, writer, advisor.", "विद्वान, वाक्पटु, लेखक, सल्लाहकार।"),
    EFFECT_MERCURY_SATURN("Analytical, profound thinker, steady progress.", "विश्लेषणात्मक, गहिरो चिन्तक, स्थिर प्रगति।"),
    EFFECT_MERCURY_VENUS("Raja Yoga related to arts/commerce, jovial, eloquent.", "कला/वाणिज्यसँग सम्बन्धित राज योग, हँसिलो, वाक्पटु।"),
    EFFECT_MERC_BIZ("Business challenges", "व्यापारमा चुनौतीहरू"),
    EFFECT_MERC_COMM("Communication difficulties", "सञ्चारमा कठिनाइहरू"),
    EFFECT_MERC_EDU("Education obstacles", "शिक्षामा अवरोधहरू"),
    EFFECT_MERC_GEN("Intellectual matters influenced", "बौद्धिक मामिलाहरू प्रभावित"),
    EFFECT_MOKSHA("Liberation, spiritual enlightenment potential.", "मुक्ति, आध्यात्मिक ज्ञानको सम्भावना।"),
    EFFECT_MOKSHA_TRIKONA("Spiritual advancement through 4th, 8th, 12th connection.", "४, ८, १२ सम्बन्धद्वारा आध्यात्मिक प्रगति।"),
    EFFECT_MOON_EMO("Emotional fluctuations", "भावनात्मक उतार-चढाव"),
    EFFECT_MOON_GEN("Emotional matters influenced by house placement", "घरको स्थितिका कारण भावनात्मक मामिलाहरू प्रभावित"),
    EFFECT_MOON_JUPITER("Gajakesari Yoga: Famous, virtuous, wealthy, leader.", "गजकेसरी योग: प्रसिद्ध, सद्गुणी, धनी, नेता।"),
    EFFECT_MOON_MARS("Chandra-Mangala Yoga: Wealthy, enterprising, maybe mother's health issues.", "चन्द्र-मंगल योग: धनी, उद्यमशील, आमाको स्वास्थ्य समस्या हुन सक्छ।"),
    EFFECT_MOON_MERCURY("Learned, pleasant speech, clever, artistic.", "विद्वान, सुखद बोली, चलाख, कलात्मक।"),
    EFFECT_MOON_MOTHER("Mother's health concerns", "आमाको स्वास्थ्यमा चिन्ता"),
    EFFECT_MOON_PEACE("Mental peace disturbances", "मानसिक शान्तिमा अवरोध"),
    EFFECT_MOON_SATURN("Serious, detached, hardworking, maybe depressive.", "गम्भीर, विरक्त, मेहेनती, उदास हुन सक्छ।"),
    EFFECT_MOON_VENUS("Soft nature, artistic, beautiful, wealthy.", "कोमल स्वभाव, कलात्मक, सुन्दर, धनी।"),
    EFFECT_MRIDANGA("Respected, famous, attractive, influential.", "सम्मानित, प्रसिद्ध, आकर्षक, प्रभावशाली।"),
    EFFECT_MUSALA_EXP("Planets in fixed signs, stability and persistence.", "स्थिर राशिमा ग्रह, स्थिरता र दृढता।"),
    EFFECT_NAKSHATRA_DEVA("Divine temperament nakshatra placement.", "दैवी स्वभाव नक्षत्र स्थान।"),
    EFFECT_NAKSHATRA_MANUSHYA("Human temperament nakshatra, balanced nature.", "मानव स्वभाव नक्षत्र, सन्तुलित प्रकृति।"),
    EFFECT_NAKSHATRA_RAKSHASA("Fierce temperament nakshatra, powerful but challenging.", "उग्र स्वभाव नक्षत्र, शक्तिशाली तर चुनौतीपूर्ण।"),
    EFFECT_NALA_EXP("Planets in dual signs, adaptability and versatility.", "द्विस्वभाव राशिमा ग्रह, अनुकूलता र बहुमुखी प्रतिभा।"),
    EFFECT_NAUKA("Boat yoga, success through overseas connections.", "नाव योग, विदेशी सम्बन्धद्वारा सफलता।"),
    EFFECT_NEUTRAL("Neutral", "तटस्थ"),
    EFFECT_PAPAKARTARI_LAGNA("Malefics hemming the ascendant, challenges in life.", "लग्नलाई पाप ग्रहले घेरेको, जीवनमा चुनौती।"),
    EFFECT_PRAVRAJYA("Ascetic life, monastic tendencies.", "तपस्वी जीवन, सन्यासी प्रवृत्ति।"),
    EFFECT_PROPERTY("Gains through land, buildings, and real estate.", "जग्गा, भवन र अचल सम्पत्तिबाट लाभ।"),
    EFFECT_PUSHYA_NAKSHATRA("Auspicious star of nourishment and growth.", "पोषण र वृद्धिको शुभ तारा।"),
    EFFECT_RAHU_FOREIGN("Foreign-related complications", "विदेशसँग सम्बन्धित जटिलताहरू"),
    EFFECT_RAHU_GEN("Unconventional matters affected", "अपरम्परागत मामिलाहरू प्रभावित"),
    EFFECT_RAHU_ID("Identity confusion", "पहिचानमा भ्रम"),
    EFFECT_RAHU_SUDDEN("Sudden relationship issues", "अचानक सम्बन्धमा समस्या"),
    EFFECT_RAJJU_EXP("Planets in movable signs, constant movement and travel.", "चर राशिमा ग्रह, निरन्तर चाल र यात्रा।"),
    EFFECT_ROGAISHTA("Health afflictions, chronic diseases possible.", "स्वास्थ्य समस्या, दीर्घकालीन रोग सम्भव।"),
    EFFECT_SANNYASA("Renunciation, detachment from material world.", "त्याग, भौतिक संसारबाट विरक्ति।"),
    EFFECT_SAT_GEN("Karmic matters activated", "कार्मिक मामिलाहरू सक्रिय"),
    EFFECT_SAT_HEALTH("Health and longevity concerns", "स्वास्थ्य र दीर्घायुमा चिन्ता"),
    EFFECT_SAT_HOME("Home comfort issues", "घरेलु सुविधामा समस्या"),
    EFFECT_SAT_PARTNER("Partnership delays", "साझेदारीमा ढिलाइ"),
    EFFECT_SHAKTI("Spear yoga, powerful and commanding.", "भाला योग, शक्तिशाली र आदेशात्मक।"),
    EFFECT_SHANI_DIGNITY("Saturn in good position giving discipline and longevity.", "राम्रो स्थानमा शनिले अनुशासन र दीर्घायु दिने।"),
    EFFECT_SHARA("Arrow yoga, focused and goal-oriented.", "तीर योग, केन्द्रित र लक्ष्योन्मुख।"),
    EFFECT_SHUKRA_DIGNITY("Venus well-placed giving comforts and beauty.", "राम्रो स्थानमा शुक्रले सुख र सौन्दर्य दिने।"),
    EFFECT_SIMHASANA("Royal authority, leadership, sits on a throne-like position.", "राजकीय अधिकार, नेतृत्व, सिंहासन जस्तो स्थानमा बस्ने।"),
    EFFECT_SREENATHA("Wealthy, lordly, religious, eloquent.", "धनी, प्रभुत्वशाली, धार्मिक, वाक्पटु।"),
    EFFECT_SUBHAKARTARI_LAGNA("Benefics hemming the ascendant, overall protection.", "लग्नलाई शुभ ग्रहले घेरेको, समग्र सुरक्षा।"),
    EFFECT_SUN_AUTH("Authority challenges", "अधिकारमा चुनौतीहरू"),
    EFFECT_SUN_FATHER("Father's health concerns", "बुबाको स्वास्थ्यमा चिन्ता"),
    EFFECT_SUN_GEN("Leadership matters affected by house placement", "घरको स्थितिका कारण नेतृत्वका मामिलाहरू प्रभावित"),
    EFFECT_SUN_GOVT("Government-related obstacles", "सरकारसँग सम्बन्धित अवरोधहरू"),
    EFFECT_SUN_JUPITER("Spiritual, wealthy, respected, advisor, teacher.", "आध्यात्मिक, धनी, सम्मानित, सल्लाहकार, शिक्षक।"),
    EFFECT_SUN_MARS("Energetic, brave, aggressive, maybe health issues.", "ऊर्जावान, बहादुर, आक्रामक, स्वास्थ्य समस्या हुन सक्छ।"),
    EFFECT_SUN_MERCURY("Budhaditya Yoga: Intelligent, learned, famous, good speaker.", "बुधादित्य योग: बुद्धिमान, विद्वान, प्रसिद्ध, राम्रो वक्ता।"),
    EFFECT_SUN_MOON("Skillful in work, wealthy but fluctuating fortune.", "काममा दक्ष, धनी तर उतार-चढावपूर्ण भाग्य।"),
    EFFECT_SUN_SATURN("Hardworking, struggles with authority, disciplined.", "मेहेनती, अधिकारसँग संघर्ष, अनुशासित।"),
    EFFECT_SUN_VENUS("Artistic, comfort-loving, maybe eye trouble.", "कलात्मक, सुख-प्रेमी, आँखाको समस्या हुन सक्छ।"),
    EFFECT_SURYA_DIGNITY("Sun in strong position giving authority.", "बलियो स्थानमा सूर्यले अधिकार दिने।"),
    EFFECT_TRIMURTI("Happy, wealthy, long life, famous.", "खुसी, धनी, दीर्घायु, प्रसिद्ध।"),
    EFFECT_VAJRA("Thunderbolt yoga, strong beginning and end of life.", "वज्र योग, जीवनको सुरु र अन्त बलियो।"),
    EFFECT_VAPI("Well yoga, planets in panaparas, steady gains.", "कुवा योग, पनपारमा ग्रह, स्थिर लाभ।"),
    EFFECT_VARGOTTAMA_LAGNA("Same sign in Rashi and Navamsha, strengthened ascendant.", "राशि र नवांशमा एउटै राशि, बलियो लग्न।"),
    EFFECT_VENUS_GEN("Relationship and comfort matters affected", "सम्बन्ध र सुविधाका मामिलाहरू प्रभावित"),
    EFFECT_VENUS_LUXURY("Luxury denied", "सुख-सुविधाबाट वञ्चित"),
    EFFECT_VENUS_MARR("Marriage delays or conflicts", "विवाहमा ढिलाइ वा द्वन्द्व"),
    EFFECT_VENUS_REL("Relationship troubles", "सम्बन्धमा समस्या"),
    EFFECT_VENUS_SATURN("Artist, loyal, steady wealth, maybe late marriage.", "कलाकार, वफादार, स्थिर धन, ढिलो विवाह हुन सक्छ।"),
    EFFECT_YUPA("Sacrificial post yoga, religious and charitable.", "यज्ञस्तम्भ योग, धार्मिक र दानशील।"),
    EIGHTH_HOUSE_LORD("8th House Lord", "अष्टम भाव स्वामी"),
    EIGHTH_HOUSE_PLANETS("Planets in 8th House", "अष्टम भावमा ग्रहहरू"),
    EIGHTH_HOUSE_SIGN("8th House Sign", "अष्टम भाव राशि"),
    ELEMENT_AIR("Air", "वायु"),
    ELEMENT_EARTH("Earth", "पृथ्वी"),
    ELEMENT_ETHER("Ether", "आकाश"),
    ELEMENT_FIRE("Fire", "अग्नि"),
    ELEMENT_REC_AIR("Engage in social activities and intellectual pursuits.", "सामाजिक गतिविधिहरू र बौद्धिक प्रयासहरूमा संलग्न हुनुहोस्।"),
    ELEMENT_REC_EARTH("Focus on practical matters and material progress.", "व्यावहारिक मामिलाहरू र भौतिक प्रगतिमा ध्यान दिनुहोस्।"),
    ELEMENT_REC_FIRE("Take bold action and express yourself confidently.", "साहसी कदम चाल्नुहोस् र आत्मविश्वासका साथ आफूलाई व्यक्त गर्नुहोस्।"),
    ELEMENT_REC_WATER("Trust your intuition and honor your emotions.", "आफ्नो अन्तर्ज्ञानमाथि विश्वास गर्नुहोस् र आफ्ना भावनाहरूलाई सम्मान गर्नुहोस्।"),
    ELEMENT_WATER("Water", "जल"),
    ELEVENTH_HOUSE_LORD("11th House Lord", "एकादश भाव स्वामी"),
    ELEVENTH_HOUSE_PLANETS("Planets in 11th House", "एकादश भावमा ग्रहहरू"),
    ELEVENTH_HOUSE_SIGN("11th House Sign", "एकादश भाव राशि"),
    EMOTIONAL_CHALLENGES("Emotional Challenges", "भावनात्मक चुनौतीहरू"),
    EMOTIONAL_EXPRESSION("Emotional Expression", "भावनात्मक अभिव्यक्ति"),
    EMOTIONAL_GROWTH("Emotional Growth Path", "भावनात्मक विकास मार्ग"),
    EMOTIONAL_NATURE_TITLE("Emotional Nature", "भावनात्मक स्वभाव"),
    EMOTIONAL_STRENGTHS("Emotional Strengths", "भावनात्मक शक्तिहरू"),
    EMOTIONAL_TRIGGERS("Emotional Triggers", "भावनात्मक ट्रिगरहरू"),
    EMPLOYEE_VS_EMPLOYER("Employee vs Employer", "कर्मचारी बनाम नियोक्ता"),
    EMPLOYMENT_TITLE("Employment Type Analysis", "रोजगार प्रकार विश्लेषण"),
    ENERGY_BALANCED("Balanced energy - stay centered and focused", "सन्तुलित ऊर्जा - केन्द्रित र ध्यान केन्द्रित रहनुहोस्"),
    ENERGY_CHALLENGING("Challenging day - practice patience and self-care", "चुनौतीपूर्ण दिन - धैर्य र आत्म-हेरचाह अभ्यास गर्नुहोस्"),
    ENERGY_EXCELLENT("Excellent day ahead - favorable for important decisions", "उत्कृष्ट दिन अगाडि - महत्त्वपूर्ण निर्णयहरूको लागि अनुकूल"),
    ENERGY_EXCEPTIONAL("Exceptional cosmic alignment - seize every opportunity!", "असाधारण ब्रह्माण्डीय संरेखण - हरेक अवसर समात्नुहोस्!"),
    ENERGY_FAVORABLE("Favorable energy - maintain steady progress", "अनुकूल ऊर्जा - स्थिर प्रगति कायम राख्नुहोस्"),
    ENERGY_LOWER("Lower energy day - prioritize rest and reflection", "कम ऊर्जा दिन - आराम र चिन्तनलाई प्राथमिकता दिनुहोस्"),
    ENERGY_MODERATE("Moderate energy - pace yourself wisely", "मध्यम ऊर्जा - बुद्धिमानीपूर्वक आफ्नो गति मिलाउनुहोस्"),
    ENERGY_REST("Rest and recharge recommended - avoid major decisions", "आराम र रिचार्ज सिफारिस - प्रमुख निर्णयहरूबाट बच्नुहोस्"),
    ENERGY_STRONG("Strong positive energy - good for new initiatives", "बलियो सकारात्मक ऊर्जा - नयाँ पहलहरूको लागि राम्रो"),
    ESTIMATED_AGE("Estimated Age Range", "अनुमानित उमेर दायरा"),
    EXALTED(" Exalted - excellent results.", " उच्च - उत्कृष्ट परिणाम।"),
    EXAM_POTENTIAL("Competitive Exam Potential", "प्रतिस्पर्धी परीक्षा क्षमता"),
    EXCHANGE_6_12("6th-12th lord exchange - enemies are neutralized, losses become gains through service", "६औं-१२औं भावको स्वामी आदानप्रदान - शत्रुहरू निष्क्रिय हुन्छन्, सेवा मार्फत घाटा लाभमा परिणत हुन्छ"),
    EXCHANGE_6_8("6th-8th lord exchange creates powerful Vipareeta yoga - enemies face sudden downfall, native benefits from others'' losses", "६औं-८औं भावको स्वामी आदानप्रदानले शक्तिशाली विपरीत योग सिर्जना गर्दछ - शत्रुहरूले अचानक पतन सामना गर्छन्, जातकले अरूको घाटाबाट लाभ उठाउँछ"),
    EXCHANGE_8_12("8th-12th lord exchange - transformation leads to liberation, hidden knowledge revealed", "८औं-१२औं भावको स्वामी आदानप्रदान - रूपान्तरणले मुक्तितर्फ लैजान्छ, लुकेको ज्ञान प्रकट हुन्छ"),
    EXERCISE_RECS("Exercise Recommendations", "व्यायाम सिफारिसहरू"),
    EXPECTED_RESULTS("Expected Results", "अपेक्षित परिणामहरू"),
    FACTOR_DUSTHANA_IN_DUSTHANA("Dusthana lord placed in dusthana house ({0}th sign)", "दुस्थान स्वामी दुस्थान भावमा ({0}औं राशि)"),
    FACTOR_EXALTED_DUSTHANA("Dusthana lord is exalted - strong results", "दुस्थान स्वामी उच्च छ - बलियो परिणाम"),
    FACTOR_JUPITER_ASPECT("Jupiter''s aspect enhances benefic potential", "बृहस्पतिको दृष्टिले शुभ सम्भावना बढाउँछ"),
    FACTOR_OWN_SIGN_DUSTHANA("Dusthana lord in own sign - stable results", "दुस्थान स्वामी आफ्नै राशिमा - स्थिर परिणाम"),
    FACTOR_RETROGRADE_INTENSE("Retrograde position intensifies yoga effects", "वक्री स्थितिले योगको प्रभावलाई तीव्र बनाउँछ"),
    FAITH_AND_BELIEF("Faith & Belief", "विश्वास र आस्था"),
    FATHER_RELATIONSHIP("Relationship with Father", "बुबासँगको सम्बन्ध"),
    FAVORABLE("Favorable", "अनुकूल"),
    FAVORABLE_DATES("Favorable Dates", "अनुकूल मितिहरू"),
    FAVORABLE_INVESTMENTS("Favorable Investments", "अनुकूल लगानीहरू"),
    FAVORABLE_PERIODS("Favorable Marriage Periods", "अनुकूल विवाह अवधिहरू"),
    FAVORABLE_YOGA("Favorable Marriage Yoga", "अनुकूल विवाह योग"),
    FIFTH_HOUSE_LORD("5th House Lord", "पञ्चम भाव स्वामी"),
    FIFTH_HOUSE_SIGN("5th House Sign", "पञ्चम भाव राशि"),
    FILTER_ALL("All", "सबै"),
    FILTER_CAREER("Career", "क्यारियर"),
    FILTER_HEALTH("Health", "स्वास्थ्य"),
    FILTER_OTHER("Other", "अन्य"),
    FILTER_RELATIONSHIPS("Relationships", "सम्बन्ध"),
    FILTER_SPIRITUAL("Spiritual", "आध्यात्मिक"),
    FILTER_WEALTH("Wealth", "धन"),
    FINANCIAL_CHALLENGES("Financial Challenges", "आर्थिक चुनौतीहरू"),
    FINANCIAL_STRENGTHS("Financial Strengths", "आर्थिक शक्तिहरू"),
    FIRST_IMPRESSION_NEUTRAL("Neutral First Impression", "तटस्थ पहिलो छाप"),
    FIRST_IMPRESSION_POSITIVE("Positive First Impression", "सकारात्मक पहिलो छाप"),
    FIRST_IMPRESSION_TITLE("First Impression", "पहिलो छाप"),
    FOCUS_AREAS("Focus Areas", "फोकस क्षेत्रहरू"),
    FOCUS_ASHTAMA_SHANI("Ashtama Shani - be cautious about health, unexpected challenges", "अष्टम शनि - स्वास्थ्य र अप्रत्याशित चुनौतीहरूबारे सावधान रहनुहोस्"),
    FOCUS_JUPITER_11("Jupiter transiting 11th - gains through networking, fulfillment of desires", "एघारौं भावमा बृहस्पति - नेटवर्किङ मार्फत लाभ, इच्छाहरूको पूर्ति"),
    FOCUS_JUPITER_2("Jupiter transiting 2nd - favorable for wealth accumulation", "दोस्रो भावमा बृहस्पति - धन सञ्चयको लागि अनुकूल"),
    FOCUS_JUPITER_TRINE("Jupiter in trine houses - excellent for expansion, learning, spirituality", "त्रिकोण भावमा बृहस्पति - विस्तार, सिकाइ र आध्यात्मिकताको लागि उत्कृष्ट"),
    FOCUS_SADE_SATI("Sade Sati period - focus on patience, health, and spiritual growth", "साढे साती अवधि - धैर्य, स्वास्थ्य र आध्यात्मिक वृद्धिमा ध्यान दिनुहोस्"),
    FOCUS_SATURN_10("Saturn transiting 10th - career responsibilities, hard work pays off", "दशौं भावमा शनि - करियर जिम्मेवारीहरू, कडा परिश्रमले फल दिन्छ"),
    FOCUS_SATURN_4("Saturn transiting 4th - attention to home, mother, mental peace", "चौथो भावमा शनि - घर, आमा र मानसिक शान्तिमा ध्यान दिनुहोस्"),
    FOCUS_STRONG_ASPECT("Strong %1\$s from transit %2\$s to natal %3\$s", "गोचर %2\$s बाट जन्म %3\$s मा बलियो %1\$s"),
    FOREIGN_EDUCATION("Foreign Education Potential", "विदेशी शिक्षा क्षमता"),
    FOREIGN_EMPLOYMENT("Foreign Employment Potential", "विदेशी रोजगार क्षमता"),
    FOREIGN_STUDY("Foreign Study Prospects", "विदेशी अध्ययन सम्भावनाहरू"),
    FORMULA_ADJUSTED("Formula Adjusted", "सूत्र समायोजित"),
    FORMULA_ADJUSTED_DESC("Formulas adjusted per Tajika tradition", "ताजिक परम्परा अनुसार सूत्रहरू समायोजित"),
    FORMULA_LABEL("Formula", "सूत्र"),
    FOURTH_HOUSE_LORD("4th House Lord", "चतुर्थ भाव स्वामी"),
    FOURTH_HOUSE_SIGN("4th House Sign", "चतुर्थ भाव राशि"),
    FREQ_GEN("As recommended", "सिफारिस गरिए अनुसार"),
    FREQ_JUP("Thursdays", "बिहीबार"),
    FREQ_KETU("Tuesdays or Saturdays", "मंगलबार वा शनिबार"),
    FREQ_MARS("Tuesdays", "मंगलबार"),
    FREQ_MERC("Wednesdays", "बुधबार"),
    FREQ_MOON("Mondays", "सोमबार"),
    FREQ_RAHU("Saturdays or specific days", "शनिबार वा विशेष दिनहरू"),
    FREQ_SAT("Saturdays", "शनिबार"),
    FREQ_SUN("Daily at sunrise", "दैनिक सूर्योदयमा"),
    FREQ_VENUS("Fridays", "शुक्रबार"),
    FROM_LABEL("from", "बाट"),
    FROM_LAGNA("from Lagna", "लग्नबाट"),
    FROM_MOON("from Moon", "चन्द्रबाट"),
    FROM_VENUS("from Venus", "शुक्रबाट"),
    FULL_MANTRA("Full Mantra", "पूर्ण मन्त्र"),
    GAINS_PATTERN("Financial Gains Pattern", "आर्थिक लाभ ढाँचा"),
    GANDANTA_BENEFIT_BLOCKAGE("Removes karmic blockages from past lives", "विगतका जीवनका कार्मिक अवरोधहरू हटाउँछ"),
    GANDANTA_BENEFIT_PROTECT("Provides protection during difficult periods", "कठिन समयमा सुरक्षा प्रदान गर्दछ"),
    GANDANTA_BENEFIT_REDUCE("Reduces difficulties in the area ruled by %s", "%s द्वारा शासित क्षेत्रमा कठिनाइहरू कम गर्दछ"),
    GANDANTA_BENEFIT_TRANSFORM("Transforms challenging energy into spiritual growth", "चुनौतीपूर्ण ऊर्जालाई आध्यात्मिक वृद्धिमा परिवर्तन गर्दछ"),
    GANDANTA_BRAHMA("Brahma Gandanta (Cancer-Leo)", "ब्रह्म गण्डान्त (कर्कट-सिंह)"),
    GANDANTA_CAUTION_CONSISTENT("Gandanta requires consistent long-term remedies", "गण्डान्तलाई निरन्तर दीर्घकालीन उपायहरू चाहिन्छ"),
    GANDANTA_CAUTION_CONSULT("Consult a qualified astrologer for personalized guidance", "व्यक्तिगत मार्गदर्शनको लागि योग्य ज्योतिषीसँग परामर्श गर्नुहोस्"),
    GANDANTA_CAUTION_SKIP("Do not skip or abandon the remedy once started", "एक पटक सुरु गरेपछि उपाय नछोड्नुहोस्"),
    GANDANTA_CRITICAL("Critical", "गम्भीर"),
    GANDANTA_DESC("%s is in Gandanta zone (%s). This is a karmic junction requiring special attention.", "%s गण्डान्त क्षेत्र (%s) मा छ। यो विशेष ध्यान दिनुपर्ने कार्मिक संगम हो।"),
    GANDANTA_DURATION("40 days minimum, ideally during %s Dasha", "कम्तिमा ४० दिन, आदर्श रूपमा %s दशाको समयमा"),
    GANDANTA_EXACT_JUNCTION("Exact Junction", "यथार्थ सन्धि"),
    GANDANTA_METHOD_1("1. Perform Shanti Puja for %s", "१. %s को लागि शान्ति पूजा गर्नुहोस्"),
    GANDANTA_METHOD_2("2. Chant %s mantra 11,000 times", "२. %s मन्त्र ११,००० पटक जप गर्नुहोस्"),
    GANDANTA_METHOD_3("3. Donate items related to %s", "३. %s सँग सम्बन्धित वस्तुहरू दान गर्नुहोस्"),
    GANDANTA_METHOD_4("4. Perform Mrityunjaya Japa (108 times daily for 40 days)", "४. मृत्युञ्जय जप गर्नुहोस् (दैनिक १०८ पटक ४० दिनसम्म)"),
    GANDANTA_METHOD_5("5. Donate to orphanages or old age homes", "५. अनाथालय वा वृद्धाश्रममा दान गर्नुहोस्"),
    GANDANTA_METHOD_6("6. Feed Brahmins on %s", "६. %s मा ब्राह्मणहरूलाई भोजन गराउनुहोस्"),
    GANDANTA_METHOD_7("7. Worship Lord Ganesha to remove obstacles", "७. अवरोधहरू हटाउन भगवान गणेशको पूजा गर्नुहोस्"),
    GANDANTA_METHOD_TITLE("GANDANTA REMEDIES:", "गण्डान्त उपायहरू:"),
    GANDANTA_MILD("Mild", "हल्का"),
    GANDANTA_MODERATE("Moderate", "मध्यम"),
    GANDANTA_SEVERE("Severe", "तीव्र"),
    GANDANTA_SEV_CRITICAL("Critical", "गम्भीर"),
    GANDANTA_SEV_EXACT("Exact Junction", "पूर्ण सन्धि"),
    GANDANTA_SEV_MILD("Mild", "हल्का"),
    GANDANTA_SEV_MODERATE("Moderate", "मध्यम"),
    GANDANTA_SEV_SEVERE("Severe", "कडा"),
    GANDANTA_SHIVA("Shiva Gandanta (Pisces-Aries)", "शिव गण्डान्त (मीन-मेष)"),
    GANDANTA_SPECIAL("SPECIAL: Light a ghee lamp daily before the planet's deity", "विशेष: ग्रहको देवता अगाडि दैनिक घिउको बत्ती बाल्नुहोस्"),
    GANDANTA_SUBTITLE("Water-Fire Sign Junction Points", "जल-अग्नि राशि सन्धि बिन्दुहरू"),
    GANDANTA_TIMING("Begin on auspicious day, preferably %s", "शुभ दिनमा सुरु गर्नुहोस्, प्राथमिकता %s"),
    GANDANTA_TITLE("Gandanta Analysis", "गण्डान्त विश्लेषण"),
    GANDANTA_VISHNU("Vishnu Gandanta (Scorpio-Sagittarius)", "विष्णु गण्डान्त (वृश्चिक-धनु)"),
    GAND_BRAHMA_EFF_1("Initial life challenges (first 3 years critical)", "जीवनको सुरुवाती चुनौतीहरू (पहिलो ३ वर्ष महत्त्वपूर्ण)"),
    GAND_BRAHMA_EFF_2("Mother's health during pregnancy/delivery", "गर्भावस्था/प्रसवको समयमा आमाको स्वास्थ्य"),
    GAND_BRAHMA_EFF_3("Creative blocks requiring resolution", "समाधान आवश्यक पर्ने सिर्जनात्मक अवरोधहरू"),
    GAND_BRAHMA_REM_1("Perform Gandanta Shanti puja", "गण्डान्त शान्ति पूजा गर्नुहोस्"),
    GAND_BRAHMA_REM_2("Donate grains and gold", "अन्न र सुन दान गर्नुहोस्"),
    GAND_BRAHMA_REM_3("Worship Lord Brahma", "भगवान ब्रह्माको पूजा गर्नुहोस्"),
    GAND_MARS_EFF_1("Physical challenges or accidents possible", "शारीरिक चुनौती वा दुर्घटनाको सम्भावना"),
    GAND_MARS_EFF_2("Courage tested", "साहसको परीक्षा"),
    GAND_MOON_EFF_1("Emotional turbulence at junction points", "सन्धि बिन्दुहरूमा भावनात्मक उथलपुथल"),
    GAND_MOON_EFF_2("Mental transformation needed", "मानसिक रूपान्तरणको आवश्यकता"),
    GAND_SHIVA_EFF_1("Spiritual awakening through dissolution", "विघटन मार्फत आध्यात्मिक जागृति"),
    GAND_SHIVA_EFF_2("Endings leading to new beginnings", "नयाँ सुरुवात तर्फ लैजाने अन्त्यहरू"),
    GAND_SHIVA_EFF_3("Liberation from material attachments", "भौतिक आसक्तिबाट मुक्ति"),
    GAND_SHIVA_REM_1("Perform Rudra Abhishekam", "रुद्राभिषेक गर्नुहोस्"),
    GAND_SHIVA_REM_2("Donate silver and white items", "चाँदी र सेतो वस्तुहरू दान गर्नुहोस्"),
    GAND_SHIVA_REM_3("Worship Lord Shiva with devotion", "भक्तिका साथ भगवान शिवको पूजा गर्नुहोस्"),
    GAND_SUN_EFF_1("Identity crisis leading to self-realization", "आत्म-बोध तर्फ लैजाने पहिचानको संकट"),
    GAND_SUN_EFF_2("Authority challenges", "अधिकारमा चुनौतीहरू"),
    GAND_VISHNU_EFF_1("Transformation through crisis", "संकट मार्फत रूपान्तरण"),
    GAND_VISHNU_EFF_2("Hidden enemies or obstacles", "लुकेका शत्रु वा अवरोधहरू"),
    GAND_VISHNU_EFF_3("Research and occult abilities", "अनुसन्धान र तान्त्रिक क्षमताहरू"),
    GAND_VISHNU_REM_1("Perform Vishnu Sahasranama recitation", "विष्णु सहस्रनाम पाठ गर्नुहोस्"),
    GAND_VISHNU_REM_2("Donate black sesame and oil", "कालो तिल र तेल दान गर्नुहोस्"),
    GAND_VISHNU_REM_3("Worship Lord Vishnu regularly", "नियमित रूपमा भगवान विष्णुको पूजा गर्नुहोस्"),
    GENERAL_VITALITY("General Vitality", "सामान्य जीवनी शक्ति"),
    GEN_REC_1("Lal Kitab emphasizes practical, daily remedies over expensive rituals", "लाल किताबले महँगो अनुष्ठान भन्दा व्यावहारिक, दैनिक उपायहरूमा जोड दिन्छ"),
    GEN_REC_2("Consistency in remedies is more important than occasional grand gestures", "उपायहरूमा निरन्तरता कहिलेकाहींको ठूलो अनुष्ठान भन्दा बढी महत्त्वपूर्ण छ"),
    GEN_REC_3("Charity (daan) is considered highly effective in Lal Kitab", "लाल किताबमा दानलाई अत्यन्त प्रभावकारी मानिन्छ"),
    GEN_REC_4("Respecting elders and serving the needy brings general planetary blessings", "ठूलाको सम्मान र दुखीको सेवाले सामान्य ग्रह आशीर्वाद ल्याउँछ"),
    GEN_REC_5("Keep your ancestral items with respect for Pitru dosh relief", "पितृ दोषको शान्तिका लागि आफ्ना पुर्ख्यौली वस्तुहरू सम्मानका साथ राख्नुहोस्"),
    GEN_REC_6("Avoid hoarding money - keep it flowing through charity", "पैसा थुपारेर नराख्नुहोस् - दान मार्फत यसलाई प्रवाहित राख्नुहोस्"),
    GEN_REC_7("Maintain clean kitchen and bathroom for overall planetary harmony", "समग्र ग्रह अनुकूलताका लागि भान्छा र शौचालय सफा राख्नुहोस्"),
    GEN_REC_CHARITY("Perform regular charity based on your means - even small acts of giving create positive karma.", "आफ्नो क्षमता अनुसार नियमित दान गर्नुहोस् - सानो दानले पनि सकारात्मक कर्म सिर्जना गर्दछ।"),
    GEN_REC_CLEAN("Maintain a clean and organized living space, especially the puja area and entrance of your home.", "बस्ने ठाउँ सफा र व्यवस्थित राख्नुहोस्, विशेष गरी पूजा क्षेत्र र घरको प्रवेशद्वार।"),
    GEN_REC_DIET("Avoid non-vegetarian food and alcohol on days when performing planetary remedies.", "ग्रह उपचार गर्ने दिनहरूमा मांसाहारी भोजन र मदिराबाट टाढा रहनुहोस्।"),
    GEN_REC_DREAMS("Keep a dream journal - dreams often provide insights about which planets need attention.", "सपनाको जर्नल राख्नुहोस् - सपनाहरूले प्रायः कुन ग्रहहरूलाई ध्यान दिन आवश्यक छ भन्ने बारे अन्तर्दृष्टि प्रदान गर्छन्।"),
    GEN_REC_ELDERS("Respect elders, teachers, and parents - this strengthens Jupiter and reduces many karmic burdens.", "बृद्धबृद्धा, गुरु र आमाबाबुलाई आदर गर्नुहोस् - यसले बृहस्पतिलाई बलियो बनाउँछ र धेरै कार्मिक भारहरू कम गर्दछ।"),
    GEN_REC_GANDANTA("%s is in Gandanta (karmic knot). This requires dedicated long-term remedial measures including regular Mrityunjaya Japa.", "%s गण्डान्त (कार्मिक गाँठो) मा छ। यसका लागि नियमित मृत्युञ्जय जप सहित समर्पित दीर्घकालीन उपचारात्मक उपायहरू आवश्यक पर्दछ।"),
    GEN_REC_LUMINARIES("Both luminaries (Sun and Moon) are weak. Prioritize: Surya Namaskar at sunrise, drink water from silver glass, and practice meditation for emotional balance.", "दुबै प्रकाशपुञ्ज (सूर्य र चन्द्रमा) कमजोर छन्। प्राथमिकता दिनुहोस्: सूर्योदयमा सूर्य नमस्कार, चाँदीको गिलासबाट पानी पिउनुहोस्, र भावनात्मक सन्तुलनको लागि ध्यान अभ्यास गर्नुहोस्।"),
    GEN_REC_MEDITATION("Practice daily meditation for at least 15 minutes to harmonize all planetary energies.", "सबै ग्रह ऊर्जाहरूलाई सामंजस्य गर्न कम्तिमा १५ मिनेट दैनिक ध्यान अभ्यास गर्नुहोस्।"),
    GEN_REC_MOON("Moon remedies are essential for mental peace. Keep a bowl of water near your bed at night and offer it to plants in the morning.", "मानसिक शान्तिको लागि चन्द्रमाका उपायहरू आवश्यक छन्। राती आफ्नो ओछ्यान नजिकै पानीको कचौरा राख्नुहोस् र बिहान बोटबिरुवालाई चढाउनुहोस्।"),
    GEN_REC_MULTIPLE("Multiple planets (%d) need attention. Focus on the 2-3 most afflicted planets first. Start with mantras and charity as they have no side effects.", "धेरै ग्रहहरू (%d) लाई ध्यान दिन आवश्यक छ। पहिले २-३ सबैभन्दा पीडित ग्रहहरूमा ध्यान केन्द्रित गर्नुहोस्। मन्त्र र दानबाट सुरु गर्नुहोस् किनभने यी कुनै साइड इफेक्ट छैनन्।"),
    GEN_REC_NEECHA_BHANGA("%s has Neecha Bhanga Raja Yoga - initial struggles will transform into success. Stay patient and persistent.", "%s को नीच भङ्ग राजयोग छ - सुरुका संघर्षहरू सफलतामा परिणत हुनेछन्। धैर्य र निरन्तर रहनुहोस्।"),
    GEN_REC_SPIRITUAL("Strong spiritual potential indicated. Consider regular meditation retreats and spiritual study.", "बलियो आध्यात्मिक सम्भावना देखिन्छ। नियमित ध्यान शिविर र आध्यात्मिक अध्ययन विचार गर्नुहोस्।"),
    GEN_REC_YOGAKARAKA("%s is your Yogakaraka planet. Strengthening it through gemstone, mantra, and lifestyle will bring significant positive results.", "%s तपाईंको योगकारक ग्रह हो। रत्न, मन्त्र र जीवनशैली मार्फत यसलाई बलियो बनाउँदा महत्त्वपूर्ण सकारात्मक परिणामहरू आउनेछन्।"),
    GOT_IT("Got it", "बुझें"),
    GRAHA_ABOUT_DESC("Graha Yuddha (Planetary War) occurs when two planets (excluding Sun and Moon) are within 1 degree of each other.\n\nThe planet with the lower longitude is usually considered the winner, while the one with higher longitude is the loser.\n\nImpacts:\n• The losing planet's significations may suffer\n• If the losing planet rules important houses, those areas may be affected\n• The war is most intense during close conjunctions", "ग्रह युद्ध तब हुन्छ जब दुई ग्रहहरू (सूर्य र चन्द्रमा बाहेक) एक अर्काको १ डिग्री भित्र हुन्छन्।\n\nकम देशान्तर भएको ग्रहलाई सामान्यतया विजेता मानिन्छ, जबकि उच्च देशान्तर भएको ग्रहलाई पराजित मानिन्छ।\n\nप्रभावहरू:\n• पराजित ग्रहका कारकत्वहरूमा असर पर्न सक्छ\n• यदि पराजित ग्रहले महत्त्वपूर्ण भावहरूको स्वामी हो भने, ती क्षेत्रहरू प्रभावित हुन सक्छन्\n• नजिकको युतिमा युद्ध सबैभन्दा तीव्र हुन्छ"),
    GRAHA_ABOUT_TITLE("About Graha Yuddha", "ग्रह युद्धको बारेमा"),
    GRAHA_ACTIVE_WARS("Active Wars", "सक्रिय युद्धहरू"),
    GRAHA_ADVANTAGE("Advantage", "फाइदा"),
    GRAHA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
    GRAHA_ANALYSIS_SUMMARY("Analysis Summary", "विश्लेषण सारांश"),
    GRAHA_ANALYZING("Analyzing Planetary Wars...", "ग्रह युद्ध विश्लेषण गर्दै..."),
    GRAHA_DASHA_EFFECTS("Dasha Effects", "दशा प्रभावहरू"),
    GRAHA_DEFEATED("Defeated", "पराजित"),
    GRAHA_DEFEATS_MSG("%1\$2 defeats %2\$2", "%1\$2 ले %2\$2 लाई जित्छ"),
    GRAHA_IN_HOUSE_MSG("in %1\$2 (House %2\$2)", "%1\$2 (भाव %2\$2) मा"),
    GRAHA_MAITRI_AVERAGE("Neutral relationship - average mental compatibility. Requires effort for understanding.", "तटस्थ सम्बन्ध - औसत मानसिक अनुकूलता। बुझाइको लागि प्रयास आवश्यक।"),
    GRAHA_MAITRI_DESC("Mental compatibility and friendship", "मानसिक अनुकूलता र मित्रता"),
    GRAHA_MAITRI_EXCELLENT("Same lord or mutual friends - excellent mental compatibility. Natural understanding.", "उही स्वामी वा पारस्परिक मित्र - उत्कृष्ट मानसिक अनुकूलता। प्राकृतिक बुझाइ।"),
    GRAHA_MAITRI_FRICTION("One enemy present - some mental friction. Different thought processes.", "एउटा शत्रु उपस्थित - केही मानसिक घर्षण। फरक विचार प्रक्रियाहरू।"),
    GRAHA_MAITRI_IMPORTANCE("Graha Maitri examines mental compatibility through planetary friendship of Moon sign lords. It indicates intellectual rapport and communication ease.", "ग्रह मैत्रीले चन्द्र राशि स्वामीहरूको ग्रह मित्रताद्वारा मानसिक अनुकूलता जाँच गर्दछ। यसले बौद्धिक सम्बन्ध र सञ्चार सहजता संकेत गर्दछ।"),
    GRAHA_MAITRI_INCOMPATIBLE("Mutual enemies - significant mental incompatibility. May face frequent misunderstandings.", "पारस्परिक शत्रु - महत्त्वपूर्ण मानसिक असंगतता। बारम्बार गलतफहमीहरू हुन सक्छ।"),
    GRAHA_MAITRI_LEVELS("Same lord/Friends = 5 points. One friend + one neutral = 4 points. Both neutral = 3 points. One enemy = 1-2 points. Both enemies = 0.5 points.", "उही स्वामी/मित्र = ५ अंक। एक मित्र + एक तटस्थ = ४ अंक। दुवै तटस्थ = ३ अंक। एक शत्रु = १-२ अंक। दुवै शत्रु = ०.५ अंक।"),
    GRAHA_MAITRI_REMEDY_LOW("Remedy: Meditate together daily for at least 15 minutes. Practice active listening and clear communication. Strengthen Mercury by chanting Budh mantra on Wednesdays, donating green items, and wearing emerald after consultation.", "उपाय: दैनिक कम्तिमा १५ मिनेट सँगै ध्यान गर्नुहोस्। सक्रिय सुनाइ र स्पष्ट सञ्चार अभ्यास गर्नुहोस्। बुधबारमा बुध मन्त्र जाप गरेर, हरियो वस्तुहरू दान गरेर र परामर्श पछि पन्ना लगाएर बुधलाई बलियो बनाउनुहोस्।"),
    GRAHA_MAITRI_VERY_GOOD("One friend, one neutral - very good mental harmony. Good communication.", "एउटा मित्र, एउटा तटस्थ - धेरै राम्रो मानसिक सामञ्जस्य। राम्रो सञ्चार।"),
    GRAHA_NO_DASHA_DESC("Planets in War not currently activated in Dasha/Antardasha.", "युद्धमा रहेका ग्रहहरू हाल दशा/अन्तर्दशामा सक्रिय छैनन्।"),
    GRAHA_NO_DASHA_EFFECTS("No War-Related Dasha Effects", "कुनै युद्ध-सम्बन्धित दशा प्रभावहरू छैनन्"),
    GRAHA_NO_REMEDIES("No Specific Remedies Needed", "कुनै विशेष उपाय आवश्यक छैन"),
    GRAHA_NO_REMEDIES_DESC("Since there are no active planetary wars, remedial measures are not required.", "कुनै सक्रिय ग्रह युद्ध नभएकोले, उपायहरू आवश्यक छैनन्।"),
    GRAHA_NO_WARS("No Active Planetary Wars", "कुनै सक्रिय ग्रह युद्ध छैन"),
    GRAHA_NO_WARS_DESC("All planets are operating peacefully", "सबै ग्रहहरू शान्तिपूर्ण रूपमा काम गरिरहेका छन्"),
    GRAHA_OVERALL_IMPACT("Overall War Impact", "समग्र युद्ध प्रभाव"),
    GRAHA_SCREEN_TITLE("Graha Yuddha", "ग्रह युद्ध"),
    GRAHA_SEPARATION("Separation", "अन्तर"),
    GRAHA_SUBTITLE("Planetary War Analysis", "ग्रह युद्ध विश्लेषण"),
    GRAHA_VICTORY("Victorious", "विजयी"),
    GRAHA_VS("vs", "विरुद्ध"),
    GRAHA_WAR_STATUS("War Status", "युद्ध स्थिति"),
    GROOM("Groom", "दुलाहा"),
    GROUP_COMMUNICATION("Group Communication", "समूह सञ्चार"),
    GROWTH_OPPORTUNITIES("Growth Opportunities", "विकास अवसरहरू"),
    GROWTH_POTENTIAL("Growth Potential", "विकास क्षमता"),
    GUNA_BHAKOOT("Bhakoot", "भकूट"),
    GUNA_DESC_BHAKOOT("Bhakoot indicates love, health, and financial compatibility based on the Moon sign positions. It's crucial for long-term marital harmony.", "भकुटले चन्द्र राशि स्थितिहरूमा आधारित प्रेम, स्वास्थ्य र आर्थिक अनुकूलता संकेत गर्दछ। यो दीर्घकालीन वैवाहिक सामञ्जस्यको लागि महत्त्वपूर्ण छ।")
}
