package com.astro.storm.core.common

enum class StringKeyTransitPart2(override val en: String, override val ne: String) : StringKeyInterface {
    UPACHAYA_REC_MARS_3("Physical exercise recommended", "शारीरिक व्यायाम सिफारिस गरिन्छ"),
    UPACHAYA_REC_PREPARE_UPCOMING("Prepare for upcoming Upachaya transits by organizing current affairs", "वर्तमान मामिलाहरू व्यवस्थित गरेर आगामी उपचय गोचरहरूको लागि तयारी गर्नुहोस्"),
    UPACHAYA_REC_RAHU_1("Stay grounded amid opportunities", "अवसरहरूको बीचमा संयमित रहनुहोस्"),
    UPACHAYA_REC_RAHU_2("Avoid shortcuts", "छोटो बाटोहरू नखोज्नुहोस्"),
    UPACHAYA_REC_RAHU_3("Embrace innovation carefully", "सावधानीपूर्वक नवीनता अपनाउनुहोस्"),
    UPACHAYA_REC_SATURN_1("Work with discipline and patience", "अनुशासन र धैर्यका साथ काम गर्नुहोस्"),
    UPACHAYA_REC_SATURN_2("Don't expect quick results", "छिटो परिणामको आशा नगर्नुहोस्"),
    UPACHAYA_REC_SATURN_3("Honor commitments and responsibilities", "प्रतिबद्धता र जिम्मेवारीहरूको सम्मान गर्नुहोस्"),
    UPACHAYA_REC_SLOW_PLANET("Major slow-planet transit active - commit to long-term goals", "प्रमुख ढिलो ग्रह गोचर सक्रिय छ - दीर्घकालीन लक्ष्यहरूमा प्रतिबद्ध रहनुहोस्"),
    UPACHAYA_REFERENCE_POINTS("Reference Points", "सन्दर्भ बिन्दुहरू"),
    UPACHAYA_SATURN_PROGRESS("Saturn brings slow, steady progress in %s", "शनिले %s मा ढिलो तर स्थिर प्रगति ल्याउँछ"),
    UPACHAYA_SATURN_TRANSIT("Saturn in Upachaya", "उपचयमा शनि"),
    UPACHAYA_SCREEN_ABOUT("About Upachaya Houses", "उपचय भावहरूको बारेमा"),
    UPACHAYA_SCREEN_ABOUT_DESC("Upachaya houses (3, 6, 10, 11) are growth houses where malefic planets give good results over time. Natural malefics improve with age in these houses.", "उपचय भावहरू (३, ६, १०, ११) वृद्धि भावहरू हुन् जहाँ पापग्रहले समयसँगै राम्रो परिणाम दिन्छन्।"),
    UPACHAYA_SCREEN_DURATION("Transit Duration", "गोचर अवधि"),
    UPACHAYA_SCREEN_EFFECTS("Expected Effects", "अपेक्षित प्रभावहरू"),
    UPACHAYA_SCREEN_FROM_MOON("Transit from Moon Sign", "चन्द्र राशिबाट गोचर"),
    UPACHAYA_SCREEN_HOUSE_10("10th House - Career, Status, Authority", "दसौं भाव - क्यारियर, स्थिति, अधिकार"),
    UPACHAYA_SCREEN_HOUSE_11("11th House - Gains, Desires, Friends", "एघारौं भाव - लाभ, इच्छा, मित्र"),
    UPACHAYA_SCREEN_HOUSE_3("3rd House - Courage, Siblings, Communication", "तेस्रो भाव - साहस, भाइबहिनी, सञ्चार"),
    UPACHAYA_SCREEN_HOUSE_6("6th House - Enemies, Service, Health", "छैटौं भाव - शत्रु, सेवा, स्वास्थ्य"),
    UPACHAYA_SCREEN_SUBTITLE("Growth House Transit Tracker", "वृद्धि भाव गोचर ट्र्याकर"),
    UPACHAYA_SCREEN_TITLE("Upachaya Transits", "उपचय गोचर"),
    UPACHAYA_SCREEN_UPCOMING("Upcoming Favorable Periods", "आगामी अनुकूल अवधिहरू"),
    UPACHAYA_SIGNIFICANCE("Significance", "महत्त्व"),
    UPACHAYA_SIGNIFICANT_TRANSITS("Significant Transits", "महत्त्वपूर्ण गोचरहरू"),
    UPACHAYA_TRANSITS_LABEL("Transits", "गोचरहरू"),
    UPACHAYA_TRANSIT_ABOUT("About Upachaya Houses", "उपचय भावहरूको बारेमा"),
    UPACHAYA_TRANSIT_ABOUT_DESC("Upachaya houses (3, 6, 10, 11) are growth houses where planets, especially natural malefics, give increasingly positive results over time.", "उपचय भावहरू (३, ६, १०, ११) वृद्धि भावहरू हुन् जहाँ ग्रहहरू, विशेष गरी प्राकृतिक पापग्रह, समयसँगै बढ्दो सकारात्मक परिणामहरू दिन्छन्।"),
    UPACHAYA_TRANSIT_ASSESSMENT("Transit Assessment", "गोचर मूल्याङ्कन"),
    UPACHAYA_TRANSIT_DETAILS("Transit Details", "गोचर विवरण"),
    UPACHAYA_TRANSIT_QUALITY("Transit Quality", "गोचर गुणस्तर"),
    UPACHAYA_TRANSIT_SUBTITLE("Growth House Transit Analysis", "वृद्धि भाव गोचर विश्लेषण"),
    UPACHAYA_TRANSIT_TITLE("Upachaya Transits", "उपचय गोचर"),
    UPACHAYA_UPCOMING("Upcoming Transits", "आगामी गोचरहरू"),
    UPACHAYA_UPCOMING_REC("Prepare for %s related activities", "%s सम्बन्धित गतिविधिहरूको तयारी गर्नुहोस्"),
    UPACHAYA_UPCOMING_SIGNIFICANCE("When %s enters %s - %s activated", "जब %s ले %s मा प्रवेश गर्छ - %s सक्रिय हुन्छ"),
    UPACHAYA_UPCOMING_TRANSITS("Upcoming Transits", "आगामी गोचरहरू")
}
