package com.astro.storm.core.common

enum class StringKeyUIPart2(override val en: String, override val ne: String) : StringKeyInterface {
    UI_IN_HOUSE_FMT("In House %d", "भाव %d मा"),
    UI_JAIMINI_SOURCE("Source: Jaimini Sutras (Chapter 1, Pada 1, Sutras 5-8)", "स्रोत: जैमिनी सूत्र (अध्याय १, पाद १, सूत्र ५-८)"),
    UI_KEMADRUMA_CONDITION_MET("No planets in houses adjacent to Moon - Kemadruma condition met", "चन्द्रमाको छेउका भावहरूमा कुनै ग्रह छैन - केमद्रुम अवस्था पूरा भयो"),
    UI_KEY_CONCEPTS("Key Concepts:", "मुख्य अवधारणाहरू:"),
    UI_KEY_INSIGHTS("Key Insights", "मुख्य अन्तरदृष्टिहरू"),
    UI_LOW("Low", "न्यून"),
    UI_MALEFIC_STRENGTH("Malefic Strength", "अशुभ बल"),
    UI_MIXED_PERIOD("Mixed Period", "मिश्रित अवधि"),
    UI_MODERATE("Moderate", "मध्यम"),
    UI_NAKSHATRAS("nakshatras", "नक्षत्रहरू"),
    UI_NET_STRENGTH_FMT("Net Strength: %s", "कुल बल: %s"),
    UI_NO("No", "होइन"),
    UI_NONE("None", "केही छैन"),
    UI_NO_ACTIVE_SANDHI("No Active Sandhi", "कुनै सक्रिय सन्धि छैन"),
    UI_NO_ACTIVE_VEDHAS("No Active Vedhas", "कुनै सक्रिय वेध छैन"),
    UI_NO_ACTIVE_WAR_REMEDIES("No active wars to remediate", "उपचार गर्न कुनै सक्रिय युद्ध छैन"),
    UI_NO_AI_MODEL("No AI model configured. Please set up an AI provider in settings.", "कुनै AI मोडेल कन्फिगर गरिएको छैन। कृपया सेटिङ्समा AI प्रदायक सेटअप गर्नुहोस्।"),
    UI_NO_ARUDHA_YOGAS("No significant Arudha Yogas found", "कुनै महत्त्वपूर्ण आरुढ योग फेला परेन"),
    UI_NO_ASHTAKAVARGA_DATA("No Ashtakavarga Data", "अष्टकवर्ग डाटा छैन"),
    UI_NO_BIRTH_CHART("No Birth Chart", "कुनै जन्म कुन्डली छैन"),
    UI_NO_CALENDAR_ENTRIES("No calendar entries available.", "कुनै क्यालेन्डर प्रविष्टिहरू उपलब्ध छैनन्।"),
    UI_NO_CHART_DATA("No Chart Data", "कुन्डली डाटा उपलब्ध छैन"),
    UI_NO_PLANET_WARS("No Active Planetary Wars", "कुनै सक्रिय ग्रह युद्ध छैन"),
    UI_NO_REMEDIES_NEEDED("No Remedies Needed", "कुनै उपाय आवश्यक छैन"),
    UI_NO_UPCOMING_SANDHI("No upcoming Sandhi periods in the analysis window.", "विश्लेषण अवधिमा कुनै आगामी सन्धि अवधि छैन।"),
    UI_NO_WAR_DASHA("No War-Related Dasha Effects", "कुनै युद्ध-सम्बन्धित दशा प्रभावहरू छैन"),
    UI_NO_WAR_REMEDIES("No Specific Remedies Needed", "कुनै विशिष्ट उपाय आवश्यक छैन"),
    UI_NO_YOGAS_DISPLAY("No Yogas to Display", "देखाउनको लागि कुनै योग छैन"),
    UI_NO_YOGAS_FORMED("No Yogas Formed", "कुनै योग बनेको छैन"),
    UI_OBSTRUCTIONS_RECEIVED("Obstructions Received", "प्राप्त अवरोधहरू"),
    UI_OVERVIEW("Overview", "अवलोकन"),
    UI_PANCHANGA_UNAVAILABLE("Panchanga Unavailable", "पञ्चाङ्ग उपलब्ध छैन"),
    UI_PRESENT("Present", "उपस्थित"),
    UI_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    UI_RELATIONSHIP_INDICATIONS("Relationship Indications", "सम्बन्ध संकेतहरू"),
    UI_REMEDIES("Remedies", "उपायहरू"),
    UI_RISING_SIGN("Rising Sign", "उदित राशि"),
    UI_SELECT_CHART("Please select a birth chart", "कृपया जन्म कुन्डली चयन गर्नुहोस्"),
    UI_SELECT_CHART_PANCHANGA("Please select a birth chart to view birth Panchanga", "जन्म पञ्चाङ्ग हेर्न कृपया जन्म कुण्डली छान्नुहोस्"),
    UI_SIGNIFICANT_ONLY("Significant only", "महत्त्वपूर्ण मात्र"),
    UI_SORT_BY("Sort by", "क्रमबद्ध गर्नुहोस्"),
    UI_START("Start:", "सुरु:"),
    UI_THROUGHOUT_LIFE("Throughout life", "जीवनभर"),
    UI_TIMING("Timing", "समय"),
    UI_TIMING_GUIDANCE("Timing Guidance", "समय मार्गदर्शन"),
    UI_TRANSITS("Transits", "गोचरहरू"),
    UI_TRANSIT_SUMMARY("Transit Summary", "गोचर सारांश"),
    UI_UNABLE_CALC_PANCHANGA("Unable to calculate Panchanga for today", "आजको पञ्चाङ्ग गणना गर्न असमर्थ"),
    UI_UNFAVORABLE_SIGNS("Unfavorable Signs", "प्रतिकूल राशिहरू"),
    UI_UPCOMING("Upcoming", "आगामी"),
    UI_UPCOMING_TRANSITS("Upcoming Transits", "आगामी गोचरहरू"),
    UI_VERY_HIGH("Very High", "अत्यन्त उच्च"),
    UI_WANING("Waning", "कृष्ण पक्ष"),
    UI_WAXING("Waxing", "शुक्ल पक्ष"),
    UI_YES("Yes", "हो"),
    UI_YOGAS("Yogas", "योगहरू"),
    UI_YOGAS_FOUND_FMT("%1\$d yogas found - %2\$s", "%2\$s मा %1\$d योगहरू फेला परे")
}
