package com.astro.storm.core.common
enum class StringKeyMatchPart1(override val en: String, override val ne: String) : StringKeyInterface {
GUNA_VARNA("Varna", "वर्ण"),
GUNA_VASHYA("Vashya", "वश्य"),
GUNA_TARA("Tara", "तारा"),
GUNA_YONI("Yoni", "योनि"),
GUNA_GRAHA_MAITRI("Graha Maitri", "ग्रह मैत्री"),
GUNA_GANA("Gana", "गण"),
GUNA_BHAKOOT("Bhakoot", "भकूट"),
GUNA_NADI("Nadi", "नाडी"),
GUNA_POINTS("Points", "अंकहरू"),
ACTIVITY_MARRIAGE_NAME("Marriage", "विवाह"),
ACTIVITY_MARRIAGE_DESC("Wedding ceremonies, engagement", "विवाह समारोह, इन्गेज्मेन्ट"),
ACTIVITY_TRAVEL_NAME("Travel", "यात्रा"),
ACTIVITY_TRAVEL_DESC("Long journeys, business trips", "लामो यात्रा, व्यापारिक यात्रा"),
ACTIVITY_BUSINESS_NAME("Business", "व्यापार"),
ACTIVITY_BUSINESS_DESC("Opening shop, new ventures", "पसल खोल्ने, नयाँ उद्यमहरू"),
ACTIVITY_PROPERTY_NAME("Property", "सम्पत्ति"),
ACTIVITY_PROPERTY_DESC("Buying/selling land, house", "जग्गा, घर खरीद/बिक्री"),
ACTIVITY_EDUCATION_NAME("Education", "शिक्षा"),
ACTIVITY_EDUCATION_DESC("Admissions, starting studies", "भर्ना, अध्ययन सुरु"),
ACTIVITY_MEDICAL_NAME("Medical", "चिकित्सा"),
ACTIVITY_MEDICAL_DESC("Surgery, treatment start", "शल्यक्रिया, उपचार सुरु"),
ACTIVITY_VEHICLE_NAME("Vehicle", "सवारी साधन"),
ACTIVITY_VEHICLE_DESC("Buying new vehicle", "नयाँ सवारी साधन खरीद"),
ACTIVITY_SPIRITUAL_NAME("Spiritual", "आध्यात्मिक"),
ACTIVITY_SPIRITUAL_DESC("Initiation, ceremonies", "दीक्षा, समारोहहरू"),
ACTIVITY_GRIHA_PRAVESHA_NAME("Griha Pravesha", "गृह प्रवेश"),
ACTIVITY_GRIHA_PRAVESHA_DESC("House warming", "गृह प्रवेश"),
ACTIVITY_NAMING_NAME("Naming", "न्वारन"),
ACTIVITY_NAMING_DESC("Naming ceremony", "नामकरण समारोह"),
ACTIVITY_GENERAL_NAME("General", "सामान्य"),
ACTIVITY_GENERAL_DESC("General auspicious activities", "सामान्य शुभ गतिविधिहरू"),
VARA_SUNDAY("Sunday", "आइतबार"),
VARA_MONDAY("Monday", "सोमबार"),
VARA_TUESDAY("Tuesday", "मंगलबार"),
VARA_WEDNESDAY("Wednesday", "बुधबार"),
VARA_THURSDAY("Thursday", "बिहिबार"),
VARA_FRIDAY("Friday", "शुक्रबार"),
VARA_SATURDAY("Saturday", "शनिबार"),
CHOGHADIYA_UDVEG("Udveg", "उद्वेग"),
CHOGHADIYA_CHAR("Char", "चर"),
CHOGHADIYA_LABH("Labh", "लाभ"),
CHOGHADIYA_AMRIT("Amrit", "अमृत"),
CHOGHADIYA_KAAL("Kaal", "काल"),
CHOGHADIYA_SHUBH("Shubh", "शुभ"),
CHOGHADIYA_ROG("Rog", "रोग"),
HOUSE_LABEL("House %d", "भाव %d"),
PANCHA_NO_YOGAS("No major Panch Mahapurusha Yogas found.", "कुनै प्रमुख पञ्च महापुरुष योग फेला परेन।"),
PLANETARY_STATUS_EXALTED("Exalted", "उच्च"),
PLANETARY_STATUS_DEBILITATED("Debilitated", "नीच"),
PLANETARY_STATUS_RETROGRADE("Retrograde", "वक्री"),
PLANETARY_STATUS_COMBUST("Combust", "अस्त"),
PLANETARY_STATUS_OWN_SIGN("Own Sign", "स्वराशि"),
PLANETARY_STATUS_MOOLATRIKONA("Moolatrikona", "मूलत्रिकोण"),
PLANETARY_STATUS_FRIENDLY("Friendly", "मित्र"),
PLANETARY_STATUS_ENEMY_SIGN("Enemy Sign", "शत्रु राशि"),
TIME_DAYS("%dd", "%d दिन"),
TIME_WEEKS("%dw", "%d हप्ता"),
TIME_MONTHS("%dm", "%d महिना"),
TIME_YEARS("%dy", "%d वर्ष"),
TIME_IN("in %s", "%s मा"),
BS_DATE_PICKER_TITLE("Select BS Date", "वि.सं. मिति छान्नुहोस्"),
BS_YEAR("Year", "वर्ष"),
BS_MONTH("Month", "महिना"),
BS_DAY("Day", "दिन"),
BS_MONTH_BAISHAKH("Baishakh", "बैशाख"),
BS_MONTH_JESTHA("Jestha", "जेठ"),
BS_MONTH_ASHADH("Ashadh", "असार"),
BS_MONTH_SHRAWAN("Shrawan", "साउन"),
BS_MONTH_BHADRA("Bhadra", "भदौ"),
BS_MONTH_ASHWIN("Ashwin", "असोज"),
BS_MONTH_KARTIK("Kartik", "कार्तिक"),
BS_MONTH_MANGSIR("Mangsir", "मंसिर"),
BS_MONTH_POUSH("Poush", "पुष"),
BS_MONTH_MAGH("Magh", "माघ"),
BS_MONTH_FALGUN("Falgun", "फाल्गुन"),
BS_MONTH_CHAITRA("Chaitra", "चैत्र"),
DAY_SUNDAY("Sunday", "आइतबार"),
DAY_MONDAY("Monday", "सोमबार"),
DAY_TUESDAY("Tuesday", "मंगलबार"),
DAY_WEDNESDAY("Wednesday", "बुधबार"),
DAY_THURSDAY("Thursday", "बिहिबार"),
DAY_FRIDAY("Friday", "शुक्रबार"),
DAY_SATURDAY("Saturday", "शनिबार"),
DAY_ANY("any day", "कुनै पनि दिन"),
MISC_UNAVAILABLE("Unavailable", "उपलब्ध छैन"),
MISC_LOADING("Loading...", "लोड हुँदैछ..."),
MISC_NO_DATA("No data available", "डाटा उपलब्ध छैन"),
MISC_UNKNOWN("Unknown", "अज्ञात"),
MISC_EXPAND("Expand", "विस्तार"),
MISC_COLLAPSE("Collapse", "संकुचन"),
MISC_MORE("More", "थप"),
MISC_LESS("Less", "कम"),
RAJJU_PADA("Pada Rajju", "पाद रज्जु"),
RAJJU_PADA_BODY("Feet", "पाउ"),
RAJJU_KATI("Kati Rajju", "कटि रज्जु"),
RAJJU_KATI_BODY("Waist", "कम्मर"),
RAJJU_NABHI("Nabhi Rajju", "नाभि रज्जु"),
RAJJU_NABHI_BODY("Navel", "नाभि"),
RAJJU_KANTHA("Kantha Rajju", "कण्ठ रज्जु"),
RAJJU_KANTHA_BODY("Neck", "घाँटी"),
RAJJU_SIRO("Siro Rajju", "शिरो रज्जु"),
RAJJU_SIRO_BODY("Head", "शिर"),
RAJJU_SIRO_WARNING("Most serious - affects longevity of spouse", "सबैभन्दा गम्भीर - जीवनसाथीको आयुमा असर पार्छ"),
RAJJU_KANTHA_WARNING("May cause health issues to both", "दुवैलाई स्वास्थ्य समस्या हुन सक्छ"),
RAJJU_NABHI_WARNING("May affect children", "सन्तानमा असर पर्न सक्छ"),
RAJJU_KATI_WARNING("May cause financial difficulties", "आर्थिक कठिनाइहरू हुन सक्छ"),
RAJJU_PADA_WARNING("May cause wandering tendencies", "भ्रमण प्रवृत्ति हुन सक्छ"),
FROM_LAGNA("from Lagna", "लग्नबाट"),
FROM_MOON("from Moon", "चन्द्रबाट"),
FROM_VENUS("from Venus", "शुक्रबाट"),
    TARA_JANMA("Janma (Birth)", "Janma (Birth)"),
    TARA_SAMPAT("Sampat (Wealth)", "Sampat (Wealth)"),
    TARA_VIPAT("Vipat (Danger)", "Vipat (Danger)"),
    TARA_KSHEMA("Kshema (Wellbeing)", "Kshema (Wellbeing)"),
    TARA_PRATYARI("Pratyari (Obstacle)", "Pratyari (Obstacle)"),
    TARA_SADHANA("Sadhana (Achievement)", "Sadhana (Achievement)"),
    TARA_VADHA("Vadha (Death)", "Vadha (Death)"),
    TARA_MITRA("Mitra (Friend)", "Mitra (Friend)"),
    TARA_PARAMA_MITRA("Parama Mitra (Best Friend)", "Parama Mitra (Best Friend)"),
TARA_DESC("Destiny and birth star compatibility", "भाग्य र जन्म तारा अनुकूलता"),
TARA_EXCELLENT("Both have auspicious Taras - excellent destiny compatibility. Harmonious life path.", "दुवैको शुभ तारा छ - उत्कृष्ट भाग्य अनुकूलता। सामञ्जस्यपूर्ण जीवन मार्ग।"),
TARA_MODERATE("One auspicious Tara present - moderate destiny compatibility.", "एउटा शुभ तारा उपस्थित - मध्यम भाग्य अनुकूलता।"),
TARA_INAUSPICIOUS("Both Taras are inauspicious - may face obstacles together. Remedies recommended.", "दुवै तारा अशुभ - सँगै अवरोधहरू सामना गर्न सक्छन्। उपायहरू सिफारिस गरिएको।"),
GRAHA_MAITRI_DESC("Mental compatibility and friendship", "मानसिक अनुकूलता र मित्रता"),
GRAHA_MAITRI_EXCELLENT("Same lord or mutual friends - excellent mental compatibility. Natural understanding.", "उही स्वामी वा पारस्परिक मित्र - उत्कृष्ट मानसिक अनुकूलता। प्राकृतिक बुझाइ।"),
GRAHA_MAITRI_VERY_GOOD("One friend, one neutral - very good mental harmony. Good communication.", "एउटा मित्र, एउटा तटस्थ - धेरै राम्रो मानसिक सामञ्जस्य। राम्रो सञ्चार।"),
GRAHA_MAITRI_AVERAGE("Neutral relationship - average mental compatibility. Requires effort for understanding.", "तटस्थ सम्बन्ध - औसत मानसिक अनुकूलता। बुझाइको लागि प्रयास आवश्यक।"),
GRAHA_MAITRI_FRICTION("One enemy present - some mental friction. Different thought processes.", "एउटा शत्रु उपस्थित - केही मानसिक घर्षण। फरक विचार प्रक्रियाहरू।"),
GRAHA_MAITRI_INCOMPATIBLE("Mutual enemies - significant mental incompatibility. May face frequent misunderstandings.", "पारस्परिक शत्रु - महत्त्वपूर्ण मानसिक असंगतता। बारम्बार गलतफहमीहरू हुन सक्छ।"),
BHAKOOT_DESC("Love, health, and financial compatibility", "प्रेम, स्वास्थ्य र आर्थिक अनुकूलता"),
BHAKOOT_NO_DOSHA("No Bhakoot dosha - excellent compatibility for love, health, and finances.", "भकुट दोष छैन - प्रेम, स्वास्थ्य र वित्तको लागि उत्कृष्ट अनुकूलता।"),
BHAKOOT_CANCELLED("Bhakoot dosha cancelled by same sign lord - no adverse effects.", "उही राशि स्वामीद्वारा भकुट दोष रद्द - कुनै प्रतिकूल प्रभाव छैन।"),
    BHAKOOT_2_12("Dhan-Vyaya (2-12)", "Dhan-Vyaya (2-12)"),
BHAKOOT_2_12_DESC("May cause financial fluctuations and differences in spending habits.", "आर्थिक उतार-चढाव र खर्च बानीमा भिन्नता हुन सक्छ।"),
    BHAKOOT_6_8("Shadashtak (6-8)", "Shadashtak (6-8)"),
BHAKOOT_6_8_DESC("May affect health and cause separation tendencies. Most serious Bhakoot dosha.", "स्वास्थ्यमा असर पार्न र विच्छेद प्रवृत्ति हुन सक्छ। सबैभन्दा गम्भीर भकुट दोष।"),
    BHAKOOT_5_9("Signs are in 5-9 (Trine)", "Signs are in 5-9 (Trine)"),
BHAKOOT_5_9_DESC("Trine relationship is auspicious for progeny, dharma, and spiritual growth.", "त्रिकोण सम्बन्ध सन्तान, धर्म र आध्यात्मिक विकासको लागि शुभ छ।"),
BHAKOOT_FAVORABLE("Signs are in favorable positions for marital harmony.", "राशिहरू वैवाहिक सामञ्जस्यको लागि अनुकूल स्थानमा छन्।"),
    BHAKOOT_CANCEL_SAME_LORD("Same lord ({lord})", "Same lord ({lord})"),
    BHAKOOT_CANCEL_MUTUAL_FRIENDS("Moon sign lords ({lord1} & {lord2})", "Moon sign lords ({lord1} & {lord2})"),
BHAKOOT_CANCEL_EXALTATION("Lord is exalted in partner's sign - Partial Cancellation", "स्वामी साथीको राशिमा उच्च छ - आंशिक रद्द"),
BHAKOOT_CANCEL_FRIENDLY("Moon sign lords have friendly disposition - Partial Cancellation", "चन्द्र राशि स्वामीहरूको मैत्रीपूर्ण स्वभाव छ - आंशिक रद्द"),
    BHAKOOT_CANCEL_ELEMENT("Both Moon signs share same element ({element})", "Both Moon signs share same element ({element})"),
DASHA_LEVEL_MAHADASHA("Mahadasha", "महादशा"),
DASHA_LEVEL_ANTARDASHA("Antardasha", "अन्तर्दशा"),
DASHA_LEVEL_PRATYANTARDASHA("Pratyantardasha", "प्रत्यन्तर्दशा"),
DASHA_LEVEL_SOOKSHMADASHA("Sookshmadasha", "सूक्ष्मदशा"),
DASHA_LEVEL_PRANADASHA("Pranadasha", "प्राणदशा"),
DASHA_LEVEL_DEHADASHA("Dehadasha", "देहदशा"),
DASHA_CURRENT_DASHA_PERIOD("Current Dasha Period", "हालको दशा अवधि"),
DASHA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
DASHA_LORD("Lord", "स्वामी"),
DASHA_PADA("Pada", "पाद"),
DASHA_PERIOD_INSIGHTS("Period Insights", "अवधि अन्तर्दृष्टि"),
DASHA_SANDHI_ALERTS("Dasha Sandhi Alerts", "दशा सन्धि अलर्टहरू"),
    DASHA_UPCOMING_TRANSITIONS("%1\$d upcoming transition(s)", "%1\$d upcoming transition(s)"),
DASHA_TRANSITION("transition", "सन्क्रमण"),
DASHA_SANDHI_EXPLANATION("Sandhi periods mark transitions between planetary periods. These are sensitive times requiring careful attention as the energy shifts from one planet to another.", "सन्धि अवधिहरूले ग्रह अवधिहरूबीचको सन्क्रमण चिन्ह लगाउँछन्। यी संवेदनशील समयहरू हुन् जहाँ एउटा ग्रहबाट अर्को ग्रहमा ऊर्जा परिवर्तन हुन्छ।"),
DASHA_ACTIVE_NOW("Active Now", "अहिले सक्रिय"),
DASHA_TODAY("Today", "आज"),
DASHA_TOMORROW("Tomorrow", "भोलि"),
DASHA_IN_DAYS("In %d days", "%d दिनमा"),
DASHA_TIMELINE("Dasha Timeline", "दशा समयरेखा"),
DASHA_COMPLETE_CYCLE("Complete 120-year Vimshottari cycle", "पूर्ण १२०-वर्षे विम्शोत्तरी चक्र"),
DASHA_SUB_PERIODS("%d sub-periods", "%d उप-अवधिहरू"),
DASHA_ANTARDASHAS("Antardashas", "अन्तर्दशाहरू"),
DASHA_UNABLE_CALCULATE("Unable to calculate current dasha period", "हालको दशा अवधि गणना गर्न असक्षम"),
DASHA_ABOUT_VIMSHOTTARI("About Vimshottari Dasha", "विम्शोत्तरी दशाको बारेमा"),
    DASHA_VIMSHOTTARI_DESC("The Vimshottari Dasha is the most widely used planetary period system in Vedic astrology (Jyotish)", "The Vimshottari Dasha is the most widely used planetary period system in Vedic astrology (Jyotish)"),
    DASHA_PERIODS_SEQUENCE("Dasha Periods (Vimshottari Sequence)", "Dasha Periods (Vimshottari Sequence)"),
DASHA_TOTAL_CYCLE("Total Cycle: 120 Years", "कुल चक्र: १२० वर्ष"),
DASHA_HIERARCHY("Dasha Hierarchy", "दशा पदानुक्रम"),
    DASHA_MAJOR_PERIOD_YEARS("Major period (years)", "Major period (years)"),
    DASHA_SUB_PERIOD_MONTHS("Sub-period (months)", "Sub-period (months)"),
    DASHA_SUB_SUB_PERIOD_WEEKS("Sub-sub-period (weeks)", "Sub-sub-period (weeks)"),
    DASHA_SUBTLE_PERIOD_DAYS("Subtle period (days)", "Subtle period (days)"),
    DASHA_BREATH_PERIOD_HOURS("Breath period (hours)", "Breath period (hours)"),
    DASHA_BODY_PERIOD_MINUTES("Body period (minutes)", "Body period (minutes)"),
    DASHA_SANDHI_NOTE("Dasha Sandhi (junction periods)", "Dasha Sandhi (junction periods)"),
DASHA_PERCENT_COMPLETE("%s%% complete", "%s%% पूरा"),
DASHA_YEARS_ABBR("yrs", "वर्ष"),
DASHA_COLLAPSE("Collapse", "संकुचन गर्नुहोस्"),
DASHA_EXPAND("Expand", "विस्तार गर्नुहोस्"),
ASPECT_CONJUNCTION("Conjunction", "युति"),
ASPECT_NATURE_HARMONIOUS("Harmonious", "सामञ्जस्यपूर्ण"),
ASPECT_NATURE_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
ASPECT_NATURE_VARIABLE("Variable", "परिवर्तनशील"),
ASPECT_NATURE_SIGNIFICANT("Significant", "महत्त्वपूर्ण"),
DIR_EAST("East", "पूर्व"),
DIR_WEST("West", "पश्चिम"),
DIR_NORTH("North", "उत्तर"),
DIR_SOUTH("South", "दक्षिण"),
DIR_NORTH_EAST("North-East", "उत्तर-पूर्व"),
DIR_NORTH_WEST("North-West", "उत्तर-पश्चिम"),
DIR_SOUTH_EAST("South-East", "दक्षिण-पूर्व"),
DIR_SOUTH_WEST("South-West", "दक्षिण-पश्चिम"),
ELEMENT_FIRE("Fire", "अग्नि"),
ELEMENT_EARTH("Earth", "पृथ्वी"),
ELEMENT_AIR("Air", "वायु"),
ELEMENT_WATER("Water", "जल"),
RELATION_FRIEND("Friend", "मित्र"),
RELATION_ENEMY("Enemy", "शत्रु"),
RELATION_NEUTRAL("Neutral", "तटस्थ"),
RELATION_MUTUAL_FRIENDS("Mutual Friends", "पारस्परिक मित्र"),
RELATION_MUTUAL_ENEMIES("Mutual Enemies", "पारस्परिक शत्रु"),
RELATION_ONE_FRIENDLY("One Friendly", "एक मैत्रीपूर्ण"),
RELATION_ONE_INIMICAL("One Inimical", "एक शत्रुतापूर्ण"),
    HOUSE_DHARMA("Dharma (1, 5, 9)", "Dharma (1, 5, 9)"),
    HOUSE_ARTHA("Artha (2, 6, 10)", "Artha (2, 6, 10)"),
    HOUSE_KAMA("Kama (3, 7, 11)", "Kama (3, 7, 11)"),
    HOUSE_MOKSHA("Moksha (4, 8, 12)", "Moksha (4, 8, 12)"),
    RAJJU_ASCENDING("Aarohana (Ascending)", "Aarohana (Ascending)"),
    RAJJU_DESCENDING("Avarohana (Descending)", "Avarohana (Descending)"),
MAHENDRA_FAVORABLE("Mahendra favorable at position {count} - promotes longevity and progeny", "महेन्द्र स्थिति {count} मा अनुकूल - दीर्घायु र सन्तान प्रवर्धन गर्छ"),
MAHENDRA_NOT_APPLICABLE("Mahendra position not in favorable sequence", "महेन्द्र स्थिति अनुकूल क्रममा छैन"),
    VEDHA_PRESENT("Vedha (obstruction)", "Vedha (obstruction)"),
VEDHA_NOT_PRESENT("No Vedha between the nakshatras - favorable", "नक्षत्रहरू बीच वेध छैन - अनुकूल"),
RAJJU_COMPATIBLE("Different Rajju types - compatible, no concerns related to body part compatibility", "फरक रज्जु प्रकार - अनुकूल, शरीर भाग अनुकूलतासम्बन्धी कुनै चिन्ता छैन"),
    RAJJU_SAME_DIFF_ARUDHA("Same {rajju} but different Arudha ({arudha1} vs {arudha2})", "Same {rajju} but different Arudha ({arudha1} vs {arudha2})"),
    RAJJU_SAME_SAME_ARUDHA("Same {rajju} ({body})", "Same {rajju} ({body})"),
SPECIAL_NADI_DOSHA("NADI DOSHA: Same Nadi can affect health and progeny. Consider remedies before proceeding.", "नाडी दोष: उही नाडीले स्वास्थ्य र सन्तानमा असर पार्न सक्छ। अगाडि बढ्नु अघि उपायहरू विचार गर्नुहोस्।"),
SPECIAL_BHAKOOT_DOSHA("BHAKOOT DOSHA present: {analysis}. May affect love, finances, or health.", "भकुट दोष उपस्थित: {analysis}। प्रेम, वित्त, वा स्वास्थ्यमा असर पर्न सक्छ।"),
SPECIAL_BRIDE_MANGLIK("MANGLIK IMBALANCE: Bride has {dosha} while Groom is non-Manglik. Kumbh Vivah or remedies strongly advised.", "मांगलिक असन्तुलन: दुलहीमा {dosha} छ जबकि दुलाहा गैर-मांगलिक छन्। कुम्भ विवाह वा उपायहरू दृढतापूर्वक सल्लाह दिइएको।"),
SPECIAL_GROOM_MANGLIK("MANGLIK IMBALANCE: Groom has {dosha} while Bride is non-Manglik. Remedies strongly recommended.", "मांगलिक असन्तुलन: दुलाहामा {dosha} छ जबकि दुलही गैर-मांगलिक छिन्। उपायहरू दृढतापूर्वक सिफारिस गरिएको।"),
    SPECIAL_GANA_INCOMPAT("GANA INCOMPATIBILITY: Opposite temperaments (Deva-Rakshasa)", "GANA INCOMPATIBILITY: Opposite temperaments (Deva-Rakshasa)"),
SPECIAL_YONI_INCOMPAT("YONI INCOMPATIBILITY: Enemy Yonis present. Physical and instinctual harmony may require extra effort.", "योनि असंगतता: शत्रु योनि उपस्थित। शारीरिक र सहज सामञ्जस्यको लागि अतिरिक्त प्रयास आवश्यक पर्न सक्छ।"),
SPECIAL_VEDHA("VEDHA PRESENT: {details}. Nakshatra obstruction may cause challenges in specific life areas.", "वेध उपस्थित: {details}। नक्षत्र बाधाले जीवनका विशेष क्षेत्रहरूमा चुनौतीहरू ल्याउन सक्छ।"),
SPECIAL_RAJJU("RAJJU DOSHA: {details}. Related body part may face health concerns in marriage.", "रज्जु दोष: {details}। सम्बन्धित शरीर भागमा विवाहमा स्वास्थ्य चिन्ता हुन सक्छ।"),
    SPECIAL_STREE_DEERGHA("STREE DEERGHA not satisfied: Nakshatra difference is {diff} (requires 13+)", "STREE DEERGHA not satisfied: Nakshatra difference is {diff} (requires 13+)"),
SPECIAL_MULTIPLE_LOW("MULTIPLE CONCERNS: {count} Gunas scored below threshold. Overall compatibility requires attention.", "बहु चिन्ताहरू: {count} गुणले न्यूनतम भन्दा कम अंक पाए। समग्र अनुकूलतामा ध्यान आवश्यक।"),
SPECIAL_7TH_LORDS_ENEMY("7TH HOUSE LORDS INCOMPATIBLE: {lord1} and {lord2} are mutual enemies. Marriage house lords in conflict.", "७औं भाव स्वामी असंगत: {lord1} र {lord2} पारस्परिक शत्रु हुन्। विवाह भाव स्वामीहरू द्वन्द्वमा।"),
SPECIAL_NO_ISSUES("No significant special concerns noted. The match appears harmonious across additional factors.", "कुनै महत्त्वपूर्ण विशेष चिन्ता छैन। मिलान अतिरिक्त कारकहरूमा सामञ्जस्यपूर्ण देखिन्छ।"),
SUMMARY_TITLE("KUNDLI MILAN SUMMARY", "कुण्डली मिलान सारांश"),
SUMMARY_OVERALL_SCORE("Overall Score", "समग्र अंक"),
SUMMARY_RATING("Rating", "मूल्यांकन"),
SUMMARY_STRENGTHS("Strengths", "शक्तिहरू"),
SUMMARY_CONCERNS("Areas of Concern", "चिन्ताका क्षेत्रहरू"),
SUMMARY_MANGLIK("Manglik Status", "मांगलिक स्थिति"),
SUMMARY_ADDITIONAL("Additional Factors", "अतिरिक्त कारकहरू"),
SUMMARY_RECOMMENDATION("Recommendation", "सिफारिस"),
DETAILED_TITLE("DETAILED MATCHMAKING ANALYSIS", "विस्तृत मिलान विश्लेषण"),
BIRTH_DATA_SUMMARY("Birth Data Summary", "जन्म डाटा सारांश"),
MOON_SIGN("Moon Sign", "चन्द्र राशि"),
PADA_LABEL("Pada", "पाद"),
MOON_LONGITUDE("Moon Longitude", "चन्द्र देशान्तर"),
PURPOSE("Purpose", "उद्देश्य"),
ANALYSIS_LABEL("Analysis", "विश्लेषण"),
ADDITIONAL_FACTORS_TITLE("Additional Compatibility Factors", "अतिरिक्त अनुकूलता कारकहरू"),
OBSTRUCTION("Obstruction", "बाधा"),
COSMIC_BOND("Cosmic Bond", "ब्रह्माण्डीय बन्धन"),
WARNING_LABEL("Warning", "चेतावनी"),
WIFE_PROSPERITY("Wife's Prosperity", "पत्नीको समृद्धि"),
SATISFIED("Satisfied", "सन्तुष्ट"),
NOT_SATISFIED("Not Satisfied", "सन्तुष्ट छैन"),
LONGEVITY_PROSPERITY("Longevity & Prosperity", "दीर्घायु र समृद्धि"),
NOT_APPLICABLE("Not Applicable", "लागू हुँदैन"),
BRIDE("Bride", "दुलही"),
GROOM("Groom", "दुलाहा"),
STATUS("Status", "स्थिति"),
COMPATIBLE("Compatible", "अनुकूल"),
NEEDS_ATTENTION("Needs Attention", "ध्यान आवश्यक"),
PRESENT("Present", "उपस्थित"),
NOT_PRESENT("Not Present", "उपस्थित छैन"),
FAVORABLE("Favorable", "अनुकूल"),
SAME_RAJJU("Same Rajju", "उही रज्जु"),
DETAILS("Details", "विवरण"),
GUNA_DESC_VARNA("Varna indicates spiritual compatibility based on the Moon sign's element. It measures ego harmony and how partners relate on a spiritual level. Higher compatibility suggests natural understanding of values.", "वर्णले चन्द्र राशिको तत्वमा आधारित आध्यात्मिक अनुकूलता संकेत गर्दछ। यसले अहंकार सामञ्जस्य र साझेदारहरू आध्यात्मिक स्तरमा कसरी सम्बन्धित छन् मापन गर्दछ।"),
GUNA_DESC_VASHYA("Vashya measures the mutual attraction and influence between partners. It indicates who can influence whom and the power dynamics in the relationship.", "वश्यले साझेदारहरू बीचको पारस्परिक आकर्षण र प्रभाव मापन गर्दछ। यसले कसले कसलाई प्रभाव पार्न सक्छ र सम्बन्धमा शक्ति गतिशीलता संकेत गर्दछ।"),
    GUNA_DESC_TARA("Tara analyzes destiny compatibility through the birth stars (Nakshatras)", "Tara analyzes destiny compatibility through the birth stars (Nakshatras)"),
GUNA_DESC_YONI("Yoni represents physical and sexual compatibility based on the animal nature assigned to each Nakshatra. Same or friendly animals indicate better physical harmony.", "योनीले प्रत्येक नक्षत्रलाई तोकिएको पशु प्रकृतिमा आधारित शारीरिक र यौन अनुकूलता प्रतिनिधित्व गर्दछ। उही वा मित्र पशुहरूले राम्रो शारीरिक सामञ्जस्य संकेत गर्दछ।"),
GUNA_DESC_GRAHA_MAITRI("Graha Maitri analyzes mental compatibility through the friendship of Moon sign lords. It indicates how well the couple can understand each other intellectually.", "ग्रह मैत्रीले चन्द्र राशि स्वामीहरूको मित्रता मार्फत मानसिक अनुकूलता विश्लेषण गर्दछ। यसले जोडीले बौद्धिक रूपमा एकअर्कालाई कत्तिको राम्रोसँग बुझ्न सक्छ संकेत गर्दछ।"),
    GUNA_DESC_GANA("Gana measures temperament compatibility through Deva (divine)", "Gana measures temperament compatibility through Deva (divine)"),
GUNA_DESC_BHAKOOT("Bhakoot indicates love, health, and financial compatibility based on the Moon sign positions. It's crucial for long-term marital harmony.", "भकुटले चन्द्र राशि स्थितिहरूमा आधारित प्रेम, स्वास्थ्य र आर्थिक अनुकूलता संकेत गर्दछ। यो दीर्घकालीन वैवाहिक सामञ्जस्यको लागि महत्त्वपूर्ण छ।"),
    GUNA_DESC_NADI("Nadi is the most important factor (8 points)", "Nadi is the most important factor (8 points)"),
GUNA_DESC_NOT_AVAILABLE("Detailed description not available for this Guna.", "यस गुणको विस्तृत विवरण उपलब्ध छैन।"),
TARA_REMEDY_LOW("Remedy: Perform Nakshatra Shanti puja for both birth stars. Donate black sesame, iron, and blue cloth on Saturdays. Chant Maha Mrityunjaya Mantra 108 times daily for 40 days to neutralize destiny obstacles.", "उपाय: दुवै जन्म नक्षत्रको लागि नक्षत्र शान्ति पूजा गर्नुहोस्। शनिबारमा कालो तिल, फलाम र नीलो कपडा दान गर्नुहोस्। भाग्य बाधाहरू निष्क्रिय गर्न ४० दिन दैनिक १०८ पटक महा मृत्युञ्जय मन्त्र जाप गर्नुहोस्।"),
GRAHA_MAITRI_REMEDY_LOW("Remedy: Meditate together daily for at least 15 minutes. Practice active listening and clear communication. Strengthen Mercury by chanting Budh mantra on Wednesdays, donating green items, and wearing emerald after consultation.", "उपाय: दैनिक कम्तिमा १५ मिनेट सँगै ध्यान गर्नुहोस्। सक्रिय सुनाइ र स्पष्ट सञ्चार अभ्यास गर्नुहोस्। बुधबारमा बुध मन्त्र जाप गरेर, हरियो वस्तुहरू दान गरेर र परामर्श पछि पन्ना लगाएर बुधलाई बलियो बनाउनुहोस्।"),
BHAKOOT_REMEDY_LOW("Remedy: Perform Graha Shanti puja for Moon sign lords of both partners. Chant Vishnu Sahasranama on Thursdays for 21 weeks. Donate white items, rice, and silver on Mondays. Financial planning together is essential.", "उपाय: दुवै साझेदारको चन्द्र राशि स्वामीको ग्रह शान्ति पूजा गर्नुहोस्। २१ हप्ता बिहीबारमा विष्णु सहस्रनाम जाप गर्नुहोस्। सोमबारमा सेता वस्तुहरू, चामल र चाँदी दान गर्नुहोस्। सँगै वित्तीय योजना आवश्यक छ।"),
TARA_IMPORTANCE("Tara analyzes birth star compatibility to determine destiny harmony. It predicts how well the couple's life paths align and support each other.", "तारा भाग्य सामञ्जस्य निर्धारण गर्न जन्म तारा अनुकूलता विश्लेषण गर्दछ। यसले जोडीको जीवन मार्गहरू कत्तिको राम्रोसँग मिल्छन् र एकअर्कालाई समर्थन गर्छन् भनेर भविष्यवाणी गर्दछ।"),
TARA_CATEGORIES_EXPLAINED("Nakshatras are grouped in sets of 9 from each person's birth star. Janma, Vipat, and Vadha taras are inauspicious; Sampat, Kshema, Sadhana, and Mitra taras are auspicious.", "नक्षत्रहरू प्रत्येक व्यक्तिको जन्म ताराबाट ९ को सेटमा समूहीकृत गरिन्छ। जन्म, विपत् र वध तारा अशुभ हुन्; सम्पत्, क्षेम, साधना र मित्र तारा शुभ हुन्।"),
GRAHA_MAITRI_IMPORTANCE("Graha Maitri examines mental compatibility through planetary friendship of Moon sign lords. It indicates intellectual rapport and communication ease.", "ग्रह मैत्रीले चन्द्र राशि स्वामीहरूको ग्रह मित्रताद्वारा मानसिक अनुकूलता जाँच गर्दछ। यसले बौद्धिक सम्बन्ध र सञ्चार सहजता संकेत गर्दछ।"),
GRAHA_MAITRI_LEVELS("Same lord/Friends = 5 points. One friend + one neutral = 4 points. Both neutral = 3 points. One enemy = 1-2 points. Both enemies = 0.5 points.", "उही स्वामी/मित्र = ५ अंक। एक मित्र + एक तटस्थ = ४ अंक। दुवै तटस्थ = ३ अंक। एक शत्रु = १-२ अंक। दुवै शत्रु = ०.५ अंक।"),
BHAKOOT_IMPORTANCE("Bhakoot assesses emotional love, family welfare, and financial prosperity. It's based on sign positions and is crucial for long-term happiness.", "भकुटले भावनात्मक प्रेम, पारिवारिक कल्याण र आर्थिक समृद्धि मूल्याङ्कन गर्दछ। यो राशि स्थितिहरूमा आधारित छ र दीर्घकालीन खुशीको लागि महत्त्वपूर्ण छ।"),
    BHAKOOT_DOSHA_TYPES("No dosha = 7 points. 2-12 position (Dhan-Vyaya dosha)", "No dosha = 7 points. 2-12 position (Dhan-Vyaya dosha)"),
SCORE_EXCELLENT("Excellent match! Score above 28 indicates highly favorable compatibility across all dimensions.", "उत्कृष्ट मिलान! २८ माथिको अंकले सबै आयामहरूमा अत्यन्त अनुकूल अनुकूलता संकेत गर्दछ।"),
SCORE_EXCELLENT_GUIDANCE("Your compatibility across spiritual, mental, physical, and temperamental dimensions is outstanding. You share compatible values, communication styles, and life goals. This union has the blessings of celestial alignments. Focus on maintaining open communication and mutual respect to nurture this harmonious connection throughout your married life.", "तपाईंको आध्यात्मिक, मानसिक, शारीरिक र स्वभावगत आयामहरूमा अनुकूलता उत्कृष्ट छ। तपाईं अनुकूल मूल्यहरू, सञ्चार शैली र जीवन लक्ष्यहरू साझा गर्नुहुन्छ। यस संघमा आकाशीय संरेखणको आशीर्वाद छ। आफ्नो वैवाहिक जीवनभर यो सामञ्जस्यपूर्ण सम्बन्धलाई पोषण गर्न खुला सञ्चार र पारस्परिक सम्मान कायम राख्नमा ध्यान दिनुहोस्।"),
SCORE_GOOD("Good match. Score of 21-27 suggests strong compatibility with minor areas to work on.", "राम्रो मिलान। २१-२७ को अंकले काम गर्नुपर्ने सानातिना क्षेत्रहरूसहित बलियो अनुकूलता सुझाव दिन्छ।"),
SCORE_GOOD_GUIDANCE("You have strong overall compatibility with good harmony in most areas. While there are some minor differences, these can be easily managed through mutual understanding and effort. The relationship has solid foundations for a successful marriage. Focus on conscious communication, especially in areas where gunas scored lower. Regular discussions about expectations and compromise will strengthen your bond.", "तपाईं धेरै क्षेत्रहरूमा राम्रो सामञ्जस्यसहित बलियो समग्र अनुकूलता राख्नुहुन्छ। यद्यपि केही सानातिना भिन्नताहरू छन्, यी पारस्परिक बुझाइ र प्रयासद्वारा सजिलैसँग व्यवस्थापन गर्न सकिन्छ। सम्बन्धमा सफल विवाहको लागि ठोस आधारहरू छन्। सचेत सञ्चारमा ध्यान दिनुहोस्, विशेष गरी ती क्षेत्रहरूमा जहाँ गुणहरूले कम अंक पाएको छ। अपेक्षाहरू र सम्झौताको बारेमा नियमित छलफलले तपाईंको बन्धनलाई बलियो बनाउनेछ।"),
SCORE_AVERAGE("Average compatibility. Score of 18-20 requires attention to problem areas and remedies.", "औसत अनुकूलता। १८-२० को अंकले समस्या क्षेत्रहरू र उपायहरूमा ध्यान आवश्यक पर्छ।"),
    SCORE_AVERAGE_GUIDANCE("Your compatibility is moderate with several areas requiring conscious effort and adjustment. While the match is acceptable, success depends on both partners' willingness to work through differences. Identify specific problem areas (especially low-scoring gunas)", "Your compatibility is moderate with several areas requiring conscious effort and adjustment. While the match is acceptable, success depends on both partners' willingness to work through differences. Identify specific problem areas (especially low-scoring gunas)"),
SCORE_BELOW_AVERAGE("Below average compatibility. Score of 14-17 indicates significant challenges requiring serious consideration.", "औसतमुनि अनुकूलता। १४-१७ को अंकले गम्भीर विचार आवश्यक पर्ने महत्त्वपूर्ण चुनौतीहरू संकेत गर्दछ।"),
SCORE_BELOW_AVERAGE_GUIDANCE("Your compatibility score indicates notable challenges across multiple dimensions. This match faces significant obstacles that require serious consideration before proceeding. Multiple gunas showing low scores suggest fundamental differences in temperament, values, or life approaches. Extensive Vedic remedies are essential - consult a qualified Vedic astrologer for a comprehensive remedy plan. Professional couples counseling is strongly recommended. Both partners must be willing to make substantial adjustments and compromises. Carefully evaluate whether both are prepared for the level of conscious effort required to build a harmonious relationship.", "तपाईंको अनुकूलता अंकले विभिन्न आयामहरूमा उल्लेखनीय चुनौतीहरू संकेत गर्दछ। यो मिलानले अगाडि बढ्नु अघि गम्भीर विचार आवश्यक पर्ने महत्त्वपूर्ण बाधाहरूको सामना गर्दछ। धेरै गुणहरूले कम अंक देखाउनुले स्वभाव, मूल्यहरू वा जीवन दृष्टिकोणमा आधारभूत भिन्नताहरू सुझाव दिन्छ। व्यापक वैदिक उपायहरू आवश्यक छन् - व्यापक उपाय योजनाको लागि योग्य वैदिक ज्योतिषीसँग परामर्श गर्नुहोस्। पेशेवर जोडी परामर्श दृढतापूर्वक सिफारिस गरिएको छ। दुवै साझेदारहरू पर्याप्त समायोजन र सम्झौता गर्न इच्छुक हुनुपर्छ। सामञ्जस्यपूर्ण सम्बन्ध निर्माण गर्न आवश्यक सचेत प्रयासको स्तरको लागि दुवै तयार छन् कि छैनन् भनेर सावधानीपूर्वक मूल्याङ्कन गर्नुहोस्।"),
SCORE_POOR("Poor compatibility. Score below 14 suggests major challenges. Marriage not recommended without extensive remedies.", "कमजोर अनुकूलता। १४ मुनिको अंकले प्रमुख चुनौतीहरू सुझाव दिन्छ। व्यापक उपायहरू बिना विवाह सिफारिस गरिएको छैन।"),
    SCORE_POOR_GUIDANCE("This match shows poor compatibility with fundamental incompatibilities across critical areas. Traditional Vedic astrology does not recommend proceeding with this marriage without addressing severe issues. The low score suggests conflicts in temperament, values, physical harmony, and mental compatibility. If you choose to proceed despite this assessment, the following are absolutely essential: 1)", "This match shows poor compatibility with fundamental incompatibilities across critical areas. Traditional Vedic astrology does not recommend proceeding with this marriage without addressing severe issues. The low score suggests conflicts in temperament, values, physical harmony, and mental compatibility. If you choose to proceed despite this assessment, the following are absolutely essential: 1)"),
BHAKOOT_CANCEL_EXPLANATION("Bhakoot Dosha cancellation occurs when deeper planetary relationships indicate harmony. Even though Moon signs are in challenging positions, the underlying planetary friendships or same lords can neutralize the dosha effects.", "भकुट दोष रद्द गहन ग्रह सम्बन्धहरूले सामञ्जस्य संकेत गर्दा हुन्छ। यद्यपि चन्द्र राशिहरू चुनौतीपूर्ण स्थानमा छन्, अन्तर्निहित ग्रह मित्रता वा उही स्वामीहरूले दोष प्रभावहरू निष्क्रिय पार्न सक्छन्।"),
PLANETARY_STRENGTH_VERY_STRONG("Very Strong", "धेरै बलियो"),
PLANETARY_STRENGTH_STRONG("Strong", "बलियो"),
PLANETARY_STRENGTH_MODERATE("Moderate", "मध्यम"),
PLANETARY_STRENGTH_WEAK("Weak", "कमजोर"),
PLANETARY_STRENGTH_VERY_WEAK("Very Weak", "धेरै कमजोर"),
PLANETARY_STRENGTH_AFFLICTED("Afflicted", "पीडित"),
HOUSE_1_SIGNIFICATION("self-effort and personality", "आत्म-प्रयास र व्यक्तित्व"),
HOUSE_2_SIGNIFICATION("family wealth and speech", "पारिवारिक धन र वाणी"),
HOUSE_3_SIGNIFICATION("courage and communication", "साहस र सञ्चार"),
HOUSE_4_SIGNIFICATION("property and domestic comfort", "सम्पत्ति र घरेलु सुविधा"),
HOUSE_5_SIGNIFICATION("speculation and creative ventures", "अनुमान र सिर्जनात्मक उद्यमहरू"),
HOUSE_6_SIGNIFICATION("service and defeating competition", "सेवा र प्रतिस्पर्धा जित्नु"),
HOUSE_7_SIGNIFICATION("partnership and business", "साझेदारी र व्यापार"),
HOUSE_8_SIGNIFICATION("inheritance and unexpected gains", "विरासत र अप्रत्याशित लाभ"),
HOUSE_9_SIGNIFICATION("fortune and higher pursuits", "भाग्य र उच्च खोजीहरू"),
HOUSE_10_SIGNIFICATION("career and public recognition", "क्यारियर र सार्वजनिक मान्यता"),
HOUSE_11_SIGNIFICATION("gains and social networks", "लाभ र सामाजिक सञ्जालहरू"),
HOUSE_12_SIGNIFICATION("foreign connections and spiritual pursuits", "विदेशी सम्बन्ध र आध्यात्मिक खोजीहरू"),
VARIOUS_ACTIVITIES("various activities", "विभिन्न गतिविधिहरू"),
VARSHAPHALA_TITLE("Varshaphala", "वर्षफल"),
VARSHAPHALA_ANNUAL_CHART("Annual Chart", "वार्षिक चार्ट"),
VARSHAPHALA_SAHAMS("Sahams", "सहमहरू"),
VARSHAPHALA_TAJIKA("Tajika Aspects", "ताजिक दृष्टि"),
VARSHAPHALA_YOGAS("Tajika Yogas", "ताजिक योग"),
VARSHAPHALA_PREDICTIONS("Year Predictions", "वर्ष भविष्यवाणी"),
VARSHAPHALA_SELECT_YEAR("Select Year", "वर्ष चयन गर्नुहोस्"),
VARSHAPHALA_YEAR_OF_LIFE("Year %d of life", "जीवनको वर्ष %d"),
TITHI_PRATIPADA("Pratipada", "प्रतिपदा"),
TITHI_DWITIYA("Dwitiya", "द्वितीया"),
TITHI_TRITIYA("Tritiya", "तृतीया"),
TITHI_CHATURTHI("Chaturthi", "चतुर्थी"),
TITHI_PANCHAMI("Panchami", "पञ्चमी"),
TITHI_SHASHTHI("Shashthi", "षष्ठी"),
TITHI_SAPTAMI("Saptami", "सप्तमी"),
TITHI_ASHTAMI("Ashtami", "अष्टमी"),
TITHI_NAVAMI("Navami", "नवमी"),
TITHI_DASHAMI("Dashami", "दशमी"),
TITHI_EKADASHI("Ekadashi", "एकादशी"),
TITHI_DWADASHI("Dwadashi", "द्वादशी"),
TITHI_TRAYODASHI("Trayodashi", "त्रयोदशी"),
TITHI_CHATURDASHI("Chaturdashi", "चतुर्दशी"),
TITHI_PURNIMA("Purnima", "पूर्णिमा"),
TITHI_AMAVASYA("Amavasya", "अमावस्या"),
KARANA_BAVA("Bava", "बव"),
KARANA_BALAVA("Balava", "बालव"),
KARANA_KAULAVA("Kaulava", "कौलव"),
KARANA_TAITILA("Taitila", "तैतिल"),
KARANA_GARA("Gara", "गर"),
KARANA_VANIJA("Vanija", "वणिज"),
    KARANA_VISHTI("Vishti (Bhadra)", "Vishti (Bhadra)"),
KARANA_SHAKUNI("Shakuni", "शकुनि"),
KARANA_CHATUSHPADA("Chatushpada", "चतुष्पद"),
KARANA_NAGA("Naga", "नाग"),
KARANA_KIMSTUGHNA("Kimstughna", "किंस्तुघ्न"),
DAILY_YOGA_VISHKUMBHA("Vishkumbha", "विष्कम्भ"),
DAILY_YOGA_PRITI("Priti", "प्रीति"),
DAILY_YOGA_AYUSHMAN("Ayushman", "आयुष्मान"),
DAILY_YOGA_SAUBHAGYA("Saubhagya", "सौभाग्य"),
DAILY_YOGA_SHOBHANA("Shobhana", "शोभन"),
DAILY_YOGA_ATIGANDA("Atiganda", "अतिगण्ड"),
DAILY_YOGA_SUKARMA("Sukarma", "सुकर्म"),
DAILY_YOGA_DHRITI("Dhriti", "धृति"),
DAILY_YOGA_SHOOLA("Shoola", "शूल"),
DAILY_YOGA_GANDA("Ganda", "गण्ड"),
DAILY_YOGA_VRIDDHI("Vriddhi", "वृद्धि"),
DAILY_YOGA_DHRUVA("Dhruva", "ध्रुव"),
DAILY_YOGA_VYAGHATA("Vyaghata", "व्याघात"),
DAILY_YOGA_HARSHANA("Harshana", "हर्षण"),
DAILY_YOGA_VAJRA("Vajra", "वज्र"),
DAILY_YOGA_SIDDHI("Siddhi", "सिद्धि"),
DAILY_YOGA_VYATIPATA("Vyatipata", "व्यतीपात"),
DAILY_YOGA_VARIYANA("Variyana", "वरीयान"),
DAILY_YOGA_PARIGHA("Parigha", "परिघ"),
DAILY_YOGA_SHIVA("Shiva", "शिव"),
DAILY_YOGA_SIDDHA("Siddha", "सिद्ध"),
DAILY_YOGA_SADHYA("Sadhya", "साध्य"),
DAILY_YOGA_SHUBHA("Shubha", "शुभ"),
DAILY_YOGA_SHUKLA("Shukla", "शुक्ल"),
DAILY_YOGA_BRAHMA("Brahma", "ब्रह्म"),
DAILY_YOGA_INDRA("Indra", "इन्द्र"),
DAILY_YOGA_VAIDHRITI("Vaidhriti", "वैधृति"),
VARA_SUNDAY_DESC("Ruled by Sun - Good for government work, authority, spiritual practices", "सूर्य द्वारा शासित - सरकारी काम, अधिकार, आध्यात्मिक अभ्यासको लागि राम्रो"),
VARA_MONDAY_DESC("Ruled by Moon - Good for travel, public dealings, emotional matters", "चन्द्रमा द्वारा शासित - यात्रा, सार्वजनिक व्यवहार, भावनात्मक मामिलाहरूको लागि राम्रो"),
VARA_TUESDAY_DESC("Ruled by Mars - Good for property, surgery, competitive activities", "मंगल द्वारा शासित - सम्पत्ति, शल्यक्रिया, प्रतिस्पर्धात्मक गतिविधिहरूको लागि राम्रो"),
VARA_WEDNESDAY_DESC("Ruled by Mercury - Good for education, communication, business", "बुध द्वारा शासित - शिक्षा, सञ्चार, व्यापारको लागि राम्रो"),
VARA_THURSDAY_DESC("Ruled by Jupiter - Good for religious ceremonies, marriage, education", "बृहस्पति द्वारा शासित - धार्मिक समारोह, विवाह, शिक्षाको लागि राम्रो"),
VARA_FRIDAY_DESC("Ruled by Venus - Good for romance, marriage, arts, luxury", "शुक्र द्वारा शासित - प्रेम, विवाह, कला, विलासिताको लागि राम्रो"),
VARA_SATURDAY_DESC("Ruled by Saturn - Good for property, agriculture, spiritual discipline", "शनि द्वारा शासित - सम्पत्ति, कृषि, आध्यात्मिक अनुशासनको लागि राम्रो"),
ACTION_NEW_BEGINNINGS("New beginnings", "नयाँ सुरुवातहरू"),
ACTION_STARTING_VENTURES("Starting ventures", "उद्यमहरू सुरु गर्दै"),
ACTION_TRAVEL("Travel", "यात्रा"),
ACTION_MARRIAGE("Marriage", "विवाह"),
ACTION_EDUCATION("Education", "शिक्षा"),
ACTION_BUSINESS("Business", "व्यापार"),
ACTION_SPIRITUAL_PRACTICES("Spiritual practices", "आध्यात्मिक अभ्यास"),
ACTION_WORSHIP("Worship", "पूजा"),
ACTION_CHARITY("Charity", "दान"),
ACTION_FASTING("Fasting", "उपवास"),
ACTION_MEDITATION("Meditation", "ध्यान"),
ACTION_SURGERY("Surgery", "शल्यक्रिया"),
ACTION_CREATIVE_WORK("Creative work", "सिर्जनात्मक काम"),
ACTION_GOVERNMENT_WORK("Government work", "सरकारी काम"),
ACTION_PROPERTY_MATTERS("Property matters", "सम्पत्ति मामिलाहरू"),
ACTION_FINANCIAL_MATTERS("Financial matters", "वित्तीय मामिलाहरू")
}
