package com.astro.storm.core.common
enum class StringKeyPart1(override val en: String, override val ne: String) : StringKeyInterface {
HOME_CHART_ANALYSIS("Chart Analysis", "कुण्डली विश्लेषण"),
HOME_COMING_SOON("Coming Soon", "छिट्टै आउँदैछ"),
HOME_SOON_BADGE("Soon", "छिट्टै"),
ASHTAKAVARGA_ABOUT_TITLE("About Ashtakavarga", "अष्टकवर्ग बारेमा"),
ASHTAKAVARGA_ABOUT_DESC("Ashtakavarga is an ancient Vedic astrology technique for assessing planetary strength and predicting transit effects.", "अष्टकवर्ग वैदिक ज्योतिषको एक प्राचीन प्रविधि हो जसले ग्रहको शक्ति मापन र गोचर प्रभाव पूर्वानुमान गर्दछ।"),
    ASHTAKAVARGA_SAV_TITLE("Sarvashtakavarga (SAV)", "Sarvashtakavarga (SAV)"),
    ASHTAKAVARGA_SAV_DESC("Combined strength points from all planets in each zodiac sign. Higher values (28+)", "Combined strength points from all planets in each zodiac sign. Higher values (28+)"),
    ASHTAKAVARGA_BAV_TITLE("Bhinnashtakavarga (BAV)", "Bhinnashtakavarga (BAV)"),
    ASHTAKAVARGA_BAV_DESC("Individual planet strength in each sign (0-8 bindus)", "Individual planet strength in each sign (0-8 bindus)"),
VARSHAPHALA_TAB_OVERVIEW("Overview", "अवलोकन"),
VARSHAPHALA_TAB_TAJIKA("Tajika", "तजिका"),
VARSHAPHALA_TAB_SAHAMS("Sahams", "सहम"),
VARSHAPHALA_TAB_DASHA("Dasha", "दशा"),
VARSHAPHALA_TAB_HOUSES("Houses", "भावहरू"),
VARSHAPHALA_ANNUAL_HOROSCOPE("Annual Horoscope", "वार्षिक राशिफल"),
VARSHAPHALA_AGE("Age %d", "आयु %d"),
VARSHAPHALA_PREV_YEAR("Previous year", "अघिल्लो वर्ष"),
VARSHAPHALA_NEXT_YEAR("Next year", "अर्को वर्ष"),
VARSHAPHALA_SELECT_CHART("Select a birth chart to view Varshaphala", "वर्षफल हेर्न जन्म कुण्डली छान्नुहोस्"),
VARSHAPHALA_COMPUTING("Computing Annual Horoscope...", "वार्षिक राशिफल गणना गर्दै..."),
VARSHAPHALA_COMPUTING_DESC("Calculating Tajika aspects, Sahams & Mudda Dasha", "तजिका पक्ष, सहम र मुद्द दशा गणना गर्दै"),
VARSHAPHALA_ERROR("Calculation Error", "गणना त्रुटि"),
VARSHAPHALA_RESET_YEAR("Reset to Current Year", "वर्तमान वर्षमा रिसेट"),
VARSHAPHALA_SOLAR_RETURN("Solar Return", "सौर प्रतिफल"),
VARSHAPHALA_YEAR_LORD("Year Lord", "वर्ष स्वामी"),
VARSHAPHALA_MUNTHA("Muntha", "मुन्थ"),
VARSHAPHALA_MUNTHA_LORD("Lord: %s", "स्वामी: %s"),
VARSHAPHALA_TAJIKA_CHART("Tajika Annual Chart", "तजिका वार्षिक कुण्डली"),
VARSHAPHALA_PANCHA_VARGIYA("Pancha Vargiya Bala", "पञ्च वर्गीय बल"),
VARSHAPHALA_TRI_PATAKI("Tri-Pataki Chakra", "त्रि-पतकी चक्र"),
VARSHAPHALA_MAJOR_THEMES("Major Themes", "मुख्य विषयहरू"),
VARSHAPHALA_MONTHLY_OUTLOOK("Monthly Outlook", "मासिक दृष्टिकोण"),
VARSHAPHALA_FAVORABLE("Favorable", "अनुकूल"),
VARSHAPHALA_KEY_DATES("Key Dates", "महत्त्वपूर्ण मितिहरू"),
VARSHAPHALA_OVERALL_PREDICTION("Overall Prediction", "समग्र भविष्यवाणी"),
VARSHAPHALA_TAJIKA_SUMMARY("Tajika Yogas Summary", "तजिका योग सारांश"),
    VARSHAPHALA_SAHAMS_TITLE("Sahams (Arabic Parts)", "Sahams (Arabic Parts)"),
VARSHAPHALA_SAHAMS_DESC("Sensitive points calculated from planetary positions", "ग्रह स्थितिबाट गणना गरिएको संवेदनशील बिन्दुहरू"),
VARSHAPHALA_MUDDA_DASHA("Mudda Dasha", "मुद्द दशा"),
VARSHAPHALA_MUDDA_DASHA_DESC("Annual planetary periods based on Moon's position", "चन्द्रको स्थितिमा आधारित वार्षिक ग्रह अवधिहरू"),
VARSHAPHALA_POSITION("Position", "स्थिति"),
VARSHAPHALA_HOUSE("House", "भाव"),
VARSHAPHALA_DAYS("%d days", "%d दिन"),
PREDICTIONS_TAB_OVERVIEW("Overview", "सारांश"),
PREDICTIONS_TAB_LIFE_AREAS("Life Areas", "जीवन क्षेत्रहरू"),
PREDICTIONS_TAB_TIMING("Timing", "समय"),
PREDICTIONS_TAB_REMEDIES("Remedies", "उपाय"),
PREDICTIONS_YOUR_LIFE_PATH("Your Life Path", "तपाईंको जीवन मार्ग"),
PREDICTIONS_KEY_STRENGTHS("Key Strengths", "मुख्य शक्तिहरू"),
PREDICTIONS_SPIRITUAL_PATH("Spiritual Path", "आध्यात्मिक मार्ग"),
PREDICTIONS_CURRENT_PERIOD("Current Period", "वर्तमान अवधि"),
PREDICTIONS_ACTIVE_TRANSITS("Active Transits", "सक्रिय गोचर"),
PREDICTIONS_ACTIVE_YOGAS("Active Yogas", "सक्रिय योगहरू"),
PREDICTIONS_OPPORTUNITIES("Opportunities", "अवसरहरू"),
PREDICTIONS_CURRENT_CHALLENGES("Current Challenges", "वर्तमान चुनौतीहरू"),
PREDICTIONS_LIFE_AREAS_GLANCE("Life Areas at a Glance", "एक नजरमा जीवन क्षेत्रहरू"),
PREDICTIONS_FAVORABLE_PERIODS("Favorable Periods", "अनुकूल अवधिहरू"),
PREDICTIONS_CAUTION_PERIODS("Periods Needing Caution", "सावधानी चाहिने अवधिहरू"),
PREDICTIONS_IMPORTANT_DATES("Important Dates", "महत्त्वपूर्ण मितिहरू"),
PREDICTIONS_REMEDIAL_SUGGESTIONS("Remedial Suggestions", "उपचारात्मक सुझावहरू"),
PREDICTIONS_NO_CHART_SELECTED("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
PREDICTIONS_SELECT_CHART_MESSAGE("Please select a birth chart to view predictions", "कृपया भविष्यवाणी हेर्न जन्म कुण्डली छान्नुहोस्"),
PREDICTIONS_CALCULATING("Calculating Predictions...", "भविष्यवाणी गणना गर्दै..."),
PREDICTIONS_ERROR_LOADING("Error Loading Predictions", "भविष्यवाणी लोड गर्न त्रुटि"),
PREDICTIONS_CALC_FAILED("Failed to calculate predictions", "भविष्यवाणी गणना गर्न असफल"),
PREDICTIONS_CAREER_PROFESSION("Career & Profession", "क्यारियर र पेशा"),
PREDICTIONS_FINANCE_WEALTH("Finance & Wealth", "वित्त र सम्पत्ति"),
PREDICTIONS_RELATIONSHIPS_MARRIAGE("Relationships & Marriage", "सम्बन्ध र विवाह"),
PREDICTIONS_HEALTH_WELLBEING("Health & Wellbeing", "स्वास्थ्य र कल्याण"),
PREDICTIONS_EDUCATION_LEARNING("Education & Learning", "शिक्षा र सिकाइ"),
PREDICTIONS_FAMILY_HOME("Family & Home", "परिवार र घर"),
    PREDICTIONS_SHORT_TERM("Short-term (3-6 months)", "Short-term (3-6 months)"),
    PREDICTIONS_MEDIUM_TERM("Medium-term (6-12 months)", "Medium-term (6-12 months)"),
    PREDICTIONS_LONG_TERM("Long-term (1-2 years)", "Long-term (1-2 years)"),
PREDICTIONS_BEST_FOR("Best for", "को लागि उत्तम"),
PREDICTIONS_CAUTION_FOR("Caution for", "को लागि सावधानी"),
PREDICTIONS_ENERGY_LEVEL("Energy Level", "ऊर्जा स्तर"),
PREDICTIONS_DAYS_LEFT("days left", "दिन बाँकी"),
PREDICTIONS_MONTHS("months", "महिना"),
PREDICTIONS_GO_BACK("Go Back", "फर्कनुहोस्"),
NO_PROFILE_SELECTED("No Profile Selected", "कुनै प्रोफाइल छानिएको छैन"),
NO_PROFILE_MESSAGE("Select or create a profile to view your personalized astrological insights.", "आफ्नो व्यक्तिगत ज्योतिष अन्तर्दृष्टि हेर्न प्रोफाइल छान्नुहोस् वा बनाउनुहोस्।"),
NO_PROFILE_MESSAGE_LONG("Select or create a profile to view your personalized astrological insights and predictions", "आफ्नो व्यक्तिगत ज्योतिष अन्तर्दृष्टि र भविष्यवाणी हेर्न प्रोफाइल छान्नुहोस् वा बनाउनुहोस्"),
INFO_DASHA("Dasha information", "दशा जानकारी"),
INSIGHTS_OVERALL_ENERGY("Overall Energy", "समग्र ऊर्जा"),
INSIGHTS_LIFE_AREAS("Life Areas", "जीवन क्षेत्रहरू"),
INSIGHTS_LUCKY_ELEMENTS("Lucky Elements", "भाग्यशाली तत्वहरू"),
INSIGHTS_TODAYS_AFFIRMATION("Today's Affirmation", "आजको प्रतिज्ञा"),
INSIGHTS_WEEKLY_ENERGY("Weekly Energy Flow", "साप्ताहिक ऊर्जा प्रवाह"),
INSIGHTS_KEY_DATES("Key Dates", "महत्त्वपूर्ण मितिहरू"),
INSIGHTS_WEEKLY_OVERVIEW("Weekly Overview by Area", "क्षेत्रअनुसार साप्ताहिक अवलोकन"),
INSIGHTS_WEEKLY_ADVICE("Weekly Advice", "साप्ताहिक सल्लाह"),
INSIGHTS_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
INSIGHTS_CAUTIONS("Cautions", "सावधानीहरू"),
PERIOD_TODAY("Today", "आज"),
PERIOD_TOMORROW("Tomorrow", "भोलि"),
PERIOD_WEEKLY("Weekly", "साप्ताहिक"),
MSG_MAY_TAKE_MOMENT("This may take a moment", "यसमा केही समय लाग्न सक्छ"),
LIFE_AREA_CAREER("Career", "करियर"),
LIFE_AREA_LOVE("Love & Relationships", "प्रेम र सम्बन्ध"),
LIFE_AREA_HEALTH("Health & Vitality", "स्वास्थ्य र जीवनशक्ति"),
LIFE_AREA_FINANCE("Finance & Wealth", "वित्त र सम्पत्ति"),
LIFE_AREA_FAMILY("Family & Home", "परिवार र घर"),
LIFE_AREA_SPIRITUALITY("Spiritual Growth", "आध्यात्मिक वृद्धि"),
LIFE_AREA_CAREER_FULL("Career", "क्यारियर"),
LIFE_AREA_LOVE_FULL("Love & Relationships", "प्रेम र सम्बन्ध"),
LIFE_AREA_HEALTH_FULL("Health & Vitality", "स्वास्थ्य र जीवनशक्ति"),
LIFE_AREA_FINANCE_FULL("Finance & Wealth", "वित्त र सम्पत्ति"),
LIFE_AREA_FAMILY_FULL("Family & Home", "परिवार र घर"),
LIFE_AREA_SPIRITUALITY_FULL("Spiritual Growth", "आध्यात्मिक वृद्धि"),
THEME_DYNAMIC_ACTION("Dynamic Action", "गत्यात्मक कार्य"),
THEME_PRACTICAL_PROGRESS("Practical Progress", "व्यावहारिक प्रगति"),
THEME_SOCIAL_CONNECTIONS("Social Connections", "सामाजिक सम्बन्ध"),
THEME_EMOTIONAL_INSIGHT("Emotional Insight", "भावनात्मक अन्तर्दृष्टि"),
THEME_EXPANSION_WISDOM("Expansion & Wisdom", "विस्तार र ज्ञान"),
THEME_HARMONY_BEAUTY("Harmony & Beauty", "सामञ्जस्य र सौन्दर्य"),
THEME_DISCIPLINE_GROWTH("Discipline & Growth", "अनुशासन र वृद्धि"),
THEME_COMMUNICATION_LEARNING("Communication & Learning", "सञ्चार र सिकाई"),
THEME_ENERGY_INITIATIVE("Energy & Initiative", "ऊर्जा र पहल"),
THEME_SELF_EXPRESSION("Self-Expression", "आत्म-अभिव्यक्ति"),
THEME_INTUITION_NURTURING("Intuition & Nurturing", "अन्तर्ज्ञान र पोषण"),
THEME_TRANSFORMATION("Transformation", "रूपान्तरण"),
THEME_SPIRITUAL_LIBERATION("Spiritual Liberation", "आध्यात्मिक मुक्ति"),
THEME_BALANCE_EQUILIBRIUM("Balance & Equilibrium", "सन्तुलन र स्थिरता"),
THEME_DESC_DYNAMIC_ACTION("Your energy is high and aligned with fire elements. This is an excellent day for taking initiative, starting new projects, and asserting yourself confidently. Channel this vibrant energy into productive pursuits.", "तपाईंको ऊर्जा उच्च छ र अग्नि तत्वसँग मिल्दोजुल्दो छ। यो पहल गर्न, नयाँ परियोजनाहरू सुरु गर्न र आत्मविश्वासका साथ आफूलाई प्रस्तुत गर्न उत्कृष्ट दिन हो। यस जीवन्त ऊर्जालाई उत्पादक कार्यहरूमा लगाउनुहोस्।"),
THEME_DESC_PRACTICAL_PROGRESS("Grounded earth energy supports methodical progress today. Focus on practical tasks, financial planning, and building stable foundations. Your efforts will yield tangible results.", "पृथ्वी तत्वको ऊर्जाले आज व्यवस्थित प्रगतिलाई समर्थन गर्दछ। व्यावहारिक कार्यहरू, वित्तीय योजना, र स्थिर आधार निर्माणमा ध्यान दिनुहोस्। तपाईंको प्रयासले मूर्त परिणामहरू दिनेछ।"),
THEME_DESC_SOCIAL_CONNECTIONS("Air element energy enhances communication and social interactions. Networking, negotiations, and intellectual pursuits are favored. Express your ideas and connect with like-minded people.", "वायु तत्वको ऊर्जाले सञ्चार र सामाजिक अन्तरक्रियालाई बढावा दिन्छ। नेटवर्किङ, वार्ता, र बौद्धिक कार्यहरूका लागि आज अनुकूल छ। आफ्ना विचारहरू व्यक्त गर्नुहोस् र समान विचारधारा भएका मानिसहरूसँग जोडिनुहोस्।"),
THEME_DESC_EMOTIONAL_INSIGHT("Water element energy deepens your intuition and emotional awareness. Trust your feelings and pay attention to subtle cues. This is a powerful day for healing and self-reflection.", "जल तत्वको ऊर्जाले तपाईंको अन्तर्ज्ञान र भावनात्मक जागरूकतालाई गहिरो बनाउँछ। आफ्ना भावनाहरूमा विश्वास गर्नुहोस् र सूक्ष्म संकेतहरूमा ध्यान दिनुहोस्। यो निको पार्न र आत्म-चिन्तनका लागि एक शक्तिशाली दिन हो।"),
THEME_DESC_EXPANSION_WISDOM("Jupiter's benevolent influence brings opportunities for growth, learning, and good fortune. Be open to new possibilities and share your wisdom generously.", "बृहस्पतिको उदार प्रभावले वृद्धि, सिकाई र सौभाग्यको अवसरहरू ल्याउँछ। नयाँ सम्भावनाहरूका लागि खुला रहनुहोस् र आफ्नो ज्ञान उदारतापूर्वक बाँड्नुहोस्।"),
THEME_DESC_HARMONY_BEAUTY("Venus graces you with appreciation for beauty, art, and relationships. Indulge in pleasurable activities and nurture your connections with loved ones.", "शुक्रले तपाईंलाई सौन्दर्य, कला, र सम्बन्धहरूको लागि प्रशंसा प्रदान गर्दछ। आनन्ददायी गतिविधिहरूमा संलग्न हुनुहोस् र आफ्ना प्रियजनहरूसँगको सम्बन्धलाई प्रगाढ बनाउनुहोस्।"),
THEME_DESC_DISCIPLINE_GROWTH("Saturn's influence calls for patience, hard work, and responsibility. Embrace challenges as opportunities for growth and stay committed to your long-term goals.", "शनिको प्रभावले धैर्य, कडा परिश्रम, र जिम्मेवारीको माग गर्दछ। चुनौतीहरूलाई वृद्धिको अवसरको रूपमा स्वीकार गर्नुहोस् र आफ्ना दीर्घकालीन लक्ष्यहरूमा प्रतिबद्ध रहनुहोस्।"),
THEME_DESC_COMMUNICATION_LEARNING("Mercury enhances your mental agility and communication skills. This is ideal for learning, teaching, writing, and all forms of information exchange.", "बुधले तपाईंको मानसिक चपलता र सञ्चार सीपलाई बढावा दिन्छ। यो सिकाई, शिक्षण, लेखन, र सबै प्रकारका सूचना आदानप्रदानका लागि उपयुक्त छ।"),
THEME_DESC_ENERGY_INITIATIVE("Mars provides courage and drive. Take bold action, compete with integrity, and channel aggressive energy into constructive activities.", "मंगलले साहस र जोश प्रदान गर्दछ। साहसी कदम चाल्नुहोस्, इमानदारीका साथ प्रतिस्पर्धा गर्नुहोस्, र आक्रामक ऊर्जालाई रचनात्मक गतिविधिहरूमा लगाउनुहोस्।"),
THEME_DESC_SELF_EXPRESSION("The Sun illuminates your path to self-expression and leadership. Shine your light confidently and pursue activities that bring you recognition.", "सूर्यले तपाईंको आत्म-अभिव्यक्ति र नेतृत्वको मार्गलाई उज्यालो बनाउँछ। आत्मविश्वासका साथ आफ्नो चमक देखाउनुहोस् र तपाईंलाई पहिचान दिलाउने गतिविधिहरूमा लाग्नुहोस्।"),
THEME_DESC_INTUITION_NURTURING("The Moon heightens your sensitivity and caring nature. Nurture yourself and others, and trust your instincts in important decisions.", "चन्द्रमाले तपाईंको संवेदनशीलता र हेरचाह गर्ने प्रकृतिलाई बढाउँछ। आफू र अरूको पोषण गर्नुहोस्, र महत्त्वपूर्ण निर्णयहरूमा आफ्नो अन्तर्ज्ञानमा विश्वास गर्नुहोस्।"),
THEME_DESC_TRANSFORMATION("Rahu's influence brings unconventional opportunities and desires for change. Embrace innovation but stay grounded in your values.", "राहुको प्रभावले अपरम्परागत अवसरहरू र परिवर्तनको इच्छा ल्याउँछ। नवीनतालाई अँगाल्नुहोस् तर आफ्ना मूल्यहरूमा अडिग रहनुहोस्।"),
THEME_DESC_SPIRITUAL_LIBERATION("Ketu's energy supports detachment and spiritual insight. Let go of what no longer serves you and focus on inner growth.", "केतुको ऊर्जाले वैराग्य र आध्यात्मिक अन्तर्दृष्टिलाई समर्थन गर्दछ। जे कुराले तपाईंलाई अब फाइदा गर्दैन त्यसलाई छोडिदिनुहोस् र आन्तरिक वृद्धिमा ध्यान दिनुहोस्।"),
THEME_DESC_BALANCE_EQUILIBRIUM("A day of balance where all energies are in equilibrium. Maintain steadiness and make measured progress in all areas of life.", "सबै ऊर्जाहरू सन्तुलनमा रहेको दिन। स्थिरता कायम राख्नुहोस् र जीवनका सबै क्षेत्रमा नापिएको प्रगति गर्नुहोस्।"),
THEME_WEEK_OPPORTUNITIES("Week of Opportunities", "अवसरहरूको हप्ता"),
THEME_WEEK_STEADY_PROGRESS("Steady Progress", "स्थिर प्रगति"),
THEME_WEEK_MINDFUL_NAVIGATION("Mindful Navigation", "सचेत यात्रा"),
WEEKLY_OVERVIEW_EXCELLENT("excellent opportunities for growth and success. ", "वृद्धि र सफलताको लागि उत्कृष्ट अवसरहरू। "),
WEEKLY_OVERVIEW_STEADY("steady progress and balanced energy. ", "स्थिर प्रगति र सन्तुलित ऊर्जा। "),
WEEKLY_OVERVIEW_CHALLENGING("challenges that, when navigated wisely, lead to growth. ", "चुनौतीहरू जसलाई बुद्धिमानीपूर्वक सामना गर्दा वृद्धि हुन्छ। "),
WEEKLY_OVERVIEW_FOOTER("Trust in your cosmic guidance and make the most of each day's unique energy.", "आफ्नो ब्रह्माण्डीय मार्गदर्शनमा विश्वास गर्नुहोस् र प्रत्येक दिनको अद्वितीय ऊर्जाको सदुपयोग गर्नुहोस्।"),
ADVICE_JUPITER("embrace opportunities for learning and expansion. Your wisdom and optimism attract positive outcomes.", "सिकाई र विस्तारका अवसरहरूलाई अँगाल्नुहोस्। तपाईंको ज्ञान र आशावादले सकारात्मक परिणामहरू आकर्षित गर्दछ।"),
ADVICE_VENUS("focus on cultivating beauty, harmony, and meaningful relationships. Artistic pursuits are favored.", "सौन्दर्य, सामञ्जस्य, र अर्थपूर्ण सम्बन्धहरू विकास गर्नमा ध्यान दिनुहोस्। कलात्मक कार्यहरूलाई प्राथमिकता दिइन्छ।"),
ADVICE_SATURN("embrace discipline and patience. Hard work now builds lasting foundations for the future.", "अनुशासन र धैर्यलाई अँगाल्नुहोस्। अहिलेको कडा परिश्रमले भविष्यको लागि स्थायी आधार निर्माण गर्दछ।"),
ADVICE_MERCURY("prioritize communication, learning, and intellectual activities. Your mind is sharp.", "सञ्चार, सिकाई, र बौद्धिक गतिविधिहरूलाई प्राथमिकता दिनुहोस्। तपाईंको दिमाग तेज छ।"),
ADVICE_MARS("channel your energy into productive activities. Exercise and competition are favored.", "आफ्नो ऊर्जालाई उत्पादक गतिविधिहरूमा लगाउनुहोस्। व्यायाम र प्रतिस्पर्धालाई प्राथमिकता दिइन्छ।"),
ADVICE_SUN("let your light shine. Leadership roles and self-expression bring recognition.", "आफ्नो चमक फैलिन दिनुहोस्। नेतृत्वदायी भूमिका र आत्म-अभिव्यक्तिले पहिचान दिलाउँछ।"),
ADVICE_MOON("honor your emotions and intuition. Nurturing activities bring fulfillment.", "आफ्ना भावना र अन्तर्ज्ञानको सम्मान गर्नुहोस्। पोषण गर्ने गतिविधिहरूले सन्तुष्टि ल्याउँछ।"),
ADVICE_RAHU("embrace transformation while staying grounded. Unconventional approaches may succeed.", "आधारभूत मूल्यहरूमा रहँदै परिवर्तनलाई अँगाल्नुहोस्। अपरम्परागत दृष्टिकोणहरू सफल हुन सक्छन्।"),
ADVICE_KETU("focus on spiritual growth and letting go. Detachment brings peace.", "आध्यात्मिक वृद्धि र त्यागमा ध्यान दिनुहोस्। वैराग्यले शान्ति ल्याउँछ।"),
ADVICE_GENERAL("maintain balance and trust in divine timing.", "सन्तुलन कायम राख्नुहोस् र ईश्वरीय समयमा विश्वास गर्नुहोस्।"),
LUCKY_NUMBER("Number", "अंक"),
LUCKY_COLOR("Color", "रंग"),
LUCKY_DIRECTION("Direction", "दिशा"),
LUCKY_GEMSTONE("Gemstone", "रत्न"),
DASHA_CURRENT_PERIOD("Current Planetary Period", "हालको ग्रह अवधि"),
DASHA_ACTIVE("Active", "सक्रिय"),
DASHA_MAHADASHA("Mahadasha", "महादशा"),
DASHA_ANTARDASHA("Antardasha", "अन्तर्दशा"),
DASHA_PRATYANTARDASHA("Pratyantardasha:", "प्रत्यन्तर्दशा:"),
DASHA_UPCOMING("Upcoming Periods", "आगामी अवधिहरू"),
DASHA_REMAINING("remaining", "बाँकी"),
DASHA_PERIOD_NAME("%s: %s", "%s: %s"),
DASHA_COMBINED_NAME("%s-%s", "%s-%s"),
DASHA_LAST_IN_MAHADASHA("Current Antardasha is the last in this Mahadasha", "हालको अन्तर्दशा यस महादशाको अन्तिम हो"),
DASHA_STARTS("Starts %s", "%s मा सुरु हुन्छ"),
DASHA_VIMSHOTTARI("Vimshottari Dasha", "विम्शोत्तरी दशा"),
DASHA_JUMP_TO_TODAY("Jump to current period", "हालको अवधिमा जानुहोस्"),
DASHA_CALCULATING("Calculating...", "गणना गर्दै..."),
DASHA_ERROR("Error", "त्रुटि"),
DASHA_CALCULATING_TIMELINE("Calculating Dasha Timeline", "दशा समयरेखा गणना गर्दै"),
DASHA_CALCULATING_DESC("Computing planetary periods based on\nMoon's Nakshatra position...", "चन्द्रको नक्षत्र स्थितिको आधारमा\nग्रह अवधिहरू गणना गर्दै..."),
DASHA_CALCULATION_FAILED("Calculation Failed", "गणना असफल भयो"),
DASHA_NO_CHART_SELECTED("No Chart Selected", "कुनै कुण्डली छानिएको छैन"),
DASHA_NO_CHART_MESSAGE("Please select or create a birth profile\nto view the Dasha timeline.", "दशा समयरेखा हेर्न कृपया जन्म प्रोफाइल\nछान्नुहोस् वा बनाउनुहोस्।"),
DASHA_SOOKSHMADASHA("Sookshmadasha", "सूक्ष्मदशा"),
DASHA_PRANADASHA("Pranadasha", "प्राणदशा"),
DASHA_DEHADASHA("Dehadasha", "देहदशा"),
DASHA_BHUKTI("Bhukti", "भुक्ति"),
DASHA_PRATYANTAR("Pratyantar", "प्रत्यन्तर"),
DASHA_SOOKSHMA("Sookshma", "सूक्ष्म"),
DASHA_PRANA("Prana", "प्राण"),
DASHA_DEHA("Deha", "देह"),
DASHA_DURATION("Duration", "अवधि"),
DASHA_PERIOD("Period", "अवधि"),
DASHA_STATUS("Status", "स्थिति"),
DASHA_CURRENTLY_ACTIVE("Currently Active", "हाल सक्रिय"),
DASHA_PROGRESS("Progress", "प्रगति"),
DASHA_NO_ACTIVE_PERIOD("No active Dasha period", "कुनै सक्रिय दशा अवधि छैन"),
YEARS("years", "वर्ष"),
DAYS("days", "दिन"),
TO("to", "देखि"),
YEARS_SHORT("y", "व"),
MONTHS_SHORT("m", "म"),
WEEKS_SHORT("w", "ह"),
DAYS_SHORT("d", "दि"),
HOURS_SHORT("h", "घ"),
MINUTES_SHORT("m", "मि"),
NATURE_BENEFIC("Benefic", "शुभ"),
NATURE_MALEFIC("Malefic", "अशुभ"),
NATURE_MIXED("Mixed", "मिश्रित"),
TRANSITS_CURRENT("Current Transits", "हालका गोचरहरू"),
TRANSITS_MOON_IN("Moon in %s", "चन्द्रमा %s मा"),
ENERGY_EXCEPTIONAL("Exceptional cosmic alignment - seize every opportunity!", "असाधारण ब्रह्माण्डीय संरेखण - हरेक अवसर समात्नुहोस्!"),
ENERGY_EXCELLENT("Excellent day ahead - favorable for important decisions", "उत्कृष्ट दिन अगाडि - महत्त्वपूर्ण निर्णयहरूको लागि अनुकूल"),
ENERGY_STRONG("Strong positive energy - good for new initiatives", "बलियो सकारात्मक ऊर्जा - नयाँ पहलहरूको लागि राम्रो"),
ENERGY_FAVORABLE("Favorable energy - maintain steady progress", "अनुकूल ऊर्जा - स्थिर प्रगति कायम राख्नुहोस्"),
ENERGY_BALANCED("Balanced energy - stay centered and focused", "सन्तुलित ऊर्जा - केन्द्रित र ध्यान केन्द्रित रहनुहोस्"),
ENERGY_MODERATE("Moderate energy - pace yourself wisely", "मध्यम ऊर्जा - बुद्धिमानीपूर्वक आफ्नो गति मिलाउनुहोस्"),
ENERGY_LOWER("Lower energy day - prioritize rest and reflection", "कम ऊर्जा दिन - आराम र चिन्तनलाई प्राथमिकता दिनुहोस्"),
ENERGY_CHALLENGING("Challenging day - practice patience and self-care", "चुनौतीपूर्ण दिन - धैर्य र आत्म-हेरचाह अभ्यास गर्नुहोस्"),
ENERGY_REST("Rest and recharge recommended - avoid major decisions", "आराम र रिचार्ज सिफारिस - प्रमुख निर्णयहरूबाट बच्नुहोस्"),
LUCKY_COLOR_FIRE("Red, Orange, or Gold", "रातो, सुन्तला, वा सुनौलो"),
LUCKY_COLOR_EARTH("Green, Brown, or White", "हरियो, खैरो, वा सेतो"),
LUCKY_COLOR_AIR("Blue, Light Blue, or Silver", "निलो, हल्का निलो, वा चाँदी"),
LUCKY_COLOR_WATER("White, Cream, or Sea Green", "सेतो, क्रीम, वा समुद्री हरियो"),
LUCKY_DIRECTION_EAST("East", "पूर्व"),
LUCKY_DIRECTION_WEST("West", "पश्चिम"),
LUCKY_DIRECTION_NORTH("North", "उत्तर"),
LUCKY_DIRECTION_SOUTH("South", "दक्षिण"),
LUCKY_DIRECTION_NORTHEAST("North-East", "उत्तर-पूर्व"),
LUCKY_DIRECTION_NORTHWEST("North-West", "उत्तर-पश्चिम"),
LUCKY_DIRECTION_SOUTHEAST("South-East", "दक्षिण-पूर्व"),
LUCKY_DIRECTION_SOUTHWEST("South-West", "दक्षिण-पश्चिम"),
DASHA_REC_SUN("Engage in activities that build confidence and leadership skills.", "आत्मविश्वास र नेतृत्व कौशल विकास गर्ने गतिविधिहरूमा संलग्न हुनुहोस्।"),
DASHA_REC_MOON("Prioritize emotional well-being and nurturing relationships.", "भावनात्मक कल्याण र पोषणपूर्ण सम्बन्धहरूलाई प्राथमिकता दिनुहोस्।"),
DASHA_REC_MARS("Channel your energy into physical activities and competitive pursuits.", "आफ्नो ऊर्जालाई शारीरिक गतिविधि र प्रतिस्पर्धात्मक प्रयासहरूमा प्रयोग गर्नुहोस्।"),
DASHA_REC_MERCURY("Focus on learning, communication, and intellectual growth.", "सिकाइ, सञ्चार र बौद्धिक वृद्धिमा ध्यान दिनुहोस्।"),
DASHA_REC_JUPITER("Expand your horizons through education, travel, or spiritual practices.", "शिक्षा, यात्रा वा आध्यात्मिक अभ्यासहरूको माध्यमबाट आफ्नो क्षितिज विस्तार गर्नुहोस्।"),
DASHA_REC_VENUS("Cultivate beauty, art, and harmonious relationships.", "सौन्दर्य, कला र सामञ्जस्यपूर्ण सम्बन्धहरू विकास गर्नुहोस्।"),
DASHA_REC_SATURN("Embrace discipline, hard work, and long-term planning.", "अनुशासन, कडा परिश्रम र दीर्घकालीन योजनालाई अँगाल्नुहोस्।"),
DASHA_REC_RAHU("Explore unconventional paths while staying grounded.", "जमिनमा रहँदै अपरम्परागत मार्गहरू अन्वेषण गर्नुहोस्।"),
DASHA_REC_KETU("Practice detachment and focus on spiritual development.", "वैराग्यको अभ्यास गर्नुहोस् र आध्यात्मिक विकासमा ध्यान दिनुहोस्।"),
DASHA_AFF_SUN("I shine my light confidently and inspire those around me.", "म आत्मविश्वासका साथ आफ्नो प्रकाश फैलाउँछु र वरिपरिका मानिसहरूलाई प्रेरित गर्छु।"),
DASHA_AFF_MOON("I trust my intuition and nurture myself with compassion.", "म आफ्नो अन्तर्ज्ञानमाथि विश्वास गर्छु र करुणाका साथ आफूलाई पोषण गर्छु।"),
DASHA_AFF_MARS("I channel my energy constructively and act with courage.", "म आफ्नो ऊर्जा रचनात्मक रूपमा प्रयोग गर्छु र साहसका साथ काम गर्छु।"),
DASHA_AFF_MERCURY("I communicate clearly and embrace continuous learning.", "म स्पष्ट रूपमा सञ्चार गर्छु र निरन्तर सिकाइलाई अँगाल्छु।"),
DASHA_AFF_JUPITER("I am open to abundance and share my wisdom generously.", "म प्रचुरताको लागि खुला छु र आफ्नो ज्ञान उदारतापूर्वक साझा गर्छु।"),
DASHA_AFF_VENUS("I attract beauty and harmony into my life.", "म आफ्नो जीवनमा सौन्दर्य र सामञ्जस्य आकर्षित गर्छु।"),
DASHA_AFF_SATURN("I embrace discipline and trust in the timing of my journey.", "म अनुशासनलाई अँगाल्छु र आफ्नो यात्राको समयमाथि विश्वास गर्छु।"),
DASHA_AFF_RAHU("I embrace change and transform challenges into opportunities.", "म परिवर्तनलाई अँगाल्छु र चुनौतीहरूलाई अवसरहरूमा रूपान्तरण गर्छु।"),
DASHA_AFF_KETU("I release what no longer serves me and embrace spiritual growth.", "म जुन कुराले अब मेरो सेवा गर्दैन त्यसलाई छाड्छु र आध्यात्मिक वृद्धिलाई अँगाल्छु।"),
ELEMENT_REC_FIRE("Take bold action and express yourself confidently.", "साहसी कदम चाल्नुहोस् र आत्मविश्वासका साथ आफूलाई व्यक्त गर्नुहोस्।"),
ELEMENT_REC_EARTH("Focus on practical matters and material progress.", "व्यावहारिक मामिलाहरू र भौतिक प्रगतिमा ध्यान दिनुहोस्।"),
ELEMENT_REC_AIR("Engage in social activities and intellectual pursuits.", "सामाजिक गतिविधिहरू र बौद्धिक प्रयासहरूमा संलग्न हुनुहोस्।"),
ELEMENT_REC_WATER("Trust your intuition and honor your emotions.", "आफ्नो अन्तर्ज्ञानमाथि विश्वास गर्नुहोस् र आफ्ना भावनाहरूलाई सम्मान गर्नुहोस्।"),
AREA_REC_CAREER("Capitalize on favorable career energy today.", "आज अनुकूल क्यारियर ऊर्जाको फाइदा उठाउनुहोस्।"),
AREA_REC_LOVE("Nurture your relationships with extra attention.", "थप ध्यानका साथ आफ्ना सम्बन्धहरूलाई पोषण गर्नुहोस्।"),
AREA_REC_HEALTH("Make the most of your vibrant health energy.", "आफ्नो जीवन्त स्वास्थ्य ऊर्जाको अधिकतम फाइदा लिनुहोस्।"),
AREA_REC_FINANCE("Take advantage of positive financial influences.", "सकारात्मक वित्तीय प्रभावहरूको फाइदा उठाउनुहोस्।"),
AREA_REC_FAMILY("Spend quality time with family members.", "परिवारका सदस्यहरूसँग गुणस्तरीय समय बिताउनुहोस्।"),
AREA_REC_SPIRITUALITY("Deepen your spiritual practices.", "आफ्नो आध्यात्मिक अभ्यासहरूलाई गहिरो बनाउनुहोस्।"),
CAUTION_SATURN("Avoid rushing into decisions. Patience is key.", "निर्णयहरूमा हतार नगर्नुहोस्। धैर्य महत्त्वपूर्ण छ।"),
CAUTION_MARS("Control impulsive reactions and avoid conflicts.", "आवेगपूर्ण प्रतिक्रियाहरू नियन्त्रण गर्नुहोस् र विवादहरूबाट बच्नुहोस्।"),
CAUTION_RAHU("Be wary of deception and unrealistic expectations.", "छलकपट र अवास्तविक अपेक्षाहरूबाट सावधान रहनुहोस्।"),
CAUTION_KETU("Don't neglect practical responsibilities for escapism.", "पलायनवादको लागि व्यावहारिक जिम्मेवारीहरूलाई बेवास्ता नगर्नुहोस्।"),
HOROSCOPE_BALANCE("Balance", "सन्तुलन"),
HOROSCOPE_STEADY_ENERGY("Steady energy expected", "स्थिर ऊर्जा अपेक्षित"),
HOROSCOPE_CALCULATING("Calculating...", "गणना गर्दै..."),
HOROSCOPE_VEDHA_OBSTRUCTION("However, %s creates Vedha obstruction, reducing benefits.", "तर, %s ले वेध अवरोध सिर्जना गर्छ, फाइदाहरू घटाउँछ।"),
    HOROSCOPE_ASHTAKAVARGA_STRONG("Ashtakavarga (%d/8)", "Ashtakavarga (%d/8)"),
    HOROSCOPE_ASHTAKAVARGA_MODERATE("Ashtakavarga (%d/8)", "Ashtakavarga (%d/8)"),
    HOROSCOPE_ASHTAKAVARGA_WEAK("Low Ashtakavarga (%d/8)", "Low Ashtakavarga (%d/8)"),
HOROSCOPE_RETROGRADE_DELAY("%s's retrograde motion delays manifestation.", "%s को वक्री गतिले प्रकटीकरणमा ढिलाइ गर्छ।"),
HOROSCOPE_RETROGRADE_RELIEF("%s's retrograde provides some relief from challenges.", "%s को वक्रीले चुनौतीहरूबाट केही राहत प्रदान गर्छ।"),
HOROSCOPE_OWN_SIGN("Strong in own sign.", "आफ्नै राशिमा बलियो।"),
HOROSCOPE_EXALTED("Exalted - excellent results.", "उच्च - उत्कृष्ट परिणामहरू।"),
HOROSCOPE_DEBILITATED("Debilitated - results weakened.", "नीच - परिणामहरू कमजोर।"),
HOROSCOPE_FAVORABLE_TRANSIT("Favorable %s transit in house %d.", "भाव %d मा अनुकूल %s गोचर।"),
HOROSCOPE_UNFAVORABLE_TRANSIT("Challenging %s transit in house %d.", "भाव %d मा चुनौतीपूर्ण %s गोचर।"),
HOROSCOPE_BALANCED_ENERGY("Balanced energy in this area.", "यस क्षेत्रमा सन्तुलित ऊर्जा।"),
SETTINGS_PROFILE("Profile", "प्रोफाइल"),
SETTINGS_EXPORT("Export", "निर्यात"),
SETTINGS_AI_CHAT("AI & Chat", "AI र च्याट"),
SETTINGS_AI_MODELS("AI Models", "AI मोडेलहरू"),
SETTINGS_AI_MODELS_DESC("Configure chat AI providers", "च्याट AI प्रदायकहरू कन्फिगर गर्नुहोस्"),
SETTINGS_PREFERENCES("Preferences", "प्राथमिकताहरू"),
SETTINGS_ABOUT("About", "बारेमा"),
SETTINGS_EDIT_PROFILE("Edit Profile", "प्रोफाइल सम्पादन"),
SETTINGS_EDIT_PROFILE_DESC("Modify birth details", "जन्म विवरण परिमार्जन गर्नुहोस्"),
SETTINGS_MANAGE_PROFILES("Manage Profiles", "प्रोफाइलहरू व्यवस्थापन"),
SETTINGS_NO_PROFILE("No profile selected", "कुनै प्रोफाइल छानिएको छैन"),
SETTINGS_TAP_TO_SELECT("Tap to select or create a profile", "प्रोफाइल छान्न वा बनाउन ट्याप गर्नुहोस्"),
SETTINGS_EXPORT_PDF("Export as PDF", "PDF को रूपमा निर्यात"),
SETTINGS_EXPORT_PDF_DESC("Complete chart report", "पूर्ण कुण्डली रिपोर्ट"),
SETTINGS_EXPORT_IMAGE("Export as Image", "छविको रूपमा निर्यात"),
SETTINGS_EXPORT_IMAGE_DESC("High-quality chart image", "उच्च गुणस्तर कुण्डली छवि"),
SETTINGS_EXPORT_JSON("Export as JSON", "JSON को रूपमा निर्यात"),
SETTINGS_EXPORT_JSON_DESC("Machine-readable format", "मेसिन-पठनयोग्य ढाँचा"),
SETTINGS_EXPORT_CSV("CSV Data", "CSV डाटा"),
SETTINGS_EXPORT_CSV_DESC("Spreadsheet format", "स्प्रेडसिट ढाँचा"),
SETTINGS_HOUSE_SYSTEM("House System", "भाव पद्धति"),
SETTINGS_AYANAMSA("Ayanamsa", "अयनांश"),
SETTINGS_LANGUAGE("Language", "भाषा"),
SETTINGS_DATE_SYSTEM("Date System", "मिति प्रणाली"),
SETTINGS_THEME("Theme", "थिम"),
SETTINGS_NODE_CALCULATION("Node Calculation", "राहु-केतु गणना"),
SETTINGS_NODE_MEAN("Mean Node", "मध्यम राहु"),
SETTINGS_NODE_TRUE("True Node", "स्पष्ट राहु"),
THEME_LIGHT("Light", "उज्यालो"),
THEME_LIGHT_DESC("Always use light theme", "सधैं उज्यालो थिम प्रयोग गर्नुहोस्"),
THEME_DARK("Dark", "अँध्यारो"),
THEME_DARK_DESC("Always use dark theme", "सधैं अँध्यारो थिम प्रयोग गर्नुहोस्"),
THEME_SYSTEM("System", "प्रणाली"),
THEME_SYSTEM_DESC("Follow device settings", "यन्त्र सेटिङ्स पछ्याउनुहोस्"),
SETTINGS_ABOUT_APP("About AstroStorm", "AstroStorm बारेमा"),
SETTINGS_VERSION("Version %s", "संस्करण %s"),
SETTINGS_CALC_ENGINE("Calculation Engine", "गणना इन्जिन"),
    SETTINGS_CALC_ENGINE_DESC("Swiss Ephemeris (JPL Mode)", "Swiss Ephemeris (JPL Mode)"),
SETTINGS_APP_TAGLINE("Ultra-Precision Vedic Astrology", "अति-सटीक वैदिक ज्योतिष"),
SETTINGS_APP_DESC("Powered by Swiss Ephemeris with JPL planetary data for astronomical-grade accuracy in all calculations.", "सबै गणनाहरूमा खगोलीय-ग्रेड सटीकताको लागि JPL ग्रह डाटासहित स्विस ईफेमेरिसद्वारा संचालित।"),
SETTINGS_LAHIRI("Lahiri Ayanamsa", "लहिरी अयनांश"),
SETTINGS_PLACIDUS("Placidus Houses", "प्लासिडस भावहरू"),
DIALOG_DELETE_PROFILE("Delete Profile", "प्रोफाइल मेट्नुहोस्"),
DIALOG_DELETE_CONFIRM("Are you sure you want to delete %s? This action cannot be undone.", "के तपाईं %s मेट्न चाहनुहुन्छ? यो कार्य पूर्ववत गर्न सकिँदैन।"),
DIALOG_EXPORT_CHART("Export Chart", "कुण्डली निर्यात गर्नुहोस्"),
CHART_ASCENDANT("Ascendant", "लग्न"),
CHART_MOON_SIGN("Moon Sign", "चन्द्र राशि"),
CHART_NAKSHATRA("Nakshatra", "नक्षत्र"),
MISC_INFO("Information", "जानकारी"),
INPUT_NEW_CHART("New Birth Chart", "नयाँ जन्म कुण्डली"),
INPUT_EDIT_CHART("Edit Birth Chart", "जन्म कुण्डली सम्पादन"),
INPUT_IDENTITY("Identity", "पहिचान"),
INPUT_DATE_TIME("Date & Time", "मिति र समय"),
INPUT_COORDINATES("Coordinates", "निर्देशांकहरू"),
INPUT_FULL_NAME("Full name", "पूरा नाम"),
INPUT_GENDER("Gender", "लिङ्ग"),
INPUT_LOCATION("Location", "स्थान"),
INPUT_SEARCH_LOCATION("Search city or enter manually", "शहर खोज्नुहोस् वा म्यानुअल रूपमा प्रविष्ट गर्नुहोस्"),
INPUT_TIMEZONE("Timezone", "समय क्षेत्र"),
INPUT_LATITUDE("Latitude", "अक्षांश"),
INPUT_LONGITUDE("Longitude", "देशान्तर"),
    INPUT_ALTITUDE("Altitude (m)", "Altitude (m)"),
INPUT_SELECT_DATE("Select date", "मिति छान्नुहोस्"),
INPUT_SELECT_TIME("Select time", "समय छान्नुहोस्"),
LOCATION_SEARCH("Search location", "स्थान खोज्नुहोस्"),
LOCATION_PLACEHOLDER("Enter city or place name", "शहर वा ठाउँको नाम प्रविष्ट गर्नुहोस्"),
LOCATION_CLEAR("Clear search", "खोज हटाउनुहोस्"),
LOCATION_SELECT("Select %s", "%s छान्नुहोस्"),
EDIT_PROFILE_TITLE("Edit Profile", "प्रोफाइल सम्पादन"),
EDIT_PROFILE_NO_DATA("No chart data available. Please select a profile to edit.", "कुनै कुण्डली डाटा उपलब्ध छैन। कृपया सम्पादन गर्न प्रोफाइल छान्नुहोस्।"),
CHART_HOUSE("House", "भाव"),
PLANET_RETROGRADE("Retrograde", "वक्री"),
    PLANET_RETROGRADE_SHORT("(R)", "(R)"),
UNIT_RUPAS("rupas", "रुपास"),
UNIT_DAYS("days", "दिन"),
UNIT_MONTHS("months", "महिना"),
UNIT_YEARS("years", "वर्ष"),
PLANET_IN_SIGN_ACCESSIBILITY("%1\$s in %2\$s", "%2\$sमा %1\$s"),
PLANET("Planet", "ग्रह"),
PLANET_SUN("Sun", "सूर्य"),
PLANET_MOON("Moon", "चन्द्र"),
PLANET_MERCURY("Mercury", "बुध"),
PLANET_VENUS("Venus", "शुक्र"),
PLANET_MARS("Mars", "मंगल"),
PLANET_JUPITER("Jupiter", "बृहस्पति"),
PLANET_SATURN("Saturn", "शनि"),
PLANET_RAHU("Rahu", "राहु"),
PLANET_KETU("Ketu", "केतु"),
PLANET_URANUS("Uranus", "युरेनस"),
PLANET_NEPTUNE("Neptune", "नेप्च्युन"),
PLANET_PLUTO("Pluto", "प्लुटो"),
SIGN_ARIES("Aries", "मेष"),
SIGN_TAURUS("Taurus", "वृष"),
SIGN_GEMINI("Gemini", "मिथुन"),
SIGN_CANCER("Cancer", "कर्कट"),
SIGN_LEO("Leo", "सिंह"),
SIGN_VIRGO("Virgo", "कन्या"),
SIGN_LIBRA("Libra", "तुला"),
SIGN_SCORPIO("Scorpio", "वृश्चिक"),
SIGN_SAGITTARIUS("Sagittarius", "धनु"),
SIGN_CAPRICORN("Capricorn", "मकर"),
SIGN_AQUARIUS("Aquarius", "कुम्भ"),
SIGN_PISCES("Pisces", "मीन"),
HOUSE_PLACIDUS("Placidus", "प्लासिडस"),
HOUSE_KOCH("Koch", "कोच"),
HOUSE_PORPHYRIUS("Porphyrius", "पोर्फिरियस"),
HOUSE_REGIOMONTANUS("Regiomontanus", "रेजिओमोन्टानस"),
HOUSE_CAMPANUS("Campanus", "क्याम्पानस"),
HOUSE_EQUAL("Equal", "समान"),
HOUSE_WHOLE_SIGN("Whole Sign", "सम्पूर्ण राशि"),
HOUSE_VEHLOW("Vehlow", "भेहलो"),
HOUSE_MERIDIAN("Meridian", "मेरिडियन"),
HOUSE_MORINUS("Morinus", "मोरिनस"),
HOUSE_ALCABITUS("Alcabitus", "अल्काबिटस"),
AYANAMSA_LAHIRI("Lahiri", "लहिरी"),
AYANAMSA_RAMAN("Raman", "रमण"),
AYANAMSA_KRISHNAMURTI("Krishnamurti", "कृष्णमूर्ति"),
AYANAMSA_TRUE_CHITRAPAKSHA("True Chitrapaksha", "सत्य चित्रपक्ष"),
YOGAS_COUNT_DETECTED("%1\$d yogas detected in %2\$s", "%2\$s मा %1\$d योगहरू पत्ता लागेको"),
PROFILE_SWITCH("Switch Profile", "प्रोफाइल बदल्नुहोस्"),
PROFILE_ADD_NEW("Add New Profile", "नयाँ प्रोफाइल थप्नुहोस्"),
PROFILE_ADD_NEW_CHART("Add new chart", "नयाँ कुण्डली थप्नुहोस्"),
PROFILE_CURRENT("Current", "हालको"),
PROFILE_NO_SAVED_CHARTS("No saved charts", "कुनै सुरक्षित कुण्डली छैन"),
PROFILE_ADD_FIRST_CHART("Add your first chart to get started", "सुरु गर्न आफ्नो पहिलो कुण्डली थप्नुहोस्")
}
