package com.astro.storm.core.common
enum class StringKeyMuhurta(override val en: String, override val ne: String) : StringKeyInterface {
MUHURTA_TITLE("Muhurta Finder", "मुहूर्त खोजकर्ता"),
MUHURTA_SELECT_EVENT("Select Event Type", "घटना प्रकार छान्नुहोस्"),
MUHURTA_DATE_RANGE("Date Range", "मिति दायरा"),
MUHURTA_FIND("Find Auspicious Times", "शुभ समय खोज्नुहोस्"),
MUHURTA_RESULTS("Auspicious Muhurtas", "शुभ मुहूर्तहरू"),
MUHURTA_PREV_DAY("Previous day", "अघिल्लो दिन"),
MUHURTA_NEXT_DAY("Next day", "अर्को दिन"),
MUHURTA_CALCULATING("Calculating muhurta...", "मुहूर्त गणना गर्दै..."),
MUHURTA_ERROR("Something went wrong", "केही गलत भयो"),
MUHURTA_SCORE("Score", "अंक"),
MUHURTA_AUSPICIOUS_TIME("Auspicious Time", "शुभ समय"),
MUHURTA_AVERAGE_TIME("Average Time", "सामान्य समय"),
MUHURTA_PANCHANGA("Panchanga", "पञ्चाङ्ग"),
MUHURTA_INAUSPICIOUS_PERIODS("Inauspicious Periods", "अशुभ अवधिहरू"),
MUHURTA_RAHUKALA("Rahukala", "राहुकाल"),
MUHURTA_RAHUKALA_DESC("Avoid important work", "महत्त्वपूर्ण कार्य बच्नुहोस्"),
MUHURTA_YAMAGHANTA("Yamaghanta", "यमघन्ता"),
MUHURTA_YAMAGHANTA_DESC("Avoid travel", "यात्रा बच्नुहोस्"),
MUHURTA_GULIKA_KALA("Gulika Kala", "गुलिक काल"),
MUHURTA_GULIKA_KALA_DESC("Avoid new beginnings", "नयाँ शुरुआत बच्नुहोस्"),
MUHURTA_ACTIVE("ACTIVE", "सक्रिय"),
MUHURTA_DAY_CHOGHADIYA("Day Choghadiya", "दिनको चोघड़िया"),
MUHURTA_PERIODS("%d periods", "%d अवधिहरू"),
MUHURTA_NOW("NOW", "अहिले"),
MUHURTA_FROM("From", "बाट"),
MUHURTA_TO("To", "सम्म"),
MUHURTA_SEARCHING("Searching...", "खोज्दै..."),
MUHURTA_FIND_DATES("Find Auspicious Dates", "शुभ मिति खोज्नुहोस्"),
MUHURTA_FIND_AUSPICIOUS("Find Auspicious Dates", "शुभ मितिहरू खोज्नुहोस्"),
MUHURTA_SEARCH_EMPTY("Search for Auspicious Times", "शुभ समय खोज्नुहोस्"),
MUHURTA_SEARCH_HELP("Select an activity and date range to find the most favorable muhurtas", "सबैभन्दा अनुकूल मुहूर्तहरू खोज्न गतिविधि र मिति दायरा छान्नुहोस्"),
MUHURTA_FINDING("Finding auspicious times...", "शुभ समय खोज्दै..."),
MUHURTA_NO_RESULTS("No Auspicious Times Found", "कुनै शुभ समय फेला परेन"),
MUHURTA_NO_RESULTS_HELP("Try expanding your date range", "मिति दायरा विस्तार गर्ने प्रयास गर्नुहोस्"),
MUHURTA_SEARCH_ERROR("Search Failed", "खोज असफल"),
MUHURTA_RESULTS_TITLE("Auspicious Times", "शुभ समयहरू"),
MUHURTA_RESULTS_COUNT("%d found", "%d फेला परेको"),
MUHURTA_DETAIL_DAY("Day", "दिन"),
MUHURTA_DETAIL_CHOGHADIYA("Choghadiya", "चोघड़िया"),
MUHURTA_TODAY("Today", "आज"),
MUHURTA_PREV_DAY_A11Y("Previous day", "अघिल्लो दिन"),
MUHURTA_NEXT_DAY_A11Y("Next day", "अर्को दिन"),
MUHURTA_VARA("Vara", "वार"),
MUHURTA_TITHI("Tithi", "तिथि"),
MUHURTA_YOGA("Yoga", "योग"),
MUHURTA_KARANA("Karana", "करण"),
MUHURTA_SUNRISE_SUNSET("Sunrise / Sunset", "सूर्योदय / सूर्यास्त"),
MUHURTA_SELECT_ACTIVITY("Select Activity", "गतिविधि चयन गर्नुहोस्"),
MUHURTA_SUITABLE_ACTIVITIES("Suitable Activities", "उपयुक्त गतिविधिहरू"),
MUHURTA_AVOID_ACTIVITIES("Activities to Avoid", "बच्नुपर्ने गतिविधिहरू"),
MUHURTA_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
MUHURTA_DATE_RANGE_LABEL("Date Range", "मिति दायरा"),
MUHURTA_CHOGHADIYA_SUFFIX("Choghadiya: %s", "चौघडिया: %s"),
MUHURTA_HORA_SUFFIX("Hora: %s", "होरा: %s"),
MUHURTA_EVENT_MARRIAGE("Marriage", "विवाह"),
MUHURTA_EVENT_ENGAGEMENT("Engagement", "सगाई"),
MUHURTA_EVENT_GRIHA_PRAVESH("Griha Pravesh", "गृह प्रवेश"),
MUHURTA_EVENT_BUSINESS_START("Business Start", "व्यापार शुरुआत"),
MUHURTA_EVENT_TRAVEL("Travel", "यात्रा"),
MUHURTA_EVENT_VEHICLE_PURCHASE("Vehicle Purchase", "सवारी खरिद"),
MUHURTA_EVENT_EDUCATION_START("Education Start", "शिक्षा शुरुआत"),
MUHURTA_EVENT_MEDICAL_TREATMENT("Medical Treatment", "चिकित्सा उपचार"),
MUHURTA_EVENT_CONSTRUCTION("Construction", "निर्माण"),
MUHURTA_EVENT_INVESTMENT("Investment", "लगानी"),
MUHURTA_EVENT_NAME_CEREMONY("Name Ceremony", "नामकरण"),
MUHURTA_EVENT_MUNDAN("Mundan", "चौलकर्म"),
MUHURTA_EVENT_UPANAYANA("Upanayana", "ब्रतबन्ध"),
MUHURTA_CHOGHADIYA("Choghadiya", "चौघडिया"),
MUHURTA_RAHU_KAAL("Rahu Kaal", "राहुकाल"),
MUHURTA_YAMA_GHANTAKA("Yama Ghantaka", "यम घण्टक"),
MUHURTA_GULIKA_KAAL("Gulika Kaal", "गुलिका काल"),
MUHURTA_ABHIJIT("Abhijit Muhurta", "अभिजित मुहूर्त"),
MUHURTA_BRAHMA("Brahma Muhurta", "ब्रह्म मुहूर्त"),
MUHURTA_SELECT_DATE("Select Date", "मिति चयन गर्नुहोस्"),
MUHURTA_SEARCH_RESULTS("Search Results", "खोज परिणामहरू")
}
