package com.astro.storm.core.common

/**
 * Localization keys for Tarabala and Chandrabala recommendations
 */
enum class StringKeyTarabala(override val en: String, override val ne: String) : StringKeyInterface {
TARA_JANMA_REC_1("Birth star day - rest and introspection recommended", "जन्म नक्षत्रको दिन - आराम र आत्मनिरीक्षण सिफारिस गरिएको छ"),
TARA_JANMA_REC_2("Avoid starting new ventures", "नयाँ उद्यमहरू सुरु गर्नबाट बच्नुहोस्"),
TARA_JANMA_REC_3("Good for spiritual practices and meditation", "आध्यात्मिक अभ्यास र ध्यानको लागि राम्रो"),
TARA_JANMA_REC_4("Health requires extra attention", "स्वास्थ्यमा अतिरिक्त ध्यान आवश्यक छ"),
TARA_SAMPAT_REC_1("Excellent for financial matters", "वित्तीय मामिलाहरूको लागि उत्कृष्ट"),
TARA_SAMPAT_REC_2("Start wealth-generating activities", "धन उत्पन्न गर्ने गतिविधिहरू सुरु गर्नुहोस्"),
TARA_SAMPAT_REC_3("Good for investments and purchases", "लगानी र खरिदको लागि राम्रो"),
TARA_SAMPAT_REC_4("Favorable for business negotiations", "व्यापारिक वार्ताको लागि अनुकूल"),
TARA_VIPAT_REC_1("Avoid important decisions", "महत्त्वपूर्ण निर्णयहरू लिनबाट बच्नुहोस्"),
TARA_VIPAT_REC_2("Be cautious in travels", "यात्रामा सावधान रहनुहोस्"),
TARA_VIPAT_REC_3("Not suitable for new beginnings", "नयाँ सुरुवातका लागि उपयुक्त छैन"),
TARA_VIPAT_REC_4("Focus on routine activities only", "नियमित गतिविधिहरूमा मात्र ध्यान दिनुहोस्"),
TARA_KSHEMA_REC_1("Good for health-related activities", "स्वास्थ्य सम्बन्धी गतिविधिहरूको लागि राम्रो"),
TARA_KSHEMA_REC_2("Favorable for medical treatments", "चिकित्सा उपचारको लागि अनुकूल"),
TARA_KSHEMA_REC_3("Support well-being initiatives", "कल्याणकारी पहलहरूलाई समर्थन गर्नुहोस्"),
TARA_KSHEMA_REC_4("Safe for moderate new undertakings", "मध्यम नयाँ उपक्रमहरूको लागि सुरक्षित"),
TARA_PRATYARI_REC_1("Expect minor obstacles", "सानो बाधाहरूको अपेक्षा गर्नुहोस्"),
TARA_PRATYARI_REC_2("Stay patient with challenges", "चुनौतीहरूको साथ धैर्यवान रहनुहोस्"),
TARA_PRATYARI_REC_3("Avoid confrontations", "द्वन्द्वबाट बच्नुहोस्"),
TARA_PRATYARI_REC_4("Not ideal for important meetings", "महत्त्वपूर्ण बैठकहरूको लागि आदर्श छैन"),
TARA_SADHAKA_REC_1("Good for achieving goals", "लक्ष्यहरू प्राप्त गर्नका लागि राम्रो"),
TARA_SADHAKA_REC_2("Favorable for completing tasks", "कार्यहरू पूरा गर्नका लागि अनुकूल"),
TARA_SADHAKA_REC_3("Support ongoing projects", "चलिरहेका परियोजनाहरूलाई समर्थन गर्नुहोस्"),
TARA_SADHAKA_REC_4("Moderate success in new ventures", "नयाँ उद्यमहरूमा मध्यम सफलता"),
TARA_VADHA_REC_1("Most inauspicious tara - maximum caution", "सबैभन्दा अशुभ तारा - अधिकतम सावधानी"),
TARA_VADHA_REC_2("Avoid all major activities", "सबै प्रमुख गतिविधिहरूबाट बच्नुहोस्"),
TARA_VADHA_REC_3("Not suitable for travel or surgery", "यात्रा वा शल्यक्रियाका लागि उपयुक्त छैन"),
TARA_VADHA_REC_4("Focus on prayers and spiritual protection", "प्रार्थना र आध्यात्मिक सुरक्षामा ध्यान दिनुहोस्"),
TARA_MITRA_REC_1("Favorable for relationships", "सम्बन्धका लागि अनुकूल"),
TARA_MITRA_REC_2("Good for meetings and collaborations", "बैठक र सहयोगका लागि राम्रो"),
TARA_MITRA_REC_3("Support partnerships and friendships", "साझेदारी र मित्रतालाई समर्थन गर्नुहोस्"),
TARA_MITRA_REC_4("Suitable for social activities", "सामाजिक गतिविधिहरूको लागि उपयुक्त"),
TARA_PARAMA_MITRA_REC_1("Most auspicious tara - excellent for everything", "सबैभन्दा शुभ तारा - सबै कुराका लागि उत्कृष्ट"),
TARA_PARAMA_MITRA_REC_2("Ideal for starting new ventures", "नयाँ उद्यमहरू सुरु गर्नका लागि आदर्श"),
TARA_PARAMA_MITRA_REC_3("Best time for important decisions", "महत्त्वपूर्ण निर्णयहरूको लागि उत्तम समय"),
TARA_PARAMA_MITRA_REC_4("Maximum success probability", "अधिकतम सफलताको सम्भावना"),
CHANDRA_REC_1_1("Personal matters are neutral", "व्यक्तिगत मामिलाहरू तटस्थ छन्"),
CHANDRA_REC_1_2("Self-reflection day", "आत्म-चिन्तन गर्ने दिन"),
CHANDRA_REC_1_3("Health awareness needed", "स्वास्थ्य सचेतना आवश्यक छ"),
CHANDRA_REC_2_1("Good for family matters", "पारिवारिक मामिलाहरूको लागि राम्रो"),
CHANDRA_REC_2_2("Favorable for financial discussions", "वित्तीय छलफलको लागि अनुकूल"),
CHANDRA_REC_2_3("Speech brings benefits", "वाणीले लाभ ल्याउँछ"),
CHANDRA_REC_3_1("Excellent courage and initiative", "उत्कृष्ट साहस र पहल"),
CHANDRA_REC_3_2("Best for bold actions", "साहसी कार्यहरूको लागि उत्तम"),
CHANDRA_REC_3_3("Travel is favorable", "यात्रा अनुकूल छ"),
CHANDRA_REC_3_4("Communications succeed", "सञ्चार सफल हुन्छ"),
CHANDRA_REC_4_1("Focus on home comforts", "घरको सुख-सुविधामा ध्यान दिनुहोस्"),
CHANDRA_REC_4_2("Mother may need attention", "आमालाई ध्यान दिनुपर्ने हुन सक्छ"),
CHANDRA_REC_4_3("Avoid property decisions", "सम्पत्ति सम्बन्धी निर्णयहरूबाट बच्नुहोस्"),
CHANDRA_REC_5_1("Intelligence enhanced", "बुद्धिमत्ता बढ्छ"),
CHANDRA_REC_5_2("Good for education", "शिक्षाका लागि राम्रो"),
CHANDRA_REC_5_3("Children bring joy", "सन्तानले खुशी ल्याउँछन्"),
CHANDRA_REC_5_4("Romance may blossom", "रोमान्स फस्टाउन सक्छ"),
CHANDRA_REC_6_1("Victory over enemies", "शत्रुहरूमाथि विजय"),
CHANDRA_REC_6_2("Competitions favored", "प्रतिस्पर्धाहरू अनुकूल छन्"),
CHANDRA_REC_6_3("Health improves", "स्वास्थ्यमा सुधार हुन्छ"),
CHANDRA_REC_6_4("Service brings rewards", "सेवाले पुरस्कार ल्याउँछ"),
CHANDRA_REC_7_1("Partnerships favorable", "साझेदारीहरू अनुकूल छन्"),
CHANDRA_REC_7_2("Business dealings good", "व्यापारिक कारोबार राम्रो छ"),
CHANDRA_REC_7_3("Marriage matters positive", "विवाह सम्बन्धी मामिलाहरू सकारात्मक छन्"),
CHANDRA_REC_8_1("Avoid risky activities", "जोखिमपूर्ण गतिविधिहरूबाट बच्नुहोस्"),
CHANDRA_REC_8_2("Hidden matters surface", "लुकेका कुराहरू सतहमा आउँछन्"),
CHANDRA_REC_8_3("Transformation possible", "रूपान्तरण सम्भव छ"),
CHANDRA_REC_8_4("Caution advised", "सावधानी अपनाउन सल्लाह दिइन्छ"),
CHANDRA_REC_9_1("Fortune smiles", "भाग्य मुस्कुराउँछ"),
CHANDRA_REC_9_2("Long journeys favorable", "लामो यात्राहरू अनुकूल छन्"),
CHANDRA_REC_9_3("Spiritual growth", "आध्यात्मिक वृद्धि"),
CHANDRA_REC_9_4("Father may help", "बुबाले मद्दत गर्न सक्नुहुन्छ"),
CHANDRA_REC_10_1("Career advancement", "क्यारियर प्रगति"),
CHANDRA_REC_10_2("Professional success", "व्यावसायिक सफलता"),
CHANDRA_REC_10_3("Authority recognition", "अधिकारको मान्यता"),
CHANDRA_REC_10_4("Best for work matters", "कामका मामिलाहरूको लागि उत्तम"),
CHANDRA_REC_11_1("Maximum gains possible", "अधिकतम लाभ सम्भव छ"),
CHANDRA_REC_11_2("Friends bring opportunities", "साथीहरूले अवसर ल्याउँछन्"),
CHANDRA_REC_11_3("Wishes get fulfilled", "इच्छाहरू पूरा हुन्छन्"),
CHANDRA_REC_11_4("Income increases", "आय बढ्छ"),
CHANDRA_REC_12_1("Expenses may increase", "खर्च बढ्न सक्छ"),
CHANDRA_REC_12_2("Rest and recuperation needed", "आराम र स्वास्थ्य लाभ आवश्यक छ"),
CHANDRA_REC_12_3("Spiritual practices beneficial", "आध्यात्मिक अभ्यासहरू लाभदायक छन्"),
CHANDRA_REC_12_4("Foreign matters need care", "विदेशी मामिलामा ध्यान दिनुहोस्"),
NEUTRAL_INFLUENCES("Neutral influences", "तटस्थ प्रभावहरू"),
ACTIVITY_START_BUSINESS("Starting new business", "नयाँ व्यवसाय सुरु गर्दै"),
REASON_TARA_CHANDRA_SUPPORT("Both Tara and Chandra support new beginnings", "तारा र चन्द्र दुवैले नयाँ सुरुवातलाई समर्थन गर्दछ"),
ACTIVITY_IMPORTANT_MEETINGS("Important meetings", "महत्त्वपूर्ण बैठकहरू"),
REASON_COMM_ENHANCED("Communication enhanced", "सञ्चार बढाइएको छ"),
ACTIVITY_FINANCIAL_INVEST("Financial investments", "वित्तीय लगानी"),
REASON_WEALTH_FAVORED("Wealth matters favored", "धनको मामिलामा अनुकूल"),
ACTIVITY_MEDICAL_TREATMENT("Medical treatments", "चिकित्सा उपचार"),
REASON_HEALTH_SUPPORTED("Health matters supported", "स्वास्थ्य मामिलाहरू समर्थित"),
ACTIVITY_TRAVEL("Travel", "यात्रा"),
REASON_JOURNEYS_SUCCESS("Journeys will be successful", "यात्राहरू सफल हुनेछन्"),
ACTIVITY_MARRIAGE("Marriage ceremonies", "विवाह समारोह"),
REASON_AUSPICIOUS_UNIONS("Auspicious for unions", "मिलनका लागि शुभ"),
ACTIVITY_BUSINESS_ACT("Business activities", "व्यापारिक गतिविधिहरू"),
REASON_GENERALLY_SUPPORTIVE("Generally supportive", "सामान्यतया समर्थनात्मक"),
ACTIVITY_ROUTINE_WORK("Routine work", "नियमित काम"),
REASON_PRODUCTIVITY_ENHANCED("Productivity enhanced", "उत्पादकता बढाइएको छ"),
ACTIVITY_SHORT_TRAVEL("Short travels", "छोटो यात्राहरू"),
REASON_SAFE_JOURNEYS("Safe for journeys", "यात्राको लागि सुरक्षित"),
ACTIVITY_SOCIAL_EVENTS("Social events", "सामाजिक कार्यक्रमहरू"),
REASON_RELATIONSHIPS_FAVORED("Relationships favored", "सम्बन्धहरूको लागि अनुकूल"),
ACTIVITY_HIGH_RISK_INVEST("High-risk investments", "उच्च जोखिमको लगानी"),
REASON_NOT_BEST_SPECULATION("Not the best time for speculation", "सट्टेबाजीको लागि उत्तम समय होइन"),
ACTIVITY_ROUTINE_ACT("Routine activities", "नियमित गतिविधिहरू"),
REASON_NORMAL_PRODUCTIVITY("Normal productivity expected", "सामान्य उत्पादकता अपेक्षित छ"),
ACTIVITY_ONGOING_PROJECTS("Ongoing projects", "चलिरहेका परियोजनाहरू"),
REASON_CONTINUE_WORK("Continue existing work", "अवस्थित काम जारी राख्नुहोस्"),
ACTIVITY_NEW_VENTURES("New ventures", "नयाँ उद्यमहरू"),
REASON_WAIT_BETTER_TIMING("Wait for better timing", "राम्रो समयको लागि पर्खनुहोस्"),
ACTIVITY_MAJOR_PURCHASES("Major purchases", "ठूला खरिदहरू"),
REASON_DELAYS_POSSIBLE("Delays possible", "ढिलाइ हुन सक्छ"),
ACTIVITY_IMPORTANT_NEGOTIATIONS("Important negotiations", "महत्त्वपूर्ण वार्ता"),
REASON_MIXED_RESULTS("Mixed results likely", "मिश्रित परिणामको सम्भावना"),
ACTIVITY_SPIRITUAL_PRACTICES("Spiritual practices", "आध्यात्मिक अभ्यासहरू"),
REASON_INNER_WORK_BENEFICIAL("Inner work beneficial", "आन्तरिक कार्य लाभदायक"),
ACTIVITY_REST_RECOVERY("Rest and recovery", "आराम र स्वास्थ्य लाभ"),
REASON_REJUVENATION_FAVORED("Rejuvenation favored", "पुनरुत्थानका लागि अनुकूल"),
ACTIVITY_NEW_BEGINNINGS("New beginnings", "नयाँ सुरुवात"),
REASON_OBSTACLES_LIKELY("Obstacles likely", "बाधाहरूको सम्भावना"),
REASON_DELAYS_PROBLEMS("Delays and problems possible", "ढिलाइ र समस्याहरू सम्भव छ"),
ACTIVITY_IMPORTANT_DECISIONS("Important decisions", "महत्त्वपूर्ण निर्णयहरू"),
REASON_JUDGMENT_CLOUDED("Judgment may be clouded", "निर्णय धमिलो हुन सक्छ"),
ACTIVITY_MEDICAL_PROCEDURES("Medical procedures", "चिकित्सा प्रक्रियाहरू"),
REASON_UNLESS_EMERGENCY("Unless emergency", "संकट बाहेक"),
ACTIVITY_PRAYER_MEDITATION("Prayers and meditation", "प्रार्थना र ध्यान"),
REASON_SPIRITUAL_PROT_NEEDED("Spiritual protection needed", "आध्यात्मिक सुरक्षा आवश्यक छ"),
ACTIVITY_CHARITY("Charity", "दान"),
REASON_REDUCES_NEG_KARMA("Reduces negative karma", "नकारात्मक कर्म कम गर्दछ"),
ACTIVITY_MAJOR_ACT("All major activities", "सबै प्रमुख गतिविधिहरू"),
REASON_DAY_INAUSPICIOUS("Day is inauspicious", "दिन अशुभ छ"),
REASON_ACCIDENTS_LIKELY("Accidents/problems likely", "दुर्घटना/समस्याको सम्भावना"),
ACTIVITY_CONTRACTS_AGREEMENTS("Contracts and agreements", "सम्झौता र सम्झौताहरू"),
REASON_NOT_BENEFICIAL("Will not be beneficial", "लाभदायक हुने छैन"),
REASON_FACE_DESTRUCTION("Will face destruction", "विनाशको सामना गर्नेछ"),
ACTIVITY_SURGERIES("Surgeries", "शल्यक्रियाहरू"),
REASON_UNLESS_LIFE_THREATENING("Unless life-threatening emergency", "जीवन-जोखिम संकट बाहेक"),
    ADVICE_HIGHLY_AUSPICIOUS("Today is highly auspicious with both Tarabala (%s)", "Today is highly auspicious with both Tarabala (%s)"),
ADVICE_FAVORABLE("Today offers good support from the cosmic energies. Tarabala is %s and Moon's position in the %dth house provides %s results. Proceed with confidence in normal activities.", "आज ब्रह्माण्डीय ऊर्जाहरूबाट राम्रो सहयोग मिल्नेछ। तारबल %s छ र चन्द्रमाको %dऔं भावमा स्थितिको कारण %s परिणाम मिल्नेछ। सामान्य गतिविधिहरू आत्मविश्वासका साथ अगाडि बढाउनुहोस्।"),
ADVICE_MIXED("Mixed influences today require balanced approach. While %s Tara brings %s, Chandrabala shows %s strength. Focus on routine matters and avoid extremes.", "आजको मिश्रित प्रभावले सन्तुलित दृष्टिकोणको आवश्यकता देखाउँछ। %s ताराले %s ल्याउँदा, चन्द्रबलले %s बल देखाउँछ। नियमित मामिलामा ध्यान दिनुहोस् र चरम सीमाबाट बच्नुहोस्।"),
ADVICE_CHALLENGING("Today presents challenges with %s Tara and Moon in %dth house. Exercise caution in all matters. Postpone important decisions if possible. Focus on spiritual practices and inner strength.", "आज %s तारा र %dऔं भावमा चन्द्रमा भएकाले चुनौतीहरू छन्। सबै कुरामा सावधानी अपनाउनुहोस्। सम्भव भएमा महत्त्वपूर्ण निर्णयहरू स्थगित गर्नुहोस्। आध्यात्मिक अभ्यास र आन्तरिक शक्तिमा ध्यान दिनुहोस्।"),
ADVICE_UNFAVORABLE("Caution advised today. The %s Tara combined with Moon's position creates unfavorable conditions. This is not suitable for any important activity. Focus on prayers, charity, and rest. Wait for better cosmic alignment before proceeding with significant matters.", "आज सावधानी अपनाउन सल्लाह दिइन्छ। %s तारा र चन्द्रमाको स्थितिले प्रतिकूल परिस्थिति सिर्जना गर्दछ। यो कुनै पनि महत्त्वपूर्ण गतिविधिको लागि उपयुक्त छैन। प्रार्थना, दान र आराममा ध्यान दिनुहोस्। महत्त्वपूर्ण कार्यहरू अघि बढाउनु अघि राम्रो समयको पर्खाइ गर्नुहोस्।"),
    ADVICE_WEEKLY_TEMPLATE("This week shows an average strength score of %d%%. %d out of 7 days are favorable for important activities. Best day is %s with %d%% strength. Avoid major decisions on %s (%d%% strength)", "This week shows an average strength score of %d%%. %d out of 7 days are favorable for important activities. Best day is %s with %d%% strength. Avoid major decisions on %s (%d%% strength)"),
SUPPORT_POSITIVE("positive", "सकारात्मक"),
SUPPORT_NEUTRAL("neutral", "तटस्थ"),
SUPPORT_SUPPORT("support", "सहयोग"),
SUPPORT_CHALLENGES("challenges", "चुनौतीहरू"),
HOUSE_SIG_1("Self, personality, physical body", "स्वयं, व्यक्तित्व, शरीर"),
HOUSE_SIG_2("Wealth, family, speech, food", "धन, परिवार, वाणी, भोजन"),
HOUSE_SIG_3("Courage, siblings, short journeys, communications", "साहस, भाइबहिनी, छोटो यात्रा, सञ्चार"),
HOUSE_SIG_4("Home, mother, comfort, vehicles", "घर, आमा, सुख-सुविधा, सवारी साधन"),
HOUSE_SIG_5("Children, intelligence, romance, creativity", "सन्तान, बुद्धिमत्ता, रोमान्स, सिर्जनशीलता"),
HOUSE_SIG_6("Enemies, diseases, debts, service", "शत्रु, रोग, ऋण, सेवा"),
HOUSE_SIG_7("Marriage, partnership, business, travel", "विवाह, साझेदारी, व्यापार, यात्रा"),
HOUSE_SIG_8("Longevity, obstacles, inheritance, transformation", "आयु, बाधा, विरासत, रूपान्तरण"),
HOUSE_SIG_9("Fortune, father, religion, long journeys", "भाग्य, पिता, धर्म, लामो यात्रा"),
HOUSE_SIG_10("Career, status, authority, profession", "क्यारियर, प्रतिष्ठा, अधिकार, पेशा"),
HOUSE_SIG_11("Gains, friends, aspirations, income", "लाभ, साथीहरू, आकांक्षा, आय"),
HOUSE_SIG_12("Losses, expenses, liberation, foreign", "हानि, खर्च, मोक्ष, विदेश"),
HOUSE_SIG_UNKNOWN("Unknown", "अज्ञात"),
REPORT_TITLE("TARABALA & CHANDRABALA ANALYSIS", "तारबल र चन्द्रबल विश्लेषण"),
REPORT_BIRTH_NAK("Birth Nakshatra:", "जन्म नक्षत्र:"),
REPORT_NATAL_MOON("Natal Moon Sign:", "जन्म चन्द्र राशि:"),
REPORT_ANALYSIS_DATE("Analysis Date:", "विश्लेषण मिति:"),
REPORT_TODAY_TARA("TODAY'S TARABALA", "आजको तारबल"),
REPORT_TRANSIT_NAK("Transit Nakshatra:", "गोचर नक्षत्र:"),
REPORT_TARA_LABEL("Tara:", "तारा:"),
REPORT_CYCLE_LABEL("Cycle:", "चक्र:"),
REPORT_FAVORABLE_LABEL("Favorable:", "अनुकूल:"),
REPORT_STRENGTH_LABEL("Strength:", "शक्ति:"),
REPORT_RECS_LABEL("Recommendations:", "सिफारिसहरू:"),
REPORT_TODAY_CHANDRA("TODAY'S CHANDRABALA", "आजको चन्द्रबल"),
REPORT_TRANSIT_MOON("Transit Moon:", "गोचर चन्द्र:"),
REPORT_HOUSE_FROM_MOON("House from Natal Moon:", "जन्म चन्द्रबाट भाव:"),
REPORT_SIGNIFICATIONS("Significations:", "कारकत्व:"),
REPORT_COMBINED_STRENGTH("COMBINED DAILY STRENGTH", "संयुक्त दैनिक शक्ति"),
REPORT_OVERALL_SCORE("Overall Score:", "समग्र स्कोर:"),
REPORT_GENERAL_ADVICE("General Advice:", "सामान्य सल्लाह:"),
REPORT_FAV_ACT("Favorable Activities:", "अनुकूल गतिविधिहरू:"),
REPORT_AVOID_ACT("Activities to Avoid:", "बच्नुपर्ने गतिविधिहरू:"),
REPORT_WEEKLY_FORECAST("WEEKLY FORECAST", "साप्ताहिक पूर्वानुमान"),
REPORT_BEST_DAY("Best Day:", "सबैभन्दा राम्रो दिन:"),
REPORT_AVOID_LABEL("Avoid:", "बच्नुहोस्:"),
REPORT_DAILY_FORECAST("Daily Forecast:", "दैनिक पूर्वानुमान:"),
REPORT_WEEKLY_ADVICE("Weekly Advice:", "साप्ताहिक सल्लाह:")
}
