package com.astro.storm.core.common
enum class StringKeyAnalysisPart2(override val en: String, override val ne: String) : StringKeyInterface {
ASHTAK_GUIDE_TRANSIT_1("Check SAV of the sign a planet transits", "ग्रहले गोचर गर्ने राशिको SAV जाँच गर्नुहोस्"),
ASHTAK_GUIDE_TRANSIT_2("Check BAV score of that planet in transited sign", "गोचर गरिएको राशिमा त्यो ग्रहको BAV स्कोर जाँच गर्नुहोस्"),
ASHTAK_GUIDE_TRANSIT_3("High combined scores = favorable transit", "उच्च संयुक्त स्कोर = अनुकूल गोचर"),
ASHTAK_GUIDE_TRANSIT_4("Use for timing important decisions", "महत्त्वपूर्ण निर्णयहरूको समयको लागि प्रयोग गर्नुहोस्"),
ASPECT_TYPE_CONJUNCTION("Conjunction", "युति"),
ASPECT_TYPE_7TH("7th Aspect", "सप्तम दृष्टि"),
ASPECT_TYPE_MARS_4TH("Mars 4th Aspect", "मंगलको चतुर्थ दृष्टि"),
ASPECT_TYPE_MARS_8TH("Mars 8th Aspect", "मंगलको अष्टम दृष्टि"),
ASPECT_TYPE_JUPITER_5TH("Jupiter 5th Aspect", "गुरुको पञ्चम दृष्टि"),
ASPECT_TYPE_JUPITER_9TH("Jupiter 9th Aspect", "गुरुको नवम दृष्टि"),
ASPECT_TYPE_SATURN_3RD("Saturn 3rd Aspect", "शनिको तृतीय दृष्टि"),
ASPECT_TYPE_SATURN_10TH("Saturn 10th Aspect", "शनिको दशम दृष्टि"),
    ASPECT_STRENGTH_EXACT("Exact (Purna)", "Exact (Purna)"),
    ASPECT_STRENGTH_ADHIKA("Strong (Adhika)", "Strong (Adhika)"),
    ASPECT_STRENGTH_MADHYA("Medium (Madhya)", "Medium (Madhya)"),
    ASPECT_STRENGTH_ALPA("Weak (Alpa)", "Weak (Alpa)"),
    ASPECT_STRENGTH_SUNYA("Negligible (Sunya)", "Negligible (Sunya)"),
ASPECT_CASTS_ON("%s casts %s on %s", "%s ले %s मा %s दृष्टि राख्छ"),
ASPECT_APPLYING("Applying", "समीप आउँदै"),
ASPECT_SEPARATING("Separating", "टाढा हुँदै"),
ASPECT_DRISHTI_BALA("Drishti Bala", "दृष्टि बल"),
ELEMENT_ETHER("Ether", "आकाश"),
PLANET_SUN_NATURE("Malefic", "पापी"),
PLANET_SUN_ELEMENT("Fire", "अग्नि"),
PLANET_SUN_REPRESENTS_1("Soul, Self, Ego", "आत्मा, स्वयं, अहंकार"),
PLANET_SUN_REPRESENTS_2("Father, Authority Figures", "पिता, अधिकारीहरू"),
PLANET_SUN_REPRESENTS_3("Government, Power", "सरकार, शक्ति"),
PLANET_SUN_REPRESENTS_4("Health, Vitality", "स्वास्थ्य, जीवनशक्ति"),
PLANET_SUN_REPRESENTS_5("Fame, Recognition", "प्रसिद्धि, मान्यता"),
PLANET_SUN_BODY_PARTS("Heart, Spine, Right Eye, Bones", "हृदय, मेरुदण्ड, दाहिने आँखा, हड्डी"),
PLANET_SUN_PROFESSIONS("Government jobs, Politics, Medicine, Administration, Leadership roles", "सरकारी जागिर, राजनीति, चिकित्सा, प्रशासन, नेतृत्व भूमिकाहरू"),
PLANET_MOON_NATURE("Benefic", "शुभ"),
PLANET_MOON_ELEMENT("Water", "जल"),
PLANET_MOON_REPRESENTS_1("Mind, Emotions", "मन, भावनाहरू"),
PLANET_MOON_REPRESENTS_2("Mother, Nurturing", "आमा, पालनपोषण"),
PLANET_MOON_REPRESENTS_3("Public, Masses", "जनता, समुदाय"),
PLANET_MOON_REPRESENTS_4("Comforts, Happiness", "आराम, खुशी"),
PLANET_MOON_REPRESENTS_5("Memory, Imagination", "स्मृति, कल्पना"),
PLANET_MOON_BODY_PARTS("Mind, Left Eye, Breast, Blood, Fluids", "मन, बायाँ आँखा, स्तन, रगत, तरल पदार्थ"),
PLANET_MOON_PROFESSIONS("Nursing, Hotel industry, Shipping, Agriculture, Psychology", "नर्सिङ, होटल उद्योग, जहाजरानी, कृषि, मनोविज्ञान"),
PLANET_MARS_NATURE("Malefic", "पापी"),
PLANET_MARS_ELEMENT("Fire", "अग्नि"),
PLANET_MARS_REPRESENTS_1("Energy, Action, Courage", "ऊर्जा, कार्य, साहस"),
PLANET_MARS_REPRESENTS_2("Siblings, Younger Brothers", "भाइबहिनी, सानो भाइ"),
PLANET_MARS_REPRESENTS_3("Property, Land", "सम्पत्ति, जमिन"),
PLANET_MARS_REPRESENTS_4("Competition, Sports", "प्रतिस्पर्धा, खेलकुद"),
PLANET_MARS_REPRESENTS_5("Technical Skills", "प्राविधिक सीपहरू"),
PLANET_MARS_BODY_PARTS("Blood, Muscles, Marrow, Head injuries", "रगत, मांसपेशी, मज्जा, टाउकोमा चोटपटक"),
PLANET_MARS_PROFESSIONS("Military, Police, Surgery, Engineering, Sports, Real Estate", "सेना, प्रहरी, शल्यक्रिया, इन्जिनियरिङ, खेलकुद, घरजग्गा"),
PLANET_MERCURY_NATURE("Benefic", "शुभ"),
PLANET_MERCURY_ELEMENT("Earth", "पृथ्वी"),
PLANET_MERCURY_REPRESENTS_1("Intelligence, Communication", "बुद्धि, सञ्चार"),
PLANET_MERCURY_REPRESENTS_2("Learning, Education", "सिकाइ, शिक्षा"),
PLANET_MERCURY_REPRESENTS_3("Business, Trade", "व्यापार, व्यवसाय"),
PLANET_MERCURY_REPRESENTS_4("Writing, Speech", "लेखन, वाणी"),
PLANET_MERCURY_REPRESENTS_5("Siblings, Friends", "भाइबहिनी, साथीहरू"),
PLANET_MERCURY_BODY_PARTS("Nervous system, Skin, Speech, Hands", "स्नायु प्रणाली, छाला, वाणी, हातहरू"),
PLANET_MERCURY_PROFESSIONS("Writing, Teaching, Accounting, Trading, IT, Media", "लेखन, शिक्षण, लेखा, व्यापार, आईटी, मिडिया"),
PLANET_JUPITER_NATURE("Benefic", "शुभ"),
PLANET_JUPITER_ELEMENT("Ether", "आकाश"),
PLANET_JUPITER_REPRESENTS_1("Wisdom, Knowledge", "ज्ञान, विद्या"),
PLANET_JUPITER_REPRESENTS_2("Teachers, Gurus", "शिक्षकहरू, गुरुहरू"),
PLANET_JUPITER_REPRESENTS_3("Fortune, Luck", "भाग्य, किस्मत"),
PLANET_JUPITER_REPRESENTS_4("Children, Dharma", "सन्तान, धर्म"),
PLANET_JUPITER_REPRESENTS_5("Expansion, Growth", "विस्तार, वृद्धि"),
PLANET_JUPITER_BODY_PARTS("Liver, Fat tissue, Ears, Thighs", "कलेजो, बोसो, कान, जाँघ"),
PLANET_JUPITER_PROFESSIONS("Teaching, Law, Priesthood, Banking, Counseling", "शिक्षण, कानून, पुरोहित, बैंकिङ, परामर्श"),
PLANET_VENUS_NATURE("Benefic", "शुभ"),
PLANET_VENUS_ELEMENT("Water", "जल"),
PLANET_VENUS_REPRESENTS_1("Love, Beauty, Art", "प्रेम, सौन्दर्य, कला"),
PLANET_VENUS_REPRESENTS_2("Marriage, Relationships", "विवाह, सम्बन्धहरू"),
PLANET_VENUS_REPRESENTS_3("Luxuries, Comforts", "विलासिता, आराम"),
PLANET_VENUS_REPRESENTS_4("Vehicles, Pleasures", "सवारी, आनन्द"),
PLANET_VENUS_REPRESENTS_5("Creativity", "सिर्जनशीलता"),
PLANET_VENUS_BODY_PARTS("Reproductive system, Face, Skin, Throat", "प्रजनन प्रणाली, अनुहार, छाला, घाँटी"),
PLANET_VENUS_PROFESSIONS("Entertainment, Fashion, Art, Hospitality, Beauty industry", "मनोरञ्जन, फेसन, कला, आतिथ्य, सौन्दर्य उद्योग"),
PLANET_SATURN_NATURE("Malefic", "पापी"),
PLANET_SATURN_ELEMENT("Air", "वायु"),
PLANET_SATURN_REPRESENTS_1("Discipline, Hard work", "अनुशासन, कडा परिश्रम"),
PLANET_SATURN_REPRESENTS_2("Karma, Delays", "कर्म, ढिलाइ"),
PLANET_SATURN_REPRESENTS_3("Longevity, Service", "दीर्घायु, सेवा"),
PLANET_SATURN_REPRESENTS_4("Laborers, Servants", "श्रमिकहरू, सेवकहरू"),
PLANET_SATURN_REPRESENTS_5("Chronic issues", "दीर्घकालीन समस्याहरू"),
PLANET_SATURN_BODY_PARTS("Bones, Teeth, Knees, Joints, Nerves", "हड्डी, दाँत, घुँडा, जोर्नीहरू, स्नायु"),
PLANET_SATURN_PROFESSIONS("Mining, Agriculture, Labor, Judiciary, Real Estate", "खनन, कृषि, श्रम, न्यायपालिका, घरजग्गा"),
PLANET_RAHU_NATURE("Malefic", "पापी"),
PLANET_RAHU_ELEMENT("Air", "वायु"),
PLANET_RAHU_REPRESENTS_1("Obsession, Illusion", "जुनून, भ्रम"),
PLANET_RAHU_REPRESENTS_2("Foreign lands, Travel", "विदेश, यात्रा"),
PLANET_RAHU_REPRESENTS_3("Technology, Innovation", "प्रविधि, नवीनता"),
PLANET_RAHU_REPRESENTS_4("Unconventional paths", "अपरंपरागत मार्गहरू"),
PLANET_RAHU_REPRESENTS_5("Material desires", "भौतिक इच्छाहरू"),
PLANET_RAHU_BODY_PARTS("Skin diseases, Nervous disorders", "छालाका रोगहरू, स्नायु विकारहरू"),
PLANET_RAHU_PROFESSIONS("Technology, Foreign affairs, Aviation, Politics, Research", "प्रविधि, विदेशी मामिला, उड्डयन, राजनीति, अनुसन्धान"),
PLANET_KETU_NATURE("Malefic", "पापी"),
PLANET_KETU_ELEMENT("Fire", "अग्नि"),
PLANET_KETU_REPRESENTS_1("Spirituality, Liberation", "आध्यात्मिकता, मोक्ष"),
PLANET_KETU_REPRESENTS_2("Past life karma", "पूर्वजन्मको कर्म"),
PLANET_KETU_REPRESENTS_3("Detachment, Isolation", "वैराग्य, एकान्त"),
PLANET_KETU_REPRESENTS_4("Occult, Mysticism", "गुप्त विद्या, रहस्यवाद"),
PLANET_KETU_REPRESENTS_5("Healing abilities", "उपचार क्षमता"),
PLANET_KETU_BODY_PARTS("Skin, Spine, Nervous system", "छाला, मेरुदण्ड, स्नायु प्रणाली"),
PLANET_KETU_PROFESSIONS("Spirituality, Research, Healing, Astrology, Philosophy", "आध्यात्मिकता, अनुसन्धान, उपचार, ज्योतिष, दर्शन"),
CHART_LEGEND_RETRO_SHORT("Retro", "वक्री"),
CHART_LEGEND_COMBUST_SHORT("Comb", "अस्त"),
CHART_LEGEND_VARGO_SHORT("Vargo", "वर्गो"),
CHART_LEGEND_EXALT_SHORT("Exalt", "उच्च"),
CHART_LEGEND_DEB_SHORT("Deb", "नीच"),
CHART_LEGEND_OWN_SHORT("Own", "स्व"),
CHART_ASC_ABBR("Asc", "ल"),
PLANET_SUN_ABBR("Su", "सू"),
PLANET_MOON_ABBR("Mo", "च"),
PLANET_MARS_ABBR("Ma", "मं"),
PLANET_MERCURY_ABBR("Me", "बु"),
PLANET_JUPITER_ABBR("Ju", "गु"),
PLANET_VENUS_ABBR("Ve", "शु"),
PLANET_SATURN_ABBR("Sa", "श"),
PLANET_RAHU_ABBR("Ra", "रा"),
PLANET_KETU_ABBR("Ke", "के"),
PLANET_URANUS_ABBR("Ur", "यु"),
PLANET_NEPTUNE_ABBR("Ne", "ने"),
PLANET_PLUTO_ABBR("Pl", "प्लु"),
ASHTAK_ANALYSIS_HEADER("ASHTAKAVARGA ANALYSIS", "अष्टकवर्ग विश्लेषण"),
    ASHTAK_SAV_HEADER("SARVASHTAKAVARGA (Combined Strength)", "SARVASHTAKAVARGA (Combined Strength)"),
    ASHTAK_BAV_HEADER("BHINNASHTAKAVARGA (Individual Planet Strengths)", "BHINNASHTAKAVARGA (Individual Planet Strengths)"),
ASHTAK_TOTAL_SAV_BINDUS("Total SAV Bindus:", "कुल SAV बिन्दुहरू:"),
ASHTAK_AVG_PER_SIGN("Average per Sign:", "प्रति राशि औसत:"),
ASHTAK_NOT_APPLICABLE("Ashtakavarga not applicable for %s", "%s को लागि अष्टकवर्ग लागू हुँदैन"),
ASHTAK_SUN_EFFECTS("authority, father, health, government, career", "अधिकार, पिता, स्वास्थ्य, सरकार, क्यारियर"),
ASHTAK_MOON_EFFECTS("mind, emotions, mother, public image", "मन, भावना, आमा, सार्वजनिक छवि"),
ASHTAK_MARS_EFFECTS("energy, siblings, property, courage", "ऊर्जा, भाइबहिनी, सम्पत्ति, साहस"),
ASHTAK_MERCURY_EFFECTS("communication, intellect, business, education", "सञ्चार, बुद्धि, व्यापार, शिक्षा"),
ASHTAK_JUPITER_EFFECTS("wisdom, children, fortune, spirituality", "ज्ञान, सन्तान, भाग्य, आध्यात्मिकता"),
ASHTAK_VENUS_EFFECTS("relationships, luxury, arts, vehicles", "सम्बन्ध, विलासिता, कला, सवारी"),
ASHTAK_SATURN_EFFECTS("career, longevity, discipline, challenges", "क्यारियर, दीर्घायु, अनुशासन, चुनौतीहरू"),
ASHTAK_GENERAL_EFFECTS("general matters", "सामान्य मामिलाहरू"),
ASHTAK_HOUSE_1_MATTERS("self, personality, health", "आफू, व्यक्तित्व, स्वास्थ्य"),
ASHTAK_HOUSE_2_MATTERS("wealth, family, speech", "धन, परिवार, वाणी"),
ASHTAK_HOUSE_3_MATTERS("courage, siblings, communication", "साहस, भाइबहिनी, सञ्चार"),
ASHTAK_HOUSE_4_MATTERS("home, mother, comfort", "घर, आमा, आराम"),
ASHTAK_HOUSE_5_MATTERS("children, intelligence, romance", "सन्तान, बुद्धि, प्रेम"),
ASHTAK_HOUSE_6_MATTERS("enemies, health issues, service", "शत्रु, स्वास्थ्य समस्या, सेवा"),
ASHTAK_HOUSE_7_MATTERS("partnership, marriage, business", "साझेदारी, विवाह, व्यापार"),
ASHTAK_HOUSE_8_MATTERS("transformation, inheritance, occult", "रूपान्तरण, सम्पत्ति, गुप्त विद्या"),
ASHTAK_HOUSE_9_MATTERS("luck, father, higher learning", "भाग्य, पिता, उच्च शिक्षा"),
ASHTAK_HOUSE_10_MATTERS("career, status, authority", "क्यारियर, हैसियत, अधिकार"),
ASHTAK_HOUSE_11_MATTERS("gains, friends, aspirations", "लाभ, साथीहरू, आकांक्षाहरू"),
ASHTAK_HOUSE_12_MATTERS("losses, spirituality, foreign", "हानि, आध्यात्मिकता, विदेश"),
GUNA_RAJAS("Rajas", "रजस्"),
GUNA_TAMAS("Tamas", "तमस्"),
TRANSITION_FRIEND_FRIEND("Friend to Friend", "मित्र देखि मित्र"),
TRANSITION_FRIEND_NEUTRAL("Friend to Neutral", "मित्र देखि तटस्थ"),
TRANSITION_FRIEND_ENEMY("Friend to Enemy", "मित्र देखि शत्रु"),
TRANSITION_NEUTRAL_FRIEND("Neutral to Friend", "तटस्थ देखि मित्र"),
TRANSITION_NEUTRAL_NEUTRAL("Neutral to Neutral", "तटस्थ देखि तटस्थ"),
TRANSITION_NEUTRAL_ENEMY("Neutral to Enemy", "तटस्थ देखि शत्रु"),
TRANSITION_ENEMY_FRIEND("Enemy to Friend", "शत्रु देखि मित्र"),
TRANSITION_ENEMY_NEUTRAL("Enemy to Neutral", "शत्रु देखि तटस्थ"),
TRANSITION_ENEMY_ENEMY("Enemy to Enemy", "शत्रु देखि शत्रु"),
VEDHA_COMPLETE("Complete", "पूर्ण"),
VEDHA_STRONG("Strong", "बलियो"),
VEDHA_MODERATE("Moderate", "मध्यम"),
VEDHA_PARTIAL("Partial", "आंशिक"),
VEDHA_NONE("None", "कुनै छैन"),
KEMADRUMA_NOT_PRESENT("Not Present", "उपस्थित छैन"),
KEMADRUMA_FULLY_CANCELLED("Fully Cancelled", "पूर्ण रद्द"),
KEMADRUMA_MOSTLY_CANCELLED("Mostly Cancelled", "प्राय: रद्द"),
KEMADRUMA_PARTIALLY_CANCELLED("Partially Cancelled", "आंशिक रद्द"),
KEMADRUMA_WEAKLY_CANCELLED("Weakly Cancelled", "कमजोर रद्द"),
KEMADRUMA_ACTIVE_MODERATE("Active - Moderate", "सक्रिय - मध्यम"),
KEMADRUMA_ACTIVE_SEVERE("Active - Severe", "सक्रिय - गम्भीर"),
BHANGA_KENDRA_MOON("Kendra Moon", "केन्द्र चन्द्र"),
BHANGA_KENDRA_LAGNA("Kendra Lagna", "केन्द्र लग्न"),
BHANGA_MOON_KENDRA("Moon in Kendra", "चन्द्र केन्द्रमा"),
BHANGA_BENEFIC_ASPECT("Benefic Aspect", "शुभ दृष्टि"),
BHANGA_BENEFIC_CONJUNCTION("Benefic Conjunction", "शुभ संयोग"),
BHANGA_MOON_EXALTED("Moon Exalted", "चन्द्र उच्च"),
BHANGA_MOON_OWN("Moon Own Sign", "चन्द्र स्वराशि"),
BHANGA_MOON_FRIEND("Moon with Friend", "चन्द्र मित्र साथ"),
BHANGA_FULL_MOON("Full Moon", "पूर्ण चन्द्र"),
BHANGA_ANGULAR_MOON("Angular Moon", "केन्द्रीय चन्द्र"),
BHANGA_STRONG_DISPOSITOR("Strong Dispositor", "बलियो स्वामी"),
BHANGA_JUPITER_ASPECT("Jupiter Aspect", "गुरु दृष्टि"),
BHANGA_VENUS_ASPECT("Venus Aspect", "शुक्र दृष्टि"),
TARA_JANMA("Janma", "जन्म"),
TARA_SAMPAT("Sampat", "सम्पत्ति"),
TARA_VIPAT("Vipat", "विपत्ति"),
TARA_KSHEMA("Kshema", "क्षेम"),
TARA_PRATYARI("Pratyari", "प्रत्यारी"),
TARA_SADHAKA("Sadhaka", "साधक"),
TARA_VADHA("Vadha", "वध"),
TARA_MITRA("Mitra", "मित्र"),
TARA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),
TARA_JANMA_DESC("Birth Star", "जन्म नक्षत्र"),
TARA_SAMPAT_DESC("Wealth Star", "सम्पत्ति नक्षत्र"),
TARA_VIPAT_DESC("Misfortune Star", "विपत्ति नक्षत्र"),
TARA_KSHEMA_DESC("Welfare Star", "क्षेम नक्षत्र"),
TARA_PRATYARI_DESC("Enemy Star", "प्रत्यारी नक्षत्र"),
TARA_SADHAKA_DESC("Achiever Star", "साधक नक्षत्र"),
TARA_VADHA_DESC("Death Star", "वध नक्षत्र"),
TARA_MITRA_DESC("Friend Star", "मित्र नक्षत्र"),
TARA_PARAMA_MITRA_DESC("Highest Friend Star", "परम मित्र नक्षत्र"),
CHANDRABALA_EXCELLENT("Excellent", "उत्कृष्ट"),
CHANDRABALA_GOOD("Good", "राम्रो"),
CHANDRABALA_NEUTRAL("Neutral", "तटस्थ"),
CHANDRABALA_WEAK("Weak", "कमजोर"),
CHANDRABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
COMBINED_HIGHLY_FAVORABLE("Highly Favorable", "अत्यन्त अनुकूल"),
COMBINED_FAVORABLE("Favorable", "अनुकूल"),
COMBINED_MIXED("Mixed", "मिश्रित"),
COMBINED_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
COMBINED_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
TARABALA_TITLE("Tarabala", "तारबल"),
TARABALA_TODAY("Today", "आज"),
TARABALA_WEEKLY("Weekly", "साप्ताहिक"),
TARABALA_ALL_NAKSHATRAS("All 27 Nakshatras", "सबै २७ नक्षत्र"),
TARABALA_WHAT_IS("What is Tarabala?", "तारबल के हो?"),
TARABALA_UNABLE_CALCULATE("Unable to calculate Tarabala without birth details", "जन्म विवरण बिना तारबल गणना गर्न सक्षम छैन"),
TARABALA_TODAY_STRENGTH("Today's Strength", "आजको शक्ति"),
TARABALA_LABEL("Tarabala", "तारबल"),
TARABALA_STAR_STRENGTH("Star Strength", "नक्षत्र शक्ति"),
TARABALA_FAVORABLE("Favorable", "अनुकूल"),
TARABALA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
TARABALA_BIRTH_STAR("Birth Star", "जन्म नक्षत्र"),
TARABALA_TRANSIT_STAR("Transit Star", "गोचर नक्षत्र"),
TARABALA_TARA_TYPE("Tara Type", "तार प्रकार"),
TARABALA_CYCLE("Cycle", "चक्र"),
CHANDRABALA_LABEL("Chandrabala", "चन्द्रबल"),
CHANDRABALA_MOON_STRENGTH("Moon Strength", "चन्द्र शक्ति"),
CHANDRABALA_NATAL_MOON("Natal Moon", "जन्मकालीन चन्द्र"),
CHANDRABALA_TRANSIT_MOON("Transit Moon", "गोचर चन्द्र"),
CHANDRABALA_HOUSE("House", "भाव"),
CHANDRABALA_SIGNIFICATIONS("Significations", "करकत्व"),
TARABALA_ACTIVITIES("Activities", "गतिविधिहरू"),
TARABALA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
TARABALA_AVOID_ACTIVITIES("Activities to Avoid", "टाढा रहनु पर्ने गतिविधिहरू"),
TARABALA_DAILY_BREAKDOWN("Daily Breakdown", "दैनिक विभाजन"),
TARABALA_WEEKLY_OVERVIEW("Weekly Overview", "साप्ताहिक सिंहावलोकन"),
TARABALA_BEST_DAY("Best Day", "सबैभन्दा राम्रो दिन"),
TARABALA_AVOID_DAY("Day to Avoid", "टाढा रहनु पर्ने दिन"),
TARABALA_BEST_LABEL("Best", "सबैभन्दा राम्रो"),
TARABALA_ALL_27_DESC("All 27 Nakshatras with their Tarabala values", "सबै २७ नक्षत्र तिनीहरूको तारबल मानहरू साथ"),
TARABALA_EXPLANATION("Explanation", "व्याख्या"),
CHANDRABALA_EXPLANATION("Explanation", "व्याख्या"),
AUSPICIOUSNESS_HIGHLY_AUSPICIOUS("Highly Auspicious", "अत्यन्त शुभ"),
AUSPICIOUSNESS_AUSPICIOUS("Auspicious", "शुभ"),
AUSPICIOUSNESS_NEUTRAL("Neutral", "तटस्थ"),
AUSPICIOUSNESS_INAUSPICIOUS("Inauspicious", "अशुभ"),
AUSPICIOUSNESS_HIGHLY_INAUSPICIOUS("Highly Inauspicious", "अत्यन्त अशुभ"),
NITYA_STRENGTH_VERY_STRONG("Very Strong", "अत्यन्त बलियो"),
NITYA_STRENGTH_STRONG("Strong", "बलियो"),
NITYA_STRENGTH_MODERATE("Moderate", "मध्यम"),
NITYA_STRENGTH_WEAK("Weak", "कमजोर"),
NITYA_STRENGTH_VERY_WEAK("Very Weak", "अत्यन्त कमजोर"),
RECOMMEND_SPIRITUAL("Spiritual Practice", "आध्यात्मिक अभ्यास"),
RECOMMEND_ACTIVITY("Activity Guidance", "गतिविधि मार्गदर्शन"),
RECOMMEND_MANTRA("Mantra Recitation", "मन्त्र जप"),
RECOMMEND_TIMING("Timing Advice", "समय सल्लाह"),
RECOMMEND_GENERAL("General Guidance", "सामान्य मार्गदर्शन"),
VARA_SUNDAY("Sunday", "आइतबार"),
VARA_MONDAY("Monday", "सोमबार"),
VARA_TUESDAY("Tuesday", "मंगलबार"),
VARA_WEDNESDAY("Wednesday", "बुधबार"),
VARA_THURSDAY("Thursday", "बिहीबार"),
VARA_FRIDAY("Friday", "शुक्रबार"),
VARA_SATURDAY("Saturday", "शनिबार"),
CHOGHADIYA_UDVEG("Udveg", "उद्वेग"),
CHOGHADIYA_CHAR("Char", "चर"),
CHOGHADIYA_LABH("Labh", "लाभ"),
CHOGHADIYA_AMRIT("Amrit", "अमृत"),
CHOGHADIYA_KAAL("Kaal", "काल"),
CHOGHADIYA_SHUBH("Shubh", "शुभ"),
CHOGHADIYA_ROG("Rog", "रोग"),
CHOGHADIYA_NATURE_AUSPICIOUS("Auspicious", "शुभ"),
CHOGHADIYA_NATURE_INAUSPICIOUS("Inauspicious", "अशुभ"),
CHOGHADIYA_NATURE_MIXED("Mixed", "मिश्रित"),
TITHI_NATURE_NANDA("Nanda", "नन्दा"),
TITHI_NATURE_BHADRA("Bhadra", "भद्रा"),
TITHI_NATURE_JAYA("Jaya", "जया"),
TITHI_NATURE_RIKTA("Rikta", "रिक्ता"),
TITHI_NATURE_PURNA("Purna", "पूर्णा"),
KARANA_MOVABLE("Movable", "चर"),
KARANA_FIXED("Fixed", "स्थिर"),
TITHI_GROUP_NANDA("Nanda", "नन्दा"),
TITHI_GROUP_NANDA_NATURE("Joyful", "आनन्दमय"),
TITHI_GROUP_BHADRA("Bhadra", "भद्रा"),
TITHI_GROUP_BHADRA_NATURE("Auspicious", "शुभ"),
TITHI_GROUP_JAYA("Jaya", "जया"),
TITHI_GROUP_JAYA_NATURE("Victorious", "विजयी"),
TITHI_GROUP_RIKTA("Rikta", "रिक्ता"),
TITHI_GROUP_RIKTA_NATURE("Empty", "रित्त"),
TITHI_GROUP_PURNA("Purna", "पूर्णा"),
TITHI_GROUP_PURNA_NATURE("Complete", "पूर्ण"),
PAKSHA_SHUKLA("Shukla Paksha", "शुक्ल पक्ष"),
PAKSHA_KRISHNA("Krishna Paksha", "कृष्ण पक्ष"),
RETRO_DIRECT("Direct", "मार्गी"),
RETRO_RETROGRADE("Retrograde", "वक्री"),
RETRO_STATIONARY_RETRO("Stationary Retrograde", "स्थिर वक्री"),
RETRO_STATIONARY_DIRECT("Stationary Direct", "स्थिर मार्गी"),
RETRO_ALWAYS_RETROGRADE("Perpetual Retrograde", "सदा वक्री"),
COMBUST_NOT("Not Combust", "अस्त छैन"),
COMBUST_APPROACHING("Approaching Combustion", "अस्त हुँदै"),
COMBUST_COMBUST("Combust", "अस्त"),
COMBUST_DEEP("Deep Combustion", "गहिरो अस्त"),
COMBUST_CAZIMI("Cazimi", "कज़िमी"),
COMBUST_SEPARATING("Separating", "अलग हुँदै"),
SPEED_VERY_FAST("Very Fast", "अति छिटो"),
SPEED_FAST("Fast", "छिटो"),
SPEED_NORMAL("Normal", "सामान्य"),
SPEED_SLOW("Slow", "ढिलो"),
SPEED_VERY_SLOW("Very Slow", "अति ढिलो"),
SPEED_STATIONARY("Stationary", "स्थिर"),
SPEED_RETROGRADE_MOTION("Retrograde Motion", "वक्री गति"),
WAR_NORTHERN_LAT("Northern Latitude", "उत्तरी अक्षांश"),
WAR_BRIGHTNESS("Greater Brightness", "अधिक चमक"),
WAR_COMBINED("Both Factors", "दुवै कारक"),
WAR_INDETERMINATE("Evenly Matched", "बराबर"),
BENEFIC("Benefic", "शुभ"),
MALEFIC("Malefic", "पाप"),
LORDS("Lords", "स्वामीहरू"),
ARGALA_CALCULATING("Calculating Argala...", "अर्गला गणना गर्दै..."),
ARGALA_FAILED("Failed to calculate Argala", "अर्गला गणना गर्न असफल"),
ARGALA_SELECT_HOUSE("Select House to Analyze", "विश्लेषण गर्न भाव चयन गर्नुहोस्"),
ARGALA_HOUSE_SELECTOR_LABEL("Select House to Analyze", "विश्लेषण गर्न भाव चयन गर्नुहोस्"),
ARGALA_TYPES_TITLE("Argala Types", "अर्गलाका प्रकारहरू"),
ARGALA_PRIMARY_DESC("4th & 11th houses create primary interventions", "चौथो र एघारौं भावले प्राथमिक हस्तक्षेप सिर्जना गर्दछ"),
ARGALA_SECONDARY_DESC("2nd house creates secondary interventions", "दोस्रो भावले माध्यमिक हस्तक्षेप सिर्जना गर्दछ"),
ARGALA_FIFTH_HOUSE_DESC("5th house creates special interventions", "पाँचौं भावले विशेष हस्तक्षेप सिर्जना गर्दछ"),
ARGALA_VIRODHA_DESC("12th, 10th, 3rd, 9th houses obstruct Argala", "१२औं, १०औं, ३औं, र ९औं भावले अर्गालालाई बाधा पुर्‍याउँछ"),
ARGALA_CHART_WIDE_PATTERNS("Chart-Wide Argala Patterns", "कुण्डली-व्यापी अर्गाला ढाँचाहरू"),
ARGALA_STRONGEST_SUPPORT("Strongest Support", "सबैभन्दा बलियो समर्थन"),
ARGALA_GREATEST_CHALLENGE("Greatest Challenge", "सबैभन्दा ठूलो चुनौती"),
ARGALA_MOST_OBSTRUCTED("Most Obstructed", "सबैभन्दा बाधित"),
CALCULATING_CHARA_DASHA("Calculating Chara Dasha periods...", "कारा दशा अवधि गणना गर्दै..."),
KARAKA_ACTIVATION("Karaka Activation", "कारक सक्रियता"),
INFLUENCE_VERY_FAVORABLE("Very Favorable", "धेरै अनुकूल"),
INFLUENCE_FAVORABLE("Favorable", "अनुकूल"),
INFLUENCE_NEUTRAL("Neutral", "तटस्थ"),
INFLUENCE_NEEDS_ATTENTION("Needs Attention", "ध्यान दिनुपर्ने"),
AREA_CAREER("Career", "करियर"),
AREA_RELATIONSHIPS("Relationships", "सम्बन्ध"),
AREA_HEALTH("Health", "स्वास्थ्य"),
AREA_SPIRITUALITY("Spirituality", "आध्यात्मिकता"),
AREA_WEALTH("Wealth", "धन"),
AREA_FAMILY("Family", "परिवार"),
AREA_EDUCATION("Education", "शिक्षा"),
AREA_FOREIGN_CONNECTIONS("Foreign Connections", "विदेशी सम्बन्ध"),
ASPECT_CONJUNCTION("Conjunction", "युति"),
ASPECT_OPPOSITION("Opposition", "दृष्टि"),
ASPECT_TRINE("Trine", "त्रिकोण"),
ASPECT_SQUARE("Square", "केन्द्र"),
ARGALA_LEAST_OBSTRUCTED("Least Obstructed", "कम से कम बाधित"),
ARGALA_KARMA_PATTERNS("Karma Patterns", "कर्म ढाँचाहरू"),
ARGALA_SIGNIFICANT_ARGALAS("Significant Argalas", "महत्वपूर्ण अर्गालाहरू"),
ARGALA_STRENGTH_VERY_STRONG("Very Strong", "धेरै बलियो"),
ARGALA_STRENGTH_STRONG("Strong", "बलियो"),
ARGALA_STRENGTH_MODERATE("Moderate", "मध्यम"),
ARGALA_STRENGTH_WEAK("Weak", "कमजोर"),
ARGALA_STRENGTH_OBSTRUCTED("Obstructed", "बाधित"),
AVASTHA_TAB_OVERVIEW("Overview", "अवलोकन"),
AVASTHA_TAB_PLANETS("Planets", "ग्रहहरू"),
AVASTHA_TAB_BALADI("Baladi", "बालादि"),
AVASTHA_TAB_JAGRADADI("Jagradadi", "जाग्रदादि"),
AVASTHA_TAB_DEEPTADI("Deeptadi", "दीप्तादि"),
AVASTHA_TAB_LAJJITADI("Lajjitadi", "लज्जितादि"),
AVASTHA_STRONG_CONFIG("Strong overall planetary configuration", "बलियो समग्र ग्रह विन्यास"),
AVASTHA_MODERATE_STRENGTH("Moderate overall planetary strength", "मध्यम समग्र ग्रह बल"),
AVASTHA_NEEDS_MEASURES("Planets need strengthening measures", "ग्रहहरूलाई सवलीकरण उपायहरू आवश्यक छ"),
TRI_PATAKI_DHARMA("Dharma Sector", "धर्म क्षेत्र"),
TRI_PATAKI_ARTHA("Artha Sector", "अर्थ क्षेत्र"),
TRI_PATAKI_KAMA("Kama Sector", "काम क्षेत्र"),
TRI_PATAKI_DHARMA_DESC("Focus on purpose, spirituality, and duties.", "उद्देश्य, आध्यात्मिकता र कर्तव्यहरूमा ध्यान।"),
TRI_PATAKI_ARTHA_DESC("Focus on material success, career, and stability.", "भौतिक सफलता, क्यारियर र स्थिरतामा ध्यान।"),
TRI_PATAKI_KAMA_DESC("Focus on desires, relationships, and social life.", "इच्छाहरू, सम्बन्धहरू र सामाजिक जीवनमा ध्यान।"),
TRI_PATAKI_BALANCED("Balanced Influence", "सन्तुलित प्रभाव"),
TRI_PATAKI_QUIET("Quiet Period", "शान्त अवधि"),
TRI_PATAKI_FAVORABLE("Favorable Activation", "अनुकूल सक्रियता"),
TRI_PATAKI_CHALLENGING("Challenging Activation", "चुनौतीपूर्ण सक्रियता"),
TRI_PATAKI_VARIABLE("Variable Energy", "परिवर्तनशील ऊर्जा"),
TRI_PATAKI_DHARMA_AREA("spiritual or professional duties", "आध्यात्मिक वा व्यावसायिक कर्तव्यहरू"),
TRI_PATAKI_ARTHA_AREA("financial or material growth", "आर्थिक वा भौतिक विकास"),
TRI_PATAKI_KAMA_AREA("desires and social connections", "इच्छाहरू र सामाजिक सम्बन्धहरू"),
TRI_PATAKI_EMPHASIS("Strong emphasis on %s.", "%s मा कडा जोड।"),
TRI_PATAKI_BALANCED_DESC("Energy is evenly distributed across life areas.", "जीवनका क्षेत्रहरूमा ऊर्जा समान रूपमा वितरित छ।"),
PLANET_NATURE_SUN("vitality and authority", "जीवनशक्ति र अधिकार"),
PLANET_NATURE_MOON("emotional connection and growth", "भावनात्मक सम्बन्ध र विकास"),
PLANET_NATURE_MARS("energy and initiative", "ऊर्जा र पहल"),
PLANET_NATURE_MERCURY("communication and skills", "सञ्चार र सीप"),
PLANET_NATURE_JUPITER("wisdom and opportunity", "बुद्धि र अवसर"),
PLANET_NATURE_VENUS("creativity and harmony", "सिर्जनशीलता र सद्भाव"),
PLANET_NATURE_SATURN("discipline and persistence", "अनुशासन र दृढता"),
PLANET_NATURE_RAHU("ambition and innovation", "महत्त्वाकांक्षा र नवीनता"),
PLANET_NATURE_KETU("spiritual depth and detachment", "आध्यात्मिक गहिराइ र वैराग्य"),
KEYWORD_LEADERSHIP("Leadership", "नेतृत्व"),
KEYWORD_VITALITY("Vitality", "प्राणशक्ति"),
KEYWORD_FATHER("Father", "पिता"),
KEYWORD_EMOTIONS("Emotions", "भावना"),
KEYWORD_MOTHER("Mother", "माता"),
KEYWORD_PUBLIC("Public", "सार्वजनिक"),
KEYWORD_ACTION("Action", "कार्य")
}
