package com.astro.storm.core.common

enum class StringKeyPrediction(override val en: String, override val ne: String) : StringKeyInterface {
    LUCKY_COLOR_AIR("Blue, Light Blue, or Silver", "निलो, हल्का निलो, वा चाँदी"),
    LUCKY_COLOR_EARTH("Green, Brown, or White", "हरियो, खैरो, वा सेतो"),
    LUCKY_COLOR_FIRE("Red, Orange, or Gold", "रातो, सुन्तला, वा सुनौलो"),
    LUCKY_COLOR_WATER("White, Cream, or Sea Green", "सेतो, क्रीम, वा समुद्री हरियो"),
    LUCKY_DIR_EAST("East", "पूर्व"),
    LUCKY_DIR_NORTH("North", "उत्तर"),
    LUCKY_DIR_NORTHEAST("North-East", "उत्तर-पूर्व"),
    LUCKY_DIR_NORTHWEST("North-West", "उत्तर-पश्चिम"),
    LUCKY_DIR_SOUTH("South", "दक्षिण"),
    LUCKY_DIR_SOUTHEAST("South-East", "दक्षिण-पूर्व"),
    LUCKY_DIR_SOUTHWEST("South-West", "दक्षिण-पश्चिम"),
    LUCKY_DIR_WEST("West", "पश्चिम"),
    PREDICTION_DEBILITATED("Debilitated Planet", "नीच ग्रह"),
    PREDICTION_DEBILITATED_DESC("%s is in its fall. Its positive significations may be reduced or delayed.", "%s आफ्नो नीच राशिमा छ। यसको सकारात्मक करकत्वहरू कम वा ढिलो हुन सक्छन्।"),
    PREDICTION_DUSTHANA("Dusthana Placement", "दुःस्थान स्थिति"),
    PREDICTION_DUSTHANA_DESC("%s in house %d may face obstacles but can also give transformative experiences.", "भाव %d मा %s ले बाधाहरू सामना गर्न सक्छ तर रूपान्तरणकारी अनुभवहरू पनि दिन सक्छ।"),
    PREDICTION_EXALTED("Exalted Planet", "उच्च ग्रह"),
    PREDICTION_EXALTED_DESC("%s is in its sign of exaltation, giving exceptional results in its significations.", "%s आफ्नो उच्च राशिमा छ, यसको करकत्वमा असाधारण परिणामहरू दिँदै।"),
    PREDICTION_KENDRA("Kendra Placement", "केन्द्र स्थिति"),
    PREDICTION_KENDRA_DESC("%s in house %d (Kendra) gains strength and visibility.", "भाव %d (केन्द्र) मा %s ले बल र दृश्यता प्राप्त गर्दछ।"),
    PREDICTION_OWN_SIGN("Planet in Own Sign", "स्वराशिमा ग्रह"),
    PREDICTION_OWN_SIGN_DESC("%s is comfortable in its own sign, giving stable and reliable results.", "%s आफ्नै राशिमा सहज छ, स्थिर र भरपर्दो परिणामहरू दिँदै।"),
    PREDICTION_RETROGRADE("Retrograde Motion", "वक्री गति"),
    PREDICTION_RETROGRADE_DESC("Retrograde planets work on an internal level. Results may be delayed but often more profound.", "वक्री ग्रहहरू आन्तरिक स्तरमा काम गर्छन्। परिणामहरू ढिलो हुन सक्छन् तर प्रायः अधिक गहिरो हुन्छन्।"),
    PREDICTION_SCORE("Prediction Favorability Score", "भविष्यवाणी अनुकूलता स्कोर"),
    PREDICTION_STRONG_DESC("This planet has sufficient strength to deliver positive results. Its significations will manifest more easily in your life.", "यो ग्रहसँग सकारात्मक परिणामहरू दिनको लागि पर्याप्त बल छ। यसको करकत्वहरू तपाईंको जीवनमा सजिलैसँग प्रकट हुनेछन्।"),
    PREDICTION_STRONG_PLANET("Strong %s", "बलियो %s"),
    PREDICTION_SUMMARY("Prediction Summary", "भविष्यवाणी सारांश"),
    PREDICTION_TEMPLATE_CAUTION("Planetary influences suggest caution regarding %s. Remedial measures can help mitigate challenges.",
        "ग्रह प्रभावहरूले %s सम्बन्धमा सावधानी सुझाव गर्दछ। उपचारात्मक उपायहरूले चुनौतीहरू कम गर्न मद्दत गर्न सक्छ।"),
    PREDICTION_TEMPLATE_POSITIVE("The planetary configuration indicates %s, bringing %s in the coming period.",
        "ग्रह विन्यासले %s संकेत गर्छ, आउने अवधिमा %s ल्याउँदै।"),
    PREDICTION_TRIKONA("Trikona Placement", "त्रिकोण स्थिति"),
    PREDICTION_TRIKONA_DESC("%s in house %d (Trikona) is auspicious for fortune and dharma.", "भाव %d (त्रिकोण) मा %s भाग्य र धर्मको लागि शुभ छ।"),
    PREDICTION_WEAK_DESC("This planet lacks sufficient strength. You may face challenges in areas it governs. Remedial measures may help.", "यो ग्रहमा पर्याप्त बल छैन। तपाईंले यसले शासन गर्ने क्षेत्रहरूमा चुनौतीहरू सामना गर्न सक्नुहुन्छ। उपाय उपायहरूले मद्दत गर्न सक्छ।"),
    PREDICTION_WEAK_PLANET("Weak %s", "कमजोर %s"),
    THEME_BALANCE("Balance", "सन्तुलन"),
    THEME_BALANCE_EQUILIBRIUM("Balance & Equilibrium", "सन्तुलन र स्थिरता"),
    THEME_COMMUNICATION_LEARNING("Communication & Learning", "सञ्चार र सिकाई"),
    THEME_DARK("Dark", "अँध्यारो"),
    THEME_DARK_DESC("Always use dark theme", "सधैं अँध्यारो थिम प्रयोग गर्नुहोस्"),
    THEME_DESC_BALANCE_EQUILIBRIUM("A day of balance where all energies are in equilibrium. Maintain steadiness and make measured progress in all areas of life.", "सबै ऊर्जाहरू सन्तुलनमा रहेको दिन। स्थिरता कायम राख्नुहोस् र जीवनका सबै क्षेत्रमा नापिएको प्रगति गर्नुहोस्।"),
    THEME_DESC_COMMUNICATION_LEARNING("Mercury enhances your mental agility and communication skills. This is ideal for learning, teaching, writing, and all forms of information exchange.", "बुधले तपाईंको मानसिक चपलता र सञ्चार सीपलाई बढावा दिन्छ। यो सिकाई, शिक्षण, लेखन, र सबै प्रकारका सूचना आदानप्रदानका लागि उपयुक्त छ।"),
    THEME_DESC_DARK("Always use dark theme", "सधैं गाढा थीम प्रयोग गर्नुहोस्"),
    THEME_DESC_DISCIPLINE_GROWTH("Saturn's influence calls for patience, hard work, and responsibility. Embrace challenges as opportunities for growth and stay committed to your long-term goals.", "शनिको प्रभावले धैर्य, कडा परिश्रम, र जिम्मेवारीको माग गर्दछ। चुनौतीहरूलाई वृद्धिको अवसरको रूपमा स्वीकार गर्नुहोस् र आफ्ना दीर्घकालीन लक्ष्यहरूमा प्रतिबद्ध रहनुहोस्।"),
    THEME_DESC_DYNAMIC_ACTION("Your energy is high and aligned with fire elements. This is an excellent day for taking initiative, starting new projects, and asserting yourself confidently. Channel this vibrant energy into productive pursuits.", "तपाईंको ऊर्जा उच्च छ र अग्नि तत्वसँग मिल्दोजुल्दो छ। यो पहल गर्न, नयाँ परियोजनाहरू सुरु गर्न र आत्मविश्वासका साथ आफूलाई प्रस्तुत गर्न उत्कृष्ट दिन हो। यस जीवन्त ऊर्जालाई उत्पादक कार्यहरूमा लगाउनुहोस्।"),
    THEME_DESC_EMOTIONAL_INSIGHT("Water element energy deepens your intuition and emotional awareness. Trust your feelings and pay attention to subtle cues. This is a powerful day for healing and self-reflection.", "जल तत्वको ऊर्जाले तपाईंको अन्तर्ज्ञान र भावनात्मक जागरूकतालाई गहिरो बनाउँछ। आफ्ना भावनाहरूमा विश्वास गर्नुहोस् र सूक्ष्म संकेतहरूमा ध्यान दिनुहोस्। यो निको पार्न र आत्म-चिन्तनका लागि एक शक्तिशाली दिन हो।"),
    THEME_DESC_ENERGY_INITIATIVE("Mars provides courage and drive. Take bold action, compete with integrity, and channel aggressive energy into constructive activities.", "मंगलले साहस र जोश प्रदान गर्दछ। साहसी कदम चाल्नुहोस्, इमानदारीका साथ प्रतिस्पर्धा गर्नुहोस्, र आक्रामक ऊर्जालाई रचनात्मक गतिविधिहरूमा लगाउनुहोस्।"),
    THEME_DESC_EXPANSION_WISDOM("Jupiter's benevolent influence brings opportunities for growth, learning, and good fortune. Be open to new possibilities and share your wisdom generously.", "बृहस्पतिको उदार प्रभावले वृद्धि, सिकाई र सौभाग्यको अवसरहरू ल्याउँछ। नयाँ सम्भावनाहरूका लागि खुला रहनुहोस् र आफ्नो ज्ञान उदारतापूर्वक बाँड्नुहोस्।"),
    THEME_DESC_HARMONY_BEAUTY("Venus graces you with appreciation for beauty, art, and relationships. Indulge in pleasurable activities and nurture your connections with loved ones.", "शुक्रले तपाईंलाई सौन्दर्य, कला, र सम्बन्धहरूको लागि प्रशंसा प्रदान गर्दछ। आनन्ददायी गतिविधिहरूमा संलग्न हुनुहोस् र आफ्ना प्रियजनहरूसँगको सम्बन्धलाई प्रगाढ बनाउनुहोस्।"),
    THEME_DESC_INTUITION_NURTURING("The Moon heightens your sensitivity and caring nature. Nurture yourself and others, and trust your instincts in important decisions.", "चन्द्रमाले तपाईंको संवेदनशीलता र हेरचाह गर्ने प्रकृतिलाई बढाउँछ। आफू र अरूको पोषण गर्नुहोस्, र महत्त्वपूर्ण निर्णयहरूमा आफ्नो अन्तर्ज्ञानमा विश्वास गर्नुहोस्।"),
    THEME_DESC_LIGHT("Always use light theme", "सधैं उज्यालो थीम प्रयोग गर्नुहोस्"),
    THEME_DESC_PRACTICAL_PROGRESS("Grounded earth energy supports methodical progress today. Focus on practical tasks, financial planning, and building stable foundations. Your efforts will yield tangible results.", "पृथ्वी तत्वको ऊर्जाले आज व्यवस्थित प्रगतिलाई समर्थन गर्दछ। व्यावहारिक कार्यहरू, वित्तीय योजना, र स्थिर आधार निर्माणमा ध्यान दिनुहोस्। तपाईंको प्रयासले मूर्त परिणामहरू दिनेछ।"),
    THEME_DESC_SELF_EXPRESSION("The Sun illuminates your path to self-expression and leadership. Shine your light confidently and pursue activities that bring you recognition.", "सूर्यले तपाईंको आत्म-अभिव्यक्ति र नेतृत्वको मार्गलाई उज्यालो बनाउँछ। आत्मविश्वासका साथ आफ्नो चमक देखाउनुहोस् र तपाईंलाई पहिचान दिलाउने गतिविधिहरूमा लाग्नुहोस्।"),
    THEME_DESC_SOCIAL_CONNECTIONS("Air element energy enhances communication and social interactions. Networking, negotiations, and intellectual pursuits are favored. Express your ideas and connect with like-minded people.", "वायु तत्वको ऊर्जाले सञ्चार र सामाजिक अन्तरक्रियालाई बढावा दिन्छ। नेटवर्किङ, वार्ता, र बौद्धिक कार्यहरूका लागि आज अनुकूल छ। आफ्ना विचारहरू व्यक्त गर्नुहोस् र समान विचारधारा भएका मानिसहरूसँग जोडिनुहोस्।"),
    THEME_DESC_SPIRITUAL_LIBERATION("Ketu's energy supports detachment and spiritual insight. Let go of what no longer serves you and focus on inner growth.", "केतुको ऊर्जाले वैराग्य र आध्यात्मिक अन्तर्दृष्टिलाई समर्थन गर्दछ। जे कुराले तपाईंलाई अब फाइदा गर्दैन त्यसलाई छोडिदिनुहोस् र आन्तरिक वृद्धिमा ध्यान दिनुहोस्।"),
    THEME_DESC_SYSTEM("Follow device settings", "डिभाइस सेटिङ अनुसरण गर्नुहोस्"),
    THEME_DESC_TRANSFORMATION("Rahu's influence brings unconventional opportunities and desires for change. Embrace innovation but stay grounded in your values.", "राहुको प्रभावले अपरम्परागत अवसरहरू र परिवर्तनको इच्छा ल्याउँछ। नवीनतालाई अँगाल्नुहोस् तर आफ्ना मूल्यहरूमा अडिग रहनुहोस्।"),
    THEME_DISCIPLINE_GROWTH("Discipline & Growth", "अनुशासन र वृद्धि"),
    THEME_DYNAMIC_ACTION("Dynamic Action", "गतिशील कार्य"),
    THEME_EMOTIONAL_INSIGHT("Emotional Insight", "भावनात्मक अन्तर्दृष्टि"),
    THEME_ENERGY_INITIATIVE("Energy & Initiative", "ऊर्जा र पहल"),
    THEME_EXPANSION_WISDOM("Expansion & Wisdom", "विस्तार र ज्ञान"),
    THEME_HARMONY_BEAUTY("Harmony & Beauty", "सामञ्जस्य र सौन्दर्य"),
    THEME_INTUITION_NURTURING("Intuition & Nurturing", "अन्तर्ज्ञान र पोषण"),
    THEME_LIGHT("Light", "उज्यालो"),
    THEME_LIGHT_DESC("Always use light theme", "सधैं उज्यालो थिम प्रयोग गर्नुहोस्"),
    THEME_PRACTICAL_PROGRESS("Practical Progress", "व्यावहारिक प्रगति"),
    THEME_SELF_EXPRESSION("Self-Expression", "आत्म-अभिव्यक्ति"),
    THEME_SOCIAL_CONNECTIONS("Social Connections", "सामाजिक सम्बन्धहरू"),
    THEME_SPIRITUAL_LIBERATION("Spiritual Liberation", "आध्यात्मिक मुक्ति"),
    THEME_SYSTEM("System", "प्रणाली"),
    THEME_SYSTEM_DESC("Follow device settings", "यन्त्र सेटिङ्स पछ्याउनुहोस्"),
    THEME_TRANSFORMATION("Transformation", "रूपान्तरण"),
    THEME_WEEK_MINDFUL_NAVIGATION("Mindful Navigation", "सचेत यात्रा"),
    THEME_WEEK_OPPORTUNITIES("Week of Opportunities", "अवसरहरूको हप्ता"),
    THEME_WEEK_STEADY_PROGRESS("Steady Progress", "स्थिर प्रगति")
}
