package com.astro.storm.core.common
enum class StringKeyShadbala(override val en: String, override val ne: String) : StringKeyInterface {
SHADBALA_RUPAS_VALUE("%s Rupas", "%s रूपा"),
SHADBALA_TITLE("Shadbala", "षड्बल"),
SHADBALA_SUBTITLE("Six-fold Planetary Strength", "छवटा ग्रह शक्ति"),
SHADBALA_OVERVIEW("Overview", "अवलोकन"),
SHADBALA_DETAILS("Detailed Analysis", "विस्तृत विश्लेषण"),
SHADBALA_COMPARISON("Comparison", "तुलना"),
SHADBALA_TOTAL_STRENGTH("Total Strength", "कुल शक्ति"),
SHADBALA_RUPAS("Rupas", "रूपा"),
SHADBALA_VIRUPAS("Virupas", "विरूपा"),
SHADBALA_REQUIRED("Required", "आवश्यक"),
SHADBALA_PERCENTAGE("Percentage", "प्रतिशत"),
SHADBALA_RATING("Rating", "मूल्यांकन"),
SHADBALA_STRONGEST_PLANET("Strongest Planet", "सबैभन्दा बलियो ग्रह"),
SHADBALA_WEAKEST_PLANET("Weakest Planet", "सबैभन्दा कमजोर ग्रह"),
SHADBALA_OVERALL_STRENGTH("Overall Chart Strength", "समग्र कुण्डली शक्ति"),
SHADBALA_STRONG_COUNT("%d planets above required", "%d ग्रह आवश्यकताभन्दा माथि"),
SHADBALA_WEAK_COUNT("%d planets below required", "%d ग्रह आवश्यकताभन्दा तल"),
SHADBALA_STHANA_BALA("Sthana Bala", "स्थान बल"),
SHADBALA_STHANA_BALA_DESC("Positional Strength", "स्थितिगत शक्ति"),
SHADBALA_DIG_BALA("Dig Bala", "दिग् बल"),
SHADBALA_DIG_BALA_DESC("Directional Strength", "दिशागत शक्ति"),
SHADBALA_KALA_BALA("Kala Bala", "काल बल"),
SHADBALA_KALA_BALA_DESC("Temporal Strength", "समयगत शक्ति"),
SHADBALA_CHESTA_BALA("Chesta Bala", "चेष्टा बल"),
SHADBALA_CHESTA_BALA_DESC("Motional Strength", "गतिशील शक्ति"),
SHADBALA_NAISARGIKA_BALA("Naisargika Bala", "नैसर्गिक बल"),
SHADBALA_NAISARGIKA_BALA_DESC("Natural Strength", "प्राकृतिक शक्ति"),
SHADBALA_DRIK_BALA("Drik Bala", "दृक् बल"),
SHADBALA_DRIK_BALA_DESC("Aspectual Strength", "दृष्टिगत शक्ति"),
SHADBALA_UCCHA_BALA("Uccha Bala", "उच्च बल"),
SHADBALA_SAPTAVARGAJA_BALA("Saptavargaja Bala", "सप्तवर्गज बल"),
SHADBALA_OJHAYUGMA_BALA("Ojhayugma Bala", "ओझायुग्म बल"),
SHADBALA_KENDRADI_BALA("Kendradi Bala", "केन्द्रादि बल"),
SHADBALA_DREKKANA_BALA("Drekkana Bala", "द्रेक्काण बल"),
SHADBALA_NATHONNATHA_BALA("Nathonnatha Bala", "नथोन्नथ बल"),
SHADBALA_PAKSHA_BALA("Paksha Bala", "पक्ष बल"),
SHADBALA_TRIBHAGA_BALA("Tribhaga Bala", "त्रिभाग बल"),
SHADBALA_HORA_BALA("Hora/Dina/Masa/Varsha", "होरा/दिन/मास/वर्ष"),
SHADBALA_AYANA_BALA("Ayana Bala", "अयन बल"),
SHADBALA_YUDDHA_BALA("Yuddha Bala", "युद्ध बल"),
SHADBALA_INFO_TITLE("About Shadbala", "षड्बलको बारेमा"),
SHADBALA_INFO_DESC("Shadbala is the six-fold strength calculation system in Vedic astrology that determines a planet's capacity to deliver its significations. Each planet needs to meet a minimum threshold to be considered functionally strong.", "षड्बल वैदिक ज्योतिषमा छवटा शक्ति गणना प्रणाली हो जसले ग्रहको आफ्नो संकेतहरू प्रदान गर्ने क्षमता निर्धारण गर्दछ। प्रत्येक ग्रहलाई कार्यात्मक रूपमा बलियो मानिनको लागि न्यूनतम सीमा पूरा गर्नुपर्छ।"),
SHADBALA_INFO_INTRO("The six sources of strength:", "शक्तिका छवटा स्रोतहरू:"),
SHADBALA_INFO_ITEM_1("1. Sthana Bala - Positional strength based on exaltation, own sign, etc.", "१. स्थान बल - उच्चता, स्वराशि, आदिमा आधारित स्थितिगत शक्ति।"),
SHADBALA_INFO_ITEM_2("2. Dig Bala - Directional strength based on house placement", "२. दिग् बल - भाव स्थितिमा आधारित दिशागत शक्ति"),
SHADBALA_INFO_ITEM_3("3. Kala Bala - Temporal strength from time of birth", "३. काल बल - जन्म समयबाट समयगत शक्ति"),
SHADBALA_INFO_ITEM_4("4. Chesta Bala - Motional strength from planetary motion", "४. चेष्टा बल - ग्रह गतिबाट गतिशील शक्ति"),
SHADBALA_INFO_ITEM_5("5. Naisargika Bala - Natural inherent strength", "५. नैसर्गिक बल - प्राकृतिक अन्तर्निहित शक्ति"),
SHADBALA_INFO_ITEM_6("6. Drik Bala - Strength from aspects received", "६. दृक् बल - प्राप्त दृष्टिहरूबाट शक्ति"),
SHADBALA_INTERPRETATION("Interpretation", "व्याख्या"),
SHADBALA_PLANET_ANALYSIS("%s Analysis", "%s विश्लेषण"),
SHADBALA_MEETS_REQUIREMENT("Meets required strength", "आवश्यक शक्ति पूरा गर्दछ"),
SHADBALA_BELOW_REQUIREMENT("Below required strength", "आवश्यक शक्तिभन्दा तल"),
SHADBALA_BREAKDOWN("Strength Breakdown", "शक्ति विवरण"),
SHADBALA_CALCULATING("Calculating Shadbala...", "षड्बल गणना गर्दै..."),
SHADBALA_CHART_ANALYSIS("Chart Strength Analysis", "कुण्डली शक्ति विश्लेषण"),
SHADBALA_CALCULATION_ERROR("Failed to calculate Shadbala", "षडबल गणना गर्न असफल भयो"),
SHADBALA_STHANA("Sthana", "स्थान"),
SHADBALA_DIG("Dig", "दिक्"),
SHADBALA_KALA("Kala", "काल"),
SHADBALA_CHESTA("Chesta", "चेष्टा"),
SHADBALA_TOTAL("Total", "कुल"),
SHADBALA_EXTREMELY_WEAK("Extremely Weak", "अत्यन्त कमजोर"),
SHADBALA_WEAK("Weak", "कमजोर"),
SHADBALA_BELOW_AVERAGE("Below Average", "औसतभन्दा तल"),
SHADBALA_AVERAGE("Average", "औसत"),
SHADBALA_ABOVE_AVERAGE("Above Average", "औसतभन्दा माथि"),
SHADBALA_STRONG("Strong", "बलियो"),
SHADBALA_VERY_STRONG("Very Strong", "धेरै बलियो"),
SHADBALA_EXTREMELY_STRONG("Extremely Strong", "अत्यन्त बलियो"),
}
