package com.astro.storm.core.common

enum class StringKeyGeneralPart11(override val en: String, override val ne: String) : StringKeyInterface {
    SYMBOL_PURVA_ASHADHA("Elephant Tusk/Fan", "हात्तीको दाह्रा/हाते पंखा"),
    SYMBOL_PURVA_BHADRAPADA("Sword/Two Front Legs", "तरवार/अघिल्ला दुई खुट्टा"),
    SYMBOL_PURVA_PHALGUNI("Swinging Hammock", "झुल्ने खाट"),
    SYMBOL_PUSHYA("Cow's Udder/Flower", "गाईको थुन/फूल"),
    SYMBOL_REVATI("Fish/Drum", "माछा/डमरु"),
    SYMBOL_ROHINI("Cart/Chariot", "गाडा/रथ"),
    SYMBOL_SHATABHISHA("Empty Circle", "खाली घेरा"),
    SYMBOL_SHRAVANA("Ear/Arrow", "कान/काँड"),
    SYMBOL_SWATI("Coral/Sword", "मुगा/तरवार"),
    SYMBOL_UTTARA_ASHADHA("Elephant Tusk/Bed", "हात्तीको दाह्रा/खाट"),
    SYMBOL_UTTARA_BHADRAPADA("Twin/Back Legs", "जुम्ल्याहा/पछिल्ला खुट्टा"),
    SYMBOL_UTTARA_PHALGUNI("Bed/Legs of Cot", "खाट/पलङको खुट्टा"),
    SYMBOL_VISHAKHA("Triumphal Arch", "विजय द्वार"),
    SYNASTRY_ANALYZING("Analyzing synastry...", "सिनेस्ट्री विश्लेषण गर्दै..."),
    SYNASTRY_APPLYING("Applying", "निकट आउँदै"),
    SYNASTRY_ASCENDANT("Ascendant Connections", "लग्न सम्बन्धहरू"),
    SYNASTRY_ASPECTS("Inter-Aspects", "अन्तर-दृष्टिहरू"),
    SYNASTRY_ASPECT_ORB("Orb: %.1fÂ°", "ओर्ब: %.1f°"),
    SYNASTRY_AVAILABLE_CHARTS("%d charts available", "%d कुण्डलीहरू उपलब्ध छन्"),
    SYNASTRY_CALCULATE("Analyze Synastry", "सिनेस्ट्री विश्लेषण गर्नुहोस्"),
    SYNASTRY_CALC_FAILED("Calculation failed", "गणना असफल भयो"),
    SYNASTRY_CHALLENGING("Challenging Aspects", "चुनौतीपूर्ण दृष्टिहरू"),
    SYNASTRY_CHART_1("Chart 1", "कुण्डली १"),
    SYNASTRY_CHART_2("Chart 2", "कुण्डली २"),
    SYNASTRY_CLEAR("Clear Selection", "छनौट खाली गर्नुहोस्"),
    SYNASTRY_COMMUNICATION("Communication", "सञ्चार"),
    SYNASTRY_COMPATIBILITY("Compatibility", "अनुकूलता"),
    SYNASTRY_CONJUNCTION("Conjunction", "युति"),
    SYNASTRY_DESC_COMMUNICATION("Mental connection and dialogue", "मानसिक सम्बन्ध र संवाद"),
    SYNASTRY_DESC_EMOTIONAL("Emotional understanding and nurturing", "भावनात्मक समझदारी र पोषण"),
    SYNASTRY_DESC_GROWTH("Mutual expansion and learning", "आपसी विस्तार र सिकाइ"),
    SYNASTRY_DESC_ROMANCE("Physical attraction and passion", "शारीरिक आकर्षण र जुनून"),
    SYNASTRY_DESC_STABILITY("Commitment and endurance", "प्रतिबद्धता र धैर्यता"),
    SYNASTRY_EMOTIONAL_BOND("Emotional Bond", "भावनात्मक बन्धन"),
    SYNASTRY_FINDING_ASPECT("Strong %1\$s between %2\$s and %3\$s", "%2\$s र %3\$s बीच बलियो %1\$s"),
    SYNASTRY_FINDING_HOUSE("%1\$s activates the %2\$dth house of %3\$s", "%1\$s ले %3\$s को %2\$d भावलाई सक्रिय गर्दछ"),
    SYNASTRY_GROWTH("Growth & Evolution", "वृद्धि र विकास"),
    SYNASTRY_HARMONIOUS("Harmonious Aspects", "सामञ्जस्यपूर्ण दृष्टिहरू"),
    SYNASTRY_HOUSES("House Overlays", "भाव ओभरले"),
    SYNASTRY_HOUSE_IN("in House", "भावमा"),
    SYNASTRY_HOUSE_INFLUENCE("House Influences", "भाव प्रभावहरू"),
    SYNASTRY_INFO_DESC("Synastry compares two birth charts to analyze relationship dynamics, compatibility, and areas of harmony or challenge between individuals.", "सिनेस्ट्रीले दुई जन्म कुण्डलीहरू तुलना गरेर व्यक्तिहरू बीचको सम्बन्ध गतिशीलता, अनुकूलता, र सामञ्जस्य वा चुनौतीका क्षेत्रहरू विश्लेषण गर्दछ।"),
    SYNASTRY_INFO_TITLE("About Synastry", "सिनेस्ट्रीको बारेमा"),
    SYNASTRY_INTERPRET_ASCENDANT("%1\$s conjunct Person %2\$d's Ascendant creates a strong personal connection.", "%1\$s व्यक्ति %2\$d को लग्नमा हुनुले एक बलियो व्यक्तिगत सम्बन्ध सिर्जना गर्दछ।"),
    SYNASTRY_INTERPRET_CHALLENGING("%1\$s and %2\$s create tension that requires conscious effort to integrate.", "%1\$s र %2\$s ले तनाव सिर्जना गर्दछन् जसलाई एकीकृत गर्न सचेत प्रयासको आवश्यक पर्दछ।"),
    SYNASTRY_INTERPRET_HARMONIOUS("%1\$s and %2\$s work together harmoniously, creating mutual understanding and support.", "%1\$s र %2\$s सामञ्जस्यपूर्ण रूपमा सँगै काम गर्छन्, जसले आपसी समझदारी र समर्थन सिर्जना गर्दछ।"),
    SYNASTRY_INTERPRET_MAJOR("%1\$s and %2\$s are closely connected, amplifying each other's energies.", "%1\$s र %2\$s नजिकबाट जोडिएका छन्, एक अर्काको ऊर्जालाई बढाउँदै।"),
    SYNASTRY_INTERPRET_MINOR("%1\$s and %2\$s have a subtle connection that adds nuance to the relationship.", "%1\$s र %2\$s बीच एक सूक्ष्म सम्बन्ध छ जसले सम्बन्धमा नयाँ पक्ष थप्दछ।"),
    SYNASTRY_INTERPRET_OVERLAY("Person %1\$d's %2\$s falls in the %3\$dth house, influencing %4\$s.", "व्यक्ति %1\$d को %2\$s %3\$d भावमा पर्दछ, जसले %4\$s लाई प्रभावित गर्दछ।"),
    SYNASTRY_KEY_ASPECTS("Key Synastry Aspects", "मुख्य सिनेस्ट्री दृष्टिहरू"),
    SYNASTRY_LAGNA("Lagna", "लग्न"),
    SYNASTRY_LIFE_AREA_GENERAL("General", "सामान्य"),
    SYNASTRY_MODERATE("Moderate", "मध्यम"),
    SYNASTRY_MOON("Moon", "चन्द्र"),
    SYNASTRY_MUTUAL_ASPECTS("Mutual Aspects", "पारस्परिक दृष्टिहरू"),
    SYNASTRY_NO_ASPECTS("No significant aspects found", "कुनै महत्त्वपूर्ण दृष्टि फेला परेन"),
    SYNASTRY_OPPOSITION("Opposition", "प्रतिपक्ष"),
    SYNASTRY_OVERALL_SCORE("Overall Compatibility Score", "समग्र अनुकूलता स्कोर"),
    SYNASTRY_OVERVIEW("Overview", "अवलोकन"),
    SYNASTRY_PLANET_CONNECTIONS("Planetary Connections", "ग्रह सम्बन्धहरू"),
    SYNASTRY_PLANET_IN_HOUSE("%s in %s's House %d", "%s को भाव %d मा %s"),
    SYNASTRY_QUINCUNX("Quincunx", "क्विनकनक्स"),
    SYNASTRY_ROMANCE("Romance & Attraction", "रोमान्स र आकर्षण"),
    SYNASTRY_SELECT_BOTH("Please select both charts to compare", "कृपया तुलना गर्न दुवै कुण्डली छान्नुहोस्"),
    SYNASTRY_SELECT_CHARTS("Select Charts to Compare", "तुलना गर्न कुण्डलीहरू छान्नुहोस्"),
    SYNASTRY_SEMI_SEXTILE("Semi-Sextile", "अर्ध-षड्भाग"),
    SYNASTRY_SEPARATING("Separating", "टाढा जाँदै"),
    SYNASTRY_SEXTILE("Sextile", "षड्भाग"),
    SYNASTRY_SQUARE("Square", "चतुर्थांश"),
    SYNASTRY_STABILITY("Long-term Stability", "दीर्घकालीन स्थिरता"),
    SYNASTRY_STRONG("Strong", "बलियो"),
    SYNASTRY_SUBTITLE("Synastry Analysis", "सिनेस्ट्री विश्लेषण"),
    SYNASTRY_SUN_MOON("Sun-Moon Aspects", "सूर्य-चन्द्र दृष्टिहरू"),
    SYNASTRY_SWAP("Swap Charts", "कुण्डलीहरू स्वाप गर्नुहोस्"),
    SYNASTRY_TITLE("Chart Comparison", "कुण्डली तुलना"),
    SYNASTRY_TRINE("Trine", "त्रिकोण"),
    SYNASTRY_VENUS("Venus", "शुक्र"),
    SYNASTRY_VENUS_MARS("Venus-Mars Aspects", "शुक्र-मंगल दृष्टिहरू"),
    SYNASTRY_WEAK("Weak", "कमजोर"),
    SYSTEM_NOTE("Lal Kitab is a distinct astrological system from classical Vedic astrology. These remedies are based on Lal Kitab principles and traditions.", "लाल किताब शास्त्रीय वैदिक ज्योतिषभन्दा फरक एक विशिष्ट ज्योतिष प्रणाली हो। यी उपायहरू लाल किताबका सिद्धान्त र परम्परामा आधारित छन्।"),
    TAP_TO_VIEW_DASHAS("Tap to view your Dasha timeline", "आफ्नो दशा समयरेखा हेर्न ट्याप गर्नुहोस्"),
    TARABALA_ACTIVITIES("Activities", "गतिविधिहरू"),
    TARABALA_ALL_27_DESC("All 27 Nakshatras with their Tarabala values", "सबै २७ नक्षत्र तिनीहरूको तारबल मानहरू साथ"),
    TARABALA_ALL_NAKSHATRAS("All 27 Nakshatras", "सबै २७ नक्षत्र"),
    TARABALA_ALL_TARAS("All 27 Nakshatras", "सबै २७ नक्षत्रहरू"),
    TARABALA_AVOID_ACTIVITIES("Activities to Avoid", "टाढा रहने गतिविधिहरू"),
    TARABALA_AVOID_DAY("Day to Avoid", "टाढा रहनु पर्ने दिन"),
    TARABALA_BEST_DAY("Best Day", "उत्तम दिन"),
    TARABALA_BEST_LABEL("Best", "सबैभन्दा राम्रो"),
    TARABALA_BIRTH_NAKSHATRA("Birth Nakshatra", "जन्म नक्षत्र"),
    TARABALA_BIRTH_STAR("Birth Star", "जन्म नक्षत्र"),
    TARABALA_CHALLENGING("Challenging", "चुनौतीपूर्ण"),
    TARABALA_CYCLE("Cycle", "चक्र"),
    TARABALA_DAILY_BREAKDOWN("Daily Breakdown", "दैनिक विभाजन"),
    TARABALA_DAILY_SCORE("Daily Strength Score", "दैनिक बल स्कोर"),
    TARABALA_DESC_JANMA("Birth star - challenging for new beginnings", "जन्म नक्षत्र - नयाँ सुरुवातीका लागि चुनौतीपूर्ण"),
    TARABALA_DESC_KSHEMA("Well-being - favorable for health matters", "कल्याण - स्वास्थ्य मामिलाका लागि शुभ"),
    TARABALA_DESC_MITRA("Friend - favorable for relationships", "मित्र - सम्बन्धका लागि शुभ"),
    TARABALA_DESC_PARAMA_MITRA("Great Friend - highly auspicious", "परम मित्र - अत्यन्त शुभ"),
    TARABALA_DESC_PRATYARI("Obstacle - creates hindrances", "बाधा - अवरोधहरू सिर्जना गर्दछ"),
    TARABALA_DESC_SADHAKA("Achievement - good for goals", "उपलब्धि - लक्ष्यका लागि राम्रो"),
    TARABALA_DESC_SAMPAT("Wealth - favorable for financial matters", "सम्पत्ति - आर्थिक मामिलाका लागि शुभ"),
    TARABALA_DESC_VADHA("Death - highly inauspicious", "वध - अत्यन्त अशुभ"),
    TARABALA_DESC_VIPAT("Danger - avoid important activities", "खतरा - महत्त्वपूर्ण कार्यहरू नगर्नुहोस्"),
    TARABALA_EXPLANATION("Explanation", "व्याख्या"),
    TARABALA_FAVORABLE("Favorable", "अनुकूल"),
    TARABALA_FAVORABLE_ACTIVITIES("Favorable Activities", "अनुकूल गतिविधिहरू"),
    TARABALA_GENERAL_ADVICE("General Advice", "सामान्य सल्लाह"),
    TARABALA_JANMA("Janma", "जन्म"),
    TARABALA_KSHEMA("Kshema", "क्षेम"),
    TARABALA_LABEL("Tarabala", "तारबल"),
    TARABALA_MITRA("Mitra", "मित्र"),
    TARABALA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),
    TARABALA_PRATYARI("Pratyari", "प्रत्यरि"),
    TARABALA_SADHAKA("Sadhaka", "साधक"),
    TARABALA_SAMPAT("Sampat", "सम्पत"),
    TARABALA_STAR_STRENGTH("Star Strength", "नक्षत्र शक्ति"),
    TARABALA_SUBTITLE("Daily Strength Analysis", "दैनिक बल विश्लेषण"),
    TARABALA_TARA_TYPE("Tara Type", "तार प्रकार"),
    TARABALA_TITLE("Tarabala & Chandrabala", "ताराबल र चन्द्रबल"),
    TARABALA_TODAY("Today's Tarabala", "आजको ताराबल"),
    TARABALA_TODAY_STRENGTH("Today's Strength", "आजको शक्ति"),
    TARABALA_TRANSIT_NAKSHATRA("Transit Nakshatra", "गोचर नक्षत्र"),
    TARABALA_TRANSIT_STAR("Transit Star", "गोचर नक्षत्र"),
    TARABALA_UNABLE_CALCULATE("Unable to calculate Tarabala without birth details", "जन्म विवरण बिना तारबल गणना गर्न सक्षम छैन"),
    TARABALA_UNFAVORABLE("Unfavorable", "प्रतिकूल"),
    TARABALA_VADHA("Vadha", "वध"),
    TARABALA_VIPAT("Vipat", "विफत"),
    TARABALA_WEEKLY("Weekly Forecast", "साप्ताहिक पूर्वानुमान"),
    TARABALA_WEEKLY_ADVICE("Weekly Guidance", "साप्ताहिक मार्गदर्शन"),
    TARABALA_WEEKLY_OVERVIEW("Weekly Overview", "साप्ताहिक सिंहावलोकन"),
    TARABALA_WHAT_IS("What is Tarabala?", "तारबल के हो?"),
    TARABALA_WORST_DAY("Challenging Day", "चुनौतीपूर्ण दिन"),
    TARA_CATEGORIES_EXPLAINED("Nakshatras are grouped in sets of 9 from each person's birth star. Janma, Vipat, and Vadha taras are inauspicious; Sampat, Kshema, Sadhana, and Mitra taras are auspicious.", "नक्षत्रहरू प्रत्येक व्यक्तिको जन्म ताराबाट ९ को सेटमा समूहीकृत गरिन्छ। जन्म, विपत् र वध तारा अशुभ हुन्; सम्पत्, क्षेम, साधना र मित्र तारा शुभ हुन्।"),
    TARA_DESC("Destiny and birth star compatibility", "भाग्य र जन्म तारा अनुकूलता"),
    TARA_EXCELLENT("Both have auspicious Taras - excellent destiny compatibility. Harmonious life path.", "दुवैको शुभ तारा छ - उत्कृष्ट भाग्य अनुकूलता। सामञ्जस्यपूर्ण जीवन मार्ग।"),
    TARA_IMPORTANCE("Tara analyzes birth star compatibility to determine destiny harmony. It predicts how well the couple's life paths align and support each other.", "तारा भाग्य सामञ्जस्य निर्धारण गर्न जन्म तारा अनुकूलता विश्लेषण गर्दछ। यसले जोडीको जीवन मार्गहरू कत्तिको राम्रोसँग मिल्छन् र एकअर्कालाई समर्थन गर्छन् भनेर भविष्यवाणी गर्दछ।"),
    TARA_INAUSPICIOUS("Both Taras are inauspicious - may face obstacles together. Remedies recommended.", "दुवै तारा अशुभ - सँगै अवरोधहरू सामना गर्न सक्छन्। उपायहरू सिफारिस गरिएको।"),
    TARA_JANMA("Janma", "जन्म"),
    TARA_JANMA_DESC("Birth star day - rest and introspection recommended", "जन्म नक्षत्र दिन - आराम र आत्मचिन्तन सिफारिस"),
    TARA_JANMA_REC_1("Birth star day - rest and introspection recommended", "जन्म नक्षत्रको दिन - आराम र आत्मनिरीक्षण सिफारिस गरिएको छ"),
    TARA_JANMA_REC_2("Avoid starting new ventures", "नयाँ उद्यमहरू सुरु गर्नबाट बच्नुहोस्"),
    TARA_JANMA_REC_3("Good for spiritual practices and meditation", "आध्यात्मिक अभ्यास र ध्यानको लागि राम्रो"),
    TARA_JANMA_REC_4("Health requires extra attention", "स्वास्थ्यमा अतिरिक्त ध्यान आवश्यक छ"),
    TARA_KSHEMA("Kshema", "क्षेम"),
    TARA_KSHEMA_DESC("Well-being star - favorable for health matters", "क्षेम नक्षत्र - स्वास्थ्य मामिलाहरूको लागि अनुकूल"),
    TARA_KSHEMA_REC_1("Good for health-related activities", "स्वास्थ्य सम्बन्धी गतिविधिहरूको लागि राम्रो"),
    TARA_KSHEMA_REC_2("Favorable for medical treatments", "चिकित्सा उपचारको लागि अनुकूल"),
    TARA_KSHEMA_REC_3("Support well-being initiatives", "कल्याणकारी पहलहरूलाई समर्थन गर्नुहोस्"),
    TARA_KSHEMA_REC_4("Safe for moderate new undertakings", "मध्यम नयाँ उपक्रमहरूको लागि सुरक्षित"),
    TARA_MITRA("Mitra", "मित्र"),
    TARA_MITRA_DESC("Friend star - favorable for relationships", "मित्र नक्षत्र - सम्बन्धहरूको लागि अनुकूल"),
    TARA_MITRA_REC_1("Favorable for relationships", "सम्बन्धका लागि अनुकूल"),
    TARA_MITRA_REC_2("Good for meetings and collaborations", "बैठक र सहयोगका लागि राम्रो"),
    TARA_MITRA_REC_3("Support partnerships and friendships", "साझेदारी र मित्रतालाई समर्थन गर्नुहोस्"),
    TARA_MITRA_REC_4("Suitable for social activities", "सामाजिक गतिविधिहरूको लागि उपयुक्त"),
    TARA_MODERATE("One auspicious Tara present - moderate destiny compatibility.", "एउटा शुभ तारा उपस्थित - मध्यम भाग्य अनुकूलता।"),
    TARA_PARAMA_MITRA("Parama Mitra", "परम मित्र"),
    TARA_PARAMA_MITRA_DESC("Great friend star - most auspicious for everything", "परम मित्र नक्षत्र - सबैको लागि सबैभन्दा शुभ"),
    TARA_PARAMA_MITRA_REC_1("Most auspicious tara - excellent for everything", "सबैभन्दा शुभ तारा - सबै कुराका लागि उत्कृष्ट"),
    TARA_PARAMA_MITRA_REC_2("Ideal for starting new ventures", "नयाँ उद्यमहरू सुरु गर्नका लागि आदर्श"),
    TARA_PARAMA_MITRA_REC_3("Best time for important decisions", "महत्त्वपूर्ण निर्णयहरूको लागि उत्तम समय"),
    TARA_PARAMA_MITRA_REC_4("Maximum success probability", "अधिकतम सफलताको सम्भावना"),
    TARA_PRATYARI("Pratyari", "प्रत्यारि"),
    TARA_PRATYARI_DESC("Obstacle star - expect minor hindrances", "प्रत्यारि नक्षत्र - सानातिना बाधाहरू अपेक्षा गर्नुहोस्"),
    TARA_PRATYARI_REC_1("Expect minor obstacles", "सानो बाधाहरूको अपेक्षा गर्नुहोस्"),
    TARA_PRATYARI_REC_2("Stay patient with challenges", "चुनौतीहरूको साथ धैर्यवान रहनुहोस्"),
    TARA_PRATYARI_REC_3("Avoid confrontations", "द्वन्द्वबाट बच्नुहोस्"),
    TARA_PRATYARI_REC_4("Not ideal for important meetings", "महत्त्वपूर्ण बैठकहरूको लागि आदर्श छैन"),
    TARA_REMEDY_LOW("Remedy: Perform Nakshatra Shanti puja for both birth stars. Donate black sesame, iron, and blue cloth on Saturdays. Chant Maha Mrityunjaya Mantra 108 times daily for 40 days to neutralize destiny obstacles.", "उपाय: दुवै जन्म नक्षत्रको लागि नक्षत्र शान्ति पूजा गर्नुहोस्। शनिबारमा कालो तिल, फलाम र नीलो कपडा दान गर्नुहोस्। भाग्य बाधाहरू निष्क्रिय गर्न ४० दिन दैनिक १०८ पटक महा मृत्युञ्जय मन्त्र जाप गर्नुहोस्।"),
    TARA_SADHAKA("Sadhaka", "साधक"),
    TARA_SADHAKA_DESC("Achievement star - good for completing goals", "साधक नक्षत्र - लक्ष्य पूरा गर्नको लागि राम्रो"),
    TARA_SADHAKA_REC_1("Good for achieving goals", "लक्ष्यहरू प्राप्त गर्नका लागि राम्रो"),
    TARA_SADHAKA_REC_2("Favorable for completing tasks", "कार्यहरू पूरा गर्नका लागि अनुकूल"),
    TARA_SADHAKA_REC_3("Support ongoing projects", "चलिरहेका परियोजनाहरूलाई समर्थन गर्नुहोस्"),
    TARA_SADHAKA_REC_4("Moderate success in new ventures", "नयाँ उद्यमहरूमा मध्यम सफलता"),
    TARA_SADHANA("Sadhana (Achievement)", "साधना (उपलब्धि)"),
    TARA_SAMPAT("Sampat", "सम्पत्"),
    TARA_SAMPAT_DESC("Wealth star - excellent for financial matters", "धन नक्षत्र - आर्थिक मामिलाहरूको लागि उत्कृष्ट"),
    TARA_SAMPAT_REC_1("Excellent for financial matters", "वित्तीय मामिलाहरूको लागि उत्कृष्ट"),
    TARA_SAMPAT_REC_2("Start wealth-generating activities", "धन उत्पन्न गर्ने गतिविधिहरू सुरु गर्नुहोस्"),
    TARA_SAMPAT_REC_3("Good for investments and purchases", "लगानी र खरिदको लागि राम्रो"),
    TARA_SAMPAT_REC_4("Favorable for business negotiations", "व्यापारिक वार्ताको लागि अनुकूल"),
    TARA_VADHA("Vadha", "वध"),
    TARA_VADHA_DESC("Death star - highly inauspicious, maximum caution", "वध नक्षत्र - अत्यन्त अशुभ, अधिकतम सावधानी"),
    TARA_VADHA_REC_1("Most inauspicious tara - maximum caution", "सबैभन्दा अशुभ तारा - अधिकतम सावधानी"),
    TARA_VADHA_REC_2("Avoid all major activities", "सबै प्रमुख गतिविधिहरूबाट बच्नुहोस्"),
    TARA_VADHA_REC_3("Not suitable for travel or surgery", "यात्रा वा शल्यक्रियाका लागि उपयुक्त छैन"),
    TARA_VADHA_REC_4("Focus on prayers and spiritual protection", "प्रार्थना र आध्यात्मिक सुरक्षामा ध्यान दिनुहोस्"),
    TARA_VIPAT("Vipat", "विपत्"),
    TARA_VIPAT_DESC("Danger star - avoid important activities", "विपत् नक्षत्र - महत्त्वपूर्ण गतिविधिहरू टाळ्नुहोस्"),
    TARA_VIPAT_REC_1("Avoid important decisions", "महत्त्वपूर्ण निर्णयहरू लिनबाट बच्नुहोस्"),
    TARA_VIPAT_REC_2("Be cautious in travels", "यात्रामा सावधान रहनुहोस्"),
    TARA_VIPAT_REC_3("Not suitable for new beginnings", "नयाँ सुरुवातका लागि उपयुक्त छैन"),
    TARA_VIPAT_REC_4("Focus on routine activities only", "नियमित गतिविधिहरूमा मात्र ध्यान दिनुहोस्"),
    TARGET_PLANET("For Planet", "ग्रहको लागि"),
    TEACHING_ABILITY("Teaching Ability", "शिक्षण क्षमता"),
    TEAMWORK_APPROACH("Teamwork Approach", "टोली कार्य दृष्टिकोण"),
    TEMPERAMENT_AIR("Air Temperament", "वायु स्वभाव"),
    TEMPERAMENT_CARDINAL("Cardinal Modality", "कार्डिनल मोडालिटी"),
    TEMPERAMENT_EARTH("Earth Temperament", "पृथ्वी स्वभाव"),
    TEMPERAMENT_FIRE("Fire Temperament", "अग्नि स्वभाव"),
    TEMPERAMENT_FIXED("Fixed Modality", "स्थिर मोडालिटी"),
    TEMPERAMENT_MUTABLE("Mutable Modality", "परिवर्तनशील मोडालिटी"),
    TEMPERAMENT_WATER("Water Temperament", "जल स्वभाव"),
    TENTH_HOUSE_ASPECTS("Aspects to 10th House", "दशम भावमा दृष्टिहरू"),
    TENTH_HOUSE_LORD("10th House Lord", "दशम भाव स्वामी"),
    TENTH_HOUSE_PLANETS("Planets in 10th House", "दशम भावमा ग्रहहरू"),
    TENTH_HOUSE_SIGN("10th House Sign", "दशम भाव राशि"),
    TENTH_HOUSE_STRENGTH("10th House Strength", "दशम भाव बल"),
    THE_EIGHT_POSITIONS("The Eight Positions", "आठ स्थितिहरू"),
    TIME_AFTERNOON("Afternoon hours", "दिउँसोको समय"),
    TIME_AVOID_DAY("Avoid Acting On", "यो दिनमा नगर्नुहोस्"),
    TIME_BEST_DAY("Best Day for Action", "कार्यको लागि उत्तम दिन"),
    TIME_DAYS("%dd", "%d दिन"),
    TIME_DELAYED("Delayed (1+ year)", "ढिलो (१+ वर्ष)"),
    TIME_EVENING("Evening hours", "साँझको समय"),
    TIME_IMMEDIATE("Immediate (1-7 days)", "तुरुन्तै (१-७ दिन)"),
    TIME_IN("in %s", "%s मा"),
    TIME_LONG("Long term (3-12 months)", "लामो अवधि (३-१२ महिना)"),
    TIME_MEDIUM("Medium term (1-3 months)", "मध्यम अवधि (१-३ महिना)"),
    TIME_MONTHS("%dm", "%d महिना"),
    TIME_MORNING("Morning hours", "बिहानको समय"),
    TIME_SHORT("Short term (1-4 weeks)", "छोटो अवधि (१-४ हप्ता)"),
    TIME_TITLE("Timing Prediction", "समय भविष्यवाणी"),
    TIME_UNCERTAIN("Timing Uncertain", "समय अनिश्चित"),
    TIME_WEEKS("%dw", "%d हप्ता"),
    TIME_YEARS("%dy", "%d वर्ष"),
    TIMING_ADVICE("Investment Timing Advice", "लगानी समय सल्लाह"),
    TIMING_ANALYSIS("Timing Analysis", "समय विश्लेषण"),
    TIMING_CATEGORY("Timing Category", "समय श्रेणी"),
    TIMING_DAILY_EVENING("Daily in the evening", "दैनिक साँझमा"),
    TIMING_DAWN_DUSK("Daily, preferably at dawn and dusk", "दैनिक, प्राथमिकताका साथ सूर्योदय र सूर्यास्तमा"),
    TIMING_DELAYED("Delayed Marriage", "ढिलो विवाह"),
    TIMING_DENIED("Marriage Challenges", "विवाह चुनौतीहरू"),
    TIMING_EARLY("Early Marriage", "प्रारम्भिक विवाह"),
    TIMING_EVERY_MONDAY("Every Monday", "हरेक सोमबार"),
    TIMING_INDICATION("Timing indication", "समय संकेत"),
    TIMING_MONDAY_EVENING("Monday evenings", "सोमबार साँझ"),
    TIMING_MONDAY_HORA("Monday evenings, during Moon hora", "सोमबार साँझ, चन्द्र होरामा"),
    TIMING_NORMAL("Normal Marriage Age", "सामान्य विवाह उमेर"),
    TIMING_ONGOING("Ongoing", "निरन्तर"),
    TIMING_PURNIMA("Mondays, especially on Purnima", "सोमबार, विशेष गरी पूर्णिमामा"),
    TIMING_SHUKLA_PAKSHA("On a Monday in Shukla Paksha", "शुक्ल पक्षको सोमबार"),
    TITLE("Sahams (Arabic Parts)", "सहम (अरबी भाग)"),
    TITLE_ACADEMIC_POTENTIAL("Academic Potential", "शैक्षिक सम्भावना"),
    TITLE_ASCENDANT_TRAITS("Ascendant Traits", "लग्नका विशेषताहरू"),
    TITLE_CAREER_STRENGTH("Career Strength", "क्यारियरको बल"),
    TITLE_MOON_SIGN_INFLUENCE("Moon Sign Influence", "चन्द्र राशिको प्रभाव"),
    TITLE_NAKSHATRA_INFLUENCE("Nakshatra Influence", "नक्षत्रको प्रभाव"),
    TITLE_RELATIONSHIP_STRENGTH("Relationship Strength", "सम्बन्धको बल"),
    TITLE_SPIRITUAL_INCLINATION("Spiritual Inclination", "आध्यात्मिक झुकाव"),
    TITLE_WEALTH_POTENTIAL("Wealth Potential", "धनको सम्भावना"),
    TO("to", "देखि"),
    TODAYS_SNAPSHOT("Today's Snapshot", "आजको झलक"),
    TODO_IN_PROGRESS("In Progress", "प्रगतिमा"),
    TOOLS_MORE_COUNT(" +%d more", " +%d थप"),
    TOOLS_USED_LABEL("Used: %s", "प्रयोग गरियो: %s"),
    TOOL_STATUS_COMPLETED_IN("Completed in %s", "%s मा सम्पन्न"),
    TOOL_STATUS_FAILED("Failed", "असफल"),
    TOOL_STATUS_PENDING("Pending", "पर्खिएको"),
    TOOL_STATUS_RUNNING("Running...", "चलिरहेको..."),
    TOTAL_SAHAMS("Total Sahams", "कुल सहमहरू"),
    TRAITS_CAREER_GENERIC("Success in fields aligned with the planet's nature", "ग्रहको प्रकृतिसँग मिल्दाजुल्दा क्षेत्रमा सफलता"),
    TRAITS_MENTAL_BHADRA("Sharp intellect, excellent memory, witty communication", "तीखो बुद्धि, उत्कृष्ट स्मरणशक्ति, रोचक सञ्चार"),
    TRAITS_MENTAL_HAMSA("Wisdom, philosophical outlook, positive thinking", "ज्ञान, दार्शनिक दृष्टिकोण, सकारात्मक सोच"),
    TRAITS_MENTAL_MALAVYA("Refined sensibilities, appreciation of beauty, romantic nature", "परिष्कृत संवेदनशीलता, सौन्दर्यको प्रशंसा, रोमान्टिक स्वभाव"),
    TRAITS_MENTAL_RUCHAKA("Fearless mindset, competitive spirit, quick decision-making", "निडर मानसिकता, प्रतिस्पर्धात्मक भावना, द्रुत निर्णय क्षमता"),
    TRAITS_MENTAL_SASHA("Disciplined mind, methodical thinking, patience", "अनुशासित दिमाग, व्यवस्थित सोच, धैर्य"),
    TRAITS_PHYSICAL_BHADRA("Youthful appearance, expressive gestures, quick movements", "युवा उपस्थिति, अर्थपूर्ण हाउभाउ, छिटो चाल"),
    TRAITS_PHYSICAL_HAMSA("Graceful bearing, fair complexion, pleasant appearance", "शालीन स्वभाव, गोरो वर्ण, रमाइलो उपस्थिति"),
    TRAITS_PHYSICAL_MALAVYA("Attractive appearance, pleasant features, artistic grace", "आकर्षक उपस्थिति, सुखद अनुहार, कलात्मक अनुग्रह"),
    TRAITS_PHYSICAL_RUCHAKA("Strong physical constitution, athletic build, courage in action", "बलियो शारीरिक बनावट, एथलेटिक शरीर, कार्यमा साहस"),
    TRAITS_PHYSICAL_SASHA("Lean build, serious demeanor, endurance and stamina", "दुब्लो बनावट, गम्भीर व्यवहार, सहनशक्ति र सामर्थ्य"),
    TRAITS_RELATIONSHIP_GENERIC("Impact on interpersonal dynamics and social standing", "अन्तरव्यक्तिगत गतिशीलता र सामाजिक स्थितिमा प्रभाव"),
    TRAITS_SPIRITUAL_GENERIC("Inclination toward higher values and spiritual paths", "उच्च मूल्य र आध्यात्मिक मार्गहरू प्रति झुकाव"),
    TRAIT_ADAPTABILITY("Adaptability", "अनुकूलनशीलता"),
    TRAIT_ADAPTABLE("Adaptable", "अनुकूलनशील"),
    TRAIT_AFFECTIONATE("Affectionate", "मायालु"),
    TRAIT_AMBITIOUS("Ambitious", "महत्त्वाकांक्षी"),
    TRAIT_ANALYTICAL("Analytical thinking", "विश्लेषणात्मक सोच"),
    TRAIT_ANCESTRAL_PRIDE("Ancestral pride", "पैतृक गौरव"),
    TRAIT_ARTISTIC("Artistic", "कलात्मक"),
    TRAIT_ARTISTIC_MASTERY("Artistic mastery", "कलात्मक निपुणता"),
    TRAIT_ARTISTIC_TALENT("Artistic talent", "कलात्मक प्रतिभा"),
    TRAIT_ASCETICISM("Asceticism", "तपस्या"),
    TRAIT_BEARING_RESPONSIBILITY("Bearing responsibility", "जिम्मेवारी वहन गर्ने"),
    TRAIT_BRILLIANT("Brilliant", "प्रतिभाशाली"),
    TRAIT_BUSINESS_ACUMEN("Business acumen", "व्यापारिक सुझबुझ"),
    TRAIT_CLEVER("Clever", "चलाख"),
    TRAIT_COMMUNICATION("Communication skills", "सञ्चार कौशल"),
    TRAIT_COMPASSION("Compassion", "करुणा"),
    TRAIT_CONNECTION_TO_TRUTH("Connection to truth", "सत्यसँगको सम्बन्ध"),
    TRAIT_CONTRACT_KEEPER("Contract-keeper", "सम्झौता पालन गर्ने"),
    TRAIT_CONTROL_OVER_DESIRES("Control over desires", "इच्छाहरूमा नियन्त्रण"),
    TRAIT_CREATIVE("Creative", "रचनात्मक"),
    TRAIT_CREATIVE_GENIUS("Creative genius", "सिर्जनात्मक प्रतिभा"),
    TRAIT_CREATIVITY("Creative expression", "रचनात्मक अभिव्यक्ति"),
    TRAIT_CURIOUS_MIND("Curious mind", "जिज्ञासु मन"),
    TRAIT_DEEP_MEDITATION("Deep meditation", "गहिरो ध्यान"),
    TRAIT_DESTRUCTIVE_CREATIVE("Destructive-creative", "विनाशकारी-रचनात्मक"),
    TRAIT_DETERMINATION("Determination", "दृढता"),
    TRAIT_DETERMINED("Determined", "दृढ संकल्पित"),
    TRAIT_DEVOTED("Devoted", "समर्पित"),
    TRAIT_DIPLOMACY("Diplomatic skills", "कूटनीतिक कौशल"),
    TRAIT_DIPLOMATIC("Diplomatic", "कूटनीतिक"),
    TRAIT_ELDER_BROTHER_ENERGY("Elder brother energy", "ठूलो दाइको जस्तो ऊर्जा"),
    TRAIT_FIERY_DETERMINATION("Fiery determination", "अग्नि जस्तै दृढ संकल्प"),
    TRAIT_FIERY_PASSION("Fiery passion", "तीव्र जोश"),
    TRAIT_FINAL_VICTORY("Final victory", "अन्तिम विजय"),
    TRAIT_FRIENDLY("Friendly", "मिलनसार"),
    TRAIT_GENTLE_DEMEANOR("Gentle demeanor", "कोमल व्यवहार"),
    TRAIT_GOAL_ORIENTED("Goal-oriented", "लक्ष्यमुखी"),
    TRAIT_GOOD_LISTENER("Good listener", "राम्रो श्रोता"),
    TRAIT_GOOD_ORGANIZER("Good organizer", "राम्रो आयोजक"),
    TRAIT_GROUP_ACTIVITIES("Group activities", "सामूहिक गतिविधिहरू"),
    TRAIT_HEALING_ABILITIES("Healing abilities", "निको पार्ने क्षमता"),
    TRAIT_HEALING_POWERS("Healing powers", "निको पार्ने शक्ति"),
    TRAIT_HEALING_TOUCH("Healing touch", "निको पार्ने स्पर्श"),
    TRAIT_HELPFUL_NATURE("Helpful nature", "सहयोगी प्रकृति"),
    TRAIT_HYPNOTIC_CHARM("Hypnotic charm", "सम्मोहक आकर्षण"),
    TRAIT_INDEPENDENCE("Independence", "स्वतन्त्रता"),
    TRAIT_INDEPENDENT("Independent", "स्वतन्त्र"),
    TRAIT_INTEGRITY("Integrity", "निष्ठा"),
    TRAIT_INTENSE_EMOTIONS("Intense emotions", "तीव्र भावनाहरू"),
    TRAIT_INTUITION("Strong intuition", "बलियो अन्तर्ज्ञान"),
    TRAIT_INVESTIGATIVE("Investigative", "अनुसन्धानमुलक"),
    TRAIT_INVINCIBLE_SPIRIT("Invincible spirit", "अपराजित भावना"),
    TRAIT_JOURNEY_COMPLETION("Journey completion", "यात्राको समाप्ति"),
    TRAIT_KUNDALINI_ENERGY("Kundalini energy", "कुण्डलिनी ऊर्जा"),
    TRAIT_LEADERSHIP("Leadership ability", "नेतृत्व क्षमता"),
    TRAIT_LEARNING_ABILITY("Learning ability", "सिक्ने क्षमता"),
    TRAIT_MAGNETIC("Magnetic", "चुम्बकीय"),
    TRAIT_MAGNETIC_PERSONALITY("Magnetic personality", "चुम्बकीय व्यक्तित्व"),
    TRAIT_MARCHING_FORWARD("Marching forward", "अगाडि बढ्ने"),
    TRAIT_MATERIAL_ABUNDANCE("Material abundance", "भौतिक प्रचुरता"),
    TRAIT_MUSICAL_TALENT("Musical talent", "सांगीतिक प्रतिभा"),
    TRAIT_MYSTICAL_WISDOM("Mystical wisdom", "रहस्यमय ज्ञान"),
    TRAIT_NOURISHING("Nourishing", "पोषण गर्ने"),
    TRAIT_OPTIMISTIC("Optimistic", "आशावादी"),
    TRAIT_ORGANIZATIONAL_ABILITY("Organizational ability", "सांगठनिक क्षमता"),
    TRAIT_PATIENCE("Patience", "धैर्य"),
    TRAIT_PHILOSOPHICAL("Philosophical", "दार्शनिक"),
    TRAIT_PIONEERING_SPIRIT("Pioneering spirit", "अग्रगामी भावना"),
    TRAIT_PLEASURE_SEEKING("Pleasure-seeking", "आनन्द खोज्ने"),
    TRAIT_PRACTICALITY("Practical approach", "व्यावहारिक दृष्टिकोण"),
    TRAIT_PRESERVATION("Preservation", "संरक्षण"),
    TRAIT_PROSPERITY("Prosperity", "समृद्धि"),
    TRAIT_PROTECTIVE("Protective", "सुरक्षात्मक"),
    TRAIT_PROTECTIVE_OF_OTHERS("Protective of others", "अरूको सुरक्षा गर्ने"),
    TRAIT_PSYCHIC_ABILITIES("Psychic abilities", "मानसिक क्षमताहरू"),
    TRAIT_PURIFYING("Purifying", "शुद्धिकरण"),
    TRAIT_PURIFYING_NATURE("Purifying nature", "शुद्धिकरण गर्ने प्रकृति"),
    TRAIT_QUICK_THINKING("Quick-thinking", "छिटो सोच्ने"),
    TRAIT_RENEWAL("Renewal", "नवीकरण"),
    TRAIT_RESEARCH_ORIENTED("Research-oriented", "अनुसन्धानमुखी"),
    TRAIT_RESOURCEFUL("Resourceful", "स्रोतसाधन सम्पन्न"),
    TRAIT_RESPONSIBILITY("Responsibility", "जिम्मेवारी"),
    TRAIT_RETURN_TO_ROOTS("Return to roots", "जरामा फिर्ता"),
    TRAIT_ROOT_SEEKING("Root-seeking", "जरा खोज्ने"),
    TRAIT_ROYAL_BEARING("Royal bearing", "शाही व्यवहार"),
    TRAIT_SEARCHING_NATURE("Searching nature", "खोजी गर्ने प्रकृति"),
    TRAIT_SECRETIVE_NATURE("Secretive nature", "गोप्य प्रकृति"),
    TRAIT_SECRETIVE_WISDOM("Secretive wisdom", "गोप्य ज्ञान"),
    TRAIT_SELF_SUFFICIENT("Self-sufficient", "आत्मनिर्भर"),
    TRAIT_SERVICE_ORIENTED("Service-oriented", "सेवामुखी"),
    TRAIT_SHARP_INTELLECT("Sharp intellect", "तीक्ष्ण बुद्धि"),
    TRAIT_SINGLE_MINDED_FOCUS("Single-minded focus", "एकाग्र ध्यान"),
    TRAIT_SKILLED_HANDS("Skilled hands", "दक्ष हातहरू"),
    TRAIT_SPIRITUAL_DEPTH("Spiritual depth", "आध्यात्मिक गहिराई"),
    TRAIT_SPIRITUAL_GROWTH("Spiritual growth", "आध्यात्मिक वृद्धि"),
    TRAIT_SPIRITUAL_WARRIOR("Spiritual warrior", "आध्यात्मिक योद्धा"),
    TRAIT_SPIRITUAL_WISDOM("Spiritual wisdom", "आध्यात्मिक ज्ञान"),
    TRAIT_STRONG_WILLPOWER("Strong willpower", "बलियो इच्छाशक्ति"),
    TRAIT_TEACHING_ABILITY("Teaching ability", "शिक्षण क्षमता"),
    TRAIT_TRADITIONALIST("Traditionalist", "परम्परावादी"),
    TRAIT_TRANSFORMATION("Transformation", "रूपान्तरण"),
    TRAIT_TRANSFORMATIVE("Transformative", "परिवर्तनकारी"),
    TRAIT_TRAVEL_LOVING("Travel-loving", "यात्रा प्रेमी"),
    TRAIT_UNIVERSAL_VALUES("Universal values", "विश्वव्यापी मूल्यहरू"),
    TRAIT_WEALTH_GIVING("Wealth-giving", "धन दिने"),
    TRAIT_WISDOM("Wisdom", "ज्ञान"),
    TRAIT_YOUTHFUL_ENERGY("Youthful energy", "युवा ऊर्जा"),
    TRIPATAKI_ARTHA("Artha (2, 6, 10)", "अर्थ (२, ६, १०)"),
    TRIPATAKI_ARTHA_AREA("wealth, career, and practical achievements", "धन, क्यारियर र व्यावहारिक उपलब्धिहरू"),
    TRIPATAKI_ARTHA_DOMINANT("Material prosperity and career emphasis", "भौतिक समृद्धि र क्यारियर जोड"),
    TRIPATAKI_BALANCED("Balanced influences across all areas", "सबै क्षेत्रहरूमा सन्तुलित प्रभाव"),
    TRIPATAKI_BALANCED_DISTRIBUTION("Balanced distribution of planetary energies across all life sectors.", "सबै जीवन क्षेत्रहरूमा ग्रह ऊर्जाहरूको सन्तुलित वितरण।"),
    TRIPATAKI_BENEFIC_INFLUENCE("Benefic %s bring favorable influences.", "शुभ %s ले अनुकूल प्रभावहरू ल्याउँछ।"),
    TRIPATAKI_DHARMA("Dharma (1, 5, 9)", "धर्म (१, ५, ९)"),
    TRIPATAKI_DHARMA_AREA("righteousness, fortune, and higher learning", "धार्मिकता, भाग्य र उच्च शिक्षा"),
    TRIPATAKI_DHARMA_DOMINANT("Spiritual growth and righteous pursuits dominate", "आध्यात्मिक वृद्धि र धार्मिक खोजीहरू प्रभावी"),
    TRIPATAKI_KAMA("Kama (3, 7, 11)", "काम (३, ७, ११)"),
    TRIPATAKI_KAMA_AREA("relationships, desires, and social connections", "सम्बन्धहरू, इच्छाहरू र सामाजिक सम्बन्धहरू"),
    TRIPATAKI_KAMA_DOMINANT("Relationships and desires take center stage", "सम्बन्धहरू र इच्छाहरू केन्द्रमा"),
    TRIPATAKI_MALEFIC_INFLUENCE("Malefic %s bring challenges requiring effort.", "पाप %s ले प्रयास चाहिने चुनौतीहरू ल्याउँछ।"),
    TRIPATAKI_MIXED_INFLUENCE("Mixed influences suggest variable results.", "मिश्रित प्रभावहरूले परिवर्तनशील परिणामहरू सुझाव दिन्छ।"),
    TRIPATAKI_NO_PLANETS("No planets in %s sector - quieter year for these matters.", "%s क्षेत्रमा कुनै ग्रह छैन - यी मामिलाहरूको लागि शान्त वर्ष।"),
    TRIPATAKI_PLANETS_IN_TRIKONA("%d planet(s) in %s trikona emphasizes %s.", "%s त्रिकोणमा %d ग्रह(हरू)ले %s मा जोड दिन्छ।"),
    TRI_PATAKI_ARTHA("Artha Sector", "अर्थ क्षेत्र")
}
