package com.astro.storm.core.common
enum class StringKeyDoshaPart1(override val en: String, override val ne: String) : StringKeyInterface {
GUNA_SATTVA("Sattva", "सत्त्व"),
SHOOLA_SUMMARY_EN("Overall health and longevity assessment based on Rudra and Tri Murti analysis.", "समग्र स्वास्थ्य र दीर्घायु मूल्याङ्कन।"),
SHOOLA_SUMMARY_NE("Overall health and longevity assessment based on Rudra and Tri Murti analysis.", "समग्र स्वास्थ्य र दीर्घायु मूल्याङ्कन।"),
LIFE_AREA_SPIRITUAL("Spiritual Growth", "आध्यात्मिक वृद्धि"),
THEME_BALANCE("Balance", "सन्तुलन"),
THEME_DYNAMIC_ACTION("Dynamic Action", "गतिशील कार्य"),
THEME_PRACTICAL_PROGRESS("Practical Progress", "व्यावहारिक प्रगति"),
THEME_SOCIAL_CONNECTIONS("Social Connections", "सामाजिक सम्बन्धहरू"),
THEME_EMOTIONAL_INSIGHT("Emotional Insight", "भावनात्मक अन्तर्दृष्टि"),
THEME_SELF_EXPRESSION("Self-Expression", "आत्म-अभिव्यक्ति"),
THEME_TRANSFORMATION("Transformation", "रूपान्तरण"),
THEME_SPIRITUAL_LIBERATION("Spiritual Liberation", "आध्यात्मिक मुक्ति"),
ADVICE_FIRE_ELEMENT("Take bold action and express yourself confidently.", "साहसिक कदम चाल्नुहोस् र आत्मविश्वासका साथ आफूलाई अभिव्यक्त गर्नुहोस्।"),
ADVICE_EARTH_ELEMENT("Focus on practical matters and material progress.", "व्यावहारिक मामिलाहरू र भौतिक प्रगतिमा ध्यान दिनुहोस्।"),
ADVICE_AIR_ELEMENT("Engage in social activities and intellectual pursuits.", "सामाजिक क्रियाकलापहरू र बौद्धिक खोजमा संलग्न हुनुहोस्।"),
ADVICE_WATER_ELEMENT("Trust your intuition and honor your emotions.", "आफ्नो अन्तर्ज्ञानमा विश्वास गर्नुहोस् र भावनाहरूलाई सम्मान गर्नुहोस्।"),
WEEK_OPPORTUNITIES("Week of Opportunities", "अवसरहरूको हप्ता"),
WEEK_STEADY_PROGRESS("Steady Progress", "स्थिर प्रगति"),
WEEK_MINDFUL_NAVIGATION("Mindful Navigation", "सचेत नेभिगेसन"),
TIME_MORNING("Morning hours", "बिहानको समय"),
TIME_AFTERNOON("Afternoon hours", "दिउँसोको समय"),
TIME_EVENING("Evening hours", "साँझको समय"),
WEEKDAY_SU("Su", "आ"),
WEEKDAY_MO("Mo", "सो"),
WEEKDAY_TU("Tu", "मं"),
WEEKDAY_WE("We", "बु"),
WEEKDAY_TH("Th", "बि"),
WEEKDAY_FR("Fr", "शु"),
WEEKDAY_SA("Sa", "श"),
MOON_FIRST_QUARTER("First Quarter Moon", "पहिलो चौथाई चन्द्रमा"),
MOON_FIRST_QUARTER_DESC("Good for taking action", "कार्य गर्नको लागि राम्रो"),
MOON_FULL("Full Moon", "पूर्णिमा"),
MOON_FULL_DESC("Emotional peak - completion energy", "भावनात्मक शिखर - पूर्णता ऊर्जा"),
BODY_PART_HEAD("Head", "टाउको"),
BODY_PART_FACE("Face/Mouth", "अनुहार/मुख"),
BODY_PART_ARMS("Arms/Shoulders", "पाखुरा/काँध"),
BODY_PART_CHEST("Chest", "छाती"),
BODY_PART_UPPER_ABDOMEN("Upper Abdomen", "माथिल्लो पेट"),
BODY_PART_LOWER_ABDOMEN("Lower Abdomen", "तल्लो पेट"),
BODY_PART_BELOW_NAVEL("Below Navel", "नाभिमुनि"),
BODY_PART_REPRODUCTIVE("Reproductive organs", "प्रजनन अंगहरू"),
BODY_PART_THIGHS("Thighs", "जाँघ"),
BODY_PART_KNEES("Knees", "घुँडा"),
BODY_PART_CALVES("Calves/Shins", "पिँडौला"),
BODY_PART_FEET("Feet", "खुट्टा"),
PLANET_LIFE_AREA_SUN("authority, career, government favor, father's health, self-confidence", "अधिकार, करियर, सरकारी कृपा, बुबाको स्वास्थ्य, आत्मविश्वास"),
PLANET_LIFE_AREA_MOON("mental peace, mother's health, emotional stability, public relations", "मानसिक शान्ति, आमाको स्वास्थ्य, भावनात्मक स्थिरता, जनसम्पर्क"),
PLANET_LIFE_AREA_MARS("courage, siblings, property matters, physical strength, competition", "साहस, भाइबहिनी, सम्पत्ति मामिला, शारीरिक शक्ति, प्रतिस्पर्धा"),
PLANET_LIFE_AREA_MERCURY("intellect, communication, business, education, nervous system", "बुद्धि, सञ्चार, व्यापार, शिक्षा, स्नायु प्रणाली"),
PLANET_LIFE_AREA_JUPITER("wisdom, children, wealth, spirituality, teachers, dharma", "ज्ञान, सन्तान, धन, आध्यात्मिकता, गुरु, धर्म"),
PLANET_LIFE_AREA_VENUS("marriage, love, luxury, art, vehicles, pleasure", "विवाह, प्रेम, विलासिता, कला, सवारी, आनन्द"),
PLANET_LIFE_AREA_SATURN("longevity, service, discipline, karma, delays, chronic issues", "दीर्घायु, सेवा, अनुशासन, कर्म, ढिलाइ, दीर्घकालीन समस्या"),
PLANET_LIFE_AREA_RAHU("foreign connections, unconventional success, material desires", "विदेशी सम्बन्ध, अपरम्परागत सफलता, भौतिक इच्छा"),
PLANET_LIFE_AREA_KETU("spirituality, liberation, past karma, psychic abilities", "आध्यात्मिकता, मोक्ष, पूर्व कर्म, मानसिक क्षमता"),
PLANET_DAY_SUN("Sunday", "आइतबार"),
PLANET_DAY_MOON("Monday", "सोमबार"),
PLANET_DAY_MARS("Tuesday", "मंगलबार"),
PLANET_DAY_MERCURY("Wednesday", "बुधबार"),
PLANET_DAY_JUPITER("Thursday", "बिहिबार"),
PLANET_DAY_VENUS("Friday", "शुक्रबार"),
PLANET_DAY_SATURN("Saturday", "शनिबार"),
PLANET_DAY_RAHU("Saturday", "शनिबार"),
PLANET_DAY_KETU("Tuesday", "मंगलबार"),
SYNASTRY_TITLE("Chart Comparison", "कुण्डली तुलना"),
SYNASTRY_SUBTITLE("Synastry Analysis", "सिनेस्ट्री विश्लेषण"),
SYNASTRY_SELECT_CHARTS("Select Charts to Compare", "तुलना गर्न कुण्डलीहरू छान्नुहोस्"),
SYNASTRY_CHART_1("Chart 1", "कुण्डली १"),
SYNASTRY_CHART_2("Chart 2", "कुण्डली २"),
SYNASTRY_OVERVIEW("Overview", "अवलोकन"),
SYNASTRY_ASPECTS("Inter-Aspects", "अन्तर-दृष्टिहरू"),
SYNASTRY_HOUSES("House Overlays", "भाव ओभरले"),
SYNASTRY_COMPATIBILITY("Compatibility", "अनुकूलता"),
SYNASTRY_NO_ASPECTS("No significant aspects found", "कुनै महत्त्वपूर्ण दृष्टि फेला परेन"),
SYNASTRY_OVERALL_SCORE("Overall Compatibility Score", "समग्र अनुकूलता स्कोर"),
SYNASTRY_HARMONIOUS("Harmonious Aspects", "सामञ्जस्यपूर्ण दृष्टिहरू"),
SYNASTRY_CHALLENGING("Challenging Aspects", "चुनौतीपूर्ण दृष्टिहरू"),
SYNASTRY_PLANET_CONNECTIONS("Planetary Connections", "ग्रह सम्बन्धहरू"),
SYNASTRY_HOUSE_INFLUENCE("House Influences", "भाव प्रभावहरू"),
SYNASTRY_PLANET_IN_HOUSE("%s in %s's House %d", "%s को भाव %d मा %s"),
SYNASTRY_ASPECT_ORB("Orb: %.1fÂ°", "ओर्ब: %.1f°"),
SYNASTRY_APPLYING("Applying", "निकट आउँदै"),
SYNASTRY_SEPARATING("Separating", "टाढा जाँदै"),
SYNASTRY_CONJUNCTION("Conjunction", "युति"),
SYNASTRY_OPPOSITION("Opposition", "प्रतिपक्ष"),
SYNASTRY_TRINE("Trine", "त्रिकोण"),
SYNASTRY_SQUARE("Square", "चतुर्थांश"),
SYNASTRY_SEXTILE("Sextile", "षड्भाग"),
SYNASTRY_STRONG("Strong", "बलियो"),
SYNASTRY_MODERATE("Moderate", "मध्यम"),
SYNASTRY_WEAK("Weak", "कमजोर"),
SYNASTRY_KEY_ASPECTS("Key Synastry Aspects", "मुख्य सिनेस्ट्री दृष्टिहरू"),
SYNASTRY_EMOTIONAL_BOND("Emotional Bond", "भावनात्मक बन्धन"),
SYNASTRY_COMMUNICATION("Communication", "सञ्चार"),
SYNASTRY_ROMANCE("Romance & Attraction", "रोमान्स र आकर्षण"),
SYNASTRY_STABILITY("Long-term Stability", "दीर्घकालीन स्थिरता"),
SYNASTRY_GROWTH("Growth & Evolution", "वृद्धि र विकास"),
SYNASTRY_INFO_TITLE("About Synastry", "सिनेस्ट्रीको बारेमा"),
SYNASTRY_INFO_DESC("Synastry compares two birth charts to analyze relationship dynamics, compatibility, and areas of harmony or challenge between individuals.", "सिनेस्ट्रीले दुई जन्म कुण्डलीहरू तुलना गरेर व्यक्तिहरू बीचको सम्बन्ध गतिशीलता, अनुकूलता, र सामञ्जस्य वा चुनौतीका क्षेत्रहरू विश्लेषण गर्दछ।"),
SYNASTRY_SWAP("Swap Charts", "कुण्डलीहरू स्वाप गर्नुहोस्"),
SYNASTRY_CLEAR("Clear Selection", "छनौट खाली गर्नुहोस्"),
SYNASTRY_CALCULATE("Analyze Synastry", "सिनेस्ट्री विश्लेषण गर्नुहोस्"),
SYNASTRY_ANALYZING("Analyzing synastry...", "सिनेस्ट्री विश्लेषण गर्दै..."),
SYNASTRY_SUN_MOON("Sun-Moon Aspects", "सूर्य-चन्द्र दृष्टिहरू"),
SYNASTRY_VENUS_MARS("Venus-Mars Aspects", "शुक्र-मंगल दृष्टिहरू"),
SYNASTRY_ASCENDANT("Ascendant Connections", "लग्न सम्बन्धहरू"),
SYNASTRY_MUTUAL_ASPECTS("Mutual Aspects", "पारस्परिक दृष्टिहरू"),
SYNASTRY_SELECT_BOTH("Please select both charts to compare", "कृपया तुलना गर्न दुवै कुण्डली छान्नुहोस्"),
SYNASTRY_QUINCUNX("Quincunx", "क्विनकनक्स"),
SYNASTRY_SEMI_SEXTILE("Semi-Sextile", "अर्ध-षड्भाग"),
SYNASTRY_INTERPRET_HARMONIOUS("%1\$s and %2\$s work together harmoniously, creating mutual understanding and support.", "%1\$s र %2\$s सामञ्जस्यपूर्ण रूपमा सँगै काम गर्छन्, जसले आपसी समझदारी र समर्थन सिर्जना गर्दछ।"),
SYNASTRY_INTERPRET_CHALLENGING("%1\$s and %2\$s create tension that requires conscious effort to integrate.", "%1\$s र %2\$s ले तनाव सिर्जना गर्दछन् जसलाई एकीकृत गर्न सचेत प्रयासको आवश्यक पर्दछ।"),
SYNASTRY_INTERPRET_MAJOR("%1\$s and %2\$s are closely connected, amplifying each other's energies.", "%1\$s र %2\$s नजिकबाट जोडिएका छन्, एक अर्काको ऊर्जालाई बढाउँदै।"),
SYNASTRY_INTERPRET_MINOR("%1\$s and %2\$s have a subtle connection that adds nuance to the relationship.", "%1\$s र %2\$s बीच एक सूक्ष्म सम्बन्ध छ जसले सम्बन्धमा नयाँ पक्ष थप्दछ।"),
SYNASTRY_INTERPRET_ASCENDANT("%1\$s conjunct Person %2\$d's Ascendant creates a strong personal connection.", "%1\$s व्यक्ति %2\$d को लग्नमा हुनुले एक बलियो व्यक्तिगत सम्बन्ध सिर्जना गर्दछ।"),
SYNASTRY_INTERPRET_OVERLAY("Person %1\$d's %2\$s falls in the %3\$dth house, influencing %4\$s.", "व्यक्ति %1\$d को %2\$s %3\$d भावमा पर्दछ, जसले %4\$s लाई प्रभावित गर्दछ।"),
SYNASTRY_DESC_EMOTIONAL("Emotional understanding and nurturing", "भावनात्मक समझदारी र पोषण"),
SYNASTRY_DESC_ROMANCE("Physical attraction and passion", "शारीरिक आकर्षण र जुनून"),
SYNASTRY_DESC_COMMUNICATION("Mental connection and dialogue", "मानसिक सम्बन्ध र संवाद"),
SYNASTRY_DESC_STABILITY("Commitment and endurance", "प्रतिबद्धता र धैर्यता"),
SYNASTRY_DESC_GROWTH("Mutual expansion and learning", "आपसी विस्तार र सिकाइ"),
SYNASTRY_FINDING_ASPECT("Strong %1\$s between %2\$s and %3\$s", "%2\$s र %3\$s बीच बलियो %1\$s"),
SYNASTRY_FINDING_HOUSE("%1\$s activates the %2\$dth house of %3\$s", "%1\$s ले %3\$s को %2\$d भावलाई सक्रिय गर्दछ"),
SYNASTRY_CALC_FAILED("Calculation failed", "गणना असफल भयो"),
SYNASTRY_AVAILABLE_CHARTS("%d charts available", "%d कुण्डलीहरू उपलब्ध छन्"),
SYNASTRY_LIFE_AREA_GENERAL("General", "सामान्य"),
SADE_SATI_TITLE("Sade Sati Analysis", "साढेसाती विश्लेषण"),
SADE_SATI_SUBTITLE("Saturn's 7.5 Year Transit", "शनिको ७.५ वर्षे गोचर"),
SADE_SATI_ACTIVE("Sade Sati Active", "साढेसाती सक्रिय"),
SADE_SATI_NOT_ACTIVE("Sade Sati is not currently active", "साढेसाती हाल सक्रिय छैन"),
SADE_SATI_PHASE_RISING("Rising Phase", "उदय चरण"),
SADE_SATI_PHASE_PEAK("Peak Phase", "शिखर चरण"),
SADE_SATI_PHASE_SETTING("Setting Phase", "अस्त चरण"),
SADE_SATI_RISING_DESC("Saturn transiting 12th from Moon - Beginning of Sade Sati", "शनि चन्द्रबाट १२औं राशिमा गोचर - साढेसातीको शुरुआत"),
SADE_SATI_PEAK_DESC("Saturn transiting over natal Moon - Most intense phase", "शनि जन्म चन्द्रमाथि गोचर - सबैभन्दा तीव्र चरण"),
SADE_SATI_SETTING_DESC("Saturn transiting 2nd from Moon - Final phase of Sade Sati", "शनि चन्द्रबाट २औं राशिमा गोचर - साढेसातीको अन्तिम चरण"),
SADE_SATI_ACTIVE_SUMMARY("{phase} phase active with {severity} intensity", "{phase} चरण {severity} तीव्रताका साथ सक्रिय"),
    SMALL_PANOTI_FOURTH("Kantak Shani (4th from Moon)", "Kantak Shani (4th from Moon)"),
    SMALL_PANOTI_EIGHTH("Ashtama Shani (8th from Moon)", "Ashtama Shani (8th from Moon)"),
SMALL_PANOTI_ACTIVE_SUMMARY("{type} is active", "{type} सक्रिय छ"),
SEVERITY_MILD("Mild", "हल्का"),
SEVERITY_MODERATE("Moderate", "मध्यम"),
SEVERITY_SIGNIFICANT("Significant", "महत्त्वपूर्ण"),
SEVERITY_INTENSE("Intense", "तीव्र"),
SADE_SATI_DAYS_REMAINING("Days Remaining", "बाँकी दिनहरू"),
SADE_SATI_PROGRESS("Progress in Phase", "चरणमा प्रगति"),
SADE_SATI_MOON_SIGN("Natal Moon Sign", "जन्म चन्द्र राशि"),
SADE_SATI_SATURN_SIGN("Transit Saturn Sign", "गोचर शनि राशि"),
MANGLIK_TITLE("Manglik Dosha Analysis", "मांगलिक दोष विश्लेषण"),
MANGLIK_SUBTITLE("Mars Placement Analysis for Marriage", "विवाहको लागि मंगल स्थिति विश्लेषण"),
MANGLIK_NONE_LEVEL("No Manglik Dosha", "मांगलिक दोष छैन"),
MANGLIK_MILD("Mild Manglik", "हल्का मांगलिक"),
MANGLIK_PARTIAL_LEVEL("Partial Manglik", "आंशिक मांगलिक"),
MANGLIK_FULL_LEVEL("Full Manglik", "पूर्ण मांगलिक"),
MANGLIK_SEVERE("Severe Manglik", "गम्भीर मांगलिक"),
MANGLIK_SUMMARY_PRESENT("{level} present with {intensity}% intensity", "{level} {intensity}% तीव्रताका साथ उपस्थित"),
MANGLIK_SUMMARY_ABSENT("No Manglik Dosha in this chart", "यस कुण्डलीमा मांगलिक दोष छैन"),
MANGLIK_FROM_LAGNA("From Lagna", "लग्नबाट"),
MANGLIK_FROM_MOON("From Moon", "चन्द्रबाट"),
MANGLIK_FROM_VENUS("From Venus", "शुक्रबाट"),
MANGLIK_CANCELLATIONS("Cancellation Factors", "रद्द गर्ने कारकहरू"),
MANGLIK_EFFECTIVE_LEVEL("Effective Level", "प्रभावी स्तर"),
MANGLIK_CANCEL_OWN_SIGN_TITLE("Mars in Own Sign", "मंगल स्वराशिमा"),
MANGLIK_CANCEL_OWN_SIGN_DESC("Mars in Aries or Scorpio reduces Manglik effects", "मंगल मेष वा वृश्चिकमा मांगलिक प्रभाव कम गर्छ"),
MANGLIK_CANCEL_EXALTED_TITLE("Mars Exalted", "मंगल उच्च"),
MANGLIK_CANCEL_EXALTED_DESC("Mars in Capricorn cancels Manglik Dosha completely", "मंगल मकरमा मांगलिक दोष पूर्ण रूपमा रद्द गर्छ"),
MANGLIK_CANCEL_JUPITER_CONJUNCT_TITLE("Jupiter Conjunction", "गुरु युति"),
MANGLIK_CANCEL_JUPITER_CONJUNCT_DESC("Jupiter conjunct Mars cancels Manglik effects", "गुरुले मंगलसँग युतिले मांगलिक प्रभाव रद्द गर्छ"),
MANGLIK_CANCEL_VENUS_CONJUNCT_TITLE("Venus Conjunction", "शुक्र युति"),
MANGLIK_CANCEL_VENUS_CONJUNCT_DESC("Venus conjunct Mars significantly reduces effects", "शुक्रले मंगलसँग युतिले प्रभाव उल्लेखनीय रूपमा कम गर्छ"),
MANGLIK_CANCEL_JUPITER_ASPECT_TITLE("Jupiter's Aspect", "गुरुको दृष्टि"),
MANGLIK_CANCEL_JUPITER_ASPECT_DESC("Jupiter aspecting Mars reduces Manglik effects", "गुरुको मंगलमा दृष्टिले मांगलिक प्रभाव कम गर्छ"),
MANGLIK_CANCEL_SECOND_MERCURY_TITLE("Mars in 2nd in Mercury Sign", "बुध राशिमा २औं मंगल"),
MANGLIK_CANCEL_SECOND_MERCURY_DESC("Mars in 2nd house in Gemini/Virgo cancels dosha", "मिथुन/कन्यामा २औं भावमा मंगलले दोष रद्द गर्छ"),
MANGLIK_CANCEL_FOURTH_OWN_TITLE("Mars in 4th in Own Sign", "स्वराशिमा ४औं मंगल"),
MANGLIK_CANCEL_FOURTH_OWN_DESC("Mars in 4th house in Aries/Scorpio cancels dosha", "मेष/वृश्चिकमा ४औं भावमा मंगलले दोष रद्द गर्छ"),
MANGLIK_CANCEL_SEVENTH_SPECIAL_TITLE("Mars in 7th Special", "७औं मंगल विशेष"),
MANGLIK_CANCEL_SEVENTH_SPECIAL_DESC("Mars in 7th in Cancer/Capricorn reduces effects", "कर्कट/मकरमा ७औं भावमा मंगलले प्रभाव कम गर्छ"),
MANGLIK_CANCEL_EIGHTH_JUPITER_TITLE("Mars in 8th Jupiter Sign", "गुरु राशिमा ८औं मंगल"),
MANGLIK_CANCEL_EIGHTH_JUPITER_DESC("Mars in 8th in Sagittarius/Pisces reduces effects", "धनु/मीनमा ८औं भावमा मंगलले प्रभाव कम गर्छ"),
MANGLIK_CANCEL_TWELFTH_VENUS_TITLE("Mars in 12th Venus Sign", "शुक्र राशिमा १२औं मंगल"),
MANGLIK_CANCEL_TWELFTH_VENUS_DESC("Mars in 12th in Taurus/Libra cancels dosha", "वृषभ/तुलामा १२औं भावमा मंगलले दोष रद्द गर्छ"),
MANGLIK_CANCEL_BENEFIC_ASC_TITLE("Benefic Ascendant", "शुभ लग्न"),
MANGLIK_CANCEL_BENEFIC_ASC_DESC("For Aries/Cancer/Leo/Scorpio ascendants, Mars is benefic", "मेष/कर्कट/सिंह/वृश्चिक लग्नको लागि मंगल शुभ हो"),
PITRA_DOSHA_TITLE("Pitra Dosha Analysis", "पितृ दोष विश्लेषण"),
PITRA_DOSHA_SUBTITLE("Ancestral Karma Assessment", "पुर्खाको कर्म मूल्यांकन"),
PITRA_DOSHA_NONE("No Pitra Dosha", "पितृ दोष छैन"),
PITRA_DOSHA_MINOR("Minor Pitra Dosha", "हल्का पितृ दोष"),
PITRA_DOSHA_MODERATE("Moderate Pitra Dosha", "मध्यम पितृ दोष"),
PITRA_DOSHA_SIGNIFICANT("Significant Pitra Dosha", "महत्त्वपूर्ण पितृ दोष"),
PITRA_DOSHA_SEVERE("Severe Pitra Dosha", "गम्भीर पितृ दोष"),
PITRA_DOSHA_PRESENT_SUMMARY("{level} detected in chart", "कुण्डलीमा {level} पत्ता लाग्यो"),
PITRA_DOSHA_ABSENT_SUMMARY("No significant Pitra Dosha indicators found", "कुनै महत्त्वपूर्ण पितृ दोष संकेतकहरू फेला परेनन्"),
PITRA_TYPE_SURYA_RAHU("Sun-Rahu Conjunction", "सूर्य-राहु युति"),
PITRA_TYPE_SURYA_KETU("Sun-Ketu Conjunction", "सूर्य-केतु युति"),
PITRA_TYPE_SURYA_SHANI("Sun-Saturn Affliction", "सूर्य-शनि पीडा"),
PITRA_TYPE_NINTH_HOUSE("9th House Affliction", "९औं भाव पीडा"),
PITRA_TYPE_NINTH_LORD("9th Lord Affliction", "९औं भावेश पीडा"),
PITRA_TYPE_RAHU_NINTH("Rahu in 9th House", "९औं भावमा राहु"),
PITRA_TYPE_COMBINED("Combined Affliction", "संयुक्त पीडा"),
PITRA_DESC_SURYA_RAHU("Primary indicator - eclipsed Sun indicates blocked ancestral blessings", "प्राथमिक संकेतक - ग्रहण लागेको सूर्यले अवरुद्ध पुर्खाको आशीर्वाद संकेत गर्छ"),
PITRA_DESC_SURYA_KETU("Past-life karmic debts from paternal lineage", "पितृ वंशबाट पूर्व जन्मको कर्म ऋण"),
PITRA_DESC_SURYA_SHANI("Father-related karmic lessons and delays", "पिता-सम्बन्धित कर्म पाठ र ढिलाइ"),
PITRA_DESC_NINTH_HOUSE("House of ancestors afflicted by malefics", "पुर्खाको भाव अशुभ ग्रहबाट पीडित"),
PITRA_DESC_NINTH_LORD("Lord of father and fortune is weakened", "पिता र भाग्यको स्वामी कमजोर छ"),
PITRA_DESC_RAHU_NINTH("Strong indication of ancestral debts", "पुर्खाको ऋणको बलियो संकेत"),
PITRA_DESC_COMBINED("Multiple factors indicate significant ancestral karma", "बहु कारकहरूले महत्त्वपूर्ण पुर्खाको कर्म संकेत गर्छन्"),
DOSHA_ANALYSIS("Dosha Analysis", "दोष विश्लेषण"),
DOSHA_INDICATORS("Indicators Found", "संकेतकहरू फेला परे"),
DOSHA_AFFECTED_AREAS("Affected Life Areas", "प्रभावित जीवन क्षेत्रहरू"),
DOSHA_REMEDIES_SECTION("Recommended Remedies", "सिफारिस गरिएका उपायहरू"),
DOSHA_INTERPRETATION("Interpretation", "व्याख्या"),
DOSHA_SEVERITY_SCORE("Severity Score", "गम्भीरता अंक"),
DOSHA_AUSPICIOUS_TIMES("Auspicious Times for Remedies", "उपायहरूको लागि शुभ समय"),
INTERP_ANALYSIS_HEADER("ANALYSIS", "विश्लेषण"),
INTERP_INDICATORS_FOUND("INDICATORS FOUND:", "पाइएका संकेतकहरू:"),
INTERP_INTERPRETATION("INTERPRETATION:", "व्याख्या:"),
INTERP_SEVERITY("SEVERITY:", "गम्भीरता:"),
INTERP_LEVEL("Level:", "स्तर:"),
MANGLIK_INTERP_NO_DOSHA("NO MANGLIK DOSHA", "मांगलिक दोष छैन"),
MANGLIK_INTERP_MARS_NOT_PLACED("Mars is not placed in houses 1, 2, 4, 7, 8, or 12 from your Lagna, Moon, or Venus.",
        "मंगल तपाईंको लग्न, चन्द्र वा शुक्रबाट १, २, ४, ७, ८ वा १२ भावमा छैन।"),
MANGLIK_INTERP_HEADER("MANGLIK DOSHA ANALYSIS", "मांगलिक दोष विश्लेषण"),
MANGLIK_INTERP_FROM_REFERENCE("ANALYSIS FROM THREE REFERENCE POINTS:", "तीन सन्दर्भ बिन्दुबाट विश्लेषण:"),
MANGLIK_INTERP_FROM_LAGNA("From Lagna", "लग्नबाट"),
MANGLIK_INTERP_FROM_MOON("From Moon", "चन्द्रबाट"),
MANGLIK_INTERP_FROM_VENUS("From Venus", "शुक्रबाट"),
MANGLIK_INTERP_MARS_IN_HOUSE("Mars in house", "मंगल भावमा"),
MANGLIK_INTERP_MANGLIK_YES("YES", "छ"),
MANGLIK_INTERP_MANGLIK_NO("NO", "छैन"),
MANGLIK_INTERP_CANCELLATION_PRESENT("CANCELLATION FACTORS PRESENT:", "निरसन कारकहरू उपस्थित:"),
MANGLIK_INTERP_EFFECTIVE_LEVEL("Effective Level After Cancellations:", "निरसन पछिको प्रभावकारी स्तर:"),
MANGLIK_INTERP_HOUSE_SUFFIX_ST("st", "औं"),
MANGLIK_INTERP_HOUSE_SUFFIX_ND("nd", "औं"),
MANGLIK_INTERP_HOUSE_SUFFIX_RD("rd", "औं"),
MANGLIK_INTERP_HOUSE_SUFFIX_TH("th", "औं"),
MANGLIK_MARRIAGE_HEADER("MARRIAGE CONSIDERATIONS", "विवाह विचार"),
MANGLIK_MARRIAGE_NONE_NO_RESTRICTION("No restrictions based on Manglik Dosha",
        "मांगलिक दोषको आधारमा कुनै प्रतिबन्ध छैन"),
MANGLIK_MARRIAGE_NONE_COMPATIBLE("Compatible with both Manglik and non-Manglik partners",
        "मांगलिक र गैर-मांगलिक दुवै साझेदारसँग मिल्दो"),
MANGLIK_MARRIAGE_MILD_EFFECTS("Mild Manglik effects - marriage with non-Manglik is possible",
        "हल्का मांगलिक प्रभाव - गैर-मांगलिकसँग विवाह सम्भव छ"),
MANGLIK_MARRIAGE_MILD_REMEDIES("Simple remedies recommended before marriage",
        "विवाह अघि सरल उपायहरू सिफारिस गरिन्छ"),
MANGLIK_MARRIAGE_MILD_MATCHING("Matching with another Manglik is beneficial but not essential",
        "अर्को मांगलिकसँग मिलान लाभदायक तर अनिवार्य होइन"),
MANGLIK_MARRIAGE_PARTIAL_REMEDIES("Partial Manglik - remedies strongly recommended",
        "आंशिक मांगलिक - उपायहरू जोडदार सिफारिस"),
MANGLIK_MARRIAGE_PARTIAL_PREFERABLE("Marriage with Manglik partner is preferable",
        "मांगलिक साझेदारसँग विवाह उपयुक्त"),
MANGLIK_MARRIAGE_PARTIAL_KUMBH("If marrying non-Manglik, perform Kumbh Vivah",
        "गैर-मांगलिकसँग विवाह गर्दा कुम्भ विवाह गर्नुहोस्"),
MANGLIK_MARRIAGE_FULL_PRESENT("Full Manglik Dosha present",
        "पूर्ण मांगलिक दोष उपस्थित"),
MANGLIK_MARRIAGE_FULL_RECOMMENDED("Marriage with Manglik partner highly recommended",
        "मांगलिक साझेदारसँग विवाह अत्यधिक सिफारिस"),
MANGLIK_MARRIAGE_FULL_KUMBH_ESSENTIAL("Kumbh Vivah or equivalent ritual essential before marriage",
        "विवाह अघि कुम्भ विवाह वा समान अनुष्ठान आवश्यक"),
MANGLIK_MARRIAGE_FULL_PROPITIATION("Regular Mars propitiation recommended",
        "नियमित मंगल शान्ति सिफारिस गरिन्छ"),
MANGLIK_MARRIAGE_SEVERE_CONSIDERATION("Severe Manglik Dosha - careful consideration required",
        "गम्भीर मांगलिक दोष - सावधानीपूर्ण विचार आवश्यक"),
MANGLIK_MARRIAGE_SEVERE_ONLY_MANGLIK("Only marry Manglik partner with similar intensity",
        "समान तीव्रता भएको मांगलिक साझेदारसँग मात्र विवाह गर्नुहोस्"),
MANGLIK_MARRIAGE_SEVERE_MULTIPLE_REMEDIES("Multiple remedies required before and after marriage",
        "विवाह अघि र पछि धेरै उपायहरू आवश्यक"),
    MANGLIK_MARRIAGE_SEVERE_DELAY("Consider delaying marriage until after age 28 (Mars maturity)", "Consider delaying marriage until after age 28 (Mars maturity)"),
MANGLIK_MARRIAGE_FULL_CANCELLATION("NOTE: Full cancellation present - Manglik Dosha effectively nullified",
        "नोट: पूर्ण निरसन उपस्थित - मांगलिक दोष प्रभावकारी रूपमा शून्य"),
MANGLIK_COMPAT_EXCELLENT("Excellent Manglik compatibility - no concerns",
        "उत्कृष्ट मांगलिक मिलान - कुनै चिन्ता छैन"),
MANGLIK_COMPAT_GOOD("Good compatibility - minor remedies may help",
        "राम्रो मिलान - साना उपायहरू सहायक हुन सक्छ"),
MANGLIK_COMPAT_AVERAGE("Average compatibility - remedies recommended",
        "औसत मिलान - उपायहरू सिफारिस गरिन्छ"),
MANGLIK_COMPAT_BELOW_AVERAGE("Below average - significant remedies required",
        "औसतभन्दा कम - महत्वपूर्ण उपायहरू आवश्यक"),
MANGLIK_COMPAT_POOR("Challenging combination - expert consultation advised",
        "कठिन संयोजन - विशेषज्ञ परामर्श सल्लाह दिइन्छ"),
MANGLIK_REF_LAGNA("Lagna", "लग्न"),
MANGLIK_REF_MOON("Moon", "चन्द्र"),
MANGLIK_REF_VENUS("Venus", "शुक्र"),
YES("Yes", "छ"),
NO("No", "छैन"),
MANGLIK_INTERP_NO_DOSHA_TITLE("NO MANGLIK DOSHA", "मांगलिक दोष छैन"),
MANGLIK_INTERP_NO_DOSHA_DESC("Mars is not placed in houses 1, 2, 4, 7, 8, or 12 from your Lagna, Moon, or Venus. There is no Manglik Dosha in your chart.",
        "मंगल तपाईंको लग्न, चन्द्र वा शुक्रबाट १, २, ४, ७, ८ वा १२औं भावमा छैन। तपाईंको कुण्डलीमा मांगलिक दोष छैन।"),
MANGLIK_INTERP_TITLE("MANGLIK DOSHA ANALYSIS", "मांगलिक दोष विश्लेषण"),
MANGLIK_INTERP_MARS_POSITION("Mars Position: {sign} in House {house}", "मंगल स्थिति: {sign} भाव {house} मा"),
MANGLIK_INTERP_MARS_RETROGRADE("Note: Mars is retrograde which can intensify or modify its effects.", "नोट: मंगल वक्री छ जसले यसको प्रभावहरू तीव्र वा परिमार्जन गर्न सक्छ।"),
MANGLIK_INTERP_THREE_REF("ANALYSIS FROM THREE REFERENCE POINTS:", "तीन सन्दर्भ बिन्दुबाट विश्लेषण:"),
MANGLIK_INTERP_MARS_HOUSE("Mars in House {house}", "मंगल भाव {house} मा"),
MANGLIK_INTERP_IS_MANGLIK("Manglik", "मांगलिक"),
MANGLIK_INTERP_INITIAL_LEVEL("Initial Level: {level}", "प्रारम्भिक स्तर: {level}"),
MANGLIK_MARRIAGE_TITLE("MARRIAGE CONSIDERATIONS", "विवाह सम्बन्धी विचारहरू"),
MANGLIK_MARRIAGE_NONE_1("No restrictions based on Manglik Dosha.", "मांगलिक दोषमा आधारित कुनै प्रतिबन्ध छैन।"),
MANGLIK_MARRIAGE_NONE_2("Compatible with both Manglik and non-Manglik partners.", "मांगलिक र गैर-मांगलिक दुवै साझेदारसँग मिल्दो।"),
MANGLIK_MARRIAGE_MILD_1("Mild Manglik effects - marriage with non-Manglik is possible.", "हल्का मांगलिक प्रभाव - गैर-मांगलिकसँग विवाह सम्भव।"),
MANGLIK_MARRIAGE_MILD_2("Simple remedies recommended before marriage.", "विवाह अघि सरल उपायहरू सिफारिस।"),
MANGLIK_MARRIAGE_MILD_3("Matching with another Manglik is beneficial but not essential.", "अर्को मांगलिकसँग मिलान लाभदायक तर अनिवार्य होइन।"),
MANGLIK_MARRIAGE_PARTIAL_1("Partial Manglik - remedies strongly recommended.", "आंशिक मांगलिक - उपायहरू जोडदार सिफारिस।"),
MANGLIK_MARRIAGE_PARTIAL_2("Marriage with Manglik partner is preferable.", "मांगलिक साझेदारसँग विवाह उपयुक्त।"),
MANGLIK_MARRIAGE_PARTIAL_3("If marrying non-Manglik, perform Kumbh Vivah.", "गैर-मांगलिकसँग विवाह गर्दा कुम्भ विवाह गर्नुहोस्।"),
MANGLIK_MARRIAGE_FULL_1("Full Manglik Dosha present.", "पूर्ण मांगलिक दोष उपस्थित।"),
MANGLIK_MARRIAGE_FULL_2("Marriage with Manglik partner highly recommended.", "मांगलिक साझेदारसँग विवाह अत्यधिक सिफारिस।"),
MANGLIK_MARRIAGE_FULL_3("Kumbh Vivah or equivalent ritual essential before marriage.", "विवाह अघि कुम्भ विवाह वा समतुल्य अनुष्ठान अनिवार्य।"),
MANGLIK_MARRIAGE_FULL_4("Regular Mars propitiation recommended.", "नियमित मंगल शान्ति सिफारिस।"),
MANGLIK_MARRIAGE_SEVERE_1("Severe Manglik Dosha - careful consideration required.", "गम्भीर मांगलिक दोष - सावधानीपूर्ण विचार आवश्यक।"),
MANGLIK_MARRIAGE_SEVERE_2("Only marry Manglik partner with similar intensity.", "समान तीव्रता भएको मांगलिक साझेदारसँग मात्र विवाह।"),
MANGLIK_MARRIAGE_SEVERE_3("Multiple remedies required before and after marriage.", "विवाह अघि र पछि बहु उपायहरू आवश्यक।"),
    MANGLIK_MARRIAGE_SEVERE_4("Consider delaying marriage until after age 28 (Mars maturity)", "Consider delaying marriage until after age 28 (Mars maturity)"),
MANGLIK_MARRIAGE_FULL_CANCEL_NOTE("NOTE: Full cancellation present - Manglik Dosha effectively nullified.", "नोट: पूर्ण निरसन उपस्थित - मांगलिक दोष प्रभावकारी रूपमा शून्य।"),
PITRA_INTERP_NO_DOSHA("NO SIGNIFICANT PITRA DOSHA", "कुनै महत्वपूर्ण पित्र दोष छैन"),
PITRA_INTERP_NO_DOSHA_DESC("Your chart does not show significant indicators of Pitra Dosha.",
        "तपाईंको कुण्डलीमा पित्र दोषको महत्वपूर्ण संकेतकहरू देखिँदैनन्।"),
PITRA_INTERP_SUPPORTIVE("The ancestral lineage appears supportive of your life journey.",
        "पैतृक वंश तपाईंको जीवन यात्रामा सहायक देखिन्छ।"),
    PITRA_INTERP_BENEFICIAL("However, performing regular ancestral offerings (Shraddha)", "However, performing regular ancestral offerings (Shraddha)"),
PITRA_INTERP_HEADER("PITRA DOSHA ANALYSIS", "पित्र दोष विश्लेषण"),
    PITRA_INTERP_NINTH_HOUSE("9TH HOUSE ANALYSIS (House of Ancestors)", "9TH HOUSE ANALYSIS (House of Ancestors)"),
PITRA_INTERP_NINTH_LORD("9th Lord:", "९औं स्वामी:"),
PITRA_INTERP_NINTH_LORD_POSITION("9th Lord Position:", "९औं स्वामीको स्थिति:"),
PITRA_INTERP_LORD_AFFLICTED("9th Lord Afflicted:", "९औं स्वामी पीडित:"),
PITRA_INTERP_HOUSE_AFFLICTED("9th House Afflicted:", "९औं भाव पीडित:"),
PITRA_INTERP_BENEFIC_INFLUENCE("Benefic Influence:", "शुभ प्रभाव:"),
PITRA_INTERP_YES_MITIGATING("Yes - Mitigating", "छ - न्यूनीकरण गर्दै"),
PITRA_DESC_SUN_RAHU_HOUSE("Sun conjunct Rahu in House %d - Primary Pitra Dosha indicator",
        "भाव %d मा सूर्य-राहु युति - प्रमुख पित्र दोष संकेतक"),
PITRA_DESC_SUN_KETU_HOUSE("Sun conjunct Ketu in House %d - Indicates past-life ancestral karma",
        "भाव %d मा सूर्य-केतु युति - पूर्वजन्मको पैतृक कर्म संकेत"),
PITRA_DESC_SUN_SATURN_CONJUNCT("Sun conjunct Saturn in House %d - Father-related karmic issues",
        "भाव %d मा सूर्य-शनि युति - पितृ-सम्बन्धी कार्मिक मुद्दाहरू"),
PITRA_DESC_SATURN_ASPECT("Saturn aspects Sun from House %d - Delayed results due to ancestral karma",
        "शनिले भाव %d बाट सूर्यलाई हेर्छ - पैतृक कर्मले गर्दा ढिलो परिणाम"),
PITRA_DESC_MALEFICS_NINTH("Malefics in 9th house - Ancestral blessings blocked",
        "९औं भावमा पाप ग्रह - पैतृक आशीर्वाद अवरुद्ध"),
PITRA_DESC_NINTH_LORD_AFFLICTED("9th lord %s is afflicted - Ancestral lineage karma",
        "९औं स्वामी %s पीडित छ - पैतृक वंश कर्म"),
PITRA_LEVEL_MINOR_DESC("Minor ancestral karma is indicated. This may manifest as occasional obstacles or delays that seem unexplained. Regular ancestral prayers and offerings during Pitru Paksha should be sufficient.",
        "साना पैतृक कर्म संकेत गरिएको छ। यसले अव्याख्येय देखिने कहिलेकाहीं अवरोधहरू वा ढिलाइको रूपमा प्रकट हुन सक्छ। पितृ पक्षमा नियमित पैतृक प्रार्थना र अर्पण पर्याप्त हुनुपर्छ।"),
PITRA_LEVEL_MODERATE_DESC("Moderate Pitra Dosha suggests unresolved ancestral obligations. You may experience recurring challenges in life that feel karmic. Regular Tarpan and Shraddha ceremonies are recommended.",
        "मध्यम पित्र दोषले अपूर्ण पैतृक दायित्वहरू संकेत गर्दछ। तपाईंले कार्मिक जस्तो लाग्ने जीवनमा आवर्ती चुनौतीहरू अनुभव गर्न सक्नुहुन्छ। नियमित तर्पण र श्राद्ध समारोहहरू सिफारिस गरिन्छ।"),
PITRA_LEVEL_SIGNIFICANT_DESC("Significant ancestral karma is present. This may manifest as: delayed marriage or relationship issues, difficulties with children or progeny, career obstacles despite qualifications, and family disharmony. Comprehensive remedies including Narayan Bali may be beneficial.",
        "महत्वपूर्ण पैतृक कर्म उपस्थित छ। यसले विवाहमा ढिलाइ वा सम्बन्ध समस्या, सन्तान वा सन्ततिमा कठिनाइहरू, योग्यता भएता पनि क्यारियरमा अवरोधहरू, र पारिवारिक विसंगतिको रूपमा प्रकट हुन सक्छ। नारायण बलि सहित व्यापक उपायहरू लाभदायक हुन सक्छ।"),
PITRA_LEVEL_SEVERE_DESC("Severe Pitra Dosha indicates deep ancestral karma that requires serious attention and remedial measures. This level of dosha often indicates: ancestors who departed with unfulfilled wishes, interrupted or improper last rites in the lineage, and significant karmic debts carried forward. Consult a qualified priest for Narayan Bali/Nagbali and Pind Daan at sacred places like Gaya.",
        "गम्भीर पित्र दोषले गहिरो पैतृक कर्म संकेत गर्दछ जसलाई गम्भीर ध्यान र उपचारात्मक उपायहरू आवश्यक छ। यस स्तरको दोषले प्रायः संकेत गर्दछ: अपूर्ण इच्छाहरूसँग गएका पूर्वजहरू, वंशमा अवरुद्ध वा अनुचित अन्तिम संस्कार, र अगाडि लगिएको महत्वपूर्ण कार्मिक ऋणहरू। गयामा नारायण बलि/नागबलि र पिण्डदान को लागि योग्य पुजारीसँग परामर्श गर्नुहोस्।"),
PITRA_AREA_FATHER("Father and paternal lineage", "पिता र पैतृक वंश"),
PITRA_AREA_SPIRITUAL("Spiritual progress and dharma", "आध्यात्मिक प्रगति र धर्म"),
PITRA_AREA_SELF("Self, health, and overall life direction", "आत्म, स्वास्थ्य, र समग्र जीवन दिशा"),
PITRA_AREA_FAMILY_WEALTH("Family wealth and accumulated assets", "पारिवारिक सम्पत्ति र संचित सम्पत्ति"),
PITRA_AREA_SIBLINGS("Siblings and communication", "भाइबहिनी र संचार"),
PITRA_AREA_MOTHER("Mother, property, and domestic peace", "आमा, सम्पत्ति, र घरेलु शान्ति"),
PITRA_AREA_CHILDREN("Children, education, and creativity", "बच्चाहरू, शिक्षा, र सृजनात्मकता"),
PITRA_AREA_HEALTH("Health, debts, and service", "स्वास्थ्य, ऋण, र सेवा"),
PITRA_AREA_MARRIAGE("Marriage and partnerships", "विवाह र साझेदारी"),
PITRA_AREA_LONGEVITY("Longevity and inherited wealth", "दीर्घायु र विरासत सम्पत्ति"),
PITRA_AREA_FORTUNE("Fortune, higher learning, and spirituality", "भाग्य, उच्च शिक्षा, र आध्यात्मिकता"),
PITRA_AREA_CAREER("Career and public reputation", "क्यारियर र सार्वजनिक प्रतिष्ठा"),
PITRA_AREA_GAINS("Gains and social network", "लाभ र सामाजिक नेटवर्क"),
PITRA_AREA_LIBERATION("Spiritual liberation and foreign lands", "आध्यात्मिक मुक्ति र विदेश"),
    PITRA_TIMING_AMAVASYA("Amavasya (New Moon)", "Amavasya (New Moon)"),
PITRA_TIMING_DEATH_ANNIVERSARY("Father's death anniversary or Pitru Paksha", "पिताको पुण्यतिथि वा पितृ पक्ष"),
PITRA_TIMING_DAILY_PITRU("Daily, especially during Pitru Paksha", "दैनिक, विशेष गरी पितृ पक्षमा"),
PITRA_TIMING_NARAYAN_BALI("Once in lifetime at Trimbakeshwar or Gaya", "जीवनकालमा एकपटक त्र्यम्बकेश्वर वा गयामा"),
PITRA_TIMING_PIND_DAAN("Pitru Paksha at Gaya", "गयामा पितृ पक्ष"),
PITRA_TIMING_BRAHMA_MUHURTA("Daily during Brahma Muhurta", "ब्रह्म मुहूर्तमा दैनिक"),
    PITRA_PERIOD_PITRU_PAKSHA("Pitru Paksha (15-day period in Bhadrapada month)", "Pitru Paksha (15-day period in Bhadrapada month)"),
    PITRA_PERIOD_AMAVASYA("Amavasya (New Moon days)", "Amavasya (New Moon days)"),
PITRA_PERIOD_ECLIPSE("Solar/Lunar eclipses", "सूर्य/चन्द्र ग्रहण"),
PITRA_PERIOD_DEATH_ANNIV("Father's death anniversary", "पिताको पुण्यतिथि"),
PITRA_PERIOD_MAHALAYA("Mahalaya Amavasya", "महालय अमावस्या"),
PITRA_PERIOD_AKSHAYA("Akshaya Tritiya", "अक्षय तृतीया"),
PITRA_PERIOD_GAYA("Gaya Shraddha periods", "गया श्राद्ध अवधिहरू"),
SADE_SATI_ACTIVE_HEADER("SADE SATI ACTIVE - %s PHASE", "साढ़े साती सक्रिय - %s चरण"),
SADE_SATI_TRANSIT_DESC("Saturn is currently transiting %s, which is the %s from your natal Moon in %s.",
        "शनि हाल %s मा गोचर गर्दैछ, जुन तपाईंको जन्म चन्द्र %s बाट %s हो।"),
SADE_SATI_12TH_HOUSE("12th house", "१२औं भाव"),
SADE_SATI_SAME_SIGN("same sign", "उही राशि"),
SADE_SATI_2ND_HOUSE("2nd house", "२औं भाव"),
SADE_SATI_RISING_HEADER("RISING PHASE CHARACTERISTICS:", "उदय चरण विशेषताहरू:"),
SADE_SATI_RISING_BEGIN("Beginning of Sade Sati period", "साढ़े साती अवधिको सुरुवात"),
    SADE_SATI_RISING_EXPENSES("Focus on expenses and losses (12th house)", "Focus on expenses and losses (12th house)"),
SADE_SATI_RISING_SLEEP("Sleep disturbances possible", "निद्रामा गडबडी सम्भव"),
SADE_SATI_RISING_ENEMIES("Hidden enemies may become active", "लुकेका शत्रुहरू सक्रिय हुन सक्छन्"),
SADE_SATI_RISING_SPIRITUAL("Spiritual growth opportunities", "आध्यात्मिक वृद्धिका अवसरहरू"),
SADE_SATI_PEAK_HEADER("PEAK PHASE CHARACTERISTICS:", "शिखर चरण विशेषताहरू:"),
SADE_SATI_PEAK_INTENSE("Most intense phase of Sade Sati", "साढ़े साती को सबैभन्दा तीव्र चरण"),
SADE_SATI_PEAK_MIND("Direct impact on mind and emotions", "मन र भावनाहरूमा प्रत्यक्ष प्रभाव"),
SADE_SATI_PEAK_HEALTH("Health may need attention", "स्वास्थ्यमा ध्यान आवश्यक हुन सक्छ"),
SADE_SATI_PEAK_SELF("Self-image transformation", "आत्म-छवि रूपान्तरण"),
SADE_SATI_PEAK_RESTRUCTURE("Major life restructuring possible", "प्रमुख जीवन पुनर्संरचना सम्भव"),
SADE_SATI_SETTING_HEADER("SETTING PHASE CHARACTERISTICS:", "अस्त चरण विशेषताहरू:"),
SADE_SATI_SETTING_FINAL("Final phase of Sade Sati", "साढ़े साती को अन्तिम चरण"),
    SADE_SATI_SETTING_FINANCES("Focus on finances and family (2nd house)", "Focus on finances and family (2nd house)"),
SADE_SATI_SETTING_SPEECH("Speech and communication impacted", "वाणी र संचार प्रभावित"),
SADE_SATI_SETTING_WEALTH("Accumulated wealth may fluctuate", "संचित सम्पत्तिमा उतारचढाव"),
SADE_SATI_SETTING_LESSONS("Integration of lessons learned", "सिकेका पाठहरूको एकीकरण"),
SADE_SATI_NOT_ACTIVE_HEADER("SADE SATI NOT ACTIVE", "साढ़े साती सक्रिय छैन"),
SADE_SATI_NOT_ACTIVE_DESC("Saturn is currently transiting %s, which does not form Sade Sati or Small Panoti with your natal Moon in %s.",
        "शनि हाल %s मा गोचर गर्दैछ, जसले तपाईंको जन्म चन्द्र %s सँग साढ़े साती वा सानो पनोती बनाउँदैन।"),
SADE_SATI_FAVORABLE_PERIOD("This is generally a favorable period regarding Saturn's influence on emotional and mental well-being.",
        "भावनात्मक र मानसिक कल्याणमा शनिको प्रभाव सम्बन्धमा यो सामान्यतया अनुकूल अवधि हो।"),
    SADE_SATI_SMALL_PANOTI_HEADER("SMALL PANOTI (DHAIYA)", "SMALL PANOTI (DHAIYA)"),
SADE_SATI_FOURTH_TRANSIT("Saturn is transiting the 4th house from your Moon.", "शनि तपाईंको चन्द्रबाट ४औं भावमा गोचर गर्दैछ।"),
SADE_SATI_FOURTH_DOMESTIC("Domestic peace may be disturbed", "घरेलु शान्ति अशान्त हुन सक्छ"),
SADE_SATI_FOURTH_MOTHER("Mother's health may need attention", "आमाको स्वास्थ्यमा ध्यान आवश्यक"),
SADE_SATI_FOURTH_PROPERTY("Property matters require caution", "सम्पत्ति मामिलाहरूमा सावधानी आवश्यक"),
SADE_SATI_FOURTH_MENTAL("Mental peace may fluctuate", "मानसिक शान्तिमा उतारचढाव"),
SADE_SATI_ASHTAMA_HEADER("ASHTAMA SHANI - Saturn in 8th from Moon", "अष्टम शनि - चन्द्रबाट ८औं मा शनि"),
SADE_SATI_ASHTAMA_CHALLENGING("This is considered one of the most challenging Saturn transits.",
        "यो शनिको सबैभन्दा चुनौतीपूर्ण गोचर मध्ये एक मानिन्छ।"),
SADE_SATI_ASHTAMA_CHANGES("Sudden changes and transformations", "अचानक परिवर्तन र रूपान्तरणहरू"),
SADE_SATI_ASHTAMA_HEALTH("Health requires vigilance", "स्वास्थ्यमा सतर्कता आवश्यक"),
SADE_SATI_ASHTAMA_OBSTACLES("Obstacles in ventures", "उद्यमहरूमा अवरोधहरू"),
SADE_SATI_ASHTAMA_PSYCHOLOGICAL("Deep psychological transformation", "गहिरो मनोवैज्ञानिक रूपान्तरण"),
SADE_SATI_FACTOR_EXALTED("Saturn is exalted in transit - effects significantly reduced", "शनि गोचरमा उच्च - प्रभावहरू उल्लेखनीय कम"),
SADE_SATI_FACTOR_OWN_SIGN("Saturn is in own sign - effects well-managed", "शनि स्वराशिमा - प्रभावहरू राम्रोसँग व्यवस्थित"),
SADE_SATI_FACTOR_YOGAKARAKA("Saturn is Yogakaraka for your ascendant - may bring positive results", "शनि तपाईंको लग्नको लागि योगकारक - सकारात्मक परिणाम ल्याउन सक्छ"),
SADE_SATI_FACTOR_NATAL_STRONG("Natal Saturn is strong - better equipped to handle transit", "जन्म शनि बलियो - गोचर सम्हाल्न राम्रो सुसज्जित"),
SADE_SATI_FACTOR_DEBILITATED("Saturn is debilitated in transit - effects may be more challenging", "शनि गोचरमा नीच - प्रभावहरू थप चुनौतीपूर्ण हुन सक्छ"),
SADE_SATI_FACTOR_WEAK_MOON("Natal Moon is weak - emotional resilience may be tested", "जन्म चन्द्र कमजोर - भावनात्मक लचिलोपन परीक्षण हुन सक्छ"),
SADE_SATI_FACTOR_NATAL_WEAK("Natal Saturn is weak - transit effects may be more pronounced", "जन्म शनि कमजोर - गोचर प्रभाव थप उच्चारित हुन सक्छ"),
SADE_SATI_FACTOR_RETROGRADE("Natal Saturn is retrograde - internal processing of karmic lessons", "जन्म शनि वक्री - कार्मिक पाठहरूको आन्तरिक प्रशोधन"),
SADE_SATI_TIMING_SATURN_HORA("Saturday during Saturn Hora", "शनि होरामा शनिबार"),
SADE_SATI_TIMING_EVERY_SATURDAY("Every Saturday", "हरेक शनिबार"),
SADE_SATI_TIMING_TUE_SAT("Tuesday and Saturday", "मंगलबार र शनिबार"),
SYNASTRY_LAGNA("Lagna", "लग्न"),
SYNASTRY_MOON("Moon", "चन्द्र"),
SYNASTRY_VENUS("Venus", "शुक्र"),
SYNASTRY_HOUSE_IN("in House", "भावमा"),
BHRIGU_BINDU_TITLE("Bhrigu Bindu Analysis", "भृगु बिन्दु विश्लेषण"),
BHRIGU_BINDU_SUBTITLE("Karmic Destiny Point", "कार्मिक भाग्य बिन्दु"),
BHRIGU_BINDU_LONGITUDE("Bhrigu Bindu Longitude", "भृगु बिन्दु देशान्तर"),
BHRIGU_BINDU_SIGN("Sign", "राशि"),
BHRIGU_BINDU_NAKSHATRA("Nakshatra", "नक्षत्र"),
BHRIGU_BINDU_PADA("Pada", "पद"),
BHRIGU_BINDU_HOUSE("House", "भाव"),
BHRIGU_BINDU_LORD("Sign Lord", "राशि स्वामी"),
BHRIGU_BINDU_NAKSHATRA_LORD("Nakshatra Lord", "नक्षत्र स्वामी")
}
