package com.astro.storm.core.common

enum class StringKeyGeneralPart5(override val en: String, override val ne: String) : StringKeyInterface {
    GUNA_DESC_GANA("Gana measures temperament compatibility through Deva (divine), Manushya (human), or Rakshasa (demon) classification based on Nakshatra.", "गणले नक्षत्रमा आधारित देव, मनुष्य, वा राक्षस वर्गीकरण मार्फत स्वभाव अनुकूलता मापन गर्दछ।"),
    GUNA_DESC_GRAHA_MAITRI("Graha Maitri analyzes mental compatibility through the friendship of Moon sign lords. It indicates how well the couple can understand each other intellectually.", "ग्रह मैत्रीले चन्द्र राशि स्वामीहरूको मित्रता मार्फत मानसिक अनुकूलता विश्लेषण गर्दछ। यसले जोडीले बौद्धिक रूपमा एकअर्कालाई कत्तिको राम्रोसँग बुझ्न सक्छ संकेत गर्दछ।"),
    GUNA_DESC_NADI("Nadi is the most important factor (8 points), indicating health and progeny compatibility. Same Nadi can cause health issues and affect children.", "नाडी सबैभन्दा महत्त्वपूर्ण कारक (८ अंक) हो, स्वास्थ्य र सन्तान अनुकूलता संकेत गर्दछ। उही नाडीले स्वास्थ्य समस्या र सन्तानमा असर पार्न सक्छ।"),
    GUNA_DESC_NOT_AVAILABLE("Detailed description not available for this Guna.", "यस गुणको विस्तृत विवरण उपलब्ध छैन।"),
    GUNA_DESC_TARA("Tara analyzes destiny compatibility through the birth stars (Nakshatras). It determines the auspiciousness of the couple's combined destiny path.", "तारा जन्म तारा (नक्षत्र) मार्फत भाग्य अनुकूलता विश्लेषण गर्दछ। यसले जोडीको संयुक्त भाग्य मार्गको शुभता निर्धारण गर्दछ।"),
    GUNA_DESC_VARNA("Varna indicates spiritual compatibility based on the Moon sign's element. It measures ego harmony and how partners relate on a spiritual level. Higher compatibility suggests natural understanding of values.", "वर्णले चन्द्र राशिको तत्वमा आधारित आध्यात्मिक अनुकूलता संकेत गर्दछ। यसले अहंकार सामञ्जस्य र साझेदारहरू आध्यात्मिक स्तरमा कसरी सम्बन्धित छन् मापन गर्दछ।"),
    GUNA_DESC_VASHYA("Vashya measures the mutual attraction and influence between partners. It indicates who can influence whom and the power dynamics in the relationship.", "वश्यले साझेदारहरू बीचको पारस्परिक आकर्षण र प्रभाव मापन गर्दछ। यसले कसले कसलाई प्रभाव पार्न सक्छ र सम्बन्धमा शक्ति गतिशीलता संकेत गर्दछ।"),
    GUNA_DESC_YONI("Yoni represents physical and sexual compatibility based on the animal nature assigned to each Nakshatra. Same or friendly animals indicate better physical harmony.", "योनीले प्रत्येक नक्षत्रलाई तोकिएको पशु प्रकृतिमा आधारित शारीरिक र यौन अनुकूलता प्रतिनिधित्व गर्दछ। उही वा मित्र पशुहरूले राम्रो शारीरिक सामञ्जस्य संकेत गर्दछ।"),
    GUNA_GANA("Gana", "गण"),
    GUNA_GRAHA_MAITRI("Graha Maitri", "ग्रह मैत्री"),
    GUNA_NADI("Nadi", "नाडी"),
    GUNA_POINTS("Points", "अंकहरू"),
    GUNA_RAJAS("Rajas", "रजस्"),
    GUNA_SATTVA("Sattva", "सत्त्व"),
    GUNA_TAMAS("Tamas", "तमस्"),
    GUNA_TARA("Tara", "तारा"),
    GUNA_VARNA("Varna", "वर्ण"),
    GUNA_VASHYA("Vashya", "वश्य"),
    GUNA_YONI("Yoni", "योनि"),
    GURU_BLESSINGS("Guru Blessings", "गुरु आशीर्वाद"),
    GURU_CONNECTION("Guru Connection", "गुरु सम्बन्ध"),
    HARMONY_INDICATORS("Harmony Indicators", "सामंजस्य सूचकहरू"),
    HEALING_CAPACITY("Healing Capacity", "उपचार क्षमता"),
    HEALTH_ADVICE("Health Advice", "स्वास्थ्य सल्लाह"),
    HEALTH_AQUARIUS_AREAS("Areas requiring attention: Ankles, circulation, calves. Tendency toward circulatory and nervous issues.",
        "ध्यान आवश्यक क्षेत्रहरू: गोली, रक्त संचार, पिण्डली। रक्त संचार र स्नायु समस्याहरूको प्रवृत्ति।"),
    HEALTH_ARIES_AREAS("Areas requiring attention: Head, brain, face, eyes. Tendency toward headaches, fevers, and inflammations.",
        "ध्यान आवश्यक क्षेत्रहरू: टाउको, मस्तिष्क, अनुहार, आँखा। टाउको दुखाइ, ज्वरो, र सूजनको प्रवृत्ति।"),
    HEALTH_CANCER_AREAS("Areas requiring attention: Chest, stomach, breasts, digestion. Tendency toward digestive and emotional health issues.",
        "ध्यान आवश्यक क्षेत्रहरू: छाती, पेट, स्तन, पाचन। पाचन र भावनात्मक स्वास्थ्य समस्याहरूको प्रवृत्ति।"),
    HEALTH_CAPRICORN_AREAS("Areas requiring attention: Knees, bones, joints, skin. Tendency toward joint and bone conditions.",
        "ध्यान आवश्यक क्षेत्रहरू: घुँडा, हड्डी, जोर्नी, छाला। जोर्नी र हड्डी अवस्थाहरूको प्रवृत्ति।"),
    HEALTH_CONCERN_AREAS("Health Concern Areas", "स्वास्थ्य चिन्ता क्षेत्रहरू"),
    HEALTH_CONSTITUTION_MODERATE("Your constitution is moderate, requiring regular attention to diet and lifestyle for optimal health.",
        "तपाईंको संरचना मध्यम छ, इष्टतम स्वास्थ्यको लागि आहार र जीवनशैलीमा नियमित ध्यान आवश्यक छ।"),
    HEALTH_CONSTITUTION_SENSITIVE("Your constitution is sensitive, benefiting from preventive care and balanced routines.",
        "तपाईंको संरचना संवेदनशील छ, निवारक हेरचाह र सन्तुलित दिनचर्याबाट लाभ हुन्छ।"),
    HEALTH_CONSTITUTION_STRONG("You possess a strong constitution with good vitality and natural resistance to illness.",
        "तपाईंसँग राम्रो जीवनी शक्ति र रोगको लागि प्राकृतिक प्रतिरोधको साथ बलियो संरचना छ।"),
    HEALTH_GEMINI_AREAS("Areas requiring attention: Lungs, arms, hands, nervous system. Tendency toward respiratory and nervous disorders.",
        "ध्यान आवश्यक क्षेत्रहरू: फोक्सो, हात, हातहरू, स्नायु प्रणाली। श्वासप्रश्वास र स्नायु विकारहरूको प्रवृत्ति।"),
    HEALTH_LEO_AREAS("Areas requiring attention: Heart, spine, back. Tendency toward cardiac and spinal issues.",
        "ध्यान आवश्यक क्षेत्रहरू: मुटु, मेरुदण्ड, पिठ्यूँ। हृदय र मेरुदण्ड समस्याहरूको प्रवृत्ति।"),
    HEALTH_LIBRA_AREAS("Areas requiring attention: Kidneys, lower back, skin. Tendency toward kidney and skin conditions.",
        "ध्यान आवश्यक क्षेत्रहरू: मिर्गौला, तल्लो ढाड, छाला। मिर्गौला र छाला अवस्थाहरूको प्रवृत्ति।"),
    HEALTH_OUTLOOK("Health Outlook", "स्वास्थ्य दृष्टिकोण"),
    HEALTH_OVERVIEW("Health analysis is based on your Ascendant, 6th house (diseases), 8th house (longevity), and planetary afflictions.",
        "स्वास्थ्य विश्लेषण तपाईंको लग्न, ६औं भाव (रोग), ८औं भाव (आयु), र ग्रह पीडाहरूमा आधारित छ।"),
    HEALTH_PISCES_AREAS("Areas requiring attention: Feet, lymphatic system, immune system. Tendency toward foot problems and immune issues.",
        "ध्यान आवश्यक क्षेत्रहरू: खुट्टा, लिम्फेटिक प्रणाली, प्रतिरक्षा प्रणाली। खुट्टा समस्या र प्रतिरक्षा समस्याहरूको प्रवृत्ति।"),
    HEALTH_SAGITTARIUS_AREAS("Areas requiring attention: Hips, thighs, liver, sciatic nerve. Tendency toward liver and hip issues.",
        "ध्यान आवश्यक क्षेत्रहरू: कमर, जाँघ, कलेजो, साइटिक नसा। कलेजो र कमर समस्याहरूको प्रवृत्ति।"),
    HEALTH_SCORE("Health Strength Score", "स्वास्थ्य शक्ति स्कोर"),
    HEALTH_SCORPIO_AREAS("Areas requiring attention: Reproductive organs, bladder, elimination. Tendency toward urogenital issues.",
        "ध्यान आवश्यक क्षेत्रहरू: प्रजनन अंगहरू, मूत्राशय, उत्सर्जन। मूत्रजननांगी समस्याहरूको प्रवृत्ति।"),
    HEALTH_STRENGTHS("Health Strengths", "स्वास्थ्य शक्तिहरू"),
    HEALTH_SUMMARY("Health Summary", "स्वास्थ्य सारांश"),
    HEALTH_TAURUS_AREAS("Areas requiring attention: Throat, neck, thyroid, tonsils. Tendency toward throat ailments and metabolic issues.",
        "ध्यान आवश्यक क्षेत्रहरू: घाँटी, गर्दन, थाइरोइड, टन्सिल। घाँटी रोग र चयापचय समस्याहरूको प्रवृत्ति।"),
    HEALTH_TIMELINE("Health Timeline", "स्वास्थ्य समयरेखा"),
    HEALTH_VIRGO_AREAS("Areas requiring attention: Intestines, digestive system, nervous system. Tendency toward digestive and anxiety issues.",
        "ध्यान आवश्यक क्षेत्रहरू: आन्द्रा, पाचन प्रणाली, स्नायु प्रणाली। पाचन र चिन्ता समस्याहरूको प्रवृत्ति।"),
    HIGHER_EDU_POTENTIAL("Higher Education Potential", "उच्च शिक्षा क्षमता"),
    HIGHER_EDU_TITLE("Higher Education Analysis", "उच्च शिक्षा विश्लेषण"),
    HIGHER_LEARNING("Higher Learning Ability", "उच्च सिक्ने क्षमता"),
    HIGHER_PHILOSOPHY("Higher Philosophy", "उच्च दर्शन"),
    HOME_CHART_ANALYSIS("Chart Analysis", "कुण्डली विश्लेषण"),
    HOME_COMING_SOON("Coming Soon", "छिट्टै आउँदैछ"),
    HOME_DASHA_LABEL("Dasha", "दशा"),
    HOME_EXPLORE_FEATURES("Explore your chart features", "आफ्नो कुण्डली सुविधाहरू अन्वेषण गर्नुहोस्"),
    HOME_SOON_BADGE("Soon", "छिट्टै"),
    HOROSCOPE_ASHTAKAVARGA_MODERATE("Ashtakavarga (%d/8) moderates results.", "अष्टकवर्ग (%d/8) ले परिणामहरूलाई मध्यम बनाउँछ।"),
    HOROSCOPE_ASHTAKAVARGA_STRONG("Ashtakavarga (%d/8) strengthens results.", "अष्टकवर्ग (%d/8) ले परिणामहरू बलियो बनाउँछ।"),
    HOROSCOPE_ASHTAKAVARGA_WEAK("Low Ashtakavarga (%d/8) weakens results.", "कम अष्टकवर्ग (%d/8) ले परिणामहरू कमजोर बनाउँछ।"),
    HOROSCOPE_BALANCE("Balance", "सन्तुलन"),
    HOROSCOPE_BALANCED_ENERGY("Balanced energy in this area.", "यस क्षेत्रमा सन्तुलित ऊर्जा।"),
    HOROSCOPE_CALCULATING("Calculating...", "गणना गर्दै..."),
    HOROSCOPE_DEBILITATED("Debilitated - results weakened.", "नीच - परिणामहरू कमजोर।"),
    HOROSCOPE_EXALTED("Exalted - excellent results.", "उच्च - उत्कृष्ट परिणामहरू।"),
    HOROSCOPE_FAVORABLE_TRANSIT("Favorable %s transit in house %d.", "भाव %d मा अनुकूल %s गोचर।"),
    HOROSCOPE_OWN_SIGN("Strong in own sign.", "आफ्नै राशिमा बलियो।"),
    HOROSCOPE_RETROGRADE_DELAY("%s's retrograde motion delays manifestation.", "%s को वक्री गतिले प्रकटीकरणमा ढिलाइ गर्छ।"),
    HOROSCOPE_RETROGRADE_RELIEF("%s's retrograde provides some relief from challenges.", "%s को वक्रीले चुनौतीहरूबाट केही राहत प्रदान गर्छ।"),
    HOROSCOPE_STEADY_ENERGY("Steady energy expected", "स्थिर ऊर्जा अपेक्षित"),
    HOROSCOPE_UNFAVORABLE_TRANSIT("Challenging %s transit in house %d.", "भाव %d मा चुनौतीपूर्ण %s गोचर।"),
    HOROSCOPE_VEDHA_OBSTRUCTION("However, %s creates Vedha obstruction, reducing benefits.", "तर, %s ले वेध अवरोध सिर्जना गर्छ, फाइदाहरू घटाउँछ।"),
    HOURS_SHORT("h", "घ"),
    HOUSE("House", "भाव"),
    HOUSE_10_NAME("Tenth House (Karma)", "दसौं भाव (कर्म)"),
    HOUSE_10_SIG("Career, Status, Public Image", "क्यारियर, पद, सार्वजनिक छवि"),
    HOUSE_10_SIGNIFICANCE("Career, Status, Authority", "क्यारियर, स्थिति, अधिकार"),
    HOUSE_10_SIGNIFICATION("career and public recognition", "क्यारियर र सार्वजनिक मान्यता"),
    HOUSE_11_NAME("Eleventh House (Labha)", "एघारौं भाव (लाभ)"),
    HOUSE_11_SIG("Gains, Income, Desires", "लाभ, आय, इच्छाहरू"),
    HOUSE_11_SIGNIFICANCE("Gains, Income, Friends", "लाभ, आय, मित्रहरू"),
    HOUSE_11_SIGNIFICATION("gains and social networks", "लाभ र सामाजिक सञ्जालहरू"),
    HOUSE_12_NAME("Twelfth House (Vyaya)", "बाह्रौं भाव (व्यय)"),
    HOUSE_12_SIG("Losses, Expenses, Liberation", "हानि, खर्च, मोक्ष"),
    HOUSE_12_SIGNIFICANCE("Losses, Expenses, Foreign", "हानि, खर्च, विदेश"),
    HOUSE_12_SIGNIFICATION("foreign connections and spiritual pursuits", "विदेशी सम्बन्ध र आध्यात्मिक खोजीहरू"),
    HOUSE_1_NAME("First House (Lagna)", "पहिलो भाव (लग्न)"),
    HOUSE_1_SIG("Self, Body, Personality", "आत्म, शरीर, व्यक्तित्व"),
    HOUSE_1_SIGNIFICANCE("Self, Appearance, Health", "स्वयं, स्वरूप, स्वास्थ्य"),
    HOUSE_1_SIGNIFICATION("self-effort and personality", "आत्म-प्रयास र व्यक्तित्व"),
    HOUSE_2_NAME("Second House (Dhana)", "दोस्रो भाव (धन)"),
    HOUSE_2_SIG("Wealth, Family, Speech", "धन, परिवार, वाणी"),
    HOUSE_2_SIGNIFICANCE("Wealth, Family, Speech", "धन, परिवार, वाणी"),
    HOUSE_2_SIGNIFICATION("family wealth and speech", "पारिवारिक धन र वाणी"),
    HOUSE_3_NAME("Third House (Sahaja)", "तेस्रो भाव (सहज)"),
    HOUSE_3_SIG("Siblings, Courage, Communication", "भाइबहिनी, साहस, सञ्चार"),
    HOUSE_3_SIGNIFICANCE("Siblings, Courage, Communication", "भाइबहिनी, साहस, सञ्चार"),
    HOUSE_3_SIGNIFICATION("courage and communication", "साहस र सञ्चार"),
    HOUSE_4_NAME("Fourth House (Sukha)", "चौथो भाव (सुख)"),
    HOUSE_4_SIG("Home, Mother, Happiness", "घर, आमा, सुख"),
    HOUSE_4_SIGNIFICANCE("Mother, Happiness, Property", "आमा, सुख, सम्पत्ति"),
    HOUSE_4_SIGNIFICATION("property and domestic comfort", "सम्पत्ति र घरेलु सुविधा"),
    HOUSE_5_NAME("Fifth House (Putra)", "पाँचौं भाव (पुत्र)"),
    HOUSE_5_SIG("Children, Intelligence, Romance", "सन्तान, बुद्धि, प्रेम"),
    HOUSE_5_SIGNIFICANCE("Children, Intelligence, Creativity", "सन्तान, बुद्धि, सिर्जनात्मकता"),
    HOUSE_5_SIGNIFICATION("speculation and creative ventures", "अनुमान र सिर्जनात्मक उद्यमहरू"),
    HOUSE_6_NAME("Sixth House (Ripu)", "छैटौं भाव (रिपु)"),
    HOUSE_6_SIG("Enemies, Health, Service", "शत्रु, स्वास्थ्य, सेवा"),
    HOUSE_6_SIGNIFICANCE("Health, Debts, Enemies", "स्वास्थ्य, ऋण, शत्रु"),
    HOUSE_6_SIGNIFICATION("service and defeating competition", "सेवा र प्रतिस्पर्धा जित्नु"),
    HOUSE_7_NAME("Seventh House (Kalatra)", "सातौं भाव (कलत्र)"),
    HOUSE_7_SIG("Marriage, Partnerships, Business", "विवाह, साझेदारी, व्यापार"),
    HOUSE_7_SIGNIFICANCE("Marriage, Partnership, Public", "विवाह, साझेदारी, सार्वजनिक"),
    HOUSE_7_SIGNIFICATION("partnership and business", "साझेदारी र व्यापार"),
    HOUSE_8_NAME("Eighth House (Ayur)", "आठौं भाव (आयु)"),
    HOUSE_8_SIG("Longevity, Transformation, Occult", "आयु, रूपान्तरण, तन्त्र"),
    HOUSE_8_SIGNIFICANCE("Longevity, Transformation, Hidden", "दीर्घायु, रूपान्तरण, लुकेका कुराहरू"),
    HOUSE_8_SIGNIFICATION("inheritance and unexpected gains", "विरासत र अप्रत्याशित लाभ"),
    HOUSE_9_NAME("Ninth House (Dharma)", "नवौं भाव (धर्म)"),
    HOUSE_9_SIG("Fortune, Dharma, Father", "भाग्य, धर्म, पिता"),
    HOUSE_9_SIGNIFICANCE("Fortune, Religion, Father", "भाग्य, धर्म, पिता"),
    HOUSE_9_SIGNIFICATION("fortune and higher pursuits", "भाग्य र उच्च खोजीहरू"),
    HOUSE_ALCABITUS("Alcabitus", "अल्काबिटस"),
    HOUSE_ARTHA("Artha (2, 6, 10)", "अर्थ (२, ६, १०)"),
    HOUSE_CAMPANUS("Campanus", "क्याम्पानस"),
    HOUSE_DETAIL_INTERP_1("The First House is the most important house, representing you as a whole. It shows your physical constitution, personality traits, and how you present yourself to the world. A strong 1st house gives good health, confidence, and success in self-started ventures.", "पहिलो भाव सबैभन्दा महत्त्वपूर्ण भाव हो, जसले समग्र रूपमा तपाईंको प्रतिनिधित्व गर्दछ। यसले तपाईंको शारीरिक संरचना, व्यक्तित्वका लक्षणहरू, र तपाईंले संसारमा आफूलाई कसरी प्रस्तुत गर्नुहुन्छ भन्ने देखाउँछ। बलियो पहिलो भावले राम्रो स्वास्थ्य, आत्मविश्वास र स्व-सुरु गरिएका उद्यमहरूमा सफलता दिन्छ।"),
    HOUSE_DETAIL_INTERP_10("The Tenth House is the house of career and public image. It shows your profession, status in society, and relationship with authority. A strong 10th house gives career success, fame, and high position in society.", "दशौं भाव करियर र सार्वजनिक छविको भाव हो। यसले तपाईंको पेशा, समाजमा स्थिति, र अधिकारसँगको सम्बन्ध देखाउँछ। बलियो दशौं भावले करियर सफलता, प्रसिद्धि, र समाजमा उच्च पद दिन्छ।"),
    HOUSE_DETAIL_INTERP_11("The Eleventh House is the house of gains and fulfillment of desires. It governs income, elder siblings, and friendships. A strong 11th house gives multiple sources of income, supportive friends, and fulfillment of hopes.", "एघारौं भाव नाफा र इच्छाहरूकोपूर्तिको भाव हो। यसले आय, ठूला भाइबहिनी, र मित्रतालाई नियन्त्रण गर्दछ। बलियो एघारौं भावले आयका धेरै स्रोतहरू, सहयोगी साथीहरू, र आशाहरूको पूर्ति दिन्छ।"),
    HOUSE_DETAIL_INTERP_12("The Twelfth House governs losses, expenses, and liberation. While it shows material losses, it also represents spiritual gains and final liberation. A strong 12th house gives spiritual inclinations, success abroad, and peaceful sleep.", "बाह्रौं भावले हानि, खर्च, र मुक्तिलाई नियन्त्रण गर्दछ। यसले भौतिक हानि देखाए पनि, यसले आध्यात्मिक लाभ र अन्तिम मुक्तिलाई पनि प्रतिनिधित्व गर्दछ। बलियो बाह्रौं भावले आध्यात्मिक झुकाव, विदेशमा सफलता, र शान्त निद्रा दिन्छ।"),
    HOUSE_DETAIL_INTERP_2("The Second House governs accumulated wealth, family values, and speech. It shows how you earn and save money, your relationship with family, and your communication style. A strong 2nd house indicates financial stability and sweet speech.", "दोस्रो भावले सञ्चित धन, पारिवारिक मूल्य मान्यता र वाणीलाई नियन्त्रण गर्दछ। यसले तपाईंले कसरी पैसा कमाउनुहुन्छ र बचत गर्नुहुन्छ, परिवारसँगको तपाईंको सम्बन्ध, र तपाईंको सञ्चार शैली देखाउँछ। बलियो दोस्रो भावले आर्थिक स्थिरता र मधुर वाणी संकेत गर्दछ।"),
    HOUSE_DETAIL_INTERP_3("The Third House represents courage, initiative, and self-effort. It governs siblings (especially younger), short travels, and all forms of communication. A strong 3rd house gives courage, good relationships with siblings, and success through personal effort.", "तेस्रो भावले साहस, पहल र आत्म-प्रयासको प्रतिनिधित्व गर्दछ। यसले भाइबहिनी (विशेष गरी साना), छोटो यात्रा, र सञ्चारका सबै रूपहरूलाई नियन्त्रण गर्दछ। बलियो तेस्रो भावले साहस, भाइबहिनीसँग राम्रो सम्बन्ध, र व्यक्तिगत प्रयास मार्फत सफलता दिन्छ।"),
    HOUSE_DETAIL_INTERP_4("The Fourth House is the foundation of your life. It represents your mother, home environment, and emotional security. It also governs formal education and landed property. A strong 4th house gives domestic happiness, property ownership, and mental peace.", "चौथो भाव तपाईंको जीवनको आधार हो। यसले तपाईंको आमा, घरको वातावरण, र भावनात्मक सुरक्षाको प्रतिनिधित्व गर्दछ। यसले औपचारिक शिक्षा र जग्गा जमिनलाई पनि नियन्त्रण गर्दछ। बलियो चौथो भावले पारिवारिक खुसी, सम्पत्ति स्वामित्व, र मानसिक शान्ति दिन्छ।"),
    HOUSE_DETAIL_INTERP_5("The Fifth House is the house of creativity and Purva Punya (past life merits). It governs children, intelligence, romance, and speculative gains. A strong 5th house gives intelligent children, creative talents, and success in speculation.", "पाँचौं भाव सिर्जनशीलता र पूर्व पुण्य (पूर्वजन्मको गुणहरू) को भाव हो। यसले सन्तान, बुद्धि, रोमान्स, र अनुमानित लाभहरूलाई नियन्त्रण गर्दछ। बलियो पाँचौं भावले बुद्धिमान सन्तान, सिर्जनात्मक प्रतिभा, र अनुमानमा सफलता दिन्छ।"),
    HOUSE_DETAIL_INTERP_6("The Sixth House governs obstacles, health issues, and service. While considered malefic, it also shows the ability to overcome challenges. A well-placed 6th house gives victory over enemies, good health practices, and success in competitive fields.", "छैटौं भावले अवरोध, स्वास्थ्य समस्या, र सेवालाई नियन्त्रण गर्दछ। यसलाई पापी मानिए पनि, यसले चुनौतीहरू पार गर्ने क्षमता पनि देखाउँछ। राम्रोसँग स्थित छैटौं भावले शत्रुहरूमाथि विजय, राम्रो स्वास्थ्य अभ्यास, र प्रतिस्पर्धी क्षेत्रहरूमा सफलता दिन्छ।"),
    HOUSE_DETAIL_INTERP_7("The Seventh House is the house of partnerships and marriage. It shows your spouse's nature and quality of marriage. It also governs business partnerships and public dealings. A strong 7th house gives a good spouse and success in partnerships.", "सातौं भाव साझेदारी र विवाहको भाव हो। यसले तपाईंको जीवनसाथीको स्वभाव र विवाहको गुणस्तर देखाउँछ। यसले व्यापार साझेदारी र सार्वजनिक व्यवहारलाई पनि नियन्त्रण गर्दछ। बलियो सातौं भावले राम्रो जीवनसाथी र साझेदारीमा सफलता दिन्छ।"),
    HOUSE_DETAIL_INTERP_8("The Eighth House governs transformation, death, and rebirth (metaphorical). It shows hidden matters, inheritance, and occult interests. While considered difficult, a well-placed 8th house gives longevity, research abilities, and unexpected gains.", "आठौं भावले रूपान्तरण, मृत्यु, र पुनर्जन्म (लाक्षणिक) लाई नियन्त्रण गर्दछ। यसले लुकेका कुरा, पैतृक सम्पत्ति, र तान्त्रिक रुचिहरू देखाउँछ। यसलाई कठिन मानिए पनि, राम्रोसँग स्थित आठौं भावले दीर्घायु, अनुसन्धान क्षमता, र अप्रत्याशित लाभ दिन्छ।"),
    HOUSE_DETAIL_INTERP_9("The Ninth House is the most auspicious house of fortune and dharma. It represents your father, teachers, and higher wisdom. A strong 9th house gives good fortune, philosophical inclinations, and blessings from elders and teachers.", "नवौं भाव भाग्य र धर्मको सबैभन्दा शुभ भाव हो। यसले तपाईंको पिता, शिक्षकहरू, र उच्च ज्ञानको प्रतिनिधित्व गर्दछ। बलियो नवौं भावले राम्रो भाग्य, दार्शनिक झुकाव, र ठूलाहरू तथा शिक्षकहरूबाट आशीर्वाद दिन्छ।"),
    HOUSE_DETAIL_NAME_1("Lagna Bhava (Ascendant)", "लग्न भाव (उदय)"),
    HOUSE_DETAIL_NAME_10("Karma Bhava (Career)", "कर्म भाव (करियर)"),
    HOUSE_DETAIL_NAME_11("Labha Bhava (Gains)", "लाभ भाव (नाफा)"),
    HOUSE_DETAIL_NAME_12("Vyaya Bhava (Loss)", "व्यय भाव (हानि)"),
    HOUSE_DETAIL_NAME_2("Dhana Bhava (Wealth)", "धन भाव (सम्पत्ति)"),
    HOUSE_DETAIL_NAME_3("Sahaja Bhava (Siblings)", "सहज भाव (भाइबहिनी)"),
    HOUSE_DETAIL_NAME_4("Sukha Bhava (Happiness)", "सुख भाव (खुसी)"),
    HOUSE_DETAIL_NAME_5("Putra Bhava (Children)", "पुत्र भाव (सन्तान)"),
    HOUSE_DETAIL_NAME_6("Ripu Bhava (Enemies)", "रिपु भाव (शत्रु)"),
    HOUSE_DETAIL_NAME_7("Kalatra Bhava (Spouse)", "कलत्र भाव (जीवनसाथी)"),
    HOUSE_DETAIL_NAME_8("Ayur Bhava (Longevity)", "आयु भाव (दीर्घायु)"),
    HOUSE_DETAIL_NAME_9("Dharma Bhava (Fortune)", "धर्म भाव (भाग्य)"),
    HOUSE_DETAIL_SIG_1("Physical body, Personality, Self-identity, Head and brain, General health, Beginning of life, Appearance", "भौतिक शरीर, व्यक्तित्व, आत्म-पहिचान, टाउको र मस्तिष्क, सामान्य स्वास्थ्य, जीवनको सुरुवात, रूप"),
    HOUSE_DETAIL_SIG_10("Career, Profession, Status & Fame, Authority, Government, Father, Knees", "करियर, पेशा, पद र प्रतिष्ठा, अधिकार, सरकार, पिता, घुँडा"),
    HOUSE_DETAIL_SIG_11("Income & Gains, Elder siblings, Friends, Hopes & Wishes, Social network, Left ear, Ankles", "आय र नाफा, ठूला भाइबहिनी, साथीहरू, आशा र इच्छाहरू, सामाजिक सञ्जाल, बायाँ कान, कुर्कुच्चा"),
    HOUSE_DETAIL_SIG_12("Losses & Expenses, Liberation (Moksha), Foreign lands, Isolation, Feet, Sleep, Subconscious", "हानि र खर्च, मुक्ति (मोक्ष), विदेशी भूमि, एकान्त, खुट्टा, निद्रा, अवचेतन"),
    HOUSE_DETAIL_SIG_2("Wealth & Possessions, Family, Speech, Right eye, Face, Food intake, Early childhood", "धन र सम्पत्ति, परिवार, वाणी, दाहिने आँखा, अनुहार, भोजन, प्रारम्भिक बाल्यकाल"),
    HOUSE_DETAIL_SIG_3("Siblings, Courage, Short journeys, Communication, Arms and shoulders, Neighbors, Hobbies", "भाइबहिनी, साहस, छोटो यात्रा, सञ्चार, हात र काँध, छिमेकी, शौक"),
    HOUSE_DETAIL_SIG_4("Mother, Home & Property, Vehicles, Education, Chest & Heart, Inner peace, Emotional foundation", "आमा, घर र सम्पत्ति, सवारी साधन, शिक्षा, छाती र हृदय, आन्तरिक शान्ति, भावनात्मक आधार"),
    HOUSE_DETAIL_SIG_5("Children, Intelligence, Creativity, Romance, Past life merit, Speculation, Higher education", "सन्तान, बुद्धि, सिर्जनशीलता, रोमान्स, पूर्वजन्मको पुण्य, अनुमान, उच्च शिक्षा"),
    HOUSE_DETAIL_SIG_6("Enemies, Diseases, Debts, Service, Competition, Daily work, Maternal uncle", "शत्रु, रोग, ऋण, सेवा, प्रतिस्पर्धा, दैनिक काम, मामा"),
    HOUSE_DETAIL_SIG_7("Marriage, Spouse, Business partnerships, Foreign travel, Public dealing, Lower abdomen, Sexual organs", "विवाह, जीवनसाथी, व्यापार साझेदारी, विदेश यात्रा, सार्वजनिक व्यवहार, तल्लो पेट, यौन अंग"),
    HOUSE_DETAIL_SIG_8("Longevity, Transformation, Occult, Inheritance, Hidden matters, Chronic diseases, In-laws' wealth", "दीर्घायु, रूपान्तरण, तन्त्रमन्त्र, पैतृक सम्पत्ति, लुकेका कुरा, दीर्घकालीन रोग, ससुरालीको धन"),
    HOUSE_DETAIL_SIG_9("Fortune & Luck, Father, Higher learning, Long journeys, Religion & Philosophy, Guru/Teacher, Righteousness", "भाग्य र किस्मत, पिता, उच्च शिक्षा, लामो यात्रा, धर्म र दर्शन, गुरु/शिक्षक, धार्मिकता"),
    HOUSE_DETAIL_TYPE_1("Kendra (Angular) & Trikona (Trine)", "केन्द्र (कोणीय) र त्रिकोण"),
    HOUSE_DETAIL_TYPE_10("Kendra (Angular) & Upachaya", "केन्द्र (कोणीय) र उपचय"),
    HOUSE_DETAIL_TYPE_11("Upachaya (Growth) & Panapara", "उपचय (वृद्धि) र पणफर"),
    HOUSE_DETAIL_TYPE_12("Dusthana (Malefic) & Apoklima", "दुःस्थान (पापी) र आपोक्लिम"),
    HOUSE_DETAIL_TYPE_2("Maraka (Death-inflicting) & Panapara", "मारक (मृत्युकारक) र पणफर"),
    HOUSE_DETAIL_TYPE_3("Upachaya (Growth) & Apoklima", "उपचय (वृद्धि) र आपोक्लिम"),
    HOUSE_DETAIL_TYPE_4("Kendra (Angular)", "केन्द्र (कोणीय)"),
    HOUSE_DETAIL_TYPE_5("Trikona (Trine) & Panapara", "त्रिकोण र पणफर"),
    HOUSE_DETAIL_TYPE_6("Dusthana (Malefic) & Upachaya", "दुःस्थान (पापी) र उपचय"),
    HOUSE_DETAIL_TYPE_7("Kendra (Angular) & Maraka", "केन्द्र (कोणीय) र मारक"),
    HOUSE_DETAIL_TYPE_8("Dusthana (Malefic) & Panapara", "दुःस्थान (पापी) र पणफर"),
    HOUSE_DETAIL_TYPE_9("Trikona (Trine) & Apoklima", "त्रिकोण र आपोक्लिम"),
    HOUSE_DHARMA("Dharma (1, 5, 9)", "धर्म (१, ५, ९)"),
    HOUSE_EFFECT_1("{0} in 1st house: Yoga effects directly impact personality, health, and overall life approach. Strong self-projection of {1}''s qualities.", "{0} पहिलो भावमा: योगको प्रभावले व्यक्तित्व, स्वास्थ्य र समग्र जीवन दृष्टिकोणमा सीधा प्रभाव पार्छ। {1} को गुणहरूको बलियो आत्म-प्रक्षेपण।"),
    HOUSE_EFFECT_10("{0} in 10th house: Career excellence, public recognition, authority. {1}''s qualities shine in professional life.", "{0} दशौं भावमा: करियरमा उत्कृष्टता, सार्वजनिक मान्यता, अधिकार। व्यावसायिक जीवनमा {1} को गुणहरू चम्किन्छन्।"),
    HOUSE_EFFECT_4("{0} in 4th house: Benefits related to home, mother, vehicles, property, and inner peace. {1}''s blessings in domestic life.", "{0} चौथो भावमा: घर, आमा, सवारी साधन, सम्पत्ति र आन्तरिक शान्तिसँग सम्बन्धित लाभहरू। पारिवारिक जीवनमा {1} को आशीर्वाद।"),
    HOUSE_EFFECT_7("{0} in 7th house: Strong impact on marriage, partnerships, business dealings. Spouse may have {1}''s characteristics.", "{0} सातौं भावमा: विवाह, साझेदारी, व्यापारिक लेनदेनमा बलियो प्रभाव। जीवनसाथीमा {1} को विशेषताहरू हुन सक्छन्।"),
    HOUSE_EFFECT_GENERIC("General yoga effects apply", "सामान्य योग प्रभावहरू लागू हुन्छन्"),
    HOUSE_EQUAL("Equal", "समान"),
    HOUSE_FORMAT("House %d", "भाव %d"),
    HOUSE_KAMA("Kama (3, 7, 11)", "काम (३, ७, ११)"),
    HOUSE_KOCH("Koch", "कोच"),
    HOUSE_LABEL("House", "भाव"),
    HOUSE_LORD_1("1st Lord", "लग्नेश"),
    HOUSE_LORD_10("10th Lord", "दशमेश"),
    HOUSE_LORD_11("11th Lord", "एकादशेश"),
    HOUSE_LORD_12("12th Lord", "द्वादशेश"),
    HOUSE_LORD_2("2nd Lord", "द्वितीयेश"),
    HOUSE_LORD_3("3rd Lord", "तृतीयेश"),
    HOUSE_LORD_4("4th Lord", "चतुर्थेश"),
    HOUSE_LORD_5("5th Lord", "पञ्चमेश"),
    HOUSE_LORD_6("6th Lord", "षष्ठेश"),
    HOUSE_LORD_7("7th Lord", "सप्तमेश"),
    HOUSE_LORD_8("8th Lord", "अष्टमेश"),
    HOUSE_LORD_9("9th Lord", "नवमेश"),
    HOUSE_MERIDIAN("Meridian", "मेरिडियन"),
    HOUSE_MOKSHA("Moksha (4, 8, 12)", "मोक्ष (४, ८, १२)"),
    HOUSE_MORINUS("Morinus", "मोरिनस"),
    HOUSE_PLACIDUS("Placidus", "प्लासिडस"),
    HOUSE_PORPHYRIUS("Porphyrius", "पोर्फिरियस"),
    HOUSE_REC_STRENGTHEN("Strengthen %1\$s for %2\$s house matters", "%2\$s भावका मामिलाका लागि %1\$s लाई बलियो बनाउनुहोस्"),
    HOUSE_REGIOMONTANUS("Regiomontanus", "रेजिओमोन्टानस"),
    HOUSE_SIG_1("Self, Body, Personality", "स्वयं, शरीर, व्यक्तित्व"),
    HOUSE_SIG_10("Career, Fame", "क्यारियर, प्रसिद्धि"),
    HOUSE_SIG_11("Gains, Wishes", "लाभ, इच्छा"),
    HOUSE_SIG_12("Losses, Liberation", "हानी, मोक्ष"),
    HOUSE_SIG_2("Wealth, Speech, Family", "धन, वाणी, परिवार"),
    HOUSE_SIG_3("Siblings, Courage", "दाजुभाइ, साहस"),
    HOUSE_SIG_4("Home, Mother, Property", "घर, आमा, सम्पत्ति"),
    HOUSE_SIG_5("Children, Education", "सन्तान, शिक्षा"),
    HOUSE_SIG_6("Health, Enemies", "स्वास्थ्य, शत्रु"),
    HOUSE_SIG_7("Marriage, Partnership", "विवाह, साझेदारी"),
    HOUSE_SIG_8("Transformation", "रूपान्तरण"),
    HOUSE_SIG_9("Fortune, Father", "भाग्य, पिता"),
    HOUSE_SIG_UNKNOWN("Unknown", "अज्ञात"),
    HOUSE_STRENGTH_CHALLENGED("Challenged", "चुनौतीपूर्ण"),
    HOUSE_STRENGTH_EXCELLENT("Excellent", "उत्कृष्ट"),
    HOUSE_STRENGTH_MODERATE("Moderate", "मध्यम"),
    HOUSE_STRENGTH_STRONG("Strong", "बलियो"),
    HOUSE_STRENGTH_WEAK("Weak", "कमजोर"),
    HOUSE_TYPE_APOKLIMA("Apoklima", "आपोक्लिम"),
    HOUSE_TYPE_DUSTHANA("Dusthana (Malefic)", "दुःस्थान"),
    HOUSE_TYPE_KENDRA("Kendra (Angular)", "केन्द्र"),
    HOUSE_TYPE_MARAKA("Maraka (Death-inflicting)", "मारक"),
    HOUSE_TYPE_PANAPARA("Panapara", "पणफर"),
    HOUSE_TYPE_TRIKONA("Trikona (Trine)", "त्रिकोण"),
    HOUSE_TYPE_UPACHAYA("Upachaya (Growth)", "उपचय"),
    HOUSE_VEHLOW("Vehlow", "भेहलो"),
    HOUSE_WHOLE_SIGN("Whole Sign", "सम्पूर्ण राशि"),
    HUSBAND_INDICATOR("Husband Indicator", "पति सूचक"),
    IMMUNE_SYSTEM("Immune System Profile", "प्रतिरक्षा प्रणाली प्रोफाइल"),
    IMPACT_HIGH("High", "उच्च"),
    IMPACT_MILD("Mild", "हल्का"),
    IMPACT_MINIMAL("Minimal", "न्यूनतम"),
    IMPACT_MODERATE("Moderate", "मध्यम"),
    IMPACT_POSITIVE("Positive", "सकारात्मक"),
    IMPACT_SEVERE("Severe", "गम्भीर"),
    INACTIVE("Inactive", "निष्क्रिय"),
    INCOME_SOURCES("Income Sources", "आय स्रोतहरू"),
    INCOME_STREAMS("Multiple Income Streams", "बहु आय स्रोतहरू"),
    INDIC_JUP_8("Jupiter in 8th house", "बृहस्पति ८औं भावमा"),
    INDIC_MERC_HOUSE("Mercury in %s house", "बुध %s भावमा"),
    INDIC_MOON_HOUSE("Moon in %s house", "चन्द्रमा %s भावमा"),
    INDIC_SUN_HOUSE("Sun in %s house", "सूर्य %s भावमा"),
    INDIC_VENUS_HOUSE("Venus in %s house", "शुक्र %s भावमा"),
    INDU_LAGNA_SIGN("Indu Lagna Sign", "इन्दु लग्न राशि"),
    INDU_LAGNA_STRENGTH("Indu Lagna Strength", "इन्दु लग्न बल"),
    INFLUENCE_FAVORABLE("Favorable", "अनुकूल"),
    INFLUENCE_NEEDS_ATTENTION("Needs Attention", "ध्यान दिनुपर्ने"),
    INFLUENCE_NEUTRAL("Neutral", "तटस्थ"),
    INFLUENCE_VERY_FAVORABLE("Very Favorable", "धेरै अनुकूल"),
    INFO_ACTIVATION("Activation: A Saham is considered active when transiting planets conjunct or aspect it, or during relevant Dasha periods.", "सक्रियता: गोचर ग्रहले युति वा दृष्टि गर्दा, वा सान्दर्भिक दशा अवधिमा सहम सक्रिय मानिन्छ।"),
    INFO_CLOSE("Close", "बन्द गर्नुहोस्"),
    INFO_DASHA("Dasha information", "दशा जानकारी"),
    INFO_DAY_NIGHT("Day/Night Charts: The formula for many Sahams reverses between day and night births. Day births have the Sun above the horizon, night births have it below.", "दिवा/रात्रि कुण्डली: धेरै सहमहरूको सूत्र दिवा र रात्रि जन्ममा उल्टो हुन्छ। दिवा जन्ममा सूर्य क्षितिज माथि हुन्छ, रात्रि जन्ममा तल हुन्छ।"),
    INFO_DESC("Ashtamangala Prashna is a powerful horary divination system from Kerala, using eight cowrie shells to determine outcomes. Each position represents a deity and direction, and the combination of open/closed shells reveals the answer to queries. This app integrates traditional shell readings with Prashna (horary) chart analysis for comprehensive guidance.", "अष्टमंगल प्रश्न केरलको एक शक्तिशाली प्रश्न विज्ञान प्रणाली हो, जसले परिणाम निर्धारण गर्न आठ कौडीहरू प्रयोग गर्छ। प्रत्येक स्थितिले एक देवता र दिशा प्रतिनिधित्व गर्छ, र खुला/बन्द कौडीहरूको संयोजनले प्रश्नको उत्तर प्रकट गर्छ। यो एपले व्यापक मार्गदर्शनको लागि प्रश्न कुण्डली विश्लेषणसँग परम्परागत कौडी पठन एकीकृत गर्छ।"),
    INFO_DESCRIPTION("Sahams (Arabic Parts) are sensitive points calculated from the positions of planets, Ascendant, and house cusps. They reveal specific life themes and their activation periods.", "सहमहरू (अरबी भाग) ग्रहको स्थिति, लग्न र भाव सन्धिबाट गणना गरिएको संवेदनशील बिन्दुहरू हुन्। तिनीहरूले विशिष्ट जीवन विषयहरू र तिनीहरूको सक्रियता अवधिहरू प्रकट गर्छन्।"),
    INFO_FORMULA("Formula: Most Sahams follow the pattern: Asc + Planet A - Planet B. For night charts, planets A and B may swap positions.", "सूत्र: धेरैजसो सहमहरू यो ढाँचा पछ्याउँछन्: लग्न + ग्रह A - ग्रह B। रात्रि कुण्डलीमा, ग्रह A र B को स्थान बदलिन सक्छ।"),
    INFO_TITLE("About Sahams", "सहमहरूको बारेमा"),
    INFO_VEDIC_REF("References: Prashna Marga, Kerala Jyotisha traditions", "सन्दर्भ: प्रश्न मार्ग, केरल ज्योतिष परम्पराहरू"),
    INNATE_PROWESS("Innate Physical Prowess", "जन्मजात शारीरिक शक्ति"),
    INNER_NEEDS_TITLE("Inner Needs", "आन्तरिक आवश्यकताहरू"),
    INPUT_ALTITUDE("Altitude (m) - Optional", "उचाई (मि.) - वैकल्पिक"),
    INPUT_COORDINATES("Coordinates", "निर्देशांकहरू"),
    INPUT_DATE_TIME("Date & Time", "मिति र समय"),
    INPUT_EDIT_CHART("Edit Birth Chart", "जन्म कुण्डली सम्पादन"),
    INPUT_FULL_NAME("Full name", "पूरा नाम"),
    INPUT_GENDER("Gender", "लिङ्ग"),
    INPUT_IDENTITY("Identity", "पहिचान"),
    INPUT_LATITUDE("Latitude", "अक्षांश"),
    INPUT_LOCATION("Location", "स्थान"),
    INPUT_LONGITUDE("Longitude", "देशान्तर"),
    INPUT_NEW_CHART("New Birth Chart", "नयाँ जन्म कुण्डली"),
    INPUT_SEARCH_LOCATION("Search city or enter manually", "शहर खोज्नुहोस् वा म्यानुअल रूपमा प्रविष्ट गर्नुहोस्"),
    INPUT_SELECT_DATE("Select date", "मिति छान्नुहोस्"),
    INPUT_SELECT_TIME("Select time", "समय छान्नुहोस्"),
    INPUT_TIMEZONE("Timezone", "समय क्षेत्र"),
    INSIGHTS_CAUTIONS("Cautions", "सावधानीहरू"),
    INSIGHTS_KEY_DATES("Key Dates", "महत्त्वपूर्ण मितिहरू"),
    INSIGHTS_LIFE_AREAS("Life Areas", "जीवन क्षेत्रहरू"),
    INSIGHTS_LUCKY_ELEMENTS("Lucky Elements", "भाग्यशाली तत्वहरू"),
    INSIGHTS_OVERALL_ENERGY("Overall Energy", "समग्र ऊर्जा"),
    INSIGHTS_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    INSIGHTS_TODAYS_AFFIRMATION("Today's Affirmation", "आजको प्रतिज्ञा"),
    INSIGHTS_WEEKLY_ADVICE("Weekly Advice", "साप्ताहिक सल्लाह"),
    INSIGHTS_WEEKLY_ENERGY("Weekly Energy Flow", "साप्ताहिक ऊर्जा प्रवाह"),
    INSIGHTS_WEEKLY_OVERVIEW("Weekly Overview by Area", "क्षेत्रअनुसार साप्ताहिक अवलोकन"),
    INSIGHT_ITEM("{0}: {1} (Strength: {2}%)", "{0}: {1} (बल: {2}%)"),
    INTELLECTUAL_ABILITY("Intellectual Ability", "बौद्धिक क्षमता"),
    INTELLECT_CHALLENGES("Intellectual Challenges", "बौद्धिक चुनौतीहरू"),
    INTELLECT_STRENGTHS("Intellectual Strengths", "बौद्धिक शक्तिहरू"),
    INTELLECT_TITLE("Intellectual Profile", "बौद्धिक प्रोफाइल"),
    INTERPRETATION_CHALLENGES("Challenges", "चुनौतीहरू"),
    INTERPRETATION_FAVORABLE("Favorable Areas", "अनुकूल क्षेत्रहरू"),
    INTERPRETATION_GENERAL("General Effects", "सामान्य प्रभावहरू"),
    INTERPRETATION_LORD_EFFECTS("Lord Effects", "स्वामी प्रभावहरू"),
    INTERPRETATION_RECOMMENDATIONS("Recommendations", "सिफारिसहरू"),
    INTERPRETATION_TITLE("Interpretation", "व्याख्या"),
    INTERPRET_BLESSINGS("Key blessings: {0}", "मुख्य आशीर्वाद: {0}"),
    INTERPRET_EXCEPTIONALLY_RARE("exceptionally rare and powerful", "असाधारण रूपमा दुर्लभ र शक्तिशाली"),
    INTERPRET_FORMATION("{0} is formed with {1} {2} in the {3}.", "{3} मा {1} {2} हुँदा {0} बन्छ।"),
    INTERPRET_MODERATE("This yoga has moderate strength and will manifest clearly during favorable periods.", "यो योगको मध्यम बल छ र अनुकूल अवधिमा स्पष्ट रूपमा प्रकट हुनेछ।"),
    INTERPRET_POWERFUL("This is an exceptionally powerful yoga that will significantly influence your life.", "यो एक असाधारण शक्तिशाली योग हो जसले तपाईंको जीवनमा महत्त्वपूर्ण प्रभाव पार्नेछ।"),
    INTERPRET_SIGNIFICANT_BLESSING("a significant blessing", "एक महत्त्वपूर्ण आशीर्वाद"),
    INTERPRET_STRENGTH("With a strength of {0}%, {1}", "{0}% को बलको साथ, {1}"),
    INTERPRET_STRONG("This is a strong yoga with notable effects throughout life.", "यो एक बलियो योग हो जसको जीवनभर उल्लेखनीय प्रभाव रहनेछ।"),
    INTERPRET_VIP_FORMED("{0} ({1}) is FORMED. {2}, lord of the {3}th house, is placed in the {4}th house/sign in {5}. Yoga strength: {6}.", "{0} ({1}) बनेको छ। {3}औं भावको स्वामी {2} {4}औं भाव/राशि {5} मा स्थित छ। योग बल: {6}।"),
    INTERPRET_VIP_NOT_FORMED("{0} is NOT formed. The {1}th lord {2} is in {3}th sign, not in a dusthana house (6th, 8th, or 12th).", "{0} बनेको छैन। {1}औं भावको स्वामी {2} {3}औं राशिमा छ, दुस्थान भाव (६औं, ८औं वा १२औं) मा छैन।"),
    INTERPRET_WEAK("This yoga exists but may need activation through conscious effort or favorable transits.", "यो योग अवस्थित छ तर सचेत प्रयास वा अनुकूल गोचर मार्फत सक्रियताको आवश्यकता पर्न सक्छ।"),
    INTERP_ACTIVE_MODERATE("The yoga is ACTIVE with moderate intensity. Feelings of isolation, financial instability, and emotional sensitivity are likely. Regular Moon remedies are recommended. ", "यो योग मध्यम तीव्रताका साथ सक्रिय छ। एक्लोपनको भावना, आर्थिक अस्थिरता र भावनात्मक संवेदनशीलताको सम्भावना छ। नियमित चन्द्रमाका उपायहरू सिफारिस गरिन्छ। "),
    INTERP_ACTIVE_SEVERE("The yoga is SEVERELY ACTIVE with minimal cancellation. Significant challenges in emotional wellbeing, finances, and social support may occur. Strong remedial measures are essential. ", "यो योग न्यूनतम रद्दको साथ गम्भीर रूपमा सक्रिय छ। भावनात्मक कल्याण, वित्त र सामाजिक सहयोगमा महत्त्वपूर्ण चुनौतीहरू आउन सक्छन्। कडा उपचारात्मक उपायहरू आवश्यक छन्। "),
    INTERP_ANALYSIS_HEADER("ANALYSIS", "विश्लेषण"),
    INTERP_CANCELLATION_SUMMARY("\n\nCancellation factors present: {0}", "\n\nउपस्थित रद्द गर्ने कारकहरू: {0}"),
    INTERP_FULLY_CANCELLED("However, the yoga is FULLY CANCELLED due to strong cancellation factors. The negative effects are largely neutralized. ", "यद्यपि, बलियो रद्द गर्ने कारकहरूको कारण योग पूर्ण रूपमा रद्द गरिएको छ। नकारात्मक प्रभावहरू धेरै हदसम्म निष्क्रिय छन्। "),
    INTERP_INDICATORS_FOUND("INDICATORS FOUND:", "पाइएका संकेतकहरू:"),
    INTERP_INTERPRETATION("INTERPRETATION:", "व्याख्या:"),
    INTERP_KEMA_FORMED("Kemadruma Yoga IS formed in this chart as the Moon lacks planetary support in adjacent houses. ", "यस कुण्डलीमा केमद्रुम योग बनेको छ किनकि चन्द्रमालाई वरपरका भावहरूमा ग्रह सहयोगको अभाव छ। "),
    INTERP_KEMA_NOT_PRESENT("Kemadruma Yoga is NOT present in this chart. The Moon has adequate planetary support, indicating good emotional stability and ability to receive help from others. Mental peace and financial support from family/friends is generally available.", "यस कुण्डलीमा केमद्रुम योग छैन। चन्द्रमालाई पर्याप्त ग्रह सहयोग छ, जसले राम्रो भावनात्मक स्थिरता र अरूबाट सहयोग प्राप्त गर्ने क्षमता संकेत गर्दछ। मानसिक शान्ति र परिवार/साथीहरूबाट आर्थिक सहयोग सामान्यतया उपलब्ध हुन्छ।"),
    INTERP_LEVEL("Level:", "स्तर:"),
    INTERP_MOON_DEBILITATED("Moon''s debilitation intensifies emotional sensitivity. Extra care needed. ", "चन्द्रमाको नीचताले भावनात्मक संवेदनशीलता बढाउँछ। अतिरिक्त हेरचाह आवश्यक छ। "),
    INTERP_MOON_EXALTED("Moon''s exaltation provides inherent strength to handle challenges. ", "चन्द्रमाको उच्चताले चुनौतीहरू सामना गर्न अन्तर्निहित शक्ति प्रदान गर्दछ। "),
    INTERP_MOON_PLACEMENT("\n\nMoon is placed in {0} ({1}th house) in {2}. ", "\n\nचन्द्रमा {0} ({1}औं भाव) मा {2} नक्षत्रमा स्थित छ। "),
    INTERP_MOSTLY_CANCELLED("The yoga is MOSTLY cancelled with {0} cancellation factors. Negative effects are significantly reduced but some sensitivity remains. ", "यो योग {0} रद्द गर्ने कारकहरूको साथ प्रायः रद्द गरिएको छ। नकारात्मक प्रभावहरू उल्लेखनीय रूपमा कम भएका छन् तर केही संवेदनशीलता अझै बाँकी छ। "),
    INTERP_PAKSHA_BRIGHT("The {0} paksha {1} Moon indicates {2} emotional resilience. ", "{0} पक्षको {1} चन्द्रमाले {2} भावनात्मक लचिलोपन संकेत गर्दछ। "),
    INTERP_PARTIALLY_CANCELLED("The yoga is PARTIALLY cancelled. Some negative effects may manifest during challenging planetary periods. ", "यो योग आंशिक रूपमा रद्द गरिएको छ। केही नकारात्मक प्रभावहरू चुनौतीपूर्ण ग्रह अवधिहरूमा प्रकट हुन सक्छन्। "),
    INTERP_SEVERITY("SEVERITY:", "गम्भीरता:"),
    INTERP_WEAKLY_CANCELLED("The yoga has WEAK cancellation. Emotional and financial challenges may arise, especially during Moon periods. ", "यस योगमा कमजोर रद्द छ। भावनात्मक र आर्थिक चुनौतीहरू आउन सक्छन्, विशेष गरी चन्द्रमाको अवधिमा। "),
    INTIMACY_APPROACH("Intimacy Approach", "घनिष्टता दृष्टिकोण"),
    INVESTMENT_STYLE("Investment Style", "लगानी शैली"),
    INVESTMENT_TITLE("Investment Profile", "लगानी प्रोफाइल"),
    ISHTA_DEVATA("Ishta Devata", "इष्ट देवता"),
    JUPITER_FAVORABLE_AREAS("Jupiter Favorable Areas", "बृहस्पति अनुकूल क्षेत्रहरू"),
    JUPITER_HEALTH("Jupiter Health Influence", "बृहस्पति स्वास्थ्य प्रभाव"),
    JUPITER_HOUSE("Jupiter House", "बृहस्पति भाव"),
    JUPITER_HOUSE_EDU("Jupiter House", "बृहस्पति भाव"),
    JUPITER_SIGN("Jupiter Sign", "बृहस्पति राशि"),
    JUPITER_SIGN_EDU("Jupiter Sign", "बृहस्पति राशि"),
    JUPITER_SPIRITUAL_HOUSE("Jupiter House", "बृहस्पति भाव"),
    JUPITER_SPIRITUAL_SIGN("Jupiter Sign", "बृहस्पति राशि"),
    JUPITER_TRANSIT("Jupiter Transit", "बृहस्पति गोचर"),
    JUPITER_TRANSIT_HOUSE("Jupiter Transit House", "बृहस्पति गोचर भाव"),
    KALA_ANALYZING("Analyzing Kala Bala...", "कालबल विश्लेषण गर्दै..."),
    KALA_AYANA("Ayana Bala", "अयन बल"),
    KALA_AYANA_DESC("Solstice/Declination strength", "अयन/क्रान्ति बल"),
    KALA_DAY_BIRTH("Day Birth", "दिन जन्म"),
    KALA_DESC("Shadbala component measuring strength from time factors", "समय कारकहरूबाट बल मापन गर्ने षड्बल घटक"),
    KALA_DINA("Dina Bala", "दिन बल"),
    KALA_DINA_DESC("Day lord strength", "दिन स्वामी बल"),
    KALA_HORA("Hora Bala", "होरा बल"),
    KALA_HORA_DESC("Hour lord strength", "होरा स्वामी बल"),
    KALA_INFO_DESC("Kala Bala measures temporal strength through 9 components related to time of birth, lunar phase, day/night, seasons, and planetary wars. It reflects how time supports each planet's strength.", "कालबलले जन्म समय, चन्द्र चरण, दिन/रात, ऋतु, र ग्रह युद्धसँग सम्बन्धित ९ घटकहरू मार्फत समयगत बल मापन गर्छ। यसले प्रत्येक ग्रहको बललाई समयले कसरी समर्थन गर्छ भनी प्रतिबिम्बित गर्छ।"),
    KALA_INFO_TITLE("About Kala Bala", "कालबलको बारेमा"),
    KALA_KRISHNA_PAKSHA("Krishna Paksha", "कृष्ण पक्ष"),
    KALA_MASA("Masa Bala", "मास बल"),
    KALA_MASA_DESC("Month lord strength", "महिना स्वामी बल"),
    KALA_NATHONNATHA("Nathonnatha Bala", "नाथोन्नथ बल"),
    KALA_NATHONNATHA_DESC("Day/Night strength", "दिन/रात बल"),
    KALA_NIGHT_BIRTH("Night Birth", "रात जन्म"),
    KALA_PAKSHA("Paksha Bala", "पक्ष बल"),
    KALA_PAKSHA_DESC("Lunar fortnight strength", "चन्द्र पाक्षिक बल"),
    KALA_SHUKLA_PAKSHA("Shukla Paksha", "शुक्ल पक्ष"),
    KALA_SUBTITLE("Temporal Strength Analysis", "समयगत बल विश्लेषण"),
    KALA_TAB_COMPONENTS("Components", "घटकहरू"),
    KALA_TAB_OVERVIEW("Overview", "सिंहावलोकन"),
    KALA_TAB_PLANETS("Planets", "ग्रहहरू"),
    KALA_TITLE("Kala Bala", "कालबल"),
    KALA_TOTAL("Total Kala Bala", "कुल कालबल"),
    KALA_TRIBHAGA("Tribhaga Bala", "त्रिभाग बल"),
    KALA_TRIBHAGA_DESC("Day/Night third strength", "दिन/रात तृतीयांश बल"),
    KALA_UNABLE("Unable to calculate Kala Bala", "कालबल गणना गर्न सकिएन"),
    KALA_VARSHA("Varsha Bala", "वर्ष बल"),
    KALA_VARSHA_DESC("Year lord strength", "वर्ष स्वामी बल"),
    KALA_VEDIC_REF("Vedic Reference: BPHS Chapter 28, Surya Siddhanta", "वैदिक सन्दर्भ: बृहत् पाराशर होरा शास्त्र अध्याय २८, सूर्य सिद्धान्त"),
    KALA_YUDDHA("Yuddha Bala", "युद्ध बल"),
    KALA_YUDDHA_DESC("Planetary war strength", "ग्रह युद्ध बल"),
    KARAKAMSHA_DESC("Navamsa sign of Atmakaraka - Key for spiritual and material destiny", "आत्मकारकको नवांश राशि - आध्यात्मिक र भौतिक भाग्यको लागि महत्त्वपूर्ण"),
    KARAKAMSHA_TITLE("Karakamsha", "कारकांश"),
    KARAKA_ABOUT("About Chara Karakas", "चर कारकको बारेमा"),
    KARAKA_ABOUT_DESC("Chara Karakas are Jaimini's system of variable significators based on planetary degrees. Unlike fixed karakas, these change based on each chart.", "चर कारकहरू ग्रहको अंशमा आधारित जैमिनीको परिवर्तनशील कारक प्रणाली हो। स्थिर कारकहरूको विपरीत, यी प्रत्येक कुण्डली अनुसार परिवर्तन हुन्छन्।"),
    KARAKA_ACTIVATION("Karaka Activation", "कारक सक्रियता"),
    KARAKA_AK("Atmakaraka (AK)", "आत्मकारक (AK)"),
    KARAKA_AK_DESC("Soul significator - Highest degree planet, represents the self and spiritual evolution", "आत्मा कारक - उच्चतम अंश ग्रह, आत्म र आध्यात्मिक विकासको प्रतिनिधित्व"),
    KARAKA_AMK("Amatyakaraka (AmK)", "अमात्यकारक (AmK)"),
    KARAKA_AMK_DESC("Minister significator - Career, profession, and life purpose", "मन्त्री कारक - क्यारियर, पेशा, र जीवन उद्देश्य"),
    KARAKA_BK("Bhratrikaraka (BK)", "भ्रातृकारक (BK)"),
    KARAKA_BK_DESC("Sibling significator - Brothers, sisters, and courage", "भाइबहिनी कारक - भाइ, बहिनी, र साहस"),
    KARAKA_DK("Darakaraka (DK)", "दारकारक (DK)"),
    KARAKA_DK_DESC("Spouse significator - Marriage partner, business partners", "जीवनसाथी कारक - विवाह साथी, व्यापार साझेदार"),
    KARAKA_GK("Gnatikaraka (GK)", "ज्ञातिकारक (GK)"),
    KARAKA_GK_DESC("Relative significator - Relatives, obstacles, competition", "सम्बन्धी कारक - आफन्त, बाधा, प्रतिस्पर्धा"),
    KARAKA_MK("Matrikaraka (MK)", "मातृकारक (MK)"),
    KARAKA_MK_DESC("Mother significator - Mother, nurturing, emotional foundation", "आमा कारक - आमा, पालनपोषण, भावनात्मक आधार"),
    KARAKA_PIK("Pitrikaraka (PiK)", "पितृकारक (PiK)"),
    KARAKA_PIK_DESC("Father significator - Father, authority, guidance", "बुबा कारक - बुबा, अधिकार, मार्गदर्शन"),
    KARAKA_PUK("Putrakaraka (PuK)", "पुत्रकारक (PuK)"),
    KARAKA_PUK_DESC("Children significator - Children, creativity, intelligence", "सन्तान कारक - सन्तान, सृजनशीलता, बुद्धि"),
    KARAKA_SUBTITLE("Jaimini Variable Significators", "जैमिनी परिवर्तनशील कारकहरू"),
    KARAKA_TITLE("Chara Karakas", "चर कारकहरू"),
    KARMIC_LESSON("Karmic Lesson", "कार्मिक पाठ"),
    KARMIC_TITLE("Karmic Patterns", "कार्मिक ढाँचाहरू"),
    KEMADRUMA_ACTIVATION("Activation Periods", "सक्रियता अवधिहरू")
}
